/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.ModuleSymmetry.RankTwo
import LieLean.Algebra.QuantumGroup.Faithful
import LieLean.Algebra.QuantumGroup.RootDatumHom
import LieLean.Algebra.QuantumGroup.PBW.RootVectorsQuantum

/-!
# The braid relations for Lusztig's `Tᵢ` in arbitrary rank

Let `v` be nonzero and not a root of unity, and let `Tᵢ` be Lusztig's automorphisms
(`QuantumGroup.braidEquivOfNotRoot`) of `U = U_q(𝔤)` for an arbitrary Cartan datum and root datum.
We prove the braid relations `Tᵢ Tⱼ Tᵢ ⋯ = Tⱼ Tᵢ Tⱼ ⋯` (`mᵢⱼ` factors) for every pair of nodes
with `aᵢⱼ aⱼᵢ ≤ 3`, with no condition on the other nodes
(`QuantumGroup.isBraidLiftable_braidEquivOfNotRoot`), hence the action of the Artin group of the
Coxeter matrix of any Cartan datum (`QuantumGroup.braidArtinHomOfNotRoot`); [Lus] 39.4.3.

The relations on `Eᵢ, Eⱼ, Fᵢ, Fⱼ, K_μ` are the rank-two computations of `BraidAction/`. For a
third node `l` the argument is module-theoretic (our own; Lusztig uses quantum Verma identities):
* both sides `X(E_l)`, `Y(E_l)` lie in `U⁺` (`alternatingWord_apply_mem_adjoin`, from the rank-two
  root vector property);
* on every integrable module `M` the module symmetries satisfy the braid relation
  (`QuantumGroup/ModuleSymmetry/RankTwo.lean`) and are compatible with the `Tᵢ` of `U`
  (`nodeSl2_T_smul`), so `X(E_l) - Y(E_l)` acts as zero on `M`;
* if the simple coroots can be paired with arbitrarily large integers, `U⁺` acts faithfully on
  the integrable modules `ʷL̃_q(Λ)` (`plusHom_eq_zero_of_forall_smul_eq_zero`); in general we pass
  to the root datum `freeCoroot R` and map back along `freeCorootHom`.
The relation on `F_l` follows from the one on `E_l` by `ω Tᵢ ω D_ζ = D_ζ Tᵢ`
(`chevalley_comp_comp_diagHom`).

## References

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, 39.4.3.
-/

open LieLean Finset CoxeterSystem

noncomputable section

namespace LieLean.QuantumGroup

variable {k I Y : Type*} [Field k] [AddCommGroup Y] [DecidableEq I] {D : LusztigCartanDatum I}
  {R : D.RootDatum Y} {v : k}

/-! ### Words in the `Tᵢ` -/

section Words

variable {Y' : Type*} [AddCommGroup Y'] {R' : D.RootDatum Y'}

lemma mapHom_wordProd (φ : R.Hom R') (T : I → QuantumGroup R v ≃ₐ[k] QuantumGroup R v)
    (T' : I → QuantumGroup R' v ≃ₐ[k] QuantumGroup R' v)
    (H : ∀ l, HasBraidGeneratorImages l (T l).toAlgHom)
    (H' : ∀ l, HasBraidGeneratorImages l (T' l).toAlgHom) (w : List I) (u : QuantumGroup R v) :
    mapHom v φ ((w.map T).prod u) = (w.map T').prod (mapHom v φ u) := by
  induction w with
  | nil => simp
  | cons a w ih =>
    simp only [List.map_cons, List.prod_cons, AlgEquiv.mul_apply]
    rw [← ih]
    exact DFunLike.congr_fun (mapHom_comp_of_hasBraidGeneratorImages φ (H a) (H' a)) _

omit [DecidableEq I] in
/-- Along alternating words in two nodes, a third generator stays in the subalgebra generated by
all `Eᵢ`, given the rank-two root vector property for the two nodes. -/
theorem alternatingWord_apply_mem_adjoin {A : Type*} [Ring A] [Algebra k A]
    (T : I → A ≃ₐ[k] A) (E : I → A) {i j l : I} {m : ℕ}
    (hpre : ∀ n < m, ((alternatingWord i j n).map T).prod (E i) ∈ Algebra.adjoin k {E i, E j} ∧
      ((alternatingWord j i n).map T).prod (E j) ∈ Algebra.adjoin k {E i, E j})
    (hli : T i (E l) ∈ Algebra.adjoin k {E i, E l})
    (hlj : T j (E l) ∈ Algebra.adjoin k {E j, E l}) (n : ℕ) (hn : n ≤ m) :
    ((alternatingWord i j n).map T).prod (E l) ∈ Algebra.adjoin k (Set.range E) ∧
      ((alternatingWord j i n).map T).prod (E l) ∈ Algebra.adjoin k (Set.range E) := by
  have hpair : ∀ a b : I, Algebra.adjoin k {E a, E b} ≤ Algebra.adjoin k (Set.range E) :=
    fun a b ↦ Algebra.adjoin_mono (by rintro _ (rfl | rfl) <;> exact ⟨_, rfl⟩)
  induction n with
  | zero =>
    simp only [alternatingWord, List.map_nil, List.prod_nil, AlgEquiv.one_apply, and_self]
    exact Algebra.subset_adjoin ⟨l, rfl⟩
  | succ n ih =>
    obtain ⟨h1, h2⟩ := ih (by omega)
    obtain ⟨p1, p2⟩ := hpre n (by omega)
    simp only [alternatingWord_succ, List.concat_eq_append, List.map_append, List.prod_append,
      List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one, AlgEquiv.mul_apply]
    constructor
    · refine (Algebra.adjoin_le (S := (Algebra.adjoin k (Set.range E)).comap
        ((alternatingWord j i n).map T).prod.toAlgHom) ?_) hlj
      rintro _ (rfl | rfl)
      · exact hpair i j p2
      · exact h2
    · refine (Algebra.adjoin_le (S := (Algebra.adjoin k (Set.range E)).comap
        ((alternatingWord i j n).map T).prod.toAlgHom) ?_) hli
      rintro _ (rfl | rfl)
      · exact hpair i j p1
      · exact h1

end Words

/-! ### The rank-two root vector property for one pair -/

section PairRoot

variable [NeZero v] (hq : ∀ i, v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) (hS : ∀ i, BraidSerreGeneric D v i)
include hq hS

/-- The membership part of `rankTwoRootProperty_braidEquivOfGeneric` for a single pair with
`aᵢₗ aₗᵢ ≤ 3`. -/
theorem pairRoot_mem {i l : I} (hil : i ≠ l)
    (hpair : D.cartanMatrix i l * D.cartanMatrix l i ≤ 3) (n : ℕ)
    (hn : D.cartanMatrix.coxeterMatrix i l = 0 ∨ n < D.cartanMatrix.coxeterMatrix i l) :
    ((alternatingWord i l n).map fun i ↦ braidEquivOfGeneric (R := R) (hq i) (hS i)).prod
      (E R v i) ∈ Algebra.adjoin k {E R v i, E R v l} := by
  have HT := braidEquivOfGeneric_images (R := R) hq hS
  have h2 : ∀ {i l : I}, l ≠ i → D.cartanMatrix i l = -2 → qFactorial (v ^ D.d i) 2 ≠ 0 :=
    fun hli h ↦ by simpa [b2_negA h] using qFactorial_negA_ne hq hS hli
  have h3' : ∀ {i l : I}, l ≠ i → D.cartanMatrix i l = -3 → qFactorial (v ^ D.d i) 3 ≠ 0 :=
    fun hli h ↦ by simpa [tripleSix_negA h] using qFactorial_negA_ne hq hS hli
  rw [Matrix.coxeterMatrix_apply_of_ne _ hil] at hn
  have hl := E_mem_pair_left (k := k) (R := R) (v := v) (i := i) (j := l)
  have hr := E_mem_pair_right (k := k) (R := R) (v := v) (i := i) (j := l)
  rcases cartan_pair_cases hil hpair with ⟨h1, h1'⟩ | ⟨h1, h1'⟩ | ⟨h1, h1'⟩ |
    ⟨h1, h1'⟩ | ⟨h1, h1'⟩ | ⟨h1, h1'⟩ <;>
    simp only [h1, h1'] at hn <;> norm_num [Matrix.coxeterEntry] at hn <;>
    interval_cases n <;>
    simp only [alternatingWord, List.concat_eq_append, List.nil_append, List.cons_append,
      List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one,
      AlgEquiv.mul_apply, AlgEquiv.one_apply]
  all_goals first
    | exact hl
    | skip
  -- `A₁ × A₁`
  · rw [show (braidEquivOfGeneric (R := R) (hq l) (hS l)) (E R v i) = E R v i from
      a1a1_rootVector_two hil.symm h1' (HT l)]
    exact hl
  -- `A₂`
  · exact (a2_words (HT i) (HT l) hil h1 h1' (hq i)).1
  · rw [show (braidEquivOfGeneric (R := R) (hq i) (hS i))
        ((braidEquivOfGeneric (R := R) (hq l) (hS l)) (E R v i)) = E R v l from
      (a2_words (HT i) (HT l) hil h1 h1' (hq i)).2]
    exact hr
  -- `B₂`, `i` short
  · exact (b2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h2 hil.symm h1)).1
  · exact (b2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h2 hil.symm h1)).2.1
  · convert hl using 1
    exact (b2_words_short (HT i) (HT l) hil h1 h1' (hq i)
      (h2 hil.symm h1)).2.2
  -- `B₂`, `i` long
  · rw [Set.pair_comm]
    exact (b2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h2 hil h1')).1
  · rw [Set.pair_comm]
    exact (b2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h2 hil h1')).2.1
  · convert hl using 1
    exact (b2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l)
      (h2 hil h1')).2.2
  -- `G₂`, `i` short
  · exact (g2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h3' hil.symm h1)).1
  · exact (g2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h3' hil.symm h1)).2.1
  · exact (g2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h3' hil.symm h1)).2.2.1
  · exact (g2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h3' hil.symm h1)).2.2.2.1
  · convert hl using 1
    exact (g2_words_short (HT i) (HT l) hil h1 h1' (hq i)
      (h3' hil.symm h1)).2.2.2.2
  -- `G₂`, `i` long
  · rw [Set.pair_comm]
    exact (g2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h3' hil h1')).1
  · rw [Set.pair_comm]
    exact (g2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h3' hil h1')).2.1
  · rw [Set.pair_comm]
    exact (g2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h3' hil h1')).2.2.1
  · rw [Set.pair_comm]
    exact (g2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h3' hil h1')).2.2.2.1
  · convert hl using 1
    exact (g2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l)
      (h3' hil h1')).2.2.2.2

end PairRoot

/-! ### Words of module symmetries -/

section ModuleWords

variable [NeZero v] (hv : ∀ n : ℕ, 0 < n → v ^ n ≠ 1)
  {M : Type*} [AddCommGroup M] [Module k M] [Module (QuantumGroup R v) M]
  [IsScalarTower k (QuantumGroup R v) M] (hM : IsIntegrable R v M)

lemma nodeT_surjective (l : I) : Function.Surjective (nodeT R v M hv hM l) := fun m ↦
  ⟨(nodeSl2 R v M hv hM l).flip.T (v ^ D.d l)⁻¹ m,
    IntegrableSl2.T_flip_T_inv (pow_ne_zero _ (NeZero.ne v)) (pow_d_ne_one hv l)
      (pow_ne_zero _ (NeZero.ne v)) (fun _ _ ↦ rfl) m⟩

lemma wordT_surjective (w : List I) :
    Function.Surjective ((w.map (nodeT R v M hv hM)).prod) := by
  induction w with
  | nil => exact Function.surjective_id
  | cons a w ih =>
    rw [List.map_cons, List.prod_cons, Module.End.coe_mul]
    exact (nodeT_surjective hv hM a).comp ih

lemma wordT_smul (T : I → QuantumGroup R v ≃ₐ[k] QuantumGroup R v)
    (H : ∀ l, HasBraidGeneratorImages l (T l).toAlgHom) (w : List I) (u : QuantumGroup R v)
    (m : M) : (w.map (nodeT R v M hv hM)).prod (u • m) =
      (w.map T).prod u • (w.map (nodeT R v M hv hM)).prod m := by
  induction w with
  | nil => simp
  | cons a w ih =>
    simp only [List.map_cons, List.prod_cons, Module.End.mul_apply, AlgEquiv.mul_apply]
    rw [ih]
    exact nodeSl2_T_smul hv hM (H a) _ _

omit hM in
lemma braidEquivOfNotRoot_hasImages (R : D.RootDatum Y) (l : I) :
    HasBraidGeneratorImages l (braidEquivOfNotRoot R hv l).toAlgHom :=
  braidEquivOfGeneric_images (R := R)
    (fun l ↦ (shortNode_braidGeneric_of_not_root (D := D) hv l).sub_ne)
    (braidSerreGeneric_of_not_root hv) l

/-- The braid relation for the module symmetries, in the form of alternating words. -/
theorem wordT_braid {i j : I} (hij : i ≠ j)
    (hfin : D.cartanMatrix i j * D.cartanMatrix j i ≤ 3) :
    ((alternatingWord i j (D.cartanMatrix.coxeterMatrix i j)).map (nodeT R v M hv hM)).prod =
      ((alternatingWord j i (D.cartanMatrix.coxeterMatrix i j)).map
        (nodeT R v M hv hM)).prod := by
  have HT := braidEquivOfNotRoot_hasImages hv R
  rw [Matrix.coxeterMatrix_apply_of_ne _ hij]
  rcases cartan_pair_cases hij hfin with ⟨h1, h1'⟩ | ⟨h1, h1'⟩ | ⟨h1, h1'⟩ |
    ⟨h1, h1'⟩ | ⟨h1, h1'⟩ | ⟨h1, h1'⟩ <;>
    simp only [h1, h1'] <;> norm_num [Matrix.coxeterEntry] <;>
    simp only [alternatingWord, List.concat_eq_append, List.nil_append, List.cons_append,
      List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one] <;>
    ext m <;> simp only [Module.End.mul_apply]
  · exact nodeSl2_T_comm hv hM (HT j) hij h1 m
  · exact (nodeSl2_T_braid_three hv hM (HT i) (HT j) hij h1 h1' m).symm
  · exact nodeSl2_T_braid_four hv hM (HT i) (HT j) hij h1 h1' m
  · exact (nodeSl2_T_braid_four hv hM (HT j) (HT i) hij.symm h1' h1 m).symm
  · exact nodeSl2_T_braid_six hv hM (HT i) (HT j) hij h1 h1' m
  · exact (nodeSl2_T_braid_six hv hM (HT j) (HT i) hij.symm h1' h1 m).symm

end ModuleWords

/-! ### Third nodes -/

section Outer

variable [NeZero v] (hv : ∀ n : ℕ, 0 < n → v ^ n ≠ 1)

omit [NeZero v] in
lemma exists_plusHom_eq {z : QuantumGroup R v} (hz : z ∈ Algebra.adjoin k (Set.range (E R v))) :
    ∃ x, plusHom R v x = z := by
  have : Algebra.adjoin k (Set.range (E R v)) ≤ (plusHom R v).range :=
    Algebra.adjoin_le (by rintro _ ⟨i, rfl⟩; exact ⟨LusztigF.θ k i, plusHom_θ R v i⟩)
  exact this hz

lemma coxeterMatrix_comm (i j : I) :
    D.cartanMatrix.coxeterMatrix j i = D.cartanMatrix.coxeterMatrix i j :=
  D.cartanMatrix.coxeterMatrix.symmetric j i

/-- **The braid relation on a third generator `E_l`.** -/
theorem wordProd_E_outer (R : D.RootDatum Y) {i j l : I} (hij : i ≠ j)
    (hfin : D.cartanMatrix i j * D.cartanMatrix j i ≤ 3) (hli : l ≠ i) (hlj : l ≠ j) :
    ((alternatingWord i j (D.cartanMatrix.coxeterMatrix i j)).map
      (braidEquivOfNotRoot R hv)).prod (E R v l) =
    ((alternatingWord j i (D.cartanMatrix.coxeterMatrix i j)).map
      (braidEquivOfNotRoot R hv)).prod (E R v l) := by
  set m := D.cartanMatrix.coxeterMatrix i j with hm
  set R' := R.freeCoroot
  have HT' := braidEquivOfNotRoot_hasImages hv R'
  have key : ((alternatingWord i j m).map (braidEquivOfNotRoot R' hv)).prod (E R' v l) =
      ((alternatingWord j i m).map (braidEquivOfNotRoot R' hv)).prod (E R' v l) := by
    have hq := fun l ↦ (shortNode_braidGeneric_of_not_root (D := D) hv l).sub_ne
    have hS := braidSerreGeneric_of_not_root (D := D) hv
    have hfin' : D.cartanMatrix j i * D.cartanMatrix i j ≤ 3 := by rwa [mul_comm]
    have hpre : ∀ n < m, ((alternatingWord i j n).map (braidEquivOfNotRoot R' hv)).prod
          (E R' v i) ∈ Algebra.adjoin k {E R' v i, E R' v j} ∧
        ((alternatingWord j i n).map (braidEquivOfNotRoot R' hv)).prod (E R' v j) ∈
          Algebra.adjoin k {E R' v i, E R' v j} := fun n hn ↦ by
      refine ⟨pairRoot_mem (R := R') hq hS hij hfin n (Or.inr hn), ?_⟩
      have := pairRoot_mem (R := R') hq hS hij.symm hfin' n
        (Or.inr (by rwa [coxeterMatrix_comm]))
      rwa [Set.pair_comm] at this
    have hmem := alternatingWord_apply_mem_adjoin (braidEquivOfNotRoot R' hv) (E R' v) hpre
      (by rw [Set.pair_comm]; exact map_E_mem_pair (HT' i) hli)
      (by rw [Set.pair_comm]; exact map_E_mem_pair (HT' j) hlj) m le_rfl
    obtain ⟨x, hx⟩ := exists_plusHom_eq (sub_mem hmem.1 hmem.2)
    have h0 : plusHom R' v x = 0 := by
      refine plusHom_eq_zero_of_forall_smul_eq_zero hv R.exists_le_freeCoroot x fun Λ m0 ↦ ?_
      have hM := ChevalleyTwist.isIntegrable (FPowQuotient.isIntegrable (R := R') (v := v) Λ)
      obtain ⟨m', rfl⟩ := wordT_surjective hv hM (alternatingWord i j m) m0
      rw [hx, sub_smul, ← wordT_smul hv hM _ HT' (alternatingWord i j m) (E R' v l) m',
        wordT_braid hv hM hij hfin,
        ← wordT_smul hv hM _ HT' (alternatingWord j i m) (E R' v l) m', sub_self]
    rw [h0, eq_comm, sub_eq_zero] at hx
    exact hx
  have e1 := mapHom_wordProd R.freeCorootHom (braidEquivOfNotRoot R' hv)
    (braidEquivOfNotRoot R hv) HT' (braidEquivOfNotRoot_hasImages hv R) (alternatingWord i j m)
    (E R' v l)
  have e2 := mapHom_wordProd R.freeCorootHom (braidEquivOfNotRoot R' hv)
    (braidEquivOfNotRoot R hv) HT' (braidEquivOfNotRoot_hasImages hv R) (alternatingWord j i m)
    (E R' v l)
  rw [mapHom_E] at e1 e2
  rw [← e1, ← e2, key]

/-- `ω T_w ω D_ζ = D_ζ T_w` for every word `w`. -/
lemma chevalley_wordProd_diagHom (R : D.RootDatum Y) (w : List I) (u : QuantumGroup R v) :
    chevalley R v ((w.map (braidEquivOfNotRoot R hv)).prod
      (chevalley R v (diagHom R v (chevalleyScalar D v) u))) =
      diagHom R v (chevalleyScalar D v) ((w.map (braidEquivOfNotRoot R hv)).prod u) := by
  induction w generalizing u with
  | nil => exact DFunLike.congr_fun (chevalley_comp_chevalley R v) _
  | cons a w ih =>
    simp only [List.map_cons, List.prod_cons, AlgEquiv.mul_apply]
    have hw : (w.map (braidEquivOfNotRoot R hv)).prod
        (chevalley R v (diagHom R v (chevalleyScalar D v) u)) =
        chevalley R v (diagHom R v (chevalleyScalar D v)
          ((w.map (braidEquivOfNotRoot R hv)).prod u)) := by
      rw [← ih u]
      exact (DFunLike.congr_fun (chevalley_comp_chevalley R v) _).symm
    rw [hw]
    exact DFunLike.congr_fun
      (chevalley_comp_comp_diagHom (braidEquivOfNotRoot_hasImages hv R a)) _

/-- **The braid relation on a third generator `F_l`.** -/
theorem wordProd_F_outer (R : D.RootDatum Y) {i j l : I} (hij : i ≠ j)
    (hfin : D.cartanMatrix i j * D.cartanMatrix j i ≤ 3) (hli : l ≠ i) (hlj : l ≠ j) :
    ((alternatingWord i j (D.cartanMatrix.coxeterMatrix i j)).map
      (braidEquivOfNotRoot R hv)).prod (F R v l) =
    ((alternatingWord j i (D.cartanMatrix.coxeterMatrix i j)).map
      (braidEquivOfNotRoot R hv)).prod (F R v l) := by
  have key : ∀ w : List I, (chevalleyScalar D v l : k) •
      chevalley R v ((w.map (braidEquivOfNotRoot R hv)).prod (F R v l)) =
      diagHom R v (chevalleyScalar D v) ((w.map (braidEquivOfNotRoot R hv)).prod (E R v l)) := by
    intro w
    rw [← chevalley_wordProd_diagHom hv R w (E R v l), diagHom_E, map_smul, chevalley_E,
      map_smul, map_smul]
  have h := congrArg (diagHom R v (chevalleyScalar D v))
    (wordProd_E_outer hv R hij hfin hli hlj)
  rw [← key, ← key] at h
  have h' := smul_right_injective _ (Units.ne_zero (chevalleyScalar D v l)) h
  have := congrArg (chevalley R v) h'
  simpa only [← AlgHom.comp_apply, chevalley_comp_chevalley, AlgHom.id_apply] using this

end Outer

/-! ### The braid relations -/

section Assembly

variable [NeZero v] (hv : ∀ n : ℕ, 0 < n → v ^ n ≠ 1)

omit [NeZero v] in
lemma algEquiv_eq_of_generators {X Y : QuantumGroup R v ≃ₐ[k] QuantumGroup R v}
    (hE : ∀ l, X (E R v l) = Y (E R v l)) (hF : ∀ l, X (F R v l) = Y (F R v l))
    (hK : ∀ μ, X (K R v μ) = Y (K R v μ)) : X = Y :=
  AlgEquiv.coe_toAlgHom_injective (hom_ext hE hF hK)

/-- The braid relation on `Eᵢ, Eⱼ, Fᵢ, Fⱼ, K_μ`: the rank-two computations of `BraidAction/`. -/
theorem wordProd_pair (R : D.RootDatum Y) {i j : I} (hij : i ≠ j)
    (hfin : D.cartanMatrix i j * D.cartanMatrix j i ≤ 3) :
    (∀ l, (l = i ∨ l = j) →
      ((alternatingWord i j (D.cartanMatrix.coxeterMatrix i j)).map
        (braidEquivOfNotRoot R hv)).prod (E R v l) =
      ((alternatingWord j i (D.cartanMatrix.coxeterMatrix i j)).map
        (braidEquivOfNotRoot R hv)).prod (E R v l) ∧
      ((alternatingWord i j (D.cartanMatrix.coxeterMatrix i j)).map
        (braidEquivOfNotRoot R hv)).prod (F R v l) =
      ((alternatingWord j i (D.cartanMatrix.coxeterMatrix i j)).map
        (braidEquivOfNotRoot R hv)).prod (F R v l)) ∧
    ∀ μ, ((alternatingWord i j (D.cartanMatrix.coxeterMatrix i j)).map
        (braidEquivOfNotRoot R hv)).prod (K R v μ) =
      ((alternatingWord j i (D.cartanMatrix.coxeterMatrix i j)).map
        (braidEquivOfNotRoot R hv)).prod (K R v μ) := by
  have HT := braidEquivOfNotRoot_hasImages hv R
  have hq (l : I) := (shortNode_braidGeneric_of_not_root (D := D) hv l).sub_ne
  have hS := braidSerreGeneric_of_not_root (D := D) hv
  have hg (l : I) := braidGeneric_of_braidSerreGeneric (hq l) (hS l)
  have hT (l : I) := transformedSerre_of_braidSerreGeneric (R := R) (hq l) (hS l)
  have hs (l : I) := sum_ne_zero_of_qFactorial_three (pow_ne_zero (D.d l) (NeZero.ne v))
    (LusztigF.qFactorial_ne_zero_of_not_root (NeZero.ne v) hv l 3)
  have h3 (l : I) := LusztigF.qFactorial_ne_zero_of_not_root (D := D) (NeZero.ne v) hv l 3
  have hK (l : I) (μ : Y) : braidEquivOfNotRoot R hv l (K R v μ) = K R v (reflY R l μ) :=
    (HT l).map_K μ
  rw [Matrix.coxeterMatrix_apply_of_ne _ hij]
  rcases cartan_pair_cases hij hfin with ⟨h1, h1'⟩ | ⟨h1, h1'⟩ | ⟨h1, h1'⟩ |
    ⟨h1, h1'⟩ | ⟨h1, h1'⟩ | ⟨h1, h1'⟩
  · -- `A₁ × A₁`
    have hc := HasBraidGeneratorImages.equiv_comm (HT i) (HT j) hij h1
    simp only [h1, h1', mul_zero, Int.toNat_zero, Matrix.coxeterEntry, alternatingWord,
      List.concat_eq_append, List.nil_append, List.cons_append, List.map_cons, List.map_nil,
      List.prod_cons, List.prod_nil, mul_one]
    exact ⟨fun l _ ↦ ⟨by rw [hc], by rw [hc]⟩, fun μ ↦ by rw [hc]⟩
  all_goals
    simp only [h1, h1']; norm_num [Matrix.coxeterEntry]
    simp only [alternatingWord, List.concat_eq_append, List.nil_append, List.cons_append,
      List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one, AlgEquiv.mul_apply]
  · -- `A₂`
    have hqj : v ^ D.d j - (v ^ D.d j)⁻¹ ≠ 0 := hq j
    refine ⟨⟨⟨((HT i).three_Ei (HT j) hij h1 h1' (hq i)).symm,
      ((HT i).three_Fi (HT j) hij h1 h1' (hq i)).symm⟩,
      (HT j).three_Ei (HT i) hij.symm h1' h1 hqj, (HT j).three_Fi (HT i) hij.symm h1' h1 hqj⟩,
      fun μ ↦ ?_⟩
    simp only [hK, reflY_braid_of_simply_laced_edge h1 h1']
  · -- `B₂`, `aᵢⱼ = -2`
    refine ⟨⟨⟨braidHom_double_four_Ei (hg i) (hT i) (hg j) (hT j) hij h1 h1' (hs i),
      braidHom_double_four_Fi (hg i) (hT i) (hg j) (hT j) hij h1 h1' (hs i)⟩,
      braidHom_double_four_Ej (hg i) (hT i) (hg j) (hT j) hij h1 h1',
      braidHom_double_four_Fj (hg i) (hT i) (hg j) (hT j) hij h1 h1'⟩, fun μ ↦ ?_⟩
    simp only [hK, reflY_braid_of_double_edge h1 h1']
  · -- `B₂`, `aⱼᵢ = -2`
    refine ⟨⟨⟨(braidHom_double_four_Ej (hg j) (hT j) (hg i) (hT i) hij.symm h1' h1).symm,
      (braidHom_double_four_Fj (hg j) (hT j) (hg i) (hT i) hij.symm h1' h1).symm⟩,
      (braidHom_double_four_Ei (hg j) (hT j) (hg i) (hT i) hij.symm h1' h1 (hs j)).symm,
      (braidHom_double_four_Fi (hg j) (hT j) (hg i) (hT i) hij.symm h1' h1 (hs j)).symm⟩,
      fun μ ↦ ?_⟩
    simp only [hK, reflY_braid_of_double_edge h1' h1]
  · -- `G₂`, `aᵢⱼ = -3`
    refine ⟨⟨⟨tripleSix_six_Ei (HT i) (HT j) hij h1 h1' (hq i) (h3 i),
      tripleSix_six_Fi (HT i) (HT j) hij h1 h1' (hq i) (h3 i)⟩,
      tripleSix_six_Ej (HT i) (HT j) hij h1 h1' (hq i) (h3 i),
      tripleSix_six_Fj (HT i) (HT j) hij h1 h1' (hq i) (h3 i)⟩, fun μ ↦ ?_⟩
    simp only [hK, reflY_braid_six_of_triple_edge h1 h1']
  · -- `G₂`, `aⱼᵢ = -3`
    refine ⟨⟨⟨(tripleSix_six_Ej (HT j) (HT i) hij.symm h1' h1 (hq j) (h3 j)).symm,
      (tripleSix_six_Fj (HT j) (HT i) hij.symm h1' h1 (hq j) (h3 j)).symm⟩,
      (tripleSix_six_Ei (HT j) (HT i) hij.symm h1' h1 (hq j) (h3 j)).symm,
      (tripleSix_six_Fi (HT j) (HT i) hij.symm h1' h1 (hq j) (h3 j)).symm⟩, fun μ ↦ ?_⟩
    simp only [hK, reflY_braid_six_of_triple_edge h1' h1]

variable (R) in
/-- **The braid relations for Lusztig's `Tᵢ` for every Cartan datum** ([Lus] 39.4.3): if `v` is
nonzero and not a root of unity, the automorphisms `braidEquivOfNotRoot` satisfy the braid
relations of the Coxeter matrix of the Cartan matrix, for every root datum, in arbitrary rank and
with no condition on the Dynkin diagram. -/
theorem isBraidLiftable_braidEquivOfNotRoot :
    D.cartanMatrix.coxeterMatrix.IsBraidLiftable (braidEquivOfNotRoot R hv) := by
  intro i j hij hm
  have hMij := Matrix.coxeterMatrix_apply_of_ne D.cartanMatrix hij
  have hfin : D.cartanMatrix i j * D.cartanMatrix j i ≤ 3 := by
    by_contra h
    exact hm (by rw [hMij]; exact Matrix.coxeterEntry_of_four_le (by omega))
  change ((alternatingWord i j (D.cartanMatrix.coxeterMatrix i j)).map _).prod =
    ((alternatingWord j i (D.cartanMatrix.coxeterMatrix j i)).map _).prod
  rw [coxeterMatrix_comm i j]
  obtain ⟨hpair, hK⟩ := wordProd_pair hv R hij hfin
  refine algEquiv_eq_of_generators (fun l ↦ ?_) (fun l ↦ ?_) hK
  · by_cases hl : l = i ∨ l = j
    · exact (hpair l hl).1
    · obtain ⟨hli, hlj⟩ := not_or.1 hl
      exact wordProd_E_outer hv R hij hfin hli hlj
  · by_cases hl : l = i ∨ l = j
    · exact (hpair l hl).2
    · obtain ⟨hli, hlj⟩ := not_or.1 hl
      exact wordProd_F_outer hv R hij hfin hli hlj

variable (R) in
/-- **The Artin group action on `U` for every Cartan datum** ([Lus] 39.4.3): if `v` is nonzero
and not a root of unity, `σᵢ ↦ Tᵢ = braidEquivOfNotRoot` defines a homomorphism from the Artin
group of the Coxeter matrix of the Cartan matrix to the algebra automorphisms of `U`, for every
root datum, in arbitrary rank (Lusztig works over `ℚ(v)`). -/
def braidArtinHomOfNotRoot :
    D.cartanMatrix.coxeterMatrix.ArtinGroup →* (QuantumGroup R v ≃ₐ[k] QuantumGroup R v) :=
  CoxeterMatrix.artinLift (braidEquivOfNotRoot R hv) (isBraidLiftable_braidEquivOfNotRoot R hv)

@[simp]
theorem braidArtinHomOfNotRoot_artinGenerator (i : I) :
    braidArtinHomOfNotRoot R hv (D.cartanMatrix.coxeterMatrix.artinGenerator i) =
      braidEquivOfNotRoot R hv i :=
  CoxeterMatrix.artinLift_artinGenerator _ _ i

end Assembly

end LieLean.QuantumGroup
