/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.LinearAlgebra.Matrix.Cartan.WeylGroupExchange

/-!
# Real coroots

Let `A` be a generalized Cartan matrix with realization `(𝔥, Π, Π^∨)` over a field `K`. The
fundamental reflections `rᵢ^∨ h = h - ⟨αᵢ, h⟩ αᵢ^∨` of `𝔥` generate the group `W^∨ ⊂ GL(𝔥)`
(the contragredient action of the Weyl group, [Kac] §3.7), and the real coroots are the
elements `u αᵢ^∨`, `u ∈ W^∨` ([Kac] §5.1). The walls of the Tits cone in `𝔥*` are the
hyperplanes orthogonal to the real coroots.

We transfer the results on the signs of real roots
(`Matrix.Realization.apply_root_nonneg_or_nonpos`, `Matrix.Realization.eq_root_of_reflection_apply`)
to real coroots through the *transposed
realization* `(𝔥*, Π^∨, Π)` of `Aᵀ` (`Matrix.Realization.transpose`): its Weyl group acts on
`𝔥**`, and the evaluation map `𝔥 → 𝔥**` intertwines `W^∨` with it.

## Main definitions

* `Matrix.Realization.transpose`: the realization `(𝔥*, Π^∨, Π)` of `Aᵀ` ([Kac] §1.1).
* `Matrix.Realization.corootOf`: `k ↦ ∑ kᵢ αᵢ^∨`, the coroot lattice.
* `Matrix.Realization.coweylGroup`: the group `W^∨ ⊂ GL(𝔥)` generated by the `rᵢ^∨`.
* `Matrix.Realization.realCoroots`, `Matrix.Realization.posRealCoroots`: the real coroots and
  the positive real coroots.

## Main results

* `Matrix.Realization.exists_coweylGroup_apply_apply`: for `w ∈ W` there is `u ∈ W^∨` with
  `⟨w λ, h⟩ = ⟨λ, u h⟩`.
* `Matrix.Realization.mem_posRealCoroots_or_neg_mem`: every real coroot is positive or negative.
* `Matrix.Realization.coreflection_mem_posRealCoroots`: `rᵢ^∨` permutes the positive real
  coroots other than `αᵢ^∨` ([Kac] Lemma 3.7, for coroots).
* `Matrix.Realization.finite_inversionSet_coweylGroup`: an element of `W^∨` maps only finitely
  many positive real coroots to negative ones.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §1.1, §3.7, §5.1
  (stated over `ℂ`).
-/

open Module

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H) (hA : A.IsGeneralizedCartan)

/-! ### The transposed realization -/

/-- The transposed realization `(𝔥*, Π^∨, Π)` of `Aᵀ`: the coroots are the simple roots
`αᵢ ∈ 𝔥*` and the roots are the evaluations at the coroots `αᵢ^∨`, viewed in `𝔥**`. -/
noncomputable def transpose : Realization Aᵀ K (Dual K H) where
  coroot := P.root
  root i := Dual.eval K H (P.coroot i)
  linearIndependent_coroot := P.linearIndependent_root
  linearIndependent_root := P.linearIndependent_coroot.map' _
    (LinearMap.ker_eq_bot.mpr (Module.eval_apply_injective K))
  root_coroot i j := by simp [P.root_coroot]
  finrank_add_rank := by
    rw [Subspace.dual_finrank_eq, transpose_map, rank_transpose]
    exact P.finrank_add_rank

@[simp] lemma transpose_coroot (i : ι) : P.transpose.coroot i = P.root i := rfl

@[simp] lemma transpose_root (i : ι) : P.transpose.root i = Dual.eval K H (P.coroot i) := rfl

/-- The element `∑ kᵢ αᵢ^∨ ∈ 𝔥` of the coroot lattice attached to `k : ι → ℤ`. -/
def corootOf : (ι → ℤ) →+ H where
  toFun k := ∑ i, (k i : K) • P.coroot i
  map_zero' := by simp
  map_add' k l := by simp [add_smul, Finset.sum_add_distrib]

lemma corootOf_apply (k : ι → ℤ) : P.corootOf k = ∑ i, (k i : K) • P.coroot i := rfl

@[simp] lemma corootOf_single [DecidableEq ι] (i : ι) :
    P.corootOf (Pi.single i 1) = P.coroot i := by
  simp [corootOf_apply, Pi.single_apply]

lemma transpose_rootOf (k : ι → ℤ) :
    P.transpose.rootOf k = Dual.eval K H (P.corootOf k) := by
  simp [rootOf_apply, corootOf_apply, map_sum, map_smul]

lemma apply_corootOf (μ : Dual K H) (k : ι → ℤ) :
    μ (P.corootOf k) = ∑ i, (k i : K) * μ (P.coroot i) := by
  simp [corootOf_apply, map_sum, map_smul]

/-- The evaluation map `𝔥 → 𝔥**` intertwines `rᵢ^∨` with the fundamental reflection of the
transposed realization. -/
lemma eval_coreflection (i : ι) (x : H) :
    Dual.eval K H (P.coreflection hA i x) =
      P.transpose.reflection hA.transpose i (Dual.eval K H x) := by
  ext μ
  simp only [coreflection_apply, reflection_apply, map_sub, map_smul, Dual.eval_apply,
    transpose_coroot, transpose_root, LinearMap.sub_apply, LinearMap.smul_apply, smul_eq_mul]

/-! ### The group `W^∨` -/

@[simp] lemma coreflection_mul_self (i : ι) :
    P.coreflection hA i * P.coreflection hA i = 1 := by
  ext x : 1
  exact P.coreflection_coreflection hA i x

@[simp] lemma coreflection_inv (i : ι) : (P.coreflection hA i)⁻¹ = P.coreflection hA i :=
  inv_eq_of_mul_eq_one_right (P.coreflection_mul_self hA i)

/-- The group `W^∨ ⊂ GL(𝔥)` generated by the fundamental reflections `rᵢ^∨` of `𝔥`; it is the
contragredient of the Weyl group ([Kac] §3.7). -/
noncomputable def coweylGroup : Subgroup (H ≃ₗ[K] H) :=
  Subgroup.closure (Set.range (P.coreflection hA))

lemma coreflection_mem_coweylGroup (i : ι) : P.coreflection hA i ∈ P.coweylGroup hA :=
  Subgroup.subset_closure ⟨i, rfl⟩

/-- Induction principle for `W^∨`. -/
@[elab_as_elim]
lemma coweylGroup_induction {p : (H ≃ₗ[K] H) → Prop} (one : p 1)
    (mul : ∀ i u, u ∈ P.coweylGroup hA → p u → p (P.coreflection hA i * u)) {u : H ≃ₗ[K] H}
    (hu : u ∈ P.coweylGroup hA) : p u := by
  induction hu using Subgroup.closure_induction_left with
  | one => exact one
  | mul_left x hx u hu ih =>
    obtain ⟨i, rfl⟩ := hx
    exact mul i u hu ih
  | inv_mul_cancel x hx u hu ih =>
    obtain ⟨i, rfl⟩ := hx
    rw [coreflection_inv]
    exact mul i u hu ih

/-- For `w ∈ W` there is `u ∈ W^∨` with `⟨w λ, h⟩ = ⟨λ, u h⟩` for all `λ, h`. -/
theorem exists_coweylGroup_apply_apply {w : Dual K H ≃ₗ[K] Dual K H} (hw : w ∈ P.weylGroup hA) :
    ∃ u ∈ P.coweylGroup hA, ∀ μ x, w μ x = μ (u x) := by
  refine P.weylGroup_induction hA (p := fun w ↦ ∃ u ∈ P.coweylGroup hA, ∀ μ x, w μ x = μ (u x))
    ⟨1, one_mem _, fun _ _ ↦ rfl⟩ (fun i w ⟨u, hu, h⟩ ↦ ?_) hw
  refine ⟨u * P.coreflection hA i, mul_mem hu (P.coreflection_mem_coweylGroup hA i),
    fun μ x ↦ ?_⟩
  rw [LinearEquiv.mul_apply, reflection_apply_apply, h, LinearEquiv.mul_apply]

/-- The evaluation map `𝔥 → 𝔥**` intertwines `W^∨` with the Weyl group of the transposed
realization. -/
theorem exists_transpose_weylGroup {u : H ≃ₗ[K] H} (hu : u ∈ P.coweylGroup hA) :
    ∃ u' ∈ P.transpose.weylGroup hA.transpose,
      ∀ x, Dual.eval K H (u x) = u' (Dual.eval K H x) := by
  refine P.coweylGroup_induction hA (p := fun u ↦ ∃ u' ∈ P.transpose.weylGroup hA.transpose,
    ∀ x, Dual.eval K H (u x) = u' (Dual.eval K H x)) ⟨1, one_mem _, fun _ ↦ rfl⟩
    (fun i u _ ⟨u', hu', h⟩ ↦ ?_) hu
  refine ⟨P.transpose.reflection hA.transpose i * u',
    mul_mem (P.transpose.reflection_mem_weylGroup _ i) hu', fun x ↦ ?_⟩
  rw [LinearEquiv.mul_apply, eval_coreflection, h, LinearEquiv.mul_apply]

/-! ### Real coroots -/

/-- The real coroots `{u αᵢ^∨ | u ∈ W^∨, i ∈ ι}` ([Kac] §5.1). -/
def realCoroots : Set H :=
  {h | ∃ u ∈ P.coweylGroup hA, ∃ i, u (P.coroot i) = h}

/-- The positive real coroots: the real coroots which are nonnegative integral combinations of the
simple coroots. -/
def posRealCoroots : Set H :=
  {h | h ∈ P.realCoroots hA ∧ ∃ k : ι → ℤ, 0 ≤ k ∧ P.corootOf k = h}

lemma coroot_mem_realCoroots (i : ι) : P.coroot i ∈ P.realCoroots hA :=
  ⟨1, one_mem _, i, rfl⟩

lemma coroot_mem_posRealCoroots (i : ι) : P.coroot i ∈ P.posRealCoroots hA := by
  classical
  exact ⟨P.coroot_mem_realCoroots hA i, Pi.single i 1,
    fun j ↦ by by_cases h : j = i <;> simp [h], P.corootOf_single i⟩

lemma apply_mem_realCoroots {u : H ≃ₗ[K] H} (hu : u ∈ P.coweylGroup hA) {h : H}
    (hh : h ∈ P.realCoroots hA) : u h ∈ P.realCoroots hA := by
  obtain ⟨v, hv, i, rfl⟩ := hh
  exact ⟨u * v, mul_mem hu hv, i, rfl⟩

lemma neg_mem_realCoroots {h : H} (hh : h ∈ P.realCoroots hA) : -h ∈ P.realCoroots hA := by
  obtain ⟨u, hu, i, rfl⟩ := hh
  refine ⟨u * P.coreflection hA i, mul_mem hu (P.coreflection_mem_coweylGroup hA i), i, ?_⟩
  rw [LinearEquiv.mul_apply, coreflection_coroot_self, map_neg]

lemma ne_zero_of_mem_realCoroots {h : H} (hh : h ∈ P.realCoroots hA) : h ≠ 0 := by
  obtain ⟨u, -, i, rfl⟩ := hh
  rw [Ne, LinearEquiv.map_eq_zero_iff]
  exact P.linearIndependent_coroot.ne_zero i

section CharZero

variable [CharZero K]

/-- Every real coroot is either positive or negative ([Kac] Lemma 3.11 (a), for coroots). -/
theorem mem_posRealCoroots_or_neg_mem {h : H} (hh : h ∈ P.realCoroots hA) :
    h ∈ P.posRealCoroots hA ∨ -h ∈ P.posRealCoroots hA := by
  obtain ⟨u, hu, i, rfl⟩ := hh
  obtain ⟨u', hu', hu'e⟩ := P.exists_transpose_weylGroup hA hu
  have hr : u' (P.transpose.root i) = Dual.eval K H (u (P.coroot i)) := by
    rw [hu'e, transpose_root]
  rcases P.transpose.apply_root_nonneg_or_nonpos hA.transpose hu' i with ⟨k, hk, hk'⟩ | ⟨k, hk, hk'⟩
  · refine Or.inl ⟨⟨u, hu, i, rfl⟩, k, hk, Module.eval_apply_injective K ?_⟩
    rw [← transpose_rootOf, ← hk', hr]
  · refine Or.inr ⟨P.neg_mem_realCoroots hA ⟨u, hu, i, rfl⟩, k, hk,
      Module.eval_apply_injective K ?_⟩
    rw [← transpose_rootOf, map_neg, ← hr, hk', neg_neg]

/-- A real coroot cannot be both positive and negative. -/
theorem neg_notMem_posRealCoroots {h : H} (hh : h ∈ P.posRealCoroots hA) :
    -h ∉ P.posRealCoroots hA := by
  rintro ⟨-, l, hl, hlh⟩
  obtain ⟨hr, k, hk, rfl⟩ := hh
  have h0 : ∀ i, ((k + l) i : K) = 0 := by
    refine Fintype.linearIndependent_iff.mp P.linearIndependent_coroot _ ?_
    have := congrArg (· + P.corootOf k) hlh
    simp only [neg_add_cancel, ← map_add] at this
    simpa [corootOf_apply, add_comm] using this
  have hk0 : k = 0 := funext fun i ↦ by
    have := h0 i
    have := hk i; have := hl i
    simp only [Pi.add_apply, Pi.zero_apply] at *
    have : k i + l i = 0 := by exact_mod_cast ‹((k i + l i : ℤ) : K) = 0›
    omega
  exact P.ne_zero_of_mem_realCoroots hA hr (by rw [hk0, map_zero])

/-- A positive real coroot `h` with `rⱼ^∨ h` negative is the simple coroot `αⱼ^∨`. -/
theorem eq_coroot_of_coreflection_neg_mem {h : H} (hh : h ∈ P.posRealCoroots hA) {j : ι}
    (hj : -P.coreflection hA j h ∈ P.posRealCoroots hA) : h = P.coroot j := by
  obtain ⟨⟨u, hu, i, rfl⟩, k, hk, hkh⟩ := hh
  obtain ⟨-, l, hl, hlh⟩ := hj
  obtain ⟨u', hu', hu'e⟩ := P.exists_transpose_weylGroup hA hu
  have hr : u' (P.transpose.root i) = Dual.eval K H (u (P.coroot i)) := by
    rw [hu'e, transpose_root]
  refine Module.eval_apply_injective K ?_
  rw [← hr, ← transpose_root]
  refine P.transpose.eq_root_of_reflection_apply hA.transpose hu' hk ?_ hl ?_
  · rw [hr, transpose_rootOf, hkh]
  · rw [hr, ← eval_coreflection, transpose_rootOf, hlh, map_neg, neg_neg]

/-- `rᵢ^∨` maps a positive real coroot other than `αᵢ^∨` to a positive real coroot
([Kac] Lemma 3.7, for coroots). -/
theorem coreflection_mem_posRealCoroots {h : H} (hh : h ∈ P.posRealCoroots hA) {i : ι}
    (hi : h ≠ P.coroot i) : P.coreflection hA i h ∈ P.posRealCoroots hA := by
  refine (P.mem_posRealCoroots_or_neg_mem hA (P.apply_mem_realCoroots hA
    (P.coreflection_mem_coweylGroup hA i) hh.1)).resolve_right fun h' ↦ hi ?_
  exact P.eq_coroot_of_coreflection_neg_mem hA hh h'

/-- An element `u ∈ W^∨` maps only finitely many positive real coroots to non-positive ones
([Kac] Exercise 3.6, for coroots; it follows from Lemma 3.7 by induction). -/
theorem finite_inversionSet_coweylGroup {u : H ≃ₗ[K] H} (hu : u ∈ P.coweylGroup hA) :
    {h | h ∈ P.posRealCoroots hA ∧ u h ∉ P.posRealCoroots hA}.Finite := by
  refine P.coweylGroup_induction hA
    (p := fun u ↦ {h | h ∈ P.posRealCoroots hA ∧ u h ∉ P.posRealCoroots hA}.Finite)
    (by simp) (fun i u _ ih ↦ ?_) hu
  refine (ih.union (Set.finite_singleton (u.symm (P.coroot i)))).subset ?_
  rintro h ⟨hh, hih⟩
  by_cases huh : u h ∈ P.posRealCoroots hA
  · refine Or.inr (Set.mem_singleton_iff.mpr ?_)
    by_contra hne
    refine hih (P.coreflection_mem_posRealCoroots hA huh fun heq ↦ hne ?_)
    rw [← heq, LinearEquiv.symm_apply_apply]
  · exact Or.inl ⟨hh, huh⟩

end CharZero

end Matrix.Realization
