/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.Sl2

/-!
# The simple `U_q(𝔰𝔩₂)`-modules `L(n, σ)`

`U_v(𝔰𝔩₂)` is the quantized enveloping algebra `QuantumGroup R v` of the root datum of `SL₂`:
`I = {∗}`, `∗ · ∗ = 2`, `Y = ℤ` with simple coroot `1` and simple root `μ ↦ 2μ`
(`QuantumGroup.sl2RootDatum`). It is generated by `E`, `F`, `K^{±1} = K_{±1}` with
`K E K⁻¹ = v² E`, `K F K⁻¹ = v⁻² F`, `EF - FE = (K - K⁻¹)/(v - v⁻¹)` ([Jan] 1.1 (check)).

For `n ∈ ℕ` and `σ ∈ {±1}` the module `L(n, σ)` ([Jan] 2.2–2.3 (check)) has basis
`m₀, …, mₙ` with
`K mⱼ = σ v^{n-2j} mⱼ`, `F mⱼ = mⱼ₊₁` (`mₙ₊₁ = 0`), `E mⱼ = σ [j]_v [n+1-j]_v mⱼ₋₁` (`m₋₁ = 0`);
more generally `K_μ` acts on `mⱼ` by `σ^μ v^{μ(n-2j)}`. We realize it on `k^{n+1}`
(`QuantumGroup.Sl2.simpleRep`) and prove that it is irreducible when `v` is not a root of unity
(`QuantumGroup.Sl2.simpleRep_irreducible`).

## Main definitions

* `QuantumGroup.sl2Datum`, `QuantumGroup.sl2RootDatum`, `QuantumGroup.Sl2 v = U_v(𝔰𝔩₂)`.
* `QuantumGroup.Sl2.simpleRep v n σ`: the representation `U_v(𝔰𝔩₂) → End(k^{n+1})` of `L(n, σ)`.

## Main results

* `QuantumGroup.Sl2.simpleRep_E_single`, `simpleRep_F_single`, `simpleRep_K_single`: the action
  on the basis.
* `QuantumGroup.Sl2.simpleRep_irreducible`: `L(n, σ)` is irreducible.

## References

* [Jan] J. C. Jantzen, *Lectures on quantum groups*, GSM 6, Ch. 1–2.
-/

noncomputable section

namespace QuantumGroup

/-- The Cartan datum of type `A₁`: `I = {∗}` and `∗ · ∗ = 2`. -/
def sl2Datum : LusztigCartanDatum Unit where
  dot _ _ := 2
  dot_comm _ _ := rfl
  dot_self_pos _ := two_pos
  even_dot_self _ := even_two
  dot_nonpos i j h := absurd (Subsingleton.elim i j) h
  dot_self_dvd _ _ := ⟨2, rfl⟩

@[simp] lemma sl2Datum_d (i : Unit) : sl2Datum.d i = 1 := rfl

@[simp] lemma sl2Datum_cartanMatrix (i j : Unit) : sl2Datum.cartanMatrix i j = 2 := rfl

/-- The root datum of `SL₂`: `Y = ℤ`, simple coroot `1`, simple root `μ ↦ 2μ`. -/
def sl2RootDatum : sl2Datum.RootDatum ℤ where
  coroot _ := 1
  root _ := 2 • AddMonoidHom.id ℤ
  root_coroot _ _ := rfl

@[simp] lemma sl2RootDatum_root (i : Unit) (μ : ℤ) : sl2RootDatum.root i μ = 2 * μ := by
  simp [sl2RootDatum]

@[simp] lemma sl2RootDatum_ktilde (i : Unit) : ktilde sl2RootDatum i = 1 := by
  simp [ktilde, sl2RootDatum]

/-- The quantized enveloping algebra `U_v(𝔰𝔩₂)`. -/
abbrev Sl2 {k : Type*} [Field k] (v : k) : Type _ := QuantumGroup sl2RootDatum v

namespace Sl2

variable {k : Type*} [Field k] (v : k) (n : ℕ) (σ : k)

/-- Coordinates of `x ∈ k^{n+1}`, extended by zero to `ℕ`. -/
def coord (x : Fin (n + 1) → k) (l : ℕ) : k := if h : l < n + 1 then x ⟨l, h⟩ else 0

variable {n} in
lemma coord_of_lt (x : Fin (n + 1) → k) {l : ℕ} (h : l < n + 1) : coord n x l = x ⟨l, h⟩ :=
  by simp [coord, h]

variable {n} in
lemma coord_of_le (x : Fin (n + 1) → k) {l : ℕ} (h : n + 1 ≤ l) : coord n x l = 0 :=
  by simp [coord]; omega

variable {n} in
@[simp] lemma coord_fin (x : Fin (n + 1) → k) (j : Fin (n + 1)) : coord n x j = x j :=
  coord_of_lt x j.2

@[simp] lemma coord_zero (l : ℕ) : coord n (0 : Fin (n + 1) → k) l = 0 := by
  unfold coord; split_ifs <;> rfl

lemma coord_add (x y : Fin (n + 1) → k) (l : ℕ) :
    coord n (x + y) l = coord n x l + coord n y l := by
  unfold coord; split_ifs <;> simp

lemma coord_sub (x y : Fin (n + 1) → k) (l : ℕ) :
    coord n (x - y) l = coord n x l - coord n y l := by
  unfold coord; split_ifs <;> simp

lemma coord_smul (c : k) (x : Fin (n + 1) → k) (l : ℕ) : coord n (c • x) l = c * coord n x l := by
  unfold coord; split_ifs <;> simp

/-- The scalars `σ [j]_v [n+1-j]_v` by which `E` lowers `mⱼ` to `mⱼ₋₁`. -/
def eCoeff (j : ℕ) : k := σ * qInt v j * qInt v (n + 1 - j)

@[simp] lemma eCoeff_zero : eCoeff v n σ 0 = 0 := by simp [eCoeff]

@[simp] lemma eCoeff_succ_self : eCoeff v n σ (n + 1) = 0 := by simp [eCoeff]

/-- The operator `F` on `L(n, σ)`: `mⱼ ↦ mⱼ₊₁`. -/
def opF : Module.End k (Fin (n + 1) → k) where
  toFun x j := if (j : ℕ) = 0 then 0 else coord n x (j - 1)
  map_add' x y := by
    ext j
    simp only [Pi.add_apply]
    split_ifs <;> simp only [coord_add, add_zero]
  map_smul' c x := by
    ext j
    simp only [Pi.smul_apply, smul_eq_mul, RingHom.id_apply]
    split_ifs <;> simp only [coord_smul, mul_zero]

/-- The operator `E` on `L(n, σ)`: `mⱼ ↦ σ [j] [n+1-j] mⱼ₋₁`. -/
def opE : Module.End k (Fin (n + 1) → k) where
  toFun x j := eCoeff v n σ (j + 1) * coord n x (j + 1)
  map_add' x y := by ext j; simp [coord_add, mul_add]
  map_smul' c x := by ext j; simp [coord_smul]; ring

/-- The operator `K_μ` on `L(n, σ)`: `mⱼ ↦ σ^μ v^{μ(n-2j)} mⱼ`. -/
def opK (μ : ℤ) : Module.End k (Fin (n + 1) → k) where
  toFun x j := σ ^ μ * v ^ (μ * ((n : ℤ) - 2 * j)) * x j
  map_add' x y := by ext j; simp [mul_add]
  map_smul' c x := by ext j; simp; ring

variable {v n σ}

lemma coord_opF (x : Fin (n + 1) → k) (l : ℕ) :
    coord n (opF n x) l = if 0 < l ∧ l < n + 1 then coord n x (l - 1) else 0 := by
  by_cases hl : l < n + 1
  · rw [coord_of_lt _ hl]
    change (if l = 0 then 0 else coord n x (l - 1)) = _
    by_cases h0 : l = 0 <;> simp [h0, hl]
  · rw [coord_of_le _ (by omega)]; simp; omega

lemma coord_opE (x : Fin (n + 1) → k) (l : ℕ) :
    coord n (opE v n σ x) l = eCoeff v n σ (l + 1) * coord n x (l + 1) := by
  by_cases hl : l < n + 1
  · rw [coord_of_lt _ hl]; rfl
  · rw [coord_of_le _ (by omega), coord_of_le _ (by omega), mul_zero]

lemma coord_opK (μ : ℤ) (x : Fin (n + 1) → k) (l : ℕ) :
    coord n (opK v n σ μ x) l = σ ^ μ * v ^ (μ * ((n : ℤ) - 2 * l)) * coord n x l := by
  by_cases hl : l < n + 1
  · rw [coord_of_lt _ hl, coord_of_lt _ hl]; rfl
  · rw [coord_of_le _ (by omega), coord_of_le _ (by omega), mul_zero]

lemma ext_coord {x y : Fin (n + 1) → k} (h : ∀ l, coord n x l = coord n y l) : x = y := by
  ext j; simpa using h j

/-- The key identity `σ([l+1][n-l] - [l][n+1-l]) = σ(v^{n-2l} - v^{2l-n})/(v - v⁻¹)`
behind `EF - FE = (K - K⁻¹)/(v - v⁻¹)` on `L(n, σ)`. -/
lemma eCoeff_succ_sub (hv : v ≠ 0) (hv2 : v ^ 2 ≠ 1) (hσ : σ ^ 2 = 1) {l : ℕ} (hl : l ≤ n) :
    eCoeff v n σ (l + 1) - eCoeff v n σ l = (v - v⁻¹)⁻¹ *
      (σ ^ (1 : ℤ) * v ^ ((1 : ℤ) * ((n : ℤ) - 2 * l)) -
        σ ^ (-1 : ℤ) * v ^ ((-1 : ℤ) * ((n : ℤ) - 2 * l))) := by
  have hD : v - v⁻¹ ≠ 0 := by
    intro h
    apply hv2
    have : v * v = v * v⁻¹ := congrArg (v * ·) (sub_eq_zero.1 h)
    rwa [mul_inv_cancel₀ hv, ← sq] at this
  have hq : ∀ m, qInt v m = (v ^ m - (v ^ m)⁻¹) / (v - v⁻¹) := fun m ↦ by
    rw [eq_div_iff hD, mul_comm, qInt_mul_sub, inv_pow]
  have hσ' : σ⁻¹ = σ := inv_eq_of_mul_eq_one_right (by rw [← sq, hσ])
  have hz : (n : ℤ) - 2 * l = ((n - l : ℕ) : ℤ) - (l : ℤ) := by push_cast [hl]; ring
  have ha : v ^ l ≠ 0 := pow_ne_zero _ hv
  have hb : v ^ (n - l) ≠ 0 := pow_ne_zero _ hv
  simp only [eCoeff, one_mul, zpow_one, neg_one_mul, zpow_neg, hz, zpow_sub₀ hv, zpow_natCast,
    hσ']
  rw [hq, hq, hq, hq, show n + 1 - (l + 1) = n - l by omega, show n + 1 - l = n - l + 1 by omega,
    pow_succ, pow_succ]
  field_simp
  ring

variable (v n σ) in
/-- `μ ↦ K_μ` on `L(n, σ)` as a monoid homomorphism. -/
def opKHom (hv : v ≠ 0) (hσ : σ ≠ 0) : Multiplicative ℤ →* Module.End k (Fin (n + 1) → k) where
  toFun μ := opK v n σ μ.toAdd
  map_one' := LinearMap.ext fun x ↦ funext fun j ↦ by simp [opK]
  map_mul' a b := LinearMap.ext fun x ↦ funext fun j ↦ by
    simp only [opK, toAdd_mul, LinearMap.coe_mk, AddHom.coe_mk, Module.End.mul_apply,
      zpow_add₀ hσ, add_mul, zpow_add₀ hv]
    ring

lemma opKHom_apply (hv : v ≠ 0) (hσ : σ ≠ 0) (μ : ℤ) :
    opKHom v n σ hv hσ (.ofAdd μ) = opK v n σ μ := rfl

/-- The operators `E, F, K_μ` on `k^{n+1}` satisfy the defining relations of `U_v(𝔰𝔩₂)`. -/
theorem relations (hv : v ≠ 0) (hv2 : v ^ 2 ≠ 1) (hσ : σ ^ 2 = 1) :
    Relations sl2RootDatum v (fun _ ↦ opE v n σ) (fun _ ↦ opF n)
      (opKHom v n σ hv (by rintro rfl; simp at hσ)) where
  K_mul_E μ i := LinearMap.ext fun x ↦ ext_coord fun l ↦ by
    simp only [opKHom_apply, Module.End.mul_apply, LinearMap.smul_apply, coord_smul, coord_opK,
      coord_opE, sl2RootDatum_root]
    rw [show μ * ((n : ℤ) - 2 * l) = 2 * μ + μ * ((n : ℤ) - 2 * ((l + 1 : ℕ) : ℤ)) by
      push_cast; ring, zpow_add₀ hv]
    ring
  K_mul_F μ i := LinearMap.ext fun x ↦ ext_coord fun l ↦ by
    simp only [opKHom_apply, Module.End.mul_apply, LinearMap.smul_apply, coord_smul, coord_opK,
      coord_opF, sl2RootDatum_root]
    split_ifs with h
    · obtain ⟨l, rfl⟩ : ∃ l', l = l' + 1 := ⟨l - 1, by omega⟩
      rw [show μ * ((n : ℤ) - 2 * ((l + 1 : ℕ) : ℤ)) =
        -(2 * μ) + μ * ((n : ℤ) - 2 * ((l + 1 - 1 : ℕ) : ℤ)) by push_cast; ring, zpow_add₀ hv]
      ring
    · simp
  E_mul_F i j := LinearMap.ext fun x ↦ ext_coord fun l ↦ by
    obtain rfl := Subsingleton.elim i j
    simp only [↓reduceIte, sl2Datum_d, pow_one, sl2RootDatum_ktilde, LinearMap.sub_apply,
      Module.End.mul_apply, LinearMap.smul_apply, opKHom_apply, coord_sub, coord_smul,
      coord_opE, coord_opF, coord_opK]
    by_cases hl : l < n + 1
    · have key := eCoeff_succ_sub hv hv2 hσ (show l ≤ n by omega)
      have e1 : eCoeff v n σ (l + 1) * (if 0 < l + 1 ∧ l + 1 < n + 1 then coord n x (l + 1 - 1)
          else 0) = eCoeff v n σ (l + 1) * coord n x l := by
        split_ifs with h
        · rfl
        · obtain rfl : l = n := by omega
          simp
      have e2 : (if 0 < l ∧ l < n + 1 then eCoeff v n σ (l - 1 + 1) * coord n x (l - 1 + 1)
          else 0) = eCoeff v n σ l * coord n x l := by
        split_ifs with h
        · rw [Nat.sub_add_cancel (by omega)]
        · obtain rfl : l = 0 := by omega
          simp
      rw [e1, e2]
      linear_combination coord n x l * key
    · rw [coord_of_le x (show n + 1 ≤ l by omega)]
      simp only [mul_zero, sub_zero]
      split_ifs <;> first | (exfalso; omega) | simp
  serre_E i j h := absurd (Subsingleton.elim i j) h
  serre_F i j h := absurd (Subsingleton.elim i j) h

variable (v n σ) in
/-- The representation `L(n, σ)` of `U_v(𝔰𝔩₂)` on `k^{n+1}` ([Jan] 2.2–2.3 (check)). -/
def simpleRep (hv : v ≠ 0) (hv2 : v ^ 2 ≠ 1) (hσ : σ ^ 2 = 1) :
    Sl2 v →ₐ[k] Module.End k (Fin (n + 1) → k) :=
  lift (relations hv hv2 hσ)

section Basis

variable (hv : v ≠ 0) (hv2 : v ^ 2 ≠ 1) (hσ : σ ^ 2 = 1)

@[simp] lemma simpleRep_E (i : Unit) : simpleRep v n σ hv hv2 hσ (E sl2RootDatum v i) = opE v n σ :=
  lift_E _ i

@[simp] lemma simpleRep_F (i : Unit) : simpleRep v n σ hv hv2 hσ (F sl2RootDatum v i) = opF n :=
  lift_F _ i

@[simp] lemma simpleRep_K (μ : ℤ) : simpleRep v n σ hv hv2 hσ (K sl2RootDatum v μ) = opK v n σ μ :=
  lift_K _ μ

omit hv hv2 hσ in
lemma coord_single (j : Fin (n + 1)) (c : k) (l : ℕ) :
    coord n (Pi.single j c) l = if l = j then c else 0 := by
  have hj := j.2
  by_cases hl : l < n + 1
  · rw [coord_of_lt _ hl, Pi.single_apply]
    simp only [Fin.ext_iff]
  · rw [coord_of_le _ (by omega)]
    split_ifs <;> first | rfl | (exfalso; omega)

/-- `F mⱼ = mⱼ₊₁` (and `F mₙ = 0`). -/
theorem simpleRep_F_single (i : Unit) (j : Fin (n + 1)) :
    simpleRep v n σ hv hv2 hσ (F sl2RootDatum v i) (Pi.single j 1) =
      if h : (j : ℕ) + 1 < n + 1 then Pi.single ⟨j + 1, h⟩ 1 else 0 := by
  rw [simpleRep_F]
  refine ext_coord fun l ↦ ?_
  have hj := j.2
  rw [coord_opF]
  by_cases h : (j : ℕ) + 1 < n + 1
  · simp only [h, ↓reduceDIte, coord_single]
    split_ifs <;> first | rfl | (exfalso; omega)
  · simp only [h, ↓reduceDIte, coord_single, coord_zero]
    split_ifs <;> first | rfl | (exfalso; omega)

/-- `E mⱼ = σ [j] [n+1-j] mⱼ₋₁` (and `E m₀ = 0`). -/
theorem simpleRep_E_single (i : Unit) (j : Fin (n + 1)) :
    simpleRep v n σ hv hv2 hσ (E sl2RootDatum v i) (Pi.single j 1) =
      if h : 0 < (j : ℕ) then eCoeff v n σ j • Pi.single ⟨j - 1, by omega⟩ 1 else 0 := by
  rw [simpleRep_E]
  refine ext_coord fun l ↦ ?_
  have hj := j.2
  rw [coord_opE, coord_single]
  by_cases h : 0 < (j : ℕ)
  · simp only [h, ↓reduceDIte, coord_smul, coord_single]
    split_ifs with h1 h2 h2
    · rw [h1]
    · exfalso; omega
    · exfalso; omega
    · simp
  · simp only [h, ↓reduceDIte, coord_zero]
    split_ifs <;> first | (exfalso; omega) | simp

/-- `K_μ mⱼ = σ^μ v^{μ(n-2j)} mⱼ`. -/
theorem simpleRep_K_single (μ : ℤ) (j : Fin (n + 1)) :
    simpleRep v n σ hv hv2 hσ (K sl2RootDatum v μ) (Pi.single j 1) =
      (σ ^ μ * v ^ (μ * ((n : ℤ) - 2 * j))) • Pi.single j 1 := by
  rw [simpleRep_K]
  refine ext_coord fun l ↦ ?_
  rw [coord_opK, coord_smul, coord_single]
  split_ifs with h
  · subst h; rfl
  · simp

end Basis

lemma coord_opF_pow (a : ℕ) (x : Fin (n + 1) → k) (l : ℕ) :
    coord n ((opF n ^ a) x) l = if a ≤ l ∧ l < n + 1 then coord n x (l - a) else 0 := by
  induction a generalizing l with
  | zero =>
    simp only [pow_zero, Module.End.one_apply, zero_le, true_and, Nat.sub_zero]
    split_ifs with h
    · rfl
    · exact coord_of_le x (by omega)
  | succ a ih =>
    rw [pow_succ', Module.End.mul_apply, coord_opF, ih]
    split_ifs <;> first | (exfalso; omega) | rfl | (congr 1; omega)

lemma coord_opE_pow (a : ℕ) (x : Fin (n + 1) → k) (l : ℕ) :
    coord n ((opE v n σ ^ a) x) l =
      (∏ t ∈ Finset.range a, eCoeff v n σ (l + 1 + t)) * coord n x (l + a) := by
  induction a generalizing l with
  | zero => simp
  | succ a ih =>
    rw [pow_succ', Module.End.mul_apply, coord_opE, ih, Finset.prod_range_succ',
      show l + 1 + a = l + (a + 1) by omega]
    simp only [add_zero]
    have : ∏ t ∈ Finset.range a, eCoeff v n σ (l + 1 + 1 + t) =
        ∏ t ∈ Finset.range a, eCoeff v n σ (l + 1 + (t + 1)) :=
      Finset.prod_congr rfl fun t _ ↦ by rw [show l + 1 + 1 + t = l + 1 + (t + 1) by omega]
    rw [this]
    ring

/-- `L(n, σ)` is irreducible if `v` is not a root of unity ([Jan] 2.3 (check)): the only
subspaces of `k^{n+1}` stable under `U_v(𝔰𝔩₂)` are `0` and `k^{n+1}`. -/
theorem simpleRep_irreducible (hv : v ≠ 0) (hv' : ∀ m : ℕ, 0 < m → v ^ m ≠ 1) (hσ : σ ^ 2 = 1)
    (W : Submodule k (Fin (n + 1) → k))
    (hW : ∀ (u : Sl2 v) x, x ∈ W → simpleRep v n σ hv (hv' 2 two_pos) hσ u x ∈ W) :
    W = ⊥ ∨ W = ⊤ := by
  classical
  by_cases hW0 : W = ⊥
  · exact Or.inl hW0
  right
  have hσ0 : σ ≠ 0 := by rintro rfl; simp at hσ
  have hFW : ∀ a y, y ∈ W → (opF n ^ a) y ∈ W := fun a y hy ↦ by
    have := hW (F sl2RootDatum v () ^ a) y hy
    rwa [map_pow, simpleRep_F] at this
  have hEW : ∀ a y, y ∈ W → (opE v n σ ^ a) y ∈ W := fun a y hy ↦ by
    have := hW (E sl2RootDatum v () ^ a) y hy
    rwa [map_pow, simpleRep_E] at this
  have hsmul : ∀ (c : k) y, c ≠ 0 → c • y ∈ W → y ∈ W := fun c y hc h ↦ by
    simpa [smul_smul, inv_mul_cancel₀ hc] using W.smul_mem c⁻¹ h
  obtain ⟨x, hxW, hx0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hW0
  have hex : ∃ l, coord n x l ≠ 0 := by
    by_contra! h
    exact hx0 (ext_coord fun l ↦ by simp [h l])
  set j0 := Nat.find hex
  have hj0 : coord n x j0 ≠ 0 := Nat.find_spec hex
  have hmin : ∀ l < j0, coord n x l = 0 := fun l hl ↦ by simpa using Nat.find_min hex hl
  have hj0n : j0 < n + 1 := by
    by_contra h
    exact hj0 (coord_of_le x (by omega))
  -- `F^{n - j₀} x = x_{j₀} mₙ`
  have h1 : (opF n ^ (n - j0)) x = coord n x j0 • Pi.single (Fin.last n) 1 :=
    ext_coord fun l ↦ by
      rw [coord_opF_pow, coord_smul, coord_single, Fin.val_last]
      split_ifs with h h'
      · rw [h', show n - (n - j0) = j0 by omega, mul_one]
      · rw [hmin _ (by omega), mul_zero]
      · exfalso; omega
      · rw [mul_zero]
  have hn : Pi.single (Fin.last n) (1 : k) ∈ W := hsmul _ _ hj0 (h1 ▸ hFW _ _ hxW)
  -- `E^n mₙ = (∏ₜ σ [t+1] [n-t]) m₀`
  have hP : ∏ t ∈ Finset.range n, eCoeff v n σ (0 + 1 + t) ≠ 0 := by
    rw [Finset.prod_ne_zero_iff]
    intro t ht
    have ht := Finset.mem_range.1 ht
    have hq : ∀ m, 0 < m → qInt v m ≠ 0 := fun m hm ↦ qInt_ne_zero hv (hv' _ (by omega))
    exact mul_ne_zero (mul_ne_zero hσ0 (hq _ (by omega))) (hq _ (by omega))
  have h2 : (opE v n σ ^ n) (Pi.single (Fin.last n) 1) =
      (∏ t ∈ Finset.range n, eCoeff v n σ (0 + 1 + t)) • Pi.single 0 1 :=
    ext_coord fun l ↦ by
      rw [coord_opE_pow, coord_single, coord_smul, coord_single, Fin.val_last, Fin.val_zero]
      split_ifs with h h'
      · subst h'; simp
      · exfalso; omega
      · omega
      · rw [mul_zero, mul_zero]
  have h0 : Pi.single (0 : Fin (n + 1)) (1 : k) ∈ W := hsmul _ _ hP (h2 ▸ hEW _ _ hn)
  -- `F^j m₀ = mⱼ`
  have hall : ∀ j : Fin (n + 1), Pi.single j (1 : k) ∈ W := fun j ↦ by
    have h3 : (opF n ^ (j : ℕ)) (Pi.single 0 1) = Pi.single j (1 : k) := ext_coord fun l ↦ by
      have := j.2
      rw [coord_opF_pow, coord_single, coord_single, Fin.val_zero]
      split_ifs <;> first | rfl | (exfalso; omega)
    exact h3 ▸ hFW _ _ h0
  rw [eq_top_iff]
  rintro y -
  rw [← Finset.univ_sum_single y]
  refine W.sum_mem fun j _ ↦ ?_
  have : Pi.single j (y j) = y j • Pi.single j (1 : k) := by
    ext l; by_cases h : l = j <;> simp [h]
  rw [this]
  exact W.smul_mem _ (hall j)

end Sl2

end QuantumGroup
