/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import Mathlib.Topology.Instances.Rat
import Mathlib.Topology.Order.LeftRightNhds
import LieLean.LinearAlgebra.Matrix.Cartan.IntegralWeylGroup
import LieLean.LinearAlgebra.Matrix.Cartan.TitsCone
import LieLean.LinearAlgebra.Matrix.Cartan.FiniteType
import LieLean.LinearAlgebra.Matrix.Cartan.WeylGroupExchange
import LieLean.LinearAlgebra.Matrix.Cartan.WeylGroupForm

/-!
# The affine Weyl group `W ⋉ Q` and the integral Weyl group of a rational weight

Let `A` be a Cartan matrix of finite type with a realization over `ℚ`. The group `W ⋉ Q` acts on
`𝔥*` by affine maps `x ↦ w x + δ`; it is generated by the affine reflections
`x ↦ x - (⟨x, β^∨⟩ - k) β` (`k ∈ ℤ`) in the hyperplanes `⟨x, β^∨⟩ = k`. An element `w ∈ W` lies in
the integral Weyl group `W_[x] = {w | w x - x ∈ Q}` exactly when `x ↦ w x - (w x - x)` is an
element of `W ⋉ Q` fixing `x`, so Humphreys, GSM 94, Thm. 3.4 (b) — `W_[x]` is generated by the
reflections in the roots integral for `x` — is the statement that the stabilizer of a point in
`W ⋉ Q` is generated by the affine reflections fixing it. We prove it for rational weights.

A real root is written `β = v αᵢ` (`v ∈ W`), with `⟨x, β^∨⟩ = ⟨v⁻¹ x, αᵢ^∨⟩`
(`Matrix.Realization.corootPairing`); it is positive if `v αᵢ ∈ Q₊`
(`Matrix.Realization.IsPosRoot`).

## Main results

* `Matrix.Realization.length_mul_reflectionOf_lt`: if `β > 0` and `w β < 0` then
  `ℓ(w s_β) < ℓ(w)` (any generalized Cartan matrix, characteristic zero).
* `Matrix.Realization.eq_zero_of_mem_rootLattice_of_corootPairing`: `0` is the only element `μ`
  of `Q` with `⟨μ, β^∨⟩ ∈ {0, 1}` for all positive roots `β`.
* `Matrix.Realization.exists_mem_closedAlcove`: every `W ⋉ Q`-orbit of rational weights meets the
  closed fundamental alcove `{x | 0 ≤ ⟨x, β^∨⟩ ≤ 1 for all β > 0}`.
* `Matrix.Realization.eq_one_of_mem_openAlcove`: no element `w ≠ 1` of `W` has `w x - x ∈ Q` for a
  point `x` of the open fundamental alcove.
* `Matrix.Realization.eq_one_of_forall_not_isIntegralRoot`: `W_[x] = 1` if no root is integral
  for `x`.
* `Matrix.Realization.integralWeylGroup_eq_integralReflectionGroup_of_rat`: Humphreys, GSM 94,
  Thm. 3.4 (b) for rational weights.

## Proofs

Our own arguments, organized differently from the alcove theory of Humphreys, *Reflection groups
and Coxeter groups*, Ch. 4 (§4.3 alcoves, §4.5 simple transitivity, §4.8 fundamental domain),
which treats `W ⋉ L(Φ^∨)` acting on `V`; here the translations are by the root lattice and the
hyperplanes are `⟨x, β^∨⟩ = k`. No Coxeter presentation of `W ⋉ Q` is used.

* The closed alcove meets every orbit: minimize the distance to a point of the open alcove over
  the orbit, which is discrete (all its points lie in `N⁻¹ Q` for some `N`); a point outside the
  closed alcove is moved closer by an affine reflection.
* Freeness on the open alcove: if `0 < ⟨x, β^∨⟩ < 1` for all `β > 0` and `w x = x + γ`, `γ ∈ Q`,
  then `⟨γ, β^∨⟩ ∈ {-1, 0}` for all `β > 0`; then `γ = 0` by a norm argument (pick the element
  `∑ kⱼ αⱼ` of the `W`-orbit of `-γ` with `∑ |kⱼ|` minimal; then `kᵀ diag(d) A k ≤ 0`), and `w`
  fixes a strictly dominant weight.
* If `w ∈ W_[x]` maps the positive roots integral for `x` to positive roots, average `ρ` over
  `⟨w⟩`: for small `ε > 0` the weight `x + ε ρ'` is generic and `w ∈ W_[x + ε ρ']`, so `w = 1`.
* Otherwise multiply `w` by the reflection in a positive integral root that `w` makes negative,
  which decreases the length.

## References

* J. E. Humphreys, *Representations of semisimple Lie algebras in the BGG category 𝒪*, GSM 94,
  AMS 2008, §3.4.
* J. E. Humphreys, *Reflection groups and Coxeter groups*, CUP 1990, Ch. 4.
-/

noncomputable section

open Module CoxeterSystem Filter Topology

/-- For `a, b ∈ ℚ` with `a ∉ ℤ` or `b ≠ 0`, `a + ε b ∉ ℤ` for all small `ε > 0`. -/
theorem Rat.eventually_not_exists_int_add_mul {a b : ℚ} (h : (¬∃ z : ℤ, a = z) ∨ b ≠ 0) :
    ∀ᶠ ε in 𝓝[>] (0 : ℚ), ¬∃ z : ℤ, a + ε * b = z := by
  by_cases ha : ∃ z : ℤ, a = z
  · obtain ⟨z₀, rfl⟩ := ha
    have hb : b ≠ 0 := h.resolve_left (not_not.mpr ⟨z₀, rfl⟩)
    have hb' : 0 < |b| := abs_pos.mpr hb
    filter_upwards [Ioo_mem_nhdsGT (inv_pos.mpr hb')] with ε hε
    rintro ⟨z, hz⟩
    have h1 : ε * b = ((z - z₀ : ℤ) : ℚ) := by push_cast; linarith
    have h2 : |ε * b| < 1 := by
      rw [abs_mul, abs_of_pos hε.1]
      calc ε * |b| < |b|⁻¹ * |b| := mul_lt_mul_of_pos_right hε.2 hb'
        _ = 1 := inv_mul_cancel₀ hb'.ne'
    have h3 : ε * b ≠ 0 := mul_ne_zero hε.1.ne' hb
    rw [h1] at h2 h3
    have h4 : |z - z₀| < 1 := by
      rw [← Int.cast_abs] at h2
      exact_mod_cast h2
    exact h3 (by rw [Int.abs_lt_one_iff.mp h4, Int.cast_zero])
  · have hlt : (⌊a⌋ : ℚ) < a := lt_of_le_of_ne (Int.floor_le a) fun h ↦ ha ⟨_, h.symm⟩
    have hlt' : a < ⌊a⌋ + 1 := Int.lt_floor_add_one a
    have hcont : Continuous fun ε : ℚ ↦ a + ε * b := by fun_prop
    have hmem : (fun ε : ℚ ↦ a + ε * b) ⁻¹' Set.Ioo (⌊a⌋ : ℚ) (⌊a⌋ + 1) ∈ 𝓝 (0 : ℚ) :=
      hcont.continuousAt.preimage_mem_nhds
        (show Set.Ioo (⌊a⌋ : ℚ) (⌊a⌋ + 1) ∈ 𝓝 (a + 0 * b) by
          rw [zero_mul, add_zero]; exact Ioo_mem_nhds hlt hlt')
    filter_upwards [nhdsWithin_le_nhds hmem] with ε hε
    rintro ⟨z, hz⟩
    simp only [Set.mem_preimage, Set.mem_Ioo, hz] at hε
    have h1 : ⌊a⌋ < z := by exact_mod_cast hε.1
    have h2 : z < ⌊a⌋ + 1 := by exact_mod_cast hε.2
    omega

namespace Matrix.Realization

section General

variable {ι K H : Type*} [Fintype ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H) (hA : A.IsGeneralizedCartan)

/-- The pairing `⟨x, β^∨⟩ = ⟨v⁻¹ x, αᵢ^∨⟩` of a weight `x` with the coroot of the real root
`β = v αᵢ`. -/
def corootPairing (x : Dual K H) (v : P.weylGroup hA) (i : ι) : K :=
  ((v⁻¹ : P.weylGroup hA) : Dual K H ≃ₗ[K] Dual K H) x (P.coroot i)

/-- The real root `v αᵢ` is positive: `v αᵢ ∈ Q₊`. -/
def IsPosRoot (v : P.weylGroup hA) (i : ι) : Prop :=
  ∃ k : ι → ℤ, 0 ≤ k ∧ (v : Dual K H ≃ₗ[K] Dual K H) (P.root i) = P.rootOf k

variable {P hA}

lemma isIntegralRoot_iff_corootPairing {x : Dual K H} {v : P.weylGroup hA} {i : ι} :
    P.IsIntegralRoot hA x v i ↔ ∃ z : ℤ, P.corootPairing hA x v i = z :=
  Iff.rfl

@[simp] lemma corootPairing_one (x : Dual K H) (i : ι) :
    P.corootPairing hA x 1 i = x (P.coroot i) := by
  simp [corootPairing]

lemma corootPairing_add (x y : Dual K H) (v : P.weylGroup hA) (i : ι) :
    P.corootPairing hA (x + y) v i = P.corootPairing hA x v i + P.corootPairing hA y v i := by
  simp [corootPairing]

lemma corootPairing_sub (x y : Dual K H) (v : P.weylGroup hA) (i : ι) :
    P.corootPairing hA (x - y) v i = P.corootPairing hA x v i - P.corootPairing hA y v i := by
  simp [corootPairing]

lemma corootPairing_neg (x : Dual K H) (v : P.weylGroup hA) (i : ι) :
    P.corootPairing hA (-x) v i = -P.corootPairing hA x v i := by
  simp [corootPairing]

lemma corootPairing_smul (c : K) (x : Dual K H) (v : P.weylGroup hA) (i : ι) :
    P.corootPairing hA (c • x) v i = c * P.corootPairing hA x v i := by
  simp [corootPairing]

/-- `⟨w x, β^∨⟩ = ⟨x, (w⁻¹ β)^∨⟩`. -/
lemma corootPairing_apply (w v : P.weylGroup hA) (x : Dual K H) (i : ι) :
    P.corootPairing hA ((w : Dual K H ≃ₗ[K] Dual K H) x) v i =
      P.corootPairing hA x (w⁻¹ * v) i := by
  rw [corootPairing, corootPairing, show (w⁻¹ * v)⁻¹ = v⁻¹ * w by group]
  rfl

/-- `⟨u x, αⱼ^∨⟩ = ⟨x, (u⁻¹ αⱼ)^∨⟩`. -/
lemma apply_coroot_eq_corootPairing (u : P.weylGroup hA) (x : Dual K H) (j : ι) :
    (u : Dual K H ≃ₗ[K] Dual K H) x (P.coroot j) = P.corootPairing hA x u⁻¹ j := by
  rw [corootPairing, _root_.inv_inv]

lemma inv_apply_apply (u : P.weylGroup hA) (x : Dual K H) :
    ((u⁻¹ : P.weylGroup hA) : Dual K H ≃ₗ[K] Dual K H) ((u : Dual K H ≃ₗ[K] Dual K H) x) = x := by
  rw [← LinearEquiv.mul_apply, ← Subgroup.coe_mul, _root_.inv_mul_cancel]
  rfl

lemma apply_inv_apply (u : P.weylGroup hA) (x : Dual K H) :
    (u : Dual K H ≃ₗ[K] Dual K H) (((u⁻¹ : P.weylGroup hA) : Dual K H ≃ₗ[K] Dual K H) x) = x := by
  rw [← LinearEquiv.mul_apply, ← Subgroup.coe_mul, _root_.mul_inv_cancel]
  rfl

/-- Elements of the root lattice pair integrally with all real coroots. -/
lemma exists_int_corootPairing_of_mem_rootLattice {μ : Dual K H} (hμ : μ ∈ P.rootLattice)
    (v : P.weylGroup hA) (i : ι) : ∃ z : ℤ, P.corootPairing hA μ v i = z :=
  P.exists_int_of_mem_rootLattice (P.apply_mem_rootLattice hA (v⁻¹).2 hμ) i

/-- `s_β x = x - ⟨x, β^∨⟩ β`. -/
lemma reflectionOf_apply' (v : P.weylGroup hA) (i : ι) (x : Dual K H) :
    (P.reflectionOf hA v i : Dual K H ≃ₗ[K] Dual K H) x =
      x - P.corootPairing hA x v i • (v : Dual K H ≃ₗ[K] Dual K H) (P.root i) :=
  P.reflectionOf_apply hA v i x

lemma reflectionOf_mul_self (v : P.weylGroup hA) (i : ι) :
    P.reflectionOf hA v i * P.reflectionOf hA v i = 1 := by
  have : (⟨P.reflection hA i, P.reflection_mem_weylGroup hA i⟩ : P.weylGroup hA) *
      ⟨P.reflection hA i, P.reflection_mem_weylGroup hA i⟩ = 1 :=
    Subtype.ext (P.reflection_mul_self hA i)
  simp only [reflectionOf]
  calc v * ⟨P.reflection hA i, _⟩ * v⁻¹ * (v * ⟨P.reflection hA i, _⟩ * v⁻¹)
      = v * (⟨P.reflection hA i, P.reflection_mem_weylGroup hA i⟩ *
          ⟨P.reflection hA i, P.reflection_mem_weylGroup hA i⟩) * v⁻¹ := by group
    _ = 1 := by rw [this, mul_one, mul_inv_cancel]

variable [DecidableEq ι] [CharZero K]

/-- `⟨x, (-β)^∨⟩ = -⟨x, β^∨⟩`, with `-v αᵢ = (v rᵢ) αᵢ`. -/
lemma corootPairing_mul_simple (x : Dual K H) (v : P.weylGroup hA) (i : ι) :
    P.corootPairing hA x (v * (P.coxeterSystem hA).simple i) i = -P.corootPairing hA x v i := by
  unfold corootPairing
  rw [Subgroup.coe_inv, Subgroup.coe_mul, _root_.mul_inv_rev, coxeterSystem_simple, reflection_inv,
    LinearEquiv.mul_apply, reflection_apply, Subgroup.coe_inv]
  simp [P.root_coroot_self hA]
  ring

lemma mul_simple_apply_root (v : P.weylGroup hA) (i : ι) :
    ((v * (P.coxeterSystem hA).simple i : P.weylGroup hA) : Dual K H ≃ₗ[K] Dual K H)
      (P.root i) = -(v : Dual K H ≃ₗ[K] Dual K H) (P.root i) := by
  simp only [Subgroup.coe_mul, coxeterSystem_simple, LinearEquiv.mul_apply, reflection_apply,
    P.root_coroot_self hA]
  rw [show P.root i - (2 : K) • P.root i = -P.root i by module, map_neg]

/-- Every real root is positive or negative. -/
lemma isPosRoot_or (v : P.weylGroup hA) (i : ι) :
    P.IsPosRoot hA v i ∨ P.IsPosRoot hA (v * (P.coxeterSystem hA).simple i) i := by
  rcases P.apply_root_nonneg_or_nonpos hA v.2 i with ⟨k, hk, h⟩ | ⟨k, hk, h⟩
  · exact Or.inl ⟨k, hk, h⟩
  · exact Or.inr ⟨k, hk, by rw [mul_simple_apply_root, h, neg_neg]⟩

/-- No real root is both positive and negative. -/
lemma not_isPosRoot_and {v : P.weylGroup hA} {i : ι} (h₁ : P.IsPosRoot hA v i)
    (h₂ : P.IsPosRoot hA (v * (P.coxeterSystem hA).simple i) i) : False := by
  obtain ⟨k, hk, hk'⟩ := h₁
  obtain ⟨l, hl, hl'⟩ := h₂
  rw [mul_simple_apply_root] at hl'
  have h0 := P.eq_zero_of_mem_closure_of_neg_mem
    ((P.mem_closure_range_root_iff).mpr ⟨k, hk, hk'.symm⟩)
    ((P.mem_closure_range_root_iff).mpr ⟨l, hl, hl'.symm⟩)
  rw [LinearEquiv.map_eq_zero_iff] at h0
  exact P.linearIndependent_root.ne_zero i h0

lemma isPosRoot_iff_not_isRightDescent {v : P.weylGroup hA} {i : ι} :
    P.IsPosRoot hA v i ↔ ¬(P.coxeterSystem hA).IsRightDescent v i := by
  rw [not_isRightDescent_coxeterSystem_iff]
  rfl

/-! ### The exchange property for reflections in positive roots -/

/-- If `β = v αᵢ` is a positive root and `w β < 0`, then `ℓ(w s_β) < ℓ(w)` (the exchange
condition for the reflection `s_β`, deduced from
`Matrix.Realization.exists_mul_reflection_eq_eraseIdx` applied to a reduced word for `w` followed
by a reduced word for `v`). -/
theorem length_mul_reflectionOf_lt {w v : P.weylGroup hA} {i : ι} (hv : P.IsPosRoot hA v i)
    (hw : ¬P.IsPosRoot hA (w * v) i) :
    (P.coxeterSystem hA).length (w * P.reflectionOf hA v i) <
      (P.coxeterSystem hA).length w := by
  classical
  obtain ⟨ω, hωr, rfl⟩ := (P.coxeterSystem hA).exists_isReduced w
  obtain ⟨ν, hνr, rfl⟩ := (P.coxeterSystem hA).exists_isReduced v
  obtain ⟨k, hk, hk'⟩ := (isPosRoot_or _ i).resolve_left hw
  rw [mul_simple_apply_root] at hk'
  have hlin : (((P.coxeterSystem hA).wordProd (ω ++ ν) : P.weylGroup hA) :
      Dual K H ≃ₗ[K] Dual K H) = ((ω ++ ν).map (P.reflection hA)).prod :=
    P.coxeterSystem_wordProd hA _
  have hprod : ((ω ++ ν).map (P.reflection hA)).prod (P.root i) = -P.rootOf k := by
    rw [← hlin, (P.coxeterSystem hA).wordProd_append, ← hk', neg_neg]
  obtain ⟨s, hs, hse⟩ := P.exists_mul_reflection_eq_eraseIdx hA (ω ++ ν) hk hprod
  rw [← hlin, ← P.coxeterSystem_wordProd hA, (P.coxeterSystem hA).wordProd_append] at hse
  have hr : P.reflectionOf hA ((P.coxeterSystem hA).wordProd ν) i =
      (P.coxeterSystem hA).wordProd ν * (P.coxeterSystem hA).simple i *
        ((P.coxeterSystem hA).wordProd ν)⁻¹ := by
    simp only [reflectionOf]
    congr 2
  by_cases hsω : s < ω.length
  · rw [List.eraseIdx_append_of_lt_length hsω] at hse
    have h3 : (P.coxeterSystem hA).wordProd ω * (P.coxeterSystem hA).wordProd ν *
        (P.coxeterSystem hA).simple i =
        (P.coxeterSystem hA).wordProd (ω.eraseIdx s) * (P.coxeterSystem hA).wordProd ν := by
      apply Subtype.ext
      rw [Subgroup.coe_mul _ _ ((P.coxeterSystem hA).simple i), coxeterSystem_simple, hse,
        (P.coxeterSystem hA).wordProd_append]
    rw [hr, ← mul_assoc, ← mul_assoc, h3, mul_assoc, _root_.mul_inv_cancel, mul_one]
    calc (P.coxeterSystem hA).length ((P.coxeterSystem hA).wordProd (ω.eraseIdx s))
        ≤ (ω.eraseIdx s).length := (P.coxeterSystem hA).length_wordProd_le _
      _ < ω.length := by rw [List.length_eraseIdx_of_lt hsω]; omega
      _ = (P.coxeterSystem hA).length ((P.coxeterSystem hA).wordProd ω) := hωr.symm
  · exfalso
    rw [not_lt] at hsω
    rw [List.eraseIdx_append_of_length_le hsω] at hse
    have hs' : s - ω.length < ν.length := by
      simp only [List.length_append] at hs; omega
    have h3 : (P.coxeterSystem hA).wordProd ω * ((P.coxeterSystem hA).wordProd ν *
        (P.coxeterSystem hA).simple i) =
        (P.coxeterSystem hA).wordProd ω *
          (P.coxeterSystem hA).wordProd (ν.eraseIdx (s - ω.length)) := by
      apply Subtype.ext
      rw [← mul_assoc, Subgroup.coe_mul _ _ ((P.coxeterSystem hA).simple i), coxeterSystem_simple,
        hse, (P.coxeterSystem hA).wordProd_append]
    have heq := mul_left_cancel h3
    have hdesc : (P.coxeterSystem hA).IsRightDescent ((P.coxeterSystem hA).wordProd ν) i := by
      unfold IsRightDescent
      rw [heq]
      calc (P.coxeterSystem hA).length
            ((P.coxeterSystem hA).wordProd (ν.eraseIdx (s - ω.length)))
          ≤ (ν.eraseIdx (s - ω.length)).length := (P.coxeterSystem hA).length_wordProd_le _
        _ < ν.length := by rw [List.length_eraseIdx_of_lt hs']; omega
        _ = (P.coxeterSystem hA).length ((P.coxeterSystem hA).wordProd ν) := hνr.symm
    exact (isPosRoot_iff_not_isRightDescent.mp hv) hdesc

/-! ### Elements of `Q` in the closed fundamental alcove -/

/-- If `μ ∈ Q` satisfies `⟨μ, β^∨⟩ ∈ {0, 1}` for every positive root `β`, then `μ = 0`: the only
point of the root lattice in the closure of the fundamental alcove is `0`. In the `W`-orbit of `μ`
pick `ν = ∑ kⱼ αⱼ` with `∑ |kⱼ|` minimal; since `⟨ν, αⱼ^∨⟩ ∈ {-1, 0, 1}`, minimality forces
`kⱼ ⟨ν, αⱼ^∨⟩ ≤ 0` for all `j` (otherwise `rⱼ ν = ν ∓ αⱼ` is smaller), so
`kᵀ diag(d) A k = ∑ kⱼ dⱼ ⟨ν, αⱼ^∨⟩ ≤ 0` and `k = 0` by positive definiteness. (Our own
argument.) -/
theorem eq_zero_of_mem_rootLattice_of_corootPairing (hF : A.IsFiniteCartan) {μ : Dual K H}
    (hμ : μ ∈ P.rootLattice)
    (h : ∀ v i, P.IsPosRoot hA v i →
      P.corootPairing hA μ v i = 0 ∨ P.corootPairing hA μ v i = 1) :
    μ = 0 := by
  classical
  have hall : ∀ v i, P.corootPairing hA μ v i = -1 ∨ P.corootPairing hA μ v i = 0 ∨
      P.corootPairing hA μ v i = 1 := by
    intro v i
    rcases isPosRoot_or v i with hv | hv
    · rcases h v i hv with h0 | h1
      · exact Or.inr (Or.inl h0)
      · exact Or.inr (Or.inr h1)
    · have hm := corootPairing_mul_simple μ v i
      rcases h _ i hv with h0 | h1
      · exact Or.inr (Or.inl (by linear_combination hm - h0))
      · exact Or.inl (by linear_combination hm - h1)
  -- on the orbit, `⟨ν, αⱼ^∨⟩ = (A k)ⱼ ∈ {-1, 0, 1}`
  have horb : ∀ (u : P.weylGroup hA) (k : ι → ℤ), (u : Dual K H ≃ₗ[K] Dual K H) μ = P.rootOf k →
      ∀ j, (A *ᵥ k) j = -1 ∨ (A *ᵥ k) j = 0 ∨ (A *ᵥ k) j = 1 := by
    intro u k huk j
    have e := apply_coroot_eq_corootPairing u μ j
    rw [huk, rootOf_apply_coroot] at e
    rcases hall u⁻¹ j with h' | h' | h' <;> rw [← e] at h'
    · exact Or.inl (by exact_mod_cast h')
    · exact Or.inr (Or.inl (by exact_mod_cast h'))
    · exact Or.inr (Or.inr (by exact_mod_cast h'))
  have hex : ∃ n : ℕ, ∃ u : P.weylGroup hA, ∃ k : ι → ℤ,
      (u : Dual K H ≃ₗ[K] Dual K H) μ = P.rootOf k ∧ ∑ j, (k j).natAbs = n := by
    obtain ⟨k, hk⟩ := (P.mem_rootLattice).mp hμ
    exact ⟨_, 1, k, by rw [OneMemClass.coe_one, LinearEquiv.coe_one, id, hk], rfl⟩
  obtain ⟨u, k, huk, hkn⟩ := Nat.find_spec hex
  have hkey : ∀ j, (A *ᵥ k) j * k j ≤ 0 := by
    intro j
    by_contra hlt
    push Not at hlt
    have hj := horb u k huk j
    set k' : ι → ℤ := k - (A *ᵥ k) j • Pi.single j 1 with hk'
    have hu' : (((P.coxeterSystem hA).simple j * u : P.weylGroup hA) :
        Dual K H ≃ₗ[K] Dual K H) μ = P.rootOf k' := by
      rw [Subgroup.coe_mul, coxeterSystem_simple, LinearEquiv.mul_apply, huk, reflection_rootOf]
    have hle := Nat.find_min' hex ⟨_, k', hu', rfl⟩
    have hlt' : ∑ l, (k' l).natAbs < ∑ l, (k l).natAbs := by
      refine Finset.sum_lt_sum (fun l _ ↦ ?_) ⟨j, Finset.mem_univ _, ?_⟩
      · by_cases hl : l = j
        · subst hl
          simp only [hk', Pi.sub_apply, Pi.smul_apply, Pi.single_eq_same, smul_eq_mul, mul_one]
          rcases hj with h' | h' | h' <;> rw [h'] at hlt ⊢ <;> omega
        · simp [hk', hl]
      · simp only [hk', Pi.sub_apply, Pi.smul_apply, Pi.single_eq_same, smul_eq_mul, mul_one]
        rcases hj with h' | h' | h' <;> rw [h'] at hlt ⊢ <;> omega
    omega
  obtain ⟨d, hdpos, hpos⟩ := hF.exists_posDef
  have hq : star k ⬝ᵥ (diagonal d * A) *ᵥ k = ∑ j, k j * (d j * (A *ᵥ k) j) := by
    simp [dotProduct, ← mulVec_mulVec, mulVec_diagonal]
  have hk0 : k = 0 := by
    by_contra hne
    have h1 := hpos.dotProduct_mulVec_pos hne
    rw [hq] at h1
    have h2 : ∑ j, k j * (d j * (A *ᵥ k) j) ≤ 0 := Finset.sum_nonpos fun j _ ↦ by
      have := hkey j
      have := hdpos j
      nlinarith
    omega
  rw [hk0, map_zero, LinearEquiv.map_eq_zero_iff] at huk
  exact huk

end General


/-! ### Rational weights: the affine Weyl group `W ⋉ Q` -/

section Rational

variable {ι H : Type*} [Fintype ι] [AddCommGroup H] [Module ℚ H]
  {A : Matrix ι ι ℤ} {P : Realization A ℚ H} {hA : A.IsGeneralizedCartan}

lemma corootPairing_sum {α : Type*} (s : Finset α) (f : α → Dual ℚ H) (v : P.weylGroup hA)
    (i : ι) : P.corootPairing hA (∑ a ∈ s, f a) v i = ∑ a ∈ s, P.corootPairing hA (f a) v i := by
  simp [corootPairing, map_sum]

lemma natCast_smul_mem_rootLattice {μ : Dual ℚ H} (hμ : μ ∈ P.rootLattice) (N : ℕ) :
    (N : ℚ) • μ ∈ P.rootLattice := by
  rw [Nat.cast_smul_eq_nsmul]
  exact nsmul_mem hμ N

/-- `‖a - t β‖² = ‖a‖² + 2 dᵢ t (t - ⟨a, β^∨⟩)` for `β = v αᵢ`. -/
lemma bilinForm_sub_smul {B : LinearMap.BilinForm ℚ (Dual ℚ H)} {d : ι → ℤ}
    (hBs : ∀ x y, B x y = B y x)
    (hBr : ∀ x (v : P.weylGroup hA) i,
      B x ((v : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (P.root i)) = d i * P.corootPairing hA x v i)
    (a : Dual ℚ H) (t : ℚ) (v : P.weylGroup hA) (i : ι) :
    B (a - t • (v : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (P.root i))
        (a - t • (v : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (P.root i)) =
      B a a + 2 * d i * t * (t - P.corootPairing hA a v i) := by
  have h1 := hBr a v i
  have h2 := hBr ((v : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (P.root i)) v i
  have h3 : P.corootPairing hA ((v : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (P.root i)) v i = 2 := by
    rw [corootPairing, ← LinearEquiv.mul_apply, ← Subgroup.coe_mul, _root_.inv_mul_cancel]
    exact P.root_coroot_self hA i
  rw [h3] at h2
  simp only [map_sub, map_smul, LinearMap.sub_apply, LinearMap.smul_apply, smul_eq_mul]
  rw [hBs ((v : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (P.root i)) a, h1, h2]
  ring

variable [DecidableEq ι] [FiniteDimensional ℚ H]

/-- The `W`-invariant form attached to a finite-type Cartan matrix, normalized by
`(x | v αᵢ) = dᵢ ⟨x, (v αᵢ)^∨⟩` with `diag(d) A` positive definite. -/
lemma exists_bilinForm (hF : A.IsFiniteCartan) :
    ∃ (B : LinearMap.BilinForm ℚ (Dual ℚ H)) (d : ι → ℤ), (∀ i, 0 < d i) ∧
      (∀ x y, B x y = B y x) ∧
      (∀ x (v : P.weylGroup hA) i,
        B x ((v : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (P.root i)) = d i * P.corootPairing hA x v i) ∧
      (∀ k x, B (P.rootOf k) x = ∑ i, ((k i * d i : ℤ) : ℚ) * x (P.coroot i)) ∧
      (∀ k, ∃ n : ℕ, B (P.rootOf k) (P.rootOf k) = n) := by
  obtain ⟨d, hdpos, hpos⟩ := hF.exists_posDef
  have hsymm : (diagonal d * A).IsSymm := by
    simpa [IsHermitian, IsSymm] using hpos.isHermitian
  set S := Symmetrization.ofDiagonal d hdpos hsymm
  have hroot := P.dualBilinForm_ofDiagonal_rootOf d hdpos hsymm
  refine ⟨P.dualBilinForm S, d, hdpos, fun x y ↦ (P.isSymm_dualBilinForm S).eq x y, ?_, hroot, ?_⟩
  · intro x v i
    have e : ((v⁻¹ : P.weylGroup hA) : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H)
        ((v : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (P.root i)) = P.root i := by
      rw [← LinearEquiv.mul_apply, ← Subgroup.coe_mul, _root_.inv_mul_cancel]
      rfl
    rw [← P.dualBilinForm_weylGroup hA S (v⁻¹).2 x, e, dualBilinForm_root_right]
    simp only [S, Symmetrization.ofDiagonal, corootPairing, Rat.cast_id]
    have hi : (d i : ℚ) ≠ 0 := by exact_mod_cast (hdpos i).ne'
    field_simp
  · intro k
    have hnn : 0 ≤ ∑ i, k i * (d i * (A *ᵥ k) i) := by
      have hq : star k ⬝ᵥ (diagonal d * A) *ᵥ k = ∑ i, k i * (d i * (A *ᵥ k) i) := by
        simp [dotProduct, ← mulVec_mulVec, mulVec_diagonal]
      by_cases hk : k = 0
      · simp [hk]
      · rw [← hq]; exact (hpos.dotProduct_mulVec_pos hk).le
    refine ⟨(∑ i, k i * (d i * (A *ᵥ k) i)).toNat, ?_⟩
    rw [hroot]
    simp_rw [rootOf_apply_coroot]
    have : (((∑ i, k i * (d i * (A *ᵥ k) i)).toNat : ℤ) : ℚ) =
        ((∑ i, k i * (d i * (A *ᵥ k) i) : ℤ) : ℚ) := by rw [Int.toNat_of_nonneg hnn]
    rw [Int.cast_natCast] at this
    rw [this]
    push_cast
    exact Finset.sum_congr rfl fun i _ ↦ by ring

/-- A strictly dominant weight pairs positively with the coroot of every positive root. -/
lemma corootPairing_pos (hF : A.IsFiniteCartan) {x : Dual ℚ H} (hx : ∀ j, 0 < x (P.coroot j))
    {v : P.weylGroup hA} {i : ι} (hv : P.IsPosRoot hA v i) : 0 < P.corootPairing hA x v i := by
  obtain ⟨B, d, hd, hBs, hBr, hBk, -⟩ := exists_bilinForm (P := P) (hA := hA) hF
  obtain ⟨k, hk, hvk⟩ := hv
  have h := hBr x v i
  rw [hvk, hBs, hBk] at h
  have hk0 : k ≠ 0 := by
    rintro rfl
    rw [map_zero, LinearEquiv.map_eq_zero_iff] at hvk
    exact P.linearIndependent_root.ne_zero i hvk
  obtain ⟨j, hj⟩ := Function.ne_iff.mp hk0
  have hkj : 0 < k j := lt_of_le_of_ne (hk j) (Ne.symm hj)
  have hsum : 0 < ∑ l, ((k l * d l : ℤ) : ℚ) * x (P.coroot l) := by
    refine Finset.sum_pos' (fun l _ ↦ mul_nonneg ?_ (hx l).le) ⟨j, Finset.mem_univ _, ?_⟩
    · exact_mod_cast mul_nonneg (hk l) (hd l).le
    · exact mul_pos (by exact_mod_cast mul_pos hkj (hd j)) (hx j)
  rw [h] at hsum
  exact (mul_pos_iff_of_pos_left (by exact_mod_cast hd i)).mp hsum

/-- Every rational weight has a positive integer multiple in the root lattice. -/
lemma exists_nsmul_mem_rootLattice (hF : A.IsFiniteCartan) (μ : Dual ℚ H) :
    ∃ N : ℕ, 0 < N ∧ (N : ℚ) • μ ∈ P.rootLattice := by
  classical
  have hμ : μ ∈ Submodule.span ℚ (Set.range P.root) := by
    rw [P.span_root_eq_top_of_isFiniteCartan hF]; exact Submodule.mem_top
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun ℚ).mp hμ
  refine ⟨∏ i, (c i).den, Finset.prod_pos fun i _ ↦ (c i).den_pos, ?_⟩
  have hdiv : ∀ i, ∃ m : ℤ, ((∏ j, (c j).den : ℕ) : ℚ) * c i = m := by
    intro i
    obtain ⟨m, hm⟩ := Finset.dvd_prod_of_mem (fun j ↦ (c j).den) (Finset.mem_univ i)
    refine ⟨m * (c i).num, ?_⟩
    rw [hm]
    push_cast
    rw [← Rat.mul_den_eq_num]
    ring
  choose m hm using hdiv
  refine (P.mem_rootLattice).mpr ⟨m, ?_⟩
  rw [rootOf_apply, ← hc, Finset.smul_sum]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  rw [smul_smul, hm]

/-- A point `z₀` of the open fundamental alcove: `0 < ⟨z₀, β^∨⟩ < 1` for every positive root. -/
lemma exists_mem_openAlcove (hF : A.IsFiniteCartan) :
    ∃ z₀ : Dual ℚ H, ∀ v i, P.IsPosRoot hA v i →
      0 < P.corootPairing hA z₀ v i ∧ P.corootPairing hA z₀ v i < 1 := by
  have : Finite (P.weylGroup hA) := P.finite_weylGroup hF
  obtain ⟨M, hM⟩ := (Set.finite_range fun p : P.weylGroup hA × ι ↦
    P.corootPairing hA P.rho p.1 p.2).bddAbove
  refine ⟨(max M 0 + 1)⁻¹ • P.rho, fun v i hv ↦ ?_⟩
  have hρ := corootPairing_pos hF (x := P.rho) (fun j ↦ by rw [rho_coroot]; exact one_pos) hv
  have hle : P.corootPairing hA P.rho v i ≤ max M 0 :=
    (hM ⟨(v, i), rfl⟩).trans (le_max_left _ _)
  rw [corootPairing_smul]
  have hM1 : 0 < max M 0 + 1 := by have := le_max_right M 0; linarith
  refine ⟨mul_pos (inv_pos.mpr hM1) hρ, ?_⟩
  rw [inv_mul_lt_iff₀ hM1]
  linarith

/-- **The closed fundamental alcove meets every orbit of `W ⋉ Q`.** For every rational weight
`x` there are `u ∈ W` and `δ ∈ Q` with `0 ≤ ⟨u x + δ, β^∨⟩ ≤ 1` for every positive root `β`.
Among the points of the orbit (a discrete set) choose `y` closest to a point `z₀` of the open
alcove for the invariant form; if `⟨y, β^∨⟩ < 0` or `> 1`, the affine reflection of `y` in the
hyperplane `⟨·, β^∨⟩ = 0`, resp. `= 1`, is closer to `z₀`. (Standard argument, written out
here; cf. Humphreys, *Reflection groups and Coxeter groups*, Ch. 4.) -/
theorem exists_mem_closedAlcove (hF : A.IsFiniteCartan) (x : Dual ℚ H) :
    ∃ u : P.weylGroup hA, ∃ δ ∈ P.rootLattice, ∀ v i, P.IsPosRoot hA v i →
      0 ≤ P.corootPairing hA ((u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ) v i ∧
        P.corootPairing hA ((u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ) v i ≤ 1 := by
  classical
  obtain ⟨B, d, hd, hBs, hBr, -, hBn⟩ := exists_bilinForm (P := P) (hA := hA) hF
  obtain ⟨z₀, hz₀α⟩ := exists_mem_openAlcove (P := P) (hA := hA) hF
  obtain ⟨N₁, hN₁, hxN⟩ := exists_nsmul_mem_rootLattice (P := P) hF x
  obtain ⟨N₂, hN₂, hzN⟩ := exists_nsmul_mem_rootLattice (P := P) hF z₀
  have hNx : ((N₁ * N₂ : ℕ) : ℚ) • x ∈ P.rootLattice := by
    rw [Nat.cast_mul, mul_comm, mul_smul]
    exact natCast_smul_mem_rootLattice hxN N₂
  have hNz : ((N₁ * N₂ : ℕ) : ℚ) • z₀ ∈ P.rootLattice := by
    rw [Nat.cast_mul, mul_smul]
    exact natCast_smul_mem_rootLattice hzN N₁
  have hNpos : 0 < N₁ * N₂ := Nat.mul_pos hN₁ hN₂
  generalize N₁ * N₂ = N at hNx hNz hNpos
  -- the orbit of `x` under `W ⋉ Q`
  let O : Dual ℚ H → Prop := fun y ↦
    ∃ u : P.weylGroup hA, ∃ δ ∈ P.rootLattice, y = (u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ
  have hval : ∀ y, O y → ∃ n : ℕ, B ((N : ℚ) • (y - z₀)) ((N : ℚ) • (y - z₀)) = n := by
    rintro y ⟨u, δ, hδ, rfl⟩
    have hmem : (N : ℚ) • ((u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ - z₀) ∈ P.rootLattice := by
      rw [smul_sub, smul_add, ← map_smul]
      exact sub_mem (add_mem (P.apply_mem_rootLattice hA u.2 hNx)
        (natCast_smul_mem_rootLattice hδ N)) hNz
    obtain ⟨k, hk⟩ := (P.mem_rootLattice).mp hmem
    rw [← hk]
    exact hBn k
  have hxO : O x := ⟨1, 0, zero_mem _, by simp⟩
  have hex : ∃ n : ℕ, ∃ y, O y ∧ B ((N : ℚ) • (y - z₀)) ((N : ℚ) • (y - z₀)) = n := by
    obtain ⟨n, hn⟩ := hval x hxO
    exact ⟨n, x, hxO, hn⟩
  obtain ⟨y, hyO, hyn⟩ := Nat.find_spec hex
  have hsq : ∀ a : Dual ℚ H, B ((N : ℚ) • a) ((N : ℚ) • a) = (N : ℚ) ^ 2 * B a a := fun a ↦ by
    simp only [map_smul, LinearMap.smul_apply, smul_eq_mul]; ring
  have hmin : ∀ y', O y' → B (y - z₀) (y - z₀) ≤ B (y' - z₀) (y' - z₀) := by
    intro y' hy'
    obtain ⟨n', hn'⟩ := hval y' hy'
    have hle : (Nat.find hex : ℚ) ≤ n' := by exact_mod_cast Nat.find_min' hex ⟨y', hy', hn'⟩
    rw [hsq] at hn'
    have hN0 : (0 : ℚ) < (N : ℚ) ^ 2 := by
      have : (0 : ℚ) < N := by exact_mod_cast hNpos
      positivity
    refine le_of_mul_le_mul_left ?_ hN0
    rw [← hsq, hyn, hn']
    exact hle
  obtain ⟨u, δ, hδ, rfl⟩ := hyO
  refine ⟨u, δ, hδ, fun v i hv ↦ ?_⟩
  obtain ⟨hz0, hz1⟩ := hz₀α v i hv
  -- the reflected points stay in the orbit
  have hO : ∀ n : ℤ, O ((u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ -
      (P.corootPairing hA ((u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ) v i - n) •
        (v : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (P.root i)) := by
    intro n
    refine ⟨P.reflectionOf hA v i * u,
      (P.reflectionOf hA v i : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) δ +
        (n : ℚ) • (v : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (P.root i), ?_, ?_⟩
    · obtain ⟨k, -, hk⟩ := hv
      refine add_mem (P.apply_mem_rootLattice hA (P.reflectionOf hA v i).2 hδ) ?_
      rw [hk, Int.cast_smul_eq_zsmul, ← map_zsmul]
      exact P.rootOf_mem_rootLattice _
    · rw [Subgroup.coe_mul, LinearEquiv.mul_apply, reflectionOf_apply', reflectionOf_apply',
        corootPairing_add]
      module
  have hstep : ∀ n : ℤ, 0 ≤ 2 * d i *
      (P.corootPairing hA ((u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ) v i - n) *
        (P.corootPairing hA z₀ v i - n) := by
    intro n
    have h := hmin _ (hO n)
    rw [sub_right_comm, bilinForm_sub_smul hBs hBr, corootPairing_sub] at h
    linarith
  have hdi : (0 : ℚ) < d i := by exact_mod_cast hd i
  constructor
  · by_contra hlt
    push Not at hlt
    have := hstep 0
    push_cast at this
    nlinarith [mul_pos (mul_pos hdi hz0) (neg_pos.mpr hlt)]
  · by_contra hlt
    push Not at hlt
    have := hstep 1
    push_cast at this
    nlinarith [mul_pos (mul_pos hdi (sub_pos.mpr hlt)) (sub_pos.mpr hz1)]

omit [FiniteDimensional ℚ H] in
/-- **No nontrivial element of `W ⋉ Q` fixes a point of the open fundamental alcove.** If
`0 < ⟨x, β^∨⟩ < 1` for all positive roots `β` and `w x - x ∈ Q`, then `w = 1`. Writing
`w x = x + γ`, the bounds force `⟨γ, β^∨⟩ ∈ {-1, 0}`, so `γ = 0`
(`Matrix.Realization.eq_zero_of_mem_rootLattice_of_corootPairing`), and `w` fixes the strictly
dominant `x`. (Our own argument.) -/
theorem eq_one_of_mem_openAlcove (hF : A.IsFiniteCartan) {x : Dual ℚ H}
    (hx : ∀ v i, P.IsPosRoot hA v i →
      0 < P.corootPairing hA x v i ∧ P.corootPairing hA x v i < 1)
    {w : P.weylGroup hA} (hw : w ∈ P.integralWeylGroup hA x) : w = 1 := by
  set γ := (w : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x - x with hγ
  have hγQ : γ ∈ P.rootLattice := hw
  have hwx : (w : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x = x + γ := by rw [hγ]; abel
  have hγ01 : ∀ v i, P.IsPosRoot hA v i →
      P.corootPairing hA (-γ) v i = 0 ∨ P.corootPairing hA (-γ) v i = 1 := by
    intro v i hv
    obtain ⟨n, hn⟩ := exists_int_corootPairing_of_mem_rootLattice hγQ v i
    have hb : -1 < P.corootPairing hA ((w : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x) v i ∧
        P.corootPairing hA ((w : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x) v i < 1 := by
      rw [corootPairing_apply]
      rcases isPosRoot_or (w⁻¹ * v) i with h | h
      · obtain ⟨h1, h2⟩ := hx _ i h
        constructor <;> linarith
      · obtain ⟨h1, h2⟩ := hx _ i h
        rw [corootPairing_mul_simple] at h1 h2
        constructor <;> linarith
    obtain ⟨h1, h2⟩ := hb
    obtain ⟨h3, h4⟩ := hx v i hv
    rw [hwx, corootPairing_add, hn] at h1 h2
    have hn1 : -2 < n := by exact_mod_cast (by linarith : (-2 : ℚ) < n)
    have hn2 : n < 1 := by exact_mod_cast (by linarith : (n : ℚ) < 1)
    rw [corootPairing_neg, hn]
    rcases (by omega : n = 0 ∨ n = -1) with rfl | rfl
    · left; simp
    · right; simp
  have hγ0 := eq_zero_of_mem_rootLattice_of_corootPairing hF (neg_mem hγQ) hγ01
  have hfix : (w : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x = x := by
    rw [neg_eq_zero, hγ, sub_eq_zero] at hγ0
    exact hγ0
  have hpos : ∀ j, 0 < x (P.coroot j) := fun j ↦ by
    have h1 : P.IsPosRoot hA 1 j :=
      ⟨Pi.single j 1, fun l ↦ by by_cases h : l = j <;> simp [h], by simp⟩
    simpa using (hx 1 j h1).1
  exact Subtype.ext (P.eq_one_of_apply_eq_self_of_forall_pos hA hpos w.2 hfix)

/-- **`W ⋉ Q` acts freely on generic rational weights.** If no root is integral for `x`
(`⟨x, β^∨⟩ ∉ ℤ` for all `β`), then `W_[x] = 1`. Move `x` into the closed fundamental alcove by
`W ⋉ Q` (`Matrix.Realization.exists_mem_closedAlcove`); genericity puts it in the open alcove,
and `Matrix.Realization.eq_one_of_mem_openAlcove` applies to the conjugate of `w`. -/
theorem eq_one_of_forall_not_isIntegralRoot (hF : A.IsFiniteCartan) {x : Dual ℚ H}
    (hx : ∀ v i, ¬P.IsIntegralRoot hA x v i) {w : P.weylGroup hA}
    (hw : w ∈ P.integralWeylGroup hA x) : w = 1 := by
  obtain ⟨u, δ, hδ, hy⟩ := exists_mem_closedAlcove (P := P) (hA := hA) hF x
  have hyo : ∀ v i, P.IsPosRoot hA v i →
      0 < P.corootPairing hA ((u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ) v i ∧
        P.corootPairing hA ((u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ) v i < 1 := by
    intro v i hv
    obtain ⟨h0, h1⟩ := hy v i hv
    obtain ⟨n, hn⟩ := exists_int_corootPairing_of_mem_rootLattice hδ v i
    have hne : ∀ m : ℤ, P.corootPairing hA ((u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ) v i ≠ m := by
      intro m hm
      apply hx (u⁻¹ * v) i
      refine ⟨m - n, ?_⟩
      change P.corootPairing hA x (u⁻¹ * v) i = _
      rw [corootPairing_add, hn, corootPairing_apply] at hm
      push_cast
      linarith
    exact ⟨lt_of_le_of_ne h0 fun h ↦ hne 0 (by rw [← h]; simp),
      lt_of_le_of_ne h1 fun h ↦ hne 1 (by rw [h]; simp)⟩
  have hw' : u * w * u⁻¹ ∈ P.integralWeylGroup hA ((u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ) := by
    rw [mem_integralWeylGroup]
    have e : ((u * w * u⁻¹ : P.weylGroup hA) : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H)
        ((u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ) - ((u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x + δ) =
        (u : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) ((w : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x - x) +
          (((u * w * u⁻¹ : P.weylGroup hA) : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) δ - δ) := by
      simp only [map_add, map_sub, Subgroup.coe_mul, LinearEquiv.mul_apply, inv_apply_apply]
      abel
    rw [e]
    exact add_mem (P.apply_mem_rootLattice hA u.2 hw)
      (sub_mem (P.apply_mem_rootLattice hA (u * w * u⁻¹).2 hδ) hδ)
  have h1 := eq_one_of_mem_openAlcove hF hyo hw'
  rwa [_root_.mul_inv_eq_one, mul_eq_left] at h1

/-- If `w ∈ W_[x]` maps every positive root integral for `x` to a positive root, then `w = 1`.
The average `ρ'` of the `⟨w⟩`-orbit of `ρ` is fixed by `w` and pairs positively with the
coroots of the integral positive roots; for small `ε > 0` the weight `x + ε ρ'` is generic and
`w ∈ W_[x + ε ρ']`, so `w = 1` by `Matrix.Realization.eq_one_of_forall_not_isIntegralRoot`.
(Our own argument.) -/
theorem eq_one_of_forall_isPosRoot (hF : A.IsFiniteCartan) {x : Dual ℚ H}
    {w : P.weylGroup hA} (hw : w ∈ P.integralWeylGroup hA x)
    (hpos : ∀ v i, P.IsPosRoot hA v i → P.IsIntegralRoot hA x v i →
      P.IsPosRoot hA (w * v) i) : w = 1 := by
  classical
  have : Finite (P.weylGroup hA) := P.finite_weylGroup hF
  have : Fintype (P.weylGroup hA) := Fintype.ofFinite _
  have hn : w ^ Fintype.card (P.weylGroup hA) = 1 := pow_card_eq_one
  have hn0 : 0 < Fintype.card (P.weylGroup hA) := Fintype.card_pos
  generalize Fintype.card (P.weylGroup hA) = n at hn hn0
  let g : ℕ → Dual ℚ H := fun m ↦ (((w⁻¹) ^ m : P.weylGroup hA) : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) P.rho
  set ρ' : Dual ℚ H := ∑ m ∈ Finset.range n, g m with hρ'
  have hfix : (w : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) ρ' = ρ' := by
    have hg : ∀ m, ((w⁻¹ : P.weylGroup hA) : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (g m) = g (m + 1) := by
      intro m
      simp only [g, pow_succ', Subgroup.coe_mul, LinearEquiv.mul_apply]
    have hgn : g n = g 0 := by simp only [g, inv_pow, hn, inv_one, pow_zero]
    have h1 : ((w⁻¹ : P.weylGroup hA) : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) ρ' = ρ' := by
      rw [hρ', map_sum]
      simp_rw [hg]
      have e1 := Finset.sum_range_succ' g n
      have e2 := Finset.sum_range_succ g n
      rw [hgn] at e2
      exact add_right_cancel (e1.symm.trans e2)
    calc (w : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) ρ' =
        (w : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (((w⁻¹ : P.weylGroup hA) : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) ρ') := by
          rw [h1]
      _ = ρ' := apply_inv_apply w ρ'
  have hiter : ∀ m : ℕ, ∀ v i, P.IsPosRoot hA v i → P.IsIntegralRoot hA x v i →
      P.IsPosRoot hA (w ^ m * v) i ∧ P.IsIntegralRoot hA x (w ^ m * v) i := by
    intro m
    induction m with
    | zero => intro v i h1 h2; simpa using ⟨h1, h2⟩
    | succ m ih =>
      intro v i h1 h2
      obtain ⟨h3, h4⟩ := ih v i h1 h2
      rw [pow_succ', mul_assoc]
      exact ⟨hpos _ i h3 h4, P.isIntegralRoot_mul hA hw h4⟩
  have hρpos : ∀ v i, P.IsPosRoot hA v i → P.IsIntegralRoot hA x v i →
      0 < P.corootPairing hA ρ' v i := by
    intro v i h1 h2
    rw [hρ', corootPairing_sum]
    refine Finset.sum_pos (fun m _ ↦ ?_) (Finset.nonempty_range_iff.mpr hn0.ne')
    simp only [g]
    rw [corootPairing_apply, inv_pow, _root_.inv_inv]
    exact corootPairing_pos hF (fun j ↦ by rw [rho_coroot]; exact one_pos) (hiter m v i h1 h2).1
  have hgen : ∀ᶠ ε in 𝓝[>] (0 : ℚ), ∀ (v : P.weylGroup hA) (i : ι),
      ¬∃ z : ℤ, P.corootPairing hA x v i + ε * P.corootPairing hA ρ' v i = z := by
    rw [Filter.eventually_all]
    intro v
    rw [Filter.eventually_all]
    intro i
    apply Rat.eventually_not_exists_int_add_mul
    by_cases hint : ∃ z : ℤ, P.corootPairing hA x v i = z
    · right
      rcases isPosRoot_or v i with h | h
      · exact (hρpos v i h hint).ne'
      · have hint' : P.IsIntegralRoot hA x (v * (P.coxeterSystem hA).simple i) i := by
          obtain ⟨z, hz⟩ := hint
          refine ⟨-z, ?_⟩
          change P.corootPairing hA x _ i = _
          rw [corootPairing_mul_simple, hz]
          push_cast
          ring
        have := hρpos _ i h hint'
        rw [corootPairing_mul_simple] at this
        linarith
    · left
      exact hint
  obtain ⟨ε, hε, -⟩ := (hgen.and self_mem_nhdsWithin).exists
  have hc : ∀ v i, ¬P.IsIntegralRoot hA (x + ε • ρ') v i := by
    rintro v i ⟨z, hz⟩
    change P.corootPairing hA (x + ε • ρ') v i = z at hz
    rw [corootPairing_add, corootPairing_smul] at hz
    exact hε v i ⟨z, hz⟩
  have hwc : w ∈ P.integralWeylGroup hA (x + ε • ρ') := by
    rw [mem_integralWeylGroup]
    have e : (w : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) (x + ε • ρ') - (x + ε • ρ') =
        (w : Dual ℚ H ≃ₗ[ℚ] Dual ℚ H) x - x := by
      rw [map_add, map_smul, hfix]
      abel
    rw [e]
    exact hw
  exact eq_one_of_forall_not_isIntegralRoot hF hc hwc

/-- **Humphreys, GSM 94, Thm. 3.4 (b), for rational weights.** For a Cartan matrix of finite type
and a weight `x` over `ℚ`, every element of the integral Weyl group `W_[x]` is a product of
reflections in roots integral for `x`. By induction on the length: if some positive integral
root `β` has `w β < 0`, then `w s_β ∈ W_[x]` is shorter
(`Matrix.Realization.length_mul_reflectionOf_lt`); otherwise `w = 1`
(`Matrix.Realization.eq_one_of_forall_isPosRoot`). -/
theorem integralWeylGroup_le_integralReflectionGroup_of_rat (hF : A.IsFiniteCartan)
    (x : Dual ℚ H) : P.integralWeylGroup hA x ≤ P.integralReflectionGroup hA x := by
  intro w hw
  induction hlen : (P.coxeterSystem hA).length w using Nat.strong_induction_on generalizing w with
  | _ n ih =>
  by_cases hex : ∃ v i, P.IsPosRoot hA v i ∧ P.IsIntegralRoot hA x v i ∧
      ¬P.IsPosRoot hA (w * v) i
  · obtain ⟨v, i, hv, hint, hneg⟩ := hex
    have hs : P.reflectionOf hA v i ∈ P.integralWeylGroup hA x :=
      (P.reflectionOf_mem_integralWeylGroup_iff hA v i).mpr hint
    have h' := ih _ (hlen ▸ length_mul_reflectionOf_lt hv hneg) (mul_mem hw hs) rfl
    have e : w = w * P.reflectionOf hA v i * P.reflectionOf hA v i := by
      rw [mul_assoc, reflectionOf_mul_self, mul_one]
    rw [e]
    exact mul_mem h' (Subgroup.subset_closure ⟨v, i, hint, rfl⟩)
  · push Not at hex
    rw [eq_one_of_forall_isPosRoot hF hw hex]
    exact one_mem _

/-- **Humphreys, GSM 94, Thm. 3.4 (b), for rational weights**: `W_[x]` is generated by the
reflections in the roots integral for `x`. -/
theorem integralWeylGroup_eq_integralReflectionGroup_of_rat (hF : A.IsFiniteCartan)
    (x : Dual ℚ H) : P.integralWeylGroup hA x = P.integralReflectionGroup hA x :=
  le_antisymm (integralWeylGroup_le_integralReflectionGroup_of_rat hF x)
    (P.integralReflectionGroup_le hA x)

end Rational

end Matrix.Realization
