/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.LinearAlgebra.Matrix.Cartan.IntegralWeylGroupAntidominant
import LieLean.LinearAlgebra.Matrix.Cartan.WeylGroupForm

/-!
# Facet exclusion for non-integral weights (root-datum form)

Let `A` be a Cartan matrix of finite type with a realization over a field `K` of characteristic
zero. For a weight `b` whose pairings with the coroots of the positive roots integral for `b` are
`≤ 0`, every `w b - b` with `w ∈ W_[b]` is a nonnegative integral combination of positive roots
integral for `b` (`Matrix.Realization.apply_sub_mem_closure_integralPosRoots`). With this, the
norm argument for facet exclusion (`Matrix.Realization.apply_eq_of_add_eq_apply` for integral
weights) extends to arbitrary weights and the integral Weyl group: this is the root-datum core of
Humphreys, GSM 94, Lemma 7.5 (`Matrix.Realization.apply_eq_of_add_eq_apply_integralWeylGroup`).

All comparisons are made between integers (the pairings of `a`, `b` with integral coroots), so no
order on `K` and no auxiliary weight `λ♮` in the real span of the integral roots are needed; the
argument is our own (Humphreys proves Lemma 7.5 by induction on the distance between chambers of
`W_[λ]`).

## References

* J. E. Humphreys, *Representations of semisimple Lie algebras in the BGG category 𝒪*, GSM 94,
  AMS 2008, §7.4, Lemma 7.5.
-/

noncomputable section

open Module CoxeterSystem

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [CharZero K] [AddCommGroup H]
  [Module K H] {A : Matrix ι ι ℤ} {P : Realization A K H} (hF : A.IsFiniteCartan)

variable (P) in
/-- The additive monoid generated by the positive roots integral for `b`. -/
def integralPosRootCone (hA : A.IsGeneralizedCartan) (b : Dual K H) : AddSubmonoid (Dual K H) :=
  AddSubmonoid.closure {x | ∃ v i, P.IsPosRoot hA v i ∧ P.IsIntegralRoot hA b v i ∧
    (v : Dual K H ≃ₗ[K] Dual K H) (P.root i) = x}

/-- If `⟨b, β^∨⟩ ≤ 0` for the positive roots `β` integral for `b`, then `w b - b` lies in the
cone spanned by the positive integral roots, for every `w ∈ W_[b]` (the refinement of
`Matrix.Realization.exists_nonneg_apply_sub_eq_rootOf` with the same induction). -/
theorem apply_sub_mem_integralPosRootCone {b : Dual K H}
    (hb : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i → ∀ n : ℤ,
      P.corootPairing hF.isGeneralizedCartan b v i = n → n ≤ 0)
    {w : P.weylGroup hF.isGeneralizedCartan}
    (hw : w ∈ P.integralWeylGroup hF.isGeneralizedCartan b) :
    (w : Dual K H ≃ₗ[K] Dual K H) b - b ∈ P.integralPosRootCone hF.isGeneralizedCartan b := by
  induction hlen : (P.coxeterSystem hF.isGeneralizedCartan).length w
    using Nat.strong_induction_on generalizing w with
  | _ n ih =>
  by_cases hex : ∃ v i, P.IsPosRoot hF.isGeneralizedCartan v i ∧
      P.IsIntegralRoot hF.isGeneralizedCartan b v i ∧
        ¬P.IsPosRoot hF.isGeneralizedCartan (w * v) i
  · obtain ⟨v, i, hv, ⟨z, hz⟩, hneg⟩ := hex
    have hs : P.reflectionOf hF.isGeneralizedCartan v i ∈
        P.integralWeylGroup hF.isGeneralizedCartan b :=
      (P.reflectionOf_mem_integralWeylGroup_iff _ v i).mpr ⟨z, hz⟩
    have hk := ih _ (hlen ▸ length_mul_reflectionOf_lt hv hneg) (mul_mem hw hs) rfl
    have hpos := (isPosRoot_or (w * v) i).resolve_left hneg
    have hint : P.IsIntegralRoot hF.isGeneralizedCartan b
        (w * v * (P.coxeterSystem hF.isGeneralizedCartan).simple i) i := by
      have h1 := P.isIntegralRoot_mul _ hw ⟨z, hz⟩
      obtain ⟨z', hz'⟩ := h1
      change P.corootPairing _ b (w * v) i = _ at hz'
      refine ⟨-z', ?_⟩
      change P.corootPairing _ b _ i = _
      rw [corootPairing_mul_simple, hz']
      push_cast
      ring
    have hz0 := hb v i hv z hz
    have hβ : ((w * P.reflectionOf hF.isGeneralizedCartan v i : P.weylGroup _) :
        Dual K H ≃ₗ[K] Dual K H) ((v : Dual K H ≃ₗ[K] Dual K H) (P.root i)) =
        ((w * v * (P.coxeterSystem hF.isGeneralizedCartan).simple i : P.weylGroup _) :
          Dual K H ≃ₗ[K] Dual K H) (P.root i) := by
      rw [mul_simple_apply_root, Subgroup.coe_mul, LinearEquiv.mul_apply, reflectionOf_apply',
        corootPairing, inv_apply_apply, P.root_coroot_self hF.isGeneralizedCartan, two_smul,
        sub_add_cancel_left, map_neg]
      rfl
    have hrefl : (P.reflectionOf hF.isGeneralizedCartan v i : Dual K H ≃ₗ[K] Dual K H) b =
        b - (z : K) • (v : Dual K H ≃ₗ[K] Dual K H) (P.root i) := by
      rw [reflectionOf_apply', ← hz]
      rfl
    have e : w = w * P.reflectionOf hF.isGeneralizedCartan v i *
        P.reflectionOf hF.isGeneralizedCartan v i := by
      rw [mul_assoc, reflectionOf_mul_self, mul_one]
    have hsplit : (w : Dual K H ≃ₗ[K] Dual K H) b - b =
        (((w * P.reflectionOf hF.isGeneralizedCartan v i : P.weylGroup _) :
          Dual K H ≃ₗ[K] Dual K H) b - b) + (-z).toNat •
          ((w * v * (P.coxeterSystem hF.isGeneralizedCartan).simple i : P.weylGroup _) :
            Dual K H ≃ₗ[K] Dual K H) (P.root i) := by
      have hzK : (z : K) = -(((-z).toNat : ℕ) : K) := by
        have h' : (((-z).toNat : ℕ) : K) = ((-z : ℤ) : K) := by
          exact_mod_cast Int.toNat_of_nonneg (show 0 ≤ -z by omega)
        rw [h']
        push_cast
        ring
      conv_lhs => rw [e]
      rw [Subgroup.coe_mul _ (w * _), LinearEquiv.mul_apply, hrefl, map_sub, map_smul, hβ,
        ← Nat.cast_smul_eq_nsmul K, hzK]
      module
    rw [hsplit]
    refine add_mem hk (nsmul_mem ?_ _)
    apply AddSubmonoid.subset_closure
    exact ⟨_, i, hpos, hint, rfl⟩
  · push Not at hex
    rw [eq_one_of_forall_isPosRoot_integral hF hw hex]
    simp

variable [FiniteDimensional K H]

/-- The sign and orthogonality properties of the form on the integral root cone: for `x` in the
cone of the positive roots integral for `b`, `(x | a) = n` with `n ∈ ℤ_{≤ 0}`, and `(x | a) = 0`
forces `(x | b) = 0`, as soon as `a - b` is integral, `⟨a, β^∨⟩ ≤ 0` for the positive integral
roots, and every integral root orthogonal to `a` is orthogonal to `b`. -/
lemma bilinForm_integralPosRootCone (S : A.Symmetrization) {a b : Dual K H}
    (hab : ∀ v i, P.IsIntegralRoot hF.isGeneralizedCartan b v i →
      P.IsIntegralRoot hF.isGeneralizedCartan a v i)
    (ha : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i → ∀ n : ℤ,
      P.corootPairing hF.isGeneralizedCartan a v i = n → n ≤ 0)
    (hfacet : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i →
      P.corootPairing hF.isGeneralizedCartan a v i = 0 →
        P.corootPairing hF.isGeneralizedCartan b v i = 0)
    {x : Dual K H} (hx : x ∈ P.integralPosRootCone hF.isGeneralizedCartan b) :
    ∃ q : ℚ, q ≤ 0 ∧ P.dualBilinForm S x a = q ∧
      (q = 0 → P.dualBilinForm S x b = 0) := by
  induction hx using AddSubmonoid.closure_induction with
  | mem x hx =>
    obtain ⟨v, i, hv, hint, rfl⟩ := hx
    obtain ⟨n, hn⟩ := hab v i hint
    change P.corootPairing _ a v i = n at hn
    have hform : ∀ y : Dual K H, P.dualBilinForm S y ((v : Dual K H ≃ₗ[K] Dual K H) (P.root i)) =
        P.corootPairing hF.isGeneralizedCartan y v i / S.ε i := by
      intro y
      rw [← P.dualBilinForm_weylGroup hF.isGeneralizedCartan S (v⁻¹).2, inv_apply_apply,
        dualBilinForm_root_right]
      rfl
    have hsymm := (P.isSymm_dualBilinForm S).eq
    refine ⟨n / S.ε i, ?_, ?_, fun h0 ↦ ?_⟩
    · exact div_nonpos_of_nonpos_of_nonneg (by exact_mod_cast ha v i hv n hn) (S.ε_pos i).le
    · rw [hsymm, hform, hn]
      push_cast
      rfl
    · have hn0 : n = 0 := by
        have := S.ε_ne_zero i
        rw [div_eq_zero_iff] at h0
        exact_mod_cast h0.resolve_right this
      rw [hsymm, hform, hfacet v i hv (by rw [hn, hn0, Int.cast_zero]), zero_div]
  | zero => exact ⟨0, le_rfl, by simp, fun _ ↦ by simp⟩
  | add x y _ _ hx hy =>
    obtain ⟨q₁, hq₁, hx₁, hx₂⟩ := hx
    obtain ⟨q₂, hq₂, hy₁, hy₂⟩ := hy
    refine ⟨q₁ + q₂, add_nonpos hq₁ hq₂, ?_, fun h0 ↦ ?_⟩
    · rw [map_add, LinearMap.add_apply, hx₁, hy₁]
      push_cast
      rfl
    rw [map_add, LinearMap.add_apply, hx₂ (by linarith), hy₂ (by linarith), add_zero]

/-- **Facet exclusion for the integral Weyl group, root-datum form** (the core of Humphreys,
GSM 94, Lemma 7.5, for arbitrary weights). Let `a = λ + ρ`, `b = μ + ρ` with `b - a` integral,
`⟨a, β^∨⟩, ⟨b, β^∨⟩ ≤ 0` for the positive roots `β` integral for `a` (antidominance), and every
integral root orthogonal to `a` orthogonal to `b` (the facet containing `λ` has `μ` in its
closure). Let `ν = z (b - a)` be dominant integral (`z ∈ W`), and `ν₁ = u ν₂` with `u ∈ W`,
`ν₂` dominant integral, `ν - ν₂ ∈ Q₊`. If `a + ν₁ = y b` with `y ∈ W_[b]`, then `y b = b`. -/
theorem apply_eq_of_add_eq_apply_integralWeylGroup {a b : Dual K H}
    (hab : ∀ j, ∃ n : ℤ, (b - a) (P.coroot j) = n)
    (ha : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i → ∀ n : ℤ,
      P.corootPairing hF.isGeneralizedCartan a v i = n → n ≤ 0)
    (hb : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i → ∀ n : ℤ,
      P.corootPairing hF.isGeneralizedCartan b v i = n → n ≤ 0)
    (hfacet : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i →
      P.corootPairing hF.isGeneralizedCartan a v i = 0 →
        P.corootPairing hF.isGeneralizedCartan b v i = 0)
    {z u y : P.weylGroup hF.isGeneralizedCartan}
    (hν : ∀ i, ∃ n : ℕ, (z : Dual K H ≃ₗ[K] Dual K H) (b - a) (P.coroot i) = n)
    {ν₂ : Dual K H} (hν₂ : ∀ i, ∃ n : ℕ, ν₂ (P.coroot i) = n) {c : ι → ℤ} (hc : 0 ≤ c)
    (hνc : (z : Dual K H ≃ₗ[K] Dual K H) (b - a) - ν₂ = P.rootOf c)
    (hy : y ∈ P.integralWeylGroup hF.isGeneralizedCartan b)
    (h : a + (u : Dual K H ≃ₗ[K] Dual K H) ν₂ = (y : Dual K H ≃ₗ[K] Dual K H) b) :
    (y : Dual K H ≃ₗ[K] Dual K H) b = b := by
  classical
  obtain ⟨d, hdpos, hpos⟩ := hF.exists_posDef
  have hsymm : (diagonal d * A).IsSymm := by
    simpa [IsHermitian, IsSymm] using hpos.isHermitian
  set S := Symmetrization.ofDiagonal d hdpos hsymm
  set B := P.dualBilinForm S
  have hB (k : ι → ℤ) (x : Dual K H) := P.dualBilinForm_ofDiagonal_rootOf d hdpos hsymm k x
  have hW (w : P.weylGroup hF.isGeneralizedCartan) (x x' : Dual K H) :
      B ((w : Dual K H ≃ₗ[K] Dual K H) x) ((w : Dual K H ≃ₗ[K] Dual K H) x') = B x x' :=
    P.dualBilinForm_weylGroup hF.isGeneralizedCartan S w.2 x x'
  have hBsymm (x x' : Dual K H) : B x x' = B x' x := (P.isSymm_dualBilinForm S).eq x x'
  -- integrality of `b` and `a` agree
  have hab' : ∀ j, ∃ n : ℤ, (a - b) (P.coroot j) = n := fun j ↦ by
    obtain ⟨n, hn⟩ := hab j
    refine ⟨-n, ?_⟩
    rw [← neg_sub, LinearMap.neg_apply, hn, Int.cast_neg]
  have hint : ∀ v i, P.IsIntegralRoot hF.isGeneralizedCartan b v i →
      P.IsIntegralRoot hF.isGeneralizedCartan a v i := fun v i hbi ↦
    (P.isIntegralRoot_congr _ hab' v i).mpr hbi
  -- `x := y b - b` lies in the integral root cone, and in `Q`
  set x := (y : Dual K H ≃ₗ[K] Dual K H) b - b with hx
  have hxcone := apply_sub_mem_integralPosRootCone hF hb hy
  obtain ⟨e, he⟩ := (P.mem_rootLattice).mp hy
  obtain ⟨q, hq, hxa, hxb⟩ := bilinForm_integralPosRootCone hF S hint ha hfacet hxcone
  choose n2 hn2 using hν₂
  choose nν hnν using hν
  -- `R₁ := |ν|² - |ν₂|² = (ν - ν₂ | ν + ν₂) ≥ 0`.
  set R₁ : ℤ := ∑ i, c i * d i * ((nν i : ℤ) + n2 i) with hR₁
  have hR₁nonneg : 0 ≤ R₁ := Finset.sum_nonneg fun i _ =>
    mul_nonneg (mul_nonneg (hc i) (hdpos i).le) (by positivity)
  have hR₁eq : B ((z : Dual K H ≃ₗ[K] Dual K H) (b - a)) ((z : Dual K H ≃ₗ[K] Dual K H) (b - a))
      - B ν₂ ν₂ = R₁ := by
    have hsplit : (z : Dual K H ≃ₗ[K] Dual K H) (b - a) = ν₂ + P.rootOf c := by
      rw [← hνc]; abel
    calc _ = B (P.rootOf c) ((z : Dual K H ≃ₗ[K] Dual K H) (b - a) + ν₂) := by
          rw [hsplit]
          simp only [map_add, LinearMap.add_apply]
          rw [hBsymm ν₂ (P.rootOf c)]
          ring
      _ = R₁ := by
          rw [hB, hR₁]
          push_cast
          refine Finset.sum_congr rfl fun i _ => ?_
          rw [LinearMap.add_apply, hnν, hn2]
  -- `|b - a|² - |y b - a|² = 2 (x | a) = 2 q ≤ 0`.
  have h1 : B ((y : Dual K H ≃ₗ[K] Dual K H) b) ((y : Dual K H ≃ₗ[K] Dual K H) b) = B b b :=
    hW y b b
  have hyb : (y : Dual K H ≃ₗ[K] Dual K H) b = b + x := by rw [hx]; abel
  have hR₂eq : B (b - a) (b - a) - B ((y : Dual K H ≃ₗ[K] Dual K H) b - a)
      ((y : Dual K H ≃ₗ[K] Dual K H) b - a) = 2 * q := by
    rw [hyb] at h1 ⊢
    simp only [map_add, map_sub, LinearMap.add_apply, LinearMap.sub_apply] at h1 ⊢
    rw [hBsymm b a, hBsymm b x, hBsymm a x, hxa] at *
    linear_combination (-1 : K) * h1
  have hR : (R₁ : K) = 2 * q := by
    have h3 : (y : Dual K H ≃ₗ[K] Dual K H) b - a = (u : Dual K H ≃ₗ[K] Dual K H) ν₂ := by
      rw [← h]; abel
    rw [← hR₁eq, ← hR₂eq, hW z, h3, hW u]
  have hq0 : q = 0 := by
    have : ((R₁ : ℚ) : K) = ((2 * q : ℚ) : K) := by push_cast; exact hR
    have h' : (R₁ : ℚ) = 2 * q := by exact_mod_cast this
    have : (0 : ℚ) ≤ R₁ := by exact_mod_cast hR₁nonneg
    linarith
  -- so `(x | b) = 0` and `|x|² = 0`
  have hxx : B x x = 0 := by
    rw [hyb] at h1
    simp only [map_add, LinearMap.add_apply] at h1
    rw [hBsymm b x, hxb hq0] at h1
    linear_combination h1
  have he0 : e = 0 := by
    by_contra hne
    have hqd := hpos.dotProduct_mulVec_pos hne
    rw [hx, ← he, hB] at hxx
    have hcast : ((e ⬝ᵥ (diagonal d * A) *ᵥ e : ℤ) : K) = 0 := by
      rw [← hxx, ← mulVec_mulVec, dotProduct]
      simp only [mulVec_diagonal]
      push_cast
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [rootOf_apply_coroot]
      ring
    simp only [star_trivial] at hqd
    exact hqd.ne' (by exact_mod_cast hcast)
  rw [← sub_eq_zero, ← he, he0, map_zero]

end Matrix.Realization
