/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.LinearAlgebra.Matrix.Cartan.WeylGroup
import LieLean.LinearAlgebra.Matrix.Cartan.Symmetrizable

/-!
# The integral Weyl group `W_[λ]`

For a weight `λ ∈ 𝔥*` the **integral Weyl group** is
`W_[λ] = {w ∈ W | wλ - λ ∈ Q}` (Humphreys, *Representations of semisimple Lie algebras in the
BGG category 𝒪*, GSM 94, §3.4), where `Q` is the root lattice. A real root `β = v αᵢ` (`v ∈ W`)
is **integral** for `λ` if `⟨λ, β^∨⟩ = ⟨v⁻¹ λ, αᵢ^∨⟩ ∈ ℤ`; the reflection in `β` is
`s_β = v rᵢ v⁻¹` (`Realization.reflectionOf`).

## Main results

* `Realization.integralWeylGroup`: `W_[λ]`, a subgroup of `W`.
* `Realization.integralWeylGroup_eq_of_integral`: `W_[λ] = W_[μ]` if `λ - μ` is integral; in
  particular `W_[λ] = W` for integral `λ` (`integralWeylGroup_eq_top`) and `W_[λ]` may be
  defined equally with the dot action (`mem_integralWeylGroup_iff_dot`).
* `Realization.reflectionOf_mem_integralWeylGroup_iff`: `s_β ∈ W_[λ]` iff `β` is integral for
  `λ` (Humphreys, GSM 94, §3.4: `Φ_[λ] = {α ∈ Φ | s_α ∈ W_[λ]}`); this uses that the only scalar
  multiples of a real root in `Q` are its integer multiples.
* `Realization.isIntegralRoot_mul`: `W_[λ]` permutes the roots integral for `λ`.
* `Realization.integralReflectionGroup_le`: the subgroup generated by the reflections in the
  integral roots lies in `W_[λ]`.

The converse (Humphreys, GSM 94, Thm. 3.4 (b): in finite type `W_[λ]` is generated by these
reflections) is not proved here. The arguments hold for every generalized Cartan matrix and are
our own.
-/

noncomputable section

open Module

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H) (hA : A.IsGeneralizedCartan)

/-- The root lattice `Q = ⊕ ℤ αᵢ` as an additive subgroup of `𝔥*`. -/
def rootLattice : AddSubgroup (Dual K H) := P.rootOf.range

lemma mem_rootLattice {μ : Dual K H} : μ ∈ P.rootLattice ↔ ∃ k, P.rootOf k = μ :=
  AddMonoidHom.mem_range

lemma rootOf_mem_rootLattice (k : ι → ℤ) : P.rootOf k ∈ P.rootLattice := ⟨k, rfl⟩

/-- Elements of `Q` pair integrally with the simple coroots. -/
lemma exists_int_of_mem_rootLattice {μ : Dual K H} (hμ : μ ∈ P.rootLattice) (j : ι) :
    ∃ z : ℤ, μ (P.coroot j) = z := by
  obtain ⟨k, rfl⟩ := hμ
  exact ⟨_, P.rootOf_apply_coroot k j⟩

/-- The Weyl group preserves `Q`. -/
lemma apply_mem_rootLattice {w : Dual K H ≃ₗ[K] Dual K H} (hw : w ∈ P.weylGroup hA)
    {μ : Dual K H} (hμ : μ ∈ P.rootLattice) : w μ ∈ P.rootLattice := by
  obtain ⟨k, rfl⟩ := hμ
  obtain ⟨k', hk'⟩ := P.exists_apply_rootOf_eq_rootOf hA hw k
  exact ⟨k', hk'.symm⟩

/-- For `w ∈ W` and an integral weight `μ` (`⟨μ, αⱼ^∨⟩ ∈ ℤ`), `w μ - μ ∈ Q`. -/
lemma apply_sub_mem_rootLattice_of_integral {w : Dual K H ≃ₗ[K] Dual K H}
    (hw : w ∈ P.weylGroup hA) {μ : Dual K H} (hμ : ∀ j, ∃ z : ℤ, μ (P.coroot j) = z) :
    w μ - μ ∈ P.rootLattice := by
  obtain ⟨k, hk⟩ := P.exists_apply_eq_add_rootOf hA hw hμ
  exact ⟨k, by rw [hk, add_sub_cancel_left]⟩

/-- The only multiples `c αᵢ` (`c ∈ K`) of a simple root in `Q` are the integer multiples. -/
lemma exists_int_of_smul_root_mem_rootLattice {c : K} {i : ι}
    (h : c • P.root i ∈ P.rootLattice) : ∃ z : ℤ, c = z := by
  classical
  obtain ⟨k, hk⟩ := h
  refine ⟨k i, ?_⟩
  have h1 : ∑ j, (if j = i then c else 0) • P.root j = c • P.root i := by
    rw [Finset.sum_eq_single i (fun j _ hj ↦ by rw [ite_eq_right hj, zero_smul])
      (fun h ↦ absurd (Finset.mem_univ i) h),
      ite_eq_left rfl]
  have h0 : ∑ j, ((k j : K) - if j = i then c else 0) • P.root j = 0 := by
    have e : ∑ j, ((k j : K) - if j = i then c else 0) • P.root j =
        P.rootOf k - c • P.root i := by
      rw [← h1, rootOf_apply, ← Finset.sum_sub_distrib]
      exact Finset.sum_congr rfl fun j _ ↦ LinearMap.ext fun x ↦ by split_ifs <;> simp [sub_mul]
    rw [e, hk, sub_self]
  have := Fintype.linearIndependent_iff.mp P.linearIndependent_root _ h0 i
  rw [ite_eq_left rfl] at this
  exact (sub_eq_zero.mp this).symm

omit [Fintype ι] in
private lemma one_apply' (μ : Dual K H) : (1 : Dual K H ≃ₗ[K] Dual K H) μ = μ := rfl

/-! ### The integral Weyl group -/

/-- The **integral Weyl group** `W_[λ] = {w ∈ W | wλ - λ ∈ Q}` (Humphreys, GSM 94, §3.4). -/
def integralWeylGroup (μ : Dual K H) : Subgroup (P.weylGroup hA) where
  carrier := {w | (w : Dual K H ≃ₗ[K] Dual K H) μ - μ ∈ P.rootLattice}
  one_mem' := by
    change (1 : Dual K H ≃ₗ[K] Dual K H) μ - μ ∈ P.rootLattice
    rw [one_apply', sub_self]
    exact zero_mem _
  mul_mem' := by
    intro w w' hw hw'
    change (w * w' : Dual K H ≃ₗ[K] Dual K H) μ - μ ∈ P.rootLattice
    have e : (w * w' : Dual K H ≃ₗ[K] Dual K H) μ - μ =
        (w : Dual K H ≃ₗ[K] Dual K H) ((w' : Dual K H ≃ₗ[K] Dual K H) μ - μ) +
          ((w : Dual K H ≃ₗ[K] Dual K H) μ - μ) := by
      rw [LinearEquiv.mul_apply, map_sub]
      abel
    rw [e]
    exact add_mem (P.apply_mem_rootLattice hA w.2 hw') hw
  inv_mem' := by
    intro w hw
    change ((w : Dual K H ≃ₗ[K] Dual K H)⁻¹) μ - μ ∈ P.rootLattice
    have e : ((w : Dual K H ≃ₗ[K] Dual K H)⁻¹) μ - μ =
        -((w : Dual K H ≃ₗ[K] Dual K H)⁻¹) ((w : Dual K H ≃ₗ[K] Dual K H) μ - μ) := by
      rw [map_sub, ← LinearEquiv.mul_apply, inv_mul_cancel, one_apply']
      abel
    rw [e]
    exact neg_mem (P.apply_mem_rootLattice hA (inv_mem w.2) hw)

lemma mem_integralWeylGroup {μ : Dual K H} {w : P.weylGroup hA} :
    w ∈ P.integralWeylGroup hA μ ↔ (w : Dual K H ≃ₗ[K] Dual K H) μ - μ ∈ P.rootLattice :=
  Iff.rfl

/-- `W_[λ]` only depends on `λ` modulo integral weights. -/
theorem integralWeylGroup_eq_of_integral {μ μ' : Dual K H}
    (h : ∀ j, ∃ z : ℤ, (μ - μ') (P.coroot j) = z) :
    P.integralWeylGroup hA μ = P.integralWeylGroup hA μ' := by
  ext w
  rw [mem_integralWeylGroup, mem_integralWeylGroup]
  have hd := P.apply_sub_mem_rootLattice_of_integral hA w.2 h
  have e : (w : Dual K H ≃ₗ[K] Dual K H) μ - μ = ((w : Dual K H ≃ₗ[K] Dual K H) μ' - μ') +
      ((w : Dual K H ≃ₗ[K] Dual K H) (μ - μ') - (μ - μ')) := by
    rw [map_sub]
    abel
  rw [e]
  exact ⟨fun h' ↦ by simpa using sub_mem h' hd, fun h' ↦ add_mem h' hd⟩

/-- For an integral weight, `W_[λ] = W`. -/
theorem integralWeylGroup_eq_top {μ : Dual K H} (h : ∀ j, ∃ z : ℤ, μ (P.coroot j) = z) :
    P.integralWeylGroup hA μ = ⊤ := by
  rw [eq_top_iff]
  intro w _
  exact P.apply_sub_mem_rootLattice_of_integral hA w.2 h

/-- `W_[λ]` defined with the dot action: `w ∈ W_[λ]` iff `w(λ + ρ) - ρ - λ ∈ Q`. -/
theorem mem_integralWeylGroup_iff_dot {μ : Dual K H} {w : P.weylGroup hA} :
    w ∈ P.integralWeylGroup hA μ ↔
      (w : Dual K H ≃ₗ[K] Dual K H) (μ + P.rho) - P.rho - μ ∈ P.rootLattice := by
  rw [P.integralWeylGroup_eq_of_integral hA (μ' := μ + P.rho) fun j ↦ ⟨-1, by simp⟩,
    mem_integralWeylGroup, sub_sub, add_comm P.rho μ]

/-! ### Reflections in real roots -/

/-- The reflection `s_β = v rᵢ v⁻¹` in the real root `β = v αᵢ`, as an element of `W`. -/
def reflectionOf (v : P.weylGroup hA) (i : ι) : P.weylGroup hA :=
  v * ⟨P.reflection hA i, P.reflection_mem_weylGroup hA i⟩ * v⁻¹

/-- `s_β μ = μ - ⟨μ, β^∨⟩ β` with `⟨μ, β^∨⟩ = ⟨v⁻¹ μ, αᵢ^∨⟩`, `β = v αᵢ`. -/
lemma reflectionOf_apply (v : P.weylGroup hA) (i : ι) (μ : Dual K H) :
    (P.reflectionOf hA v i : Dual K H ≃ₗ[K] Dual K H) μ =
      μ - ((v⁻¹ : P.weylGroup hA) : Dual K H ≃ₗ[K] Dual K H) μ (P.coroot i) •
        (v : Dual K H ≃ₗ[K] Dual K H) (P.root i) := by
  change (v : Dual K H ≃ₗ[K] Dual K H) (P.reflection hA i
    (((v⁻¹ : P.weylGroup hA) : Dual K H ≃ₗ[K] Dual K H) μ)) = _
  rw [reflection_apply, map_sub, map_smul, ← LinearEquiv.mul_apply, ← Subgroup.coe_mul,
    mul_inv_cancel, Subgroup.coe_one, one_apply']

/-- The real root `v αᵢ` is **integral** for `μ` if `⟨μ, (v αᵢ)^∨⟩ = ⟨v⁻¹ μ, αᵢ^∨⟩ ∈ ℤ`. -/
def IsIntegralRoot (μ : Dual K H) (v : P.weylGroup hA) (i : ι) : Prop :=
  ∃ z : ℤ, ((v⁻¹ : P.weylGroup hA) : Dual K H ≃ₗ[K] Dual K H) μ (P.coroot i) = z

/-- `s_β ∈ W_[λ]` iff `β` is integral for `λ` (Humphreys, GSM 94, §3.4). -/
theorem reflectionOf_mem_integralWeylGroup_iff {μ : Dual K H}
    (v : P.weylGroup hA) (i : ι) :
    P.reflectionOf hA v i ∈ P.integralWeylGroup hA μ ↔ P.IsIntegralRoot hA μ v i := by
  classical
  rw [mem_integralWeylGroup, reflectionOf_apply, sub_sub_cancel_left]
  set c := ((v⁻¹ : P.weylGroup hA) : Dual K H ≃ₗ[K] Dual K H) μ (P.coroot i)
  constructor
  · intro h
    have h' := P.apply_mem_rootLattice hA (v⁻¹).2 (neg_mem h)
    rw [neg_neg, map_smul, ← LinearEquiv.mul_apply, ← Subgroup.coe_mul, inv_mul_cancel,
      Subgroup.coe_one, one_apply'] at h'
    exact P.exists_int_of_smul_root_mem_rootLattice h'
  · rintro ⟨z, hz⟩
    rw [show c = z from hz, ← map_smul, Int.cast_smul_eq_zsmul K z (P.root i), ← rootOf_single,
      ← map_zsmul]
    exact neg_mem (P.apply_mem_rootLattice hA v.2 (P.rootOf_mem_rootLattice _))

/-- Integrality of a root only depends on `λ` modulo integral weights. -/
theorem isIntegralRoot_congr {μ μ' : Dual K H} (h : ∀ j, ∃ z : ℤ, (μ - μ') (P.coroot j) = z)
    (v : P.weylGroup hA) (i : ι) :
    P.IsIntegralRoot hA μ v i ↔ P.IsIntegralRoot hA μ' v i := by
  have hd := P.apply_sub_mem_rootLattice_of_integral hA (v⁻¹).2 h
  obtain ⟨z, hz⟩ := P.exists_int_of_mem_rootLattice hd i
  obtain ⟨z', hz'⟩ := h i
  have e : ((v⁻¹ : P.weylGroup hA) : Dual K H ≃ₗ[K] Dual K H) μ (P.coroot i) =
      ((v⁻¹ : P.weylGroup hA) : Dual K H ≃ₗ[K] Dual K H) μ' (P.coroot i) + ((z + z' : ℤ) : K) := by
    simp only [map_sub, LinearMap.sub_apply] at hz hz'
    push_cast
    linear_combination hz + hz'
  unfold IsIntegralRoot
  rw [e]
  exact ⟨fun ⟨n, hn⟩ ↦ ⟨n - (z + z'), by push_cast at hn ⊢; rw [← hn]; ring⟩,
    fun ⟨n, hn⟩ ↦ ⟨n + (z + z'), by push_cast at hn ⊢; rw [hn]⟩⟩

/-- `W_[λ]` permutes the roots integral for `λ`: if `w ∈ W_[λ]` and `v αᵢ` is integral, so is
`w v αᵢ`. -/
theorem isIntegralRoot_mul {μ : Dual K H} {w : P.weylGroup hA}
    (hw : w ∈ P.integralWeylGroup hA μ) {v : P.weylGroup hA} {i : ι}
    (hv : P.IsIntegralRoot hA μ v i) : P.IsIntegralRoot hA μ (w * v) i := by
  obtain ⟨n, hn⟩ := hv
  have hw' : (((w⁻¹ : P.weylGroup hA) : Dual K H ≃ₗ[K] Dual K H) μ - μ) ∈ P.rootLattice :=
    inv_mem hw
  have hq := P.apply_mem_rootLattice hA (v⁻¹).2 hw'
  obtain ⟨z, hz⟩ := P.exists_int_of_mem_rootLattice hq i
  refine ⟨n + z, ?_⟩
  rw [show (w * v)⁻¹ = v⁻¹ * w⁻¹ by group, Subgroup.coe_mul, LinearEquiv.mul_apply]
  simp only [map_sub, LinearMap.sub_apply] at hz
  push_cast
  linear_combination hz + hn

/-- Conjugating the reflection in `v αᵢ` by `w` gives the reflection in `w v αᵢ`. -/
lemma mul_reflectionOf_mul_inv (w v : P.weylGroup hA) (i : ι) :
    w * P.reflectionOf hA v i * w⁻¹ = P.reflectionOf hA (w * v) i := by
  simp only [reflectionOf]
  group

/-- The subgroup of `W` generated by the reflections in the roots integral for `λ`. -/
def integralReflectionGroup (μ : Dual K H) : Subgroup (P.weylGroup hA) :=
  Subgroup.closure {s | ∃ v i, P.IsIntegralRoot hA μ v i ∧ P.reflectionOf hA v i = s}

/-- The reflections in the integral roots generate a subgroup of `W_[λ]`. -/
theorem integralReflectionGroup_le (μ : Dual K H) :
    P.integralReflectionGroup hA μ ≤ P.integralWeylGroup hA μ := by
  rw [integralReflectionGroup, Subgroup.closure_le]
  rintro _ ⟨v, i, hv, rfl⟩
  exact (P.reflectionOf_mem_integralWeylGroup_iff hA v i).mpr hv

end Matrix.Realization
