/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.LinearAlgebra.Matrix.Cartan.IntegralWeylGroupReflections

/-!
# Stabilizers and antidominant weights for the integral Weyl group

Let `A` be a Cartan matrix of finite type with a realization over a field `K` of characteristic
zero, and `λ ∈ 𝔥*`. Using that the integral Weyl group `W_[λ]` is generated by the reflections in
the roots integral for `λ` (`Matrix.Realization.integralWeylGroup_eq_integralReflectionGroup`),
we prove:

* the stabilizer of any weight `μ` in `W` is generated by the reflections `s_β` with
  `⟨μ, β^∨⟩ = 0` (`Matrix.Realization.apply_eq_self_iff_mem_closure_reflectionOf`; for the dot
  action apply it to `μ + ρ`, cf. Humphreys, GSM 94, §7.4, Remark (2));
* an element of `W_[λ]` mapping every positive root integral for `λ` to a positive root is `1`
  (`Matrix.Realization.eq_one_of_forall_isPosRoot_integral`);
* **Humphreys, GSM 94, Prop. 3.5 (c)**: if `λ` is antidominant (`⟨λ + ρ, β^∨⟩ ∉ ℤ_{>0}` for all
  positive roots `β`), then `λ ≤ w·λ` for all `w ∈ W_[λ]`
  (`Matrix.Realization.IsAntidominant.exists_weylDot_sub_eq_rootOf`), and the orbit `W_[λ]·λ`
  contains exactly one antidominant weight (`Matrix.Realization.exists_isAntidominant_weylDot`,
  `Matrix.Realization.IsAntidominant.eq_of_weylDot_eq`).

Humphreys proves Prop. 3.5 by induction on the length in `W_[λ]` relative to its own simple
system; we use the length in `W` and the exchange property for reflections in positive roots
(`Matrix.Realization.length_mul_reflectionOf_lt`). The arguments are our own.

## References

* J. E. Humphreys, *Representations of semisimple Lie algebras in the BGG category 𝒪*, GSM 94,
  AMS 2008, §3.5, §7.4.
-/

noncomputable section

open Module CoxeterSystem

namespace Matrix.Realization

variable {ι : Type*} [Fintype ι] [DecidableEq ι] {A : Matrix ι ι ℤ}

/-! ### Lengths under `weylGroupEquiv` -/

section Equiv

variable {K H K' H' : Type*} [Field K] [CharZero K] [AddCommGroup H] [Module K H]
  [Field K'] [CharZero K'] [AddCommGroup H'] [Module K' H']
  (P : Realization A K H) (Q : Realization A K' H') (hA : A.IsGeneralizedCartan)

lemma weylGroupEquiv_symm_wordProd (ω : List ι) :
    (weylGroupEquiv P Q hA).symm ((Q.coxeterSystem hA).wordProd ω) =
      (P.coxeterSystem hA).wordProd ω := by
  rw [MulEquiv.symm_apply_eq, weylGroupEquiv_wordProd]

lemma length_weylGroupEquiv (w : P.weylGroup hA) :
    (Q.coxeterSystem hA).length (weylGroupEquiv P Q hA w) = (P.coxeterSystem hA).length w := by
  refine le_antisymm ?_ ?_
  · obtain ⟨ω, hω, rfl⟩ := (P.coxeterSystem hA).exists_isReduced w
    rw [weylGroupEquiv_wordProd, hω.eq]
    exact (Q.coxeterSystem hA).length_wordProd_le ω
  · obtain ⟨ω, hω, hw⟩ := (Q.coxeterSystem hA).exists_isReduced (weylGroupEquiv P Q hA w)
    rw [hw, hω.eq]
    calc (P.coxeterSystem hA).length w
        = (P.coxeterSystem hA).length
            ((weylGroupEquiv P Q hA).symm ((Q.coxeterSystem hA).wordProd ω)) := by
          rw [← hw, MulEquiv.symm_apply_apply]
      _ ≤ ω.length := by
          rw [weylGroupEquiv_symm_wordProd]
          exact (P.coxeterSystem hA).length_wordProd_le ω

variable {P Q hA} in
lemma isPosRoot_weylGroupEquiv_iff {v : P.weylGroup hA} {i : ι} :
    Q.IsPosRoot hA (weylGroupEquiv P Q hA v) i ↔ P.IsPosRoot hA v i := by
  rw [isPosRoot_iff_not_isRightDescent, isPosRoot_iff_not_isRightDescent, IsRightDescent,
    IsRightDescent, ← weylGroupEquiv_simple P Q hA, ← map_mul, length_weylGroupEquiv,
    length_weylGroupEquiv]

end Equiv

variable {K H : Type*} [Field K] [CharZero K] [AddCommGroup H] [Module K H]
  {P : Realization A K H} (hF : A.IsFiniteCartan)

/-! ### Stabilizers -/

omit [DecidableEq ι] [CharZero K] in
/-- Elements of the stabilizer of `μ` generated by reflections fixing `μ` fix `μ`. -/
lemma apply_eq_self_of_mem_closure {hA : A.IsGeneralizedCartan} {μ : Dual K H}
    {w : P.weylGroup hA} (hw : w ∈ Subgroup.closure
      {s | ∃ v i, P.corootPairing hA μ v i = 0 ∧ P.reflectionOf hA v i = s}) :
    (w : Dual K H ≃ₗ[K] Dual K H) μ = μ := by
  induction hw using Subgroup.closure_induction with
  | mem s hs =>
    obtain ⟨v, i, h0, rfl⟩ := hs
    rw [reflectionOf_apply', h0, zero_smul, sub_zero]
  | one => rfl
  | mul a b _ _ ha hb => rw [Subgroup.coe_mul, LinearEquiv.mul_apply, hb, ha]
  | inv a _ ha =>
    conv_lhs => rw [← ha]
    exact inv_apply_apply a μ

/-- **Stabilizers are generated by reflections.** For a Cartan matrix of finite type and any
weight `μ` over a field of characteristic zero, the stabilizer of `μ` in `W` is generated by the
reflections `s_β` with `⟨μ, β^∨⟩ = 0` (cf. Humphreys, GSM 94, §7.4, Remark (2), for the dot
action). For a large integer `N` the roots integral for `μ / N` are those orthogonal to `μ`, and
the stabilizer of `μ` lies in `W_[μ / N]`. -/
theorem apply_eq_self_iff_mem_closure_reflectionOf (μ : Dual K H)
    (w : P.weylGroup hF.isGeneralizedCartan) :
    (w : Dual K H ≃ₗ[K] Dual K H) μ = μ ↔ w ∈ Subgroup.closure
      {s | ∃ v i, P.corootPairing hF.isGeneralizedCartan μ v i = 0 ∧
        P.reflectionOf hF.isGeneralizedCartan v i = s} := by
  classical
  refine ⟨fun hw ↦ ?_, apply_eq_self_of_mem_closure⟩
  have : Finite (P.weylGroup hF.isGeneralizedCartan) := P.finite_weylGroup hF
  have : Fintype (P.weylGroup hF.isGeneralizedCartan) := Fintype.ofFinite _
  -- a bound `M` for the integral pairings `⟨μ, β^∨⟩`
  let f : P.weylGroup hF.isGeneralizedCartan × ι → ℕ := fun p ↦
    if h : ∃ z : ℤ, P.corootPairing hF.isGeneralizedCartan μ p.1 p.2 = z then h.choose.natAbs
    else 0
  set M : ℕ := ∑ p, f p + 1
  have hM : ∀ v i (z : ℤ), P.corootPairing hF.isGeneralizedCartan μ v i = z → z.natAbs < M := by
    intro v i z hz
    have h : ∃ z : ℤ, P.corootPairing hF.isGeneralizedCartan μ v i = z := ⟨z, hz⟩
    have hzc : h.choose = z := by exact_mod_cast h.choose_spec.symm.trans hz
    have : f (v, i) = z.natAbs := by simp only [f, h, ↓reduceDIte, hzc]
    have hle : f (v, i) ≤ ∑ p, f p := Finset.single_le_sum (fun _ _ ↦ Nat.zero_le _)
      (Finset.mem_univ (v, i))
    omega
  have hM0 : (M : K) ≠ 0 := Nat.cast_ne_zero.mpr (Nat.succ_ne_zero _)
  have hwt : w ∈ P.integralWeylGroup hF.isGeneralizedCartan ((M : K)⁻¹ • μ) := by
    rw [mem_integralWeylGroup, map_smul, hw, sub_self]
    exact zero_mem _
  rw [integralWeylGroup_eq_integralReflectionGroup hF] at hwt
  refine Subgroup.closure_mono ?_ hwt
  rintro _ ⟨v, i, ⟨z, hz⟩, rfl⟩
  refine ⟨v, i, ?_, rfl⟩
  change P.corootPairing hF.isGeneralizedCartan ((M : K)⁻¹ • μ) v i = z at hz
  rw [corootPairing_smul] at hz
  have hμ : P.corootPairing hF.isGeneralizedCartan μ v i = ((M * z : ℤ) : K) := by
    push_cast
    rw [← hz]
    field_simp
  have h1 := hM v i _ hμ
  have hz0 : z = 0 := by
    by_contra hz0
    rw [Int.natAbs_mul, Int.natAbs_natCast] at h1
    have : 1 ≤ z.natAbs := Int.natAbs_pos.mpr hz0
    nlinarith
  rw [hμ, hz0, mul_zero, Int.cast_zero]

/-! ### Elements of `W_[μ]` preserving the positive integral roots -/

/-- If `w ∈ W_[μ]` maps every positive root integral for `μ` to a positive root, then `w = 1`.
This is `Matrix.Realization.eq_one_of_forall_isPosRoot` transported from `ℚ`. -/
theorem eq_one_of_forall_isPosRoot_integral {μ : Dual K H}
    {w : P.weylGroup hF.isGeneralizedCartan}
    (hw : w ∈ P.integralWeylGroup hF.isGeneralizedCartan μ)
    (hpos : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i →
      P.IsIntegralRoot hF.isGeneralizedCartan μ v i →
        P.IsPosRoot hF.isGeneralizedCartan (w * v) i) : w = 1 := by
  obtain ⟨μ', hW, hint⟩ := exists_transport_integral (P := P) hF μ
  set e := weylGroupEquiv P (ratRealization hF) hF.isGeneralizedCartan
  have h := eq_one_of_forall_isPosRoot hF (hW w hw) fun v' i hv' hint' ↦ by
    rw [show v' = e (e.symm v') by simp] at hv' hint' ⊢
    rw [← map_mul, isPosRoot_weylGroupEquiv_iff] at *
    exact hpos _ i hv' (hint _ i hint')
  simpa using h

/-! ### Antidominant weights -/

/-- A weight `λ` is **antidominant** if `⟨λ + ρ, β^∨⟩ ∉ ℤ_{>0}` for every positive root `β`
(Humphreys, GSM 94, §3.5). -/
def IsAntidominant (hA : A.IsGeneralizedCartan) (μ : Dual K H) : Prop :=
  ∀ v i, P.IsPosRoot hA v i → ∀ n : ℤ, P.corootPairing hA (μ + P.rho) v i = n → n ≤ 0

/-- If `⟨b, β^∨⟩ ∉ ℤ_{>0}` for all positive roots `β`, then `w b - b ∈ Q₊` for all
`w ∈ W_[b]`. Induction on `ℓ(w)`: if `w` makes a positive integral root `β` negative, then
`w b - b = (w' b - b) - ⟨b, β^∨⟩ w' β` with `w' = w s_β` shorter and `w' β = -w β > 0`; otherwise
`w = 1` (`Matrix.Realization.eq_one_of_forall_isPosRoot_integral`). -/
theorem exists_nonneg_apply_sub_eq_rootOf {b : Dual K H}
    (hb : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i → ∀ n : ℤ,
      P.corootPairing hF.isGeneralizedCartan b v i = n → n ≤ 0)
    {w : P.weylGroup hF.isGeneralizedCartan}
    (hw : w ∈ P.integralWeylGroup hF.isGeneralizedCartan b) :
    ∃ k : ι → ℤ, 0 ≤ k ∧ (w : Dual K H ≃ₗ[K] Dual K H) b - b = P.rootOf k := by
  induction hlen : (P.coxeterSystem hF.isGeneralizedCartan).length w
    using Nat.strong_induction_on generalizing w with
  | _ n ih =>
  by_cases hex : ∃ v i, P.IsPosRoot hF.isGeneralizedCartan v i ∧
      P.IsIntegralRoot hF.isGeneralizedCartan b v i ∧
        ¬P.IsPosRoot hF.isGeneralizedCartan (w * v) i
  · obtain ⟨v, i, hv, ⟨z, hz⟩, hneg⟩ := hex
    have hs : P.reflectionOf hF.isGeneralizedCartan v i ∈
        P.integralWeylGroup hF.isGeneralizedCartan b :=
      (P.reflectionOf_mem_integralWeylGroup_iff _ v i).mpr ⟨z, hz⟩
    obtain ⟨k, hk, hwk⟩ := ih _ (hlen ▸ length_mul_reflectionOf_lt hv hneg) (mul_mem hw hs) rfl
    obtain ⟨l, hl, hwl⟩ := (isPosRoot_or (w * v) i).resolve_left hneg
    rw [mul_simple_apply_root] at hwl
    have hz0 := hb v i hv z hz
    refine ⟨k + (-z) • l, add_nonneg hk (smul_nonneg (by omega) hl), ?_⟩
    have hβ : ((w * P.reflectionOf hF.isGeneralizedCartan v i : P.weylGroup _) :
        Dual K H ≃ₗ[K] Dual K H) ((v : Dual K H ≃ₗ[K] Dual K H) (P.root i)) = P.rootOf l := by
      rw [Subgroup.coe_mul, LinearEquiv.mul_apply, reflectionOf_apply', corootPairing,
        inv_apply_apply, P.root_coroot_self hF.isGeneralizedCartan, two_smul, sub_add_cancel_left,
        map_neg, ← hwl]
      rfl
    have hrefl : (P.reflectionOf hF.isGeneralizedCartan v i : Dual K H ≃ₗ[K] Dual K H) b =
        b - (z : K) • (v : Dual K H ≃ₗ[K] Dual K H) (P.root i) := by
      rw [reflectionOf_apply', ← hz]
      rfl
    have e : w = w * P.reflectionOf hF.isGeneralizedCartan v i *
        P.reflectionOf hF.isGeneralizedCartan v i := by
      rw [mul_assoc, reflectionOf_mul_self, mul_one]
    calc (w : Dual K H ≃ₗ[K] Dual K H) b - b
        = ((w * P.reflectionOf hF.isGeneralizedCartan v i : P.weylGroup _) :
            Dual K H ≃ₗ[K] Dual K H)
            ((P.reflectionOf hF.isGeneralizedCartan v i : Dual K H ≃ₗ[K] Dual K H) b) - b := by
          conv_lhs => rw [e]
          rfl
      _ = P.rootOf (k + (-z) • l) := by
          rw [hrefl, map_sub, map_smul, hβ, map_add, map_zsmul, ← hwk, ← Int.cast_smul_eq_zsmul K,
            Int.cast_neg, neg_smul]
          abel
  · push Not at hex
    rw [eq_one_of_forall_isPosRoot_integral hF hw hex]
    exact ⟨0, le_rfl, by simp⟩

/-- **Humphreys, GSM 94, Prop. 3.5 (c).** If `λ` is antidominant, then `λ ≤ w·λ` for every
`w ∈ W_[λ]`: `w·λ - λ = w(λ + ρ) - (λ + ρ) ∈ Q₊`. -/
theorem IsAntidominant.exists_weylDot_sub_eq_rootOf {μ : Dual K H}
    (hμ : P.IsAntidominant hF.isGeneralizedCartan μ) {w : P.weylGroup hF.isGeneralizedCartan}
    (hw : w ∈ P.integralWeylGroup hF.isGeneralizedCartan μ) :
    ∃ k : ι → ℤ, 0 ≤ k ∧ (w : Dual K H ≃ₗ[K] Dual K H) (μ + P.rho) - (μ + P.rho) =
      P.rootOf k := by
  refine exists_nonneg_apply_sub_eq_rootOf hF hμ ?_
  rwa [P.integralWeylGroup_eq_of_integral _ (μ' := μ) fun j ↦ ⟨1, by simp⟩]

/-- The antidominant weight of a `W_[λ]`-orbit is unique: if `λ` and `w·λ` (`w ∈ W_[λ]`) are both
antidominant, then `w·λ = λ` (Humphreys, GSM 94, Prop. 3.5). -/
theorem IsAntidominant.eq_of_weylDot_eq {μ : Dual K H}
    (hμ : P.IsAntidominant hF.isGeneralizedCartan μ) {w : P.weylGroup hF.isGeneralizedCartan}
    (hw : w ∈ P.integralWeylGroup hF.isGeneralizedCartan μ)
    (hwμ : P.IsAntidominant hF.isGeneralizedCartan
      ((w : Dual K H ≃ₗ[K] Dual K H) (μ + P.rho) - P.rho)) :
    (w : Dual K H ≃ₗ[K] Dual K H) (μ + P.rho) = μ + P.rho := by
  obtain ⟨k, hk, hwk⟩ := hμ.exists_weylDot_sub_eq_rootOf hF hw
  have hw' : w⁻¹ ∈ P.integralWeylGroup hF.isGeneralizedCartan
      ((w : Dual K H ≃ₗ[K] Dual K H) (μ + P.rho) - P.rho) := by
    have e : P.integralWeylGroup hF.isGeneralizedCartan
        ((w : Dual K H ≃ₗ[K] Dual K H) (μ + P.rho) - P.rho) =
        P.integralWeylGroup hF.isGeneralizedCartan μ := by
      refine P.integralWeylGroup_eq_of_integral _ fun j ↦ ?_
      obtain ⟨z, hz⟩ := P.exists_int_of_mem_rootLattice (P.rootOf_mem_rootLattice k) j
      refine ⟨z, ?_⟩
      rw [← hz, ← hwk]
      simp only [LinearMap.sub_apply, LinearMap.add_apply]
      ring
    rw [e]
    exact inv_mem hw
  obtain ⟨l, hl, hwl⟩ := hwμ.exists_weylDot_sub_eq_rootOf hF hw'
  rw [sub_add_cancel, inv_apply_apply] at hwl
  have h0 := P.eq_zero_of_mem_closure_of_neg_mem
    ((P.mem_closure_range_root_iff).mpr ⟨k, hk, hwk.symm⟩)
    ((P.mem_closure_range_root_iff).mpr ⟨l, hl, by rw [← hwl, neg_sub]⟩)
  rwa [sub_eq_zero] at h0

/-- Every `W_[λ]`-orbit (for the dot action) contains an antidominant weight (Humphreys, GSM 94,
§3.5): take `w·λ` with `w·λ - λ ∈ Q` of minimal height. -/
theorem exists_isAntidominant_weylDot (μ : Dual K H) :
    ∃ w ∈ P.integralWeylGroup hF.isGeneralizedCartan μ,
      P.IsAntidominant hF.isGeneralizedCartan
        ((w : Dual K H ≃ₗ[K] Dual K H) (μ + P.rho) - P.rho) := by
  classical
  have : Finite (P.weylGroup hF.isGeneralizedCartan) := P.finite_weylGroup hF
  have : Fintype (P.weylGroup hF.isGeneralizedCartan) := Fintype.ofFinite _
  set b := μ + P.rho with hb
  have hWb : P.integralWeylGroup hF.isGeneralizedCartan μ =
      P.integralWeylGroup hF.isGeneralizedCartan b :=
    P.integralWeylGroup_eq_of_integral _ fun j ↦ ⟨-1, by simp [hb]⟩
  -- the height of `w b - b ∈ Q`
  have hQ : ∀ w ∈ P.integralWeylGroup hF.isGeneralizedCartan b,
      ∃ k, P.rootOf k = (w : Dual K H ≃ₗ[K] Dual K H) b - b := fun w hw ↦
    (P.mem_rootLattice).mp hw
  let ht : P.weylGroup hF.isGeneralizedCartan → ℤ := fun w ↦
    if h : w ∈ P.integralWeylGroup hF.isGeneralizedCartan b then ∑ j, (hQ w h).choose j else 0
  have hht : ∀ w (h : w ∈ P.integralWeylGroup hF.isGeneralizedCartan b) (k : ι → ℤ),
      P.rootOf k = (w : Dual K H ≃ₗ[K] Dual K H) b - b → ht w = ∑ j, k j := by
    intro w h k hk
    simp only [ht, h, ↓reduceDIte]
    rw [P.rootOf_injective ((hQ w h).choose_spec.trans hk.symm)]
  obtain ⟨w, hw, hmin⟩ := (Finset.univ.filter
    (· ∈ P.integralWeylGroup hF.isGeneralizedCartan b)).exists_min_image ht
    ⟨1, Finset.mem_filter.mpr ⟨Finset.mem_univ _, one_mem _⟩⟩
  rw [Finset.mem_filter] at hw
  refine ⟨w, hWb ▸ hw.2, fun v i hv n hn ↦ ?_⟩
  by_contra hpos
  push Not at hpos
  rw [sub_add_cancel] at hn
  -- `s_β w` lowers the height by `n · ht(β) > 0`
  obtain ⟨k, hk⟩ := hQ w hw.2
  obtain ⟨l, hl, hvl⟩ := hv
  have hs : P.reflectionOf hF.isGeneralizedCartan v i * w ∈
      P.integralWeylGroup hF.isGeneralizedCartan b := by
    refine mul_mem ?_ hw.2
    have e : P.integralWeylGroup hF.isGeneralizedCartan ((w : Dual K H ≃ₗ[K] Dual K H) b) =
        P.integralWeylGroup hF.isGeneralizedCartan b :=
      P.integralWeylGroup_eq_of_integral _ (P.exists_int_of_mem_rootLattice hw.2)
    rw [← e]
    exact (P.reflectionOf_mem_integralWeylGroup_iff _ v i).mpr ⟨n, hn⟩
  have hk' : P.rootOf (k - n • l) =
      ((P.reflectionOf hF.isGeneralizedCartan v i * w : P.weylGroup _) :
        Dual K H ≃ₗ[K] Dual K H) b - b := by
    rw [Subgroup.coe_mul, LinearEquiv.mul_apply, reflectionOf_apply', hn, map_sub, map_zsmul, hk,
      ← hvl]
    module
  have h1 := hmin _ (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hs⟩)
  rw [hht _ hs _ hk', hht _ hw.2 _ hk] at h1
  have hl0 : l ≠ 0 := by
    rintro rfl
    rw [map_zero, LinearEquiv.map_eq_zero_iff] at hvl
    exact P.linearIndependent_root.ne_zero i hvl
  obtain ⟨j, hj⟩ := Function.ne_iff.mp hl0
  have hsum : 0 < ∑ j, l j := Finset.sum_pos' (fun j _ ↦ hl j)
    ⟨j, Finset.mem_univ _, lt_of_le_of_ne (hl j) (Ne.symm hj)⟩
  simp only [Pi.sub_apply, Pi.smul_apply, smul_eq_mul, Finset.sum_sub_distrib,
    ← Finset.mul_sum] at h1
  nlinarith

end Matrix.Realization
