/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.LinearAlgebra.Matrix.Cartan.IntegralWeylGroupAntidominant
import LieLean.LinearAlgebra.Matrix.Cartan.WeylGroupForm

/-!
# Facet exclusion for non-integral weights (root-datum form)

Let `A` be a Cartan matrix of finite type with a realization over a field `K` of characteristic
zero. For a weight `b` whose pairings with the coroots of the positive roots integral for `b` are
`≤ 0`, every `w b - b` with `w ∈ W_[b]` is a nonnegative integral combination of positive roots
integral for `b` (`Matrix.Realization.apply_sub_mem_closure_integralPosRoots`). With this, the
norm argument for facet exclusion (`Matrix.Realization.apply_eq_of_add_eq_apply` for integral
weights) extends to arbitrary weights and the integral Weyl group: this is the root-datum core of
Humphreys, GSM 94, Lemma 7.5 (`Matrix.Realization.apply_eq_of_add_eq_apply_integralWeylGroup`).

All comparisons are made between integers (the pairings of `a`, `b` with integral coroots), so no
order on `K` and no auxiliary weight `λ♮` in the real span of the integral roots are needed; the
argument is our own (Humphreys proves Lemma 7.5 by induction on the distance between chambers of
`W_[λ]`).

## References

* J. E. Humphreys, *Representations of semisimple Lie algebras in the BGG category 𝒪*, GSM 94,
  AMS 2008, §7.4, Lemma 7.5.
-/

noncomputable section

open Module CoxeterSystem

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [CharZero K] [AddCommGroup H]
  [Module K H] {A : Matrix ι ι ℤ} {P : Realization A K H} (hF : A.IsFiniteCartan)

variable (P) in
/-- The additive monoid generated by the positive roots integral for `b`. -/
def integralPosRootCone (hA : A.IsGeneralizedCartan) (b : Dual K H) : AddSubmonoid (Dual K H) :=
  AddSubmonoid.closure {x | ∃ v i, P.IsPosRoot hA v i ∧ P.IsIntegralRoot hA b v i ∧
    (v : Dual K H ≃ₗ[K] Dual K H) (P.root i) = x}

/-- If `⟨b, β^∨⟩ ≤ 0` for the positive roots `β` integral for `b`, then `w b - b` lies in the
cone spanned by the positive integral roots, for every `w ∈ W_[b]` (the refinement of
`Matrix.Realization.exists_nonneg_apply_sub_eq_rootOf` with the same induction). -/
theorem apply_sub_mem_integralPosRootCone {b : Dual K H}
    (hb : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i → ∀ n : ℤ,
      P.corootPairing hF.isGeneralizedCartan b v i = n → n ≤ 0)
    {w : P.weylGroup hF.isGeneralizedCartan}
    (hw : w ∈ P.integralWeylGroup hF.isGeneralizedCartan b) :
    (w : Dual K H ≃ₗ[K] Dual K H) b - b ∈ P.integralPosRootCone hF.isGeneralizedCartan b := by
  induction hlen : (P.coxeterSystem hF.isGeneralizedCartan).length w
    using Nat.strong_induction_on generalizing w with
  | _ n ih =>
  by_cases hex : ∃ v i, P.IsPosRoot hF.isGeneralizedCartan v i ∧
      P.IsIntegralRoot hF.isGeneralizedCartan b v i ∧
        ¬P.IsPosRoot hF.isGeneralizedCartan (w * v) i
  · obtain ⟨v, i, hv, ⟨z, hz⟩, hneg⟩ := hex
    have hs : P.reflectionOf hF.isGeneralizedCartan v i ∈
        P.integralWeylGroup hF.isGeneralizedCartan b :=
      (P.reflectionOf_mem_integralWeylGroup_iff _ v i).mpr ⟨z, hz⟩
    have hk := ih _ (hlen ▸ length_mul_reflectionOf_lt hv hneg) (mul_mem hw hs) rfl
    have hpos := (isPosRoot_or (w * v) i).resolve_left hneg
    have hint : P.IsIntegralRoot hF.isGeneralizedCartan b
        (w * v * (P.coxeterSystem hF.isGeneralizedCartan).simple i) i := by
      have h1 := P.isIntegralRoot_mul _ hw ⟨z, hz⟩
      obtain ⟨z', hz'⟩ := h1
      change P.corootPairing _ b (w * v) i = _ at hz'
      refine ⟨-z', ?_⟩
      change P.corootPairing _ b _ i = _
      rw [corootPairing_mul_simple, hz']
      push_cast
      ring
    have hz0 := hb v i hv z hz
    have hβ : ((w * P.reflectionOf hF.isGeneralizedCartan v i : P.weylGroup _) :
        Dual K H ≃ₗ[K] Dual K H) ((v : Dual K H ≃ₗ[K] Dual K H) (P.root i)) =
        ((w * v * (P.coxeterSystem hF.isGeneralizedCartan).simple i : P.weylGroup _) :
          Dual K H ≃ₗ[K] Dual K H) (P.root i) := by
      rw [mul_simple_apply_root, Subgroup.coe_mul, LinearEquiv.mul_apply, reflectionOf_apply',
        corootPairing, inv_apply_apply, P.root_coroot_self hF.isGeneralizedCartan, two_smul,
        sub_add_cancel_left, map_neg]
      rfl
    have hrefl : (P.reflectionOf hF.isGeneralizedCartan v i : Dual K H ≃ₗ[K] Dual K H) b =
        b - (z : K) • (v : Dual K H ≃ₗ[K] Dual K H) (P.root i) := by
      rw [reflectionOf_apply', ← hz]
      rfl
    have e : w = w * P.reflectionOf hF.isGeneralizedCartan v i *
        P.reflectionOf hF.isGeneralizedCartan v i := by
      rw [mul_assoc, reflectionOf_mul_self, mul_one]
    have hsplit : (w : Dual K H ≃ₗ[K] Dual K H) b - b =
        (((w * P.reflectionOf hF.isGeneralizedCartan v i : P.weylGroup _) :
          Dual K H ≃ₗ[K] Dual K H) b - b) + (-z).toNat •
          ((w * v * (P.coxeterSystem hF.isGeneralizedCartan).simple i : P.weylGroup _) :
            Dual K H ≃ₗ[K] Dual K H) (P.root i) := by
      have hzK : (z : K) = -(((-z).toNat : ℕ) : K) := by
        have h' : (((-z).toNat : ℕ) : K) = ((-z : ℤ) : K) := by
          exact_mod_cast Int.toNat_of_nonneg (show 0 ≤ -z by omega)
        rw [h']
        push_cast
        ring
      conv_lhs => rw [e]
      rw [Subgroup.coe_mul _ (w * _), LinearEquiv.mul_apply, hrefl, map_sub, map_smul, hβ,
        ← Nat.cast_smul_eq_nsmul K, hzK]
      module
    rw [hsplit]
    refine add_mem hk (nsmul_mem ?_ _)
    apply AddSubmonoid.subset_closure
    exact ⟨_, i, hpos, hint, rfl⟩
  · push Not at hex
    rw [eq_one_of_forall_isPosRoot_integral hF hw hex]
    simp

variable [FiniteDimensional K H]

/-- The sign and orthogonality properties of the form on the integral root cone: for `x` in the
cone of the positive roots integral for `b`, `(x | a) = n` with `n ∈ ℤ_{≤ 0}`, and `(x | a) = 0`
forces `(x | b) = 0`, as soon as `a - b` is integral, `⟨a, β^∨⟩ ≤ 0` for the positive integral
roots, and every integral root orthogonal to `a` is orthogonal to `b`. -/
lemma bilinForm_integralPosRootCone (S : A.Symmetrization) {a b : Dual K H}
    (hab : ∀ v i, P.IsIntegralRoot hF.isGeneralizedCartan b v i →
      P.IsIntegralRoot hF.isGeneralizedCartan a v i)
    (ha : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i → ∀ n : ℤ,
      P.corootPairing hF.isGeneralizedCartan a v i = n → n ≤ 0)
    (hfacet : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i →
      P.corootPairing hF.isGeneralizedCartan a v i = 0 →
        P.corootPairing hF.isGeneralizedCartan b v i = 0)
    {x : Dual K H} (hx : x ∈ P.integralPosRootCone hF.isGeneralizedCartan b) :
    ∃ q : ℚ, q ≤ 0 ∧ P.dualBilinForm S x a = q ∧
      (q = 0 → P.dualBilinForm S x b = 0) := by
  induction hx using AddSubmonoid.closure_induction with
  | mem x hx =>
    obtain ⟨v, i, hv, hint, rfl⟩ := hx
    obtain ⟨n, hn⟩ := hab v i hint
    change P.corootPairing _ a v i = n at hn
    have hform : ∀ y : Dual K H, P.dualBilinForm S y ((v : Dual K H ≃ₗ[K] Dual K H) (P.root i)) =
        P.corootPairing hF.isGeneralizedCartan y v i / S.ε i := by
      intro y
      rw [← P.dualBilinForm_weylGroup hF.isGeneralizedCartan S (v⁻¹).2, inv_apply_apply,
        dualBilinForm_root_right]
      rfl
    have hsymm := (P.isSymm_dualBilinForm S).eq
    refine ⟨n / S.ε i, ?_, ?_, fun h0 ↦ ?_⟩
    · exact div_nonpos_of_nonpos_of_nonneg (by exact_mod_cast ha v i hv n hn) (S.ε_pos i).le
    · rw [hsymm, hform, hn]
      push_cast
      rfl
    · have hn0 : n = 0 := by
        have := S.ε_ne_zero i
        rw [div_eq_zero_iff] at h0
        exact_mod_cast h0.resolve_right this
      rw [hsymm, hform, hfacet v i hv (by rw [hn, hn0, Int.cast_zero]), zero_div]
  | zero => exact ⟨0, le_rfl, by simp, fun _ ↦ by simp⟩
  | add x y _ _ hx hy =>
    obtain ⟨q₁, hq₁, hx₁, hx₂⟩ := hx
    obtain ⟨q₂, hq₂, hy₁, hy₂⟩ := hy
    refine ⟨q₁ + q₂, add_nonpos hq₁ hq₂, ?_, fun h0 ↦ ?_⟩
    · rw [map_add, LinearMap.add_apply, hx₁, hy₁]
      push_cast
      rfl
    rw [map_add, LinearMap.add_apply, hx₂ (by linarith), hy₂ (by linarith), add_zero]

/-- **Facet exclusion for the integral Weyl group, root-datum form** (the core of Humphreys,
GSM 94, Lemma 7.5, for arbitrary weights). Let `a = λ + ρ`, `b = μ + ρ` with `b - a` integral,
`⟨a, β^∨⟩, ⟨b, β^∨⟩ ≤ 0` for the positive roots `β` integral for `a` (antidominance), and every
integral root orthogonal to `a` orthogonal to `b` (the facet containing `λ` has `μ` in its
closure). Let `ν = z (b - a)` be dominant integral (`z ∈ W`), and `ν₁ = u ν₂` with `u ∈ W`,
`ν₂` dominant integral, `ν - ν₂ ∈ Q₊`. If `a + ν₁ = y b` with `y ∈ W_[b]`, then `y b = b`. -/
theorem apply_eq_of_add_eq_apply_integralWeylGroup {a b : Dual K H}
    (hab : ∀ j, ∃ n : ℤ, (b - a) (P.coroot j) = n)
    (ha : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i → ∀ n : ℤ,
      P.corootPairing hF.isGeneralizedCartan a v i = n → n ≤ 0)
    (hb : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i → ∀ n : ℤ,
      P.corootPairing hF.isGeneralizedCartan b v i = n → n ≤ 0)
    (hfacet : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i →
      P.corootPairing hF.isGeneralizedCartan a v i = 0 →
        P.corootPairing hF.isGeneralizedCartan b v i = 0)
    {z u y : P.weylGroup hF.isGeneralizedCartan}
    (hν : ∀ i, ∃ n : ℕ, (z : Dual K H ≃ₗ[K] Dual K H) (b - a) (P.coroot i) = n)
    {ν₂ : Dual K H} (hν₂ : ∀ i, ∃ n : ℕ, ν₂ (P.coroot i) = n) {c : ι → ℤ} (hc : 0 ≤ c)
    (hνc : (z : Dual K H ≃ₗ[K] Dual K H) (b - a) - ν₂ = P.rootOf c)
    (hy : y ∈ P.integralWeylGroup hF.isGeneralizedCartan b)
    (h : a + (u : Dual K H ≃ₗ[K] Dual K H) ν₂ = (y : Dual K H ≃ₗ[K] Dual K H) b) :
    (y : Dual K H ≃ₗ[K] Dual K H) b = b := by
  classical
  obtain ⟨d, hdpos, hpos⟩ := hF.exists_posDef
  have hsymm : (diagonal d * A).IsSymm := by
    simpa [IsHermitian, IsSymm] using hpos.isHermitian
  set S := Symmetrization.ofDiagonal d hdpos hsymm
  set B := P.dualBilinForm S
  have hB (k : ι → ℤ) (x : Dual K H) := P.dualBilinForm_ofDiagonal_rootOf d hdpos hsymm k x
  have hW (w : P.weylGroup hF.isGeneralizedCartan) (x x' : Dual K H) :
      B ((w : Dual K H ≃ₗ[K] Dual K H) x) ((w : Dual K H ≃ₗ[K] Dual K H) x') = B x x' :=
    P.dualBilinForm_weylGroup hF.isGeneralizedCartan S w.2 x x'
  have hBsymm (x x' : Dual K H) : B x x' = B x' x := (P.isSymm_dualBilinForm S).eq x x'
  -- integrality of `b` and `a` agree
  have hab' : ∀ j, ∃ n : ℤ, (a - b) (P.coroot j) = n := fun j ↦ by
    obtain ⟨n, hn⟩ := hab j
    refine ⟨-n, ?_⟩
    rw [← neg_sub, LinearMap.neg_apply, hn, Int.cast_neg]
  have hint : ∀ v i, P.IsIntegralRoot hF.isGeneralizedCartan b v i →
      P.IsIntegralRoot hF.isGeneralizedCartan a v i := fun v i hbi ↦
    (P.isIntegralRoot_congr _ hab' v i).mpr hbi
  -- `x := y b - b` lies in the integral root cone, and in `Q`
  set x := (y : Dual K H ≃ₗ[K] Dual K H) b - b with hx
  have hxcone := apply_sub_mem_integralPosRootCone hF hb hy
  obtain ⟨e, he⟩ := (P.mem_rootLattice).mp hy
  obtain ⟨q, hq, hxa, hxb⟩ := bilinForm_integralPosRootCone hF S hint ha hfacet hxcone
  choose n2 hn2 using hν₂
  choose nν hnν using hν
  -- `R₁ := |ν|² - |ν₂|² = (ν - ν₂ | ν + ν₂) ≥ 0`.
  set R₁ : ℤ := ∑ i, c i * d i * ((nν i : ℤ) + n2 i) with hR₁
  have hR₁nonneg : 0 ≤ R₁ := Finset.sum_nonneg fun i _ =>
    mul_nonneg (mul_nonneg (hc i) (hdpos i).le) (by positivity)
  have hR₁eq : B ((z : Dual K H ≃ₗ[K] Dual K H) (b - a)) ((z : Dual K H ≃ₗ[K] Dual K H) (b - a))
      - B ν₂ ν₂ = R₁ := by
    have hsplit : (z : Dual K H ≃ₗ[K] Dual K H) (b - a) = ν₂ + P.rootOf c := by
      rw [← hνc]; abel
    calc _ = B (P.rootOf c) ((z : Dual K H ≃ₗ[K] Dual K H) (b - a) + ν₂) := by
          rw [hsplit]
          simp only [map_add, LinearMap.add_apply]
          rw [hBsymm ν₂ (P.rootOf c)]
          ring
      _ = R₁ := by
          rw [hB, hR₁]
          push_cast
          refine Finset.sum_congr rfl fun i _ => ?_
          rw [LinearMap.add_apply, hnν, hn2]
  -- `|b - a|² - |y b - a|² = 2 (x | a) = 2 q ≤ 0`.
  have h1 : B ((y : Dual K H ≃ₗ[K] Dual K H) b) ((y : Dual K H ≃ₗ[K] Dual K H) b) = B b b :=
    hW y b b
  have hyb : (y : Dual K H ≃ₗ[K] Dual K H) b = b + x := by rw [hx]; abel
  have hR₂eq : B (b - a) (b - a) - B ((y : Dual K H ≃ₗ[K] Dual K H) b - a)
      ((y : Dual K H ≃ₗ[K] Dual K H) b - a) = 2 * q := by
    rw [hyb] at h1 ⊢
    simp only [map_add, map_sub, LinearMap.add_apply, LinearMap.sub_apply] at h1 ⊢
    rw [hBsymm b a, hBsymm b x, hBsymm a x, hxa] at *
    linear_combination (-1 : K) * h1
  have hR : (R₁ : K) = 2 * q := by
    have h3 : (y : Dual K H ≃ₗ[K] Dual K H) b - a = (u : Dual K H ≃ₗ[K] Dual K H) ν₂ := by
      rw [← h]; abel
    rw [← hR₁eq, ← hR₂eq, hW z, h3, hW u]
  have hq0 : q = 0 := by
    have : ((R₁ : ℚ) : K) = ((2 * q : ℚ) : K) := by push_cast; exact hR
    have h' : (R₁ : ℚ) = 2 * q := by exact_mod_cast this
    have : (0 : ℚ) ≤ R₁ := by exact_mod_cast hR₁nonneg
    linarith
  -- so `(x | b) = 0` and `|x|² = 0`
  have hxx : B x x = 0 := by
    rw [hyb] at h1
    simp only [map_add, LinearMap.add_apply] at h1
    rw [hBsymm b x, hxb hq0] at h1
    linear_combination h1
  have he0 : e = 0 := by
    by_contra hne
    have hqd := hpos.dotProduct_mulVec_pos hne
    rw [hx, ← he, hB] at hxx
    have hcast : ((e ⬝ᵥ (diagonal d * A) *ᵥ e : ℤ) : K) = 0 := by
      rw [← hxx, ← mulVec_mulVec, dotProduct]
      simp only [mulVec_diagonal]
      push_cast
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [rootOf_apply_coroot]
      ring
    simp only [star_trivial] at hqd
    exact hqd.ne' (by exact_mod_cast hcast)
  rw [← sub_eq_zero, ← he, he0, map_zero]


/-! ### Stabilizers and the roots orthogonal to a weight -/

section Orth

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [CharZero K] [AddCommGroup H]
  [Module K H] {A : Matrix ι ι ℤ} {P : Realization A K H}

variable (P) in
/-- The additive monoid generated by the positive roots orthogonal to `b`. -/
def orthPosRootCone (hA : A.IsGeneralizedCartan) (b : Dual K H) : AddSubmonoid (Dual K H) :=
  AddSubmonoid.closure {x | ∃ v i, (P.IsPosRoot hA v i ∧ P.corootPairing hA b v i = 0) ∧
    (v : Dual K H ≃ₗ[K] Dual K H) (P.root i) = x}

omit [DecidableEq ι] in
/-- Every `w ∈ W` factors as `w = w₁ u₁` with `u₁ b = b` and `w₁ β > 0` for every positive root
`β` orthogonal to `b` (take `w₁` of minimal length in `w · Stab(b)`). -/
theorem exists_mul_eq_isPosRoot_of_orth {hA : A.IsGeneralizedCartan} (b : Dual K H)
    (w : P.weylGroup hA) :
    ∃ w₁ u₁ : P.weylGroup hA, w = w₁ * u₁ ∧ (u₁ : Dual K H ≃ₗ[K] Dual K H) b = b ∧
      ∀ v i, P.IsPosRoot hA v i → P.corootPairing hA b v i = 0 → P.IsPosRoot hA (w₁ * v) i := by
  classical
  induction hn : (P.coxeterSystem hA).length w using Nat.strong_induction_on generalizing w with
  | _ n ih =>
  by_cases hex : ∃ v i, P.IsPosRoot hA v i ∧ P.corootPairing hA b v i = 0 ∧
      ¬P.IsPosRoot hA (w * v) i
  · obtain ⟨v, i, hv, hb0, hneg⟩ := hex
    obtain ⟨w₁, u₁, hw, hu, hpos⟩ :=
      ih _ (hn ▸ length_mul_reflectionOf_lt hv hneg) (w * P.reflectionOf hA v i) rfl
    refine ⟨w₁, u₁ * P.reflectionOf hA v i, ?_, ?_, hpos⟩
    · rw [← mul_assoc, ← hw, mul_assoc, reflectionOf_mul_self, mul_one]
    · rw [Subgroup.coe_mul, LinearEquiv.mul_apply, reflectionOf_apply', hb0, zero_smul,
        sub_zero, hu]
  · push Not at hex
    exact ⟨w, 1, (mul_one w).symm, rfl, hex⟩

variable (hF : A.IsFiniteCartan)

/-- For a weight `μ` there is `t ≠ 0` such that the roots integral for `t μ` are exactly the
roots orthogonal to `μ`. -/
theorem exists_smul_isIntegralRoot_iff (μ : Dual K H) :
    ∃ t : K, t ≠ 0 ∧ ∀ v i, P.IsIntegralRoot hF.isGeneralizedCartan (t • μ) v i ↔
      P.corootPairing hF.isGeneralizedCartan μ v i = 0 := by
  classical
  have : Finite (P.weylGroup hF.isGeneralizedCartan) := P.finite_weylGroup hF
  have : Fintype (P.weylGroup hF.isGeneralizedCartan) := Fintype.ofFinite _
  let f : P.weylGroup hF.isGeneralizedCartan × ι → ℕ := fun p ↦
    if h : ∃ z : ℤ, P.corootPairing hF.isGeneralizedCartan μ p.1 p.2 = z then h.choose.natAbs
    else 0
  set M : ℕ := ∑ p, f p + 1
  have hM : ∀ v i (z : ℤ), P.corootPairing hF.isGeneralizedCartan μ v i = z → z.natAbs < M := by
    intro v i z hz
    have h : ∃ z : ℤ, P.corootPairing hF.isGeneralizedCartan μ v i = z := ⟨z, hz⟩
    have hzc : h.choose = z := by exact_mod_cast h.choose_spec.symm.trans hz
    have : f (v, i) = z.natAbs := by simp only [f, h, ↓reduceDIte, hzc]
    have hle : f (v, i) ≤ ∑ p, f p := Finset.single_le_sum (fun _ _ ↦ Nat.zero_le _)
      (Finset.mem_univ (v, i))
    omega
  have hM0 : (M : K) ≠ 0 := Nat.cast_ne_zero.mpr (Nat.succ_ne_zero _)
  refine ⟨(M : K)⁻¹, inv_ne_zero hM0, fun v i ↦ ⟨fun ⟨z, hz⟩ ↦ ?_, fun h0 ↦ ⟨0, ?_⟩⟩⟩
  · change P.corootPairing hF.isGeneralizedCartan ((M : K)⁻¹ • μ) v i = z at hz
    rw [corootPairing_smul] at hz
    have hμ : P.corootPairing hF.isGeneralizedCartan μ v i = ((M * z : ℤ) : K) := by
      push_cast
      rw [← hz]
      field_simp
    have h1 := hM v i _ hμ
    have hz0 : z = 0 := by
      by_contra hz0
      rw [Int.natAbs_mul, Int.natAbs_natCast] at h1
      have : 1 ≤ z.natAbs := Int.natAbs_pos.mpr hz0
      nlinarith
    rw [hμ, hz0, mul_zero, Int.cast_zero]
  · change P.corootPairing hF.isGeneralizedCartan ((M : K)⁻¹ • μ) v i = _
    rw [corootPairing_smul, h0, mul_zero, Int.cast_zero]

/-- An element of the stabilizer of `b` mapping every positive root orthogonal to `b` to a
positive root is `1`. -/
theorem eq_one_of_apply_eq_of_forall_isPosRoot {b : Dual K H}
    {v : P.weylGroup hF.isGeneralizedCartan} (hvb : (v : Dual K H ≃ₗ[K] Dual K H) b = b)
    (hpos : ∀ u i, P.IsPosRoot hF.isGeneralizedCartan u i →
      P.corootPairing hF.isGeneralizedCartan b u i = 0 →
        P.IsPosRoot hF.isGeneralizedCartan (v * u) i) : v = 1 := by
  obtain ⟨t, -, ht⟩ := exists_smul_isIntegralRoot_iff (P := P) hF b
  refine eq_one_of_forall_isPosRoot_integral hF (μ := t • b) ?_
    fun u i hu hint ↦ hpos u i hu ((ht u i).mp hint)
  rw [mem_integralWeylGroup, map_smul, hvb, sub_self]
  exact zero_mem _

/-- If `⟨a, β^∨⟩ ∈ ℤ_{≤ 0}` for the positive roots `β` orthogonal to `b`, then `v a - a` lies in
the cone of the positive roots orthogonal to `b`, for every `v ∈ W` fixing `b`. -/
theorem apply_sub_mem_orthPosRootCone {a b : Dual K H}
    (ha : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i →
      P.corootPairing hF.isGeneralizedCartan b v i = 0 →
        ∃ n : ℤ, n ≤ 0 ∧ P.corootPairing hF.isGeneralizedCartan a v i = n)
    {v : P.weylGroup hF.isGeneralizedCartan} (hvb : (v : Dual K H ≃ₗ[K] Dual K H) b = b) :
    (v : Dual K H ≃ₗ[K] Dual K H) a - a ∈ P.orthPosRootCone hF.isGeneralizedCartan b := by
  induction hlen : (P.coxeterSystem hF.isGeneralizedCartan).length v
    using Nat.strong_induction_on generalizing v with
  | _ n ih =>
  by_cases hex : ∃ u i, P.IsPosRoot hF.isGeneralizedCartan u i ∧
      P.corootPairing hF.isGeneralizedCartan b u i = 0 ∧
        ¬P.IsPosRoot hF.isGeneralizedCartan (v * u) i
  · obtain ⟨u, i, hu, hb0, hneg⟩ := hex
    obtain ⟨z, hz0, hz⟩ := ha u i hu hb0
    have hsb : (P.reflectionOf hF.isGeneralizedCartan u i : Dual K H ≃ₗ[K] Dual K H) b = b := by
      rw [reflectionOf_apply', hb0, zero_smul, sub_zero]
    have hv'b : ((v * P.reflectionOf hF.isGeneralizedCartan u i : P.weylGroup _) :
        Dual K H ≃ₗ[K] Dual K H) b = b := by
      rw [Subgroup.coe_mul, LinearEquiv.mul_apply, hsb, hvb]
    have hk := ih _ (hlen ▸ length_mul_reflectionOf_lt hu hneg) hv'b rfl
    have hpos := (isPosRoot_or (v * u) i).resolve_left hneg
    have hvinv : ((v⁻¹ : P.weylGroup _) : Dual K H ≃ₗ[K] Dual K H) b = b := by
      conv_lhs => rw [← hvb]
      exact inv_apply_apply v b
    have horth : P.corootPairing hF.isGeneralizedCartan b
        (v * u * (P.coxeterSystem hF.isGeneralizedCartan).simple i) i = 0 := by
      rw [corootPairing_mul_simple, ← _root_.inv_inv v, ← corootPairing_apply, hvinv, hb0,
        neg_zero]
    have hβ : ((v * P.reflectionOf hF.isGeneralizedCartan u i : P.weylGroup _) :
        Dual K H ≃ₗ[K] Dual K H) ((u : Dual K H ≃ₗ[K] Dual K H) (P.root i)) =
        ((v * u * (P.coxeterSystem hF.isGeneralizedCartan).simple i : P.weylGroup _) :
          Dual K H ≃ₗ[K] Dual K H) (P.root i) := by
      rw [mul_simple_apply_root, Subgroup.coe_mul, LinearEquiv.mul_apply, reflectionOf_apply',
        corootPairing, inv_apply_apply, P.root_coroot_self hF.isGeneralizedCartan, two_smul,
        sub_add_cancel_left, map_neg]
      rfl
    have e : v = v * P.reflectionOf hF.isGeneralizedCartan u i *
        P.reflectionOf hF.isGeneralizedCartan u i := by
      rw [mul_assoc, reflectionOf_mul_self, mul_one]
    have hzK : (z : K) = -(((-z).toNat : ℕ) : K) := by
      have h' : (((-z).toNat : ℕ) : K) = ((-z : ℤ) : K) := by
        exact_mod_cast Int.toNat_of_nonneg (show 0 ≤ -z by omega)
      rw [h']
      push_cast
      ring
    have hsplit : (v : Dual K H ≃ₗ[K] Dual K H) a - a =
        (((v * P.reflectionOf hF.isGeneralizedCartan u i : P.weylGroup _) :
          Dual K H ≃ₗ[K] Dual K H) a - a) + (-z).toNat •
          ((v * u * (P.coxeterSystem hF.isGeneralizedCartan).simple i : P.weylGroup _) :
            Dual K H ≃ₗ[K] Dual K H) (P.root i) := by
      conv_lhs => rw [e]
      rw [Subgroup.coe_mul _ (v * _), LinearEquiv.mul_apply, reflectionOf_apply', hz, map_sub,
        map_smul, hβ, ← Nat.cast_smul_eq_nsmul K, hzK]
      module
    rw [hsplit]
    refine add_mem hk (nsmul_mem ?_ _)
    apply AddSubmonoid.subset_closure
    exact ⟨_, i, ⟨hpos, horth⟩, rfl⟩
  · push Not at hex
    rw [eq_one_of_apply_eq_of_forall_isPosRoot hF hvb hex]
    simp

variable [FiniteDimensional K H]

omit [DecidableEq ι] in
/-- On a cone generated by roots `β` with `⟨c, β^∨⟩ ∈ ℤ_{≤ 0}`, the form `(· | c)` takes values
in `ℚ_{≤ 0}`, and it vanishes only if `(· | c')` vanishes, provided `⟨c', β^∨⟩ = 0` for the
generators with `⟨c, β^∨⟩ = 0`. -/
lemma bilinForm_mem_closure_nonpos {hA : A.IsGeneralizedCartan} (S : A.Symmetrization)
    {G : P.weylGroup hA → ι → Prop} {c c' : Dual K H}
    (hG : ∀ v i, G v i → ∃ n : ℤ, n ≤ 0 ∧ P.corootPairing hA c v i = n ∧
      (n = 0 → P.corootPairing hA c' v i = 0))
    {x : Dual K H} (hx : x ∈ AddSubmonoid.closure
      {y | ∃ v i, G v i ∧ (v : Dual K H ≃ₗ[K] Dual K H) (P.root i) = y}) :
    ∃ q : ℚ, q ≤ 0 ∧ P.dualBilinForm S x c = q ∧ (q = 0 → P.dualBilinForm S x c' = 0) := by
  induction hx using AddSubmonoid.closure_induction with
  | mem x hx =>
    obtain ⟨v, i, hv, rfl⟩ := hx
    obtain ⟨n, hn0, hn, hc'⟩ := hG v i hv
    have hform : ∀ y : Dual K H, P.dualBilinForm S y ((v : Dual K H ≃ₗ[K] Dual K H) (P.root i)) =
        P.corootPairing hA y v i / S.ε i := by
      intro y
      rw [← P.dualBilinForm_weylGroup hA S (v⁻¹).2, inv_apply_apply, dualBilinForm_root_right]
      rfl
    have hsymm := (P.isSymm_dualBilinForm S).eq
    refine ⟨n / S.ε i, div_nonpos_of_nonpos_of_nonneg (by exact_mod_cast hn0) (S.ε_pos i).le,
      ?_, fun h0 ↦ ?_⟩
    · rw [hsymm, hform, hn]
      push_cast
      rfl
    · have hn' : n = 0 := by
        rw [div_eq_zero_iff] at h0
        exact_mod_cast h0.resolve_right (S.ε_ne_zero i)
      rw [hsymm, hform, hc' hn', zero_div]
  | zero => exact ⟨0, le_rfl, by simp, fun _ ↦ by simp⟩
  | add x y _ _ hx hy =>
    obtain ⟨q₁, hq₁, hx₁, hx₂⟩ := hx
    obtain ⟨q₂, hq₂, hy₁, hy₂⟩ := hy
    refine ⟨q₁ + q₂, add_nonpos hq₁ hq₂, ?_, fun h0 ↦ ?_⟩
    · rw [map_add, LinearMap.add_apply, hx₁, hy₁]
      push_cast
      rfl
    rw [map_add, LinearMap.add_apply, hx₂ (by linarith), hy₂ (by linarith), add_zero]

/-- **The stabilizer of `b` fixes the "antidominant" weights on the walls of `b`.** Let `a - b` be
integral, `⟨a, β^∨⟩ ∈ ℤ_{≤ 0}` for the positive roots `β` orthogonal to `b`, and `u ∈ W` with
`u b = b` and `⟨u a, β^∨⟩ ∈ ℤ_{≤ 0}` for the same roots. Then `u a = a` (norm argument). -/
theorem apply_eq_self_of_apply_eq_of_orth {a b : Dual K H}
    (hab : ∀ j, ∃ n : ℤ, (a - b) (P.coroot j) = n)
    (ha : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i →
      P.corootPairing hF.isGeneralizedCartan b v i = 0 →
        ∃ n : ℤ, n ≤ 0 ∧ P.corootPairing hF.isGeneralizedCartan a v i = n)
    {u : P.weylGroup hF.isGeneralizedCartan} (hub : (u : Dual K H ≃ₗ[K] Dual K H) b = b)
    (hua : ∀ v i, P.IsPosRoot hF.isGeneralizedCartan v i →
      P.corootPairing hF.isGeneralizedCartan b v i = 0 →
        ∃ n : ℤ, n ≤ 0 ∧
          P.corootPairing hF.isGeneralizedCartan ((u : Dual K H ≃ₗ[K] Dual K H) a) v i = n) :
    (u : Dual K H ≃ₗ[K] Dual K H) a = a := by
  classical
  obtain ⟨d, hdpos, hpos⟩ := hF.exists_posDef
  have hsymm : (diagonal d * A).IsSymm := by
    simpa [IsHermitian, IsSymm] using hpos.isHermitian
  set S := Symmetrization.ofDiagonal d hdpos hsymm
  set B := P.dualBilinForm S
  have hBsymm (x x' : Dual K H) : B x x' = B x' x := (P.isSymm_dualBilinForm S).eq x x'
  have hx := apply_sub_mem_orthPosRootCone hF ha hub
  have hG1 : ∀ v i, (P.IsPosRoot hF.isGeneralizedCartan v i ∧
      P.corootPairing hF.isGeneralizedCartan b v i = 0) → ∃ n : ℤ, n ≤ 0 ∧
        P.corootPairing hF.isGeneralizedCartan a v i = n ∧
          (n = 0 → P.corootPairing hF.isGeneralizedCartan a v i = 0) := fun v i ⟨hv, hb⟩ ↦ by
    obtain ⟨n, hn, hn'⟩ := ha v i hv hb
    exact ⟨n, hn, hn', fun h0 ↦ by rw [hn', h0, Int.cast_zero]⟩
  have hG2 : ∀ v i, (P.IsPosRoot hF.isGeneralizedCartan v i ∧
      P.corootPairing hF.isGeneralizedCartan b v i = 0) → ∃ n : ℤ, n ≤ 0 ∧
        P.corootPairing hF.isGeneralizedCartan ((u : Dual K H ≃ₗ[K] Dual K H) a) v i = n ∧
          (n = 0 → P.corootPairing hF.isGeneralizedCartan
            ((u : Dual K H ≃ₗ[K] Dual K H) a) v i = 0) := fun v i ⟨hv, hb⟩ ↦ by
    obtain ⟨n, hn, hn'⟩ := hua v i hv hb
    exact ⟨n, hn, hn', fun h0 ↦ by rw [hn', h0, Int.cast_zero]⟩
  obtain ⟨q₁, hq₁, h₁, -⟩ := bilinForm_mem_closure_nonpos S hG1 hx
  obtain ⟨q₂, hq₂, h₂, -⟩ := bilinForm_mem_closure_nonpos S hG2 hx
  have hW : B ((u : Dual K H ≃ₗ[K] Dual K H) a) ((u : Dual K H ≃ₗ[K] Dual K H) a) = B a a :=
    P.dualBilinForm_weylGroup hF.isGeneralizedCartan S u.2 a a
  have hsum : ((q₁ + q₂ : ℚ) : K) = 0 := by
    push_cast
    rw [← h₁, ← h₂]
    simp only [map_sub, LinearMap.sub_apply]
    rw [hBsymm a ((u : Dual K H ≃ₗ[K] Dual K H) a)]
    linear_combination hW
  have hq : q₁ + q₂ = 0 := by exact_mod_cast hsum
  have hq₁0 : q₁ = 0 := by linarith
  have hq₂0 : q₂ = 0 := by linarith
  have hxx : B ((u : Dual K H ≃ₗ[K] Dual K H) a - a) ((u : Dual K H ≃ₗ[K] Dual K H) a - a) = 0 := by
    rw [map_sub (B ((u : Dual K H ≃ₗ[K] Dual K H) a - a)), h₁, h₂, hq₁0, hq₂0]
    simp
  have hxQ : (u : Dual K H ≃ₗ[K] Dual K H) a - a ∈ P.rootLattice := by
    have e : (u : Dual K H ≃ₗ[K] Dual K H) a - a =
        (u : Dual K H ≃ₗ[K] Dual K H) (a - b) - (a - b) := by
      rw [map_sub, hub]
      abel
    rw [e]
    exact P.apply_sub_mem_rootLattice_of_integral hF.isGeneralizedCartan u.2 hab
  obtain ⟨k, hk⟩ := (P.mem_rootLattice).mp hxQ
  have hk0 : k = 0 := by
    by_contra hne
    have hqd := hpos.dotProduct_mulVec_pos hne
    rw [← hk, P.dualBilinForm_ofDiagonal_rootOf d hdpos hsymm] at hxx
    have hcast : ((k ⬝ᵥ (diagonal d * A) *ᵥ k : ℤ) : K) = 0 := by
      rw [← hxx, ← mulVec_mulVec, dotProduct]
      simp only [mulVec_diagonal]
      push_cast
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [rootOf_apply_coroot]
      ring
    simp only [star_trivial] at hqd
    exact hqd.ne' (by exact_mod_cast hcast)
  rw [← sub_eq_zero, ← hk, hk0, map_zero]

end Orth

end Matrix.Realization
