/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.LinearAlgebra.Matrix.Cartan.WeylGroupCoxeter

/-!
# The fundamental chamber and the Tits cone

Let `A` be a generalized Cartan matrix with realization `(𝔥, Π, Π^∨)` over a linearly ordered
field `K`, and let `W` be its Weyl group, acting on `𝔥*`. The *dominant (fundamental) chamber* is
`C = {λ ∈ 𝔥* | ⟨λ, αᵢ^∨⟩ ≥ 0 for all i}` and the *Tits cone* is `X = ⋃_{w ∈ W} w(C)`.

[Kac] §3.12 (check) works over `ℝ` with the action of `W` on `𝔥_ℝ` (via the fundamental
reflections `rᵢ^∨`) and the chamber `{h | ⟨αᵢ, h⟩ ≥ 0}`. We work dually, with the action of `W` on
`𝔥*` and the chamber `C` above; this is the form used for weights (e.g. in the Weyl–Kac character
formula). The statements are the same after exchanging the roles of `A` and `Aᵀ`, but the proofs
below are written directly for `𝔥*`: they use the Coxeter structure of `W`
(`Matrix.Realization.coxeterSystem`) and the characterization of right descents by the sign of
`w αᵢ` (`Matrix.Realization.isRightDescent_coxeterSystem_iff`).

The key identity is `λ - (w rᵢ) λ = (λ - w λ) + ⟨λ, αᵢ^∨⟩ w αᵢ`. If `ℓ(w rᵢ) > ℓ(w)`, then
`w αᵢ ∈ Q₊`, so by induction on `ℓ(w)`, `λ - w λ` is a nonnegative combination of simple roots
for `λ ∈ C`. If moreover `(w rᵢ) λ = λ`, both summands vanish, since the cone of nonnegative
combinations of the linearly independent `αᵢ` is pointed; hence `⟨λ, αᵢ^∨⟩ = 0`, and induction
shows that the stabilizer of `λ` is generated by the `rᵢ` it contains. These arguments are
reconstructed (they are the standard ones, cf. [Hum] §1.12, §5.13) rather than copied from [Kac].

## Main definitions

* `Matrix.Realization.dominantChamber`: the chamber `C = {λ | ∀ i, ⟨λ, αᵢ^∨⟩ ≥ 0}`.
* `Matrix.Realization.titsCone`: the Tits cone `X = ⋃_{w ∈ W} w(C)`.

## Main results

* `Matrix.Realization.exists_nonneg_sub_apply_eq_sum`: for `λ ∈ C` and `w ∈ W`,
  `λ - w λ = ∑ cᵢ αᵢ` with all `cᵢ ≥ 0`; conversely this characterizes `C`
  (`Matrix.Realization.mem_dominantChamber_iff_forall_exists_nonneg`, [Kac] Prop. 3.12 (d)
  (check), dually).
* `Matrix.Realization.stabilizer_eq_closure_reflection`: for `λ ∈ C`, the stabilizer of `λ` in
  `W` is generated by the fundamental reflections `rᵢ` with `⟨λ, αᵢ^∨⟩ = 0`
  ([Kac] Prop. 3.12 (a) (check)).
* `Matrix.Realization.eq_one_of_apply_eq_self_of_forall_pos`: an element of `W` fixing a point of
  the open chamber `{λ | ∀ i, ⟨λ, αᵢ^∨⟩ > 0}` is `1`.
* `Matrix.Realization.eq_of_apply_eq_of_mem_dominantChamber`: if `λ, μ ∈ C` and `w λ = μ` for
  some `w ∈ W`, then `λ = μ`; so `C` is a fundamental domain for the action of `W` on the Tits
  cone (`Matrix.Realization.existsUnique_mem_dominantChamber`, [Kac] Prop. 3.12 (b) (check)).

The description of the Tits cone by finiteness of the set of positive real coroots on which a
point is negative, and its convexity ([Kac] Prop. 3.12 (c) (check)), are in
`LieLean.LinearAlgebra.Matrix.Cartan.TitsCone.Convex`.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §3.12.
* [Hum] J. E. Humphreys, *Reflection groups and Coxeter groups*, CUP 1990, §1.12, §5.13.
-/

open Module CoxeterSystem

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [Field K] [LinearOrder K] [IsStrictOrderedRing K]
  [AddCommGroup H] [Module K H] {A : Matrix ι ι ℤ} (P : Realization A K H)
  (hA : A.IsGeneralizedCartan)

/-- The dominant (fundamental) chamber `C = {λ ∈ 𝔥* | ⟨λ, αᵢ^∨⟩ ≥ 0 for all i}`
([Kac] §3.12 (check), dually: Kac's chamber lies in `𝔥_ℝ`). -/
def dominantChamber : Set (Dual K H) :=
  {μ | ∀ i, 0 ≤ μ (P.coroot i)}

/-- The Tits cone `X = ⋃_{w ∈ W} w(C)` ([Kac] §3.12 (check), dually: Kac's Tits cone lies in
`𝔥_ℝ`). -/
def titsCone : Set (Dual K H) :=
  {μ | ∃ w ∈ P.weylGroup hA, ∃ ν ∈ P.dominantChamber, w ν = μ}

omit [IsStrictOrderedRing K] in
lemma mem_dominantChamber {μ : Dual K H} :
    μ ∈ P.dominantChamber ↔ ∀ i, 0 ≤ μ (P.coroot i) :=
  Iff.rfl

/-! ### The pointed cone of nonnegative combinations of simple roots -/

/-- The cone of nonnegative combinations of the (linearly independent) simple roots is pointed:
if `∑ cᵢ αᵢ + ∑ dᵢ αᵢ = 0` with all `cᵢ, dᵢ ≥ 0`, then `c = d = 0`. -/
lemma eq_zero_of_sum_smul_root_add_sum_smul_root_eq_zero {c d : ι → K} (hc : 0 ≤ c)
    (hd : 0 ≤ d) (h : ∑ i, c i • P.root i + ∑ i, d i • P.root i = 0) : c = 0 ∧ d = 0 := by
  rw [← Finset.sum_add_distrib] at h
  simp_rw [← add_smul] at h
  have h0 := Fintype.linearIndependent_iff.mp P.linearIndependent_root _ h
  have hc0 : c = 0 := funext fun i ↦ by
    have := hc i; have := hd i; have := h0 i
    simp only [Pi.zero_apply] at *
    linarith
  refine ⟨hc0, funext fun i ↦ ?_⟩
  have := h0 i
  simp only [hc0, Pi.zero_apply, zero_add] at this
  exact this

omit [LinearOrder K] [IsStrictOrderedRing K] in
/-- `λ - (v rᵢ) λ = (λ - v λ) + ⟨λ, αᵢ^∨⟩ v αᵢ`. -/
lemma sub_mul_reflection_apply (v : Dual K H ≃ₗ[K] Dual K H) (i : ι) (μ : Dual K H) :
    μ - (v * P.reflection hA i) μ = (μ - v μ) + μ (P.coroot i) • v (P.root i) := by
  rw [LinearEquiv.mul_apply, reflection_apply, map_sub, map_smul]
  abel

omit [LinearOrder K] [IsStrictOrderedRing K] in
/-- Induction on the length in the Weyl group: a property of elements of `W` which holds for `1`
and passes from `w` to `w rᵢ` whenever `ℓ(w rᵢ) > ℓ(w)` holds on `W`. -/
lemma weylGroup_induction_length [DecidableEq ι] [CharZero K] {p : P.weylGroup hA → Prop}
    (one : p 1)
    (step : ∀ w i, ¬(P.coxeterSystem hA).IsRightDescent w i → p w →
      p (w * (P.coxeterSystem hA).simple i))
    (w : P.weylGroup hA) : p w := by
  set cs := P.coxeterSystem hA
  generalize hn : cs.length w = n
  induction n using Nat.strong_induction_on generalizing w with
  | _ n ih =>
  by_cases hw1 : w = 1
  · exact hw1 ▸ one
  obtain ⟨i, hi⟩ := cs.exists_rightDescent_of_ne_one hw1
  have hnd : ¬cs.IsRightDescent (w * cs.simple i) i := by
    rwa [← isRightDescent_iff_not_isRightDescent_mul]
  have := step _ i hnd (ih _ (hn ▸ hi) _ rfl)
  rwa [cs.simple_mul_simple_cancel_right] at this

/-! ### `λ - w λ ≥ 0` for `λ ∈ C` -/

/-- For `λ ∈ C` and `w ∈ W`, `λ - w λ` is a nonnegative combination of simple roots:
`λ - w λ = ∑ cᵢ αᵢ` with `cᵢ ≥ 0` ([Kac] Prop. 3.12 (d) (check), for the action on `𝔥*`; the
case of dominant integral `λ` is `Matrix.Realization.exists_sub_apply_eq_rootOf`). -/
theorem exists_nonneg_sub_apply_eq_sum {μ : Dual K H} (hμ : μ ∈ P.dominantChamber)
    {w : Dual K H ≃ₗ[K] Dual K H} (hw : w ∈ P.weylGroup hA) :
    ∃ c : ι → K, 0 ≤ c ∧ μ - w μ = ∑ i, c i • P.root i := by
  classical
  suffices ∀ w : P.weylGroup hA, ∃ c : ι → K, 0 ≤ c ∧
      μ - (w : Dual K H ≃ₗ[K] Dual K H) μ = ∑ i, c i • P.root i from this ⟨w, hw⟩
  refine P.weylGroup_induction_length hA ⟨0, le_rfl, by simp⟩ fun w i hwi ⟨c, hc, hwc⟩ ↦ ?_
  obtain ⟨l, hl, hwl⟩ := (P.not_isRightDescent_coxeterSystem_iff hA).mp hwi
  refine ⟨c + μ (P.coroot i) • fun j ↦ (l j : K),
    add_nonneg hc (smul_nonneg (hμ i) fun j ↦ by simpa using hl j), ?_⟩
  rw [Subgroup.coe_mul, coxeterSystem_simple, sub_mul_reflection_apply, hwc, hwl, rootOf_apply,
    Finset.smul_sum]
  simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul, add_smul, Finset.sum_add_distrib,
    mul_smul]

/-- **Characterization of the chamber** ([Kac] Prop. 3.12 (d) (check), for the action on `𝔥*`):
`λ ∈ C` if and only if for every `w ∈ W`, `λ - w λ` is a nonnegative combination of simple
roots. -/
theorem mem_dominantChamber_iff_forall_exists_nonneg {μ : Dual K H} :
    μ ∈ P.dominantChamber ↔ ∀ w ∈ P.weylGroup hA,
      ∃ c : ι → K, 0 ≤ c ∧ μ - w μ = ∑ i, c i • P.root i := by
  classical
  refine ⟨fun hμ _ hw ↦ P.exists_nonneg_sub_apply_eq_sum hA hμ hw, fun h i ↦ ?_⟩
  obtain ⟨c, hc, hci⟩ := h _ (P.reflection_mem_weylGroup hA i)
  rw [reflection_apply, sub_sub_cancel] at hci
  have h0 := Fintype.linearIndependent_iff.mp P.linearIndependent_root
    (fun j ↦ c j - if j = i then μ (P.coroot i) else 0) (by
      simp only [sub_smul, Finset.sum_sub_distrib, ite_smul, zero_smul, Finset.sum_ite_eq',
        Finset.mem_univ, ↓reduceIte, ← hci, sub_self]) i
  simp only [↓reduceIte, sub_eq_zero] at h0
  exact h0 ▸ hc i

/-! ### Stabilizers -/

/-- The stabilizer of a point `λ ∈ C` in `W` is generated by the fundamental reflections it
contains, i.e. by the `rᵢ` with `⟨λ, αᵢ^∨⟩ = 0` ([Kac] Prop. 3.12 (a) (check), for the action on
`𝔥*`). -/
theorem mem_closure_reflection_of_apply_eq_self {μ : Dual K H} (hμ : μ ∈ P.dominantChamber)
    {w : Dual K H ≃ₗ[K] Dual K H} (hw : w ∈ P.weylGroup hA) (hwμ : w μ = μ) :
    w ∈ Subgroup.closure (P.reflection hA '' {i | μ (P.coroot i) = 0}) := by
  classical
  suffices ∀ w : P.weylGroup hA, (w : Dual K H ≃ₗ[K] Dual K H) μ = μ →
      (w : Dual K H ≃ₗ[K] Dual K H) ∈
        Subgroup.closure (P.reflection hA '' {i | μ (P.coroot i) = 0})
    from this ⟨w, hw⟩ hwμ
  refine P.weylGroup_induction_length hA (fun _ ↦ one_mem _) fun w i hwi ih hwiμ ↦ ?_
  obtain ⟨l, hl, hwl⟩ := (P.not_isRightDescent_coxeterSystem_iff hA).mp hwi
  obtain ⟨c, hc, hwc⟩ := P.exists_nonneg_sub_apply_eq_sum hA hμ w.2
  rw [Subgroup.coe_mul, coxeterSystem_simple] at hwiμ ⊢
  -- `0 = λ - (w rᵢ) λ = (λ - w λ) + ⟨λ, αᵢ^∨⟩ w αᵢ`, a sum of two elements of the pointed cone
  have h0 := P.sub_mul_reflection_apply hA w i μ
  rw [hwiμ, sub_self, hwc, hwl, rootOf_apply, Finset.smul_sum] at h0
  simp_rw [smul_smul] at h0
  obtain ⟨-, hd⟩ := P.eq_zero_of_sum_smul_root_add_sum_smul_root_eq_zero (d := fun j ↦
    μ (P.coroot i) * l j) hc (fun j ↦ mul_nonneg (hμ i) (by simpa using hl j)) h0.symm
  -- `w αᵢ ≠ 0`, so `l ≠ 0`, hence `⟨λ, αᵢ^∨⟩ = 0`
  have hl0 : l ≠ 0 := by
    rintro rfl
    rw [map_zero, LinearEquiv.map_eq_zero_iff] at hwl
    exact P.linearIndependent_root.ne_zero i hwl
  obtain ⟨j, hj⟩ := Function.ne_iff.mp hl0
  have hi : μ (P.coroot i) = 0 := by
    have := congr_fun hd j
    simp only [Pi.zero_apply, mul_eq_zero, Int.cast_eq_zero] at this
    exact this.resolve_right hj
  have hri : P.reflection hA i μ = μ := by rw [reflection_apply, hi, zero_smul, sub_zero]
  have hwμ' : (w : Dual K H ≃ₗ[K] Dual K H) μ = μ := by
    rwa [LinearEquiv.mul_apply, hri] at hwiμ
  exact mul_mem (ih hwμ') (Subgroup.subset_closure ⟨i, hi, rfl⟩)

/-- **The stabilizer of a point of the chamber** ([Kac] Prop. 3.12 (a) (check), for the action on
`𝔥*`): for `λ ∈ C`, `{w ∈ W | w λ = λ}` is the subgroup generated by the fundamental reflections
`rᵢ` with `⟨λ, αᵢ^∨⟩ = 0`. -/
theorem stabilizer_eq_closure_reflection {μ : Dual K H} (hμ : μ ∈ P.dominantChamber) :
    P.weylGroup hA ⊓ MulAction.stabilizer (Dual K H ≃ₗ[K] Dual K H) μ =
      Subgroup.closure (P.reflection hA '' {i | μ (P.coroot i) = 0}) := by
  refine le_antisymm (fun w ⟨hw, hwμ⟩ ↦
    P.mem_closure_reflection_of_apply_eq_self hA hμ hw hwμ) ?_
  rw [Subgroup.closure_le]
  rintro _ ⟨i, hi, rfl⟩
  refine ⟨P.reflection_mem_weylGroup hA i, MulAction.mem_stabilizer_iff.mpr ?_⟩
  rw [LinearEquiv.smul_def, reflection_apply,
    Set.mem_ofPred_eq.mp hi, zero_smul, sub_zero]

/-- An element of `W` fixing a point `λ` of the open chamber (`⟨λ, αᵢ^∨⟩ > 0` for all `i`) is the
identity ([Kac] Prop. 3.12 (a) (check), for the action on `𝔥*`). -/
theorem eq_one_of_apply_eq_self_of_forall_pos {μ : Dual K H} (hμ : ∀ i, 0 < μ (P.coroot i))
    {w : Dual K H ≃ₗ[K] Dual K H} (hw : w ∈ P.weylGroup hA) (hwμ : w μ = μ) : w = 1 := by
  have h := P.mem_closure_reflection_of_apply_eq_self hA (fun i ↦ (hμ i).le) hw hwμ
  have he : {i | μ (P.coroot i) = 0} = ∅ :=
    Set.eq_empty_of_forall_notMem fun i hi ↦ (hμ i).ne' hi
  rwa [he, Set.image_empty, Subgroup.closure_empty, Subgroup.mem_bot] at h

/-! ### The chamber is a fundamental domain -/

/-- If `λ, μ ∈ C` and `w λ = μ` for some `w ∈ W`, then `λ = μ` ([Kac] Prop. 3.12 (b) (check),
for the action on `𝔥*`). By `Matrix.Realization.stabilizer_eq_closure_reflection`, `w` is then a
product of fundamental reflections fixing `λ`. -/
theorem eq_of_apply_eq_of_mem_dominantChamber {μ ν : Dual K H} (hμ : μ ∈ P.dominantChamber)
    (hν : ν ∈ P.dominantChamber) {w : Dual K H ≃ₗ[K] Dual K H} (hw : w ∈ P.weylGroup hA)
    (hwμ : w μ = ν) : μ = ν := by
  obtain ⟨c, hc, hcw⟩ := P.exists_nonneg_sub_apply_eq_sum hA hμ hw
  obtain ⟨d, hd, hdw⟩ := P.exists_nonneg_sub_apply_eq_sum hA hν (inv_mem hw)
  rw [hwμ] at hcw
  rw [← hwμ, show w⁻¹ (w μ) = μ from w.symm_apply_apply μ, hwμ] at hdw
  obtain ⟨rfl, -⟩ := P.eq_zero_of_sum_smul_root_add_sum_smul_root_eq_zero hc hd
    (by rw [← hcw, ← hdw]; abel)
  simpa [sub_eq_zero] using hcw

/-- If `λ` and `w λ` both lie in `C`, then `w λ = λ`. -/
theorem apply_eq_self_of_mem_dominantChamber {μ : Dual K H} (hμ : μ ∈ P.dominantChamber)
    {w : Dual K H ≃ₗ[K] Dual K H} (hw : w ∈ P.weylGroup hA) (hwμ : w μ ∈ P.dominantChamber) :
    w μ = μ :=
  (P.eq_of_apply_eq_of_mem_dominantChamber hA hμ hwμ hw rfl).symm

/-! ### The Tits cone -/

omit [IsStrictOrderedRing K] in
lemma dominantChamber_subset_titsCone : P.dominantChamber ⊆ P.titsCone hA :=
  fun μ hμ ↦ ⟨1, one_mem _, μ, hμ, rfl⟩

omit [IsStrictOrderedRing K] in
/-- The Tits cone is `W`-invariant. -/
lemma apply_mem_titsCone {w : Dual K H ≃ₗ[K] Dual K H} (hw : w ∈ P.weylGroup hA)
    {μ : Dual K H} (hμ : μ ∈ P.titsCone hA) : w μ ∈ P.titsCone hA := by
  obtain ⟨v, hv, ν, hν, rfl⟩ := hμ
  exact ⟨w * v, mul_mem hw hv, ν, hν, rfl⟩

/-- **The chamber is a fundamental domain for the action of `W` on the Tits cone**
([Kac] Prop. 3.12 (b) (check), for the action on `𝔥*`): every `W`-orbit in `X` meets `C` in
exactly one point. -/
theorem existsUnique_mem_dominantChamber {μ : Dual K H} (hμ : μ ∈ P.titsCone hA) :
    ∃! ν, ν ∈ P.dominantChamber ∧ ∃ w ∈ P.weylGroup hA, w μ = ν := by
  obtain ⟨v, hv, ν, hν, rfl⟩ := hμ
  refine ⟨ν, ⟨hν, v⁻¹, inv_mem hv, v.symm_apply_apply ν⟩, fun ν' ⟨hν', w, hw, hwν⟩ ↦ ?_⟩
  exact (P.eq_of_apply_eq_of_mem_dominantChamber hA hν hν' (mul_mem hw hv) hwν).symm

end Matrix.Realization
