/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import Mathlib.LinearAlgebra.Reflection
import LieLean.LinearAlgebra.Matrix.Cartan.Generalized

/-!
# The Weyl group of a realization of a generalized Cartan matrix

Let `A` be a generalized Cartan matrix with realization `(𝔥, Π, Π^∨)` over a field `K`. The
fundamental reflections `rᵢ λ = λ - ⟨λ, αᵢ^∨⟩ αᵢ` of `𝔥*` generate the Weyl group `W`
([Kac] §3.7 (check)). The fundamental reflections of `𝔥` are the dual reflections
`rᵢ^∨ h = h - ⟨αᵢ, h⟩ αᵢ^∨`, so that `⟨rᵢ λ, h⟩ = ⟨λ, rᵢ^∨ h⟩` ([Kac] (3.7.1) (check)).

## Main definitions

* `Matrix.Realization.reflection`: the fundamental reflection `rᵢ` of `𝔥*`.
* `Matrix.Realization.coreflection`: the fundamental reflection `rᵢ^∨` of `𝔥`.
* `Matrix.Realization.weylGroup`: the Weyl group `W`, the subgroup of `GL(𝔥*)` generated by the
  fundamental reflections.

## Main results

* `Matrix.Realization.reflection_apply_apply`: `⟨rᵢ λ, h⟩ = ⟨λ, rᵢ^∨ h⟩`.
* `Matrix.Realization.reflection_reflection`: `rᵢ² = 1`.
* `Matrix.Realization.reflection_root`: `rᵢ αⱼ = αⱼ - aᵢⱼ αᵢ`; in particular `rᵢ αᵢ = -αᵢ`.
* `Matrix.Realization.exists_apply_eq_add_rootOf`: `w λ - λ` lies in the root lattice `Q` for
  every `w ∈ W`; hence `W` preserves `Q` (`Matrix.Realization.exists_apply_rootOf_eq_rootOf`).

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §3.7.
-/

open Module

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H) (hA : A.IsGeneralizedCartan)

include hA in
/-- `⟨αᵢ, αᵢ^∨⟩ = aᵢᵢ = 2`. -/
lemma root_coroot_self (i : ι) : P.root i (P.coroot i) = 2 := by
  rw [P.root_coroot, hA.diag]
  norm_num

/-- The fundamental reflection `rᵢ λ = λ - ⟨λ, αᵢ^∨⟩ αᵢ` of `𝔥*` ([Kac] §3.7 (check)). -/
noncomputable def reflection (i : ι) : Dual K H ≃ₗ[K] Dual K H :=
  Module.reflection (x := P.root i) (f := Dual.eval K H (P.coroot i)) (P.root_coroot_self hA i)

/-- The fundamental reflection `rᵢ^∨ h = h - ⟨αᵢ, h⟩ αᵢ^∨` of `𝔥` ([Kac] §3.7 (check)). -/
noncomputable def coreflection (i : ι) : H ≃ₗ[K] H :=
  Module.reflection (x := P.coroot i) (f := P.root i) (P.root_coroot_self hA i)

lemma reflection_apply (i : ι) (μ : Dual K H) :
    P.reflection hA i μ = μ - μ (P.coroot i) • P.root i :=
  Module.reflection_apply _ _

lemma coreflection_apply (i : ι) (a : H) :
    P.coreflection hA i a = a - P.root i a • P.coroot i :=
  Module.reflection_apply _ _

/-- The reflections of `𝔥*` and `𝔥` are adjoint: `⟨rᵢ λ, h⟩ = ⟨λ, rᵢ^∨ h⟩`. -/
lemma reflection_apply_apply (i : ι) (μ : Dual K H) (a : H) :
    P.reflection hA i μ a = μ (P.coreflection hA i a) := by
  simp only [reflection_apply, coreflection_apply, LinearMap.sub_apply, LinearMap.smul_apply,
    map_sub, map_smul, smul_eq_mul]
  ring

/-- `rᵢ` is the transpose of `rᵢ^∨`. -/
lemma reflection_eq_dualMap (i : ι) :
    P.reflection hA i = (P.coreflection hA i).dualMap := by
  ext μ a
  rw [reflection_apply_apply, LinearEquiv.dualMap_apply]

@[simp] lemma reflection_reflection (i : ι) (μ : Dual K H) :
    P.reflection hA i (P.reflection hA i μ) = μ :=
  Module.involutive_reflection _ μ

@[simp] lemma coreflection_coreflection (i : ι) (a : H) :
    P.coreflection hA i (P.coreflection hA i a) = a :=
  Module.involutive_reflection _ a

@[simp] lemma reflection_mul_self (i : ι) : P.reflection hA i * P.reflection hA i = 1 := by
  ext μ : 1
  exact P.reflection_reflection hA i μ

@[simp] lemma reflection_inv (i : ι) : (P.reflection hA i)⁻¹ = P.reflection hA i := rfl

@[simp] lemma reflection_symm (i : ι) : (P.reflection hA i).symm = P.reflection hA i := rfl

/-- `rᵢ αⱼ = αⱼ - aᵢⱼ αᵢ`. -/
lemma reflection_root (i j : ι) :
    P.reflection hA i (P.root j) = P.root j - (A i j : K) • P.root i := by
  rw [reflection_apply, P.root_coroot]

/-- `rᵢ αᵢ = -αᵢ`. -/
@[simp] lemma reflection_root_self (i : ι) : P.reflection hA i (P.root i) = -P.root i :=
  Module.reflection_apply_self _

/-- `rᵢ^∨ αⱼ^∨ = αⱼ^∨ - aⱼᵢ αᵢ^∨`. -/
lemma coreflection_coroot (i j : ι) :
    P.coreflection hA i (P.coroot j) = P.coroot j - (A j i : K) • P.coroot i := by
  rw [coreflection_apply, P.root_coroot]

@[simp] lemma coreflection_coroot_self (i : ι) :
    P.coreflection hA i (P.coroot i) = -P.coroot i :=
  Module.reflection_apply_self _

/-- `⟨rᵢ λ, αᵢ^∨⟩ = -⟨λ, αᵢ^∨⟩`. -/
@[simp] lemma reflection_apply_coroot_self (i : ι) (μ : Dual K H) :
    P.reflection hA i μ (P.coroot i) = -μ (P.coroot i) := by
  rw [reflection_apply_apply, coreflection_coroot_self, map_neg]

/-- The fundamental reflections preserve the pairing: `⟨rᵢ λ, rᵢ^∨ h⟩ = ⟨λ, h⟩`. -/
@[simp] lemma reflection_apply_coreflection (i : ι) (μ : Dual K H) (a : H) :
    P.reflection hA i μ (P.coreflection hA i a) = μ a := by
  rw [reflection_apply_apply, coreflection_coreflection]

/-- `rᵢ` acts on the root lattice: `rᵢ (∑ kⱼ αⱼ) = ∑ kⱼ αⱼ - (∑ⱼ aᵢⱼ kⱼ) αᵢ`. -/
lemma reflection_rootOf [DecidableEq ι] (i : ι) (k : ι → ℤ) :
    P.reflection hA i (P.rootOf k) = P.rootOf (k - (A *ᵥ k) i • Pi.single i 1) := by
  rw [reflection_apply, map_sub, map_zsmul, rootOf_single]
  congr 1
  rw [← Int.cast_smul_eq_zsmul K]
  congr 1
  simp [rootOf_apply, P.root_coroot, mulVec, dotProduct, mul_comm]

/-- The fundamental reflections preserve the root lattice. -/
lemma reflection_rootOf_mem_range (i : ι) (k : ι → ℤ) :
    P.reflection hA i (P.rootOf k) ∈ Set.range P.rootOf := by
  classical
  exact ⟨_, (P.reflection_rootOf hA i k).symm⟩

/-! ### The Weyl group -/

/-- The Weyl group `W` of the realization: the subgroup of `GL(𝔥*)` generated by the fundamental
reflections `rᵢ` ([Kac] §3.7 (check)). -/
noncomputable def weylGroup : Subgroup (Dual K H ≃ₗ[K] Dual K H) :=
  Subgroup.closure (Set.range (P.reflection hA))

lemma reflection_mem_weylGroup (i : ι) : P.reflection hA i ∈ P.weylGroup hA :=
  Subgroup.subset_closure ⟨i, rfl⟩

/-- Induction principle for the Weyl group: a property of elements of `GL(𝔥*)` which holds for
`1` and is preserved by left multiplication by fundamental reflections holds on `W`. -/
@[elab_as_elim]
lemma weylGroup_induction {p : (Dual K H ≃ₗ[K] Dual K H) → Prop} (one : p 1)
    (mul : ∀ i w, p w → p (P.reflection hA i * w)) {w : Dual K H ≃ₗ[K] Dual K H}
    (hw : w ∈ P.weylGroup hA) : p w := by
  induction hw using Subgroup.closure_induction_left with
  | one => exact one
  | mul_left x hx w _ ih =>
    obtain ⟨i, rfl⟩ := hx
    exact mul i w ih
  | inv_mul_cancel x hx w _ ih =>
    obtain ⟨i, rfl⟩ := hx
    rw [reflection_inv]
    exact mul i w ih

/-- `⟨∑ kₗ αₗ, αⱼ^∨⟩ = ∑ₗ aⱼₗ kₗ`. -/
lemma rootOf_apply_coroot (k : ι → ℤ) (j : ι) :
    P.rootOf k (P.coroot j) = ((A *ᵥ k) j : ℤ) := by
  simp [rootOf_apply, P.root_coroot, mulVec, dotProduct, mul_comm]

/-- Every `w ∈ W` changes an integral weight `λ` (i.e. `⟨λ, αⱼ^∨⟩ ∈ ℤ` for all `j`) by an element
of the root lattice: `w λ ∈ λ + Q`. -/
theorem exists_apply_eq_add_rootOf {w : Dual K H ≃ₗ[K] Dual K H} (hw : w ∈ P.weylGroup hA)
    {μ : Dual K H} (hμ : ∀ j, ∃ z : ℤ, μ (P.coroot j) = z) :
    ∃ k : ι → ℤ, w μ = μ + P.rootOf k := by
  classical
  refine P.weylGroup_induction hA (p := fun w ↦ ∃ k : ι → ℤ, w μ = μ + P.rootOf k)
    ⟨0, by simp⟩ (fun i w ih ↦ ?_) hw
  · obtain ⟨k, hk⟩ := ih
    obtain ⟨z, hz⟩ := hμ i
    refine ⟨k - (z + (A *ᵥ k) i) • Pi.single i 1, ?_⟩
    rw [LinearEquiv.mul_apply, hk, reflection_apply, map_sub, map_zsmul, rootOf_single,
      LinearMap.add_apply, hz, rootOf_apply_coroot, ← Int.cast_add,
      ← Int.cast_smul_eq_zsmul K (z + (A *ᵥ k) i)]
    abel

/-- The Weyl group preserves the root lattice `Q`. -/
theorem exists_apply_rootOf_eq_rootOf {w : Dual K H ≃ₗ[K] Dual K H} (hw : w ∈ P.weylGroup hA)
    (k : ι → ℤ) : ∃ k' : ι → ℤ, w (P.rootOf k) = P.rootOf k' := by
  obtain ⟨l, hl⟩ := P.exists_apply_eq_add_rootOf hA hw (μ := P.rootOf k)
    fun j ↦ ⟨_, P.rootOf_apply_coroot k j⟩
  exact ⟨k + l, by rw [hl, map_add]⟩

/-- The Weyl group acts on `𝔥*` through linear maps of the form `λ ↦ λ - ∑ cᵢ(λ) αᵢ`: `w λ - λ`
lies in the span of the simple roots. -/
theorem apply_sub_mem_span {w : Dual K H ≃ₗ[K] Dual K H} (hw : w ∈ P.weylGroup hA)
    (μ : Dual K H) : w μ - μ ∈ Submodule.span K (Set.range P.root) := by
  refine P.weylGroup_induction hA
    (p := fun w ↦ w μ - μ ∈ Submodule.span K (Set.range P.root)) (by simp) (fun i w ih ↦ ?_) hw
  · have : (P.reflection hA i * w) μ - μ = (w μ - μ) - (w μ) (P.coroot i) • P.root i := by
      rw [LinearEquiv.mul_apply, reflection_apply]; abel
    rw [this]
    exact Submodule.sub_mem _ ih (Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩))

end Matrix.Realization
