/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import Mathlib.RingTheory.Polynomial.Chebyshev
import LieLean.LinearAlgebra.Matrix.Cartan.WeylGroup
import LieLean.LinearAlgebra.Matrix.Cartan.WeylGroupTits

/-!
# The Weyl group of a generalized Cartan matrix is a Coxeter group

Let `A` be a generalized Cartan matrix with realization `(𝔥, Π, Π^∨)` over a field `K` of
characteristic zero, and let `W ⊂ GL(𝔥*)` be its Weyl group, generated by the fundamental
reflections `rᵢ`. Put `mᵢᵢ = 1` and, for `i ≠ j`, `mᵢⱼ = 2, 3, 4, 6, ∞` according as
`aᵢⱼ aⱼᵢ = 0, 1, 2, 3, ≥ 4`. We prove that `(W, {rᵢ})` is a Coxeter system with Coxeter matrix
`(mᵢⱼ)` ([Kac] Prop. 3.13), and that `ℓ(w rᵢ) < ℓ(w)` if and only if `w αᵢ` is a negative
element of the root lattice ([Kac] Lemma 3.11 (a)).

The proof does not follow [Kac], which deduces the exchange condition from the equality
`u rⱼ u⁻¹ = rᵢ` for `u αⱼ = αᵢ`, proved there using lifts of the `rᵢ` to automorphisms of
`𝔤(A)`. Instead we use Tits' argument for the geometric representation of a Coxeter group
([Hum] §5.3–5.4, [Bou] Ch. V §4.4), which works verbatim for the (non-symmetric) action of the
Coxeter group of `(mᵢⱼ)` on `𝔥*`:

1. The relations `(rᵢ rⱼ)^{mᵢⱼ} = 1` hold in `GL(𝔥*)`
   (`Matrix.Realization.reflection_mul_reflection_pow_coxeterMatrix`), so the rᵢ define a
   homomorphism from the Coxeter group onto `W` (`Matrix.Realization.coxeterGroupHom`).
2. Rank two positivity: for `i ≠ j` and an alternating word `u = ⋯ rᵢ rⱼ` of length `k < mᵢⱼ`,
   `u αᵢ` is a nonnegative integral combination of `αᵢ, αⱼ`. This is a computation with
   Chebyshev polynomials, using Mathlib's formula for `(rᵢ rⱼ)ᵏ`.
3. Tits' positivity theorem (`CoxeterSystem.smul_mem_closure_of_not_isRightDescent`) then
   implies that the homomorphism is injective, since `Q₊ ∩ -Q₊ = 0`.

## Main definitions

* `Matrix.coxeterMatrix`: the Coxeter matrix `(mᵢⱼ)` of a generalized Cartan matrix.
* `Matrix.Realization.coxeterGroupHom`: the homomorphism from the Coxeter group of `(mᵢⱼ)` to
  `GL(𝔥*)` sending the generators to the fundamental reflections.
* `Matrix.Realization.coxeterSystem`: the Coxeter system structure on the Weyl group `W`.

## Main results

* `Matrix.Realization.orderOf_reflection_mul_reflection`: the order of `rᵢ rⱼ` is `mᵢⱼ`.
* `Matrix.Realization.coxeterGroupHom_injective`: the Coxeter group of `(mᵢⱼ)` embeds in
  `GL(𝔥*)`.
* `Matrix.Realization.coxeterSystem_simple`: the simple reflections of the Coxeter system `W` are
  the fundamental reflections `rᵢ`.
* `Matrix.Realization.isRightDescent_coxeterSystem_iff`: `ℓ(w rᵢ) < ℓ(w)` if and only if
  `w αᵢ ∈ -Q₊` ([Kac] Lemma 3.11 (a)); `not_isRightDescent_coxeterSystem_iff`:
  otherwise `w αᵢ ∈ Q₊`.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §3.10–3.13.
* [Hum] J. E. Humphreys, *Reflection groups and Coxeter groups*, CUP 1990, §5.3–5.4.
* [Bou] N. Bourbaki, *Lie groups and Lie algebras*, Ch. IV–VI, Ch. V §4.
-/

open Module Polynomial Polynomial.Chebyshev CoxeterSystem

namespace Matrix

/-- The order `m` of `rᵢ rⱼ` in terms of `n = aᵢⱼ aⱼᵢ`: `m = 2, 3, 4, 6` for `n = 0, 1, 2, 3` and
`m = 0` (standing for `∞`) for `n ≥ 4` ([Kac] Prop. 3.13). -/
def coxeterEntry : ℕ → ℕ
  | 0 => 2
  | 1 => 3
  | 2 => 4
  | 3 => 6
  | _ + 4 => 0

lemma coxeterEntry_ne_one (n : ℕ) : coxeterEntry n ≠ 1 := by
  rcases n with _ | _ | _ | _ | n <;> simp [coxeterEntry]

lemma coxeterEntry_of_four_le {n : ℕ} (hn : 4 ≤ n) : coxeterEntry n = 0 := by
  obtain ⟨n, rfl⟩ := Nat.exists_eq_add_of_le' hn
  rfl

variable {ι : Type*}

lemma IsGeneralizedCartan.mul_nonneg {A : Matrix ι ι ℤ} (hA : A.IsGeneralizedCartan)
    {i j : ι} (h : i ≠ j) : 0 ≤ A i j * A j i :=
  mul_nonneg_of_nonpos_of_nonpos (hA.offDiag_nonpos i j h) (hA.offDiag_nonpos j i (Ne.symm h))

variable [DecidableEq ι]

/-- The Coxeter matrix of a generalized Cartan matrix `A`: `mᵢᵢ = 1` and, for `i ≠ j`,
`mᵢⱼ = 2, 3, 4, 6, 0` according as `aᵢⱼ aⱼᵢ = 0, 1, 2, 3, ≥ 4` (here `0` stands for `∞`)
([Kac] Prop. 3.13). -/
def coxeterMatrix (A : Matrix ι ι ℤ) : CoxeterMatrix ι where
  M := Matrix.of fun i j ↦ if i = j then 1 else coxeterEntry (A i j * A j i).toNat
  isSymm := by
    ext i j
    simp only [transpose_apply, of_apply]
    by_cases h : i = j
    · simp [h]
    · simp [h, Ne.symm h, mul_comm]
  diagonal i := by simp
  off_diagonal i j h := by simpa [h] using coxeterEntry_ne_one _

lemma coxeterMatrix_apply_of_ne (A : Matrix ι ι ℤ) {i j : ι} (h : i ≠ j) :
    A.coxeterMatrix i j = coxeterEntry (A i j * A j i).toNat := by
  simp [coxeterMatrix, h]

end Matrix

namespace Polynomial.Chebyshev

variable {K : Type*} [Field K]

/-- `S_n` at an integer point can be evaluated over `ℤ`. -/
lemma S_eval_intCast (n z : ℤ) : (S K n).eval (z : K) = (((S ℤ n).eval z : ℤ) : K) := by
  rw [← map_S (Int.castRingHom K), eval_intCast_map, eq_intCast, Int.cast_id]

/-- For `t ≥ 2`, the sequence `S_n(t)` is nonnegative and nondecreasing for `n ≥ -1`. -/
lemma S_eval_nonneg_of_two_le {t : ℤ} (ht : 2 ≤ t) (n : ℕ) :
    0 ≤ (S ℤ ((n : ℤ) - 1)).eval t ∧ (S ℤ ((n : ℤ) - 1)).eval t ≤ (S ℤ n).eval t := by
  induction n with
  | zero => simp
  | succ n ih =>
    have h := S_sub_one ℤ n
    have h' : (S ℤ ((n : ℤ) - 1)).eval t = t * (S ℤ n).eval t - (S ℤ (n + 1)).eval t := by
      rw [h]; simp
    push_cast
    simp only [add_sub_cancel_right]
    constructor
    · linarith [ih.1, ih.2]
    · nlinarith [ih.1, ih.2]

end Polynomial.Chebyshev

namespace Matrix.Realization

/-! ### Rank two computations -/

/-- Positivity of the rank two data: with `t = n - 2`, `m = coxeterEntry n` and `k < m` (or
`m = 0`), the Chebyshev values entering the formula for the alternating word of length `k`
are nonnegative. -/
lemma S_eval_nonneg_of_lt_coxeterEntry (p : ℕ) (k : ℕ)
    (hk : Matrix.coxeterEntry p = 0 ∨ k < Matrix.coxeterEntry p) :
    0 ≤ (S ℤ ((k / 2 : ℕ) : ℤ)).eval ((p : ℤ) - 2) + (S ℤ ((k / 2 : ℕ) - 1)).eval ((p : ℤ) - 2) ∧
      0 ≤ (S ℤ (if Even k then ((k / 2 : ℕ) : ℤ) - 1 else ((k / 2 : ℕ) : ℤ))).eval
        ((p : ℤ) - 2) := by
  rcases Nat.lt_or_ge p 4 with hp | hp
  · have hk' : k < Matrix.coxeterEntry p := by
      rcases hk with hk | hk
      · interval_cases p <;> simp [Matrix.coxeterEntry] at hk
      · exact hk
    interval_cases p <;> simp only [Matrix.coxeterEntry] at hk' <;> interval_cases k <;>
      norm_num [S_two, Nat.even_iff]
  · have ht : (2 : ℤ) ≤ (p : ℤ) - 2 := by omega
    have h1 := S_eval_nonneg_of_two_le ht (k / 2)
    have h2 := S_eval_nonneg_of_two_le ht (k / 2 + 1)
    push_cast at h2
    simp only [add_sub_cancel_right] at h2
    split_ifs <;> constructor <;> linarith [h1.1, h1.2, h2.1, h2.2]

/-- With `t = p - 2` and `m = coxeterEntry p`, if `0 < n < m` (or `m = 0`) and
`S_n(t) + S_{n-1}(t) = 1`, then `S_{n-1}(t) ≠ 0` and `p ≠ 0`. This is what shows that `(rᵢ rⱼ)ⁿ`
does not fix `αᵢ` for `0 < n < mᵢⱼ`. -/
lemma S_eval_ne_zero_of_lt_coxeterEntry (p n : ℕ) (hn : 0 < n)
    (hnm : Matrix.coxeterEntry p = 0 ∨ n < Matrix.coxeterEntry p)
    (h : (S ℤ n).eval ((p : ℤ) - 2) + (S ℤ ((n : ℤ) - 1)).eval ((p : ℤ) - 2) = 1) :
    (S ℤ ((n : ℤ) - 1)).eval ((p : ℤ) - 2) ≠ 0 ∧ p ≠ 0 := by
  rcases Nat.lt_or_ge p 4 with hp | hp
  · have hn' : n < Matrix.coxeterEntry p := by
      rcases hnm with hnm | hnm
      · interval_cases p <;> simp [Matrix.coxeterEntry] at hnm
      · exact hnm
    have e3 : S ℤ 3 = X * S ℤ 2 - S ℤ 1 := by simpa using S_add_two ℤ 1
    have e4 : S ℤ 4 = X * S ℤ 3 - S ℤ 2 := by simpa using S_add_two ℤ 2
    have e5 : S ℤ 5 = X * S ℤ 4 - S ℤ 3 := by simpa using S_add_two ℤ 3
    revert h
    interval_cases p <;> simp only [Matrix.coxeterEntry] at hn' <;> interval_cases n <;>
      norm_num [S_two, e3, e4, e5]
  · have ht : (2 : ℤ) ≤ (p : ℤ) - 2 := by omega
    obtain ⟨n, rfl⟩ := Nat.exists_eq_add_of_le' hn
    -- `S_n(t) ≥ S_1(t) = t ≥ 2` for `n ≥ 1`
    have hmono : ∀ k : ℕ,
        (S ℤ 1).eval ((p : ℤ) - 2) ≤ (S ℤ ((k + 1 : ℕ) : ℤ)).eval ((p : ℤ) - 2) := by
      intro k
      induction k with
      | zero => simp
      | succ k ih =>
        have := (S_eval_nonneg_of_two_le ht (k + 2)).2
        push_cast at this ih ⊢
        simp only [show (k : ℤ) + 2 - 1 = k + 1 by ring] at this
        rw [show (k : ℤ) + 1 + 1 = k + 2 by ring]
        linarith
    have h1 := hmono n
    have h2 := (S_eval_nonneg_of_two_le ht (n + 1)).1
    simp only [S_one, eval_X] at h1
    push_cast at h1 h2 h
    omega

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H) (hA : A.IsGeneralizedCartan)

omit [DecidableEq ι] in
include hA in
lemma root_coroot_mul_eq (i j : ι) (h : i ≠ j) :
    P.root j (P.coroot i) * P.root i (P.coroot j) =
      (((A i j * A j i).toNat : ℤ) : K) := by
  rw [P.root_coroot, P.root_coroot, Int.toNat_of_nonneg (hA.mul_nonneg h)]
  push_cast; ring

/-- The fundamental reflections satisfy the Coxeter relations `(rᵢ rⱼ)^{mᵢⱼ} = 1`
([Kac] Prop. 3.13). -/
theorem reflection_mul_reflection_pow_coxeterMatrix (i j : ι) :
    (P.reflection hA i * P.reflection hA j) ^ A.coxeterMatrix i j = 1 := by
  by_cases hij : i = j
  · subst hij
    simp [coxeterMatrix]
  rw [A.coxeterMatrix_apply_of_ne hij]
  set p := (A i j * A j i).toNat with hp
  rcases Nat.lt_or_ge p 4 with hp4 | hp4
  swap
  · rw [coxeterEntry_of_four_le hp4, pow_zero]
  have ht : ((p : ℤ) : K) - 2 = Dual.eval K H (P.coroot i) (P.root j) *
      Dual.eval K H (P.coroot j) (P.root i) - 2 := by
    simp only [Dual.eval_apply, P.root_coroot_mul_eq hA i j hij, hp]
  ext μ : 1
  change _ = μ
  refine (reflection_mul_reflection_pow_apply (x := P.root i) (f := Dual.eval K H (P.coroot i))
    (y := P.root j) (g := Dual.eval K H (P.coroot j)) (P.root_coroot_self hA i)
    (P.root_coroot_self hA j) _ μ _ ht).trans ?_
  simp only [Dual.eval_apply]
  interval_cases hpv : p
  · -- `aᵢⱼ = aⱼᵢ = 0`
    have h0 : A i j * A j i = 0 := by have := hA.mul_nonneg hij; omega
    have hij0 : A i j = 0 ∧ A j i = 0 := by
      rcases mul_eq_zero.mp h0 with h | h
      · exact ⟨h, (hA.zero_comm i j).mp h⟩
      · exact ⟨(hA.zero_comm j i).mp h, h⟩
    simp only [coxeterEntry, P.root_coroot, hij0.1, hij0.2]
    norm_num
    module
  all_goals simp only [coxeterEntry]; norm_num [S_two]

omit [Fintype ι] [DecidableEq ι] in
/-- A combination `a • x + b • y` with nonnegative integers `a, b` lies in the additive monoid
generated by `x` and `y`. -/
lemma intCast_smul_add_mem_closure {V : Type*} [AddCommGroup V] [Module K V] {a b : ℤ}
    (ha : 0 ≤ a) (hb : 0 ≤ b) (x y : V) :
    (a : K) • x + (b : K) • y ∈ AddSubmonoid.closure {x, y} := by
  lift a to ℕ using ha
  lift b to ℕ using hb
  rw [AddSubmonoid.mem_closure_pair]
  exact ⟨a, b, by simp [Nat.cast_smul_eq_nsmul]⟩

/-- Rank two positivity: for `i ≠ j` and `k < mᵢⱼ` (or `mᵢⱼ = ∞`), the alternating product
`⋯ rᵢ rⱼ` of length `k` maps `αᵢ` to a nonnegative integral combination of `αᵢ` and `αⱼ`
([Hum] §5.4, proof of Thm. 5.4; cf. [Kac] (3.13.2) for the rank-two matrices). -/
theorem alternating_apply_root_mem_closure {i j : ι} (hij : i ≠ j) (k : ℕ)
    (hk : A.coxeterMatrix i j = 0 ∨ k < A.coxeterMatrix i j) :
    ((if Even k then 1 else P.reflection hA j) * (P.reflection hA i * P.reflection hA j) ^ (k / 2))
      (P.root i) ∈ AddSubmonoid.closure {P.root i, P.root j} := by
  rw [A.coxeterMatrix_apply_of_ne hij] at hk
  set p := (A i j * A j i).toNat with hp
  have ht : ((p : ℤ) : K) - 2 = Dual.eval K H (P.coroot i) (P.root j) *
      Dual.eval K H (P.coroot j) (P.root i) - 2 := by
    simp only [Dual.eval_apply, P.root_coroot_mul_eq hA i j hij, hp]
  have hS := S_eval_nonneg_of_lt_coxeterEntry p k hk
  have hji : 0 ≤ -A j i := by linarith [hA.offDiag_nonpos j i (Ne.symm hij)]
  have hcast : ((p : ℤ) : K) - 2 = (((p : ℤ) - 2 : ℤ) : K) := by push_cast; ring
  split_ifs with hk2
  · rw [one_mul]
    refine (congrArg (· ∈ AddSubmonoid.closure {P.root i, P.root j})
      (reflection_mul_reflection_pow_apply_self (x := P.root i)
      (f := Dual.eval K H (P.coroot i)) (y := P.root j) (g := Dual.eval K H (P.coroot j))
      (P.root_coroot_self hA i) (P.root_coroot_self hA j) _ _ ht)).mpr ?_
    rw [hcast, S_eval_intCast, S_eval_intCast]
    simp only [hk2, ↓reduceIte] at hS
    simp only [Dual.eval_apply, P.root_coroot]
    have := intCast_smul_add_mem_closure (K := K) hS.1 (mul_nonneg hS.2 hji) (P.root i) (P.root j)
    push_cast at this
    simpa using this
  · refine (congrArg (· ∈ AddSubmonoid.closure {P.root i, P.root j})
      (reflection_mul_reflection_mul_reflection_pow_apply_self (x := P.root i)
      (f := Dual.eval K H (P.coroot i)) (y := P.root j) (g := Dual.eval K H (P.coroot j))
      (P.root_coroot_self hA i) (P.root_coroot_self hA j) _ _ ht)).mpr ?_
    rw [hcast, S_eval_intCast, S_eval_intCast]
    simp only [hk2, ↓reduceIte] at hS
    simp only [Dual.eval_apply, P.root_coroot]
    have := intCast_smul_add_mem_closure (K := K) hS.1 (mul_nonneg hS.2 hji) (P.root i) (P.root j)
    push_cast at this
    simpa using this

/-! ### The order of `rᵢ rⱼ` -/

section Order

variable [CharZero K]

omit [CharZero K] in
/-- `(rᵢ rⱼ)ⁿ αᵢ = (Sₙ(t) + Sₙ₋₁(t)) αᵢ - Sₙ₋₁(t) aⱼᵢ αⱼ` with `t = aᵢⱼ aⱼᵢ - 2`
(a special case of `Module.reflection_mul_reflection_pow_apply_self`). -/
lemma reflection_mul_reflection_pow_apply_root {i j : ι} (hij : i ≠ j) (n : ℕ) :
    ((P.reflection hA i * P.reflection hA j) ^ n) (P.root i) =
      P.rootOf ((((S ℤ n).eval ((A i j * A j i).toNat - 2 : ℤ) +
        (S ℤ ((n : ℤ) - 1)).eval ((A i j * A j i).toNat - 2 : ℤ))) • Pi.single i 1 +
        ((S ℤ ((n : ℤ) - 1)).eval ((A i j * A j i).toNat - 2 : ℤ) * -A j i) •
          Pi.single j 1) := by
  set p := (A i j * A j i).toNat with hp
  have ht : ((p : ℤ) : K) - 2 = Dual.eval K H (P.coroot i) (P.root j) *
      Dual.eval K H (P.coroot j) (P.root i) - 2 := by
    simp only [Dual.eval_apply, P.root_coroot_mul_eq hA i j hij, hp]
  have hcast : ((p : ℤ) : K) - 2 = (((p : ℤ) - 2 : ℤ) : K) := by push_cast; ring
  refine (reflection_mul_reflection_pow_apply_self (x := P.root i)
    (f := Dual.eval K H (P.coroot i)) (y := P.root j) (g := Dual.eval K H (P.coroot j))
    (P.root_coroot_self hA i) (P.root_coroot_self hA j) _ _ ht).trans ?_
  rw [hcast, S_eval_intCast, S_eval_intCast, map_add, map_zsmul, map_zsmul, rootOf_single,
    rootOf_single, ← Int.cast_smul_eq_zsmul K, ← Int.cast_smul_eq_zsmul K]
  simp only [Dual.eval_apply, P.root_coroot]
  push_cast
  ring_nf

/-- **The order of `rᵢ rⱼ` is `mᵢⱼ`** ([Kac] Prop. 3.13): for `i ≠ j` it is `2, 3, 4, 6`
or `∞` according as `aᵢⱼ aⱼᵢ = 0, 1, 2, 3` or `≥ 4` (`orderOf = 0` meaning infinite order). -/
theorem orderOf_reflection_mul_reflection (i j : ι) :
    orderOf (P.reflection hA i * P.reflection hA j) = A.coxeterMatrix i j := by
  by_cases hij : i = j
  · subst hij
    simp [coxeterMatrix]
  -- `(rᵢ rⱼ)ⁿ ≠ 1` for `0 < n < mᵢⱼ`
  have hne : ∀ n, 0 < n → (A.coxeterMatrix i j = 0 ∨ n < A.coxeterMatrix i j) →
      (P.reflection hA i * P.reflection hA j) ^ n ≠ 1 := by
    intro n hn hnm h1
    rw [A.coxeterMatrix_apply_of_ne hij] at hnm
    have h := P.reflection_mul_reflection_pow_apply_root hA hij n
    rw [h1] at h
    change P.root i = _ at h
    rw [← rootOf_single] at h
    have h' := P.rootOf_injective h
    have hi := congr_fun h' i
    have hj := congr_fun h' j
    simp only [Pi.add_apply, Pi.smul_apply, Pi.single_eq_same, Pi.single_apply, hij,
      Ne.symm hij, ↓reduceIte, smul_eq_mul, mul_one, mul_zero, add_zero, zero_add] at hi hj
    obtain ⟨hs, hp⟩ := S_eval_ne_zero_of_lt_coxeterEntry _ n hn hnm hi.symm
    have hji : A j i = 0 := by
      rcases mul_eq_zero.mp hj.symm with h | h
      · exact absurd h hs
      · omega
    exact hp (by simp [hji])
  rcases Nat.eq_zero_or_pos (A.coxeterMatrix i j) with h0 | hpos
  · rw [h0, orderOf_eq_zero_iff']
    exact fun n hn ↦ hne n hn (Or.inl h0)
  · rw [orderOf_eq_iff hpos]
    exact ⟨P.reflection_mul_reflection_pow_coxeterMatrix hA i j,
      fun n hn hn0 ↦ hne n hn0 (Or.inr hn)⟩

end Order

/-! ### The positive cone `Q₊` -/

omit [DecidableEq ι] in
/-- The additive monoid generated by the simple roots is `Q₊ = {∑ kᵢ αᵢ | kᵢ ∈ ℕ}`. -/
lemma mem_closure_range_root_iff {μ : Dual K H} :
    μ ∈ AddSubmonoid.closure (Set.range P.root) ↔ ∃ k : ι → ℤ, 0 ≤ k ∧ P.rootOf k = μ := by
  classical
  constructor
  · intro h
    induction h using AddSubmonoid.closure_induction with
    | mem x hx =>
      obtain ⟨i, rfl⟩ := hx
      exact ⟨Pi.single i 1, fun j ↦ by by_cases h : j = i <;> simp [h], rootOf_single _ _⟩
    | zero => exact ⟨0, le_rfl, map_zero _⟩
    | add x y _ _ hx hy =>
      obtain ⟨k, hk, rfl⟩ := hx
      obtain ⟨l, hl, rfl⟩ := hy
      exact ⟨k + l, add_nonneg hk hl, map_add _ _ _⟩
  · rintro ⟨k, hk, rfl⟩
    rw [rootOf_apply]
    refine AddSubmonoid.sum_mem _ fun i _ ↦ ?_
    obtain ⟨n, hn⟩ := Int.eq_ofNat_of_zero_le (hk i)
    rw [hn, Int.cast_natCast, Nat.cast_smul_eq_nsmul]
    exact AddSubmonoid.nsmul_mem _ (AddSubmonoid.subset_closure (Set.mem_range_self i)) n

omit [DecidableEq ι] in
/-- In characteristic zero, the cone `Q₊` is pointed: `Q₊ ∩ -Q₊ = 0`. -/
lemma eq_zero_of_mem_closure_of_neg_mem [CharZero K] {μ : Dual K H}
    (h : μ ∈ AddSubmonoid.closure (Set.range P.root))
    (h' : -μ ∈ AddSubmonoid.closure (Set.range P.root)) : μ = 0 := by
  obtain ⟨k, hk, rfl⟩ := (P.mem_closure_range_root_iff).mp h
  obtain ⟨l, hl, hl'⟩ := (P.mem_closure_range_root_iff).mp h'
  have hkl : k + l = 0 := P.rootOf_injective (by rw [map_add, hl', add_neg_cancel, map_zero])
  have hk0 : k = 0 := by
    ext i
    have h1 := congr_fun hkl i
    have h2 := hk i
    have h3 := hl i
    simp only [Pi.add_apply, Pi.zero_apply] at h1 h2 h3 ⊢
    omega
  rw [hk0, map_zero]

/-! ### The Coxeter system -/

/-- The homomorphism from the Coxeter group of `(mᵢⱼ)` to `GL(𝔥*)` sending the `i`-th generator
to the fundamental reflection `rᵢ`. Its image is the Weyl group
(`Matrix.Realization.range_coxeterGroupHom`), and it is injective in characteristic zero
(`Matrix.Realization.coxeterGroupHom_injective`). -/
noncomputable def coxeterGroupHom : A.coxeterMatrix.Group →* (Dual K H ≃ₗ[K] Dual K H) :=
  A.coxeterMatrix.toCoxeterSystem.lift
    ⟨P.reflection hA, P.reflection_mul_reflection_pow_coxeterMatrix hA⟩

@[simp] lemma coxeterGroupHom_simple (i : ι) :
    P.coxeterGroupHom hA (A.coxeterMatrix.simple i) = P.reflection hA i :=
  A.coxeterMatrix.toCoxeterSystem.lift_apply_simple
    (P.reflection_mul_reflection_pow_coxeterMatrix hA) i

/-- The image of the Coxeter group is the Weyl group. -/
theorem range_coxeterGroupHom : (P.coxeterGroupHom hA).range = P.weylGroup hA := by
  rw [MonoidHom.range_eq_map, ← A.coxeterMatrix.toCoxeterSystem.subgroup_closure_range_simple,
    MonoidHom.map_closure, ← Set.range_comp, weylGroup]
  congr 2

/-- **The Weyl group is a Coxeter group** ([Kac] Prop. 3.13): in characteristic zero,
the Coxeter group of `(mᵢⱼ)` maps isomorphically onto the Weyl group `W`. The proof uses Tits'
positivity theorem (`CoxeterSystem.eq_one_of_forall_smul_eq`) rather than the argument of
[Kac]; see the module docstring. -/
theorem coxeterGroupHom_injective [CharZero K] : Function.Injective (P.coxeterGroupHom hA) := by
  let _ : DistribMulAction A.coxeterMatrix.Group (Dual K H) :=
    DistribMulAction.compHom _ (P.coxeterGroupHom hA)
  have hsmul : ∀ (g : A.coxeterMatrix.Group) μ, g • μ = P.coxeterGroupHom hA g μ :=
    fun _ _ ↦ rfl
  rw [injective_iff_map_eq_one]
  intro g hg
  refine A.coxeterMatrix.toCoxeterSystem.eq_one_of_forall_smul_eq (α := P.root) ?_ ?_
    (fun _ hv hv' ↦ P.eq_zero_of_mem_closure_of_neg_mem hv hv') P.linearIndependent_root.ne_zero
    fun i ↦ by rw [hsmul, hg]; rfl
  · intro i j hij k hk
    rw [hsmul, prod_alternatingWord_eq_mul_pow, map_mul, map_pow, map_mul,
      apply_ite (P.coxeterGroupHom hA), map_one]
    simpa using P.alternating_apply_root_mem_closure hA hij k hk
  · intro i
    rw [hsmul]
    simp

/-- The Coxeter system structure on the Weyl group `W` of a generalized Cartan matrix, with
Coxeter matrix `(mᵢⱼ)` and simple reflections the fundamental reflections `rᵢ`
([Kac] Prop. 3.13). In particular `(P.coxeterSystem hA).length w` is the length `ℓ(w)`
of [Kac] §3.11: the minimal number of fundamental reflections whose product is `w`. -/
noncomputable def coxeterSystem [CharZero K] : CoxeterSystem A.coxeterMatrix (P.weylGroup hA) :=
  ⟨((MonoidHom.ofInjective (P.coxeterGroupHom_injective hA)).trans
    (MulEquiv.subgroupCongr (P.range_coxeterGroupHom hA))).symm⟩

@[simp] lemma coxeterSystem_simple [CharZero K] (i : ι) :
    ((P.coxeterSystem hA).simple i : Dual K H ≃ₗ[K] Dual K H) = P.reflection hA i := by
  simp only [CoxeterSystem.simple, coxeterSystem, MulEquiv.symm_symm]
  exact P.coxeterGroupHom_simple hA i

lemma coxeterSystem_wordProd [CharZero K] (l : List ι) :
    ((P.coxeterSystem hA).wordProd l : Dual K H ≃ₗ[K] Dual K H) =
      (l.map (P.reflection hA)).prod := by
  induction l with
  | nil => simp
  | cons i l ih => simp [wordProd_cons, ih]

/-! ### Descents and the sign of `w αᵢ` -/

section Descent

variable [CharZero K]

lemma isDihedrallyPositive_coxeterSystem :
    (P.coxeterSystem hA).IsDihedrallyPositive P.root := by
  intro i j hij k hk
  rw [Submonoid.smul_def, prod_alternatingWord_eq_mul_pow, LinearEquiv.smul_def]
  push_cast [apply_ite (Subtype.val : P.weylGroup hA → _)]
  simpa using P.alternating_apply_root_mem_closure hA hij k hk

lemma coxeterSystem_simple_smul_root (i : ι) :
    (P.coxeterSystem hA).simple i • P.root i = -P.root i := by
  rw [Submonoid.smul_def, LinearEquiv.smul_def]
  simp

/-- **[Kac] Lemma 3.11 (a)**: for `w ∈ W`, `ℓ(w rᵢ) < ℓ(w)` if and only if `w αᵢ < 0`,
i.e. `w αᵢ ∈ -Q₊`. -/
theorem isRightDescent_coxeterSystem_iff {w : P.weylGroup hA} {i : ι} :
    (P.coxeterSystem hA).IsRightDescent w i ↔
      ∃ k : ι → ℤ, 0 ≤ k ∧ (w : Dual K H ≃ₗ[K] Dual K H) (P.root i) = -P.rootOf k := by
  rw [(P.coxeterSystem hA).isRightDescent_iff_neg_smul_mem_closure
    (P.isDihedrallyPositive_coxeterSystem hA) (P.coxeterSystem_simple_smul_root hA)
    (fun _ hv hv' ↦ P.eq_zero_of_mem_closure_of_neg_mem hv hv') P.linearIndependent_root.ne_zero,
    mem_closure_range_root_iff, Submonoid.smul_def, LinearEquiv.smul_def]
  simp only [neg_eq_iff_eq_neg, eq_comm]

/-- **[Kac] Lemma 3.11 (a)**: for `w ∈ W`, `ℓ(w rᵢ) > ℓ(w)` if and only if `w αᵢ > 0`,
i.e. `w αᵢ ∈ Q₊`. -/
theorem not_isRightDescent_coxeterSystem_iff {w : P.weylGroup hA} {i : ι} :
    ¬(P.coxeterSystem hA).IsRightDescent w i ↔
      ∃ k : ι → ℤ, 0 ≤ k ∧ (w : Dual K H ≃ₗ[K] Dual K H) (P.root i) = P.rootOf k := by
  have h1 := fun hw ↦ (P.coxeterSystem hA).smul_mem_closure_of_not_isRightDescent
    (P.isDihedrallyPositive_coxeterSystem hA) (w := w) (i := i) hw
  rw [mem_closure_range_root_iff, Submonoid.smul_def, LinearEquiv.smul_def] at h1
  refine ⟨fun hw ↦ ?_, fun ⟨k, hk, hwk⟩ hw ↦ ?_⟩
  · obtain ⟨k, hk, hwk⟩ := h1 hw
    exact ⟨k, hk, hwk.symm⟩
  · obtain ⟨l, hl, hwl⟩ := (P.isRightDescent_coxeterSystem_iff hA).mp hw
    have h0 := P.eq_zero_of_mem_closure_of_neg_mem
      ((P.mem_closure_range_root_iff).mpr ⟨k, hk, rfl⟩)
      ((P.mem_closure_range_root_iff).mpr ⟨l, hl, by rw [← hwk, hwl, neg_neg]⟩)
    rw [← hwk, LinearEquiv.map_eq_zero_iff] at h0
    exact P.linearIndependent_root.ne_zero i h0

/-- Induction on the length in the Weyl group: a property of elements of `W` which holds for `1`
and passes from `w` to `w rᵢ` whenever `ℓ(w rᵢ) > ℓ(w)` holds on `W`. -/
lemma weylGroup_induction_length {p : P.weylGroup hA → Prop}
    (one : p 1)
    (step : ∀ w i, ¬(P.coxeterSystem hA).IsRightDescent w i → p w →
      p (w * (P.coxeterSystem hA).simple i))
    (w : P.weylGroup hA) : p w := by
  set cs := P.coxeterSystem hA
  generalize hn : cs.length w = n
  induction n using Nat.strong_induction_on generalizing w with
  | _ n ih =>
  by_cases hw1 : w = 1
  · exact hw1 ▸ one
  obtain ⟨i, hi⟩ := cs.exists_rightDescent_of_ne_one hw1
  have hnd : ¬cs.IsRightDescent (w * cs.simple i) i := by
    rwa [← isRightDescent_iff_not_isRightDescent_mul]
  have := step _ i hnd (ih _ (hn ▸ hi) _ rfl)
  rwa [cs.simple_mul_simple_cancel_right] at this

end Descent

end Matrix.Realization
