/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.SerrePresented.Homology
import LieLean.Algebra.Lie.KacMoody.Verma
import LieLean.Algebra.Lie.UniversalEnveloping.Kernel

/-!
# The enveloping algebras of `𝔫̂₋` and `𝔫₋` agree in low degrees

Let `A` be a generalized Cartan matrix, `K` a field of characteristic zero, `𝔤̂ = 𝔤̂(A)` the
Serre-presented algebra, `𝔫̂₋ ⊆ 𝔤̂` and `𝔫₋ ⊆ 𝔤(A)` the negative nilpotent subalgebras, and
`φ : 𝔫̂₋ → 𝔫₋` the projection, with kernel `𝔯̂₋`. Suppose that `𝔯̂₋` has no nonzero weight vectors
of weight `-γ` with `ht γ < ht β`. We show that the induced map `U(φ) : U(𝔫̂₋) → U(𝔫₋)` is
injective on the span of the words `f_{i₁} ⋯ f_{iₘ}` of weight `-γ` with `ht γ < ht β`. This is
used in the syzygy step of the proof of the Gabber–Kac theorem
(`Matrix.Realization.SerrePresentedAlgebra.exists_syzygy`).

## Proof

We grade `U(𝔫̂₋)` through the injection `U(𝔫̂₋) ↪ U(𝔤̂)` (PBW, as `𝔫̂₋` has the complementary
subalgebra `𝔥 ⊕ 𝔫̂₊`), using the weight spaces of `U(𝔤̂)` for the adjoint action of `𝔥`. The
kernel of `U(φ)` is the two-sided ideal generated by `ι(𝔯̂₋)`
(`UniversalEnvelopingAlgebra.ker_map_eq_span`). As `𝔯̂₋` lives in weights `-γ` with
`ht γ ≥ ht β`, and `U(𝔫̂₋)` in weights `-γ` with `ht γ ≥ 0`, this ideal lies in the sum of the
weight spaces `U(𝔤̂)_{-γ}` with `ht γ ≥ ht β`, which meets `U(𝔤̂)_{-γ}` trivially if
`ht γ < ht β`. The argument is standard; it is written out here in full.

## Main definitions

* `Matrix.Realization.SerrePresentedAlgebra.borel`: the subalgebra `𝔥 ⊕ 𝔫̂₊` of `𝔤̂(A)`.
* `Matrix.Realization.SerrePresentedAlgebra.envWeightSpace`: the weight space `U(𝔤̂)_μ`.
* `Matrix.Realization.SerrePresentedAlgebra.negProjN`: the projection `φ : 𝔫̂₋ → 𝔫₋`, with
  codomain `Matrix.Realization.KacMoodyAlgebra.nNeg`.
* `Matrix.Realization.SerrePresentedAlgebra.nNegFWord`,
  `Matrix.Realization.KacMoodyAlgebra.nNegFWord`: the word `f_{i₁} ⋯ f_{iₘ}` in `U(𝔫̂₋)`,
  resp. `U(𝔫₋)`.
* `Matrix.Realization.SerrePresentedAlgebra.nNegFWordSpan`,
  `Matrix.Realization.KacMoodyAlgebra.nNegFWordSpan`: the span of the words with prescribed
  letter counts.

## Main results

* `Matrix.Realization.SerrePresentedAlgebra.map_incl_range_fHom_injective`:
  `U(𝔫̂₋) → U(𝔤̂)` is injective.
* `Matrix.Realization.SerrePresentedAlgebra.eq_zero_of_map_negProj_eq_zero`: `U(φ)` is injective
  in low degrees.
* `Matrix.Realization.SerrePresentedAlgebra.exists_eq_sum_mul_f`: a weight vector `x ∈ 𝔫̂₋` of
  weight `-β` satisfies `ι x = ∑ᵢ xᵢ fᵢ` in `U(𝔫̂₋)`, with `xᵢ` in the span of the words of
  weight `-β + αᵢ`.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §9.11 (check).
* [GK] O. Gabber, V. G. Kac, *On defining relations of certain infinite-dimensional Lie
  algebras*, Bull. Amer. Math. Soc. (N.S.) **5** (1981), 185–189.
-/

open Module LieModule

noncomputable section

/-! ### Weight spaces of an associative algebra -/

namespace LieModule

attribute [local instance 100] LieRing.ofAssociativeRing

variable {K H A : Type*} [Field K] [AddCommGroup H] [Module K H] [Ring A] [Algebra K A]
  (φ : H →ₗ[K] A)

/-- For the commutator action of an associative algebra on itself, `A_μ A_ν ⊆ A_{μ+ν}`. -/
lemma mul_mem_weightSpaceOfMap {μ ν : Dual K H} {u v : A} (hu : u ∈ weightSpaceOfMap A φ μ)
    (hv : v ∈ weightSpaceOfMap A φ ν) : u * v ∈ weightSpaceOfMap A φ (μ + ν) := by
  intro a
  have hu' := hu a
  have hv' := hv a
  rw [LieRing.of_associative_ring_bracket] at hu' hv' ⊢
  rw [LinearMap.add_apply, add_smul, ← smul_mul_assoc, ← mul_smul_comm, ← hu', ← hv']
  noncomm_ring

lemma one_mem_weightSpaceOfMap : (1 : A) ∈ weightSpaceOfMap A φ 0 := fun a ↦ by
  rw [LieRing.of_associative_ring_bracket]; simp

end LieModule

/-! ### Words in `U(𝔫₋)` -/

namespace Matrix.Realization.KacMoodyAlgebra

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H)

local notation "ιᵤ" => UniversalEnvelopingAlgebra.ι K

/-- The generator `fᵢ` as an element of `𝔫₋`. -/
def nNegF (i : ι) : nNeg P := ⟨f P i, f_mem_nNeg P i⟩

/-- The word `f_{i₁} ⋯ f_{iₘ}` in `U(𝔫₋)`. -/
def nNegFWord (w : List ι) : UniversalEnvelopingAlgebra K (nNeg P) :=
  (w.map fun i ↦ ιᵤ (nNegF P i)).prod

@[simp] lemma nNegFWord_nil : nNegFWord P [] = 1 := rfl

lemma nNegFWord_cons (i : ι) (w : List ι) :
    nNegFWord P (i :: w) = ιᵤ (nNegF P i) * nNegFWord P w := by
  simp [nNegFWord]

/-- The span of the words `f_{i₁} ⋯ f_{iₘ}` in `U(𝔫₋)` with letter counts `l`. -/
def nNegFWordSpan (l : ι → ℤ) : Submodule K (UniversalEnvelopingAlgebra K (nNeg P)) :=
  Submodule.span K (nNegFWord P '' {w | AuxLieAlgebra.counts w = l})

end Matrix.Realization.KacMoodyAlgebra

namespace Matrix.Realization.SerrePresentedAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H)

local notation "ιᵤ" => UniversalEnvelopingAlgebra.ι K
local notation "jmap" => UniversalEnvelopingAlgebra.map (LieSubalgebra.incl (LieHom.range (fHom P)))
local notation "Û" => UniversalEnvelopingAlgebra K (LieHom.range (fHom P))

/-! ### The Borel subalgebra `𝔥 ⊕ 𝔫̂₊` -/

lemma lie_h_mem_range_eHom (a : H) {x : P.SerrePresentedAlgebra} (hx : x ∈ (eHom P).range) :
    ⁅h P a, x⁆ ∈ (eHom P).range := by
  obtain ⟨z, rfl⟩ := hx
  obtain ⟨z', hz'⟩ := AuxLieAlgebra.lie_h_eHom P a z
  refine ⟨z', ?_⟩
  change π P (AuxLieAlgebra.eHom P z') = ⁅π P (AuxLieAlgebra.h P a), π P (AuxLieAlgebra.eHom P z)⁆
  rw [← LieHom.map_lie, hz']

/-- The Borel subalgebra `𝔥 ⊕ 𝔫̂₊` of `𝔤̂(A)`. -/
def borel : LieSubalgebra K P.SerrePresentedAlgebra where
  toSubmodule := LinearMap.range (h P) ⊔ (eHom P).range.toSubmodule
  lie_mem' {x y} hx hy := by
    obtain ⟨_, ⟨a, rfl⟩, n, hn, rfl⟩ := Submodule.mem_sup.mp hx
    obtain ⟨_, ⟨b, rfl⟩, n', hn', rfl⟩ := Submodule.mem_sup.mp hy
    refine Submodule.mem_sup_right ?_
    rw [add_lie, lie_add, lie_add, lie_h_h, zero_add, ← lie_skew n (h P b)]
    exact add_mem (lie_h_mem_range_eHom P a hn') (add_mem (neg_mem (lie_h_mem_range_eHom P b hn))
      ((eHom P).range.lie_mem hn hn'))

/-! ### Weight spaces of `U(𝔤̂)` -/

/-- The weight space `U(𝔤̂)_μ` for the adjoint action of `𝔥`. -/
abbrev envWeightSpace (μ : Dual K H) :
    Submodule K (UniversalEnvelopingAlgebra K P.SerrePresentedAlgebra) :=
  weightSpaceOfMap (UniversalEnvelopingAlgebra K P.SerrePresentedAlgebra)
    ((ιᵤ : P.SerrePresentedAlgebra →ₗ⁅K⁆ _).toLinearMap ∘ₗ h P) μ

lemma ι_mem_envWeightSpace {μ : Dual K H} {x : P.SerrePresentedAlgebra}
    (hx : x ∈ rootSpace P μ) : ιᵤ x ∈ envWeightSpace P μ := fun a ↦ by
  change ⁅ιᵤ (h P a), ιᵤ x⁆ = μ a • ιᵤ x
  rw [← LieHom.map_lie, hx a, map_smul]

/-- The sum of the weight spaces `U(𝔤̂)_{-γ}` with `ht γ ≥ n`. -/
def envDegGe (n : ℤ) : Submodule K (UniversalEnvelopingAlgebra K P.SerrePresentedAlgebra) :=
  ⨆ (l : ι → ℤ) (_ : n ≤ height l), envWeightSpace P (-P.rootOf l)

lemma mem_envDegGe_of_mem {n : ℤ} {l : ι → ℤ} (hl : n ≤ height l)
    {u : UniversalEnvelopingAlgebra K P.SerrePresentedAlgebra}
    (hu : u ∈ envWeightSpace P (-P.rootOf l)) : u ∈ envDegGe P n :=
  Submodule.mem_iSup_of_mem l (Submodule.mem_iSup_of_mem hl hu)

lemma mul_mem_envDegGe {n m : ℤ} {u v : UniversalEnvelopingAlgebra K P.SerrePresentedAlgebra}
    (hu : u ∈ envDegGe P n) (hv : v ∈ envDegGe P m) : u * v ∈ envDegGe P (n + m) := by
  rw [envDegGe, iSup_subtype'] at hu hv
  refine Submodule.iSup_induction _ (motive := fun u ↦ u * v ∈ _) hu (fun l u hu ↦ ?_)
    (by simp) (fun u₁ u₂ h₁ h₂ ↦ by rw [add_mul]; exact add_mem h₁ h₂)
  refine Submodule.iSup_induction _ (motive := fun v ↦ u * v ∈ _) hv (fun l' v hv ↦ ?_)
    (by simp) (fun v₁ v₂ h₁ h₂ ↦ by rw [mul_add]; exact add_mem h₁ h₂)
  refine mem_envDegGe_of_mem P (l := l + l') ?_ ?_
  · rw [height_add]; exact add_le_add l.2 l'.2
  · rw [map_add, neg_add]; exact mul_mem_weightSpaceOfMap _ hu hv

/-- `U(𝔫̂₋)` lies in the weights `-γ` with `ht γ ≥ 0`. -/
lemma map_mem_envDegGe_zero (u : Û) : jmap u ∈ envDegGe P 0 := by
  induction u using UniversalEnvelopingAlgebra.induction with
  | algebraMap r =>
    rw [AlgHom.commutes, Algebra.algebraMap_eq_smul_one]
    refine Submodule.smul_mem _ r (mem_envDegGe_of_mem P (l := 0) (by simp [height]) ?_)
    rw [map_zero, neg_zero]
    exact one_mem_weightSpaceOfMap _
  | ι x =>
    rw [UniversalEnvelopingAlgebra.map_ι, LieSubalgebra.coe_incl]
    have hx := range_fHom_le P ((fHom P).range.coe_mem x)
    have : (⨆ μ ∈ P.negWeights, rootSpace P μ) ≤
        (envDegGe P 0).comap (ιᵤ : P.SerrePresentedAlgebra →ₗ⁅K⁆ _).toLinearMap := by
      refine iSup₂_le fun μ hμ y hy ↦ ?_
      obtain ⟨m, hm, rfl⟩ := hμ
      exact mem_envDegGe_of_mem P (height_pos hm).le (ι_mem_envWeightSpace P hy)
    exact this hx
  | mul a b ha hb => rw [map_mul]; simpa using mul_mem_envDegGe P ha hb
  | add a b ha hb => rw [map_add]; exact add_mem ha hb

/-! ### Words in `U(𝔫̂₋)` -/

/-- The generator `fᵢ` as an element of `𝔫̂₋`. -/
def nNegF (i : ι) : (fHom P).range := ⟨f P i, FreeLieAlgebra.of K i, fHom_of P i⟩

/-- The word `f_{i₁} ⋯ f_{iₘ}` in `U(𝔫̂₋)`. -/
def nNegFWord (w : List ι) : Û := (w.map fun i ↦ ιᵤ (nNegF P i)).prod

@[simp] lemma nNegFWord_nil : nNegFWord P [] = 1 := rfl

lemma nNegFWord_cons (i : ι) (w : List ι) :
    nNegFWord P (i :: w) = ιᵤ (nNegF P i) * nNegFWord P w := by
  simp [nNegFWord]

lemma nNegFWord_append (w w' : List ι) :
    nNegFWord P (w ++ w') = nNegFWord P w * nNegFWord P w' := by
  simp [nNegFWord]

/-- The span of the words `f_{i₁} ⋯ f_{iₘ}` in `U(𝔫̂₋)` with letter counts `l`. -/
def nNegFWordSpan (l : ι → ℤ) : Submodule K Û :=
  Submodule.span K (nNegFWord P '' {w | AuxLieAlgebra.counts w = l})

omit [Fintype ι] in
lemma counts_append (w w' : List ι) :
    AuxLieAlgebra.counts (w ++ w') = AuxLieAlgebra.counts w + AuxLieAlgebra.counts w' := by
  ext i; simp [AuxLieAlgebra.counts, List.count_append]

lemma mul_mem_nNegFWordSpan {l l' : ι → ℤ} {u v : Û} (hu : u ∈ nNegFWordSpan P l)
    (hv : v ∈ nNegFWordSpan P l') : u * v ∈ nNegFWordSpan P (l + l') := by
  have := Submodule.mul_mem_mul hu hv
  rw [nNegFWordSpan, nNegFWordSpan, Submodule.span_mul_span] at this
  refine Submodule.span_mono ?_ this
  rintro _ ⟨_, ⟨w, hw, rfl⟩, _, ⟨w', hw', rfl⟩, rfl⟩
  refine ⟨w ++ w', ?_, nNegFWord_append P w w'⟩
  change AuxLieAlgebra.counts (w ++ w') = l + l'
  rw [counts_append]
  exact congrArg₂ (· + ·) hw hw'

lemma ι_nNegF_mem_nNegFWordSpan (i : ι) : ιᵤ (nNegF P i) ∈ nNegFWordSpan P (Pi.single i 1) :=
  Submodule.subset_span ⟨[i], by simp, by simp [nNegFWord]⟩

lemma map_nNegFWord_mem (w : List ι) :
    jmap (nNegFWord P w) ∈ envWeightSpace P (-P.rootOf (AuxLieAlgebra.counts w)) := by
  induction w with
  | nil => simpa using one_mem_weightSpaceOfMap _
  | cons i w ih =>
    rw [nNegFWord_cons, map_mul, UniversalEnvelopingAlgebra.map_ι, AuxLieAlgebra.counts_cons,
      map_add, neg_add, rootOf_single]
    exact mul_mem_weightSpaceOfMap _ (ι_mem_envWeightSpace P (f_mem_rootSpace P i)) ih

lemma nNegFWordSpan_le_comap (l : ι → ℤ) :
    nNegFWordSpan P l ≤ (envWeightSpace P (-P.rootOf l)).comap (jmap).toLinearMap := by
  rw [nNegFWordSpan, Submodule.span_le]
  rintro _ ⟨w, rfl, rfl⟩
  exact map_nNegFWord_mem P w

/-- `ι(𝔫̂₋)` lies in the span of the words. -/
lemma ι_mem_span_nNegFWord (x : (fHom P).range) :
    ιᵤ x ∈ Submodule.span K (Set.range (nNegFWord P)) := by
  set W := Submodule.span K (Set.range (nNegFWord P))
  have hW : ∀ u ∈ W, ∀ v ∈ W, u * v ∈ W := fun u hu v hv ↦ by
    have := Submodule.mul_mem_mul hu hv
    rw [Submodule.span_mul_span] at this
    refine Submodule.span_mono ?_ this
    rintro _ ⟨_, ⟨w, rfl⟩, _, ⟨w', rfl⟩, rfl⟩
    exact ⟨w ++ w', nNegFWord_append P w w'⟩
  obtain ⟨z, rfl⟩ := (fHom P).surjective_rangeRestrict x
  induction z using FreeLieAlgebra.induction_on with
  | of i =>
    have : (fHom P).rangeRestrict (FreeLieAlgebra.of K i) = nNegF P i :=
      Subtype.ext (fHom_of P i)
    rw [this]
    exact Submodule.subset_span ⟨[i], by simp [nNegFWord]⟩
  | zero => rw [map_zero, map_zero]; exact zero_mem _
  | add y z hy hz => rw [map_add, map_add]; exact add_mem hy hz
  | smul c y hy => rw [map_smul, map_smul]; exact Submodule.smul_mem _ c hy
  | lie y z hy hz =>
    rw [LieHom.map_lie, LieHom.map_lie, LieRing.of_associative_ring_bracket]
    exact sub_mem (hW _ hy _ hz) (hW _ hz _ hy)

lemma span_nNegFWord_le : Submodule.span K (Set.range (nNegFWord P)) ≤ ⨆ l, nNegFWordSpan P l := by
  rw [Submodule.span_le]
  rintro _ ⟨w, rfl⟩
  exact Submodule.mem_iSup_of_mem (AuxLieAlgebra.counts w) (Submodule.subset_span ⟨w, rfl, rfl⟩)

/-- For `k ≠ 0`, every element of the span of the words with letter counts `k` is of the form
`∑ᵢ yᵢ fᵢ`, with `yᵢ` in the span of the words with letter counts `k - eᵢ`. -/
lemma exists_eq_sum_mul_of_mem {k : ι → ℤ} (hk : k ≠ 0) {u : Û} (hu : u ∈ nNegFWordSpan P k) :
    ∃ y : ι → Û, (∀ i, y i ∈ nNegFWordSpan P (k - Pi.single i 1)) ∧
      u = ∑ i, y i * ιᵤ (nNegF P i) := by
  induction hu using Submodule.span_induction with
  | mem u hu =>
    obtain ⟨w, hw, rfl⟩ := hu
    obtain rfl | ⟨w', i, rfl⟩ := List.eq_nil_or_concat w
    · exact absurd hw.symm (by simpa using hk)
    refine ⟨Pi.single i (nNegFWord P w'), fun j ↦ ?_, ?_⟩
    · by_cases hj : j = i
      · subst hj
        rw [Pi.single_eq_same]
        refine Submodule.subset_span ⟨w', ?_, rfl⟩
        rw [Set.mem_ofPred_eq, ← hw, List.concat_eq_append, counts_append]
        simp
      · rw [Pi.single_eq_of_ne hj]; exact zero_mem _
    · rw [Finset.sum_eq_single i (fun j _ hj ↦ by rw [Pi.single_eq_of_ne hj, zero_mul])
        (by simp), Pi.single_eq_same, List.concat_eq_append, nNegFWord_append]
      simp [nNegFWord]
  | zero => exact ⟨0, fun _ ↦ zero_mem _, by simp⟩
  | add u v _ _ hu hv =>
    obtain ⟨y, hy, rfl⟩ := hu
    obtain ⟨y', hy', rfl⟩ := hv
    exact ⟨y + y', fun i ↦ add_mem (hy i) (hy' i), by
      simp [add_mul, Finset.sum_add_distrib]⟩
  | smul c u _ hu =>
    obtain ⟨y, hy, rfl⟩ := hu
    exact ⟨c • y, fun i ↦ Submodule.smul_mem _ c (hy i), by
      simp [Finset.smul_sum]⟩

/-! ### Low degrees -/

variable [CharZero K] (hA : A.IsGeneralizedCartan)

/-- The projection `φ : 𝔫̂₋ → 𝔫₋`, with codomain `KacMoodyAlgebra.nNeg P`. -/
abbrev negProjN : (fHom P).range →ₗ⁅K⁆ KacMoodyAlgebra.nNeg P := negProj P hA

include hA in
/-- The triangular decomposition in the form `𝔤̂ = 𝔫̂₋ ⊕ (𝔥 ⊕ 𝔫̂₊)`. -/
theorem isCompl_range_fHom_borel :
    IsCompl (fHom P).range.toSubmodule (borel P).toSubmodule := by
  refine ⟨Submodule.disjoint_def.mpr fun x hx hx' ↦ ?_,
    Submodule.codisjoint_iff_exists_add_eq.mpr fun x ↦ ?_⟩
  · obtain ⟨y, rfl⟩ := hx
    obtain ⟨_, ⟨a, rfl⟩, _, ⟨z, rfl⟩, hyz⟩ := Submodule.mem_sup.mp hx'
    change h P a + eHom P z = fHom P y at hyz
    have := triangular_eq_zero P hA (y := y) (a := -a) (z := -z) (by
      rw [map_neg, map_neg, ← hyz]; abel)
    exact this.1
  · obtain ⟨y, a, z, rfl⟩ := exists_triangular P x
    exact ⟨fHom P y, h P a + eHom P z, ⟨y, rfl⟩,
      Submodule.add_mem_sup ⟨a, rfl⟩ ⟨z, rfl⟩, (add_assoc _ _ _).symm⟩

include hA in
/-- `U(𝔫̂₋) → U(𝔤̂)` is injective (a consequence of PBW). -/
theorem map_incl_range_fHom_injective : Function.Injective jmap :=
  UniversalEnvelopingAlgebra.map_incl_injective_of_isCompl (isCompl_range_fHom_borel P hA)

/-- `U(𝔤̂)_{-γ}` meets the sum of the `U(𝔤̂)_{-γ'}` with `ht γ' ≥ n` trivially if `ht γ < n`. -/
lemma disjoint_envDegGe {n : ℤ} {l : ι → ℤ} (hl : height l < n) :
    Disjoint (envWeightSpace P (-P.rootOf l)) (envDegGe P n) := by
  refine ((iSupIndep_weightSpaceOfMap _) (-P.rootOf l)).mono_right ?_
  refine iSup₂_le fun l' hl' ↦ le_iSup₂_of_le (-P.rootOf l') (fun h ↦ ?_) le_rfl
  rw [neg_inj] at h
  rw [P.rootOf_injective h] at hl'
  exact absurd hl' (not_le.mpr hl)

include hA in
/-- A weight vector `x ∈ 𝔫̂₋` of weight `-β`, `β = ∑ kᵢ αᵢ ∈ Q₊ \ {0}`, satisfies
`ι x = ∑ᵢ xᵢ fᵢ` in `U(𝔫̂₋)`, with `xᵢ` in the span of the words with letter counts
`k - eᵢ`. -/
theorem exists_eq_sum_mul_f {k : ι → ℤ} (hk : k ∈ posCone ι) {x : (fHom P).range}
    (hx : (x : P.SerrePresentedAlgebra) ∈ rootSpace P (-P.rootOf k)) :
    ∃ y : ι → Û, (∀ i, y i ∈ nNegFWordSpan P (k - Pi.single i 1)) ∧
      ιᵤ x = ∑ i, y i * ιᵤ (nNegF P i) := by
  refine exists_eq_sum_mul_of_mem P hk.2 ?_
  have h1 : ιᵤ x ∈ ⨆ l, nNegFWordSpan P l := span_nNegFWord_le P (ι_mem_span_nNegFWord P x)
  have h2 : jmap (ιᵤ x) ∈ envWeightSpace P (-P.rootOf k) := by
    rw [UniversalEnvelopingAlgebra.map_ι]; exact ι_mem_envWeightSpace P hx
  let N : Dual K H → Submodule K (UniversalEnvelopingAlgebra K P.SerrePresentedAlgebra) :=
    fun μ ↦ ⨆ (l : ι → ℤ) (_ : -P.rootOf l = μ), (nNegFWordSpan P l).map (jmap).toLinearMap
  have hN : ∀ μ, N μ ≤ envWeightSpace P μ := fun μ ↦ iSup₂_le fun l hl ↦ hl ▸
    Submodule.map_le_iff_le_comap.mpr (nNegFWordSpan_le_comap P l)
  have h3 : jmap (ιᵤ x) ∈ ⨆ μ, N μ := by
    have : (⨆ l, nNegFWordSpan P l).map (jmap).toLinearMap ≤ ⨆ μ, N μ := by
      rw [Submodule.map_iSup]
      exact iSup_le fun l ↦ le_iSup_of_le (-P.rootOf l) (le_iSup₂_of_le l rfl le_rfl)
    exact this (Submodule.mem_map_of_mem h1)
  have h4 := mem_of_mem_iSup_of_le _ N hN h2 h3
  have h5 : N (-P.rootOf k) ≤ (nNegFWordSpan P k).map (jmap).toLinearMap :=
    iSup₂_le fun l hl ↦ by rw [P.rootOf_injective (neg_inj.mp hl)]
  obtain ⟨y, hy, hyx⟩ := h5 h4
  rwa [← map_incl_range_fHom_injective P hA hyx]

include hA in
/-- If `𝔯̂₋` vanishes in the weights `-γ` with `ht γ < ht β`, then `ι(𝔯̂₋)` lies in the weights
`-γ` with `ht γ ≥ ht β`. -/
lemma ι_mem_envDegGe_of_mem_radicalNeg {k : ι → ℤ}
    (hmin : ∀ l ∈ posCone ι, height l < height k →
      (radicalNeg P).toSubmodule ⊓ rootSpace P (-P.rootOf l) = ⊥)
    {x : P.SerrePresentedAlgebra} (hx : x ∈ radicalNeg P) : ιᵤ x ∈ envDegGe P (height k) := by
  have hx' : x ∈ ⨆ μ ∈ P.negWeights, ((radicalNeg P).toSubmodule ⊓ rootSpace P μ) :=
    inf_iSup_weightSpaceOfMap_le (h P) _ (fun _ _ hy ↦ (radicalNeg P).lie_mem hy) _
      ⟨hx, range_fHom_le P (radicalNeg_le_range_fHom P hA hx)⟩
  have : ⨆ μ ∈ P.negWeights, ((radicalNeg P).toSubmodule ⊓ rootSpace P μ) ≤
      (envDegGe P (height k)).comap (ιᵤ : P.SerrePresentedAlgebra →ₗ⁅K⁆ _).toLinearMap := by
    refine iSup₂_le fun μ hμ y hy ↦ ?_
    obtain ⟨m, hm, rfl⟩ := hμ
    by_cases hmk : height m < height k
    · rw [hmin m hm hmk, Submodule.mem_bot] at hy
      rw [hy, Submodule.mem_comap, map_zero]
      exact zero_mem _
    · exact mem_envDegGe_of_mem P (not_lt.mp hmk) (ι_mem_envWeightSpace P hy.2)
  exact this hx'

include hA in
/-- **`U(𝔫̂₋) → U(𝔫₋)` is injective in low degrees.** If `𝔯̂₋` vanishes in the weights `-γ` with
`ht γ < ht β`, then `U(φ) : U(𝔫̂₋) → U(𝔫₋)` is injective on the span of the words of weight
`-γ` with `ht γ < ht β`. -/
theorem eq_zero_of_map_negProj_eq_zero {k : ι → ℤ}
    (hmin : ∀ l ∈ posCone ι, height l < height k →
      (radicalNeg P).toSubmodule ⊓ rootSpace P (-P.rootOf l) = ⊥)
    {l : ι → ℤ} (hl : height l < height k) {u : Û} (hu : u ∈ nNegFWordSpan P l)
    (h0 : UniversalEnvelopingAlgebra.map (negProjN P hA) u = 0) : u = 0 := by
  have h1 := UniversalEnvelopingAlgebra.mem_span_of_map_eq_zero (negProj_surjective P hA) h0
  let I : TwoSidedIdeal Û := TwoSidedIdeal.mk' {u | jmap u ∈ envDegGe P (height k)}
    (by simp) (fun hx hy ↦ by simp only [Set.mem_ofPred_eq, map_add] at *; exact add_mem hx hy)
    (fun hx ↦ by simp only [Set.mem_ofPred_eq, map_neg] at *; exact neg_mem hx)
    (fun {x y} hy ↦ by
      have := mul_mem_envDegGe P (map_mem_envDegGe_zero P x) hy
      rwa [zero_add, ← map_mul] at this)
    (fun {x y} hx ↦ by
      have := mul_mem_envDegGe P hx (map_mem_envDegGe_zero P y)
      rwa [add_zero, ← map_mul] at this)
  have h2 : TwoSidedIdeal.span (ιᵤ '' {x | negProjN P hA x = 0}) ≤ I := by
    rw [TwoSidedIdeal.span_le]
    rintro _ ⟨x, hx, rfl⟩
    rw [SetLike.mem_coe, TwoSidedIdeal.mem_mk', Set.mem_ofPred_eq, UniversalEnvelopingAlgebra.map_ι]
    exact ι_mem_envDegGe_of_mem_radicalNeg P hA hmin ((negProj_eq_zero_iff P hA).mp hx)
  have h3 : jmap u ∈ envDegGe P (height k) := (TwoSidedIdeal.mem_mk' _ _ _ _ _ _ u).mp (h2 h1)
  have h4 := Submodule.disjoint_def.mp (disjoint_envDegGe P hl) _ (nNegFWordSpan_le_comap P l hu)
    h3
  exact map_incl_range_fHom_injective P hA (h4.trans (map_zero _).symm)

/-! ### Words in `U(𝔫₋)` -/

lemma negProj_nNegF (i : ι) : negProjN P hA (nNegF P i) = KacMoodyAlgebra.nNegF P i :=
  Subtype.ext (toKacMoody_f P hA i)

lemma map_negProj_nNegFWord (w : List ι) :
    UniversalEnvelopingAlgebra.map (negProjN P hA) (nNegFWord P w) =
      KacMoodyAlgebra.nNegFWord P w := by
  induction w with
  | nil => exact map_one _
  | cons i w ih =>
    rw [nNegFWord_cons, map_mul, UniversalEnvelopingAlgebra.map_ι, negProj_nNegF, ih,
      KacMoodyAlgebra.nNegFWord_cons]

/-- `U(φ)` maps the span of the words with letter counts `l` onto its counterpart in `U(𝔫₋)`. -/
lemma map_negProj_nNegFWordSpan (l : ι → ℤ) :
    (nNegFWordSpan P l).map (UniversalEnvelopingAlgebra.map (negProjN P hA)).toLinearMap =
      KacMoodyAlgebra.nNegFWordSpan P l := by
  rw [nNegFWordSpan, Submodule.map_span, ← Set.image_comp]
  congr 1
  exact Set.image_congr fun w _ ↦ map_negProj_nNegFWord P hA w

end Matrix.Realization.SerrePresentedAlgebra
