/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.HighestWeight
import LieLean.Algebra.Lie.KacMoody.SerrePresented.SyzygyEnveloping
import LieLean.Algebra.Lie.KacMoody.VermaPBW
import Mathlib.Algebra.Lie.DirectSum

/-!
# A lowest weight vector of `𝔯̂₋` gives a primitive syzygy

Let `A` be a generalized Cartan matrix, `K` a field of characteristic zero, `𝔤 = 𝔤(A)`, and
`𝔤̂ = 𝔤̂(A)` the Serre-presented algebra, with `𝔫̂₋ ⊆ 𝔤̂`, `𝔫₋ ⊆ 𝔤` the negative nilpotent
subalgebras, `φ : 𝔫̂₋ → 𝔫₋` the projection and `𝔯̂₋ = ker φ`. This file contains a step of the
proof of the Gabber–Kac theorem ([Kac] Thm. 9.11, [GK]) which reduces the vanishing of `𝔯̂₋` to a
statement about `𝔤`-modules in category `𝒪`, to which the Casimir operator can be applied.

Let `E = ⊕ᵢ M(-αᵢ)` and let `Φ : E → M(0)` be the morphism of `𝔤`-modules with
`v_{-αᵢ} ↦ fᵢ v₀`. Its kernel `Syz` is the module of *syzygies* of the `fᵢ`: under
`M(Λ) ≅ U(𝔫₋)`, it is `{(uᵢ) ∈ U(𝔫₋)^I | ∑ᵢ uᵢ fᵢ = 0}`. For `β = ∑ kᵢ αᵢ ∈ Q₊ \ {0}` let `T` be
the `𝔤`-submodule of `E` generated by the weight spaces `Syz_{-γ}` with `ht γ < ht β`.

**Theorem** (`Matrix.Realization.SerrePresentedAlgebra.exists_syzygy`). Let `x ∈ 𝔯̂₋` be a
nonzero weight vector of weight `-β`, such that `𝔯̂₋` has no nonzero weight vectors of weight
`-γ` with `ht γ < ht β`. Then there is `s ∈ Syz_{-β}` with `s ∉ T` and `eᵢ s ∈ T` for all `i`.
Thus the image of `s` in the subquotient `Syz / T` of `E` is a nonzero vector of weight `-β`
killed by `𝔫₊`.

Combined with the Casimir operator, which acts by `(λ + 2ρ | λ) = 0` on each `M(-αᵢ)` and by
`(-β + 2ρ | -β)` on the image of `s`, this gives `(β | β) = 2 (ρ | β)` (in the symmetrizable
case), which is the key identity of the proof of Gabber–Kac.

## Proof

The argument is reconstructed (it is a module-theoretic form of the argument of [GK]).
1. By `Matrix.Realization.SerrePresentedAlgebra.exists_eq_sum_mul_f`, `ι x = ∑ᵢ xᵢ fᵢ` in
   `U(𝔫̂₋)`, with `xᵢ` in the span of the words of weight `-β + αᵢ`. Let `s = (φ(xᵢ) v_{-αᵢ})ᵢ`.
   Then `Φ(s) = φ(∑ᵢ xᵢ fᵢ) v₀ = φ(x) v₀ = 0`, so `s ∈ Syz_{-β}`.
2. `eᵢ s ∈ Syz` has weight `-β + αᵢ`, of smaller height, so `eᵢ s ∈ T`.
3. `T` is spanned by the `f_{j₁} ⋯ f_{jₘ} t` with `t ∈ Syz_{-γ}`, `ht γ < ht β` (this span is
   stable under the `eᵢ`, by induction on `m`). Hence `T_{-β} ⊆ ∑ⱼ fⱼ Syz_{-β+αⱼ}`.
4. Suppose `s ∈ T`, so `s = ∑ⱼ fⱼ tⱼ` with `tⱼ = (τⱼᵢ v_{-αᵢ})ᵢ ∈ Syz_{-β+αⱼ}`, i.e.
   `∑ᵢ τⱼᵢ fᵢ = 0` in `U(𝔫₋)`. Lift the `τⱼᵢ` to `τ̂ⱼᵢ ∈ U(𝔫̂₋)` in the span of words of the same
   weight. As `U(φ)` is injective in weights of height `< ht β`
   (`Matrix.Realization.SerrePresentedAlgebra.eq_zero_of_map_negProj_eq_zero`), we get
   `∑ᵢ τ̂ⱼᵢ fᵢ = 0` and `xᵢ = ∑ⱼ fⱼ τ̂ⱼᵢ` in `U(𝔫̂₋)`. Hence
   `ι x = ∑ᵢ ∑ⱼ fⱼ τ̂ⱼᵢ fᵢ = ∑ⱼ fⱼ (∑ᵢ τ̂ⱼᵢ fᵢ) = 0`, so `x = 0` by PBW, a contradiction.

## Main definitions

* `Matrix.Realization.KacMoodyAlgebra.VermaSum`: `E = ⊕ᵢ M(-αᵢ)`.
* `Matrix.Realization.KacMoodyAlgebra.syzygyMap`: `Φ : E → M(0)`, `v_{-αᵢ} ↦ fᵢ v₀`.
* `Matrix.Realization.KacMoodyAlgebra.syzygies`: `Syz = ker Φ`.
* `Matrix.Realization.KacMoodyAlgebra.lowerSyzygies`: the submodule `T`.

## Main results

* `Matrix.Realization.SerrePresentedAlgebra.exists_syzygy`: the theorem above.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §9.11.
* [GK] O. Gabber, V. G. Kac, *On defining relations of certain infinite-dimensional Lie
  algebras*, Bull. Amer. Math. Soc. (N.S.) **5** (1981), 185–189.
-/

open Module LieModule

noncomputable section

namespace Matrix.Realization.KacMoodyAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H)

open VermaModule (rep fWord equivEnvNNeg)

local notation "ιᵤ" => UniversalEnvelopingAlgebra.ι K
local notation "mapN" => UniversalEnvelopingAlgebra.map (LieSubalgebra.incl (nNeg P))

/-! ### Words acting on `𝔤`-modules -/

section Words

variable {V : Type*} [AddCommGroup V] [Module K V] [LieRingModule P.KacMoodyAlgebra V]
  [LieModule K P.KacMoodyAlgebra V]

lemma rep_fWord_nil (v : V) : rep P V (fWord P []) v = v := by simp

lemma rep_fWord_cons (j : ι) (w : List ι) (v : V) :
    rep P V (fWord P (j :: w)) v = ⁅f P j, rep P V (fWord P w) v⁆ := by
  rw [VermaModule.fWord_cons, map_mul, Module.End.mul_apply, VermaModule.rep_ι]

lemma rep_fWord_mem_weightSpace (w : List ι) {μ : Dual K H} {v : V}
    (hv : v ∈ weightSpaceOfMap V (h P) μ) :
    rep P V (fWord P w) v ∈
      weightSpaceOfMap V (h P) (μ - P.rootOf (AuxLieAlgebra.counts w)) := by
  induction w with
  | nil => simpa [rep_fWord_nil] using hv
  | cons j w ih =>
    rw [rep_fWord_cons]
    convert lie_mem_weightSpaceOfMap (h P) (f_mem_rootSpace P j) ih using 2
    rw [AuxLieAlgebra.counts_cons, map_add, rootOf_single]
    abel

lemma rep_fWord_mem (N : LieSubmodule K P.KacMoodyAlgebra V) (w : List ι) {v : V}
    (hv : v ∈ N) : rep P V (fWord P w) v ∈ N := by
  induction w with
  | nil => rwa [rep_fWord_nil]
  | cons j w ih => rw [rep_fWord_cons]; exact N.lie_mem ih

end Words

lemma map_nNegFWord (w : List ι) : mapN (nNegFWord P w) = fWord P w := by
  induction w with
  | nil => exact map_one _
  | cons j w ih =>
    rw [nNegFWord_cons, map_mul, UniversalEnvelopingAlgebra.map_ι, ih, VermaModule.fWord_cons]
    rfl

lemma rep_eq_smul {Λ : Dual K H} (u : UniversalEnvelopingAlgebra K P.KacMoodyAlgebra)
    (m : VermaModule P Λ) : rep P (VermaModule P Λ) u m = u • m :=
  (VermaModule.map_smul_eq_rep P Λ LieModuleHom.id u m).symm

/-! ### The morphism `Φ : ⊕ᵢ M(-αᵢ) → M(0)` -/

lemma lie_e_lie_f_hwv_zero (i j : ι) : ⁅e P j, ⁅f P i, VermaModule.hwv P 0⁆⁆ = 0 := by
  rw [leibniz_lie, lie_e_f, VermaModule.lie_e_hwv, lie_zero, add_zero]
  split_ifs <;> simp

lemma lie_f_hwv_zero_mem (i : ι) :
    ⁅f P i, VermaModule.hwv P 0⁆ ∈ VermaModule.weightSpace P 0 (-P.root i) := by
  simpa using
    lie_mem_weightSpaceOfMap (h P) (f_mem_rootSpace P i) (VermaModule.hwv_mem_weightSpace P 0)

/-- The morphism `M(-αᵢ) → M(0)`, `v_{-αᵢ} ↦ fᵢ v₀`. -/
def syzygyComponent (i : ι) :
    VermaModule P (-P.root i) →ₗ⁅K,P.KacMoodyAlgebra⁆ VermaModule P 0 :=
  VermaModule.lift P ⁅f P i, VermaModule.hwv P 0⁆
    (fun _ hx ↦ lie_eq_zero_of_mem_nPos (fun j ↦ lie_e_lie_f_hwv_zero P i j) hx)
    (fun a ↦ lie_f_hwv_zero_mem P i a)

lemma syzygyComponent_hwv (i : ι) :
    syzygyComponent P i (VermaModule.hwv P (-P.root i)) = ⁅f P i, VermaModule.hwv P 0⁆ :=
  VermaModule.lift_hwv P _ _ _

/-- The direct sum `E = ⊕ᵢ M(-αᵢ)` of the Verma modules with highest weights `-αᵢ`. -/
abbrev VermaSum : Type _ := DirectSum ι fun i ↦ VermaModule P (-P.root i)

/-- The morphism `Φ : ⊕ᵢ M(-αᵢ) → M(0)` sending `v_{-αᵢ}` to `fᵢ v₀`. -/
def syzygyMap : VermaSum P →ₗ⁅K,P.KacMoodyAlgebra⁆ VermaModule P 0 where
  toLinearMap := DirectSum.toModule K ι _ fun i ↦
    (syzygyComponent P i : VermaModule P (-P.root i) →ₗ[K] VermaModule P 0)
  map_lie' {x m} := by
    let ψ : VermaSum P →ₗ[K] VermaModule P 0 := DirectSum.toModule K ι _ fun i ↦
      (syzygyComponent P i : VermaModule P (-P.root i) →ₗ[K] VermaModule P 0)
    change ψ ⁅x, m⁆ = ⁅x, ψ m⁆
    induction m using DirectSum.induction_on with
    | zero => rw [lie_zero, map_zero, lie_zero]
    | of i m =>
      have : ⁅x, DirectSum.of (fun i ↦ VermaModule P (-P.root i)) i m⁆ =
          DirectSum.of (fun i ↦ VermaModule P (-P.root i)) i ⁅x, m⁆ :=
        ((DirectSum.lieModuleOf K ι P.KacMoodyAlgebra
          (fun i ↦ VermaModule P (-P.root i)) i).map_lie x m).symm
      rw [this, ← DirectSum.lof_eq_of K, ← DirectSum.lof_eq_of K, DirectSum.toModule_lof,
        DirectSum.toModule_lof]
      exact LieModuleHom.map_lie _ _ _
    | add m m' hm hm' => rw [lie_add, map_add, map_add, hm, hm', lie_add]

lemma syzygyMap_of (i : ι) (v : VermaModule P (-P.root i)) :
    syzygyMap P (DirectSum.of (fun i ↦ VermaModule P (-P.root i)) i v) = syzygyComponent P i v :=
  DirectSum.toModule_lof (M := fun i ↦ VermaModule P (-P.root i)) K i v

lemma syzygyMap_apply (m : VermaSum P) : syzygyMap P m = ∑ i, syzygyComponent P i (m i) := by
  conv_lhs => rw [← DirectSum.sum_univ_of m]
  rw [map_sum]
  exact Finset.sum_congr rfl fun i _ ↦ syzygyMap_of P i (m i)

/-- The module of syzygies `Syz = ker Φ ⊆ ⊕ᵢ M(-αᵢ)`. -/
def syzygies : LieSubmodule K P.KacMoodyAlgebra (VermaSum P) := (syzygyMap P).ker

lemma mem_syzygies_iff {m : VermaSum P} : m ∈ syzygies P ↔ syzygyMap P m = 0 :=
  LieModuleHom.mem_ker

lemma apply_mem_weightSpace {μ : Dual K H} {m : VermaSum P}
    (hm : m ∈ weightSpaceOfMap (VermaSum P) (h P) μ) (i : ι) :
    m i ∈ VermaModule.weightSpace P (-P.root i) μ :=
  map_mem_weightSpaceOfMap P
    (DirectSum.lieModuleComponent K ι P.KacMoodyAlgebra (fun i ↦ VermaModule P (-P.root i)) i) hm

lemma of_mem_weightSpace {μ : Dual K H} {i : ι} {v : VermaModule P (-P.root i)}
    (hv : v ∈ VermaModule.weightSpace P (-P.root i) μ) :
    DirectSum.of (fun i ↦ VermaModule P (-P.root i)) i v ∈
      weightSpaceOfMap (VermaSum P) (h P) μ :=
  map_mem_weightSpaceOfMap P
    (DirectSum.lieModuleOf K ι P.KacMoodyAlgebra (fun i ↦ VermaModule P (-P.root i)) i) hv

/-! ### The submodule `T` -/

/-- The weight vectors of `Syz` of weight `-γ` with `ht γ < ht β`, where `β = ∑ kᵢ αᵢ`. -/
def lowerSyzygySet (k : ι → ℤ) : Set (VermaSum P) :=
  {t | t ∈ syzygies P ∧ ∃ l, height l < height k ∧
    t ∈ weightSpaceOfMap (VermaSum P) (h P) (-P.rootOf l)}

/-- The submodule `T ⊆ Syz` generated by the weight spaces `Syz_{-γ}` with `ht γ < ht β`,
where `β = ∑ kᵢ αᵢ`. -/
def lowerSyzygies (k : ι → ℤ) : LieSubmodule K P.KacMoodyAlgebra (VermaSum P) :=
  LieSubmodule.lieSpan K P.KacMoodyAlgebra (lowerSyzygySet P k)

lemma lowerSyzygies_le (k : ι → ℤ) : lowerSyzygies P k ≤ syzygies P :=
  LieSubmodule.lieSpan_le.mpr fun _ ht ↦ ht.1

/-- The span of the `f_{j₁} ⋯ f_{jₘ} t` with `t ∈ lowerSyzygySet P k`; it equals `T`. -/
def lowerSyzygySpan (k : ι → ℤ) : Submodule K (VermaSum P) :=
  Submodule.span K {v | ∃ w t, t ∈ lowerSyzygySet P k ∧ v = rep P _ (fWord P w) t}

lemma lie_f_mem_lowerSyzygySpan (k : ι → ℤ) (j : ι) :
    ∀ m ∈ lowerSyzygySpan P k, ⁅f P j, m⁆ ∈ lowerSyzygySpan P k := by
  refine VermaModule.lie_mem_span_of_forall P ?_
  rintro _ ⟨w, t, ht, rfl⟩
  exact Submodule.subset_span ⟨j :: w, t, ht, (rep_fWord_cons P j w t).symm⟩

lemma lie_h_mem_lowerSyzygySpan (k : ι → ℤ) (a : H) :
    ∀ m ∈ lowerSyzygySpan P k, ⁅h P a, m⁆ ∈ lowerSyzygySpan P k := by
  refine VermaModule.lie_mem_span_of_forall P ?_
  rintro _ ⟨w, t, ht, rfl⟩
  rw [rep_fWord_mem_weightSpace P w ht.2.choose_spec.2 a]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨w, t, ht, rfl⟩)

lemma lie_e_mem_lowerSyzygySpan (k : ι → ℤ) (i : ι) :
    ∀ m ∈ lowerSyzygySpan P k, ⁅e P i, m⁆ ∈ lowerSyzygySpan P k := by
  refine VermaModule.lie_mem_span_of_forall P ?_
  rintro _ ⟨w, t, ht, rfl⟩
  induction w with
  | nil =>
    obtain ⟨hts, l, hl, htl⟩ := ht
    refine Submodule.subset_span ⟨[], ⁅e P i, t⁆, ⟨(syzygies P).lie_mem hts,
      l - Pi.single i 1, ?_, ?_⟩, ?_⟩
    · have := height_add (l - Pi.single i 1) (Pi.single i 1)
      rw [sub_add_cancel] at this
      have h1 : height (Pi.single i 1 : ι → ℤ) = 1 := by simp [height]
      omega
    · have he : e P i ∈ rootSpace P (P.root i) := fun a ↦ lie_h_e P a i
      convert lie_mem_weightSpaceOfMap (h P) he htl using 2
      rw [map_sub, rootOf_single]
      abel
    · rw [rep_fWord_nil, rep_fWord_nil]
  | cons j w ih =>
    rw [rep_fWord_cons, leibniz_lie, lie_e_f]
    refine add_mem ?_ (lie_f_mem_lowerSyzygySpan P k j _ ih)
    split_ifs
    · exact lie_h_mem_lowerSyzygySpan P k _ _ (Submodule.subset_span ⟨w, t, ht, rfl⟩)
    · rw [zero_lie]; exact zero_mem _

lemma lowerSyzygies_le_lowerSyzygySpan (k : ι → ℤ) :
    (lowerSyzygies P k).toSubmodule ≤ lowerSyzygySpan P k := by
  let N : LieSubmodule K P.KacMoodyAlgebra (VermaSum P) :=
    { lowerSyzygySpan P k with
      lie_mem := fun {x m} hm ↦ lie_mem_of_generators P (lowerSyzygySpan P k)
        (lie_e_mem_lowerSyzygySpan P k) (lie_f_mem_lowerSyzygySpan P k)
        (lie_h_mem_lowerSyzygySpan P k) x m hm }
  have : lowerSyzygies P k ≤ N := LieSubmodule.lieSpan_le.mpr fun t ht ↦
    Submodule.subset_span ⟨[], t, ht, (rep_fWord_nil P t).symm⟩
  exact this

lemma exists_eq_sum_of_mem_iSup {S : ι → Submodule K (VermaSum P)} {s : VermaSum P}
    (hs : s ∈ ⨆ j, (S j).map (toEnd K P.KacMoodyAlgebra (VermaSum P) (f P j))) :
    ∃ t : ι → VermaSum P, (∀ j, t j ∈ S j) ∧ s = ∑ j, ⁅f P j, t j⁆ := by
  induction hs using Submodule.iSup_induction' with
  | mem j s hs =>
    obtain ⟨t, ht, rfl⟩ := hs
    refine ⟨Pi.single j t, fun j' ↦ ?_, ?_⟩
    · by_cases hj : j' = j
      · subst hj; rwa [Pi.single_eq_same]
      · rw [Pi.single_eq_of_ne hj]; exact zero_mem _
    · rw [Finset.sum_eq_single j (fun j' _ hj ↦ by rw [Pi.single_eq_of_ne hj, lie_zero])
        (by simp), Pi.single_eq_same]
      rfl
  | zero => exact ⟨0, fun _ ↦ zero_mem _, by simp⟩
  | add s s' _ _ hs hs' =>
    obtain ⟨t, ht, rfl⟩ := hs
    obtain ⟨t', ht', rfl⟩ := hs'
    exact ⟨t + t', fun j ↦ add_mem (ht j) (ht' j), by
      simp [lie_add, Finset.sum_add_distrib]⟩

/-! ### Weight spaces of Verma modules and words in `U(𝔫₋)` -/

variable [CharZero K]

lemma equivEnvNNeg_mem_weightSpace {Λ : Dual K H} {l : ι → ℤ}
    {τ : UniversalEnvelopingAlgebra K (nNeg P)} (hτ : τ ∈ nNegFWordSpan P l) :
    equivEnvNNeg P Λ τ ∈ VermaModule.weightSpace P Λ (Λ - P.rootOf l) := by
  have : (nNegFWordSpan P l).map (equivEnvNNeg P Λ).toLinearMap ≤
      VermaModule.weightSpace P Λ (Λ - P.rootOf l) := by
    rw [nNegFWordSpan, Submodule.map_span, Submodule.span_le]
    rintro _ ⟨_, ⟨w, rfl, rfl⟩, rfl⟩
    have := VermaModule.fWord_smul_mem_weightSpace P Λ w
    rw [AuxLieAlgebra.wordWt_eq_rootOf] at this
    simpa [map_nNegFWord] using this
  exact this (Submodule.mem_map_of_mem hτ)

/-- The weight space `M(Λ)_{Λ - γ}`, `γ = ∑ lᵢ αᵢ`, is the image of the span of the words with
letter counts `l` under `U(𝔫₋) ≅ M(Λ)`. -/
lemma exists_mem_nNegFWordSpan {Λ : Dual K H} {l : ι → ℤ} {m : VermaModule P Λ}
    (hm : m ∈ VermaModule.weightSpace P Λ (Λ - P.rootOf l)) :
    ∃ τ ∈ nNegFWordSpan P l, equivEnvNNeg P Λ τ = m := by
  rw [VermaModule.weightSpace_eq_wordSpan] at hm
  have : VermaModule.wordSpan P Λ (Λ - P.rootOf l) ≤
      (nNegFWordSpan P l).map (equivEnvNNeg P Λ).toLinearMap := by
    rw [VermaModule.wordSpan, Submodule.span_le]
    rintro _ ⟨w, hw, rfl⟩
    refine ⟨nNegFWord P w, Submodule.subset_span ⟨w, ?_, rfl⟩, ?_⟩
    · apply P.rootOf_injective
      rw [← AuxLieAlgebra.wordWt_eq_rootOf]
      exact sub_right_injective hw
    · simp [map_nNegFWord]
  obtain ⟨τ, hτ, rfl⟩ := this hm
  exact ⟨τ, hτ, rfl⟩

lemma lie_f_equivEnvNNeg {Λ : Dual K H} (j : ι) (τ : UniversalEnvelopingAlgebra K (nNeg P)) :
    ⁅f P j, equivEnvNNeg P Λ τ⁆ = equivEnvNNeg P Λ (ιᵤ (nNegF P j) * τ) := by
  rw [VermaModule.equivEnvNNeg_mul, VermaModule.lie_eq_smul, UniversalEnvelopingAlgebra.map_ι]
  rfl
lemma syzygyComponent_equivEnvNNeg (i : ι) (τ : UniversalEnvelopingAlgebra K (nNeg P)) :
    syzygyComponent P i (equivEnvNNeg P (-P.root i) τ) =
      equivEnvNNeg P 0 (τ * ιᵤ (nNegF P i)) := by
  rw [VermaModule.equivEnvNNeg_apply, VermaModule.map_smul_eq_rep, syzygyComponent_hwv,
    rep_eq_smul, VermaModule.equivEnvNNeg_mul, VermaModule.lie_eq_smul,
    VermaModule.equivEnvNNeg_apply, UniversalEnvelopingAlgebra.map_ι]
  rfl

/-- `Φ((τᵢ v_{-αᵢ})ᵢ) = (∑ᵢ τᵢ fᵢ) v₀`. -/
lemma syzygyMap_eq_equivEnvNNeg {t : VermaSum P} {τ : ι → UniversalEnvelopingAlgebra K (nNeg P)}
    (ht : ∀ i, equivEnvNNeg P _ (τ i) = t i) :
    syzygyMap P t = equivEnvNNeg P 0 (∑ i, τ i * ιᵤ (nNegF P i)) := by
  rw [syzygyMap_apply, map_sum]
  exact Finset.sum_congr rfl fun i _ ↦ by rw [← ht i, syzygyComponent_equivEnvNNeg]

/-- `T_{-β} ⊆ ∑ⱼ fⱼ Syz_{-β+αⱼ}`. -/
lemma mem_iSup_of_mem_lowerSyzygies {k : ι → ℤ} {s : VermaSum P} (hs : s ∈ lowerSyzygies P k)
    (hsk : s ∈ weightSpaceOfMap (VermaSum P) (h P) (-P.rootOf k)) :
    s ∈ ⨆ j, ((syzygies P).toSubmodule ⊓
      weightSpaceOfMap (VermaSum P) (h P) (-P.rootOf (k - Pi.single j 1))).map
        (toEnd K P.KacMoodyAlgebra (VermaSum P) (f P j)) := by
  let W : Dual K H → Submodule K (VermaSum P) := fun ν ↦ Submodule.span K
    {v | ∃ w t l, height l < height k ∧ t ∈ syzygies P ∧
      t ∈ weightSpaceOfMap (VermaSum P) (h P) (-P.rootOf l) ∧
      -P.rootOf l - P.rootOf (AuxLieAlgebra.counts w) = ν ∧ v = rep P _ (fWord P w) t}
  have hW : ∀ ν, W ν ≤ weightSpaceOfMap (VermaSum P) (h P) ν := fun ν ↦ by
    rw [Submodule.span_le]
    rintro _ ⟨w, t, l, -, -, htl, rfl, rfl⟩
    exact rep_fWord_mem_weightSpace P w htl
  have h1 : s ∈ ⨆ ν, W ν := by
    refine (Submodule.span_le.mpr ?_ : lowerSyzygySpan P k ≤ _)
      (lowerSyzygies_le_lowerSyzygySpan P k hs)
    rintro _ ⟨w, t, ⟨hts, l, hl, htl⟩, rfl⟩
    exact Submodule.mem_iSup_of_mem _ (Submodule.subset_span ⟨w, t, l, hl, hts, htl, rfl, rfl⟩)
  have h2 := mem_of_mem_iSup_of_le (h P) W hW hsk h1
  refine (Submodule.span_le.mpr ?_ : W _ ≤ _) h2
  rintro _ ⟨w, t, l, hl, hts, htl, hν, rfl⟩
  have hlw : l + AuxLieAlgebra.counts w = k := by
    apply P.rootOf_injective
    rw [map_add, ← neg_inj, neg_add, ← sub_eq_add_neg]
    exact hν
  obtain rfl | ⟨j, w, rfl⟩ : w = [] ∨ ∃ j w', w = j :: w' := by
    cases w with
    | nil => exact Or.inl rfl
    | cons j w => exact Or.inr ⟨j, w, rfl⟩
  · rw [AuxLieAlgebra.counts_nil, add_zero] at hlw
    exact absurd hl (by rw [hlw]; exact lt_irrefl _)
  · refine Submodule.mem_iSup_of_mem j ⟨rep P _ (fWord P w) t,
      ⟨rep_fWord_mem P (syzygies P) w hts, ?_⟩, (rep_fWord_cons P j w t).symm⟩
    have e : -P.rootOf (k - Pi.single j 1) = -P.rootOf l - P.rootOf (AuxLieAlgebra.counts w) := by
      rw [← hlw, AuxLieAlgebra.counts_cons, map_sub, map_add, map_add, rootOf_single]
      abel
    rw [e]
    exact rep_fWord_mem_weightSpace P w htl

end Matrix.Realization.KacMoodyAlgebra

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H)

lemma height_sub_single (k : ι → ℤ) (i : ι) :
    height (k - Pi.single i 1) = height k - 1 := by
  have := height_add (k - Pi.single i 1) (Pi.single i 1)
  rw [sub_add_cancel] at this
  have h1 : height (Pi.single i 1 : ι → ℤ) = 1 := by simp [height]
  omega

namespace SerrePresentedAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

variable [CharZero K] (hA : A.IsGeneralizedCartan)

local notation "ιᵤ" => UniversalEnvelopingAlgebra.ι K
local notation "mapφ" => UniversalEnvelopingAlgebra.map (negProjN P hA)

include hA in
/-- **A lowest weight vector of `𝔯̂₋` gives a primitive syzygy.** Let `x ∈ 𝔯̂₋` be a nonzero weight
vector of weight `-β`, `β = ∑ kᵢ αᵢ ∈ Q₊ \ {0}`, such that `𝔯̂₋` has no nonzero weight vectors of
weight `-γ` with `ht γ < ht β`. Then there is a syzygy `s ∈ Syz ⊆ ⊕ᵢ M(-αᵢ)` of weight `-β` which
does not lie in the submodule `T` generated by the syzygies of weight `-γ`, `ht γ < ht β`, while
`eᵢ s ∈ T` for all `i`.

This is a step of the proof of the Gabber–Kac theorem ([Kac] §9.11, [GK]); the argument
is reconstructed, see the module docstring. -/
theorem exists_syzygy {k : ι → ℤ} (hk : k ∈ posCone ι)
    (hmin : ∀ l ∈ posCone ι, height l < height k →
      (radicalNeg P).toSubmodule ⊓ rootSpace P (-P.rootOf l) = ⊥)
    {x : P.SerrePresentedAlgebra} (hx : x ∈ radicalNeg P) (hxk : x ∈ rootSpace P (-P.rootOf k))
    (hx0 : x ≠ 0) :
    ∃ s ∈ KacMoodyAlgebra.syzygies P,
      s ∈ weightSpaceOfMap (KacMoodyAlgebra.VermaSum P) (KacMoodyAlgebra.h P) (-P.rootOf k) ∧
      s ∉ KacMoodyAlgebra.lowerSyzygies P k ∧
      ∀ i, ⁅KacMoodyAlgebra.e P i, s⁆ ∈ KacMoodyAlgebra.lowerSyzygies P k := by
  have hlt : ∀ i, height (k - Pi.single i 1) < height k := fun i ↦ by
    rw [height_sub_single]; omega
  -- Step 1: `ι x = ∑ᵢ xᵢ fᵢ` in `U(𝔫̂₋)`, and the syzygy `s = (φ(xᵢ) v_{-αᵢ})ᵢ`.
  let x' : (fHom P).range := ⟨x, by
    obtain ⟨y, hy⟩ := radicalNeg_le_range_fHom P hA hx
    exact ⟨y, hy⟩⟩
  obtain ⟨y, hy, hxy⟩ := exists_eq_sum_mul_f P hA hk (x := x') hxk
  have hφy : ∀ i, mapφ (y i) ∈ KacMoodyAlgebra.nNegFWordSpan P (k - Pi.single i 1) := fun i ↦ by
    rw [← map_negProj_nNegFWordSpan P hA]
    exact Submodule.mem_map_of_mem (hy i)
  let s : KacMoodyAlgebra.VermaSum P := ∑ i, DirectSum.of (fun i ↦ KacMoodyAlgebra.VermaModule P
    (-P.root i)) i (KacMoodyAlgebra.VermaModule.equivEnvNNeg P _ (mapφ (y i)))
  have hs : ∀ i, s i = KacMoodyAlgebra.VermaModule.equivEnvNNeg P _ (mapφ (y i)) := fun i ↦ by
    simp [s, DirectSum.of_apply]
  have hsw : s ∈ weightSpaceOfMap (KacMoodyAlgebra.VermaSum P) (KacMoodyAlgebra.h P)
      (-P.rootOf k) := by
    refine Submodule.sum_mem _ fun i _ ↦ KacMoodyAlgebra.of_mem_weightSpace P ?_
    have := KacMoodyAlgebra.equivEnvNNeg_mem_weightSpace P (Λ := -P.root i) (hφy i)
    rwa [show -P.root i - P.rootOf (k - Pi.single i 1) = -P.rootOf k by
      rw [map_sub, rootOf_single]; abel] at this
  have hsS : s ∈ KacMoodyAlgebra.syzygies P := by
    rw [KacMoodyAlgebra.mem_syzygies_iff,
      KacMoodyAlgebra.syzygyMap_eq_equivEnvNNeg P (fun i ↦ (hs i).symm)]
    have : ∑ i, mapφ (y i) * ιᵤ (KacMoodyAlgebra.nNegF P i) = mapφ (ιᵤ x') := by
      rw [hxy, map_sum]
      simp_rw [map_mul, UniversalEnvelopingAlgebra.map_ι, negProj_nNegF]
    rw [this, UniversalEnvelopingAlgebra.map_ι,
      show negProjN P hA x' = 0 from (negProj_eq_zero_iff P hA (x := x')).mpr hx, map_zero,
      map_zero]
  refine ⟨s, hsS, hsw, ?_, fun i ↦ ?_⟩
  swap
  · -- Step 2: `eᵢ s ∈ T`.
    refine LieSubmodule.subset_lieSpan ⟨(KacMoodyAlgebra.syzygies P).lie_mem hsS,
      k - Pi.single i 1, hlt i, ?_⟩
    have he : KacMoodyAlgebra.e P i ∈ KacMoodyAlgebra.rootSpace P (P.root i) :=
      fun a ↦ KacMoodyAlgebra.lie_h_e P a i
    have := lie_mem_weightSpaceOfMap (KacMoodyAlgebra.h P) he hsw
    rwa [show P.root i + -P.rootOf k = -P.rootOf (k - Pi.single i 1) by
      rw [map_sub, rootOf_single]; abel] at this
  -- Step 3: if `s ∈ T` then `s = ∑ⱼ fⱼ tⱼ` with `tⱼ ∈ Syz_{-β+αⱼ}`.
  intro hsT
  obtain ⟨t, ht, hst⟩ := KacMoodyAlgebra.exists_eq_sum_of_mem_iSup P
    (KacMoodyAlgebra.mem_iSup_of_mem_lowerSyzygies P hsT hsw)
  -- Step 4: write `tⱼ = (τⱼᵢ v_{-αᵢ})ᵢ` and lift the `τⱼᵢ` to `U(𝔫̂₋)`.
  have hτ : ∀ j i, ∃ τ ∈ KacMoodyAlgebra.nNegFWordSpan P (k - Pi.single j 1 - Pi.single i 1),
      KacMoodyAlgebra.VermaModule.equivEnvNNeg P (-P.root i) τ = t j i := fun j i ↦ by
    have := KacMoodyAlgebra.apply_mem_weightSpace P (ht j).2 i
    refine KacMoodyAlgebra.exists_mem_nNegFWordSpan P ?_
    rwa [show -P.root i - P.rootOf (k - Pi.single j 1 - Pi.single i 1) =
      -P.rootOf (k - Pi.single j 1) by
        rw [map_sub (P.rootOf) (k - Pi.single j 1), rootOf_single]; abel]
  choose τ hτS hτe using hτ
  have hlift : ∀ j i, ∃ τ' ∈ nNegFWordSpan P (k - Pi.single j 1 - Pi.single i 1),
      mapφ τ' = τ j i := fun j i ↦ by
    have := hτS j i
    rw [← map_negProj_nNegFWordSpan P hA] at this
    obtain ⟨τ', h1, h2⟩ := this
    exact ⟨τ', h1, h2⟩
  choose τ' hτ'S hτ'e using hlift
  -- `tⱼ ∈ Syz` means `∑ᵢ τⱼᵢ fᵢ = 0` in `U(𝔫₋)`, hence `∑ᵢ τ'ⱼᵢ fᵢ = 0` in `U(𝔫̂₋)`.
  have hrel : ∀ j, ∑ i, τ j i * ιᵤ (KacMoodyAlgebra.nNegF P i) = 0 := fun j ↦ by
    have h1 := (KacMoodyAlgebra.mem_syzygies_iff P).mp (ht j).1
    rwa [KacMoodyAlgebra.syzygyMap_eq_equivEnvNNeg P (hτe j),
      LinearEquiv.map_eq_zero_iff] at h1
  have hρ : ∀ j, ∑ i, τ' j i * ιᵤ (nNegF P i) = 0 := fun j ↦ by
    refine eq_zero_of_map_negProj_eq_zero P hA hmin (hlt j)
      (Submodule.sum_mem _ fun i _ ↦ ?_) ?_
    · have := mul_mem_nNegFWordSpan P (hτ'S j i) (ι_nNegF_mem_nNegFWordSpan P i)
      rwa [sub_add_cancel] at this
    · rw [map_sum]
      simp_rw [map_mul, UniversalEnvelopingAlgebra.map_ι, negProj_nNegF, hτ'e]
      exact hrel j
  -- Comparing components of `s = ∑ⱼ fⱼ tⱼ`: `φ(xᵢ) = ∑ⱼ fⱼ τⱼᵢ`, hence `xᵢ = ∑ⱼ fⱼ τ'ⱼᵢ`.
  have hcomp : ∀ i, mapφ (y i) = ∑ j, ιᵤ (KacMoodyAlgebra.nNegF P j) * τ j i := fun i ↦ by
    have h1 := congrArg (fun v : KacMoodyAlgebra.VermaSum P ↦ v i) hst
    simp only [hs, DirectSum.sum_apply, DirectSum.lie_module_bracket_apply] at h1
    simp_rw [← hτe, KacMoodyAlgebra.lie_f_equivEnvNNeg, ← map_sum] at h1
    exact (KacMoodyAlgebra.VermaModule.equivEnvNNeg P _).injective h1
  have hy' : ∀ i, y i = ∑ j, ιᵤ (nNegF P j) * τ' j i := fun i ↦ by
    rw [← sub_eq_zero]
    refine eq_zero_of_map_negProj_eq_zero P hA hmin (hlt i)
      (sub_mem (hy i) (Submodule.sum_mem _ fun j _ ↦ ?_)) ?_
    · have := mul_mem_nNegFWordSpan P (ι_nNegF_mem_nNegFWordSpan P j) (hτ'S j i)
      rwa [show Pi.single j 1 + (k - Pi.single j 1 - Pi.single i 1) = k - Pi.single i 1 by
        abel] at this
    · rw [map_sub, hcomp i, map_sum]
      simp_rw [map_mul, UniversalEnvelopingAlgebra.map_ι, negProj_nNegF, hτ'e]
      exact sub_self _
  -- Conclusion: `ι x = ∑ᵢ ∑ⱼ fⱼ τ'ⱼᵢ fᵢ = ∑ⱼ fⱼ (∑ᵢ τ'ⱼᵢ fᵢ) = 0`, so `x = 0` by PBW.
  apply hx0
  have hι : ιᵤ x' = 0 := by
    rw [hxy]
    simp_rw [hy', Finset.sum_mul]
    rw [Finset.sum_comm]
    simp_rw [mul_assoc, ← Finset.mul_sum, hρ, mul_zero, Finset.sum_const_zero]
  have := UniversalEnvelopingAlgebra.ι_injective K (fHom P).range (hι.trans (map_zero _).symm)
  exact congrArg Subtype.val this

end SerrePresentedAlgebra

end Matrix.Realization
