/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import Mathlib.Algebra.Lie.Free
import Mathlib.LinearAlgebra.Basis.VectorSpace
import LieLean.Algebra.Lie.UniversalEnveloping.PBW

/-!
# Free Lie algebras: generation and the embedding into the free associative algebra

Additions to `Mathlib.Algebra.Lie.Free`.

## Main definitions

* `FreeLieAlgebra.toFreeAlgebra`: the canonical morphism from the free Lie algebra on `X` to the
  free associative algebra on `X`.

## Main results

* `FreeLieAlgebra.lieSpan_range_of`: the free Lie algebra is generated by `X`.
* `FreeLieAlgebra.induction_on`: induction on the generators.
* `FreeLieAlgebra.toFreeAlgebra_injective`: over a field, the canonical Lie algebra morphism
  from the free Lie algebra on `X` to the free associative algebra on `X` is injective. This is a
  consequence of the Poincaré–Birkhoff–Witt theorem, since `U(L(X))` is the free associative
  algebra (`FreeLieAlgebra.universalEnvelopingEquivFreeAlgebra`).

## References

* N. Bourbaki, *Lie groups and Lie algebras*, Ch. II, §3.1.
-/

namespace FreeLieAlgebra

variable (R X : Type*) [CommRing R]

/-- The free Lie algebra on `X` is generated, as a Lie algebra, by `X`. -/
theorem lieSpan_range_of :
    LieSubalgebra.lieSpan R (FreeLieAlgebra R X) (Set.range (of R)) = ⊤ := by
  set S := LieSubalgebra.lieSpan R (FreeLieAlgebra R X) (Set.range (of R))
  let g : FreeLieAlgebra R X →ₗ⁅R⁆ S :=
    lift R fun x ↦ ⟨of R x, LieSubalgebra.subset_lieSpan (Set.mem_range_self x)⟩
  have hg : S.incl.comp g = LieHom.id := by ext x; simp [g]
  rw [eq_top_iff]
  intro y _
  have : S.incl (g y) = y := by rw [← LieHom.comp_apply, hg, LieHom.id_apply]
  rw [← this]
  exact (g y).2

variable {R X} in
/-- Induction principle for the free Lie algebra. -/
@[elab_as_elim]
theorem induction_on {p : FreeLieAlgebra R X → Prop} (y : FreeLieAlgebra R X)
    (of : ∀ x, p (of R x)) (zero : p 0) (add : ∀ y z, p y → p z → p (y + z))
    (smul : ∀ (a : R) y, p y → p (a • y)) (lie : ∀ y z, p y → p z → p ⁅y, z⁆) : p y := by
  have hy : y ∈ LieSubalgebra.lieSpan R (FreeLieAlgebra R X) (Set.range (FreeLieAlgebra.of R)) :=
    by rw [lieSpan_range_of]; trivial
  induction hy using LieSubalgebra.lieSpan_induction with
  | mem x hx => obtain ⟨x, rfl⟩ := hx; exact of x
  | zero => exact zero
  | add y z _ _ hy hz => exact add y z hy hz
  | smul a y _ hy => exact smul a y hy
  | lie y z _ _ hy hz => exact lie y z hy hz

attribute [local instance 100] LieRing.ofAssociativeRing

/-- The canonical morphism from the free Lie algebra to the free associative algebra. -/
noncomputable def toFreeAlgebra : FreeLieAlgebra R X →ₗ⁅R⁆ FreeAlgebra R X :=
  lift R (FreeAlgebra.ι R)

@[simp] lemma toFreeAlgebra_of (x : X) : toFreeAlgebra R X (of R x) = FreeAlgebra.ι R x := by
  simp [toFreeAlgebra]

lemma toFreeAlgebra_eq :
    toFreeAlgebra R X = ((universalEnvelopingEquivFreeAlgebra R X).toAlgHom :
      UniversalEnvelopingAlgebra R (FreeLieAlgebra R X) →ₗ⁅R⁆ FreeAlgebra R X).comp
      (UniversalEnvelopingAlgebra.ι R) := by
  ext x
  simp [toFreeAlgebra]

/-- Over a field, the free Lie algebra embeds in the free associative algebra (a consequence of
the Poincaré–Birkhoff–Witt theorem). -/
theorem toFreeAlgebra_injective (K : Type*) [Field K] :
    Function.Injective (toFreeAlgebra K X) := by
  rw [toFreeAlgebra_eq, LieHom.coe_comp]
  exact (universalEnvelopingEquivFreeAlgebra K X).injective.comp
    (UniversalEnvelopingAlgebra.ι_injective K _)

end FreeLieAlgebra
