/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import Mathlib.Algebra.Lie.Subalgebra

/-!
# The Lie subalgebra generated by a set is spanned by iterated brackets

Additions to `Mathlib.Algebra.Lie.Subalgebra`.

## Main definitions

* `LieAlgebra.adProd`: the iterated bracket `⁅y₁, ⁅y₂, ⋯ ⁅yₖ, x⁆⋯⁆⁆` attached to a list
  `[y₁, …, yₖ]` and an element `x`.

## Main results

* `LieSubalgebra.lieSpan_toSubmodule_eq_span_adProd`: the Lie subalgebra generated by a set `s` is
  spanned, as a module, by the iterated brackets `⁅y₁, ⁅y₂, ⋯ ⁅yₖ, x⁆⋯⁆⁆` with `yᵢ, x ∈ s`.
-/

namespace LieAlgebra

variable {R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]

/-- The iterated bracket `⁅y₁, ⁅y₂, ⋯ ⁅yₖ, x⁆⋯⁆⁆`. -/
def adProd (l : List L) (x : L) : L := l.foldr (fun y z ↦ ⁅y, z⁆) x

@[simp] lemma adProd_nil (x : L) : adProd [] x = x := rfl

@[simp] lemma adProd_cons (y : L) (l : List L) (x : L) :
    adProd (y :: l) x = ⁅y, adProd l x⁆ := rfl

end LieAlgebra

namespace LieSubalgebra

open LieAlgebra

variable (R : Type*) {L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]

/-- The set of iterated brackets of elements of `s`. -/
def adProdSet (s : Set L) : Set L :=
  {z | ∃ l : List L, (∀ y ∈ l, y ∈ s) ∧ ∃ x ∈ s, z = adProd l x}

variable {R}

lemma subset_adProdSet (s : Set L) : s ⊆ adProdSet s :=
  fun x hx ↦ ⟨[], by simp, x, hx, rfl⟩

lemma lie_mem_span_adProdSet {s : Set L} {y : L} (hy : y ∈ s) {z : L}
    (hz : z ∈ Submodule.span R (adProdSet s)) : ⁅y, z⁆ ∈ Submodule.span R (adProdSet s) := by
  induction hz using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨l, hl, x, hx, rfl⟩ := hz
    refine Submodule.subset_span ⟨y :: l, ?_, x, hx, rfl⟩
    intro w hw
    rcases List.mem_cons.mp hw with rfl | hw
    exacts [hy, hl w hw]
  | zero => simp
  | add z₁ z₂ _ _ h₁ h₂ => rw [lie_add]; exact Submodule.add_mem _ h₁ h₂
  | smul c z _ h => rw [lie_smul]; exact Submodule.smul_mem _ c h

lemma lie_mem_span_adProdSet_of_mem {s : Set L} {z w : L}
    (hz : z ∈ Submodule.span R (adProdSet s)) (hw : w ∈ Submodule.span R (adProdSet s)) :
    ⁅z, w⁆ ∈ Submodule.span R (adProdSet s) := by
  induction hz using Submodule.span_induction generalizing w with
  | mem z hz =>
    obtain ⟨l, hl, x, hx, rfl⟩ := hz
    induction l generalizing w with
    | nil => exact lie_mem_span_adProdSet hx hw
    | cons y l ih =>
      have hy : y ∈ s := hl y (List.mem_cons_self ..)
      have hl' : ∀ u ∈ l, u ∈ s := fun u hu ↦ hl u (List.mem_cons_of_mem _ hu)
      rw [adProd_cons, lie_lie]
      exact Submodule.sub_mem _ (lie_mem_span_adProdSet hy (ih hw hl'))
        (ih (lie_mem_span_adProdSet hy hw) hl')
  | zero => simp
  | add z₁ z₂ _ _ h₁ h₂ => rw [add_lie]; exact Submodule.add_mem _ (h₁ hw) (h₂ hw)
  | smul c z _ h => rw [smul_lie]; exact Submodule.smul_mem _ c (h hw)

variable (R) in
/-- The Lie subalgebra generated by `s` is spanned by iterated brackets of elements of `s`. -/
theorem lieSpan_toSubmodule_eq_span_adProd (s : Set L) :
    (lieSpan R L s).toSubmodule = Submodule.span R (adProdSet s) := by
  refine le_antisymm ?_ ?_
  · let S : LieSubalgebra R L :=
      { Submodule.span R (adProdSet s) with
        lie_mem' := fun hz hw ↦ lie_mem_span_adProdSet_of_mem hz hw }
    have : lieSpan R L s ≤ S :=
      lieSpan_le.mpr fun x hx ↦ Submodule.subset_span (subset_adProdSet s hx)
    exact this
  · rw [Submodule.span_le]
    rintro _ ⟨l, hl, x, hx, rfl⟩
    induction l with
    | nil => exact subset_lieSpan hx
    | cons y l ih =>
      exact (lieSpan R L s).lie_mem (subset_lieSpan (hl y (List.mem_cons_self ..)))
        (ih fun u hu ↦ hl u (List.mem_cons_of_mem _ hu))

end LieSubalgebra
