/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.GabberKac.MapCoeffs
import LieLean.Algebra.QuantumGroup.QBinomial
import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# Weight components of Serre ideals in free algebras

For a commutative ring `R`, the projection `FreeAlgebra.weightProj ν` of `FreeAlgebra R X` onto
the span of the words of weight `ν` is compatible with multiplication by words
(`FreeAlgebra.weightProj_wordBasis_mul`, `FreeAlgebra.weightProj_mul_wordBasis`).

For a Cartan datum `(I, ·)` with Cartan matrix `(aᵢⱼ)`, a field `K` and parameters `q : I → K`,
let `sᵢⱼ = Σ_{r=0}^{m} (-1)^r [m r]_{qᵢ} θᵢ^{m-r} θⱼ θᵢ^r` (`m = 1 - aᵢⱼ`) be the (binomial)
quantum Serre element (`LusztigF.serreWord`); for `q = 1` it is the classical Serre element, up to
the sign `(-1)^m`. We show that the weight-`ν` component of the two-sided ideal generated by the
`sᵢⱼ`, `i ≠ j`, is spanned by the products `a sᵢⱼ b` of weight `ν` with words `a`, `b`
(`LusztigF.weightProj_mem_serreSpan`): the ideal is graded, with explicit homogeneous spanning
sets.

## Main definitions

* `FreeAlgebra.weightProj ν`: the projection onto the words of weight `ν`.
* `LusztigF.serreWord D q i j`, `LusztigF.serreProduct D q g`, `LusztigF.serreSpan D q ν`.

## Main results

* `LusztigF.weightProj_mem_serreSpan`: the weight components of the Serre ideal.
-/

noncomputable section

open Finset QuantumGroup

namespace FreeAlgebra

variable {R X : Type*} [CommRing R] [DecidableEq X]

/-! ### Projections onto weights -/

variable (R) in
/-- The projection of `FreeAlgebra R X` onto the span of the words of weight `ν`. -/
def weightProj (ν : X →₀ ℕ) : FreeAlgebra R X →ₗ[R] FreeAlgebra R X :=
  (wordBasis R X).constr R fun w ↦ if LusztigF.wordWeight w = ν then wordBasis R X w else 0

lemma weightProj_wordBasis (ν : X →₀ ℕ) (w : List X) :
    weightProj R ν (wordBasis R X w) = if LusztigF.wordWeight w = ν then wordBasis R X w else 0 :=
  (wordBasis R X).constr_basis R _ w

lemma weightProj_of_mem {ν μ : X →₀ ℕ} {x : FreeAlgebra R X} (hx : x ∈ wordSpan R μ) :
    weightProj R ν x = if μ = ν then x else 0 := by
  induction hx using wordSpan_induction with
  | word w hw => rw [weightProj_wordBasis, hw]
  | zero => simp
  | add y z _ _ hy hz => rw [map_add, hy, hz]; split_ifs <;> simp
  | smul c y _ hy => rw [map_smul, hy]; split_ifs <;> simp

lemma weightProj_self {ν : X →₀ ℕ} {x : FreeAlgebra R X} (hx : x ∈ wordSpan R ν) :
    weightProj R ν x = x := by
  simp [weightProj_of_mem hx]

lemma weightProj_mem (ν : X →₀ ℕ) (x : FreeAlgebra R X) : weightProj R ν x ∈ wordSpan R ν := by
  induction x using induction_wordBasis with
  | zero => simp
  | add y z hy hz => rw [map_add]; exact add_mem hy hz
  | smul c y hy => rw [map_smul]; exact Submodule.smul_mem _ _ hy
  | word w =>
    rw [weightProj_wordBasis]
    split_ifs with h
    · exact wordBasis_mem_wordSpan_of_eq h
    · exact zero_mem _

omit [DecidableEq X] in
lemma wordWeight_add_eq_iff {a b ν : X →₀ ℕ} : a + b = ν ↔ a ≤ ν ∧ b = ν - a := by
  constructor
  · rintro rfl; exact ⟨le_self_add, (add_tsub_cancel_left a b).symm⟩
  · rintro ⟨h, rfl⟩; exact add_tsub_cancel_of_le h

lemma weightProj_wordBasis_mul (ν : X →₀ ℕ) (a : List X) (x : FreeAlgebra R X) :
    weightProj R ν (wordBasis R X a * x) =
      if LusztigF.wordWeight a ≤ ν then
        wordBasis R X a * weightProj R (ν - LusztigF.wordWeight a) x else 0 := by
  induction x using induction_wordBasis with
  | zero => simp
  | add y z hy hz => rw [mul_add, map_add, hy, hz]; split_ifs <;> simp [mul_add]
  | smul c y hy => rw [mul_smul_comm, map_smul, hy]; split_ifs <;> simp
  | word w =>
    rw [← wordBasis_append, weightProj_wordBasis, weightProj_wordBasis, LusztigF.wordWeight_append]
    by_cases h1 : LusztigF.wordWeight a ≤ ν
    · by_cases h2 : LusztigF.wordWeight w = ν - LusztigF.wordWeight a
      · have h := wordWeight_add_eq_iff.2 ⟨h1, h2⟩
        simp [h1, h2]
      · have h : ¬ LusztigF.wordWeight a + LusztigF.wordWeight w = ν :=
          fun h ↦ h2 (wordWeight_add_eq_iff.1 h).2
        simp [h, h1, h2]
    · have h : ¬ LusztigF.wordWeight a + LusztigF.wordWeight w = ν :=
        fun h ↦ h1 (wordWeight_add_eq_iff.1 h).1
      simp [h, h1]

lemma weightProj_mul_wordBasis (ν : X →₀ ℕ) (b : List X) (x : FreeAlgebra R X) :
    weightProj R ν (x * wordBasis R X b) =
      if LusztigF.wordWeight b ≤ ν then
        weightProj R (ν - LusztigF.wordWeight b) x * wordBasis R X b else 0 := by
  induction x using induction_wordBasis with
  | zero => simp
  | add y z hy hz => rw [add_mul, map_add, hy, hz]; split_ifs <;> simp [add_mul]
  | smul c y hy => rw [smul_mul_assoc, map_smul, hy]; split_ifs <;> simp
  | word w =>
    rw [← wordBasis_append, weightProj_wordBasis, weightProj_wordBasis, LusztigF.wordWeight_append,
      add_comm]
    by_cases h1 : LusztigF.wordWeight b ≤ ν
    · by_cases h2 : LusztigF.wordWeight w = ν - LusztigF.wordWeight b
      · have h := wordWeight_add_eq_iff.2 ⟨h1, h2⟩
        simp [h1, h2]
      · have h : ¬ LusztigF.wordWeight b + LusztigF.wordWeight w = ν :=
          fun h ↦ h2 (wordWeight_add_eq_iff.1 h).2
        simp [h, h1, h2]
    · have h : ¬ LusztigF.wordWeight b + LusztigF.wordWeight w = ν :=
        fun h ↦ h1 (wordWeight_add_eq_iff.1 h).1
      simp [h, h1]

lemma weightProj_mul_ι_pow {ν : X →₀ ℕ} {i : X} {N : ℕ} (h : ν i < N)
    (x : FreeAlgebra R X) : weightProj R ν (x * ι R i ^ N) = 0 := by
  have hN : ι R i ^ N = wordBasis R X (List.replicate N i) := by simp
  rw [hN, weightProj_mul_wordBasis, ite_eq_right_iff]
  intro hle
  exfalso
  have := hle i
  rw [LusztigF.wordWeight_apply, List.count_replicate_self] at this
  omega

end FreeAlgebra

namespace LusztigF

open FreeAlgebra

variable {K I : Type*} [Field K] (D : LusztigCartanDatum I) (q : I → K)

/-! ### Serre words and their products -/

/-- The exponent `m = 1 - aᵢⱼ` of the Serre relation. -/
def serreExp (i j : I) : ℕ := (1 - D.cartanMatrix i j).toNat

/-- The weight `m αᵢ + αⱼ` of the Serre element `sᵢⱼ`. -/
def serreWeight (i j : I) : I →₀ ℕ := serreExp D i j • Finsupp.single i 1 + Finsupp.single j 1

/-- The binomial quantum Serre element `Σ_{r=0}^{m} (-1)^r [m r]_{qᵢ} θᵢ^{m-r} θⱼ θᵢ^r` with
parameter `qᵢ`, `m = 1 - aᵢⱼ`. -/
def serreWord (i j : I) : LusztigF K I :=
  qSerre (q i) (serreExp D i j) (θ K i) (θ K j)

lemma wordWeight_replicate (N : ℕ) (i : I) :
    wordWeight (List.replicate N i) = N • Finsupp.single i 1 := by
  induction N with
  | zero => simp
  | succ N ih => rw [List.replicate_succ, wordWeight_cons, ih, succ_nsmul, add_comm]

lemma serreWord_mem (i j : I) : serreWord D q i j ∈ weightSpace K (serreWeight D i j) := by
  rw [serreWord, qSerre]
  refine Submodule.sum_mem _ fun r hr ↦ Submodule.smul_mem _ _ ?_
  have hr := Finset.mem_range.1 hr
  have e : θ K i ^ (serreExp D i j - r) * θ K j * θ K i ^ r =
      wordBasis K I (List.replicate (serreExp D i j - r) i ++ [j] ++ List.replicate r i) := by
    simp [List.prod_replicate, mul_assoc]
  rw [e]
  refine wordBasis_mem_wordSpan_of_eq ?_
  rw [wordWeight_append, wordWeight_append, wordWeight_replicate, wordWeight_replicate, serreWeight]
  simp only [wordWeight_cons, wordWeight_nil, add_zero]
  rw [add_comm _ (r • _), ← add_assoc, ← add_nsmul, Nat.add_sub_cancel' (by omega)]

/-- The product `a sᵢⱼ b` for `g = (a, i, j, b)` with words `a`, `b`. -/
def serreProduct (g : List I × I × I × List I) : LusztigF K I :=
  wordBasis K I g.1 * serreWord D q g.2.1 g.2.2.1 * wordBasis K I g.2.2.2

/-- The weight `|a| + m αᵢ + αⱼ + |b|` of `serreProduct D q (a, i, j, b)`. -/
def serreIndexWeight (g : List I × I × I × List I) : I →₀ ℕ :=
  wordWeight g.1 + serreWeight D g.2.1 g.2.2.1 + wordWeight g.2.2.2

/-- The indices `(a, i, j, b)`, `i ≠ j`, of the Serre products of weight `ν`. -/
def serreIndices (ν : I →₀ ℕ) : Set (List I × I × I × List I) :=
  {g | g.2.1 ≠ g.2.2.1 ∧ serreIndexWeight D g = ν}

/-- The span of the Serre products `a sᵢⱼ b` (`i ≠ j`, `a`, `b` words) of weight `ν`. -/
def serreSpan (ν : I →₀ ℕ) : Submodule K (LusztigF K I) :=
  Submodule.span K (serreProduct D q '' serreIndices D ν)

lemma serreProduct_mem (g : List I × I × I × List I) :
    serreProduct D q g ∈ weightSpace K (serreIndexWeight D g) :=
  mul_mem_weightSpace (mul_mem_weightSpace (wordBasis_mem_wordSpan g.1) (serreWord_mem D q _ _))
    (wordBasis_mem_wordSpan g.2.2.2)

lemma serreSpan_le_weightSpace (ν : I →₀ ℕ) : serreSpan D q ν ≤ weightSpace K ν := by
  rw [serreSpan, Submodule.span_le]
  rintro _ ⟨g, ⟨_, hg⟩, rfl⟩
  exact hg ▸ serreProduct_mem D q g

lemma serreProduct_mem_serreSpan {g : List I × I × I × List I} (hg : g.2.1 ≠ g.2.2.1) :
    serreProduct D q g ∈ serreSpan D q (serreIndexWeight D g) :=
  Submodule.subset_span ⟨g, ⟨hg, rfl⟩, rfl⟩

lemma wordBasis_mul_mem_serreSpan (a : List I) {μ : I →₀ ℕ} {x : LusztigF K I}
    (hx : x ∈ serreSpan D q μ) : wordBasis K I a * x ∈ serreSpan D q (wordWeight a + μ) := by
  induction hx using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨g, ⟨hg, rfl⟩, rfl⟩ := hy
    have e1 : wordBasis K I a * serreProduct D q g =
        serreProduct D q (a ++ g.1, g.2.1, g.2.2.1, g.2.2.2) := by
      simp only [serreProduct, wordBasis_append, mul_assoc]
    have e2 : wordWeight a + serreIndexWeight D g =
        serreIndexWeight D (a ++ g.1, g.2.1, g.2.2.1, g.2.2.2) := by
      simp only [serreIndexWeight, wordWeight_append, add_assoc]
    rw [e1, e2]
    exact serreProduct_mem_serreSpan D q hg
  | zero => simp
  | add y z _ _ hy hz => rw [mul_add]; exact add_mem hy hz
  | smul c y _ hy => rw [mul_smul_comm]; exact Submodule.smul_mem _ _ hy

lemma mul_wordBasis_mem_serreSpan (b : List I) {μ : I →₀ ℕ} {x : LusztigF K I}
    (hx : x ∈ serreSpan D q μ) : x * wordBasis K I b ∈ serreSpan D q (μ + wordWeight b) := by
  induction hx using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨g, ⟨hg, rfl⟩, rfl⟩ := hy
    have e1 : serreProduct D q g * wordBasis K I b =
        serreProduct D q (g.1, g.2.1, g.2.2.1, g.2.2.2 ++ b) := by
      simp only [serreProduct, wordBasis_append, mul_assoc]
    have e2 : serreIndexWeight D g + wordWeight b =
        serreIndexWeight D (g.1, g.2.1, g.2.2.1, g.2.2.2 ++ b) := by
      simp only [serreIndexWeight, wordWeight_append, add_assoc]
    rw [e1, e2]
    exact serreProduct_mem_serreSpan D q hg
  | zero => simp
  | add y z _ _ hy hz => rw [add_mul]; exact add_mem hy hz
  | smul c y _ hy => rw [smul_mul_assoc]; exact Submodule.smul_mem _ _ hy

variable [DecidableEq I]

/-- **The weight components of the Serre ideal.** The weight-`ν` component of any element of the
two-sided ideal generated by the Serre elements `sᵢⱼ` (`i ≠ j`) is a linear combination of the
products `a sᵢⱼ b` of weight `ν`. -/
theorem weightProj_mem_serreSpan {x : LusztigF K I}
    (hx : x ∈ TwoSidedIdeal.span {y | ∃ i j, i ≠ j ∧ serreWord D q i j = y}) (ν : I →₀ ℕ) :
    weightProj K ν x ∈ serreSpan D q ν := by
  induction hx using TwoSidedIdeal.span_induction generalizing ν with
  | mem y hy =>
    obtain ⟨i, j, hij, rfl⟩ := hy
    rw [weightProj_of_mem (serreWord_mem D q i j)]
    split_ifs with h
    · have := serreProduct_mem_serreSpan D q (g := ([], i, j, [])) hij
      simp only [serreProduct, serreIndexWeight, wordBasis_nil, one_mul, mul_one, wordWeight_nil,
        zero_add, add_zero] at this
      exact h ▸ this
    · exact zero_mem _
  | zero => simp
  | add y z _ _ hy hz => rw [map_add]; exact add_mem (hy ν) (hz ν)
  | neg y _ hy => rw [map_neg]; exact neg_mem (hy ν)
  | left_absorb a y _ hy =>
    induction a using induction_wordBasis with
    | zero => simp
    | add a a' ha ha' => rw [add_mul, map_add]; exact add_mem ha ha'
    | smul c a ha => rw [smul_mul_assoc, map_smul]; exact Submodule.smul_mem _ _ ha
    | word w =>
      rw [weightProj_wordBasis_mul]
      split_ifs with h
      · have := wordBasis_mul_mem_serreSpan D q w (hy (ν - wordWeight w))
        rwa [add_tsub_cancel_of_le h] at this
      · exact zero_mem _
  | right_absorb b y _ hy =>
    induction b using induction_wordBasis with
    | zero => simp
    | add b b' hb hb' => rw [mul_add, map_add]; exact add_mem hb hb'
    | smul c b hb => rw [mul_smul_comm, map_smul]; exact Submodule.smul_mem _ _ hb
    | word w =>
      rw [weightProj_mul_wordBasis]
      split_ifs with h
      · have := mul_wordBasis_mem_serreSpan D q w (hy (ν - wordWeight w))
        rwa [tsub_add_cancel_of_le h] at this
      · exact zero_mem _

end LusztigF
