/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.GroupTheory.Coxeter.Exchange
import Mathlib.Data.List.Induction

/-!
# The Bruhat order

Let `cs : CoxeterSystem M W` be a Coxeter system (possibly infinite). The Bruhat order on `W` is
the reflexive-transitive closure of the relation `u → w` ("Bruhat step") where `u⁻¹ w` is a
reflection and `ℓ(u) < ℓ(w)`. We prove its basic properties, following [BB] Ch. 2. The main tool
is the strong exchange condition (`LieLean.GroupTheory.Coxeter.Exchange`).

## Main definitions

* `CoxeterSystem.BruhatStep`, `CoxeterSystem.BruhatLE`: Bruhat steps and the Bruhat order.
* `CoxeterSystem.BruhatOrder`: a type synonym for `W` carrying the Bruhat order as a
  `PartialOrder` (with `⊥ = 1`).

## Main results

* `CoxeterSystem.IsReduced.bruhatLE_iff`: **the subword property** ([BB] Thm. 2.2.2): for a
  reduced word `ω` of `w`, `u ≤ w` iff `u` is the product of a subword of `ω`.
* `CoxeterSystem.BruhatLE.length_le`, `CoxeterSystem.bruhatLE_inv_iff`,
  `CoxeterSystem.one_bruhatLE`: `u ≤ w → ℓ(u) ≤ ℓ(w)`, `u⁻¹ ≤ w⁻¹ ↔ u ≤ w`, `1 ≤ w`.
* `CoxeterSystem.BruhatLE.lifting`, `CoxeterSystem.BruhatLE.lifting_left`: **the lifting
  property** ([BB] Prop. 2.2.7).
* `CoxeterSystem.mul_simple_bruhatLE_mul_simple_iff`: if `s` is a right descent of `u` and `w`,
  then `us ≤ ws ↔ u ≤ w`.
* `CoxeterSystem.bruhatLE_iff_reflTransGen`: **the chain property** ([BB] Thm. 2.2.6): the
  Bruhat order is generated by steps that increase the length by one;
  `CoxeterSystem.BruhatOrder.covBy_iff` describes the covering relation.
* `CoxeterSystem.finite_setOf_bruhatLE`, `CoxeterSystem.BruhatOrder.finite_Icc`: Bruhat intervals
  are finite.

## Implementation notes

The subword property is proved as in [BB] §2.2: the "only if" direction by the strong exchange
and deletion conditions; for the "if" direction we use the elementary lemma
`CoxeterSystem.BruhatLE.mul_simple_or` (`u ≤ w → u s ≤ w ∨ u s ≤ w s`, cf. [BB] §2.2 and
[HumC] §5.9 (check)), whose proof we reconstructed from the strong exchange condition.

## References

* [BB] A. Björner, F. Brenti, *Combinatorics of Coxeter groups*, GTM 231, Springer 2005, Ch. 2.
* [HumC] J. E. Humphreys, *Reflection groups and Coxeter groups*, CUP 1990, §5.9–5.11.
-/

open List

namespace CoxeterSystem

variable {B W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

local prefix:100 "s " => cs.simple
local prefix:100 "π " => cs.wordProd
local prefix:100 "ℓ " => cs.length

/-- One step of the Bruhat order: `u⁻¹ w` is a reflection and `ℓ(u) < ℓ(w)`. Equivalently,
`w = u t = t' u` for reflections `t`, `t'` (`CoxeterSystem.bruhatStep_iff_left`). -/
def BruhatStep (u w : W) : Prop := cs.IsReflection (u⁻¹ * w) ∧ ℓ u < ℓ w

/-- The **Bruhat order** ([HumC] §5.9, [BB] Def. 2.1.1): `u ≤ w` if there is a chain
`u = x₀ → x₁ → ⋯ → xₖ = w` in which each `x_{i+1}` is obtained from `xᵢ` by multiplying by a
reflection and `ℓ(xᵢ) < ℓ(x_{i+1})`. -/
def BruhatLE (u w : W) : Prop := Relation.ReflTransGen cs.BruhatStep u w

variable {cs}

/-- A Bruhat step `u → w` can equivalently be described by the reflection `w u⁻¹`. -/
theorem bruhatStep_iff_left {u w : W} :
    cs.BruhatStep u w ↔ cs.IsReflection (w * u⁻¹) ∧ ℓ u < ℓ w := by
  have : u⁻¹ * w = u⁻¹ * (w * u⁻¹) * u⁻¹⁻¹ := by group
  rw [BruhatStep, this, cs.isReflection_conj_iff]

/-- A Bruhat step increases the length. -/
theorem BruhatStep.length_lt {u w : W} (h : cs.BruhatStep u w) : ℓ u < ℓ w := h.2

/-- A Bruhat step is a Bruhat relation. -/
theorem BruhatStep.bruhatLE {u w : W} (h : cs.BruhatStep u w) : cs.BruhatLE u w :=
  Relation.ReflTransGen.single h

/-- Bruhat steps are compatible with inversion. -/
theorem BruhatStep.inv {u w : W} (h : cs.BruhatStep u w) : cs.BruhatStep u⁻¹ w⁻¹ := by
  refine ⟨?_, by simpa using h.2⟩
  simpa using (bruhatStep_iff_left.mp h).1.isReflection_inv

variable (cs) in
/-- The Bruhat order is reflexive. -/
@[refl]
theorem bruhatLE_refl (w : W) : cs.BruhatLE w w := Relation.ReflTransGen.refl

/-- The Bruhat order is transitive. -/
theorem BruhatLE.trans {u v w : W} (h₁ : cs.BruhatLE u v) (h₂ : cs.BruhatLE v w) :
    cs.BruhatLE u w :=
  Relation.ReflTransGen.trans h₁ h₂

/-- If `u ≤ w`, then `u = w` or `ℓ(u) < ℓ(w)`. -/
theorem BruhatLE.eq_or_length_lt {u w : W} (h : cs.BruhatLE u w) : u = w ∨ ℓ u < ℓ w := by
  induction h with
  | refl => exact .inl rfl
  | tail _ hs ih =>
    rcases ih with rfl | h
    · exact .inr hs.2
    · exact .inr (h.trans hs.2)

/-- If `u ≤ w` in the Bruhat order, then `ℓ(u) ≤ ℓ(w)`. -/
theorem BruhatLE.length_le {u w : W} (h : cs.BruhatLE u w) : ℓ u ≤ ℓ w := by
  rcases h.eq_or_length_lt with rfl | h
  · rfl
  · exact h.le

/-- The Bruhat order is antisymmetric. -/
theorem BruhatLE.antisymm {u w : W} (h₁ : cs.BruhatLE u w) (h₂ : cs.BruhatLE w u) : u = w := by
  rcases h₁.eq_or_length_lt with h | h
  · exact h
  · exact absurd h₂.length_le (not_le.mpr h)

/-- The Bruhat order is compatible with inversion. -/
theorem BruhatLE.inv {u w : W} (h : cs.BruhatLE u w) : cs.BruhatLE u⁻¹ w⁻¹ := by
  induction h with
  | refl => rfl
  | tail _ hs ih => exact ih.trans hs.inv.bruhatLE

/-- `u ≤ w ↔ u⁻¹ ≤ w⁻¹` ([BB] Cor. 2.2.5 (check)). -/
@[simp]
theorem bruhatLE_inv_iff {u w : W} : cs.BruhatLE u⁻¹ w⁻¹ ↔ cs.BruhatLE u w :=
  ⟨fun h ↦ by simpa using h.inv, BruhatLE.inv⟩

/-- `w → w sᵢ` is a Bruhat step if `sᵢ` is not a right descent of `w`. -/
theorem bruhatStep_mul_simple {w : W} {i : B} (h : ¬cs.IsRightDescent w i) :
    cs.BruhatStep w (w * s i) :=
  ⟨by simpa using cs.isReflection_simple i, by
    rw [(cs.not_isRightDescent_iff).mp h]; omega⟩

/-- `w → sᵢ w` is a Bruhat step if `sᵢ` is not a left descent of `w`. -/
theorem bruhatStep_simple_mul {w : W} {i : B} (h : ¬cs.IsLeftDescent w i) :
    cs.BruhatStep w (s i * w) := by
  rw [bruhatStep_iff_left]
  exact ⟨by simpa using cs.isReflection_simple i, by
    rw [(cs.not_isLeftDescent_iff).mp h]; omega⟩

/-- `w ≤ w sᵢ` if `sᵢ` is not a right descent of `w`. -/
theorem bruhatLE_mul_simple {w : W} {i : B} (h : ¬cs.IsRightDescent w i) :
    cs.BruhatLE w (w * s i) :=
  (bruhatStep_mul_simple h).bruhatLE

/-- `w sᵢ ≤ w` if `sᵢ` is a right descent of `w`. -/
theorem mul_simple_bruhatLE {w : W} {i : B} (h : cs.IsRightDescent w i) :
    cs.BruhatLE (w * s i) w := by
  have := bruhatLE_mul_simple ((cs.isRightDescent_iff_not_isRightDescent_mul).mp h)
  rwa [simple_mul_simple_cancel_right] at this

/-- `w ≤ sᵢ w` if `sᵢ` is not a left descent of `w`. -/
theorem bruhatLE_simple_mul {w : W} {i : B} (h : ¬cs.IsLeftDescent w i) :
    cs.BruhatLE w (s i * w) :=
  (bruhatStep_simple_mul h).bruhatLE

/-- `sᵢ w ≤ w` if `sᵢ` is a left descent of `w`. -/
theorem simple_mul_bruhatLE {w : W} {i : B} (h : cs.IsLeftDescent w i) :
    cs.BruhatLE (s i * w) w := by
  have := bruhatLE_simple_mul ((cs.isLeftDescent_iff_not_isLeftDescent_mul).mp h)
  rwa [simple_mul_simple_cancel_left] at this

/-- The key step of the proof of the subword property: if `y → z` is a Bruhat step, then either
`y sᵢ = z` or `y sᵢ → z sᵢ` is a Bruhat step. -/
theorem BruhatStep.mul_simple {y z : W} (h : cs.BruhatStep y z) (i : B) :
    y * s i = z ∨ cs.BruhatStep (y * s i) (z * s i) := by
  set t := y⁻¹ * z with ht_def
  have ht : cs.IsReflection t := h.1
  have hrefl : cs.IsReflection ((y * s i)⁻¹ * (z * s i)) := by
    have e : (y * s i)⁻¹ * (z * s i) = s i * t * (s i)⁻¹ := by
      rw [ht_def, mul_inv_rev]
      simp only [inv_simple]
      group
    rw [e]
    exact ht.conj _
  have hzt : z * t = y := by
    rw [← ht.inv, ht_def]
    group
  have hz : z * s i = y * s i * ((y * s i)⁻¹ * (z * s i)) := by group
  have hne : ℓ (z * s i) ≠ ℓ (y * s i) := by
    rw [hz]; exact hrefl.length_mul_left_ne _
  rcases hne.lt_or_gt with hlt | hlt
  swap
  · exact .inr ⟨hrefl, hlt⟩
  left
  have h1 := cs.length_mul_simple y i
  have h2 := cs.length_mul_simple z i
  have h3 := h.2
  have hzi : cs.IsRightDescent z i := by
    rw [isRightDescent_iff]; omega
  obtain ⟨ζ, hζ, hζe⟩ := cs.exists_isReduced (z * s i)
  have hzω : z = π (ζ ++ [i]) := by
    rw [wordProd_append, ← hζe, wordProd_singleton, simple_mul_simple_cancel_right]
  have hred : ℓ z = ζ.length + 1 := by
    rw [← hζ.eq, ← hζe]; rw [isRightDescent_iff] at hzi; omega
  have hinv : cs.IsRightInversion z t := ⟨ht, by rw [hzt]; exact h.2⟩
  rw [hzω] at hinv
  obtain ⟨j, hj, hje⟩ := hinv.exists_wordProd_mul_eq
  rw [← hzω, hzt] at hje
  simp only [length_append, length_singleton] at hj
  rcases Nat.lt_succ_iff_lt_or_eq.mp hj with hj | rfl
  · exfalso
    rw [eraseIdx_append_of_lt_length hj, wordProd_append, wordProd_singleton] at hje
    have : y * s i = π (ζ.eraseIdx j) := by rw [hje, simple_mul_simple_cancel_right]
    have h4 := cs.length_wordProd_le (ζ.eraseIdx j)
    have h5 := List.length_eraseIdx_add_one hj
    rw [← this] at h4
    rw [hζe, hζ.eq] at hlt
    omega
  · rw [eraseIdx_append_of_length_le le_rfl, Nat.sub_self] at hje
    simp only [eraseIdx_cons_zero, append_nil] at hje
    rw [hje, ← hζe, simple_mul_simple_cancel_right]

/-- If `u → w` is a Bruhat step with reflection `t = u⁻¹ w`, then `w t = u`. -/
theorem BruhatStep.mul_eq {u w : W} (h : cs.BruhatStep u w) : w * (u⁻¹ * w) = u := by
  rw [← h.1.inv]
  group

/-- If `u → w` is a Bruhat step, then `u⁻¹ w` is a right inversion of `w`. -/
theorem BruhatStep.isRightInversion {u w : W} (h : cs.BruhatStep u w) :
    cs.IsRightInversion w (u⁻¹ * w) :=
  ⟨h.1, by rw [h.mul_eq]; exact h.2⟩

/-- If `y⁻¹ z` is a reflection, so is `(y sᵢ)⁻¹ (z sᵢ)`. -/
theorem isReflection_mul_simple_inv_mul {y z : W} (h : cs.IsReflection (y⁻¹ * z)) (i : B) :
    cs.IsReflection ((y * s i)⁻¹ * (z * s i)) := by
  have e : (y * s i)⁻¹ * (z * s i) = s i * (y⁻¹ * z) * (s i)⁻¹ := by
    rw [mul_inv_rev]
    simp only [inv_simple]
    group
  rw [e]
  exact h.conj _

/-- If `u ≤ w`, then `u sᵢ ≤ w` or `u sᵢ ≤ w sᵢ` (cf. [BB] §2.2, [HumC] §5.9 (check)). -/
theorem BruhatLE.mul_simple_or {u w : W} (h : cs.BruhatLE u w) (i : B) :
    cs.BruhatLE (u * s i) w ∨ cs.BruhatLE (u * s i) (w * s i) := by
  induction h with
  | refl => exact .inr (bruhatLE_refl _ _)
  | tail _ hs ih =>
    rcases ih with h | h
    · exact .inl (h.trans hs.bruhatLE)
    · rcases hs.mul_simple i with e | hs'
      · exact .inl (e ▸ h)
      · exact .inr (h.trans hs'.bruhatLE)

/-- If `ω sᵢ` is reduced, then `sᵢ` is not a right descent of `π ω`. -/
theorem IsReduced.not_isRightDescent_of_append_singleton {ω : List B} {i : B}
    (hω : cs.IsReduced (ω ++ [i])) : ¬cs.IsRightDescent (π ω) i := by
  have hω' : cs.IsReduced ω := by simpa using hω.take ω.length
  rw [not_isRightDescent_iff, ← wordProd_singleton, ← wordProd_append, hω.eq, hω'.eq]
  simp

/-- Every subword of a reduced word for `w` is a word for an element `≤ w`
([BB] Thm. 2.2.2, "if" direction). -/
theorem IsReduced.bruhatLE_of_sublist {ω σ : List B} (hω : cs.IsReduced ω) (hσ : σ <+ ω) :
    cs.BruhatLE (π σ) (π ω) := by
  induction ω using List.reverseRecOn generalizing σ with
  | nil => rw [sublist_nil.mp hσ]
  | append_singleton ω i ih =>
    have hω' : cs.IsReduced ω := by simpa using hω.take ω.length
    have hstep : cs.BruhatLE (π ω) (π (ω ++ [i])) := by
      rw [wordProd_append, wordProd_singleton]
      exact bruhatLE_mul_simple hω.not_isRightDescent_of_append_singleton
    obtain ⟨σ₁, σ₂, rfl, h₁, h₂⟩ := sublist_append_iff.mp hσ
    rcases sublist_singleton.mp h₂ with rfl | rfl
    · simpa using (ih hω' h₁).trans hstep
    · rw [wordProd_append, wordProd_singleton]
      rcases (ih hω' h₁).mul_simple_or i with h | h
      · exact h.trans hstep
      · rwa [wordProd_append, wordProd_singleton]

/-- If `u ≤ w`, then every reduced word for `w` has a reduced subword for `u`
([BB] Thm. 2.2.2, "only if" direction). -/
theorem IsReduced.exists_sublist_of_bruhatLE {ω : List B} (hω : cs.IsReduced ω) {u : W}
    (h : cs.BruhatLE u (π ω)) : ∃ σ, σ <+ ω ∧ cs.IsReduced σ ∧ π σ = u := by
  induction h using Relation.ReflTransGen.head_induction_on with
  | refl => exact ⟨ω, Sublist.refl _, hω, rfl⟩
  | head hs _ ih =>
    obtain ⟨σ, hσ, -, hσe⟩ := ih
    have hinv := hs.isRightInversion
    rw [← hσe] at hinv
    obtain ⟨j, -, hj⟩ := hinv.exists_wordProd_mul_eq
    rw [hσe, hs.mul_eq] at hj
    obtain ⟨σ', hσ', hσ'r, hσ'e⟩ := cs.exists_sublist_isReduced (σ.eraseIdx j)
    exact ⟨σ', hσ'.trans ((eraseIdx_sublist _ _).trans hσ), hσ'r, hσ'e.trans hj.symm⟩

/-- **The subword property** ([BB] Thm. 2.2.2, [HumC] §5.10 (check)): if `ω` is a reduced word
for `w`, then `u ≤ w` in the Bruhat order if and only if `u` is the product of a subword of `ω`. -/
theorem IsReduced.bruhatLE_iff {ω : List B} (hω : cs.IsReduced ω) {u : W} :
    cs.BruhatLE u (π ω) ↔ ∃ σ, σ <+ ω ∧ π σ = u :=
  ⟨fun h ↦ let ⟨σ, h₁, _, h₃⟩ := hω.exists_sublist_of_bruhatLE h; ⟨σ, h₁, h₃⟩,
    fun ⟨_, h₁, h₂⟩ ↦ h₂ ▸ hω.bruhatLE_of_sublist h₁⟩

/-- **The subword property**, with reduced subwords ([BB] Thm. 2.2.2). -/
theorem IsReduced.bruhatLE_iff' {ω : List B} (hω : cs.IsReduced ω) {u : W} :
    cs.BruhatLE u (π ω) ↔ ∃ σ, σ <+ ω ∧ cs.IsReduced σ ∧ π σ = u :=
  ⟨hω.exists_sublist_of_bruhatLE, fun ⟨_, h₁, _, h₂⟩ ↦ h₂ ▸ hω.bruhatLE_of_sublist h₁⟩

variable (cs) in
/-- The identity is the least element of the Bruhat order. -/
theorem one_bruhatLE (w : W) : cs.BruhatLE 1 w := by
  obtain ⟨ω, hω, rfl⟩ := cs.exists_isReduced w
  exact hω.bruhatLE_iff.mpr ⟨[], nil_sublist _, wordProd_nil _⟩

variable (cs) in
/-- Lower Bruhat intervals are finite. -/
theorem finite_setOf_bruhatLE (w : W) : {u | cs.BruhatLE u w}.Finite := by
  obtain ⟨ω, hω, rfl⟩ := cs.exists_isReduced w
  refine (ω.sublists.map cs.wordProd).finite_toSet.subset fun u hu ↦ ?_
  obtain ⟨σ, hσ, rfl⟩ := hω.bruhatLE_iff.mp hu
  exact List.mem_map.mpr ⟨σ, List.mem_sublists.mpr hσ, rfl⟩

variable (cs) in
/-- Bruhat intervals are finite. -/
theorem finite_setOf_bruhatLE_and_bruhatLE (u w : W) :
    {v | cs.BruhatLE u v ∧ cs.BruhatLE v w}.Finite :=
  (cs.finite_setOf_bruhatLE w).subset fun _ hv ↦ hv.2

/-- If `sᵢ` is a right descent of `w`, then `w` has a reduced word ending with `i`. -/
theorem exists_isReduced_append_singleton {w : W} {i : B} (hw : cs.IsRightDescent w i) :
    ∃ ω, cs.IsReduced (ω ++ [i]) ∧ π ω = w * s i := by
  obtain ⟨ω, hω, hωe⟩ := cs.exists_isReduced (w * s i)
  refine ⟨ω, ?_, hωe.symm⟩
  rw [isRightDescent_iff] at hw
  unfold IsReduced
  rw [wordProd_append, ← hωe, wordProd_singleton, simple_mul_simple_cancel_right, length_append,
    ← hω.eq, ← hωe, length_singleton, hw]

/-- **The lifting property** ([BB] Prop. 2.2.7, right-handed version): if `u ≤ w`, `sᵢ` is a right
descent of `w` but not of `u`, then `u ≤ w sᵢ` and `u sᵢ ≤ w`. -/
theorem BruhatLE.lifting {u w : W} {i : B} (h : cs.BruhatLE u w) (hw : cs.IsRightDescent w i)
    (hu : ¬cs.IsRightDescent u i) : cs.BruhatLE u (w * s i) ∧ cs.BruhatLE (u * s i) w := by
  obtain ⟨ω, hω, hωe⟩ := cs.exists_isReduced_append_singleton hw
  have hω' : cs.IsReduced ω := by simpa using hω.take ω.length
  have hwω : w = π (ω ++ [i]) := by
    rw [wordProd_append, hωe, wordProd_singleton, simple_mul_simple_cancel_right]
  have h1 : cs.BruhatLE u (w * s i) := by
    rw [hwω] at h
    obtain ⟨σ, hσ, hσr, rfl⟩ := hω.exists_sublist_of_bruhatLE h
    obtain ⟨σ₁, σ₂, rfl, h₁, h₂⟩ := sublist_append_iff.mp hσ
    rcases sublist_singleton.mp h₂ with rfl | rfl
    · rw [← hωe, append_nil]
      exact hω'.bruhatLE_of_sublist h₁
    · exfalso
      apply hu
      rw [isRightDescent_iff, wordProd_append, wordProd_singleton, simple_mul_simple_cancel_right,
        ← wordProd_singleton, ← wordProd_append, hσr.eq, length_append, length_singleton]
      have hσ₁ : cs.IsReduced σ₁ := by simpa using hσr.take σ₁.length
      rw [hσ₁.eq]
  refine ⟨h1, ?_⟩
  rcases h1.mul_simple_or i with h2 | h2
  · exact h2.trans (mul_simple_bruhatLE hw)
  · rwa [simple_mul_simple_cancel_right] at h2

/-- **The lifting property** ([BB] Prop. 2.2.7): if `u ≤ w`, `sᵢ` is a left descent of `w` but
not of `u`, then `u ≤ sᵢ w` and `sᵢ u ≤ w`. -/
theorem BruhatLE.lifting_left {u w : W} {i : B} (h : cs.BruhatLE u w)
    (hw : cs.IsLeftDescent w i) (hu : ¬cs.IsLeftDescent u i) :
    cs.BruhatLE u (s i * w) ∧ cs.BruhatLE (s i * u) w := by
  rw [← isRightDescent_inv_iff] at hw hu
  obtain ⟨h1, h2⟩ := h.inv.lifting hw hu
  exact ⟨by simpa using h1.inv, by simpa using h2.inv⟩

/-- If `sᵢ` is a right descent of both `u` and `w`, then `u sᵢ ≤ w sᵢ ↔ u ≤ w`
([BB] Prop. 2.2.7 (check), [HumC] §5.9 Prop. (check)). -/
theorem mul_simple_bruhatLE_mul_simple_iff {u w : W} {i : B} (hu : cs.IsRightDescent u i)
    (hw : cs.IsRightDescent w i) : cs.BruhatLE (u * s i) (w * s i) ↔ cs.BruhatLE u w := by
  constructor
  · intro h
    rcases h.mul_simple_or i with h | h <;> rw [simple_mul_simple_cancel_right] at h
    · exact h.trans (mul_simple_bruhatLE hw)
    · rwa [simple_mul_simple_cancel_right] at h
  · intro h
    obtain ⟨ω, hω, hωe⟩ := cs.exists_isReduced_append_singleton hw
    have hω' : cs.IsReduced ω := by simpa using hω.take ω.length
    have hwω : w = π (ω ++ [i]) := by
      rw [wordProd_append, hωe, wordProd_singleton, simple_mul_simple_cancel_right]
    rw [hwω] at h
    obtain ⟨σ, hσ, -, rfl⟩ := hω.exists_sublist_of_bruhatLE h
    obtain ⟨σ₁, σ₂, rfl, h₁, h₂⟩ := sublist_append_iff.mp hσ
    rw [← hωe]
    rcases sublist_singleton.mp h₂ with rfl | rfl
    · rw [append_nil] at hu ⊢
      exact (mul_simple_bruhatLE hu).trans (hω'.bruhatLE_of_sublist h₁)
    · rw [wordProd_append, wordProd_singleton, simple_mul_simple_cancel_right]
      exact hω'.bruhatLE_of_sublist h₁

/-- If `sᵢ` is a left descent of both `u` and `w`, then `sᵢ u ≤ sᵢ w ↔ u ≤ w`. -/
theorem simple_mul_bruhatLE_simple_mul_iff {u w : W} {i : B} (hu : cs.IsLeftDescent u i)
    (hw : cs.IsLeftDescent w i) : cs.BruhatLE (s i * u) (s i * w) ↔ cs.BruhatLE u w := by
  rw [← isRightDescent_inv_iff] at hu hw
  have := mul_simple_bruhatLE_mul_simple_iff hu hw
  rw [bruhatLE_inv_iff] at this
  rw [← this, ← bruhatLE_inv_iff]
  simp

/-- If `u < w` in the Bruhat order, then there is `v` with `u ≤ v` and a Bruhat step `v → w` with
`ℓ(v) + 1 = ℓ(w)`. This is the inductive step of the chain property ([BB] Thm. 2.2.6); the proof
follows [BB] (induction on `ℓ(w)` using the lifting property). -/
theorem BruhatLE.exists_bruhatStep_length_eq {u w : W} (h : cs.BruhatLE u w) (hne : u ≠ w) :
    ∃ v, cs.BruhatLE u v ∧ cs.BruhatStep v w ∧ ℓ w = ℓ v + 1 := by
  induction hn : ℓ w using Nat.strong_induction_on generalizing u w with
  | _ n ih =>
  subst hn
  have hlt := h.eq_or_length_lt.resolve_left hne
  have hw1 : w ≠ 1 := by rintro rfl; simp at hlt
  obtain ⟨i, hi⟩ := cs.exists_rightDescent_of_ne_one hw1
  have hwi := (cs.isRightDescent_iff).mp hi
  have hstep : cs.BruhatStep (w * s i) w := by
    have := bruhatStep_mul_simple ((cs.isRightDescent_iff_not_isRightDescent_mul).mp hi)
    rwa [simple_mul_simple_cancel_right] at this
  by_cases hu : cs.IsRightDescent u i
  · have h' := (mul_simple_bruhatLE_mul_simple_iff hu hi).mpr h
    have hne' : u * s i ≠ w * s i := fun e ↦ hne (mul_right_cancel e)
    obtain ⟨v', hv', hv's, hv'l⟩ := ih _ (by omega) h' hne' rfl
    have hor := hv'.mul_simple_or i
    rw [simple_mul_simple_cancel_right] at hor
    by_cases hv : cs.IsRightDescent v' i
    · refine ⟨w * s i, ?_, hstep, by omega⟩
      rcases hor with hor | hor
      · exact hor.trans hv's.bruhatLE
      · exact (hor.trans (mul_simple_bruhatLE hv)).trans hv's.bruhatLE
    · refine ⟨v' * s i, ?_, ⟨?_, ?_⟩, ?_⟩
      · rcases hor with hor | hor
        · exact hor.trans (bruhatLE_mul_simple hv)
        · exact hor
      · simpa using isReflection_mul_simple_inv_mul hv's.1 i
      · rw [(cs.not_isRightDescent_iff).mp hv]; omega
      · rw [(cs.not_isRightDescent_iff).mp hv]; omega
  · exact ⟨w * s i, (h.lifting hi hu).1, hstep, by omega⟩

/-- **The chain property** ([BB] Thm. 2.2.6, [HumC] §5.11 (check)): the Bruhat order is generated
by the Bruhat steps `v → w` with `ℓ(w) = ℓ(v) + 1`. Equivalently, if `u ≤ w` there is a chain
`u = x₀ → x₁ → ⋯ → xₖ = w` with `ℓ(xⱼ) = ℓ(u) + j`. -/
theorem bruhatLE_iff_reflTransGen {u w : W} :
    cs.BruhatLE u w ↔
      Relation.ReflTransGen (fun x y ↦ cs.BruhatStep x y ∧ ℓ y = ℓ x + 1) u w := by
  refine ⟨fun h ↦ ?_, fun h ↦ Relation.ReflTransGen.mono (fun _ _ h ↦ h.1) _ _ h⟩
  induction hn : ℓ w using Nat.strong_induction_on generalizing w with
  | _ n ih =>
  subst hn
  by_cases hne : u = w
  · rw [hne]
  obtain ⟨v, huv, hvw, hl⟩ := h.exists_bruhatStep_length_eq hne
  exact (ih _ (by omega) huv rfl).tail ⟨hvw, hl⟩

/-- Multiplying by a reflection moves up or down one Bruhat step. -/
theorem IsReflection.bruhatStep_or {t : W} (ht : cs.IsReflection t) (w : W) :
    cs.BruhatStep w (w * t) ∨ cs.BruhatStep (w * t) w := by
  rcases (ht.length_mul_left_ne w).lt_or_gt with h | h
  · exact .inr ⟨by simpa [ht.inv] using ht, h⟩
  · exact .inl ⟨by simpa using ht, h⟩

/-! ### The Bruhat order as a partial order -/

variable (cs) in
/-- A type synonym for `W` equipped with the Bruhat order of the Coxeter system `cs`. -/
def BruhatOrder (_cs : CoxeterSystem M W) : Type _ := W

namespace BruhatOrder

variable (cs) in
/-- The identity map from `W` to `cs.BruhatOrder`. -/
def toBruhatOrder : W ≃ cs.BruhatOrder := Equiv.refl W

variable (cs) in
/-- The identity map from `cs.BruhatOrder` to `W`. -/
def ofBruhatOrder : cs.BruhatOrder ≃ W := Equiv.refl W

instance : PartialOrder cs.BruhatOrder where
  le u w := cs.BruhatLE (ofBruhatOrder cs u) (ofBruhatOrder cs w)
  le_refl w := cs.bruhatLE_refl _
  le_trans _ _ _ := BruhatLE.trans
  le_antisymm _ _ := BruhatLE.antisymm

/-- The order on `cs.BruhatOrder` is the Bruhat order. -/
theorem toBruhatOrder_le_toBruhatOrder_iff {u w : W} :
    toBruhatOrder cs u ≤ toBruhatOrder cs w ↔ cs.BruhatLE u w := Iff.rfl

/-- The order on `cs.BruhatOrder` is the Bruhat order. -/
theorem le_iff {u w : cs.BruhatOrder} :
    u ≤ w ↔ cs.BruhatLE (ofBruhatOrder cs u) (ofBruhatOrder cs w) := Iff.rfl

instance : OrderBot cs.BruhatOrder where
  bot := toBruhatOrder cs 1
  bot_le w := cs.one_bruhatLE (ofBruhatOrder cs w)

/-- The strict Bruhat order. -/
theorem lt_iff {u w : cs.BruhatOrder} :
    u < w ↔ cs.BruhatLE (ofBruhatOrder cs u) (ofBruhatOrder cs w) ∧ u ≠ w :=
  lt_iff_le_and_ne

/-- The covering relation of the Bruhat order: `u ⋖ w` if and only if `u → w` is a Bruhat step
with `ℓ(w) = ℓ(u) + 1`. -/
theorem covBy_iff {u w : cs.BruhatOrder} :
    u ⋖ w ↔ cs.BruhatStep (ofBruhatOrder cs u) (ofBruhatOrder cs w) ∧
      ℓ (ofBruhatOrder cs w) = ℓ (ofBruhatOrder cs u) + 1 := by
  constructor
  · intro h
    obtain ⟨v, huv, hvw, hl⟩ := h.le.exists_bruhatStep_length_eq h.ne
    have hvw' : toBruhatOrder cs v < w :=
      lt_of_le_of_ne hvw.bruhatLE (fun e ↦ by rw [← e] at hl; change ℓ v = ℓ v + 1 at hl; omega)
    have : u = toBruhatOrder cs v := by
      by_contra hne
      exact h.2 (lt_of_le_of_ne huv hne) hvw'
    subst this
    exact ⟨hvw, hl⟩
  · rintro ⟨hs, hl⟩
    refine ⟨lt_of_le_of_ne hs.bruhatLE (fun e ↦ by rw [e] at hl; simp at hl), fun v h₁ h₂ ↦ ?_⟩
    have := h₁.le.length_le
    have := h₂.le.length_le
    have h₁' := h₁.le.eq_or_length_lt.resolve_left h₁.ne
    have h₂' := h₂.le.eq_or_length_lt.resolve_left h₂.ne
    omega

/-- Lower intervals of the Bruhat order are finite. -/
theorem finite_Iic (w : cs.BruhatOrder) : (Set.Iic w).Finite :=
  cs.finite_setOf_bruhatLE (ofBruhatOrder cs w)

/-- Intervals of the Bruhat order are finite. -/
theorem finite_Icc (u w : cs.BruhatOrder) : (Set.Icc u w).Finite :=
  (finite_Iic w).subset Set.Icc_subset_Iic_self

end BruhatOrder

end CoxeterSystem
