/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.GroupTheory.Coxeter.Deletion

/-!
# Standard parabolic subgroups and minimal coset representatives

Let `cs : CoxeterSystem M W` be a Coxeter system and `J` a set of indices. The standard parabolic
subgroup `W_J` is the subgroup generated by the `sᵢ`, `i ∈ J`. We show that its elements have
reduced words (for `W`) with letters in `J`, and prove the parabolic decomposition: every `w`
is uniquely `w = w^J w_J` with `w_J ∈ W_J` and `w^J ∈ W^J`, the set of elements without right
descents in `J`, and `ℓ(w) = ℓ(w^J) + ℓ(w_J)`.

That `W_J` is itself a Coxeter group with Coxeter matrix `M` restricted to `J` is proved in
`LieLean.GroupTheory.Coxeter.Matsumoto` (it uses Matsumoto's theorem).

## Main definitions

* `CoxeterSystem.parabolicSubgroup`: the standard parabolic subgroup `W_J`.
* `CoxeterSystem.minCosetReps`: the set `W^J`.
* `CoxeterSystem.minCosetRep`, `CoxeterSystem.parabolicComponent`: `w^J` and `w_J`.

## Main results

* `CoxeterSystem.exists_isReduced_of_mem_parabolicSubgroup`: elements of `W_J` have reduced
  words with letters in `J`.
* `CoxeterSystem.length_mul_of_mem_minCosetReps`: `ℓ(u v) = ℓ(u) + ℓ(v)` for `u ∈ W^J`,
  `v ∈ W_J`.
* `CoxeterSystem.exists_mem_minCosetReps_mul_eq`, `CoxeterSystem.eq_and_eq_of_mul_eq_mul`: the
  parabolic decomposition and its uniqueness; `CoxeterSystem.length_eq_length_minCosetRep_add`.
* `CoxeterSystem.exists_mul_eq_of_forall_not_isLeftDescent`,
  `CoxeterSystem.length_mul_of_forall_not_isLeftDescent`: the left-handed versions.

## Implementation notes

We follow [BB] §2.4: `w^J` is first taken to be an element of minimal length in `w W_J`, and
length additivity is proved for it with the strong exchange condition (our reconstruction of the
argument); uniqueness then shows that it is the unique element of `W^J` in the coset.

## References

* [BB] A. Björner, F. Brenti, *Combinatorics of Coxeter groups*, GTM 231, Springer 2005, §2.4.
* [HumC] J. E. Humphreys, *Reflection groups and Coxeter groups*, CUP 1990, §1.10, §5.5.
-/

open List

namespace CoxeterSystem

variable {B W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

local prefix:100 "s " => cs.simple
local prefix:100 "π " => cs.wordProd
local prefix:100 "ℓ " => cs.length

/-- The standard parabolic subgroup `W_J` of `W` generated by the simple reflections `sᵢ`,
`i ∈ J` ([HumC] §1.10, [BB] §2.4). -/
def parabolicSubgroup (J : Set B) : Subgroup W := Subgroup.closure (cs.simple '' J)

variable {cs} {J : Set B}

/-- `sᵢ ∈ W_J` for `i ∈ J`. -/
theorem simple_mem_parabolicSubgroup {i : B} (hi : i ∈ J) : s i ∈ cs.parabolicSubgroup J :=
  Subgroup.subset_closure ⟨i, hi, rfl⟩

/-- The product of a word with letters in `J` lies in `W_J`. -/
theorem wordProd_mem_parabolicSubgroup {ω : List B} (hω : ∀ i ∈ ω, i ∈ J) :
    π ω ∈ cs.parabolicSubgroup J := by
  induction ω with
  | nil => exact Subgroup.one_mem _
  | cons i ω ih =>
    rw [wordProd_cons]
    exact Subgroup.mul_mem _ (simple_mem_parabolicSubgroup (hω i mem_cons_self))
      (ih fun j hj ↦ hω j (mem_cons_of_mem _ hj))

/-- An element lies in `W_J` if and only if it is the product of a word with letters in `J`. -/
theorem mem_parabolicSubgroup_iff {w : W} :
    w ∈ cs.parabolicSubgroup J ↔ ∃ ω : List B, (∀ i ∈ ω, i ∈ J) ∧ π ω = w := by
  refine ⟨fun h ↦ ?_, fun ⟨ω, hω, he⟩ ↦ he ▸ wordProd_mem_parabolicSubgroup hω⟩
  induction h using Subgroup.closure_induction with
  | mem x hx =>
    obtain ⟨i, hi, rfl⟩ := hx
    exact ⟨[i], by simpa using hi, wordProd_singleton _ _⟩
  | one => exact ⟨[], by simp, wordProd_nil _⟩
  | mul x y _ _ hx hy =>
    obtain ⟨ω, hω, rfl⟩ := hx
    obtain ⟨ω', hω', rfl⟩ := hy
    exact ⟨ω ++ ω', by simpa using fun i hi ↦ (mem_append.mp hi).elim (hω i) (hω' i),
      wordProd_append _ _ _⟩
  | inv x _ hx =>
    obtain ⟨ω, hω, rfl⟩ := hx
    exact ⟨ω.reverse, by simpa using hω, wordProd_reverse _ _⟩

/-- Every element of `W_J` has a reduced word with letters in `J`; in particular, the length
function of `W_J` with respect to `{sᵢ : i ∈ J}` is the restriction of that of `W`
([HumC] §5.5 Thm. (check), [BB] §2.4 (check)). -/
theorem exists_isReduced_of_mem_parabolicSubgroup {w : W} (hw : w ∈ cs.parabolicSubgroup J) :
    ∃ ω : List B, cs.IsReduced ω ∧ (∀ i ∈ ω, i ∈ J) ∧ π ω = w := by
  obtain ⟨ω, hω, rfl⟩ := mem_parabolicSubgroup_iff.mp hw
  obtain ⟨ω', hsub, hred, he⟩ := cs.exists_sublist_isReduced ω
  exact ⟨ω', hred, fun i hi ↦ hω i (hsub.subset hi), he⟩

/-- A nontrivial element of `W_J` has a right descent in `J`. -/
theorem exists_isRightDescent_of_mem_parabolicSubgroup {w : W}
    (hw : w ∈ cs.parabolicSubgroup J) (hw1 : w ≠ 1) : ∃ i ∈ J, cs.IsRightDescent w i := by
  obtain ⟨ω, hred, hJ, rfl⟩ := exists_isReduced_of_mem_parabolicSubgroup hw
  obtain ⟨ω', i, rfl⟩ : ∃ ω' i, ω = ω' ++ [i] := by
    rcases ω.eq_nil_or_concat with rfl | ⟨ω', i, rfl⟩
    · simp at hw1
    · exact ⟨ω', i, by simp⟩
  refine ⟨i, hJ i (by simp), ?_⟩
  have h := hred.eq
  rw [wordProd_append, wordProd_singleton] at h
  rw [IsRightDescent, wordProd_append, wordProd_singleton, simple_mul_simple_cancel_right, h]
  have := cs.length_wordProd_le ω'
  simp only [length_append, length_singleton]
  omega

/-! ### Minimal coset representatives -/

variable (cs J) in
/-- The set `W^J` of minimal left coset representatives: elements `w` with no right descent in
`J` ([BB] §2.4). -/
def minCosetReps : Set W := {w | ∀ i ∈ J, ¬cs.IsRightDescent w i}

variable (cs J) in
private theorem exists_min_length (w : W) :
    ∃ u, w⁻¹ * u ∈ cs.parabolicSubgroup J ∧
      ∀ u', w⁻¹ * u' ∈ cs.parabolicSubgroup J → ℓ u ≤ ℓ u' := by
  classical
  have hex : ∃ n, ∃ u, w⁻¹ * u ∈ cs.parabolicSubgroup J ∧ ℓ u = n :=
    ⟨_, w, by simp, rfl⟩
  obtain ⟨u, hu, hl⟩ := Nat.find_spec hex
  exact ⟨u, hu, fun u' hu' ↦ hl ▸ Nat.find_min' hex ⟨u', hu', rfl⟩⟩

/-- If `u` has minimal length in `u W_J`, then `ℓ(u v) = ℓ(u) + ℓ(v)` for `v ∈ W_J`. -/
private theorem length_mul_of_min {u : W}
    (hu : ∀ x ∈ cs.parabolicSubgroup J, ℓ u ≤ ℓ (u * x)) {v : W}
    (hv : v ∈ cs.parabolicSubgroup J) : ℓ (u * v) = ℓ u + ℓ v := by
  obtain ⟨η, hη, hJ, rfl⟩ := exists_isReduced_of_mem_parabolicSubgroup hv
  induction η using List.reverseRecOn with
  | nil => simp
  | append_singleton η j ih =>
    have hη' : cs.IsReduced η := by simpa using hη.take η.length
    have hJ' : ∀ i ∈ η, i ∈ J := fun i hi ↦ hJ i (by simp [hi])
    have ih := ih hη' hJ' (wordProd_mem_parabolicSubgroup hJ')
    rw [hη.eq, wordProd_append, wordProd_singleton, ← mul_assoc]
    rcases cs.length_mul_simple (u * π η) j with h | h
    · rw [h, ih, hη'.eq]; simp; omega
    exfalso
    obtain ⟨ν, hν, rfl⟩ := cs.exists_isReduced u
    have hred : cs.IsReduced (ν ++ η) := by
      unfold IsReduced; rw [wordProd_append, ih, hν.eq, hη'.eq, length_append]
    have hdesc : cs.IsRightDescent (π (ν ++ η)) j := by
      rw [IsRightDescent, wordProd_append]; omega
    obtain ⟨p, hp, hpe⟩ := hdesc.exists_wordProd_mul_eq
    rw [length_append] at hp
    by_cases hpν : p < ν.length
    · -- then `u t` is shorter than `u` for some `t ∈ W_J`
      rw [eraseIdx_append_of_lt_length hpν, wordProd_append, wordProd_append] at hpe
      have hmem : π η * s j * (π η)⁻¹ ∈ cs.parabolicSubgroup J :=
        Subgroup.mul_mem _ (Subgroup.mul_mem _ (wordProd_mem_parabolicSubgroup hJ')
          (simple_mem_parabolicSubgroup (hJ j (by simp)))) (Subgroup.inv_mem _
          (wordProd_mem_parabolicSubgroup hJ'))
      have h1 := hu _ hmem
      have h2 : π ν * (π η * s j * (π η)⁻¹) = π (ν.eraseIdx p) := by
        rw [← mul_assoc, ← mul_assoc, hpe]; group
      rw [h2, hν.eq] at h1
      have := cs.length_wordProd_le (ν.eraseIdx p)
      have := List.length_eraseIdx_add_one hpν
      omega
    · -- then `π η sⱼ` is shorter than `η` allows
      push Not at hpν
      rw [eraseIdx_append_of_length_le hpν, wordProd_append, wordProd_append, mul_assoc] at hpe
      have h1 := mul_left_cancel hpe
      have := cs.length_wordProd_le (η.eraseIdx (p - ν.length))
      have := List.length_eraseIdx_add_one (show p - ν.length < η.length by omega)
      have h3 : ℓ (π η * s j) = η.length + 1 := by
        rw [← wordProd_singleton, ← wordProd_append, hη.eq, length_append, length_singleton]
      rw [h1] at h3
      omega

/-- If `u` has minimal length in `u W_J`, then `u ∈ W^J`, and `u` is the only element of `W^J` in
`u W_J`. -/
private theorem eq_of_min {u₀ u : W}
    (hu₀ : ∀ x ∈ cs.parabolicSubgroup J, ℓ u₀ ≤ ℓ (u₀ * x)) (hu : u ∈ cs.minCosetReps J)
    (hy : u₀⁻¹ * u ∈ cs.parabolicSubgroup J) : u = u₀ := by
  by_contra hne
  have hy1 : u₀⁻¹ * u ≠ 1 := fun h ↦ hne (inv_mul_eq_one.mp h).symm
  obtain ⟨j, hj, hdesc⟩ := exists_isRightDescent_of_mem_parabolicSubgroup hy hy1
  have h1 := length_mul_of_min hu₀ hy
  have h2 := length_mul_of_min hu₀
    (Subgroup.mul_mem _ hy (simple_mem_parabolicSubgroup hj))
  rw [mul_inv_cancel_left] at h1
  rw [← mul_assoc, mul_inv_cancel_left] at h2
  apply hu j hj
  rw [IsRightDescent, h2, h1]
  exact Nat.add_lt_add_left hdesc _

/-- **Length additivity** ([BB] Prop. 2.4.4 (check), [HumC] §1.10 Prop. (c) (check)): if
`u ∈ W^J` and `v ∈ W_J`, then `ℓ(u v) = ℓ(u) + ℓ(v)`. -/
theorem length_mul_of_mem_minCosetReps {u v : W} (hu : u ∈ cs.minCosetReps J)
    (hv : v ∈ cs.parabolicSubgroup J) : ℓ (u * v) = ℓ u + ℓ v := by
  obtain ⟨u₀, hu₀, hmin⟩ := exists_min_length cs J u
  have hu₀' : ∀ x ∈ cs.parabolicSubgroup J, ℓ u₀ ≤ ℓ (u₀ * x) := fun x hx ↦
    hmin _ (by rw [← mul_assoc]; exact Subgroup.mul_mem _ hu₀ hx)
  have := eq_of_min hu₀' hu (by simpa using Subgroup.inv_mem _ hu₀)
  subst this
  exact length_mul_of_min hu₀' hv

/-- The elements of `W^J` in a coset `u W_J` agree. -/
theorem eq_of_mem_minCosetReps {u u' : W} (hu : u ∈ cs.minCosetReps J)
    (hu' : u' ∈ cs.minCosetReps J) (h : u⁻¹ * u' ∈ cs.parabolicSubgroup J) : u = u' := by
  have hu₀ : ∀ x ∈ cs.parabolicSubgroup J, ℓ u ≤ ℓ (u * x) := fun x hx ↦ by
    rw [length_mul_of_mem_minCosetReps hu hx]; omega
  exact (eq_of_min hu₀ hu' h).symm

/-- **The parabolic decomposition** ([BB] Prop. 2.4.4, [HumC] §1.10 (check)): every `w ∈ W` can be
written as `w = u v` with `u ∈ W^J` and `v ∈ W_J`. -/
theorem exists_mem_minCosetReps_mul_eq (J : Set B) (w : W) :
    ∃ u ∈ cs.minCosetReps J, ∃ v ∈ cs.parabolicSubgroup J, u * v = w := by
  obtain ⟨u, hu, hmin⟩ := exists_min_length cs J w
  have hu' : ∀ x ∈ cs.parabolicSubgroup J, ℓ u ≤ ℓ (u * x) := fun x hx ↦
    hmin _ (by rw [← mul_assoc]; exact Subgroup.mul_mem _ hu hx)
  refine ⟨u, fun j hj hdesc ↦ ?_, u⁻¹ * w, by simpa using Subgroup.inv_mem _ hu, by group⟩
  have := length_mul_of_min hu' (simple_mem_parabolicSubgroup hj)
  rw [IsRightDescent, this, length_simple] at hdesc
  omega

/-- The parabolic decomposition is unique. -/
theorem eq_and_eq_of_mul_eq_mul {u u' v v' : W} (hu : u ∈ cs.minCosetReps J)
    (hu' : u' ∈ cs.minCosetReps J) (hv : v ∈ cs.parabolicSubgroup J)
    (hv' : v' ∈ cs.parabolicSubgroup J) (h : u * v = u' * v') : u = u' ∧ v = v' := by
  have huu : u = u' := by
    refine eq_of_mem_minCosetReps hu hu' ?_
    have : u⁻¹ * u' = v * v'⁻¹ := by
      rw [inv_mul_eq_iff_eq_mul, ← mul_assoc, h, mul_inv_cancel_right]
    rw [this]
    exact Subgroup.mul_mem _ hv (Subgroup.inv_mem _ hv')
  subst huu
  exact ⟨rfl, mul_left_cancel h⟩

variable (cs J) in
/-- The minimal coset representative `w^J ∈ W^J` of `w W_J`. -/
noncomputable def minCosetRep (w : W) : W := (cs.exists_mem_minCosetReps_mul_eq J w).choose

variable (cs J) in
/-- The parabolic component `w_J = (w^J)⁻¹ w ∈ W_J` of `w`, so that `w = w^J w_J`. -/
noncomputable def parabolicComponent (w : W) : W := (cs.minCosetRep J w)⁻¹ * w

/-- `w^J ∈ W^J`. -/
theorem minCosetRep_mem (w : W) : cs.minCosetRep J w ∈ cs.minCosetReps J :=
  (cs.exists_mem_minCosetReps_mul_eq J w).choose_spec.1

/-- `w_J ∈ W_J`. -/
theorem parabolicComponent_mem (w : W) :
    cs.parabolicComponent J w ∈ cs.parabolicSubgroup J := by
  obtain ⟨v, hv, he⟩ := (cs.exists_mem_minCosetReps_mul_eq J w).choose_spec.2
  have : cs.parabolicComponent J w = v := by
    rw [parabolicComponent, inv_mul_eq_iff_eq_mul]
    exact he.symm
  rw [this]
  exact hv

/-- `w = w^J w_J`. -/
theorem minCosetRep_mul_parabolicComponent (w : W) :
    cs.minCosetRep J w * cs.parabolicComponent J w = w := by
  rw [parabolicComponent, mul_inv_cancel_left]

/-- `ℓ(w) = ℓ(w^J) + ℓ(w_J)` ([BB] Prop. 2.4.4 (check)). -/
theorem length_eq_length_minCosetRep_add (w : W) :
    ℓ w = ℓ (cs.minCosetRep J w) + ℓ (cs.parabolicComponent J w) := by
  conv_lhs => rw [← minCosetRep_mul_parabolicComponent (cs := cs) (J := J) w]
  exact length_mul_of_mem_minCosetReps (minCosetRep_mem w) (parabolicComponent_mem w)

/-- Characterization of `w^J` and `w_J`. -/
theorem minCosetRep_eq_iff {w u : W} :
    cs.minCosetRep J w = u ↔ u ∈ cs.minCosetReps J ∧ u⁻¹ * w ∈ cs.parabolicSubgroup J := by
  constructor
  · rintro rfl
    exact ⟨minCosetRep_mem w, parabolicComponent_mem w⟩
  · rintro ⟨hu, hw⟩
    refine (eq_and_eq_of_mul_eq_mul (minCosetRep_mem w) hu (parabolicComponent_mem w) hw ?_).1
    rw [minCosetRep_mul_parabolicComponent, mul_inv_cancel_left]

/-- Left-handed length additivity: if `u` has no left descent in `J` and `v ∈ W_J`, then
`ℓ(v u) = ℓ(v) + ℓ(u)`. -/
theorem length_mul_of_forall_not_isLeftDescent {u v : W}
    (hu : ∀ i ∈ J, ¬cs.IsLeftDescent u i) (hv : v ∈ cs.parabolicSubgroup J) :
    ℓ (v * u) = ℓ v + ℓ u := by
  have hu' : u⁻¹ ∈ cs.minCosetReps J := fun i hi h ↦ hu i hi (cs.isRightDescent_inv_iff.mp h)
  have := length_mul_of_mem_minCosetReps hu' (Subgroup.inv_mem _ hv)
  rwa [← mul_inv_rev, length_inv, length_inv, length_inv, add_comm] at this

/-- Left-handed parabolic decomposition: every `w ∈ W` can be written as `w = v u` with
`v ∈ W_J` and `u` without left descents in `J`. -/
theorem exists_mul_eq_of_forall_not_isLeftDescent (J : Set B) (w : W) :
    ∃ v ∈ cs.parabolicSubgroup J, ∃ u, (∀ i ∈ J, ¬cs.IsLeftDescent u i) ∧ v * u = w := by
  obtain ⟨u, hu, v, hv, he⟩ := cs.exists_mem_minCosetReps_mul_eq J w⁻¹
  refine ⟨v⁻¹, Subgroup.inv_mem _ hv, u⁻¹, fun i hi h ↦ hu i hi ?_, ?_⟩
  · rwa [← isRightDescent_inv_iff, inv_inv] at h
  · rw [← mul_inv_rev, he, inv_inv]

end CoxeterSystem
