/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.CasimirIrreducible
import LieLean.Algebra.Lie.KacMoody.SerreAssociative.NegativePart

/-!
# `L(Λ)` as a cyclic module over the associative Serre algebra

Let `A` be a symmetrizable generalized Cartan matrix, `K` a field of characteristic zero,
`(𝔥, Π, Π^∨)` a realization of `A` with `𝔥` finite-dimensional, and `Λ ∈ 𝔥*` dominant integral,
`nᵢ = ⟨Λ, αᵢ^∨⟩ ∈ ℕ`. Let `𝒮 = SerreAssocAlgebra K A` be the associative algebra generated by the
`θᵢ` subject to the associative Serre relations.

**Theorem** (`Matrix.Realization.KacMoodyAlgebra.serreAssocQuotientEquiv`). There is a linear
isomorphism `𝒮 / ∑ᵢ 𝒮 θᵢ^{nᵢ+1} ≃ L(Λ)` sending `1` to the highest-weight vector `v_Λ` and
intertwining left multiplication by `θᵢ` with the action of `fᵢ`.

## Proof

It is the composite of the following isomorphisms.
1. `𝒮 ≃ U(𝔫₋)`, `θᵢ ↦ fᵢ` (`Matrix.Realization.KacMoodyAlgebra.serreAssocAlgebraEquiv`; this uses
   the Gabber–Kac theorem, [Kac] Thm. 9.11), which maps the left ideal `∑ᵢ 𝒮 θᵢ^{nᵢ+1}` onto
   `∑ᵢ U(𝔫₋) fᵢ^{nᵢ+1}`.
2. `U(𝔫₋) ≃ M(Λ)`, `u ↦ u v_Λ` (PBW, `Matrix.Realization.KacMoodyAlgebra.VermaModule.equivEnvNNeg`),
   which maps `∑ᵢ U(𝔫₋) fᵢ^{nᵢ+1}` onto the submodule of `M(Λ)` generated by the vectors
   `fᵢ^{nᵢ+1} v_Λ` (`Matrix.Realization.KacMoodyAlgebra.VermaModule.mem_fPowSubmodule_iff`): as
   `fᵢ^{nᵢ+1} v_Λ` is a highest-weight vector of some weight `μᵢ` ([Kac] §10.1), the
   submodule it generates is the image of `M(μᵢ) = U(𝔫₋) v_{μᵢ}`, i.e. `U(𝔫₋) fᵢ^{nᵢ+1} v_Λ`.
3. `M(Λ) / ∑ᵢ U(𝔤) fᵢ^{nᵢ+1} v_Λ ≃ L(Λ)` ([Kac] Cor. 10.4,
   `Matrix.Realization.KacMoodyAlgebra.FPowQuotient.equivIrreducibleModule`).

This combination is standard; the argument for step 2 is reconstructed and written out here.

## Main definitions

* `Matrix.SerreAssocAlgebra.thetaPowLeftIdeal K A n`: the left ideal `∑ᵢ 𝒮 θᵢ^{nᵢ+1}`.
* `Matrix.Realization.KacMoodyAlgebra.VermaModule.fPowLeftIdeal P n`: the left ideal
  `∑ᵢ U(𝔫₋) fᵢ^{nᵢ+1}`.
* `Matrix.Realization.KacMoodyAlgebra.serreAssocQuotientEquiv`: the isomorphism
  `𝒮 / ∑ᵢ 𝒮 θᵢ^{nᵢ+1} ≃ₗ[K] L(Λ)`.

## Main results

* `Matrix.Realization.KacMoodyAlgebra.VermaModule.mem_fPowSubmodule_iff`: under
  `U(𝔫₋) ≃ M(Λ)`, the submodule generated by the `fᵢ^{nᵢ+1} v_Λ` is `∑ᵢ U(𝔫₋) fᵢ^{nᵢ+1}`.
* `Matrix.Realization.KacMoodyAlgebra.serreAssocQuotientEquiv_mk_one`,
  `Matrix.Realization.KacMoodyAlgebra.serreAssocQuotientEquiv_θ_smul`: `1 ↦ v_Λ`, and
  `θᵢ · q ↦ fᵢ · (image of q)`.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §9.2, §9.11, §10.1,
  §10.4.
-/

open Module LieModule

noncomputable section

namespace Matrix.SerreAssocAlgebra

variable {ι : Type*} (K : Type*) [CommRing K] (A : Matrix ι ι ℤ)

/-- The left ideal `∑ᵢ 𝒮 θᵢ^{nᵢ+1}` of the associative Serre algebra `𝒮`. -/
def thetaPowLeftIdeal (n : ι → ℕ) :
    Submodule (SerreAssocAlgebra K A) (SerreAssocAlgebra K A) :=
  Submodule.span _ (Set.range fun i ↦ θ K A i ^ (n i + 1))

end Matrix.SerreAssocAlgebra

private lemma RingEquiv.apply_mem_span_image_of_mem {S U : Type*} [Ring S] [Ring U]
    (Φ : S ≃+* U) (T : Set S) {a : S} (ha : a ∈ Submodule.span S T) :
    Φ a ∈ Submodule.span U (Φ '' T) := by
  induction ha using Submodule.span_induction with
  | mem x hx => exact Submodule.subset_span ⟨x, hx, rfl⟩
  | zero => simp
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | smul c x _ hx => rw [smul_eq_mul, map_mul]; exact Submodule.smul_mem _ (Φ c) hx

/-- The preimage of the left ideal generated by the image of a set under a ring isomorphism is
the left ideal generated by the set. -/
private lemma RingEquiv.apply_mem_span_image_iff {S U : Type*} [Ring S] [Ring U] (Φ : S ≃+* U)
    (T : Set S) {a : S} : Φ a ∈ Submodule.span U (Φ '' T) ↔ a ∈ Submodule.span S T := by
  refine ⟨fun h ↦ ?_, RingEquiv.apply_mem_span_image_of_mem Φ T⟩
  have := RingEquiv.apply_mem_span_image_of_mem Φ.symm _ h
  have hT : Φ.symm '' (Φ '' T) = T := by
    rw [Set.image_image]
    simp
  rwa [RingEquiv.symm_apply_apply, hT] at this

namespace Matrix.Realization.KacMoodyAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H)

local notation "𝓤" => UniversalEnvelopingAlgebra K (KacMoodyAlgebra P)
local notation "𝓤₋" => UniversalEnvelopingAlgebra K (nNeg P)
local notation "ιᵤ" => UniversalEnvelopingAlgebra.ι K
local notation "mapN" => UniversalEnvelopingAlgebra.map (LieSubalgebra.incl (nNeg P))

namespace VermaModule

/-- The left ideal `∑ᵢ U(𝔫₋) fᵢ^{nᵢ+1}` of `U(𝔫₋)`. -/
def fPowLeftIdeal (n : ι → ℕ) : Submodule 𝓤₋ 𝓤₋ :=
  Submodule.span _ (Set.range fun i ↦ ιᵤ (nNegF P i) ^ (n i + 1))

variable (Λ : Dual K H)

lemma toEnd_pow_apply_eq_smul (x : P.KacMoodyAlgebra) (k : ℕ) (m : VermaModule P Λ) :
    (toEnd K P.KacMoodyAlgebra (VermaModule P Λ) x ^ k) m = ιᵤ x ^ k • m := by
  induction k with
  | zero => simp
  | succ k ih =>
    rw [pow_succ', Module.End.mul_apply, ih, toEnd_apply_apply, lie_eq_smul, pow_succ', mul_smul]

/-- On a Verma module, the action of `U(𝔤)` through `rep` is the module structure. -/
lemma rep_apply_eq_smul (u : 𝓤) (m : VermaModule P Λ) : rep P (VermaModule P Λ) u m = u • m :=
  (map_smul_eq_rep P Λ LieModuleHom.id u m).symm

variable [CharZero K]

lemma equivEnvNNeg_fPow (i : ι) (k : ℕ) :
    equivEnvNNeg P Λ (ιᵤ (nNegF P i) ^ (k + 1)) = fPowHwv P Λ i k := by
  rw [equivEnvNNeg_apply, map_pow, UniversalEnvelopingAlgebra.map_ι, fPowHwv,
    toEnd_pow_apply_eq_smul]
  rfl

variable {Λ} {n : ι → ℕ}

lemma equivEnvNNeg_mem_fPowSubmodule {u : 𝓤₋} (hu : u ∈ fPowLeftIdeal P n) :
    equivEnvNNeg P Λ u ∈ fPowSubmodule P Λ n := by
  induction hu using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨i, rfl⟩ := hx
    rw [equivEnvNNeg_fPow]
    exact LieSubmodule.subset_lieSpan ⟨i, rfl⟩
  | zero => simp
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | smul c x _ hx => rw [smul_eq_mul, equivEnvNNeg_mul]; exact smul_mem P Λ _ _ hx

variable (hA : A.IsGeneralizedCartan) (hn : ∀ i, Λ (P.coroot i) = n i)
include hA hn

/-- Under `U(𝔫₋) ≃ M(Λ)`, `u ↦ u v_Λ`, the submodule of `M(Λ)` generated by the singular vectors
`fᵢ^{nᵢ+1} v_Λ` (`nᵢ = ⟨Λ, αᵢ^∨⟩`) corresponds to the left ideal `∑ᵢ U(𝔫₋) fᵢ^{nᵢ+1}`. -/
theorem mem_fPowSubmodule_iff {u : 𝓤₋} :
    equivEnvNNeg P Λ u ∈ fPowSubmodule P Λ n ↔ u ∈ fPowLeftIdeal P n := by
  refine ⟨fun hu ↦ ?_, equivEnvNNeg_mem_fPowSubmodule P⟩
  -- the morphisms `M(μᵢ) → M(Λ)`, `v_{μᵢ} ↦ fᵢ^{nᵢ+1} v_Λ`
  let φ : ∀ i, VermaModule P (Λ - (n i + 1) • P.root i) →ₗ⁅K,P.KacMoodyAlgebra⁆
      VermaModule P Λ := fun i ↦ lift P (fPowHwv P Λ i (n i))
    (fun _ hx ↦ lie_eq_zero_of_mem_nPos (lie_e_fPowHwv P Λ hA (hn i)) hx)
    (fun a ↦ fPowHwv_mem_weightSpace P Λ i (n i) a)
  set N : Submodule K (VermaModule P Λ) :=
    ((fPowLeftIdeal P n).restrictScalars K).map (equivEnvNNeg P Λ : 𝓤₋ →ₗ[K] VermaModule P Λ)
  have hle : fPowSubmodule P Λ n ≤ ⨆ i, (φ i).range := by
    rw [fPowSubmodule, LieSubmodule.lieSpan_le]
    rintro _ ⟨i, rfl⟩
    exact LieSubmodule.mem_iSup_of_mem i ((LieModuleHom.mem_range _ _).mpr ⟨_, lift_hwv _ _ _ _⟩)
  have hN : (⨆ i, (φ i).range).toSubmodule ≤ N := by
    rw [LieSubmodule.iSup_toSubmodule, iSup_le_iff]
    rintro i _ ⟨x, rfl⟩
    obtain ⟨v, rfl⟩ := (equivEnvNNeg P (Λ - (n i + 1) • P.root i)).surjective x
    refine ⟨v * ιᵤ (nNegF P i) ^ (n i + 1),
      Submodule.smul_mem _ v (Submodule.subset_span ⟨i, rfl⟩), ?_⟩
    change equivEnvNNeg P Λ _ = φ i _
    rw [equivEnvNNeg_mul, equivEnvNNeg_fPow, equivEnvNNeg_apply, map_smul_eq_rep, hwv, ← hwv,
      lift_hwv, rep_apply_eq_smul]
  obtain ⟨v, hv, hvu⟩ := hN (hle hu)
  rwa [(equivEnvNNeg P Λ).injective hvu] at hv

end VermaModule

/-! ### The presentation of `L(Λ)` -/

variable [CharZero K] [FiniteDimensional K H] (hA : A.IsGeneralizedCartan)
  (hS : A.IsSymmetrizable) {Λ : Dual K H} {n : ι → ℕ} (hn : ∀ i, Λ (P.coroot i) = n i)

omit [FiniteDimensional K H] in
include hA hS in
lemma serreAssocAlgebraEquiv_mem_fPowLeftIdeal_iff {a : SerreAssocAlgebra K A} :
    serreAssocAlgebraEquiv P hA hS a ∈ VermaModule.fPowLeftIdeal P n ↔
      a ∈ SerreAssocAlgebra.thetaPowLeftIdeal K A n := by
  have himage : (Set.range fun i ↦ ιᵤ (nNegF P i) ^ (n i + 1)) =
      (serreAssocAlgebraEquiv P hA hS : SerreAssocAlgebra K A ≃+* 𝓤₋) ''
        Set.range fun i ↦ SerreAssocAlgebra.θ K A i ^ (n i + 1) := by
    ext x
    simp only [Set.mem_range, Set.mem_image, exists_exists_eq_and]
    refine exists_congr fun i ↦ ?_
    rw [map_pow, AlgEquiv.coe_ringEquiv, serreAssocAlgebraEquiv_θ]
    rfl
  rw [VermaModule.fPowLeftIdeal, himage, SerreAssocAlgebra.thetaPowLeftIdeal,
    ← RingEquiv.apply_mem_span_image_iff
      (serreAssocAlgebraEquiv P hA hS : SerreAssocAlgebra K A ≃+* 𝓤₋)]
  rfl

/-- The linear map `𝒮 → L(Λ)`, `a ↦ Φ(a) v_Λ`, where `Φ : 𝒮 ≃ U(𝔫₋)` sends `θᵢ` to `fᵢ`. -/
def serreAssocToIrreducibleModule : SerreAssocAlgebra K A →ₗ[K] IrreducibleModule P Λ :=
  (FPowQuotient.equivIrreducibleModule hS hA hn).toLinearEquiv.toLinearMap ∘ₗ
    ((LieSubmodule.Quotient.mk' (VermaModule.fPowSubmodule P Λ n) :
      VermaModule P Λ →ₗ⁅K,P.KacMoodyAlgebra⁆ FPowQuotient P Λ n) :
        VermaModule P Λ →ₗ[K] FPowQuotient P Λ n) ∘ₗ
    (VermaModule.equivEnvNNeg P Λ).toLinearMap ∘ₗ (serreAssocAlgebraEquiv P hA hS).toLinearMap

lemma serreAssocToIrreducibleModule_apply (a : SerreAssocAlgebra K A) :
    serreAssocToIrreducibleModule P hA hS hn a =
      FPowQuotient.equivIrreducibleModule hS hA hn (LieSubmodule.Quotient.mk'
        (VermaModule.fPowSubmodule P Λ n)
          (VermaModule.equivEnvNNeg P Λ (serreAssocAlgebraEquiv P hA hS a))) :=
  rfl

lemma serreAssocToIrreducibleModule_surjective :
    Function.Surjective (serreAssocToIrreducibleModule P hA hS hn) := by
  intro y
  obtain ⟨x, rfl⟩ := (FPowQuotient.equivIrreducibleModule hS hA hn).surjective y
  obtain ⟨m, rfl⟩ := LieSubmodule.Quotient.surjective_mk' _ x
  obtain ⟨u, rfl⟩ := (VermaModule.equivEnvNNeg P Λ).surjective m
  obtain ⟨a, rfl⟩ := (serreAssocAlgebraEquiv P hA hS).surjective u
  exact ⟨a, rfl⟩

theorem ker_serreAssocToIrreducibleModule :
    LinearMap.ker (serreAssocToIrreducibleModule P hA hS hn) =
      (SerreAssocAlgebra.thetaPowLeftIdeal K A n).restrictScalars K := by
  ext a
  rw [LinearMap.mem_ker, Submodule.restrictScalars_mem,
    ← serreAssocAlgebraEquiv_mem_fPowLeftIdeal_iff P hA hS,
    ← VermaModule.mem_fPowSubmodule_iff P hA hn, ← LieSubmodule.Quotient.mk_eq_zero']
  rw [serreAssocToIrreducibleModule_apply]
  exact (FPowQuotient.equivIrreducibleModule hS hA hn).injective.eq_iff' (map_zero _)

/-- **Presentation of `L(Λ)` over the associative Serre algebra** ([Kac] Cor. 10.4 and
Thm. 9.11): for a symmetrizable generalized Cartan matrix `A` over a field of characteristic
zero and `Λ` dominant integral, `nᵢ = ⟨Λ, αᵢ^∨⟩`, the irreducible highest-weight module `L(Λ)` is
isomorphic to the quotient of the associative Serre algebra `𝒮` by the left ideal
`∑ᵢ 𝒮 θᵢ^{nᵢ+1}`; the isomorphism sends `1` to `v_Λ` and intertwines left multiplication by `θᵢ`
with the action of `fᵢ` (`serreAssocQuotientEquiv_mk_one`, `serreAssocQuotientEquiv_θ_smul`).
[Kac] states both results over `ℂ`. -/
def serreAssocQuotientEquiv :
    (SerreAssocAlgebra K A ⧸ SerreAssocAlgebra.thetaPowLeftIdeal K A n) ≃ₗ[K]
      IrreducibleModule P Λ :=
  (Submodule.Quotient.restrictScalarsEquiv K _).symm.trans <|
    (Submodule.quotEquivOfEq _ _ (ker_serreAssocToIrreducibleModule P hA hS hn)).symm.trans <|
      (serreAssocToIrreducibleModule P hA hS hn).quotKerEquivOfSurjective
        (serreAssocToIrreducibleModule_surjective P hA hS hn)

@[simp] lemma serreAssocQuotientEquiv_mk (a : SerreAssocAlgebra K A) :
    serreAssocQuotientEquiv P hA hS hn (Submodule.Quotient.mk a) =
      serreAssocToIrreducibleModule P hA hS hn a :=
  rfl

/-- The isomorphism `𝒮 / ∑ᵢ 𝒮 θᵢ^{nᵢ+1} ≃ L(Λ)` sends `1` to the highest-weight vector. -/
theorem serreAssocQuotientEquiv_mk_one :
    serreAssocQuotientEquiv P hA hS hn (Submodule.Quotient.mk 1) = IrreducibleModule.hwv P Λ := by
  rw [serreAssocQuotientEquiv_mk, serreAssocToIrreducibleModule_apply, map_one,
    VermaModule.equivEnvNNeg_apply, map_one, one_smul, FPowQuotient.equivIrreducibleModule_apply]
  rfl

/-- The isomorphism `𝒮 / ∑ᵢ 𝒮 θᵢ^{nᵢ+1} ≃ L(Λ)` intertwines left multiplication by `θᵢ` with the
action of `fᵢ`. -/
theorem serreAssocQuotientEquiv_θ_smul (i : ι)
    (q : SerreAssocAlgebra K A ⧸ SerreAssocAlgebra.thetaPowLeftIdeal K A n) :
    serreAssocQuotientEquiv P hA hS hn (SerreAssocAlgebra.θ K A i • q) =
      ⁅f P i, serreAssocQuotientEquiv P hA hS hn q⁆ := by
  induction q using Submodule.Quotient.induction_on with
  | H a =>
    rw [← Submodule.Quotient.mk_smul, serreAssocQuotientEquiv_mk, serreAssocQuotientEquiv_mk,
      serreAssocToIrreducibleModule_apply, serreAssocToIrreducibleModule_apply, smul_eq_mul,
      map_mul, serreAssocAlgebraEquiv_θ, VermaModule.equivEnvNNeg_mul,
      UniversalEnvelopingAlgebra.map_ι, ← VermaModule.lie_eq_smul, LieModuleHom.map_lie]
    exact (FPowQuotient.equivIrreducibleModule hS hA hn).toLieModuleHom.map_lie _ _

end Matrix.Realization.KacMoodyAlgebra
