/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import Mathlib.Algebra.Lie.Free
import LieLean.Algebra.Lie.Quotient
import LieLean.Algebra.Lie.Free
import LieLean.LinearAlgebra.Matrix.Cartan.Generalized

/-!
# The auxiliary Lie algebra `𝔤̃(A)`

Let `A` be a square integer matrix and `(𝔥, Π, Π^∨)` a realization of `A` over a field `K`. The
auxiliary Lie algebra `𝔤̃(A)` ([Kac] §1.2) is the Lie algebra generated by `eᵢ, fᵢ` (`i ∈ ι`) and
`𝔥` subject to the relations (1.2.1):
`[eᵢ, fⱼ] = δᵢⱼ αᵢ^∨`, `[h, h'] = 0`, `[h, eᵢ] = ⟨αᵢ, h⟩ eᵢ`, `[h, fᵢ] = -⟨αᵢ, h⟩ fᵢ`.

## Main definitions

* `Matrix.Realization.AuxLieAlgebra`: the Lie algebra `𝔤̃(A)`.
* `Matrix.Realization.AuxLieAlgebra.e`, `.f`, `.h`: the generators.
* `Matrix.Realization.AuxLieAlgebra.lift`: the universal property.
* `Matrix.Realization.AuxLieAlgebra.chevalleyInvolution`: the Chevalley involution
  `eᵢ ↦ -fᵢ, fᵢ ↦ -eᵢ, h ↦ -h` ([Kac] (1.3.4)).

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §1.2–1.3.
-/

open FreeLieAlgebra

noncomputable section

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H)

variable (ι H) in
/-- The generators of the free Lie algebra of which `𝔤̃(A)` is a quotient. -/
inductive AuxGen
  | e : ι → AuxGen
  | f : ι → AuxGen
  | h : H → AuxGen

variable (K H) in
/-- The generator `eᵢ` of the free Lie algebra. -/
abbrev genE (i : ι) : FreeLieAlgebra K (AuxGen ι H) := FreeLieAlgebra.of K (.e i)

variable (K H) in
/-- The generator `fᵢ` of the free Lie algebra. -/
abbrev genF (i : ι) : FreeLieAlgebra K (AuxGen ι H) := FreeLieAlgebra.of K (.f i)

variable (K ι) in
/-- The generator `h` of the free Lie algebra. -/
abbrev genH (a : H) : FreeLieAlgebra K (AuxGen ι H) := FreeLieAlgebra.of K (.h a)

/-- The defining relations of `𝔤̃(A)`, including the relations making `h ↦ h` linear. -/
def auxRels : Set (FreeLieAlgebra K (AuxGen ι H)) :=
  {x | (∃ a b : H, x = genH ι K (a + b) - genH ι K a - genH ι K b) ∨
       (∃ (c : K) (a : H), x = genH ι K (c • a) - c • genH ι K a) ∨
       (∃ a b : H, x = ⁅genH ι K a, genH ι K b⁆) ∨
       (∃ i j : ι, x = ⁅genE K H i, genF K H j⁆ - if i = j then genH ι K (P.coroot i) else 0) ∨
       (∃ (a : H) (i : ι), x = ⁅genH ι K a, genE K H i⁆ - P.root i a • genE K H i) ∨
       (∃ (a : H) (i : ι), x = ⁅genH ι K a, genF K H i⁆ + P.root i a • genF K H i)}

/-- The ideal of relations of `𝔤̃(A)`. -/
def auxIdeal : LieIdeal K (FreeLieAlgebra K (AuxGen ι H)) :=
  LieSubmodule.lieSpan K _ P.auxRels

/-- The auxiliary Lie algebra `𝔤̃(A)` of [Kac] §1.2, generated by `eᵢ, fᵢ, 𝔥` subject to the
relations (1.2.1). -/
abbrev AuxLieAlgebra : Type _ := FreeLieAlgebra K (AuxGen ι H) ⧸ P.auxIdeal

namespace AuxLieAlgebra

/-- The quotient map from the free Lie algebra. -/
def mk : FreeLieAlgebra K (AuxGen ι H) →ₗ⁅K⁆ P.AuxLieAlgebra := LieIdeal.mkHom P.auxIdeal

lemma mk_surjective : Function.Surjective (mk P) := LieIdeal.mkHom_surjective _

lemma mk_eq_zero_of_mem {x} (hx : x ∈ P.auxRels) : mk P x = 0 :=
  (LieIdeal.mkHom_eq_zero_iff _).mpr (LieSubmodule.subset_lieSpan hx)

/-- The generator `eᵢ`. -/
def e (i : ι) : P.AuxLieAlgebra := mk P (genE K H i)

/-- The generator `fᵢ`. -/
def f (i : ι) : P.AuxLieAlgebra := mk P (genF K H i)

/-- The linear map `𝔥 → 𝔤̃(A)`. -/
def h : H →ₗ[K] P.AuxLieAlgebra where
  toFun a := mk P (genH ι K a)
  map_add' a b := by
    have := mk_eq_zero_of_mem P (x := genH ι K (a + b) - genH ι K a - genH ι K b)
      (Or.inl ⟨a, b, rfl⟩)
    rw [map_sub, map_sub, sub_sub, sub_eq_zero] at this
    exact this
  map_smul' c a := by
    have := mk_eq_zero_of_mem P (x := genH ι K (c • a) - c • genH ι K a)
      (Or.inr (Or.inl ⟨c, a, rfl⟩))
    rw [map_sub, map_smul, sub_eq_zero] at this
    exact this

lemma lie_h_h (a b : H) : ⁅h P a, h P b⁆ = 0 := by
  have := mk_eq_zero_of_mem P (Or.inr (Or.inr (Or.inl ⟨a, b, rfl⟩)))
  rwa [LieHom.map_lie] at this

lemma lie_e_f (i j : ι) : ⁅e P i, f P j⁆ = if i = j then h P (P.coroot i) else 0 := by
  have := mk_eq_zero_of_mem P (Or.inr (Or.inr (Or.inr (Or.inl ⟨i, j, rfl⟩))))
  rw [map_sub, LieHom.map_lie, sub_eq_zero] at this
  rw [e, f, this]
  split_ifs <;> simp [h]

@[simp] lemma lie_e_f_self (i : ι) : ⁅e P i, f P i⁆ = h P (P.coroot i) := by
  simp [lie_e_f]

lemma lie_e_f_of_ne {i j : ι} (hij : i ≠ j) : ⁅e P i, f P j⁆ = 0 := by
  simp [lie_e_f, hij]

lemma lie_h_e (a : H) (i : ι) : ⁅h P a, e P i⁆ = P.root i a • e P i := by
  have := mk_eq_zero_of_mem P (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl ⟨a, i, rfl⟩)))))
  rw [map_sub, LieHom.map_lie, map_smul, sub_eq_zero] at this
  exact this

lemma lie_h_f (a : H) (i : ι) : ⁅h P a, f P i⁆ = -(P.root i a • f P i) := by
  have := mk_eq_zero_of_mem P (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr ⟨a, i, rfl⟩)))))
  rw [map_add, LieHom.map_lie, map_smul, add_eq_zero_iff_eq_neg] at this
  exact this

section lift

variable {L : Type*} [LieRing L] [LieAlgebra K L]

/-- Data of a morphism out of `𝔤̃(A)`: images of `𝔥`, of the `eᵢ` and of the `fᵢ` satisfying the
relations (1.2.1). -/
structure LiftData (L : Type*) [LieRing L] [LieAlgebra K L] where
  /-- The image of `𝔥`. -/
  h : H →ₗ[K] L
  /-- The images of the `eᵢ`. -/
  e : ι → L
  /-- The images of the `fᵢ`. -/
  f : ι → L
  lie_h_h : ∀ a b, ⁅h a, h b⁆ = 0
  lie_e_f : ∀ i j, ⁅e i, f j⁆ = if i = j then h (P.coroot i) else 0
  lie_h_e : ∀ a i, ⁅h a, e i⁆ = P.root i a • e i
  lie_h_f : ∀ a i, ⁅h a, f i⁆ = -(P.root i a • f i)

variable {P}

/-- The map on generators. -/
def LiftData.gen (D : LiftData P L) : AuxGen ι H → L
  | .e i => D.e i
  | .f i => D.f i
  | .h a => D.h a

lemma LiftData.le_ker (D : LiftData P L) :
    P.auxIdeal ≤ (FreeLieAlgebra.lift K D.gen).ker := by
  rw [auxIdeal, LieSubmodule.lieSpan_le]
  intro x hx
  simp only [SetLike.mem_coe, LieHom.mem_ker]
  rcases hx with ⟨a, b, rfl⟩ | ⟨c, a, rfl⟩ | ⟨a, b, rfl⟩ | ⟨i, j, rfl⟩ | ⟨a, i, rfl⟩ | ⟨a, i, rfl⟩
  · simp [LiftData.gen]
  · simp [LiftData.gen]
  · simp [LiftData.gen, D.lie_h_h]
  · simp only [map_sub, LieHom.map_lie, lift_of_apply, LiftData.gen, D.lie_e_f]
    split_ifs <;> simp [LiftData.gen]
  · simp [LiftData.gen, D.lie_h_e]
  · simp [LiftData.gen, D.lie_h_f]

/-- The universal property of `𝔤̃(A)`. -/
def lift (D : LiftData P L) : P.AuxLieAlgebra →ₗ⁅K⁆ L :=
  LieIdeal.lift P.auxIdeal (FreeLieAlgebra.lift K D.gen) D.le_ker

@[simp] lemma lift_e (D : LiftData P L) (i : ι) : lift D (e P i) = D.e i := by
  simp [lift, e, mk, LiftData.gen]

@[simp] lemma lift_f (D : LiftData P L) (i : ι) : lift D (f P i) = D.f i := by
  simp [lift, f, mk, LiftData.gen]

@[simp] lemma lift_h (D : LiftData P L) (a : H) : lift D (h P a) = D.h a := by
  simp [lift, h, mk, LiftData.gen]

/-- Morphisms out of `𝔤̃(A)` are determined by their values on the generators. -/
@[ext]
lemma hom_ext {g₁ g₂ : P.AuxLieAlgebra →ₗ⁅K⁆ L} (he : ∀ i, g₁ (e P i) = g₂ (e P i))
    (hf : ∀ i, g₁ (f P i) = g₂ (f P i)) (hh : ∀ a, g₁ (h P a) = g₂ (h P a)) : g₁ = g₂ := by
  have : g₁.comp (mk P) = g₂.comp (mk P) := by
    ext (x | x | x)
    · exact he x
    · exact hf x
    · exact hh x
  exact LieIdeal.lieHom_ext _ fun x ↦ LieHom.congr_fun this x

end lift

variable {P}

/-- The generators span `𝔤̃(A)` as a Lie algebra. -/
lemma lieSpan_generators :
    LieSubalgebra.lieSpan K P.AuxLieAlgebra
      (Set.range (e P) ∪ Set.range (f P) ∪ Set.range (h P)) = ⊤ := by
  rw [eq_top_iff]
  rintro y -
  obtain ⟨x, rfl⟩ := mk_surjective P y
  induction x using FreeLieAlgebra.induction_on with
  | of g =>
    apply LieSubalgebra.subset_lieSpan
    rcases g with i | i | a
    · exact Or.inl (Or.inl ⟨i, rfl⟩)
    · exact Or.inl (Or.inr ⟨i, rfl⟩)
    · exact Or.inr ⟨a, rfl⟩
  | zero => simp
  | add y z hy hz => simpa using LieSubalgebra.add_mem _ hy hz
  | smul a y hy => simpa using LieSubalgebra.smul_mem _ a hy
  | lie y z hy hz => simpa using LieSubalgebra.lie_mem _ hy hz

/-- Induction principle for `𝔤̃(A)`. -/
@[elab_as_elim]
lemma induction_on {p : P.AuxLieAlgebra → Prop} (y : P.AuxLieAlgebra)
    (he : ∀ i, p (e P i)) (hf : ∀ i, p (f P i)) (hh : ∀ a, p (h P a)) (zero : p 0)
    (add : ∀ y z, p y → p z → p (y + z)) (smul : ∀ (a : K) y, p y → p (a • y))
    (lie : ∀ y z, p y → p z → p ⁅y, z⁆) : p y := by
  have hy : y ∈ LieSubalgebra.lieSpan K P.AuxLieAlgebra
      (Set.range (e P) ∪ Set.range (f P) ∪ Set.range (h P)) := by
    rw [lieSpan_generators]; trivial
  induction hy using LieSubalgebra.lieSpan_induction with
  | mem x hx =>
    rcases hx with (⟨i, rfl⟩ | ⟨i, rfl⟩) | ⟨a, rfl⟩
    exacts [he i, hf i, hh a]
  | zero => exact zero
  | add y z _ _ hy hz => exact add y z hy hz
  | smul a y _ hy => exact smul a y hy
  | lie y z _ _ hy hz => exact lie y z hy hz

/-- A submodule of `𝔤̃(A)` stable under the adjoint action of the generators is stable under the
adjoint action of every element. -/
lemma lie_mem_of_generators (S : Submodule K P.AuxLieAlgebra)
    (he : ∀ i, ∀ x ∈ S, ⁅e P i, x⁆ ∈ S) (hf : ∀ i, ∀ x ∈ S, ⁅f P i, x⁆ ∈ S)
    (hh : ∀ a, ∀ x ∈ S, ⁅h P a, x⁆ ∈ S) (y : P.AuxLieAlgebra) : ∀ x ∈ S, ⁅y, x⁆ ∈ S := by
  induction y using induction_on with
  | he i => exact he i
  | hf i => exact hf i
  | hh a => exact hh a
  | zero => simp
  | add y z hy hz => intro x hx; rw [add_lie]; exact S.add_mem (hy x hx) (hz x hx)
  | smul a y hy => intro x hx; rw [smul_lie]; exact S.smul_mem a (hy x hx)
  | lie y z hy hz =>
    intro x hx
    rw [lie_lie]
    exact S.sub_mem (hy _ (hz x hx)) (hz _ (hy x hx))

/-- The ideal of `𝔤̃(A)` given by a submodule stable under the adjoint action of the
generators. -/
def idealOfGenerators (S : Submodule K P.AuxLieAlgebra)
    (he : ∀ i, ∀ x ∈ S, ⁅e P i, x⁆ ∈ S) (hf : ∀ i, ∀ x ∈ S, ⁅f P i, x⁆ ∈ S)
    (hh : ∀ a, ∀ x ∈ S, ⁅h P a, x⁆ ∈ S) : LieIdeal K P.AuxLieAlgebra where
  __ := S
  lie_mem := fun {y} {_} hx ↦ lie_mem_of_generators S he hf hh y _ hx

@[simp] lemma idealOfGenerators_toSubmodule (S : Submodule K P.AuxLieAlgebra) (he hf hh) :
    (idealOfGenerators S he hf hh).toSubmodule = S := rfl

/-- A submodule of `𝔤̃(A)` containing the generators and stable under the adjoint action of the
generators is everything. -/
lemma eq_top_of_generators (S : Submodule K P.AuxLieAlgebra)
    (hse : ∀ i, e P i ∈ S) (hsf : ∀ i, f P i ∈ S) (hsh : ∀ a, h P a ∈ S)
    (he : ∀ i, ∀ x ∈ S, ⁅e P i, x⁆ ∈ S) (hf : ∀ i, ∀ x ∈ S, ⁅f P i, x⁆ ∈ S)
    (hh : ∀ a, ∀ x ∈ S, ⁅h P a, x⁆ ∈ S) : S = ⊤ := by
  rw [eq_top_iff]
  rintro y -
  induction y using induction_on with
  | he i => exact hse i
  | hf i => exact hsf i
  | hh a => exact hsh a
  | zero => exact S.zero_mem
  | add y z hy hz => exact S.add_mem hy hz
  | smul a y hy => exact S.smul_mem a hy
  | lie y z _ hz => exact lie_mem_of_generators S he hf hh y z hz

variable (P)

/-- The Chevalley involution of `𝔤̃(A)`: `eᵢ ↦ -fᵢ`, `fᵢ ↦ -eᵢ`, `h ↦ -h` ([Kac] (1.3.4)). -/
def chevalleyInvolution : P.AuxLieAlgebra →ₗ⁅K⁆ P.AuxLieAlgebra :=
  lift
    { h := -h P
      e := fun i ↦ -f P i
      f := fun i ↦ -e P i
      lie_h_h := fun a b ↦ by simp [lie_h_h]
      lie_e_f := fun i j ↦ by
        rw [neg_lie, lie_neg, neg_neg, ← lie_skew, lie_e_f]
        split_ifs with h1 h2 h2
        · subst h1; simp
        · exact absurd h1.symm h2
        · exact absurd h2.symm h1
        · simp
      lie_h_e := fun a i ↦ by simp [lie_h_f]
      lie_h_f := fun a i ↦ by simp [lie_h_e] }

@[simp] lemma chevalleyInvolution_e (i : ι) : chevalleyInvolution P (e P i) = -f P i := by
  simp [chevalleyInvolution]

@[simp] lemma chevalleyInvolution_f (i : ι) : chevalleyInvolution P (f P i) = -e P i := by
  simp [chevalleyInvolution]

@[simp] lemma chevalleyInvolution_h (a : H) : chevalleyInvolution P (h P a) = -h P a := by
  simp [chevalleyInvolution]

@[simp] lemma chevalleyInvolution_chevalleyInvolution (x : P.AuxLieAlgebra) :
    chevalleyInvolution P (chevalleyInvolution P x) = x := by
  have : (chevalleyInvolution P).comp (chevalleyInvolution P) = LieHom.id := by
    ext <;> simp
  exact LieHom.congr_fun this x

end AuxLieAlgebra

end Matrix.Realization

end
