/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.Grothendieck
import LieLean.Algebra.Lie.KacMoody.CompleteReducibility
import LieLean.Algebra.Lie.KacMoody.CompositionSeries.Casimir

/-!
# Casimir blocks of the category `𝒪`

Let `A` be a symmetrizable generalized Cartan matrix, `K` a field of characteristic zero, and `V`
a `𝔤(A)`-module in the category `𝒪`. The generalized Casimir operator `Ω` (`KacMoody/Casimir.lean`)
commutes with `𝔤(A)` and preserves the finite-dimensional weight spaces of `V`. We show that `V`
is the direct sum of the generalized eigenspaces `V^c` of `Ω` (`c ∈ K`), the *Casimir blocks*;
each is a submodule in `𝒪`, and its composition factors `L(μ)` are exactly those of `V` with
`(μ + 2ρ | μ) = c`. No algebraic closure of `K` is needed: the eigenvalues of `Ω` on a weight
space are of the form `(μ + 2ρ | μ)`. A module generated by a highest-weight vector of weight `λ`
lies in the single block `c = (λ + 2ρ | λ)`.

This is the Kac–Moody form of the decomposition of `𝒪` by central (infinitesimal) characters
([HumO] §1.12–1.13 (check)); since only the Casimir operator is available, the blocks here are
unions of linkage classes: `L(λ)` and `L(μ)` lie in the same block iff
`(λ + ρ | λ + ρ) = (μ + ρ | μ + ρ)` ([Kac] §9.8 (check)).

## Main definitions

* `Matrix.Realization.KacMoodyAlgebra.IsStandardForm.casimirBlock`: the Casimir block `V^c`, the
  generalized `c`-eigenspace of `Ω`, as a Lie submodule.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.casimirBlock`: the same, for the invariant form
  `invForm` of [Kac] Thm. 2.2 (check).

## Main results

* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.isInternal_casimirBlock`: **block
  decomposition**, `V = ⊕_c V^c`.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.multiplicity_casimirBlock`:
  `[V^c : L(μ)] = [V : L(μ)]` if `(μ + 2ρ | μ) = c` and `0` otherwise.
* `IsStandardForm.exists_multiplicity_ne_zero_of_casimirBlock_ne_bot`: a nonzero block `V^c` has
  `c = (μ + 2ρ | μ)` for a composition factor `L(μ)` of `V`.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.casimirBlock_eq_top_of_surjective`,
  `Matrix.Realization.KacMoodyAlgebra.IsStandardForm.lieSpan_le_casimirBlock`: a module generated
  by a highest-weight vector of weight `λ` lies in the block `c = (λ + 2ρ | λ)`.
* `Matrix.Realization.KacMoodyAlgebra.IsStandardForm.map_mem_casimirBlock`,
  `Matrix.Realization.KacMoodyAlgebra.IsStandardForm.casimirBlock_le_map`: morphisms preserve
  blocks, and surjective morphisms are surjective on blocks.

## Proof

We reconstructed the argument (the idea is that of [HumO] §1.12 (check) and [Kac] §9.8 (check)).

1. *`Ω` is locally finite with eigenvalues `(μ + 2ρ | μ)`.* Let `v ∈ V_ν` and take a local
   composition series `0 = V₀ ⊆ ⋯ ⊆ V_t = V` for `ν` ([Kac] Lemma 9.6 (check)) with irreducible
   factors `V_j / V_{j-1} ≅ L(λ_j)`, `j ∈ J`. The operator `Ω` preserves each `V_j` and each
   weight space, acts on `L(λ_j)` by `c(λ_j) = (λ_j + 2ρ | λ_j)` ([Kac] Cor. 2.6 (check)), and
   the factors `j ∉ J` have zero `ν`-weight space. Hence `∏_{j ∈ J} (Ω - c(λ_j))` maps `V_j ∩ V_ν`
   into `V_{j-1}` step by step, and kills `v`.
2. *Linear algebra.* If `∏_j (Ω - c_j)` kills `v`, then `v` is a sum of generalized eigenvectors
   of `Ω` (the kernel of a product of pairwise coprime polynomials `(X - c)^m` is the sum of the
   kernels). With the independence of generalized eigenspaces, `V = ⊕_c V^c`.
3. *Factors of a block.* A factor `L(μ)` of `V^c` gives `w ∈ V^c ∩ V_μ` primitive modulo a
   submodule `N`, so `Ω w ≡ c(μ) w` modulo the `Ω`-stable `N`; then `(Ω - c)^k w ≡ (c(μ) - c)^k w`,
   and `(Ω - c)^k w = 0` forces `c(μ) = c`. Conversely, such a factor of `V` gives an eigenvector of
   `Ω` for `c(μ)` in a quotient of `V`, which lifts to `V^{c(μ)}` since surjective morphisms are
   surjective on blocks. Additivity of multiplicities on `0 → V^c → V → V / V^c → 0`, where
   `(V / V^c)^c = 0`, gives the multiplicities of `V^c`.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §2.5–2.6, §9.5–9.8.
* [HumO] J. E. Humphreys, *Representations of semisimple Lie algebras in the BGG category `𝒪`*,
  GSM 94, AMS 2008, §1.12–1.13.
-/

open Module LieModule Polynomial

noncomputable section

namespace Module.End

variable {K M : Type*} [Field K] [AddCommGroup M] [Module K M]

theorem ker_aeval_prod_le_iSup_maxGenEigenspace (f : End K M) (s : Finset K) (m : K → ℕ) :
    LinearMap.ker (aeval f (∏ c ∈ s, (X - C c) ^ m c)) ≤ ⨆ c ∈ s, f.maxGenEigenspace c := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [LinearMap.ker_eq_bot']
  | insert a s ha ih =>
    rw [Finset.prod_insert ha, ← sup_ker_aeval_eq_ker_aeval_mul_of_coprime]
    · refine sup_le ?_ (ih.trans (biSup_mono fun c hc ↦ Finset.mem_insert_of_mem hc))
      refine le_trans ?_ (le_biSup _ (Finset.mem_insert_self a s))
      intro v hv
      rw [mem_maxGenEigenspace]
      refine ⟨m a, ?_⟩
      simpa [Algebra.algebraMap_eq_smul_one] using hv
    · refine IsCoprime.prod_right fun c hc ↦ ?_
      exact (isCoprime_X_sub_C_of_isUnit_sub
        (sub_ne_zero.mpr fun h : a = c ↦ ha (h ▸ hc)).isUnit).pow

theorem mem_iSup_maxGenEigenspace_of_prod_apply_eq_zero (f : End K M) (l : List K) {v : M}
    (hv : (l.map fun c ↦ f - c • (1 : End K M)).prod v = 0) :
    v ∈ ⨆ c ∈ l, f.maxGenEigenspace c := by
  classical
  have h : aeval f (∏ c ∈ l.toFinset, (X - C c) ^ l.count c) =
      (l.map fun c ↦ f - c • (1 : End K M)).prod := by
    rw [← Finset.prod_list_map_count, map_list_prod, List.map_map]
    congr 1
    refine List.map_congr_left fun c _ ↦ ?_
    simp [Algebra.algebraMap_eq_smul_one]
  have := ker_aeval_prod_le_iSup_maxGenEigenspace f l.toFinset l.count
    (LinearMap.mem_ker.mpr (h ▸ hv))
  simpa using this

end Module.End

namespace Matrix.Realization.KacMoodyAlgebra

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [CharZero K] [AddCommGroup H]
  [Module K H] [FiniteDimensional K H] {A : Matrix ι ι ℤ} {P : Realization A K H}
  {S : A.Symmetrization} {B : LinearMap.BilinForm K P.KacMoodyAlgebra}
  {V W : Type*} [AddCommGroup V] [Module K V] [LieRingModule P.KacMoodyAlgebra V]
  [LieModule K P.KacMoodyAlgebra V] [AddCommGroup W] [Module K W]
  [LieRingModule P.KacMoodyAlgebra W] [LieModule K P.KacMoodyAlgebra W]

namespace IsStandardForm

variable (hB : IsStandardForm P S B)
include hB

/-- Naturality of `(Ω - c)ᵏ`. -/
lemma map_pow_casimir_sub (f : V →ₗ⁅K,P.KacMoodyAlgebra⁆ W) (hV : IsPosFinite P V)
    (hW : IsPosFinite P W) (c : K) (k : ℕ) (v : V) :
    f (((hB.casimir V hV - c • (1 : Module.End K V)) ^ k) v) =
      ((hB.casimir W hW - c • (1 : Module.End K W)) ^ k) (f v) := by
  induction k generalizing v with
  | zero => simp
  | succ k ih =>
    rw [pow_succ, pow_succ, Module.End.mul_apply, Module.End.mul_apply, ih]
    congr 1
    simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply, map_sub,
      map_smul, hB.map_casimir f hV hW]

/-- The operators `∏ⱼ (Ω - cⱼ)` preserve every subspace preserved by `Ω`. -/
lemma prod_map_casimir_sub_mem (hV : IsPosFinite P V) (p : Submodule K V)
    (hp : ∀ v ∈ p, hB.casimir V hV v ∈ p) (l : List K) {v : V} (hv : v ∈ p) :
    (l.map fun c ↦ hB.casimir V hV - c • (1 : Module.End K V)).prod v ∈ p := by
  induction l with
  | nil => simpa using hv
  | cons c l ih =>
    rw [List.map_cons, List.prod_cons, Module.End.mul_apply]
    simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply]
    exact sub_mem (hp _ ih) (p.smul_mem c ih)

/-- The Casimir operator preserves every Lie submodule of a module in `𝒪`. -/
lemma casimir_mem_lieSubmodule (hV : IsCategoryO P V) (N : LieSubmodule K P.KacMoodyAlgebra V)
    {v : V} (hv : v ∈ N) : hB.casimir V hV.isPosFinite v ∈ N := by
  have := hB.map_casimir N.incl (hV.lieSubmodule N).isPosFinite hV.isPosFinite ⟨v, hv⟩
  have h : hB.casimir V hV.isPosFinite v =
      ((hB.casimir N (hV.lieSubmodule N).isPosFinite ⟨v, hv⟩ : N) : V) := this.symm
  rw [h]
  exact Subtype.prop _

variable (hA : A.IsGeneralizedCartan)
include hA

/-- The Casimir operator commutes with the action of `𝔤(A)`. -/
lemma commute_casimir_toEnd (hV : IsPosFinite P V) (x : P.KacMoodyAlgebra) :
    Commute (hB.casimir V hV) (toEnd K P.KacMoodyAlgebra V x) :=
  LinearMap.ext fun v ↦ hB.casimir_lie hA hV x v

/-- The Casimir operator preserves the weight spaces. -/
lemma casimir_mem_weightSpace (hV : IsPosFinite P V) {μ : Dual K H} {v : V}
    (hv : v ∈ weightSpace P V μ) : hB.casimir V hV v ∈ weightSpace P V μ :=
  map_mem_weightSpaceOfMap P (hB.casimirHom hA hV) hv

/-- The *Casimir block* `V^c` of a `𝔤(A)`-module `V`: the generalized eigenspace of the Casimir
operator `Ω` for the eigenvalue `c`. It is a Lie submodule, since `Ω` commutes with `𝔤(A)`. -/
def casimirBlock (hV : IsPosFinite P V) (c : K) : LieSubmodule K P.KacMoodyAlgebra V :=
  { (hB.casimir V hV).maxGenEigenspace c with
    lie_mem := fun {x _} hv ↦
      Module.End.mapsTo_maxGenEigenspace_of_comm (hB.commute_casimir_toEnd hA hV x) c hv }

@[simp] lemma casimirBlock_toSubmodule (hV : IsPosFinite P V) (c : K) :
    (hB.casimirBlock hA hV c).toSubmodule = (hB.casimir V hV).maxGenEigenspace c :=
  rfl

lemma mem_casimirBlock (hV : IsPosFinite P V) (c : K) {v : V} :
    v ∈ hB.casimirBlock hA hV c ↔
      ∃ k : ℕ, ((hB.casimir V hV - c • (1 : Module.End K V)) ^ k) v = 0 :=
  Module.End.mem_maxGenEigenspace _ _ _

/-- Morphisms of modules map Casimir blocks to Casimir blocks. -/
theorem map_mem_casimirBlock (f : V →ₗ⁅K,P.KacMoodyAlgebra⁆ W) (hV : IsPosFinite P V)
    (hW : IsPosFinite P W) {c : K} {v : V} (hv : v ∈ hB.casimirBlock hA hV c) :
    f v ∈ hB.casimirBlock hA hW c := by
  obtain ⟨k, hk⟩ := (hB.mem_casimirBlock hA hV c).mp hv
  exact (hB.mem_casimirBlock hA hW c).mpr
    ⟨k, by rw [← hB.map_pow_casimir_sub f hV hW, hk, map_zero]⟩

/-- The Casimir blocks are independent. -/
theorem iSupIndep_casimirBlock (hV : IsPosFinite P V) :
    iSupIndep fun c ↦ (hB.casimirBlock hA hV c).toSubmodule :=
  Module.End.independent_maxGenEigenspace _

/-- If `u ∈ N'` and `N' / N ≅ L(μ)`, then `Ω u - (μ + 2ρ | μ) u ∈ N`. -/
lemma casimir_sub_smul_mem_of_equiv (hV : IsCategoryO P V)
    {N N' : LieSubmodule K P.KacMoodyAlgebra V} {μ : Dual K H}
    (ψ : N.Subquotient N' ≃ₗ⁅K,P.KacMoodyAlgebra⁆ IrreducibleModule P μ) {u : V} (hu : u ∈ N') :
    hB.casimir V hV.isPosFinite u - P.dualBilinForm S (μ + 2 • P.rho) μ • u ∈ N := by
  have hN' : IsCategoryO P N' := hV.lieSubmodule N'
  have hQ : IsCategoryO P (N.Subquotient N') := hN'.quotient _
  let φ : VermaModule P μ →ₗ⁅K,P.KacMoodyAlgebra⁆ N.Subquotient N' :=
    (ψ.symm : IrreducibleModule P μ →ₗ⁅K,P.KacMoodyAlgebra⁆ N.Subquotient N').comp
      (LieSubmodule.Quotient.mk' _)
  have hφ : Function.Surjective φ :=
    ψ.symm.surjective.comp (LieSubmodule.Quotient.surjective_mk' _)
  set π := LieSubmodule.Quotient.mk' (N.comap N'.incl)
  have h1 := hB.casimir_eq_smul_of_surjective hA hQ.isPosFinite φ hφ (π ⟨u, hu⟩)
  have h2 := hB.map_casimir π hN'.isPosFinite hQ.isPosFinite ⟨u, hu⟩
  have h3 := hB.map_casimir N'.incl hN'.isPosFinite hV.isPosFinite ⟨u, hu⟩
  have h4 : π (hB.casimir N' hN'.isPosFinite ⟨u, hu⟩ -
      P.dualBilinForm S (μ + 2 • P.rho) μ • ⟨u, hu⟩) = 0 := by
    rw [map_sub, map_smul, h2, h1, sub_self]
  rw [LieSubmodule.Quotient.mk_eq_zero, LieSubmodule.mem_comap, map_sub, map_smul, h3] at h4
  exact h4

/-- Along a local composition series for `ν` from `N` to `M` with irreducible factors `L(λⱼ)`,
the operator `∏ⱼ (Ω - (λⱼ + 2ρ | λⱼ))` maps `M ∩ V_ν` into `N`. -/
theorem prod_apply_mem_of_isLocalCompositionSeries (hV : IsCategoryO P V) {ν : Dual K H}
    {N M : LieSubmodule K P.KacMoodyAlgebra V}
    {l : List (LieSubmodule K P.KacMoodyAlgebra V × Option (Dual K H))}
    (hl : IsLocalCompositionSeries P ν N l M) {v : V} (hvM : v ∈ M)
    (hv : v ∈ weightSpace P V ν) :
    (((factorWeights l).map fun μ ↦ P.dualBilinForm S (μ + 2 • P.rho) μ).map
      fun c ↦ hB.casimir V hV.isPosFinite - c • (1 : Module.End K V)).prod v ∈ N := by
  induction l generalizing N with
  | nil =>
    rw [IsLocalCompositionSeries.nil_iff.mp hl]
    simpa using hvM
  | cons a l ih =>
    obtain ⟨N', o⟩ := a
    obtain ⟨-, hf, hl'⟩ := IsLocalCompositionSeries.cons_iff.mp hl
    have hu := ih hl'
    have huν : (((factorWeights l).map fun μ ↦ P.dualBilinForm S (μ + 2 • P.rho) μ).map
        fun c ↦ hB.casimir V hV.isPosFinite - c • (1 : Module.End K V)).prod v ∈
          weightSpace P V ν :=
      hB.prod_map_casimir_sub_mem hV.isPosFinite (weightSpace P V ν)
        (fun _ ↦ hB.casimir_mem_weightSpace hA hV.isPosFinite) _ hv
    cases o with
    | none =>
      exact (weightSpace_subquotient_eq_bot_iff hV N N' ν).mp (hf ν (mem_cone_self ν)) ⟨hu, huν⟩
    | some μ =>
      simp only [factorWeights_cons_some, List.map_cons, List.prod_cons, Module.End.mul_apply,
        LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply]
      exact hB.casimir_sub_smul_mem_of_equiv hA hV hf.2.some hu

/-- **Casimir block decomposition**: a module in `𝒪` is the sum of its Casimir blocks. -/
theorem iSup_casimirBlock_eq_top (hV : IsCategoryO P V) :
    ⨆ c, (hB.casimirBlock hA hV.isPosFinite c).toSubmodule = ⊤ := by
  rw [eq_top_iff, ← hV.iSup_weightSpaceOfMap_eq_top]
  refine iSup_le fun ν v hv ↦ ?_
  obtain ⟨l, hl⟩ := hV.exists_isLocalCompositionSeries ν
  have h0 := hB.prod_apply_mem_of_isLocalCompositionSeries hA hV hl (LieSubmodule.mem_top v) hv
  rw [LieSubmodule.mem_bot] at h0
  exact (iSup₂_le fun c _ ↦ le_iSup (fun c ↦ (hB.casimirBlock hA hV.isPosFinite c).toSubmodule) c)
    (Module.End.mem_iSup_maxGenEigenspace_of_prod_apply_eq_zero _ _ h0)

open scoped Classical in
/-- **Casimir block decomposition** ([HumO] §1.12 (check); [Kac] §9.5 (check)): a module in `𝒪`
is the internal direct sum of its Casimir blocks. -/
theorem isInternal_casimirBlock (hV : IsCategoryO P V) :
    DirectSum.IsInternal fun c ↦ (hB.casimirBlock hA hV.isPosFinite c).toSubmodule :=
  DirectSum.isInternal_submodule_of_iSupIndep_of_iSup_eq_top
    (hB.iSupIndep_casimirBlock hA hV.isPosFinite) (hB.iSup_casimirBlock_eq_top hA hV)

/-- A morphism `f : V → W` of modules in `𝒪` with `f` surjective maps `V^c` onto `W^c`. -/
theorem casimirBlock_le_map (hV : IsCategoryO P V) (hW : IsCategoryO P W)
    (f : V →ₗ⁅K,P.KacMoodyAlgebra⁆ W) (hf : Function.Surjective f) (c : K) :
    hB.casimirBlock hA hW.isPosFinite c ≤ (hB.casimirBlock hA hV.isPosFinite c).map f := by
  intro w hw
  obtain ⟨v, rfl⟩ := hf w
  have hv : v ∈ ⨆ c, (hB.casimirBlock hA hV.isPosFinite c).toSubmodule := by
    rw [hB.iSup_casimirBlock_eq_top hA hV]; trivial
  have hmap : f v ∈ ⨆ c, ((hB.casimirBlock hA hV.isPosFinite c).toSubmodule.map
      (f : V →ₗ[K] W)) := by
    rw [← Submodule.map_iSup]; exact Submodule.mem_map_of_mem hv
  have := (hB.iSupIndep_casimirBlock hA hW.isPosFinite).mem_of_mem_iSup_of_le
    (F := fun c ↦ (hB.casimirBlock hA hV.isPosFinite c).toSubmodule.map (f : V →ₗ[K] W))
    (fun c ↦ by
      rintro _ ⟨u, hu, rfl⟩
      exact hB.map_mem_casimirBlock hA f hV.isPosFinite hW.isPosFinite hu) hw hmap
  obtain ⟨u, hu, hfu⟩ := this
  exact (LieSubmodule.mem_map _).mpr ⟨u, hu, hfu⟩

/-- Let `w ∈ V_μ` be primitive modulo a submodule `N` (`w ∉ N`, `eᵢ w ∈ N` for all `i`). If `w`
lies in the Casimir block `V^c`, then `c = (μ + 2ρ | μ)`. -/
theorem eq_of_mem_casimirBlock (hV : IsCategoryO P V) (N : LieSubmodule K P.KacMoodyAlgebra V)
    {μ : Dual K H} {w : V} (hw : w ∈ weightSpace P V μ) (hwN : w ∉ N) (he : ∀ i, ⁅e P i, w⁆ ∈ N)
    {c : K} (hc : w ∈ hB.casimirBlock hA hV.isPosFinite c) :
    P.dualBilinForm S (μ + 2 • P.rho) μ = c := by
  set Ω := hB.casimir V hV.isPosFinite
  set a := P.dualBilinForm S (μ + 2 • P.rho) μ
  have h1 : Ω w - a • w ∈ N := hB.casimir_sub_smul_mem hV N hw he
  have key (k : ℕ) : ((Ω - c • (1 : Module.End K V)) ^ k) w - (a - c) ^ k • w ∈ N := by
    induction k with
    | zero => simp
    | succ k ih =>
      set u := ((Ω - c • (1 : Module.End K V)) ^ k) w
      have hT := sub_mem (hB.casimir_mem_lieSubmodule hV N ih) (N.smul_mem c ih)
      have e : ((Ω - c • (1 : Module.End K V)) ^ (k + 1)) w - (a - c) ^ (k + 1) • w =
          (a - c) ^ k • (Ω w - a • w) + (Ω (u - (a - c) ^ k • w) - c • (u - (a - c) ^ k • w)) := by
        rw [pow_succ', Module.End.mul_apply]
        simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply, map_sub,
          map_smul, u]
        module
      rw [e]
      exact add_mem (N.smul_mem _ h1) hT
  obtain ⟨k, hk⟩ := (hB.mem_casimirBlock hA hV.isPosFinite c).mp hc
  have := key k
  rw [hk, zero_sub, neg_mem_iff] at this
  by_contra hne
  have hne' : (a - c) ^ k ≠ 0 := pow_ne_zero _ (sub_ne_zero.mpr hne)
  have := N.smul_mem ((a - c) ^ k)⁻¹ this
  rw [inv_smul_smul₀ hne'] at this
  exact hwN this

/-- Every composition factor `L(μ)` of the Casimir block `V^c` of a module in `𝒪` satisfies
`(μ + 2ρ | μ) = c`. -/
theorem eq_of_multiplicity_casimirBlock_ne_zero (hV : IsCategoryO P V) {c : K} {μ : Dual K H}
    (hμ : (hV.lieSubmodule (hB.casimirBlock hA hV.isPosFinite c)).multiplicity μ ≠ 0) :
    P.dualBilinForm S (μ + 2 • P.rho) μ = c := by
  set N := hB.casimirBlock hA hV.isPosFinite c
  have hN := hV.lieSubmodule N
  obtain ⟨l, hl⟩ := hN.exists_isLocalCompositionSeries μ
  obtain ⟨M₁, M₂, -, -, -, -, ⟨ψ⟩⟩ :=
    hl.exists_of_mem_factorWeights ((hN.multiplicity_ne_zero_iff (mem_cone_self μ) hl).mp hμ)
  obtain ⟨w, hw, -, hw₁, he⟩ := hN.exists_lie_e_mem_of_equiv ψ
  refine hB.eq_of_mem_casimirBlock hA hN M₁ hw hw₁ he ?_
  obtain ⟨k, hk⟩ := (hB.mem_casimirBlock hA hV.isPosFinite c).mp w.2
  refine (hB.mem_casimirBlock hA hN.isPosFinite c).mpr ⟨k, Subtype.ext ?_⟩
  have := hB.map_pow_casimir_sub N.incl hN.isPosFinite hV.isPosFinite c k w
  rw [LieSubmodule.incl_apply] at this
  rw [this]
  exact hk

/-- If `L(μ)` is a composition factor of a module `V` in `𝒪`, then the Casimir block
`V^{(μ + 2ρ | μ)}` is nonzero. -/
theorem casimirBlock_ne_bot_of_multiplicity_ne_zero (hV : IsCategoryO P V) {μ : Dual K H}
    (hμ : hV.multiplicity μ ≠ 0) :
    hB.casimirBlock hA hV.isPosFinite (P.dualBilinForm S (μ + 2 • P.rho) μ) ≠ ⊥ := by
  obtain ⟨l, hl⟩ := hV.exists_isLocalCompositionSeries μ
  obtain ⟨M₁, M₂, -, -, -, -, ⟨ψ⟩⟩ :=
    hl.exists_of_mem_factorWeights ((hV.multiplicity_ne_zero_iff (mem_cone_self μ) hl).mp hμ)
  obtain ⟨w, hw, -, hw₁, he⟩ := hV.exists_lie_e_mem_of_equiv ψ
  set π := LieSubmodule.Quotient.mk' M₁
  have hQ : IsCategoryO P (V ⧸ M₁) := hV.quotient M₁
  have hπw : π w ∈ hB.casimirBlock hA hQ.isPosFinite (P.dualBilinForm S (μ + 2 • P.rho) μ) := by
    refine (hB.mem_casimirBlock hA hQ.isPosFinite _).mpr ⟨1, ?_⟩
    rw [pow_one, LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply,
      hB.casimir_apply_of_lie_e_eq_zero hQ.isPosFinite (map_mem_weightSpaceOfMap P π hw)
        fun i ↦ by rw [← LieModuleHom.map_lie, LieSubmodule.Quotient.mk_eq_zero]; exact he i,
      sub_self]
  intro hbot
  obtain ⟨u, hu, hπu⟩ := (LieSubmodule.mem_map _).mp
    (hB.casimirBlock_le_map hA hV hQ π (LieSubmodule.Quotient.surjective_mk' M₁) _ hπw)
  rw [hbot, LieSubmodule.mem_bot] at hu
  rw [hu, map_zero, eq_comm, LieSubmodule.Quotient.mk_eq_zero] at hπu
  exact hw₁ hπu

/-- The Casimir block `c` of `V / V^c` is zero. -/
lemma casimirBlock_quotient_eq_bot (hV : IsCategoryO P V) (c : K) :
    hB.casimirBlock hA (hV.quotient (hB.casimirBlock hA hV.isPosFinite c)).isPosFinite c = ⊥ := by
  set N := hB.casimirBlock hA hV.isPosFinite c
  have hQ := hV.quotient N
  rw [eq_bot_iff]
  intro x hx
  obtain ⟨v, rfl⟩ := LieSubmodule.Quotient.surjective_mk' N x
  obtain ⟨k, hk⟩ := (hB.mem_casimirBlock hA hQ.isPosFinite c).mp hx
  rw [← hB.map_pow_casimir_sub _ hV.isPosFinite, LieSubmodule.Quotient.mk_eq_zero] at hk
  obtain ⟨m, hm⟩ := (hB.mem_casimirBlock hA hV.isPosFinite c).mp hk
  rw [← Module.End.mul_apply, ← pow_add] at hm
  rw [LieSubmodule.mem_bot, LieSubmodule.Quotient.mk_eq_zero]
  exact (hB.mem_casimirBlock hA hV.isPosFinite c).mpr ⟨_, hm⟩

open scoped Classical in
/-- **Multiplicities in a Casimir block**: `[V^c : L(μ)] = [V : L(μ)]` if `(μ + 2ρ | μ) = c`, and
`[V^c : L(μ)] = 0` otherwise. -/
theorem multiplicity_casimirBlock (hV : IsCategoryO P V) (c : K) (μ : Dual K H) :
    (hV.lieSubmodule (hB.casimirBlock hA hV.isPosFinite c)).multiplicity μ =
      if P.dualBilinForm S (μ + 2 • P.rho) μ = c then hV.multiplicity μ else 0 := by
  have hadd := hV.multiplicity_eq_add (hB.casimirBlock hA hV.isPosFinite c) μ
  split_ifs with h
  · have h0 : (hV.quotient (hB.casimirBlock hA hV.isPosFinite c)).multiplicity μ = 0 := by
      by_contra hne
      have := hB.casimirBlock_ne_bot_of_multiplicity_ne_zero hA _ hne
      rw [h, hB.casimirBlock_quotient_eq_bot hA hV c] at this
      exact this rfl
    rw [hadd, h0, add_zero]
  · by_contra hne
    exact h (hB.eq_of_multiplicity_casimirBlock_ne_zero hA hV hne)

/-- A nonzero Casimir block `V^c` of a module in `𝒪` has a composition factor `L(μ)`; then
`[V : L(μ)] ≠ 0` and `c = (μ + 2ρ | μ)`. -/
theorem exists_multiplicity_ne_zero_of_casimirBlock_ne_bot (hV : IsCategoryO P V) {c : K}
    (hc : hB.casimirBlock hA hV.isPosFinite c ≠ ⊥) :
    ∃ μ, hV.multiplicity μ ≠ 0 ∧ P.dualBilinForm S (μ + 2 • P.rho) μ = c := by
  set N := hB.casimirBlock hA hV.isPosFinite c
  have hN := hV.lieSubmodule N
  have hne : hN.multiplicities ≠ 0 := by
    intro h0
    have hch := hN.character_eq_sumIrreducibleCharacter
    rw [h0, map_zero] at hch
    apply hc
    rw [← LieSubmodule.toSubmodule_eq_bot, eq_bot_iff]
    intro v hv
    have hv' : (⟨v, hv⟩ : N) ∈ ⨆ μ, weightSpace P N μ := by
      rw [hN.iSup_weightSpaceOfMap_eq_top]; trivial
    have hbot : ∀ μ, weightSpace P N μ = ⊥ := fun μ ↦ by
      have := hN.finiteDimensional_weightSpaceOfMap μ
      have h' := congrArg (fun x ↦ x.coeffAt μ) hch
      simp only [IsCategoryO.coeffAt_character, HahnSeries.coeff_zero, Nat.cast_eq_zero,
        Submodule.finrank_eq_zero] at h'
      exact h'
    simp only [hbot, iSup_bot, Submodule.mem_bot] at hv'
    exact congrArg Subtype.val hv'
  obtain ⟨μ, hμ⟩ : ∃ μ, hN.multiplicities.coeffAt μ ≠ 0 := by
    by_contra! h
    exact hne (CharacterRing.ext fun μ ↦ h μ)
  rw [IsCategoryO.coeffAt_multiplicities, Nat.cast_ne_zero] at hμ
  have hc' := hB.eq_of_multiplicity_casimirBlock_ne_zero hA hV hμ
  refine ⟨μ, ?_, hc'⟩
  simpa only [hB.multiplicity_casimirBlock hA hV c μ, hc', ↓reduceIte] using hμ

/-- A quotient of the Verma module `M(λ)` lies in the single Casimir block `c = (λ + 2ρ | λ)`. -/
theorem casimirBlock_eq_top_of_surjective (hV : IsPosFinite P V) {Λ : Dual K H}
    (φ : VermaModule P Λ →ₗ⁅K,P.KacMoodyAlgebra⁆ V) (hφ : Function.Surjective φ) :
    hB.casimirBlock hA hV (P.dualBilinForm S (Λ + 2 • P.rho) Λ) = ⊤ := by
  rw [eq_top_iff]
  intro v _
  refine (hB.mem_casimirBlock hA hV _).mpr ⟨1, ?_⟩
  rw [pow_one, LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply,
    hB.casimir_eq_smul_of_surjective hA hV φ hφ, sub_self]

/-- In any module, the submodule generated by a vector `w` of weight `λ` killed by all the `eᵢ`
(a highest-weight vector) lies in the single Casimir block `c = (λ + 2ρ | λ)`. -/
theorem lieSpan_le_casimirBlock (hV : IsPosFinite P V) {Λ : Dual K H} {w : V}
    (hw : w ∈ weightSpace P V Λ) (he : ∀ i, ⁅e P i, w⁆ = 0) :
    LieSubmodule.lieSpan K P.KacMoodyAlgebra {w} ≤
      hB.casimirBlock hA hV (P.dualBilinForm S (Λ + 2 • P.rho) Λ) := by
  rw [LieSubmodule.lieSpan_le, Set.singleton_subset_iff]
  refine (hB.mem_casimirBlock hA hV _).mpr ⟨1, ?_⟩
  rw [pow_one, LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply,
    hB.casimir_apply_of_lie_e_eq_zero hV hw he, sub_self]

end IsStandardForm

/-! ### Versions for the invariant form `invForm` -/

namespace IsCategoryO

variable (hA : A.IsGeneralizedCartan) (S) (hV : IsCategoryO P V)

/-- The *Casimir block* `V^c` of a module `V` in `𝒪`, for the Casimir operator of the invariant
form `invForm` of [Kac] Thm. 2.2 (check) attached to the symmetrization `S`: the generalized
eigenspace of `Ω` for the eigenvalue `c`, as a Lie submodule. -/
abbrev casimirBlock (c : K) : LieSubmodule K P.KacMoodyAlgebra V :=
  (isStandardForm_invForm P S).casimirBlock hA hV.isPosFinite c

open scoped Classical in
/-- **Casimir block decomposition** ([HumO] §1.12 (check); [Kac] §9.5 (check)): for a
symmetrizable generalized Cartan matrix `A` with symmetrization `S` and `K` of characteristic zero,
a module `V` in `𝒪` is the internal direct sum of its Casimir blocks `V^c`, `c ∈ K`. -/
theorem isInternal_casimirBlock :
    DirectSum.IsInternal fun c ↦ (hV.casimirBlock S hA c).toSubmodule :=
  (isStandardForm_invForm P S).isInternal_casimirBlock hA hV

open scoped Classical in
/-- **Composition factors of a Casimir block**: `[V^c : L(μ)] = [V : L(μ)]` if
`(μ + 2ρ | μ) = c`, and `[V^c : L(μ)] = 0` otherwise. -/
theorem multiplicity_casimirBlock (c : K) (μ : Dual K H) :
    (hV.lieSubmodule (hV.casimirBlock S hA c)).multiplicity μ =
      if P.dualBilinForm S (μ + 2 • P.rho) μ = c then hV.multiplicity μ else 0 := by
  convert (isStandardForm_invForm P S).multiplicity_casimirBlock hA hV c μ

/-- A quotient `V` of the Verma module `M(λ)` lies in the single Casimir block
`c = (λ + 2ρ | λ)`. -/
theorem casimirBlock_eq_top_of_surjective {Λ : Dual K H}
    (φ : VermaModule P Λ →ₗ⁅K,P.KacMoodyAlgebra⁆ V) (hφ : Function.Surjective φ) :
    hV.casimirBlock S hA (P.dualBilinForm S (Λ + 2 • P.rho) Λ) = ⊤ :=
  (isStandardForm_invForm P S).casimirBlock_eq_top_of_surjective hA hV.isPosFinite φ hφ

end IsCategoryO

end Matrix.Realization.KacMoodyAlgebra

end
