/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.CasimirIrreducible
import LieLean.Algebra.Lie.KacMoody.Character

/-!
# Complete reducibility of integrable modules in the category `𝒪`

Let `A` be a symmetrizable generalized Cartan matrix and `K` a field of characteristic zero. We
show that every integrable `𝔤(A)`-module `V` in the category `𝒪` is a direct sum of irreducible
modules `L(Λ)` with `Λ` dominant integral ([Kac] Thm. 10.7 (b)). The main tool is the
generalized Casimir operator `Ω` (`KacMoody/Casimir.lean`), which commutes with `𝔤(A)` and acts on
a vector of weight `λ` killed by all the `eᵢ` by `c(λ) = (λ + 2ρ | λ)`; for dominant integral
`Λ, μ` with `Λ - μ ∈ Q₊ \ {0}` one has `c(Λ) ≠ c(μ)` (`dualBilinForm_add_two_rho_ne`).

## Main definitions

* `Matrix.Realization.KacMoodyAlgebra.IsStandardForm.casimirHom`: the Casimir operator as a
  morphism of `𝔤(A)`-modules.

## Main results

* `Matrix.Realization.KacMoodyAlgebra.IsIntegrable.quotient`,
  `Matrix.Realization.KacMoodyAlgebra.IsIntegrable.lieSubmodule`: quotients and submodules of
  integrable modules in `𝒪` are integrable.
* `Matrix.Realization.KacMoodyAlgebra.IsStandardForm.map_casimir`: the Casimir operator is
  natural with respect to morphisms of `𝔤(A)`-modules.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.exists_equiv_irreducibleModule_of_isAtom`: an
  irreducible submodule of an integrable module in `𝒪` is isomorphic to `L(Λ)` for some dominant
  integral `Λ`.
* `Matrix.Realization.KacMoodyAlgebra.IsStandardForm.isAtom_lieSpan_singleton`: in an integrable
  module in `𝒪`, a nonzero vector of weight `Λ` killed by all the `eᵢ` generates an irreducible
  submodule.
* `Matrix.Realization.KacMoodyAlgebra.IsStandardForm.lieSpan_primitive_eq_top`: an integrable
  module in `𝒪` is generated by such vectors.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.sSup_isAtom_eq_top`,
  `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.complementedLattice`: an integrable module in
  `𝒪` is the sum of its irreducible submodules, and every submodule has a complement.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.exists_sSupIndep_irreducibleModule`,
  `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.exists_isInternal_irreducibleModule`:
  **complete reducibility** ([Kac] Thm. 10.7 (b)): an integrable module in `𝒪` is the
  internal direct sum of submodules isomorphic to modules `L(Λ)`, `Λ` dominant integral.

## Proof

The argument is the standard one ([Kac] §10.7; cf. [Car] §19.2 for `Ω`); we reconstructed it
and wrote it out as follows. Call `v ∈ V_μ` *primitive* if `eᵢ v = 0` for all `i`, and write
`c(μ) = (μ + 2ρ | μ)`.

1. *Weight vectors in `ker (Ω - c(λ))ⁿ`.* Let `λ` be dominant integral and `y ∈ V_ν` with
   `ν - λ ∈ Q₊ \ {0}` and `(Ω - c(λ))ⁿ y = 0`. Then `y = 0`. By induction on `n` it suffices to
   treat `n = 1`. The submodule `Y = ker (Ω - c(λ))` lies in `𝒪`; if `y ≠ 0`, it has a nonzero
   primitive vector `w` of weight `μ ≥ ν` (`exists_lie_e_eq_zero_of_weightSpace_ne_bot`). Then `μ`
   is dominant integral by integrability, and `c(μ) w = Ω w = c(λ) w`, so `c(μ) = c(λ)`,
   contradicting `μ - λ ∈ Q₊ \ {0}`.
2. *Primitive vectors generate irreducible submodules.* Let `w ≠ 0` be primitive of weight `Λ`.
   Then `U = U(𝔤) w` is an integrable quotient of `M(Λ)`, hence irreducible
   (`IsStandardForm.eq_bot_or_eq_top_of_isIntegrable`, [Kac] Cor. 10.4).
3. *Irreducible submodules.* An irreducible submodule `N ⊆ V` contains a nonzero primitive vector
   `w` of some dominant integral weight `Λ`, so `N = U(𝔤) w` is the image of `φ : M(Λ) → V`. The
   kernel of `φ` is proper, hence contained in the maximal submodule `M'(Λ)`; and `φ(M'(Λ))` is a
   submodule of the irreducible `N` not containing `w`, hence zero. So `ker φ = M'(Λ)` and
   `N ≅ L(Λ)`.
4. *`V` is generated by its primitive vectors.* Let `V'` be the submodule generated by all primitive
   vectors, and suppose `V' ≠ V`. Then `V / V'` is a nonzero integrable module in `𝒪`, so it has a
   nonzero primitive vector `v̄` of some weight `λ`, dominant integral. Lift it to `v ∈ V_λ`. By
   naturality of `Ω`, `Ω v̄ = c(λ) v̄` gives `T v ∈ V'` where `T = Ω - c(λ)`. Now `T` preserves `V'`
   (it acts on each primitive vector of weight `μ` by `c(μ) - c(λ)`) and `V_λ`, hence the
   finite-dimensional space `W = V' ∩ V_λ`. The ranges of the powers of `T|_W` stabilize:
   `T^n W = T^{n+1} W` for some `n`. As `T v ∈ W`, `T^{n+1} v = T^n (T v) = T^{n+1} w` for some
   `w ∈ W`. Then `v₀ = v - w ∈ V_λ` is another lift of `v̄`, and `T^{n+1} v₀ = 0`. For each `i`,
   `eᵢ v₀ ∈ V_{λ + αᵢ}` and `T^{n+1} (eᵢ v₀) = eᵢ T^{n+1} v₀ = 0`, so `eᵢ v₀ = 0` by step 1. Thus
   `v₀` is primitive, so `v₀ ∈ V'`, contradicting `v̄ ≠ 0`.
5. *Conclusion.* By steps 2 and 4, `V` is the sum of its irreducible submodules. In the modular,
   compactly generated lattice of Lie submodules, a sum of atoms is the direct sum of an
   independent subfamily (`exists_sSupIndep_of_sSup_atoms_eq_top`); by step 3 each summand is
   isomorphic to some `L(Λ)`, `Λ` dominant integral.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §2.5, §9.3, §10.4,
  §10.7.
* [Car] R. W. Carter, *Lie algebras of finite and affine type*, CUP 2005, Ch. 19.
-/

open Module LieModule

noncomputable section

namespace Matrix.Realization.KacMoodyAlgebra

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} {P : Realization A K H}
  {V : Type*} [AddCommGroup V] [Module K V] [LieRingModule P.KacMoodyAlgebra V]
  [LieModule K P.KacMoodyAlgebra V]

/-! ### Submodules and quotients of modules in `𝒪` -/

/-- A Lie submodule of an integrable module in `𝒪` is integrable. -/
theorem IsIntegrable.lieSubmodule (hI : IsIntegrable P V) (hV : IsCategoryO P V)
    (N : LieSubmodule K P.KacMoodyAlgebra V) : IsIntegrable P N where
  isHDiagonalizable := (hV.lieSubmodule N).iSup_weightSpaceOfMap_eq_top
  exists_pow_e_eq_zero i x := by
    obtain ⟨n, hn⟩ := hI.exists_pow_e_eq_zero i x
    exact ⟨n, N.injective_incl (by rw [← toEnd_pow_apply_map, map_zero]; exact hn)⟩
  exists_pow_f_eq_zero i x := by
    obtain ⟨n, hn⟩ := hI.exists_pow_f_eq_zero i x
    exact ⟨n, N.injective_incl (by rw [← toEnd_pow_apply_map, map_zero]; exact hn)⟩

section Quotient

variable {N : LieSubmodule K P.KacMoodyAlgebra V}

/-- A quotient of an integrable module is integrable. -/
theorem IsIntegrable.quotient (hV : IsIntegrable P V) : IsIntegrable P (V ⧸ N) where
  isHDiagonalizable := by
    have hV' : ⨆ μ, weightSpace P V μ = ⊤ := hV.isHDiagonalizable
    simp only [IsHDiagonalizable, ← map_weightSpaceOfMap_quotient P N hV']
    rw [← Submodule.map_iSup, hV', Submodule.map_top, LinearMap.range_eq_top]
    exact LieSubmodule.Quotient.surjective_mk' N
  exists_pow_e_eq_zero i x := by
    obtain ⟨v, rfl⟩ := LieSubmodule.Quotient.surjective_mk' N x
    obtain ⟨n, hn⟩ := hV.exists_pow_e_eq_zero i v
    exact ⟨n, by rw [toEnd_pow_apply_map, hn, map_zero]⟩
  exists_pow_f_eq_zero i x := by
    obtain ⟨v, rfl⟩ := LieSubmodule.Quotient.surjective_mk' N x
    obtain ⟨n, hn⟩ := hV.exists_pow_f_eq_zero i v
    exact ⟨n, by rw [toEnd_pow_apply_map, hn, map_zero]⟩

end Quotient

/-! ### Irreducible submodules -/

variable [CharZero K] (hA : A.IsGeneralizedCartan)

namespace IsCategoryO

include hA in
/-- An irreducible submodule of an integrable module in `𝒪` is isomorphic to `L(Λ)` for some
dominant integral weight `Λ` ([Kac] Prop. 9.3 (b), Lemma 10.1). -/
theorem exists_equiv_irreducibleModule_of_isAtom (hV : IsCategoryO P V) (hI : IsIntegrable P V)
    {N : LieSubmodule K P.KacMoodyAlgebra V} (hN : IsAtom N) :
    ∃ Λ, P.IsDominantIntegral Λ ∧
      Nonempty (N ≃ₗ⁅K,P.KacMoodyAlgebra⁆ IrreducibleModule P Λ) := by
  have : Nontrivial N := (LieSubmodule.nontrivial_iff_ne_bot K _ V).mpr hN.1
  obtain ⟨Λ, x, hx, hx0, hxe⟩ := (hV.lieSubmodule N).exists_lie_e_eq_zero
  set w : V := (x : V)
  have hw : w ∈ weightSpace P V Λ := mem_weightSpaceOfMap_lieSubmodule_iff.mp hx
  have hwe : ∀ i, ⁅e P i, w⁆ = 0 := fun i ↦ by
    simp only [w, ← LieSubmodule.coe_bracket, hxe i, LieSubmodule.coe_zero]
  have hw0 : w ≠ 0 := fun h ↦ hx0 (Subtype.ext h)
  refine ⟨Λ, isDominantIntegral_of_isIntegrable hA hI hw hwe hw0, ?_⟩
  let φ := VermaModule.lift P w (fun _ hy ↦ lie_eq_zero_of_mem_nPos hwe hy) (fun a ↦ hw a)
  have hφv : φ (VermaModule.hwv P Λ) = w := VermaModule.lift_hwv P w _ _
  have hrange : φ.range = N := by
    rw [VermaModule.range_eq_lieSpan, hφv]
    refine (hN.le_iff.mp (LieSubmodule.lieSpan_le.mpr ?_)).resolve_left ?_
    · rintro _ rfl; exact x.2
    · rw [LieSubmodule.lieSpan_eq_bot_iff]
      exact fun h ↦ hw0 (h w rfl)
  have hker_le : φ.ker ≤ VermaModule.maxSubmodule P Λ :=
    (VermaModule.le_maxSubmodule_iff P Λ _).mpr fun htop ↦ hw0 (by
      rw [← hφv, ← LieModuleHom.mem_ker, htop]; trivial)
  have hle_ker : VermaModule.maxSubmodule P Λ ≤ φ.ker := by
    rw [LieModuleHom.le_ker_iff_map]
    have hle : (VermaModule.maxSubmodule P Λ).map φ ≤ N := by
      rw [← hrange, ← LieModuleHom.map_top]
      exact LieSubmodule.map_mono le_top
    refine (hN.le_iff.mp hle).resolve_right fun heq ↦ ?_
    have hwmem : w ∈ (VermaModule.maxSubmodule P Λ).map φ := heq ▸ x.2
    obtain ⟨m, hm, hmw⟩ := (LieSubmodule.mem_map w).mp hwmem
    apply VermaModule.hwv_notMem_maxSubmodule P Λ
    have hdiff : m - VermaModule.hwv P Λ ∈ VermaModule.maxSubmodule P Λ :=
      hker_le (by rw [LieModuleHom.mem_ker, map_sub, hmw, hφv, sub_self])
    simpa using sub_mem hm hdiff
  -- the induced injective map `L(Λ) → V`, with image `N`
  let ψ := LieSubmodule.Quotient.lift _ φ hle_ker
  have hψN : ∀ q, ψ q ∈ N := fun q ↦ by
    obtain ⟨m, rfl⟩ := LieSubmodule.Quotient.surjective_mk' _ q
    rw [← hrange]
    exact (LieModuleHom.mem_range φ _).mpr ⟨m, rfl⟩
  let ψ' := LieModuleHom.codRestrict N ψ hψN
  have hψ' : Function.Bijective ψ' := by
    refine ⟨(injective_iff_map_eq_zero ψ').mpr fun q hq ↦ ?_, fun y ↦ ?_⟩
    · obtain ⟨m, rfl⟩ := LieSubmodule.Quotient.surjective_mk' _ q
      rw [LieSubmodule.Quotient.mk_eq_zero]
      refine hker_le ?_
      rw [LieModuleHom.mem_ker]
      exact congrArg Subtype.val hq
    · have hy : (y : V) ∈ φ.range := by rw [hrange]; exact y.2
      obtain ⟨m, hm⟩ := (LieModuleHom.mem_range φ _).mp hy
      exact ⟨LieSubmodule.Quotient.mk' _ m, Subtype.ext hm⟩
  exact ⟨(LieModuleEquiv.ofBijective ψ' hψ').symm⟩

end IsCategoryO

/-! ### The Casimir operator as a morphism of modules -/

variable [FiniteDimensional K H] {S : A.Symmetrization}
  {B : LinearMap.BilinForm K P.KacMoodyAlgebra}

namespace IsStandardForm

variable (hB : IsStandardForm P S B)
include hB

/-- The Casimir operator is natural: it commutes with morphisms of `𝔤(A)`-modules. -/
theorem map_casimir {W : Type*} [AddCommGroup W] [Module K W] [LieRingModule P.KacMoodyAlgebra W]
    [LieModule K P.KacMoodyAlgebra W] (f : V →ₗ⁅K,P.KacMoodyAlgebra⁆ W) (hV : IsPosFinite P V)
    (hW : IsPosFinite P W) (v : V) : f (hB.casimir V hV v) = hB.casimir W hW (f v) := by
  have hterm (μ : Dual K H) : f (hB.casimirTerm V μ v) = hB.casimirTerm W μ (f v) := by
    simp only [casimirTerm_apply, casimirSum_def, map_sum, LieModuleHom.map_lie]
  rw [casimir_apply, casimir_apply, map_add, map_add, map_smul, map_smul, LieModuleHom.map_lie,
    hterm]
  congr 2
  have := (f : V →ₗ[K] W).toAddMonoidHom.map_finsum_mem' (hB.finite_casimirTerm hV v)
  simp only [LinearMap.toAddMonoidHom_coe, LieModuleHom.coe_toLinearMap] at this
  rw [this]
  exact finsum_mem_congr rfl fun μ _ ↦ hterm μ

/-- The Casimir operator as a morphism of `𝔤(A)`-modules ([Kac] Thm. 2.6). -/
def casimirHom (hV : IsPosFinite P V) : V →ₗ⁅K,P.KacMoodyAlgebra⁆ V :=
  { hB.casimir V hV with map_lie' := fun {x v} ↦ hB.casimir_lie hA hV x v }

@[simp] lemma casimirHom_apply (hV : IsPosFinite P V) (v : V) :
    hB.casimirHom hA hV v = hB.casimir V hV v :=
  rfl

/-- If `v ∈ V_μ` and `eᵢ v ∈ N` for all `i`, then `Ω v - (μ + 2ρ | μ) v ∈ N`: the Casimir
operator acts by `(μ + 2ρ | μ)` on the image of `v` in `V / N` ([Kac] Cor. 2.6). -/
theorem casimir_sub_smul_mem (hV : IsCategoryO P V) (N : LieSubmodule K P.KacMoodyAlgebra V)
    {μ : Dual K H} {v : V} (hv : v ∈ weightSpace P V μ) (he : ∀ i, ⁅e P i, v⁆ ∈ N) :
    hB.casimir V hV.isPosFinite v - P.dualBilinForm S (μ + 2 • P.rho) μ • v ∈ N := by
  rw [← LieSubmodule.Quotient.mk_eq_zero, map_sub, map_smul,
    hB.map_casimir _ hV.isPosFinite (hV.quotient N).isPosFinite,
    hB.casimir_apply_of_lie_e_eq_zero _ (map_mem_weightSpaceOfMap P _ hv) fun i ↦ by
      rw [← LieModuleHom.map_lie, (LieSubmodule.Quotient.mk_eq_zero _).mpr (he i)],
    sub_self]

/-! ### Complete reducibility -/

variable (hV : IsCategoryO P V) (hI : IsIntegrable P V)
include hA hV hI

/-- Step 1 of the proof of complete reducibility: if `λ` is dominant integral and `y` is a weight
vector of weight `λ + β`, `β ∈ Q₊ \ {0}`, with `(Ω - (λ + 2ρ | λ))ⁿ y = 0`, then `y = 0`. -/
theorem eq_zero_of_pow_apply_eq_zero {μ : Dual K H} (hμ : P.IsDominantIntegral μ) {k : ι → ℤ}
    (hk : k ∈ posCone ι) {y : V} (hy : y ∈ weightSpace P V (μ + P.rootOf k)) {n : ℕ}
    (hn : (((hB.casimirHom hA hV.isPosFinite - P.dualBilinForm S (μ + 2 • P.rho) μ •
      LieModuleHom.id : V →ₗ⁅K,P.KacMoodyAlgebra⁆ V) : Module.End K V) ^ n) y = 0) :
    y = 0 := by
  set T : V →ₗ⁅K,P.KacMoodyAlgebra⁆ V := hB.casimirHom hA hV.isPosFinite -
    P.dualBilinForm S (μ + 2 • P.rho) μ • LieModuleHom.id with hT
  induction n generalizing y with
  | zero => simpa using hn
  | succ n ih =>
    rw [pow_succ, Module.End.mul_apply] at hn
    have hTy : T y = 0 := ih (map_mem_weightSpaceOfMap P T hy) hn
    by_contra hy0
    have hne : weightSpace P T.ker (μ + P.rootOf k) ≠ ⊥ := fun hbot ↦
      hy0 (congrArg Subtype.val ((Submodule.eq_bot_iff _).mp hbot ⟨y, hTy⟩
        (mem_weightSpaceOfMap_lieSubmodule_iff.mpr hy)))
    obtain ⟨l, hl, w, hw, hw0, hwe⟩ :=
      (hV.lieSubmodule T.ker).exists_lie_e_eq_zero_of_weightSpace_ne_bot hne
    have hw' := mem_weightSpaceOfMap_lieSubmodule_iff.mp hw
    have hwe' : ∀ i, ⁅e P i, (w : V)⁆ = 0 := fun i ↦ by
      rw [← LieSubmodule.coe_bracket, hwe i, LieSubmodule.coe_zero]
    have hw0' : (w : V) ≠ 0 := fun h ↦ hw0 (Subtype.ext h)
    have hdom := isDominantIntegral_of_isIntegrable hA hI hw' hwe' hw0'
    have h2 : hB.casimir V hV.isPosFinite w - P.dualBilinForm S (μ + 2 • P.rho) μ • (w : V) = 0 :=
      w.2
    rw [hB.casimir_apply_of_lie_e_eq_zero _ hw' hwe', ← sub_smul, smul_eq_zero] at h2
    refine dualBilinForm_add_two_rho_ne S hdom hμ (k := k + l) ⟨add_nonneg hk.1 hl,
      fun h0 ↦ hk.2 ?_⟩ ?_ (sub_eq_zero.mp (h2.resolve_right hw0'))
    · ext j
      have h1 := congrFun h0 j
      have h2 := hk.1 j
      have h3 := hl j
      simp only [Pi.add_apply, Pi.zero_apply] at h1 h2 h3 ⊢
      omega
    · rw [map_add, add_assoc]

/-- Step 2 of the proof of complete reducibility: in an integrable module in `𝒪`, a nonzero vector
of weight `Λ` killed by all the `eᵢ` generates an irreducible submodule. -/
theorem isAtom_lieSpan_singleton {Λ : Dual K H} {w : V} (hw : w ∈ weightSpace P V Λ)
    (he : ∀ i, ⁅e P i, w⁆ = 0) (hw0 : w ≠ 0) :
    IsAtom (LieSubmodule.lieSpan K P.KacMoodyAlgebra {w}) := by
  set U := LieSubmodule.lieSpan K P.KacMoodyAlgebra {w}
  let φ := VermaModule.lift P w (fun _ hy ↦ lie_eq_zero_of_mem_nPos he hy) (fun a ↦ hw a)
  have hrange : φ.range = U := by
    rw [VermaModule.range_eq_lieSpan, VermaModule.lift_hwv]
  have hφU : ∀ m, φ m ∈ U := fun m ↦ by
    rw [← hrange]; exact (LieModuleHom.mem_range φ _).mpr ⟨m, rfl⟩
  let φ' := LieModuleHom.codRestrict U φ hφU
  have hφ' : Function.Surjective φ' := fun y ↦ by
    have hy : (y : V) ∈ φ.range := by rw [hrange]; exact y.2
    obtain ⟨m, hm⟩ := (LieModuleHom.mem_range φ _).mp hy
    exact ⟨m, Subtype.ext hm⟩
  refine ⟨fun h ↦ hw0 (by rw [LieSubmodule.lieSpan_eq_bot_iff] at h; exact h w rfl),
    fun N hN ↦ ?_⟩
  rcases hB.eq_bot_or_eq_top_of_isIntegrable hA φ' hφ' (hI.lieSubmodule hV U)
    (N.comap U.incl) with h | h
  · rw [LieSubmodule.comap_incl_eq_bot] at h
    rw [eq_bot_iff, ← h]
    exact le_inf hN.le le_rfl
  · rw [LieSubmodule.comap_incl_eq_top] at h
    exact absurd h hN.not_ge

/-- Step 4 of the proof of complete reducibility: an integrable module in `𝒪` is generated by its
weight vectors killed by all the `eᵢ`. -/
theorem lieSpan_primitive_eq_top :
    LieSubmodule.lieSpan K P.KacMoodyAlgebra
      {v : V | ∃ μ, v ∈ weightSpace P V μ ∧ ∀ i, ⁅e P i, v⁆ = 0} = ⊤ := by
  set V' := LieSubmodule.lieSpan K P.KacMoodyAlgebra
      {v : V | ∃ μ, v ∈ weightSpace P V μ ∧ ∀ i, ⁅e P i, v⁆ = 0} with hV'
  by_contra hne
  obtain ⟨x, -, hx⟩ := SetLike.exists_of_lt (lt_top_iff_ne_top.mpr hne)
  have : Nontrivial (V ⧸ V') := ⟨⟨LieSubmodule.Quotient.mk' V' x, 0, by
    rwa [Ne, LieSubmodule.Quotient.mk_eq_zero]⟩⟩
  -- a primitive vector `v̄ ≠ 0` of `V / V'`, of dominant integral weight `μ`
  obtain ⟨μ, v', hv', hv'0, hv'e⟩ := (hV.quotient V').exists_lie_e_eq_zero
  have hμ := isDominantIntegral_of_isIntegrable hA (hI.quotient (N := V')) hv' hv'e hv'0
  change v' ∈ weightSpaceOfMap (V ⧸ V') (h P) μ at hv'
  rw [← map_weightSpaceOfMap_quotient P V' hV.iSup_weightSpaceOfMap_eq_top] at hv'
  obtain ⟨v, hv, rfl⟩ := hv'
  simp only [LieModuleHom.coe_toLinearMap] at hv'0 hv'e
  have hve : ∀ i, ⁅e P i, v⁆ ∈ V' := fun i ↦ by
    rw [← LieSubmodule.Quotient.mk_eq_zero, LieModuleHom.map_lie]
    exact hv'e i
  set T : V →ₗ⁅K,P.KacMoodyAlgebra⁆ V := hB.casimirHom hA hV.isPosFinite -
    P.dualBilinForm S (μ + 2 • P.rho) μ • LieModuleHom.id with hT
  have hTv : T v ∈ V' := hB.casimir_sub_smul_mem hV V' hv hve
  -- `T` preserves `V'`
  have hTV' : ∀ y ∈ V', T y ∈ V' := by
    intro y hy
    have : V' ≤ V'.comap T := by
      rw [LieSubmodule.lieSpan_le]
      rintro z ⟨ν, hz, hze⟩
      change hB.casimir V hV.isPosFinite z - P.dualBilinForm S (μ + 2 • P.rho) μ • z ∈ V'
      rw [hB.casimir_apply_of_lie_e_eq_zero _ hz hze, ← sub_smul]
      exact V'.smul_mem _ (LieSubmodule.subset_lieSpan ⟨ν, hz, hze⟩)
    exact this hy
  -- the finite-dimensional space `W = V' ∩ V_μ`, stable under `T`
  set W : Submodule K V := V'.toSubmodule ⊓ weightSpace P V μ with hW
  have hTW : ∀ y ∈ W, (T : Module.End K V) y ∈ W := fun y hy ↦
    ⟨hTV' y hy.1, map_mem_weightSpaceOfMap P T hy.2⟩
  have : FiniteDimensional K W := by
    have := hV.finiteDimensional_weightSpaceOfMap μ
    exact Submodule.finiteDimensional_of_le inf_le_right
  have hpow : ∀ m (y : W), ((((T : Module.End K V).restrict hTW ^ m) y : W) : V) =
      ((T : Module.End K V) ^ m) y := fun m y ↦ by
    rw [Module.End.pow_restrict, LinearMap.coe_restrict_apply]
  obtain ⟨n, hn⟩ := IsArtinian.monotone_stabilizes ((T : Module.End K V).restrict hTW).iterateRange
  have hrange : LinearMap.range ((T : Module.End K V).restrict hTW ^ n) =
      LinearMap.range ((T : Module.End K V).restrict hTW ^ (n + 1)) := hn (n + 1) n.le_succ
  have hTvW : (T : Module.End K V) v ∈ W := ⟨hTv, map_mem_weightSpaceOfMap P T hv⟩
  have hmem : ((T : Module.End K V).restrict hTW ^ n) ⟨_, hTvW⟩ ∈
      LinearMap.range ((T : Module.End K V).restrict hTW ^ (n + 1)) := by
    rw [← hrange]; exact LinearMap.mem_range_self _ _
  obtain ⟨w, hw⟩ := hmem
  have hw' : ((T : Module.End K V) ^ (n + 1)) (w : V) = ((T : Module.End K V) ^ (n + 1)) v := by
    have := congrArg Subtype.val hw
    rw [hpow, hpow] at this
    rw [this, pow_succ, Module.End.mul_apply]
  -- the lift `v₀ = v - w` of `v̄` is killed by `T^(n+1)`, hence primitive
  have hv₀μ : v - (w : V) ∈ weightSpace P V μ := sub_mem hv w.2.2
  have hv₀T : ((T : Module.End K V) ^ (n + 1)) (v - (w : V)) = 0 := by
    rw [map_sub, hw', sub_self]
  have hv₀e : ∀ i, ⁅e P i, v - (w : V)⁆ = 0 := by
    intro i
    have hy : ⁅e P i, v - (w : V)⁆ ∈ weightSpace P V (μ + P.rootOf (Pi.single i 1)) := by
      rw [rootOf_single]
      exact toEnd_e_mem_weightSpace i hv₀μ
    refine hB.eq_zero_of_pow_apply_eq_zero hA hV hI hμ
      ⟨Pi.single_nonneg.mpr zero_le_one, fun h ↦ by simpa using congrFun h i⟩ hy
      (n := n + 1) ?_
    have hcomm : Commute (T : Module.End K V) (toEnd K P.KacMoodyAlgebra V (e P i)) :=
      LinearMap.ext fun z ↦ T.map_lie (e P i) z
    rw [← toEnd_apply_apply (R := K), ← Module.End.mul_apply, (hcomm.pow_left (n + 1)).eq,
      Module.End.mul_apply, hv₀T, map_zero]
  apply hv'0
  rw [LieSubmodule.Quotient.mk_eq_zero]
  have := add_mem (LieSubmodule.subset_lieSpan ⟨μ, hv₀μ, hv₀e⟩ : v - (w : V) ∈ V') w.2.1
  rwa [sub_add_cancel] at this

end IsStandardForm

namespace IsCategoryO

variable (hS : A.IsSymmetrizable) (hV : IsCategoryO P V) (hI : IsIntegrable P V)
include hS hA hV hI

/-- An integrable module in `𝒪` is the sum of its irreducible submodules, for `A` symmetrizable
([Kac] Thm. 10.7). -/
theorem sSup_isAtom_eq_top : sSup {N : LieSubmodule K P.KacMoodyAlgebra V | IsAtom N} = ⊤ := by
  have hB := isStandardForm_invForm P (isSymmetrizable_iff_nonempty_symmetrization.mp hS).some
  rw [eq_top_iff, ← hB.lieSpan_primitive_eq_top hA hV hI, LieSubmodule.lieSpan_le]
  rintro w ⟨μ, hw, he⟩
  by_cases hw0 : w = 0
  · rw [hw0]; exact zero_mem _
  · exact (le_sSup (hB.isAtom_lieSpan_singleton hA hV hI hw he hw0) :
      _ ≤ sSup {N : LieSubmodule K P.KacMoodyAlgebra V | IsAtom N})
      (LieSubmodule.subset_lieSpan rfl)

/-- Every submodule of an integrable module in `𝒪` has a complement, for `A` symmetrizable
([Kac] Thm. 10.7). -/
theorem complementedLattice : ComplementedLattice (LieSubmodule K P.KacMoodyAlgebra V) :=
  complementedLattice_of_sSup_atoms_eq_top (sSup_isAtom_eq_top hA hS hV hI)

/-- **Complete reducibility** ([Kac] Thm. 10.7 (b)): for `A` a symmetrizable generalized
Cartan matrix and `K` of characteristic zero, an integrable `𝔤(A)`-module in `𝒪` is the direct sum
of an independent family of submodules, each isomorphic to `L(Λ)` for some dominant integral
`Λ`. -/
theorem exists_sSupIndep_irreducibleModule :
    ∃ s : Set (LieSubmodule K P.KacMoodyAlgebra V), sSupIndep s ∧ sSup s = ⊤ ∧
      ∀ N ∈ s, ∃ Λ, P.IsDominantIntegral Λ ∧
        Nonempty (N ≃ₗ⁅K,P.KacMoodyAlgebra⁆ IrreducibleModule P Λ) := by
  obtain ⟨s, hs, htop, hatom⟩ :=
    exists_sSupIndep_of_sSup_atoms_eq_top (sSup_isAtom_eq_top hA hS hV hI)
  exact ⟨s, hs, htop, fun N hN ↦ exists_equiv_irreducibleModule_of_isAtom hA hV hI (hatom hN)⟩

open scoped Classical in
/-- **Complete reducibility** ([Kac] Thm. 10.7 (b)): for `A` a symmetrizable generalized
Cartan matrix and `K` of characteristic zero, an integrable `𝔤(A)`-module `V` in `𝒪` is the
internal direct sum of a family of submodules, each isomorphic to `L(Λ)` for some dominant
integral `Λ`. -/
theorem exists_isInternal_irreducibleModule :
    ∃ s : Set (LieSubmodule K P.KacMoodyAlgebra V),
      DirectSum.IsInternal (fun N : s ↦ (N : Submodule K V)) ∧
      ∀ N ∈ s, ∃ Λ, P.IsDominantIntegral Λ ∧
        Nonempty (N ≃ₗ⁅K,P.KacMoodyAlgebra⁆ IrreducibleModule P Λ) := by
  obtain ⟨s, hs, htop, hN⟩ := exists_sSupIndep_irreducibleModule hA hS hV hI
  refine ⟨s, DirectSum.isInternal_submodule_of_iSupIndep_of_iSup_eq_top
    (LieSubmodule.iSupIndep_toSubmodule.mpr ((sSupIndep_iff s).mp hs)) ?_, hN⟩
  rw [LieSubmodule.iSup_toSubmodule_eq_top, ← sSup_eq_iSup']
  exact htop

end IsCategoryO

end Matrix.Realization.KacMoodyAlgebra
