/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.CasimirEigenvalue
import LieLean.Algebra.Lie.KacMoody.HighestWeightVector

/-!
# Complete reducibility of integrable modules in the category `𝒪`

Let `A` be a symmetrizable generalized Cartan matrix and `K` a field of characteristic zero. We
show that every integrable `𝔤(A)`-module `V` in the category `𝒪` is a direct sum of irreducible
modules `L(Λ)` with `Λ` dominant integral ([Kac] Thm. 10.7 (b) (check)).

The proof uses a generalized Casimir operator on `V` ([Kac] §2.5). To keep this file independent
of the construction of that operator, we work with an *abstract* Casimir operator: a morphism of
`𝔤(A)`-modules `Ω : V → V` together with a function `c : 𝔥* → K` such that

* (`hΩ`) for every Lie submodule `N ⊆ V`, every weight `μ` and every `v ∈ V_μ` with `eᵢ v ∈ N` for
  all `i`, one has `Ω v - c(μ) v ∈ N`; i.e. `Ω` acts by `c(μ)` on the image of `v` in `V / N`
  whenever that image is a highest-weight vector;
* (`hc`) `c(Λ) ≠ c(μ)` whenever `Λ, μ` are dominant integral and `Λ - μ ∈ Q₊ \ {0}`.

For the Casimir operator of [Kac] §2.5 one has `c(μ) = (μ + 2ρ | μ)` ([Kac] Cor. 2.6 (check));
indeed `Ω v = (μ + 2ρ | μ) v + 2 Σ_{α > 0} Σ_j e_{-α}^{(j)} e_α^{(j)} v` for `v ∈ V_μ`, and
`e_α^{(j)} v ∈ N` as soon as all `eᵢ v ∈ N`. Property `hc` for this `c` is
`Matrix.Realization.dualBilinForm_add_two_smul_ne`. The final result, with `c(μ) = (μ + 2ρ | μ)`,
is `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.exists_isInternal_irreducibleModule`.

## Main definitions

* `LieModuleEquiv.ofBijective`: a bijective morphism of Lie modules is an equivalence.

## Main results

* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.lieSubmodule`,
  `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.quotient`,
  `Matrix.Realization.KacMoodyAlgebra.IsIntegrable.quotient`: submodules and quotients of modules
  in `𝒪` lie in `𝒪`; quotients of integrable modules are integrable.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.exists_equiv_irreducibleModule_of_isAtom`: an
  irreducible submodule of an integrable module in `𝒪` is isomorphic to `L(Λ)` for some dominant
  integral `Λ`.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.eq_zero_of_pow_apply_eq_zero`: given `Ω`, for
  `λ` dominant integral, `(Ω - c(λ))ⁿ` is injective on the weight spaces `V_{λ + β}`,
  `β ∈ Q₊ \ {0}`.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.isAtom_lieSpan_singleton`: given `Ω`, a nonzero
  highest-weight vector generates an irreducible submodule.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.lieSpan_primitive_eq_top`: given `Ω`, `V` is
  generated by its highest-weight vectors.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.sSup_isAtom_eq_top`,
  `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.complementedLattice_of_casimir`: given `Ω`, `V`
  is the sum of its irreducible submodules, and every submodule has a complement.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.exists_sSupIndep_of_casimir`: given `Ω`, `V` is
  the direct sum of an independent family of submodules, each isomorphic to some `L(Λ)` with `Λ`
  dominant integral.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.exists_isInternal_irreducibleModule`:
  **complete reducibility** ([Kac] Thm. 10.7 (b) (check)), for `A` symmetrizable, assuming a
  Casimir operator acting on highest-weight vectors of weight `μ` by `(μ + 2ρ | μ)`.

## Proof

The argument follows the standard proof ([Kac] §10.7, (check); [Car] Ch. 19 (check)); we
reconstructed it and wrote it out as follows. Call `v ∈ V_μ` *primitive* if `eᵢ v = 0` for all `i`.

1. *Weight vectors in `ker (Ω - c(λ))ⁿ`.* Let `λ` be dominant integral and `y ∈ V_ν` with
   `ν - λ ∈ Q₊ \ {0}` and `(Ω - c(λ))ⁿ y = 0`. Then `y = 0`. By induction on `n` it suffices to
   treat `n = 1`. The submodule `Y = ker (Ω - c(λ))` lies in `𝒪`; if `y ≠ 0`, it has a nonzero
   primitive vector `w` of weight `μ ≥ ν` (`exists_lie_e_eq_zero_of_weightSpace_ne_bot`). Then `μ`
   is dominant integral by integrability, and `c(μ) w = Ω w = c(λ) w`, so `c(μ) = c(λ)`,
   contradicting `hc` as `μ - λ ∈ Q₊ \ {0}`.
2. *Primitive vectors generate irreducible submodules.* Let `w ≠ 0` be primitive of weight `Λ` and
   `U = U(𝔤) w`, the image of `M(Λ) → V`, `v_Λ ↦ w`. Then `Ω = c(Λ)` on `U`. A nonzero
   submodule `N ⊆ U` lies in `𝒪`, hence has a nonzero primitive vector `x` of some weight `μ`.
   Since `x ∈ U`, `μ = Λ - β` with `β ∈ Q₊`, and `μ` is dominant integral; `c(μ) x = Ω x = c(Λ) x`
   forces `β = 0` by `hc`. As `U_Λ = K w`, `x` is a nonzero multiple of `w`, so `N = U`.
3. *Irreducible submodules.* An irreducible submodule `N ⊆ V` contains a nonzero primitive vector
   `w` of some dominant integral weight `Λ`, so `N = U(𝔤) w` is the image of `φ : M(Λ) → V`. The
   kernel of `φ` is proper, hence contained in the maximal submodule `M'(Λ)`; and `φ(M'(Λ))` is a
   submodule of the irreducible `N` not containing `w`, hence zero. So `ker φ = M'(Λ)` and
   `N ≅ L(Λ)`.
4. *`V` is generated by its primitive vectors.* Let `V'` be the submodule generated by all primitive
   vectors, and suppose `V' ≠ V`. Then `V / V'` is a nonzero integrable module in `𝒪`, so it has a
   nonzero primitive vector `v̄` of some weight `λ`, dominant integral. Lift it to `v ∈ V_λ`; then
   `eᵢ v ∈ V'`, so `T v ∈ V'` where `T = Ω - c(λ)`, by `hΩ`. Now `T` preserves `V'` (it acts on
   each primitive vector of weight `μ` by `c(μ) - c(λ)`) and `V_λ`, hence the finite-dimensional
   space `W = V' ∩ V_λ`. The ranges of the powers of `T|_W` stabilize: `T^n W = T^{n+1} W` for some
   `n`. As `T v ∈ W`, `T^{n+1} v = T^n (T v) = T^{n+1} w` for some `w ∈ W`. Then `v₀ = v - w ∈ V_λ`
   is another lift of `v̄`, and `T^{n+1} v₀ = 0`. For each `i`, `eᵢ v₀ ∈ V_{λ + αᵢ}` and
   `T^{n+1} (eᵢ v₀) = eᵢ T^{n+1} v₀ = 0`, so `eᵢ v₀ = 0` by step 1. Thus `v₀` is primitive, so
   `v₀ ∈ V'`, contradicting `v̄ ≠ 0`.
5. *Conclusion.* By steps 2 and 4, `V` is the sum of its irreducible submodules. In the modular,
   compactly generated lattice of Lie submodules, a sum of atoms is the direct sum of an
   independent subfamily (`exists_sSupIndep_of_sSup_atoms_eq_top`); by step 3 each summand is
   isomorphic to some `L(Λ)`, `Λ` dominant integral.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §2.5, §9.3, §10.7.
* [Car] R. W. Carter, *Lie algebras of finite and affine type*, CUP 2005, Ch. 19.
-/

open Module LieModule

noncomputable section

/-! ### Bijective morphisms of Lie modules -/

namespace LieModuleEquiv

variable {R L M N : Type*} [CommRing R] [LieRing L] [AddCommGroup M]
  [Module R M] [LieRingModule L M] [AddCommGroup N] [Module R N] [LieRingModule L N]

/-- A bijective morphism of Lie modules is an equivalence of Lie modules. -/
def ofBijective (f : M →ₗ⁅R,L⁆ N) (hf : Function.Bijective f) : M ≃ₗ⁅R,L⁆ N :=
  { f, LinearEquiv.ofBijective (f : M →ₗ[R] N) hf with }

@[simp] lemma ofBijective_apply (f : M →ₗ⁅R,L⁆ N) (hf : Function.Bijective f) (m : M) :
    ofBijective f hf m = f m :=
  rfl

end LieModuleEquiv

namespace Matrix.Realization.KacMoodyAlgebra

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} {P : Realization A K H}
  {V : Type*} [AddCommGroup V] [Module K V] [LieRingModule P.KacMoodyAlgebra V]
  [LieModule K P.KacMoodyAlgebra V]

/-! ### Submodules and quotients of modules in `𝒪` -/

section Submodule

variable (N : LieSubmodule K P.KacMoodyAlgebra V)

lemma mem_weightSpace_lieSubmodule {μ : Dual K H} {x : N} :
    x ∈ weightSpace P N μ ↔ (x : V) ∈ weightSpace P V μ := by
  simp only [mem_weightSpaceOfMap, Subtype.ext_iff, LieSubmodule.coe_bracket,
    LieSubmodule.coe_smul]

/-- The weight spaces of a Lie submodule `N ⊆ V` are the intersections `N ∩ V_μ`. -/
lemma map_weightSpace_lieSubmodule (μ : Dual K H) :
    (weightSpace P N μ).map (N.incl : N →ₗ[K] V) = N.toSubmodule ⊓ weightSpace P V μ := by
  ext x
  simp only [Submodule.mem_map, Submodule.mem_inf, LieSubmodule.mem_toSubmodule]
  constructor
  · rintro ⟨y, hy, rfl⟩
    exact ⟨y.2, (mem_weightSpace_lieSubmodule N).mp hy⟩
  · rintro ⟨hxN, hx⟩
    exact ⟨⟨x, hxN⟩, (mem_weightSpace_lieSubmodule N).mpr hx, rfl⟩

variable {N}

/-- A Lie submodule of a module in `𝒪` lies in `𝒪`. -/
theorem IsCategoryO.lieSubmodule (hV : IsCategoryO P V) : IsCategoryO P N where
  iSup_weightSpaceOfMap_eq_top := by
    rw [eq_top_iff]
    rintro x -
    have hx : (x : V) ∈ N.toSubmodule ⊓ ⨆ μ ∈ Set.univ, weightSpace P V μ := by
      refine ⟨x.2, ?_⟩
      simp only [Set.mem_univ, iSup_pos]
      rw [hV.iSup_weightSpaceOfMap_eq_top]
      trivial
    have := inf_iSup_weightSpaceOfMap_le (h P) N.toSubmodule (fun _ _ hm ↦ N.lie_mem hm)
      Set.univ hx
    simp only [Set.mem_univ, iSup_pos, ← map_weightSpace_lieSubmodule, ← Submodule.map_iSup]
      at this
    obtain ⟨y, hy, hyx⟩ := Submodule.mem_map.mp this
    rwa [← Subtype.ext hyx]
  finiteDimensional_weightSpaceOfMap μ := by
    have := hV.finiteDimensional_weightSpaceOfMap μ
    have hle : (weightSpace P N μ).map (N.incl : N →ₗ[K] V) ≤ weightSpace P V μ := by
      rw [map_weightSpace_lieSubmodule]
      exact inf_le_right
    have := Submodule.finiteDimensional_of_le hle
    exact (Submodule.equivMapOfInjective (N.incl : N →ₗ[K] V) N.injective_incl
      (weightSpace P N μ)).symm.finiteDimensional
  exists_finset := by
    obtain ⟨s, hs⟩ := hV.exists_finset
    refine ⟨s, fun μ hμ ↦ hs μ fun hbot ↦ hμ (eq_bot_iff.mpr fun x hx ↦ ?_)⟩
    have := (mem_weightSpace_lieSubmodule N).mp hx
    rw [show weightSpace P V μ = ⊥ from hbot, Submodule.mem_bot] at this
    exact (Submodule.mem_bot K).mpr (Subtype.ext this)

end Submodule

section Quotient

variable (N : LieSubmodule K P.KacMoodyAlgebra V)

/-- If `V` is the sum of its weight spaces, the weight spaces of `V ⧸ N` are the images of those
of `V`. -/
lemma weightSpace_quotient_eq_map (hV : ⨆ μ, weightSpace P V μ = ⊤) (μ : Dual K H) :
    weightSpace P (V ⧸ N) μ =
      (weightSpace P V μ).map (LieSubmodule.Quotient.mk' N : V →ₗ[K] V ⧸ N) := by
  refine le_antisymm (fun x hx ↦ ?_) ?_
  · obtain ⟨v, rfl⟩ := LieSubmodule.Quotient.surjective_mk' N x
    have hv : v ∈ ⨆ ν, weightSpace P V ν := hV ▸ Submodule.mem_top
    have := Submodule.mem_map_of_mem (f := (LieSubmodule.Quotient.mk' N : V →ₗ[K] V ⧸ N)) hv
    rw [Submodule.map_iSup] at this
    refine mem_of_mem_iSup_of_le (h P) _ (fun ν ↦ ?_) hx this
    rintro _ ⟨y, hy, rfl⟩
    exact map_mem_weightSpaceOfMap P _ hy
  · rintro _ ⟨y, hy, rfl⟩
    exact map_mem_weightSpaceOfMap P _ hy

variable {N}

/-- A quotient of a module in `𝒪` lies in `𝒪`. -/
theorem IsCategoryO.quotient (hV : IsCategoryO P V) : IsCategoryO P (V ⧸ N) where
  iSup_weightSpaceOfMap_eq_top := by
    simp only [weightSpace_quotient_eq_map N hV.iSup_weightSpaceOfMap_eq_top]
    rw [← Submodule.map_iSup, hV.iSup_weightSpaceOfMap_eq_top, Submodule.map_top,
      LinearMap.range_eq_top]
    exact LieSubmodule.Quotient.surjective_mk' N
  finiteDimensional_weightSpaceOfMap μ := by
    have := hV.finiteDimensional_weightSpaceOfMap μ
    change FiniteDimensional K (weightSpace P (V ⧸ N) μ)
    rw [weightSpace_quotient_eq_map N hV.iSup_weightSpaceOfMap_eq_top]
    infer_instance
  exists_finset := by
    obtain ⟨s, hs⟩ := hV.exists_finset
    refine ⟨s, fun μ hμ ↦ hs μ fun hbot ↦ hμ ?_⟩
    change weightSpace P (V ⧸ N) μ = ⊥
    rw [weightSpace_quotient_eq_map N hV.iSup_weightSpaceOfMap_eq_top,
      show weightSpace P V μ = ⊥ from hbot, Submodule.map_bot]

/-- A quotient of an integrable module is integrable. -/
theorem IsIntegrable.quotient (hV : IsIntegrable P V) : IsIntegrable P (V ⧸ N) where
  isHDiagonalizable := by
    have hV' : ⨆ μ, weightSpace P V μ = ⊤ := hV.isHDiagonalizable
    simp only [IsHDiagonalizable, weightSpace_quotient_eq_map N hV']
    rw [← Submodule.map_iSup, hV', Submodule.map_top, LinearMap.range_eq_top]
    exact LieSubmodule.Quotient.surjective_mk' N
  exists_pow_e_eq_zero i x := by
    obtain ⟨v, rfl⟩ := LieSubmodule.Quotient.surjective_mk' N x
    obtain ⟨n, hn⟩ := hV.exists_pow_e_eq_zero i v
    exact ⟨n, by rw [toEnd_pow_apply_map, hn, map_zero]⟩
  exists_pow_f_eq_zero i x := by
    obtain ⟨v, rfl⟩ := LieSubmodule.Quotient.surjective_mk' N x
    obtain ⟨n, hn⟩ := hV.exists_pow_f_eq_zero i v
    exact ⟨n, by rw [toEnd_pow_apply_map, hn, map_zero]⟩

end Quotient

/-! ### Images of Verma modules -/

/-- A weight vector in the image of a morphism `φ : M(Λ) → V` is the image of a weight vector of
`M(Λ)` of the same weight. -/
lemma VermaModule.mem_map_weightSpace_of_mem_range {Λ : Dual K H}
    (φ : VermaModule P Λ →ₗ⁅K,P.KacMoodyAlgebra⁆ V) {μ : Dual K H} {x : V}
    (hx : x ∈ weightSpaceOfMap V (h P) μ) (hxφ : x ∈ φ.range) :
    x ∈ (VermaModule.weightSpace P Λ μ).map (φ : VermaModule P Λ →ₗ[K] V) := by
  obtain ⟨m, rfl⟩ := (LieModuleHom.mem_range φ x).mp hxφ
  have hm : m ∈ ⨆ ν, VermaModule.weightSpace P Λ ν := by
    have : m ∈ ⨆ (k : ι → ℤ) (_ : 0 ≤ k), VermaModule.weightSpace P Λ (Λ - P.rootOf k) := by
      rw [VermaModule.iSup_weightSpace_eq_top]; trivial
    exact (iSup₂_le fun k _ ↦ le_iSup (VermaModule.weightSpace P Λ) _ :
      _ ≤ ⨆ ν, VermaModule.weightSpace P Λ ν) this
  have := Submodule.mem_map_of_mem (f := (φ : VermaModule P Λ →ₗ[K] V)) hm
  rw [Submodule.map_iSup] at this
  refine mem_of_mem_iSup_of_le (h P) _ (fun ν ↦ ?_) hx this
  rintro _ ⟨y, hy, rfl⟩
  exact map_mem_weightSpaceOfMap P φ hy

/-! ### Irreducible submodules -/

variable [CharZero K] (hA : A.IsGeneralizedCartan)

namespace IsCategoryO

include hA in
/-- An irreducible submodule of an integrable module in `𝒪` is isomorphic to `L(Λ)` for some
dominant integral weight `Λ` ([Kac] §10.7 (check)). -/
theorem exists_equiv_irreducibleModule_of_isAtom (hV : IsCategoryO P V) (hI : IsIntegrable P V)
    {N : LieSubmodule K P.KacMoodyAlgebra V} (hN : IsAtom N) :
    ∃ Λ, P.IsDominantIntegral Λ ∧
      Nonempty (N ≃ₗ⁅K,P.KacMoodyAlgebra⁆ IrreducibleModule P Λ) := by
  have : Nontrivial N := (LieSubmodule.nontrivial_iff_ne_bot K _ V).mpr hN.1
  obtain ⟨Λ, x, hx, hx0, hxe⟩ := (hV.lieSubmodule (N := N)).exists_lie_e_eq_zero
  set w : V := (x : V)
  have hw : w ∈ weightSpace P V Λ := (mem_weightSpace_lieSubmodule N).mp hx
  have hwe : ∀ i, ⁅e P i, w⁆ = 0 := fun i ↦ by
    simp only [w, ← LieSubmodule.coe_bracket, hxe i, LieSubmodule.coe_zero]
  have hw0 : w ≠ 0 := fun h ↦ hx0 (Subtype.ext h)
  refine ⟨Λ, isDominantIntegral_of_isIntegrable hA hI hw hwe hw0, ?_⟩
  let φ := VermaModule.lift P w (fun _ hy ↦ lie_eq_zero_of_mem_nPos hwe hy) (fun a ↦ hw a)
  have hφv : φ (VermaModule.hwv P Λ) = w := VermaModule.lift_hwv P w _ _
  have hrange : φ.range = N := by
    rw [VermaModule.range_eq_lieSpan, hφv]
    refine (hN.le_iff.mp (LieSubmodule.lieSpan_le.mpr ?_)).resolve_left ?_
    · rintro _ rfl; exact x.2
    · rw [LieSubmodule.lieSpan_eq_bot_iff]
      exact fun h ↦ hw0 (h w rfl)
  have hker_le : φ.ker ≤ VermaModule.maxSubmodule P Λ :=
    (VermaModule.le_maxSubmodule_iff P Λ _).mpr fun htop ↦ hw0 (by
      rw [← hφv, ← LieModuleHom.mem_ker, htop]; trivial)
  have hle_ker : VermaModule.maxSubmodule P Λ ≤ φ.ker := by
    rw [LieModuleHom.le_ker_iff_map]
    have hle : (VermaModule.maxSubmodule P Λ).map φ ≤ N := by
      rw [← hrange, ← LieModuleHom.map_top]
      exact LieSubmodule.map_mono le_top
    refine (hN.le_iff.mp hle).resolve_right fun heq ↦ ?_
    have hwmem : w ∈ (VermaModule.maxSubmodule P Λ).map φ := heq ▸ x.2
    obtain ⟨m, hm, hmw⟩ := (LieSubmodule.mem_map w).mp hwmem
    apply VermaModule.hwv_notMem_maxSubmodule P Λ
    have hdiff : m - VermaModule.hwv P Λ ∈ VermaModule.maxSubmodule P Λ :=
      hker_le (by rw [LieModuleHom.mem_ker, map_sub, hmw, hφv, sub_self])
    simpa using sub_mem hm hdiff
  -- the induced injective map `L(Λ) → V`, with image `N`
  let ψ := LieSubmodule.Quotient.lift _ φ hle_ker
  have hψN : ∀ q, ψ q ∈ N := fun q ↦ by
    obtain ⟨m, rfl⟩ := LieSubmodule.Quotient.surjective_mk' _ q
    rw [← hrange]
    exact (LieModuleHom.mem_range φ _).mpr ⟨m, rfl⟩
  let ψ' := LieModuleHom.codRestrict N ψ hψN
  have hψ' : Function.Bijective ψ' := by
    refine ⟨(injective_iff_map_eq_zero ψ').mpr fun q hq ↦ ?_, fun y ↦ ?_⟩
    · obtain ⟨m, rfl⟩ := LieSubmodule.Quotient.surjective_mk' _ q
      rw [LieSubmodule.Quotient.mk_eq_zero]
      refine hker_le ?_
      rw [LieModuleHom.mem_ker]
      exact congrArg Subtype.val hq
    · have hy : (y : V) ∈ φ.range := by rw [hrange]; exact y.2
      obtain ⟨m, hm⟩ := (LieModuleHom.mem_range φ _).mp hy
      exact ⟨LieSubmodule.Quotient.mk' _ m, Subtype.ext hm⟩
  exact ⟨(LieModuleEquiv.ofBijective ψ' hψ').symm⟩

end IsCategoryO

/-! ### Complete reducibility, given an abstract Casimir operator -/

section Casimir

variable (hV : IsCategoryO P V) (hI : IsIntegrable P V) (Ω : V →ₗ⁅K,P.KacMoodyAlgebra⁆ V)
  {c : Dual K H → K}
  (hc : ∀ Λ μ : Dual K H, P.IsDominantIntegral Λ → P.IsDominantIntegral μ → ∀ k : ι → ℤ,
    0 ≤ k → k ≠ 0 → Λ = μ + P.rootOf k → c Λ ≠ c μ)
  (hΩ : ∀ (N : LieSubmodule K P.KacMoodyAlgebra V) (μ : Dual K H) (v : V),
    v ∈ weightSpace P V μ → (∀ i, ⁅e P i, v⁆ ∈ N) → Ω v - c μ • v ∈ N)

omit [CharZero K] in
/-- The hypothesis `hΩ` on an abstract Casimir operator follows from the stronger-looking but
equivalent condition `Ω v - c(μ) v ∈ U(𝔤) {eᵢ v | i}` for all `v ∈ V_μ`. -/
lemma sub_smul_mem_of_forall_mem_lieSpan
    (h : ∀ (μ : Dual K H) (v : V), v ∈ weightSpace P V μ →
      Ω v - c μ • v ∈ LieSubmodule.lieSpan K P.KacMoodyAlgebra (Set.range fun i ↦ ⁅e P i, v⁆))
    (N : LieSubmodule K P.KacMoodyAlgebra V) (μ : Dual K H) (v : V)
    (hv : v ∈ weightSpace P V μ) (he : ∀ i, ⁅e P i, v⁆ ∈ N) : Ω v - c μ • v ∈ N :=
  LieSubmodule.lieSpan_le.mpr (by rintro _ ⟨i, rfl⟩; exact he i) (h μ v hv)

include hΩ in
omit [CharZero K] in
/-- `Ω` acts on a primitive vector of weight `μ` by `c(μ)`. -/
lemma eq_smul_of_lie_e_eq_zero {μ : Dual K H} {v : V} (hv : v ∈ weightSpace P V μ)
    (he : ∀ i, ⁅e P i, v⁆ = 0) : Ω v = c μ • v := by
  have := hΩ ⊥ μ v hv fun i ↦ by rw [he i]; exact zero_mem _
  rwa [LieSubmodule.mem_bot, sub_eq_zero] at this

namespace IsCategoryO

include hA hV hI hc hΩ in
/-- Step 1 of the proof of complete reducibility: if `λ` is dominant integral and `y` is a weight
vector of weight `λ + β`, `β ∈ Q₊ \ {0}`, with `(Ω - c(λ))ⁿ y = 0`, then `y = 0`. -/
theorem eq_zero_of_pow_apply_eq_zero {μ : Dual K H} (hμ : P.IsDominantIntegral μ) {k : ι → ℤ}
    (hk : 0 ≤ k) (hk0 : k ≠ 0) {y : V} (hy : y ∈ weightSpace P V (μ + P.rootOf k)) {n : ℕ}
    (hn : (((Ω - c μ • LieModuleHom.id : V →ₗ⁅K,P.KacMoodyAlgebra⁆ V) : Module.End K V) ^ n) y
      = 0) :
    y = 0 := by
  set T : V →ₗ⁅K,P.KacMoodyAlgebra⁆ V := Ω - c μ • LieModuleHom.id with hT
  induction n generalizing y with
  | zero => simpa using hn
  | succ n ih =>
    rw [pow_succ, Module.End.mul_apply] at hn
    have hTy : T y = 0 := ih (map_mem_weightSpaceOfMap P T hy) hn
    by_contra hy0
    have hne : weightSpace P T.ker (μ + P.rootOf k) ≠ ⊥ := fun hbot ↦
      hy0 (congrArg Subtype.val ((Submodule.eq_bot_iff _).mp hbot ⟨y, hTy⟩
        ((mem_weightSpace_lieSubmodule T.ker).mpr hy)))
    obtain ⟨l, hl, w, hw, hw0, hwe⟩ :=
      (lieSubmodule (N := T.ker) hV).exists_lie_e_eq_zero_of_weightSpace_ne_bot hne
    have hw' := (mem_weightSpace_lieSubmodule T.ker).mp hw
    have hwe' : ∀ i, ⁅e P i, (w : V)⁆ = 0 := fun i ↦ by
      rw [← LieSubmodule.coe_bracket, hwe i, LieSubmodule.coe_zero]
    have hw0' : (w : V) ≠ 0 := fun h ↦ hw0 (Subtype.ext h)
    have hdom := isDominantIntegral_of_isIntegrable hA hI hw' hwe' hw0'
    have h2 : Ω w - c μ • (w : V) = 0 := w.2
    rw [eq_smul_of_lie_e_eq_zero Ω hΩ hw' hwe', ← sub_smul, smul_eq_zero] at h2
    refine hc _ μ hdom hμ (k + l) (add_nonneg hk hl) (fun h0 ↦ hk0 ?_) ?_
      (sub_eq_zero.mp (h2.resolve_right hw0'))
    · ext j
      have h1 := congrFun h0 j
      have h2 := hk j
      have h3 := hl j
      simp only [Pi.add_apply, Pi.zero_apply] at h1 h2 h3 ⊢
      omega
    · rw [map_add, add_assoc]

include hA hV hI hc hΩ in
/-- Step 2 of the proof of complete reducibility: a nonzero primitive vector generates an
irreducible submodule. -/
theorem isAtom_lieSpan_singleton {Λ : Dual K H} {w : V} (hw : w ∈ weightSpace P V Λ)
    (he : ∀ i, ⁅e P i, w⁆ = 0) (hw0 : w ≠ 0) :
    IsAtom (LieSubmodule.lieSpan K P.KacMoodyAlgebra {w}) := by
  let φ := VermaModule.lift P w (fun _ hy ↦ lie_eq_zero_of_mem_nPos he hy) (fun a ↦ hw a)
  have hφv : φ (VermaModule.hwv P Λ) = w := VermaModule.lift_hwv P w _ _
  have hrange : φ.range = LieSubmodule.lieSpan K P.KacMoodyAlgebra {w} := by
    rw [VermaModule.range_eq_lieSpan, hφv]
  -- `Ω` acts on `U(𝔤) w` by `c(Λ)`
  have hΩU : LieSubmodule.lieSpan K P.KacMoodyAlgebra {w} ≤
      (Ω - c Λ • LieModuleHom.id).ker := by
    rw [LieSubmodule.lieSpan_le, Set.singleton_subset_iff]
    change Ω w - c Λ • w = 0
    rw [eq_smul_of_lie_e_eq_zero Ω hΩ hw he, sub_self]
  refine ⟨fun h ↦ hw0 (by rw [LieSubmodule.lieSpan_eq_bot_iff] at h; exact h w rfl),
    fun N hN ↦ ?_⟩
  by_contra hN0
  refine hN.not_ge (LieSubmodule.lieSpan_le.mpr (Set.singleton_subset_iff.mpr ?_))
  -- a nonzero primitive vector `x ∈ N`
  have : Nontrivial N := (LieSubmodule.nontrivial_iff_ne_bot K _ V).mpr hN0
  obtain ⟨μ, x, hx, hx0, hxe⟩ := (lieSubmodule (N := N) hV).exists_lie_e_eq_zero
  have hx' := (mem_weightSpace_lieSubmodule N).mp hx
  have hxe' : ∀ i, ⁅e P i, (x : V)⁆ = 0 := fun i ↦ by
    rw [← LieSubmodule.coe_bracket, hxe i, LieSubmodule.coe_zero]
  have hx0' : (x : V) ≠ 0 := fun h ↦ hx0 (Subtype.ext h)
  have hxU : (x : V) ∈ φ.range := by rw [hrange]; exact hN.le x.2
  obtain ⟨m, hm, hmx⟩ := VermaModule.mem_map_weightSpace_of_mem_range φ hx' hxU
  have hm0 : m ≠ 0 := by rintro rfl; exact hx0' (by rw [← hmx, map_zero])
  obtain ⟨k, hk, hμ⟩ := VermaModule.exists_eq_sub_of_mem_weightSpace P Λ LieModuleHom.id
    Function.surjective_id hm hm0
  -- `c(μ) = c(Λ)`
  have hcx : c μ = c Λ := by
    have h2 : Ω x - c Λ • (x : V) = 0 := hΩU (hN.le x.2)
    rw [eq_smul_of_lie_e_eq_zero Ω hΩ hx' hxe', ← sub_smul, smul_eq_zero] at h2
    exact sub_eq_zero.mp (h2.resolve_right hx0')
  have hk0 : k = 0 := by
    by_contra hk0
    exact hc Λ μ (isDominantIntegral_of_isIntegrable hA hI hw he hw0)
      (isDominantIntegral_of_isIntegrable hA hI hx' hxe' hx0') k hk hk0 (by rw [hμ]; abel)
      hcx.symm
  rw [hk0, map_zero, sub_zero] at hμ
  subst hμ
  rw [VermaModule.weightSpace_self] at hm
  obtain ⟨a, rfl⟩ := Submodule.mem_span_singleton.mp hm
  have hmx' : a • w = x := by rw [← hmx, ← hφv]; exact (map_smul φ a _).symm
  have ha : a ≠ 0 := by rintro rfl; exact hx0' (by rw [← hmx', zero_smul])
  have : w = a⁻¹ • (x : V) := by rw [← hmx', smul_smul, inv_mul_cancel₀ ha, one_smul]
  rw [this]
  exact N.smul_mem _ x.2

include hA hV hI hc hΩ in
/-- Step 4 of the proof of complete reducibility: `V` is generated by its primitive vectors. -/
theorem lieSpan_primitive_eq_top :
    LieSubmodule.lieSpan K P.KacMoodyAlgebra
      {v : V | ∃ μ, v ∈ weightSpace P V μ ∧ ∀ i, ⁅e P i, v⁆ = 0} = ⊤ := by
  set V' := LieSubmodule.lieSpan K P.KacMoodyAlgebra
      {v : V | ∃ μ, v ∈ weightSpace P V μ ∧ ∀ i, ⁅e P i, v⁆ = 0} with hV'
  by_contra hne
  obtain ⟨x, -, hx⟩ := SetLike.exists_of_lt (lt_top_iff_ne_top.mpr hne)
  have : Nontrivial (V ⧸ V') := ⟨⟨LieSubmodule.Quotient.mk' V' x, 0, by
    rwa [Ne, LieSubmodule.Quotient.mk_eq_zero]⟩⟩
  -- a primitive vector `v̄ ≠ 0` of `V / V'`, of dominant integral weight `μ`
  obtain ⟨μ, v', hv', hv'0, hv'e⟩ := (quotient (N := V') hV).exists_lie_e_eq_zero
  have hμ := isDominantIntegral_of_isIntegrable hA (hI.quotient (N := V')) hv' hv'e hv'0
  rw [weightSpace_quotient_eq_map V' hV.iSup_weightSpaceOfMap_eq_top] at hv'
  obtain ⟨v, hv, rfl⟩ := hv'
  simp only [LieModuleHom.coe_toLinearMap] at hv'0 hv'e
  have hve : ∀ i, ⁅e P i, v⁆ ∈ V' := fun i ↦ by
    rw [← LieSubmodule.Quotient.mk_eq_zero, LieModuleHom.map_lie]
    exact hv'e i
  set T : V →ₗ⁅K,P.KacMoodyAlgebra⁆ V := Ω - c μ • LieModuleHom.id with hT
  have hTv : T v ∈ V' := hΩ V' μ v hv hve
  -- `T` preserves `V'`
  have hTV' : ∀ y ∈ V', T y ∈ V' := by
    intro y hy
    have : V' ≤ V'.comap T := by
      rw [LieSubmodule.lieSpan_le]
      rintro z ⟨ν, hz, hze⟩
      change Ω z - c μ • z ∈ V'
      rw [eq_smul_of_lie_e_eq_zero Ω hΩ hz hze, ← sub_smul]
      exact V'.smul_mem _ (LieSubmodule.subset_lieSpan ⟨ν, hz, hze⟩)
    exact this hy
  -- the finite-dimensional space `W = V' ∩ V_μ`, stable under `T`
  set W : Submodule K V := V'.toSubmodule ⊓ weightSpace P V μ with hW
  have hTW : ∀ y ∈ W, (T : Module.End K V) y ∈ W := fun y hy ↦
    ⟨hTV' y hy.1, map_mem_weightSpaceOfMap P T hy.2⟩
  have : FiniteDimensional K W := by
    have := hV.finiteDimensional_weightSpaceOfMap μ
    exact Submodule.finiteDimensional_of_le inf_le_right
  have hpow : ∀ m (y : W), ((((T : Module.End K V).restrict hTW ^ m) y : W) : V) =
      ((T : Module.End K V) ^ m) y := fun m y ↦ by
    rw [Module.End.pow_restrict, LinearMap.coe_restrict_apply]
  obtain ⟨n, hn⟩ := IsArtinian.monotone_stabilizes ((T : Module.End K V).restrict hTW).iterateRange
  have hrange : LinearMap.range ((T : Module.End K V).restrict hTW ^ n) =
      LinearMap.range ((T : Module.End K V).restrict hTW ^ (n + 1)) := hn (n + 1) n.le_succ
  have hTvW : (T : Module.End K V) v ∈ W := ⟨hTv, map_mem_weightSpaceOfMap P T hv⟩
  have hmem : ((T : Module.End K V).restrict hTW ^ n) ⟨_, hTvW⟩ ∈
      LinearMap.range ((T : Module.End K V).restrict hTW ^ (n + 1)) := by
    rw [← hrange]; exact LinearMap.mem_range_self _ _
  obtain ⟨w, hw⟩ := hmem
  have hw' : ((T : Module.End K V) ^ (n + 1)) (w : V) = ((T : Module.End K V) ^ (n + 1)) v := by
    have := congrArg Subtype.val hw
    rw [hpow, hpow] at this
    rw [this, pow_succ, Module.End.mul_apply]
  -- the lift `v₀ = v - w` of `v̄` is killed by `T^(n+1)`, hence primitive
  have hv₀μ : v - (w : V) ∈ weightSpace P V μ := sub_mem hv w.2.2
  have hv₀T : ((T : Module.End K V) ^ (n + 1)) (v - (w : V)) = 0 := by
    rw [map_sub, hw', sub_self]
  have hv₀e : ∀ i, ⁅e P i, v - (w : V)⁆ = 0 := by
    intro i
    have hy : ⁅e P i, v - (w : V)⁆ ∈ weightSpace P V (μ + P.rootOf (Pi.single i 1)) := by
      rw [rootOf_single]
      exact toEnd_e_mem_weightSpace i hv₀μ
    refine eq_zero_of_pow_apply_eq_zero hA hV hI Ω hc hΩ hμ
      (Pi.single_nonneg.mpr zero_le_one) (fun h ↦ by simpa using congrFun h i) hy
      (n := n + 1) ?_
    have hcomm : Commute (T : Module.End K V) (toEnd K P.KacMoodyAlgebra V (e P i)) :=
      LinearMap.ext fun z ↦ T.map_lie (e P i) z
    rw [← toEnd_apply_apply (R := K), ← Module.End.mul_apply, (hcomm.pow_left (n + 1)).eq,
      Module.End.mul_apply, hv₀T, map_zero]
  apply hv'0
  rw [LieSubmodule.Quotient.mk_eq_zero]
  have := add_mem (LieSubmodule.subset_lieSpan ⟨μ, hv₀μ, hv₀e⟩ : v - (w : V) ∈ V') w.2.1
  rwa [sub_add_cancel] at this

include hA hV hI hc hΩ in
/-- `V` is the sum of its irreducible submodules. -/
theorem sSup_isAtom_eq_top : sSup {N : LieSubmodule K P.KacMoodyAlgebra V | IsAtom N} = ⊤ := by
  rw [eq_top_iff, ← lieSpan_primitive_eq_top hA hV hI Ω hc hΩ, LieSubmodule.lieSpan_le]
  rintro w ⟨μ, hw, he⟩
  by_cases hw0 : w = 0
  · rw [hw0]; exact zero_mem _
  · exact (le_sSup (isAtom_lieSpan_singleton hA hV hI Ω hc hΩ hw he hw0) :
      _ ≤ sSup {N : LieSubmodule K P.KacMoodyAlgebra V | IsAtom N})
      (LieSubmodule.subset_lieSpan rfl)

include hA hV hI hc hΩ in
/-- Given an abstract Casimir operator, every submodule of an integrable module in `𝒪` has a
complement. -/
theorem complementedLattice_of_casimir :
    ComplementedLattice (LieSubmodule K P.KacMoodyAlgebra V) :=
  complementedLattice_of_sSup_atoms_eq_top (sSup_isAtom_eq_top hA hV hI Ω hc hΩ)

include hA hV hI hc hΩ in
/-- **Complete reducibility**, given an abstract Casimir operator `Ω` with eigenvalue function `c`
separating comparable dominant integral weights: an integrable module in `𝒪` is the direct sum of
an independent family of submodules, each isomorphic to `L(Λ)` for some dominant integral `Λ`
([Kac] Thm. 10.7 (b) (check)). -/
theorem exists_sSupIndep_of_casimir :
    ∃ s : Set (LieSubmodule K P.KacMoodyAlgebra V), sSupIndep s ∧ sSup s = ⊤ ∧
      ∀ N ∈ s, ∃ Λ, P.IsDominantIntegral Λ ∧
        Nonempty (N ≃ₗ⁅K,P.KacMoodyAlgebra⁆ IrreducibleModule P Λ) := by
  obtain ⟨s, hs, htop, hatom⟩ :=
    exists_sSupIndep_of_sSup_atoms_eq_top (sSup_isAtom_eq_top hA hV hI Ω hc hΩ)
  exact ⟨s, hs, htop, fun N hN ↦ exists_equiv_irreducibleModule_of_isAtom hA hV hI (hatom hN)⟩

end IsCategoryO

end Casimir

/-! ### Complete reducibility for symmetrizable `A` -/

namespace IsCategoryO

open scoped Classical in
include hA in
/-- **Complete reducibility** ([Kac] Thm. 10.7 (b) (check)). Let `A` be a symmetrizable
generalized Cartan matrix (with symmetrization `S`) and `K` a field of characteristic zero. Let
`V` be an integrable `𝔤(A)`-module in the category `𝒪`, and let `Ω` be a Casimir operator on `V`:
an endomorphism of `𝔤(A)`-modules such that for every Lie submodule `N`, every weight `μ` and every
`v ∈ V_μ` with `eᵢ v ∈ N` for all `i`, `Ω v - (μ + 2ρ | μ) v ∈ N` ([Kac] §2.5, Cor. 2.6 (check);
here `ρ` is any element with `⟨ρ, αᵢ^∨⟩ = 1`). Then `V` is the internal direct sum of a family of
submodules, each isomorphic to `L(Λ)` for some dominant integral `Λ`. -/
theorem exists_isInternal_irreducibleModule [FiniteDimensional K H] (S : A.Symmetrization)
    {ρ : Dual K H} (hρ : ∀ i, ρ (P.coroot i) = 1) (hV : IsCategoryO P V) (hI : IsIntegrable P V)
    (Ω : V →ₗ⁅K,P.KacMoodyAlgebra⁆ V)
    (hΩ : ∀ (N : LieSubmodule K P.KacMoodyAlgebra V) (μ : Dual K H) (v : V),
      v ∈ weightSpace P V μ → (∀ i, ⁅e P i, v⁆ ∈ N) →
        Ω v - P.dualBilinForm S (μ + 2 • ρ) μ • v ∈ N) :
    ∃ s : Set (LieSubmodule K P.KacMoodyAlgebra V),
      DirectSum.IsInternal (fun N : s ↦ (N : Submodule K V)) ∧
      ∀ N ∈ s, ∃ Λ, P.IsDominantIntegral Λ ∧
        Nonempty (N ≃ₗ⁅K,P.KacMoodyAlgebra⁆ IrreducibleModule P Λ) := by
  obtain ⟨s, hs, htop, hN⟩ := exists_sSupIndep_of_casimir hA hV hI Ω
    (fun Λ μ hΛ hμ k hk hk0 hΛμ ↦ dualBilinForm_add_two_smul_ne hρ hΛ hμ hk hk0 hΛμ) hΩ
  refine ⟨s, DirectSum.isInternal_submodule_of_iSupIndep_of_iSup_eq_top
    (LieSubmodule.iSupIndep_toSubmodule.mpr ((sSupIndep_iff s).mp hs)) ?_, hN⟩
  rw [LieSubmodule.iSup_toSubmodule_eq_top, ← sSup_eq_iSup']
  exact htop

end IsCategoryO


end Matrix.Realization.KacMoodyAlgebra
