/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.CompleteReducibility
import LieLean.Algebra.Lie.KacMoody.SerrePresented.LowestWeight
import LieLean.Algebra.Lie.KacMoody.SerrePresented.Syzygy

/-!
# The Gabber–Kac theorem

Let `A` be a symmetrizable generalized Cartan matrix, `K` a field of characteristic zero and
`(𝔥, Π, Π^∨)` a realization of `A`. Let `𝔤̃ = 𝔤̃(A)`, `𝔯 ⊆ 𝔤̃` its maximal ideal meeting `𝔥`
trivially, so that `𝔤(A) = 𝔤̃ / 𝔯`, and `𝔰 ⊆ 𝔯` the ideal generated by the Serre elements
`(ad eᵢ)^{1 - aᵢⱼ} eⱼ`, `(ad fᵢ)^{1 - aᵢⱼ} fⱼ` (`i ≠ j`).

**Theorem** (Gabber–Kac, [Kac] Thm. 9.11, stated there over `ℂ`; [GK]). `𝔯 = 𝔰`.
Equivalently, `𝔤(A)` is the Lie
algebra generated by `eᵢ, fᵢ` (`i ∈ I`) and `𝔥` subject to the relations (1.2.1) of [Kac] and the
Serre relations: the projection `𝔤̂(A) = 𝔤̃/𝔰 → 𝔤(A)` from the Serre-presented algebra is an
isomorphism.

## Proof

The argument is reconstructed from [Kac] §9.11 and [GK], in a module-theoretic form; the
individual steps are in `KacMoody/SerrePresented/*.lean`. Let `𝔯̂ = 𝔯/𝔰 = 𝔯̂₋ ⊕ 𝔯̂₊ ⊆ 𝔤̂(A)` be
the kernel of `𝔤̂(A) → 𝔤(A)`. By the Chevalley involution it suffices to show `𝔯̂₋ = 0`
(`Matrix.Realization.SerrePresentedAlgebra.radical_eq_bot_iff`). Since `𝔯̂₋` is an ideal
contained in `𝔫̂₋ = ⊕_{β > 0} 𝔤̂_{-β}`, it is the sum of its weight spaces `(𝔯̂₋)_{-β}`,
`β ∈ Q₊ \ {0}`. We show by strong induction on `ht β` that they vanish.

So let `β = ∑ kⱼ αⱼ ∈ Q₊ \ {0}` and suppose that `(𝔯̂₋)_{-γ} = 0` for `ht γ < ht β`, and that
`x ∈ (𝔯̂₋)_{-β}` is nonzero.
1. `[eᵢ, x] = 0` for all `i`, and by `𝔰𝔩₂`-theory in the integrable algebra `𝔤̂(A)`,
   `⟨β, αᵢ^∨⟩ = ∑ⱼ aᵢⱼ kⱼ ≤ 0` for all `i`
   (`Matrix.Realization.SerrePresentedAlgebra.sum_mul_le_zero_of_minimal`).
2. Let `E = ⊕ᵢ M(-αᵢ)`, with its module of syzygies `Syz` (the kernel of `E → M(0)`,
   `v_{-αᵢ} ↦ fᵢ v₀`), and `T ⊆ Syz` the submodule generated by the weight spaces `Syz_{-γ}`,
   `ht γ < ht β`. There is `s ∈ Syz_{-β}` with `s ∉ T` and `eᵢ s ∈ T` for all `i`
   (`Matrix.Realization.SerrePresentedAlgebra.exists_syzygy`).
3. `E` lies in the category `𝒪`, so the Casimir operator `Ω` of [Kac] §2.5 acts on it. It acts
   on `M(-αᵢ)` by `(-αᵢ + 2ρ | -αᵢ) = (αᵢ | αᵢ) - 2 (ρ | αᵢ) = 0`, hence by `0` on `E`. On the
   image of `s` in `E / T` it acts by `(-β + 2ρ | -β)` ([Kac] Cor. 2.6), so `(-β + 2ρ | -β) = 0`
   since `s ∉ T`, i.e. `(β | β) = 2 (ρ | β)`.
4. But with `(αᵢ | αᵢ) = 2/εᵢ > 0`,
   `2 (ρ | β) - (β | β) = ∑ᵢ kᵢ (2 - ⟨β, αᵢ^∨⟩) / εᵢ > 0`, since all terms are `≥ 0` by step 1
   and some `kᵢ > 0`. This contradiction shows `(𝔯̂₋)_{-β} = 0`.

## Main results

* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.directSum`: a finite direct sum of modules in
  `𝒪` lies in `𝒪`.
* `Matrix.Realization.KacMoodyAlgebra.IsStandardForm.casimir_vermaSum_eq_zero`: `Ω = 0` on
  `⊕ᵢ M(-αᵢ)`.
* `Matrix.Realization.SerrePresentedAlgebra.radicalNeg_eq_bot`: `𝔯̂₋ = 0`.
* `Matrix.Realization.AuxLieAlgebra.maxIdeal_eq_serreIdeal`: the **Gabber–Kac theorem** `𝔯 = 𝔰`.
* `Matrix.Realization.SerrePresentedAlgebra.equivKacMoody`: the isomorphism `𝔤̂(A) ≃ 𝔤(A)`.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §2.5, §9.11.
* [GK] O. Gabber, V. G. Kac, *On defining relations of certain infinite-dimensional Lie
  algebras*, Bull. Amer. Math. Soc. (N.S.) **5** (1981), 185–189.
-/

open Module LieModule

noncomputable section

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H)

omit [DecidableEq ι] in
include P in
/-- If the index set is nonempty, the Cartan subalgebra `𝔥` of a realization is
finite-dimensional. -/
lemma finiteDimensional_of_nonempty [Nonempty ι] : FiniteDimensional K H := by
  apply Module.finite_of_finrank_pos
  have h1 := P.finrank_add_rank
  have h2 := (A.map (Int.cast : ℤ → K)).rank_le_card_width
  have h3 : 0 < Fintype.card ι := Fintype.card_pos
  omega

/-! ### The key inequality -/

section Arithmetic

variable [CharZero K] [FiniteDimensional K H] (S : A.Symmetrization)

omit [DecidableEq ι] in
/-- `(μ | ∑ kᵢ αᵢ) = ∑ kᵢ ⟨μ, αᵢ^∨⟩ / εᵢ`. -/
lemma dualBilinForm_rootOf_right (μ : Dual K H) (k : ι → ℤ) :
    P.dualBilinForm S μ (P.rootOf k) = ∑ i, (k i : K) * (μ (P.coroot i) / S.ε i) := by
  simp only [rootOf_apply, map_sum, map_smul, dualBilinForm_root_right, smul_eq_mul]

omit [DecidableEq ι] in
/-- For `β = ∑ kᵢ αᵢ ∈ Q₊ \ {0}` with `⟨β, αᵢ^∨⟩ ≤ 0` for all `i`, we have `(β | β) ≠ 2 (ρ | β)`,
in the form `(-β + 2ρ | -β) ≠ 0`. This is the final step of the proof of the Gabber–Kac theorem
([Kac] §9.11, [GK]; reconstructed argument). -/
theorem dualBilinForm_neg_rootOf_add_two_rho_ne_zero {k : ι → ℤ} (hk : k ∈ posCone ι)
    (hle : ∀ i, ∑ j, A i j * k j ≤ 0) :
    P.dualBilinForm S (-P.rootOf k + 2 • P.rho) (-P.rootOf k) ≠ 0 := by
  set q : ℚ := ∑ i, (k i : ℚ) * ((2 - ((∑ j, A i j * k j : ℤ) : ℚ)) / S.ε i) with hq
  have key : P.dualBilinForm S (-P.rootOf k + 2 • P.rho) (-P.rootOf k) = ((-q : ℚ) : K) := by
    rw [map_neg, dualBilinForm_rootOf_right, hq]
    simp only [LinearMap.add_apply, LinearMap.neg_apply, LinearMap.smul_apply,
      rootOf_apply_coroot, mulVec, dotProduct, rho_coroot]
    push_cast
    congr 1
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    rw [two_nsmul]
    ring
  have hpos : 0 < q := by
    obtain ⟨i, hi⟩ := Function.ne_iff.mp hk.2
    have hki : 0 < k i := lt_of_le_of_ne (hk.1 i) (Ne.symm hi)
    refine Finset.sum_pos' (fun j _ ↦ ?_) ⟨i, Finset.mem_univ i, ?_⟩
    · have h1 : (0 : ℚ) ≤ k j := by exact_mod_cast hk.1 j
      have h2 : ((∑ l, A j l * k l : ℤ) : ℚ) ≤ 0 := by exact_mod_cast hle j
      exact mul_nonneg h1 (div_nonneg (by linarith) (S.ε_pos j).le)
    · have h1 : (0 : ℚ) < k i := by exact_mod_cast hki
      have h2 : ((∑ l, A i l * k l : ℤ) : ℚ) ≤ 0 := by exact_mod_cast hle i
      exact mul_pos h1 (div_pos (by linarith) (S.ε_pos i))
  rw [key, Rat.cast_ne_zero, neg_ne_zero]
  exact hpos.ne'

omit [DecidableEq ι] in
/-- `(-αᵢ + 2ρ | -αᵢ) = 0`: the Casimir operator acts by `0` on `M(-αᵢ)`. -/
theorem dualBilinForm_neg_root_add_two_rho (hA : A.IsGeneralizedCartan) (i : ι) :
    P.dualBilinForm S (-P.root i + 2 • P.rho) (-P.root i) = 0 := by
  have := two_mul_dualBilinForm_rho_root (P := P) S hA i
  simp only [map_neg, map_add, map_nsmul, LinearMap.neg_apply, LinearMap.add_apply,
    LinearMap.smul_apply, nsmul_eq_mul, Nat.cast_ofNat]
  linear_combination -this

end Arithmetic

namespace KacMoodyAlgebra

/-! ### Finite direct sums in the category `𝒪` -/

section DirectSum

variable {κ : Type*} [Finite κ] (M : κ → Type*) [∀ i, AddCommGroup (M i)]
  [∀ i, Module K (M i)] [∀ i, LieRingModule P.KacMoodyAlgebra (M i)]
  [∀ i, LieModule K P.KacMoodyAlgebra (M i)]

variable {P} in
/-- A finite direct sum of modules in the category `𝒪` lies in `𝒪`. -/
theorem IsCategoryO.directSum (hM : ∀ i, IsCategoryO P (M i)) :
    IsCategoryO P (DirectSum κ M) := by
  classical
  have := Fintype.ofFinite κ
  have hof : ∀ i μ (m : M i), m ∈ weightSpace P (M i) μ →
      DirectSum.of M i m ∈ weightSpace P (DirectSum κ M) μ := fun i _ _ hm ↦
    map_mem_weightSpaceOfMap P (DirectSum.lieModuleOf K κ P.KacMoodyAlgebra M i) hm
  have hcomp : ∀ i μ (v : DirectSum κ M), v ∈ weightSpace P (DirectSum κ M) μ →
      v i ∈ weightSpace P (M i) μ := fun i _ _ hv ↦
    map_mem_weightSpaceOfMap P (DirectSum.lieModuleComponent K κ P.KacMoodyAlgebra M i) hv
  have hle : ∀ μ, weightSpace P (DirectSum κ M) μ ≤
      ⨆ i, (weightSpace P (M i) μ).map (DirectSum.lof K κ M i) := by
    intro μ v hv
    rw [← DirectSum.sum_univ_of v]
    exact Submodule.sum_mem _ fun i _ ↦ Submodule.mem_iSup_of_mem i ⟨v i, hcomp i μ v hv, rfl⟩
  refine ⟨?_, fun μ ↦ ?_, ?_⟩
  · rw [eq_top_iff]
    rintro v -
    rw [← DirectSum.sum_univ_of v]
    refine Submodule.sum_mem _ fun i _ ↦ ?_
    have hv : v i ∈ ⨆ μ, weightSpace P (M i) μ := by
      rw [(hM i).iSup_weightSpaceOfMap_eq_top]; trivial
    refine Submodule.iSup_induction _
      (motive := fun m ↦ DirectSum.of M i m ∈ ⨆ μ, weightSpace P (DirectSum κ M) μ) hv
      (fun μ m hm ↦ Submodule.mem_iSup_of_mem μ (hof i μ m hm)) (by simp) ?_
    intro m m' hm hm'
    rw [map_add]
    exact add_mem hm hm'
  · have : ∀ i, FiniteDimensional K (weightSpace P (M i) μ) := fun i ↦
      (hM i).finiteDimensional_weightSpaceOfMap μ
    exact Submodule.finiteDimensional_of_le (hle μ)
  · choose s hs using fun i ↦ (hM i).exists_finset
    refine ⟨Finset.univ.biUnion s, fun μ hμ ↦ ?_⟩
    obtain ⟨v, hv, hv0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hμ
    obtain ⟨i, hi⟩ : ∃ i, v i ≠ 0 := by
      by_contra! h0
      exact hv0 (DFinsupp.ext h0)
    have hne : weightSpace P (M i) μ ≠ ⊥ := fun hbot ↦ by
      have := hcomp i μ v hv
      rw [hbot, Submodule.mem_bot] at this
      exact hi this
    obtain ⟨Λ, hΛ, hμΛ⟩ := hs i μ hne
    exact ⟨Λ, Finset.mem_biUnion.mpr ⟨i, Finset.mem_univ i, hΛ⟩, hμΛ⟩

end DirectSum

variable [CharZero K]

/-- `E = ⊕ᵢ M(-αᵢ)` lies in the category `𝒪`. -/
theorem isCategoryO_vermaSum : IsCategoryO P (VermaSum P) :=
  IsCategoryO.directSum _ fun _ ↦ VermaModule.isCategoryO P _

variable [FiniteDimensional K H] {S : A.Symmetrization}
  {B : LinearMap.BilinForm K P.KacMoodyAlgebra}

variable {P} in
/-- The Casimir operator vanishes on `E = ⊕ᵢ M(-αᵢ)`: it acts on `M(-αᵢ)` by
`(-αᵢ + 2ρ | -αᵢ) = 0` ([Kac] Cor. 2.6). -/
theorem IsStandardForm.casimir_vermaSum_eq_zero (hB : IsStandardForm P S B)
    (hA : A.IsGeneralizedCartan) (v : VermaSum P) :
    hB.casimir (VermaSum P) (isCategoryO_vermaSum P).isPosFinite v = 0 := by
  induction v using DirectSum.induction_on with
  | zero => exact map_zero _
  | of i m =>
    have := hB.map_casimir
      (DirectSum.lieModuleOf K ι P.KacMoodyAlgebra (fun i ↦ VermaModule P (-P.root i)) i)
      (VermaModule.isCategoryO P _).isPosFinite (isCategoryO_vermaSum P).isPosFinite m
    rw [← show DirectSum.lieModuleOf K ι P.KacMoodyAlgebra (fun i ↦ VermaModule P (-P.root i)) i
      m = DirectSum.of _ i m from rfl, ← this,
      hB.casimir_eq_smul_of_surjective hA _ LieModuleHom.id Function.surjective_id,
      dualBilinForm_neg_root_add_two_rho P S hA, zero_smul, map_zero]
  | add v w hv hw => rw [map_add, hv, hw, add_zero]

end KacMoodyAlgebra

/-! ### Vanishing of `𝔯̂₋` -/

namespace SerrePresentedAlgebra

variable [CharZero K] (hA : A.IsGeneralizedCartan)

include hA in
/-- The inductive step of the proof of the Gabber–Kac theorem: if `𝔯̂₋` has no nonzero weight
vectors of weight `-γ` with `ht γ < ht β`, then it has none of weight `-β`
([Kac] §9.11, [GK]; reconstructed argument, see the module docstring). -/
theorem radicalNeg_inf_rootSpace_eq_bot_of_minimal (S : A.Symmetrization) {k : ι → ℤ}
    (hk : k ∈ posCone ι)
    (hmin : ∀ l ∈ posCone ι, height l < height k →
      (radicalNeg P).toSubmodule ⊓ rootSpace P (-P.rootOf l) = ⊥) :
    (radicalNeg P).toSubmodule ⊓ rootSpace P (-P.rootOf k) = ⊥ := by
  have : Nonempty ι := by
    obtain ⟨i, -⟩ := Function.ne_iff.mp hk.2
    exact ⟨i⟩
  have := P.finiteDimensional_of_nonempty
  rw [Submodule.eq_bot_iff]
  rintro x ⟨hx, hxk⟩
  by_contra hx0
  obtain ⟨s, -, hsw, hsT, he⟩ := exists_syzygy P hA hk hmin hx hxk hx0
  have hB := KacMoodyAlgebra.isStandardForm_invForm P S
  have h1 := hB.casimir_sub_smul_mem (KacMoodyAlgebra.isCategoryO_vermaSum P)
    (KacMoodyAlgebra.lowerSyzygies P k) hsw he
  rw [hB.casimir_vermaSum_eq_zero hA, zero_sub, neg_mem_iff] at h1
  have hc := P.dualBilinForm_neg_rootOf_add_two_rho_ne_zero S hk
    (sum_mul_le_zero_of_minimal P hA hk hmin hx hxk hx0)
  have h2 := (KacMoodyAlgebra.lowerSyzygies P k).toSubmodule.smul_mem
    (P.dualBilinForm S (-P.rootOf k + 2 • P.rho) (-P.rootOf k))⁻¹ h1
  rw [inv_smul_smul₀ hc] at h2
  exact hsT h2

include hA in
/-- For a symmetrizable generalized Cartan matrix, `𝔯̂₋ = 0` ([Kac] §9.11, [GK];
reconstructed argument). -/
theorem radicalNeg_eq_bot (hS : A.IsSymmetrizable) : radicalNeg P = ⊥ := by
  obtain ⟨S⟩ := isSymmetrizable_iff_nonempty_symmetrization.mp hS
  have hind : ∀ n : ℕ, ∀ k ∈ posCone ι, height k < n →
      (radicalNeg P).toSubmodule ⊓ rootSpace P (-P.rootOf k) = ⊥ := by
    intro n
    induction n with
    | zero =>
      intro k hk hkn
      have : 0 ≤ height k := Finset.sum_nonneg fun i _ ↦ hk.1 i
      omega
    | succ n ih =>
      intro k hk hkn
      exact radicalNeg_inf_rootSpace_eq_bot_of_minimal P hA S hk fun l hl hlk ↦
        ih l hl (by omega)
  have hbot : ⨆ μ ∈ P.negWeights, ((radicalNeg P).toSubmodule ⊓ rootSpace P μ) = ⊥ := by
    refine iSup₂_eq_bot.mpr ?_
    rintro _ ⟨k, hk, rfl⟩
    exact hind ((height k).toNat + 1) k hk (by omega)
  rw [eq_bot_iff]
  intro x hx
  have hx' : x ∈ (radicalNeg P).toSubmodule := hx
  have hmem : x ∈ (radicalNeg P).toSubmodule ⊓ ⨆ μ ∈ P.negWeights, rootSpace P μ := by
    refine ⟨hx', ?_⟩
    rw [radicalNeg_toSubmodule P hA] at hx'
    obtain ⟨y, rfl⟩ := hx'.2
    exact fHom_mem P y
  have := inf_iSup_weightSpaceOfMap_le (h P) _ (fun _ _ hm ↦ (radicalNeg P).lie_mem hm) _ hmem
  rw [hbot, Submodule.mem_bot] at this
  rw [this]
  exact LieSubmodule.zero_mem _

end SerrePresentedAlgebra

/-! ### The Gabber–Kac theorem -/

variable [CharZero K] (hA : A.IsGeneralizedCartan) (hS : A.IsSymmetrizable)

include hA hS in
/-- **Gabber–Kac theorem** ([Kac] Thm. 9.11, over `ℂ`; [GK]). For a symmetrizable
generalized Cartan
matrix `A` over a field of characteristic zero, the maximal ideal `𝔯` of `𝔤̃(A)` meeting `𝔥`
trivially is generated by the Serre elements `(ad eᵢ)^{1 - aᵢⱼ} eⱼ`, `(ad fᵢ)^{1 - aᵢⱼ} fⱼ`
(`i ≠ j`). The argument is reconstructed; see the module docstring. -/
theorem AuxLieAlgebra.maxIdeal_eq_serreIdeal :
    AuxLieAlgebra.maxIdeal P = AuxLieAlgebra.serreIdeal P :=
  (SerrePresentedAlgebra.maxIdeal_eq_serreIdeal_iff P hA).mpr
    ((SerrePresentedAlgebra.radical_eq_bot_iff P hA).mpr
      (SerrePresentedAlgebra.radicalNeg_eq_bot P hA hS))

namespace SerrePresentedAlgebra

include hS in
/-- The projection `𝔤̂(A) → 𝔤(A)` is injective (Gabber–Kac, [Kac] Thm. 9.11; [GK]). -/
theorem toKacMoody_injective : Function.Injective (toKacMoody P hA) :=
  (radical_eq_bot_iff_injective P hA).mp
    ((radical_eq_bot_iff P hA).mpr (radicalNeg_eq_bot P hA hS))

include hS in
/-- The projection `𝔤̂(A) → 𝔤(A)` is bijective (Gabber–Kac, [Kac] Thm. 9.11; [GK]). -/
theorem toKacMoody_bijective : Function.Bijective (toKacMoody P hA) :=
  ⟨toKacMoody_injective P hA hS, toKacMoody_surjective P hA⟩

/-- **Gabber–Kac theorem** ([Kac] Thm. 9.11, over `ℂ`; [GK]), as an isomorphism: for a
symmetrizable
generalized Cartan matrix `A` over a field of characteristic zero, `𝔤(A)` is isomorphic to the
Lie algebra `𝔤̂(A)` generated by `eᵢ, fᵢ` (`i ∈ I`) and `𝔥` subject to the relations (1.2.1) of
[Kac] and the Serre relations. -/
def equivKacMoody : P.SerrePresentedAlgebra ≃ₗ⁅K⁆ P.KacMoodyAlgebra :=
  LieEquiv.ofBijective (toKacMoody P hA) (toKacMoody_bijective P hA hS)

@[simp] lemma equivKacMoody_apply (x : P.SerrePresentedAlgebra) :
    equivKacMoody P hA hS x = toKacMoody P hA x :=
  rfl

end SerrePresentedAlgebra

end Matrix.Realization

end
