/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.FiniteType
import LieLean.Algebra.Lie.KacMoody.GabberKac
import LieLean.Algebra.Lie.KacMoody.ToLieAlgebra
import Mathlib.LinearAlgebra.RootSystem.GeckConstruction.Basis

/-!
# Serre's theorem: Lie algebras with a Chevalley–Serre basis and Geck's construction

Let `L` be a finite-dimensional Lie algebra over a field `K` of characteristic zero, with a basis
`B : LieAlgebra.Basis ι C` in the sense of Mathlib: elements `hᵢ, eᵢ, fᵢ` (`i ∈ ι`) such that each
`(hᵢ, eᵢ, fᵢ)` is an `sl₂`-triple, the `hᵢ` are linearly independent and commute,
`[hⱼ, eᵢ] = Aᵢⱼ eᵢ`, `[hⱼ, fᵢ] = -Aᵢⱼ fᵢ`, `[eᵢ, fⱼ] = 0` for `i ≠ j`, and the `eᵢ, fᵢ` generate
`L`. Suppose that `A = B.A` is a Cartan matrix of finite type. We prove that `L` is isomorphic to
the Kac–Moody algebra `𝔤(Aᵀ)` (for any realization of `Aᵀ`), by an isomorphism sending
`eᵢ, fᵢ, αᵢ^∨` to `eᵢ, fᵢ, hᵢ`. Applied to Mathlib's Geck construction
`RootPairing.GeckConstruction.lieAlgebra b` of the Lie algebra of a reduced irreducible
crystallographic root system with base `b`, this identifies Geck's algebra with `𝔤(A)` for
Kac's Cartan matrix of the root system, and (via the Gabber–Kac theorem) with the Lie algebra
presented by the Chevalley–Serre generators and relations.

## Conventions

Mathlib's Cartan matrices (`RootPairing.Base.cartanMatrix`, `LieAlgebra.Basis.A`) satisfy
`Aᵢⱼ = ⟨αᵢ, αⱼ^∨⟩`, i.e. `[hⱼ, eᵢ] = Aᵢⱼ eᵢ`, whereas Kac's (and this project's
`Matrix.Realization`) satisfy `aᵢⱼ = ⟨αᵢ^∨, αⱼ⟩` (`root j (coroot i) = A i j`). So the Kac–Moody
algebra attached to `B` is that of the transpose `Aᵀ`.

## The argument

This is the standard proof of the uniqueness part of Serre's theorem ([Hum] §18.3–18.4);
we reconstructed it in the present setting.

1. Since `Aᵀ` is nonsingular, the simple coroots `αᵢ^∨` form a basis of `𝔥`
   (`LieAlgebra.Basis.corootBasis`); the linear map `𝔥 → L`, `αᵢ^∨ ↦ hᵢ`, together with
   `eᵢ ↦ eᵢ`, `fᵢ ↦ fᵢ` satisfies the relations (1.2.1) of [Kac], giving `𝔤̃(Aᵀ) → L`.
2. The Serre relations hold in `L`: for `i ≠ j`, `eⱼ` is a primitive vector of weight
   `-Aⱼᵢ ∈ ℕ` for the `sl₂`-triple `(-hᵢ, fᵢ, eᵢ)` acting on the finite-dimensional module `L`
   (`[fᵢ, eⱼ] = 0`), so `(ad eᵢ)^{1 - Aⱼᵢ} eⱼ = 0`; similarly `(ad fᵢ)^{1 - Aⱼᵢ} fⱼ = 0` using
   `(hᵢ, eᵢ, fᵢ)`. Hence the Serre ideal lies in the kernel, and by the Gabber–Kac theorem
   ([Kac] Thm. 9.11; `Aᵀ` is symmetrizable) so does the maximal ideal `𝔯`: we get
   `𝔤(Aᵀ) → L`.
3. The morphism is surjective since `L` is generated by the `eᵢ, fᵢ`. Its kernel is an ideal of
   `𝔤(Aᵀ)`; a nonzero ideal meets `𝔥` ([Kac] §1.3), but `𝔥 → L` is injective since the
   `hᵢ` are linearly independent. So it is injective.

## Main definitions

* `LieAlgebra.Basis.corootBasis`: the simple coroots as a basis of `𝔥`.
* `LieAlgebra.Basis.kacMoodyHom`: the morphism `𝔤(Aᵀ) → L`.
* `LieAlgebra.Basis.kacMoodyEquiv`: the isomorphism `𝔤(Aᵀ) ≃ L`.
* `RootPairing.GeckConstruction.equivKacMoodyAlgebra`: Geck's Lie algebra of a root system is
  isomorphic to the Kac–Moody algebra of (Kac's form of) its Cartan matrix.
* `RootPairing.GeckConstruction.equivSerrePresentedAlgebra`: Geck's Lie algebra is presented by
  the Chevalley–Serre generators and relations (Serre's theorem).
* `RootPairing.GeckConstruction.equivToLieAlgebra`: Mathlib's `Matrix.ToLieAlgebra K A` is
  isomorphic to Geck's Lie algebra (`A = b.cartanMatrixᵀ`).

## Main results

* `LieAlgebra.Basis.ad_e_pow_e_eq_zero`, `LieAlgebra.Basis.ad_f_pow_f_eq_zero`: the Serre
  relations in a finite-dimensional Lie algebra with a basis.
* `LieAlgebra.Basis.kacMoodyHom_injective`, `LieAlgebra.Basis.kacMoodyHom_surjective`.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §1.2–1.3, Thm. 9.11
  (stated over `ℂ`).
* [Hum] J. E. Humphreys, *Introduction to Lie algebras and representation theory*, GTM 9,
  §7.2, §18.
* M. Geck, *On the construction of semisimple Lie algebras and Chevalley groups*, Proc. Amer.
  Math. Soc. 145 (2017).
-/

open Module LieAlgebra LieModule
open scoped Matrix

noncomputable section

namespace LieAlgebra.Basis

variable {ι K L H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [CharZero K]
  [LieRing L] [LieAlgebra K L] {C : LieSubalgebra K L} (B : LieAlgebra.Basis ι C)
  [AddCommGroup H] [Module K H] [FiniteDimensional K H] (Q : Matrix.Realization B.Aᵀ K H)
  (hA : B.A.IsFiniteCartan)

/-- For a finite-type Cartan matrix, the simple coroots of a realization form a basis of `𝔥`. -/
def corootBasis : Module.Basis ι K H :=
  .mk Q.linearIndependent_coroot (Q.linearIndependent_coroot.span_eq_top_of_card_eq_finrank'
    (Q.finrank_eq_card_of_isFiniteCartan hA.transpose).symm).ge

@[simp] lemma corootBasis_apply (i : ι) : corootBasis B Q hA i = Q.coroot i := by
  simp [corootBasis]

/-- The data defining the morphism `𝔤̃(Aᵀ) → L`. -/
def liftData : Matrix.Realization.AuxLieAlgebra.LiftData Q L where
  h := (corootBasis B Q hA).constr K B.h
  e := B.e
  f := B.f
  lie_h_h a b := by
    simp [Module.Basis.constr_apply_fintype, sum_lie, lie_sum, B.lie_h_h]
  lie_e_f i j := by
    split_ifs with hij
    · subst hij
      rw [(B.sl2 i).lie_e_f, ← corootBasis_apply B Q hA, Module.Basis.constr_basis]
    · exact B.lie_e_f_ne i j hij
  lie_h_e a i := by
    conv_rhs => rw [← (corootBasis B Q hA).sum_equivFun a]
    simp [Module.Basis.constr_apply_fintype, sum_lie, B.lie_h_e, Finset.sum_smul, smul_smul,
      Q.root_coroot, ← Int.cast_smul_eq_zsmul K]
  lie_h_f a i := by
    conv_rhs => rw [← (corootBasis B Q hA).sum_equivFun a]
    simp [Module.Basis.constr_apply_fintype, sum_lie, B.lie_h_f, Finset.sum_smul, smul_smul,
      Q.root_coroot, ← Int.cast_smul_eq_zsmul K]

open Matrix.Realization

/-- The morphism `𝔤̃(Aᵀ) → L` sending `eᵢ, fᵢ, αᵢ^∨` to `B.e i, B.f i, B.h i`. -/
def auxHom : Q.AuxLieAlgebra →ₗ⁅K⁆ L := AuxLieAlgebra.lift (liftData B Q hA)

@[simp] lemma auxHom_e (i : ι) : auxHom B Q hA (AuxLieAlgebra.e Q i) = B.e i :=
  AuxLieAlgebra.lift_e _ i

@[simp] lemma auxHom_f (i : ι) : auxHom B Q hA (AuxLieAlgebra.f Q i) = B.f i :=
  AuxLieAlgebra.lift_f _ i

lemma auxHom_h (a : H) :
    auxHom B Q hA (AuxLieAlgebra.h Q a) = (corootBasis B Q hA).constr K B.h a :=
  AuxLieAlgebra.lift_h _ a

@[simp] lemma auxHom_h_coroot (i : ι) : auxHom B Q hA (AuxLieAlgebra.h Q (Q.coroot i)) = B.h i := by
  rw [auxHom_h, ← corootBasis_apply B Q hA, Module.Basis.constr_basis]

variable [FiniteDimensional K L]

include hA in
/-- The Serre relation `(ad eᵢ)^{1 - aⱼᵢ} eⱼ = 0` (`i ≠ j`) in a finite-dimensional Lie algebra
with a basis `B`, from the representation theory of the `sl₂`-triple `(hᵢ, eᵢ, fᵢ)`: `eⱼ` is a
primitive vector of weight `-aⱼᵢ` for the triple `(-hᵢ, fᵢ, eᵢ)`. -/
theorem ad_e_pow_e_eq_zero {i j : ι} (hij : i ≠ j) :
    (ad K L (B.e i) ^ ((-B.A j i).toNat + 1)) (B.e j) = 0 := by
  obtain ⟨n, hn⟩ : ∃ n : ℕ, -B.A j i = n :=
    ⟨_, (Int.toNat_of_nonneg (by linarith [hA.offDiag_nonpos j i hij.symm])).symm⟩
  rw [hn, Int.toNat_natCast]
  have hP : (B.sl2 i).symm.HasPrimitiveVectorWith (B.e j) (n : K) :=
    { ne_zero := (B.sl2 j).e_ne_zero
      lie_h := by
        rw [neg_lie, B.lie_h_e, ← neg_smul, hn, natCast_zsmul, Nat.cast_smul_eq_nsmul]
      lie_e := by rw [← lie_skew, B.lie_e_f_ne j i hij.symm, neg_zero] }
  exact hP.pow_toEnd_f_eq_zero_of_eq_nat rfl

include hA in
/-- The Serre relation `(ad fᵢ)^{1 - aⱼᵢ} fⱼ = 0` (`i ≠ j`) in a finite-dimensional Lie algebra
with a basis `B`: `fⱼ` is a primitive vector of weight `-aⱼᵢ` for the triple `(hᵢ, eᵢ, fᵢ)`. -/
theorem ad_f_pow_f_eq_zero {i j : ι} (hij : i ≠ j) :
    (ad K L (B.f i) ^ ((-B.A j i).toNat + 1)) (B.f j) = 0 := by
  obtain ⟨n, hn⟩ : ∃ n : ℕ, -B.A j i = n :=
    ⟨_, (Int.toNat_of_nonneg (by linarith [hA.offDiag_nonpos j i hij.symm])).symm⟩
  rw [hn, Int.toNat_natCast]
  have hP : (B.sl2 i).HasPrimitiveVectorWith (B.f j) (n : K) :=
    { ne_zero := (B.sl2 j).f_ne_zero
      lie_h := by
        rw [B.lie_h_f, hn, natCast_zsmul, Nat.cast_smul_eq_nsmul]
      lie_e := B.lie_e_f_ne i j hij }
  exact hP.pow_toEnd_f_eq_zero_of_eq_nat rfl

/-- The Serre ideal of `𝔤̃(Aᵀ)` lies in the kernel of `auxHom`. -/
lemma serreIdeal_le_ker_auxHom : AuxLieAlgebra.serreIdeal Q ≤ (auxHom B Q hA).ker := by
  rw [AuxLieAlgebra.serreIdeal, LieSubmodule.lieSpan_le]
  rintro _ ⟨i, j, hij, rfl | rfl⟩
  · rw [SetLike.mem_coe, LieHom.mem_ker, AuxLieAlgebra.serreE_eq, LieHom.map_ad_pow, auxHom_e,
      auxHom_e]
    exact ad_e_pow_e_eq_zero B hA hij
  · rw [SetLike.mem_coe, LieHom.mem_ker, AuxLieAlgebra.serreF, ← ad_apply K, ← Module.End.mul_apply,
      ← pow_succ, LieHom.map_ad_pow, auxHom_f, auxHom_f]
    exact ad_f_pow_f_eq_zero B hA hij

/-- The maximal ideal `𝔯` of `𝔤̃(Aᵀ)` lies in the kernel of `auxHom`, by the Gabber–Kac theorem
`𝔯 = ` Serre ideal. -/
lemma maxIdeal_le_ker_auxHom : AuxLieAlgebra.maxIdeal Q ≤ (auxHom B Q hA).ker := by
  rw [AuxLieAlgebra.maxIdeal_eq_serreIdeal Q hA.transpose.isGeneralizedCartan
    hA.transpose.isSymmetrizable]
  exact serreIdeal_le_ker_auxHom B Q hA

/-- The morphism `𝔤(Aᵀ) → L` sending `eᵢ, fᵢ, αᵢ^∨` to `B.e i, B.f i, B.h i`. -/
def kacMoodyHom : Q.KacMoodyAlgebra →ₗ⁅K⁆ L :=
  LieIdeal.lift _ (auxHom B Q hA) (maxIdeal_le_ker_auxHom B Q hA)

@[simp] lemma kacMoodyHom_π (x : Q.AuxLieAlgebra) :
    kacMoodyHom B Q hA (KacMoodyAlgebra.π Q x) = auxHom B Q hA x :=
  LieIdeal.lift_mkHom _ (auxHom B Q hA) _ x

@[simp] lemma kacMoodyHom_e (i : ι) : kacMoodyHom B Q hA (KacMoodyAlgebra.e Q i) = B.e i := by
  rw [← KacMoodyAlgebra.π_e, kacMoodyHom_π, auxHom_e]

@[simp] lemma kacMoodyHom_f (i : ι) : kacMoodyHom B Q hA (KacMoodyAlgebra.f Q i) = B.f i := by
  rw [← KacMoodyAlgebra.π_f, kacMoodyHom_π, auxHom_f]

lemma kacMoodyHom_h (a : H) :
    kacMoodyHom B Q hA (KacMoodyAlgebra.h Q a) = (corootBasis B Q hA).constr K B.h a := by
  rw [← KacMoodyAlgebra.π_h, kacMoodyHom_π, auxHom_h]

@[simp] lemma kacMoodyHom_h_coroot (i : ι) :
    kacMoodyHom B Q hA (KacMoodyAlgebra.h Q (Q.coroot i)) = B.h i := by
  rw [← KacMoodyAlgebra.π_h, kacMoodyHom_π, auxHom_h_coroot]

/-- `𝔤(Aᵀ) → L` is surjective, since `L` is generated by the `eᵢ, fᵢ`. -/
theorem kacMoodyHom_surjective : Function.Surjective (kacMoodyHom B Q hA) := by
  rw [← LieHom.range_eq_top, eq_top_iff, ← B.span_ef, LieSubalgebra.lieSpan_le]
  rintro _ (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · exact ⟨KacMoodyAlgebra.e Q i, kacMoodyHom_e B Q hA i⟩
  · exact ⟨KacMoodyAlgebra.f Q i, kacMoodyHom_f B Q hA i⟩

/-- `𝔤(Aᵀ) → L` is injective: a nonzero ideal of `𝔤(Aᵀ)` meets `𝔥` ([Kac] §1.3), and
`𝔥 → L` is injective since the `hᵢ` are linearly independent. -/
theorem kacMoodyHom_injective : Function.Injective (kacMoodyHom B Q hA) := by
  rw [← LieHom.ker_eq_bot]
  by_contra hne
  obtain ⟨a, ha0, ha⟩ := KacMoodyAlgebra.exists_h_mem_of_ne_bot Q hne
  rw [LieHom.mem_ker, kacMoodyHom_h, Module.Basis.constr_apply_fintype] at ha
  have hc := Fintype.linearIndependent_iff.mp B.linInd _ ha
  exact ha0 ((corootBasis B Q hA).equivFun.injective (funext fun i ↦ by simp [hc i]))

/-- **Serre's theorem**, in the form: a finite-dimensional Lie algebra `L` with a basis `B` in the
sense of `LieAlgebra.Basis` whose matrix is a Cartan matrix of finite type is isomorphic to the
Kac–Moody algebra `𝔤(Aᵀ)`. -/
def kacMoodyEquiv : Q.KacMoodyAlgebra ≃ₗ⁅K⁆ L :=
  LieEquiv.ofBijective (kacMoodyHom B Q hA) ⟨kacMoodyHom_injective B Q hA,
    kacMoodyHom_surjective B Q hA⟩

@[simp] lemma kacMoodyEquiv_apply (x : Q.KacMoodyAlgebra) :
    kacMoodyEquiv B Q hA x = kacMoodyHom B Q hA x :=
  rfl

end LieAlgebra.Basis

namespace RootPairing.GeckConstruction

open Matrix.Realization

variable {ι K M N H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [CharZero K]
  [AddCommGroup M] [Module K M] [AddCommGroup N] [Module K N]
  {P : RootPairing ι K M N} [P.IsReduced] [P.IsCrystallographic] [P.IsIrreducible]
  [P.IsRootSystem] (b : P.Base) [AddCommGroup H] [Module K H] [FiniteDimensional K H]
  (Q : Matrix.Realization b.cartanMatrixᵀ K H)

attribute [local instance 100] LieRing.ofAssociativeRing

/-- **Geck's construction is the Kac–Moody algebra of the root system.** For a reduced,
irreducible, crystallographic root system with base `b` over a field of characteristic zero,
Geck's Lie algebra `RootPairing.GeckConstruction.lieAlgebra b` is isomorphic to the Kac–Moody
algebra `𝔤(A)` of Kac's Cartan matrix `A = b.cartanMatrixᵀ` (`aᵢⱼ = ⟨αᵢ^∨, αⱼ⟩`), for any
realization of `A`; the isomorphism sends `eᵢ, fᵢ, αᵢ^∨` to Geck's `e i, f i, h i`.
(Cf. [Hum] §18.4; the argument is reconstructed, see the module docstring.) -/
def equivKacMoodyAlgebra : Q.KacMoodyAlgebra ≃ₗ⁅K⁆ lieAlgebra b :=
  (basis b).kacMoodyEquiv Q b.cartanMatrix_isFiniteCartan

@[simp] lemma equivKacMoodyAlgebra_e (i : b.support) :
    equivKacMoodyAlgebra b Q (KacMoodyAlgebra.e Q i) = ⟨e i, e_mem_lieAlgebra i⟩ :=
  (basis b).kacMoodyHom_e Q _ i

@[simp] lemma equivKacMoodyAlgebra_f (i : b.support) :
    equivKacMoodyAlgebra b Q (KacMoodyAlgebra.f Q i) = ⟨f i, f_mem_lieAlgebra i⟩ :=
  (basis b).kacMoodyHom_f Q _ i

@[simp] lemma equivKacMoodyAlgebra_h_coroot (i : b.support) :
    equivKacMoodyAlgebra b Q (KacMoodyAlgebra.h Q (Q.coroot i)) = ⟨h i, h_mem_lieAlgebra i⟩ :=
  (basis b).kacMoodyHom_h_coroot Q _ i

/-- **Serre's theorem** for Geck's construction ([Hum] §18.3–18.4): for a reduced,
irreducible, crystallographic root system with base `b` over a field of characteristic zero,
Geck's Lie algebra is isomorphic to the Lie algebra generated by `𝔥` and `eᵢ, fᵢ` subject to the
relations (1.2.1) of [Kac] and the Serre relations `(ad eᵢ)^{1 - aᵢⱼ} eⱼ = 0 = (ad fᵢ)^{1 - aᵢⱼ} fⱼ`
(`i ≠ j`), where `A = b.cartanMatrixᵀ`. This combines `equivKacMoodyAlgebra` with the Gabber–Kac
theorem ([Kac] Thm. 9.11). -/
def equivSerrePresentedAlgebra : Q.SerrePresentedAlgebra ≃ₗ⁅K⁆ lieAlgebra b :=
  have hA := (b.cartanMatrix_isFiniteCartan (P := P)).transpose
  (SerrePresentedAlgebra.equivKacMoody Q hA.isGeneralizedCartan hA.isSymmetrizable).trans
    (equivKacMoodyAlgebra b Q)

/-- Geck's Lie algebra is isomorphic to the Kac–Moody algebra `𝔤(A)`, `A = b.cartanMatrixᵀ`,
built on the standard realization of `A` (`Matrix.Realization.std`). -/
def equivKacMoodyAlgebraStd :
    (Matrix.Realization.std b.cartanMatrixᵀ K).KacMoodyAlgebra ≃ₗ⁅K⁆ lieAlgebra b :=
  equivKacMoodyAlgebra b _

/-- **Serre's theorem**, comparing Mathlib's two constructions ([Hum] §18.3–18.4): for a
reduced, irreducible, crystallographic root system with base `b` over a field of characteristic
zero, Mathlib's `Matrix.ToLieAlgebra K A` (the Lie algebra presented by the Chevalley–Serre
relations, `A = b.cartanMatrixᵀ` in Kac's convention) is isomorphic to Geck's Lie algebra
`RootPairing.GeckConstruction.lieAlgebra b`. -/
def equivToLieAlgebra : Matrix.ToLieAlgebra K b.cartanMatrixᵀ ≃ₗ⁅K⁆ lieAlgebra b :=
  have hA := (b.cartanMatrix_isFiniteCartan (P := P)).transpose
  (KacMoodyAlgebra.toLieAlgebraEquiv (Matrix.Realization.std b.cartanMatrixᵀ K)
    hA.isGeneralizedCartan hA.isSymmetrizable hA.det_pos.ne').trans (equivKacMoodyAlgebraStd b)

end RootPairing.GeckConstruction
