/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.HighestWeight

/-!
# Highest-weight vectors in the category `𝒪`

Let `V ≠ 0` be a module in the category `𝒪` over the Kac–Moody algebra `𝔤(A)`. Then `V` has a
nonzero weight vector `v` killed by all the `eᵢ` (a *primitive* vector): take `v` of a weight
that is maximal among the weights of `V` for the order `μ ≤ ν ↔ ν - μ ∈ Q₊`
([Kac] §9.3). Such a vector is the image of the highest-weight vector of a Verma module
`M(λ)` under a morphism `M(λ) → V`, whose image is the submodule generated by `v`. If `V` is
moreover integrable, then `λ` is dominant integral ([Kac] (3.2.4), as in the proof of
Lemma 10.1). This is used in the
proof of complete reducibility ([Kac] Thm. 10.7).

## Main results

* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.exists_lie_e_eq_zero`: a nonzero module in `𝒪`
  has a nonzero weight vector killed by all the `eᵢ`.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.exists_lieModuleHom_verma`: a nonzero module
  in `𝒪` receives a nonzero morphism from some Verma module `M(λ)`, whose image is the submodule
  generated by a primitive vector of weight `λ`.
* `Matrix.Realization.KacMoodyAlgebra.IsCategoryO.exists_lieModuleHom_verma_of_isIntegrable`:
  if moreover `V` is integrable, `λ` can be taken dominant integral.

## Proof

Let `μ₀` be a weight of `V`. The set `T` of `l ∈ Q₊` such that `μ₀ + l` is a weight of `V` is
finite: its elements lie in the finitely many boxes `0 ≤ l ≤ c_Λ`, where `Λ` runs over the finite
set of vertices of cones containing the weights of `V`, and `c_Λ = Λ - μ₀ ∈ Q₊` (when it is). A
maximal element `l` of `T` gives the weight `μ₀ + l`, and `eᵢ` maps its weight space to the weight
space of `μ₀ + l + αᵢ`, which is zero by maximality. (This is the standard argument; we wrote it
out ourselves.)

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §9.3, §10.1.
-/

open Module LieModule

noncomputable section

namespace Matrix.Realization.KacMoodyAlgebra

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [CharZero K] [AddCommGroup H]
  [Module K H] {A : Matrix ι ι ℤ} {P : Realization A K H}
  {V : Type*} [AddCommGroup V] [Module K V] [LieRingModule P.KacMoodyAlgebra V]
  [LieModule K P.KacMoodyAlgebra V]

namespace IsCategoryO

/-- A module in `𝒪` has a weight vector killed by all the `eᵢ`, of a weight above any given weight
`μ₀`: the vector is taken of a maximal weight. -/
theorem exists_lie_e_eq_zero_of_weightSpace_ne_bot (hV : IsCategoryO P V) {μ₀ : Dual K H}
    (hμ₀ : weightSpace P V μ₀ ≠ ⊥) :
    ∃ l : ι → ℤ, 0 ≤ l ∧ ∃ v ∈ weightSpace P V (μ₀ + P.rootOf l), v ≠ 0 ∧
      ∀ i, ⁅e P i, v⁆ = 0 := by
  classical
  obtain ⟨s, hs⟩ := hV.exists_finset
  set T : Set (ι → ℤ) := {l | 0 ≤ l ∧ weightSpace P V (μ₀ + P.rootOf l) ≠ ⊥} with hT
  let c : Dual K H → ι → ℤ := fun Λ ↦
    if h : ∃ c, P.rootOf c = Λ - μ₀ then h.choose else 0
  have hTfin : T.Finite := by
    refine (s.finite_toSet.biUnion fun Λ _ ↦
      (Set.Finite.pi (t := fun i ↦ Set.Icc 0 (c Λ i)) fun i ↦ Set.finite_Icc _ _)).subset ?_
    rintro l ⟨hl0, hl⟩
    obtain ⟨Λ, hΛs, k, hk, heq⟩ := hs _ hl
    have hlk : P.rootOf (l + k) = Λ - μ₀ := by
      rw [map_add, eq_sub_iff_add_eq, add_comm, ← add_assoc, heq, sub_add_cancel]
    have hex : ∃ c, P.rootOf c = Λ - μ₀ := ⟨l + k, hlk⟩
    have hc : c Λ = l + k := by
      refine P.rootOf_injective ?_
      simp only [c, hex, ↓reduceDIte]
      rw [hex.choose_spec, hlk]
    refine Set.mem_biUnion (x := Λ) hΛs fun i _ ↦ ⟨hl0 i, ?_⟩
    rw [hc, Pi.add_apply, le_add_iff_nonneg_right]
    exact hk i
  have hTne : T.Nonempty := ⟨0, le_rfl, by rwa [map_zero, add_zero]⟩
  obtain ⟨l, ⟨hl0, hl⟩, hmax⟩ := hTfin.exists_maximal hTne
  obtain ⟨v, hv, hv0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hl
  refine ⟨l, hl0, v, hv, hv0, fun i ↦ by_contra fun hne ↦ ?_⟩
  have hmem : l + Pi.single i 1 ∈ T := by
    refine ⟨add_nonneg hl0 (Pi.single_nonneg.mpr zero_le_one), fun hbot ↦ hne ?_⟩
    have := toEnd_e_mem_weightSpace i hv
    rw [add_assoc, ← rootOf_single P i, ← map_add, hbot] at this
    exact this
  have := hmax hmem (le_add_of_nonneg_right (Pi.single_nonneg.mpr zero_le_one)) i
  simp at this

/-- A nonzero module in the category `𝒪` has a nonzero weight vector killed by all the `eᵢ`
([Kac] §9.3). -/
theorem exists_lie_e_eq_zero [Nontrivial V] (hV : IsCategoryO P V) :
    ∃ μ, ∃ v ∈ weightSpace P V μ, v ≠ 0 ∧ ∀ i, ⁅e P i, v⁆ = 0 := by
  obtain ⟨μ₀, hμ₀⟩ : ∃ μ₀, weightSpace P V μ₀ ≠ ⊥ := by
    by_contra! h
    have := hV.iSup_weightSpaceOfMap_eq_top
    simp only [h, iSup_bot] at this
    exact bot_ne_top this
  obtain ⟨l, -, v, hv, hv0, he⟩ := exists_lie_e_eq_zero_of_weightSpace_ne_bot hV hμ₀
  exact ⟨_, v, hv, hv0, he⟩

/-- A nonzero module `V` in the category `𝒪` receives a nonzero morphism `M(λ) → V` from some
Verma module; its image is the submodule generated by a primitive vector of weight `λ`
(`VermaModule.range_eq_lieSpan`) ([Kac] §9.3). -/
theorem exists_lieModuleHom_verma [Nontrivial V] (hV : IsCategoryO P V) :
    ∃ (μ : Dual K H) (φ : VermaModule P μ →ₗ⁅K,P.KacMoodyAlgebra⁆ V),
      φ (VermaModule.hwv P μ) ≠ 0 := by
  obtain ⟨μ, v, hv, hv0, he⟩ := hV.exists_lie_e_eq_zero
  exact ⟨μ, VermaModule.lift P v (fun _ hx ↦ lie_eq_zero_of_mem_nPos he hx) (fun a ↦ hv a),
    by rwa [VermaModule.lift_hwv]⟩

/-- A nonzero integrable module `V` in the category `𝒪` receives a nonzero morphism `M(λ) → V`
from the Verma module of some dominant integral weight `λ` ([Kac] Prop. 9.3 (a), (3.2.4)). -/
theorem exists_lieModuleHom_verma_of_isIntegrable [Nontrivial V] (hA : A.IsGeneralizedCartan)
    (hV : IsCategoryO P V) (hV' : IsIntegrable P V) :
    ∃ (μ : Dual K H), P.IsDominantIntegral μ ∧
      ∃ φ : VermaModule P μ →ₗ⁅K,P.KacMoodyAlgebra⁆ V, φ (VermaModule.hwv P μ) ≠ 0 := by
  obtain ⟨μ, v, hv, hv0, he⟩ := hV.exists_lie_e_eq_zero
  exact ⟨μ, isDominantIntegral_of_isIntegrable hA hV' hv he hv0,
    VermaModule.lift P v (fun _ hx ↦ lie_eq_zero_of_mem_nPos he hx) (fun a ↦ hv a),
    by rwa [VermaModule.lift_hwv]⟩

end IsCategoryO

end Matrix.Realization.KacMoodyAlgebra
