/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.ProjectiveCover

/-!
# Morphisms out of `P(λ)`

Humphreys, GSM 94, Theorem 3.9: `P(λ)` has the unique simple quotient `L(λ)`, every projective in
`𝒪` mapping onto `L(λ)` has `P(λ)` as a direct summand, and `dim Hom(P(λ), M) = [M : L(λ)]` for
`M ∈ 𝒪`.

## Main definitions

* `Matrix.Realization.KacMoodyAlgebra.IsProjectiveCover`: `π : V → L(λ)` surjective with `V ∈ 𝒪`
  and no proper submodule of `V` mapping onto `L(λ)`.

## Main results

* `Matrix.Realization.KacMoodyAlgebra.IsProjectiveCover.exists_generator`: `V` is generated by a
  vector of weight `λ`; `IsProjectiveCover.finrank_hom_le`: `dim Hom(V, X) ≤ dim X_λ`.
* `Matrix.Realization.KacMoodyAlgebra.IsProjectiveCover.finrank_hom_irreducible`:
  `dim Hom(V, L(μ)) = δ_{λμ}`.
* `Matrix.Realization.KacMoodyAlgebra.IsProjectiveCover.finrank_hom_eq_multiplicity`,
  `ProjectiveCover.finrank_hom_eq_multiplicity`: **Theorem 3.9 (c)**,
  `dim Hom(P(λ), M) = [M : L(λ)]` for `M ∈ 𝒪`.
* `Matrix.Realization.KacMoodyAlgebra.IsProjectiveCover.exists_retract`,
  `ProjectiveCover.nonempty_equiv_of_indecomposable`: **Theorem 3.9 (a)**: a projective module in
  `𝒪` mapping onto `L(λ)` has `P(λ)` as a retract, and is isomorphic to `P(λ)` if indecomposable.

## References

* J. E. Humphreys, *Representations of semisimple Lie algebras in the BGG category 𝒪*, GSM 94,
  AMS 2008, §3.9.
-/

noncomputable section

open Module LieModule

universe u₁ u₂ w

namespace Matrix.Realization.KacMoodyAlgebra

open VermaModule

variable {ι : Type u₁} {H : Type u₂} {K : Type} [Fintype ι] [DecidableEq ι] [Field K] [CharZero K]
  [AddCommGroup H] [Module K H] {A : Matrix ι ι ℤ} (P : Realization A K H) (Λ : Dual K H)

local notation "𝔤" => KacMoodyAlgebra P

variable {Λ} in
/-- `π : V → L(λ)` is a **projective cover** in `𝒪` up to projectivity: `V ∈ 𝒪`, `π` is
surjective, and no proper submodule of `V` maps onto `L(λ)`. -/
structure IsProjectiveCover (V : Type*) [AddCommGroup V] [Module K V]
    [LieRingModule P.KacMoodyAlgebra V] [LieModule K P.KacMoodyAlgebra V]
    (π : V →ₗ⁅K,P.KacMoodyAlgebra⁆ IrreducibleModule P Λ) : Prop where
  isCategoryO : IsCategoryO P V
  surjective : Function.Surjective π
  eq_top_of_not_le_ker : ∀ N : LieSubmodule K P.KacMoodyAlgebra V, ¬ N ≤ π.ker → N = ⊤

namespace IsProjectiveCover

variable {P Λ} {V : Type*} [AddCommGroup V] [Module K V] [LieRingModule P.KacMoodyAlgebra V]
  [LieModule K P.KacMoodyAlgebra V] {π : V →ₗ⁅K,P.KacMoodyAlgebra⁆ IrreducibleModule P Λ}
  (hπ : IsProjectiveCover P V π)
include hπ

/-- A projective cover of `L(λ)` is generated by a vector `p` of weight `λ` with `π p = v_λ`. -/
theorem exists_generator : ∃ p ∈ weightSpaceOfMap V (h P) Λ,
    π p = IrreducibleModule.hwv P Λ ∧ LieSubmodule.lieSpan K 𝔤 {p} = ⊤ := by
  have hmem := IrreducibleModule.hwv_mem_weightSpace P Λ
  rw [← map_weightSpace_of_surjective P hπ.isCategoryO.iSup_weightSpaceOfMap_eq_top _
    hπ.surjective] at hmem
  obtain ⟨p, hp, hπp⟩ := hmem
  refine ⟨p, hp, hπp, hπ.eq_top_of_not_le_ker _ fun hle ↦ ?_⟩
  have : p ∈ π.ker := hle (LieSubmodule.subset_lieSpan rfl)
  rw [LieModuleHom.mem_ker] at this
  exact IrreducibleModule.hwv_ne_zero P Λ (hπp.symm.trans this)

omit hπ [CharZero K] [LieModule K P.KacMoodyAlgebra V] in
/-- A morphism killing a generator is zero. -/
theorem eq_zero_of_apply_eq_zero {X : Type*} [AddCommGroup X] [Module K X]
    [LieRingModule P.KacMoodyAlgebra X] [LieModule K P.KacMoodyAlgebra X] {p : V}
    (hp : LieSubmodule.lieSpan K 𝔤 {p} = ⊤) {f : V →ₗ⁅K,𝔤⁆ X} (hf : f p = 0) : f = 0 := by
  have hle : LieSubmodule.lieSpan K 𝔤 {p} ≤ f.ker := by
    rw [LieSubmodule.lieSpan_le, Set.singleton_subset_iff]
    exact hf
  ext y
  have hy : y ∈ f.ker := hle (hp ▸ LieSubmodule.mem_top y)
  exact hy

/-- `dim Hom(V, X) ≤ dim X_λ`: a morphism is determined by the image of the generator. -/
theorem finrank_hom_le {X : Type*} [AddCommGroup X] [Module K X]
    [LieRingModule P.KacMoodyAlgebra X] [LieModule K P.KacMoodyAlgebra X]
    [FiniteDimensional K (weightSpaceOfMap X (h P) Λ)] :
    finrank K (V →ₗ⁅K,𝔤⁆ X) ≤ finrank K (weightSpaceOfMap X (h P) Λ) := by
  obtain ⟨p, hpw, -, hp⟩ := hπ.exists_generator
  let φ : (V →ₗ⁅K,𝔤⁆ X) →ₗ[K] weightSpaceOfMap X (h P) Λ :=
    { toFun f := ⟨f p, map_mem_weightSpaceOfMap P f hpw⟩
      map_add' _ _ := rfl
      map_smul' _ _ := rfl }
  refine LinearMap.finrank_le_finrank_of_injective (f := φ) fun f g hfg ↦ ?_
  rw [← sub_eq_zero]
  refine eq_zero_of_apply_eq_zero hp ?_
  have := congrArg Subtype.val hfg
  simpa [φ, sub_eq_zero] using this

theorem π_ne_zero : π ≠ 0 := fun h0 ↦ by
  obtain ⟨x, hx⟩ := hπ.surjective (IrreducibleModule.hwv P Λ)
  rw [h0] at hx
  exact IrreducibleModule.hwv_ne_zero P Λ hx.symm

/-- `Hom(V, L(μ)) = 0` for `μ ≠ λ`: `L(λ)` is the only simple quotient of a projective cover of
`L(λ)`. -/
theorem hom_irreducible_eq_zero {μ : Dual K H} (hμ : μ ≠ Λ)
    (f : V →ₗ⁅K,𝔤⁆ IrreducibleModule P μ) : f = 0 := by
  by_contra hf0
  have := IrreducibleModule.isIrreducible P μ
  have hf : Function.Surjective f := by
    rw [← LieModuleHom.range_eq_top]
    refine (IsSimpleOrder.eq_bot_or_eq_top f.range).resolve_left fun h0 ↦ hf0 ?_
    ext y
    have : f y ∈ f.range := (LieModuleHom.mem_range _ _).mpr ⟨y, rfl⟩
    rw [h0, LieSubmodule.mem_bot] at this
    exact this
  have hker : f.ker ≤ π.ker := by
    by_contra hle
    have := hπ.eq_top_of_not_le_ker f.ker hle
    exact hf0 (by ext y; exact (this ▸ LieSubmodule.mem_top y : y ∈ f.ker))
  let ℓ := LieSubmodule.Quotient.lift f.ker f le_rfl
  have hℓ : Function.Bijective ℓ := by
    refine ⟨fun x y hxy ↦ ?_, LieSubmodule.Quotient.lift_surjective f.ker f le_rfl hf⟩
    obtain ⟨x, rfl⟩ := LieSubmodule.Quotient.surjective_mk' f.ker x
    obtain ⟨y, rfl⟩ := LieSubmodule.Quotient.surjective_mk' f.ker y
    rw [LieSubmodule.Quotient.lift_mk, LieSubmodule.Quotient.lift_mk] at hxy
    rw [← sub_eq_zero, ← map_sub, LieSubmodule.Quotient.mk_eq_zero, LieModuleHom.mem_ker,
      map_sub, hxy, sub_self]
  let e := LieModuleEquiv.ofBijective ℓ hℓ
  let g := (LieSubmodule.Quotient.lift f.ker π hker).comp e.symm.toLieModuleHom
  have hg (y : V) : g (f y) = π y := by
    change LieSubmodule.Quotient.lift f.ker π hker (e.symm (f y)) = _
    have : e.symm (f y) = LieSubmodule.Quotient.mk' f.ker y := by
      rw [LieModuleEquiv.symm_apply_eq]
      rfl
    rw [this]
    rfl
  have hgs : Function.Surjective g := fun z ↦ by
    obtain ⟨y, rfl⟩ := hπ.surjective z
    exact ⟨f y, hg y⟩
  have hgi : Function.Injective g := by
    rw [← LieModuleHom.ker_eq_bot]
    refine (IsSimpleOrder.eq_bot_or_eq_top g.ker).resolve_right fun htop ↦ ?_
    apply hπ.π_ne_zero
    ext y
    rw [← hg]
    exact (htop ▸ LieSubmodule.mem_top (f y) : f y ∈ g.ker)
  exact hμ (IrreducibleModule.eq_of_equiv P (LieModuleEquiv.ofBijective g ⟨hgi, hgs⟩))

/-- `dim Hom(V, L(λ)) = 1` for a projective cover `V` of `L(λ)` with finite-dimensional
`Hom(V, L(λ))`. -/
theorem finrank_hom_irreducible_self
    [FiniteDimensional K (V →ₗ⁅K,𝔤⁆ IrreducibleModule P Λ)] :
    finrank K (V →ₗ⁅K,𝔤⁆ IrreducibleModule P Λ) = 1 := by
  have hfin : FiniteDimensional K (weightSpaceOfMap (IrreducibleModule P Λ) (h P) Λ) :=
    (IrreducibleModule.isCategoryO P Λ).finiteDimensional_weightSpaceOfMap Λ
  have hle := hπ.finrank_hom_le (X := IrreducibleModule P Λ)
  rw [show finrank K (weightSpaceOfMap (IrreducibleModule P Λ) (h P) Λ) = 1 from
    IrreducibleModule.finrank_weightSpace_self P Λ] at hle
  have hpos : 0 < finrank K (V →ₗ⁅K,𝔤⁆ IrreducibleModule P Λ) :=
    Module.finrank_pos_iff_exists_ne_zero.mpr ⟨π, hπ.π_ne_zero⟩
  omega

/-- Morphisms from a projective cover to a module in `𝒪` form a finite-dimensional space. -/
theorem finiteDimensional_hom {X : Type*} [AddCommGroup X] [Module K X]
    [LieRingModule P.KacMoodyAlgebra X] [LieModule K P.KacMoodyAlgebra X] (hX : IsCategoryO P X) :
    FiniteDimensional K (V →ₗ⁅K,𝔤⁆ X) := by
  have := hX.finiteDimensional_weightSpaceOfMap Λ
  obtain ⟨p, hpw, -, hp⟩ := hπ.exists_generator
  let φ : (V →ₗ⁅K,𝔤⁆ X) →ₗ[K] weightSpaceOfMap X (h P) Λ :=
    { toFun f := ⟨f p, map_mem_weightSpaceOfMap P f hpw⟩
      map_add' _ _ := rfl
      map_smul' _ _ := rfl }
  refine Module.Finite.of_injective φ fun f g hfg ↦ ?_
  rw [← sub_eq_zero]
  refine eq_zero_of_apply_eq_zero hp ?_
  have := congrArg Subtype.val hfg
  simpa [φ, sub_eq_zero] using this

/-- **Exactness of `Hom(V, −)` for `V` projective**: for `A ⊆ B ⊆ X ∈ 𝒪`,
`dim Hom(V, B) = dim Hom(V, A) + dim Hom(V, B/A)`. -/
theorem finrank_hom_eq_add (hproj : IsProjectiveO.{w} P V) {X : Type w}
    [AddCommGroup X] [Module K X] [LieRingModule P.KacMoodyAlgebra X]
    [LieModule K P.KacMoodyAlgebra X] (hX : IsCategoryO P X)
    {A B : LieSubmodule K 𝔤 X} (hAB : A ≤ B) :
    finrank K (V →ₗ⁅K,𝔤⁆ B) = finrank K (V →ₗ⁅K,𝔤⁆ A) +
      finrank K (V →ₗ⁅K,𝔤⁆ A.Subquotient B) := by
  set S := A.comap B.incl
  let Φ : (V →ₗ⁅K,𝔤⁆ B) →ₗ[K] (V →ₗ⁅K,𝔤⁆ A.Subquotient B) :=
    { toFun g := (LieSubmodule.Quotient.mk' S).comp g
      map_add' _ _ := by ext; simp
      map_smul' _ _ := by ext; simp }
  let Ψ : (V →ₗ⁅K,𝔤⁆ A) →ₗ[K] (V →ₗ⁅K,𝔤⁆ B) :=
    { toFun g := (LieSubmodule.inclusion hAB).comp g
      map_add' _ _ := by ext; simp
      map_smul' _ _ := by ext; simp }
  have hBO : IsCategoryO P B := hX.lieSubmodule B
  have := hπ.finiteDimensional_hom hBO
  have := hπ.finiteDimensional_hom (hBO.quotient S)
  have hΦ : Function.Surjective Φ := fun φ ↦ by
    obtain ⟨g, hg⟩ := hproj hBO (hBO.quotient S) (LieSubmodule.Quotient.mk' S)
      (LieSubmodule.Quotient.surjective_mk' S) φ
    exact ⟨g, hg⟩
  have hΨ : Function.Injective Ψ := fun g g' hgg' ↦ by
    ext y
    have := LieModuleHom.congr_fun hgg' y
    simpa [Ψ] using congrArg Subtype.val this
  have hker : LinearMap.ker Φ = LinearMap.range Ψ := by
    ext g
    constructor
    · intro hg
      have hmem (y : V) : ((g y : B) : X) ∈ A := by
        have := LieModuleHom.congr_fun (LinearMap.mem_ker.mp hg) y
        change LieSubmodule.Quotient.mk' S (g y) = 0 at this
        rw [LieSubmodule.Quotient.mk_eq_zero] at this
        exact this
      refine ⟨LieModuleHom.codRestrict A (B.incl.comp g) hmem, ?_⟩
      ext y
      rfl
    · rintro ⟨g', rfl⟩
      rw [LinearMap.mem_ker]
      ext y
      change LieSubmodule.Quotient.mk' S (LieSubmodule.inclusion hAB (g' y)) = 0
      rw [LieSubmodule.Quotient.mk_eq_zero]
      exact (g' y).2
  have h1 := LinearMap.finrank_range_add_finrank_ker Φ
  rw [LinearMap.range_eq_top.mpr hΦ, finrank_top, hker,
    LinearMap.finrank_range_of_inj hΨ] at h1
  omega

/-- `dim Hom(V, Y) = 0` if `Y_λ = 0`. -/
theorem finrank_hom_eq_zero {Y : Type*} [AddCommGroup Y] [Module K Y]
    [LieRingModule P.KacMoodyAlgebra Y] [LieModule K P.KacMoodyAlgebra Y]
    (hY : weightSpaceOfMap Y (h P) Λ = ⊥) : finrank K (V →ₗ⁅K,𝔤⁆ Y) = 0 := by
  have : FiniteDimensional K (weightSpaceOfMap Y (h P) Λ) := by
    rw [hY]; infer_instance
  have h1 := hπ.finrank_hom_le (X := Y)
  have h2 : finrank K (weightSpaceOfMap Y (h P) Λ) = 0 :=
    (LinearEquiv.ofEq _ _ hY).finrank_eq.trans (finrank_bot K Y)
  omega

/-- `dim Hom(V, L(μ)) = δ_{λμ}`. -/
theorem finrank_hom_irreducible [DecidableEq (Dual K H)] (μ : Dual K H) :
    finrank K (V →ₗ⁅K,𝔤⁆ IrreducibleModule P μ) = if μ = Λ then 1 else 0 := by
  split_ifs with hμ
  · subst hμ
    have := hπ.finiteDimensional_hom (IrreducibleModule.isCategoryO P μ)
    exact hπ.finrank_hom_irreducible_self
  · have : Subsingleton (V →ₗ⁅K,𝔤⁆ IrreducibleModule P μ) :=
      ⟨fun f g ↦ (hπ.hom_irreducible_eq_zero hμ f).trans (hπ.hom_irreducible_eq_zero hμ g).symm⟩
    exact Module.finrank_zero_of_subsingleton

/-- **Humphreys, GSM 94, Theorem 3.9 (c).** For a projective cover `V → L(λ)` in `𝒪` (projective
relative to modules in the universe of `X`) and `X ∈ 𝒪`, `dim Hom(V, X) = [X : L(λ)]`. -/
theorem finrank_hom_eq_multiplicity (hproj : IsProjectiveO.{w} P V) {X : Type w}
    [AddCommGroup X] [Module K X] [LieRingModule P.KacMoodyAlgebra X]
    [LieModule K P.KacMoodyAlgebra X] (hX : IsCategoryO P X) :
    finrank K (V →ₗ⁅K,𝔤⁆ X) = hX.multiplicity Λ := by
  classical
  obtain ⟨l, hl⟩ := hX.exists_isLocalCompositionSeries Λ
  rw [← hX.count_factorWeights_eq_multiplicity (mem_cone_self Λ) hl]
  have key : ∀ (l : List (LieSubmodule K 𝔤 X × Option (Dual K H)))
      (N M : LieSubmodule K 𝔤 X), IsLocalCompositionSeries P Λ N l M →
      finrank K (V →ₗ⁅K,𝔤⁆ M) = finrank K (V →ₗ⁅K,𝔤⁆ N) + (factorWeights l).count Λ := by
    intro l
    induction l with
    | nil =>
      intro N M h
      rw [IsLocalCompositionSeries.nil_iff] at h
      subst h
      simp
    | cons a l ih =>
      obtain ⟨N', o⟩ := a
      intro N M h
      obtain ⟨hNN', hfac, hrest⟩ := h
      rw [ih N' M hrest, hπ.finrank_hom_eq_add hproj hX hNN']
      cases o with
      | none =>
        rw [hπ.finrank_hom_eq_zero (hfac Λ (mem_cone_self Λ)), factorWeights_cons_none]
        ring
      | some μ =>
        obtain ⟨-, ⟨e⟩⟩ := hfac
        rw [(lieModuleHomCongr P LieModuleEquiv.refl e).finrank_eq,
          hπ.finrank_hom_irreducible μ, factorWeights_cons_some, List.count_cons]
        by_cases hμ : μ = Λ
        · subst hμ
          simp only [ite_true, beq_self_eq_true]
          omega
        · simp [hμ]
  have h := key l ⊥ ⊤ hl
  have hbot : finrank K (V →ₗ⁅K,𝔤⁆ (⊥ : LieSubmodule K 𝔤 X)) = 0 := by
    have : Subsingleton (V →ₗ⁅K,𝔤⁆ (⊥ : LieSubmodule K 𝔤 X)) :=
      ⟨fun f g ↦ LieModuleHom.ext fun x ↦ Subtype.ext
        (((LieSubmodule.mem_bot _).mp (f x).2).trans ((LieSubmodule.mem_bot _).mp (g x).2).symm)⟩
    exact Module.finrank_zero_of_subsingleton
  have etop : (⊤ : LieSubmodule K 𝔤 X) ≃ₗ⁅K,𝔤⁆ X :=
    LieModuleEquiv.ofBijective (⊤ : LieSubmodule K 𝔤 X).incl
      ⟨Subtype.val_injective, fun x ↦ ⟨⟨x, trivial⟩, rfl⟩⟩
  rw [hbot, zero_add, (lieModuleHomCongr P LieModuleEquiv.refl etop).finrank_eq] at h
  exact h

end IsProjectiveCover

section Retract

namespace IsProjectiveCover

variable {P Λ} {V : Type (max u₁ u₂)} [AddCommGroup V] [Module K V]
  [LieRingModule P.KacMoodyAlgebra V] [LieModule K P.KacMoodyAlgebra V]
  {π : V →ₗ⁅K,P.KacMoodyAlgebra⁆ IrreducibleModule P Λ} (hπ : IsProjectiveCover P V π)
include hπ

/-- **Humphreys, GSM 94, Theorem 3.9 (a), first step.** If `W ∈ 𝒪` is projective and maps onto
`L(λ)`, then a projective cover `V` of `L(λ)` is a retract of `W`. -/
theorem exists_retract {W : Type (max u₁ u₂)} [AddCommGroup W] [Module K W]
    [LieRingModule P.KacMoodyAlgebra W] [LieModule K P.KacMoodyAlgebra W]
    (hproj : IsProjectiveO.{max u₁ u₂} P V) (hWproj : IsProjectiveO.{max u₁ u₂} P W)
    (hW : IsCategoryO P W)
    (φ : W →ₗ⁅K,𝔤⁆ IrreducibleModule P Λ) (hφ : Function.Surjective φ) :
    ∃ (s : V →ₗ⁅K,𝔤⁆ W) (r : W →ₗ⁅K,𝔤⁆ V), r.comp s = LieModuleHom.id := by
  obtain ⟨r, hr⟩ := hWproj hπ.isCategoryO (IrreducibleModule.isCategoryO P Λ) π hπ.surjective φ
  have hrs : Function.Surjective r := by
    rw [← LieModuleHom.range_eq_top]
    refine hπ.eq_top_of_not_le_ker _ fun hle ↦ ?_
    obtain ⟨x, hx⟩ := hφ (IrreducibleModule.hwv P Λ)
    have : r x ∈ π.ker := hle ((LieModuleHom.mem_range _ _).mpr ⟨x, rfl⟩)
    rw [LieModuleHom.mem_ker, ← LieModuleHom.comp_apply, hr, hx] at this
    exact IrreducibleModule.hwv_ne_zero P Λ this
  obtain ⟨s, hs⟩ := hproj hW hπ.isCategoryO r hrs LieModuleHom.id
  exact ⟨s, r, hs⟩

/-- **Humphreys, GSM 94, Theorem 3.9 (a).** An indecomposable projective `W ∈ 𝒪` (every
idempotent endomorphism is `0` or `1`) mapping onto `L(λ)` is isomorphic to the projective cover
`V` of `L(λ)`. (Humphreys' `𝒪` consists of finitely generated modules, which always have a
simple quotient; here the surjection onto `L(λ)` is a hypothesis.) -/
theorem nonempty_equiv_of_indecomposable {W : Type (max u₁ u₂)} [AddCommGroup W] [Module K W]
    [LieRingModule P.KacMoodyAlgebra W] [LieModule K P.KacMoodyAlgebra W]
    (hproj : IsProjectiveO.{max u₁ u₂} P V) (hWproj : IsProjectiveO.{max u₁ u₂} P W)
    (hW : IsCategoryO P W)
    (hind : ∀ a : W →ₗ⁅K,𝔤⁆ W, a.comp a = a → a = 0 ∨ a = LieModuleHom.id)
    (φ : W →ₗ⁅K,𝔤⁆ IrreducibleModule P Λ) (hφ : Function.Surjective φ) :
    Nonempty (V ≃ₗ⁅K,𝔤⁆ W) := by
  obtain ⟨s, r, hrs⟩ := hπ.exists_retract hproj hWproj hW φ hφ
  have hidem : (s.comp r).comp (s.comp r) = s.comp r := by
    ext x
    change s (r (s (r x))) = s (r x)
    rw [← LieModuleHom.comp_apply r s, hrs]
    rfl
  rcases hind _ hidem with h0 | h1
  · exfalso
    apply hπ.π_ne_zero
    ext v
    have := LieModuleHom.congr_fun h0 (s v)
    change s (r (s v)) = 0 at this
    rw [← LieModuleHom.comp_apply r s, hrs] at this
    change s v = 0 at this
    have hv : v = r (s v) := by rw [← LieModuleHom.comp_apply, hrs]; rfl
    rw [hv, this, map_zero, map_zero]
    rfl
  · refine ⟨LieModuleEquiv.ofBijective s ⟨fun a b hab ↦ ?_, fun w ↦ ⟨r w, ?_⟩⟩⟩
    · have := congrArg r hab
      rwa [← LieModuleHom.comp_apply r s, ← LieModuleHom.comp_apply r s, hrs] at this
    · exact LieModuleHom.congr_fun h1 w

end IsProjectiveCover

end Retract

namespace ProjectiveCover

variable [IsAlgClosed K] [FiniteDimensional K H] (hA : A.IsFiniteCartan)

/-- `π_λ : P(λ) → L(λ)` is a projective cover. -/
theorem isProjectiveCover : IsProjectiveCover P (ProjectiveCover P hA Λ) (π P hA Λ) :=
  ⟨isCategoryO P hA Λ, surjective_π P hA Λ, eq_top_of_not_le_ker P hA Λ⟩

/-- **Humphreys, GSM 94, Theorem 3.9 (c).** `dim Hom(P(λ), M) = [M : L(λ)]` for `M ∈ 𝒪`. -/
theorem finrank_hom_eq_multiplicity {X : Type*} [AddCommGroup X] [Module K X]
    [LieRingModule P.KacMoodyAlgebra X] [LieModule K P.KacMoodyAlgebra X] (hX : IsCategoryO P X) :
    finrank K (ProjectiveCover P hA Λ →ₗ⁅K,𝔤⁆ X) = hX.multiplicity Λ :=
  (isProjectiveCover P Λ hA).finrank_hom_eq_multiplicity (isProjectiveO P hA Λ) hX

/-- `dim Hom(P(λ), L(μ)) = δ_{λμ}`: `L(λ)` is the unique simple quotient of `P(λ)`
(Humphreys, GSM 94, §3.9). -/
theorem finrank_hom_irreducible [DecidableEq (Dual K H)] (μ : Dual K H) :
    finrank K (ProjectiveCover P hA Λ →ₗ⁅K,𝔤⁆ IrreducibleModule P μ) = if μ = Λ then 1 else 0 :=
  (isProjectiveCover P Λ hA).finrank_hom_irreducible μ

/-- **Humphreys, GSM 94, Theorem 3.9 (a).** Every indecomposable projective `W ∈ 𝒪` mapping onto
`L(λ)` is isomorphic to `P(λ)`. -/
theorem nonempty_equiv_of_indecomposable {W : Type (max u₁ u₂)} [AddCommGroup W] [Module K W]
    [LieRingModule P.KacMoodyAlgebra W] [LieModule K P.KacMoodyAlgebra W]
    (hWproj : IsProjectiveO.{max u₁ u₂} P W) (hW : IsCategoryO P W)
    (hind : ∀ a : W →ₗ⁅K,𝔤⁆ W, a.comp a = a → a = 0 ∨ a = LieModuleHom.id)
    (φ : W →ₗ⁅K,𝔤⁆ IrreducibleModule P Λ) (hφ : Function.Surjective φ) :
    Nonempty (ProjectiveCover P hA Λ ≃ₗ⁅K,𝔤⁆ W) :=
  (isProjectiveCover P Λ hA).nonempty_equiv_of_indecomposable (isProjectiveO P hA Λ) hWproj hW
    hind φ hφ

end ProjectiveCover

end Matrix.Realization.KacMoodyAlgebra
