/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.RootSpaceDim

/-!
# The Serre relations hold in `𝔤(A)`

Let `A` be a generalized Cartan matrix. The Serre elements `(ad eᵢ)^{1 - aᵢⱼ} eⱼ` and
`(ad fᵢ)^{1 - aᵢⱼ} fⱼ` (`i ≠ j`) of `𝔤̃(A)` lie in the maximal ideal `𝔯`; equivalently the Serre
relations hold in `𝔤(A) = 𝔤̃(A)/𝔯`.

The proof follows [Kac] §3.3: a weight vector `x ∈ 𝔫̃₊` with `[fₖ, x] = 0` for all `k`
generates an ideal contained in `𝔫̃₊` (it is spanned by the `ad e_{i₁} ⋯ ad e_{iₘ} x`), hence
meeting `𝔥` trivially, so `x ∈ 𝔯` ([Kac] Lemma 1.5). For the Serre element
`θ = (ad eᵢ)^{1 - aᵢⱼ} eⱼ` one checks `[fₖ, θ] = 0` directly: for `k ≠ i, j` because `fₖ` commutes
with `eᵢ` and `eⱼ`; for `k = j` using `aᵢⱼ = 0 ↔ aⱼᵢ = 0`; and for `k = i` by the `𝔰𝔩₂`
identity `[f, (ad e)^{m+1} v] = -(m + 1)(λ + m) (ad e)^m v` for `v` with `[f, v] = 0`,
`[h, v] = λ v`.

## Main definitions

* `Matrix.Realization.AuxLieAlgebra.serreE`, `serreF`: the Serre elements, in the same form as
  Mathlib's `CartanMatrix.Relations.adE`: `(ad eᵢ)^{-aᵢⱼ} [eᵢ, eⱼ]`.
* `Matrix.Realization.AuxLieAlgebra.serreIdeal`: the ideal of `𝔤̃(A)` generated by them.

## Main results

* `Matrix.Realization.AuxLieAlgebra.mem_maxIdeal_of_lie_f_eq_zero`: [Kac] Lemma 1.5.
* `Matrix.Realization.AuxLieAlgebra.serreIdeal_le_maxIdeal`: the Serre relations hold in `𝔤(A)`.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §1.5, §3.3
  (stated over `ℂ`).
-/

open FreeLieAlgebra Module LieModule LieAlgebra

noncomputable section

namespace LieAlgebra

variable {K L : Type*} [Field K] [LieRing L] [LieAlgebra K L]

/-- The `𝔰𝔩₂` identity `[f, (ad e)^{m+1} v] = -(m + 1)(λ + m) (ad e)^m v` for a vector `v` with
`[f, v] = 0` and `[h, v] = λ v`, where `[e, f] = h` and `[h, e] = 2e`. -/
lemma lie_f_ad_e_pow_succ {e f h v : L} {c : K} (hef : ⁅e, f⁆ = h) (hhe : ⁅h, e⁆ = (2 : K) • e)
    (hfv : ⁅f, v⁆ = 0) (hhv : ⁅h, v⁆ = c • v) (m : ℕ) :
    ⁅f, (ad K L e ^ (m + 1)) v⁆ = -(((m + 1 : K) * (c + m))) • (ad K L e ^ m) v := by
  have hh : ∀ n : ℕ, ⁅h, (ad K L e ^ n) v⁆ = (c + 2 * n) • (ad K L e ^ n) v := by
    intro n
    induction n with
    | zero => simpa using hhv
    | succ n ih =>
      rw [pow_succ', Module.End.mul_apply, ad_apply, leibniz_lie, hhe, ih, smul_lie, lie_smul,
        ← add_smul]
      push_cast; congr 1; ring
  have hsucc : ∀ (n : ℕ) (w : L), ⁅e, (ad K L e ^ n) w⁆ = (ad K L e ^ (n + 1)) w := by
    intro n w; rw [pow_succ', Module.End.mul_apply, ad_apply]
  induction m with
  | zero =>
    rw [zero_add, pow_one, ad_apply, leibniz_lie, ← lie_skew f e, hef, hfv, lie_zero, add_zero,
      neg_lie, hhv]
    simp
  | succ m ih =>
    rw [← hsucc, leibniz_lie, ← lie_skew f e, hef, neg_lie, hh, ih, lie_smul, hsucc,
      ← neg_smul, ← add_smul]
    congr 1; push_cast; ring

/-- Lie algebra morphisms commute with iterated adjoint actions. -/
lemma _root_.LieHom.map_ad_pow {L' : Type*} [LieRing L']
    [LieAlgebra K L'] (φ : L →ₗ⁅K⁆ L') (x y : L) (n : ℕ) :
    φ ((ad K L x ^ n) y) = (ad K L' (φ x) ^ n) (φ y) := by
  induction n with
  | zero => simp
  | succ n ih => rw [pow_succ', Module.End.mul_apply, ad_apply, LieHom.map_lie, ih, pow_succ',
      Module.End.mul_apply, ad_apply]

lemma ad_neg_pow_apply (x y : L) (n : ℕ) :
    (ad K L (-x) ^ n) y = (-1 : K) ^ n • (ad K L x ^ n) y := by
  induction n with
  | zero => simp
  | succ n ih =>
    have e1 : (ad K L (-x) ^ (n + 1)) y = ⁅-x, (ad K L (-x) ^ n) y⁆ := by
      rw [pow_succ', Module.End.mul_apply, ad_apply]
    have e2 : (ad K L x ^ (n + 1)) y = ⁅x, (ad K L x ^ n) y⁆ := by
      rw [pow_succ', Module.End.mul_apply, ad_apply]
    rw [e1, e2, ih, neg_lie, lie_smul, pow_succ, mul_neg_one, neg_smul]

end LieAlgebra

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H)

namespace AuxLieAlgebra

lemma range_eHom_inf_range_h :
    LinearMap.range (eHom P : FreeLieAlgebra K ι →ₗ[K] P.AuxLieAlgebra) ⊓ LinearMap.range (h P)
      = ⊥ := by
  refine eq_bot_iff.mpr fun x ⟨⟨z, hz⟩, ⟨a, ha⟩⟩ ↦ ?_
  have hz' : eHom P z = x := hz
  have h0 : triangularMap P (0, -a, z) = triangularMap P 0 := by
    rw [triangularMap_apply, map_neg, ha, hz', map_zero, zero_add, neg_add_cancel, map_zero]
  have := congr_arg (fun p ↦ p.2.2) (triangularMap_injective P h0)
  simp only [Prod.snd_zero] at this
  rw [← hz', this, map_zero]
  exact Submodule.zero_mem _

/-- The span of the `ad e_{i₁} ⋯ ad e_{iₘ} x`. -/
def eSpan (x : P.AuxLieAlgebra) : Submodule K P.AuxLieAlgebra :=
  Submodule.span K (Set.range fun l : List ι ↦ adProd (l.map (e P)) x)

lemma lie_e_mem_eSpan (x : P.AuxLieAlgebra) (i : ι) :
    ∀ y ∈ eSpan P x, ⁅e P i, y⁆ ∈ eSpan P x := by
  intro y hy
  induction hy using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨l, rfl⟩ := hy
    exact Submodule.subset_span ⟨i :: l, rfl⟩
  | zero => simp
  | add y z _ _ hy hz => rw [lie_add]; exact add_mem hy hz
  | smul c y _ hy => rw [lie_smul]; exact Submodule.smul_mem _ c hy

lemma adProd_mem_rootSpace_of_mem {μ : Dual K H} {x : P.AuxLieAlgebra} (hx : x ∈ rootSpace P μ)
    (l : List ι) : adProd (l.map (e P)) x ∈ rootSpace P (wordWt P l + μ) := by
  induction l with
  | nil => simpa using hx
  | cons i l ih =>
    rw [List.map_cons, adProd_cons, wordWt_cons, add_assoc]
    exact lie_mem_rootSpace P (e_mem_rootSpace P i) ih

lemma lie_h_mem_eSpan {μ : Dual K H} {x : P.AuxLieAlgebra} (hx : x ∈ rootSpace P μ) (a : H) :
    ∀ y ∈ eSpan P x, ⁅h P a, y⁆ ∈ eSpan P x := by
  intro y hy
  induction hy using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨l, rfl⟩ := hy
    rw [adProd_mem_rootSpace_of_mem P hx l a]
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨l, rfl⟩)
  | zero => simp
  | add y z _ _ hy hz => rw [lie_add]; exact add_mem hy hz
  | smul c y _ hy => rw [lie_smul]; exact Submodule.smul_mem _ c hy

lemma lie_f_mem_eSpan {μ : Dual K H} {x : P.AuxLieAlgebra} (hx : x ∈ rootSpace P μ)
    (hfx : ∀ k, ⁅f P k, x⁆ = 0) (j : ι) : ∀ y ∈ eSpan P x, ⁅f P j, y⁆ ∈ eSpan P x := by
  have key : ∀ l : List ι, ⁅f P j, adProd (l.map (e P)) x⁆ ∈ eSpan P x := by
    intro l
    induction l with
    | nil => simp [hfx j]
    | cons i l ih =>
      rw [List.map_cons, adProd_cons, leibniz_lie, ← lie_skew (f P j) (e P i), lie_e_f, neg_lie]
      refine add_mem (neg_mem ?_) (lie_e_mem_eSpan P x i _ ih)
      split_ifs
      · exact lie_h_mem_eSpan P hx _ _ (Submodule.subset_span ⟨l, rfl⟩)
      · simp
  intro y hy
  induction hy using Submodule.span_induction with
  | mem y hy => obtain ⟨l, rfl⟩ := hy; exact key l
  | zero => simp
  | add y z _ _ hy hz => rw [lie_add]; exact add_mem hy hz
  | smul c y _ hy => rw [lie_smul]; exact Submodule.smul_mem _ c hy

lemma eSpan_le_range_eHom {x : P.AuxLieAlgebra}
    (hx : x ∈ LinearMap.range (eHom P : FreeLieAlgebra K ι →ₗ[K] P.AuxLieAlgebra)) :
    eSpan P x ≤ LinearMap.range (eHom P : FreeLieAlgebra K ι →ₗ[K] P.AuxLieAlgebra) := by
  rw [eSpan, Submodule.span_le]
  rintro _ ⟨l, rfl⟩
  induction l with
  | nil => exact hx
  | cons i l ih =>
    obtain ⟨z, hz⟩ := ih
    have hz' : eHom P z = _ := hz
    exact ⟨⁅FreeLieAlgebra.of K i, z⁆, by simp [hz']⟩

/-- The positive Serre element `(ad eᵢ)^{-aᵢⱼ} [eᵢ, eⱼ] = (ad eᵢ)^{1 - aᵢⱼ} eⱼ`. -/
def serreE (i j : ι) : P.AuxLieAlgebra := (ad K _ (e P i) ^ (-A i j).toNat) ⁅e P i, e P j⁆

/-- The negative Serre element `(ad fᵢ)^{-aᵢⱼ} [fᵢ, fⱼ] = (ad fᵢ)^{1 - aᵢⱼ} fⱼ`. -/
def serreF (i j : ι) : P.AuxLieAlgebra := (ad K _ (f P i) ^ (-A i j).toNat) ⁅f P i, f P j⁆

/-- The ideal of `𝔤̃(A)` generated by the Serre elements `serreE i j`, `serreF i j` (`i ≠ j`). -/
def serreIdeal : LieIdeal K P.AuxLieAlgebra :=
  LieSubmodule.lieSpan K _ {x | ∃ i j, i ≠ j ∧ (x = serreE P i j ∨ x = serreF P i j)}

lemma serreE_eq (i j : ι) : serreE P i j = (ad K _ (e P i) ^ ((-A i j).toNat + 1)) (e P j) := by
  rw [serreE, pow_succ, Module.End.mul_apply, ad_apply]

lemma lie_f_ad_e_pow_of_lie_eq_zero {k i : ι} (hki : ⁅f P k, e P i⁆ = 0) (n : ℕ)
    (y : P.AuxLieAlgebra) : ⁅f P k, (ad K _ (e P i) ^ n) y⁆ = (ad K _ (e P i) ^ n) ⁅f P k, y⁆ := by
  induction n generalizing y with
  | zero => simp
  | succ n ih =>
    rw [pow_succ, Module.End.mul_apply, ih, Module.End.mul_apply, ad_apply, ad_apply,
      leibniz_lie, hki, zero_lie, zero_add]

lemma serreE_mem_rootSpace (i j : ι) :
    serreE P i j ∈ rootSpace P (((-A i j).toNat + 1) • P.root i + P.root j) := by
  rw [serreE_eq]
  induction (-A i j).toNat + 1 with
  | zero => simpa using e_mem_rootSpace P j
  | succ n ih =>
    rw [pow_succ', Module.End.mul_apply, ad_apply, succ_nsmul', add_assoc]
    exact lie_mem_rootSpace P (e_mem_rootSpace P i) ih

lemma serreE_mem_range_eHom (i j : ι) :
    serreE P i j ∈ LinearMap.range (eHom P : FreeLieAlgebra K ι →ₗ[K] P.AuxLieAlgebra) := by
  rw [serreE_eq]
  induction (-A i j).toNat + 1 with
  | zero => exact ⟨FreeLieAlgebra.of K j, by simp⟩
  | succ n ih =>
    obtain ⟨z, hz⟩ := ih
    have hz' : eHom P z = _ := hz
    refine ⟨⁅FreeLieAlgebra.of K i, z⁆, ?_⟩
    rw [pow_succ', Module.End.mul_apply, ad_apply]
    simp [hz']

lemma chevalleyInvolution_serreE (i j : ι) :
    chevalleyInvolution P (serreE P i j) = (-1 : K) ^ (-A i j).toNat • serreF P i j := by
  rw [serreE, serreF, LieHom.map_ad_pow, LieHom.map_lie, chevalleyInvolution_e,
    chevalleyInvolution_e, neg_lie, lie_neg, neg_neg, ad_neg_pow_apply]

variable [CharZero K]

/-- A weight vector `x ∈ 𝔫̃₊` with `[fₖ, x] = 0` for all `k` lies in `𝔯` ([Kac] Lemma 1.5). -/
theorem mem_maxIdeal_of_lie_f_eq_zero {μ : Dual K H} {x : P.AuxLieAlgebra}
    (hx : x ∈ rootSpace P μ)
    (hxe : x ∈ LinearMap.range (eHom P : FreeLieAlgebra K ι →ₗ[K] P.AuxLieAlgebra))
    (hfx : ∀ k, ⁅f P k, x⁆ = 0) : x ∈ maxIdeal P := by
  let I := idealOfGenerators (eSpan P x) (lie_e_mem_eSpan P x) (lie_f_mem_eSpan P hx hfx)
    (lie_h_mem_eSpan P hx)
  have hI : I ≤ maxIdeal P := by
    rw [le_maxIdeal_iff, eq_bot_iff]
    refine le_trans (inf_le_inf_right _ (eSpan_le_range_eHom P hxe)) ?_
    rw [range_eHom_inf_range_h]
  exact hI (Submodule.subset_span ⟨[], rfl⟩)

/-- `ω(𝔯) ⊆ 𝔯`, where `ω` is the Chevalley involution. -/
lemma chevalleyInvolution_mem_maxIdeal {x : P.AuxLieAlgebra} (hx : x ∈ maxIdeal P) :
    chevalleyInvolution P x ∈ maxIdeal P := by
  have hle : LieIdeal.comap (chevalleyInvolution P) (maxIdeal P) ≤ maxIdeal P := by
    rw [le_maxIdeal_iff, eq_bot_iff]
    rintro _ ⟨hy, ⟨a, rfl⟩⟩
    have hy' : chevalleyInvolution P (h P a) ∈ maxIdeal P := hy
    rw [chevalleyInvolution_h, ← map_neg] at hy'
    have := (Submodule.eq_bot_iff _).mp (maxIdeal_inf_range_h P) _
      ⟨hy', LinearMap.mem_range_self _ _⟩
    rw [map_neg, neg_eq_zero] at this
    exact this
  apply hle
  change chevalleyInvolution P (chevalleyInvolution P x) ∈ maxIdeal P
  rwa [chevalleyInvolution_chevalleyInvolution]

variable (hA : A.IsGeneralizedCartan)
include hA

lemma lie_f_serreE {i j : ι} (hij : i ≠ j) (k : ι) : ⁅f P k, serreE P i j⁆ = 0 := by
  rw [serreE_eq]
  set n := (-A i j).toNat
  have hn : (n : ℤ) = -A i j := hA.toNat_neg_eq hij
  by_cases hki : k = i
  · subst hki
    have hef : ⁅e P k, f P k⁆ = h P (P.coroot k) := lie_e_f_self P k
    have hhe : ⁅h P (P.coroot k), e P k⁆ = (2 : K) • e P k := by
      rw [lie_h_e, P.root_coroot, hA.diag]; simp
    have hfv : ⁅f P k, e P j⁆ = 0 := by rw [← lie_skew, lie_e_f_of_ne P (Ne.symm hij), neg_zero]
    have hhv : ⁅h P (P.coroot k), e P j⁆ = (A k j : K) • e P j := by
      rw [lie_h_e, P.root_coroot]
    rw [lie_f_ad_e_pow_succ hef hhe hfv hhv n]
    have : (A k j : K) + n = 0 := by exact_mod_cast (by omega : (A k j : ℤ) + n = 0)
    simp [this]
  · by_cases hkj : k = j
    · subst hkj
      have hki' : ⁅f P k, e P i⁆ = 0 := by rw [← lie_skew, lie_e_f_of_ne P (Ne.symm hki),
        neg_zero]
      have hfe : ⁅f P k, e P k⁆ = -(h P (P.coroot k)) := by rw [← lie_skew, lie_e_f_self]
      rw [lie_f_ad_e_pow_of_lie_eq_zero P hki', hfe, pow_succ, Module.End.mul_apply, ad_apply,
        lie_neg, ← lie_skew, neg_neg, lie_h_e, P.root_coroot, map_smul]
      rcases Nat.eq_zero_or_pos n with hn0 | hn0
      · have hA0 : A i k = 0 := by omega
        rw [(hA.zero_comm i k).mp hA0]; simp
      · obtain ⟨m, hm⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
        rw [hm, pow_succ, Module.End.mul_apply, ad_apply, lie_self, map_zero, smul_zero]
    · have hki' : ⁅f P k, e P i⁆ = 0 := by rw [← lie_skew, lie_e_f_of_ne P (Ne.symm hki),
        neg_zero]
      have hkj' : ⁅f P k, e P j⁆ = 0 := by rw [← lie_skew, lie_e_f_of_ne P (Ne.symm hkj),
        neg_zero]
      rw [lie_f_ad_e_pow_of_lie_eq_zero P hki', hkj', map_zero]

/-- The positive Serre elements lie in `𝔯`. -/
theorem serreE_mem_maxIdeal {i j : ι} (hij : i ≠ j) : serreE P i j ∈ maxIdeal P :=
  mem_maxIdeal_of_lie_f_eq_zero P (serreE_mem_rootSpace P i j) (serreE_mem_range_eHom P i j)
    (lie_f_serreE P hA hij)

/-- The negative Serre elements lie in `𝔯`. -/
theorem serreF_mem_maxIdeal {i j : ι} (hij : i ≠ j) : serreF P i j ∈ maxIdeal P := by
  have h := chevalleyInvolution_mem_maxIdeal P (serreE_mem_maxIdeal P hA hij)
  rw [chevalleyInvolution_serreE] at h
  have := (maxIdeal P).smul_mem ((-1 : K) ^ (-A i j).toNat) h
  rwa [smul_smul, ← mul_pow, neg_one_mul, neg_neg, one_pow, one_smul] at this

/-- The Serre relations hold in `𝔤(A)`: the ideal generated by the Serre elements is contained in
`𝔯` ([Kac] §3.3). -/
theorem serreIdeal_le_maxIdeal : serreIdeal P ≤ maxIdeal P := by
  rw [serreIdeal, LieSubmodule.lieSpan_le]
  rintro _ ⟨i, j, hij, rfl | rfl⟩
  exacts [serreE_mem_maxIdeal P hA hij, serreF_mem_maxIdeal P hA hij]

end AuxLieAlgebra

end Matrix.Realization

end
