/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.Quotient
import Mathlib.Algebra.Lie.Free
import Mathlib.Algebra.Lie.UniversalEnveloping
import Mathlib.Algebra.RingQuot
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# The associative Serre algebra

Let `A = (aᵢⱼ)_{i,j ∈ I}` be a square integer matrix and `K` a commutative ring. For `i ≠ j` put
`nᵢⱼ = 1 - aᵢⱼ` (more precisely `nᵢⱼ = max(-aᵢⱼ, 0) + 1`, which is `1 - aᵢⱼ` for a generalized
Cartan matrix). The *associative Serre algebra* is the associative `K`-algebra generated by
elements `θᵢ` (`i ∈ I`) subject to the associative Serre relations
`∑_{r + s = nᵢⱼ} (-1)^r (nᵢⱼ choose r) θᵢ^r θⱼ θᵢ^s = 0` (`i ≠ j`).

In the free associative algebra, the Serre element `∑_{r+s=n} (-1)^r (n choose r) θᵢ^r θⱼ θᵢ^s`
equals `(ad (-θᵢ))^n θⱼ = (-1)^n (ad θᵢ)^n θⱼ` (`Matrix.serreAssocElem_eq_ad_neg_pow`). Note the
sign `(-1)^n`: the sum with `(-1)^r` in front of `θᵢ^r θⱼ θᵢ^{n-r}` is `(-1)^n (ad θᵢ)^n θⱼ`, not
`(ad θᵢ)^n θⱼ`; the two differ by a unit, so they generate the same ideal.

Let `𝔫̂(A)` be the Lie algebra generated by elements `θᵢ` subject to the Lie Serre relations
`(ad θᵢ)^{nᵢⱼ} θⱼ = 0` (`i ≠ j`), i.e. the free Lie algebra on `I` modulo the ideal generated by
the Lie Serre elements. By `Matrix.Realization.SerrePresentedAlgebra.serreLieAlgebraEquivRangeFHom`
it is the negative part `𝔫̂₋` of the Serre-presented algebra `𝔤̂(A)`, and by the Gabber–Kac
theorem it is the negative part `𝔫₋` of `𝔤(A)` for symmetrizable `A`
(`Matrix.Realization.KacMoodyAlgebra.serreLieAlgebraEquivNNeg`).

**Theorem** (`Matrix.SerreAssocAlgebra.equivUniversalEnveloping`). The associative Serre algebra
is the universal enveloping algebra of `𝔫̂(A)`, via `θᵢ ↦ θᵢ`.

The proof is by universal properties: the enveloping algebra of the free Lie algebra is the free
associative algebra, and imposing Lie relations on a Lie algebra imposes the same relations on its
enveloping algebra. It is standard; the argument is written out here in full.

## Main definitions

* `Matrix.serreAssocElem K A i j`: the associative Serre element
  `∑_{r+s=nᵢⱼ} (-1)^r (nᵢⱼ choose r) θᵢ^r θⱼ θᵢ^s` in the free algebra `FreeAlgebra K ι`.
* `Matrix.serreAssocIdeal K A`: the two-sided ideal of `FreeAlgebra K ι` generated by the
  `serreAssocElem K A i j`, `i ≠ j`.
* `Matrix.SerreAssocAlgebra K A`: the associative Serre algebra, as the `RingQuot` of
  `FreeAlgebra K ι` by the relations `serreAssocElem K A i j = 0`, `i ≠ j`.
* `Matrix.SerreAssocAlgebra.mkAlgHom`, `Matrix.SerreAssocAlgebra.θ`,
  `Matrix.SerreAssocAlgebra.lift`: the projection from the free algebra, the generators, and the
  universal property.
* `Matrix.serreLieElem K A i j`: the Lie Serre element `(ad θᵢ)^{nᵢⱼ} θⱼ` of `FreeLieAlgebra K ι`.
* `Matrix.serreLieIdeal K A`, `Matrix.SerreLieAlgebra K A`: the ideal they generate and the
  quotient `𝔫̂(A)`.

## Main results

* `Matrix.serreAssocElem_eq_ad_neg_pow`, `Matrix.serreAssocElem_eq_neg_one_pow_smul_ad_pow`: the
  Serre element is `(ad (-θᵢ))^n θⱼ = (-1)^n (ad θᵢ)^n θⱼ`.
* `Matrix.SerreAssocAlgebra.ker_mkAlgHom`: the kernel of `FreeAlgebra K ι → SerreAssocAlgebra K A`
  is `serreAssocIdeal K A`.
* `Matrix.SerreAssocAlgebra.equivUniversalEnveloping`: `SerreAssocAlgebra K A ≃ₐ[K] U(𝔫̂(A))`.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §1.2–1.3,
  §9.11.
-/

open Finset LieAlgebra

noncomputable section

namespace LieAlgebra

section Ad

attribute [local instance 100] LieRing.ofAssociativeRing

variable {K B : Type*} [CommRing K] [Ring B] [Algebra K B]

/-- In an associative algebra, `(ad (-x))^n y = ∑_{r+s=n} (-1)^r (n choose r) x^r y x^s`. -/
theorem ad_neg_pow_apply_eq_sum (x y : B) (n : ℕ) :
    (ad K B (-x) ^ n) y =
      ∑ r ∈ range (n + 1), ((-1 : K) ^ r * n.choose r) • (x ^ r * y * x ^ (n - r)) := by
  have had : ad K B (-x) = -LinearMap.mulLeft K x + LinearMap.mulRight K x := by
    rw [ad_eq_lmul_left_sub_lmul_right]
    ext z
    simp
  have hc : Commute (-LinearMap.mulLeft K x) (LinearMap.mulRight K x) :=
    (LinearMap.commute_mulLeft_right x x).neg_left
  rw [had, hc.add_pow, LinearMap.sum_apply]
  refine sum_congr rfl fun r _ ↦ ?_
  rw [neg_pow, LinearMap.pow_mulLeft, LinearMap.pow_mulRight, Module.End.mul_apply,
    Module.End.mul_apply, Module.End.mul_apply, LinearMap.mulRight_apply, LinearMap.mulLeft_apply,
    Module.End.natCast_apply, mul_smul]
  rcases Nat.even_or_odd r with hr | hr <;>
    simp [hr.neg_one_pow, Nat.cast_smul_eq_nsmul, mul_assoc, (Nat.cast_commute _ _).eq]

end Ad

end LieAlgebra

namespace Matrix

variable {K L : Type*} [CommRing K] [LieRing L] [LieAlgebra K L]

private lemma ad_neg_pow_apply_aux (x y : L) (n : ℕ) :
    (ad K L (-x) ^ n) y = (-1 : K) ^ n • (ad K L x ^ n) y := by
  induction n with
  | zero => simp
  | succ n ih =>
    have e1 : (ad K L (-x) ^ (n + 1)) y = ⁅-x, (ad K L (-x) ^ n) y⁆ := by
      rw [pow_succ', Module.End.mul_apply, ad_apply]
    have e2 : (ad K L x ^ (n + 1)) y = ⁅x, (ad K L x ^ n) y⁆ := by
      rw [pow_succ', Module.End.mul_apply, ad_apply]
    rw [e1, e2, ih, neg_lie, lie_smul, pow_succ, mul_neg_one, neg_smul]

private lemma map_ad_pow_aux {L' : Type*} [LieRing L'] [LieAlgebra K L'] (φ : L →ₗ⁅K⁆ L')
    (x y : L) (n : ℕ) : φ ((ad K L x ^ n) y) = (ad K L' (φ x) ^ n) (φ y) := by
  induction n with
  | zero => simp
  | succ n ih => rw [pow_succ', Module.End.mul_apply, ad_apply, LieHom.map_lie, ih, pow_succ',
      Module.End.mul_apply, ad_apply]

variable {ι : Type*} (K) (A : Matrix ι ι ℤ)

/-! ### The associative Serre algebra -/

/-- The **associative Serre element** `∑_{r+s=n} (-1)^r (n choose r) θᵢ^r θⱼ θᵢ^s` of the free
associative algebra on `ι`, where `n = max(-aᵢⱼ, 0) + 1` (which is `1 - aᵢⱼ` for a generalized
Cartan matrix and `i ≠ j`). It equals `(-1)^n (ad θᵢ)^n θⱼ`
(`Matrix.serreAssocElem_eq_neg_one_pow_smul_ad_pow`). -/
def serreAssocElem (i j : ι) : FreeAlgebra K ι :=
  ∑ r ∈ range ((-A i j).toNat + 1 + 1), ((-1 : K) ^ r * ((-A i j).toNat + 1).choose r) •
    (FreeAlgebra.ι K i ^ r * FreeAlgebra.ι K j * FreeAlgebra.ι K i ^ ((-A i j).toNat + 1 - r))

/-- The relations `serreAssocElem K A i j = 0` (`i ≠ j`) of the associative Serre algebra. -/
inductive SerreAssocRel : FreeAlgebra K ι → FreeAlgebra K ι → Prop
  | serre {i j : ι} (hij : i ≠ j) : SerreAssocRel (serreAssocElem K A i j) 0

/-- The two-sided ideal of the free associative algebra generated by the associative Serre
elements `serreAssocElem K A i j`, `i ≠ j`. -/
def serreAssocIdeal : TwoSidedIdeal (FreeAlgebra K ι) :=
  TwoSidedIdeal.span {x | ∃ i j, i ≠ j ∧ serreAssocElem K A i j = x}

/-- The **associative Serre algebra**: the associative `K`-algebra generated by elements `θᵢ`
(`i ∈ ι`) subject to the relations
`∑_{r+s=nᵢⱼ} (-1)^r (nᵢⱼ choose r) θᵢ^r θⱼ θᵢ^s = 0` (`i ≠ j`), where
`nᵢⱼ = max(-aᵢⱼ, 0) + 1`. It is the quotient of `FreeAlgebra K ι` by `serreAssocIdeal K A`
(`Matrix.SerreAssocAlgebra.ker_mkAlgHom`), and it is the universal enveloping algebra of the
Lie algebra `Matrix.SerreLieAlgebra K A` (`Matrix.SerreAssocAlgebra.equivUniversalEnveloping`).
-/
abbrev SerreAssocAlgebra : Type _ := RingQuot (SerreAssocRel K A)

section Ad

attribute [local instance 100] LieRing.ofAssociativeRing

/-- The associative Serre element is `(ad (-θᵢ))^n θⱼ`. -/
theorem serreAssocElem_eq_ad_neg_pow (i j : ι) :
    serreAssocElem K A i j =
      (ad K _ (-FreeAlgebra.ι K i) ^ ((-A i j).toNat + 1)) (FreeAlgebra.ι K j) :=
  (ad_neg_pow_apply_eq_sum _ _ _).symm

/-- The associative Serre element is `(-1)^n (ad θᵢ)^n θⱼ`. -/
theorem serreAssocElem_eq_neg_one_pow_smul_ad_pow (i j : ι) :
    serreAssocElem K A i j = (-1 : K) ^ ((-A i j).toNat + 1) •
      (ad K _ (FreeAlgebra.ι K i) ^ ((-A i j).toNat + 1)) (FreeAlgebra.ι K j) := by
  rw [serreAssocElem_eq_ad_neg_pow, ad_neg_pow_apply_aux]

variable {K A}

/-- The image of an associative Serre element under an algebra morphism. -/
theorem map_serreAssocElem {B : Type*} [Ring B] [Algebra K B] (f : FreeAlgebra K ι →ₐ[K] B)
    (i j : ι) : f (serreAssocElem K A i j) =
      (ad K B (-f (FreeAlgebra.ι K i)) ^ ((-A i j).toNat + 1)) (f (FreeAlgebra.ι K j)) := by
  rw [ad_neg_pow_apply_eq_sum, serreAssocElem, map_sum]
  simp only [map_smul, map_mul, map_pow]

end Ad

namespace SerreAssocAlgebra

/-- The projection `FreeAlgebra K ι → SerreAssocAlgebra K A`. -/
def mkAlgHom : FreeAlgebra K ι →ₐ[K] SerreAssocAlgebra K A :=
  RingQuot.mkAlgHom K (SerreAssocRel K A)

lemma mkAlgHom_surjective : Function.Surjective (mkAlgHom K A) :=
  RingQuot.mkAlgHom_surjective K _

/-- The generator `θᵢ` of the associative Serre algebra. -/
def θ (i : ι) : SerreAssocAlgebra K A := mkAlgHom K A (FreeAlgebra.ι K i)

@[simp] lemma mkAlgHom_ι (i : ι) : mkAlgHom K A (FreeAlgebra.ι K i) = θ K A i := rfl

variable {K A}

lemma mkAlgHom_serreAssocElem {i j : ι} (hij : i ≠ j) :
    mkAlgHom K A (serreAssocElem K A i j) = 0 := by
  rw [mkAlgHom, RingQuot.mkAlgHom_rel K (SerreAssocRel.serre hij), map_zero]

/-- The **associative Serre relations** hold in `SerreAssocAlgebra K A`. -/
theorem sum_eq_zero {i j : ι} (hij : i ≠ j) :
    ∑ r ∈ range ((-A i j).toNat + 1 + 1), ((-1 : K) ^ r * ((-A i j).toNat + 1).choose r) •
      (θ K A i ^ r * θ K A j * θ K A i ^ ((-A i j).toNat + 1 - r)) = 0 := by
  rw [← mkAlgHom_serreAssocElem hij, serreAssocElem, map_sum]
  simp only [map_smul, map_mul, map_pow, mkAlgHom_ι]

section Ad

attribute [local instance 100] LieRing.ofAssociativeRing

/-- The Serre relations `(ad θᵢ)^{nᵢⱼ} θⱼ = 0` in `SerreAssocAlgebra K A`. -/
theorem ad_pow_θ {i j : ι} (hij : i ≠ j) :
    (ad K _ (θ K A i) ^ ((-A i j).toNat + 1)) (θ K A j) = 0 := by
  have h := mkAlgHom_serreAssocElem (K := K) (A := A) hij
  rw [map_serreAssocElem, mkAlgHom_ι, mkAlgHom_ι, ad_neg_pow_apply_aux] at h
  have := congrArg (fun x ↦ (-1 : K) ^ ((-A i j).toNat + 1) • x) h
  simpa [smul_smul, ← mul_pow] using this

end Ad

variable {B : Type*} [Ring B] [Algebra K B]

/-- Two algebra morphisms out of `SerreAssocAlgebra K A` agreeing on the generators `θᵢ` are
equal. -/
@[ext]
theorem hom_ext {f g : SerreAssocAlgebra K A →ₐ[K] B} (h : ∀ i, f (θ K A i) = g (θ K A i)) :
    f = g :=
  RingQuot.ringQuot_ext' K _ _ (FreeAlgebra.hom_ext (funext h))

/-- The **universal property** of the associative Serre algebra: algebra morphisms out of
`SerreAssocAlgebra K A` correspond to algebra morphisms out of the free algebra `FreeAlgebra K ι`
killing the associative Serre elements. -/
def lift : {f : FreeAlgebra K ι →ₐ[K] B // ∀ i j, i ≠ j → f (serreAssocElem K A i j) = 0} ≃
    (SerreAssocAlgebra K A →ₐ[K] B) :=
  (Equiv.subtypeEquivRight fun f ↦ ⟨fun hf x y hxy ↦ by
    obtain ⟨hij⟩ := hxy
    rw [hf _ _ hij, map_zero], fun hf i j hij ↦ by
    rw [hf (SerreAssocRel.serre hij), map_zero]⟩).trans (RingQuot.liftAlgHom K)

@[simp] lemma lift_mkAlgHom_apply
    (f : {f : FreeAlgebra K ι →ₐ[K] B // ∀ i j, i ≠ j → f (serreAssocElem K A i j) = 0})
    (x : FreeAlgebra K ι) : lift f (mkAlgHom K A x) = f.1 x :=
  RingQuot.liftAlgHom_mkAlgHom_apply _ _ _ _

@[simp] lemma lift_θ
    (f : {f : FreeAlgebra K ι →ₐ[K] B // ∀ i j, i ≠ j → f (serreAssocElem K A i j) = 0})
    (i : ι) : lift f (θ K A i) = f.1 (FreeAlgebra.ι K i) :=
  lift_mkAlgHom_apply f _

variable (K A) in
/-- The kernel of the projection `FreeAlgebra K ι → SerreAssocAlgebra K A` is the two-sided
ideal generated by the associative Serre elements. -/
theorem ker_mkAlgHom : TwoSidedIdeal.ker (mkAlgHom K A) = serreAssocIdeal K A := by
  refine le_antisymm (fun x hx ↦ ?_) ?_
  · set J := serreAssocIdeal K A
    let q := RingCon.mkₐ K J.ringCon
    have hq : ∀ v, q v = 0 ↔ v ∈ J := fun v ↦ by
      rw [TwoSidedIdeal.mem_iff, ← RingCon.eq]
      rfl
    let g := lift ⟨q, fun i j hij ↦ (hq _).mpr (TwoSidedIdeal.subset_span ⟨i, j, hij, rfl⟩)⟩
    have hg : g (mkAlgHom K A x) = q x := lift_mkAlgHom_apply _ x
    rw [← hq, ← hg, (TwoSidedIdeal.mem_ker _).mp hx, map_zero]
  · rw [serreAssocIdeal, TwoSidedIdeal.span_le]
    rintro _ ⟨i, j, hij, rfl⟩
    rw [SetLike.mem_coe, TwoSidedIdeal.mem_ker, mkAlgHom_serreAssocElem hij]

lemma mkAlgHom_eq_zero_iff {x : FreeAlgebra K ι} :
    mkAlgHom K A x = 0 ↔ x ∈ serreAssocIdeal K A := by
  rw [← ker_mkAlgHom, TwoSidedIdeal.mem_ker]

end SerreAssocAlgebra

/-! ### The Lie algebra `𝔫̂(A)` -/

/-- The **Lie Serre element** `(ad θᵢ)^{nᵢⱼ} θⱼ` of the free Lie algebra on `ι`, where
`nᵢⱼ = max(-aᵢⱼ, 0) + 1` (which is `1 - aᵢⱼ` for a generalized Cartan matrix and `i ≠ j`). -/
def serreLieElem (i j : ι) : FreeLieAlgebra K ι :=
  (ad K _ (FreeLieAlgebra.of K i) ^ ((-A i j).toNat + 1)) (FreeLieAlgebra.of K j)

/-- The ideal of the free Lie algebra generated by the Lie Serre elements `serreLieElem K A i j`,
`i ≠ j`. -/
def serreLieIdeal : LieIdeal K (FreeLieAlgebra K ι) :=
  LieSubmodule.lieSpan K _ {x | ∃ i j, i ≠ j ∧ serreLieElem K A i j = x}

/-- The Lie algebra `𝔫̂(A)` generated by elements `θᵢ` (`i ∈ ι`) subject to the Serre relations
`(ad θᵢ)^{nᵢⱼ} θⱼ = 0` (`i ≠ j`), `nᵢⱼ = max(-aᵢⱼ, 0) + 1`. For a generalized Cartan matrix it is
the negative part `𝔫̂₋` of the Serre-presented algebra `𝔤̂(A)`
(`Matrix.Realization.SerrePresentedAlgebra.serreLieAlgebraEquivRangeFHom`), hence, by the
Gabber–Kac theorem, the negative part `𝔫₋` of `𝔤(A)` if `A` is moreover symmetrizable
(`Matrix.Realization.KacMoodyAlgebra.serreLieAlgebraEquivNNeg`). -/
abbrev SerreLieAlgebra : Type _ := FreeLieAlgebra K ι ⧸ serreLieIdeal K A

namespace SerreLieAlgebra

/-- The projection from the free Lie algebra onto `𝔫̂(A)`. -/
def mkHom : FreeLieAlgebra K ι →ₗ⁅K⁆ SerreLieAlgebra K A := LieIdeal.mkHom _

lemma mkHom_surjective : Function.Surjective (mkHom K A) := LieIdeal.mkHom_surjective _

/-- The generator `θᵢ` of `𝔫̂(A)`. -/
def θ (i : ι) : SerreLieAlgebra K A := mkHom K A (FreeLieAlgebra.of K i)

@[simp] lemma mkHom_of (i : ι) : mkHom K A (FreeLieAlgebra.of K i) = θ K A i := rfl

variable {K A}

lemma mkHom_eq_zero_iff {x : FreeLieAlgebra K ι} : mkHom K A x = 0 ↔ x ∈ serreLieIdeal K A :=
  LieIdeal.mkHom_eq_zero_iff _

lemma mkHom_serreLieElem {i j : ι} (hij : i ≠ j) : mkHom K A (serreLieElem K A i j) = 0 :=
  mkHom_eq_zero_iff.mpr (LieSubmodule.subset_lieSpan ⟨i, j, hij, rfl⟩)

/-- The **Serre relations** `(ad θᵢ)^{nᵢⱼ} θⱼ = 0` hold in `𝔫̂(A)`. -/
theorem ad_pow_θ {i j : ι} (hij : i ≠ j) :
    (ad K _ (θ K A i) ^ ((-A i j).toNat + 1)) (θ K A j) = 0 := by
  rw [← mkHom_serreLieElem hij, serreLieElem, map_ad_pow_aux, mkHom_of, mkHom_of]

variable {L' : Type*} [LieRing L'] [LieAlgebra K L']

/-- A morphism of Lie algebras out of the free Lie algebra killing the Lie Serre elements factors
through `𝔫̂(A)`. -/
def lift (f : FreeLieAlgebra K ι →ₗ⁅K⁆ L') (hf : ∀ i j, i ≠ j → f (serreLieElem K A i j) = 0) :
    SerreLieAlgebra K A →ₗ⁅K⁆ L' :=
  LieIdeal.lift _ f (by
    rw [serreLieIdeal, LieSubmodule.lieSpan_le]
    rintro _ ⟨i, j, hij, rfl⟩
    exact (LieHom.mem_ker).mpr (hf i j hij))

@[simp] lemma lift_mkHom (f : FreeLieAlgebra K ι →ₗ⁅K⁆ L')
    (hf : ∀ i j, i ≠ j → f (serreLieElem K A i j) = 0) (x : FreeLieAlgebra K ι) :
    lift f hf (mkHom K A x) = f x :=
  rfl

@[simp] lemma lift_θ (f : FreeLieAlgebra K ι →ₗ⁅K⁆ L')
    (hf : ∀ i j, i ≠ j → f (serreLieElem K A i j) = 0) (i : ι) :
    lift f hf (θ K A i) = f (FreeLieAlgebra.of K i) :=
  rfl

/-- Two morphisms of Lie algebras out of `𝔫̂(A)` agreeing on the generators `θᵢ` are equal. -/
theorem hom_ext {f g : SerreLieAlgebra K A →ₗ⁅K⁆ L'} (h : ∀ i, f (θ K A i) = g (θ K A i)) :
    f = g := by
  refine LieIdeal.lieHom_ext _ fun x ↦ ?_
  have : f.comp (mkHom K A) = g.comp (mkHom K A) := FreeLieAlgebra.hom_ext h
  exact LieHom.congr_fun this x

end SerreLieAlgebra

/-! ### The associative Serre algebra is the enveloping algebra of `𝔫̂(A)` -/

namespace SerreAssocAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

/-- The algebra morphism `SerreAssocAlgebra K A → U(𝔫̂(A))`, `θᵢ ↦ θᵢ`. -/
def toUniversalEnveloping :
    SerreAssocAlgebra K A →ₐ[K] UniversalEnvelopingAlgebra K (SerreLieAlgebra K A) :=
  lift ⟨FreeAlgebra.lift K fun i ↦ UniversalEnvelopingAlgebra.ι K (SerreLieAlgebra.θ K A i),
    fun i j hij ↦ by
    rw [map_serreAssocElem, FreeAlgebra.lift_ι_apply, FreeAlgebra.lift_ι_apply, ← map_neg,
      ← map_ad_pow_aux, ad_neg_pow_apply_aux, SerreLieAlgebra.ad_pow_θ hij, smul_zero,
      map_zero]⟩

/-- The algebra morphism `U(𝔫̂(A)) → SerreAssocAlgebra K A`, `θᵢ ↦ θᵢ`. -/
def ofUniversalEnveloping :
    UniversalEnvelopingAlgebra K (SerreLieAlgebra K A) →ₐ[K] SerreAssocAlgebra K A :=
  UniversalEnvelopingAlgebra.lift K <| SerreLieAlgebra.lift (FreeLieAlgebra.lift K (θ K A))
    fun i j hij ↦ by
      rw [serreLieElem, map_ad_pow_aux, FreeLieAlgebra.lift_of_apply,
        FreeLieAlgebra.lift_of_apply, ad_pow_θ hij]

@[simp] lemma toUniversalEnveloping_θ (i : ι) :
    toUniversalEnveloping K A (θ K A i) =
      UniversalEnvelopingAlgebra.ι K (SerreLieAlgebra.θ K A i) := by
  rw [toUniversalEnveloping, lift_θ, FreeAlgebra.lift_ι_apply]

@[simp] lemma ofUniversalEnveloping_ι_θ (i : ι) :
    ofUniversalEnveloping K A (UniversalEnvelopingAlgebra.ι K (SerreLieAlgebra.θ K A i)) =
      θ K A i := by
  rw [ofUniversalEnveloping, UniversalEnvelopingAlgebra.lift_ι_apply, SerreLieAlgebra.lift_θ,
    FreeLieAlgebra.lift_of_apply]

/-- **The associative Serre algebra is the enveloping algebra of `𝔫̂(A)`**: the algebra generated
by the `θᵢ` subject to the associative Serre relations is isomorphic to the universal enveloping
algebra of the Lie algebra generated by the `θᵢ` subject to the Lie Serre relations, via
`θᵢ ↦ θᵢ`. For a symmetrizable generalized Cartan matrix and `K` a field of characteristic zero,
the latter is `U(𝔫₋)` by the Gabber–Kac theorem ([Kac] Thm. 9.11;
`Matrix.Realization.KacMoodyAlgebra.serreAssocAlgebraEquiv`). This is standard; the argument
(by universal properties) is written out here. -/
def equivUniversalEnveloping :
    SerreAssocAlgebra K A ≃ₐ[K] UniversalEnvelopingAlgebra K (SerreLieAlgebra K A) :=
  AlgEquiv.ofAlgHom (toUniversalEnveloping K A) (ofUniversalEnveloping K A)
    (by
      ext x
      obtain ⟨x, rfl⟩ := SerreLieAlgebra.mkHom_surjective K A x
      change ((toUniversalEnveloping K A).comp (ofUniversalEnveloping K A) :
          _ →ₗ⁅K⁆ _).comp ((UniversalEnvelopingAlgebra.ι K).comp (SerreLieAlgebra.mkHom K A)) x =
        (UniversalEnvelopingAlgebra.ι K).comp (SerreLieAlgebra.mkHom K A) x
      congr 1
      refine FreeLieAlgebra.hom_ext fun i ↦ ?_
      change toUniversalEnveloping K A (ofUniversalEnveloping K A
        (UniversalEnvelopingAlgebra.ι K (SerreLieAlgebra.θ K A i))) =
          UniversalEnvelopingAlgebra.ι K (SerreLieAlgebra.θ K A i)
      rw [ofUniversalEnveloping_ι_θ, toUniversalEnveloping_θ])
    (hom_ext fun i ↦ by
      rw [AlgHom.comp_apply, toUniversalEnveloping_θ, ofUniversalEnveloping_ι_θ, AlgHom.id_apply])

@[simp] lemma equivUniversalEnveloping_θ (i : ι) :
    equivUniversalEnveloping K A (θ K A i) =
      UniversalEnvelopingAlgebra.ι K (SerreLieAlgebra.θ K A i) :=
  toUniversalEnveloping_θ K A i

@[simp] lemma equivUniversalEnveloping_symm_ι_θ (i : ι) :
    (equivUniversalEnveloping K A).symm
        (UniversalEnvelopingAlgebra.ι K (SerreLieAlgebra.θ K A i)) = θ K A i :=
  ofUniversalEnveloping_ι_θ K A i

end SerreAssocAlgebra

end Matrix
