/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.TensorVerma
import LieLean.Algebra.Lie.KacMoody.HighestWeight

/-!
# Full Lie-algebra tensor-Verma pieces

## Main definitions / Main results

* `lie_mem_tensorSubspace_of_generators`: full Lie stability from Cartan and positive-simple
  stability of the coefficient space.
* `tensorBorelSubmodule`: the existing concrete range, now as a full Lie submodule,
  with monotonicity and bottom/top identities.
* `shiftedVermaToTensorQuotient_injective`: a nonzero primitive coefficient coset
  yields an actual shifted-Verma embedding into the tensor quotient.
* `shiftedVermaEquivTensorBorelStep`: the image of a one-dimensional weight coefficient
  step in that quotient is genuinely isomorphic to the shifted Verma module.

## References

All arguments below are reconstructed from the existing tensor identity, PBW and the
Verma universal property, not certified against a newly consulted printed source.
The finite-dimensional weight-compatible Borel flag and its assembled standard filtration
are not constructed here. No character identity replaces a module map, and no Casimir
block is identified with a full-central-character block.
-/

open TensorProduct LieModule

noncomputable section

namespace Matrix.Realization.KacMoodyAlgebra.VermaModule

open UniversalEnvelopingAlgebra

variable {ι K H Z : Type*} [Fintype ι] [DecidableEq ι] [Field K] [CharZero K]
  [AddCommGroup H] [Module K H] {A : Matrix ι ι ℤ} (P : Realization A K H)
  (Λ : Module.Dual K H) [AddCommGroup Z] [Module K Z]
  [LieRingModule P.KacMoodyAlgebra Z] [LieModule K P.KacMoodyAlgebra Z]

/-- Every coefficient vector in F gives a tensor seed in the concrete range. -/
theorem hwv_tmul_mem_tensorSubspace (F : Submodule K Z) {z : Z} (hz : z ∈ F) :
    hwv P Λ ⊗ₜ[K] z ∈ tensorSubspace P Λ F := by
  refine ⟨(LeftRegular.equiv K (nNeg P)).symm 1 ⊗ₜ[K]
    (TrivialLieModule.equiv K (nNeg P) F).symm ⟨z, hz⟩, ?_⟩
  simp only [tensorSubspaceMap, LieModuleHom.comp_apply, TensorProduct.LieModule.map_tmul]
  exact tensorEquivLeftRegular_one P Λ z

/-- The concrete range is the negative-nilradical submodule generated by its seeds. -/
theorem tensorSubspace_le (F : Submodule K Z)
    (N : LieSubmodule K (nNeg P) (VermaModule P Λ ⊗[K] Z))
    (hN : ∀ z ∈ F, hwv P Λ ⊗ₜ[K] z ∈ N) : tensorSubspace P Λ F ≤ N := by
  rintro t ⟨s, rfl⟩
  suffices h : ∀ (u : UniversalEnvelopingAlgebra K (nNeg P))
      (z : TrivialLieModule K (nNeg P) F),
      tensorSubspaceMap P Λ F ((LeftRegular.equiv K (nNeg P)).symm u ⊗ₜ[K] z) ∈ N by
    induction s using TensorProduct.inductionOn with
    | tmul u z => simpa using h (LeftRegular.equiv K (nNeg P) u) z
    | add s t hs ht => rw [map_add]; exact N.add_mem hs ht
  intro u
  induction u using TensorIdentity.induction_left with
  | hone =>
    intro z
    simp only [tensorSubspaceMap, LieModuleHom.comp_apply, TensorProduct.LieModule.map_tmul]
    change tensorEquivLeftRegular P Λ
      ((LeftRegular.equiv K (nNeg P)).symm 1 ⊗ₜ[K]
        (TrivialLieModule.equiv K (nNeg P) Z).symm
          (TrivialLieModule.equiv K (nNeg P) F z).val) ∈ N
    rw [tensorEquivLeftRegular_one]
    exact hN _ (TrivialLieModule.equiv K (nNeg P) F z).property
  | hadd a b ha hb => intro z; simp only [map_add, add_tmul]; exact N.add_mem (ha z) (hb z)
  | hsmul r a ha =>
    intro z
    simp only [map_smul, ← smul_tmul']
    exact N.smul_mem r (ha z)
  | hι x a ha =>
    intro z
    have heq : (LeftRegular.equiv K (nNeg P)).symm (UniversalEnvelopingAlgebra.ι K x * a)
        ⊗ₜ[K] z = ⁅x, (LeftRegular.equiv K (nNeg P)).symm a ⊗ₜ[K] z⁆ := by
      simp only [TensorProduct.LieModule.lie_tmul_right, trivial_lie_zero, tmul_zero,
        add_zero]
      rfl
    rw [heq, LieModuleHom.map_lie]
    exact N.lie_mem (ha z)

/-- Borel-stable coefficients make every full Lie action on a seed belong to the range. -/
theorem lie_hwv_tmul_mem_tensorSubspace (F : LieSubmodule K (borel P) Z)
    (x : P.KacMoodyAlgebra) {z : Z} (hz : z ∈ F) :
    ⁅x, hwv P Λ ⊗ₜ[K] z⁆ ∈ tensorSubspace P Λ F.toSubmodule := by
  obtain ⟨y, a, w, rfl⟩ := exists_triangular P x
  rw [add_lie, add_lie]
  refine (tensorSubspace P Λ F.toSubmodule).add_mem
    ((tensorSubspace P Λ F.toSubmodule).add_mem ?_ ?_) ?_
  · exact (tensorSubspace P Λ F.toSubmodule).lie_mem
      (x := ⟨fHom P y, ⟨y, rfl⟩⟩) (hwv_tmul_mem_tensorSubspace P Λ _ hz)
  · rw [TensorProduct.LieModule.lie_tmul_right, lie_h_hwv, ← smul_tmul']
    exact (tensorSubspace P Λ F.toSubmodule).add_mem
      ((tensorSubspace P Λ F.toSubmodule).smul_mem _
        (hwv_tmul_mem_tensorSubspace P Λ _ hz))
      (hwv_tmul_mem_tensorSubspace P Λ _
        (F.lie_mem (x := ⟨h P a, h_mem_borel P a⟩) hz))
  · rw [TensorProduct.LieModule.lie_tmul_right,
      lie_hwv_of_mem_nPos P Λ (show eHom P w ∈ nPos P from ⟨w, rfl⟩),
      zero_tmul, zero_add]
    exact hwv_tmul_mem_tensorSubspace P Λ _
      (F.lie_mem (x := ⟨eHom P w, nPos_le_borel P ⟨w, rfl⟩⟩) hz)

/-- The actual tensor range of a Borel submodule is stable under the full Lie algebra.
Reconstructed commutator induction: the subspace of vectors whose every Lie derivative
belongs to the range is itself negative-nilradical-stable and contains all seeds. -/
theorem lie_mem_tensorSubspace (F : LieSubmodule K (borel P) Z)
    (x : P.KacMoodyAlgebra) {t : VermaModule P Λ ⊗[K] Z}
    (ht : t ∈ tensorSubspace P Λ F.toSubmodule) :
    ⁅x, t⁆ ∈ tensorSubspace P Λ F.toSubmodule := by
  let N := tensorSubspace P Λ F.toSubmodule
  let D : LieSubmodule K (nNeg P) (VermaModule P Λ ⊗[K] Z) :=
    { carrier := {t | ∀ x : P.KacMoodyAlgebra, ⁅x, t⁆ ∈ N}
      zero_mem' := by intro x; rw [lie_zero]; exact N.zero_mem
      add_mem' := by
        intro s t hs ht x
        rw [lie_add]
        exact N.add_mem (hs x) (ht x)
      smul_mem' := by
        intro c t ht x
        rw [lie_smul]
        exact N.smul_mem c (ht x)
      lie_mem := by
        intro y t ht x
        change ⁅x, ⁅(y : P.KacMoodyAlgebra), t⁆⁆ ∈ N
        rw [leibniz_lie]
        exact N.add_mem (ht ⁅x, (y : P.KacMoodyAlgebra)⁆) (N.lie_mem (ht x)) }
  have hD : tensorSubspace P Λ F.toSubmodule ≤ D :=
    tensorSubspace_le P Λ _ D (fun z hz x => lie_hwv_tmul_mem_tensorSubspace P Λ F x hz)
  exact hD ht x

/-- Full Lie-algebra submodule with exactly the existing concrete tensor-range carrier. -/
def tensorBorelSubmodule (F : LieSubmodule K (borel P) Z) :
    LieSubmodule K P.KacMoodyAlgebra (VermaModule P Λ ⊗[K] Z) :=
  { (tensorSubspace P Λ F.toSubmodule).toSubmodule with
    lie_mem := fun {x} {_t} ht => lie_mem_tensorSubspace P Λ F x ht }

/-- Cartan and positive-simple stability suffice for Borel stability. -/
def borelSubmoduleOfGenerators (F : Submodule K Z)
    (he : ∀ i, ∀ z ∈ F, ⁅e P i, z⁆ ∈ F)
    (hh : ∀ a, ∀ z ∈ F, ⁅h P a, z⁆ ∈ F) : LieSubmodule K (borel P) Z := by
  refine { F with lie_mem := ?_ }
  intro x z hz
  obtain ⟨a, w, ⟨v, rfl⟩, hx⟩ := (mem_borel P).mp x.property
  change ⁅(x : P.KacMoodyAlgebra), z⁆ ∈ F
  rw [← hx, add_lie]
  refine F.add_mem (hh a z hz) ?_
  have hn : ∀ z ∈ F, ⁅eHom P v, z⁆ ∈ F := by
    clear hx
    induction v using FreeLieAlgebra.induction_on with
    | of i => simpa only [eHom_of] using he i
    | zero => intro z _hz; rw [map_zero, zero_lie]; exact F.zero_mem
    | add u v hu hv =>
      intro z hz
      rw [map_add, add_lie]
      exact F.add_mem (hu z hz) (hv z hz)
    | smul c u hu =>
      intro z hz
      rw [map_smul, smul_lie]
      exact F.smul_mem c (hu z hz)
    | lie u v hu hv =>
      intro z hz
      rw [LieHom.map_lie, lie_lie]
      exact F.sub_mem (hu _ (hv z hz)) (hv _ (hu z hz))
  exact hn z hz

/-- Full stability stated using only Cartan and positive-simple hypotheses on coefficients. -/
theorem lie_mem_tensorSubspace_of_generators (F : Submodule K Z)
    (he : ∀ i, ∀ z ∈ F, ⁅e P i, z⁆ ∈ F)
    (hh : ∀ a, ∀ z ∈ F, ⁅h P a, z⁆ ∈ F)
    (x : P.KacMoodyAlgebra) {t : VermaModule P Λ ⊗[K] Z}
    (ht : t ∈ tensorSubspace P Λ F) : ⁅x, t⁆ ∈ tensorSubspace P Λ F :=
  lie_mem_tensorSubspace P Λ (borelSubmoduleOfGenerators P F he hh) x ht

/-- Increasing Borel coefficient spaces give increasing full Lie submodules. -/
theorem tensorBorelSubmodule_mono : Monotone (tensorBorelSubmodule (Z := Z) P Λ) := by
  intro F G hFG
  exact tensorSubspace_mono P Λ hFG

/-- The full coefficient space gives the entire tensor-Verma module. -/
@[simp] theorem tensorBorelSubmodule_top : tensorBorelSubmodule (Z := Z) P Λ ⊤ = ⊤ := by
  ext t
  change t ∈ tensorSubspace P Λ (⊤ : Submodule K Z) ↔ _
  rw [tensorSubspace_top]
  rfl

/-- The zero coefficient space gives the zero concrete piece. -/
@[simp] theorem tensorSubspace_bot : tensorSubspace (Z := Z) P Λ ⊥ = ⊥ := by
  apply le_antisymm _ bot_le
  apply tensorSubspace_le
  intro z hz
  have hz0 : z = 0 := hz
  rw [hz0, tmul_zero]
  exact LieSubmodule.zero_mem _

/-- The zero Borel coefficient space gives the zero full submodule. -/
@[simp] theorem tensorBorelSubmodule_bot : tensorBorelSubmodule (Z := Z) P Λ ⊥ = ⊥ := by
  ext t
  change t ∈ tensorSubspace P Λ (⊥ : Submodule K Z) ↔ _
  rw [tensorSubspace_bot]
  rfl

/-- A negative-nilradical morphism out of a Verma module is determined by its seed. -/
theorem hom_ext_nNeg {V : Type*} [AddCommGroup V] [Module K V]
    [LieRingModule (nNeg P) V] [LieModule K (nNeg P) V]
    {f g : VermaModule P Λ →ₗ⁅K,nNeg P⁆ V} (hfg : f (hwv P Λ) = g (hwv P Λ)) : f = g := by
  ext m
  obtain ⟨u, rfl⟩ := (equivEnvNNeg P Λ).surjective m
  induction u using TensorIdentity.induction_left with
  | hone => simpa using hfg
  | hadd u v hu hv => simp only [map_add, hu, hv]
  | hsmul c u hu => simp only [map_smul, hu]
  | hι x u hu =>
    have heq : equivEnvNNeg P Λ (UniversalEnvelopingAlgebra.ι K x * u) =
        ⁅x, equivEnvNNeg P Λ u⁆ :=
      (equivLeftRegular P Λ).map_lie x ((LeftRegular.equiv K (nNeg P)).symm u)
    rw [heq, f.map_lie, g.map_lie, hu]

/-- Extract a coefficient functional after undoing the actual tensor identity. -/
def tensorCoefficientProbe (ℓ : Z →ₗ[K] K) :
    VermaModule P Λ ⊗[K] Z →ₗ⁅K,nNeg P⁆ LeftRegular K (nNeg P) := by
  let p : LeftRegular K (nNeg P) ⊗[K] TrivialLieModule K (nNeg P) Z →ₗ[K]
      LeftRegular K (nNeg P) := TensorProduct.lift
    { toFun := fun u =>
        { toFun := fun z => ℓ (TrivialLieModule.equiv K (nNeg P) Z z) • u
          map_add' := by intros; simp [add_smul]
          map_smul' := by intros; simp [smul_smul] }
      map_add' := by intros; ext z; simp [smul_add]
      map_smul' := by intros; ext z; simp [smul_smul, mul_comm] }
  let q : LeftRegular K (nNeg P) ⊗[K] TrivialLieModule K (nNeg P) Z →ₗ⁅K,nNeg P⁆
      LeftRegular K (nNeg P) :=
    { p with
      map_lie' := by
        intro x t
        change p ⁅x, t⁆ = ⁅x, p t⁆
        induction t using TensorProduct.inductionOn with
        | tmul u z =>
          simp only [TensorProduct.LieModule.lie_tmul_right, trivial_lie_zero, tmul_zero,
            add_zero, p, TensorProduct.lift.tmul, LinearMap.coe_mk, AddHom.coe_mk, lie_smul]
        | add s t hs ht => simp only [lie_add, map_add, hs, ht] }
  exact q.comp (tensorEquivLeftRegular P Λ).symm.toLieModuleHom

@[simp] theorem tensorCoefficientProbe_seed (ℓ : Z →ₗ[K] K) (z : Z) :
    tensorCoefficientProbe P Λ ℓ (hwv P Λ ⊗ₜ[K] z) =
      ℓ z • (LeftRegular.equiv K (nNeg P)).symm 1 := by
  unfold tensorCoefficientProbe
  simp only [LieModuleHom.comp_apply, LieModuleEquiv.coe_toLieModuleHom]
  rw [← tensorEquivLeftRegular_one P Λ z, LieModuleEquiv.symm_apply_apply]
  rfl

/-- A coefficient functional annihilating F annihilates the actual tensor range. -/
theorem tensorSubspace_le_ker_probe (F : Submodule K Z) (ℓ : Z →ₗ[K] K)
    (hℓ : F ≤ LinearMap.ker ℓ) : tensorSubspace P Λ F ≤ (tensorCoefficientProbe P Λ ℓ).ker := by
  apply tensorSubspace_le
  intro z hz
  change tensorCoefficientProbe P Λ ℓ (hwv P Λ ⊗ₜ[K] z) = 0
  rw [tensorCoefficientProbe_seed, show ℓ z = 0 from hℓ hz, zero_smul]

/-- The actual tensor-Verma quotient by a Borel coefficient piece. -/
abbrev TensorBorelQuotient (F : LieSubmodule K (borel P) Z) :=
  (VermaModule P Λ ⊗[K] Z) ⧸ tensorBorelSubmodule P Λ F

/-- A coefficient probe descends to the actual full-Lie-module quotient; it is nNeg-equivariant. -/
def quotientCoefficientProbe (F : LieSubmodule K (borel P) Z) (ℓ : Z →ₗ[K] K)
    (hℓ : F.toSubmodule ≤ LinearMap.ker ℓ) :
    TensorBorelQuotient P Λ F →ₗ⁅K,nNeg P⁆ LeftRegular K (nNeg P) :=
  { (tensorBorelSubmodule P Λ F).toSubmodule.liftQ
      (tensorCoefficientProbe P Λ ℓ).toLinearMap (tensorSubspace_le_ker_probe P Λ _ ℓ hℓ) with
    map_lie' := by
      intro x t
      obtain ⟨s, rfl⟩ := LieSubmodule.Quotient.surjective_mk' (tensorBorelSubmodule P Λ F) t
      exact (tensorCoefficientProbe P Λ ℓ).map_lie x s }

/-- The highest-weight tensor modulo F, when the coefficient is primitive modulo F,
induces an actual shifted Verma morphism. -/
def shiftedVermaToTensorQuotient (F : LieSubmodule K (borel P) Z)
    (μ : Module.Dual K H) (z : Z)
    (he : ∀ i, ⁅e P i, z⁆ ∈ F) (hh : ∀ a, ⁅h P a, z⁆ - μ a • z ∈ F) :
    VermaModule P (Λ + μ) →ₗ⁅K,P.KacMoodyAlgebra⁆ TensorBorelQuotient P Λ F := by
  let q := LieSubmodule.Quotient.mk' (tensorBorelSubmodule P Λ F)
  refine lift P (q (hwv P Λ ⊗ₜ[K] z)) ?_ ?_
  · intro x hx
    apply lie_eq_zero_of_mem_nPos (P := P) (x := x) _ hx
    intro i
    rw [← q.map_lie, TensorProduct.LieModule.lie_tmul_right, lie_e_hwv, zero_tmul, zero_add]
    exact (LieSubmodule.Quotient.mk_eq_zero _).mpr (hwv_tmul_mem_tensorSubspace P Λ _ (he i))
  · intro a
    rw [← q.map_lie, ← map_smul, ← sub_eq_zero, ← map_sub]
    apply (LieSubmodule.Quotient.mk_eq_zero _).mpr
    have heq : ⁅h P a, hwv P Λ ⊗ₜ[K] z⁆ - (Λ + μ) a • (hwv P Λ ⊗ₜ[K] z) =
        hwv P Λ ⊗ₜ[K] (⁅h P a, z⁆ - μ a • z) := by
      simp only [TensorProduct.LieModule.lie_tmul_right, lie_h_hwv, LinearMap.add_apply,
        add_smul, smul_tmul', tmul_smul, tmul_sub]
      abel
    rw [heq]
    exact hwv_tmul_mem_tensorSubspace P Λ _ (hh a)

@[simp] theorem shiftedVermaToTensorQuotient_hwv (F : LieSubmodule K (borel P) Z)
    (μ : Module.Dual K H) (z : Z)
    (he : ∀ i, ⁅e P i, z⁆ ∈ F) (hh : ∀ a, ⁅h P a, z⁆ - μ a • z ∈ F) :
    shiftedVermaToTensorQuotient P Λ F μ z he hh (hwv P (Λ + μ)) =
      LieSubmodule.Quotient.mk' (tensorBorelSubmodule P Λ F) (hwv P Λ ⊗ₜ[K] z) := by
  unfold shiftedVermaToTensorQuotient
  rw [lift_hwv]

/-- No extra relations occur: a nonzero primitive coefficient coset gives a Verma embedding. -/
theorem shiftedVermaToTensorQuotient_injective (F : LieSubmodule K (borel P) Z)
    (μ : Module.Dual K H) (z : Z) (hz : z ∉ F)
    (he : ∀ i, ⁅e P i, z⁆ ∈ F) (hh : ∀ a, ⁅h P a, z⁆ - μ a • z ∈ F) :
    Function.Injective (shiftedVermaToTensorQuotient P Λ F μ z he hh) := by
  obtain ⟨ℓ, hℓz, hℓ⟩ := F.toSubmodule.exists_le_ker_of_notMem hz
  let φ := shiftedVermaToTensorQuotient P Λ F μ z he hh
  have hcomp : (quotientCoefficientProbe P Λ F ℓ hℓ).comp (φ.restrictLie (nNeg P)) =
      ℓ z • (equivLeftRegular P (Λ + μ)).symm.toLieModuleHom := by
    apply hom_ext_nNeg
    change quotientCoefficientProbe P Λ F ℓ hℓ
      (shiftedVermaToTensorQuotient P Λ F μ z he hh (hwv P (Λ + μ))) = _
    rw [shiftedVermaToTensorQuotient_hwv]
    change tensorCoefficientProbe P Λ ℓ (hwv P Λ ⊗ₜ[K] z) = _
    rw [tensorCoefficientProbe_seed]
    congr 1
    apply (equivLeftRegular P (Λ + μ)).injective
    simp [equivLeftRegular]
  intro u v huv
  have heq := congrArg (quotientCoefficientProbe P Λ F ℓ hℓ) huv
  change ((quotientCoefficientProbe P Λ F ℓ hℓ).comp (φ.restrictLie (nNeg P))) u =
    ((quotientCoefficientProbe P Λ F ℓ hℓ).comp (φ.restrictLie (nNeg P))) v at heq
  rw [hcomp] at heq
  exact (equivLeftRegular P (Λ + μ)).symm.injective ((smul_right_injective _ hℓz) heq)

/-- The image of a coefficient step in the actual quotient by its preceding piece. -/
def tensorBorelStep (F G : LieSubmodule K (borel P) Z) :
    LieSubmodule K P.KacMoodyAlgebra (TensorBorelQuotient P Λ F) :=
  (tensorBorelSubmodule P Λ G).map
    (LieSubmodule.Quotient.mk' (tensorBorelSubmodule P Λ F))

/-- A one-dimensional weight step has exactly the image of the shifted-Verma morphism.
The hypothesis describes the coefficient step, not its tensor-Verma quotient. -/
theorem range_shiftedVermaToTensorQuotient (F G : LieSubmodule K (borel P) Z)
    (μ : Module.Dual K H) (z : Z) (hzG : z ∈ G)
    (hG : ∀ w ∈ G, ∃ f ∈ F, ∃ c : K, w = f + c • z)
    (he : ∀ i, ⁅e P i, z⁆ ∈ F) (hh : ∀ a, ⁅h P a, z⁆ - μ a • z ∈ F) :
    (shiftedVermaToTensorQuotient P Λ F μ z he hh).range = tensorBorelStep P Λ F G := by
  let φ := shiftedVermaToTensorQuotient P Λ F μ z he hh
  let q := LieSubmodule.Quotient.mk' (tensorBorelSubmodule P Λ F)
  apply le_antisymm
  · have htop : (tensorBorelStep P Λ F G).comap φ = ⊤ := by
      apply eq_top_of_hwv_mem
      change φ (hwv P (Λ + μ)) ∈ tensorBorelStep P Λ F G
      rw [shiftedVermaToTensorQuotient_hwv]
      exact ⟨hwv P Λ ⊗ₜ[K] z, hwv_tmul_mem_tensorSubspace P Λ _ hzG, rfl⟩
    rintro t ⟨m, rfl⟩
    exact show m ∈ (tensorBorelStep P Λ F G).comap φ from htop ▸ trivial
  · have hle : tensorSubspace P Λ G.toSubmodule ≤
        (φ.range.comap q).restr (nNeg P) := by
      apply tensorSubspace_le
      intro w hw
      obtain ⟨f, hf, c, rfl⟩ := hG w hw
      change q (hwv P Λ ⊗ₜ[K] (f + c • z)) ∈ φ.range
      rw [tmul_add, tmul_smul, map_add, map_smul]
      have hf0 : q (hwv P Λ ⊗ₜ[K] f) = 0 :=
        (LieSubmodule.Quotient.mk_eq_zero _).mpr (hwv_tmul_mem_tensorSubspace P Λ _ hf)
      rw [hf0, zero_add]
      exact φ.range.smul_mem c ⟨hwv P (Λ + μ), shiftedVermaToTensorQuotient_hwv P Λ F μ z he hh⟩
    rintro t ⟨s, hs, rfl⟩
    exact hle hs

/-- Actual shifted-Verma identification for a one-dimensional coefficient flag step.
The target is the image of T(G) in the ambient quotient by T(F), so when F ≤ G
it realizes the subquotient T(G)/T(F). No tensor-filtration or quotient isomorphism is assumed. -/
def shiftedVermaEquivTensorBorelStep (F G : LieSubmodule K (borel P) Z)
    (μ : Module.Dual K H) (z : Z) (hz : z ∉ F) (hzG : z ∈ G)
    (hG : ∀ w ∈ G, ∃ f ∈ F, ∃ c : K, w = f + c • z)
    (he : ∀ i, ⁅e P i, z⁆ ∈ F) (hh : ∀ a, ⁅h P a, z⁆ - μ a • z ∈ F) :
    VermaModule P (Λ + μ) ≃ₗ⁅K,P.KacMoodyAlgebra⁆ tensorBorelStep P Λ F G := by
  let φ := shiftedVermaToTensorQuotient P Λ F μ z he hh
  have hr : φ.range = tensorBorelStep P Λ F G :=
    range_shiftedVermaToTensorQuotient P Λ F G μ z hzG hG he hh
  let ψ := φ.codRestrict (tensorBorelStep P Λ F G) (fun m => hr ▸ ⟨m, rfl⟩)
  have hψ : Function.Bijective ψ := by
    constructor
    · intro u v huv
      exact shiftedVermaToTensorQuotient_injective P Λ F μ z hz he hh
        (congrArg Subtype.val huv)
    · intro t
      have ht : (t : TensorBorelQuotient P Λ F) ∈ φ.range := hr.symm ▸ t.property
      obtain ⟨m, hm⟩ := ht
      exact ⟨m, Subtype.ext hm⟩
  exact { LinearEquiv.ofBijective ψ.toLinearMap hψ with map_lie' := ψ.map_lie _ _ }

end Matrix.Realization.KacMoodyAlgebra.VermaModule
