/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import Mathlib.LinearAlgebra.FreeAlgebra
import LieLean.Algebra.Lie.KacMoody.Auxiliary

/-!
# The triangular decomposition of `𝔤̃(A)`

We prove parts (a)–(c) of [Kac] Theorem 1.2 for the auxiliary Lie algebra `𝔤̃(A)`:

* the map `𝔥 → 𝔤̃(A)` is injective;
* the subalgebra `𝔫̃₋` (resp. `𝔫̃₊`) generated by the `fᵢ` (resp. `eᵢ`) is freely generated by
  them;
* `𝔤̃(A) = 𝔫̃₋ ⊕ 𝔥 ⊕ 𝔫̃₊` as vector spaces.

Following [Kac] §1.3 (proof of Thm. 1.2), for `λ ∈ 𝔥*` we construct a representation of `𝔤̃(A)`
on the tensor algebra `T(V) = K⟨vᵢ : i ∈ ι⟩` (here the free associative algebra
`FreeAlgebra K ι`): `fᵢ` acts by left multiplication by `vᵢ`, `h` acts on a word
`v_{j₁} ⋯ v_{jₖ}` by the scalar
`⟨λ - α_{j₁} - ⋯ - α_{jₖ}, h⟩`, and `eᵢ` is defined by `eᵢ 1 = 0` and
`eᵢ (vⱼ a) = vⱼ (eᵢ a) + δᵢⱼ αᵢ^∨(a)`.

## Main definitions

* `Matrix.Realization.AuxLieAlgebra.tensorRep`: the representation of `𝔤̃(A)` on `T(V)`.
* `Matrix.Realization.AuxLieAlgebra.fHom`, `eHom`: the morphisms from the free Lie algebra on `ι`
  sending the generators to the `fᵢ` (resp. `eᵢ`).
* `Matrix.Realization.AuxLieAlgebra.triangularEquiv`: the linear isomorphism
  `L(ι) × 𝔥 × L(ι) ≃ₗ[K] 𝔤̃(A)`, `(y, a, z) ↦ fHom y + h a + eHom z`, where `L(ι)` is the free
  Lie algebra on `ι`.

## Main results

* `Matrix.Realization.AuxLieAlgebra.h_injective`, `fHom_injective`, `eHom_injective`.
* `Matrix.Realization.AuxLieAlgebra.triangularEquiv`: [Kac] Theorem 1.2 (a), (b), (c).

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, Thm. 1.2 and §1.3.
-/

open FreeLieAlgebra Module

namespace FreeAlgebra

variable (R X : Type*) [CommRing R]

lemma basisFreeMonoid_apply (w : FreeMonoid X) :
    basisFreeMonoid R X w = FreeMonoid.lift (ι R) w := by
  rw [basisFreeMonoid, Module.Basis.map_apply, Finsupp.coe_basisSingleOne]
  change equivMonoidAlgebraFreeMonoid.symm (MonoidAlgebra.single w 1) = _
  simp [equivMonoidAlgebraFreeMonoid]

lemma basisFreeMonoid_one : basisFreeMonoid R X 1 = 1 := by
  simp [basisFreeMonoid_apply]

lemma basisFreeMonoid_of_mul (x : X) (w : FreeMonoid X) :
    basisFreeMonoid R X (FreeMonoid.of x * w) = ι R x * basisFreeMonoid R X w := by
  simp [basisFreeMonoid_apply]

variable {R X}

/-- The basis vector of `FreeAlgebra R X` attached to a word. -/
noncomputable abbrev word (w : List X) : FreeAlgebra R X :=
  basisFreeMonoid R X (FreeMonoid.ofList w)

lemma word_nil : word (R := R) ([] : List X) = 1 := basisFreeMonoid_one R X

lemma word_cons (j : X) (w : List X) : word (R := R) (j :: w) = ι R j * word w := by
  rw [word, FreeMonoid.ofList_cons, basisFreeMonoid_of_mul]

/-- Linear maps out of `FreeAlgebra R X` defined on words. -/
noncomputable def onWords {M : Type*} [AddCommGroup M] [Module R M] (g : List X → M) :
    FreeAlgebra R X →ₗ[R] M :=
  (basisFreeMonoid R X).constr R fun w ↦ g (FreeMonoid.toList w)

@[simp] lemma onWords_word {M : Type*} [AddCommGroup M] [Module R M] (g : List X → M)
    (w : List X) : onWords g (word (R := R) w) = g w := by
  simp [onWords, word]

lemma endo_ext {φ ψ : Module.End R (FreeAlgebra R X)} (h : ∀ w, φ (word w) = ψ (word w)) :
    φ = ψ :=
  (basisFreeMonoid R X).ext fun w ↦ by simpa [word] using h (FreeMonoid.toList w)

end FreeAlgebra

open FreeAlgebra (word onWords onWords_word endo_ext word_nil word_cons)

noncomputable section

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H)

namespace AuxLieAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

local notation "T" => FreeAlgebra K ι

/-- The weight `α_{j₁} + ⋯ + α_{jₖ}` of a word. -/
def wordWt (w : List ι) : Dual K H := (w.map P.root).sum

omit [DecidableEq ι] in
@[simp] lemma wordWt_nil : wordWt P [] = 0 := rfl

omit [DecidableEq ι] in
@[simp] lemma wordWt_cons (j : ι) (w : List ι) : wordWt P (j :: w) = P.root j + wordWt P w := by
  simp [wordWt]

variable (Λ : Dual K H)

/-- The action of `h ∈ 𝔥` on `T(V)`: a word `w` is an eigenvector with eigenvalue
`⟨λ - wt w, h⟩`. -/
noncomputable def repH : H →ₗ[K] Module.End K T where
  toFun a := onWords fun w ↦ (Λ a - wordWt P w a) • word w
  map_add' a b := endo_ext fun w ↦ by
    simp only [LinearMap.add_apply, onWords_word, map_add]
    module
  map_smul' c a := endo_ext fun w ↦ by
    simp only [LinearMap.smul_apply, onWords_word, map_smul, smul_eq_mul, RingHom.id_apply]
    module

omit [DecidableEq ι] in
@[simp] lemma repH_word (a : H) (w : List ι) :
    repH P Λ a (word w) = (Λ a - wordWt P w a) • word w := by
  simp [repH]

/-- The action of `fᵢ` on `T(V)`: left multiplication by `vᵢ`. -/
noncomputable def repF (i : ι) : Module.End K T := LinearMap.mulLeft K (FreeAlgebra.ι K i)

omit [Fintype ι] [DecidableEq ι] in
@[simp] lemma repF_word (i : ι) (w : List ι) : repF (K := K) i (word w) = word (i :: w) := by
  simp [repF, word_cons]

/-- The action of `eᵢ` on words. -/
noncomputable def eWord (i : ι) : List ι → T
  | [] => 0
  | j :: w => FreeAlgebra.ι K j * eWord i w +
      if i = j then (Λ (P.coroot i) - wordWt P w (P.coroot i)) • word w else 0

/-- The action of `eᵢ` on `T(V)`. -/
noncomputable def repE (i : ι) : Module.End K T := onWords (eWord P Λ i)

@[simp] lemma repE_word (i : ι) (w : List ι) : repE P Λ i (word w) = eWord P Λ i w := by
  simp [repE]

omit [DecidableEq ι] in
lemma repH_mulLeft (a : H) (j : ι) (x : T) :
    repH P Λ a (FreeAlgebra.ι K j * x) =
      FreeAlgebra.ι K j * repH P Λ a x - P.root j a • (FreeAlgebra.ι K j * x) := by
  have : repH P Λ a ∘ₗ repF j = repF j ∘ₗ repH P Λ a - P.root j a • repF j := by
    refine endo_ext fun w ↦ ?_
    simp only [LinearMap.comp_apply, repF_word, repH_word, wordWt_cons, LinearMap.add_apply,
      LinearMap.sub_apply, LinearMap.smul_apply, map_smul]
    module
  simpa [repF] using LinearMap.congr_fun this x

lemma repH_eWord (a : H) (i : ι) (w : List ι) :
    repH P Λ a (eWord P Λ i w) =
      (Λ a - wordWt P w a + P.root i a) • eWord P Λ i w := by
  induction w with
  | nil => simp [eWord]
  | cons j w ih =>
    simp only [eWord, map_add, repH_mulLeft, ih, wordWt_cons, LinearMap.add_apply]
    split_ifs with hij
    · subst hij
      simp only [map_smul, repH_word, smul_add, mul_smul_comm, smul_smul]
      module
    · simp only [add_zero, mul_smul_comm, map_zero]
      module

/-- The data of the representation of `𝔤̃(A)` on `T(V)`. -/
noncomputable def tensorRepData : LiftData P (Module.End K T) where
  h := repH P Λ
  e := repE P Λ
  f := repF
  lie_h_h a b := endo_ext fun w ↦ by
    simp [LieRing.of_associative_ring_bracket, smul_smul, mul_comm]
  lie_e_f i j := endo_ext fun w ↦ by
    simp only [LieRing.of_associative_ring_bracket, LinearMap.sub_apply, Module.End.mul_apply,
      repF_word, repE_word, eWord]
    simp only [repF, LinearMap.mulLeft_apply, add_sub_cancel_left]
    split_ifs with hij
    · subst hij; simp
    · simp
  lie_h_e a i := endo_ext fun w ↦ by
    simp only [LieRing.of_associative_ring_bracket, LinearMap.sub_apply, Module.End.mul_apply,
      repE_word, repH_word, map_smul, repH_eWord, LinearMap.smul_apply]
    rw [← sub_smul]
    congr 1
    ring
  lie_h_f a i := endo_ext fun w ↦ by
    simp only [LieRing.of_associative_ring_bracket, LinearMap.sub_apply, Module.End.mul_apply,
      repF_word, repH_word, map_smul, wordWt_cons, LinearMap.neg_apply, LinearMap.smul_apply,
      LinearMap.add_apply]
    rw [← sub_smul, ← neg_smul]
    congr 1
    ring

/-- The representation of `𝔤̃(A)` on the tensor algebra `T(V)` attached to `λ ∈ 𝔥*`
([Kac] §1.3, proof of Thm. 1.2). -/
noncomputable def tensorRep : P.AuxLieAlgebra →ₗ⁅K⁆ Module.End K T :=
  lift (tensorRepData P Λ)

@[simp] lemma tensorRep_e (i : ι) : tensorRep P Λ (e P i) = repE P Λ i := lift_e _ i
@[simp] lemma tensorRep_f (i : ι) : tensorRep P Λ (f P i) = repF i := lift_f _ i
@[simp] lemma tensorRep_h (a : H) : tensorRep P Λ (h P a) = repH P Λ a := lift_h _ a

omit [DecidableEq ι] in
@[simp] lemma repH_one (a : H) : repH P Λ a 1 = Λ a • 1 := by
  rw [← word_nil, repH_word]
  simp

lemma tensorRep_h_one (a : H) : tensorRep P Λ (h P a) 1 = Λ a • 1 := by
  rw [tensorRep_h, ← word_nil, repH_word]
  simp

/-! ### The subalgebras `𝔫̃₋` and `𝔫̃₊` -/

/-- The morphism from the free Lie algebra on `ι` sending generators to the `fᵢ`. -/
noncomputable def fHom : FreeLieAlgebra K ι →ₗ⁅K⁆ P.AuxLieAlgebra :=
  FreeLieAlgebra.lift K (f P)

/-- The morphism from the free Lie algebra on `ι` sending generators to the `eᵢ`. -/
noncomputable def eHom : FreeLieAlgebra K ι →ₗ⁅K⁆ P.AuxLieAlgebra :=
  FreeLieAlgebra.lift K (e P)

@[simp] lemma fHom_of (i : ι) : fHom P (FreeLieAlgebra.of K i) = f P i := by simp [fHom]
@[simp] lemma eHom_of (i : ι) : eHom P (FreeLieAlgebra.of K i) = e P i := by simp [eHom]

/-- The action of `𝔫̃₋` on `1 ∈ T(V)` is via the embedding of the free Lie algebra in
`T(V)`. -/
lemma tensorRep_fHom_one (y : FreeLieAlgebra K ι) :
    tensorRep P Λ (fHom P y) 1 = FreeLieAlgebra.toFreeAlgebra K ι y := by
  have : (tensorRep P Λ).comp (fHom P) =
      ((Algebra.lmul K T).toLieHom : T →ₗ⁅K⁆ Module.End K T).comp
        (FreeLieAlgebra.toFreeAlgebra K ι) := by
    ext i
    simp [repF]
  have := LieHom.congr_fun this y
  simp only [LieHom.coe_comp, Function.comp_apply] at this
  rw [this]
  simp

/-- `𝔫̃₊` kills `1 ∈ T(V)`. -/
lemma tensorRep_eHom_one (z : FreeLieAlgebra K ι) : tensorRep P Λ (eHom P z) 1 = 0 := by
  induction z using FreeLieAlgebra.induction_on with
  | of i => rw [eHom_of, tensorRep_e, ← word_nil, repE_word]; rfl
  | zero => simp
  | add y z hy hz => simp [hy, hz]
  | smul a y hy => simp [hy]
  | lie y z hy hz =>
    simp [LieRing.of_associative_ring_bracket, hy, hz]

/-- The map `𝔥 → 𝔤̃(A)` is injective ([Kac] Thm. 1.2 (c)). -/
theorem h_injective : Function.Injective (h P) := by
  rw [← LinearMap.ker_eq_bot, LinearMap.ker_eq_bot']
  intro a ha
  refine (forall_dual_apply_eq_zero_iff K a).mp fun Λ ↦ ?_
  have := tensorRep_h_one P Λ a
  rw [ha, map_zero, LinearMap.zero_apply, eq_comm, smul_eq_zero] at this
  simpa using this

/-- `𝔫̃₋` is freely generated by the `fᵢ` ([Kac] Thm. 1.2 (b)). -/
theorem fHom_injective : Function.Injective (fHom P) := by
  intro y z hyz
  apply FreeLieAlgebra.toFreeAlgebra_injective ι K
  rw [← tensorRep_fHom_one P 0, ← tensorRep_fHom_one P 0, hyz]

/-- The automorphism of the free Lie algebra negating the generators. -/
noncomputable def negGen : FreeLieAlgebra K ι →ₗ⁅K⁆ FreeLieAlgebra K ι :=
  FreeLieAlgebra.lift K fun i ↦ -FreeLieAlgebra.of K i

omit [Fintype ι] [DecidableEq ι] in
lemma negGen_negGen (y : FreeLieAlgebra K ι) : negGen (negGen y) = y := by
  have : (negGen (K := K) (ι := ι)).comp negGen = LieHom.id := by ext; simp [negGen]
  exact LieHom.congr_fun this y

lemma eHom_eq : eHom P = (chevalleyInvolution P).comp ((fHom P).comp negGen) := by
  ext i; simp [negGen]

/-- `𝔫̃₊` is freely generated by the `eᵢ` ([Kac] Thm. 1.2 (b)). -/
theorem eHom_injective : Function.Injective (eHom P) := by
  rw [eHom_eq, LieHom.coe_comp, LieHom.coe_comp]
  refine Function.Injective.comp ?_ (Function.Injective.comp (fHom_injective P) ?_)
  · exact Function.LeftInverse.injective (chevalleyInvolution_chevalleyInvolution P)
  · exact Function.LeftInverse.injective negGen_negGen

/-! ### The triangular decomposition -/

/-- The linear map `L(ι) × 𝔥 × L(ι) → 𝔤̃(A)`, `(y, a, z) ↦ fHom y + h a + eHom z`. -/
noncomputable def triangularMap :
    FreeLieAlgebra K ι × H × FreeLieAlgebra K ι →ₗ[K] P.AuxLieAlgebra :=
  (fHom P : FreeLieAlgebra K ι →ₗ[K] P.AuxLieAlgebra).coprod
    ((h P).coprod (eHom P : FreeLieAlgebra K ι →ₗ[K] P.AuxLieAlgebra))

@[simp] lemma triangularMap_apply (y : FreeLieAlgebra K ι) (a : H) (z : FreeLieAlgebra K ι) :
    triangularMap P (y, a, z) = fHom P y + h P a + eHom P z := by
  simp [triangularMap, add_assoc]

lemma triangularMap_injective : Function.Injective (triangularMap P) := by
  rw [← LinearMap.ker_eq_bot, LinearMap.ker_eq_bot']
  rintro ⟨y, a, z⟩ hyaz
  rw [triangularMap_apply] at hyaz
  have key : ∀ Λ : Dual K H,
      FreeLieAlgebra.toFreeAlgebra K ι y + Λ a • (1 : FreeAlgebra K ι) = 0 := by
    intro Λ
    have := congr_arg (fun x ↦ tensorRep P Λ x 1) hyaz
    simpa [tensorRep_fHom_one, tensorRep_h_one, tensorRep_eHom_one] using this
  -- the constant term of `toFreeAlgebra y` vanishes
  have hconst : FreeAlgebra.algebraMapInv (FreeLieAlgebra.toFreeAlgebra K ι y) = 0 := by
    have : (FreeAlgebra.algebraMapInv : FreeAlgebra K ι →ₐ[K] K).toLieHom.comp
        (FreeLieAlgebra.toFreeAlgebra K ι) = 0 := by
      ext i
      simp [FreeAlgebra.algebraMapInv]
    simpa using LieHom.congr_fun this y
  have ha : a = 0 := by
    refine (forall_dual_apply_eq_zero_iff K a).mp fun Λ ↦ ?_
    have := congr_arg FreeAlgebra.algebraMapInv (key Λ)
    simpa [hconst, Algebra.smul_def] using this
  subst ha
  have hy : y = 0 := by
    apply FreeLieAlgebra.toFreeAlgebra_injective ι K
    simpa using key 0
  subst hy
  have hz : z = 0 := by
    apply eHom_injective P
    simpa using hyaz
  simp [hz]

lemma lie_h_fHom (a : H) (y : FreeLieAlgebra K ι) : ∃ y', ⁅h P a, fHom P y⁆ = fHom P y' := by
  induction y using FreeLieAlgebra.induction_on with
  | of i => exact ⟨-(P.root i a • FreeLieAlgebra.of K i), by simp [lie_h_f]⟩
  | zero => exact ⟨0, by simp⟩
  | add y z hy hz =>
    obtain ⟨y', hy⟩ := hy; obtain ⟨z', hz⟩ := hz
    exact ⟨y' + z', by simp [hy, hz]⟩
  | smul c y hy => obtain ⟨y', hy⟩ := hy; exact ⟨c • y', by simp [hy]⟩
  | lie y z hy hz =>
    obtain ⟨y', hy⟩ := hy; obtain ⟨z', hz⟩ := hz
    exact ⟨⁅y', z⁆ + ⁅y, z'⁆, by simp [leibniz_lie, hy, hz]⟩

lemma lie_e_fHom (i : ι) (y : FreeLieAlgebra K ι) :
    ∃ y' b, ⁅e P i, fHom P y⁆ = fHom P y' + h P b := by
  induction y using FreeLieAlgebra.induction_on with
  | of j =>
    by_cases hij : i = j
    · subst hij; exact ⟨0, P.coroot i, by simp⟩
    · exact ⟨0, 0, by simp [lie_e_f_of_ne P hij]⟩
  | zero => exact ⟨0, 0, by simp⟩
  | add y z hy hz =>
    obtain ⟨y', b, hy⟩ := hy; obtain ⟨z', c, hz⟩ := hz
    exact ⟨y' + z', b + c, by simp [hy, hz]; abel⟩
  | smul c y hy => obtain ⟨y', b, hy⟩ := hy; exact ⟨c • y', c • b, by simp [hy]⟩
  | lie y z hy hz =>
    obtain ⟨y', b, hy⟩ := hy; obtain ⟨z', c, hz⟩ := hz
    obtain ⟨w, hw⟩ := lie_h_fHom P b z
    obtain ⟨w', hw'⟩ := lie_h_fHom P c y
    refine ⟨⁅y', z⁆ + w + ⁅y, z'⁆ - w', 0, ?_⟩
    rw [LieHom.map_lie, leibniz_lie, hy, hz, add_lie, lie_add, hw, ← lie_skew (fHom P y) (h P c),
      hw']
    simp only [map_add, map_sub, LieHom.map_lie, map_zero, add_zero]
    abel

lemma chevalleyInvolution_fHom (y : FreeLieAlgebra K ι) :
    chevalleyInvolution P (fHom P y) = eHom P (negGen y) := by
  rw [eHom_eq, LieHom.comp_apply, LieHom.comp_apply, negGen_negGen]

lemma chevalleyInvolution_eHom (z : FreeLieAlgebra K ι) :
    chevalleyInvolution P (eHom P z) = fHom P (negGen z) := by
  conv_lhs => rw [← negGen_negGen z, ← chevalleyInvolution_fHom]
  rw [chevalleyInvolution_chevalleyInvolution]

lemma lie_h_eHom (a : H) (z : FreeLieAlgebra K ι) : ∃ z', ⁅h P a, eHom P z⁆ = eHom P z' := by
  obtain ⟨w, hw⟩ := lie_h_fHom P (-a) (negGen z)
  refine ⟨negGen w, ?_⟩
  rw [← chevalleyInvolution_fHom, ← hw, LieHom.map_lie, chevalleyInvolution_h,
    chevalleyInvolution_fHom, negGen_negGen, map_neg, neg_neg]

lemma lie_f_eHom (i : ι) (z : FreeLieAlgebra K ι) :
    ∃ z' b, ⁅f P i, eHom P z⁆ = eHom P z' + h P b := by
  obtain ⟨y', b, hy⟩ := lie_e_fHom P i (negGen z)
  refine ⟨-negGen y', b, ?_⟩
  have := congr_arg (chevalleyInvolution P) hy
  rw [LieHom.map_lie, chevalleyInvolution_e, chevalleyInvolution_fHom, negGen_negGen, map_add,
    chevalleyInvolution_fHom, chevalleyInvolution_h, neg_lie] at this
  rw [map_neg, ← neg_neg (⁅f P i, eHom P z⁆), this]
  abel

lemma triangularMap_surjective : Function.Surjective (triangularMap P) := by
  rw [← LinearMap.range_eq_top]
  set S := LinearMap.range (triangularMap P)
  have hf : ∀ y, fHom P y ∈ S := fun y ↦ ⟨(y, 0, 0), by simp⟩
  have hh : ∀ a, h P a ∈ S := fun a ↦ ⟨(0, a, 0), by simp⟩
  have he : ∀ z, eHom P z ∈ S := fun z ↦ ⟨(0, 0, z), by simp⟩
  have hS : ∀ x ∈ S, ∃ y a z, x = fHom P y + h P a + eHom P z := by
    rintro x ⟨⟨y, a, z⟩, rfl⟩; exact ⟨y, a, z, by simp⟩
  refine eq_top_of_generators S (fun i ↦ by simpa using he (FreeLieAlgebra.of K i))
    (fun i ↦ by simpa using hf (FreeLieAlgebra.of K i)) hh ?_ ?_ ?_
  · intro i x hx
    obtain ⟨y, a, z, rfl⟩ := hS x hx
    obtain ⟨y', b, hy⟩ := lie_e_fHom P i y
    have h1 : ⁅e P i, fHom P y⁆ ∈ S := hy ▸ S.add_mem (hf _) (hh _)
    have h2 : ⁅e P i, h P a⁆ ∈ S := by
      rw [← lie_skew, lie_h_e, ← eHom_of]; exact S.neg_mem (S.smul_mem _ (he _))
    have h3 : ⁅e P i, eHom P z⁆ ∈ S := by rw [← eHom_of, ← LieHom.map_lie]; exact he _
    rw [lie_add, lie_add]; exact S.add_mem (S.add_mem h1 h2) h3
  · intro i x hx
    obtain ⟨y, a, z, rfl⟩ := hS x hx
    obtain ⟨z', b, hz⟩ := lie_f_eHom P i z
    have h1 : ⁅f P i, fHom P y⁆ ∈ S := by rw [← fHom_of, ← LieHom.map_lie]; exact hf _
    have h2 : ⁅f P i, h P a⁆ ∈ S := by
      rw [← lie_skew, lie_h_f, neg_neg, ← fHom_of]; exact S.smul_mem _ (hf _)
    have h3 : ⁅f P i, eHom P z⁆ ∈ S := hz ▸ S.add_mem (he _) (hh _)
    rw [lie_add, lie_add]; exact S.add_mem (S.add_mem h1 h2) h3
  · intro a x hx
    obtain ⟨y, b, z, rfl⟩ := hS x hx
    obtain ⟨y', hy⟩ := lie_h_fHom P a y
    obtain ⟨z', hz⟩ := lie_h_eHom P a z
    rw [lie_add, lie_add, hy, hz, lie_h_h, add_zero]
    exact S.add_mem (hf _) (he _)

/-- The triangular decomposition `𝔤̃(A) = 𝔫̃₋ ⊕ 𝔥 ⊕ 𝔫̃₊`, with `𝔫̃₋` and `𝔫̃₊` freely generated by
the `fᵢ` and the `eᵢ` respectively ([Kac] Thm. 1.2 (a), (b), (c)). -/
noncomputable def triangularEquiv :
    (FreeLieAlgebra K ι × H × FreeLieAlgebra K ι) ≃ₗ[K] P.AuxLieAlgebra :=
  LinearEquiv.ofBijective (triangularMap P)
    ⟨triangularMap_injective P, triangularMap_surjective P⟩

@[simp] lemma triangularEquiv_apply (y : FreeLieAlgebra K ι) (a : H) (z : FreeLieAlgebra K ι) :
    triangularEquiv P (y, a, z) = fHom P y + h P a + eHom P z :=
  triangularMap_apply P y a z

end AuxLieAlgebra

end Matrix.Realization

end
