/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import Mathlib.Algebra.Lie.SerreConstruction
import LieLean.Algebra.Lie.KacMoody.GabberKac

/-!
# Comparison of `𝔤(A)` with `Matrix.ToLieAlgebra`

Mathlib's `Matrix.ToLieAlgebra R A` is the Lie algebra generated by `Hᵢ, Eᵢ, Fᵢ` (`i ∈ I`) subject
to the Chevalley–Serre relations `[Hᵢ, Hⱼ] = 0`, `[Eᵢ, Fⱼ] = δᵢⱼ Hᵢ`, `[Hᵢ, Eⱼ] = aᵢⱼ Eⱼ`,
`[Hᵢ, Fⱼ] = -aᵢⱼ Fⱼ`, `(ad Eᵢ)^{1 - aᵢⱼ} Eⱼ = 0 = (ad Fᵢ)^{1 - aᵢⱼ} Fⱼ` (`i ≠ j`). Its Cartan
part is spanned by the `n` elements `Hᵢ`, whereas `𝔤(A)` has Cartan subalgebra `𝔥` of dimension
`2n - rank A`.

For a generalized Cartan matrix `A` over a field of characteristic zero there is a morphism
`Matrix.ToLieAlgebra K A → 𝔤(A)`, `Hᵢ ↦ αᵢ^∨`, `Eᵢ ↦ eᵢ`, `Fᵢ ↦ fᵢ` (the Serre relations hold in
`𝔤(A)`), with image the derived algebra `𝔤'(A)`, the subalgebra generated by the `eᵢ, fᵢ`
([Kac] §1.3). If moreover `A` is symmetrizable and nonsingular, then the coroots span `𝔥` and
this morphism is an isomorphism: its inverse comes from the universal property of `𝔤̃(A)`, which
factors through `𝔤(A) = 𝔤̃(A)/𝔯` because `𝔯` is generated by the Serre elements (Gabber–Kac,
[Kac] Thm. 9.11). For `A` of finite type this is Serre's theorem ([Hum] §18.3, over an
algebraically closed field).

## Main definitions

* `Matrix.ToLieAlgebra.mk`, `Matrix.ToLieAlgebra.h`, `.e`, `.f`: the quotient map from the free
  Lie algebra and the generators `Hᵢ, Eᵢ, Fᵢ`.
* `Matrix.ToLieAlgebra.lift`: the universal property of `Matrix.ToLieAlgebra`.
* `Matrix.Realization.KacMoodyAlgebra.ofToLieAlgebra`: the morphism
  `Matrix.ToLieAlgebra K A → 𝔤(A)`.
* `Matrix.Realization.KacMoodyAlgebra.toLieAlgebraEquiv`: the isomorphism
  `Matrix.ToLieAlgebra K A ≃ 𝔤(A)` for a nonsingular symmetrizable generalized Cartan matrix.

## Main results

* `Matrix.Realization.KacMoodyAlgebra.range_ofToLieAlgebra`: the image of
  `Matrix.ToLieAlgebra K A` in `𝔤(A)` is the subalgebra generated by the `eᵢ, fᵢ`.
* `Matrix.Realization.KacMoodyAlgebra.lieSpan_e_f_eq_derivedSeries`,
  `Matrix.Realization.KacMoodyAlgebra.range_ofToLieAlgebra_eq_derivedSeries`: this subalgebra is
  the derived algebra `𝔤'(A) = [𝔤(A), 𝔤(A)]`.
* `Matrix.Realization.span_coroot_eq_top_of_det_ne_zero`: for nonsingular `A` the coroots span
  `𝔥`.
* `Matrix.Realization.KacMoodyAlgebra.toLieAlgebraEquiv`: for a nonsingular symmetrizable
  generalized Cartan matrix, `Matrix.ToLieAlgebra K A ≃ 𝔤(A)` (Serre's theorem in finite type).

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §1.3, §9.11.
* [Hum] J. E. Humphreys, *Introduction to Lie algebras and representation theory*, GTM 9, §18.3.
-/

open FreeLieAlgebra Module LieAlgebra

noncomputable section

/-! ### API for `Matrix.ToLieAlgebra` -/

namespace Matrix.ToLieAlgebra

open CartanMatrix

variable {ι : Type*} [DecidableEq ι] (R : Type*) [CommRing R] (A : Matrix ι ι ℤ)

/-- The quotient map from the free Lie algebra on the generators `Hᵢ, Eᵢ, Fᵢ`. -/
def mk : FreeLieAlgebra R (Generators ι) →ₗ⁅R⁆ Matrix.ToLieAlgebra R A :=
  LieIdeal.mkHom (Relations.toIdeal R A)

lemma mk_surjective : Function.Surjective (mk R A) := LieIdeal.mkHom_surjective _

/-- The generator `Hᵢ`. -/
def h (i : ι) : Matrix.ToLieAlgebra R A := mk R A (FreeLieAlgebra.of R (Generators.H i))

/-- The generator `Eᵢ`. -/
def e (i : ι) : Matrix.ToLieAlgebra R A := mk R A (FreeLieAlgebra.of R (Generators.E i))

/-- The generator `Fᵢ`. -/
def f (i : ι) : Matrix.ToLieAlgebra R A := mk R A (FreeLieAlgebra.of R (Generators.F i))

variable {R A} in
lemma mk_eq_zero_of_mem {x : FreeLieAlgebra R (Generators ι)} (hx : x ∈ Relations.toSet R A) :
    mk R A x = 0 :=
  (LieIdeal.mkHom_eq_zero_iff _).mpr (LieSubmodule.subset_lieSpan hx)

lemma lie_h_h (i j : ι) : ⁅h R A i, h R A j⁆ = 0 := by
  have := mk_eq_zero_of_mem (R := R) (A := A)
    (Or.inl <| Or.inl <| Or.inl <| Or.inl <| Or.inl ⟨(i, j), rfl⟩)
  rwa [Relations.HH, Function.uncurry_apply_pair, LieHom.map_lie] at this

lemma lie_e_f (i j : ι) : ⁅e R A i, f R A j⁆ = if i = j then h R A i else 0 := by
  have := mk_eq_zero_of_mem (R := R) (A := A)
    (Or.inl <| Or.inl <| Or.inl <| Or.inl <| Or.inr ⟨(i, j), rfl⟩)
  rw [Relations.EF, Function.uncurry_apply_pair] at this
  split_ifs at this ⊢ with hij
  · subst hij
    rwa [map_sub, LieHom.map_lie, sub_eq_zero] at this
  · rwa [LieHom.map_lie] at this

lemma lie_h_e (i j : ι) : ⁅h R A i, e R A j⁆ = A i j • e R A j := by
  have := mk_eq_zero_of_mem (R := R) (A := A) (Or.inl <| Or.inl <| Or.inl <| Or.inr ⟨(i, j), rfl⟩)
  rwa [Relations.HE, Function.uncurry_apply_pair, map_sub, LieHom.map_lie, map_zsmul,
    sub_eq_zero] at this

lemma lie_h_f (i j : ι) : ⁅h R A i, f R A j⁆ = -(A i j • f R A j) := by
  have := mk_eq_zero_of_mem (R := R) (A := A) (Or.inl <| Or.inl <| Or.inr ⟨(i, j), rfl⟩)
  rwa [Relations.HF, Function.uncurry_apply_pair, map_add, LieHom.map_lie, map_zsmul,
    add_eq_zero_iff_eq_neg] at this

/-- Lie algebra morphisms commute with iterated adjoint actions (over a commutative ring). -/
private lemma map_ad_pow {L L' : Type*} [LieRing L] [LieAlgebra R L] [LieRing L']
    [LieAlgebra R L'] (φ : L →ₗ⁅R⁆ L') (x y : L) (n : ℕ) :
    φ ((ad R L x ^ n) y) = (ad R L' (φ x) ^ n) (φ y) := by
  induction n with
  | zero => simp
  | succ n ih => rw [pow_succ', Module.End.mul_apply, ad_apply, LieHom.map_lie, ih, pow_succ',
      Module.End.mul_apply, ad_apply]

lemma serre_e (i j : ι) :
    (ad R _ (e R A i) ^ (-A i j).toNat) ⁅e R A i, e R A j⁆ = 0 := by
  have := mk_eq_zero_of_mem (R := R) (A := A) (Or.inl <| Or.inr ⟨(i, j), rfl⟩)
  rwa [Relations.adE, Function.uncurry_apply_pair, map_ad_pow, LieHom.map_lie] at this

lemma serre_f (i j : ι) :
    (ad R _ (f R A i) ^ (-A i j).toNat) ⁅f R A i, f R A j⁆ = 0 := by
  have := mk_eq_zero_of_mem (R := R) (A := A) (Or.inr ⟨(i, j), rfl⟩)
  rwa [Relations.adF, Function.uncurry_apply_pair, map_ad_pow, LieHom.map_lie] at this

section lift

variable (L : Type*) [LieRing L] [LieAlgebra R L]

/-- Data of a morphism out of `Matrix.ToLieAlgebra R A`: images of the generators `Hᵢ, Eᵢ, Fᵢ`
satisfying the Chevalley–Serre relations. The Serre relations are only required for `i ≠ j`
(for `i = j` they hold trivially). -/
structure LiftData where
  /-- The images of the `Hᵢ`. -/
  h : ι → L
  /-- The images of the `Eᵢ`. -/
  e : ι → L
  /-- The images of the `Fᵢ`. -/
  f : ι → L
  lie_h_h : ∀ i j, ⁅h i, h j⁆ = 0
  lie_e_f : ∀ i j, ⁅e i, f j⁆ = if i = j then h i else 0
  lie_h_e : ∀ i j, ⁅h i, e j⁆ = A i j • e j
  lie_h_f : ∀ i j, ⁅h i, f j⁆ = -(A i j • f j)
  serre_e : ∀ i j, i ≠ j → (ad R L (e i) ^ (-A i j).toNat) ⁅e i, e j⁆ = 0
  serre_f : ∀ i j, i ≠ j → (ad R L (f i) ^ (-A i j).toNat) ⁅f i, f j⁆ = 0

variable {R A L}

/-- The map on generators. -/
def LiftData.gen (D : LiftData R A L) : Generators ι → L
  | .H i => D.h i
  | .E i => D.e i
  | .F i => D.f i

lemma LiftData.le_ker (D : LiftData R A L) :
    Relations.toIdeal R A ≤ (FreeLieAlgebra.lift R D.gen).ker := by
  rw [Relations.toIdeal, LieSubmodule.lieSpan_le]
  rintro x (((((⟨⟨i, j⟩, rfl⟩ | ⟨⟨i, j⟩, rfl⟩) | ⟨⟨i, j⟩, rfl⟩) | ⟨⟨i, j⟩, rfl⟩) |
    ⟨⟨i, j⟩, rfl⟩) | ⟨⟨i, j⟩, rfl⟩)
  · simp [Relations.HH, LiftData.gen, D.lie_h_h]
  · simp only [Relations.EF, Function.uncurry_apply_pair, SetLike.mem_coe, LieHom.mem_ker]
    split_ifs with hij
    · subst hij; simp [LiftData.gen, D.lie_e_f]
    · simp [LiftData.gen, D.lie_e_f, hij]
  · simp [Relations.HE, LiftData.gen, D.lie_h_e]
  · simp [Relations.HF, LiftData.gen, D.lie_h_f]
  · simp only [Relations.adE, Function.uncurry_apply_pair, SetLike.mem_coe, LieHom.mem_ker,
      map_ad_pow, LieHom.map_lie, Function.comp_apply, lift_of_apply, LiftData.gen]
    by_cases hij : i = j
    · subst hij; simp
    · exact D.serre_e i j hij
  · simp only [Relations.adF, Function.uncurry_apply_pair, SetLike.mem_coe, LieHom.mem_ker,
      map_ad_pow, LieHom.map_lie, Function.comp_apply, lift_of_apply, LiftData.gen]
    by_cases hij : i = j
    · subst hij; simp
    · exact D.serre_f i j hij

/-- The universal property of `Matrix.ToLieAlgebra R A`. -/
def lift (D : LiftData R A L) : Matrix.ToLieAlgebra R A →ₗ⁅R⁆ L :=
  LieIdeal.lift (Relations.toIdeal R A) (FreeLieAlgebra.lift R D.gen) D.le_ker

@[simp] lemma lift_h (D : LiftData R A L) (i : ι) : lift D (h R A i) = D.h i :=
  lift_of_apply (R := R) D.gen (Generators.H i)

@[simp] lemma lift_e (D : LiftData R A L) (i : ι) : lift D (e R A i) = D.e i :=
  lift_of_apply (R := R) D.gen (Generators.E i)

@[simp] lemma lift_f (D : LiftData R A L) (i : ι) : lift D (f R A i) = D.f i :=
  lift_of_apply (R := R) D.gen (Generators.F i)

/-- Morphisms out of `Matrix.ToLieAlgebra R A` are determined by their values on the
generators. -/
@[ext]
lemma hom_ext {g₁ g₂ : Matrix.ToLieAlgebra R A →ₗ⁅R⁆ L} (hh : ∀ i, g₁ (h R A i) = g₂ (h R A i))
    (he : ∀ i, g₁ (e R A i) = g₂ (e R A i)) (hf : ∀ i, g₁ (f R A i) = g₂ (f R A i)) :
    g₁ = g₂ := by
  have : g₁.comp (mk R A) = g₂.comp (mk R A) := by
    ext (x | x | x)
    · exact hh x
    · exact he x
    · exact hf x
  exact LieIdeal.lieHom_ext _ fun x ↦ LieHom.congr_fun this x

end lift

/-- The generators span `Matrix.ToLieAlgebra R A` as a Lie algebra. -/
lemma lieSpan_generators :
    LieSubalgebra.lieSpan R (Matrix.ToLieAlgebra R A)
      (Set.range (h R A) ∪ Set.range (e R A) ∪ Set.range (f R A)) = ⊤ := by
  rw [eq_top_iff]
  rintro y -
  obtain ⟨x, rfl⟩ := mk_surjective R A y
  induction x using FreeLieAlgebra.induction_on with
  | of g =>
    apply LieSubalgebra.subset_lieSpan
    rcases g with i | i | i
    · exact Or.inl (Or.inl ⟨i, rfl⟩)
    · exact Or.inl (Or.inr ⟨i, rfl⟩)
    · exact Or.inr ⟨i, rfl⟩
  | zero => simp
  | add y z hy hz => simpa using LieSubalgebra.add_mem _ hy hz
  | smul a y hy => simpa using LieSubalgebra.smul_mem _ a hy
  | lie y z hy hz => simpa using LieSubalgebra.lie_mem _ hy hz

end Matrix.ToLieAlgebra

/-! ### The morphism `Matrix.ToLieAlgebra K A → 𝔤(A)` -/

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H)

namespace KacMoodyAlgebra

variable {P} in
/-- Morphisms out of `𝔤(A)` are determined by their values on the generators. -/
lemma hom_ext {L : Type*} [LieRing L] [LieAlgebra K L] {g₁ g₂ : P.KacMoodyAlgebra →ₗ⁅K⁆ L}
    (he : ∀ i, g₁ (e P i) = g₂ (e P i)) (hf : ∀ i, g₁ (f P i) = g₂ (f P i))
    (hh : ∀ a, g₁ (h P a) = g₂ (h P a)) : g₁ = g₂ := by
  have : g₁.comp (π P) = g₂.comp (π P) := AuxLieAlgebra.hom_ext he hf hh
  exact LieIdeal.lieHom_ext _ fun x ↦ LieHom.congr_fun this x

variable [CharZero K] (hA : A.IsGeneralizedCartan)

/-- The data defining `Matrix.ToLieAlgebra K A → 𝔤(A)`: `Hᵢ ↦ αᵢ^∨`, `Eᵢ ↦ eᵢ`, `Fᵢ ↦ fᵢ`. -/
def toLieAlgebraLiftData : Matrix.ToLieAlgebra.LiftData K A P.KacMoodyAlgebra where
  h i := h P (P.coroot i)
  e := e P
  f := f P
  lie_h_h _ _ := lie_h_h P _ _
  lie_e_f i j := by rw [lie_e_f]
  lie_h_e i j := by rw [lie_h_e, root_coroot, Int.cast_smul_eq_zsmul]
  lie_h_f i j := by rw [lie_h_f, root_coroot, Int.cast_smul_eq_zsmul]
  serre_e _ _ hij := serre_e P hA hij
  serre_f _ _ hij := serre_f P hA hij

/-- The morphism `Matrix.ToLieAlgebra K A → 𝔤(A)`, `Hᵢ ↦ αᵢ^∨`, `Eᵢ ↦ eᵢ`, `Fᵢ ↦ fᵢ`, for a
generalized Cartan matrix `A` (it exists since the Serre relations hold in `𝔤(A)`). -/
def ofToLieAlgebra : Matrix.ToLieAlgebra K A →ₗ⁅K⁆ P.KacMoodyAlgebra :=
  Matrix.ToLieAlgebra.lift (toLieAlgebraLiftData P hA)

@[simp] lemma ofToLieAlgebra_h (i : ι) :
    ofToLieAlgebra P hA (Matrix.ToLieAlgebra.h K A i) = h P (P.coroot i) :=
  Matrix.ToLieAlgebra.lift_h _ i

@[simp] lemma ofToLieAlgebra_e (i : ι) :
    ofToLieAlgebra P hA (Matrix.ToLieAlgebra.e K A i) = e P i :=
  Matrix.ToLieAlgebra.lift_e _ i

@[simp] lemma ofToLieAlgebra_f (i : ι) :
    ofToLieAlgebra P hA (Matrix.ToLieAlgebra.f K A i) = f P i :=
  Matrix.ToLieAlgebra.lift_f _ i

/-- The image of `Matrix.ToLieAlgebra K A` in `𝔤(A)` is the subalgebra `𝔤'(A)` generated by the
Chevalley generators `eᵢ, fᵢ` ([Kac] §1.3). -/
theorem range_ofToLieAlgebra :
    (ofToLieAlgebra P hA).range =
      LieSubalgebra.lieSpan K P.KacMoodyAlgebra (Set.range (e P) ∪ Set.range (f P)) := by
  have he : ofToLieAlgebra P hA ∘ Matrix.ToLieAlgebra.e K A = e P :=
    funext (ofToLieAlgebra_e P hA)
  have hf : ofToLieAlgebra P hA ∘ Matrix.ToLieAlgebra.f K A = f P :=
    funext (ofToLieAlgebra_f P hA)
  rw [LieHom.range_eq_map, ← Matrix.ToLieAlgebra.lieSpan_generators, LieSubalgebra.map_lieSpan,
    Set.image_union, Set.image_union, ← Set.range_comp, ← Set.range_comp, ← Set.range_comp, he,
    hf]
  refine le_antisymm (LieSubalgebra.lieSpan_le.mpr ?_)
    (LieSubalgebra.lieSpan_mono (Set.union_subset_union_left _ Set.subset_union_right))
  rintro _ ((⟨i, rfl⟩ | ⟨i, rfl⟩) | ⟨i, rfl⟩)
  · simp only [Function.comp_apply, ofToLieAlgebra_h, ← lie_e_f_self]
    exact LieSubalgebra.lie_mem _
      (LieSubalgebra.subset_lieSpan (Or.inl ⟨i, rfl⟩))
      (LieSubalgebra.subset_lieSpan (Or.inr ⟨i, rfl⟩))
  · exact LieSubalgebra.subset_lieSpan (Or.inl ⟨i, rfl⟩)
  · exact LieSubalgebra.subset_lieSpan (Or.inr ⟨i, rfl⟩)

/-! ### The derived algebra `𝔤'(A)` -/

omit [CharZero K] in
lemma lie_h_mem_lieSpan_e_f (a : H) {x : P.KacMoodyAlgebra}
    (hx : x ∈ LieSubalgebra.lieSpan K P.KacMoodyAlgebra (Set.range (e P) ∪ Set.range (f P))) :
    ⁅h P a, x⁆ ∈ LieSubalgebra.lieSpan K P.KacMoodyAlgebra (Set.range (e P) ∪ Set.range (f P)) := by
  set S := LieSubalgebra.lieSpan K P.KacMoodyAlgebra (Set.range (e P) ∪ Set.range (f P))
  induction hx using LieSubalgebra.lieSpan_induction with
  | mem x hx =>
    rcases hx with ⟨i, rfl⟩ | ⟨i, rfl⟩
    · rw [lie_h_e]
      exact S.smul_mem _ (LieSubalgebra.subset_lieSpan (Or.inl ⟨i, rfl⟩))
    · rw [lie_h_f]
      exact S.neg_mem (S.smul_mem _ (LieSubalgebra.subset_lieSpan (Or.inr ⟨i, rfl⟩)))
  | zero => simp
  | add x y _ _ hx hy => rw [lie_add]; exact S.add_mem hx hy
  | smul c x _ hx => rw [lie_smul]; exact S.smul_mem c hx
  | lie x y hx' hy' hx hy =>
    rw [leibniz_lie]
    exact S.add_mem (S.lie_mem hx hy') (S.lie_mem hx' hy)

omit [CharZero K] in
/-- The subalgebra of `𝔤(A)` generated by the `eᵢ, fᵢ` is an ideal. -/
lemma lie_mem_lieSpan_e_f (x : P.KacMoodyAlgebra) {y : P.KacMoodyAlgebra}
    (hy : y ∈ LieSubalgebra.lieSpan K P.KacMoodyAlgebra (Set.range (e P) ∪ Set.range (f P))) :
    ⁅x, y⁆ ∈ LieSubalgebra.lieSpan K P.KacMoodyAlgebra (Set.range (e P) ∪ Set.range (f P)) := by
  set S := LieSubalgebra.lieSpan K P.KacMoodyAlgebra (Set.range (e P) ∪ Set.range (f P))
  obtain ⟨x, rfl⟩ := π_surjective P x
  induction x using AuxLieAlgebra.induction_on generalizing y with
  | he i => exact S.lie_mem (LieSubalgebra.subset_lieSpan (Or.inl ⟨i, rfl⟩)) hy
  | hf i => exact S.lie_mem (LieSubalgebra.subset_lieSpan (Or.inr ⟨i, rfl⟩)) hy
  | hh a => exact lie_h_mem_lieSpan_e_f P a hy
  | zero => simp
  | add x z hx hz => rw [map_add, add_lie]; exact S.add_mem (hx hy) (hz hy)
  | smul c x hx => rw [map_smul, smul_lie]; exact S.smul_mem c (hx hy)
  | lie x z hx hz => rw [LieHom.map_lie, lie_lie]; exact S.sub_mem (hx (hz hy)) (hz (hx hy))

omit [CharZero K] in
lemma lie_mem_lieSpan_e_f_of_mem_left {x : P.KacMoodyAlgebra}
    (hx : x ∈ LieSubalgebra.lieSpan K P.KacMoodyAlgebra (Set.range (e P) ∪ Set.range (f P)))
    (y : P.KacMoodyAlgebra) :
    ⁅x, y⁆ ∈ LieSubalgebra.lieSpan K P.KacMoodyAlgebra (Set.range (e P) ∪ Set.range (f P)) := by
  rw [← lie_skew]
  exact neg_mem (lie_mem_lieSpan_e_f P y hx)

omit [CharZero K] in
/-- `[𝔤(A), 𝔤(A)]` is contained in the subalgebra generated by the `eᵢ, fᵢ`. -/
lemma lie_mem_lieSpan_e_f' (x y : P.KacMoodyAlgebra) :
    ⁅x, y⁆ ∈ LieSubalgebra.lieSpan K P.KacMoodyAlgebra (Set.range (e P) ∪ Set.range (f P)) := by
  set S := LieSubalgebra.lieSpan K P.KacMoodyAlgebra (Set.range (e P) ∪ Set.range (f P))
  have hh (a : H) (x : P.KacMoodyAlgebra) : ⁅h P a, x⁆ ∈ S := by
    obtain ⟨x, rfl⟩ := π_surjective P x
    induction x using AuxLieAlgebra.induction_on with
    | he i => exact lie_h_mem_lieSpan_e_f P a (LieSubalgebra.subset_lieSpan (Or.inl ⟨i, rfl⟩))
    | hf i => exact lie_h_mem_lieSpan_e_f P a (LieSubalgebra.subset_lieSpan (Or.inr ⟨i, rfl⟩))
    | hh b => rw [π_h, lie_h_h]; exact S.zero_mem
    | zero => simp
    | add x z hx hz => rw [map_add, lie_add]; exact S.add_mem hx hz
    | smul c x hx => rw [map_smul, lie_smul]; exact S.smul_mem c hx
    | lie x z hx hz =>
      rw [LieHom.map_lie, leibniz_lie]
      exact S.add_mem (lie_mem_lieSpan_e_f_of_mem_left P hx _) (lie_mem_lieSpan_e_f P _ hz)
  obtain ⟨y, rfl⟩ := π_surjective P y
  induction y using AuxLieAlgebra.induction_on generalizing x with
  | he i => exact lie_mem_lieSpan_e_f P x (LieSubalgebra.subset_lieSpan (Or.inl ⟨i, rfl⟩))
  | hf i => exact lie_mem_lieSpan_e_f P x (LieSubalgebra.subset_lieSpan (Or.inr ⟨i, rfl⟩))
  | hh a => rw [π_h, ← lie_skew]; exact neg_mem (hh a x)
  | zero => simp
  | add y z hy hz => rw [map_add, lie_add]; exact S.add_mem (hy x) (hz x)
  | smul c y hy => rw [map_smul, lie_smul]; exact S.smul_mem c (hy x)
  | lie y z hy hz =>
    rw [LieHom.map_lie, leibniz_lie]
    exact S.add_mem (hz _) (lie_mem_lieSpan_e_f P _ (hz x))

include hA in
/-- The derived algebra `𝔤'(A) = [𝔤(A), 𝔤(A)]` is the subalgebra generated by the Chevalley
generators `eᵢ, fᵢ` ([Kac] §1.3), for a generalized Cartan matrix `A` over a field of
characteristic zero. -/
theorem lieSpan_e_f_eq_derivedSeries :
    LieSubalgebra.lieSpan K P.KacMoodyAlgebra (Set.range (e P) ∪ Set.range (f P)) =
      (derivedSeries K P.KacMoodyAlgebra 1 : LieSubalgebra K P.KacMoodyAlgebra) := by
  have hD : derivedSeries K P.KacMoodyAlgebra 1 = ⁅(⊤ : LieIdeal K P.KacMoodyAlgebra), ⊤⁆ := by
    rw [derivedSeries_def, derivedSeriesOfIdeal_succ, derivedSeriesOfIdeal_zero]
  refine le_antisymm (LieSubalgebra.lieSpan_le.mpr ?_) fun x hx ↦ ?_
  · have h2 (i : ι) : (2 : K) • e P i = ⁅h P (P.coroot i), e P i⁆ := by
      rw [lie_h_e, root_coroot, hA.diag i]; norm_num
    rintro _ (⟨i, rfl⟩ | ⟨i, rfl⟩)
    · have : e P i = (2 : K)⁻¹ • ⁅h P (P.coroot i), e P i⁆ := by
        rw [← h2, smul_smul, inv_mul_cancel₀ two_ne_zero, one_smul]
      rw [SetLike.mem_coe, LieIdeal.mem_toLieSubalgebra, hD, this]
      exact SMulMemClass.smul_mem _ (LieSubmodule.lie_mem_lie trivial trivial)
    · have : f P i = -(2 : K)⁻¹ • ⁅h P (P.coroot i), f P i⁆ := by
        rw [lie_h_f, root_coroot, hA.diag i, smul_neg, smul_smul]
        push_cast
        norm_num
      rw [SetLike.mem_coe, LieIdeal.mem_toLieSubalgebra, hD, this]
      exact SMulMemClass.smul_mem _ (LieSubmodule.lie_mem_lie trivial trivial)
  · rw [LieIdeal.mem_toLieSubalgebra, hD] at hx
    let S' : LieIdeal K P.KacMoodyAlgebra :=
      { (LieSubalgebra.lieSpan K P.KacMoodyAlgebra
          (Set.range (e P) ∪ Set.range (f P))).toSubmodule with
        lie_mem := fun {y} {_} hz ↦ lie_mem_lieSpan_e_f P y hz }
    have : ⁅(⊤ : LieIdeal K P.KacMoodyAlgebra), ⊤⁆ ≤ S' :=
      (LieSubmodule.lie_le_iff _ _ _).mpr fun y _ z _ ↦ lie_mem_lieSpan_e_f' P y z
    exact this hx

/-- The image of `Matrix.ToLieAlgebra K A` in `𝔤(A)` is the derived algebra
`𝔤'(A) = [𝔤(A), 𝔤(A)]` ([Kac] §1.3). -/
theorem range_ofToLieAlgebra_eq_derivedSeries :
    (ofToLieAlgebra P hA).range =
      (derivedSeries K P.KacMoodyAlgebra 1 : LieSubalgebra K P.KacMoodyAlgebra) := by
  rw [range_ofToLieAlgebra, lieSpan_e_f_eq_derivedSeries P hA]

end KacMoodyAlgebra

/-! ### The nonsingular symmetrizable case -/

variable {P}

/-- If `A` is nonsingular (and `𝔥` is finite-dimensional), then `dim 𝔥 = n` and the simple
coroots `αᵢ^∨` span `𝔥` (by [Kac] (1.1.1), (1.1.3)). -/
theorem span_coroot_eq_top_of_det_ne_zero [CharZero K] [FiniteDimensional K H]
    (hdet : A.det ≠ 0) : Submodule.span K (Set.range P.coroot) = ⊤ := by
  have hunit : IsUnit (A.map (Int.cast : ℤ → K)) := by
    rw [Matrix.isUnit_iff_isUnit_det, isUnit_iff_ne_zero]
    have := (Int.castRingHom K).map_det A
    rw [RingHom.mapMatrix_apply, eq_intCast, Int.coe_castRingHom] at this
    rw [← this]
    exact_mod_cast hdet
  have hrank := Matrix.rank_of_isUnit _ hunit
  have hfin := P.finrank_add_rank
  refine P.linearIndependent_coroot.span_eq_top_of_card_eq_finrank' ?_
  omega

namespace KacMoodyAlgebra

variable (hA : A.IsGeneralizedCartan) (hS : A.IsSymmetrizable)
  (hspan : Submodule.span K (Set.range P.coroot) = ⊤)

/-- The basis of `𝔥` given by the simple coroots, when they span `𝔥`. -/
def corootBasis : Basis ι K H := Basis.mk P.linearIndependent_coroot hspan.ge

omit [DecidableEq ι] in
@[simp] lemma corootBasis_apply (i : ι) : corootBasis hspan i = P.coroot i := by
  simp [corootBasis]

omit [DecidableEq ι] in
include hspan in
/-- Induction on `𝔥` along the simple coroots, when they span `𝔥`. -/
lemma induction_coroot {p : H → Prop} (a : H) (hc : ∀ i, p (P.coroot i)) (h0 : p 0)
    (hadd : ∀ a b, p a → p b → p (a + b)) (hsmul : ∀ (c : K) a, p a → p (c • a)) : p a := by
  have ha : a ∈ Submodule.span K (Set.range P.coroot) := hspan ▸ Submodule.mem_top
  induction ha using Submodule.span_induction with
  | mem x hx => obtain ⟨i, rfl⟩ := hx; exact hc i
  | zero => exact h0
  | add a b _ _ ha hb => exact hadd a b ha hb
  | smul c a _ ha => exact hsmul c a ha

/-- The linear map `𝔥 → Matrix.ToLieAlgebra K A`, `αᵢ^∨ ↦ Hᵢ`, when the coroots span `𝔥`. -/
def toLieAlgebraH : H →ₗ[K] Matrix.ToLieAlgebra K A :=
  (corootBasis hspan).constr K (Matrix.ToLieAlgebra.h K A)

@[simp] lemma toLieAlgebraH_coroot (i : ι) :
    toLieAlgebraH hspan (P.coroot i) = Matrix.ToLieAlgebra.h K A i := by
  rw [toLieAlgebraH, ← corootBasis_apply hspan, Basis.constr_basis]

variable (P) in
/-- The data defining `𝔤̃(A) → Matrix.ToLieAlgebra K A`, when the coroots span `𝔥`. -/
def auxLiftData : AuxLieAlgebra.LiftData P (Matrix.ToLieAlgebra K A) where
  h := toLieAlgebraH hspan
  e := Matrix.ToLieAlgebra.e K A
  f := Matrix.ToLieAlgebra.f K A
  lie_h_h a b := by
    induction a using induction_coroot hspan with
    | hc i =>
      induction b using induction_coroot hspan with
      | hc j => simp [Matrix.ToLieAlgebra.lie_h_h]
      | h0 => simp
      | hadd a b ha hb => rw [map_add, lie_add, ha, hb, add_zero]
      | hsmul c a ha => rw [map_smul, lie_smul, ha, smul_zero]
    | h0 => simp
    | hadd a a' ha ha' => rw [map_add, add_lie, ha, ha', add_zero]
    | hsmul c a ha => rw [map_smul, smul_lie, ha, smul_zero]
  lie_e_f i j := by
    rw [Matrix.ToLieAlgebra.lie_e_f]
    split_ifs <;> simp
  lie_h_e a i := by
    induction a using induction_coroot hspan with
    | hc j => simp [Matrix.ToLieAlgebra.lie_h_e, root_coroot, Int.cast_smul_eq_zsmul]
    | h0 => simp
    | hadd a b ha hb => rw [map_add, add_lie, ha, hb, map_add, add_smul]
    | hsmul c a ha => rw [map_smul, smul_lie, ha, map_smul, smul_eq_mul, mul_smul]
  lie_h_f a i := by
    induction a using induction_coroot hspan with
    | hc j => simp [Matrix.ToLieAlgebra.lie_h_f, root_coroot, Int.cast_smul_eq_zsmul]
    | h0 => simp
    | hadd a b ha hb => rw [map_add, add_lie, ha, hb, map_add, add_smul, neg_add]
    | hsmul c a ha => rw [map_smul, smul_lie, ha, map_smul, smul_eq_mul, mul_smul, smul_neg]

@[simp] lemma auxLift_h (a : H) :
    AuxLieAlgebra.lift (auxLiftData P hspan) (AuxLieAlgebra.h P a) = toLieAlgebraH hspan a :=
  AuxLieAlgebra.lift_h _ a

variable [CharZero K]

include hA hS in
lemma maxIdeal_le_ker_auxLift :
    AuxLieAlgebra.maxIdeal P ≤ (AuxLieAlgebra.lift (auxLiftData P hspan)).ker := by
  rw [AuxLieAlgebra.maxIdeal_eq_serreIdeal P hA hS, AuxLieAlgebra.serreIdeal,
    LieSubmodule.lieSpan_le]
  rintro x ⟨i, j, -, rfl | rfl⟩
  · simp [AuxLieAlgebra.serreE, LieHom.map_ad_pow, auxLiftData, Matrix.ToLieAlgebra.serre_e]
  · simp [AuxLieAlgebra.serreF, LieHom.map_ad_pow, auxLiftData, Matrix.ToLieAlgebra.serre_f]

/-- The morphism `𝔤(A) → Matrix.ToLieAlgebra K A`, `eᵢ ↦ Eᵢ`, `fᵢ ↦ Fᵢ`, `αᵢ^∨ ↦ Hᵢ`, for a
symmetrizable generalized Cartan matrix whose coroots span `𝔥`. It exists by the universal
property of `𝔤̃(A)` and the Gabber–Kac theorem ([Kac] Thm. 9.11). -/
def toToLieAlgebra : P.KacMoodyAlgebra →ₗ⁅K⁆ Matrix.ToLieAlgebra K A :=
  LieIdeal.lift _ (AuxLieAlgebra.lift (auxLiftData P hspan)) (maxIdeal_le_ker_auxLift hA hS hspan)

@[simp] lemma toToLieAlgebra_π (x : P.AuxLieAlgebra) :
    toToLieAlgebra hA hS hspan (π P x) = AuxLieAlgebra.lift (auxLiftData P hspan) x :=
  rfl

@[simp] lemma toToLieAlgebra_e (i : ι) :
    toToLieAlgebra hA hS hspan (e P i) = Matrix.ToLieAlgebra.e K A i := by
  rw [← π_e, toToLieAlgebra_π, AuxLieAlgebra.lift_e]; rfl

@[simp] lemma toToLieAlgebra_f (i : ι) :
    toToLieAlgebra hA hS hspan (f P i) = Matrix.ToLieAlgebra.f K A i := by
  rw [← π_f, toToLieAlgebra_π, AuxLieAlgebra.lift_f]; rfl

@[simp] lemma toToLieAlgebra_h (a : H) :
    toToLieAlgebra hA hS hspan (h P a) = toLieAlgebraH hspan a := by
  rw [← π_h, toToLieAlgebra_π, auxLift_h]

lemma toToLieAlgebra_comp_ofToLieAlgebra :
    (toToLieAlgebra hA hS hspan).comp (ofToLieAlgebra P hA) = LieHom.id := by
  ext i <;> simp

lemma ofToLieAlgebra_comp_toToLieAlgebra :
    (ofToLieAlgebra P hA).comp (toToLieAlgebra hA hS hspan) = LieHom.id := by
  refine hom_ext (fun i ↦ by simp) (fun i ↦ by simp) fun a ↦ ?_
  induction a using induction_coroot hspan with
  | hc i => simp
  | h0 => simp
  | hadd a b ha hb => simp_all
  | hsmul c a ha => simp_all

/-- For a symmetrizable generalized Cartan matrix `A` whose simple coroots span `𝔥` (i.e. `A`
nonsingular, see `span_coroot_eq_top_of_det_ne_zero`), `𝔤(A)` is isomorphic to Mathlib's
`Matrix.ToLieAlgebra K A`, the Lie algebra presented by the Chevalley generators and the
Chevalley–Serre relations ([Kac] Thm. 9.11 and the remark following it; Serre's theorem,
[Hum] §18.3, in finite type over an algebraically closed field). -/
def toLieAlgebraEquivOfSpan : Matrix.ToLieAlgebra K A ≃ₗ⁅K⁆ P.KacMoodyAlgebra :=
  { ofToLieAlgebra P hA with
    invFun := toToLieAlgebra hA hS hspan
    left_inv := fun x ↦ LieHom.congr_fun (toToLieAlgebra_comp_ofToLieAlgebra hA hS hspan) x
    right_inv := fun x ↦ LieHom.congr_fun (ofToLieAlgebra_comp_toToLieAlgebra hA hS hspan) x }

@[simp] lemma toLieAlgebraEquivOfSpan_apply (x : Matrix.ToLieAlgebra K A) :
    toLieAlgebraEquivOfSpan hA hS hspan x = ofToLieAlgebra P hA x :=
  rfl

@[simp] lemma toLieAlgebraEquivOfSpan_symm_apply (x : P.KacMoodyAlgebra) :
    (toLieAlgebraEquivOfSpan hA hS hspan).symm x = toToLieAlgebra hA hS hspan x :=
  rfl

variable (P) in
/-- **Serre-type presentation of `𝔤(A)`** ([Kac] Thm. 9.11 and the remark following it;
Serre's theorem, [Hum] §18.3, in finite type over an algebraically closed field). For a
nonsingular symmetrizable generalized Cartan
matrix `A` over a field of characteristic zero, `𝔤(A)` is isomorphic to Mathlib's
`Matrix.ToLieAlgebra K A`, the Lie algebra generated by `Hᵢ, Eᵢ, Fᵢ` subject to the
Chevalley–Serre relations, via `Hᵢ ↦ αᵢ^∨`, `Eᵢ ↦ eᵢ`, `Fᵢ ↦ fᵢ`. -/
def toLieAlgebraEquiv [FiniteDimensional K H] (hdet : A.det ≠ 0) :
    Matrix.ToLieAlgebra K A ≃ₗ⁅K⁆ P.KacMoodyAlgebra :=
  toLieAlgebraEquivOfSpan hA hS (span_coroot_eq_top_of_det_ne_zero hdet)

@[simp] lemma toLieAlgebraEquiv_apply [FiniteDimensional K H] (hdet : A.det ≠ 0)
    (x : Matrix.ToLieAlgebra K A) :
    toLieAlgebraEquiv P hA hS hdet x = ofToLieAlgebra P hA x :=
  rfl

end KacMoodyAlgebra

end Matrix.Realization

end
