/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.Triangular
import Mathlib.Algebra.Lie.UniversalEnveloping
import Mathlib.LinearAlgebra.TensorAlgebra.Basic

/-!
# Verma modules over `𝔤(A)`

For `Λ ∈ 𝔥*`, the Verma module over the Kac–Moody algebra `𝔤 = 𝔤(A)` is
`M(Λ) = U(𝔤) ⧸ J(Λ)`, where `J(Λ)` is the left ideal of `U(𝔤)` generated by `𝔫₊` and by the
elements `h - Λ(h)`, `h ∈ 𝔥` ([Kac] §9.2). Equivalently `M(Λ) = U(𝔤) ⊗_{U(𝔟)} K_Λ`.

## Main definitions

* `UniversalEnvelopingAlgebra.lieRingModuleOfModule`: a `U(L)`-module is an `L`-module.
* `Matrix.Realization.KacMoodyAlgebra.vermaIdeal`: the left ideal `J(Λ)`.
* `Matrix.Realization.KacMoodyAlgebra.VermaModule`: the Verma module `M(Λ)`.
* `Matrix.Realization.KacMoodyAlgebra.VermaModule.hwv`: the highest-weight vector `v_Λ`.
* `Matrix.Realization.KacMoodyAlgebra.VermaModule.lift`: the morphism `M(Λ) → V`, `v_Λ ↦ v`, for
  a vector `v` of weight `Λ` killed by `𝔫₊`.

## Main results

* `UniversalEnvelopingAlgebra.induction`: induction principle for `U(L)`.
* `Matrix.Realization.KacMoodyAlgebra.VermaModule.existsUnique_lieModuleHom`: the universal
  property of `M(Λ)` ([Kac] §9.2).
* `Matrix.Realization.KacMoodyAlgebra.VermaModule.eq_top_of_hwv_mem`: `M(Λ)` is generated by
  `v_Λ`.

## References

* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §9.2.
-/

open Module LieModule

noncomputable section

/-! ### Modules over the universal enveloping algebra -/

namespace UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

variable {R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]

theorem mkAlgHom_surjective : Function.Surjective (mkAlgHom R L) := by
  intro u
  induction u using Quotient.inductionOn' with
  | h a => exact ⟨a, rfl⟩

/-- Induction principle for the universal enveloping algebra: a property holding for scalars and
for the image of `ι`, and stable under addition and multiplication, holds everywhere. -/
@[elab_as_elim]
theorem induction {C : UniversalEnvelopingAlgebra R L → Prop}
    (algebraMap : ∀ r, C (algebraMap R (UniversalEnvelopingAlgebra R L) r))
    (ι : ∀ x, C (ι R x)) (mul : ∀ a b, C a → C b → C (a * b))
    (add : ∀ a b, C a → C b → C (a + b)) (u : UniversalEnvelopingAlgebra R L) : C u := by
  obtain ⟨t, rfl⟩ := mkAlgHom_surjective u
  induction t using TensorAlgebra.induction with
  | algebraMap r => rw [AlgHom.commutes]; exact algebraMap r
  | ι x => exact ι x
  | mul a b ha hb => rw [map_mul]; exact mul _ _ ha hb
  | add a b ha hb => rw [map_add]; exact add _ _ ha hb

variable (R L) (M : Type*) [AddCommGroup M] [Module (UniversalEnvelopingAlgebra R L) M]

/-- A module over `U(L)` is a Lie module over `L`, with `⁅x, m⁆ = ι x • m`.

This is not an instance, since `M` might carry an unrelated `L`-module structure. -/
abbrev lieRingModuleOfModule : LieRingModule L M where
  bracket x m := ι R x • m
  add_lie x y m := by simp only [map_add, add_smul]
  lie_add x m n := smul_add _ _ _
  leibniz_lie x y m := by
    simp only [LieHom.map_lie, LieRing.of_associative_ring_bracket, sub_smul, mul_smul]
    abel

/-- A module over `U(L)` is a Lie module over `L`. See `lieRingModuleOfModule`. -/
theorem lieModuleOfModule [Module R M] [IsScalarTower R (UniversalEnvelopingAlgebra R L) M] :
    letI := lieRingModuleOfModule R L M
    LieModule R L M :=
  letI := lieRingModuleOfModule R L M
  { smul_lie t x m := by
      change ι R (t • x) • m = t • (ι R x • m)
      rw [map_smul, smul_assoc]
    lie_smul t x m := by
      change ι R x • t • m = t • (ι R x • m)
      rw [smul_algebra_smul_comm] }

variable {R L M}

/-- A submodule of a `U(L)`-module that is stable under the action of `ι L` is stable under
`U(L)`. -/
theorem smul_mem_of_forall_ι_smul_mem [Module R M]
    [IsScalarTower R (UniversalEnvelopingAlgebra R L) M] (N : Submodule R M)
    (hN : ∀ x : L, ∀ m ∈ N, ι R x • m ∈ N) (u : UniversalEnvelopingAlgebra R L) {m : M}
    (hm : m ∈ N) : u • m ∈ N := by
  induction u using induction generalizing m with
  | algebraMap r => rw [algebraMap_smul]; exact N.smul_mem r hm
  | ι x => exact hN x m hm
  | mul a b ha hb => rw [mul_smul]; exact ha (hb hm)
  | add a b ha hb => rw [add_smul]; exact N.add_mem (ha hm) (hb hm)

end UniversalEnvelopingAlgebra

/-! ### Verma modules -/

namespace Matrix.Realization.KacMoodyAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

open UniversalEnvelopingAlgebra hiding ι

variable {ι K H : Type*} [Fintype ι] [DecidableEq ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H)

local notation "𝓤" => UniversalEnvelopingAlgebra K (KacMoodyAlgebra P)
local notation "ιᵤ" => UniversalEnvelopingAlgebra.ι K

/-- A Lie submodule of a `𝔤(A)`-module containing a submodule stable under the generators
`eᵢ`, `fᵢ`, `h` is stable under `𝔤(A)`. -/
lemma lie_mem_of_generators {M : Type*} [AddCommGroup M] [Module K M]
    [LieRingModule P.KacMoodyAlgebra M] [LieModule K P.KacMoodyAlgebra M] (N : Submodule K M)
    (he : ∀ i, ∀ m ∈ N, ⁅e P i, m⁆ ∈ N) (hf : ∀ i, ∀ m ∈ N, ⁅f P i, m⁆ ∈ N)
    (hh : ∀ a, ∀ m ∈ N, ⁅h P a, m⁆ ∈ N) (x : P.KacMoodyAlgebra) : ∀ m ∈ N, ⁅x, m⁆ ∈ N := by
  obtain ⟨x, rfl⟩ := π_surjective P x
  induction x using AuxLieAlgebra.induction_on with
  | he i => exact he i
  | hf i => exact hf i
  | hh a => exact hh a
  | zero => simp
  | add y z hy hz => intro m hm; rw [map_add, add_lie]; exact N.add_mem (hy m hm) (hz m hm)
  | smul c y hy => intro m hm; rw [map_smul, smul_lie]; exact N.smul_mem c (hy m hm)
  | lie y z hy hz =>
    intro m hm
    rw [LieHom.map_lie, lie_lie]
    exact N.sub_mem (hy _ (hz m hm)) (hz _ (hy m hm))

variable (Λ : Dual K H)

/-- The generators of the left ideal `J(Λ)`: `ι x` for `x ∈ 𝔫₊`, and `ι h - Λ(h)` for
`h ∈ 𝔥`. -/
def vermaGens : Set 𝓤 :=
  ιᵤ '' (nPos P : Set P.KacMoodyAlgebra) ∪
    Set.range fun a ↦ ιᵤ (h P a) - algebraMap K 𝓤 (Λ a)

/-- The left ideal `J(Λ)` of `U(𝔤)` generated by `𝔫₊` and by the `h - Λ(h)`, `h ∈ 𝔥`. -/
def vermaIdeal : Submodule 𝓤 𝓤 := Submodule.span 𝓤 (vermaGens P Λ)

/-- The Verma module `M(Λ) = U(𝔤) ⧸ J(Λ)` over `𝔤(A)` ([Kac] §9.2). -/
def VermaModule : Type _ := 𝓤 ⧸ vermaIdeal P Λ

namespace VermaModule

instance : AddCommGroup (VermaModule P Λ) := inferInstanceAs (AddCommGroup (𝓤 ⧸ _))

instance : Module 𝓤 (VermaModule P Λ) := inferInstanceAs (Module 𝓤 (𝓤 ⧸ _))

instance : Module K (VermaModule P Λ) := inferInstanceAs (Module K (𝓤 ⧸ vermaIdeal P Λ))

instance : IsScalarTower K 𝓤 (VermaModule P Λ) :=
  inferInstanceAs (IsScalarTower K 𝓤 (𝓤 ⧸ vermaIdeal P Λ))

instance : LieRingModule P.KacMoodyAlgebra (VermaModule P Λ) :=
  lieRingModuleOfModule K P.KacMoodyAlgebra (VermaModule P Λ)

instance : LieModule K P.KacMoodyAlgebra (VermaModule P Λ) :=
  lieModuleOfModule K P.KacMoodyAlgebra (VermaModule P Λ)

lemma lie_eq_smul (x : P.KacMoodyAlgebra) (m : VermaModule P Λ) : ⁅x, m⁆ = ιᵤ x • m := rfl

/-- The quotient map `U(𝔤) → M(Λ)`. -/
def mk : 𝓤 →ₗ[𝓤] VermaModule P Λ := (vermaIdeal P Λ).mkQ

lemma mk_surjective : Function.Surjective (mk P Λ) := (vermaIdeal P Λ).mkQ_surjective

lemma mk_eq_zero_iff {u : 𝓤} : mk P Λ u = 0 ↔ u ∈ vermaIdeal P Λ :=
  Submodule.Quotient.mk_eq_zero _

/-- The highest-weight vector `v_Λ`, the image of `1 ∈ U(𝔤)`. -/
def hwv : VermaModule P Λ := mk P Λ 1

lemma mk_eq_smul (u : 𝓤) : mk P Λ u = u • hwv P Λ := by
  rw [hwv, ← map_smul, smul_eq_mul, mul_one]

lemma mk_mem_vermaIdeal_of_mem_vermaGens {u : 𝓤} (hu : u ∈ vermaGens P Λ) :
    u ∈ vermaIdeal P Λ :=
  Submodule.subset_span hu

/-- `𝔫₊` kills `v_Λ`. -/
lemma lie_hwv_of_mem_nPos {x : P.KacMoodyAlgebra} (hx : x ∈ nPos P) : ⁅x, hwv P Λ⁆ = 0 := by
  rw [lie_eq_smul, ← mk_eq_smul, mk_eq_zero_iff]
  exact Submodule.subset_span (Or.inl ⟨x, hx, rfl⟩)

@[simp] lemma lie_e_hwv (i : ι) : ⁅e P i, hwv P Λ⁆ = 0 :=
  lie_hwv_of_mem_nPos P Λ (e_mem_nPos P i)

/-- `v_Λ` has weight `Λ`. -/
@[simp] lemma lie_h_hwv (a : H) : ⁅h P a, hwv P Λ⁆ = Λ a • hwv P Λ := by
  rw [lie_eq_smul, ← mk_eq_smul, ← sub_eq_zero, ← algebraMap_smul 𝓤 (Λ a), ← mk_eq_smul,
    ← map_sub, mk_eq_zero_iff]
  exact Submodule.subset_span (Or.inr ⟨a, rfl⟩)

/-- Every Lie submodule of `M(Λ)` is stable under `U(𝔤)`. -/
lemma smul_mem (N : LieSubmodule K P.KacMoodyAlgebra (VermaModule P Λ)) (u : 𝓤)
    {m : VermaModule P Λ} (hm : m ∈ N) : u • m ∈ N :=
  smul_mem_of_forall_ι_smul_mem N.toSubmodule (fun _ _ hm ↦ N.lie_mem hm) u hm

/-- `M(Λ)` is generated by `v_Λ`: a Lie submodule containing `v_Λ` is everything. -/
theorem eq_top_of_hwv_mem {N : LieSubmodule K P.KacMoodyAlgebra (VermaModule P Λ)}
    (hN : hwv P Λ ∈ N) : N = ⊤ := by
  rw [eq_top_iff]
  rintro m -
  obtain ⟨u, rfl⟩ := mk_surjective P Λ m
  rw [mk_eq_smul]
  exact smul_mem P Λ N u hN

/-! ### The universal property -/

section lift

variable {V : Type*} [AddCommGroup V] [Module K V] [LieRingModule P.KacMoodyAlgebra V]
  [LieModule K P.KacMoodyAlgebra V]

/-- The action of `U(𝔤)` on a `𝔤`-module. -/
abbrev rep (V : Type*) [AddCommGroup V] [Module K V] [LieRingModule P.KacMoodyAlgebra V]
    [LieModule K P.KacMoodyAlgebra V] : 𝓤 →ₐ[K] Module.End K V :=
  UniversalEnvelopingAlgebra.lift K (toEnd K P.KacMoodyAlgebra V)

lemma rep_ι (x : P.KacMoodyAlgebra) (v : V) : rep P V (ιᵤ x) v = ⁅x, v⁆ := by
  rw [lift_ι_apply, toEnd_apply_apply]

/-- A morphism of `𝔤`-modules out of `M(Λ)` commutes with the action of `U(𝔤)`. -/
lemma map_smul_eq_rep (φ : VermaModule P Λ →ₗ⁅K,P.KacMoodyAlgebra⁆ V) (u : 𝓤)
    (m : VermaModule P Λ) : φ (u • m) = rep P V u (φ m) := by
  induction u using UniversalEnvelopingAlgebra.induction generalizing m with
  | algebraMap r => rw [algebraMap_smul, map_smul, AlgHom.commutes, Module.algebraMap_end_apply]
  | ι x => rw [rep_ι, ← lie_eq_smul, LieModuleHom.map_lie]
  | mul a b ha hb => rw [mul_smul, ha, hb, map_mul, Module.End.mul_apply]
  | add a b ha hb => rw [add_smul, map_add, ha, hb, map_add, LinearMap.add_apply]

/-- Two morphisms of `𝔤`-modules out of `M(Λ)` agreeing on `v_Λ` are equal. -/
theorem hom_ext {φ ψ : VermaModule P Λ →ₗ⁅K,P.KacMoodyAlgebra⁆ V}
    (h : φ (hwv P Λ) = ψ (hwv P Λ)) : φ = ψ := by
  ext m
  obtain ⟨u, rfl⟩ := mk_surjective P Λ m
  rw [mk_eq_smul, map_smul_eq_rep, map_smul_eq_rep, h]

variable {Λ} (v : V) (he : ∀ x ∈ nPos P, ⁅x, v⁆ = 0) (hh : ∀ a, ⁅h P a, v⁆ = Λ a • v)

/-- The linear map `U(𝔤) → V`, `u ↦ u • v`. -/
abbrev evalAt : 𝓤 →ₗ[K] V := LinearMap.applyₗ v ∘ₗ (rep P V).toLinearMap

include he hh in
lemma evalAt_eq_zero {u : 𝓤} (hu : u ∈ vermaIdeal P Λ) : evalAt P v u = 0 := by
  induction hu using Submodule.span_induction with
  | mem u hu =>
    rcases hu with ⟨x, hx, rfl⟩ | ⟨a, rfl⟩
    · simp [he x hx]
    · simp [hh a]
  | zero => simp
  | add u w _ _ hu hw => rw [map_add, hu, hw, add_zero]
  | smul c u _ hu =>
    simp only [LinearMap.coe_comp, Function.comp_apply, LinearMap.applyₗ_apply_apply,
      AlgHom.toLinearMap_apply, smul_eq_mul, map_mul, Module.End.mul_apply] at hu ⊢
    rw [hu, map_zero]

/-- The morphism of `𝔤`-modules `M(Λ) → V` sending `v_Λ` to a vector `v ∈ V` of weight `Λ`
killed by `𝔫₊`. -/
def lift : VermaModule P Λ →ₗ⁅K,P.KacMoodyAlgebra⁆ V where
  toLinearMap := ((vermaIdeal P Λ).restrictScalars K).liftQ (evalAt P v)
      (fun _ hu ↦ evalAt_eq_zero P v he hh hu) ∘ₗ
    (Submodule.Quotient.restrictScalarsEquiv K (vermaIdeal P Λ)).symm.toLinearMap
  map_lie' {x m} := by
    obtain ⟨u, rfl⟩ := mk_surjective P Λ m
    simp only [lie_eq_smul, ← map_smul]
    change evalAt P v (ιᵤ x * u) = ⁅x, evalAt P v u⁆
    simp

lemma lift_mk (u : 𝓤) : lift P v he hh (mk P Λ u) = rep P V u v := rfl

@[simp] lemma lift_hwv : lift P v he hh (hwv P Λ) = v := by
  rw [hwv, lift_mk, map_one, Module.End.one_apply]

variable (Λ) in
/-- **Universal property of the Verma module** ([Kac] §9.2): for a `𝔤(A)`-module `V`
and `v ∈ V` of weight `Λ` killed by `𝔫₊`, there is a unique morphism of `𝔤(A)`-modules
`M(Λ) → V` sending `v_Λ` to `v`. -/
theorem existsUnique_lieModuleHom (v : V) (he : ∀ x ∈ nPos P, ⁅x, v⁆ = 0)
    (hh : ∀ a, ⁅h P a, v⁆ = Λ a • v) :
    ∃! φ : VermaModule P Λ →ₗ⁅K,P.KacMoodyAlgebra⁆ V, φ (hwv P Λ) = v :=
  ⟨lift P v he hh, lift_hwv P v he hh, fun _ hφ ↦ hom_ext P Λ (by rw [hφ, lift_hwv])⟩

end lift

end VermaModule

end Matrix.Realization.KacMoodyAlgebra

end
