/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.LinearAlgebra.Matrix.Cartan.WeylGroupExchange
import LieLean.RepresentationTheory.Crystal.Realization
import LieLean.RepresentationTheory.Crystal.SimilarityComparison

/-!
# Extremal elements of highest weight crystals

Let `B` be a seminormal crystal generated by the `f̃ᵢ` from an element `b₀` of weight `Λ`. If the
simple roots are linearly independent and the images of the simple roots under products of
simple reflections are positive or negative (`CartanDatum.RootSign`, e.g. for the Cartan datum
of a realization, `Matrix.Realization.rootSign_cartanDatum`), then for every weight `μ` in the
orbit of `Λ` under the simple reflections:

* `B` has exactly one element `u_μ` of weight `μ` (`Crystal.existsUnique_wt_of_orbit`);
* `εᵢ(u_μ) = 0` if `⟨μ, αᵢ^∨⟩ ≥ 0` (`Crystal.ε_eq_zero_of_orbit`).

These are the properties of the extremal vectors used in [Kas96] (4.7), (4.8). For `B = B(λ)`
they are usually derived from the representation theory of `U_q(𝔤)` (`W`-invariance of
characters); here they follow from Kashiwara's reflections `Sᵢ` on seminormal crystals and the
sign property of `W` acting on simple roots (our argument).

## References

* [Kas96] M. Kashiwara, *Similarity of crystal bases*, Contemp. Math. 194 (1996), 177–186, §4.
* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, Lemma 3.11 (a).
-/

namespace CartanDatum

variable {ι X : Type*} [AddCommGroup X] (D : CartanDatum ι X)

/-- The product `r_{j₁} ⋯ r_{jₖ}` of simple reflections, applied to `μ`. -/
def reflWord (js : List ι) (μ : X) : X := js.foldr (fun j ν ↦ D.reflection j ν) μ

@[simp] lemma reflWord_nil (μ : X) : D.reflWord [] μ = μ := rfl

lemma reflWord_cons (j : ι) (js : List ι) (μ : X) :
    D.reflWord (j :: js) μ = D.reflection j (D.reflWord js μ) := rfl

lemma reflWord_append (js ks : List ι) (μ : X) :
    D.reflWord (js ++ ks) μ = D.reflWord js (D.reflWord ks μ) := by
  simp [reflWord, List.foldr_append]

lemma reflWord_add (js : List ι) (μ ν : X) :
    D.reflWord js (μ + ν) = D.reflWord js μ + D.reflWord js ν := by
  induction js with
  | nil => rfl
  | cons j js ih => rw [reflWord_cons, reflWord_cons, reflWord_cons, ih, map_add]

lemma reflWord_neg (js : List ι) (μ : X) : D.reflWord js (-μ) = -D.reflWord js μ := by
  induction js with
  | nil => rfl
  | cons j js ih => rw [reflWord_cons, reflWord_cons, ih, map_neg]

lemma reflWord_sub (js : List ι) (μ ν : X) :
    D.reflWord js (μ - ν) = D.reflWord js μ - D.reflWord js ν := by
  rw [sub_eq_add_neg, reflWord_add, reflWord_neg, ← sub_eq_add_neg]

@[simp] lemma reflWord_zero (js : List ι) : D.reflWord js 0 = 0 := by
  induction js with
  | nil => rfl
  | cons j js ih => rw [reflWord_cons, ih, map_zero]

lemma rootSum_nsmul (c : ℕ) (ν : ι →₀ ℕ) : D.rootSum (c • ν) = c • D.rootSum ν := by
  induction c with
  | zero => simp
  | succ c ih => rw [succ_nsmul, D.rootSum_add, ih, succ_nsmul]

lemma rootSum_wordCount (w : List ι) :
    D.rootSum (w.map fun j ↦ Finsupp.single j 1).sum = (w.map D.root).sum := by
  induction w with
  | nil => simp
  | cons j w ih =>
    rw [List.map_cons, List.sum_cons, D.rootSum_add, D.rootSum_single, one_smul, ih,
      List.map_cons, List.sum_cons]

lemma reflWord_zsmul (js : List ι) (n : ℤ) (μ : X) :
    D.reflWord js (n • μ) = n • D.reflWord js μ := by
  induction js with
  | nil => rfl
  | cons j js ih => rw [reflWord_cons, reflWord_cons, ih, map_zsmul]

lemma reflWord_reverse_reflWord (js : List ι) (μ : X) :
    D.reflWord js.reverse (D.reflWord js μ) = μ := by
  induction js generalizing μ with
  | nil => rfl
  | cons j js ih =>
    rw [List.reverse_cons, reflWord_append, reflWord_cons, reflWord_cons, reflWord_nil,
      reflection_reflection, ih]

lemma Orbit.exists_reflWord {Λ μ : X} (h : D.Orbit Λ μ) : ∃ js, μ = D.reflWord js Λ := by
  induction h with
  | self => exact ⟨[], rfl⟩
  | reflection i _ ih =>
    obtain ⟨js, rfl⟩ := ih
    exact ⟨i :: js, rfl⟩

lemma orbit_reflWord (Λ : X) (js : List ι) : D.Orbit Λ (D.reflWord js Λ) := by
  induction js with
  | nil => exact Orbit.self
  | cons j js ih => exact ih.reflection j

/-- The images of the simple roots under products of simple reflections are positive or negative
combinations of simple roots ([Kac] Lemma 3.11 (a) for the Weyl group of a realization). -/
def RootSign : Prop :=
  ∀ (js : List ι) (i : ι), ∃ ν : ι →₀ ℕ,
    D.reflWord js (D.root i) = D.rootSum ν ∨ D.reflWord js (D.root i) = -D.rootSum ν

end CartanDatum

namespace Crystal

variable {ι X : Type*} [AddCommGroup X] {D : CartanDatum ι X} {B : Type*} {C : Crystal D B}
  {b₀ : B}

lemma exists_wt_eq_of_fWord (hgen : ∀ b, ∃ w, C.fWord w b₀ = some b) (b : B) :
    ∃ ν : ι →₀ ℕ, C.wt b = C.wt b₀ - D.rootSum ν := by
  classical
  obtain ⟨w, hw⟩ := hgen b
  refine ⟨(w.map fun j ↦ Finsupp.single j 1).sum, ?_⟩
  rw [wt_fWord w hw, D.rootSum_wordCount]

lemma nonempty_wt_reflWord (hC : C.IsSeminormal) {μ : X} (h : ∃ b, C.wt b = μ) (js : List ι) :
    ∃ b, C.wt b = D.reflWord js μ := by
  induction js with
  | nil => exact h
  | cons j js ih =>
    obtain ⟨b, hb⟩ := ih
    exact ⟨C.reflection j b, by rw [hC.wt_reflection, hb]; rfl⟩

lemma existsUnique_wt_reflection (hC : C.IsSeminormal) {μ : X} (h : ∃! b, C.wt b = μ) (j : ι) :
    ∃! b, C.wt b = D.reflection j μ := by
  obtain ⟨b, hb, huniq⟩ := h
  let e := hC.weightEquiv j μ
  refine ⟨(e ⟨b, hb⟩).1, (e ⟨b, hb⟩).2, fun b' hb' ↦ ?_⟩
  have h1 : (e.symm ⟨b', hb'⟩).1 = b := huniq _ (e.symm ⟨b', hb'⟩).2
  have h2 : e.symm ⟨b', hb'⟩ = ⟨b, hb⟩ := Subtype.ext h1
  rw [← h2, e.apply_symm_apply]

variable (hC : C.IsSeminormal) (hgen : ∀ b, ∃ w, C.fWord w b₀ = some b)
  (hD : LinearIndependent ℤ D.root)
include hC hgen hD

/-- In a seminormal crystal generated by `b₀`, every weight of the orbit of `wt b₀` under the
simple reflections is the weight of exactly one element. -/
theorem existsUnique_wt_of_orbit {μ : X} (h : D.Orbit (C.wt b₀) μ) : ∃! b, C.wt b = μ := by
  induction h with
  | self =>
    refine ⟨b₀, rfl, fun b hb ↦ ?_⟩
    obtain ⟨w, hw⟩ := hgen b
    have h1 := wt_fWord w hw
    rw [hb, eq_comm, sub_eq_self] at h1
    have h2 : w = [] := by
      classical
      have key := D.rootSum_wordCount w
      rw [h1, ← D.rootSum_zero] at key
      have h3 := D.rootSum_injective hD key
      cases w with
      | nil => rfl
      | cons j w =>
        exfalso
        have := congrArg (· j) h3
        simp at this
    subst h2
    exact (Option.some_injective _ hw).symm
  | reflection j _ ih => exact existsUnique_wt_reflection hC ih j

/-- In a seminormal crystal generated by `b₀`, an element `b` whose weight lies in the orbit of
`wt b₀` under the simple reflections, with `⟨wt b, αᵢ^∨⟩ ≥ 0`, has `εᵢ(b) = 0` ([Kas96] (4.7)),
provided `W` maps simple roots to positive or negative roots. -/
theorem ε_eq_zero_of_orbit (hsign : D.RootSign) {b : B} {i : ι} (h : D.Orbit (C.wt b₀) (C.wt b))
    (ha : 0 ≤ D.coroot i (C.wt b)) : C.ε i b = 0 := by
  classical
  set Λ := C.wt b₀
  set μ := C.wt b
  -- weights of `C` are in `Λ - Q₊`
  have hwts : ∀ ν : X, (∃ b', C.wt b' = ν) → ∃ κ : ι →₀ ℕ, ν = Λ - D.rootSum κ := by
    rintro ν ⟨b', rfl⟩
    exact exists_wt_eq_of_fWord hgen b'
  -- a positive multiple of a nonzero element of `Q₊` cannot be added to `Λ`
  have hpos : ∀ (ν : ι →₀ ℕ) (c : ℕ), 0 < c → (∃ b', C.wt b' = Λ + c • D.rootSum ν) → ν = 0 := by
    intro ν c hc hb'
    obtain ⟨κ, hκ⟩ := hwts _ hb'
    rw [← sub_eq_zero] at hκ
    have h1 : D.rootSum (c • ν + κ) = D.rootSum 0 := by
      rw [D.rootSum_add, D.rootSum_zero, D.rootSum_nsmul, ← hκ]
      abel
    have h2 := D.rootSum_injective hD h1
    ext j
    have h3 := congrArg (· j) h2
    simp only [Finsupp.add_apply, Finsupp.smul_apply, smul_eq_mul, Finsupp.coe_zero,
      Pi.zero_apply, Nat.add_eq_zero_iff, mul_eq_zero] at h3
    rcases h3.1 with h4 | h4
    · omega
    · simpa using h4
  obtain ⟨js, hjs⟩ := h.exists_reflWord
  set ws := js.reverse
  have hws : D.reflWord ws μ = Λ := by rw [hjs, D.reflWord_reverse_reflWord]
  have hinj : ∀ x, D.reflWord ws x = 0 → x = 0 := fun x hx ↦ by
    have := D.reflWord_reverse_reflWord ws x
    rw [hx, D.reflWord_zero] at this
    exact this.symm
  have hroot : D.root i ≠ 0 := fun h0 ↦ by
    have := D.coroot_root_self i
    rw [h0, map_zero] at this
    exact absurd this (by norm_num)
  -- if `εᵢ(b) ≠ 0` then `μ + αᵢ` is a weight
  have hnext : C.ε i b ≠ 0 → ∃ b', C.wt b' = μ + D.root i := by
    intro hε
    obtain ⟨n, hn⟩ := hC.exists_ε_eq i b
    have hs : (C.e i b).isSome := by
      rw [← C.eIter_one, hC.isSome_eIter_iff, hn]
      rw [hn] at hε
      exact_mod_cast Nat.one_le_iff_ne_zero.2 fun h0 ↦ hε (by rw [h0, Nat.cast_zero])
    obtain ⟨b', hb'⟩ := Option.isSome_iff_exists.1 hs
    exact ⟨b', C.wt_e i b b' hb'⟩
  -- the sign of `w⁻¹ αᵢ`
  obtain ⟨ν, hν | hν⟩ := hsign ws i
  · -- `w⁻¹ αᵢ > 0`: then `μ + αᵢ` is not a weight
    by_contra hε
    have h1 := nonempty_wt_reflWord hC (hnext hε) ws
    rw [D.reflWord_add, hws, hν] at h1
    have h2 := hpos ν 1 one_pos (by simpa using h1)
    subst h2
    rw [D.rootSum_zero] at hν
    exact hroot (hinj _ hν)
  · -- `w⁻¹ αᵢ < 0`
    have hν0 : ν ≠ 0 := fun h0 ↦ by
      subst h0
      rw [D.rootSum_zero, neg_zero] at hν
      exact hroot (hinj _ hν)
    obtain ⟨a, ha'⟩ : ∃ a : ℕ, D.coroot i μ = a := ⟨(D.coroot i μ).toNat, by omega⟩
    rcases Nat.eq_zero_or_pos a with h0 | hpa
    · -- `⟨μ, αᵢ^∨⟩ = 0`: use `rᵢ(μ + αᵢ) = μ - αᵢ`
      by_contra hε
      have h1 := nonempty_wt_reflWord hC (hnext hε) (ws ++ [i])
      have hr : D.reflection i (μ + D.root i) = μ - D.root i := by
        rw [D.reflection_apply, map_add, ha', h0, D.coroot_root_self]
        simp only [Nat.cast_zero, zero_add]
        rw [two_smul]
        abel
      rw [D.reflWord_append, D.reflWord_cons, D.reflWord_nil, hr, D.reflWord_sub, hws, hν,
        sub_neg_eq_add] at h1
      exact hν0 (hpos ν 1 one_pos (by simpa using h1))
    · -- `⟨μ, αᵢ^∨⟩ > 0`: use the weight `rᵢ μ = μ - a αᵢ`
      exfalso
      have h1 := nonempty_wt_reflWord hC ⟨b, rfl⟩ (ws ++ [i])
      rw [D.reflWord_append, D.reflWord_cons, D.reflWord_nil, D.reflection_apply, ha',
        D.reflWord_sub, hws, D.reflWord_zsmul, hν, zsmul_neg, sub_neg_eq_add,
        natCast_zsmul] at h1
      exact hν0 (hpos ν a hpa h1)

end Crystal

/-! ### Realizations -/

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [Field K] [CharZero K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H) (hA : A.IsGeneralizedCartan)

lemma coe_rootSum_cartanDatum (ν : ι →₀ ℕ) :
    (((P.cartanDatum hA).rootSum ν : P.integralWeights) : Module.Dual K H) =
      P.rootOf fun i ↦ (ν i : ℤ) := by
  classical
  induction ν using Finsupp.induction_linear with
  | zero =>
    rw [CartanDatum.rootSum_zero]
    exact (map_zero P.rootOf).symm
  | add ν ν' h h' =>
    rw [CartanDatum.rootSum_add, AddSubgroup.coe_add, h, h', ← map_add]
    rfl
  | single i n =>
    rw [CartanDatum.rootSum_single, AddSubgroup.coe_nsmul, coe_root_cartanDatum, rootOf_apply,
      Finset.sum_eq_single i (fun j _ hj ↦ by simp [hj.symm])
        (by simp)]
    simp [← Nat.cast_smul_eq_nsmul K]

/-- The simple roots of the Cartan datum of a realization are linearly independent over `ℤ`. -/
theorem linearIndependent_root_cartanDatum : LinearIndependent ℤ (P.cartanDatum hA).root := by
  rw [Fintype.linearIndependent_iff]
  intro g hg
  have h1 : P.rootOf g = P.rootOf 0 := by
    have := congrArg Subtype.val hg
    rw [AddSubgroup.val_finsetSum] at this
    rw [rootOf_apply, map_zero]
    simpa [coe_root_cartanDatum, ← Int.cast_smul_eq_zsmul K] using this
  exact congrFun (P.rootOf_injective h1)

lemma coe_reflWord_cartanDatum (js : List ι) (μ : P.integralWeights) :
    ∃ w ∈ P.weylGroup hA,
      (((P.cartanDatum hA).reflWord js μ : P.integralWeights) : Module.Dual K H) =
      w μ := by
  induction js with
  | nil => exact ⟨1, Subgroup.one_mem _, rfl⟩
  | cons j js ih =>
    obtain ⟨w, hw, hwμ⟩ := ih
    refine ⟨P.reflection hA j * w, Subgroup.mul_mem _ (P.reflection_mem_weylGroup hA j) hw, ?_⟩
    rw [CartanDatum.reflWord_cons, coe_reflection_cartanDatum, hwμ]
    rfl

/-- The Cartan datum of a realization has the sign property: `W` maps each simple root to a
positive or a negative root ([Kac] Lemma 3.11 (a),
`Matrix.Realization.apply_root_nonneg_or_nonpos`). -/
theorem rootSign_cartanDatum : (P.cartanDatum hA).RootSign := by
  classical
  intro js i
  obtain ⟨w, hw, hwμ⟩ := P.coe_reflWord_cartanDatum hA js ((P.cartanDatum hA).root i)
  rw [coe_root_cartanDatum] at hwμ
  rcases P.apply_root_nonneg_or_nonpos hA hw i with ⟨k, hk, hwk⟩ | ⟨k, hk, hwk⟩
  · refine ⟨Finsupp.equivFunOnFinite.symm fun j ↦ (k j).toNat, Or.inl (Subtype.ext ?_)⟩
    rw [hwμ, hwk, coe_rootSum_cartanDatum]
    congr 1
    funext j
    simp [Int.toNat_of_nonneg (hk j)]
  · refine ⟨Finsupp.equivFunOnFinite.symm fun j ↦ (k j).toNat, Or.inr (Subtype.ext ?_)⟩
    rw [hwμ, hwk, AddSubgroup.coe_neg, coe_rootSum_cartanDatum]
    congr 2
    funext j
    simp [Int.toNat_of_nonneg (hk j)]

end Matrix.Realization
