/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.RepresentationTheory.Crystal.TensorPower

/-!
# Kashiwara's comparison of highest weight crystals by similarity

Kashiwara ([Kas96] §4) identifies the crystal `B(λ)` of the irreducible highest weight module with
Littelmann's path crystal by the following argument. Both crystals `B` are seminormal, generated
by the `f̃ᵢ` from an element `b₀` of weight `λ`, and have, for every `m > 0`, an injective
`m`-similarity `T_m : B → B^{⊗m}` with `T_m(b₀) = b₀ ⊗ ⋯ ⊗ b₀` (for `B(λ)`: the similarity
`B(λ) → B(mλ)` of [Kas96] Thm. 3.1 followed by `B(mλ) ↪ B(λ)^{⊗m}`). For a word `w` and `m` with
enough divisors, `T_m(f̃_w b₀) = f̃_{wᵐ}(b₀ ⊗ ⋯ ⊗ b₀)` is a tensor product of extremal elements
`u_{w₁λ} ⊗ ⋯ ⊗ u_{wₘλ}` ([Kas96] (4.7), (4.8)), and the weights `wⱼλ` are computed in the same way
in both crystals. So `f̃_w b₀ = f̃_{w'} b₀` holds in one crystal if and only if it holds in the
other ([Kas96] (4.5), (4.6)), and the crystals are isomorphic.

We formalize this for two abstract crystals with these data (`Crystal.SimilarityData`). The
extremal elements are the elements `u_μ` of the weights `μ` in the orbit of `λ` under the simple
reflections, which are assumed to be the only elements of their weights and to satisfy
`εᵢ(u_μ) = 0` when `⟨μ, αᵢ^∨⟩ ≥ 0` ([Kas96] (4.7)).

## Main definitions

* `CartanDatum.Orbit D Λ`: the orbit of `Λ` under the simple reflections.
* `Crystal.SimilarityData C b₀ Λ`: the data above.

## Main results

* `Crystal.SimilarityData.fWord_eq_fWord_iff`, `Crystal.SimilarityData.fWord_eq_none_iff`: the
  word relations of two crystals with similarity data for the same `Λ` agree ([Kas96] (4.5),
  (4.6)).
* `Crystal.SimilarityData.nonempty_equiv`: two crystals with similarity data for the same `Λ` are
  isomorphic by a unique isomorphism sending `b₀` to `b₀'` ([Kas96] proof of Thm. 4.1).
* `Crystal.equivOfFWord`: seminormal crystals generated by `b₀`, `b₀'` with the same weights and
  word relations are isomorphic.

## Proof

[Kas96] does not say how `m` with "sufficiently many divisors" is chosen. We argue by induction on
the word: if `f̃_{w₀ᴺ}(b₀^{⊗N}) = u_{μ₁} ⊗ ⋯ ⊗ u_{μ_N}` in both crystals, then
`f̃ᵢᴺ` moves each factor `u_{μⱼ}` to `f̃ᵢ^{cⱼ} u_{μⱼ}` with the same `cⱼ` in both crystals
(`Crystal.IsColourRel.fIter_tensorPow`); refining by `T_K` (`Crystal.Similarity.powMap`) with
`K` divisible by the lengths `aⱼ = ⟨μⱼ, αᵢ^∨⟩` of the `i`-strings gives
`T_K(f̃ᵢ^{cⱼ} u_{μⱼ}) = u_{rᵢμⱼ}^{⊗ Kcⱼ/aⱼ} ⊗ u_{μⱼ}^{⊗ K - Kcⱼ/aⱼ}` (`Crystal.fIter_replicate`),
again a tensor product of extremal elements.

## References

* [Kas96] M. Kashiwara, *Similarity of crystal bases*, Contemp. Math. 194 (1996), 177–186, §4.
-/

universe u v

namespace CartanDatum

variable {ι X : Type*} [AddCommGroup X] (D : CartanDatum ι X)

/-- The orbit of `Λ` under the simple reflections `rᵢ`. -/
inductive Orbit (Λ : X) : X → Prop
  | self : Orbit Λ Λ
  | reflection {μ : X} (i : ι) : Orbit Λ μ → Orbit Λ (D.reflection i μ)

end CartanDatum

namespace Crystal

variable {ι X : Type*} [AddCommGroup X] {D : CartanDatum ι X} {B : Type u} {B' : Type v}

/-! ### Isomorphisms from word relations -/

section Words

variable {C : Crystal D B} {C' : Crystal D B'}

lemma wt_fWord {b₀ b : B} : (w : List ι) → C.fWord w b₀ = some b →
    C.wt b = C.wt b₀ - (w.map D.root).sum
  | [], h => by cases h; simp
  | j :: w, h => by
    obtain ⟨c, hc, hf⟩ := Option.bind_eq_some_iff.mp h
    rw [C.wt_f hf, wt_fWord w hc, List.map_cons, List.sum_cons]
    abel

/-- Two seminormal crystals generated by the `f̃ᵢ` from `b₀`, `b₀'` of the same weight, with the
same vanishing words and the same word relations, are isomorphic by `f̃_w b₀ ↦ f̃_w b₀'`. -/
theorem exists_equiv_of_fWord {b₀ : B} {b₀' : B'} (hC : C.IsSeminormal)
    (hC' : C'.IsSeminormal)
    (hgen : ∀ b, ∃ w, C.fWord w b₀ = some b) (hgen' : ∀ b, ∃ w, C'.fWord w b₀' = some b)
    (hwt : C'.wt b₀' = C.wt b₀)
    (hnone : ∀ w, C.fWord w b₀ = none ↔ C'.fWord w b₀' = none)
    (hrel : ∀ w w', C.fWord w b₀ = C.fWord w' b₀ ↔ C'.fWord w b₀' = C'.fWord w' b₀') :
    ∃ Φ : Equiv C C', ∀ w b, C.fWord w b₀ = some b → C'.fWord w b₀' = some (Φ b) := by
  classical
  choose wd hwd using hgen
  choose wd' hwd' using hgen'
  have hs : ∀ b, (C'.fWord (wd b) b₀').isSome := fun b ↦ by
    rw [Option.isSome_iff_ne_none, Ne, ← hnone, hwd]; exact Option.some_ne_none _
  have hs' : ∀ b', (C.fWord (wd' b') b₀).isSome := fun b' ↦ by
    rw [Option.isSome_iff_ne_none, Ne, hnone, hwd']; exact Option.some_ne_none _
  let Φ : B → B' := fun b ↦ (C'.fWord (wd b) b₀').get (hs b)
  let Ψ : B' → B := fun b' ↦ (C.fWord (wd' b') b₀).get (hs' b')
  have hΦ : ∀ w b, C.fWord w b₀ = some b → C'.fWord w b₀' = some (Φ b) := fun w b h ↦ by
    rw [Option.some_get, ← (hrel w (wd b)).1 (by rw [h, hwd])]
  have hΨ : ∀ w b', C'.fWord w b₀' = some b' → C.fWord w b₀ = some (Ψ b') := fun w b' h ↦ by
    rw [Option.some_get, (hrel w (wd' b')).2 (by rw [h, hwd'])]
  have hΨΦ : ∀ b, Ψ (Φ b) = b := fun b ↦ by
    have := hΨ _ _ (hΦ _ _ (hwd b))
    rw [hwd] at this
    exact (Option.some_injective _ this).symm
  have hΦΨ : ∀ b', Φ (Ψ b') = b' := fun b' ↦ by
    have := hΦ _ _ (hΨ _ _ (hwd' b'))
    rw [hwd'] at this
    exact (Option.some_injective _ this).symm
  have he : ∀ i b, C'.e i (Φ b) = (C.e i b).map Φ := fun i b ↦ by
    cases h : C.e i b with
    | some b'' =>
      have h1 : C.fWord (i :: wd b'') b₀ = some b := by
        rw [fWord_cons, hwd, Option.bind_some, (C.f_eq_some_iff i b'' b).2 h]
      have h2 := hΦ _ _ h1
      rw [fWord_cons, hΦ _ _ (hwd b''), Option.bind_some] at h2
      rw [Option.map_some, C'.e_eq_some_iff, h2]
    | none =>
      rw [Option.map_none, Option.eq_none_iff_forall_ne_some]
      intro c hc
      have h1 : C'.fWord (i :: wd' c) b₀' = C'.fWord (wd b) b₀' := by
        rw [fWord_cons, hwd', Option.bind_some, (C'.f_eq_some_iff i c _).2 hc, hΦ _ _ (hwd b)]
      have h2 := (hrel _ _).2 h1
      rw [fWord_cons, hwd b, hΨ _ _ (hwd' c), Option.bind_some] at h2
      rw [← C.e_eq_some_iff] at h2
      rw [h] at h2
      cases h2
  have heIter : ∀ i n b, C'.eIter i n (Φ b) = (C.eIter i n b).map Φ := fun i n ↦ by
    induction n with
    | zero => intro b; rfl
    | succ n ih =>
      intro b
      rw [eIter_succ, eIter_succ, he]
      cases C.e i b with
      | none => rfl
      | some c => exact ih c
  refine ⟨
    { toFun := Φ
      invFun := Ψ
      left_inv := hΨΦ
      right_inv := hΦΨ
      wt_map := fun b ↦ by
        rw [wt_fWord _ (hΦ _ _ (hwd b)), wt_fWord _ (hwd b), hwt]
      ε_map := fun i b ↦ by
        obtain ⟨n, hn⟩ := hC.exists_ε_eq i b
        obtain ⟨n', hn'⟩ := hC'.exists_ε_eq i (Φ b)
        have h1 : ∀ k : ℕ, ((k : WithBot ℤ) ≤ n ↔ (k : WithBot ℤ) ≤ n') := fun k ↦ by
          rw [← hn, ← hn', ← hC.isSome_eIter_iff, ← hC'.isSome_eIter_iff, heIter,
            Option.isSome_map]
        rw [hn, hn']
        have a1 := (h1 n).1 le_rfl
        have a2 := (h1 n').2 le_rfl
        exact_mod_cast le_antisymm (by exact_mod_cast a2) (by exact_mod_cast a1)
      e_map := he
      f_map := fun i b ↦ by
        cases h : C.f i b with
        | none =>
          have h1 : C.fWord (i :: wd b) b₀ = none := by
            rw [fWord_cons, hwd, Option.bind_some, h]
          have h2 := (hnone _).1 h1
          rw [fWord_cons, hΦ _ _ (hwd b), Option.bind_some] at h2
          rw [Option.map_none]
          exact h2
        | some b₁ =>
          have h1 : C.fWord (i :: wd b) b₀ = some b₁ := by
            rw [fWord_cons, hwd, Option.bind_some, h]
          have h2 := hΦ _ _ h1
          rw [fWord_cons, hΦ _ _ (hwd b), Option.bind_some] at h2
          rw [Option.map_some]
          exact h2 }, hΦ⟩

/-- An isomorphism of crystals is determined by its value on a generating element. -/
theorem Equiv.eq_of_fWord {b₀ : B} (hgen : ∀ b, ∃ w, C.fWord w b₀ = some b) {Φ Φ' : Equiv C C'}
    (h : Φ b₀ = Φ' b₀) (b : B) : Φ b = Φ' b := by
  have key : ∀ (ψ : Equiv C C') (w : List ι), C'.fWord w (ψ b₀) = (C.fWord w b₀).map ψ := by
    intro ψ w
    induction w with
    | nil => rfl
    | cons j w ih =>
      rw [fWord_cons, fWord_cons, ih]
      cases C.fWord w b₀ with
      | none => rfl
      | some c => exact ψ.f_apply j c
  obtain ⟨w, hw⟩ := hgen b
  have h1 := key Φ w
  have h2 := key Φ' w
  rw [hw, Option.map_some] at h1 h2
  rw [h] at h1
  exact Option.some_injective _ (h1.symm.trans h2)

end Words

/-! ### Lifting similarities -/

section Lift

variable {BE BF : Type*} {C : Crystal D B} {E : Crystal D BE} {F : Crystal D BF} {m : ℕ}

/-- **Lifting a similarity** through an injective strict morphism: if `σ : B → E` is an
`m`-similarity, `ψ : F → E` an injective strict morphism, `B` is generated by `b₀` and
`ψ(f₀) = σ(b₀)`, then `σ = ψ ∘ T` for an `m`-similarity `T : B → F` with `T(b₀) = f₀`. -/
theorem Similarity.exists_lift (σ : Similarity C E m) (ψ : StrictHom F E)
    (hψ : Function.Injective ψ) {b₀ : B} {f₀ : BF} (h₀ : ψ f₀ = σ b₀)
    (hgen : ∀ b, ∃ w, C.fWord w b₀ = some b) :
    ∃ T : Similarity C F m, T b₀ = f₀ ∧ ∀ b, ψ (T b) = σ b := by
  have hex : ∀ b, ∃ y, ψ y = σ b := fun b ↦ by
    obtain ⟨w, hw⟩ := hgen b
    have h1 := σ.fWord_stretchWord w b₀
    rw [hw, Option.map_some, ← h₀, ψ.fWord_apply, Option.map_eq_some_iff] at h1
    obtain ⟨y, -, hy⟩ := h1
    exact ⟨y, hy⟩
  choose T hT using hex
  have hmap : ∀ o : Option B, (o.map T).map ψ = o.map σ := fun o ↦ by
    cases o <;> simp [hT]
  refine ⟨
    { toFun := T
      wt_map := fun b ↦ by rw [← ψ.wt_apply, hT, σ.wt_apply]
      ε_map := fun i b ↦ by rw [← ψ.ε_apply, hT, σ.ε_apply]
      e_map := fun i b ↦ by
        apply Option.map_injective hψ
        rw [← ψ.eIter_apply, hT, σ.eIter_apply, hmap]
      f_map := fun i b ↦ by
        apply Option.map_injective hψ
        rw [← ψ.fIter_apply, hT, σ.fIter_apply, hmap] }, hψ ?_, hT⟩
  change ψ (T b₀) = ψ f₀
  rw [hT, h₀]

/-- A similarity out of a crystal generated by a highest weight element `b₀` is injective. -/
theorem Similarity.injective_of_fWord (σ : Similarity C E m) {b₀ : B}
    (hgen : ∀ b, ∃ w, C.fWord w b₀ = some b) (hb₀ : ∀ j, C.e j b₀ = none) :
    Function.Injective σ := by
  have key : ∀ (w : List ι) (b : B), C.fWord w b₀ = some b → ∀ b', σ b = σ b' → b = b' := by
    intro w
    induction w with
    | nil =>
      intro b hb b' hbb'
      cases hb
      obtain ⟨w', hw'⟩ := hgen b'
      cases w' with
      | nil => exact Option.some_injective _ hw'
      | cons j w'' =>
        exfalso
        obtain ⟨c, -, hc⟩ := Option.bind_eq_some_iff.mp hw'
        have h1 := σ.eIter_apply j b'
        rw [(C.f_eq_some_iff j c b').1 hc, Option.map_some, ← hbb', σ.eIter_apply, hb₀] at h1
        cases h1
    | cons j w ih =>
      intro b hb b' hbb'
      obtain ⟨c, hc, hf⟩ := Option.bind_eq_some_iff.mp hb
      have h1 := σ.eIter_apply j b
      rw [(C.f_eq_some_iff j c b).1 hf, Option.map_some, hbb', σ.eIter_apply] at h1
      obtain ⟨c', hc', hcc⟩ := Option.map_eq_some_iff.1 h1
      have h2 := ih c hc c' hcc.symm
      subst h2
      rw [← C.f_eq_some_iff] at hc'
      exact Option.some_injective _ (hf.symm.trans hc')
  intro b b' h
  obtain ⟨w, hw⟩ := hgen b
  exact key w b hw b' h

end Lift

/-! ### Similarity data -/

variable (D) in
/-- Kashiwara's data for the comparison of highest weight crystals ([Kas96] §4) on a crystal `C`
with an element `b₀` of weight `Λ`: `C` is seminormal and generated from `b₀` by the `f̃ᵢ`; for
every `m > 0` there is an injective `m`-similarity `T_m : B → B^{⊗m}` with
`T_m(b₀) = b₀ ⊗ ⋯ ⊗ b₀`; every weight `μ` in the orbit of `Λ` under the simple reflections is the
weight of exactly one element `u_μ`, and `εᵢ(u_μ) = 0` if `⟨μ, αᵢ^∨⟩ ≥ 0`. -/
structure SimilarityData (C : Crystal D B) (b₀ : B) (Λ : X) where
  isSeminormal : C.IsSeminormal
  exists_fWord : ∀ b, ∃ w, C.fWord w b₀ = some b
  wt_b₀ : C.wt b₀ = Λ
  /-- The similarities `T_m : B → B^{⊗m}`. -/
  T : ∀ m : ℕ, 0 < m → Similarity C (C.tensorPow m) m
  T_injective : ∀ m hm, Function.Injective (T m hm)
  T_b₀ : ∀ m hm, T m hm b₀ = TPow.replicate b₀ m
  existsUnique_wt : ∀ μ, D.Orbit Λ μ → ∃! b, C.wt b = μ
  ε_eq_zero : ∀ b i, D.Orbit Λ (C.wt b) → 0 ≤ D.coroot i (C.wt b) → C.ε i b = 0

/-- The length `εᵢ(x) + φᵢ(x)` of the `i`-string through `x`. -/
noncomputable def strLen (C : Crystal D B) (i : ι) (x : B) : ℕ :=
  ((C.ε i x + C.φ i x).unbotD 0).toNat

namespace SimilarityData

variable {C : Crystal D B} {b₀ : B} {Λ : X} (S : C.SimilarityData D b₀ Λ)

open Classical in
/-- The extremal element `u_μ` of weight `μ` (`b₀` if `μ` is not in the orbit of `Λ`). -/
noncomputable def u (μ : X) : B :=
  if h : D.Orbit Λ μ then (S.existsUnique_wt μ h).exists.choose else b₀

lemma wt_u {μ : X} (h : D.Orbit Λ μ) : C.wt (S.u μ) = μ := by
  simp only [u, h, ↓reduceDIte]
  exact (S.existsUnique_wt μ h).exists.choose_spec

lemma eq_u {μ : X} (h : D.Orbit Λ μ) {b : B} (hb : C.wt b = μ) : b = S.u μ :=
  (S.existsUnique_wt μ h).unique hb (S.wt_u h)

lemma u_Λ : S.u Λ = b₀ := (S.eq_u CartanDatum.Orbit.self S.wt_b₀).symm

lemma ε_u {μ : X} (h : D.Orbit Λ μ) (i : ι) (ha : 0 ≤ D.coroot i μ) : C.ε i (S.u μ) = 0 :=
  S.ε_eq_zero _ i (by rw [S.wt_u h]; exact h) (by rw [S.wt_u h]; exact ha)

lemma φ_u {μ : X} (h : D.Orbit Λ μ) (i : ι) (ha : 0 ≤ D.coroot i μ) :
    C.φ i (S.u μ) = ((D.coroot i μ : ℤ) : WithBot ℤ) := by
  rw [C.φ_eq, S.ε_u h i ha, S.wt_u h, zero_add]

/-- `f̃ᵢ^{⟨μ, αᵢ^∨⟩} u_μ = u_{rᵢμ}` if `⟨μ, αᵢ^∨⟩ ≥ 0`. -/
lemma fIter_u {μ : X} (h : D.Orbit Λ μ) (i : ι) (ha : 0 ≤ D.coroot i μ) :
    C.fIter i (D.coroot i μ).toNat (S.u μ) = some (S.u (D.reflection i μ)) := by
  have hs : (C.fIter i (D.coroot i μ).toNat (S.u μ)).isSome := by
    rw [S.isSeminormal.isSome_fIter_iff, S.φ_u h i ha, ← WithBot.coe_natCast,
      WithBot.coe_le_coe, Int.toNat_of_nonneg ha]
  obtain ⟨y, hy⟩ := Option.isSome_iff_exists.1 hs
  rw [hy, S.eq_u (h.reflection i) (b := y)]
  rw [C.wt_fIter hy, S.wt_u h, D.reflection_apply, ← natCast_zsmul, Int.toNat_of_nonneg ha]

lemma fIter_u_reflection {μ : X} (h : D.Orbit Λ μ) (i : ι) (ha : D.coroot i μ < 0) :
    C.fIter i (-D.coroot i μ).toNat (S.u (D.reflection i μ)) = some (S.u μ) := by
  have h' := S.fIter_u (h.reflection i) i (by rw [D.coroot_reflection]; omega)
  rwa [D.coroot_reflection, D.reflection_reflection] at h'

/-- `T_m(u_μ) = u_μ ⊗ ⋯ ⊗ u_μ`. -/
theorem T_u {m : ℕ} (hm : 0 < m) {μ : X} (h : D.Orbit Λ μ) :
    S.T m hm (S.u μ) = TPow.replicate (S.u μ) m := by
  induction h with
  | self => rw [S.u_Λ, S.T_b₀]
  | @reflection μ i h ih =>
    by_cases ha : 0 ≤ D.coroot i μ
    · have h1 := (S.T m hm).fIter_mul i (D.coroot i μ).toNat (S.u μ)
      rw [S.fIter_u h i ha, Option.map_some, ih, mul_comm,
        fIter_replicate i (S.ε_u h i ha) (by rw [S.φ_u h i ha, Int.toNat_of_nonneg ha])
          (S.fIter_u h i ha) m m le_rfl, TPow.replicate₂_self] at h1
      exact (Option.some_injective _ h1).symm
    · push Not at ha
      have hν : 0 ≤ D.coroot i (D.reflection i μ) := by rw [D.coroot_reflection]; omega
      have hν' : (D.coroot i (D.reflection i μ)).toNat = (-D.coroot i μ).toNat := by
        rw [D.coroot_reflection]
      have h1 := (S.T m hm).fIter_mul i (-D.coroot i μ).toNat (S.u (D.reflection i μ))
      rw [S.fIter_u_reflection h i ha, Option.map_some, ih] at h1
      have h2 := fIter_replicate (C := C) (a := (-D.coroot i μ).toNat) i
        (S.ε_u (h.reflection i) i hν)
        (by rw [S.φ_u (h.reflection i) i hν, ← hν', Int.toNat_of_nonneg hν])
        (by rw [← hν', S.fIter_u (h.reflection i) i hν, D.reflection_reflection]) m m le_rfl
      rw [TPow.replicate₂_self, ← mul_comm] at h2
      rw [C.tensorPow m |>.fIter_eq_some_iff] at h1 h2
      exact Option.some_injective _ (h1.symm.trans h2)

/-! ### Two crystals with similarity data -/

variable {C' : Crystal D B'} {b₀' : B'} (S' : C'.SimilarityData D b₀' Λ)

/-- The extremal elements of `C` and `C'` of equal weights. -/
def ExtRel (x : B) (x' : B') : Prop := ∃ μ, D.Orbit Λ μ ∧ x = S.u μ ∧ x' = S'.u μ

/-- Elements of the `i`-strings of extremal elements `u_μ` with `⟨μ, αᵢ^∨⟩ ≥ 0`, at the same
position in `C` and `C'`. -/
def StrRel (i : ι) (x : B) (x' : B') : Prop :=
  ∃ μ, D.Orbit Λ μ ∧ 0 ≤ D.coroot i μ ∧ ∃ c : ℕ, c ≤ (D.coroot i μ).toNat ∧
    C.fIter i c (S.u μ) = some x ∧ C'.fIter i c (S'.u μ) = some x'

lemma ExtRel.strRel {x : B} {x' : B'} (h : ExtRel S S' x x') (i : ι) : StrRel S S' i x x' := by
  obtain ⟨μ, hμ, rfl, rfl⟩ := h
  by_cases ha : 0 ≤ D.coroot i μ
  · exact ⟨μ, hμ, ha, 0, Nat.zero_le _, rfl, rfl⟩
  · push Not at ha
    refine ⟨D.reflection i μ, hμ.reflection i, by rw [D.coroot_reflection]; omega,
      (-D.coroot i μ).toNat, by rw [D.coroot_reflection], S.fIter_u_reflection hμ i ha,
      S'.fIter_u_reflection hμ i ha⟩

lemma ExtRel.eq_iff {x y : B} {x' y' : B'} (hx : ExtRel S S' x x') (hy : ExtRel S S' y y') :
    x = y ↔ x' = y' := by
  obtain ⟨μ, hμ, rfl, rfl⟩ := hx
  obtain ⟨ν, hν, rfl, rfl⟩ := hy
  constructor
  · intro h
    have := congrArg C.wt h
    rw [S.wt_u hμ, S.wt_u hν] at this
    rw [this]
  · intro h
    have := congrArg C'.wt h
    rw [S'.wt_u hμ, S'.wt_u hν] at this
    rw [this]

lemma forall₂_extRel_eq_iff : {n : ℕ} → {x y : TPow B n} → {x' y' : TPow B' n} →
    TPow.Forall₂ (ExtRel S S') x x' → TPow.Forall₂ (ExtRel S S') y y' → (x = y ↔ x' = y')
  | 0, _, _, _, _, _, _ => ⟨fun _ ↦ rfl, fun _ ↦ rfl⟩
  | _ + 1, x, y, x', y', hx, hy => by
    have h1 := hx.1.eq_iff S S' hy.1
    have h2 := forall₂_extRel_eq_iff hx.2 hy.2
    obtain ⟨a, x⟩ := x
    obtain ⟨b, y⟩ := y
    obtain ⟨a', x'⟩ := x'
    obtain ⟨b', y'⟩ := y'
    change (a, x) = (b, y) ↔ (a', x') = (b', y')
    rw [Prod.mk.injEq, Prod.mk.injEq, h1, h2]

lemma isColourRel (i : ι) : IsColourRel C C' i (StrRel S S' i) where
  ε_eq x x' h := by
    obtain ⟨μ, hμ, ha, c, -, hx, hx'⟩ := h
    rw [C.ε_fIter hx, C'.ε_fIter hx', S.ε_u hμ i ha, S'.ε_u hμ i ha]
  coroot_eq x x' h := by
    obtain ⟨μ, hμ, -, c, -, hx, hx'⟩ := h
    rw [C.wt_fIter hx, C'.wt_fIter hx', S.wt_u hμ, S'.wt_u hμ]
  f_rel x x' h := by
    obtain ⟨μ, hμ, ha, c, hc, hx, hx'⟩ := h
    have e1 : C.f i x = C.fIter i (c + 1) (S.u μ) := by rw [fIter_succ', hx, Option.bind_some]
    have e2 : C'.f i x' = C'.fIter i (c + 1) (S'.u μ) := by
      rw [fIter_succ', hx', Option.bind_some]
    rw [e1, e2]
    by_cases hc' : c + 1 ≤ (D.coroot i μ).toNat
    · have hs : (C.fIter i (c + 1) (S.u μ)).isSome := by
        rw [S.isSeminormal.isSome_fIter_iff, S.φ_u hμ i ha, ← WithBot.coe_natCast,
          WithBot.coe_le_coe]
        omega
      have hs' : (C'.fIter i (c + 1) (S'.u μ)).isSome := by
        rw [S'.isSeminormal.isSome_fIter_iff, S'.φ_u hμ i ha, ← WithBot.coe_natCast,
          WithBot.coe_le_coe]
        omega
      obtain ⟨y, hy⟩ := Option.isSome_iff_exists.1 hs
      obtain ⟨y', hy'⟩ := Option.isSome_iff_exists.1 hs'
      exact Or.inr ⟨y, y', hy, hy', μ, hμ, ha, c + 1, hc', hy, hy'⟩
    · have hs : ¬ (C.fIter i (c + 1) (S.u μ)).isSome := by
        rw [S.isSeminormal.isSome_fIter_iff, S.φ_u hμ i ha, ← WithBot.coe_natCast,
          WithBot.coe_le_coe]
        omega
      have hs' : ¬ (C'.fIter i (c + 1) (S'.u μ)).isSome := by
        rw [S'.isSeminormal.isSome_fIter_iff, S'.φ_u hμ i ha, ← WithBot.coe_natCast,
          WithBot.coe_le_coe]
        omega
      exact Or.inl ⟨Option.not_isSome_iff_eq_none.1 hs, Option.not_isSome_iff_eq_none.1 hs'⟩

lemma strLen_eq {i : ι} {μ : X} (hμ : D.Orbit Λ μ) (ha : 0 ≤ D.coroot i μ) {c : ℕ} {x : B}
    (hx : C.fIter i c (S.u μ) = some x) : C.strLen i x = (D.coroot i μ).toNat := by
  have h1 := C.φ_fIter hx
  rw [S.φ_u hμ i ha] at h1
  rw [strLen, C.ε_fIter hx, S.ε_u hμ i ha, zero_add, eq_coe_sub_of_coe_eq_add h1,
    ← WithBot.coe_natCast, ← WithBot.coe_add, WithBot.unbotD_coe, add_sub_cancel]

/-- `T_K` maps `f̃ᵢᶜ u_μ` and `f̃ᵢᶜ u'_μ` to tensor products of corresponding extremal elements if
`K` is divisible by the length of the `i`-string. -/
theorem forall₂_T_of_strRel {i : ι} {K : ℕ} (hK : 0 < K) {x : B} {x' : B'}
    (h : StrRel S S' i x x') (hdvd : max 1 (C.strLen i x) ∣ K) :
    TPow.Forall₂ (ExtRel S S') (S.T K hK x) (S'.T K hK x') := by
  obtain ⟨μ, hμ, ha, c, hc, hx, hx'⟩ := h
  rw [strLen_eq S hμ ha hx] at hdvd
  set a := (D.coroot i μ).toNat with ha'
  have h1 := (S.T K hK).fIter_mul i c (S.u μ)
  have h1' := (S'.T K hK).fIter_mul i c (S'.u μ)
  rw [hx, Option.map_some, S.T_u hK hμ] at h1
  rw [hx', Option.map_some, S'.T_u hK hμ] at h1'
  rcases Nat.eq_zero_or_pos a with h0 | hpos
  · have hc0 : c = 0 := by omega
    subst hc0
    cases hx
    cases hx'
    rw [S.T_u hK hμ, S'.T_u hK hμ]
    exact TPow.forall₂_replicate ⟨μ, hμ, rfl, rfl⟩ K
  · rw [max_eq_right (by omega)] at hdvd
    obtain ⟨t, ht⟩ := hdvd
    have hq : K * c = a * (t * c) := by rw [ht]; ring
    have hqK : t * c ≤ K := by rw [ht]; nlinarith
    have e := fIter_replicate (C := C) i (S.ε_u hμ i ha)
      (by rw [S.φ_u hμ i ha, Int.toNat_of_nonneg ha]) (S.fIter_u hμ i ha) K (t * c) hqK
    have e' := fIter_replicate (C := C') i (S'.ε_u hμ i ha)
      (by rw [S'.φ_u hμ i ha, Int.toNat_of_nonneg ha]) (S'.fIter_u hμ i ha) K (t * c) hqK
    rw [hq, e] at h1
    rw [hq, e'] at h1'
    rw [← Option.some_injective _ h1, ← Option.some_injective _ h1']
    exact TPow.forall₂_replicate₂ ⟨_, hμ.reflection i, rfl, rfl⟩ ⟨μ, hμ, rfl, rfl⟩ _ _

lemma forall₂_T_of_extRel {K : ℕ} (hK : 0 < K) {x : B} {x' : B'} (h : ExtRel S S' x x') :
    TPow.Forall₂ (ExtRel S S') (S.T K hK x) (S'.T K hK x') := by
  obtain ⟨μ, hμ, rfl, rfl⟩ := h
  rw [S.T_u hK hμ, S'.T_u hK hμ]
  exact TPow.forall₂_replicate ⟨μ, hμ, rfl, rfl⟩ K

/-! ### Words on tensor powers -/

variable (C b₀) in
/-- `f̃_{wᴹ}(b₀ ⊗ ⋯ ⊗ b₀)` in `B^{⊗M}`. -/
def lvl (M : ℕ) (w : List ι) : Option (TPow B M) :=
  (C.tensorPow M).fWord (stretchWord M w) (TPow.replicate b₀ M)

lemma lvl_def (M : ℕ) (w : List ι) :
    lvl C b₀ M w = (C.tensorPow M).fWord (stretchWord M w) (TPow.replicate b₀ M) := rfl

lemma lvl_eq {M : ℕ} (hM : 0 < M) (w : List ι) :
    lvl C b₀ M w = (C.fWord w b₀).map (S.T M hM) := by
  rw [lvl, ← S.T_b₀ M hM, (S.T M hM).fWord_stretchWord]

lemma lvl_mul {K : ℕ} (hK : 0 < K) (N : ℕ) (w : List ι) :
    lvl C b₀ (K * N) w = (lvl C b₀ N w).map (Similarity.powMap hK (S.T K hK) N) := by
  rw [lvl, stretchWord_mul, ← Similarity.powMap_replicate hK (S.T K hK) (S.T_b₀ K hK),
    (Similarity.powMap hK (S.T K hK) N).fWord_stretchWord]
  rfl

lemma lvl_cons (M : ℕ) (i : ι) (w : List ι) :
    lvl C b₀ M (i :: w) = (lvl C b₀ M w).bind ((C.tensorPow M).fIter i M) := by
  rw [lvl, lvl, fWord_stretchWord_cons]

/-- The words `f̃_{wᴹ}(b₀ ⊗ ⋯ ⊗ b₀)` in `C` and `C'` are both `0` or tensor products of
corresponding extremal elements. -/
def RelAt (M : ℕ) (w : List ι) : Prop :=
  OptRel (TPow.Forall₂ (ExtRel S S')) (lvl C b₀ M w) (lvl C' b₀' M w)

lemma forall₂_powMap {K : ℕ} (hK : 0 < K) {N : ℕ} {l : TPow B N} {l' : TPow B' N}
    (h : TPow.Forall₂ (ExtRel S S') l l') :
    TPow.Forall₂ (ExtRel S S') (Similarity.powMap hK (S.T K hK) N l)
      (Similarity.powMap hK (S'.T K hK) N l') := by
  rw [Similarity.powMap_apply, Similarity.powMap_apply]
  exact TPow.forall₂_flatten (TPow.forall₂_map (fun _ _ hx ↦ forall₂_T_of_extRel S S' hK hx) h)

lemma RelAt.mul {K : ℕ} (hK : 0 < K) {N : ℕ} {w : List ι} (h : RelAt S S' N w) :
    RelAt S S' (K * N) w := by
  rw [RelAt, lvl_mul S hK, lvl_mul S' hK]
  rcases h with ⟨h1, h1'⟩ | ⟨l, l', h1, h1', hl⟩
  · exact Or.inl ⟨by rw [h1]; rfl, by rw [h1']; rfl⟩
  · exact Or.inr ⟨_, _, by rw [h1]; rfl, by rw [h1']; rfl, forall₂_powMap S S' hK hl⟩

lemma relAt_nil : RelAt S S' 1 [] := by
  refine Or.inr ⟨TPow.replicate b₀ 1, TPow.replicate b₀' 1, rfl, rfl, ?_⟩
  exact TPow.forall₂_replicate ⟨Λ, CartanDatum.Orbit.self, S.u_Λ.symm, S'.u_Λ.symm⟩ 1

lemma forall₂_and_mem {β β' : Type*} {r : β → β' → Prop} {p : β → Prop} : {n : ℕ} →
    {x : TPow β n} → {x' : TPow β' n} → TPow.Forall₂ r x x' → (∀ a ∈ TPow.toList x, p a) →
    TPow.Forall₂ (fun a a' ↦ r a a' ∧ p a) x x'
  | 0, _, _, _, _ => True.intro
  | _ + 1, _, _, h, hp => ⟨⟨h.1, hp _ (List.mem_cons_self ..)⟩,
      forall₂_and_mem h.2 fun a ha ↦ hp a (List.mem_cons_of_mem _ ha)⟩

lemma RelAt.cons {N : ℕ} (hN : 0 < N) {w : List ι} (h : RelAt S S' N w) (i : ι) :
    ∃ M, 0 < M ∧ RelAt S S' M (i :: w) := by
  rcases h with ⟨h1, h1'⟩ | ⟨l, l', h1, h1', hl⟩
  · exact ⟨N, hN, Or.inl ⟨by rw [lvl_cons, h1]; rfl, by rw [lvl_cons, h1']; rfl⟩⟩
  have hf := (isColourRel S S' i).fIter_tensorPow N
    (TPow.forall₂_mono (fun _ _ hx ↦ ExtRel.strRel S S' hx i) hl)
  rcases hf with ⟨h2, h2'⟩ | ⟨m, m', h2, h2', hm⟩
  · exact ⟨N, hN, Or.inl ⟨by rw [lvl_cons, h1, Option.bind_some, h2],
      by rw [lvl_cons, h1', Option.bind_some, h2']⟩⟩
  set K := ((TPow.toList m).map fun x ↦ max 1 (C.strLen i x)).prod with hKdef
  have hK : 0 < K := by
    rw [hKdef, Nat.pos_iff_ne_zero, Ne, List.prod_eq_zero_iff]
    simp
  have hm2 := forall₂_and_mem (p := fun x ↦ max 1 (C.strLen i x) ∣ K) hm
    (fun a ha ↦ List.dvd_prod (List.mem_map_of_mem ha))
  refine ⟨K * N, Nat.mul_pos hK hN, Or.inr ⟨Similarity.powMap hK (S.T K hK) N m,
    Similarity.powMap hK (S'.T K hK) N m', ?_, ?_, ?_⟩⟩
  · rw [lvl_cons, lvl_mul S hK, h1, Option.map_some, Option.bind_some, Similarity.fIter_mul, h2,
      Option.map_some]
  · rw [lvl_cons, lvl_mul S' hK, h1', Option.map_some, Option.bind_some, Similarity.fIter_mul,
      h2', Option.map_some]
  · rw [Similarity.powMap_apply, Similarity.powMap_apply]
    exact TPow.forall₂_flatten
      (TPow.forall₂_map (fun _ _ hx ↦ forall₂_T_of_strRel S S' hK hx.1 hx.2) hm2)

theorem exists_relAt (w : List ι) : ∃ N, 0 < N ∧ RelAt S S' N w := by
  induction w with
  | nil => exact ⟨1, one_pos, relAt_nil S S'⟩
  | cons i w ih =>
    obtain ⟨N, hN, h⟩ := ih
    exact h.cons S S' hN i

omit [AddCommGroup X] in
lemma optRel_eq_iff {β β' : Type*} {r : β → β' → Prop}
    (hr : ∀ x x' y y', r x x' → r y y' → (x = y ↔ x' = y')) {o₁ o₂ : Option β}
    {o₁' o₂' : Option β'} (h₁ : OptRel r o₁ o₁') (h₂ : OptRel r o₂ o₂') :
    o₁ = o₂ ↔ o₁' = o₂' := by
  rcases h₁ with ⟨rfl, rfl⟩ | ⟨y₁, y₁', rfl, rfl, hy₁⟩ <;>
    rcases h₂ with ⟨rfl, rfl⟩ | ⟨y₂, y₂', rfl, rfl, hy₂⟩
  · simp
  · simp
  · simp
  · rw [Option.some_inj, Option.some_inj]
    exact hr _ _ _ _ hy₁ hy₂

include S S' in
/-- **[Kas96] (4.6)**: `f̃_w b₀ = 0` in `C` if and only if `f̃_w b₀' = 0` in `C'`. -/
theorem fWord_eq_none_iff (w : List ι) : C.fWord w b₀ = none ↔ C'.fWord w b₀' = none := by
  obtain ⟨N, hN, h⟩ := exists_relAt S S' w
  rw [RelAt, lvl_eq S hN, lvl_eq S' hN] at h
  rcases h with ⟨h1, h1'⟩ | ⟨l, l', h1, h1', -⟩
  · rw [Option.map_eq_none_iff] at h1 h1'
    exact ⟨fun _ ↦ h1', fun _ ↦ h1⟩
  · obtain ⟨b, hb, -⟩ := Option.map_eq_some_iff.1 h1
    obtain ⟨b', hb', -⟩ := Option.map_eq_some_iff.1 h1'
    rw [hb, hb']
    simp

include S S' in
/-- **[Kas96] (4.5)**: `f̃_w b₀ = f̃_{w'} b₀` in `C` if and only if `f̃_w b₀' = f̃_{w'} b₀'` in
`C'`. -/
theorem fWord_eq_fWord_iff (w w' : List ι) :
    C.fWord w b₀ = C.fWord w' b₀ ↔ C'.fWord w b₀' = C'.fWord w' b₀' := by
  obtain ⟨N₁, hN₁, h₁⟩ := exists_relAt S S' w
  obtain ⟨N₂, hN₂, h₂⟩ := exists_relAt S S' w'
  have e₁ := h₁.mul S S' hN₂
  have e₂ := h₂.mul S S' hN₁
  rw [Nat.mul_comm] at e₂
  have hM : 0 < N₂ * N₁ := Nat.mul_pos hN₂ hN₁
  have key := optRel_eq_iff (fun x x' y y' hx hy ↦ forall₂_extRel_eq_iff S S' hx hy) e₁ e₂
  rw [lvl_eq S hM, lvl_eq S hM, lvl_eq S' hM, lvl_eq S' hM,
    (Option.map_injective (S.T_injective _ hM)).eq_iff,
    (Option.map_injective (S'.T_injective _ hM)).eq_iff] at key
  exact key

include S S' in
/-- **Kashiwara's comparison theorem** ([Kas96] proof of Thm. 4.1): two crystals with similarity
data for the same `Λ` are isomorphic, by the isomorphism `f̃_w b₀ ↦ f̃_w b₀'`. -/
theorem exists_equiv : ∃ Φ : Equiv C C', ∀ w b, C.fWord w b₀ = some b →
    C'.fWord w b₀' = some (Φ b) :=
  exists_equiv_of_fWord S.isSeminormal S'.isSeminormal S.exists_fWord S'.exists_fWord
    (by rw [S.wt_b₀, S'.wt_b₀]) (fWord_eq_none_iff S S') (fWord_eq_fWord_iff S S')

include S S' in
/-- Two crystals with similarity data for the same `Λ` are isomorphic by an isomorphism sending
`b₀` to `b₀'`, and such an isomorphism is unique. -/
theorem existsUnique_equiv : ∃ Φ : Equiv C C', Φ b₀ = b₀' ∧
    ∀ Φ' : Equiv C C', Φ' b₀ = b₀' → ∀ b, Φ' b = Φ b := by
  obtain ⟨Φ, hΦ⟩ := exists_equiv S S'
  have h0 : Φ b₀ = b₀' := (Option.some_injective _ (hΦ [] b₀ rfl)).symm
  exact ⟨Φ, h0, fun Φ' h' b ↦ Equiv.eq_of_fWord S.exists_fWord (h'.trans h0.symm) b⟩

end SimilarityData

end Crystal
