/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.RepresentationTheory.Crystal.SimilarityComparison

/-!
# Similarities from embeddings into a crystal with a similarity

Kashiwara deduces the similarity `B(λ) → B(mλ)` from the similarity of `B(∞)` through the
embeddings `B(λ) ↪ B(∞) ⊗ T_λ` ([Kas96] proof of Thm. 3.1). We formalize this abstractly: let
`C`, `C'` be seminormal crystals generated by `b₀`, `b₀'` with `wt b₀' = m wt b₀`, and let
`j : B → E`, `j' : B' → E` be *weak embeddings* into a crystal `E` (`Crystal.IsWeakEmbedding`:
injective, preserving `εᵢ`, shifting weights by `-wt b₀`, and commuting with `f̃ᵢ` whenever
`f̃ᵢ b ≠ 0`) with `j b₀ = j' b₀' = e₀`. If `σ : E → E` is an `m`-similarity fixing `e₀`, then
there is an `m`-similarity `S : C → C'` with `S b₀ = b₀'` and `j' ∘ S = σ ∘ j`
(`Crystal.Similarity.exists_of_isWeakEmbedding`).

## References

* [Kas96] M. Kashiwara, *Similarity of crystal bases*, Contemp. Math. 194 (1996), 177–186, §3.
-/

namespace Crystal

variable {ι X : Type*} [AddCommGroup X] {D : CartanDatum ι X} {B B' BE : Type*}

/-- A weak embedding `j : B → E` of a crystal generated by `b₀` into `E`: injective, preserving
the `εᵢ`, with `wt (j b) = wt b - wt b₀`, and `j(f̃ᵢ b) = f̃ᵢ j(b)` whenever `f̃ᵢ b ≠ 0`. This is
the structure of `B(λ) → B(∞)`, `b ↦ b ⊗ t_{-λ}` (cf. [Kas96] §2). -/
structure IsWeakEmbedding (C : Crystal D B) (E : Crystal D BE) (b₀ : B) (j : B → BE) : Prop where
  injective : Function.Injective j
  ε_map : ∀ i b, E.ε i (j b) = C.ε i b
  wt_map : ∀ b, E.wt (j b) = C.wt b - C.wt b₀
  f_map : ∀ i b b₁, C.f i b = some b₁ → E.f i (j b) = some (j b₁)

namespace IsWeakEmbedding

variable {C : Crystal D B} {E : Crystal D BE} {b₀ : B} {j : B → BE}

lemma φ_map (h : IsWeakEmbedding C E b₀ j) (i : ι) (b : B) :
    C.φ i b = E.φ i (j b) + (D.coroot i (C.wt b₀) : WithBot ℤ) := by
  rw [C.φ_eq, E.φ_eq, h.ε_map, h.wt_map, map_sub, add_assoc, ← WithBot.coe_add, sub_add_cancel]

lemma fIter_map (h : IsWeakEmbedding C E b₀ j) (i : ι) (n : ℕ) {b b₁ : B}
    (hb : C.fIter i n b = some b₁) : E.fIter i n (j b) = some (j b₁) := by
  induction n generalizing b₁ with
  | zero => cases hb; rfl
  | succ n ih =>
    rw [fIter_succ'] at hb ⊢
    obtain ⟨c, hc, hf⟩ := Option.bind_eq_some_iff.mp hb
    rw [ih hc, Option.bind_some, h.f_map i c b₁ hf]

end IsWeakEmbedding

variable {C : Crystal D B} {C' : Crystal D B'} {E : Crystal D BE} {m : ℕ}

/-- **Similarity from weak embeddings** ([Kas96] proof of Thm. 3.1): if `C`, `C'` are seminormal,
generated by `b₀`, `b₀'` with `wt b₀' = m wt b₀`, `j : C → E`, `j' : C' → E` are weak embeddings
with `j b₀ = j' b₀' = e₀`, and `σ : E → E` is an `m`-similarity fixing `e₀`, then there is an
`m`-similarity `S : C → C'` with `S b₀ = b₀'` and `j' ∘ S = σ ∘ j`. -/
theorem Similarity.exists_of_isWeakEmbedding (hm : 0 < m) (hC : C.IsSeminormal)
    (hC' : C'.IsSeminormal) {b₀ : B} {b₀' : B'} (hgen : ∀ b, ∃ w, C.fWord w b₀ = some b)
    (hwt : C'.wt b₀' = m • C.wt b₀) {j : B → BE} {j' : B' → BE}
    (hj : IsWeakEmbedding C E b₀ j) (hj' : IsWeakEmbedding C' E b₀' j')
    (h₀ : j' b₀' = j b₀) (σ : Similarity E E m) (hσ : σ (j b₀) = j b₀) :
    ∃ S : Similarity C C' m, S b₀ = b₀' ∧ ∀ b, j' (S b) = σ (j b) := by
  -- `φᵢ` of corresponding elements
  have hφ : ∀ (i : ι) (b : B) (b' : B'), j' b' = σ (j b) → C'.φ i b' = m • C.φ i b := by
    intro i b b' hb'
    rw [hj'.φ_map, hj.φ_map, hb', σ.φ_apply, hwt, map_nsmul, nsmul_add, ← WithBot.coe_nsmul]
  have key : ∀ (w : List ι) (b : B), C.fWord w b₀ = some b →
      ∃ b', C'.fWord (stretchWord m w) b₀' = some b' ∧ j' b' = σ (j b) := by
    intro w
    induction w with
    | nil => intro b hb; cases hb; exact ⟨b₀', rfl, by rw [h₀, hσ]⟩
    | cons i w ih =>
      intro b hb
      obtain ⟨c, hc, hf⟩ := Option.bind_eq_some_iff.mp hb
      obtain ⟨c', hc', hjc⟩ := ih c hc
      have h1 : (1 : WithBot ℤ) ≤ C.φ i c := by
        have := (hC.isSome_fIter_iff (i := i) (b := c) 1).1 (by rw [fIter_one, hf]; rfl)
        exact_mod_cast this
      have h2 : (C'.fIter i m c').isSome := by
        rw [hC'.isSome_fIter_iff, hφ i c c' hjc]
        obtain ⟨p, hp⟩ := hC.exists_φ_eq i c
        rw [hp] at h1 ⊢
        have : 1 ≤ p := by exact_mod_cast h1
        rw [← WithBot.coe_natCast p, nsmul_coe_withBot, ← WithBot.coe_natCast,
          WithBot.coe_le_coe]
        nlinarith
      obtain ⟨b', hb'⟩ := Option.isSome_iff_exists.1 h2
      refine ⟨b', by rw [fWord_stretchWord_cons, hc', Option.bind_some, hb'], ?_⟩
      have h3 := hj'.fIter_map i m hb'
      rw [hjc, σ.fIter_apply, hj.f_map i c b hf, Option.map_some] at h3
      exact (Option.some_injective _ h3).symm
  choose wd hwd using hgen
  have hS : ∀ b, ∃ b', j' b' = σ (j b) := fun b ↦ by
    obtain ⟨b', -, h⟩ := key (wd b) b (hwd b)
    exact ⟨b', h⟩
  choose S hSj using hS
  have hSw : ∀ w b, C.fWord w b₀ = some b → C'.fWord (stretchWord m w) b₀' = some (S b) := by
    intro w b hb
    obtain ⟨b', hb', h⟩ := key w b hb
    rw [hb', hj'.injective (h.trans (hSj b).symm)]
  have hwtS : ∀ b, C'.wt (S b) = m • C.wt b := fun b ↦ by
    have := hj'.wt_map (S b)
    rw [hSj, σ.wt_apply, hj.wt_map, hwt] at this
    rw [smul_sub] at this
    exact (sub_left_inj.1 this).symm
  have hεS : ∀ i b, C'.ε i (S b) = m • C.ε i b := fun i b ↦ by
    rw [← hj'.ε_map, hSj, σ.ε_apply, hj.ε_map]
  have hφS : ∀ i b, C'.φ i (S b) = m • C.φ i b := fun i b ↦ hφ i b (S b) (hSj b)
  obtain ⟨n, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hm.ne'
  refine ⟨
    { toFun := S
      wt_map := hwtS
      ε_map := hεS
      e_map := fun i b ↦ ?_
      f_map := fun i b ↦ ?_ }, ?_, hSj⟩
  · cases he : C.e i b with
    | some b₂ =>
      have hf : C.f i b₂ = some b := (C.f_eq_some_iff i b₂ b).2 he
      have h1 : C.fWord (i :: wd b₂) b₀ = some b := by
        rw [fWord_cons, hwd, Option.bind_some, hf]
      have h2 := hSw _ _ h1
      rw [fWord_stretchWord_cons, hSw _ _ (hwd b₂), Option.bind_some] at h2
      rw [Option.map_some, ← C'.fIter_eq_some_iff]
      exact h2
    | none =>
      have h0 : C'.ε i (S b) = 0 := by rw [hεS, hC.ε_eq_zero he, nsmul_zero]
      have h1 : C'.e i (S b) = none := by
        rw [← Option.not_isSome_iff_eq_none, ← eIter_one, hC'.isSome_eIter_iff, h0]
        exact_mod_cast (by norm_num : ¬ (1 : ℤ) ≤ 0)
      rw [eIter_succ, h1]
      rfl
  · cases hf : C.f i b with
    | some b₁ =>
      have h1 : C.fWord (i :: wd b) b₀ = some b₁ := by rw [fWord_cons, hwd, Option.bind_some, hf]
      have h2 := hSw _ _ h1
      rw [fWord_stretchWord_cons, hSw _ _ (hwd b), Option.bind_some] at h2
      rw [Option.map_some]
      exact h2
    | none =>
      have h0 : C'.φ i (S b) = 0 := by rw [hφS, hC.φ_eq_zero hf, nsmul_zero]
      have h1 : C'.f i (S b) = none := by
        rw [← Option.not_isSome_iff_eq_none, ← fIter_one, hC'.isSome_fIter_iff, h0]
        exact_mod_cast (by norm_num : ¬ (1 : ℤ) ≤ 0)
      rw [fIter_succ, h1]
      rfl
  · change S b₀ = b₀'
    exact hj'.injective ((hSj b₀).trans (by rw [hσ, h₀]))

end Crystal
