/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.LusztigF.Bar
import LieLean.Algebra.QuantumGroup.GabberKac

/-!
# Bar on the actual Serre and Lusztig radical quotients

## Main definitions

* `LusztigF.serreBar`: the semilinear ring involution on the two-sided Serre quotient.
* `LusztigF.quotientBar`: its counterpart on the existing radical quotient over `ℚ(X)`.

## Main results

* `LusztigF.bar_mem_serreIdeal_iff`: stability of the actual two-sided Serre ideal.
* `LusztigF.bar_mem_radical_iff`: radical stability, using quantum Gabber–Kac with finite `I`.
* The quotient bars are involutive, fix generators and divided powers, and bar coefficients.

## References

The descent arguments are reconstructed from ideal generation and the quotient universal
property. The relation-level input is `LusztigF/Bar.lean`; the radical identification is the
repository's quantum Gabber–Kac theorem ([Lus], *Introduction to quantum groups*,
Theorem 33.1.3 (a)). No crystal lattice, balancedness, or global basis is claimed.
-/

open LieLean

noncomputable section

namespace LusztigF

variable {K I : Type*} [Field K] (D : LusztigCartanDatum I)

/-- Bar preserves the actual two-sided ideal generated by all off-diagonal Serre relations.
Reconstructed using the universal property of `TwoSidedIdeal.span`. -/
theorem bar_mem_serreIdeal {x : LusztigF (RatFunc K) I}
    (hx : x ∈ serreIdeal D (RatFunc.X : RatFunc K)) :
    bar x ∈ serreIdeal D (RatFunc.X : RatFunc K) := by
  have h : serreIdeal D (RatFunc.X : RatFunc K) ≤
      (serreIdeal D (RatFunc.X : RatFunc K)).comap bar := by
    apply TwoSidedIdeal.span_le.mpr
    rintro _ ⟨i, j, hij, rfl⟩
    simp only [SetLike.mem_coe, TwoSidedIdeal.mem_comap, bar_serreElement]
    exact TwoSidedIdeal.subset_span ⟨i, j, hij, rfl⟩
  exact (TwoSidedIdeal.mem_comap bar).mp (h hx)

/-- The two-sided Serre ideal is invariant in both directions under bar. -/
theorem bar_mem_serreIdeal_iff (x : LusztigF (RatFunc K) I) :
    bar x ∈ serreIdeal D (RatFunc.X : RatFunc K) ↔
      x ∈ serreIdeal D (RatFunc.X : RatFunc K) :=
  ⟨fun hx ↦ by simpa using bar_mem_serreIdeal D hx, bar_mem_serreIdeal D⟩

/-- Equality with the pullback ideal, the compatibility needed by quotient descent. -/
theorem serreIdeal_comap_bar :
    (serreIdeal D (RatFunc.X : RatFunc K)).comap bar =
      serreIdeal D (RatFunc.X : RatFunc K) := by
  ext x
  exact (TwoSidedIdeal.mem_comap bar).trans (bar_mem_serreIdeal_iff D x)

/-- The actual Serre quotient at the rational-function parameter. -/
abbrev SerreBarQuotient := (serreIdeal D (RatFunc.X : RatFunc K)).ringCon.Quotient

/-- The quotient projection, retaining its ordinary coefficient algebra structure. -/
def toSerreBarQuotient : LusztigF (RatFunc K) I →ₐ[RatFunc K] SerreBarQuotient (K := K) D :=
  RingCon.mkₐ (RatFunc K) (serreIdeal D (RatFunc.X : RatFunc K)).ringCon

/-- Bar descended via Mathlib's `RingCon.congr`; this is not a `RatFunc K` algebra map. -/
def serreBar : SerreBarQuotient (K := K) D ≃+* SerreBarQuotient (K := K) D :=
  RingCon.congr bar (congrArg TwoSidedIdeal.ringCon (serreIdeal_comap_bar D).symm)

@[simp] theorem serreBar_toSerreBarQuotient (x : LusztigF (RatFunc K) I) :
    serreBar D (toSerreBarQuotient D x) = toSerreBarQuotient D (bar x) := rfl

/-- The descended Serre bar squares to the identity. -/
@[simp] theorem serreBar_serreBar (x : SerreBarQuotient (K := K) D) :
    serreBar D (serreBar D x) = x := by
  obtain ⟨x, rfl⟩ := RingCon.mkₐ_surjective (α := RatFunc K)
    (serreIdeal D (RatFunc.X : RatFunc K)).ringCon x
  change toSerreBarQuotient D (bar (bar x)) = toSerreBarQuotient D x
  rw [bar_bar]

/-- The quotient bar acts semilinearly by inversion of the coefficient parameter. -/
theorem serreBar_smul (c : RatFunc K) (x : SerreBarQuotient (K := K) D) :
    serreBar D (c • x) = RatFunc.bar c • serreBar D x := by
  obtain ⟨x, rfl⟩ := RingCon.mkₐ_surjective (α := RatFunc K)
    (serreIdeal D (RatFunc.X : RatFunc K)).ringCon x
  change serreBar D (c • toSerreBarQuotient D x) =
    RatFunc.bar c • serreBar D (toSerreBarQuotient D x)
  rw [← map_smul, serreBar_toSerreBarQuotient, bar_smul, map_smul,
    serreBar_toSerreBarQuotient]

/-- On scalar elements, the Serre quotient bar is exactly coefficient bar. -/
@[simp] theorem serreBar_algebraMap (c : RatFunc K) :
    serreBar D (algebraMap (RatFunc K) (SerreBarQuotient (K := K) D) c) =
      algebraMap (RatFunc K) (SerreBarQuotient (K := K) D) (RatFunc.bar c) := by
  simpa only [Algebra.smul_def, mul_one, map_one] using
    serreBar_smul D c (1 : SerreBarQuotient (K := K) D)

@[simp] theorem serreBar_θ (i : I) :
    serreBar D (toSerreBarQuotient D (θ (RatFunc K) i)) =
      toSerreBarQuotient D (θ (RatFunc K) i) := by simp

/-- Every generator divided power remains bar-fixed after Serre quotient descent. -/
theorem serreBar_qDivPow (d n : ℕ) (i : I) :
    serreBar D (QuantumGroup.qDivPow ((RatFunc.X : RatFunc K) ^ d) n
      (toSerreBarQuotient D (θ (RatFunc K) i))) =
    QuantumGroup.qDivPow ((RatFunc.X : RatFunc K) ^ d) n
      (toSerreBarQuotient D (θ (RatFunc K) i)) := by
  simp [QuantumGroup.qDivPow, serreBar_smul, QuantumGroup.bar_qFactorial]

section Radical

variable [Finite I] [DecidableEq I]

/-- Radical stability over `ℚ(X)`, retaining the finite-index hypothesis of quantum
Gabber–Kac. Characteristic zero and transcendence are provided by `ℚ(X)` and its indeterminate. -/
theorem bar_mem_radical_iff (x : LusztigF (RatFunc ℚ) I) :
    bar x ∈ radical D (RatFunc.X : RatFunc ℚ) ↔
      x ∈ radical D (RatFunc.X : RatFunc ℚ) := by
  rw [radical_eq_serreIdeal_ratFunc D]
  exact bar_mem_serreIdeal_iff D x

/-- The existing Lusztig radical is equal to its pullback under the constructed bar. -/
theorem radical_comap_bar :
    (radical D (RatFunc.X : RatFunc ℚ)).comap bar =
      radical D (RatFunc.X : RatFunc ℚ) := by
  ext x
  exact (TwoSidedIdeal.mem_comap bar).trans (bar_mem_radical_iff D x)

/-- The constructed involution on the repository's actual `LusztigF.Quotient`, not a new
quotient surrogate and not a coefficient-linear algebra equivalence. -/
def quotientBar : Quotient D (RatFunc.X : RatFunc ℚ) ≃+* Quotient D (RatFunc.X : RatFunc ℚ) :=
  RingCon.congr bar (congrArg TwoSidedIdeal.ringCon (radical_comap_bar D).symm)

@[simp] theorem quotientBar_toQuotient (x : LusztigF (RatFunc ℚ) I) :
    quotientBar D (toQuotient D RatFunc.X x) = toQuotient D RatFunc.X (bar x) := rfl

/-- The bar on the actual radical quotient is involutive. -/
@[simp] theorem quotientBar_quotientBar (x : Quotient D (RatFunc.X : RatFunc ℚ)) :
    quotientBar D (quotientBar D x) = x := by
  obtain ⟨x, rfl⟩ := toQuotient_surjective D (RatFunc.X : RatFunc ℚ) x
  simp

/-- The actual radical quotient bar is semilinear, with coefficient bar `X ↦ X⁻¹`. -/
theorem quotientBar_smul (c : RatFunc ℚ) (x : Quotient D (RatFunc.X : RatFunc ℚ)) :
    quotientBar D (c • x) = RatFunc.bar c • quotientBar D x := by
  obtain ⟨x, rfl⟩ := toQuotient_surjective D (RatFunc.X : RatFunc ℚ) x
  rw [← map_smul, quotientBar_toQuotient, bar_smul, map_smul, quotientBar_toQuotient]

/-- On scalar elements of the existing radical quotient, bar acts on coefficients. -/
@[simp] theorem quotientBar_algebraMap (c : RatFunc ℚ) :
    quotientBar D (algebraMap (RatFunc ℚ) (Quotient D (RatFunc.X : RatFunc ℚ)) c) =
      algebraMap (RatFunc ℚ) (Quotient D (RatFunc.X : RatFunc ℚ)) (RatFunc.bar c) := by
  simpa only [Algebra.smul_def, mul_one, map_one] using
    quotientBar_smul D c (1 : Quotient D (RatFunc.X : RatFunc ℚ))

@[simp] theorem quotientBar_θ (i : I) :
    quotientBar D (toQuotient D RatFunc.X (θ (RatFunc ℚ) i)) =
      toQuotient D RatFunc.X (θ (RatFunc ℚ) i) := by simp

/-- All generator divided powers in the actual Lusztig radical quotient are bar-fixed. -/
theorem quotientBar_qDivPow (d n : ℕ) (i : I) :
    quotientBar D (QuantumGroup.qDivPow ((RatFunc.X : RatFunc ℚ) ^ d) n
      (toQuotient D RatFunc.X (θ (RatFunc ℚ) i))) =
    QuantumGroup.qDivPow ((RatFunc.X : RatFunc ℚ) ^ d) n
      (toQuotient D RatFunc.X (θ (RatFunc ℚ) i)) := by
  simp [QuantumGroup.qDivPow, quotientBar_smul, QuantumGroup.bar_qFactorial]

end Radical

end LusztigF
