/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.LusztigF.BarQuotient

/-!
# Divided-power integral forms over the integer Laurent ring

## Main definitions

* `LusztigF.integralLaurentEval`: the actual map `ℤ[T,T⁻¹] → ℚ(X)`.
* `LusztigF.serreIntegralForm`: the subalgebra generated by all simple divided powers
  in the actual Serre quotient, using the Cartan datum's symmetrizer exponents.
* `LusztigF.quotientIntegralForm`: the analogous subalgebra in the existing radical quotient.
* `LusztigF.serreIntegralBar`, `LusztigF.quotientIntegralBar`: restricted ring involutions.

## Main results

The coefficient map is injective and intertwines Laurent inversion with coefficient bar.
Both generated integral forms span the generic quotients over `ℚ(X)`. Both are bar-stable;
their restricted bars are involutive and semilinear for Laurent inversion. The Serre results
hold for arbitrary `I`; radical bar results retain `[Finite I]` and `[DecidableEq I]`.
No freeness, crystal lattice, balancedness, or basis is assumed or concluded.

## References

Construction and proofs reconstructed from the divided-power definition and the universal
property of algebra generation; no primary source consulted for this extension.
-/

noncomputable section

namespace LusztigF

/-- The integer Laurent coefficient map at the generic parameter. -/
def integralLaurentEval : LaurentPolynomial ℤ →+* RatFunc ℚ :=
  LaurentPolynomial.eval₂ (algebraMap ℤ (RatFunc ℚ)) (Units.mk0 RatFunc.X RatFunc.X_ne_zero)

/-- The coefficient map is genuinely injective, not just an evaluation homomorphism.
Reconstructed by clearing negative powers and using transcendence. -/
theorem integralLaurentEval_injective : Function.Injective integralLaurentEval := by
  let : Algebra ℚ (RatFunc ℚ) := RatFunc.instAlgebraOfPolynomial ℚ ℚ
  have hv : Transcendental ℤ (RatFunc.X : RatFunc ℚ) :=
    Transcendental.restrictScalars (Int.cast_injective (α := ℚ)) RatFunc.transcendental_X
  rw [injective_iff_map_eq_zero]
  intro f hf
  obtain ⟨n, p, hp⟩ := LaurentPolynomial.exists_T_pow f
  have h1 : integralLaurentEval (Polynomial.toLaurent p) = 0 := by
    rw [hp, map_mul, hf, zero_mul]
  rw [integralLaurentEval, LaurentPolynomial.eval₂_toLaurent] at h1
  have h2 : p = 0 := (transcendental_iff.1 hv) p (by rwa [Polynomial.aeval_def])
  have h3 : f * LaurentPolynomial.T n = 0 := by rw [← hp, h2, map_zero]
  exact (LaurentPolynomial.isUnit_T (R := ℤ) (n : ℤ)).mul_left_eq_zero.mp h3

/-- Laurent monomials map to the corresponding integer powers of the parameter. -/
@[simp] theorem integralLaurentEval_T (n : ℤ) :
    integralLaurentEval (LaurentPolynomial.T n) = (RatFunc.X : RatFunc ℚ) ^ n := by
  simp [integralLaurentEval]

/-- The actual coefficient embedding intertwines the two constructed involutions.
Reconstructed by Laurent monomial induction. -/
theorem bar_integralLaurentEval (f : LaurentPolynomial ℤ) :
    RatFunc.bar (integralLaurentEval f) =
      integralLaurentEval (LaurentPolynomial.invert f) := by
  induction f using LaurentPolynomial.induction_on' with
  | add p q hp hq => simp only [map_add, hp, hq]
  | C_mul_T n a =>
    simp [integralLaurentEval, map_zpow₀]

variable {I : Type*} (D : LusztigCartanDatum I)

/-- Scalar restriction to the embedded integer Laurent coefficient ring. -/
instance serreIntegralAlgebra : Algebra (LaurentPolynomial ℤ) (SerreBarQuotient (K := ℚ) D) :=
  Algebra.compHom _ integralLaurentEval

/-- All divided powers, indexed by a simple root and a natural exponent. -/
def serreIntegralGenerator (i : I) (n : ℕ) : SerreBarQuotient (K := ℚ) D :=
  QuantumGroup.qDivPow ((RatFunc.X : RatFunc ℚ) ^ D.d i) n
    (toSerreBarQuotient D (θ (RatFunc ℚ) i))

/-- The actual `ℤ[X,X⁻¹]` divided-power subalgebra of the Serre quotient.
This definition asserts generation only, not freeness or a global basis. -/
def serreIntegralForm : Subalgebra (LaurentPolynomial ℤ) (SerreBarQuotient (K := ℚ) D) :=
  Algebra.adjoin (LaurentPolynomial ℤ) {x | ∃ i n, x = serreIntegralGenerator D i n}

/-- Every simple divided power belongs to the generated integral form. -/
theorem serreIntegralGenerator_mem (i : I) (n : ℕ) :
    serreIntegralGenerator D i n ∈ serreIntegralForm D :=
  Algebra.subset_adjoin ⟨i, n, rfl⟩

/-- The Serre bar acts on integral Laurent scalars by Laurent inversion. -/
theorem serreBar_integral_algebraMap (a : LaurentPolynomial ℤ) :
    serreBar D (algebraMap (LaurentPolynomial ℤ) (SerreBarQuotient (K := ℚ) D) a) =
      algebraMap (LaurentPolynomial ℤ) (SerreBarQuotient (K := ℚ) D)
        (LaurentPolynomial.invert a) := by
  change serreBar D (algebraMap (RatFunc ℚ) _ (integralLaurentEval a)) = _
  rw [serreBar_algebraMap, bar_integralLaurentEval]
  rfl

/-- Bar preserves the actual generated divided-power integral form.
Reconstructed from coefficient compatibility and fixed divided-power generators. -/
theorem serreBar_mem_integralForm {x : SerreBarQuotient (K := ℚ) D}
    (hx : x ∈ serreIntegralForm D) : serreBar D x ∈ serreIntegralForm D := by
  induction hx using Algebra.adjoin_induction with
  | mem x hx =>
    obtain ⟨i, n, rfl⟩ := hx
    rw [serreIntegralGenerator, serreBar_qDivPow]
    exact serreIntegralGenerator_mem D i n
  | algebraMap a =>
    rw [serreBar_integral_algebraMap]
    exact (serreIntegralForm D).algebraMap_mem _
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | mul x y _ _ hx hy => rw [map_mul]; exact mul_mem hx hy

/-- Bar stability in both directions; no finiteness hypothesis on the simple roots. -/
theorem serreBar_mem_integralForm_iff (x : SerreBarQuotient (K := ℚ) D) :
    serreBar D x ∈ serreIntegralForm D ↔ x ∈ serreIntegralForm D :=
  ⟨fun hx ↦ by simpa using serreBar_mem_integralForm D hx, serreBar_mem_integralForm D⟩

/-- The integral form spans the generic Serre quotient over `ℚ(X)`.
This is a spanning theorem, not linear independence or a scalar-extension isomorphism. -/
theorem span_serreIntegralForm :
    Submodule.span (RatFunc ℚ) (serreIntegralForm D : Set (SerreBarQuotient (K := ℚ) D)) =
      ⊤ := by
  have h : Algebra.adjoin (RatFunc ℚ)
      (serreIntegralForm D : Set (SerreBarQuotient (K := ℚ) D)) = ⊤ := by
    apply top_unique
    intro x hx
    clear hx
    obtain ⟨x, rfl⟩ := RingCon.mkₐ_surjective (α := RatFunc ℚ)
      (serreIdeal D (RatFunc.X : RatFunc ℚ)).ringCon x
    change toSerreBarQuotient D x ∈ _
    induction x using FreeAlgebra.induction with
    | grade0 c =>
      rw [AlgHom.commutes]
      exact Subalgebra.algebraMap_mem _ c
    | grade1 i =>
      apply Algebra.subset_adjoin
      simpa [serreIntegralGenerator, θ, QuantumGroup.qDivPow, QuantumGroup.qFactorial,
        QuantumGroup.qInt] using serreIntegralGenerator_mem D i 1
    | mul x y hx hy => rw [map_mul]; exact mul_mem hx hy
    | add x y hx hy => rw [map_add]; exact add_mem hx hy
  have hc : Submonoid.closure
      (serreIntegralForm D : Set (SerreBarQuotient (K := ℚ) D)) =
        (serreIntegralForm D).toSubmonoid := Submonoid.closure_eq _
  have hh := congrArg Subalgebra.toSubmodule h
  rw [Algebra.adjoin_eq_span, hc] at hh
  exact hh

/-- Restriction of the constructed Serre bar to the actual integral form. -/
def serreIntegralBar : serreIntegralForm D ≃+* serreIntegralForm D where
  toFun x := ⟨serreBar D x, serreBar_mem_integralForm D x.property⟩
  invFun x := ⟨serreBar D x, serreBar_mem_integralForm D x.property⟩
  left_inv x := Subtype.ext (serreBar_serreBar (K := ℚ) D (x : SerreBarQuotient D))
  right_inv x := Subtype.ext (serreBar_serreBar (K := ℚ) D (x : SerreBarQuotient D))
  map_mul' x y := Subtype.ext (map_mul (serreBar (K := ℚ) D) (↑x) (↑y))
  map_add' x y := Subtype.ext (map_add (serreBar (K := ℚ) D) (↑x) (↑y))

/-- The restricted Serre bar squares to the identity. -/
theorem serreIntegralBar_involutive : Function.Involutive (serreIntegralBar D) := by
  intro x
  exact Subtype.ext (serreBar_serreBar (K := ℚ) D x.val)

/-- The integral bar is semilinear for Laurent inversion, not Laurent-linear. -/
theorem serreIntegralBar_smul (a : LaurentPolynomial ℤ) (x : serreIntegralForm D) :
    serreIntegralBar D (a • x) = LaurentPolynomial.invert a • serreIntegralBar D x := by
  apply Subtype.ext
  change serreBar (K := ℚ) D (algebraMap (LaurentPolynomial ℤ) _ a * ↑x) =
    algebraMap (LaurentPolynomial ℤ) _ (LaurentPolynomial.invert a) * serreBar (K := ℚ) D ↑x
  rw [map_mul, serreBar_integral_algebraMap]

section Radical

variable [DecidableEq I]

/-- Integer Laurent scalars acting on the existing Lusztig radical quotient. -/
instance quotientIntegralAlgebra :
    Algebra (LaurentPolynomial ℤ) (Quotient D (RatFunc.X : RatFunc ℚ)) :=
  Algebra.compHom _ integralLaurentEval

/-- The actual divided powers in the repository's radical quotient. -/
def quotientIntegralGenerator (i : I) (n : ℕ) : Quotient D (RatFunc.X : RatFunc ℚ) :=
  QuantumGroup.qDivPow ((RatFunc.X : RatFunc ℚ) ^ D.d i) n
    (toQuotient D RatFunc.X (θ (RatFunc ℚ) i))

/-- The integer Laurent divided-power form in the existing radical quotient. -/
def quotientIntegralForm :
    Subalgebra (LaurentPolynomial ℤ) (Quotient D (RatFunc.X : RatFunc ℚ)) :=
  Algebra.adjoin (LaurentPolynomial ℤ) {x | ∃ i n, x = quotientIntegralGenerator D i n}

/-- All simple divided powers lie in the radical-quotient integral form. -/
theorem quotientIntegralGenerator_mem (i : I) (n : ℕ) :
    quotientIntegralGenerator D i n ∈ quotientIntegralForm D :=
  Algebra.subset_adjoin ⟨i, n, rfl⟩

/-- The radical-quotient form spans the generic algebra, without assuming a basis. -/
theorem span_quotientIntegralForm :
    Submodule.span (RatFunc ℚ)
      (quotientIntegralForm D : Set (Quotient D (RatFunc.X : RatFunc ℚ))) = ⊤ := by
  have h : Algebra.adjoin (RatFunc ℚ)
      (quotientIntegralForm D : Set (Quotient D (RatFunc.X : RatFunc ℚ))) = ⊤ := by
    apply top_unique
    intro x hx
    clear hx
    obtain ⟨x, rfl⟩ := toQuotient_surjective D (RatFunc.X : RatFunc ℚ) x
    induction x using FreeAlgebra.induction with
    | grade0 c =>
      rw [AlgHom.commutes]
      exact Subalgebra.algebraMap_mem _ c
    | grade1 i =>
      apply Algebra.subset_adjoin
      simpa [quotientIntegralGenerator, θ, QuantumGroup.qDivPow, QuantumGroup.qFactorial,
        QuantumGroup.qInt] using quotientIntegralGenerator_mem D i 1
    | mul x y hx hy => rw [map_mul]; exact mul_mem hx hy
    | add x y hx hy => rw [map_add]; exact add_mem hx hy
  have hc : Submonoid.closure
      (quotientIntegralForm D : Set (Quotient D (RatFunc.X : RatFunc ℚ))) =
        (quotientIntegralForm D).toSubmonoid := Submonoid.closure_eq _
  have hh := congrArg Subalgebra.toSubmodule h
  rw [Algebra.adjoin_eq_span, hc] at hh
  exact hh

variable [Finite I]

/-- The radical quotient bar acts on integral scalars by Laurent inversion. -/
theorem quotientBar_integral_algebraMap (a : LaurentPolynomial ℤ) :
    quotientBar D (algebraMap (LaurentPolynomial ℤ) (Quotient D (RatFunc.X : RatFunc ℚ)) a) =
      algebraMap (LaurentPolynomial ℤ) (Quotient D (RatFunc.X : RatFunc ℚ))
        (LaurentPolynomial.invert a) := by
  change quotientBar D (algebraMap (RatFunc ℚ) _ (integralLaurentEval a)) = _
  rw [quotientBar_algebraMap, bar_integralLaurentEval]
  rfl

/-- Bar stability of the actual integer Laurent radical-quotient form.
Finite `I` is retained from quantum Gabber–Kac in the construction of `quotientBar`. -/
theorem quotientBar_mem_integralForm {x : Quotient D (RatFunc.X : RatFunc ℚ)}
    (hx : x ∈ quotientIntegralForm D) : quotientBar D x ∈ quotientIntegralForm D := by
  induction hx using Algebra.adjoin_induction with
  | mem x hx =>
    obtain ⟨i, n, rfl⟩ := hx
    rw [quotientIntegralGenerator, quotientBar_qDivPow]
    exact quotientIntegralGenerator_mem D i n
  | algebraMap a =>
    rw [quotientBar_integral_algebraMap]
    exact (quotientIntegralForm D).algebraMap_mem _
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | mul x y _ _ hx hy => rw [map_mul]; exact mul_mem hx hy

/-- Two-sided bar invariance of the actual radical-quotient integral form. -/
theorem quotientBar_mem_integralForm_iff (x : Quotient D (RatFunc.X : RatFunc ℚ)) :
    quotientBar D x ∈ quotientIntegralForm D ↔ x ∈ quotientIntegralForm D :=
  ⟨fun hx ↦ by simpa using quotientBar_mem_integralForm D hx, quotientBar_mem_integralForm D⟩

/-- Bar restricted to the integral form of the existing radical quotient. -/
def quotientIntegralBar : quotientIntegralForm D ≃+* quotientIntegralForm D where
  toFun x := ⟨quotientBar D x, quotientBar_mem_integralForm D x.property⟩
  invFun x := ⟨quotientBar D x, quotientBar_mem_integralForm D x.property⟩
  left_inv x := Subtype.ext (quotientBar_quotientBar D x)
  right_inv x := Subtype.ext (quotientBar_quotientBar D x)
  map_mul' x y := Subtype.ext (map_mul (quotientBar D) (↑x) (↑y))
  map_add' x y := Subtype.ext (map_add (quotientBar D) (↑x) (↑y))

/-- The restricted radical-quotient bar squares to the identity. -/
theorem quotientIntegralBar_involutive : Function.Involutive (quotientIntegralBar D) := by
  intro x
  exact Subtype.ext (quotientBar_quotientBar D x)

/-- Semilinearity of the actual radical-quotient integral bar. -/
theorem quotientIntegralBar_smul (a : LaurentPolynomial ℤ) (x : quotientIntegralForm D) :
    quotientIntegralBar D (a • x) = LaurentPolynomial.invert a • quotientIntegralBar D x := by
  apply Subtype.ext
  change quotientBar D (algebraMap (LaurentPolynomial ℤ) _ a * ↑x) =
    algebraMap (LaurentPolynomial ℤ) _ (LaurentPolynomial.invert a) * quotientBar D ↑x
  rw [map_mul, quotientBar_integral_algebraMap]

end Radical

end LusztigF
