/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import Mathlib.FieldTheory.RatFunc.AsPolynomial
import LieLean.Algebra.QuantumGroup.LusztigF.Serre

/-!
# Lusztig's algebra over `ℚ(v)`

Lusztig works over the field `ℚ(v)` of rational functions in an indeterminate `v`
([Lus] 1.1.1–1.2.1). In Lean this is `RatFunc ℚ` with `v = RatFunc.X`, and
`'f = LusztigF (RatFunc ℚ) I = FreeAlgebra (RatFunc ℚ) I`. The results of the other files are
stated for any field `k` and `v ∈ k`; here we discharge their hypotheses (`v ≠ 0`, `v` not a root
of unity) for `v = RatFunc.X`.

## Main results

* `LusztigF.ratFunc_X_pow_ne_one`: `vⁿ ≠ 1` for `n > 0` in `ℚ(v)`.
* `LusztigF.serreIdeal_le_radical_ratFunc`: [Lus] Prop. 1.4.3 over `ℚ(v)`.

## References

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, §1.
-/

open LieLean

namespace LusztigF

/-- The indeterminate `v ∈ ℚ(v)` is not a root of unity. -/
theorem ratFunc_X_pow_ne_one {K : Type*} [Field K] {n : ℕ} (hn : 0 < n) :
    (RatFunc.X : RatFunc K) ^ n ≠ 1 := by
  intro h
  rw [← RatFunc.algebraMap_X, ← map_pow, ← map_one (algebraMap (Polynomial K) (RatFunc K))] at h
  have := congr_arg Polynomial.natDegree (RatFunc.algebraMap_injective K h)
  simp only [Polynomial.natDegree_X_pow, Polynomial.natDegree_one] at this
  omega

/-- Over `ℚ(v)`, the two-sided ideal of `'f` generated by the quantum Serre elements is contained
in the radical of Lusztig's form ([Lus] Prop. 1.4.3). -/
theorem serreIdeal_le_radical_ratFunc {I : Type*} [DecidableEq I] (D : LusztigCartanDatum I) :
    serreIdeal D (RatFunc.X : RatFunc ℚ) ≤ radical D RatFunc.X :=
  serreIdeal_le_radical RatFunc.X_ne_zero fun _ hn ↦ ratFunc_X_pow_ne_one hn

end LusztigF
