/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.LusztigF.Form
import LieLean.Algebra.QuantumGroup.QBinomial
import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# The quantum Serre relations hold in `f`

For `i ≠ j` in a Cartan datum, with `aᵢⱼ = 2 (i·j)/(i·i)` and `vᵢ = v^{dᵢ}`, the quantum Serre
element of `'f` is ([Lus] 1.4.3) `Σ_{r+s = 1-aᵢⱼ} (-1)^r θᵢ^{(s)} θⱼ θᵢ^{(r)}`, with divided powers
`θᵢ^{(n)} = θᵢⁿ/[n]ᵢ!`.
We show that it lies in the radical of Lusztig's form ([Lus] Prop. 1.4.3), so that the
two-sided ideal generated by the Serre elements is contained in the radical and the quantum Serre
relations hold in `f = 'f / radical`.

The proof: all skew derivations `rₗ` kill the Serre element and its constant term vanishes, so it
is orthogonal to everything since `(x θₗ, y) = (θₗ, θₗ)(x, rₗ(y))`. To see `rₗ(S) = 0` we apply
the algebra homomorphism `x ↦ [[x, rₗ(x)], [0, σₗ(x)]]` (`LusztigF.rMat`) and use the
additivity of Serre elements `QuantumGroup.qSerre_add` (for `l = i`) and the vanishing
`QuantumGroup.qSerre_eq_zero_of_mul_eq_smul` (for `l = j`, which is the identity [Lus] 1.3.4(a));
this argument is our own.

## Main definitions

* `LusztigF.serreElement D v i j`: the Serre element (divided-power form).
* `LusztigF.serreIdeal D v`: the two-sided ideal generated by the Serre elements, `i ≠ j`.

## Main results

* `LusztigF.rDeriv_qSerre`: `rₗ` kills the (binomial) Serre elements.
* `LusztigF.qSerre_mem_radical`, `LusztigF.serreElement_mem_radical`.
* `LusztigF.serreIdeal_le_radical`: [Lus] Prop. 1.4.3, for `v` not a root of unity.

## References

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, §1.3–1.4.
-/

open LieLean

noncomputable section

open LieLean.QuantumGroup Matrix

namespace LusztigF

variable {k I : Type*} [Field k] [DecidableEq I] (D : LusztigCartanDatum I) (v : k)

/-- The quantum Serre element `Σ_{r+s = 1-aᵢⱼ} (-1)^r θᵢ^{(s)} θⱼ θᵢ^{(r)}` of `'f`, with
divided powers taken with respect to `vᵢ = v^{dᵢ}` ([Lus] 1.4.3). -/
def serreElement (i j : I) : LusztigF k I :=
  qSerreDiv (v ^ D.d i) (1 - D.cartanMatrix i j).toNat (θ k i) (θ k j)

/-- The two-sided ideal of `'f` generated by the quantum Serre elements `serreElement D v i j`,
`i ≠ j`. -/
def serreIdeal : TwoSidedIdeal (LusztigF k I) :=
  TwoSidedIdeal.span {x | ∃ i j, i ≠ j ∧ serreElement D v i j = x}

lemma rMat_θ (l n : I) : rMat D v l (θ k n) =
    !![θ k n, if l = n then 1 else 0; 0, v ^ D.dot l n • θ k n] := by
  simp [rMat]

variable {D v}

omit [DecidableEq I] in
lemma zpow_dot_eq {i j : I} (hij : i ≠ j) {m : ℕ} (hm : (1 - D.cartanMatrix i j).toNat = m + 1) :
    v ^ D.dot i j = (v ^ D.d i)⁻¹ ^ m := by
  have hA := (D.isGeneralizedCartan_cartanMatrix).offDiag_nonpos i j hij
  have ha : D.cartanMatrix i j = -(m : ℤ) := by omega
  have h1 : D.dot i j = -((D.d i * m : ℕ) : ℤ) := by
    rw [← D.d_mul_cartanMatrix, ha]; push_cast; ring
  rw [h1, _root_.zpow_neg, zpow_natCast, pow_mul, inv_pow]

omit [DecidableEq I] in
lemma zpow_dot_self (i : I) : v ^ D.dot i i = (v ^ D.d i) ^ 2 := by
  rw [← D.two_mul_d, show (2 * (D.d i : ℤ)) = ((D.d i * 2 : ℕ) : ℤ) by push_cast; ring,
    zpow_natCast, pow_mul]

omit [DecidableEq I] in
private lemma qSerre_diagonal (ν : k) (M : ℕ) (f g : Fin 2 → LusztigF k I) :
    qSerre ν M (diagonal f) (diagonal g) = diagonal (qSerre ν M f g) := by
  have := map_qSerre (v := ν)
    (Matrix.diagonalAlgHom k : (Fin 2 → LusztigF k I) →ₐ[k] Matrix (Fin 2) (Fin 2) _) M f g
  exact this.symm

/-- The skew derivations `rₗ` kill the quantum Serre elements (binomial form). -/
theorem rDeriv_qSerre (hv : v ≠ 0) {i j : I} (hij : i ≠ j) (l : I) :
    rDeriv D v l (qSerre (v ^ D.d i) (1 - D.cartanMatrix i j).toNat (θ k i) (θ k j)) = 0 := by
  have hA := (D.isGeneralizedCartan_cartanMatrix).offDiag_nonpos i j hij
  set m := (-D.cartanMatrix i j).toNat with hm_def
  have hM : (1 - D.cartanMatrix i j).toNat = m + 1 := by omega
  have hν : v ^ D.d i ≠ 0 := pow_ne_zero _ hv
  rw [rDeriv_apply, map_qSerre, hM, rMat_θ, rMat_θ]
  by_cases hli : l = i
  · subst hli
    simp only [hij, ↓reduceIte]
    rw [zpow_dot_self, zpow_dot_eq hij hM]
    set u : Matrix (Fin 2) (Fin 2) (LusztigF k I) := diagonal ![θ k l, (v ^ D.d l) ^ 2 • θ k l]
    set w : Matrix (Fin 2) (Fin 2) (LusztigF k I) := !![0, 1; 0, 0]
    set b : Matrix (Fin 2) (Fin 2) (LusztigF k I) :=
      diagonal ![θ k j, (v ^ D.d l)⁻¹ ^ m • θ k j]
    have hU : !![θ k l, 1; 0, (v ^ D.d l) ^ 2 • θ k l] = u + w := by
      ext a c; fin_cases a <;> fin_cases c <;> simp [u, w]
    have hB : !![θ k j, 0; 0, (v ^ D.d l)⁻¹ ^ m • θ k j] = b + 0 := by
      ext a c; fin_cases a <;> fin_cases c <;> simp [b]
    have hwu : w * u = (v ^ D.d l) ^ 2 • (u * w) := by
      ext a c; fin_cases a <;> fin_cases c <;> simp [u, w, Matrix.mul_apply, Fin.sum_univ_two]
    have hwb : w * b = (v ^ D.d l)⁻¹ ^ m • (b * w) := by
      ext a c; fin_cases a <;> fin_cases c <;> simp [b, w, Matrix.mul_apply, Fin.sum_univ_two]
    rw [hU, hB, qSerre_add hν hwu hwb (by simp), qSerre_zero_right, add_zero, qSerre_diagonal,
      diagonal_apply_ne _ (by decide)]
  · by_cases hlj : l = j
    · subst hlj
      simp only [hli, ↓reduceIte]
      rw [zpow_dot_self, D.dot_comm, zpow_dot_eq hij hM]
      set u : Matrix (Fin 2) (Fin 2) (LusztigF k I) :=
        diagonal ![θ k i, (v ^ D.d i)⁻¹ ^ m • θ k i]
      set e : Matrix (Fin 2) (Fin 2) (LusztigF k I) := !![0, 1; 0, 0]
      set b : Matrix (Fin 2) (Fin 2) (LusztigF k I) := diagonal ![θ k l, (v ^ D.d l) ^ 2 • θ k l]
      have hU : !![θ k i, 0; 0, (v ^ D.d i)⁻¹ ^ m • θ k i] = u := by
        ext a c; fin_cases a <;> fin_cases c <;> simp [u]
      have hB : !![θ k l, 1; 0, (v ^ D.d l) ^ 2 • θ k l] = b + e := by
        ext a c; fin_cases a <;> fin_cases c <;> simp [b, e]
      have heu : e * u = (v ^ D.d i)⁻¹ ^ m • (u * e) := by
        ext a c; fin_cases a <;> fin_cases c <;> simp [u, e, Matrix.mul_apply, Fin.sum_univ_two]
      rw [hU, hB, qSerre_add_right, qSerre_eq_zero_of_mul_eq_smul hν heu, add_zero,
        qSerre_diagonal, diagonal_apply_ne _ (by decide)]
    · simp only [hli, hlj, ↓reduceIte]
      have hU : !![θ k i, 0; 0, v ^ D.dot l i • θ k i] =
          diagonal ![θ k i, v ^ D.dot l i • θ k i] := by
        ext a c; fin_cases a <;> fin_cases c <;> simp
      have hB : !![θ k j, 0; 0, v ^ D.dot l j • θ k j] =
          diagonal ![θ k j, v ^ D.dot l j • θ k j] := by
        ext a c; fin_cases a <;> fin_cases c <;> simp
      rw [hU, hB, qSerre_diagonal, diagonal_apply_ne _ (by decide)]

lemma lMat_θ (l n : I) : lMat D v l (θ k n) =
    !![v ^ D.dot l n • θ k n, if l = n then 1 else 0; 0, θ k n] := by
  simp [lMat]

/-- The skew derivations `ₗr` kill the quantum Serre elements (binomial form). -/
theorem lDeriv_qSerre (hv : v ≠ 0) {i j : I} (hij : i ≠ j) (l : I) :
    lDeriv D v l (qSerre (v ^ D.d i) (1 - D.cartanMatrix i j).toNat (θ k i) (θ k j)) = 0 := by
  have hA := (D.isGeneralizedCartan_cartanMatrix).offDiag_nonpos i j hij
  set m := (-D.cartanMatrix i j).toNat with hm_def
  have hM : (1 - D.cartanMatrix i j).toNat = m + 1 := by omega
  have hν : (v ^ D.d i)⁻¹ ≠ 0 := inv_ne_zero (pow_ne_zero _ hv)
  rw [lDeriv_apply, map_qSerre, hM, lMat_θ, lMat_θ, ← qSerre_inv]
  by_cases hli : l = i
  · subst hli
    simp only [hij, ↓reduceIte]
    rw [zpow_dot_self, zpow_dot_eq hij hM]
    set u : Matrix (Fin 2) (Fin 2) (LusztigF k I) := diagonal ![(v ^ D.d l) ^ 2 • θ k l, θ k l]
    set w : Matrix (Fin 2) (Fin 2) (LusztigF k I) := !![0, 1; 0, 0]
    set b : Matrix (Fin 2) (Fin 2) (LusztigF k I) :=
      diagonal ![(v ^ D.d l)⁻¹ ^ m • θ k j, θ k j]
    have hU : !![(v ^ D.d l) ^ 2 • θ k l, 1; 0, θ k l] = u + w := by
      ext a c; fin_cases a <;> fin_cases c <;> simp [u, w]
    have hB : !![(v ^ D.d l)⁻¹ ^ m • θ k j, 0; 0, θ k j] = b + 0 := by
      ext a c; fin_cases a <;> fin_cases c <;> simp [b]
    have hwu : w * u = (v ^ D.d l)⁻¹ ^ 2 • (u * w) := by
      ext a c; fin_cases a <;> fin_cases c <;>
        simp [u, w, Matrix.mul_apply, Fin.sum_univ_two, smul_smul,
          inv_mul_cancel₀ (pow_ne_zero _ (pow_ne_zero _ hv))]
    have hwb : w * b = (v ^ D.d l)⁻¹⁻¹ ^ m • (b * w) := by
      ext a c; fin_cases a <;> fin_cases c <;>
        simp [b, w, Matrix.mul_apply, Fin.sum_univ_two, smul_smul,
          mul_inv_cancel₀ (pow_ne_zero _ (pow_ne_zero _ hv))]
    rw [hU, hB, qSerre_add hν hwu hwb (by simp), qSerre_zero_right, add_zero, qSerre_diagonal,
      diagonal_apply_ne _ (by decide)]
  · by_cases hlj : l = j
    · subst hlj
      simp only [hli, ↓reduceIte]
      rw [zpow_dot_self, D.dot_comm, zpow_dot_eq hij hM]
      set u : Matrix (Fin 2) (Fin 2) (LusztigF k I) :=
        diagonal ![(v ^ D.d i)⁻¹ ^ m • θ k i, θ k i]
      set e : Matrix (Fin 2) (Fin 2) (LusztigF k I) := !![0, 1; 0, 0]
      set b : Matrix (Fin 2) (Fin 2) (LusztigF k I) := diagonal ![(v ^ D.d l) ^ 2 • θ k l, θ k l]
      have hU : !![(v ^ D.d i)⁻¹ ^ m • θ k i, 0; 0, θ k i] = u := by
        ext a c; fin_cases a <;> fin_cases c <;> simp [u]
      have hB : !![(v ^ D.d l) ^ 2 • θ k l, 1; 0, θ k l] = b + e := by
        ext a c; fin_cases a <;> fin_cases c <;> simp [b, e]
      have heu : e * u = (v ^ D.d i)⁻¹⁻¹ ^ m • (u * e) := by
        ext a c; fin_cases a <;> fin_cases c <;>
          simp [u, e, Matrix.mul_apply, Fin.sum_univ_two, smul_smul,
          mul_inv_cancel₀ (pow_ne_zero _ (pow_ne_zero _ hv))]
      rw [hU, hB, qSerre_add_right, qSerre_eq_zero_of_mul_eq_smul hν heu, add_zero,
        qSerre_diagonal, diagonal_apply_ne _ (by decide)]
    · simp only [hli, hlj, ↓reduceIte]
      have hU : !![v ^ D.dot l i • θ k i, 0; 0, θ k i] =
          diagonal ![v ^ D.dot l i • θ k i, θ k i] := by
        ext a c; fin_cases a <;> fin_cases c <;> simp
      have hB : !![v ^ D.dot l j • θ k j, 0; 0, θ k j] =
          diagonal ![v ^ D.dot l j • θ k j, θ k j] := by
        ext a c; fin_cases a <;> fin_cases c <;> simp
      rw [hU, hB, qSerre_diagonal, diagonal_apply_ne _ (by decide)]

/-- The quantum Serre elements (binomial form) lie in the radical of Lusztig's form. -/
theorem qSerre_mem_radical (hv : v ≠ 0) {i j : I} (hij : i ≠ j) :
    qSerre (v ^ D.d i) (1 - D.cartanMatrix i j).toNat (θ k i) (θ k j) ∈ radical D v := by
  rw [mem_radical_iff']
  intro y
  induction y using induction_right with
  | algebraMap c =>
    rw [form_algebraMap_left, map_qSerre, counit_θ, counit_θ, qSerre_zero_right, mul_zero]
  | smul c y hy => simp [hy]
  | add y z hy hz => simp [hy, hz]
  | mul_θ y l _ => rw [form_mul_θ, rDeriv_qSerre hv hij, map_zero, mul_zero]

/-- The quantum Serre elements lie in the radical of Lusztig's form ([Lus] Prop. 1.4.3),
provided `[1 - aᵢⱼ]ᵢ! ≠ 0`. -/
theorem serreElement_mem_radical (hv : v ≠ 0) {i j : I} (hij : i ≠ j)
    (hfact : qFactorial (v ^ D.d i) (1 - D.cartanMatrix i j).toNat ≠ 0) :
    serreElement D v i j ∈ radical D v := by
  rw [serreElement, qSerreDiv_eq hfact, Algebra.smul_def]
  exact TwoSidedIdeal.mul_mem_left _ _ _ (qSerre_mem_radical hv hij)

omit [DecidableEq I] in
lemma qFactorial_ne_zero_of_not_root (hv : v ≠ 0) (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) (i : I)
    (M : ℕ) : qFactorial (v ^ D.d i) M ≠ 0 := by
  refine qFactorial_ne_zero (pow_ne_zero _ hv) fun n hn _ ↦ ?_
  rw [← pow_mul]
  exact hv' _ (Nat.mul_pos (D.d_pos i) (by omega))

/-- The two-sided ideal generated by the quantum Serre elements is contained in the radical of
Lusztig's form ([Lus] Prop. 1.4.3), for `v` not a root of unity (e.g. `k = ℚ(v)`). -/
theorem serreIdeal_le_radical (hv : v ≠ 0) (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) :
    serreIdeal D v ≤ radical D v := by
  rw [serreIdeal, TwoSidedIdeal.span_le]
  rintro _ ⟨i, j, hij, rfl⟩
  exact serreElement_mem_radical hv hij (qFactorial_ne_zero_of_not_root hv hv' i _)

/-! ### Stability of the Serre ideal -/

omit [DecidableEq I] in
lemma diagTwist_serreElement (c : I → k) (i j : I) :
    diagTwist c (serreElement D v i j) =
      (c i ^ (1 - D.cartanMatrix i j).toNat * c j) • serreElement D v i j := by
  rw [serreElement, map_qSerreDiv, diagTwist_θ, diagTwist_θ, qSerreDiv_smul_smul]

omit [DecidableEq I] in
lemma smul_mem_serreIdeal (c : k) {x : LusztigF k I} (hx : x ∈ serreIdeal D v) :
    c • x ∈ serreIdeal D v := by
  rw [Algebra.smul_def]; exact TwoSidedIdeal.mul_mem_left _ _ _ hx

omit [DecidableEq I] in
lemma serreElement_mem_serreIdeal {i j : I} (hij : i ≠ j) :
    serreElement D v i j ∈ serreIdeal D v :=
  TwoSidedIdeal.subset_span ⟨i, j, hij, rfl⟩

omit [DecidableEq I] in
/-- Diagonal twists preserve the Serre ideal. -/
theorem diagTwist_mem_serreIdeal (c : I → k) {x : LusztigF k I} (hx : x ∈ serreIdeal D v) :
    diagTwist c x ∈ serreIdeal D v := by
  induction hx using TwoSidedIdeal.span_induction with
  | mem x hx =>
    obtain ⟨i, j, hij, rfl⟩ := hx
    rw [diagTwist_serreElement]
    exact smul_mem_serreIdeal _ (serreElement_mem_serreIdeal hij)
  | zero => simp
  | add x y _ _ hx hy => rw [map_add]; exact TwoSidedIdeal.add_mem _ hx hy
  | neg x _ hx => rw [map_neg]; exact TwoSidedIdeal.neg_mem _ hx
  | left_absorb a x _ hx => rw [map_mul]; exact TwoSidedIdeal.mul_mem_left _ _ _ hx
  | right_absorb b x _ hx => rw [map_mul]; exact TwoSidedIdeal.mul_mem_right _ _ _ hx

omit [DecidableEq I] in
lemma twist_mem_serreIdeal (l : I) {x : LusztigF k I} (hx : x ∈ serreIdeal D v) :
    twist D v l x ∈ serreIdeal D v := by
  rw [twist_eq_diagTwist]; exact diagTwist_mem_serreIdeal _ hx

omit [DecidableEq I] in
/-- The binomial Serre elements lie in the Serre ideal (when `[1 - aᵢⱼ]ᵢ! ≠ 0`). -/
lemma qSerre_mem_serreIdeal {i j : I} (hij : i ≠ j)
    (hfact : qFactorial (v ^ D.d i) (1 - D.cartanMatrix i j).toNat ≠ 0) :
    qSerre (v ^ D.d i) (1 - D.cartanMatrix i j).toNat (θ k i) (θ k j) ∈ serreIdeal D v := by
  have h := serreElement_mem_serreIdeal (D := D) (v := v) (k := k) hij
  rw [serreElement, qSerreDiv_eq hfact] at h
  have := smul_mem_serreIdeal (qFactorial (v ^ D.d i) (1 - D.cartanMatrix i j).toNat) h
  rwa [smul_smul, mul_inv_cancel₀ hfact, one_smul] at this

lemma rDeriv_serreElement (hv : v ≠ 0) {i j : I} (hij : i ≠ j)
    (hfact : qFactorial (v ^ D.d i) (1 - D.cartanMatrix i j).toNat ≠ 0) (l : I) :
    rDeriv D v l (serreElement D v i j) = 0 := by
  rw [serreElement, qSerreDiv_eq hfact, map_smul, rDeriv_qSerre hv hij, smul_zero]

lemma lDeriv_serreElement (hv : v ≠ 0) {i j : I} (hij : i ≠ j)
    (hfact : qFactorial (v ^ D.d i) (1 - D.cartanMatrix i j).toNat ≠ 0) (l : I) :
    lDeriv D v l (serreElement D v i j) = 0 := by
  rw [serreElement, qSerreDiv_eq hfact, map_smul, lDeriv_qSerre hv hij, smul_zero]

/-- The skew derivations `rₗ` preserve the Serre ideal (for `v` not a root of unity). -/
theorem rDeriv_mem_serreIdeal (hv : v ≠ 0) (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) (l : I)
    {x : LusztigF k I} (hx : x ∈ serreIdeal D v) : rDeriv D v l x ∈ serreIdeal D v := by
  induction hx using TwoSidedIdeal.span_induction with
  | mem x hx =>
    obtain ⟨i, j, hij, rfl⟩ := hx
    rw [rDeriv_serreElement hv hij (qFactorial_ne_zero_of_not_root hv hv' i _)]
    exact (serreIdeal D v).zero_mem
  | zero => simp
  | add x y _ _ hx hy => rw [map_add]; exact TwoSidedIdeal.add_mem _ hx hy
  | neg x _ hx => rw [map_neg]; exact TwoSidedIdeal.neg_mem _ hx
  | left_absorb a x hx' hx =>
    rw [rDeriv_mul]
    exact TwoSidedIdeal.add_mem _ (TwoSidedIdeal.mul_mem_left _ _ _ hx)
      (TwoSidedIdeal.mul_mem_left _ _ _ (twist_mem_serreIdeal l hx'))
  | right_absorb b x hx' hx =>
    rw [rDeriv_mul]
    exact TwoSidedIdeal.add_mem _ (TwoSidedIdeal.mul_mem_right _ _ _ hx')
      (TwoSidedIdeal.mul_mem_right _ _ _ hx)

/-- The skew derivations `ₗr` preserve the Serre ideal (for `v` not a root of unity). -/
theorem lDeriv_mem_serreIdeal (hv : v ≠ 0) (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) (l : I)
    {x : LusztigF k I} (hx : x ∈ serreIdeal D v) : lDeriv D v l x ∈ serreIdeal D v := by
  induction hx using TwoSidedIdeal.span_induction with
  | mem x hx =>
    obtain ⟨i, j, hij, rfl⟩ := hx
    rw [lDeriv_serreElement hv hij (qFactorial_ne_zero_of_not_root hv hv' i _)]
    exact (serreIdeal D v).zero_mem
  | zero => simp
  | add x y _ _ hx hy => rw [map_add]; exact TwoSidedIdeal.add_mem _ hx hy
  | neg x _ hx => rw [map_neg]; exact TwoSidedIdeal.neg_mem _ hx
  | left_absorb a x hx' hx =>
    rw [lDeriv_mul]
    exact TwoSidedIdeal.add_mem _ (TwoSidedIdeal.mul_mem_left _ _ _ hx')
      (TwoSidedIdeal.mul_mem_left _ _ _ hx)
  | right_absorb b x hx' hx =>
    rw [lDeriv_mul]
    exact TwoSidedIdeal.add_mem _ (TwoSidedIdeal.mul_mem_right _ _ _ hx)
      (TwoSidedIdeal.mul_mem_right _ _ _ (twist_mem_serreIdeal l hx'))

omit [DecidableEq I] in
/-- Elements of the Serre ideal have no constant term. -/
theorem counit_eq_zero_of_mem_serreIdeal {x : LusztigF k I} (hx : x ∈ serreIdeal D v) :
    counit x = 0 := by
  induction hx using TwoSidedIdeal.span_induction with
  | mem x hx =>
    obtain ⟨i, j, hij, rfl⟩ := hx
    rw [serreElement, map_qSerreDiv, counit_θ, counit_θ, qSerreDiv_zero_right]
  | zero => simp
  | add x y _ _ hx hy => rw [map_add, hx, hy, add_zero]
  | neg x _ hx => rw [map_neg, hx, neg_zero]
  | left_absorb a x _ hx => rw [map_mul, hx, mul_zero]
  | right_absorb b x _ hx => rw [map_mul, hx, zero_mul]

end LusztigF
