/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.KacMoody.VermaHom
import LieLean.Algebra.Lie.KacMoody.CharacterFormula.Orbit
import LieLean.GroupTheory.Coxeter.Squares

/-!
# Verma's theorem: embeddings of Verma modules along the Bruhat order

Let `𝔤 = 𝔤(A)` be the Kac–Moody algebra of a realization of a generalized Cartan matrix `A` over
a field `K` of characteristic zero, `W` its Weyl group with the Coxeter system of fundamental
reflections, and `w · λ = w(λ + ρ) - ρ` the dot action. For a dominant integral weight `Λ` we
prove the "Bruhat ⇒ embedding" direction of Verma's theorem: if `w ≤ w'` in the Bruhat order,
then `M(w' · Λ)` embeds into `M(w · Λ)` ([HumO] Thm. 4.6, Thm. 5.1 (a), §5.2; [Kum] Thm. 9.2.3 (a)).

## Main definitions

* `Matrix.Realization.weylDot`: the dot action `w · λ = w(λ + ρ) - ρ`.
* `Matrix.Realization.KacMoodyAlgebra.VermaModule.reflectionHom`: for `⟨λ + ρ, αᵢ^∨⟩ = n > 0`,
  the embedding `M(rᵢ · λ) ↪ M(λ)`, `v ↦ fᵢⁿ v_λ`.

## Main results

* `Matrix.Realization.exists_apply_add_rho_coroot_eq_of_not_isLeftDescent`: for `Λ` dominant
  integral and `ℓ(rᵢ w) > ℓ(w)`, `⟨w(Λ + ρ), αᵢ^∨⟩` is a positive integer (and it is a negative
  integer if `ℓ(rᵢ w) < ℓ(w)`).
* `Matrix.Realization.KacMoodyAlgebra.VermaModule.mem_range_reflectionHom`: if
  `⟨λ + ρ, αᵢ^∨⟩ ∈ ℤ_{>0}` and `⟨ν, αᵢ^∨⟩ ∉ ℕ`, every primitive vector of weight `ν` of `M(λ)`
  lies in `M(rᵢ · λ)`; hence (`bijective_reflectionHom_comp`) composition with
  `M(rᵢ · λ) ↪ M(λ)` is a bijection `Hom(M(ν), M(rᵢ · λ)) ≃ Hom(M(ν), M(λ))`.
* `Matrix.Realization.KacMoodyAlgebra.VermaModule.exists_comp_reflectionHom_eq`: **Verma's
  lemma** ([HumO] Prop. 4.5 (b)): if `⟨μ + ρ, αᵢ^∨⟩, ⟨μ' + ρ, αᵢ^∨⟩ ∈ ℤ_{>0}` and
  `φ : M(μ') → M(μ)` is nonzero, there is a nonzero `ψ : M(rᵢ · μ') → M(rᵢ · μ)` making the
  square with the embeddings `M(rᵢ · μ) ↪ M(μ)`, `M(rᵢ · μ') ↪ M(μ')` commute.
* `Matrix.Realization.KacMoodyAlgebra.VermaModule.exists_injective_simple_mul`: for `Λ` dominant
  integral and `ℓ(rᵢ w) > ℓ(w)`, `M(rᵢ w · Λ) ↪ M(w · Λ)`, and
  `finrank_hom_simple_mul`: this space of homomorphisms is one-dimensional.
* `Matrix.Realization.KacMoodyAlgebra.VermaModule.exists_injective_of_bruhatLE`: **Verma's
  theorem** ([HumO] Thm. 4.6, Thm. 5.1 (a), §5.2): for `Λ` dominant integral and
  `w ≤ w'` in the Bruhat
  order, there is an embedding `M(w' · Λ) ↪ M(w · Λ)`.

## Proofs

`mem_range_reflectionHom`: the quotient `M(λ) / M(rᵢ · λ)` is generated by the image of `v_λ`,
which is killed by `fᵢⁿ`, so `fᵢ` acts locally nilpotently on it (`ad fᵢ` is locally nilpotent
on `𝔤(A)`). The image of a primitive vector of weight `ν` is then a primitive vector for the
`𝔰𝔩₂`-triple `(αᵢ^∨, eᵢ, fᵢ)` on which `fᵢ` is nilpotent, so it vanishes unless
`⟨ν, αᵢ^∨⟩ ∈ ℕ`. Verma's lemma follows by applying this to the primitive vector
`φ(fᵢ^{n'} v_{μ'})` of weight `rᵢ · μ'`, as `⟨rᵢ · μ', αᵢ^∨⟩ = -n' - 1`; this argument is the one
of [HumO] §4.5 without the use of `U(𝔫₋)` being Ore, and was reconstructed by us.
Verma's theorem then follows by induction on `ℓ(w')`, using a left descent `s` of `w'` and the
lifting property of the Bruhat order: if `s w < w` then `s w ≤ s w'` and Verma's lemma applies to
`M(s w' · Λ) ↪ M(s w · Λ)`; otherwise `w ≤ s w'` and `M(w' · Λ) ↪ M(s w' · Λ) ↪ M(w · Λ)`.

## Remark

The converse ("embedding ⇒ Bruhat") and the uniqueness `dim Hom(M(w' · Λ), M(w · Λ)) ≤ 1` are not
proved here (see `LieLean.Algebra.Lie.KacMoody.VermaHom`).

## References

* [HumO] J. E. Humphreys, *Representations of semisimple Lie algebras in the BGG category 𝒪*,
  GSM 94, AMS 2008, §1.4, §1.8, §4.2–4.6, §5.1–5.2.
* [Kum] S. Kumar, *Kac–Moody groups, their flag varieties and representation theory*, Progr.
  Math. 204, Birkhäuser 2002, §9.2 (Lemmas 9.2.5–9.2.6, Thm. 9.2.3).
* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, §3.12, §9.
-/

open Module LieModule CoxeterSystem

noncomputable section

namespace Matrix.Realization

variable {ι K H : Type*} [Fintype ι] [Field K] [AddCommGroup H] [Module K H]
  {A : Matrix ι ι ℤ} (P : Realization A K H) (hA : A.IsGeneralizedCartan)

/-! ### The dot action -/

/-- The dot action `w · λ = w(λ + ρ) - ρ` of the Weyl group on `𝔥*` ([Kum] Def. 1.3.1;
[HumO] §1.8). It does not depend on the choice of `ρ`. -/
def weylDot (w : P.weylGroup hA) (μ : Dual K H) : Dual K H :=
  (w : Dual K H ≃ₗ[K] Dual K H) (μ + P.rho) - P.rho

lemma weylDot_add_rho (w : P.weylGroup hA) (μ : Dual K H) :
    P.weylDot hA w μ + P.rho = (w : Dual K H ≃ₗ[K] Dual K H) (μ + P.rho) :=
  sub_add_cancel _ _

@[simp] lemma weylDot_one (μ : Dual K H) : P.weylDot hA 1 μ = μ := by
  simp [weylDot]

lemma weylDot_mul (v w : P.weylGroup hA) (μ : Dual K H) :
    P.weylDot hA (v * w) μ = P.weylDot hA v (P.weylDot hA w μ) := by
  rw [weylDot, weylDot, weylDot_add_rho, Subgroup.coe_mul, LinearEquiv.mul_apply]

variable [DecidableEq ι] [CharZero K]

lemma weylDot_simple_mul (i : ι) (w : P.weylGroup hA) (μ : Dual K H) :
    P.weylDot hA ((P.coxeterSystem hA).simple i * w) μ =
      P.reflection hA i (P.weylDot hA w μ + P.rho) - P.rho := by
  rw [weylDot_mul, weylDot, coxeterSystem_simple]

/-! ### The integers `⟨w(Λ + ρ), αᵢ^∨⟩` -/

/-- For a regular dominant integral `μ` (`⟨μ, αⱼ^∨⟩ ∈ ℤ_{>0}`) and `ℓ(rᵢ w) > ℓ(w)`,
`⟨w μ, αᵢ^∨⟩` is a positive integer ([Kac] Lemma 3.11 (a), Prop. 3.12 (d)). Indeed, `w⁻¹αᵢ` is a
positive root, and `μ - (w⁻¹ rᵢ w) μ = ⟨w μ, αᵢ^∨⟩ w⁻¹ αᵢ` lies in `Q₊ \ 0`. -/
theorem exists_apply_coroot_eq_of_not_isLeftDescent {μ : Dual K H}
    (hμ : ∀ j, ∃ n : ℕ, μ (P.coroot j) = n + 1) {w : P.weylGroup hA} {i : ι}
    (hw : ¬(P.coxeterSystem hA).IsLeftDescent w i) :
    ∃ n : ℕ, 0 < n ∧ (w : Dual K H ≃ₗ[K] Dual K H) μ (P.coroot i) = n := by
  classical
  set cs := P.coxeterSystem hA
  have hdom : ∀ j, ∃ n : ℕ, μ (P.coroot j) = n := fun j ↦ by
    obtain ⟨n, hn⟩ := hμ j
    exact ⟨n + 1, by rw [hn]; push_cast; rfl⟩
  -- integrality
  obtain ⟨k, hk⟩ := P.exists_apply_eq_add_rootOf hA w.2 (μ := μ) fun j ↦ by
    obtain ⟨n, hn⟩ := hdom j
    exact ⟨n, by rw [hn]; norm_cast⟩
  obtain ⟨nᵢ, hnᵢ⟩ := hdom i
  set z : ℤ := nᵢ + (A *ᵥ k) i
  have hc : (w : Dual K H ≃ₗ[K] Dual K H) μ (P.coroot i) = z := by
    rw [hk, LinearMap.add_apply, hnᵢ, rootOf_apply_coroot]
    push_cast [z]
    rfl
  -- positivity
  have hw' : ¬cs.IsRightDescent w⁻¹ i := by rwa [cs.isRightDescent_inv_iff]
  obtain ⟨l, hl, hwl⟩ := (P.not_isRightDescent_coxeterSystem_iff hA).mp hw'
  set v := w⁻¹ * cs.simple i * w
  obtain ⟨m, hm, hvm⟩ := P.exists_sub_apply_eq_rootOf hA hdom v
  have hv : (v : Dual K H ≃ₗ[K] Dual K H) μ = μ - (z : K) • P.rootOf l := by
    simp only [v, Subgroup.coe_mul, LinearEquiv.mul_apply, coxeterSystem_simple, cs]
    rw [reflection_apply, hc, map_sub, map_smul, hwl]
    congr 1
    exact (w : Dual K H ≃ₗ[K] Dual K H).symm_apply_apply μ
  have h2 : P.rootOf (z • l) = (z : K) • P.rootOf l := by
    rw [map_zsmul, ← Int.cast_smul_eq_zsmul K]
  rw [hv, sub_sub_cancel, ← h2] at hvm
  have hml : z • l = m := P.rootOf_injective hvm
  have hl0 : l ≠ 0 := by
    rintro rfl
    rw [map_zero, LinearEquiv.map_eq_zero_iff] at hwl
    exact P.linearIndependent_root.ne_zero i hwl
  obtain ⟨j, hj⟩ : ∃ j, l j ≠ 0 := by
    by_contra! h
    exact hl0 (funext h)
  have hlj : 0 < l j := lt_of_le_of_ne (hl j) (Ne.symm hj)
  have hz0 : 0 ≤ z := by
    have h1 := congrFun hml j
    have h2 := hm j
    simp only [Pi.smul_apply, smul_eq_mul, Pi.zero_apply] at h1 h2
    nlinarith
  have hz : z ≠ 0 := by
    intro hz
    have hv1 : v ≠ 1 := by
      intro hv1
      have : cs.simple i = 1 := by
        have := congrArg (fun x ↦ w * x * w⁻¹) hv1
        simpa [v, mul_assoc] using this
      have hr : (((P.coxeterSystem hA).simple i : P.weylGroup hA) :
          Dual K H ≃ₗ[K] Dual K H) (P.root i) = P.root i := by
        rw [this]; rfl
      rw [coxeterSystem_simple, reflection_root_self] at hr
      exact P.linearIndependent_root.ne_zero i (by
        have : (2 : K) • P.root i = 0 := by rw [two_smul]; nth_rw 1 [← hr]; exact neg_add_cancel _
        exact (smul_eq_zero.mp this).resolve_left two_ne_zero)
    exact P.apply_ne_self_of_regular hA hμ hv1 (by rw [hv, hz, Int.cast_zero, zero_smul, sub_zero])
  refine ⟨z.toNat, by omega, ?_⟩
  rw [hc]
  exact_mod_cast (Int.toNat_of_nonneg hz0).symm

/-- For a regular dominant integral `μ` and `ℓ(rᵢ w) < ℓ(w)`, `⟨w μ, αᵢ^∨⟩` is a negative
integer. -/
theorem exists_apply_coroot_eq_neg_of_isLeftDescent {μ : Dual K H}
    (hμ : ∀ j, ∃ n : ℕ, μ (P.coroot j) = n + 1) {w : P.weylGroup hA} {i : ι}
    (hw : (P.coxeterSystem hA).IsLeftDescent w i) :
    ∃ n : ℕ, 0 < n ∧ (w : Dual K H ≃ₗ[K] Dual K H) μ (P.coroot i) = -n := by
  set cs := P.coxeterSystem hA
  have hw' : ¬cs.IsLeftDescent (cs.simple i * w) i := by
    rwa [← cs.isLeftDescent_iff_not_isLeftDescent_mul]
  obtain ⟨n, hn0, hn⟩ := P.exists_apply_coroot_eq_of_not_isLeftDescent hA hμ hw'
  refine ⟨n, hn0, ?_⟩
  have : w = cs.simple i * (cs.simple i * w) := (cs.simple_mul_simple_cancel_left i).symm
  rw [this, Subgroup.coe_mul, LinearEquiv.mul_apply, coxeterSystem_simple, reflection_apply,
    LinearMap.sub_apply, LinearMap.smul_apply, hn, root_coroot_self P hA, smul_eq_mul]
  ring

omit [DecidableEq ι] [CharZero K] in
/-- `Λ + ρ` is regular dominant integral if `Λ` is dominant integral. -/
lemma add_rho_regular {Λ : Dual K H} (hΛ : P.IsDominantIntegral Λ) :
    ∀ j, ∃ n : ℕ, (Λ + P.rho) (P.coroot j) = n + 1 := fun j ↦ by
  obtain ⟨n, hn⟩ := hΛ j
  exact ⟨n, by rw [LinearMap.add_apply, hn, rho_coroot]⟩

/-- For `Λ` dominant integral and `ℓ(rᵢ w) > ℓ(w)`, `⟨w · Λ + ρ, αᵢ^∨⟩ = ⟨w(Λ + ρ), αᵢ^∨⟩` is a
positive integer. -/
theorem exists_weylDot_add_rho_coroot_eq {Λ : Dual K H} (hΛ : P.IsDominantIntegral Λ)
    {w : P.weylGroup hA} {i : ι} (hw : ¬(P.coxeterSystem hA).IsLeftDescent w i) :
    ∃ n : ℕ, 0 < n ∧ (P.weylDot hA w Λ + P.rho) (P.coroot i) = n := by
  classical
  rw [weylDot_add_rho]
  exact P.exists_apply_coroot_eq_of_not_isLeftDescent hA (P.add_rho_regular hΛ) hw

namespace KacMoodyAlgebra

namespace VermaModule

variable {P}

/-! ### The embeddings `M(rᵢ · λ) ↪ M(λ)` -/

variable {Λ : Dual K H} {i : ι} {n : ℕ} (hn0 : 0 < n) (hn : (Λ + P.rho) (P.coroot i) = n)

/-- The embedding `M(rᵢ · λ) ↪ M(λ)` sending `v_{rᵢ · λ}` to `fᵢⁿ v_λ`, where
`n = ⟨λ + ρ, αᵢ^∨⟩ > 0` ([HumO] §1.4). -/
def reflectionHom :
    VermaModule P (P.reflection hA i (Λ + P.rho) - P.rho) →ₗ⁅K,P.KacMoodyAlgebra⁆
      VermaModule P Λ :=
  (homEquiv P (VermaModule P Λ) _).symm ⟨_, toEnd_f_pow_hwv_mem_primitiveVectors P hA hn0 hn⟩

lemma reflectionHom_hwv :
    reflectionHom hA hn0 hn (hwv P _) =
      (toEnd K P.KacMoodyAlgebra (VermaModule P Λ) (f P i) ^ n) (hwv P Λ) := by
  rw [reflectionHom, ← homEquiv_apply, LinearEquiv.apply_symm_apply]

lemma reflectionHom_ne_zero : reflectionHom hA hn0 hn ≠ 0 := fun h ↦
  toEnd_f_pow_hwv_ne_zero P Λ i n (by rw [← reflectionHom_hwv hA hn0 hn, h,
    _root_.zero_apply])

lemma reflectionHom_injective : Function.Injective (reflectionHom hA hn0 hn) :=
  injective_of_ne_zero P (reflectionHom_ne_zero hA hn0 hn)

/-- `fᵢ` acts locally nilpotently on `M(λ) / M(rᵢ · λ)`. -/
lemma exists_toEnd_f_pow_quotient_eq_zero (x : VermaModule P Λ ⧸ (reflectionHom hA hn0 hn).range) :
    ∃ N, (toEnd K P.KacMoodyAlgebra _ (f P i) ^ N) x = 0 := by
  set q := LieSubmodule.Quotient.mk' (reflectionHom hA hn0 hn).range
  refine exists_toEnd_pow_eq_zero_of_lieSpan (exists_ad_f_pow_eq_zero P hA i)
    (lieSpan_map_hwv_eq_top q (LieSubmodule.Quotient.surjective_mk' _)) ?_ x
  rintro _ rfl
  refine ⟨n, ?_⟩
  rw [toEnd_pow_apply_map, LieSubmodule.Quotient.mk'_apply, LieSubmodule.Quotient.mk_eq_zero',
    ← reflectionHom_hwv hA hn0 hn]
  exact ⟨_, rfl⟩

variable {V : Type*} [AddCommGroup V] [Module K V] [LieRingModule P.KacMoodyAlgebra V]
  [LieModule K P.KacMoodyAlgebra V]

omit [CharZero K] in
/-- If `g` is injective and `g z` is primitive of weight `ν`, so is `z`. -/
lemma mem_primitiveVectors_of_injective {W : Type*} [AddCommGroup W] [Module K W]
    [LieRingModule P.KacMoodyAlgebra W] [LieModule K P.KacMoodyAlgebra W]
    (g : V →ₗ⁅K,P.KacMoodyAlgebra⁆ W) (hg : Function.Injective g) {ν : Dual K H} {z : V}
    (hz : g z ∈ primitiveVectors P W ν) : z ∈ primitiveVectors P V ν := by
  rw [mem_primitiveVectors] at hz ⊢
  refine ⟨fun a ↦ hg ?_, fun j ↦ hg ?_⟩
  · rw [LieModuleHom.map_lie, hz.1 a, map_smul]
  · rw [LieModuleHom.map_lie, hz.2 j, map_zero]

include hA in
/-- A vector killed by `eᵢ`, of weight `ν` with `⟨ν, αᵢ^∨⟩ ∉ ℕ`, on which `fᵢ` acts nilpotently,
vanishes (`𝔰𝔩₂`-theory). -/
lemma eq_zero_of_lie_e_eq_zero {v : V} {ν : Dual K H} (hv : v ∈ KacMoodyAlgebra.weightSpace P V ν)
    (he : ⁅e P i, v⁆ = 0) (hν : ∀ m : ℕ, ν (P.coroot i) ≠ m)
    (hf : ∃ N, (toEnd K P.KacMoodyAlgebra V (f P i) ^ N) v = 0) : v = 0 := by
  by_contra hv0
  obtain ⟨m, hm⟩ := IsSl2Triple.HasPrimitiveVectorWith.exists_nat_of_exists_pow_eq_zero
    (t := isSl2Triple P hA i) ⟨hv0, hv (P.coroot i), he⟩ hf
  exact hν m hm

variable {hA hn0 hn} in
/-- **Primitive vectors of `M(λ)` of weight `ν` with `⟨ν, αᵢ^∨⟩ ∉ ℕ` lie in `M(rᵢ · λ)`**, for
`⟨λ + ρ, αᵢ^∨⟩ ∈ ℤ_{>0}`. (Reconstructed by us; cf. [HumO] Prop. 4.5.) -/
theorem mem_range_reflectionHom {ν : Dual K H} (hν : ∀ m : ℕ, ν (P.coroot i) ≠ m)
    {y : VermaModule P Λ} (hy : y ∈ primitiveVectors P (VermaModule P Λ) ν) :
    y ∈ (reflectionHom hA hn0 hn).range := by
  rw [← LieSubmodule.Quotient.mk_eq_zero']
  rw [mem_primitiveVectors] at hy
  refine eq_zero_of_lie_e_eq_zero hA
    (map_mem_weightSpaceOfMap P (LieSubmodule.Quotient.mk' _) hy.1) ?_ hν
    (exists_toEnd_f_pow_quotient_eq_zero hA hn0 hn _)
  rw [← LieSubmodule.Quotient.mk'_apply, ← LieModuleHom.map_lie, hy.2 i, map_zero]

variable {hA hn0 hn} in
/-- If `⟨λ + ρ, αᵢ^∨⟩ ∈ ℤ_{>0}` and `⟨ν, αᵢ^∨⟩ ∉ ℕ`, every morphism `M(ν) → M(λ)` factors through
the embedding `M(rᵢ · λ) ↪ M(λ)`. -/
theorem exists_reflectionHom_comp_eq {ν : Dual K H} (hν : ∀ m : ℕ, ν (P.coroot i) ≠ m)
    (φ : VermaModule P ν →ₗ⁅K,P.KacMoodyAlgebra⁆ VermaModule P Λ) :
    ∃ ψ, (reflectionHom hA hn0 hn).comp ψ = φ := by
  obtain ⟨z, hz⟩ := mem_range_reflectionHom hν (map_hwv_mem_primitiveVectors P φ)
  have hzp : z ∈ primitiveVectors P _ ν :=
    mem_primitiveVectors_of_injective _ (reflectionHom_injective hA hn0 hn)
      (by rw [hz]; exact map_hwv_mem_primitiveVectors P φ)
  refine ⟨(homEquiv P _ ν).symm ⟨z, hzp⟩, hom_ext P ν ?_⟩
  rw [LieModuleHom.comp_apply, ← homEquiv_apply, LinearEquiv.apply_symm_apply]
  exact hz

variable {hA hn0 hn} in
/-- If `⟨λ + ρ, αᵢ^∨⟩ ∈ ℤ_{>0}` and `⟨ν, αᵢ^∨⟩ ∉ ℕ`, composition with `M(rᵢ · λ) ↪ M(λ)` is a
bijection `Hom(M(ν), M(rᵢ · λ)) → Hom(M(ν), M(λ))`. -/
theorem bijective_reflectionHom_comp {ν : Dual K H} (hν : ∀ m : ℕ, ν (P.coroot i) ≠ m) :
    Function.Bijective fun ψ : VermaModule P ν →ₗ⁅K,P.KacMoodyAlgebra⁆
        VermaModule P (P.reflection hA i (Λ + P.rho) - P.rho) ↦
      (reflectionHom hA hn0 hn).comp ψ :=
  ⟨fun _ _ h ↦ LieModuleHom.ext fun m ↦
      reflectionHom_injective hA hn0 hn (LieModuleHom.congr_fun h m),
    fun φ ↦ exists_reflectionHom_comp_eq hν φ⟩

include hn0 hn in
/-- `dim Hom(M(ν), M(rᵢ · λ)) = dim Hom(M(ν), M(λ))` if `⟨λ + ρ, αᵢ^∨⟩ ∈ ℤ_{>0}` and
`⟨ν, αᵢ^∨⟩ ∉ ℕ`. -/
theorem finrank_hom_reflection_eq {ν : Dual K H} (hν : ∀ m : ℕ, ν (P.coroot i) ≠ m) :
    finrank K (VermaModule P ν →ₗ⁅K,P.KacMoodyAlgebra⁆
        VermaModule P (P.reflection hA i (Λ + P.rho) - P.rho)) =
      finrank K (VermaModule P ν →ₗ⁅K,P.KacMoodyAlgebra⁆ VermaModule P Λ) := by
  let e : (VermaModule P ν →ₗ⁅K,P.KacMoodyAlgebra⁆
        VermaModule P (P.reflection hA i (Λ + P.rho) - P.rho)) ≃ₗ[K]
      (VermaModule P ν →ₗ⁅K,P.KacMoodyAlgebra⁆ VermaModule P Λ) :=
    LinearEquiv.ofBijective
      { toFun := fun ψ ↦ (reflectionHom hA hn0 hn).comp ψ
        map_add' := fun _ _ ↦ LieModuleHom.ext fun _ ↦ by simp
        map_smul' := fun _ _ ↦ LieModuleHom.ext fun _ ↦ by simp }
      (bijective_reflectionHom_comp hν)
  exact e.finrank_eq

/-- **Verma's lemma** ([HumO] Prop. 4.5 (b); [Kum] Lemma 9.2.6): let `⟨μ + ρ, αᵢ^∨⟩ = n` and
`⟨μ' + ρ, αᵢ^∨⟩ = n'` be positive integers and `φ : M(μ') → M(μ)` a nonzero morphism. Then there
is a nonzero morphism `ψ : M(rᵢ · μ') → M(rᵢ · μ)` such that the square formed with the
embeddings `M(rᵢ · μ') ↪ M(μ')` and `M(rᵢ · μ) ↪ M(μ)` commutes. -/
theorem exists_comp_reflectionHom_eq {μ μ' : Dual K H} {n n' : ℕ} (hn0 : 0 < n)
    (hn : (μ + P.rho) (P.coroot i) = n) (hn0' : 0 < n') (hn' : (μ' + P.rho) (P.coroot i) = n')
    {φ : VermaModule P μ' →ₗ⁅K,P.KacMoodyAlgebra⁆ VermaModule P μ} (hφ : φ ≠ 0) :
    ∃ ψ, ψ ≠ 0 ∧ (reflectionHom hA hn0 hn).comp ψ = φ.comp (reflectionHom hA hn0' hn') := by
  have hν : ∀ m : ℕ, (P.reflection hA i (μ' + P.rho) - P.rho) (P.coroot i) ≠ m := by
    intro m hm
    rw [P.reflection_add_rho_sub_rho hA hn', LinearMap.sub_apply, LinearMap.smul_apply,
      root_coroot_self P hA, nsmul_eq_mul] at hm
    rw [LinearMap.add_apply, rho_coroot] at hn'
    have : ((m + 2 * n' + 1 : ℕ) : K) = n' := by push_cast; linear_combination hn' - hm
    have := Nat.cast_injective this
    omega
  obtain ⟨ψ, hψ⟩ := exists_reflectionHom_comp_eq (hA := hA) (hn0 := hn0) (hn := hn) hν
    (φ.comp (reflectionHom hA hn0' hn'))
  refine ⟨ψ, fun h0 ↦ ?_, hψ⟩
  have := LieModuleHom.congr_fun hψ (hwv P _)
  rw [h0, LieModuleHom.comp_apply, _root_.zero_apply, map_zero, LieModuleHom.comp_apply]
    at this
  exact reflectionHom_ne_zero hA hn0' hn' (by
    rw [eq_zero_iff]
    exact injective_of_ne_zero P hφ (by rw [← this, map_zero]))

/-! ### Verma's theorem -/

variable {Λ : Dual K H} (hΛ : P.IsDominantIntegral Λ)
include hΛ

/-- For `Λ` dominant integral and `ℓ(rᵢ w) > ℓ(w)`, there is an embedding
`M(rᵢ w · Λ) ↪ M(w · Λ)` ([HumO] Prop. 4.3; [Kum] Lemma 9.2.5, Thm. 9.2.3). -/
theorem exists_injective_simple_mul {w : P.weylGroup hA} {i : ι}
    (hw : ¬(P.coxeterSystem hA).IsLeftDescent w i) :
    ∃ φ : VermaModule P (P.weylDot hA ((P.coxeterSystem hA).simple i * w) Λ) →ₗ⁅K,
      P.KacMoodyAlgebra⁆ VermaModule P (P.weylDot hA w Λ), Function.Injective φ := by
  obtain ⟨n, hn0, hn⟩ := P.exists_weylDot_add_rho_coroot_eq hA hΛ hw
  rw [weylDot_simple_mul]
  exact ⟨reflectionHom hA hn0 hn, reflectionHom_injective hA hn0 hn⟩

/-- For `Λ` dominant integral and `ℓ(rᵢ w) > ℓ(w)`, `Hom(M(rᵢ w · Λ), M(w · Λ))` is
one-dimensional ([HumO] Thm. 4.2 (b) in this case). -/
theorem finrank_hom_simple_mul {w : P.weylGroup hA} {i : ι}
    (hw : ¬(P.coxeterSystem hA).IsLeftDescent w i) :
    finrank K (VermaModule P (P.weylDot hA ((P.coxeterSystem hA).simple i * w) Λ) →ₗ⁅K,
      P.KacMoodyAlgebra⁆ VermaModule P (P.weylDot hA w Λ)) = 1 := by
  obtain ⟨n, hn0, hn⟩ := P.exists_weylDot_add_rho_coroot_eq hA hΛ hw
  rw [weylDot_simple_mul]
  exact finrank_hom_reflection P hA hn0 hn

/-- **Verma's theorem**, "Bruhat ⇒ embedding" ([HumO] Thm. 4.6, Thm. 5.1 (a), §5.2;
[Kum] Thm. 9.2.3 (a)): for
`Λ` dominant integral and `w ≤ w'` in the Bruhat order of `W`, there is an injective morphism of
`𝔤(A)`-modules `M(w' · Λ) → M(w · Λ)`. -/
theorem exists_injective_of_bruhatLE {w w' : P.weylGroup hA}
    (h : (P.coxeterSystem hA).BruhatLE w w') :
    ∃ φ : VermaModule P (P.weylDot hA w' Λ) →ₗ⁅K,P.KacMoodyAlgebra⁆
      VermaModule P (P.weylDot hA w Λ), Function.Injective φ := by
  set cs := P.coxeterSystem hA
  induction hl : cs.length w' using Nat.strong_induction_on generalizing w w' with
  | _ l ih =>
  subst hl
  by_cases hw'1 : w' = 1
  · subst hw'1
    have : w = 1 := h.eq_of_length_le (by simp)
    subst this
    exact ⟨LieModuleHom.id, Function.injective_id⟩
  obtain ⟨i, hi⟩ := cs.exists_leftDescent_of_ne_one hw'1
  have hil := (cs.isLeftDescent_iff).mp hi
  have hsw' : ¬cs.IsLeftDescent (cs.simple i * w') i := by
    rwa [← cs.isLeftDescent_iff_not_isLeftDescent_mul]
  by_cases hw : cs.IsLeftDescent w i
  · have hsw : ¬cs.IsLeftDescent (cs.simple i * w) i := by
      rwa [← cs.isLeftDescent_iff_not_isLeftDescent_mul]
    obtain ⟨φ, hφ⟩ := ih _ (by omega) ((simple_mul_bruhatLE_simple_mul_iff hw hi).mpr h) rfl
    obtain ⟨n, hn0, hn⟩ := P.exists_weylDot_add_rho_coroot_eq hA hΛ hsw
    obtain ⟨n', hn0', hn'⟩ := P.exists_weylDot_add_rho_coroot_eq hA hΛ hsw'
    have hφ0 : φ ≠ 0 := fun h0 ↦ hwv_ne_zero P _ (hφ (by rw [h0, map_zero,
      _root_.zero_apply]))
    obtain ⟨ψ, hψ0, -⟩ := exists_comp_reflectionHom_eq hA hn0 hn hn0' hn' hφ0
    have e₁ : P.weylDot hA w Λ =
        P.reflection hA i (P.weylDot hA (cs.simple i * w) Λ + P.rho) - P.rho := by
      rw [← weylDot_simple_mul, simple_mul_simple_cancel_left]
    have e₂ : P.weylDot hA w' Λ =
        P.reflection hA i (P.weylDot hA (cs.simple i * w') Λ + P.rho) - P.rho := by
      rw [← weylDot_simple_mul, simple_mul_simple_cancel_left]
    rw [e₁, e₂]
    exact ⟨ψ, injective_of_ne_zero P hψ0⟩
  · have h' := (h.lifting_left hi hw).1
    obtain ⟨φ, hφ⟩ := ih _ (by omega) h' rfl
    have := exists_injective_simple_mul hA hΛ hsw'
    rw [simple_mul_simple_cancel_left] at this
    obtain ⟨ψ, hψ⟩ := this
    exact ⟨φ.comp ψ, hφ.comp hψ⟩

end VermaModule

end KacMoodyAlgebra

end Matrix.Realization
