/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.CrystalBasis.Boson
import LieLean.Algebra.QuantumGroup.Faithful

/-!
# Kashiwara operators on `U⁻`

Let `(I, ·)` be a Cartan datum, `k` a field and `v ∈ k` nonzero and not a root of unity. We model
`U⁻` by `'f ⧸ J` (`QuantumGroup.NegativePart`), where `'f` is Lusztig's free algebra and `J` the
quantum Serre ideal; `y ↦ y⁻` identifies it with the subalgebra of `U` generated by the `Fᵢ`
(`QuantumGroup.minusHom_eq_zero_iff`).

For `i ∈ I` let `fᵢ` be left multiplication by `θᵢ` and `e'ᵢ = ᵢr`, Lusztig's left skew
derivation ([Lus] 1.2.13: `ᵢr(θⱼ x) = δᵢⱼ x + v^{i·j} θⱼ ᵢr(x)`). On `'f` (and hence on `U⁻`) these
satisfy the relation of the `q`-boson algebra at `q = vᵢ⁻¹`: `e'ᵢ fᵢ = vᵢ² fᵢ e'ᵢ + 1`
(`LusztigF.bosonE_bosonF`); `e'ᵢ` lowers the weight by `i` and is locally nilpotent. This is
Kashiwara's boson algebra action ([HK] (6.13), [Jan] 10.1–10.2) in the normalization of this
library, where crystal lattices are taken at `v = ∞`: for `y ∈ 'f` and dominant `λ`,
`Eᵢ (y⁻ v_λ) = (vᵢ - vᵢ⁻¹)⁻¹ (vᵢ^{⟨i,λ⟩} (σᵢ⁻¹ ᵢr(y))⁻ v_λ - vᵢ^{-⟨i,λ⟩} (rᵢ y)⁻ v_λ)`
(`QuantumGroup.vermaOpQ`), so for `⟨i, λ⟩ ≫ 0` it is the kernel of `ᵢr` that controls the
`i`-strings of `U⁻ v_λ`. (In Kashiwara's normalization, with lattices at `q = 0`, the corresponding
operator is the coefficient of `tᵢ⁻¹`, which becomes `ᵢr` under `q ↦ v⁻¹`.)

The Kashiwara operators `ẽᵢ`, `f̃ᵢ` on `U⁻` (`QuantumGroup.NegativePart.kashiwaraE`,
`kashiwaraF`) are those of the `q`-boson module (`QuantumGroup.BosonModule`):
`ẽᵢ (Σ fᵢ^{(n)} uₙ) = Σ fᵢ^{(n-1)} uₙ`, `f̃ᵢ (Σ fᵢ^{(n)} uₙ) = Σ fᵢ^{(n+1)} uₙ` with `e'ᵢ uₙ = 0`.
They are homogeneous of weights `-i` and `i`. Given a commutative ring `A` acting on `U⁻`
compatibly with `k` and `c ∈ A`, `L(∞)` is the `A`-span of the `f̃_{i₁} ⋯ f̃_{iᵣ} 1` and `B(∞)`
the set of their nonzero classes in `L(∞)/c L(∞)` ([Kas] §8, [Jan] 10.3).

## Main definitions

* `QuantumGroup.NegativePart D v`: `U⁻ = 'f ⧸ J`.
* `LusztigF.bosonE`, `LusztigF.bosonF`: `e'ᵢ`, `fᵢ` on `'f`.
* `QuantumGroup.NegativePart.boson`: the `q`-boson module structure on `U⁻` at `i`.
* `QuantumGroup.NegativePart.kashiwaraE`, `kashiwaraF`: Kashiwara's operators on `U⁻`.
* `QuantumGroup.NegativePart.weightSpace ν`: `U⁻_{-ν}` (indexed by `ν ∈ ℕ[I]`).
* `QuantumGroup.NegativePart.fWord`: `f̃_{i₁} ⋯ f̃_{iᵣ} 1`; `QuantumGroup.NegativePart.latticeInf`,
  `QuantumGroup.NegativePart.baseInf`: `L(∞)`, `B(∞)`.

## Main results

* `LusztigF.bosonE_bosonF`: `e'ᵢ fᵢ = vᵢ² fᵢ e'ᵢ + 1`.
* `QuantumGroup.NegativePart.kashiwaraE_mem_weightSpace`,
  `QuantumGroup.NegativePart.kashiwaraF_mem_weightSpace`: homogeneity.
* `QuantumGroup.NegativePart.kashiwaraE_kashiwaraF`: `ẽᵢ f̃ᵢ = 1`.
* `QuantumGroup.NegativePart.kashiwaraF_mem_latticeInf`, `fWord_mem_weightSpace`.

## References

* [Kas] M. Kashiwara, *On crystal bases*, CMS Conf. Proc. 16 (1995), §8.
* [HK] J. Hong, S.-J. Kang, *Introduction to quantum groups and crystal bases*, GSM 42, §6.3.
* [Jan] J. C. Jantzen, *Lectures on quantum groups*, GSM 6, Ch. 10.
* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, §1.2.
-/

open LieLean Finset

noncomputable section

namespace LusztigF

variable {k I : Type*} [Field k]

/-! ### Diagonal twists preserve weight spaces -/

lemma diagTwist_mem_weightSpace (c : I → k) {ν : I →₀ ℕ} {x : LusztigF k I}
    (hx : x ∈ weightSpace k ν) : diagTwist c x ∈ weightSpace k ν := by
  induction hx using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨w, rfl, rfl⟩ := hy
    induction w with
    | nil => simpa [monomial] using one_mem_weightSpace
    | cons l w ih =>
      rw [monomial_cons, map_mul, diagTwist_θ, smul_mul_assoc, wordWeight_cons]
      exact Submodule.smul_mem _ _ (mul_mem_weightSpace (θ_mem_weightSpace l) ih)
  | zero => simp
  | add y z _ _ hy hz => rw [map_add]; exact Submodule.add_mem _ hy hz
  | smul c y _ hy => rw [map_smul]; exact Submodule.smul_mem _ _ hy

/-! ### Integer-indexed weight projections -/

/-- The element of `ℤ[I]` of `ν ∈ ℕ[I]`. -/
def toZ (ν : I →₀ ℕ) : I →₀ ℤ := Finsupp.mapRange (fun n : ℕ ↦ (n : ℤ)) (by simp) ν

lemma toZ_injective : Function.Injective (toZ (I := I)) := fun ν μ h ↦ by
  ext i
  have := congr($h i)
  simpa [toZ] using this

@[simp] lemma toZ_apply (ν : I →₀ ℕ) (i : I) : toZ ν i = ν i := by simp [toZ]

lemma toZ_add (ν μ : I →₀ ℕ) : toZ (ν + μ) = toZ ν + toZ μ := by
  ext i; simp

lemma toZ_single (i : I) (n : ℕ) : toZ (Finsupp.single i n) = Finsupp.single i (n : ℤ) := by
  classical
  ext j
  rw [toZ_apply, Finsupp.single_apply, Finsupp.single_apply]
  split_ifs <;> simp

lemma nonneg_toZ (ν : I →₀ ℕ) : 0 ≤ toZ ν := fun i ↦ by simp

/-- The truncation `ℤ[I] → ℕ[I]`. -/
def ofZ (γ : I →₀ ℤ) : I →₀ ℕ := Finsupp.mapRange Int.toNat (by simp) γ

lemma ofZ_toZ (ν : I →₀ ℕ) : ofZ (toZ ν) = ν := by ext i; simp [ofZ]

lemma toZ_ofZ {γ : I →₀ ℤ} (hγ : 0 ≤ γ) : toZ (ofZ γ) = γ := by
  ext i; simp [ofZ, Int.toNat_of_nonneg (hγ i)]

variable (k) in
/-- The projection of `'f` onto `'f_ν` if `γ = ν ∈ ℕ[I]`, and `0` if `γ ∉ ℕ[I]`. -/
def zWeightProj (γ : I →₀ ℤ) : LusztigF k I →ₗ[k] LusztigF k I :=
  open scoped Classical in if 0 ≤ γ then weightProj (ofZ γ) else 0

open scoped Classical in
lemma zWeightProj_of_mem {ν : I →₀ ℕ} {x : LusztigF k I} (hx : x ∈ weightSpace k ν)
    (γ : I →₀ ℤ) : zWeightProj k γ x = if toZ ν = γ then x else 0 := by
  unfold zWeightProj
  by_cases h1 : 0 ≤ γ
  · rw [ite_eq_left h1, weightProj_of_mem hx]
    by_cases h2 : toZ ν = γ
    · rw [ite_eq_left (by rw [← h2, ofZ_toZ]), ite_eq_left h2]
    · rw [ite_eq_right (fun h ↦ h2 (by rw [h, toZ_ofZ h1])), ite_eq_right h2]
  · rw [ite_eq_right h1, ite_eq_right (fun (h2 : toZ ν = γ) ↦ h1 (h2 ▸ nonneg_toZ ν))]
    rfl

/-- Two linear maps out of `'f` agreeing on all weight spaces are equal. -/
lemma ext_weightSpace {N : Type*} [AddCommGroup N] [Module k N] {φ ψ : LusztigF k I →ₗ[k] N}
    (h : ∀ ν, ∀ x ∈ weightSpace k ν, φ x = ψ x) : φ = ψ := by
  ext x
  have hx : x ∈ ⨆ ν, weightSpace k (I := I) ν := by rw [iSup_weightSpace]; trivial
  induction hx using Submodule.iSup_induction' with
  | mem ν x hx => exact h ν x hx
  | zero => simp
  | add x y _ _ hx hy => rw [map_add, map_add, hx, hy]

lemma zWeightProj_θ_mul (i : I) (γ : I →₀ ℤ) (x : LusztigF k I) :
    zWeightProj k γ (θ k i * x) = θ k i * zWeightProj k (γ - Finsupp.single i 1) x := by
  classical
  have := ext_weightSpace (φ := zWeightProj k γ ∘ₗ LinearMap.mulLeft k (θ k i))
    (ψ := LinearMap.mulLeft k (θ k i) ∘ₗ zWeightProj k (γ - Finsupp.single i 1)) fun ν x hx ↦ by
    have hθx : θ k i * x ∈ weightSpace k (Finsupp.single i 1 + ν) :=
      mul_mem_weightSpace (θ_mem_weightSpace i) hx
    simp only [LinearMap.comp_apply, LinearMap.mulLeft_apply, zWeightProj_of_mem hθx,
      zWeightProj_of_mem hx]
    rw [toZ_add, toZ_single, Nat.cast_one]
    by_cases h : Finsupp.single i (1 : ℤ) + toZ ν = γ
    · rw [ite_eq_left h, ite_eq_left (by rw [← h]; abel)]
    · rw [ite_eq_right h, ite_eq_right (fun h' ↦ h (by rw [h']; abel)), mul_zero]
  exact congr($this x)

/-! ### The boson operators on `'f` -/

variable [DecidableEq I] (D : LusztigCartanDatum I) (v : k)

lemma lDeriv_monomial_eq_zero (i : I) (w : List I) (hw : wordWeight w i = 0) :
    lDeriv D v i (monomial k w) = 0 := by
  induction w with
  | nil => simp
  | cons l w ih =>
    have hl : l ≠ i := by
      rintro rfl; simp at hw
    have hw' : wordWeight w i = 0 := by
      simp only [wordWeight_cons, Finsupp.add_apply] at hw; omega
    rw [monomial_cons, lDeriv_θ_mul, ih hw']
    simp [Ne.symm hl]

lemma lDeriv_monomial_mem (i : I) (w : List I) :
    ∀ μ, wordWeight w = μ + Finsupp.single i 1 →
      lDeriv D v i (monomial k w) ∈ weightSpace k μ := by
  induction w with
  | nil =>
    intro μ h
    have := congr($h i)
    simp at this
  | cons l w ih =>
    intro μ h
    rw [monomial_cons, lDeriv_θ_mul]
    rw [wordWeight_cons] at h
    have h1 : θ k l * lDeriv D v i (monomial k w) ∈ weightSpace k μ := by
      by_cases hwi : wordWeight w i = 0
      · rw [lDeriv_monomial_eq_zero D v i w hwi, mul_zero]; exact Submodule.zero_mem _
      · have hw : wordWeight w = (wordWeight w - Finsupp.single i 1) + Finsupp.single i 1 := by
          ext j
          simp only [Finsupp.add_apply, Finsupp.tsub_apply, Finsupp.single_apply]
          split_ifs with hij
          · subst hij; omega
          · omega
        have hμ : μ = Finsupp.single l 1 + (wordWeight w - Finsupp.single i 1) := by
          ext j
          have := congr($h j)
          simp only [Finsupp.add_apply, Finsupp.tsub_apply] at this ⊢
          by_cases hij : i = j
          · subst hij
            simp only [Finsupp.single_eq_same] at this ⊢
            omega
          · rw [Finsupp.single_eq_of_ne (Ne.symm hij)] at this ⊢
            omega
        rw [hμ]
        exact mul_mem_weightSpace (θ_mem_weightSpace l) (ih _ hw)
    split_ifs with hil
    · subst hil
      have : wordWeight w = μ := by
        rw [add_comm] at h; exact add_right_cancel h
      exact Submodule.add_mem _ (this ▸ monomial_mem_weightSpace w)
        (Submodule.smul_mem _ _ h1)
    · rw [zero_add]; exact Submodule.smul_mem _ _ h1

lemma lDeriv_mem_weightSpace (i : I) {μ : I →₀ ℕ} {y : LusztigF k I}
    (hy : y ∈ weightSpace k (μ + Finsupp.single i 1)) : lDeriv D v i y ∈ weightSpace k μ := by
  induction hy using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨w, hw, rfl⟩ := hy
    exact lDeriv_monomial_mem D v i w μ hw
  | zero => simp
  | add y z _ _ hy hz => rw [map_add]; exact Submodule.add_mem _ hy hz
  | smul c y _ hy => rw [map_smul]; exact Submodule.smul_mem _ _ hy

lemma lDeriv_eq_zero_of_mem (i : I) {μ : I →₀ ℕ} (hμ : μ i = 0) {y : LusztigF k I}
    (hy : y ∈ weightSpace k μ) : lDeriv D v i y = 0 := by
  induction hy using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨w, rfl, rfl⟩ := hy
    exact lDeriv_monomial_eq_zero D v i w hμ
  | zero => simp
  | add y z _ _ hy hz => rw [map_add, hy, hz, add_zero]
  | smul c y _ hy => rw [map_smul, hy, smul_zero]

/-- The operator `e'ᵢ = ᵢr` on `'f` (Lusztig's left skew derivation, [Lus] 1.2.13). -/
def bosonE (i : I) : Module.End k (LusztigF k I) := lDeriv D v i

/-- The operator `fᵢ`: left multiplication by `θᵢ`. -/
def bosonF (i : I) : Module.End k (LusztigF k I) := LinearMap.mulLeft k (θ k i)

variable {D v}

lemma bosonE_apply (i : I) (x : LusztigF k I) : bosonE D v i x = lDeriv D v i x := rfl

omit [DecidableEq I] in
@[simp] lemma bosonF_apply (i : I) (x : LusztigF k I) : bosonF i x = θ k i * x := rfl

/-- `e'ᵢ θⱼ x = v^{i·j} θⱼ e'ᵢ x + δᵢⱼ x`. -/
theorem bosonE_θ_mul (i j : I) (x : LusztigF k I) :
    bosonE D v i (θ k j * x) =
      v ^ D.dot i j • (θ k j * bosonE D v i x) + if i = j then x else 0 := by
  rw [bosonE_apply, lDeriv_θ_mul, add_comm, bosonE_apply]

/-- The boson relation `e'ᵢ fᵢ = vᵢ² fᵢ e'ᵢ + 1` on `'f`, i.e. `e'ᵢ fᵢ = q⁻² fᵢ e'ᵢ + 1` with
`q = vᵢ⁻¹`. -/
theorem bosonE_bosonF (i : I) :
    bosonE D v i * bosonF i = ((v ^ D.d i)⁻¹⁻¹ ^ 2) • (bosonF i * bosonE D v i) + 1 := by
  ext x
  simp only [Module.End.mul_apply, bosonF_apply, bosonE_θ_mul, ite_true,
    LinearMap.add_apply, LinearMap.smul_apply, Module.End.one_apply]
  rw [zpow_dot_self, inv_inv]

lemma bosonE_mem_weightSpace (i : I) {μ : I →₀ ℕ} {x : LusztigF k I}
    (hx : x ∈ weightSpace k (μ + Finsupp.single i 1)) : bosonE D v i x ∈ weightSpace k μ :=
  lDeriv_mem_weightSpace D v i hx

lemma bosonE_eq_zero_of_mem (i : I) {μ : I →₀ ℕ} (hμ : μ i = 0) {x : LusztigF k I}
    (hx : x ∈ weightSpace k μ) : bosonE D v i x = 0 := by
  rw [bosonE_apply, lDeriv_eq_zero_of_mem D v i hμ hx]

lemma bosonE_pow_eq_zero_of_mem (i : I) {μ : I →₀ ℕ} {x : LusztigF k I}
    (hx : x ∈ weightSpace k μ) : (bosonE D v i ^ (μ i + 1)) x = 0 := by
  induction h : μ i generalizing μ x with
  | zero => rw [zero_add, pow_one]; exact bosonE_eq_zero_of_mem i h hx
  | succ n ih =>
    obtain ⟨μ', rfl⟩ : ∃ μ', μ = μ' + Finsupp.single i 1 := by
      refine ⟨μ - Finsupp.single i 1, ?_⟩
      ext l
      by_cases hl : l = i
      · subst hl; simp [h]
      · simp [Ne.symm hl]
    have hμ' : μ' i = n := by simpa using h
    rw [pow_succ, Module.End.mul_apply]
    exact ih (bosonE_mem_weightSpace i hx) hμ'

/-- `e'ᵢ` is locally nilpotent on `'f`. -/
lemma exists_bosonE_pow_eq_zero (i : I) (x : LusztigF k I) :
    ∃ N : ℕ, (bosonE D v i ^ N) x = 0 := by
  have hx : x ∈ ⨆ ν, weightSpace k (I := I) ν := by rw [iSup_weightSpace]; trivial
  induction hx using Submodule.iSup_induction' with
  | mem ν x hx => exact ⟨ν i + 1, bosonE_pow_eq_zero_of_mem i hx⟩
  | zero => exact ⟨0, by simp⟩
  | add x y _ _ hx hy =>
    obtain ⟨N, hN⟩ := hx
    obtain ⟨N', hN'⟩ := hy
    refine ⟨N + N', ?_⟩
    have h1 : (bosonE D v i ^ (N + N')) x = 0 := by
      rw [add_comm, pow_add, Module.End.mul_apply, hN, map_zero]
    have h2 : (bosonE D v i ^ (N + N')) y = 0 := by
      rw [pow_add, Module.End.mul_apply, hN', map_zero]
    rw [map_add, h1, h2, add_zero]

lemma zWeightProj_bosonE (i : I) (γ : I →₀ ℤ) (x : LusztigF k I) :
    zWeightProj k γ (bosonE D v i x) = bosonE D v i (zWeightProj k (γ + Finsupp.single i 1) x) := by
  classical
  have := ext_weightSpace (φ := zWeightProj k γ ∘ₗ bosonE D v i)
    (ψ := bosonE D v i ∘ₗ zWeightProj k (γ + Finsupp.single i 1)) fun ν x hx ↦ by
    simp only [LinearMap.comp_apply, zWeightProj_of_mem hx]
    by_cases hν : ν i = 0
    · rw [bosonE_eq_zero_of_mem i hν hx, map_zero]
      split_ifs <;> simp [bosonE_eq_zero_of_mem i hν hx]
    · obtain ⟨μ, rfl⟩ : ∃ μ, ν = μ + Finsupp.single i 1 := by
        refine ⟨ν - Finsupp.single i 1, ?_⟩
        ext l
        by_cases hl : l = i
        · subst hl; simp; omega
        · simp [Ne.symm hl]
      rw [zWeightProj_of_mem (bosonE_mem_weightSpace i hx), toZ_add, toZ_single, Nat.cast_one]
      by_cases h : toZ μ = γ
      · rw [ite_eq_left h, ite_eq_left (by rw [h])]
      · rw [ite_eq_right h, ite_eq_right (fun h' ↦ h (add_right_cancel h')), map_zero]
  exact congr($this x)

end LusztigF

namespace LieLean.QuantumGroup

variable {k I : Type*} [Field k] [DecidableEq I] (D : LusztigCartanDatum I) (v : k)

/-- `U⁻`, modelled as `'f ⧸ J` (`J` the quantum Serre ideal). -/
abbrev NegativePart : Type _ := LusztigF k I ⧸ serreSubmodule D v

namespace NegativePart

open LusztigF

variable {D v}

/-- The class of `x ∈ 'f` in `U⁻`. -/
abbrev mk (x : LusztigF k I) : NegativePart D v := Submodule.Quotient.mk x

omit [DecidableEq I] in
lemma serreSubmodule_le_comap_bosonF (i : I) :
    serreSubmodule D v ≤ (serreSubmodule D v).comap (bosonF (k := k) i) := fun x hx ↦ by
  rw [mem_serreSubmodule] at hx
  simp only [Submodule.mem_comap, mem_serreSubmodule, bosonF_apply]
  exact TwoSidedIdeal.mul_mem_left _ _ _ hx

omit [DecidableEq I] in
lemma serreSubmodule_le_comap_zWeightProj (γ : I →₀ ℤ) :
    serreSubmodule D v ≤ (serreSubmodule D v).comap (zWeightProj k γ) := fun x hx ↦ by
  rw [mem_serreSubmodule] at hx
  simp only [Submodule.mem_comap, mem_serreSubmodule, zWeightProj]
  split_ifs
  · exact weightProj_mem_serreIdeal hx _
  · exact (serreIdeal D v).zero_mem

variable (D v) in
/-- `fᵢ` on `U⁻`: left multiplication by `Fᵢ`. -/
def f (i : I) : Module.End k (NegativePart D v) :=
  (serreSubmodule D v).mapQ (serreSubmodule D v) (bosonF i) (serreSubmodule_le_comap_bosonF i)

variable (D v) in
/-- The projection of `U⁻` onto `U⁻_{-γ}` (zero unless `γ ∈ ℕ[I]`). -/
def proj (γ : I →₀ ℤ) : Module.End k (NegativePart D v) :=
  (serreSubmodule D v).mapQ (serreSubmodule D v) (zWeightProj k γ)
    (serreSubmodule_le_comap_zWeightProj γ)

omit [DecidableEq I] in
@[simp] lemma f_mk (i : I) (x : LusztigF k I) : f D v i (mk x) = mk (θ k i * x) := rfl

omit [DecidableEq I] in
@[simp] lemma proj_mk (γ : I →₀ ℤ) (x : LusztigF k I) :
    proj D v γ (mk x) = mk (zWeightProj k γ x) := rfl

omit [DecidableEq I] in
lemma ext_mk {N : Type*} [AddCommGroup N] [Module k N] {φ ψ : NegativePart D v →ₗ[k] N}
    (h : ∀ x, φ (mk x) = ψ (mk x)) : φ = ψ :=
  Submodule.linearMap_qext _ (LinearMap.ext h)

omit [DecidableEq I] in
lemma proj_f (i : I) (γ : I →₀ ℤ) (u : NegativePart D v) :
    proj D v γ (f D v i u) = f D v i (proj D v (γ - Finsupp.single i 1) u) := by
  obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective _ u
  simp only [f_mk, proj_mk, zWeightProj_θ_mul]

/-! ### Weight spaces -/

variable (D v) in
/-- The weight space `U⁻_{-ν}`: the image of `'f_ν`. -/
def weightSpace (ν : I →₀ ℕ) : Submodule k (NegativePart D v) :=
  (LusztigF.weightSpace k ν).map (serreSubmodule D v).mkQ

omit [DecidableEq I] in
lemma mem_weightSpace_iff (ν : I →₀ ℕ) (u : NegativePart D v) :
    u ∈ weightSpace D v ν ↔ proj D v (toZ ν) u = u := by
  constructor
  · rintro ⟨x, hx, rfl⟩
    simp only [Submodule.mkQ_apply, proj_mk, zWeightProj_of_mem hx]
    simp
  · intro h
    obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective _ u
    rw [← h, proj_mk]
    refine ⟨zWeightProj k (toZ ν) x, ?_, rfl⟩
    simp only [zWeightProj, ite_eq_left (nonneg_toZ ν), ofZ_toZ]
    exact weightProj_mem ν x

/-! ### The boson operators on `U⁻` -/

section Boson

variable (hv : v ≠ 0) (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1)
include hv hv'

lemma serreSubmodule_le_comap_bosonE (i : I) :
    serreSubmodule D v ≤ (serreSubmodule D v).comap (bosonE D v i) := fun x hx ↦ by
  rw [mem_serreSubmodule] at hx
  simp only [Submodule.mem_comap, mem_serreSubmodule, bosonE_apply]
  exact lDeriv_mem_serreIdeal hv hv' i hx

variable (D v) in
/-- `e'ᵢ` on `U⁻`. -/
def e (i : I) : Module.End k (NegativePart D v) :=
  (serreSubmodule D v).mapQ (serreSubmodule D v) (bosonE D v i)
    (serreSubmodule_le_comap_bosonE hv hv' i)

@[simp] lemma e_mk (i : I) (x : LusztigF k I) : e D v hv hv' i (mk x) = mk (bosonE D v i x) :=
  rfl

variable (D v) in
/-- The `q`-boson module structure of `U⁻` at `i`, `q = vᵢ⁻¹`. -/
def boson (i : I) : BosonModule (v ^ D.d i)⁻¹ (NegativePart D v) where
  e := e D v hv hv' i
  f := f D v i
  e_mul_f := ext_mk fun x ↦ by
    simp only [Module.End.mul_apply, e_mk, f_mk, LinearMap.add_apply, LinearMap.smul_apply,
      Module.End.one_apply]
    rw [← bosonF_apply (k := k), ← Module.End.mul_apply, bosonE_bosonF]
    simp only [LinearMap.add_apply, LinearMap.smul_apply, Module.End.mul_apply,
      Module.End.one_apply, bosonF_apply]
    rfl
  exists_e_pow_eq_zero u := by
    obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective _ u
    obtain ⟨N, hN⟩ := exists_bosonE_pow_eq_zero (D := D) (v := v) i x
    refine ⟨N, ?_⟩
    have : ∀ n : ℕ, (e D v hv hv' i ^ n) (mk x) = mk ((bosonE D v i ^ n) x) := by
      intro n
      induction n with
      | zero => rfl
      | succ n ih => rw [pow_succ', Module.End.mul_apply, ih, e_mk, ← Module.End.mul_apply,
          ← pow_succ']
    rw [this, hN]
    rfl

@[simp] lemma boson_e (i : I) : (boson D v hv hv' i).e = e D v hv hv' i := rfl

@[simp] lemma boson_f (i : I) : (boson D v hv hv' i).f = f D v i := rfl

omit hv' [DecidableEq I] in
lemma pow_d_ne_zero (i : I) : (v ^ D.d i)⁻¹ ≠ 0 := inv_ne_zero (pow_ne_zero _ hv)

omit hv [DecidableEq I] in
lemma pow_d_ne_one (i : I) : ∀ n : ℕ, 0 < n → ((v ^ D.d i)⁻¹) ^ n ≠ 1 := fun n hn h ↦ by
  rw [inv_pow, inv_eq_one, ← pow_mul] at h
  exact hv' _ (Nat.mul_pos (D.d_pos i) hn) h

variable (D v) in
/-- Kashiwara's operator `ẽᵢ` on `U⁻` ([Jan] 10.2). -/
def kashiwaraE (i : I) : Module.End k (NegativePart D v) :=
  (boson D v hv hv' i).eTilde (pow_d_ne_zero hv i) (pow_d_ne_one hv' i)

variable (D v) in
/-- Kashiwara's operator `f̃ᵢ` on `U⁻` ([Jan] 10.2). -/
def kashiwaraF (i : I) : Module.End k (NegativePart D v) :=
  (boson D v hv hv' i).fTilde (pow_d_ne_zero hv i) (pow_d_ne_one hv' i)

/-- `ẽᵢ f̃ᵢ = 1` on `U⁻` ([Jan] 10.2 (4)). -/
theorem kashiwaraE_kashiwaraF (i : I) (u : NegativePart D v) :
    kashiwaraE D v hv hv' i (kashiwaraF D v hv hv' i u) = u :=
  BosonModule.eTilde_fTilde _ _ u

/-- `f̃ᵢ` is injective on `U⁻` ([Jan] 10.2 (6)). -/
theorem kashiwaraF_injective (i : I) : Function.Injective (kashiwaraF D v hv hv' i) :=
  BosonModule.fTilde_injective _ _

lemma proj_e (i : I) (γ : I →₀ ℤ) (u : NegativePart D v) :
    proj D v γ (e D v hv hv' i u) = e D v hv hv' i (proj D v (γ + Finsupp.single i 1) u) := by
  obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective _ u
  simp only [e_mk, proj_mk, zWeightProj_bosonE]

/-- `ẽᵢ` is homogeneous of degree `-i`: `P_γ ẽᵢ = ẽᵢ P_{γ+i}`. -/
theorem proj_kashiwaraE (i : I) (γ : I →₀ ℤ) (u : NegativePart D v) :
    proj D v γ (kashiwaraE D v hv hv' i u) =
      kashiwaraE D v hv hv' i (proj D v (γ + Finsupp.single i 1) u) :=
  BosonModule.map_eTilde_shift _ _ (boson D v hv hv' i) (proj D v) (Finsupp.single i 1)
    (proj_e hv hv' i) (proj_f i) γ u

/-- `f̃ᵢ` is homogeneous of degree `i`: `P_γ f̃ᵢ = f̃ᵢ P_{γ-i}`. -/
theorem proj_kashiwaraF (i : I) (γ : I →₀ ℤ) (u : NegativePart D v) :
    proj D v γ (kashiwaraF D v hv hv' i u) =
      kashiwaraF D v hv hv' i (proj D v (γ - Finsupp.single i 1) u) :=
  BosonModule.map_fTilde_shift _ _ (boson D v hv hv' i) (proj D v) (Finsupp.single i 1)
    (proj_e hv hv' i) (proj_f i) γ u

/-- `ẽᵢ U⁻_{-(μ+i)} ⊆ U⁻_{-μ}`. -/
theorem kashiwaraE_mem_weightSpace (i : I) {μ : I →₀ ℕ} {u : NegativePart D v}
    (hu : u ∈ weightSpace D v (μ + Finsupp.single i 1)) :
    kashiwaraE D v hv hv' i u ∈ weightSpace D v μ := by
  rw [mem_weightSpace_iff] at hu ⊢
  rw [proj_kashiwaraE, ← Nat.cast_one, ← toZ_single, ← toZ_add, hu]

/-- `f̃ᵢ U⁻_{-μ} ⊆ U⁻_{-(μ+i)}`. -/
theorem kashiwaraF_mem_weightSpace (i : I) {μ : I →₀ ℕ} {u : NegativePart D v}
    (hu : u ∈ weightSpace D v μ) :
    kashiwaraF D v hv hv' i u ∈ weightSpace D v (μ + Finsupp.single i 1) := by
  rw [mem_weightSpace_iff] at hu ⊢
  rw [proj_kashiwaraF, toZ_add, toZ_single, Nat.cast_one, add_sub_cancel_right, hu]

/-! ### `L(∞)` and `B(∞)` -/

variable (D v) in
/-- `f̃_{i₁} ⋯ f̃_{iᵣ} 1` for the word `[i₁, …, iᵣ]`. -/
def fWord : List I → NegativePart D v
  | [] => mk 1
  | i :: w => kashiwaraF D v hv hv' i (fWord w)

@[simp] lemma fWord_nil : fWord D v hv hv' ([] : List I) = mk 1 := rfl

@[simp] lemma fWord_cons (i : I) (w : List I) :
    fWord D v hv hv' (i :: w) = kashiwaraF D v hv hv' i (fWord D v hv hv' w) := rfl

lemma fWord_mem_weightSpace (w : List I) :
    fWord D v hv hv' w ∈ weightSpace D v (wordWeight w) := by
  induction w with
  | nil => exact ⟨1, one_mem_weightSpace, rfl⟩
  | cons i w ih =>
    rw [fWord_cons, wordWeight_cons, add_comm]
    exact kashiwaraF_mem_weightSpace hv hv' i ih

variable {A : Type*} [CommRing A] [Algebra A k]

variable (A D v) in
/-- `L(∞)`: the `A`-span of the `f̃_{i₁} ⋯ f̃_{iᵣ} 1` ([Jan] 10.3; cf. [Kas] Thm. 8.1). -/
def latticeInf : Submodule A (NegativePart D v) :=
  Submodule.span A (Set.range (fWord D v hv hv'))

lemma fWord_mem_latticeInf (w : List I) : fWord D v hv hv' w ∈ latticeInf D v hv hv' A :=
  Submodule.subset_span ⟨w, rfl⟩

lemma one_mem_latticeInf : (mk 1 : NegativePart D v) ∈ latticeInf D v hv hv' A :=
  fWord_mem_latticeInf hv hv' []

/-- `f̃ᵢ L(∞) ⊆ L(∞)`. -/
theorem kashiwaraF_mem_latticeInf (i : I) {u : NegativePart D v}
    (hu : u ∈ latticeInf D v hv hv' A) : kashiwaraF D v hv hv' i u ∈ latticeInf D v hv hv' A := by
  induction hu using Submodule.span_induction with
  | mem u hu =>
    obtain ⟨w, rfl⟩ := hu
    exact fWord_mem_latticeInf hv hv' (i :: w)
  | zero => simp
  | add u u' _ _ hu hu' => rw [map_add]; exact add_mem hu hu'
  | smul a u _ hu =>
    rw [← algebraMap_smul k a u, map_smul, algebraMap_smul]
    exact Submodule.smul_mem _ a hu

variable (A D v) in
/-- `B(∞)`: the nonzero classes of the `f̃_{i₁} ⋯ f̃_{iᵣ} 1` in `L(∞)/c L(∞)` ([Jan] 10.3). -/
def baseInf (c : A) : Set (latticeInf D v hv hv' A ⧸
    (Ideal.span {c} • ⊤ : Submodule A (latticeInf D v hv hv' A))) :=
  (Set.range fun w ↦ Submodule.Quotient.mk ⟨fWord D v hv hv' w, fWord_mem_latticeInf hv hv' w⟩) \
    {0}

end Boson

end NegativePart

end LieLean.QuantumGroup
