/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.GabberKac.Classical
import LieLean.Algebra.QuantumGroup.LusztigF.RatFunc

/-!
# The quantum Gabber–Kac theorem

Let `(I, ·)` be a Cartan datum (`LusztigCartanDatum`, e.g. `LusztigCartanDatum.ofSymmetrization`
of a symmetrizable generalized Cartan matrix) with `I` finite, `k` a field of characteristic zero
and `v ∈ k` transcendental over `ℚ` (Lusztig's case is `k = ℚ(v)`, `v` the indeterminate). Let
`'f = LusztigF k I` be the free algebra on the `θᵢ`, `(·, ·)` Lusztig's bilinear form on `'f`
(`LusztigF.form`) with radical `I` (`LusztigF.radical`), and `J` the two-sided ideal of `'f`
generated by the quantum Serre elements `Σ_{r+s=1-aᵢⱼ} (-1)^r θᵢ^{(s)} θⱼ θᵢ^{(r)}`, `i ≠ j`
(`LusztigF.serreIdeal`).

**Theorem** ([Lus] Thm. 33.1.3 (a); `LusztigF.radical_eq_serreIdeal`,
`LusztigF.radical_eq_serreIdeal_ratFunc`). `I = J`. Equivalently, Lusztig's algebra
`f = 'f / I` is presented by the generators `θᵢ` and the quantum Serre relations.

The inclusion `J ⊆ I` is [Lus] Prop. 1.4.3 (`LusztigF.serreIdeal_le_radical`). For the converse,
Lusztig's proof ([Lus] Thm. 33.1.3 (a), via 33.1.1–33.1.3) and the argument below follow the
same strategy: compare dimensions of weight spaces over `ℚ[v, v⁻¹]` with the specialization
`v = 1`, where the classical Gabber–Kac theorem is available
(`Matrix.Realization.AuxLieAlgebra.maxIdeal_eq_serreIdeal`, [Kac] Thm. 9.11).

## Proof

Both ideals are graded by `ν ∈ ℕ[I]` (`LusztigF.weightProj_mem_radical`,
`LusztigF.weightProj_mem_serreSpan`); fix `ν` and write `V = 'f_ν`, with basis the words of weight
`ν`. The comparison goes through the ring `L = ℚ[T, T⁻¹]` with the specializations
`φ_v : L → k`, `T ↦ v` (injective since `v` is transcendental) and `φ₁ : L → ℚ`, `T ↦ 1`. The
specialization lemma `LinearIndependent.of_comp_ratHom` says: vectors over `L` whose images under
`φ₁` are linearly independent over `ℚ` have linearly independent images under `φ_v`.

1. *(Upper bound for `I_ν`.)* Put `nᵢ = νᵢ` and let `S(w, y) = ε(E_w y)` be the quantum
   Shapovalov pairing of `LusztigF.vermaOpQ` (the action of the raising operators on the quantum
   Verma module of highest weight `n`, pulled back to `'f`). It vanishes for `y ∈ I`
   (`LusztigF.vermaForm_eq_zero_of_mem_radical`), so `I_ν ⊆ ker Φ` for
   `Φ : V → k^{W_ν}`, `y ↦ (S(w, y))_{w ∈ W_ν}`, `W_ν` the words of weight `ν`.
   The pairing is defined over `L` (`LusztigF.vermaCoeff`) and specializes at `T = 1` to the
   classical Shapovalov pairing `S₀`, the contravariant form of the classical irreducible module
   `L(Λ)`, `⟨Λ, αᵢ^∨⟩ = nᵢ`, of the Kac–Moody algebra `𝔤(A)`
   (`LusztigF.contravariantForm_toIrreducible`).
   By the classical Gabber–Kac theorem and the presentation of `L(Λ)`, the kernel of
   `Φ₀ : V₀ → ℚ^{W_ν}` lies in the span `Z` of the classical Serre products `a sᵢⱼ b` of weight `ν`
   (`LusztigF.mem_serreSpan_of_vermaForm_eq_zero`). Hence `rank Φ₀ ≥ |W_ν| - dim Z`, and by
   specialization `rank Φ ≥ rank Φ₀`, so `dim I_ν ≤ dim ker Φ ≤ dim Z`.
2. *(Lower bound for `J_ν`.)* A basis of `Z` can be chosen among the classical Serre products;
   their quantum analogues `a sᵢⱼ^{(v)} b` lie in `J_ν` and specialize to them, so they are
   linearly independent and `dim J_ν ≥ dim Z`.
3. Since `J_ν ⊆ I_ν`, the two are equal.

## Main results

* `LusztigF.radical_inf_weightSpace_le_serreIdeal`: the weight components.
* `LusztigF.radical_eq_serreIdeal`: the quantum Gabber–Kac theorem, `v` transcendental.
* `LusztigF.radical_eq_serreIdeal_ratFunc`: over `ℚ(v)`, `v = RatFunc.X`.
* `LusztigF.Quotient.equivSerre`: `f ≃ 'f / J`.

## References

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, §1.4, §33.1.
* [Kac] V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., CUP 1990, Thm. 9.11, §9.4,
  Cor. 10.4.
-/

noncomputable section

open FreeAlgebra QuantumGroup Module

namespace LusztigF

/-! ### Linear algebra helpers -/

/-- A family whose span is finite-dimensional contains a linearly independent subfamily with as
many members as the dimension of the span. -/
theorem exists_linearIndependent_fin {K M ι : Type*} [Field K] [AddCommGroup M] [Module K M]
    (f : ι → M) [FiniteDimensional K (Submodule.span K (Set.range f))] :
    ∃ a : Fin (finrank K (Submodule.span K (Set.range f))) → ι, LinearIndependent K (f ∘ a) := by
  obtain ⟨κ, a, -, hsp, hli⟩ := exists_linearIndependent' K f
  set S := Submodule.span K (Set.range f)
  have hmem : ∀ x, f (a x) ∈ S := fun x ↦ Submodule.subset_span ⟨a x, rfl⟩
  have hli' : LinearIndependent K (fun x ↦ (⟨f (a x), hmem x⟩ : S)) :=
    LinearIndependent.of_comp S.subtype hli
  have := hli'.finite_of_isNoetherian
  have := Fintype.ofFinite κ
  have hcard : Fintype.card κ = finrank K S := by
    rw [← hsp]; exact linearIndependent_iff_card_eq_finrank_span.1 hli
  refine ⟨a ∘ (Fintype.equivFinOfCardEq hcard).symm, ?_⟩
  exact hli.comp _ (Fintype.equivFinOfCardEq hcard).symm.injective

/-- A linearly independent family of `m` vectors of a finite-dimensional subspace `S` shows
`m ≤ dim S`. -/
lemma card_le_finrank_of_linearIndependent {K M : Type*} [Field K] [AddCommGroup M]
    [Module K M] {m : ℕ} {f : Fin m → M} (hf : LinearIndependent K f) {S : Submodule K M}
    [FiniteDimensional K S] (hS : ∀ t, f t ∈ S) : m ≤ finrank K S := by
  have h := linearIndependent_iff_card_eq_finrank_span.1 hf
  rw [Fintype.card_fin] at h
  rw [h]
  exact Submodule.finrank_mono (Submodule.span_le.2 (Set.range_subset_iff.2 hS))

variable {I : Type*}

/-- The words of weight `ν`. -/
abbrev Words (ν : I →₀ ℕ) : Type _ := {w : List I // wordWeight w = ν}

instance (ν : I →₀ ℕ) : Fintype (Words ν) := (finite_setOf_wordWeight_eq ν).fintype

lemma weightSpace_eq_span (K : Type*) [Field K] (ν : I →₀ ℕ) :
    weightSpace K ν = Submodule.span K (Set.range fun w : Words ν ↦ wordBasis K I w.1) := by
  rw [weightSpace]
  congr 1
  ext x
  simp [monomial, Words]

lemma finrank_weightSpace (K : Type*) [Field K] (ν : I →₀ ℕ) :
    finrank K (weightSpace K ν) = Fintype.card (Words ν) := by
  rw [weightSpace_eq_span]
  exact (finrank_span_eq_card
    ((wordBasis K I).linearIndependent.comp _ Subtype.val_injective))

/-- The coordinates on the words of weight `ν`. -/
def wordCoord (R : Type*) [CommRing R] (ν : I →₀ ℕ) : FreeAlgebra R I →ₗ[R] (Words ν → R) :=
  LinearMap.pi fun w ↦ (wordBasis R I).coord w.1

lemma wordCoord_apply (R : Type*) [CommRing R] (ν : I →₀ ℕ) (x : FreeAlgebra R I) (w : Words ν) :
    wordCoord R ν x w = (wordBasis R I).repr x w.1 := rfl

lemma repr_eq_zero_of_mem_wordSpan {R : Type*} [CommRing R] {ν : I →₀ ℕ} {x : FreeAlgebra R I}
    (hx : x ∈ wordSpan R ν) {w : List I} (hw : wordWeight w ≠ ν) :
    (wordBasis R I).repr x w = 0 := by
  classical
  induction hx using wordSpan_induction with
  | word u hu =>
    rw [Module.Basis.repr_self, Finsupp.single_apply, ite_eq_right_iff]
    rintro rfl; exact absurd hu hw
  | zero => simp
  | add y z _ _ hy hz => simp [hy, hz]
  | smul c y _ hy => simp [hy]

lemma eq_zero_of_wordCoord_eq_zero {R : Type*} [CommRing R] {ν : I →₀ ℕ} {x : FreeAlgebra R I}
    (hx : x ∈ wordSpan R ν) (h : wordCoord R ν x = 0) : x = 0 := by
  refine (wordBasis R I).repr.injective ?_
  ext w
  rw [map_zero, Finsupp.coe_zero, Pi.zero_apply]
  by_cases hw : wordWeight w = ν
  · exact congr_fun h ⟨w, hw⟩
  · exact repr_eq_zero_of_mem_wordSpan hx hw

/-! ### Lifting Serre products to `ℚ[T, T⁻¹]` -/

variable [DecidableEq I] (D : LusztigCartanDatum I)

/-- The quantum Serre product `a sᵢⱼ b` over `ℚ[T, T⁻¹]` (with `qᵢ = T^{dᵢ}`), for
`g = (a, i, j, b)`. -/
def serreProductL (g : List I × I × I × List I) : FreeAlgebra (LaurentPolynomial ℚ) I :=
  wordBasis _ I g.1 *
    qSerreU (laurentT ^ D.d g.2.1) (serreExp D g.2.1 g.2.2.1) (ι _ g.2.1) (ι _ g.2.2.1) *
    wordBasis _ I g.2.2.2

omit [DecidableEq I] in
lemma mapCoeffs_qSerreU {R K : Type*} [CommRing R] [Field K] (φ : R →+* K) (q : Rˣ) (m : ℕ)
    (a b : FreeAlgebra R I) :
    mapCoeffs φ (qSerreU q m a b) = qSerre (φ q) m (mapCoeffs φ a) (mapCoeffs φ b) := by
  simp only [qSerreU, qSerre, map_sum, mapCoeffs_smul, map_mul, map_pow, map_neg, map_one,
    map_qBinomialU]

omit [DecidableEq I] in
lemma mapCoeffs_serreProductL {K : Type*} [Field K] (φ : LaurentPolynomial ℚ →+* K)
    (g : List I × I × I × List I) :
    mapCoeffs φ (serreProductL D g) =
      serreProduct D (fun i ↦ φ ((laurentT ^ D.d i : (LaurentPolynomial ℚ)ˣ) : _)) g := by
  rw [serreProductL, map_mul, map_mul, mapCoeffs_qSerreU, mapCoeffs_wordBasis, mapCoeffs_wordBasis,
    mapCoeffs_ι, mapCoeffs_ι]
  rfl

/-! ### The quantum Gabber–Kac theorem -/

variable {k : Type*} [Field k] [CharZero k] {v : k}

omit [DecidableEq I] in
lemma ne_zero_of_transcendental (hv : Transcendental ℚ v) : v ≠ 0 := fun h ↦
  Polynomial.X_ne_zero ((transcendental_iff.1 hv) Polynomial.X (by simp [h]))

omit [DecidableEq I] in
lemma pow_ne_one_of_transcendental (hv : Transcendental ℚ v) {n : ℕ} (hn : 0 < n) : v ^ n ≠ 1 :=
  fun h ↦ Polynomial.X_pow_sub_C_ne_zero hn (1 : ℚ)
    ((transcendental_iff.1 hv) _ (by simp [h]))

variable (v) in
/-- The radical of Lusztig's form as a `k`-subspace of `'f`. -/
def radicalSubmodule : Submodule k (LusztigF k I) where
  carrier := {x | x ∈ radical D v}
  add_mem' {a b} ha hb := show a + b ∈ radical D v from TwoSidedIdeal.add_mem _ ha hb
  zero_mem' := (radical D v).zero_mem
  smul_mem' c x hx := by
    change c • x ∈ radical D v
    rw [Algebra.smul_def]; exact TwoSidedIdeal.mul_mem_left _ _ _ hx

omit [CharZero k] [DecidableEq I] in
lemma serreProduct_mem_serreIdeal (hv0 : v ≠ 0) (hv : ∀ n : ℕ, 0 < n → v ^ n ≠ 1)
    {g : List I × I × I × List I} (hg : g.2.1 ≠ g.2.2.1) :
    serreProduct D (fun i ↦ v ^ D.d i) g ∈ serreIdeal D v := by
  refine TwoSidedIdeal.mul_mem_right _ _ _ (TwoSidedIdeal.mul_mem_left _ _ _ ?_)
  exact qSerre_mem_serreIdeal hg (qFactorial_ne_zero_of_not_root hv0 hv _ _)

omit [CharZero k] [DecidableEq I] in
lemma serreSpan_le_serreIdeal (hv0 : v ≠ 0) (hv : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) {ν : I →₀ ℕ}
    {y : LusztigF k I} (hy : y ∈ serreSpan D (fun i ↦ v ^ D.d i) ν) : y ∈ serreIdeal D v := by
  induction hy using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨g, ⟨hg, -⟩, rfl⟩ := hz
    exact serreProduct_mem_serreIdeal D hv0 hv hg
  | zero => exact (serreIdeal D v).zero_mem
  | add y z _ _ hy hz => exact TwoSidedIdeal.add_mem _ hy hz
  | smul c y _ hy => exact smul_mem_serreIdeal c hy

variable [Fintype I]

/-- A dominant integral weight with prescribed values `⟨Λ, αᵢ^∨⟩ = nᵢ` for the standard
realization. -/
def stdWeight (n : I → ℕ) : Module.Dual ℚ (Matrix.Realization.StdSpace D.cartanMatrix ℚ) :=
  (∑ i, (n i : ℚ) • LinearMap.proj i) ∘ₗ LinearMap.fst ℚ (I → ℚ) _

omit [DecidableEq I] in
lemma stdWeight_coroot [DecidableEq I] (n : I → ℕ) (i : I) :
    stdWeight D n ((Matrix.Realization.std D.cartanMatrix ℚ).coroot i) = n i := by
  simp [stdWeight, Matrix.Realization.std, Pi.single_apply]

omit [Fintype I] in
/-- **The quantum Gabber–Kac theorem, weight by weight, with the dimension count.** For `v`
transcendental over `ℚ`, an element of weight `ν` of the radical of Lusztig's form lies in the
span of the quantum Serre products of weight `ν`, and this span has the same dimension as the span
of the classical Serre products (`q = 1`) of weight `ν` in `ℚ⟨θ⟩`. -/
theorem mem_serreSpan_of_mem_radical_and_finrank_serreSpan [Finite I] (hv : Transcendental ℚ v)
    (ν : I →₀ ℕ) :
    (∀ x : LusztigF k I, x ∈ radical D v → x ∈ weightSpace k ν →
      x ∈ serreSpan D (fun i ↦ v ^ D.d i) ν) ∧
    finrank k (serreSpan D (fun i ↦ v ^ D.d i) ν) =
      finrank ℚ (serreSpan D (fun _ ↦ (1 : ℚ)) ν) := by
  have := Fintype.ofFinite I
  have hv0 := ne_zero_of_transcendental hv
  have hvn : ∀ n : ℕ, 0 < n → v ^ n ≠ 1 := fun n hn ↦ pow_ne_one_of_transcendental hv hn
  have hv' : ∀ i, (v ^ D.d i) ^ 2 ≠ 1 := fun i ↦ by
    rw [← pow_mul]; exact hvn _ (by have := D.d_pos i; omega)
  have hinj : Function.Injective (evalAt v hv0) :=
    LaurentPolynomial.eval₂_injective_of_transcendental hv hv0
  set n : I → ℕ := fun i ↦ ν i with hn_def
  set cL : I → (I →₀ ℕ) → LaurentPolynomial ℚ := fun i μ ↦ vermaCoeff D (fun i ↦ (n i : ℤ)) i μ
  have hc₀ : (fun i ↦ (evalAt (1 : ℚ) one_ne_zero) ∘ cL i) = classicalCoeff ℚ D n := by
    funext i μ
    simp only [Function.comp_apply, cL, evalAt_one_vermaCoeff, classicalCoeff]
  -- the quantum and classical Shapovalov maps `Φ`, `Φ₀`
  let Φ : LusztigF k I →ₗ[k] (Words ν → k) :=
    LinearMap.pi fun w ↦ vermaForm (fun i ↦ (evalAt v hv0) ∘ cL i) w.1
  let Φ₀ : LusztigF ℚ I →ₗ[ℚ] (Words ν → ℚ) :=
    LinearMap.pi fun w ↦ vermaForm (classicalCoeff ℚ D n) w.1
  have hspecQ : ∀ (u : List I) (w : Words ν),
      evalAt v hv0 (vermaForm cL w.1 (wordBasis _ I u)) = Φ (wordBasis k I u) w := by
    intro u w
    rw [map_vermaForm, mapCoeffs_wordBasis]
    rfl
  have hspec₀ : ∀ (u : List I) (w : Words ν),
      evalAt (1 : ℚ) one_ne_zero (vermaForm cL w.1 (wordBasis _ I u)) = Φ₀ (wordBasis ℚ I u) w := by
    intro u w
    rw [map_vermaForm, mapCoeffs_wordBasis, hc₀]
    rfl
  set V := weightSpace k ν
  set V₀ := weightSpace ℚ ν
  set Z := serreSpan D (fun _ ↦ (1 : ℚ)) ν
  have : FiniteDimensional ℚ Z := Submodule.finiteDimensional_of_le (serreSpan_le_weightSpace D _ ν)
  -- Step 1: the kernel of `Φ₀` on `V₀` lies in `Z`
  have hker₀ : finrank ℚ (LinearMap.ker (Φ₀.domRestrict V₀)) ≤ finrank ℚ Z := by
    rw [← Submodule.finrank_map_subtype_eq]
    refine Submodule.finrank_mono ?_
    rintro _ ⟨y, hy, rfl⟩
    have hy' : Φ₀ (y : LusztigF ℚ I) = 0 := hy
    change (y : LusztigF ℚ I) ∈ Z
    refine mem_serreSpan_of_vermaForm_eq_zero D (Matrix.Realization.std D.cartanMatrix ℚ)
      (stdWeight_coroot D n) (fun _ ↦ le_rfl) y.2 fun w hw ↦ ?_
    exact congr_fun hy' ⟨w, hw⟩
  have hrange₀ : LinearMap.range (Φ₀.domRestrict V₀) =
      Submodule.span ℚ (Set.range fun w : Words ν ↦ Φ₀ (wordBasis ℚ I w.1)) := by
    rw [LinearMap.range_domRestrict, show V₀ = _ from weightSpace_eq_span ℚ ν, Submodule.map_span,
      ← Set.range_comp]
    rfl
  have hrank₀ := LinearMap.finrank_range_add_finrank_ker (Φ₀.domRestrict V₀)
  -- Step 2: `rank Φ ≥ rank Φ₀` by specialization
  obtain ⟨a, ha⟩ := exists_linearIndependent_fin (K := ℚ) fun w : Words ν ↦ Φ₀ (wordBasis ℚ I w.1)
  have hq : LinearIndependent k fun t ↦ Φ (wordBasis k I (a t).1) := by
    have h := LinearIndependent.of_comp_ratHom (evalAt (1 : ℚ) one_ne_zero) (evalAt v hv0) hinj
      (fun t (w : Words ν) ↦ vermaForm cL w.1 (wordBasis _ I (a t).1)) (by
        convert ha using 1
        funext t w
        exact hspec₀ _ w)
    convert h using 1
    funext t w
    exact (hspecQ _ w).symm
  have hr := card_le_finrank_of_linearIndependent hq (S := LinearMap.range (Φ.domRestrict V))
    fun t ↦ ⟨⟨_, wordBasis_mem_wordSpan_of_eq (a t).2⟩, rfl⟩
  rw [← hrange₀] at hr
  have hrank := LinearMap.finrank_range_add_finrank_ker (Φ.domRestrict V)
  have hVV₀ : finrank k V = finrank ℚ V₀ := by rw [finrank_weightSpace, finrank_weightSpace]
  have hker : finrank k (LinearMap.ker (Φ.domRestrict V)) ≤ finrank ℚ Z := by omega
  -- Step 3: `dim J_ν ≥ dim Z` by specialization of Serre products
  have hZ : Z = Submodule.span ℚ
      (Set.range fun g : serreIndices D ν ↦ serreProduct D (fun _ ↦ (1 : ℚ)) g.1) := by
    rw [show Z = serreSpan D (fun _ ↦ (1 : ℚ)) ν from rfl, serreSpan, Set.image_eq_range]
  have : FiniteDimensional ℚ (Submodule.span ℚ
      (Set.range fun g : serreIndices D ν ↦ serreProduct D (fun _ ↦ (1 : ℚ)) g.1)) := hZ ▸ this
  obtain ⟨b, hb⟩ := exists_linearIndependent_fin (K := ℚ)
    fun g : serreIndices D ν ↦ serreProduct D (fun _ ↦ (1 : ℚ)) g.1
  have hm : finrank ℚ (Submodule.span ℚ
      (Set.range fun g : serreIndices D ν ↦ serreProduct D (fun _ ↦ (1 : ℚ)) g.1)) =
      finrank ℚ Z := by rw [hZ]
  have hb' : LinearIndependent ℚ fun t ↦
      wordCoord ℚ ν (serreProduct D (fun _ ↦ (1 : ℚ)) (b t).1) := by
    refine hb.map (f := wordCoord ℚ ν) ?_
    rw [Submodule.disjoint_def]
    intro y hy hy0
    refine eq_zero_of_wordCoord_eq_zero ?_ hy0
    have hle : Submodule.span ℚ (Set.range
        ((fun g : serreIndices D ν ↦ serreProduct D (fun _ ↦ (1 : ℚ)) g.1) ∘ b)) ≤
        wordSpan ℚ ν := by
      rw [Submodule.span_le]
      rintro _ ⟨t, rfl⟩
      exact serreSpan_le_weightSpace D _ ν (Submodule.subset_span ⟨(b t).1, (b t).2, rfl⟩)
    exact hle hy
  have hqS : LinearIndependent k fun t ↦ serreProduct D (fun i ↦ v ^ D.d i) (b t).1 := by
    have h := LinearIndependent.of_comp_ratHom (evalAt (1 : ℚ) one_ne_zero) (evalAt v hv0) hinj
      (fun t (w : Words ν) ↦ (wordBasis _ I).repr (serreProductL D (b t).1) w.1) (by
        convert hb' using 1
        funext t w
        simp only [Function.comp_apply, wordCoord_apply, ← wordBasis_repr_mapCoeffs,
          mapCoeffs_serreProductL, evalAt_laurentT_pow, one_pow])
    refine LinearIndependent.of_comp (wordCoord k ν) ?_
    convert h using 1
    funext t w
    simp only [Function.comp_apply, wordCoord_apply, ← wordBasis_repr_mapCoeffs,
      mapCoeffs_serreProductL, evalAt_laurentT_pow]
  have : FiniteDimensional k (serreSpan D (fun i ↦ v ^ D.d i) ν) :=
    Submodule.finiteDimensional_of_le (serreSpan_le_weightSpace D _ ν)
  have hm' := card_le_finrank_of_linearIndependent hqS
    (S := serreSpan D (fun i ↦ v ^ D.d i) ν) fun t ↦
      Submodule.subset_span ⟨(b t).1, (b t).2, rfl⟩
  -- Step 4: `J_ν ⊆ I_ν ⊆ ker Φ` and `dim ker Φ ≤ dim Z ≤ dim J_ν`
  let RadV : Submodule k V := (radicalSubmodule D v).comap V.subtype
  let SerV : Submodule k V := (serreSpan D (fun i ↦ v ^ D.d i) ν).comap V.subtype
  have hSerRad : SerV ≤ RadV := fun y hy ↦
    serreIdeal_le_radical hv0 hvn (serreSpan_le_serreIdeal D hv0 hvn hy)
  have hRadKer : RadV ≤ LinearMap.ker (Φ.domRestrict V) := fun y hy ↦ by
    rw [LinearMap.mem_ker]
    funext w
    exact vermaForm_eq_zero_of_mem_radical D hv0 hv' _ w.1 hy
  have hSerV : finrank k SerV = finrank k (serreSpan D (fun i ↦ v ^ D.d i) ν) := by
    rw [← Submodule.finrank_map_subtype_eq, Submodule.map_comap_subtype,
      inf_eq_right.2 (serreSpan_le_weightSpace D _ ν)]
  have hEq : SerV = RadV := Submodule.eq_of_le_of_finrank_le hSerRad (by
    have := Submodule.finrank_mono hRadKer
    omega)
  refine ⟨fun x hx hxν ↦ ?_, ?_⟩
  · have hxV : (⟨x, hxν⟩ : V) ∈ SerV := hEq ▸ hx
    exact hxV
  · have := Submodule.finrank_mono hRadKer
    rw [← hEq] at this
    rw [hm] at hm'
    omega

omit [Fintype I] in
/-- **The quantum Gabber–Kac theorem, weight by weight.** For `v` transcendental over `ℚ`, an
element of weight `ν` of the radical of Lusztig's form lies in the ideal generated by the quantum
Serre elements. -/
theorem radical_inf_weightSpace_le_serreIdeal [Finite I] (hv : Transcendental ℚ v)
    (ν : I →₀ ℕ) {x : LusztigF k I} (hx : x ∈ radical D v) (hxν : x ∈ weightSpace k ν) :
    x ∈ serreIdeal D v :=
  serreSpan_le_serreIdeal D (ne_zero_of_transcendental hv)
    (fun _ hn ↦ pow_ne_one_of_transcendental hv hn)
    ((mem_serreSpan_of_mem_radical_and_finrank_serreSpan D hv ν).1 x hx hxν)

/-! ### Gradedness of the radical -/

omit [Fintype I] [CharZero k] in
/-- The projections onto weight spaces are self-adjoint for Lusztig's form. -/
lemma form_weightProj (ν : I →₀ ℕ) (y x : LusztigF k I) :
    form D v (weightProj k ν y) x = form D v y (weightProj k ν x) := by
  induction y using induction_wordBasis with
  | zero => simp
  | add y y' hy hy' => simp only [map_add, LinearMap.add_apply, hy, hy']
  | smul c y hy => simp only [map_smul, LinearMap.smul_apply, hy]
  | word w =>
    induction x using induction_wordBasis with
    | zero => simp
    | add x x' hx hx' => rw [map_add, map_add, map_add, hx, hx']
    | smul c x hx => rw [map_smul, map_smul, map_smul, hx]
    | word u =>
      rw [weightProj_wordBasis, weightProj_wordBasis]
      by_cases hwu : wordWeight w = wordWeight u
      · rw [hwu]; split_ifs <;> simp
      · have h0 := form_eq_zero_of_ne D v hwu (wordBasis_mem_wordSpan (R := k) w)
          (wordBasis_mem_wordSpan (R := k) u)
        split_ifs <;> simp only [map_zero, LinearMap.zero_apply, h0]

omit [Fintype I] [CharZero k] in
/-- The radical of Lusztig's form is graded. -/
lemma weightProj_mem_radical (ν : I →₀ ℕ) {x : LusztigF k I} (hx : x ∈ radical D v) :
    weightProj k ν x ∈ radical D v := by
  rw [mem_radical_iff']
  intro y
  rw [← form_weightProj, (mem_radical_iff' D v).1 hx]

omit [Fintype I] [CharZero k] in
/-- Every element is the sum of its weight components. -/
lemma sum_weightProj (x : LusztigF k I) :
    ∑ ν ∈ ((wordBasis k I).repr x).support.image wordWeight, weightProj k ν x = x := by
  classical
  set c := (wordBasis k I).repr x
  have hx : x = ∑ w ∈ c.support, c w • wordBasis k I w := by
    conv_lhs => rw [← (wordBasis k I).linearCombination_repr x]
    rw [Finsupp.linearCombination_apply, Finsupp.sum]
  conv_rhs => rw [hx]
  conv_lhs => rw [hx]
  simp only [map_sum, map_smul, weightProj_wordBasis, smul_ite, smul_zero]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun w hw ↦ ?_
  rw [Finset.sum_ite_eq]
  simp [Finset.mem_image_of_mem _ hw]

/-! ### The theorem -/

omit [Fintype I] in
/-- **Quantum Gabber–Kac theorem** ([Lus] Thm. 33.1.3 (a)): for a Cartan datum with finitely
many simple roots, a field `k` of characteristic zero and `v ∈ k` transcendental over `ℚ`, the
radical of Lusztig's form on `'f` is the two-sided ideal generated by the quantum Serre
elements. ([Lus] states this over `ℚ(v)`.) -/
theorem radical_eq_serreIdeal [Finite I] (hv : Transcendental ℚ v) :
    radical D v = serreIdeal D v := by
  refine le_antisymm (fun x hx ↦ ?_)
    (serreIdeal_le_radical (ne_zero_of_transcendental hv)
      fun _ hn ↦ pow_ne_one_of_transcendental hv hn)
  rw [← sum_weightProj x]
  refine Finset.sum_induction _ (· ∈ serreIdeal D v) (fun a b ha hb ↦ TwoSidedIdeal.add_mem _ ha hb)
    (serreIdeal D v).zero_mem fun ν _ ↦ ?_
  exact radical_inf_weightSpace_le_serreIdeal D hv ν (weightProj_mem_radical D ν hx)
    (weightProj_mem ν x)

omit [Fintype I] in
/-- The quantum Gabber–Kac theorem, elementwise: `x ∈ 'f` is orthogonal to `'f` for Lusztig's
form iff it lies in the ideal generated by the quantum Serre elements. -/
theorem forall_form_eq_zero_iff_mem_serreIdeal [Finite I] (hv : Transcendental ℚ v)
    {x : LusztigF k I} : (∀ y, form D v x y = 0) ↔ x ∈ serreIdeal D v := by
  rw [← mem_radical_iff, radical_eq_serreIdeal D hv]

omit [Fintype I] in
/-- Lusztig's algebra `f = 'f / I` is presented by the quantum Serre relations: the kernel of
`'f → f` is the ideal generated by the quantum Serre elements. -/
theorem toQuotient_eq_zero_iff_mem_serreIdeal [Finite I] (hv : Transcendental ℚ v)
    {x : LusztigF k I} : toQuotient D v x = 0 ↔ x ∈ serreIdeal D v := by
  rw [toQuotient_eq_zero_iff, radical_eq_serreIdeal D hv]

end LusztigF

namespace LusztigF

variable {I : Type*} [Finite I] [DecidableEq I] (D : LusztigCartanDatum I)

/-- The indeterminate `v ∈ ℚ(v)` is transcendental over `ℚ`. -/
lemma transcendental_ratFunc_X : Transcendental ℚ (RatFunc.X : RatFunc ℚ) := by
  convert RatFunc.transcendental_X (K := ℚ)
  exact Subsingleton.elim _ _

/-- **Quantum Gabber–Kac theorem over `ℚ(v)`** ([Lus] Thm. 33.1.3 (a)). Let `(I, ·)` be a
Cartan datum with `I` finite (e.g. `LusztigCartanDatum.ofSymmetrization` of a symmetrizable
generalized Cartan matrix), `'f = FreeAlgebra ℚ(v) I` the free algebra on the `θᵢ`, and
`(·, ·)` Lusztig's bilinear form on `'f` (`LusztigF.form`). Then the radical of the form equals
the two-sided ideal of `'f` generated by the quantum Serre elements
`Σ_{r+s=1-aᵢⱼ} (-1)^r θᵢ^{(s)} θⱼ θᵢ^{(r)}` (`i ≠ j`). -/
theorem radical_eq_serreIdeal_ratFunc :
    radical D (RatFunc.X : RatFunc ℚ) = serreIdeal D RatFunc.X :=
  radical_eq_serreIdeal D transcendental_ratFunc_X

/-- The quantum Gabber–Kac theorem over `ℚ(v)`, elementwise: an element `x` of the free algebra
`'f = FreeAlgebra ℚ(v) I` satisfies `(x, y) = 0` for all `y` iff `x` lies in the ideal generated
by the quantum Serre elements. -/
theorem forall_form_eq_zero_iff_mem_serreIdeal_ratFunc {x : FreeAlgebra (RatFunc ℚ) I} :
    (∀ y, form D RatFunc.X x y = 0) ↔ x ∈ serreIdeal D (RatFunc.X : RatFunc ℚ) :=
  forall_form_eq_zero_iff_mem_serreIdeal D transcendental_ratFunc_X

end LusztigF
