/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import Mathlib.Algebra.MonoidAlgebra.Basic
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import LieLean.Algebra.QuantumGroup.Basic
import LieLean.Algebra.QuantumGroup.LusztigF.Serre

/-!
# The subalgebras `U⁺`, `U⁰`, `U⁻` of `U_q(𝔤)` and the spanning half of the triangular
decomposition

Lusztig's algebra `'f` maps to `U = U_q(𝔤)` in two ways, `x ↦ x⁺` (`θᵢ ↦ Eᵢ`) and `x ↦ x⁻`
(`θᵢ ↦ Fᵢ`) ([Lus] 3.1.2 (check)); both kill the quantum Serre elements, hence the two-sided
ideal they generate. The group algebra `k[Y]` maps to `U` by `e^μ ↦ K_μ`. We show that `U` is
spanned by the products `y⁻ K_μ x⁺` of monomials `x, y` and `μ ∈ Y`, i.e. the multiplication map
`U⁻ ⊗ U⁰ ⊗ U⁺ → U` is surjective ([Jan] 4.21 (check), [Lus] 3.2 (check)). The injectivity
of this map (the other half of the triangular decomposition) is not proved here.

## Main definitions

* `QuantumGroup.plusHom`, `QuantumGroup.minusHom`: `'f → U`, `θᵢ ↦ Eᵢ`, resp. `θᵢ ↦ Fᵢ`.
* `QuantumGroup.zeroHom`: `k[Y] → U`, `e^μ ↦ K_μ`.

## Main results

* `QuantumGroup.plusHom_serreElement`, `QuantumGroup.serreIdeal_le_ker_plusHom` (and `minus`
  versions): the Serre elements of `'f` map to zero.
* `QuantumGroup.span_triangular`: `U` is spanned by the `y⁻ K_μ x⁺`.

## References

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, §3.1–3.2.
* [Jan] J. C. Jantzen, *Lectures on quantum groups*, GSM 6, Ch. 4.
-/

noncomputable section

open LusztigF

namespace QuantumGroup

variable {k I Y : Type*} [Field k] [AddCommGroup Y] [DecidableEq I] {D : CartanDatum I}
  (R : D.RootDatum Y) (v : k)

/-- The algebra homomorphism `'f → U`, `x ↦ x⁺`, `θᵢ ↦ Eᵢ` ([Lus] 3.1.2 (check)). -/
def plusHom : LusztigF k I →ₐ[k] QuantumGroup R v := FreeAlgebra.lift k (E R v)

/-- The algebra homomorphism `'f → U`, `x ↦ x⁻`, `θᵢ ↦ Fᵢ` ([Lus] 3.1.2 (check)). -/
def minusHom : LusztigF k I →ₐ[k] QuantumGroup R v := FreeAlgebra.lift k (F R v)

/-- The algebra homomorphism `k[Y] → U`, `e^μ ↦ K_μ`. -/
def zeroHom : AddMonoidAlgebra k Y →ₐ[k] QuantumGroup R v :=
  AddMonoidAlgebra.lift k (QuantumGroup R v) Y (KHom R v)

@[simp] lemma plusHom_θ (i : I) : plusHom R v (θ k i) = E R v i := by simp [plusHom]

@[simp] lemma minusHom_θ (i : I) : minusHom R v (θ k i) = F R v i := by simp [minusHom]

@[simp] lemma zeroHom_single (μ : Y) : zeroHom R v (AddMonoidAlgebra.single μ 1) = K R v μ := by
  simp [zeroHom]

variable {R v}

/-- The quantum Serre elements of `'f` map to zero in `U⁺`. -/
theorem plusHom_serreElement {i j : I} (hij : i ≠ j)
    (hfact : qFactorial (v ^ D.d i) (1 - D.cartanMatrix i j).toNat ≠ 0) :
    plusHom R v (serreElement D v i j) = 0 := by
  rw [serreElement, qSerreDiv_eq hfact, map_smul, map_qSerre, plusHom_θ, plusHom_θ,
    serre_E R v hij, smul_zero]

/-- The quantum Serre elements of `'f` map to zero in `U⁻`. -/
theorem minusHom_serreElement {i j : I} (hij : i ≠ j)
    (hfact : qFactorial (v ^ D.d i) (1 - D.cartanMatrix i j).toNat ≠ 0) :
    minusHom R v (serreElement D v i j) = 0 := by
  rw [serreElement, qSerreDiv_eq hfact, map_smul, map_qSerre, minusHom_θ, minusHom_θ,
    serre_F R v hij, smul_zero]

omit [DecidableEq I] in
lemma qFactorial_ne_zero_of_not_root (hv : v ≠ 0) (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) (i : I)
    (M : ℕ) : qFactorial (v ^ D.d i) M ≠ 0 := by
  refine qFactorial_ne_zero (pow_ne_zero _ hv) fun n hn _ ↦ ?_
  rw [← pow_mul]
  exact hv' _ (Nat.mul_pos (D.d_pos i) (by omega))

/-- For `v` not a root of unity, `x ↦ x⁺` kills the ideal generated by the Serre elements. -/
theorem serreIdeal_le_ker_plusHom (hv : v ≠ 0) (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) :
    serreIdeal D v ≤ TwoSidedIdeal.ker (plusHom R v) := by
  rw [serreIdeal, TwoSidedIdeal.span_le]
  rintro _ ⟨i, j, hij, rfl⟩
  exact (TwoSidedIdeal.mem_ker _).2
    (plusHom_serreElement hij (qFactorial_ne_zero_of_not_root hv hv' i _))

/-- For `v` not a root of unity, `x ↦ x⁻` kills the ideal generated by the Serre elements. -/
theorem serreIdeal_le_ker_minusHom (hv : v ≠ 0) (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) :
    serreIdeal D v ≤ TwoSidedIdeal.ker (minusHom R v) := by
  rw [serreIdeal, TwoSidedIdeal.span_le]
  rintro _ ⟨i, j, hij, rfl⟩
  exact (TwoSidedIdeal.mem_ker _).2
    (minusHom_serreElement hij (qFactorial_ne_zero_of_not_root hv hv' i _))

/-! ### `U` is spanned by the `y⁻ K_μ x⁺` -/

variable (R v) in
/-- The spanning set `{y⁻ K_μ x⁺}` of `U`, `x, y` monomials of `'f`. -/
def triangularSet : Set (QuantumGroup R v) :=
  {u | ∃ (w : List I) (μ : Y) (w' : List I),
    u = minusHom R v (monomial k w) * K R v μ * plusHom R v (monomial k w')}

lemma K_mul_minusHom_monomial (μ : Y) (w : List I) :
    K R v μ * minusHom R v (monomial k w) =
      (w.map fun j ↦ v ^ (-R.root j μ)).prod • (minusHom R v (monomial k w) * K R v μ) := by
  induction w with
  | nil => simp
  | cons j w ih =>
    rw [monomial_cons, map_mul, minusHom_θ, ← mul_assoc, K_mul_F, smul_mul_assoc, mul_assoc, ih,
      mul_smul_comm, smul_smul, List.map_cons, List.prod_cons, mul_assoc]

variable (R v) in
/-- The span of the `y⁻ K_μ x⁺`; it is all of `U` (`span_triangular`). -/
def triangularSpan : Submodule k (QuantumGroup R v) := Submodule.span k (triangularSet R v)

lemma mem_triangularSpan (w : List I) (μ : Y) (w' : List I) :
    minusHom R v (monomial k w) * K R v μ * plusHom R v (monomial k w') ∈
      triangularSpan R v :=
  Submodule.subset_span ⟨w, μ, w', rfl⟩

lemma F_mul_mem_triangularSpan (i : I) {s : QuantumGroup R v} (hs : s ∈ triangularSpan R v) :
    F R v i * s ∈ triangularSpan R v := by
  induction hs using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨w, μ, w', rfl⟩ := hx
    rw [← mul_assoc, ← mul_assoc, ← minusHom_θ R v (k := k) i, ← map_mul, ← monomial_cons]
    exact mem_triangularSpan _ _ _
  | zero => simp
  | add x y _ _ hx hy => rw [mul_add]; exact Submodule.add_mem _ hx hy
  | smul c x _ hx => rw [mul_smul_comm]; exact Submodule.smul_mem _ _ hx

lemma K_mul_mem_triangularSpan (ν : Y) {s : QuantumGroup R v} (hs : s ∈ triangularSpan R v) :
    K R v ν * s ∈ triangularSpan R v := by
  induction hs using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨w, μ, w', rfl⟩ := hx
    rw [← mul_assoc, ← mul_assoc, K_mul_minusHom_monomial, smul_mul_assoc, smul_mul_assoc,
      mul_assoc (minusHom R v _), K_add]
    exact Submodule.smul_mem _ _ (mem_triangularSpan _ _ _)
  | zero => simp
  | add x y _ _ hx hy => rw [mul_add]; exact Submodule.add_mem _ hx hy
  | smul c x _ hx => rw [mul_smul_comm]; exact Submodule.smul_mem _ _ hx

lemma E_mul_mem_triangularSpan (hv : v ≠ 0) (i : I) (w : List I) (μ : Y) (w' : List I) :
    E R v i * (minusHom R v (monomial k w) * K R v μ * plusHom R v (monomial k w')) ∈
      triangularSpan R v := by
  induction w generalizing μ w' with
  | nil =>
    have hEK : E R v i * K R v μ = v ^ (-R.root i μ) • (K R v μ * E R v i) := by
      rw [K_mul_E, smul_smul, ← zpow_add₀ hv, neg_add_cancel, zpow_zero, one_smul]
    rw [monomial_nil, map_one, one_mul, ← mul_assoc, hEK, smul_mul_assoc, mul_assoc,
      ← plusHom_θ R v (k := k) i, ← map_mul, ← monomial_cons, ← one_mul (K R v μ),
      ← map_one (minusHom R v), ← monomial_nil]
    exact Submodule.smul_mem _ _ (mem_triangularSpan _ _ _)
  | cons j w ih =>
    have h := E_mul_F_sub R v i j
    rw [sub_eq_iff_eq_add] at h
    set X := minusHom R v (monomial k w) * K R v μ * plusHom R v (monomial k w')
    have hX : E R v i * (minusHom R v (monomial k (j :: w)) * K R v μ *
        plusHom R v (monomial k w')) = F R v j * (E R v i * X) +
          (if i = j then (v ^ D.d i - (v ^ D.d i)⁻¹)⁻¹ • (Kt R v i - K R v (-ktilde R i))
            else 0) * X := by
      calc E R v i * (minusHom R v (monomial k (j :: w)) * K R v μ *
            plusHom R v (monomial k w')) = (E R v i * F R v j) * X := by
            simp only [X, monomial_cons, map_mul, minusHom_θ, mul_assoc]
        _ = _ := by rw [h, add_mul, add_comm, mul_assoc]
    rw [hX]
    refine Submodule.add_mem _ (F_mul_mem_triangularSpan j (ih μ w')) ?_
    split_ifs
    · rw [smul_mul_assoc, sub_mul]
      exact Submodule.smul_mem _ _ (Submodule.sub_mem _
        (K_mul_mem_triangularSpan _ (mem_triangularSpan _ _ _))
        (K_mul_mem_triangularSpan _ (mem_triangularSpan _ _ _)))
    · rw [zero_mul]; exact Submodule.zero_mem _

/-- `U` is spanned by the products `y⁻ K_μ x⁺` of monomials `x, y ∈ 'f` and `μ ∈ Y`; i.e. the
multiplication map `U⁻ ⊗ U⁰ ⊗ U⁺ → U` is surjective ([Jan] 4.21 (check)). -/
theorem span_triangular (hv : v ≠ 0) : triangularSpan R v = ⊤ := by
  have key : ∀ u : QuantumGroup R v, ∀ s ∈ triangularSpan R v, u * s ∈ triangularSpan R v := by
    intro u
    induction u using induction_on with
    | algebraMap c =>
      intro s hs; rw [← Algebra.smul_def]; exact Submodule.smul_mem _ _ hs
    | E i =>
      intro s hs
      induction hs using Submodule.span_induction with
      | mem x hx =>
        obtain ⟨w, μ, w', rfl⟩ := hx
        exact E_mul_mem_triangularSpan hv i w μ w'
      | zero => simp
      | add x y _ _ hx hy => rw [mul_add]; exact Submodule.add_mem _ hx hy
      | smul c x _ hx => rw [mul_smul_comm]; exact Submodule.smul_mem _ _ hx
    | F i => exact fun s hs ↦ F_mul_mem_triangularSpan i hs
    | K μ => exact fun s hs ↦ K_mul_mem_triangularSpan μ hs
    | add x y hx hy => intro s hs; rw [add_mul]; exact Submodule.add_mem _ (hx s hs) (hy s hs)
    | mul x y hx hy => intro s hs; rw [mul_assoc]; exact hx _ (hy s hs)
  refine eq_top_iff.2 fun u _ ↦ ?_
  have h1 : (1 : QuantumGroup R v) ∈ triangularSpan R v := by
    simpa using mem_triangularSpan (R := R) (v := v) [] 0 []
  simpa using key u 1 h1

end QuantumGroup
