/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import Mathlib.RingTheory.SimpleModule.Basic
import LieLean.Algebra.QuantumGroup.Sl2
import LieLean.Algebra.QuantumGroup.TriangularDecomposition

/-!
# Quantum Verma modules and the simple modules `L_q(Λ)`

Let `U = U_q(𝔤)` (`QuantumGroup R v`), `v` not a root of unity, and `Λ ∈ X = Hom(Y, ℤ)`. The
Verma module ([Jan] 5.5 (check), [Lus] 3.4.5 (check)) is
`M_q(Λ) = U ⧸ (Σᵢ U Eᵢ + Σ_μ U (K_μ - v^{⟨μ, Λ⟩}))`, generated by the class `v_Λ` of `1`, a
weight vector of weight `Λ` annihilated by all `Eᵢ`.

Using the triangular decomposition `U ≅ U⁻ ⊗ U⁰ ⊗ U⁺` (`QuantumGroup.triangularEquiv`) we show
that `y ↦ y⁻ v_Λ` induces a linear isomorphism `'f ⧸ J ≃ M_q(Λ)`, `J` the ideal generated by the
quantum Serre elements (`QuantumGroup.VermaModule.equivSerreQuotient`): `M_q(Λ)` is free of rank one
over `U⁻ ≅ 'f ⧸ J`. The element `y⁻ v_Λ`, `y ∈ 'f_ν`, has weight `Λ - Σᵢ νᵢ i'`, and for an
`X`-regular root datum the weight spaces are exactly `M_q(Λ)^{Λ - ν} = ('f_ν)⁻ v_Λ`
(`QuantumGroup.VermaModule.weightSpace_eq_map`).

The functional `m ↦` (coefficient of `v_Λ`) defines the largest submodule
`M'_q(Λ) = {m | the coefficient of v_Λ in u m vanishes for all u ∈ U}`; for an `X`-regular root
datum every proper submodule is contained in it (`QuantumGroup.VermaModule.le_maxSubmodule`),
so it is the unique maximal submodule and `L_q(Λ) = M_q(Λ) ⧸ M'_q(Λ)` is simple
(`QuantumGroup.IrreducibleModule.isSimpleModule`). The key step is that `U⁰` separates the weights
`Λ - ν`, `ν ∈ ℕ[I]` (`QuantumGroup.VermaModule.exists_zeroHom_smul_eq`).

## Main definitions

* `QuantumGroup.vermaIdeal`, `QuantumGroup.VermaModule R v Λ`, `QuantumGroup.VermaModule.hwv`.
* `QuantumGroup.VermaModule.toVerma`: `'f → M_q(Λ)`, `y ↦ y⁻ v_Λ`.
* `QuantumGroup.VermaModule.hwCoord`: the coefficient of `v_Λ`.
* `QuantumGroup.VermaModule.maxSubmodule`: the maximal submodule `M'_q(Λ)`.
* `QuantumGroup.IrreducibleModule R v Λ`: `L_q(Λ) = M_q(Λ) ⧸ M'_q(Λ)`.

## Main results

* `QuantumGroup.VermaModule.equivSerreQuotient`: `'f ⧸ J ≃ₗ[k] M_q(Λ)`, `[y] ↦ y⁻ v_Λ`.
* `QuantumGroup.VermaModule.toVerma_eq_zero_iff`: `y⁻ v_Λ = 0 ↔ y ∈ J`.
* `QuantumGroup.VermaModule.toVerma_mem_weightSpace`,
  `QuantumGroup.VermaModule.weightSpace_eq_map`, `QuantumGroup.VermaModule.weightSpace_eq_bot`,
  `QuantumGroup.VermaModule.finiteDimensional_weightSpace`,
  `QuantumGroup.VermaModule.iSup_weightSpace_eq_top`: weight spaces of `M_q(Λ)`.
* `QuantumGroup.VermaModule.le_maxSubmodule`, `QuantumGroup.VermaModule.isCoatom_maxSubmodule`.
* `QuantumGroup.IrreducibleModule.isSimpleModule`: `L_q(Λ)` is simple.

## References

* [Jan] J. C. Jantzen, *Lectures on quantum groups*, GSM 6, Ch. 5.
* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, §3.4.
-/

noncomputable section

open LusztigF TensorProduct

namespace LusztigF

variable {k I : Type*} [Field k]

/-- The projection of `'f` onto `'f_ν` along the other weight spaces. -/
def weightProj (ν : I →₀ ℕ) : LusztigF k I →ₗ[k] LusztigF k I where
  toFun y := (gradingHom k I y).coeff ν
  map_add' y z := by simp
  map_smul' c y := by simp

lemma weightProj_of_mem [DecidableEq (I →₀ ℕ)] {ν ν₀ : I →₀ ℕ} {y : LusztigF k I}
    (hy : y ∈ weightSpace k ν) : weightProj ν₀ y = if ν = ν₀ then y else 0 := by
  simp only [weightProj, LinearMap.coe_mk, AddHom.coe_mk, gradingHom_of_mem hy]
  by_cases h : ν = ν₀
  · simp [h, AddMonoidAlgebra.coeff_single]
  · simp [h, Ne.symm h, AddMonoidAlgebra.coeff_single]

lemma weightProj_mem (ν : I →₀ ℕ) (y : LusztigF k I) : weightProj ν y ∈ weightSpace k ν := by
  classical
  have hy : y ∈ ⨆ μ, weightSpace k (I := I) μ := by rw [iSup_weightSpace]; trivial
  induction hy using Submodule.iSup_induction' with
  | mem μ y hy =>
    rw [weightProj_of_mem hy]
    split_ifs with h
    · exact h ▸ hy
    · exact Submodule.zero_mem _
  | zero => simp
  | add y z _ _ hy hz => rw [map_add]; exact Submodule.add_mem _ hy hz

/-- `'f_0 = k`. -/
lemma eq_algebraMap_of_mem_weightSpace_zero {y : LusztigF k I} (hy : y ∈ weightSpace k 0) :
    y = algebraMap k _ (counit y) := by
  induction hy using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨w, hw, rfl⟩ := hy
    cases w with
    | nil => simp [monomial]
    | cons l w =>
      exfalso
      have := congr($hw l)
      simp at this
  | zero => simp
  | add y z _ _ hy hz => rw [map_add, map_add, ← hy, ← hz]
  | smul c y _ hy => rw [map_smul counit, smul_eq_mul, map_mul, ← hy, Algebra.smul_def]

lemma counit_weightProj_zero (y : LusztigF k I) : counit (weightProj 0 y) = counit y := by
  classical
  have hy : y ∈ ⨆ μ, weightSpace k (I := I) μ := by rw [iSup_weightSpace]; trivial
  induction hy using Submodule.iSup_induction' with
  | mem μ y hy =>
    rw [weightProj_of_mem hy]
    split_ifs with h
    · rfl
    · rw [counit_eq_zero_of_mem h hy, map_zero]
  | zero => simp
  | add y z _ _ hy hz => rw [map_add, map_add, hy, hz, map_add]

end LusztigF

namespace QuantumGroup

variable {k I Y : Type*} [Field k] [AddCommGroup Y] [DecidableEq I] {D : LusztigCartanDatum I}
  (R : D.RootDatum Y) (v : k)

/-- The left ideal `Σᵢ U Eᵢ + Σ_μ U (K_μ - v^{⟨μ, Λ⟩})` of `U`. -/
def vermaIdeal (Λ : Y →+ ℤ) : Submodule (QuantumGroup R v) (QuantumGroup R v) :=
  Submodule.span _ (Set.range (E R v) ∪
    Set.range fun μ ↦ K R v μ - algebraMap k (QuantumGroup R v) (v ^ Λ μ))

/-- The quantum Verma module `M_q(Λ) = U ⧸ (Σᵢ U Eᵢ + Σ_μ U (K_μ - v^{⟨μ, Λ⟩}))`
([Jan] 5.5 (check), [Lus] 3.4.5 (check)). -/
abbrev VermaModule (Λ : Y →+ ℤ) : Type _ := QuantumGroup R v ⧸ vermaIdeal R v Λ

namespace VermaModule

variable (Λ : Y →+ ℤ)

/-- The highest weight vector `v_Λ`, the class of `1`. -/
def hwv : VermaModule R v Λ := Submodule.Quotient.mk 1

variable {R v Λ}

lemma mk_eq_smul_hwv (u : QuantumGroup R v) :
    (Submodule.Quotient.mk u : VermaModule R v Λ) = u • hwv R v Λ := by
  rw [hwv, ← Submodule.Quotient.mk_smul, smul_eq_mul, mul_one]

@[simp] lemma E_smul_hwv (i : I) : E R v i • hwv R v Λ = 0 := by
  rw [← mk_eq_smul_hwv, Submodule.Quotient.mk_eq_zero]
  exact Submodule.subset_span (Or.inl ⟨i, rfl⟩)

lemma K_smul_hwv (μ : Y) : K R v μ • hwv R v Λ = v ^ Λ μ • hwv R v Λ := by
  rw [← sub_eq_zero, ← algebraMap_smul (QuantumGroup R v), ← sub_smul, ← mk_eq_smul_hwv,
    Submodule.Quotient.mk_eq_zero]
  exact Submodule.subset_span (Or.inr ⟨μ, rfl⟩)

lemma hwv_mem_weightSpace : hwv R v Λ ∈ weightSpace R v (VermaModule R v Λ) Λ := K_smul_hwv

lemma plusHom_smul_hwv (x : LusztigF k I) :
    plusHom R v x • hwv R v Λ = LusztigF.counit x • hwv R v Λ := by
  induction x using FreeAlgebra.induction with
  | grade0 c => rw [AlgHom.commutes, algebraMap_smul, LusztigF.counit_algebraMap]
  | grade1 i => rw [plusHom_θ, E_smul_hwv, LusztigF.counit_θ, zero_smul]
  | mul a b ha hb => rw [map_mul, mul_smul, hb, smul_comm, ha, smul_smul, map_mul, mul_comm]
  | add a b ha hb => rw [map_add, add_smul, ha, hb, map_add, add_smul]

variable (R v Λ) in
/-- The map `'f → M_q(Λ)`, `y ↦ y⁻ v_Λ`. -/
def toVerma : LusztigF k I →ₗ[k] VermaModule R v Λ :=
  ((LinearMap.toSpanSingleton (QuantumGroup R v) _ (hwv R v Λ)).restrictScalars k).comp
    (minusHom R v).toLinearMap

lemma toVerma_apply (y : LusztigF k I) : toVerma R v Λ y = minusHom R v y • hwv R v Λ := rfl

@[simp] lemma toVerma_one : toVerma R v Λ 1 = hwv R v Λ := by simp [toVerma_apply]

lemma toVerma_algebraMap (c : k) : toVerma R v Λ (algebraMap k _ c) = c • hwv R v Λ := by
  rw [toVerma_apply, AlgHom.commutes, algebraMap_smul]

variable [NeZero v]

/-- `y⁻ v_Λ` has weight `Λ - Σᵢ νᵢ i'` for `y ∈ 'f_ν`. -/
theorem toVerma_mem_weightSpace {ν : I →₀ ℕ} {y : LusztigF k I}
    (hy : y ∈ LusztigF.weightSpace k ν) :
    toVerma R v Λ y ∈ QuantumGroup.weightSpace R v (VermaModule R v Λ) (Λ - R.rootSum ν) := by
  induction hy using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨w, rfl, rfl⟩ := hy
    induction w with
    | nil => simpa [monomial] using hwv_mem_weightSpace
    | cons j w ih =>
      rw [monomial_cons, toVerma_apply, map_mul, mul_smul, minusHom_θ, ← toVerma_apply,
        wordWeight_cons, R.rootSum_add, R.rootSum_single, one_smul, add_comm, ← sub_sub]
      exact F_smul_mem_weightSpace ih j
  | zero => simp
  | add y z _ _ hy hz => rw [map_add]; exact Submodule.add_mem _ hy hz
  | smul c y _ hy => rw [map_smul]; exact Submodule.smul_mem _ _ hy

omit [NeZero v] in
theorem iSup_map_toVerma :
    ⨆ ν, (LusztigF.weightSpace k (I := I) ν).map (toVerma R v Λ) =
    LinearMap.range (toVerma R v Λ) := by
  rw [← Submodule.map_iSup, LusztigF.iSup_weightSpace, Submodule.map_top]

/-- `U⁰` separates the weight spaces of `M_q(Λ)` (our formulation of the standard argument,
[Jan] 5.5 (check)): for an `X`-regular root datum and `ν₀ ∈ ℕ[I]`, the `ν₀`-component of
`y⁻ v_Λ` is `g · y⁻ v_Λ` for some `g ∈ k[Y] ≅ U⁰` acting by `1` on the weight `Λ - Σ ν₀ᵢ i'`. -/
theorem exists_zeroHom_smul_eq (hR : R.IsXRegular) (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1)
    (ν₀ : I →₀ ℕ) (y : LusztigF k I) :
    ∃ g, charHom v (Λ - R.rootSum ν₀) g = 1 ∧
      zeroHom R v g • toVerma R v Λ y = toVerma R v Λ (weightProj ν₀ y) := by
  classical
  have hy : y ∈ ⨆ μ, LusztigF.weightSpace k (I := I) μ := by rw [LusztigF.iSup_weightSpace]; trivial
  induction hy using Submodule.iSup_induction' with
  | mem ν y hy =>
    rw [weightProj_of_mem hy]
    split_ifs with h
    · exact ⟨1, map_one _, by rw [map_one, one_smul]⟩
    · have hne : Λ - R.rootSum ν₀ ≠ Λ - R.rootSum ν := fun e ↦ by
        obtain ⟨μ, hμ⟩ := R.exists_rootSum_ne hR h
        have := congr($e μ)
        simp only [AddMonoidHom.sub_apply] at this
        omega
      obtain ⟨g, hg1, hg2⟩ := exists_charHom_eq_one_eq_zero hv' hne
      exact ⟨g, hg1, by rw [zeroHom_smul_of_mem_weightSpace (toVerma_mem_weightSpace hy), hg2,
        zero_smul, map_zero]⟩
  | zero => exact ⟨1, map_one _, by simp⟩
  | add y z _ _ hy hz =>
    obtain ⟨g₁, hg₁, hy⟩ := hy
    obtain ⟨g₂, hg₂, hz⟩ := hz
    refine ⟨g₁ * g₂, by rw [map_mul, hg₁, hg₂, one_mul], ?_⟩
    have h₁ := zeroHom_smul_of_mem_weightSpace (M := VermaModule R v Λ)
      (toVerma_mem_weightSpace (Λ := Λ) (weightProj_mem ν₀ y))
    have h₂ := zeroHom_smul_of_mem_weightSpace (M := VermaModule R v Λ)
      (toVerma_mem_weightSpace (Λ := Λ) (weightProj_mem ν₀ z))
    have e1 : zeroHom R v (g₁ * g₂) • toVerma R v Λ y =
        zeroHom R v g₂ • zeroHom R v g₁ • toVerma R v Λ y := by
      rw [← mul_smul, ← map_mul, mul_comm]
    have e2 : zeroHom R v (g₁ * g₂) • toVerma R v Λ z =
        zeroHom R v g₁ • zeroHom R v g₂ • toVerma R v Λ z := by
      rw [← mul_smul, ← map_mul]
    rw [map_add, map_add, map_add, smul_add, e1, e2, hy, hz, h₁, h₂, hg₁, hg₂, one_smul,
      one_smul]

/-! ### `M_q(Λ) ≅ 'f ⧸ J` -/

section Equiv

variable (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1)

include hv' in
lemma serreSubmodule_le_ker_toVerma :
    serreSubmodule D v ≤ LinearMap.ker (toVerma R v Λ) := fun y hy ↦ by
  rw [LinearMap.mem_ker, toVerma_apply, (TwoSidedIdeal.mem_ker _).1
    (serreIdeal_le_ker_minusHom (R := R) (NeZero.ne v) hv' (mem_serreSubmodule.1 hy)), zero_smul]

variable (Λ) in
/-- The map `'f ⧸ J → M_q(Λ)`, `[y] ↦ y⁻ v_Λ`. -/
def ofSerreQuotient : (LusztigF k I ⧸ serreSubmodule D v) →ₗ[k] VermaModule R v Λ :=
  (serreSubmodule D v).liftQ (toVerma R v Λ) (serreSubmodule_le_ker_toVerma hv')

omit [DecidableEq I] in
variable (D v Λ) in
/-- The linear map `'f ⊗ k[Y] ⊗ 'f → 'f ⧸ J`, `y ⊗ g ⊗ x ↦ Λ(g) ε(x) [y]`. -/
def triCoord : TriSpace k I Y →ₗ[k] LusztigF k I ⧸ serreSubmodule D v :=
  (serreSubmodule D v).mkQ ∘ₗ (TensorProduct.rid k _).toLinearMap ∘ₗ
    TensorProduct.map LinearMap.id ((TensorProduct.lid k k).toLinearMap ∘ₗ
      TensorProduct.map (charHom v Λ).toLinearMap LusztigF.counit.toLinearMap)

omit [DecidableEq I] in
lemma triCoord_tmul (y : LusztigF k I) (g : AddMonoidAlgebra k Y) (x : LusztigF k I) :
    triCoord D v Λ (y ⊗ₜ (g ⊗ₜ x)) =
      (charHom v Λ g * LusztigF.counit x) • Submodule.Quotient.mk (p := serreSubmodule D v) y := by
  simp [triCoord]

omit [DecidableEq I] in
lemma serreTriSubmodule_le_ker_triCoord :
    serreTriSubmodule Y D v ≤ LinearMap.ker (triCoord D v Λ) := by
  rw [serreTriSubmodule, Submodule.span_le]
  rintro _ ⟨y, g, x, rfl, h | h⟩
  · simp [triCoord_tmul, (Submodule.Quotient.mk_eq_zero _).2 (mem_serreSubmodule.2 h)]
  · simp [triCoord_tmul, counit_eq_zero_of_mem_serreIdeal h]

variable (Λ) in
/-- The linear map `U → 'f ⧸ J`, `y⁻ K_μ x⁺ ↦ v^{⟨μ, Λ⟩} ε(x) [y]`, defined through the
triangular decomposition. -/
def coordAux : QuantumGroup R v →ₗ[k] LusztigF k I ⧸ serreSubmodule D v :=
  (serreTriSubmodule Y D v).liftQ (triCoord D v Λ) serreTriSubmodule_le_ker_triCoord ∘ₗ
    (triangularEquiv R v hv').symm.toLinearMap

lemma coordAux_triangular (y : LusztigF k I) (g : AddMonoidAlgebra k Y) (x : LusztigF k I) :
    coordAux Λ hv' (minusHom R v y * zeroHom R v g * plusHom R v x) =
      (charHom v Λ g * LusztigF.counit x) • Submodule.Quotient.mk (p := serreSubmodule D v) y := by
  rw [← triangularEquiv_mk R v hv', coordAux, LinearMap.comp_apply, LinearEquiv.coe_coe,
    LinearEquiv.symm_apply_apply, Submodule.liftQ_apply, triCoord_tmul]

lemma coordAux_triangular' (y : LusztigF k I) (μ : Y) (x : LusztigF k I) :
    coordAux Λ hv' (minusHom R v y * K R v μ * plusHom R v x) =
      (v ^ Λ μ * LusztigF.counit x) • Submodule.Quotient.mk (p := serreSubmodule D v) y := by
  rw [← zeroHom_single, coordAux_triangular, charHom_single, one_mul]

omit [NeZero v] in
lemma mem_triangularSpan_of (u : QuantumGroup R v) (hv : v ≠ 0) : u ∈ triangularSpan R v := by
  rw [span_triangular (R := R) hv]; trivial

/-- `M_q(Λ) = U⁻ v_Λ`. -/
theorem range_toVerma : LinearMap.range (toVerma R v Λ) = ⊤ := by
  rw [eq_top_iff]
  rintro m -
  obtain ⟨u, rfl⟩ := Submodule.Quotient.mk_surjective _ m
  induction mem_triangularSpan_of u (NeZero.ne v) using Submodule.span_induction with
  | mem u hu =>
    obtain ⟨w, μ, w', rfl⟩ := hu
    refine ⟨(v ^ Λ μ * LusztigF.counit (monomial k w')) • monomial k w, ?_⟩
    rw [map_smul, toVerma_apply, mk_eq_smul_hwv, mul_smul, mul_smul, plusHom_smul_hwv]
    rw [mul_smul, smul_comm (K R v μ), K_smul_hwv, smul_comm (minusHom R v _),
      smul_comm (minusHom R v _), smul_comm (v ^ Λ μ)]
  | zero => exact Submodule.zero_mem _
  | add x y _ _ hx hy => rw [Submodule.Quotient.mk_add]; exact Submodule.add_mem _ hx hy
  | smul c x _ hx => rw [Submodule.Quotient.mk_smul]; exact Submodule.smul_mem _ _ hx

lemma coordAux_mul_E (u : QuantumGroup R v) (i : I) : coordAux Λ hv' (u * E R v i) = 0 := by
  induction mem_triangularSpan_of u (NeZero.ne v) using Submodule.span_induction with
  | mem u hu =>
    obtain ⟨w, μ, w', rfl⟩ := hu
    rw [mul_assoc, ← plusHom_θ R v (k := k) i, ← map_mul, coordAux_triangular', map_mul,
      LusztigF.counit_θ, mul_zero, mul_zero, zero_smul]
  | zero => simp
  | add x y _ _ hx hy => rw [add_mul, map_add, hx, hy, add_zero]
  | smul c x _ hx => rw [smul_mul_assoc, map_smul, hx, smul_zero]

lemma plusHom_mul_K (x : LusztigF k I) (ν : Y) :
    plusHom R v x * K R v ν = K R v ν * plusHom R v (tau R v ν x) := by
  induction x using FreeAlgebra.induction with
  | grade0 c => simp [Algebra.commutes]
  | grade1 j =>
    rw [tau_apply_θ, map_smul, plusHom_θ, E_mul_K (NeZero.ne v), mul_smul_comm]
  | mul a b ha hb => rw [map_mul, mul_assoc, hb, ← mul_assoc, ha, mul_assoc, map_mul, map_mul]
  | add a b ha hb => rw [map_add, add_mul, ha, hb, map_add, map_add, mul_add]

lemma coordAux_mul_K (u : QuantumGroup R v) (ν : Y) :
    coordAux Λ hv' (u * K R v ν) = v ^ Λ ν • coordAux Λ hv' u := by
  induction mem_triangularSpan_of u (NeZero.ne v) using Submodule.span_induction with
  | mem u hu =>
    obtain ⟨w, μ, w', rfl⟩ := hu
    rw [mul_assoc, plusHom_mul_K, ← mul_assoc, mul_assoc (minusHom R v _), K_add,
      coordAux_triangular', coordAux_triangular', tau, LusztigF.counit_diagTwist, smul_smul,
      map_add, zpow_add₀ (NeZero.ne v)]
    ring_nf
  | zero => simp
  | add x y _ _ hx hy => rw [add_mul, map_add, hx, hy, map_add, smul_add]
  | smul c x _ hx => rw [smul_mul_assoc, map_smul, hx, map_smul, smul_comm]

lemma coordAux_mul_of_mem {z : QuantumGroup R v} (hz : z ∈ vermaIdeal R v Λ)
    (u : QuantumGroup R v) : coordAux Λ hv' (u * z) = 0 := by
  induction hz using Submodule.span_induction generalizing u with
  | mem z hz =>
    rcases hz with ⟨i, rfl⟩ | ⟨μ, rfl⟩
    · exact coordAux_mul_E hv' u i
    · rw [mul_sub, map_sub, coordAux_mul_K, ← Algebra.commutes, ← Algebra.smul_def, map_smul,
        sub_self]
  | zero => simp
  | add x y _ _ hx hy => rw [mul_add, map_add, hx, hy, add_zero]
  | smul a x _ hx => rw [smul_eq_mul, ← mul_assoc, hx]

variable (Λ) in
/-- The map `M_q(Λ) → 'f ⧸ J`, inverse to `ofSerreQuotient`. -/
def ofVerma : VermaModule R v Λ →ₗ[k] LusztigF k I ⧸ serreSubmodule D v :=
  ((vermaIdeal R v Λ).restrictScalars k).liftQ (coordAux Λ hv')
      (fun z hz ↦ by simpa using coordAux_mul_of_mem hv' hz 1) ∘ₗ
    (Submodule.Quotient.restrictScalarsEquiv k (vermaIdeal R v Λ)).symm.toLinearMap

lemma ofVerma_mk (u : QuantumGroup R v) :
    ofVerma Λ hv' (Submodule.Quotient.mk u) = coordAux Λ hv' u := by
  simp [ofVerma]

variable (Λ) in
/-- **The Verma module is free of rank one over `U⁻`** ([Jan] 5.5 (check), [Lus] 3.4.5 (check)):
`[y] ↦ y⁻ v_Λ` is a linear isomorphism `'f ⧸ J ≃ M_q(Λ)`, `J` the ideal of `'f` generated by the
quantum Serre elements. Requires `v` not a root of unity. -/
def equivSerreQuotient : (LusztigF k I ⧸ serreSubmodule D v) ≃ₗ[k] VermaModule R v Λ :=
  LinearEquiv.ofLinearMap (ofSerreQuotient Λ hv') (ofVerma Λ hv')
    (by
      refine LinearMap.ext fun m ↦ ?_
      obtain ⟨u, rfl⟩ := Submodule.Quotient.mk_surjective _ m
      induction mem_triangularSpan_of u (NeZero.ne v) using Submodule.span_induction with
      | mem u hu =>
        obtain ⟨w, μ, w', rfl⟩ := hu
        rw [LinearMap.comp_apply, ofVerma_mk, coordAux_triangular', map_smul, ofSerreQuotient,
          Submodule.liftQ_apply, toVerma_apply, LinearMap.id_apply, mk_eq_smul_hwv, mul_smul,
          mul_smul, plusHom_smul_hwv]
        rw [mul_smul, smul_comm (K R v μ), K_smul_hwv, smul_comm (minusHom R v _),
          smul_comm (minusHom R v _), smul_comm (v ^ Λ μ)]
      | zero => simp
      | add x y _ _ hx hy =>
        rw [Submodule.Quotient.mk_add, map_add, map_add, hx, hy]
      | smul c x _ hx =>
        rw [Submodule.Quotient.mk_smul, map_smul, map_smul, hx])
    (by
      refine Submodule.linearMap_qext _ (LinearMap.ext fun y ↦ ?_)
      have e : minusHom R v y = minusHom R v y * zeroHom R v 1 * plusHom R v 1 := by simp
      rw [LinearMap.comp_apply, LinearMap.comp_apply, Submodule.mkQ_apply, ofSerreQuotient,
        Submodule.liftQ_apply, toVerma_apply, ← mk_eq_smul_hwv, ofVerma_mk, e,
        coordAux_triangular]
      simp)

@[simp] theorem equivSerreQuotient_mk (y : LusztigF k I) :
    equivSerreQuotient Λ hv' (Submodule.Quotient.mk y) = minusHom R v y • hwv R v Λ := rfl

include hv' in
/-- `y⁻ v_Λ = 0` iff `y` lies in the Serre ideal `J`. Requires `v` not a root of unity. -/
theorem toVerma_eq_zero_iff (y : LusztigF k I) :
    toVerma R v Λ y = 0 ↔ y ∈ serreIdeal D v := by
  rw [← mem_serreSubmodule, ← Submodule.Quotient.mk_eq_zero,
    ← (equivSerreQuotient Λ hv').map_eq_zero_iff, equivSerreQuotient_mk, toVerma_apply]

include hv' in
theorem toVerma_surjective : Function.Surjective (toVerma R v Λ) := fun m ↦ by
  obtain ⟨q, rfl⟩ := (equivSerreQuotient Λ hv').surjective m
  obtain ⟨y, rfl⟩ := Submodule.Quotient.mk_surjective _ q
  exact ⟨y, rfl⟩

include hv' in
/-- The weight spaces of `M_q(Λ)` ([Jan] 5.5 (check), [Lus] 3.4.5 (check)): for an `X`-regular
root datum, `M_q(Λ)^{Λ - ν} = ('f_ν)⁻ v_Λ`. -/
theorem weightSpace_eq_map (hR : R.IsXRegular) (ν : I →₀ ℕ) :
    QuantumGroup.weightSpace R v (VermaModule R v Λ) (Λ - R.rootSum ν) =
      (LusztigF.weightSpace k ν).map (toVerma R v Λ) := by
  refine le_antisymm (fun m hm ↦ ?_) ?_
  · obtain ⟨y, rfl⟩ := toVerma_surjective hv' m
    obtain ⟨g, hg, hgy⟩ := exists_zeroHom_smul_eq hR hv' ν y
    rw [zeroHom_smul_of_mem_weightSpace hm, hg, one_smul] at hgy
    exact ⟨_, weightProj_mem ν y, hgy.symm⟩
  · rw [Submodule.map_le_iff_le_comap]
    exact fun y hy ↦ toVerma_mem_weightSpace hy

/-- `M_q(Λ)` is a weight module. -/
theorem iSup_weightSpace_eq_top :
    ⨆ Λ', QuantumGroup.weightSpace R v (VermaModule R v Λ) Λ' = ⊤ := by
  rw [eq_top_iff, ← range_toVerma, ← iSup_map_toVerma]
  exact iSup_le fun ν ↦ Submodule.map_le_iff_le_comap.2 fun y hy ↦
    Submodule.mem_iSup_of_mem _ (toVerma_mem_weightSpace hy)

omit [DecidableEq I] [NeZero v] in
variable (D v) in
/-- The counit `'f ⧸ J → k`. -/
def counitQ : (LusztigF k I ⧸ serreSubmodule D v) →ₗ[k] k :=
  (serreSubmodule D v).liftQ LusztigF.counit.toLinearMap
    (fun _ hy ↦ LinearMap.mem_ker.2 (counit_eq_zero_of_mem_serreIdeal (mem_serreSubmodule.1 hy)))

omit [DecidableEq I] [NeZero v] in
@[simp] lemma counitQ_mk (y : LusztigF k I) :
    counitQ D v (Submodule.Quotient.mk y) = LusztigF.counit y := rfl

include hv' in
/-- The weights of `M_q(Λ)` lie in `Λ - Σᵢ ℕ i'`: all other weight spaces vanish. Requires `v`
not a root of unity. -/
theorem weightSpace_eq_bot {Λ' : Y →+ ℤ} (h : ∀ ν, Λ' ≠ Λ - R.rootSum ν) :
    QuantumGroup.weightSpace R v (VermaModule R v Λ) Λ' = ⊥ := by
  have htop : ⨆ ν : I →₀ ℕ, QuantumGroup.weightSpace R v (VermaModule R v Λ)
      (Λ - R.rootSum ν) = ⊤ := by
    rw [eq_top_iff, ← range_toVerma, ← iSup_map_toVerma]
    exact iSup_mono fun ν ↦ Submodule.map_le_iff_le_comap.2 fun y hy ↦ toVerma_mem_weightSpace hy
  have hle : ⨆ ν : I →₀ ℕ, QuantumGroup.weightSpace R v (VermaModule R v Λ) (Λ - R.rootSum ν) ≤
      ⨆ Λ'' , ⨆ (_ : Λ'' ≠ Λ'), QuantumGroup.weightSpace R v (VermaModule R v Λ) Λ'' :=
    iSup_le fun ν ↦ le_iSup₂_of_le (Λ - R.rootSum ν) (Ne.symm (h ν)) le_rfl
  have := (iSupIndep_weightSpace (M := VermaModule R v Λ) hv' Λ').mono_right
    (htop.symm.le.trans hle)
  exact disjoint_top.1 this

include hv' in
/-- The weight spaces of `M_q(Λ)` are finite-dimensional. -/
theorem finiteDimensional_weightSpace (hR : R.IsXRegular) (ν : I →₀ ℕ) :
    FiniteDimensional k
      (QuantumGroup.weightSpace R v (VermaModule R v Λ) (Λ - R.rootSum ν)) := by
  rw [weightSpace_eq_map hv' hR]
  infer_instance

variable (Λ) in
/-- The coefficient of `v_Λ`: the linear form `y⁻ v_Λ ↦ ε(y)` on `M_q(Λ)`. -/
def hwCoord : VermaModule R v Λ →ₗ[k] k :=
  counitQ D v ∘ₗ (equivSerreQuotient Λ hv').symm.toLinearMap

@[simp] theorem hwCoord_toVerma (y : LusztigF k I) :
    hwCoord Λ hv' (toVerma R v Λ y) = LusztigF.counit y := by
  rw [hwCoord, LinearMap.comp_apply, toVerma_apply, ← equivSerreQuotient_mk hv',
    LinearEquiv.coe_coe, LinearEquiv.symm_apply_apply, counitQ_mk]

@[simp] theorem hwCoord_hwv : hwCoord Λ hv' (hwv R v Λ) = 1 := by
  rw [← toVerma_one, hwCoord_toVerma, map_one]

/-- The key lemma for the maximal submodule: every submodule `N` of `M_q(Λ)` that contains an
element with nonzero `v_Λ`-coefficient contains `v_Λ`, hence is everything. -/
theorem eq_top_of_hwCoord_ne_zero (hR : R.IsXRegular)
    {N : Submodule (QuantumGroup R v) (VermaModule R v Λ)} {m : VermaModule R v Λ}
    (hm : m ∈ N) (hc : hwCoord Λ hv' m ≠ 0) : N = ⊤ := by
  obtain ⟨y, rfl⟩ := toVerma_surjective hv' m
  obtain ⟨g, -, hgy⟩ := exists_zeroHom_smul_eq hR hv' 0 y
  have e : toVerma R v Λ (weightProj 0 y) = LusztigF.counit y • hwv R v Λ := by
    rw [eq_algebraMap_of_mem_weightSpace_zero (weightProj_mem 0 y), toVerma_algebraMap,
      counit_weightProj_zero]
  rw [e] at hgy
  rw [hwCoord_toVerma] at hc
  have hw : hwv R v Λ ∈ N := by
    have := N.smul_of_tower_mem (LusztigF.counit y)⁻¹ (N.smul_mem (zeroHom R v g) hm)
    rwa [hgy, smul_smul, inv_mul_cancel₀ hc, one_smul] at this
  rw [eq_top_iff]
  intro m _
  obtain ⟨u, rfl⟩ := Submodule.Quotient.mk_surjective _ m
  rw [mk_eq_smul_hwv]
  exact N.smul_mem u hw

end Equiv

/-! ### The maximal submodule and `L_q(Λ)` -/

variable (R v Λ) in
/-- The sum `M'_q(Λ)` of all proper submodules of `M_q(Λ)`; for an `X`-regular root datum and `v`
not a root of unity it is the unique maximal submodule (`isCoatom_maxSubmodule`,
`eq_maxSubmodule_of_isCoatom`). -/
def maxSubmodule : Submodule (QuantumGroup R v) (VermaModule R v Λ) :=
  sSup {N | N ≠ ⊤}

omit [NeZero v] in
theorem le_maxSubmodule {N : Submodule (QuantumGroup R v) (VermaModule R v Λ)} (hN : N ≠ ⊤) :
    N ≤ maxSubmodule R v Λ :=
  le_sSup hN

section Max

variable (hR : R.IsXRegular) (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1)
include hR hv'

/-- `m ∈ M'_q(Λ)` iff the `v_Λ`-coefficient of `u m` vanishes for all `u ∈ U`. -/
theorem mem_maxSubmodule_iff {m : VermaModule R v Λ} :
    m ∈ maxSubmodule R v Λ ↔ ∀ u : QuantumGroup R v, hwCoord Λ hv' (u • m) = 0 := by
  let M' : Submodule (QuantumGroup R v) (VermaModule R v Λ) :=
    { carrier := {m | ∀ u : QuantumGroup R v, hwCoord Λ hv' (u • m) = 0}
      add_mem' := fun ha hb u ↦ by rw [smul_add, map_add, ha u, hb u, add_zero]
      zero_mem' := fun u ↦ by rw [smul_zero, map_zero]
      smul_mem' := fun a m hm u ↦ by rw [smul_smul]; exact hm _ }
  have hM' : M' ≠ ⊤ := fun h ↦ by
    have : hwv R v Λ ∈ M' := by rw [h]; trivial
    simpa using this 1
  have h1 : maxSubmodule R v Λ ≤ M' := sSup_le fun N hN m hm u ↦ by
    by_contra hc
    exact hN (eq_top_of_hwCoord_ne_zero hv' hR (N.smul_mem u hm) hc)
  exact ⟨fun hm ↦ h1 hm, fun hm ↦ le_maxSubmodule hM' hm⟩

theorem hwv_notMem_maxSubmodule : hwv R v Λ ∉ maxSubmodule R v Λ := fun h ↦ by
  simpa using (mem_maxSubmodule_iff hR hv').1 h 1

theorem maxSubmodule_ne_top : maxSubmodule R v Λ ≠ ⊤ := fun h ↦
  hwv_notMem_maxSubmodule hR hv' (by rw [h]; trivial)

/-- `M'_q(Λ)` is a maximal submodule. -/
theorem isCoatom_maxSubmodule : IsCoatom (maxSubmodule R v Λ) :=
  ⟨maxSubmodule_ne_top hR hv', fun _ hN ↦ by
    by_contra h
    exact hN.not_ge (le_maxSubmodule h)⟩

/-- `M'_q(Λ)` is the unique maximal submodule of `M_q(Λ)`. -/
theorem eq_maxSubmodule_of_isCoatom {N : Submodule (QuantumGroup R v) (VermaModule R v Λ)}
    (hN : IsCoatom N) : N = maxSubmodule R v Λ :=
  ((hN.le_iff_eq (maxSubmodule_ne_top hR hv')).1 (le_maxSubmodule hN.1)).symm

end Max

end VermaModule

end QuantumGroup

namespace QuantumGroup

variable {k I Y : Type*} [Field k] [AddCommGroup Y] [DecidableEq I] {D : LusztigCartanDatum I}
  (R : D.RootDatum Y) (v : k)

/-- The simple module `L_q(Λ) = M_q(Λ) ⧸ M'_q(Λ)` ([Jan] 5.5 (check)). -/
abbrev IrreducibleModule (Λ : Y →+ ℤ) : Type _ :=
  VermaModule R v Λ ⧸ VermaModule.maxSubmodule R v Λ

variable {R v} [NeZero v]

/-- `L_q(Λ)` is a simple `U`-module, for an `X`-regular root datum and `v` not a root of unity. -/
theorem IrreducibleModule.isSimpleModule (hR : R.IsXRegular) (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1)
    (Λ : Y →+ ℤ) : IsSimpleModule (QuantumGroup R v) (IrreducibleModule R v Λ) :=
  isSimpleModule_iff_isCoatom.2 (VermaModule.isCoatom_maxSubmodule hR hv')

end QuantumGroup
