/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.Modified.IntegralPBW
import LieLean.Algebra.QuantumGroup.PBW.IntegralB2
import LieLean.Algebra.QuantumGroup.PBW.RankTwoB2BraidSpan

/-!
# Integral PBW bases with double edges ([Lus] 41.1.4, 41.1.7)

For a pair of nodes `i ≠ j` with `aᵢⱼ = -2`, `aⱼᵢ = -1` (type `B₂`), the `𝒜`-span of the integral
PBW monomials of either reduced word `i j i j`, `j i j i` of the longest element of the rank-two
Weyl group is the `𝒜`-subalgebra generated by the divided powers `Eᵢ^{(n)}`, `Eⱼ^{(n)}`
(`Modified.span_pbwDiv_b2`, `Modified.span_pbwDiv_b2_rev`). The rank-two input is the integral
`B₂` straightening of `PBW/IntegralB2.lean`; the word `j i j i` is treated in the opposite algebra.

Consequently the `B₂` braid move preserves the integral PBW span, and [Lus] 41.1.4 (b), (c) for
`e = 1` and [Lus] 41.1.7 hold for every Cartan datum without a pair `aᵢⱼ aⱼᵢ = 3` (no `G₂`
subdiagram), extending the simply-laced results of `Modified/IntegralPBW.lean`.

## Main results

* `Modified.span_pbwDiv_b2_braid`: the `B₂` braid move preserves the integral PBW span.
* `Modified.span_pbwDiv_of_isReduced_of_mul_ne_three`: [Lus] 41.1.4 (b).
* `Modified.qDivPow_E_mul_mem_span_pbwDiv_of_mul_ne_three`: [Lus] 41.1.4 (c).
* `Modified.span_pbwDiv_longest_eq_of_mul_ne_three`,
  `Modified.coe_span_pbwDiv_longest_of_mul_ne_three`: [Lus] 41.1.7.

## References

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, 41.1.4, 41.1.7.
-/

open LieLean Finset MulOpposite

noncomputable section

namespace LieLean.QuantumGroup

local notation "𝕂" => RatFunc ℚ
local notation "𝕧" => (RatFunc.X : RatFunc ℚ)
local notation "𝒜" => LaurentPolynomial ℤ

attribute [local instance] neZero_ratFunc_X

variable {I Y : Type*} [AddCommGroup Y] [DecidableEq I] {D : LusztigCartanDatum I}
  {R : D.RootDatum Y}

namespace Modified

attribute [local instance] laurentAlgebraK laurentAlgebraU laurentTowerU

omit [DecidableEq I] in
lemma qDivPow_op {A : Type*} [Ring A] [Algebra 𝕂 A] (t : 𝕂) (n : ℕ) (x : A) :
    qDivPow t n (op x) = op (qDivPow t n x) := by
  simp only [qDivPow, op_smul, op_pow]

/-- The rank-two integral subalgebra, as a subring, is the subring generated by the image of `𝒜`
and the divided powers. -/
lemma coe_adjoinPair_eq_genRing {i j : I} (hd : 𝕧 ^ D.d j = (𝕧 ^ D.d i) ^ 2) :
    (adjoinPair (R := R) i j : Set (QuantumGroup R 𝕧)) =
      B2Integral.genRing (𝕧 ^ D.d i) LusztigF.integralLaurentEval.range (E R 𝕧 i)
        (E R 𝕧 j) := by
  rw [← Subalgebra.coe_toSubring, Algebra.adjoin_eq_ring_closure, B2Integral.genRing]
  have h1 : Set.range (algebraMap 𝒜 (QuantumGroup R 𝕧)) =
      algebraMap 𝕂 (QuantumGroup R 𝕧) '' (LusztigF.integralLaurentEval.range : Set 𝕂) := by
    ext x
    constructor
    · rintro ⟨a, rfl⟩; exact ⟨_, ⟨a, rfl⟩, rfl⟩
    · rintro ⟨_, ⟨a, rfl⟩, rfl⟩; exact ⟨a, rfl⟩
  have h2 : Set.range (Ed R j) = Set.range fun n : ℕ ↦ qDivPow ((𝕧 ^ D.d i) ^ 2) n (E R 𝕧 j) := by
    rw [← hd]; rfl
  rw [h1, h2, ← Set.union_assoc]
  rfl

variable {i j : I} (hij : i ≠ j) (h : D.cartanMatrix i j = -2) (h' : D.cartanMatrix j i = -1)

include hij h h' in
/-- **The integral PBW monomials of `i j i j` span the integral form of the rank-two
subalgebra** (type `B₂`). -/
theorem span_pbwDiv_b2 :
    Submodule.span 𝒜 (Set.range (pbwDiv R [i, j, i, j])) =
      (adjoinPair (R := R) i j).toSubmodule := by
  classical
  set q : 𝕂 := 𝕧 ^ D.d i
  set X := braidEj R 𝕧 i j
  set y := b2RootY R 𝕧 i j
  have hd : 𝕧 ^ D.d j = q ^ 2 := parameter_eq_square_of_double_edge h h'
  have hq0 : q ≠ 0 := pow_ne_zero _ (NeZero.ne 𝕧)
  have hqi : ∀ n : ℕ, 0 < n → qInt q n ≠ 0 := fun n hn ↦
    qInt_ne_zero_of_pow_ne_one hq0 (vd_pow_ne_one (D := D) ratFunc_X_not_root i) hn
  have hpi : ∀ n : ℕ, 0 < n → qInt (q ^ 2) n ≠ 0 := fun n hn ↦ by
    rw [← hd]
    exact qInt_ne_zero_of_pow_ne_one (pow_ne_zero _ (NeZero.ne 𝕧))
      (vd_pow_ne_one (D := D) ratFunc_X_not_root j) hn
  have hq : q - q⁻¹ ≠ 0 :=
    sub_inv_ne_zero_of_pow_ne_one hq0 (vd_pow_ne_one (D := D) ratFunc_X_not_root i)
  have h2 : qFactorial q 2 ≠ 0 := qFactorial_vd_ne_zero i 2
  have hF2 : qFactorial q 2 = qInt q 2 := by simp [qFactorial, qInt]
  have H : B2PBW.Rel (q ^ 2) (E R 𝕧 i) (qInt q 2 • X) y (E R 𝕧 j) := by
    have e : qInt q 2 • X = b2RootX R 𝕧 i j := by
      rw [show X = _ from b2_braidEj_eq h, smul_smul, ← hF2, mul_inv_cancel₀ h2, one_smul]
    rw [e]
    exact b2_rel hij h h'
  set Λ : Subring 𝕂 := (LusztigF.integralLaurentEval).range
  have hqΛ : q ∈ Λ := RingHom.mem_range.2 (isLaurent_pow (D.d i))
  have hqΛ' : q⁻¹ ∈ Λ := by
    have := isLaurent_inv_pow (D.d i)
    rw [inv_pow] at this
    exact RingHom.mem_range.2 this
  have hmap : ∀ (f : QuantumGroup R 𝕧 ≃ₐ[𝕂] QuantumGroup R 𝕧) (t : 𝕂) (n : ℕ) (x),
      f (qDivPow t n x) = qDivPow t n (f x) := fun f t n x ↦ map_qDivPow' f.toAlgHom t n x
  set T := braidEquivOfNotRoot R ratFunc_X_not_root
  have Hi := braidEquivOfNotRoot_hasImages ratFunc_X_not_root R i
  have Hj := braidEquivOfNotRoot_hasImages ratFunc_X_not_root R j
  have hT2 : T i (E R 𝕧 j) = X := a2_rootVector_two hij Hi
  have hT3 : T i (T j (E R 𝕧 i)) = y := by
    have e := b2_rootVector_three Hi Hj hij h h' hq
    change T i (T j (E R 𝕧 i)) = _ at e
    rw [e, b2_cc_two hq0 hq, ← b2_qFactorial_two hq0, inv_mul_cancel₀ h2, one_smul,
      BraidDiagonal.X_succ (n := 0), b2_shift_zero]
    rfl
  have hT4 : T i (T j (T i (E R 𝕧 j))) = E R 𝕧 j := b2_rootVector_four Hi Hj hij h h' hq h2
  have hmono : ∀ c : Fin 4 → ℕ, pbwDiv R [i, j, i, j] c =
      B2Integral.M4 q (E R 𝕧 i) X y (E R 𝕧 j) (c 0) (c 1) (c 2) (c 3) := fun c ↦ by
    simp only [CoxeterSystem.pbwDivMonomial, Ta_apply, _root_.map_mul, _root_.map_one, mul_one]
    change Ed R i _ * (T i (Ed R j _) * (T i (T j (Ed R i _)) * T i (T j (T i (Ed R j _))))) = _
    rw [Ed, Ed, Ed, Ed, hmap, hmap, hmap, hmap, hmap, hmap, hT4, hT3, hT2, hd]
    simp only [B2Integral.M4, B2Integral.M3, mul_assoc]
    rfl
  have hconv : ∀ x, x ∈ Submodule.span 𝒜 (Set.range (pbwDiv R [i, j, i, j])) ↔
      x ∈ B2Integral.orderedSpan q Λ (E R 𝕧 i) X y (E R 𝕧 j) := fun x ↦ by
    constructor
    · intro hx
      induction hx using Submodule.span_induction with
      | mem x hx =>
        obtain ⟨c, rfl⟩ := hx
        rw [hmono]; exact B2Integral.M4_mem_orderedSpan _ _ _ _
      | zero => exact zero_mem _
      | add x y _ _ hx hy => exact add_mem hx hy
      | smul a x _ hx =>
        rw [laurent_smul_U]
        exact B2Integral.smul_mem_orderedSpan (RingHom.mem_range.2 ⟨a, rfl⟩) hx
    · intro hx
      induction hx using AddSubgroup.closure_induction with
      | mem x hx =>
        obtain ⟨c, hc, a, b, c', d, rfl⟩ := hx
        obtain ⟨a', rfl⟩ := RingHom.mem_range.1 hc
        rw [← laurent_smul_U, show B2Integral.M4 q (E R 𝕧 i) X y (E R 𝕧 j) a b c' d =
          pbwDiv R [i, j, i, j] ![a, b, c', d] by rw [hmono]; rfl]
        exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨_, rfl⟩)
      | zero => exact zero_mem _
      | add x y _ _ hx hy => exact add_mem hx hy
      | neg x _ hx => exact neg_mem hx
  have hS := B2Integral.coe_orderedSpan_eq_genRing hq0 hqi hpi H hqΛ hqΛ'
  ext x
  rw [hconv, Subalgebra.mem_toSubmodule, ← SetLike.mem_coe, hS, ← coe_adjoinPair_eq_genRing hd]
  exact Iff.rfl

include hij h h' in
/-- **The integral PBW monomials of `j i j i` span the integral form of the rank-two
subalgebra** (type `B₂`; via the opposite algebra). -/
theorem span_pbwDiv_b2_rev :
    Submodule.span 𝒜 (Set.range (pbwDiv R [j, i, j, i])) =
      (adjoinPair (R := R) i j).toSubmodule := by
  classical
  set q : 𝕂 := 𝕧 ^ D.d i
  set y' := b2RevRootY R 𝕧 i j
  set X' := (qFactorial q 2)⁻¹ • b2RevRootX R 𝕧 i j
  have hd : 𝕧 ^ D.d j = q ^ 2 := parameter_eq_square_of_double_edge h h'
  have hq0 : q ≠ 0 := pow_ne_zero _ (NeZero.ne 𝕧)
  have hqi : ∀ n : ℕ, 0 < n → qInt q n ≠ 0 := fun n hn ↦
    qInt_ne_zero_of_pow_ne_one hq0 (vd_pow_ne_one (D := D) ratFunc_X_not_root i) hn
  have hpi : ∀ n : ℕ, 0 < n → qInt (q ^ 2) n ≠ 0 := fun n hn ↦ by
    rw [← hd]
    exact qInt_ne_zero_of_pow_ne_one (pow_ne_zero _ (NeZero.ne 𝕧))
      (vd_pow_ne_one (D := D) ratFunc_X_not_root j) hn
  have hq : q - q⁻¹ ≠ 0 :=
    sub_inv_ne_zero_of_pow_ne_one hq0 (vd_pow_ne_one (D := D) ratFunc_X_not_root i)
  have h2 : qFactorial q 2 ≠ 0 := qFactorial_vd_ne_zero i 2
  have hF2 : qFactorial q 2 = qInt q 2 := by simp [qFactorial, qInt]
  have hS3 := serre_E R 𝕧 hij
  rw [B2PBW.toNat_one_sub_eq_three h] at hS3
  have hS2 := serre_E R 𝕧 hij.symm
  rw [A2PBW.toNat_one_sub_eq_two h', hd] at hS2
  have H : B2PBW.Rel (q ^ 2) (op (E R 𝕧 i)) (qInt q 2 • op X') (op y') (op (E R 𝕧 j)) := by
    have e : qInt q 2 • op X' = op (b2RevRootX R 𝕧 i j) := by
      rw [← op_smul, smul_smul, ← hF2, mul_inv_cancel₀ h2, one_smul]
    rw [e]
    exact B2PBW.rel_op hq0 hS3 hS2
  set Λ : Subring 𝕂 := (LusztigF.integralLaurentEval).range
  have hqΛ : q ∈ Λ := RingHom.mem_range.2 (isLaurent_pow (D.d i))
  have hqΛ' : q⁻¹ ∈ Λ := by
    have := isLaurent_inv_pow (D.d i)
    rw [inv_pow] at this
    exact RingHom.mem_range.2 this
  have hmap : ∀ (f : QuantumGroup R 𝕧 ≃ₐ[𝕂] QuantumGroup R 𝕧) (t : 𝕂) (n : ℕ) (x),
      f (qDivPow t n x) = qDivPow t n (f x) := fun f t n x ↦ map_qDivPow' f.toAlgHom t n x
  set T := braidEquivOfNotRoot R ratFunc_X_not_root
  have Hi := braidEquivOfNotRoot_hasImages ratFunc_X_not_root R i
  have Hj := braidEquivOfNotRoot_hasImages ratFunc_X_not_root R j
  have hY' : T j (E R 𝕧 i) = y' := by
    have e := a2_rootVector_two hij.symm Hj
    change T j (E R 𝕧 i) = _ at e
    rw [e, braidEj_eq_of_cartanMatrix_eq_neg_one h', parameter_eq_square_of_double_edge h h']
    rfl
  have hY : T j (b2RootY R 𝕧 i j) = E R 𝕧 i := by
    rw [b2RootY_eq_X R 𝕧 (j := j)]
    exact b2_T_X_one Hj hij h h' hq h2
  have hX : T j (T i (E R 𝕧 j)) = X' := by
    have e := a2_rootVector_two hij Hi
    change T i (E R 𝕧 j) = _ at e
    rw [e, b2_braidEj_eq h, _root_.map_smul, b2RootX, _root_.map_sub, _root_.map_mul,
      _root_.map_mul, hY, hY']
    rfl
  have hE : T j (T i (T j (E R 𝕧 i))) = E R 𝕧 i := by
    have e := b2_rootVector_three Hi Hj hij h h' hq
    change T i (T j (E R 𝕧 i)) = _ at e
    rw [e, b2_cc_two hq0 hq, ← b2_qFactorial_two hq0, inv_mul_cancel₀ h2, one_smul,
      ← b2RootY_eq_X, hY]
  have hmono : ∀ c : Fin 4 → ℕ, op (pbwDiv R [j, i, j, i] c) =
      B2Integral.M4 q (op (E R 𝕧 i)) (op X') (op y') (op (E R 𝕧 j)) (c 3) (c 2) (c 1)
        (c 0) := fun c ↦ by
    simp only [CoxeterSystem.pbwDivMonomial, Ta_apply, _root_.map_mul, _root_.map_one, mul_one]
    change op (Ed R j _ * (T j (Ed R i _) * (T j (T i (Ed R j _)) *
      T j (T i (T j (Ed R i _)))))) = _
    rw [Ed, Ed, Ed, Ed, hmap, hmap, hmap, hmap, hmap, hmap, hE, hX, hY', hd]
    simp only [B2Integral.M4, B2Integral.M3, qDivPow_op, op_mul, mul_assoc]
    rfl
  have hconv : ∀ x, x ∈ Submodule.span 𝒜 (Set.range (pbwDiv R [j, i, j, i])) ↔
      op x ∈ B2Integral.orderedSpan q Λ (op (E R 𝕧 i)) (op X') (op y') (op (E R 𝕧 j)) := by
    intro x
    constructor
    · intro hx
      induction hx using Submodule.span_induction with
      | mem x hx =>
        obtain ⟨c, rfl⟩ := hx
        rw [hmono]; exact B2Integral.M4_mem_orderedSpan _ _ _ _
      | zero => rw [op_zero]; exact zero_mem _
      | add x y _ _ hx hy => rw [op_add]; exact add_mem hx hy
      | smul a x _ hx =>
        rw [laurent_smul_U, op_smul]
        exact B2Integral.smul_mem_orderedSpan (RingHom.mem_range.2 ⟨a, rfl⟩) hx
    · intro hx
      rw [← unop_op x]
      generalize op x = z at hx
      induction hx using AddSubgroup.closure_induction with
      | mem z hz =>
        obtain ⟨c, hc, a, b, c', d, rfl⟩ := hz
        obtain ⟨a', rfl⟩ := RingHom.mem_range.1 hc
        rw [unop_smul, ← laurent_smul_U, show unop (B2Integral.M4 q (op (E R 𝕧 i)) (op X')
          (op y') (op (E R 𝕧 j)) a b c' d) = pbwDiv R [j, i, j, i] ![d, c', b, a] by
            rw [← unop_op (pbwDiv R [j, i, j, i] _), hmono]; rfl]
        exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨_, rfl⟩)
      | zero => rw [unop_zero]; exact zero_mem _
      | add x y _ _ hx hy => rw [unop_add]; exact add_mem hx hy
      | neg x _ hx => rw [unop_neg]; exact neg_mem hx
  have hS := B2Integral.coe_orderedSpan_eq_genRing hq0 hqi hpi H hqΛ hqΛ'
  have hgen : B2Integral.genRing q Λ (op (E R 𝕧 i)) (op (E R 𝕧 j)) =
      (B2Integral.genRing q Λ (E R 𝕧 i) (E R 𝕧 j)).op := by
    rw [B2Integral.genRing, B2Integral.genRing, Subring.op_closure]
    congr 1
    ext z
    constructor
    · rintro ((⟨c, hc, rfl⟩ | ⟨n, rfl⟩) | ⟨n, rfl⟩)
      · exact Or.inl (Or.inl ⟨c, hc, rfl⟩)
      · exact Or.inl (Or.inr ⟨n, by simp [qDivPow_op]⟩)
      · exact Or.inr ⟨n, by simp [qDivPow_op]⟩
    · rintro ((⟨c, hc, hz⟩ | ⟨n, hz⟩) | ⟨n, hz⟩)
      · exact Or.inl (Or.inl ⟨c, hc, unop_injective hz⟩)
      · exact Or.inl (Or.inr ⟨n, unop_injective (by simpa [qDivPow_op] using hz)⟩)
      · exact Or.inr ⟨n, unop_injective (by simpa [qDivPow_op] using hz)⟩
  ext x
  rw [hconv, Subalgebra.mem_toSubmodule, ← SetLike.mem_coe, hS, hgen, SetLike.mem_coe,
    Subring.mem_op, unop_op, ← SetLike.mem_coe, ← coe_adjoinPair_eq_genRing hd]
  exact Iff.rfl

include hij h h' in
/-- **The `B₂` braid move preserves the integral PBW span.** -/
theorem span_pbwDiv_b2_braid :
    Submodule.span 𝒜 (Set.range (pbwDiv R [i, j, i, j])) =
      Submodule.span 𝒜 (Set.range (pbwDiv R [j, i, j, i])) := by
  rw [span_pbwDiv_b2 hij h h', span_pbwDiv_b2_rev hij h h']

/-! ### Braid moves without triple edges -/

/-- The possible pairs of Cartan entries at a finite Coxeter entry. -/
lemma cartanMatrix_cases (hij : i ≠ j) (hm : D.cartanMatrix.coxeterMatrix i j ≠ 0) :
    (D.cartanMatrix i j = 0 ∧ D.cartanMatrix j i = 0) ∨
      (D.cartanMatrix i j = -1 ∧ D.cartanMatrix j i = -1) ∨
      (D.cartanMatrix i j = -2 ∧ D.cartanMatrix j i = -1) ∨
      (D.cartanMatrix i j = -1 ∧ D.cartanMatrix j i = -2) ∨
      D.cartanMatrix i j * D.cartanMatrix j i = 3 := by
  have hA := D.isGeneralizedCartan_cartanMatrix
  have h1 := hA.offDiag_nonpos i j hij
  have h2 := hA.offDiag_nonpos j i hij.symm
  have hz := hA.zero_comm i j
  rw [Matrix.coxeterMatrix_apply_of_ne _ hij] at hm
  generalize D.cartanMatrix i j = a at *
  generalize D.cartanMatrix j i = b at *
  have hle : a * b ≤ 3 := by
    by_contra hc
    apply hm
    generalize hP : a * b = P at hc
    obtain ⟨n, hn⟩ : ∃ n, P.toNat = n + 4 := ⟨P.toNat - 4, by omega⟩
    rw [hn]
    rfl
  rcases eq_or_lt_of_le h1 with rfl | ha
  · exact Or.inl ⟨rfl, hz.mp rfl⟩
  · have hb : b < 0 := lt_of_le_of_ne h2 fun hb ↦ ha.ne (hz.mpr hb)
    have ha' : -3 ≤ a := by nlinarith
    have hb' : -3 ≤ b := by nlinarith
    interval_cases a <;> interval_cases b <;> simp_all

/-- Under the hypothesis that the integral PBW span is invariant under braid moves, the results
below follow as in the simply-laced case. -/
def BraidInvariant (R : D.RootDatum Y) : Prop :=
  ∀ u w : List I, D.cartanMatrix.coxeterMatrix.BraidMove u w →
    Submodule.span 𝒜 (Set.range (pbwDiv R u)) = Submodule.span 𝒜 (Set.range (pbwDiv R w))

/-- **Braid moves preserve the integral PBW span** for Cartan data without a pair
`aᵢⱼ aⱼᵢ = 3`. -/
theorem braidInvariant_of_mul_ne_three
    (h3 : ∀ i j, D.cartanMatrix i j * D.cartanMatrix j i ≠ 3) : BraidInvariant R := by
  intro u w hm
  obtain ⟨p, s, i, j, hij, hmij, rfl, rfl⟩ := hm
  have hT : ((CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix i j).map (Ta R)).prod =
      ((CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix j i).map (Ta R)).prod := by
    ext x
    rw [list_Ta_apply, list_Ta_apply,
      isBraidLiftable_braidEquivOfNotRoot R ratFunc_X_not_root i j hij hmij]
  have hw : ∀ (n : ℕ) (a b : ℤ), D.cartanMatrix i j = a → D.cartanMatrix j i = b →
      (a * b).toNat = n → D.cartanMatrix.coxeterMatrix i j = Matrix.coxeterEntry n ∧
        D.cartanMatrix.coxeterMatrix j i = Matrix.coxeterEntry n := by
    intro n a b ha hb hn
    rw [Matrix.coxeterMatrix_apply_of_ne _ hij, Matrix.coxeterMatrix_apply_of_ne _ hij.symm, ha,
      hb, mul_comm b, hn]
    exact ⟨rfl, rfl⟩
  rcases cartanMatrix_cases hij hmij with ⟨h0, h0'⟩ | ⟨h1, h1'⟩ | ⟨h2, h2'⟩ | ⟨h2, h2'⟩ | h3'
  · obtain ⟨hm, hm'⟩ := hw 0 0 0 h0 h0' rfl
    have e : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix i j = [i, j] := by
      simp only [CoxeterSystem.braidWord]; rw [hm]; rfl
    have e' : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix j i = [j, i] := by
      simp only [CoxeterSystem.braidWord]; rw [hm']; rfl
    rw [e, e'] at hT ⊢
    exact CoxeterSystem.span_pbwDivMonomial_context (Ta R) (Ed R) (span_pbwDiv_commuting h0) hT p s
  · obtain ⟨hm, hm'⟩ := hw 1 (-1) (-1) h1 h1' rfl
    have e : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix i j = [j, i, j] := by
      simp only [CoxeterSystem.braidWord]; rw [hm]; rfl
    have e' : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix j i = [i, j, i] := by
      simp only [CoxeterSystem.braidWord]; rw [hm']; rfl
    rw [e, e'] at hT ⊢
    exact CoxeterSystem.span_pbwDivMonomial_context (Ta R) (Ed R)
      (span_pbwDiv_a2_braid hij h1 h1').symm hT p s
  · obtain ⟨hm, hm'⟩ := hw 2 (-2) (-1) h2 h2' rfl
    have e : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix i j = [i, j, i, j] := by
      simp only [CoxeterSystem.braidWord]; rw [hm]; rfl
    have e' : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix j i = [j, i, j, i] := by
      simp only [CoxeterSystem.braidWord]; rw [hm']; rfl
    rw [e, e'] at hT ⊢
    exact CoxeterSystem.span_pbwDivMonomial_context (Ta R) (Ed R)
      (span_pbwDiv_b2_braid hij h2 h2') hT p s
  · obtain ⟨hm, hm'⟩ := hw 2 (-1) (-2) h2 h2' rfl
    have e : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix i j = [i, j, i, j] := by
      simp only [CoxeterSystem.braidWord]; rw [hm]; rfl
    have e' : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix j i = [j, i, j, i] := by
      simp only [CoxeterSystem.braidWord]; rw [hm']; rfl
    rw [e, e'] at hT ⊢
    exact CoxeterSystem.span_pbwDivMonomial_context (Ta R) (Ed R)
      (span_pbwDiv_b2_braid hij.symm h2' h2).symm hT p s
  · exact absurd h3' (h3 i j)

section BraidInvariant

variable (hB : BraidInvariant R)
include hB

/-- **[Lus] 41.1.4 (b)** (`e = 1`) from braid invariance: reduced expressions of the same element
`w` give the same `𝒜`-span `𝒜U⁺(w, 1)` of the integral PBW monomials. -/
theorem span_pbwDiv_of_isReduced_of_braidInvariant {W : Type*} [Group W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {u w : List I}
    (hu : cs.IsReduced u) (hw : cs.IsReduced w) (huw : cs.wordProd u = cs.wordProd w) :
    Submodule.span 𝒜 (Set.range (pbwDiv R u)) = Submodule.span 𝒜 (Set.range (pbwDiv R w)) :=
  CoxeterSystem.eq_of_reflTransGen_braidMove (fun _ _ _ hm ↦ hB _ _ hm)
    hu (CoxeterSystem.reflTransGen_braidMove_of_isReduced hu hw huw)

/-- **[Lus] 41.1.4 (c)** (`e = 1`) from braid invariance: if `ℓ(sᵢ w) < ℓ(w)` then
`Eᵢ^{(t)} 𝒜U⁺(w, 1) ⊆ 𝒜U⁺(w, 1)`. -/
theorem qDivPow_E_mul_mem_span_pbwDiv_of_braidInvariant {W : Type*} [Group W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : List I} (hw : cs.IsReduced w)
    {i : I} (hi : cs.IsLeftDescent (cs.wordProd w) i) (t : ℕ) {x : QuantumGroup R 𝕧}
    (hx : x ∈ Submodule.span 𝒜 (Set.range (pbwDiv R w))) :
    qDivPow (𝕧 ^ D.d i) t (E R 𝕧 i) * x ∈ Submodule.span 𝒜 (Set.range (pbwDiv R w)) := by
  obtain ⟨u, hu, hu₀⟩ := exists_reduced_cons_of_isLeftDescent cs hi
  have hs := span_pbwDiv_of_isReduced_of_braidInvariant hB cs hu hw hu₀
  rw [← hs] at hx ⊢
  exact CoxeterSystem.mul_mem_pbwDivSpan_cons (Ta R) (Ed R) i u (Ed_mul_mem_span i t) hx

/-- **[Lus] 41.1.7** (`e = 1`, finite type) from braid invariance: for a reduced expression of the
longest element `w₀`, `𝒜U⁺(w₀, 1) = 𝒜U⁺`, the `𝒜`-subalgebra generated by the `Eᵢ^{(n)}`. -/
theorem span_pbwDiv_longest_eq_of_braidInvariant {W : Type*} [Group W] [Finite W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : List I} (hw : cs.IsReduced w)
    (hw₀ : cs.wordProd w = cs.longestElement) :
    Submodule.span 𝒜 (Set.range (pbwDiv R w)) =
      (Algebra.adjoin 𝒜 (⋃ i, Set.range (Ed R i))).toSubmodule := by
  let S := Submodule.span 𝒜 (Set.range (pbwDiv R w))
  have hplus : ∀ c, pbwDiv R w c ∈ Algebra.adjoin 𝒜 (⋃ i, Set.range (Ed R i)) := fun c ↦ by
    have hc := pbwDiv_mem_aPlus (R := R) w [] (by simpa using hw) c
    simp only [List.map_nil, List.prod_nil, AlgEquiv.one_apply] at hc
    generalize pbwDiv R w c = y at hc ⊢
    induction hc using AddSubgroup.closure_induction with
    | mem x hx =>
      obtain ⟨c, w', hc, rfl⟩ := hx
      refine smul_mem_of_isLaurent hc ?_
      induction w' with
      | nil => exact one_mem _
      | cons p w' ih =>
        rw [ePow_cons]
        exact mul_mem (Algebra.subset_adjoin (Set.mem_iUnion.2 ⟨p.1, p.2, rfl⟩)) ih
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | neg x _ hx => exact neg_mem hx
  refine le_antisymm (Submodule.span_le.2 ?_) ?_
  · rintro _ ⟨c, rfl⟩; exact hplus c
  · intro x hx
    have h1 : (1 : QuantumGroup R 𝕧) ∈ S :=
      CoxeterSystem.one_mem_pbwDivSpan (Ta R) (Ed R) Ed_zero w
    have hmul : ∀ y ∈ S, x * y ∈ S := by
      induction hx using Algebra.adjoin_induction with
      | mem x hx =>
        obtain ⟨i, n, rfl⟩ := Set.mem_iUnion.1 hx
        exact fun y hy ↦ qDivPow_E_mul_mem_span_pbwDiv_of_braidInvariant hB cs hw
          (hw₀ ▸ cs.isLeftDescent_longestElement i) n hy
      | algebraMap a =>
        intro y hy
        rw [← Algebra.smul_def]
        exact S.smul_mem a hy
      | add x z _ _ hx hz =>
        intro y hy; rw [add_mul]; exact add_mem (hx y hy) (hz y hy)
      | mul x z _ _ hx hz =>
        intro y hy; rw [mul_assoc]; exact hx _ (hz y hy)
    simpa using hmul 1 h1

/-- **[Lus] 41.1.7**, second form, from braid invariance: `𝒜U⁺(w₀, 1) = aPlus R`. -/
theorem coe_span_pbwDiv_longest_of_braidInvariant {W : Type*} [Group W] [Finite W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : List I} (hw : cs.IsReduced w)
    (hw₀ : cs.wordProd w = cs.longestElement) :
    (Submodule.span 𝒜 (Set.range (pbwDiv R w)) : Set (QuantumGroup R 𝕧)) = aPlus R := by
  refine subset_antisymm (fun x hx ↦ ?_) (fun x hx ↦ ?_)
  · induction hx using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨c, rfl⟩ := hx
      simpa using pbwDiv_mem_aPlus (R := R) w [] (by simpa using hw) c
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | smul a x _ hx => rw [laurent_smul_U]; exact smul_mem_aPlus ⟨a, rfl⟩ hx
  · rw [SetLike.mem_coe, span_pbwDiv_longest_eq_of_braidInvariant hB cs hw hw₀]
    induction hx using AddSubgroup.closure_induction with
    | mem x hx =>
      obtain ⟨c, w', hc, rfl⟩ := hx
      refine smul_mem_of_isLaurent hc ?_
      induction w' with
      | nil => exact one_mem _
      | cons p w' ih =>
        rw [ePow_cons]
        exact mul_mem (Algebra.subset_adjoin (Set.mem_iUnion.2 ⟨p.1, p.2, rfl⟩)) ih
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | neg x _ hx => exact neg_mem hx

end BraidInvariant

/-! ### Cartan data without triple edges -/

section NoTripleEdge

variable (h3 : ∀ i j, D.cartanMatrix i j * D.cartanMatrix j i ≠ 3)
include h3

/-- **[Lus] 41.1.4 (b)** (`e = 1`) for Cartan data without a pair `aᵢⱼ aⱼᵢ = 3`. -/
theorem span_pbwDiv_of_isReduced_of_mul_ne_three {W : Type*} [Group W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {u w : List I}
    (hu : cs.IsReduced u) (hw : cs.IsReduced w) (huw : cs.wordProd u = cs.wordProd w) :
    Submodule.span 𝒜 (Set.range (pbwDiv R u)) = Submodule.span 𝒜 (Set.range (pbwDiv R w)) :=
  span_pbwDiv_of_isReduced_of_braidInvariant (braidInvariant_of_mul_ne_three h3) cs hu hw huw

/-- **[Lus] 41.1.4 (c)** (`e = 1`) for Cartan data without a pair `aᵢⱼ aⱼᵢ = 3`. -/
theorem qDivPow_E_mul_mem_span_pbwDiv_of_mul_ne_three {W : Type*} [Group W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : List I} (hw : cs.IsReduced w)
    {i : I} (hi : cs.IsLeftDescent (cs.wordProd w) i) (t : ℕ) {x : QuantumGroup R 𝕧}
    (hx : x ∈ Submodule.span 𝒜 (Set.range (pbwDiv R w))) :
    qDivPow (𝕧 ^ D.d i) t (E R 𝕧 i) * x ∈ Submodule.span 𝒜 (Set.range (pbwDiv R w)) :=
  qDivPow_E_mul_mem_span_pbwDiv_of_braidInvariant (braidInvariant_of_mul_ne_three h3) cs hw hi t
    hx

/-- **[Lus] 41.1.7** (`e = 1`) in finite type without a pair `aᵢⱼ aⱼᵢ = 3` (types `A`, `B`, `C`,
`D`, `E`, `F`): `𝒜U⁺(w₀, 1) = 𝒜U⁺`. -/
theorem span_pbwDiv_longest_eq_of_mul_ne_three {W : Type*} [Group W] [Finite W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : List I} (hw : cs.IsReduced w)
    (hw₀ : cs.wordProd w = cs.longestElement) :
    Submodule.span 𝒜 (Set.range (pbwDiv R w)) =
      (Algebra.adjoin 𝒜 (⋃ i, Set.range (Ed R i))).toSubmodule :=
  span_pbwDiv_longest_eq_of_braidInvariant (braidInvariant_of_mul_ne_three h3) cs hw hw₀

/-- **[Lus] 41.1.7**, second form, without a pair `aᵢⱼ aⱼᵢ = 3`: `𝒜U⁺(w₀, 1) = aPlus R`. -/
theorem coe_span_pbwDiv_longest_of_mul_ne_three {W : Type*} [Group W] [Finite W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : List I} (hw : cs.IsReduced w)
    (hw₀ : cs.wordProd w = cs.longestElement) :
    (Submodule.span 𝒜 (Set.range (pbwDiv R w)) : Set (QuantumGroup R 𝕧)) = aPlus R :=
  coe_span_pbwDiv_longest_of_braidInvariant (braidInvariant_of_mul_ne_three h3) cs hw hw₀

end NoTripleEdge

end Modified

end LieLean.QuantumGroup
