/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.Modified.RootVectors
import LieLean.Algebra.QuantumGroup.PBW.IntegralA2
import LieLean.Algebra.QuantumGroup.PBW.SimplyLacedSpanInvariance
import LieLean.Algebra.QuantumGroup.PBW.Independence

/-!
# Integral PBW bases in simply-laced type ([Lus] 41.1.4, 41.1.7)

Over `ℚ(v)`, `𝒜 = ℤ[v, v⁻¹]`, for `Tᵢ = T''_{i,1}` and a reduced expression `s_{i₁} ⋯ s_{iₙ}` of
`w ∈ W`, the divided-power PBW monomials
`E_{i₁}^{(c₁)} T_{i₁}(E_{i₂}^{(c₂)}) ⋯ T_{i₁} ⋯ T_{iₙ₋₁}(E_{iₙ}^{(cₙ)})`
(`CoxeterSystem.pbwDivMonomial`) are `𝒜`-linearly independent and their `𝒜`-span `𝒜U⁺(w, 1)` does
not depend on the reduced expression ([Lus] 41.1.4 (b) for `e = 1`); `Eᵢ^{(t)} 𝒜U⁺(w, 1) ⊆
𝒜U⁺(w, 1)` if `ℓ(sᵢ w) < ℓ(w)` ([Lus] 41.1.4 (c)); and in finite type `𝒜U⁺(w₀, 1) = 𝒜U⁺`
([Lus] 41.1.7). We prove these for **simply-laced** Cartan data, where the rank-two input is the
integral `A₂` straightening of `PBW/IntegralA2.lean` (cf. [Lus] 42.1.2). The extension to Cartan
data without triple edges (rank-two input: the integral `B₂` straightening of
`PBW/IntegralB2.lean`) is `Modified/IntegralPBWB2.lean`.

## Main results

* `CoxeterSystem.pbwDivMonomial`: PBW monomials for a family of "divided powers" `Ed i n`, with the
  context lemmas `span_pbwDivMonomial_append`, `span_pbwDivMonomial_context`.
* `Modified.span_pbwDiv_of_isReduced`: [Lus] 41.1.4 (b), independence of the reduced expression
  (via `Modified.span_pbwDiv_a2_braid`, `Modified.span_pbwDiv_commuting` and Matsumoto's theorem).
* `Modified.linearIndependent_pbwDiv`: the divided monomials are `𝒜`-linearly independent.
* `Modified.qDivPow_E_mul_mem_span_pbwDiv`: [Lus] 41.1.4 (c).
* `Modified.span_pbwDiv_longest_eq`: [Lus] 41.1.7, `𝒜U⁺(w₀, 1) = 𝒜U⁺` (as the `𝒜`-subalgebra
  generated by the `Eᵢ^{(n)}`), and `Modified.coe_span_pbwDiv_longest`: `= aPlus R`.

## References

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, 40.2.1, 41.1.4, 41.1.7,
  42.1.2.
-/

open LieLean Finset

noncomputable section

/-! ### PBW monomials with divided powers -/

namespace CoxeterSystem

variable {B k A : Type*} [CommSemiring k] [Semiring A] [Algebra k A]
  (T : B → A ≃ₐ[k] A) (Ed : B → ℕ → A)

/-- The PBW monomials `Ed i₁ c₁ · T_{i₁}(Ed i₂ c₂ · T_{i₂}(⋯))` along a word, for a family
`Ed i n` (e.g. divided powers `Eᵢ^{(n)}`). -/
def pbwDivMonomial : (ω : List B) → (Fin ω.length → ℕ) → A
  | [], _ => 1
  | i :: ω, c => Ed i (c ⟨0, Nat.succ_pos _⟩) * T i (pbwDivMonomial ω fun n ↦ c n.succ)

lemma pbwDivMonomial_cons (i : B) (ω : List B) (c : Fin (i :: ω).length → ℕ) :
    pbwDivMonomial T Ed (i :: ω) c =
      Ed i (c ⟨0, Nat.succ_pos _⟩) * T i (pbwDivMonomial T Ed ω fun n ↦ c n.succ) := rfl

theorem span_pbwDivMonomial_cons (i : B) (w : List B) :
    Submodule.span k (Set.range (pbwDivMonomial T Ed (i :: w))) =
      Submodule.span k (Set.range (Ed i)) *
        (Submodule.span k (Set.range (pbwDivMonomial T Ed w))).map (T i).toLinearMap := by
  rw [Submodule.map_span, Submodule.span_mul_span]
  congr 1
  ext x
  constructor
  · rintro ⟨c, rfl⟩
    exact ⟨_, ⟨c 0, rfl⟩, _, ⟨_, ⟨(fun n ↦ c n.succ), rfl⟩, rfl⟩, rfl⟩
  · rintro ⟨_, ⟨n, rfl⟩, _, ⟨_, ⟨c, rfl⟩, rfl⟩, rfl⟩
    exact ⟨Fin.cons n c, rfl⟩

theorem span_pbwDivMonomial_append (p s : List B) :
    Submodule.span k (Set.range (pbwDivMonomial T Ed (p ++ s))) =
      Submodule.span k (Set.range (pbwDivMonomial T Ed p)) *
        (Submodule.span k (Set.range (pbwDivMonomial T Ed s))).map
          ((p.map T).prod).toLinearMap := by
  induction p with
  | nil =>
    have hnil : Set.range (pbwDivMonomial T Ed []) = {1} := by
      ext x
      simp [pbwDivMonomial]
    simp [hnil, ← Submodule.one_eq_span, show (1 : A →ₗ[k] A) = LinearMap.id by rfl]
  | cons i p ih =>
    rw [List.cons_append, span_pbwDivMonomial_cons, ih, span_pbwDivMonomial_cons]
    have hmap (P Q : Submodule k A) :
        (P * Q).map (T i).toLinearMap = P.map (T i).toLinearMap *
          Q.map (T i).toLinearMap := Submodule.map_mul P Q (T i).toAlgHom
    rw [hmap, mul_assoc, ← Submodule.map_comp]
    rfl

theorem span_pbwDivMonomial_context {u w : List B}
    (hspan : Submodule.span k (Set.range (pbwDivMonomial T Ed u)) =
      Submodule.span k (Set.range (pbwDivMonomial T Ed w)))
    (hT : (u.map T).prod = (w.map T).prod) (p s : List B) :
    Submodule.span k (Set.range (pbwDivMonomial T Ed (p ++ u ++ s))) =
      Submodule.span k (Set.range (pbwDivMonomial T Ed (p ++ w ++ s))) := by
  rw [List.append_assoc, List.append_assoc, span_pbwDivMonomial_append,
    span_pbwDivMonomial_append T Ed p (w ++ s), span_pbwDivMonomial_append T Ed u,
    span_pbwDivMonomial_append T Ed w, hspan, hT]

lemma pbwDivMonomial_zero_exponents (hEd : ∀ i, Ed i 0 = 1) (w : List B) :
    pbwDivMonomial T Ed w (fun _ ↦ 0) = 1 := by
  induction w with
  | nil => rfl
  | cons i w ih => simp [pbwDivMonomial_cons, ih, hEd]

lemma one_mem_pbwDivSpan (hEd : ∀ i, Ed i 0 = 1) (w : List B) :
    (1 : A) ∈ Submodule.span k (Set.range (pbwDivMonomial T Ed w)) := by
  rw [← pbwDivMonomial_zero_exponents T Ed hEd w]
  exact Submodule.subset_span ⟨_, rfl⟩

lemma mul_mem_pbwDivSpan_cons (i : B) (w : List B) {y : A}
    (hy : ∀ n, y * Ed i n ∈ Submodule.span k (Set.range (Ed i))) {x : A}
    (hx : x ∈ Submodule.span k (Set.range (pbwDivMonomial T Ed (i :: w)))) :
    y * x ∈ Submodule.span k (Set.range (pbwDivMonomial T Ed (i :: w))) := by
  rw [span_pbwDivMonomial_cons] at hx ⊢
  induction hx using Submodule.mul_induction_on' with
  | mem_mul_mem a ha b hb =>
    rw [← mul_assoc]
    refine Submodule.mul_mem_mul ?_ hb
    induction ha using Submodule.span_induction with
    | mem a ha => obtain ⟨n, rfl⟩ := ha; exact hy n
    | zero => rw [mul_zero]; exact zero_mem _
    | add a b _ _ ha hb => rw [mul_add]; exact add_mem ha hb
    | smul c a _ ha => rw [mul_smul_comm]; exact Submodule.smul_mem _ c ha
  | add a b _ _ ha hb => rw [mul_add]; exact add_mem ha hb

end CoxeterSystem

namespace LieLean.QuantumGroup

local notation "𝕂" => RatFunc ℚ
local notation "𝕧" => (RatFunc.X : RatFunc ℚ)
local notation "𝒜" => LaurentPolynomial ℤ

attribute [local instance] neZero_ratFunc_X

variable {I Y : Type*} [AddCommGroup Y] [DecidableEq I] {D : LusztigCartanDatum I}
  {R : D.RootDatum Y}

namespace Modified

/-! ### `U` as an `𝒜`-algebra -/

/-- `ℚ(v)` as an `𝒜`-algebra. -/
abbrev laurentAlgebraK : Algebra 𝒜 𝕂 := LusztigF.integralLaurentEval.toAlgebra

variable (R) in
/-- `U` as an `𝒜`-algebra (through `𝒜 → ℚ(v)`). -/
abbrev laurentAlgebraU : Algebra 𝒜 (QuantumGroup R 𝕧) :=
  Algebra.compHom _ LusztigF.integralLaurentEval

attribute [local instance] laurentAlgebraK laurentAlgebraU

variable (R) in
lemma laurentTowerU : IsScalarTower 𝒜 𝕂 (QuantumGroup R 𝕧) :=
  IsScalarTower.of_algebraMap_eq fun _ ↦ rfl

attribute [local instance] laurentTowerU

lemma laurent_smul_U (a : 𝒜) (x : QuantumGroup R 𝕧) :
    a • x = LusztigF.integralLaurentEval a • x := rfl

variable (R) in
/-- `Tᵢ = T''_{i,1}` as an `𝒜`-algebra automorphism of `U`. -/
def Ta (i : I) : QuantumGroup R 𝕧 ≃ₐ[𝒜] QuantumGroup R 𝕧 :=
  (braidEquivOfNotRoot R ratFunc_X_not_root i).restrictScalars 𝒜

lemma Ta_apply (i : I) (x : QuantumGroup R 𝕧) :
    Ta R i x = braidEquivOfNotRoot R ratFunc_X_not_root i x := rfl

variable (R) in
/-- The divided powers `Eᵢ^{(n)}`. -/
def Ed (i : I) (n : ℕ) : QuantumGroup R 𝕧 := qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i)

lemma Ed_zero (i : I) : Ed R i 0 = 1 := qDivPow_zero' _ _

variable (R) in
/-- **The integral PBW monomials** `E_{i₁}^{(c₁)} T_{i₁}(E_{i₂}^{(c₂)}) ⋯` along a word. -/
abbrev pbwDiv (ω : List I) : (Fin ω.length → ℕ) → QuantumGroup R 𝕧 :=
  CoxeterSystem.pbwDivMonomial (Ta R) (Ed R) ω

/-- The divided monomials are nonzero multiples of the library's PBW monomials. -/
lemma pbwDiv_eq_smul (ω : List I) (c : Fin ω.length → ℕ) :
    CoxeterSystem.pbwDivMonomial (Ta R) (Ed R) ω c =
      (∏ t : Fin ω.length, (qFactorial (𝕧 ^ D.d ω[t]) (c t))⁻¹) •
      CoxeterSystem.pbwMonomial (braidEquivOfNotRoot R ratFunc_X_not_root) (E R 𝕧) ω c := by
  induction ω with
  | nil => simp [CoxeterSystem.pbwDivMonomial, CoxeterSystem.pbwMonomial]
  | cons i ω ih =>
    rw [CoxeterSystem.pbwDivMonomial_cons, CoxeterSystem.pbwMonomial_cons, ih]
    change _ = (∏ t : Fin (ω.length + 1), (qFactorial (𝕧 ^ D.d (i :: ω)[t]) (c t))⁻¹) • _
    rw [Fin.prod_univ_succ]
    rw [Ta_apply, map_smul, Ed, qDivPow, smul_mul_smul_comm]
    rfl

omit [DecidableEq I] in
lemma qFactorial_vd_ne_zero (i : I) (n : ℕ) : qFactorial (𝕧 ^ D.d i) n ≠ 0 :=
  LusztigF.qFactorial_ne_zero_of_not_root (D := D) (NeZero.ne 𝕧) ratFunc_X_not_root i n

/-- **The integral PBW monomials are `𝒜`-linearly independent** along a reduced word (from the
`ℚ(v)`-linear independence of the PBW monomials), for every Cartan datum. -/
theorem linearIndependent_pbwDiv
    {W : Type*} [Group W] {cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W} {ω : List I}
    (hω : cs.IsReduced ω) : LinearIndependent 𝒜 (pbwDiv R ω) := by
  classical
  have hli := linearIndependent_pbwMonomial_of_isReduced (R := R) ratFunc_X_not_root hω
  rw [linearIndependent_iff'] at hli ⊢
  intro s g hg c hc
  have hs : ∀ c : Fin ω.length → ℕ,
      (∏ t : Fin ω.length, (qFactorial (𝕧 ^ D.d ω[t]) (c t))⁻¹) ≠ 0 := fun c ↦
    prod_ne_zero_iff.2 fun t _ ↦ inv_ne_zero (qFactorial_vd_ne_zero _ _)
  have h := hli s (fun c : Fin ω.length → ℕ ↦ LusztigF.integralLaurentEval (g c) *
    ∏ t : Fin ω.length, (qFactorial (𝕧 ^ D.d ω[t]) (c t))⁻¹) (by
      simpa [laurent_smul_U, pbwDiv_eq_smul, smul_smul] using hg) c hc
  exact LusztigF.integralLaurentEval_injective (by
    rw [map_zero]; exact (mul_eq_zero.1 h).resolve_right (hs c))

/-! ### Rank two -/

lemma qSerre_two (q : 𝕂) (a b : QuantumGroup R 𝕧) :
    qSerre q 2 a b = a ^ 2 * b - (q + q⁻¹) • (a * b * a) + b * a ^ 2 := by
  simp only [qSerre, sum_range_succ, range_zero, sum_empty, zero_add, qBinomial_zero_right,
    qBinomial_one_right, qBinomial_self, pow_zero, pow_one, mul_one, one_mul, one_smul,
    Nat.sub_zero, show 2 - 1 = 1 from rfl, Nat.sub_self]
  simp only [qInt, sum_range_succ, range_zero, sum_empty, zero_add]
  simp only [Nat.add_one_sub_one, tsub_zero, pow_one, pow_zero, mul_one, tsub_self, one_mul,
    neg_mul, neg_add_rev, even_two, Even.neg_pow, one_pow, one_smul, add_left_inj]
  rw [sub_eq_add_neg, ← neg_smul, neg_add, add_comm (-q)]

/-- The integral form of the subalgebra generated by two nodes. -/
abbrev adjoinPair (i j : I) : Subalgebra 𝒜 (QuantumGroup R 𝕧) :=
  Algebra.adjoin 𝒜 (Set.range (Ed R i) ∪ Set.range (Ed R j))

lemma smul_mem_of_isLaurent {S : Subalgebra 𝒜 (QuantumGroup R 𝕧)} {c : 𝕂} (hc : IsLaurent c)
    {x : QuantumGroup R 𝕧} (hx : x ∈ S) : c • x ∈ S := by
  obtain ⟨a, rfl⟩ := hc
  exact S.smul_mem hx a

lemma isLaurent_iff_mem_range (c : 𝕂) :
    IsLaurent c ↔ c ∈ (LusztigF.integralLaurentEval).range := Iff.rfl

variable {i j : I} (hij : i ≠ j) (h : D.cartanMatrix i j = -1) (h' : D.cartanMatrix j i = -1)

include hij h h' in
/-- **The integral PBW monomials of `iji` span the integral form of the rank-two subalgebra**
(type `A₂`; from the integral straightening, cf. [Lus] 42.1.2). -/
theorem span_pbwDiv_a2 :
    Submodule.span 𝒜 (Set.range (pbwDiv R [i, j, i])) = (adjoinPair (R := R) i j).toSubmodule := by
  classical
  set q : 𝕂 := 𝕧 ^ D.d i
  set α := E R 𝕧 i
  set β := E R 𝕧 j
  set γ := braidEj R 𝕧 i j
  have hq0 : q ≠ 0 := pow_ne_zero _ (NeZero.ne 𝕧)
  have hqroot := vd_pow_ne_one (D := D) ratFunc_X_not_root i
  have hqi : ∀ n : ℕ, 0 < n → qInt q n ≠ 0 := fun n hn ↦
    qInt_ne_zero_of_pow_ne_one hq0 hqroot hn
  have hqq : q - q⁻¹ ≠ 0 := sub_inv_ne_zero_of_pow_ne_one hq0 hqroot
  have hdij : D.d j = D.d i := (D.d_eq_of_simply_laced_edge h h').symm
  have hγ : γ = α * β - q⁻¹ • (β * α) := braidEj_eq_of_cartanMatrix_eq_neg_one h
  have hβα : β * α = q • (α * β) - q • γ := by
    rw [hγ, smul_sub, smul_smul, mul_inv_cancel₀ hq0, one_smul]; abel
  have hS1 : qSerre q 2 α β = 0 := by
    have := serre_E R 𝕧 hij
    rwa [h, show (1 - -1 : ℤ).toNat = 2 from rfl] at this
  have hS2 : qSerre q 2 β α = 0 := by
    have := serre_E R 𝕧 hij.symm
    rwa [h', show (1 - -1 : ℤ).toNat = 2 from rfl, hdij] at this
  have hαγ : α * γ = q • (γ * α) := by
    have e : α * γ - q • (γ * α) = qSerre q 2 α β := by
      rw [qSerre_two, hγ]
      simp only [mul_sub, sub_mul, mul_smul_comm, smul_mul_assoc, smul_sub, smul_smul,
        mul_inv_cancel₀ hq0, one_smul, sq, mul_assoc, add_smul]
      abel
    rw [← sub_eq_zero, e, hS1]
  have hβγ : q • (β * γ) = γ * β := by
    have e : q • (β * γ) - γ * β = -qSerre q 2 β α := by
      rw [qSerre_two, hγ]
      simp only [mul_sub, sub_mul, mul_smul_comm, smul_mul_assoc, smul_sub, smul_smul,
        mul_inv_cancel₀ hq0, one_smul, sq, mul_assoc, add_smul]
      abel
    rw [← sub_eq_zero, e, hS2, neg_zero]
  set Λ : Subring 𝕂 := (LusztigF.integralLaurentEval).range
  have hqΛ : q ∈ Λ := RingHom.mem_range.2 (isLaurent_pow (D.d i))
  have hqΛ' : q⁻¹ ∈ Λ := by
    have := isLaurent_inv_pow (D.d i)
    rw [inv_pow] at this
    exact RingHom.mem_range.2 this
  have hmap : ∀ (f : QuantumGroup R 𝕧 ≃ₐ[𝕂] QuantumGroup R 𝕧) (t : 𝕂) (n : ℕ) (x),
      f (qDivPow t n x) = qDivPow t n (f x) := fun f t n x ↦ map_qDivPow' f.toAlgHom t n x
  -- the monomials
  have hT2 : braidEquivOfNotRoot R ratFunc_X_not_root i β = γ :=
    a2_rootVector_two hij (braidEquivOfNotRoot_hasImages ratFunc_X_not_root R i)
  have hT3 : braidEquivOfNotRoot R ratFunc_X_not_root i
      (braidEquivOfNotRoot R ratFunc_X_not_root j α) = β :=
    a2_rootVector_three (braidEquivOfNotRoot_hasImages ratFunc_X_not_root R i)
      (braidEquivOfNotRoot_hasImages ratFunc_X_not_root R j) hij h h' hqq
  have hmono : ∀ c : Fin 3 → ℕ, pbwDiv R [i, j, i] c =
      qDivPow q (c 0) α * qDivPow q (c 1) γ * qDivPow q (c 2) β := fun c ↦ by
    have e1 : ∀ n, braidEquivOfNotRoot R ratFunc_X_not_root i (Ed R j n) = qDivPow q n γ :=
      fun n ↦ by rw [Ed, hmap, hT2, hdij]
    have e2 : ∀ n, braidEquivOfNotRoot R ratFunc_X_not_root i
        (braidEquivOfNotRoot R ratFunc_X_not_root j (Ed R i n)) = qDivPow q n β := fun n ↦ by
      rw [Ed, hmap, hmap, hT3]
    simp only [CoxeterSystem.pbwDivMonomial, Ta_apply, _root_.map_mul, _root_.map_one, mul_one]
    rw [e1, e2, ← mul_assoc]
    rfl
  -- spans as `Λ`-combinations
  have hconv : ∀ x, x ∈ Submodule.span 𝒜 (Set.range (pbwDiv R [i, j, i])) ↔
      x ∈ A2Integral.orderedSpan Λ q α β γ := fun x ↦ by
    constructor
    · intro hx
      induction hx using Submodule.span_induction with
      | mem x hx =>
        obtain ⟨c, rfl⟩ := hx
        rw [hmono]; exact A2Integral.monomial_mem_orderedSpan _ _ _
      | zero => exact zero_mem _
      | add x y _ _ hx hy => exact add_mem hx hy
      | smul a x _ hx =>
        rw [laurent_smul_U]
        exact A2Integral.smul_mem_orderedSpan (RingHom.mem_range.2 ⟨a, rfl⟩) hx
    · intro hx
      induction hx using AddSubgroup.closure_induction with
      | mem x hx =>
        obtain ⟨c, hc, e, f, g, rfl⟩ := hx
        obtain ⟨a, rfl⟩ := RingHom.mem_range.1 hc
        rw [← laurent_smul_U, show qDivPow q e α * qDivPow q f γ * qDivPow q g β =
          pbwDiv R [i, j, i] ![e, f, g] by rw [hmono]; rfl]
        exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨_, rfl⟩)
      | zero => exact zero_mem _
      | add x y _ _ hx hy => exact add_mem hx hy
      | neg x _ hx => exact neg_mem hx
  have hγd : ∀ n, qDivPow q n γ ∈ adjoinPair (R := R) i j := fun n ↦ by
    have e : qDivPow q n γ = braidEjDiv R 𝕧 i j n := by
      have := braidEquivOfNotRoot_qDivPow_E_ne ratFunc_X_not_root R hij.symm n
      rw [hdij] at this
      rw [← hT2, ← hmap]
      exact this
    rw [e, braidEjDiv]
    refine Subalgebra.sum_mem _ fun r _ ↦ smul_mem_of_isLaurent
      ((isLaurent_neg_one.pow r).mul (isLaurent_inv_pow_pow _ _)) ?_
    refine mul_mem (mul_mem ?_ ?_) ?_
    · exact Algebra.subset_adjoin (Or.inl ⟨_, rfl⟩)
    · exact Algebra.subset_adjoin (Or.inr ⟨_, rfl⟩)
    · exact Algebra.subset_adjoin (Or.inl ⟨_, rfl⟩)
  refine le_antisymm (fun x hx ↦ ?_) (fun x hx ↦ ?_)
  · rw [hconv] at hx
    induction hx using AddSubgroup.closure_induction with
    | mem x hx =>
      obtain ⟨c, hc, e, f, g, rfl⟩ := hx
      refine smul_mem_of_isLaurent hc (mul_mem (mul_mem ?_ (hγd f)) ?_)
      · exact Algebra.subset_adjoin (Or.inl ⟨_, rfl⟩)
      · exact Algebra.subset_adjoin (Or.inr ⟨g, by rw [Ed, hdij]⟩)
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | neg x _ hx => exact neg_mem hx
  · have h1 : (1 : QuantumGroup R 𝕧) ∈ A2Integral.orderedSpan Λ q α β γ :=
      A2Integral.one_mem_orderedSpan
    have hmul : ∀ y ∈ A2Integral.orderedSpan Λ q α β γ,
        x * y ∈ A2Integral.orderedSpan Λ q α β γ := by
      induction hx using Algebra.adjoin_induction with
      | mem x hx =>
        rcases hx with ⟨n, rfl⟩ | ⟨n, rfl⟩
        · exact fun y hy ↦ A2Integral.qDivPow_α_mul_mem hqi hqΛ hqΛ' n hy
        · intro y hy
          rw [Ed, hdij]
          exact A2Integral.qDivPow_β_mul_mem hq0 hqi hβα hαγ hβγ hqΛ hqΛ' hqq n hy
      | algebraMap a =>
        intro y hy
        rw [← Algebra.smul_def, laurent_smul_U]
        exact A2Integral.smul_mem_orderedSpan (RingHom.mem_range.2 ⟨a, rfl⟩) hy
      | add x z _ _ hx hz =>
        intro y hy; rw [add_mul]; exact add_mem (hx y hy) (hz y hy)
      | mul x z _ _ hx hz =>
        intro y hy; rw [mul_assoc]; exact hx _ (hz y hy)
    rw [hconv]
    simpa using hmul 1 h1

include hij h h' in
/-- The `A₂` braid move preserves the integral PBW span. -/
theorem span_pbwDiv_a2_braid :
    Submodule.span 𝒜 (Set.range (pbwDiv R [i, j, i])) =
      Submodule.span 𝒜 (Set.range (pbwDiv R [j, i, j])) := by
  rw [span_pbwDiv_a2 hij h h', span_pbwDiv_a2 hij.symm h' h, adjoinPair, adjoinPair,
    Set.union_comm]

omit hij h h' in
/-- The commuting braid move preserves the integral PBW span. -/
theorem span_pbwDiv_commuting (h0 : D.cartanMatrix i j = 0) :
    Submodule.span 𝒜 (Set.range (pbwDiv R [i, j])) =
      Submodule.span 𝒜 (Set.range (pbwDiv R [j, i])) := by
  have h0' := (D.isGeneralizedCartan_cartanMatrix.zero_comm i j).mp h0
  have hij : i ≠ j := by rintro rfl; rw [D.cartanMatrix_self] at h0; exact two_ne_zero h0
  have hmap : ∀ (f : QuantumGroup R 𝕧 ≃ₐ[𝕂] QuantumGroup R 𝕧) (t : 𝕂) (n : ℕ) (x),
      f (qDivPow t n x) = qDivPow t n (f x) := fun f t n x ↦ map_qDivPow' f.toAlgHom t n x
  have hE : ∀ {a b : I}, D.cartanMatrix a b = 0 → a ≠ b →
      braidEquivOfNotRoot R ratFunc_X_not_root a (E R 𝕧 b) = E R 𝕧 b := by
    intro a b hab hne
    have H := braidEquivOfNotRoot_hasImages ratFunc_X_not_root R a
    change (braidEquivOfNotRoot R ratFunc_X_not_root a).toAlgHom (E R 𝕧 b) = _
    rw [H.map_E, ite_eq_right hne.symm, braidEj_eq_of_cartanMatrix_eq_zero hab]
  have hmono : ∀ {a b : I}, D.cartanMatrix a b = 0 → a ≠ b → ∀ c : Fin 2 → ℕ,
      pbwDiv R [a, b] c = Ed R a (c 0) * Ed R b (c 1) := fun hab hne c ↦ by
    simp only [CoxeterSystem.pbwDivMonomial, Ta_apply, _root_.map_one, mul_one, Ed, hmap,
      hE hab hne]
    rfl
  have hc : ∀ m n, Ed R i m * Ed R j n = Ed R j n * Ed R i m := fun m n ↦ by
    simp only [Ed, qDivPow, smul_mul_smul_comm]
    rw [((Commute.pow_pow (E_commute_E_of_cartanMatrix_eq_zero (R := R) (v := 𝕧) h0) m n)).eq,
      mul_comm (_ : 𝕂)]
  congr 1
  ext x
  constructor
  · rintro ⟨c, rfl⟩
    exact ⟨![c 1, c 0], by rw [hmono h0' hij.symm, hmono h0 hij, hc]; rfl⟩
  · rintro ⟨c, rfl⟩
    exact ⟨![c 1, c 0], by rw [hmono h0' hij.symm, hmono h0 hij, hc]; rfl⟩

/-! ### Independence of the reduced expression ([Lus] 41.1.4) -/

lemma list_Ta_apply (u : List I) (x : QuantumGroup R 𝕧) :
    (u.map (Ta R)).prod x = (u.map (braidEquivOfNotRoot R ratFunc_X_not_root)).prod x := by
  induction u generalizing x with
  | nil => rfl
  | cons i u ih => simp only [List.map_cons, List.prod_cons, AlgEquiv.mul_apply, ih, Ta_apply]

variable (hSL : D.cartanMatrix.IsSimplyLaced)

include hSL in
/-- A braid move preserves the integral PBW span (simply-laced type). -/
theorem span_pbwDiv_of_braidMove {u w : List I}
    (hm : D.cartanMatrix.coxeterMatrix.BraidMove u w) :
    Submodule.span 𝒜 (Set.range (pbwDiv R u)) = Submodule.span 𝒜 (Set.range (pbwDiv R w)) := by
  obtain ⟨p, s, i, j, hij, hmij, rfl, rfl⟩ := hm
  have hT : ((CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix i j).map (Ta R)).prod =
      ((CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix j i).map (Ta R)).prod := by
    ext x
    rw [list_Ta_apply, list_Ta_apply,
      isBraidLiftable_braidEquivOfNotRoot R ratFunc_X_not_root i j hij hmij]
  rcases hSL hij with h0 | h1
  · have h0' := (D.isGeneralizedCartan_cartanMatrix.zero_comm i j).mp h0
    have hm : D.cartanMatrix.coxeterMatrix i j = 2 := by
      rw [Matrix.coxeterMatrix_apply_of_ne _ hij, h0, h0']
      rfl
    have hm' : D.cartanMatrix.coxeterMatrix j i = 2 := by
      rw [Matrix.coxeterMatrix_apply_of_ne _ hij.symm, h0, h0']
      rfl
    have hw : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix i j = [i, j] := by
      simp only [CoxeterSystem.braidWord]
      rw [hm]
      rfl
    have hw' : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix j i = [j, i] := by
      simp only [CoxeterSystem.braidWord]
      rw [hm']
      rfl
    rw [hw, hw'] at hT ⊢
    exact CoxeterSystem.span_pbwDivMonomial_context (Ta R) (Ed R) (span_pbwDiv_commuting h0) hT p s
  · have h1' : D.cartanMatrix j i = -1 := by
      rcases hSL hij.symm with hz | hn
      · have := (D.isGeneralizedCartan_cartanMatrix.zero_comm j i).mp hz
        omega
      · exact hn
    have hm : D.cartanMatrix.coxeterMatrix i j = 3 := by
      rw [Matrix.coxeterMatrix_apply_of_ne _ hij, h1, h1']
      rfl
    have hm' : D.cartanMatrix.coxeterMatrix j i = 3 := by
      rw [Matrix.coxeterMatrix_apply_of_ne _ hij.symm, h1, h1']
      rfl
    have hw : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix i j = [j, i, j] := by
      simp only [CoxeterSystem.braidWord]
      rw [hm]
      rfl
    have hw' : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix j i = [i, j, i] := by
      simp only [CoxeterSystem.braidWord]
      rw [hm']
      rfl
    rw [hw, hw'] at hT ⊢
    exact CoxeterSystem.span_pbwDivMonomial_context (Ta R) (Ed R)
      (span_pbwDiv_a2_braid hij h1 h1').symm hT p s

include hSL in
/-- **[Lus] 41.1.4 (b)** (`e = 1`, simply-laced type): reduced expressions of the same element `w`
give the same `𝒜`-span `𝒜U⁺(w, 1)` of the integral PBW monomials. -/
theorem span_pbwDiv_of_isReduced {W : Type*} [Group W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {u w : List I}
    (hu : cs.IsReduced u) (hw : cs.IsReduced w) (huw : cs.wordProd u = cs.wordProd w) :
    Submodule.span 𝒜 (Set.range (pbwDiv R u)) = Submodule.span 𝒜 (Set.range (pbwDiv R w)) :=
  CoxeterSystem.eq_of_reflTransGen_braidMove
    (fun _ _ _ hm ↦ span_pbwDiv_of_braidMove hSL hm)
    hu (CoxeterSystem.reflTransGen_braidMove_of_isReduced hu hw huw)

lemma exists_reduced_cons_of_isLeftDescent {W : Type*} [Group W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : W} {i : I}
    (hi : cs.IsLeftDescent w i) :
    ∃ u : List I, cs.IsReduced (i :: u) ∧ cs.wordProd (i :: u) = w := by
  obtain ⟨u, hu, he⟩ := cs.exists_isReduced (cs.simple i * w)
  have hp : cs.wordProd (i :: u) = w := by
    rw [cs.wordProd_cons, ← he]
    simp
  refine ⟨u, ?_, hp⟩
  unfold CoxeterSystem.IsReduced
  rw [hp, List.length_cons, ← hu.eq, ← he]
  exact ((cs.isLeftDescent_iff).mp hi).symm

lemma Ed_mul_mem_span (i : I) (t n : ℕ) :
    Ed R i t * Ed R i n ∈ Submodule.span 𝒜 (Set.range (Ed R i)) := by
  rw [Ed, Ed, A2Integral.qDivPow_mul_qDivPow _ t n (qFactorial_vd_ne_zero i _)]
  obtain ⟨a, ha⟩ : IsLaurent (qBinomial (𝕧 ^ D.d i) (t + n) t) :=
    RingHom.mem_range.1 (A2Integral.qBinomial_mem (RingHom.mem_range.2 (isLaurent_pow _))
      (RingHom.mem_range.2 (by have := isLaurent_inv_pow (D.d i); rwa [inv_pow] at this)) _ _)
  rw [← ha, ← laurent_smul_U]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨t + n, rfl⟩)

include hSL in
/-- **[Lus] 41.1.4 (c)** (`e = 1`, simply-laced type): if `ℓ(sᵢ w) < ℓ(w)` then
`Eᵢ^{(t)} 𝒜U⁺(w, 1) ⊆ 𝒜U⁺(w, 1)`. -/
theorem qDivPow_E_mul_mem_span_pbwDiv {W : Type*} [Group W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : List I} (hw : cs.IsReduced w)
    {i : I} (hi : cs.IsLeftDescent (cs.wordProd w) i) (t : ℕ) {x : QuantumGroup R 𝕧}
    (hx : x ∈ Submodule.span 𝒜 (Set.range (pbwDiv R w))) :
    qDivPow (𝕧 ^ D.d i) t (E R 𝕧 i) * x ∈ Submodule.span 𝒜 (Set.range (pbwDiv R w)) := by
  obtain ⟨u, hu, hu₀⟩ := exists_reduced_cons_of_isLeftDescent cs hi
  have hs := span_pbwDiv_of_isReduced (R := R) hSL cs hu hw hu₀
  rw [← hs] at hx ⊢
  exact CoxeterSystem.mul_mem_pbwDivSpan_cons (Ta R) (Ed R) i u (Ed_mul_mem_span i t) hx

/-! ### Finite type ([Lus] 41.1.7) -/

lemma mul_mem_aPlus {x y : QuantumGroup R 𝕧} (hx : x ∈ aPlus R) (hy : y ∈ aPlus R) :
    x * y ∈ aPlus R := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨c, w, hc, rfl⟩ := hx
    induction hy using AddSubgroup.closure_induction with
    | mem y hy =>
      obtain ⟨c', w', hc', rfl⟩ := hy
      rw [smul_mul_smul_comm, ← ePow_append]
      exact smul_mem_aPlus (hc.mul hc') (ePow_mem_aPlus _)
    | zero => rw [mul_zero]; exact zero_mem _
    | add y z _ _ hy hz => rw [mul_add]; exact add_mem hy hz
    | neg y _ hy => rw [mul_neg]; exact neg_mem hy
  | zero => rw [zero_mul]; exact zero_mem _
  | add x z _ _ hx hz => rw [add_mul]; exact add_mem hx hz
  | neg x _ hx => rw [neg_mul]; exact neg_mem hx

/-- The integral PBW monomials lie in `𝒜U⁺` (from [Lus] 41.1.3), for every Cartan datum. -/
lemma pbwDiv_mem_aPlus {W : Type*} [Group W]
    {cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W} :
    ∀ (w p : List I), cs.IsReduced (p ++ w) → ∀ c : Fin w.length → ℕ,
      (p.map (braidEquivOfNotRoot R ratFunc_X_not_root)).prod (pbwDiv R w c) ∈ aPlus R
  | [], p, _, c => by
    simpa [CoxeterSystem.pbwDivMonomial] using ePow_mem_aPlus (R := R) []
  | i :: w, p, hpw, c => by
    rw [pbwDiv, CoxeterSystem.pbwDivMonomial_cons, _root_.map_mul, Ta_apply, ← AlgEquiv.mul_apply,
      ← List.prod_concat, ← List.map_concat]
    refine mul_mem_aPlus ?_ (pbwDiv_mem_aPlus w (p.concat i) (by simpa using hpw) _)
    have hred : cs.IsReduced (p ++ [i]) := by
      have := hpw.take (p.length + 1)
      rwa [show (p ++ i :: w).take (p.length + 1) = p ++ [i] by
        rw [List.take_length_add_append]
        rfl] at this
    exact list_braid_qDivPow_E_mem_aPlus hred _

include hSL in
/-- **[Lus] 41.1.7** (`e = 1`, simply-laced finite type): for a reduced expression of the longest
element `w₀`, `𝒜U⁺(w₀, 1) = 𝒜U⁺`, the `𝒜`-subalgebra generated by the `Eᵢ^{(n)}`. With
`linearIndependent_pbwDiv`, the integral PBW monomials form an `𝒜`-basis of `𝒜U⁺`. -/
theorem span_pbwDiv_longest_eq {W : Type*} [Group W] [Finite W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : List I} (hw : cs.IsReduced w)
    (hw₀ : cs.wordProd w = cs.longestElement) :
    Submodule.span 𝒜 (Set.range (pbwDiv R w)) =
      (Algebra.adjoin 𝒜 (⋃ i, Set.range (Ed R i))).toSubmodule := by
  let S := Submodule.span 𝒜 (Set.range (pbwDiv R w))
  have hplus : ∀ c, pbwDiv R w c ∈ Algebra.adjoin 𝒜 (⋃ i, Set.range (Ed R i)) := fun c ↦ by
    have hc := pbwDiv_mem_aPlus (R := R) w [] (by simpa using hw) c
    simp only [List.map_nil, List.prod_nil, AlgEquiv.one_apply] at hc
    generalize pbwDiv R w c = y at hc ⊢
    induction hc using AddSubgroup.closure_induction with
    | mem x hx =>
      obtain ⟨c, w', hc, rfl⟩ := hx
      refine smul_mem_of_isLaurent hc ?_
      induction w' with
      | nil => exact one_mem _
      | cons p w' ih =>
        rw [ePow_cons]
        exact mul_mem (Algebra.subset_adjoin (Set.mem_iUnion.2 ⟨p.1, p.2, rfl⟩)) ih
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | neg x _ hx => exact neg_mem hx
  refine le_antisymm (Submodule.span_le.2 ?_) ?_
  · rintro _ ⟨c, rfl⟩; exact hplus c
  · intro x hx
    have h1 : (1 : QuantumGroup R 𝕧) ∈ S :=
      CoxeterSystem.one_mem_pbwDivSpan (Ta R) (Ed R) Ed_zero w
    have hmul : ∀ y ∈ S, x * y ∈ S := by
      induction hx using Algebra.adjoin_induction with
      | mem x hx =>
        obtain ⟨i, n, rfl⟩ := Set.mem_iUnion.1 hx
        exact fun y hy ↦ qDivPow_E_mul_mem_span_pbwDiv hSL cs hw
          (hw₀ ▸ cs.isLeftDescent_longestElement i) n hy
      | algebraMap a =>
        intro y hy
        rw [← Algebra.smul_def]
        exact S.smul_mem a hy
      | add x z _ _ hx hz =>
        intro y hy; rw [add_mul]; exact add_mem (hx y hy) (hz y hy)
      | mul x z _ _ hx hz =>
        intro y hy; rw [mul_assoc]; exact hx _ (hz y hy)
    simpa using hmul 1 h1

include hSL in
/-- **[Lus] 41.1.7**, second form: `𝒜U⁺(w₀, 1) = 𝒜U⁺ = aPlus R` (the `𝒜`-combinations of the
monomials in divided powers). -/
theorem coe_span_pbwDiv_longest {W : Type*} [Group W] [Finite W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : List I} (hw : cs.IsReduced w)
    (hw₀ : cs.wordProd w = cs.longestElement) :
    (Submodule.span 𝒜 (Set.range (pbwDiv R w)) : Set (QuantumGroup R 𝕧)) = aPlus R := by
  refine subset_antisymm (fun x hx ↦ ?_) (fun x hx ↦ ?_)
  · induction hx using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨c, rfl⟩ := hx
      simpa using pbwDiv_mem_aPlus (R := R) w [] (by simpa using hw) c
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | smul a x _ hx => rw [laurent_smul_U]; exact smul_mem_aPlus ⟨a, rfl⟩ hx
  · rw [SetLike.mem_coe, span_pbwDiv_longest_eq hSL cs hw hw₀]
    induction hx using AddSubgroup.closure_induction with
    | mem x hx =>
      obtain ⟨c, w', hc, rfl⟩ := hx
      refine smul_mem_of_isLaurent hc ?_
      induction w' with
      | nil => exact one_mem _
      | cons p w' ih =>
        rw [ePow_cons]
        exact mul_mem (Algebra.subset_adjoin (Set.mem_iUnion.2 ⟨p.1, p.2, rfl⟩)) ih
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | neg x _ hx => exact neg_mem hx

end Modified

end LieLean.QuantumGroup
