/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.Modified.Basic
import LieLean.Algebra.QuantumGroup.LusztigF.IntegralForm
import LieLean.Algebra.QuantumGroup.LusztigF.RatFunc

/-!
# The `𝒜`-form of `U̇` and the braid group action on `_R U̇`

Over `ℚ(v)` (`v = RatFunc.X`), with `𝒜 = ℤ[v, v⁻¹]` (`LaurentPolynomial ℤ`, embedded by
`LusztigF.integralLaurentEval`), Lusztig's `𝒜`-form `𝒜U̇` is the `𝒜`-subalgebra of `U̇` generated by
the elements `Eᵢ^{(n)} 1_λ`, `Fᵢ^{(n)} 1_λ` ([Lus] 23.2.2 (c); Lusztig defines `𝒜U̇` as the
`𝒜`-span of the `x⁺ 1_λ x'⁻`, `x, x' ∈ 𝒜f`, and proves in 23.2.2 (a), (c) that it is this
subalgebra).

## Main results

* `Modified.aForm`: `𝒜U̇`; `Modified.divE`, `Modified.divF` (`Eᵢ^{(n)} 1_λ`, `Fᵢ^{(n)} 1_λ`).
* `Modified.braid_mem_aForm`, `Modified.braid_symm_mem_aForm`: **the `Tᵢ`, `Tᵢ⁻¹` preserve `𝒜U̇`**
  ([Lus] 41.1.2, last assertion), from the divided-power formulas of [Lus] 37.1.3
  (`QuantumGroup/ModuleSymmetry/DividedPowers.lean`), and the resulting `𝒜`-linear automorphisms
  `Modified.braidA` of `𝒜U̇`, with the braid relations `Modified.isBraidLiftable_braidA`.
* `Modified.braidR S i`: for any `𝒜`-algebra `S` (for instance a field in which `v` is a root of
  unity), the `S`-linear multiplicative automorphisms `Tᵢ = 1 ⊗ Tᵢ` of `_S U̇ = S ⊗_𝒜 𝒜U̇`
  ([Lus] 41.1.8), with inverse induced by `T'_{i,-1}` (`braidR_symm_tmul`), the braid relations
  `Modified.isBraidLiftable_braidR` and the Artin group action `Modified.braidArtinHomR`
  (`braidArtinHomR_mul`). As in Lusztig, the relations over `𝒜` come from those over `ℚ(v)`
  (`𝒜U̇ ⊆ U̇`) and over `S` by change of rings.

## References

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, 23.2, 31.1.1, 41.1.
-/

open LieLean Finset TensorProduct

noncomputable section

namespace LieLean.QuantumGroup

local notation "𝕂" => RatFunc ℚ
local notation "𝕧" => (RatFunc.X : RatFunc ℚ)
local notation "𝒜" => LaurentPolynomial ℤ

/-- `v ≠ 0` in `ℚ(v)`. -/
theorem neZero_ratFunc_X : NeZero 𝕧 := ⟨RatFunc.X_ne_zero⟩

attribute [local instance] neZero_ratFunc_X

/-- `v` is not a root of unity in `ℚ(v)`. -/
theorem ratFunc_X_not_root : ∀ n : ℕ, 0 < n → 𝕧 ^ n ≠ 1 := fun _ hn ↦
  LusztigF.ratFunc_X_pow_ne_one hn

variable {I Y : Type*} [AddCommGroup Y] [DecidableEq I] {D : LusztigCartanDatum I}
  {R : D.RootDatum Y}

/-! ### Weights of divided powers -/

lemma pow_mem_adWeightSpace {χ : Y →+ ℤ} {x : QuantumGroup R 𝕧}
    (hx : x ∈ adWeightSpace R 𝕧 χ) (n : ℕ) : x ^ n ∈ adWeightSpace R 𝕧 (n • χ) := by
  induction n with
  | zero => simpa using one_mem_adWeightSpace
  | succ n ih => rw [pow_succ, succ_nsmul]; exact mul_mem_adWeightSpace ih hx

lemma F_mem_adWeightSpace (i : I) : F R 𝕧 i ∈ adWeightSpace R 𝕧 (-R.root i) :=
  fun μ ↦ K_mul_F R 𝕧 μ i

lemma qDivPow_E_mem (q : 𝕂) (i : I) (n : ℕ) :
    qDivPow q n (E R 𝕧 i) ∈ adWeightSpace R 𝕧 (n • R.root i) :=
  Submodule.smul_mem _ _ (pow_mem_adWeightSpace (E_mem_adWeightSpace i) n)

lemma qDivPow_F_mem (q : 𝕂) (i : I) (n : ℕ) :
    qDivPow q n (F R 𝕧 i) ∈ adWeightSpace R 𝕧 (n • -R.root i) :=
  Submodule.smul_mem _ _ (pow_mem_adWeightSpace (F_mem_adWeightSpace i) n)

namespace Modified

/-! ### `U̇` as an `𝒜`-module -/

instance laurentModule : Module 𝒜 (Modified R 𝕧) :=
  Module.compHom _ LusztigF.integralLaurentEval

lemma laurent_smul (a : 𝒜) (x : Modified R 𝕧) : a • x = LusztigF.integralLaurentEval a • x :=
  rfl

instance : IsScalarTower 𝒜 (Modified R 𝕧) (Modified R 𝕧) := ⟨fun _ x y ↦ smul_mul' _ x y⟩

instance : SMulCommClass 𝒜 (Modified R 𝕧) (Modified R 𝕧) :=
  ⟨fun _ x y ↦ (mul_smul' _ x y).symm⟩

/-! ### The `𝒜`-form -/

variable (R) in
/-- `Eᵢ^{(n)} 1_λ`. -/
def divE (i : I) (n : ℕ) (l : Y →+ ℤ) : Modified R 𝕧 :=
  elt (l + n • R.root i) l (qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i))
    (by rw [add_sub_cancel_left]; exact qDivPow_E_mem _ i n)

variable (R) in
/-- `Fᵢ^{(n)} 1_λ`. -/
def divF (i : I) (n : ℕ) (l : Y →+ ℤ) : Modified R 𝕧 :=
  elt (l + n • -R.root i) l (qDivPow (𝕧 ^ D.d i) n (F R 𝕧 i))
    (by rw [add_sub_cancel_left]; exact qDivPow_F_mem _ i n)

variable (R) in
/-- **Lusztig's `𝒜`-form `𝒜U̇`**: the `𝒜`-subalgebra of `U̇` generated by the `1_λ` and the
`Eᵢ^{(n)} 1_λ`, `Fᵢ^{(n)} 1_λ` ([Lus] 23.2.2 (c); `1_λ = Eᵢ^{(0)} 1_λ` when `I` is nonempty). -/
def aForm : NonUnitalSubalgebra 𝒜 (Modified R 𝕧) :=
  NonUnitalAlgebra.adjoin 𝒜
    ({x | ∃ l, x = one l} ∪ {x | ∃ i n l, x = divE R i n l ∨ x = divF R i n l})

lemma one_mem_aForm (l : Y →+ ℤ) : one l ∈ aForm R :=
  NonUnitalAlgebra.subset_adjoin 𝒜 (Or.inl ⟨l, rfl⟩)

lemma divE_mem (i : I) (n : ℕ) (l : Y →+ ℤ) : divE R i n l ∈ aForm R :=
  NonUnitalAlgebra.subset_adjoin 𝒜 (Or.inr ⟨i, n, l, Or.inl rfl⟩)

lemma divF_mem (i : I) (n : ℕ) (l : Y →+ ℤ) : divF R i n l ∈ aForm R :=
  NonUnitalAlgebra.subset_adjoin 𝒜 (Or.inr ⟨i, n, l, Or.inr rfl⟩)

/-! ### Laurent scalars -/

/-- `c ∈ ℚ(v)` lies in the image of `𝒜`. -/
def IsLaurent (c : 𝕂) : Prop := ∃ a : 𝒜, LusztigF.integralLaurentEval a = c

lemma isLaurent_zpow (m : ℤ) : IsLaurent (𝕧 ^ m) := ⟨LaurentPolynomial.T m, by simp⟩

lemma isLaurent_neg_one : IsLaurent (-1) := ⟨-1, by simp⟩

lemma IsLaurent.mul {c c' : 𝕂} (h : IsLaurent c) (h' : IsLaurent c') : IsLaurent (c * c') := by
  obtain ⟨a, rfl⟩ := h; obtain ⟨a', rfl⟩ := h'; exact ⟨a * a', _root_.map_mul _ _ _⟩

lemma IsLaurent.pow {c : 𝕂} (h : IsLaurent c) (n : ℕ) : IsLaurent (c ^ n) := by
  obtain ⟨a, rfl⟩ := h; exact ⟨a ^ n, _root_.map_pow _ _ _⟩

lemma isLaurent_pow (m : ℕ) : IsLaurent (𝕧 ^ m) := by
  simpa using isLaurent_zpow (m : ℤ)

lemma isLaurent_inv_pow (m : ℕ) : IsLaurent (𝕧⁻¹ ^ m) := by
  simpa [inv_pow, zpow_neg] using isLaurent_zpow (-(m : ℤ))

lemma smul_mem_aForm {c : 𝕂} (hc : IsLaurent c) {x : Modified R 𝕧} (hx : x ∈ aForm R) :
    c • x ∈ aForm R := by
  obtain ⟨a, rfl⟩ := hc
  exact SMulMemClass.smul_mem a hx

lemma isLaurent_inv_pow_pow (d r : ℕ) : IsLaurent ((𝕧 ^ d)⁻¹ ^ r) := by
  rw [← inv_pow, ← pow_mul]; exact isLaurent_inv_pow _

lemma isLaurent_pow_pow (d r : ℕ) : IsLaurent ((𝕧 ^ d) ^ r) := by
  rw [← pow_mul]; exact isLaurent_pow _

lemma smul_mem_aForm_iff_laurent (a : 𝒜) {x : Modified R 𝕧} (hx : x ∈ aForm R) :
    a • x ∈ aForm R :=
  SMulMemClass.smul_mem a hx

/-! ### Elements `x ∈ U_χ` with `π_{λ+χ,λ}(x) ∈ 𝒜U̇` -/

variable (R) in
/-- `x ∈ U_χ` and `π_{λ+χ,λ}(x) ∈ 𝒜U̇` for every `λ`. -/
def IsGen (x : QuantumGroup R 𝕧) (χ : Y →+ ℤ) : Prop :=
  ∃ hx : x ∈ adWeightSpace R 𝕧 χ,
    ∀ l, elt (l + χ) l x (by rw [add_sub_cancel_left]; exact hx) ∈ aForm R

lemma IsGen.elt_mem {x : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (h : IsGen R x χ) {l₁ l₂ : Y →+ ℤ}
    (hl : l₁ - l₂ = χ) (hx : x ∈ adWeightSpace R 𝕧 (l₁ - l₂)) : elt l₁ l₂ x hx ∈ aForm R := by
  obtain ⟨_, h⟩ := h
  have e : l₁ = l₂ + χ := by rw [← hl]; abel
  rw [elt_index e rfl rfl hx]
  exact h l₂

lemma IsGen.congr {x : QuantumGroup R 𝕧} {χ χ' : Y →+ ℤ} (h : IsGen R x χ) (e : χ = χ') :
    IsGen R x χ' :=
  e ▸ h

lemma IsGen.of_eq {x y : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (e : x = y) (h : IsGen R y χ) :
    IsGen R x χ :=
  e ▸ h

lemma IsGen.mul {x y : QuantumGroup R 𝕧} {χ χ' : Y →+ ℤ} (hx : IsGen R x χ)
    (hy : IsGen R y χ') : IsGen R (x * y) (χ + χ') := by
  refine ⟨mul_mem_adWeightSpace hx.1 hy.1, fun l ↦ ?_⟩
  have hx' : x ∈ adWeightSpace R 𝕧 (l + (χ + χ') - (l + χ')) := by
    rw [show l + (χ + χ') - (l + χ') = χ by abel]; exact hx.1
  have hy' : y ∈ adWeightSpace R 𝕧 (l + χ' - l) := by rw [add_sub_cancel_left]; exact hy.1
  rw [← elt_mul_elt _ _ _ hx' hy']
  exact mul_mem (hx.elt_mem (by abel) _) (hy.elt_mem (by abel) _)

lemma IsGen.add {x y : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (hx : IsGen R x χ) (hy : IsGen R y χ) :
    IsGen R (x + y) χ := by
  refine ⟨add_mem hx.1 hy.1, fun l ↦ ?_⟩
  rw [elt_add _ _ (by rw [add_sub_cancel_left]; exact hx.1)
    (by rw [add_sub_cancel_left]; exact hy.1)]
  exact add_mem (hx.2 l) (hy.2 l)

lemma elt_zero' (l₁ l₂ : Y →+ ℤ) (h : (0 : QuantumGroup R 𝕧) ∈ adWeightSpace R 𝕧 (l₁ - l₂)) :
    elt l₁ l₂ 0 h = 0 := by
  rw [elt]
  exact (congrArg _ (map_zero _)).trans (map_zero _)

lemma isGen_zero (χ : Y →+ ℤ) : IsGen R 0 χ :=
  ⟨zero_mem _, fun l ↦ by rw [elt_zero']; exact zero_mem _⟩

lemma IsGen.smul {x : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (hx : IsGen R x χ) {c : 𝕂}
    (hc : IsLaurent c) : IsGen R (c • x) χ := by
  refine ⟨Submodule.smul_mem _ _ hx.1, fun l ↦ ?_⟩
  rw [elt_smul _ _ _ (by rw [add_sub_cancel_left]; exact hx.1)]
  exact smul_mem_aForm hc (hx.2 l)

lemma IsGen.sum {ι : Type*} (s : Finset ι) {x : ι → QuantumGroup R 𝕧} {χ : Y →+ ℤ}
    (hx : ∀ r ∈ s, IsGen R (x r) χ) : IsGen R (∑ r ∈ s, x r) χ := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using isGen_zero χ
  | insert a s ha ih =>
    rw [sum_insert ha]
    exact (hx a (mem_insert_self a s)).add (ih fun r hr ↦ hx r (mem_insert_of_mem hr))

lemma IsGen.K_mul {x : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (hx : IsGen R x χ) (μ : Y) :
    IsGen R (K R 𝕧 μ * x) χ := by
  refine ⟨by simpa using mul_mem_adWeightSpace (K_mem_adWeightSpace μ) hx.1, fun l ↦ ?_⟩
  rw [elt_K_mul _ _ _ (by rw [add_sub_cancel_left]; exact hx.1)]
  exact smul_mem_aForm (isLaurent_zpow _) (hx.2 l)

lemma IsGen.mul_K {x : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (hx : IsGen R x χ) (μ : Y) :
    IsGen R (x * K R 𝕧 μ) χ := by
  refine ⟨by simpa using mul_mem_adWeightSpace hx.1 (K_mem_adWeightSpace μ), fun l ↦ ?_⟩
  rw [elt_mul_K _ _ _ (by rw [add_sub_cancel_left]; exact hx.1)]
  exact smul_mem_aForm (isLaurent_zpow _) (hx.2 l)

lemma isGen_one : IsGen R 1 0 :=
  ⟨one_mem_adWeightSpace, fun l ↦ by
    rw [elt_index (add_zero l) rfl rfl _ (by rw [sub_self]; exact one_mem_adWeightSpace)]
    exact one_mem_aForm l⟩

lemma isGen_E (i : I) (n : ℕ) :
    IsGen R (qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i)) (n • R.root i) :=
  ⟨qDivPow_E_mem _ i n, fun l ↦ divE_mem i n l⟩

lemma isGen_F (i : I) (n : ℕ) :
    IsGen R (qDivPow (𝕧 ^ D.d i) n (F R 𝕧 i)) (n • -R.root i) :=
  ⟨qDivPow_F_mem _ i n, fun l ↦ divF_mem i n l⟩

/-! ### The `Tᵢ` preserve `𝒜U̇` ([Lus] 41.1.2) -/

section Braid

variable (i : I)

section Weights

variable {i}

omit [DecidableEq I] in
lemma root_comp_reflY_apply (j : I) (μ : Y) :
    (R.root j).comp (reflY R i) μ = R.root j μ - R.root i μ * D.cartanMatrix i j := by
  simp [reflY_apply, R.root_coroot]

omit [DecidableEq I] in
lemma root_reflY_apply' (j : I) (μ : Y) :
    R.root j (reflY R i μ) = R.root j μ - R.root i μ * D.cartanMatrix i j :=
  root_comp_reflY_apply j μ

omit [DecidableEq I] in
lemma wt_E_ne {j : I} (hji : j ≠ i) (n r : ℕ) (hr : r ≤ negA D i j * n) :
    (negA D i j * n - r) • R.root i + n • R.root j + r • R.root i =
      (n • R.root j).comp (reflY R i) := by
  classical
  ext μ
  have hc := cartanMatrix_eq_neg_negA (D := D) (Ne.symm hji)
  simp only [AddMonoidHom.add_apply, AddMonoidHom.nsmul_apply, AddMonoidHom.comp_apply,
    nsmul_eq_mul, root_reflY_apply', hc]
  push_cast [Nat.cast_sub hr]; ring

omit [DecidableEq I] in
lemma wt_E_ne' {j : I} (hji : j ≠ i) (n r : ℕ) (hr : r ≤ negA D i j * n) :
    r • R.root i + n • R.root j + (negA D i j * n - r) • R.root i =
      (n • R.root j).comp (reflY R i) := by
  rw [← wt_E_ne hji n r hr]; abel

omit [DecidableEq I] in
lemma wt_F_ne' {j : I} (hji : j ≠ i) (n r : ℕ) (hr : r ≤ negA D i j * n) :
    (negA D i j * n - r) • -R.root i + n • -R.root j + r • -R.root i =
      (n • -R.root j).comp (reflY R i) := by
  classical
  ext μ
  have hc := cartanMatrix_eq_neg_negA (D := D) (Ne.symm hji)
  simp only [AddMonoidHom.add_apply, AddMonoidHom.nsmul_apply, AddMonoidHom.neg_apply,
    AddMonoidHom.comp_apply, nsmul_eq_mul, root_reflY_apply', hc]
  push_cast [Nat.cast_sub hr]; ring

omit [DecidableEq I] in
lemma wt_F_ne {j : I} (hji : j ≠ i) (n r : ℕ) (hr : r ≤ negA D i j * n) :
    r • -R.root i + n • -R.root j + (negA D i j * n - r) • -R.root i =
      (n • -R.root j).comp (reflY R i) := by
  rw [← wt_F_ne' hji n r hr]; abel

omit [DecidableEq I] in
lemma wt_E_self (n : ℕ) : n • -R.root i = (n • R.root i).comp (reflY R i) := by
  ext μ
  simp only [AddMonoidHom.nsmul_apply, AddMonoidHom.neg_apply, AddMonoidHom.comp_apply]
  rw [root_reflY_apply', D.cartanMatrix_self]
  ring

omit [DecidableEq I] in
lemma wt_F_self (n : ℕ) : n • R.root i = (n • -R.root i).comp (reflY R i) := by
  ext μ
  simp only [AddMonoidHom.nsmul_apply, AddMonoidHom.neg_apply, AddMonoidHom.comp_apply]
  rw [root_reflY_apply', D.cartanMatrix_self]
  ring

end Weights

lemma isGen_braidEjDiv {j : I} (hji : j ≠ i) (n : ℕ) :
    IsGen R (braidEjDiv R 𝕧 i j n) ((n • R.root j).comp (reflY R i)) := by
  refine IsGen.sum _ fun r hr ↦ ?_
  have hr' : r ≤ negA D i j * n := by rw [mem_range] at hr; omega
  refine IsGen.smul (IsGen.congr (((isGen_E i _).mul (isGen_E j n)).mul (isGen_E i r))
    (wt_E_ne hji n r hr')) ?_
  exact isLaurent_neg_one.pow r |>.mul (isLaurent_inv_pow_pow _ _)

lemma isGen_braidFjDiv {j : I} (hji : j ≠ i) (n : ℕ) :
    IsGen R (braidFjDiv R 𝕧 i j n) ((n • -R.root j).comp (reflY R i)) := by
  refine IsGen.sum _ fun r hr ↦ ?_
  have hr' : r ≤ negA D i j * n := by rw [mem_range] at hr; omega
  refine IsGen.smul (IsGen.congr (((isGen_F i r).mul (isGen_F j n)).mul (isGen_F i _))
    (wt_F_ne hji n r hr')) ?_
  exact isLaurent_neg_one.pow r |>.mul (isLaurent_pow_pow _ _)

lemma braid_elt_mem {l₁ l₂ : Y →+ ℤ} {u : QuantumGroup R 𝕧}
    (hu : u ∈ adWeightSpace R 𝕧 (l₁ - l₂)) {χ : Y →+ ℤ}
    (hT : IsGen R (braidEquivOfNotRoot R ratFunc_X_not_root i u) χ)
    (hχ : l₁.comp (reflY R i) - l₂.comp (reflY R i) = χ) :
    braid ratFunc_X_not_root i (elt l₁ l₂ u hu) ∈ aForm R := by
  rw [braid_elt ratFunc_X_not_root i l₁ l₂ hu (by rw [hχ]; exact hT.1)]
  exact hT.elt_mem hχ _

lemma braid_symm_elt_mem {l₁ l₂ : Y →+ ℤ} {u : QuantumGroup R 𝕧}
    (hu : u ∈ adWeightSpace R 𝕧 (l₁ - l₂)) {χ : Y →+ ℤ}
    (hT : IsGen R ((braidEquivOfNotRoot R ratFunc_X_not_root i).symm u) χ)
    (hχ : l₁.comp (reflY R i) - l₂.comp (reflY R i) = χ) :
    (braid ratFunc_X_not_root i).symm (elt l₁ l₂ u hu) ∈ aForm R := by
  rw [braid_symm_elt ratFunc_X_not_root i l₁ l₂ hu (by rw [hχ]; exact hT.1)]
  exact hT.elt_mem hχ _

omit [DecidableEq I] in
lemma comp_sub_comp (l χ : Y →+ ℤ) :
    (l + χ).comp (reflY R i) - l.comp (reflY R i) = χ.comp (reflY R i) := by
  ext μ; simp

lemma braid_gen_mem {x : Modified R 𝕧}
    (hx : x ∈ {x | ∃ l, x = one l} ∪ {x | ∃ i n l, x = divE R i n l ∨ x = divF R i n l}) :
    braid ratFunc_X_not_root i x ∈ aForm R ∧ (braid ratFunc_X_not_root i).symm x ∈ aForm R := by
  have hv := ratFunc_X_not_root
  rcases hx with ⟨l, rfl⟩ | ⟨j, n, l, rfl | rfl⟩
  · have h1 : ∀ l : Y →+ ℤ, l.comp (reflY R i) - l.comp (reflY R i) = 0 := fun l ↦ sub_self _
    refine ⟨braid_elt_mem i _ (IsGen.of_eq (_root_.map_one _) isGen_one) (h1 l),
      braid_symm_elt_mem i _ (IsGen.of_eq (_root_.map_one _) isGen_one) (h1 l)⟩
  · by_cases hji : j = i
    · subst hji
      refine ⟨braid_elt_mem j _ (IsGen.of_eq (braidEquivOfNotRoot_qDivPow_E_self hv R j n)
          (((isGen_F j n).mul_K _).smul ((isLaurent_neg_one.pow n).mul
            (isLaurent_inv_pow_pow _ _)))) ?_,
        braid_symm_elt_mem j _ (IsGen.of_eq (braidEquivOfNotRoot_symm_qDivPow_E_self hv R j n)
          (((isGen_F j n).K_mul _).smul ((isLaurent_neg_one.pow n).mul
            (isLaurent_inv_pow_pow _ _)))) ?_⟩ <;>
      rw [comp_sub_comp, ← wt_E_self]
    · refine ⟨braid_elt_mem i _ (IsGen.of_eq (braidEquivOfNotRoot_qDivPow_E_ne hv R hji n)
          (isGen_braidEjDiv i hji n)) (comp_sub_comp i _ _),
        braid_symm_elt_mem i _ (IsGen.of_eq (braidEquivOfNotRoot_symm_qDivPow_E_ne hv R hji n)
          (IsGen.sum _ fun r hr ↦ ?_)) (comp_sub_comp i _ _)⟩
      have hr' : r ≤ negA D i j * n := by rw [mem_range] at hr; omega
      refine IsGen.smul (IsGen.congr (((isGen_E i r).mul (isGen_E j n)).mul (isGen_E i _))
        (wt_E_ne' hji n r hr')) ?_
      exact isLaurent_neg_one.pow r |>.mul (isLaurent_inv_pow_pow _ _)
  · by_cases hji : j = i
    · subst hji
      refine ⟨braid_elt_mem j _ (IsGen.of_eq (braidEquivOfNotRoot_qDivPow_F_self hv R j n)
          (((isGen_E j n).K_mul _).smul ((isLaurent_neg_one.pow n).mul
            (isLaurent_pow_pow _ _)))) ?_,
        braid_symm_elt_mem j _ (IsGen.of_eq (braidEquivOfNotRoot_symm_qDivPow_F_self hv R j n)
          (((isGen_E j n).mul_K _).smul ((isLaurent_neg_one.pow n).mul
            (isLaurent_pow_pow _ _)))) ?_⟩ <;>
      rw [comp_sub_comp, ← wt_F_self]
    · refine ⟨braid_elt_mem i _ (IsGen.of_eq (braidEquivOfNotRoot_qDivPow_F_ne hv R hji n)
          (isGen_braidFjDiv i hji n)) (comp_sub_comp i _ _),
        braid_symm_elt_mem i _ (IsGen.of_eq (braidEquivOfNotRoot_symm_qDivPow_F_ne hv R hji n)
          (IsGen.sum _ fun r hr ↦ ?_)) (comp_sub_comp i _ _)⟩
      have hr' : r ≤ negA D i j * n := by rw [mem_range] at hr; omega
      refine IsGen.smul (IsGen.congr (((isGen_F i _).mul (isGen_F j n)).mul (isGen_F i r))
        (wt_F_ne' hji n r hr')) ?_
      exact isLaurent_neg_one.pow r |>.mul (isLaurent_pow_pow _ _)

/-- **The `Tᵢ` preserve `𝒜U̇`** ([Lus] 41.1.2). -/
theorem braid_mem_aForm {x : Modified R 𝕧} (hx : x ∈ aForm R) :
    braid ratFunc_X_not_root i x ∈ aForm R := by
  induction hx using NonUnitalAlgebra.adjoin_induction with
  | mem x hx => exact (braid_gen_mem i hx).1
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | zero => rw [map_zero]; exact zero_mem _
  | mul x y _ _ hx hy => rw [braid_mul]; exact mul_mem hx hy
  | smul a x _ hx => rw [laurent_smul, map_smul, ← laurent_smul]; exact SMulMemClass.smul_mem a hx

/-- **The `Tᵢ⁻¹ = T'_{i,-1}` preserve `𝒜U̇`** ([Lus] 41.1.2). -/
theorem braid_symm_mem_aForm {x : Modified R 𝕧} (hx : x ∈ aForm R) :
    (braid ratFunc_X_not_root i).symm x ∈ aForm R := by
  induction hx using NonUnitalAlgebra.adjoin_induction with
  | mem x hx => exact (braid_gen_mem i hx).2
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | zero => rw [map_zero]; exact zero_mem _
  | mul x y _ _ hx hy =>
    have : (braid ratFunc_X_not_root i).symm (x * y) =
        (braid ratFunc_X_not_root i).symm x * (braid ratFunc_X_not_root i).symm y := by
      rw [LinearEquiv.symm_apply_eq, braid_mul, LinearEquiv.apply_symm_apply,
        LinearEquiv.apply_symm_apply]
    rw [this]; exact mul_mem hx hy
  | smul a x _ hx => rw [laurent_smul, map_smul, ← laurent_smul]; exact SMulMemClass.smul_mem a hx

end Braid

/-! ### The braid group action on `𝒜U̇` -/

variable (R) in
/-- The multiplicative linear automorphisms of `U̇` preserving `𝒜U̇` together with their
inverses. -/
def stab : Subgroup (Modified R 𝕧 ≃ₗ[𝕂] Modified R 𝕧) where
  carrier := {f | (∀ x ∈ aForm R, f x ∈ aForm R) ∧ (∀ x ∈ aForm R, f.symm x ∈ aForm R) ∧
    ∀ x y, f (x * y) = f x * f y}
  mul_mem' {f g} hf hg := ⟨fun x hx ↦ hf.1 _ (hg.1 x hx), fun x hx ↦ hg.2.1 _ (hf.2.1 x hx),
    fun x y ↦ by
      change f (g (x * y)) = f (g x) * f (g y)
      rw [hg.2.2, hf.2.2]⟩
  one_mem' := ⟨fun x hx ↦ hx, fun x hx ↦ hx, fun x y ↦ rfl⟩
  inv_mem' {f} hf := ⟨hf.2.1, hf.1, fun x y ↦ by
    change f.symm (x * y) = f.symm x * f.symm y
    rw [LinearEquiv.symm_apply_eq, hf.2.2, LinearEquiv.apply_symm_apply,
      LinearEquiv.apply_symm_apply]⟩

lemma stab_smul (f : Modified R 𝕧 ≃ₗ[𝕂] Modified R 𝕧) (a : 𝒜) (x : Modified R 𝕧) :
    f (a • x) = a • f x := by
  rw [laurent_smul, map_smul, laurent_smul]

variable (R) in
/-- Restriction to `𝒜U̇`. -/
def restrictHom : stab R →* (aForm R ≃ₗ[𝒜] aForm R) where
  toFun f :=
    { toFun := fun x ↦ ⟨f.1 (x : Modified R 𝕧), f.2.1 _ x.2⟩
      invFun := fun x ↦ ⟨f.1.symm (x : Modified R 𝕧), f.2.2.1 _ x.2⟩
      map_add' := fun x y ↦ Subtype.ext (map_add f.1 (x : Modified R 𝕧) y)
      map_smul' := fun a x ↦ Subtype.ext (stab_smul f.1 a (x : Modified R 𝕧))
      left_inv := fun x ↦ Subtype.ext (f.1.symm_apply_apply (x : Modified R 𝕧))
      right_inv := fun x ↦ Subtype.ext (f.1.apply_symm_apply (x : Modified R 𝕧)) }
  map_one' := rfl
  map_mul' _ _ := rfl

lemma restrictHom_mul (f : stab R) (x y : aForm R) :
    restrictHom R f (x * y) = restrictHom R f x * restrictHom R f y :=
  Subtype.ext (f.2.2.2 x y)

/-- `Tᵢ ∈ stab`. -/
def braidStab (i : I) : stab R :=
  ⟨braid ratFunc_X_not_root i, fun _ hx ↦ braid_mem_aForm i hx,
    fun _ hx ↦ braid_symm_mem_aForm i hx, braid_mul ratFunc_X_not_root i⟩

theorem isBraidLiftable_braidStab :
    D.cartanMatrix.coxeterMatrix.IsBraidLiftable (braidStab (R := R)) := fun i j hij hm ↦ by
  apply Subtype.ext
  have h := isBraidLiftable_braid (R := R) ratFunc_X_not_root i j hij hm
  rw [← (stab R).coe_subtype, map_list_prod, map_list_prod, List.map_map, List.map_map]
  exact h

/-- **Lusztig's `Tᵢ` on `𝒜U̇`** ([Lus] 41.1.2): an `𝒜`-linear automorphism, multiplicative
(`braidA_mul`), with inverse induced by `T'_{i,-1}`. -/
def braidA (i : I) : aForm R ≃ₗ[𝒜] aForm R := restrictHom R (braidStab i)

@[simp] lemma braidA_apply (i : I) (x : aForm R) :
    (braidA i x : Modified R 𝕧) = braid ratFunc_X_not_root i x :=
  rfl

@[simp] lemma braidA_symm_apply (i : I) (x : aForm R) :
    ((braidA i).symm x : Modified R 𝕧) = (braid ratFunc_X_not_root i).symm x :=
  rfl

lemma braidA_mul (i : I) (x y : aForm R) : braidA i (x * y) = braidA i x * braidA i y :=
  restrictHom_mul _ x y

/-- **The braid relations on `𝒜U̇`** ([Lus] 41.1.8, `R = 𝒜`; by reduction to `ℚ(v)`). -/
theorem isBraidLiftable_braidA :
    D.cartanMatrix.coxeterMatrix.IsBraidLiftable (braidA (R := R)) := fun i j hij hm ↦ by
  have h := congrArg (restrictHom R) (isBraidLiftable_braidStab (R := R) i j hij hm)
  rwa [map_list_prod, map_list_prod, List.map_map, List.map_map] at h

/-! ### Change of rings: `_S U̇ = S ⊗_𝒜 𝒜U̇` ([Lus] 31.1.1, 41.1.8) -/

section ChangeOfRings

variable (S : Type*) [CommRing S] [Algebra 𝒜 S]

variable (R) in
/-- Base change of `𝒜`-linear automorphisms of `𝒜U̇` to `S ⊗_𝒜 𝒜U̇`. -/
def baseChangeHom : (aForm R ≃ₗ[𝒜] aForm R) →* (S ⊗[𝒜] aForm R ≃ₗ[S] S ⊗[𝒜] aForm R) where
  toFun e := LinearEquiv.baseChange 𝒜 S _ _ e
  map_one' := LinearEquiv.ext fun x ↦ by
    induction x using TensorProduct.inductionOn with
    | tmul s x => rfl
    | add x y hx hy => rw [map_add, hx, hy, map_add]
  map_mul' e f := LinearEquiv.ext fun x ↦ by
    induction x using TensorProduct.inductionOn with
    | tmul s x => rfl
    | add x y hx hy => rw [map_add, hx, hy, map_add]

lemma baseChangeHom_tmul (e : aForm R ≃ₗ[𝒜] aForm R) (s : S) (x : aForm R) :
    baseChangeHom R S e (s ⊗ₜ x) = s ⊗ₜ e x :=
  rfl

lemma baseChangeHom_mul {e : aForm R ≃ₗ[𝒜] aForm R} (he : ∀ x y, e (x * y) = e x * e y)
    (x y : S ⊗[𝒜] aForm R) :
    baseChangeHom R S e (x * y) = baseChangeHom R S e x * baseChangeHom R S e y := by
  induction x using TensorProduct.inductionOn with
  | add x x' hx hx' => rw [add_mul, map_add, hx, hx', map_add, add_mul]
  | tmul s a =>
    induction y using TensorProduct.inductionOn with
    | add y y' hy hy' => rw [mul_add, map_add, hy, hy', map_add, mul_add]
    | tmul s' b =>
      rw [Algebra.TensorProduct.tmul_mul_tmul, baseChangeHom_tmul, baseChangeHom_tmul,
        baseChangeHom_tmul, he, Algebra.TensorProduct.tmul_mul_tmul]

/-- **Lusztig's `Tᵢ` on `_S U̇ = S ⊗_𝒜 𝒜U̇`** for any `𝒜`-algebra `S` ([Lus] 41.1.8), e.g. a
field in which `v` specializes to a root of unity. -/
def braidR (i : I) : S ⊗[𝒜] aForm R ≃ₗ[S] S ⊗[𝒜] aForm R := baseChangeHom R S (braidA i)

@[simp] lemma braidR_tmul (i : I) (s : S) (x : aForm R) :
    braidR S i (s ⊗ₜ x) = s ⊗ₜ braidA i x :=
  rfl

/-- The inverse of `Tᵢ` on `_S U̇` is induced by `T'_{i,-1}` ([Lus] 41.1.8). -/
@[simp] lemma braidR_symm_tmul (i : I) (s : S) (x : aForm R) :
    (braidR S i).symm (s ⊗ₜ x) = s ⊗ₜ (braidA i).symm x :=
  rfl

lemma braidR_mul (i : I) (x y : S ⊗[𝒜] aForm R) :
    braidR S i (x * y) = braidR S i x * braidR S i y :=
  baseChangeHom_mul S (braidA_mul i) x y

/-- **The braid relations on `_S U̇`** ([Lus] 41.1.8): for every `𝒜`-algebra `S` and every
Cartan datum, by change of rings from `𝒜`. -/
theorem isBraidLiftable_braidR :
    D.cartanMatrix.coxeterMatrix.IsBraidLiftable (braidR (R := R) S) := fun i j hij hm ↦ by
  have h := congrArg (baseChangeHom R S) (isBraidLiftable_braidA (R := R) i j hij hm)
  rwa [map_list_prod, map_list_prod, List.map_map, List.map_map] at h

/-- **The Artin group action on `_S U̇`** ([Lus] 41.1.8), by multiplicative `S`-linear
automorphisms (`braidArtinHomR_mul`). -/
def braidArtinHomR :
    D.cartanMatrix.coxeterMatrix.ArtinGroup →* (S ⊗[𝒜] aForm R ≃ₗ[S] S ⊗[𝒜] aForm R) :=
  ((baseChangeHom R S).comp (restrictHom R)).comp
    (CoxeterMatrix.artinLift braidStab isBraidLiftable_braidStab)

@[simp] theorem braidArtinHomR_artinGenerator (i : I) :
    braidArtinHomR (R := R) S (D.cartanMatrix.coxeterMatrix.artinGenerator i) = braidR S i :=
  congrArg (fun f ↦ baseChangeHom R S (restrictHom R f))
    (CoxeterMatrix.artinLift_artinGenerator _ _ i)

theorem braidArtinHomR_mul (g : D.cartanMatrix.coxeterMatrix.ArtinGroup)
    (x y : S ⊗[𝒜] aForm R) :
    braidArtinHomR S g (x * y) = braidArtinHomR S g x * braidArtinHomR S g y :=
  baseChangeHom_mul S (restrictHom_mul _) x y

end ChangeOfRings

end Modified

end LieLean.QuantumGroup
