/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.Modified.IntegralPBW
import LieLean.Algebra.QuantumGroup.PBW.IndependenceSymm

/-!
# Integral PBW bases for `e = -1` in simply-laced type ([Lus] 41.1.4 (a), 41.1.7, 42.1.4)

Over `ℚ(v)`, `𝒜 = ℤ[v, v⁻¹]`, for `T'_{i,-1} = Tᵢ⁻¹` and a reduced expression `s_{i₁} ⋯ s_{iₙ}` of
`w ∈ W`, the divided-power PBW monomials
`E_{i₁}^{(c₁)} T'_{i₁,-1}(E_{i₂}^{(c₂)}) ⋯ T'_{i₁,-1} ⋯ T'_{iₙ₋₁,-1}(E_{iₙ}^{(cₙ)})`
(`Modified.pbwDivSymm`; these are Lusztig's `E_h^c` of [Lus] 42.1.4 (a)) are `𝒜`-linearly
independent (`linearIndependent_pbwDivSymm`, every Cartan datum). For simply-laced Cartan data
their `𝒜`-span `𝒜U⁺(w, -1)` does not depend on the reduced expression
(`span_pbwDivSymm_of_isReduced`, [Lus] 41.1.4 (a) for `e = -1`),
`Eᵢ^{(t)} 𝒜U⁺(w, -1) ⊆ 𝒜U⁺(w, -1)` if `ℓ(sᵢ w) < ℓ(w)`
(`qDivPow_E_mul_mem_span_pbwDivSymm`, 41.1.4 (c)), and in finite type `𝒜U⁺(w₀, -1) = 𝒜U⁺`
(`coe_span_pbwDivSymm_longest`, 41.1.7).

The rank-two input is Lusztig's 42.1.2 (b), in the order `β γ α` of `E_h^c`
(`A2Integral.qDivPow_mul_qDivPow_eq_sum_lusztig`), which is the straightening
`A2Integral.qDivPow_mul_qDivPow_eq_sum` at the parameter `v⁻¹`: in type `A₂`, with `α = Eⱼ`,
`β = Eᵢ`, `γ = αβ - v⁻¹βα = T'_{i,-1}(Eⱼ)`, the monomials `β^{(a)} γ^{(b)} α^{(c)}` along `iji`
span the integral form of the subalgebra generated by `Eᵢ, Eⱼ` (`span_pbwDivSymm_a2`, using the
stability statements of `PBW/IntegralA2.lean` at the parameter `v⁻¹`).

## References

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, 40.2.1, 41.1.4, 41.1.7,
  42.1.2, 42.1.4.
-/

open LieLean Finset

noncomputable section

namespace LieLean.QuantumGroup

local notation "𝕂" => RatFunc ℚ
local notation "𝕧" => (RatFunc.X : RatFunc ℚ)
local notation "𝒜" => LaurentPolynomial ℤ

attribute [local instance] neZero_ratFunc_X

variable {I Y : Type*} [AddCommGroup Y] [DecidableEq I] {D : LusztigCartanDatum I}
  {R : D.RootDatum Y}

namespace Modified

attribute [local instance] laurentAlgebraK laurentAlgebraU laurentTowerU

lemma Ta_symm_apply (i : I) (x : QuantumGroup R 𝕧) :
    (Ta R i).symm x = (braidEquivOfNotRoot R ratFunc_X_not_root i).symm x := rfl

variable (R) in
/-- **The integral PBW monomials for `e = -1`**: `E_{i₁}^{(c₁)} T_{i₁}⁻¹(E_{i₂}^{(c₂)}) ⋯`
([Lus] 42.1.4 (a)). -/
abbrev pbwDivSymm (ω : List I) : (Fin ω.length → ℕ) → QuantumGroup R 𝕧 :=
  CoxeterSystem.pbwDivMonomial (fun i ↦ (Ta R i).symm) (Ed R) ω

/-- The divided monomials are nonzero multiples of the PBW monomials for `Tᵢ⁻¹`. -/
lemma pbwDivSymm_eq_smul (ω : List I) (c : Fin ω.length → ℕ) :
    CoxeterSystem.pbwDivMonomial (fun i ↦ (Ta R i).symm) (Ed R) ω c =
      (∏ t : Fin ω.length, (qFactorial (𝕧 ^ D.d ω[t]) (c t))⁻¹) •
      CoxeterSystem.pbwMonomial (fun j ↦ (braidEquivOfNotRoot R ratFunc_X_not_root j).symm)
        (E R 𝕧) ω c := by
  induction ω with
  | nil => simp [CoxeterSystem.pbwDivMonomial, CoxeterSystem.pbwMonomial]
  | cons i ω ih =>
    rw [CoxeterSystem.pbwDivMonomial_cons, CoxeterSystem.pbwMonomial_cons, ih]
    change _ = (∏ t : Fin (ω.length + 1), (qFactorial (𝕧 ^ D.d (i :: ω)[t]) (c t))⁻¹) • _
    rw [Fin.prod_univ_succ]
    rw [Ta_symm_apply, map_smul, Ed, qDivPow, smul_mul_smul_comm]
    rfl

/-- **The integral PBW monomials for `e = -1` are `𝒜`-linearly independent** along a reduced
word, for every Cartan datum. -/
theorem linearIndependent_pbwDivSymm
    {W : Type*} [Group W] {cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W} {ω : List I}
    (hω : cs.IsReduced ω) : LinearIndependent 𝒜 (pbwDivSymm R ω) := by
  classical
  have hli := linearIndependent_pbwMonomial_symm_of_isReduced (R := R) ratFunc_X_not_root hω
  rw [linearIndependent_iff'] at hli ⊢
  intro s g hg c hc
  have hs : ∀ c : Fin ω.length → ℕ,
      (∏ t : Fin ω.length, (qFactorial (𝕧 ^ D.d ω[t]) (c t))⁻¹) ≠ 0 := fun c ↦
    prod_ne_zero_iff.2 fun t _ ↦ inv_ne_zero (qFactorial_vd_ne_zero _ _)
  have h := hli s (fun c : Fin ω.length → ℕ ↦ LusztigF.integralLaurentEval (g c) *
    ∏ t : Fin ω.length, (qFactorial (𝕧 ^ D.d ω[t]) (c t))⁻¹) (by
      simpa [laurent_smul_U, pbwDivSymm_eq_smul, smul_smul] using hg) c hc
  exact LusztigF.integralLaurentEval_injective (by
    rw [map_zero]; exact (mul_eq_zero.1 h).resolve_right (hs c))

/-! ### Rank two -/

lemma qSerre_two_inv (q : 𝕂) (a b : QuantumGroup R 𝕧) :
    qSerre q⁻¹ 2 a b = qSerre q 2 a b := by
  rw [qSerre_two, qSerre_two, inv_inv, add_comm q⁻¹]

variable {i j : I} (hij : i ≠ j) (h : D.cartanMatrix i j = -1) (h' : D.cartanMatrix j i = -1)

include hij h h' in
/-- **The integral PBW monomials of `iji` for `e = -1` span the integral form of the rank-two
subalgebra** (type `A₂`; from [Lus] 42.1.2 (b)). -/
theorem span_pbwDivSymm_a2 :
    Submodule.span 𝒜 (Set.range (pbwDivSymm R [i, j, i])) =
      (adjoinPair (R := R) i j).toSubmodule := by
  classical
  set q : 𝕂 := 𝕧 ^ D.d i
  set p : 𝕂 := q⁻¹
  set α := E R 𝕧 i
  set β := E R 𝕧 j
  -- `γ = T'_{i,-1}(Eⱼ) = Eⱼ Eᵢ - q⁻¹ Eᵢ Eⱼ`, and `γp = Eᵢ Eⱼ - q Eⱼ Eᵢ = -q γ`
  set γ := β * α - q⁻¹ • (α * β)
  set γp := α * β - p⁻¹ • (β * α)
  have hq0 : q ≠ 0 := pow_ne_zero _ (NeZero.ne 𝕧)
  have hp0 : p ≠ 0 := inv_ne_zero hq0
  have hqroot := vd_pow_ne_one (D := D) ratFunc_X_not_root i
  have hqi : ∀ n : ℕ, 0 < n → qInt q n ≠ 0 := fun n hn ↦
    qInt_ne_zero_of_pow_ne_one hq0 hqroot hn
  have hpi : ∀ n : ℕ, 0 < n → qInt p n ≠ 0 := fun n hn ↦ by
    rw [A2Integral.qInt_inv']; exact hqi n hn
  have hqq : q - q⁻¹ ≠ 0 := sub_inv_ne_zero_of_pow_ne_one hq0 hqroot
  have hpp : p - p⁻¹ ≠ 0 := by
    rw [inv_inv, ← neg_sub]; exact neg_ne_zero.2 hqq
  have hdij : D.d j = D.d i := (D.d_eq_of_simply_laced_edge h h').symm
  have hγp : γp = (-q) • γ := by
    simp only [γp, γ, p, inv_inv, smul_sub, smul_smul, neg_mul, mul_inv_cancel₀ hq0, neg_smul,
      one_smul]
    abel
  have hβα : β * α = p • (α * β) - p • γp := by
    simp only [γp, p, inv_inv, smul_sub, smul_smul, inv_mul_cancel₀ hq0, one_smul]; abel
  have hS1 : qSerre p 2 α β = 0 := by
    have := serre_E R 𝕧 hij
    rwa [h, show (1 - -1 : ℤ).toNat = 2 from rfl, ← qSerre_two_inv] at this
  have hS2 : qSerre p 2 β α = 0 := by
    have := serre_E R 𝕧 hij.symm
    rwa [h', show (1 - -1 : ℤ).toNat = 2 from rfl, hdij, ← qSerre_two_inv] at this
  have hαγ : α * γp = p • (γp * α) := by
    have e : α * γp - p • (γp * α) = qSerre p 2 α β := by
      rw [qSerre_two]
      simp only [γp, mul_sub, sub_mul, mul_smul_comm, smul_mul_assoc, smul_sub, smul_smul,
        mul_inv_cancel₀ hp0, one_smul, sq, mul_assoc, add_smul]
      abel
    rw [← sub_eq_zero, e, hS1]
  have hβγ : p • (β * γp) = γp * β := by
    have e : p • (β * γp) - γp * β = -qSerre p 2 β α := by
      rw [qSerre_two]
      simp only [γp, mul_sub, sub_mul, mul_smul_comm, smul_mul_assoc, smul_sub, smul_smul,
        mul_inv_cancel₀ hp0, one_smul, sq, mul_assoc, add_smul]
      abel
    rw [← sub_eq_zero, e, hS2, neg_zero]
  set Λ : Subring 𝕂 := (LusztigF.integralLaurentEval).range
  have hqΛ : q ∈ Λ := RingHom.mem_range.2 (isLaurent_pow (D.d i))
  have hqΛ' : q⁻¹ ∈ Λ := by
    have := isLaurent_inv_pow (D.d i)
    rw [inv_pow] at this
    exact RingHom.mem_range.2 this
  have hpΛ : p ∈ Λ := hqΛ'
  have hpΛ' : p⁻¹ ∈ Λ := by simpa [p] using hqΛ
  have hmap : ∀ (f : QuantumGroup R 𝕧 ≃ₐ[𝕂] QuantumGroup R 𝕧) (t : 𝕂) (n : ℕ) (x),
      f (qDivPow t n x) = qDivPow t n (f x) := fun f t n x ↦ map_qDivPow' f.toAlgHom t n x
  -- the monomials
  have hT2 : (braidEquivOfNotRoot R ratFunc_X_not_root i).symm β = γ := by
    have e := a2_rootVector_two hij (braidEquivOfNotRoot_hasImages ratFunc_X_not_root R i)
    simp only [AlgEquiv.coe_toAlgHom] at e
    rw [braidEquivOfNotRoot_symm_apply, braidReversal_E, e,
      braidEj_eq_of_cartanMatrix_eq_neg_one h, map_sub, map_smul, braidReversal_mul,
      braidReversal_mul, braidReversal_E, braidReversal_E]
  have hT3 : (braidEquivOfNotRoot R ratFunc_X_not_root i).symm
      ((braidEquivOfNotRoot R ratFunc_X_not_root j).symm α) = β := by
    have e := list_braidEquivOfNotRoot_symm_apply (R := R) ratFunc_X_not_root [i, j] α
    simp only [List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one,
      AlgEquiv.mul_apply] at e
    have e3 := a2_rootVector_three (braidEquivOfNotRoot_hasImages ratFunc_X_not_root R i)
      (braidEquivOfNotRoot_hasImages ratFunc_X_not_root R j) hij h h' hqq
    simp only [AlgEquiv.coe_toAlgHom] at e3
    rw [e, braidReversal_E, e3, braidReversal_E]
  have hmono : ∀ c : Fin 3 → ℕ, pbwDivSymm R [i, j, i] c =
      qDivPow q (c 0) α * qDivPow q (c 1) γ * qDivPow q (c 2) β := fun c ↦ by
    have e1 : ∀ n, (braidEquivOfNotRoot R ratFunc_X_not_root i).symm (Ed R j n) =
        qDivPow q n γ := fun n ↦ by rw [Ed, hmap, hT2, hdij]
    have e2 : ∀ n, (braidEquivOfNotRoot R ratFunc_X_not_root i).symm
        ((braidEquivOfNotRoot R ratFunc_X_not_root j).symm (Ed R i n)) = qDivPow q n β :=
      fun n ↦ by rw [Ed, hmap, hmap, hT3]
    simp only [CoxeterSystem.pbwDivMonomial, Ta_symm_apply, _root_.map_mul, _root_.map_one,
      mul_one]
    rw [e1, e2, ← mul_assoc]
    rfl
  -- the monomials are unit multiples of those of the ordered span at `p = q⁻¹`
  have hmono' : ∀ a b d : ℕ, qDivPow p a α * qDivPow p b γp * qDivPow p d β =
      ((-q) ^ b) • (qDivPow q a α * qDivPow q b γ * qDivPow q d β) := fun a b d ↦ by
    rw [A2Integral.qDivPow_inv', A2Integral.qDivPow_inv', A2Integral.qDivPow_inv', hγp,
      qDivPow, qDivPow, smul_pow, smul_smul,
      mul_comm, ← smul_smul, ← qDivPow, mul_smul_comm, smul_mul_assoc]
    rfl
  have hmq : ∀ b : ℕ, (-q) ^ b ∈ Λ := fun b ↦ pow_mem (neg_mem hqΛ) b
  have hmq' : ∀ b : ℕ, ((-q) ^ b)⁻¹ ∈ Λ := fun b ↦ by
    rw [← inv_pow, inv_neg]; exact pow_mem (neg_mem hqΛ') b
  have hconv : ∀ x, x ∈ Submodule.span 𝒜 (Set.range (pbwDivSymm R [i, j, i])) ↔
      x ∈ A2Integral.orderedSpan Λ p α β γp := fun x ↦ by
    constructor
    · intro hx
      induction hx using Submodule.span_induction with
      | mem x hx =>
        obtain ⟨c, rfl⟩ := hx
        rw [hmono]
        have e := hmono' (c 0) (c 1) (c 2)
        rw [← inv_smul_eq_iff₀ (pow_ne_zero _ (neg_ne_zero.2 hq0))] at e
        rw [← e]
        exact A2Integral.smul_mem_orderedSpan (hmq' _)
          (A2Integral.monomial_mem_orderedSpan _ _ _)
      | zero => exact zero_mem _
      | add x y _ _ hx hy => exact add_mem hx hy
      | smul a x _ hx =>
        rw [laurent_smul_U]
        exact A2Integral.smul_mem_orderedSpan (RingHom.mem_range.2 ⟨a, rfl⟩) hx
    · intro hx
      induction hx using AddSubgroup.closure_induction with
      | mem x hx =>
        obtain ⟨c, hc, e, f, g, rfl⟩ := hx
        rw [hmono', smul_smul]
        obtain ⟨a, ha⟩ := RingHom.mem_range.1 (Subring.mul_mem _ hc (hmq f))
        rw [← ha, ← laurent_smul_U, show qDivPow q e α * qDivPow q f γ * qDivPow q g β =
          pbwDivSymm R [i, j, i] ![e, f, g] by rw [hmono]; rfl]
        exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨_, rfl⟩)
      | zero => exact zero_mem _
      | add x y _ _ hx hy => exact add_mem hx hy
      | neg x _ hx => exact neg_mem hx
  have hγd : ∀ n, qDivPow q n γ ∈ adjoinPair (R := R) i j := fun n ↦ by
    have e : qDivPow q n γ = ∑ r ∈ range (negA D i j * n + 1),
        ((-1 : 𝕂) ^ r * (𝕧 ^ D.d i)⁻¹ ^ r) •
          (qDivPow (𝕧 ^ D.d i) r (E R 𝕧 i) * qDivPow (𝕧 ^ D.d j) n (E R 𝕧 j) *
            qDivPow (𝕧 ^ D.d i) (negA D i j * n - r) (E R 𝕧 i)) := by
      rw [← braidEquivOfNotRoot_symm_qDivPow_E_ne ratFunc_X_not_root R hij.symm n, hmap, hT2,
        hdij]
    rw [e]
    refine Subalgebra.sum_mem _ fun r _ ↦ smul_mem_of_isLaurent
      ((isLaurent_neg_one.pow r).mul (isLaurent_inv_pow_pow _ _)) ?_
    refine mul_mem (mul_mem ?_ ?_) ?_
    · exact Algebra.subset_adjoin (Or.inl ⟨_, rfl⟩)
    · exact Algebra.subset_adjoin (Or.inr ⟨_, rfl⟩)
    · exact Algebra.subset_adjoin (Or.inl ⟨_, rfl⟩)
  refine le_antisymm (fun x hx ↦ ?_) (fun x hx ↦ ?_)
  · induction hx using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨c, rfl⟩ := hx
      rw [Subalgebra.mem_toSubmodule, hmono]
      refine mul_mem (mul_mem ?_ (hγd _)) ?_
      · exact Algebra.subset_adjoin (Or.inl ⟨_, rfl⟩)
      · exact Algebra.subset_adjoin (Or.inr ⟨c 2, by rw [Ed, hdij]⟩)
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | smul a x _ hx => exact Subalgebra.smul_mem _ hx a
  · have h1 : (1 : QuantumGroup R 𝕧) ∈ A2Integral.orderedSpan Λ p α β γp :=
      A2Integral.one_mem_orderedSpan
    have hmul : ∀ y ∈ A2Integral.orderedSpan Λ p α β γp,
        x * y ∈ A2Integral.orderedSpan Λ p α β γp := by
      induction hx using Algebra.adjoin_induction with
      | mem x hx =>
        rcases hx with ⟨n, rfl⟩ | ⟨n, rfl⟩
        · intro y hy
          rw [Ed, ← A2Integral.qDivPow_inv']
          exact A2Integral.qDivPow_α_mul_mem hpi hpΛ hpΛ' n hy
        · intro y hy
          rw [Ed, hdij, ← A2Integral.qDivPow_inv']
          exact A2Integral.qDivPow_β_mul_mem hp0 hpi hβα hαγ hβγ hpΛ hpΛ' hpp n hy
      | algebraMap a =>
        intro y hy
        rw [← Algebra.smul_def, laurent_smul_U]
        exact A2Integral.smul_mem_orderedSpan (RingHom.mem_range.2 ⟨a, rfl⟩) hy
      | add x z _ _ hx hz =>
        intro y hy; rw [add_mul]; exact add_mem (hx y hy) (hz y hy)
      | mul x z _ _ hx hz =>
        intro y hy; rw [mul_assoc]; exact hx _ (hz y hy)
    rw [hconv]
    simpa using hmul 1 h1

include hij h h' in
/-- The `A₂` braid move preserves the integral PBW span for `e = -1`. -/
theorem span_pbwDivSymm_a2_braid :
    Submodule.span 𝒜 (Set.range (pbwDivSymm R [i, j, i])) =
      Submodule.span 𝒜 (Set.range (pbwDivSymm R [j, i, j])) := by
  rw [span_pbwDivSymm_a2 hij h h', span_pbwDivSymm_a2 hij.symm h' h, adjoinPair, adjoinPair,
    Set.union_comm]

omit hij h h' in
/-- The commuting braid move preserves the integral PBW span for `e = -1`. -/
theorem span_pbwDivSymm_commuting (h0 : D.cartanMatrix i j = 0) :
    Submodule.span 𝒜 (Set.range (pbwDivSymm R [i, j])) =
      Submodule.span 𝒜 (Set.range (pbwDivSymm R [j, i])) := by
  have h0' := (D.isGeneralizedCartan_cartanMatrix.zero_comm i j).mp h0
  have hij : i ≠ j := by rintro rfl; rw [D.cartanMatrix_self] at h0; exact two_ne_zero h0
  have hmap : ∀ (f : QuantumGroup R 𝕧 ≃ₐ[𝕂] QuantumGroup R 𝕧) (t : 𝕂) (n : ℕ) (x),
      f (qDivPow t n x) = qDivPow t n (f x) := fun f t n x ↦ map_qDivPow' f.toAlgHom t n x
  have hE : ∀ {a b : I}, D.cartanMatrix a b = 0 → a ≠ b →
      (braidEquivOfNotRoot R ratFunc_X_not_root a).symm (E R 𝕧 b) = E R 𝕧 b := by
    intro a b hab hne
    have H := braidEquivOfNotRoot_hasImages ratFunc_X_not_root R a
    rw [AlgEquiv.symm_apply_eq]
    change _ = (braidEquivOfNotRoot R ratFunc_X_not_root a).toAlgHom (E R 𝕧 b)
    rw [H.map_E, ite_eq_right hne.symm, braidEj_eq_of_cartanMatrix_eq_zero hab]
  have hmono : ∀ {a b : I}, D.cartanMatrix a b = 0 → a ≠ b → ∀ c : Fin 2 → ℕ,
      pbwDivSymm R [a, b] c = Ed R a (c 0) * Ed R b (c 1) := fun hab hne c ↦ by
    simp only [CoxeterSystem.pbwDivMonomial, Ta_symm_apply, _root_.map_one, mul_one, Ed, hmap,
      hE hab hne]
    rfl
  have hc : ∀ m n, Ed R i m * Ed R j n = Ed R j n * Ed R i m := fun m n ↦ by
    simp only [Ed, qDivPow, smul_mul_smul_comm]
    rw [((Commute.pow_pow (E_commute_E_of_cartanMatrix_eq_zero (R := R) (v := 𝕧) h0) m n)).eq,
      mul_comm (_ : 𝕂)]
  congr 1
  ext x
  constructor
  · rintro ⟨c, rfl⟩
    exact ⟨![c 1, c 0], by rw [hmono h0' hij.symm, hmono h0 hij, hc]; rfl⟩
  · rintro ⟨c, rfl⟩
    exact ⟨![c 1, c 0], by rw [hmono h0' hij.symm, hmono h0 hij, hc]; rfl⟩

/-! ### Independence of the reduced expression ([Lus] 41.1.4 (a), `e = -1`) -/

lemma list_Ta_symm_apply (u : List I) (x : QuantumGroup R 𝕧) :
    (u.map fun i ↦ (Ta R i).symm).prod x =
      (u.map fun i ↦ (braidEquivOfNotRoot R ratFunc_X_not_root i).symm).prod x := by
  induction u generalizing x with
  | nil => rfl
  | cons i u ih =>
    simp only [List.map_cons, List.prod_cons, AlgEquiv.mul_apply, ih, Ta_symm_apply]

lemma list_symm_prod_eq_symm (u : List I) :
    (u.map fun i ↦ (braidEquivOfNotRoot R ratFunc_X_not_root i).symm).prod =
      ((u.reverse.map (braidEquivOfNotRoot R ratFunc_X_not_root)).prod).symm := by
  induction u with
  | nil => rfl
  | cons i u ih =>
    rw [List.map_cons, List.prod_cons, ih, List.reverse_cons, List.map_append, List.prod_append,
      List.map_singleton, List.prod_singleton]
    rfl

variable (hSL : D.cartanMatrix.IsSimplyLaced)

include hSL in
/-- A braid move preserves the integral PBW span for `e = -1` (simply-laced type). -/
theorem span_pbwDivSymm_of_braidMove {u w : List I}
    (hm : D.cartanMatrix.coxeterMatrix.BraidMove u w) :
    Submodule.span 𝒜 (Set.range (pbwDivSymm R u)) =
      Submodule.span 𝒜 (Set.range (pbwDivSymm R w)) := by
  obtain ⟨p, s, i, j, hij, hmij, rfl, rfl⟩ := hm
  have hT0 := isBraidLiftable_braidEquivOfNotRoot R ratFunc_X_not_root i j hij hmij
  have key : ∀ u w : List I,
      (u.reverse.map (braidEquivOfNotRoot R ratFunc_X_not_root)).prod =
        (w.reverse.map (braidEquivOfNotRoot R ratFunc_X_not_root)).prod →
      (u.map fun i ↦ (Ta R i).symm).prod = (w.map fun i ↦ (Ta R i).symm).prod := by
    intro u w huw
    ext x
    rw [list_Ta_symm_apply, list_Ta_symm_apply, list_symm_prod_eq_symm, list_symm_prod_eq_symm,
      huw]
  rcases hSL hij with h0 | h1
  · have h0' := (D.isGeneralizedCartan_cartanMatrix.zero_comm i j).mp h0
    have hm : D.cartanMatrix.coxeterMatrix i j = 2 := by
      rw [Matrix.coxeterMatrix_apply_of_ne _ hij, h0, h0']
      rfl
    have hm' : D.cartanMatrix.coxeterMatrix j i = 2 := by
      rw [Matrix.coxeterMatrix_apply_of_ne _ hij.symm, h0, h0']
      rfl
    have hw : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix i j = [i, j] := by
      simp only [CoxeterSystem.braidWord]
      rw [hm]
      rfl
    have hw' : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix j i = [j, i] := by
      simp only [CoxeterSystem.braidWord]
      rw [hm']
      rfl
    rw [hw, hw'] at hT0 ⊢
    exact CoxeterSystem.span_pbwDivMonomial_context _ (Ed R) (span_pbwDivSymm_commuting h0)
      (key [i, j] [j, i] (by simpa using hT0.symm)) p s
  · have h1' : D.cartanMatrix j i = -1 := by
      rcases hSL hij.symm with hz | hn
      · have := (D.isGeneralizedCartan_cartanMatrix.zero_comm j i).mp hz
        omega
      · exact hn
    have hm : D.cartanMatrix.coxeterMatrix i j = 3 := by
      rw [Matrix.coxeterMatrix_apply_of_ne _ hij, h1, h1']
      rfl
    have hm' : D.cartanMatrix.coxeterMatrix j i = 3 := by
      rw [Matrix.coxeterMatrix_apply_of_ne _ hij.symm, h1, h1']
      rfl
    have hw : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix i j = [j, i, j] := by
      simp only [CoxeterSystem.braidWord]
      rw [hm]
      rfl
    have hw' : CoxeterSystem.braidWord D.cartanMatrix.coxeterMatrix j i = [i, j, i] := by
      simp only [CoxeterSystem.braidWord]
      rw [hm']
      rfl
    rw [hw, hw'] at hT0 ⊢
    exact CoxeterSystem.span_pbwDivMonomial_context _ (Ed R)
      (span_pbwDivSymm_a2_braid hij h1 h1').symm (key [j, i, j] [i, j, i] (by simpa using hT0)) p s

include hSL in
/-- **[Lus] 41.1.4 (a)** (`e = -1`, simply-laced type): reduced expressions of the same element
`w` give the same `𝒜`-span `𝒜U⁺(w, -1)` of the integral PBW monomials
`E_{i₁}^{(c₁)} T'_{i₁,-1}(E_{i₂}^{(c₂)}) ⋯`. -/
theorem span_pbwDivSymm_of_isReduced {W : Type*} [Group W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {u w : List I}
    (hu : cs.IsReduced u) (hw : cs.IsReduced w) (huw : cs.wordProd u = cs.wordProd w) :
    Submodule.span 𝒜 (Set.range (pbwDivSymm R u)) =
      Submodule.span 𝒜 (Set.range (pbwDivSymm R w)) :=
  CoxeterSystem.eq_of_reflTransGen_braidMove
    (fun _ _ _ hm ↦ span_pbwDivSymm_of_braidMove hSL hm)
    hu (CoxeterSystem.reflTransGen_braidMove_of_isReduced hu hw huw)

include hSL in
/-- **[Lus] 41.1.4 (c)** (`e = -1`, simply-laced type): if `ℓ(sᵢ w) < ℓ(w)` then
`Eᵢ^{(t)} 𝒜U⁺(w, -1) ⊆ 𝒜U⁺(w, -1)`. -/
theorem qDivPow_E_mul_mem_span_pbwDivSymm {W : Type*} [Group W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : List I} (hw : cs.IsReduced w)
    {i : I} (hi : cs.IsLeftDescent (cs.wordProd w) i) (t : ℕ) {x : QuantumGroup R 𝕧}
    (hx : x ∈ Submodule.span 𝒜 (Set.range (pbwDivSymm R w))) :
    qDivPow (𝕧 ^ D.d i) t (E R 𝕧 i) * x ∈ Submodule.span 𝒜 (Set.range (pbwDivSymm R w)) := by
  obtain ⟨u, hu, hu₀⟩ := exists_reduced_cons_of_isLeftDescent cs hi
  have hs := span_pbwDivSymm_of_isReduced (R := R) hSL cs hu hw hu₀
  rw [← hs] at hx ⊢
  exact CoxeterSystem.mul_mem_pbwDivSpan_cons _ (Ed R) i u (Ed_mul_mem_span i t) hx

/-! ### Finite type ([Lus] 41.1.7, `e = -1`) -/

/-- The integral PBW monomials for `e = -1` lie in `𝒜U⁺` (from [Lus] 41.1.3 (b), `e = -1`), for
every Cartan datum. -/
lemma pbwDivSymm_mem_aPlus {W : Type*} [Group W]
    {cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W} :
    ∀ (w p : List I), cs.IsReduced (p ++ w) → ∀ c : Fin w.length → ℕ,
      (p.map fun i ↦ (braidEquivOfNotRoot R ratFunc_X_not_root i).symm).prod
        (pbwDivSymm R w c) ∈ aPlus R
  | [], p, _, c => by
    simpa [CoxeterSystem.pbwDivMonomial] using ePow_mem_aPlus (R := R) []
  | i :: w, p, hpw, c => by
    rw [pbwDivSymm, CoxeterSystem.pbwDivMonomial_cons, _root_.map_mul, Ta_symm_apply,
      ← AlgEquiv.mul_apply, ← List.prod_concat]
    rw [show (p.map fun i ↦ (braidEquivOfNotRoot R ratFunc_X_not_root i).symm).concat
        (braidEquivOfNotRoot R ratFunc_X_not_root i).symm =
        (p.concat i).map fun i ↦ (braidEquivOfNotRoot R ratFunc_X_not_root i).symm by
      simp]
    refine mul_mem_aPlus ?_ (pbwDivSymm_mem_aPlus w (p.concat i) (by simpa using hpw) _)
    have hred : cs.IsReduced (p ++ [i]) := by
      have := hpw.take (p.length + 1)
      rwa [show (p ++ i :: w).take (p.length + 1) = p ++ [i] by
        rw [List.take_length_add_append]
        rfl] at this
    exact list_braid_symm_qDivPow_E_mem_aPlus hred _

include hSL in
/-- **[Lus] 41.1.7** (`e = -1`, simply-laced finite type): for a reduced expression of the
longest element `w₀`, `𝒜U⁺(w₀, -1)` is the `𝒜`-subalgebra generated by the `Eᵢ^{(n)}`. -/
theorem span_pbwDivSymm_longest_eq {W : Type*} [Group W] [Finite W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : List I} (hw : cs.IsReduced w)
    (hw₀ : cs.wordProd w = cs.longestElement) :
    Submodule.span 𝒜 (Set.range (pbwDivSymm R w)) =
      (Algebra.adjoin 𝒜 (⋃ i, Set.range (Ed R i))).toSubmodule := by
  let S := Submodule.span 𝒜 (Set.range (pbwDivSymm R w))
  have hplus : ∀ c, pbwDivSymm R w c ∈ Algebra.adjoin 𝒜 (⋃ i, Set.range (Ed R i)) := fun c ↦ by
    have hc := pbwDivSymm_mem_aPlus (R := R) w [] (by simpa using hw) c
    simp only [List.map_nil, List.prod_nil, AlgEquiv.one_apply] at hc
    generalize pbwDivSymm R w c = y at hc ⊢
    induction hc using AddSubgroup.closure_induction with
    | mem x hx =>
      obtain ⟨c, w', hc, rfl⟩ := hx
      refine smul_mem_of_isLaurent hc ?_
      induction w' with
      | nil => exact one_mem _
      | cons p w' ih =>
        rw [ePow_cons]
        exact mul_mem (Algebra.subset_adjoin (Set.mem_iUnion.2 ⟨p.1, p.2, rfl⟩)) ih
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | neg x _ hx => exact neg_mem hx
  refine le_antisymm (Submodule.span_le.2 ?_) ?_
  · rintro _ ⟨c, rfl⟩; exact hplus c
  · intro x hx
    have h1 : (1 : QuantumGroup R 𝕧) ∈ S :=
      CoxeterSystem.one_mem_pbwDivSpan _ (Ed R) Ed_zero w
    have hmul : ∀ y ∈ S, x * y ∈ S := by
      induction hx using Algebra.adjoin_induction with
      | mem x hx =>
        obtain ⟨i, n, rfl⟩ := Set.mem_iUnion.1 hx
        exact fun y hy ↦ qDivPow_E_mul_mem_span_pbwDivSymm hSL cs hw
          (hw₀ ▸ cs.isLeftDescent_longestElement i) n hy
      | algebraMap a =>
        intro y hy
        rw [← Algebra.smul_def]
        exact S.smul_mem a hy
      | add x z _ _ hx hz =>
        intro y hy; rw [add_mul]; exact add_mem (hx y hy) (hz y hy)
      | mul x z _ _ hx hz =>
        intro y hy; rw [mul_assoc]; exact hx _ (hz y hy)
    simpa using hmul 1 h1

include hSL in
/-- **[Lus] 41.1.7** (`e = -1`), second form: `𝒜U⁺(w₀, -1) = 𝒜U⁺ = aPlus R`. With
`linearIndependent_pbwDivSymm`, the elements `E_h^c` of [Lus] 42.1.4 form an `𝒜`-basis of `𝒜U⁺`. -/
theorem coe_span_pbwDivSymm_longest {W : Type*} [Group W] [Finite W]
    (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W) {w : List I} (hw : cs.IsReduced w)
    (hw₀ : cs.wordProd w = cs.longestElement) :
    (Submodule.span 𝒜 (Set.range (pbwDivSymm R w)) : Set (QuantumGroup R 𝕧)) = aPlus R := by
  refine subset_antisymm (fun x hx ↦ ?_) (fun x hx ↦ ?_)
  · induction hx using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨c, rfl⟩ := hx
      simpa using pbwDivSymm_mem_aPlus (R := R) w [] (by simpa using hw) c
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | smul a x _ hx => rw [laurent_smul_U]; exact smul_mem_aPlus ⟨a, rfl⟩ hx
  · rw [SetLike.mem_coe, span_pbwDivSymm_longest_eq hSL cs hw hw₀]
    induction hx using AddSubgroup.closure_induction with
    | mem x hx =>
      obtain ⟨c, w', hc, rfl⟩ := hx
      refine smul_mem_of_isLaurent hc ?_
      induction w' with
      | nil => exact one_mem _
      | cons p w' ih =>
        rw [ePow_cons]
        exact mul_mem (Algebra.subset_adjoin (Set.mem_iUnion.2 ⟨p.1, p.2, rfl⟩)) ih
    | zero => exact zero_mem _
    | add x y _ _ hx hy => exact add_mem hx hy
    | neg x _ hx => exact neg_mem hx

end Modified

end LieLean.QuantumGroup
