/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.Modified.IntegralForm
import LieLean.Algebra.QuantumGroup.Modified.Commutation

/-!
# The triangular description of `𝒜U̇`

Over `ℚ(v)`, with `𝒜 = ℤ[v, v⁻¹]`, Lusztig defines `𝒜U̇` as the `𝒜`-span of the elements
`x⁺ 1_λ x'⁻` (`x, x' ∈ 𝒜f`) and proves that it equals the `𝒜`-span of the `x⁻ 1_λ x'⁺` and the
`𝒜`-subalgebra generated by the `Eᵢ^{(n)} 1_λ`, `Fᵢ^{(n)} 1_λ` ([Lus] 23.2.2 (a), (c)). The library
defines `𝒜U̇` as this subalgebra (`Modified.aForm`). Here we prove both span descriptions.
Since `𝒜f` is the `𝒜`-span of the monomials `θ_{i₁}^{(n₁)} ⋯ θ_{iₖ}^{(nₖ)}`, the elements
`x⁺ 1_λ x'⁻` with `x, x' ∈ 𝒜f` span the same `𝒜`-module as the elements `E_w 1_λ F_{w'}` with
`E_w`, `F_{w'}` monomials in divided powers (`Modified.ePow`, `Modified.fPow`).

## Main definitions and results

* `Modified.ePow w`, `Modified.fPow w`: the monomials `E_{i₁}^{(n₁)} ⋯ E_{iₖ}^{(nₖ)}` and
  `F_{i₁}^{(n₁)} ⋯ F_{iₖ}^{(nₖ)}` in `U`, `w = [(i₁, n₁), …, (iₖ, nₖ)]`.
* `Modified.aFormFE`, `Modified.aFormEF`: the `𝒜`-spans of the `F_w E_{w'} 1_λ` and of the
  `E_w F_{w'} 1_λ`.
* `Modified.aForm_eq_aFormFE`, `Modified.aForm_eq_aFormEF`: **[Lus] 23.2.2 (a), (c)**.
* `Modified.isLaurent_qBinomZ`: `[m; t]ᵢ ∈ 𝒜` ([Lus] 1.3.1 (d)).

## References

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, 1.3.1, 23.1.3, 23.2.2.
-/

open LieLean Finset

noncomputable section

namespace LieLean.QuantumGroup

local notation "𝕂" => RatFunc ℚ
local notation "𝕧" => (RatFunc.X : RatFunc ℚ)
local notation "𝒜" => LaurentPolynomial ℤ

attribute [local instance] neZero_ratFunc_X

variable {I Y : Type*} [AddCommGroup Y] [DecidableEq I] {D : LusztigCartanDatum I}
  {R : D.RootDatum Y}

namespace Modified

/-! ### Laurent scalars -/

lemma isLaurent_zero : IsLaurent 0 := ⟨0, _root_.map_zero _⟩

lemma isLaurent_one : IsLaurent 1 := ⟨1, _root_.map_one _⟩

lemma IsLaurent.add {c c' : 𝕂} (h : IsLaurent c) (h' : IsLaurent c') : IsLaurent (c + c') := by
  obtain ⟨a, rfl⟩ := h; obtain ⟨a', rfl⟩ := h'; exact ⟨a + a', map_add _ _ _⟩

lemma IsLaurent.neg {c : 𝕂} (h : IsLaurent c) : IsLaurent (-c) := by
  obtain ⟨a, rfl⟩ := h; exact ⟨-a, map_neg _ _⟩

lemma IsLaurent.sub {c c' : 𝕂} (h : IsLaurent c) (h' : IsLaurent c') : IsLaurent (c - c') := by
  rw [sub_eq_add_neg]; exact h.add h'.neg

lemma isLaurent_vd_zpow (d : ℕ) (m : ℤ) : IsLaurent ((𝕧 ^ d) ^ m) := by
  rw [← zpow_natCast, ← zpow_mul]; exact isLaurent_zpow _

/-- Pascal's rule `[m+1; t+1] = q^{-(t+1)} [m; t+1] + q^{m-t} [m; t]` ([Lus] 1.3.1). -/
lemma qBinomZ_succ_succ_eq {q : 𝕂} (hq0 : q ≠ 0) (m : ℤ) (t : ℕ)
    (ht : qIntZ q ((t : ℤ) + 1) ≠ 0) :
    qBinomZ q (m + 1) (t + 1) = q ^ (-((t : ℤ) + 1)) * qBinomZ q m (t + 1) +
      q ^ (m - t) * qBinomZ q m t := by
  rw [qBinomZ_succ_succ, qBinomZ_succ]
  have key : qIntZ q (m + 1) = q ^ (-((t : ℤ) + 1)) * qIntZ q (m - t) +
      q ^ (m - t) * qIntZ q ((t : ℤ) + 1) := by
    by_cases hq : q - q⁻¹ = 0
    · simp [qIntZ, hq]
    simp only [qIntZ, sub_eq_add_neg, neg_add, neg_neg, zpow_add₀ hq0, zpow_neg, zpow_one]
    field_simp
    ring
  rw [key]
  field_simp

lemma qBinomZ_zero_succ (q : 𝕂) (t : ℕ) : qBinomZ q 0 (t + 1) = 0 := by
  induction t with
  | zero => simp [qBinomZ_succ]
  | succ t ih => rw [qBinomZ_succ, ih, zero_mul, zero_div]

/-- The Gaussian binomials `[m; t]ᵢ` (`m ∈ ℤ`) lie in `𝒜` ([Lus] 1.3.1 (d)). -/
theorem isLaurent_qBinomZ (d : ℕ) (hd : 0 < d) (m : ℤ) (t : ℕ) :
    IsLaurent (qBinomZ (𝕧 ^ d) m t) := by
  have hq0 : (𝕧 ^ d : 𝕂) ≠ 0 := pow_ne_zero _ RatFunc.X_ne_zero
  have hq : ∀ n : ℕ, 0 < n → (𝕧 ^ d) ^ n ≠ 1 := fun n hn ↦ by
    rw [← pow_mul]; exact ratFunc_X_not_root _ (Nat.mul_pos hd hn)
  induction t generalizing m with
  | zero => exact isLaurent_one
  | succ t ih =>
    have ht : qIntZ (𝕧 ^ d) ((t : ℤ) + 1) ≠ 0 := qIntZ_ne_zero hq0 hq (by omega)
    have hrec := fun m ↦ qBinomZ_succ_succ_eq hq0 m t ht
    induction m using Int.induction_on with
    | zero => rw [qBinomZ_zero_succ]; exact isLaurent_zero
    | succ m hm =>
      rw [hrec]
      exact ((isLaurent_vd_zpow d _).mul hm).add ((isLaurent_vd_zpow d _).mul (ih m))
    | pred m hm =>
      have e := hrec (-(m : ℤ) - 1)
      rw [sub_add_cancel] at e
      have : qBinomZ (𝕧 ^ d) (-(m : ℤ) - 1) (t + 1) = (𝕧 ^ d) ^ ((t : ℤ) + 1) *
          (qBinomZ (𝕧 ^ d) (-(m : ℤ)) (t + 1) -
            (𝕧 ^ d) ^ ((-(m : ℤ) - 1) - t) * qBinomZ (𝕧 ^ d) (-(m : ℤ) - 1) t) := by
        rw [e, add_sub_cancel_right, ← mul_assoc, ← zpow_add₀ hq0, add_neg_cancel, zpow_zero,
          one_mul]
      rw [this]
      exact (isLaurent_vd_zpow d _).mul (hm.sub ((isLaurent_vd_zpow d _).mul (ih _)))

/-! ### Monomials in divided powers -/

variable (R) in
/-- `E_w = E_{i₁}^{(n₁)} ⋯ E_{iₖ}^{(nₖ)}` for `w = [(i₁, n₁), …, (iₖ, nₖ)]`. -/
def ePow (w : List (I × ℕ)) : QuantumGroup R 𝕧 :=
  (w.map fun p ↦ qDivPow (𝕧 ^ D.d p.1) p.2 (E R 𝕧 p.1)).prod

variable (R) in
/-- `F_w = F_{i₁}^{(n₁)} ⋯ F_{iₖ}^{(nₖ)}` for `w = [(i₁, n₁), …, (iₖ, nₖ)]`. -/
def fPow (w : List (I × ℕ)) : QuantumGroup R 𝕧 :=
  (w.map fun p ↦ qDivPow (𝕧 ^ D.d p.1) p.2 (F R 𝕧 p.1)).prod

variable (R) in
/-- The weight `Σ nₖ iₖ'` of `w` (an element of `X`). -/
def wtW (w : List (I × ℕ)) : Y →+ ℤ := (w.map fun p ↦ p.2 • R.root p.1).sum

@[simp] lemma ePow_nil : ePow R ([] : List (I × ℕ)) = 1 := rfl
@[simp] lemma fPow_nil : fPow R ([] : List (I × ℕ)) = 1 := rfl
omit [DecidableEq I] in
@[simp] lemma wtW_nil : wtW R ([] : List (I × ℕ)) = 0 := rfl

lemma ePow_cons (p : I × ℕ) (w : List (I × ℕ)) :
    ePow R (p :: w) = qDivPow (𝕧 ^ D.d p.1) p.2 (E R 𝕧 p.1) * ePow R w := by
  simp [ePow]

lemma fPow_cons (p : I × ℕ) (w : List (I × ℕ)) :
    fPow R (p :: w) = qDivPow (𝕧 ^ D.d p.1) p.2 (F R 𝕧 p.1) * fPow R w := by
  simp [fPow]

omit [DecidableEq I] in
lemma wtW_cons (p : I × ℕ) (w : List (I × ℕ)) :
    wtW R (p :: w) = p.2 • R.root p.1 + wtW R w := by
  simp [wtW]

lemma ePow_mem (w : List (I × ℕ)) : ePow R w ∈ adWeightSpace R 𝕧 (wtW R w) := by
  induction w with
  | nil => simpa using one_mem_adWeightSpace
  | cons p w ih =>
    rw [ePow_cons, wtW_cons]
    exact mul_mem_adWeightSpace (qDivPow_E_mem _ p.1 p.2) ih

lemma fPow_mem (w : List (I × ℕ)) : fPow R w ∈ adWeightSpace R 𝕧 (-wtW R w) := by
  induction w with
  | nil => simpa using one_mem_adWeightSpace
  | cons p w ih =>
    rw [fPow_cons, wtW_cons, neg_add, ← smul_neg]
    exact mul_mem_adWeightSpace (qDivPow_F_mem _ p.1 p.2) ih

lemma fPow_mul_ePow_mem (w w' : List (I × ℕ)) :
    fPow R w * ePow R w' ∈ adWeightSpace R 𝕧 (wtW R w' - wtW R w) := by
  rw [sub_eq_neg_add]; exact mul_mem_adWeightSpace (fPow_mem w) (ePow_mem w')

lemma ePow_mul_fPow_mem (w w' : List (I × ℕ)) :
    ePow R w * fPow R w' ∈ adWeightSpace R 𝕧 (wtW R w - wtW R w') := by
  rw [sub_eq_add_neg]; exact mul_mem_adWeightSpace (ePow_mem w) (fPow_mem w')

lemma isGen_ePow (w : List (I × ℕ)) : IsGen R (ePow R w) (wtW R w) := by
  induction w with
  | nil => simpa using isGen_one
  | cons p w ih => rw [ePow_cons, wtW_cons]; exact (isGen_E p.1 p.2).mul ih

lemma isGen_fPow (w : List (I × ℕ)) : IsGen R (fPow R w) (-wtW R w) := by
  induction w with
  | nil => simpa using isGen_one
  | cons p w ih =>
    rw [fPow_cons, wtW_cons, neg_add, ← smul_neg]; exact (isGen_F p.1 p.2).mul ih

/-! ### The two spans -/

variable (R) in
/-- The `𝒜`-span of the elements `F_w E_{w'} 1_λ` of `U̇` ([Lus] 23.2.2). -/
def aFormFE : Submodule 𝒜 (Modified R 𝕧) :=
  Submodule.span 𝒜 {x | ∃ (w w' : List (I × ℕ)) (L l : Y →+ ℤ)
    (h : fPow R w * ePow R w' ∈ adWeightSpace R 𝕧 (L - l)), x = elt L l _ h}

variable (R) in
/-- The `𝒜`-span of the elements `E_w F_{w'} 1_λ` of `U̇` ([Lus] 23.2.2). -/
def aFormEF : Submodule 𝒜 (Modified R 𝕧) :=
  Submodule.span 𝒜 {x | ∃ (w w' : List (I × ℕ)) (L l : Y →+ ℤ)
    (h : ePow R w * fPow R w' ∈ adWeightSpace R 𝕧 (L - l)), x = elt L l _ h}

lemma elt_fPow_ePow_mem {w w' : List (I × ℕ)} {L l : Y →+ ℤ}
    (h : fPow R w * ePow R w' ∈ adWeightSpace R 𝕧 (L - l)) : elt L l _ h ∈ aFormFE R :=
  Submodule.subset_span ⟨w, w', L, l, h, rfl⟩

lemma elt_ePow_fPow_mem {w w' : List (I × ℕ)} {L l : Y →+ ℤ}
    (h : ePow R w * fPow R w' ∈ adWeightSpace R 𝕧 (L - l)) : elt L l _ h ∈ aFormEF R :=
  Submodule.subset_span ⟨w, w', L, l, h, rfl⟩

/-! ### Reduction to normal form modulo `Σ_μ U (K_μ - v^{⟨μ,λ⟩})` -/

variable (R) in
/-- The `𝒜`-combinations of the `F_w E_{w'}` of weight `χ`. -/
def latFE (χ : Y →+ ℤ) : AddSubgroup (QuantumGroup R 𝕧) :=
  AddSubgroup.closure {x | ∃ (c : 𝕂) (w w' : List (I × ℕ)), IsLaurent c ∧
    wtW R w' - wtW R w = χ ∧ x = c • (fPow R w * ePow R w')}

lemma latFE_le (χ : Y →+ ℤ) : (latFE R χ : Set (QuantumGroup R 𝕧)) ⊆ adWeightSpace R 𝕧 χ := by
  intro x hx
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨c, w, w', -, rfl, rfl⟩ := hx
    exact Submodule.smul_mem _ _ (fPow_mul_ePow_mem w w')
  | zero => exact zero_mem _
  | add x y _ _ hx hy => exact add_mem hx hy
  | neg x _ hx => exact neg_mem hx

lemma smul_mem_latFE {χ : Y →+ ℤ} {c : 𝕂} (hc : IsLaurent c) {x : QuantumGroup R 𝕧}
    (hx : x ∈ latFE R χ) : c • x ∈ latFE R χ := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨c', w, w', hc', hw, rfl⟩ := hx
    exact AddSubgroup.subset_closure ⟨c * c', w, w', hc.mul hc', hw, by rw [smul_smul]⟩
  | zero => rw [smul_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [smul_add]; exact add_mem hx hy
  | neg x _ hx => rw [smul_neg]; exact neg_mem hx

lemma F_mul_mem_latFE {χ : Y →+ ℤ} (i : I) (n : ℕ) {x : QuantumGroup R 𝕧}
    (hx : x ∈ latFE R χ) : qDivPow (𝕧 ^ D.d i) n (F R 𝕧 i) * x ∈ latFE R (χ + n • -R.root i) := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨c, w, w', hc, rfl, rfl⟩ := hx
    refine AddSubgroup.subset_closure ⟨c, (i, n) :: w, w', hc, ?_, ?_⟩
    · rw [wtW_cons, smul_neg]; abel
    · rw [fPow_cons, mul_smul_comm, mul_assoc]
  | zero => rw [mul_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [mul_add]; exact add_mem hx hy
  | neg x _ hx => rw [mul_neg]; exact neg_mem hx

variable (R) in
/-- `u` is congruent modulo `Σ_μ U (K_μ - v^{⟨μ,λ⟩})`, for every `λ`, to an `𝒜`-combination of the
`F_w E_{w'}` of weight `χ`. -/
def Good (u : QuantumGroup R 𝕧) (χ : Y →+ ℤ) : Prop :=
  ∀ l, ∃ s ∈ latFE R χ, u - s ∈ rightRel R 𝕧 l

lemma Good.of_mem {u : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (hu : u ∈ latFE R χ) : Good R u χ :=
  fun _ ↦ ⟨u, hu, by rw [sub_self]; exact zero_mem _⟩

lemma Good.add {u u' : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (hu : Good R u χ) (hu' : Good R u' χ) :
    Good R (u + u') χ := fun l ↦ by
  obtain ⟨s, hs, h⟩ := hu l
  obtain ⟨s', hs', h'⟩ := hu' l
  exact ⟨s + s', add_mem hs hs', by rw [add_sub_add_comm]; exact add_mem h h'⟩

lemma Good.smul {u : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (hu : Good R u χ) {c : 𝕂}
    (hc : IsLaurent c) : Good R (c • u) χ := fun l ↦ by
  obtain ⟨s, hs, h⟩ := hu l
  exact ⟨c • s, smul_mem_latFE hc hs, by rw [← smul_sub]; exact Submodule.smul_mem _ _ h⟩

lemma good_zero (χ : Y →+ ℤ) : Good R 0 χ := Good.of_mem (zero_mem _)

lemma Good.sum {ι : Type*} (s : Finset ι) {u : ι → QuantumGroup R 𝕧} {χ : Y →+ ℤ}
    (hu : ∀ t ∈ s, Good R (u t) χ) : Good R (∑ t ∈ s, u t) χ := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using good_zero χ
  | insert a s ha ih =>
    rw [sum_insert ha]
    exact (hu a (mem_insert_self a s)).add (ih fun t ht ↦ hu t (mem_insert_of_mem ht))

lemma Good.congr {u : QuantumGroup R 𝕧} {χ χ' : Y →+ ℤ} (hu : Good R u χ) (e : χ = χ') :
    Good R u χ' := e ▸ hu

lemma Good.F_mul {u : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (hu : Good R u χ) (i : I) (n : ℕ) :
    Good R (qDivPow (𝕧 ^ D.d i) n (F R 𝕧 i) * u) (χ + n • -R.root i) := fun l ↦ by
  obtain ⟨s, hs, h⟩ := hu l
  exact ⟨_, F_mul_mem_latFE i n hs, by rw [← mul_sub]; exact mul_mem_rightRel _ h⟩

/-- `a ∈ Σ_μ U(K_μ - v^{⟨μ,λ+ψ⟩})` and `x ∈ U_ψ` give `a x ∈ Σ_μ U(K_μ - v^{⟨μ,λ⟩})`. -/
lemma mul_mem_rightRel_of_mem {l ψ : Y →+ ℤ} {a x : QuantumGroup R 𝕧}
    (ha : a ∈ rightRel R 𝕧 (l + ψ)) (hx : x ∈ adWeightSpace R 𝕧 ψ) :
    a * x ∈ rightRel R 𝕧 l := by
  induction ha using Submodule.span_induction with
  | mem a ha =>
    obtain ⟨μ, w, rfl⟩ := ha
    have e : w * (K R 𝕧 μ - algebraMap 𝕂 _ (𝕧 ^ (l + ψ) μ)) * x =
        𝕧 ^ ψ μ • ((w * x) * (K R 𝕧 μ - algebraMap 𝕂 _ (𝕧 ^ l μ))) := by
      simp only [Algebra.algebraMap_eq_smul_one, mul_sub, sub_mul, mul_assoc, hx μ,
        mul_smul_comm, smul_mul_assoc, mul_one, smul_sub, smul_smul, AddMonoidHom.add_apply]
      rw [add_comm (l μ), zpow_add₀ (NeZero.ne 𝕧)]
    rw [e]
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨μ, w * x, rfl⟩)
  | zero => rw [zero_mul]; exact zero_mem _
  | add a b _ _ ha hb => rw [add_mul]; exact add_mem ha hb
  | smul c a _ ha => rw [smul_mul_assoc]; exact Submodule.smul_mem _ _ ha

omit [DecidableEq I] in
lemma nsmul_add_nsmul_neg (α : Y →+ ℤ) {N M' t : ℕ} (h1 : t ≤ N) (h2 : t ≤ M') :
    (N - t) • α + (M' - t) • -α = N • α + M' • -α := by
  ext μ
  simp only [AddMonoidHom.add_apply, AddMonoidHom.smul_apply, AddMonoidHom.neg_apply,
    nsmul_eq_mul, Nat.cast_sub h1, Nat.cast_sub h2]
  ring

lemma good_E_mul_fPow_mul_ePow (i : I) (w w' : List (I × ℕ)) (n : ℕ) :
    Good R (qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) * (fPow R w * ePow R w'))
      (wtW R w' - wtW R w + n • R.root i) := by
  induction w generalizing n with
  | nil =>
    refine Good.of_mem (AddSubgroup.subset_closure ⟨1, [], (i, n) :: w', isLaurent_one, ?_, ?_⟩)
    · rw [wtW_cons, wtW_nil]; abel
    · rw [one_smul, fPow_nil, ePow_cons, one_mul, one_mul]
  | cons p w ih =>
    obtain ⟨j, m⟩ := p
    set x := fPow R w * ePow R w'
    have hx : x ∈ adWeightSpace R 𝕧 (wtW R w' - wtW R w) := fPow_mul_ePow_mem w w'
    have e0 : qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) * (fPow R ((j, m) :: w) * ePow R w') =
        qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) * qDivPow (𝕧 ^ D.d j) m (F R 𝕧 j) * x := by
      simp only [x, fPow_cons, mul_assoc]
    have ew : wtW R w' - wtW R ((j, m) :: w) + n • R.root i =
        wtW R w' - wtW R w + n • R.root i + m • -R.root j := by
      rw [wtW_cons, smul_neg]; abel
    rw [e0, ew]
    by_cases hij : i = j
    · subst hij
      intro l
      set c : ℕ → 𝕂 := fun t ↦ qBinomZ (𝕧 ^ D.d i)
        ((l + (wtW R w' - wtW R w)) (R.coroot i) + n - m) t
      have hr := qDivPow_E_mul_qDivPow_F_sub_mem (R := R) ratFunc_X_not_root i n m
        (l + (wtW R w' - wtW R w))
      have hrx := mul_mem_rightRel_of_mem hr hx
      have hS : Good R ((∑ t ∈ range (n + 1), if t ≤ m then c t •
          (qDivPow (𝕧 ^ D.d i) (m - t) (F R 𝕧 i) * qDivPow (𝕧 ^ D.d i) (n - t) (E R 𝕧 i))
          else 0) * x) (wtW R w' - wtW R w + n • R.root i + m • -R.root i) := by
        rw [sum_mul]
        refine Good.sum _ fun t ht ↦ ?_
        have htn : t ≤ n := Nat.lt_succ_iff.1 (mem_range.1 ht)
        split_ifs with htm
        · rw [smul_mul_assoc, mul_assoc]
          refine Good.smul (Good.congr ((ih (n - t)).F_mul i (m - t)) ?_)
            (isLaurent_qBinomZ _ (D.d_pos i) _ _)
          rw [add_assoc, add_assoc, nsmul_add_nsmul_neg (R.root i) htn htm]
        · rw [zero_mul]; exact good_zero _
      obtain ⟨s, hs, h⟩ := hS l
      refine ⟨s, hs, ?_⟩
      rw [mul_assoc]
      have : qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) * (qDivPow (𝕧 ^ D.d i) m (F R 𝕧 i) * x) - s =
          (qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) * qDivPow (𝕧 ^ D.d i) m (F R 𝕧 i) -
            ∑ t ∈ range (n + 1), (if t ≤ m then c t • (qDivPow (𝕧 ^ D.d i) (m - t) (F R 𝕧 i) *
              qDivPow (𝕧 ^ D.d i) (n - t) (E R 𝕧 i)) else 0)) * x +
          ((∑ t ∈ range (n + 1), if t ≤ m then c t • (qDivPow (𝕧 ^ D.d i) (m - t) (F R 𝕧 i) *
              qDivPow (𝕧 ^ D.d i) (n - t) (E R 𝕧 i)) else 0) * x - s) := by
        noncomm_ring
      rw [this]
      exact add_mem hrx h
    · have hc : qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) * qDivPow (𝕧 ^ D.d j) m (F R 𝕧 j) =
          qDivPow (𝕧 ^ D.d j) m (F R 𝕧 j) * qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) := by
        simp only [qDivPow, smul_mul_smul_comm]
        rw [((Commute.pow_pow (E_mul_F_of_ne (R := R) (v := 𝕧) hij) n m)).eq, mul_comm (_ : 𝕂)]
      rw [hc, mul_assoc]
      exact (ih n).F_mul j m

lemma Good.E_mul {u : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (hu : Good R u χ) (i : I) (n : ℕ) :
    Good R (qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) * u) (χ + n • R.root i) := fun l ↦ by
  obtain ⟨s, hs, h⟩ := hu l
  have hEs : Good R (qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) * s) (χ + n • R.root i) := by
    clear h
    induction hs using AddSubgroup.closure_induction with
    | mem x hx =>
      obtain ⟨c, w, w', hc, rfl, rfl⟩ := hx
      rw [mul_smul_comm]
      exact (good_E_mul_fPow_mul_ePow i w w' n).smul hc
    | zero => rw [mul_zero]; exact good_zero _
    | add x y _ _ hx hy => rw [mul_add]; exact hx.add hy
    | neg x _ hx =>
      rw [mul_neg, ← neg_one_smul 𝕂]; exact hx.smul isLaurent_neg_one
  obtain ⟨s', hs', h'⟩ := hEs l
  refine ⟨s', hs', ?_⟩
  have : qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) * u - s' =
      qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) * (u - s) +
        (qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) * s - s') := by noncomm_ring
  rw [this]
  exact add_mem (mul_mem_rightRel _ h) h'

variable (R) in
/-- Products of divided powers `Eᵢ^{(n)}`, `Fᵢ^{(n)}` (in any order), with their weights. -/
inductive IsWord : QuantumGroup R 𝕧 → (Y →+ ℤ) → Prop
  | one : IsWord 1 0
  | E (i : I) (n : ℕ) {u : QuantumGroup R 𝕧} {χ : Y →+ ℤ} :
      IsWord u χ → IsWord (qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i) * u) (χ + n • R.root i)
  | F (i : I) (n : ℕ) {u : QuantumGroup R 𝕧} {χ : Y →+ ℤ} :
      IsWord u χ → IsWord (qDivPow (𝕧 ^ D.d i) n (F R 𝕧 i) * u) (χ + n • -R.root i)

lemma IsWord.good {u : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (hu : IsWord R u χ) : Good R u χ := by
  induction hu with
  | one => exact Good.of_mem (AddSubgroup.subset_closure ⟨1, [], [], isLaurent_one, by simp,
      by simp⟩)
  | E i n _ ih => exact ih.E_mul i n
  | F i n _ ih => exact ih.F_mul i n

lemma IsWord.mem {u : QuantumGroup R 𝕧} {χ : Y →+ ℤ} (hu : IsWord R u χ) :
    u ∈ adWeightSpace R 𝕧 χ := by
  induction hu with
  | one => exact one_mem_adWeightSpace
  | E i n _ ih => rw [add_comm]; exact mul_mem_adWeightSpace (qDivPow_E_mem _ i n) ih
  | F i n _ ih => rw [add_comm]; exact mul_mem_adWeightSpace (qDivPow_F_mem _ i n) ih

lemma IsWord.mul {u u' : QuantumGroup R 𝕧} {χ χ' : Y →+ ℤ} (hu : IsWord R u χ)
    (hu' : IsWord R u' χ') : IsWord R (u * u') (χ + χ') := by
  induction hu with
  | one => simpa using hu'
  | E i n _ ih => rw [mul_assoc, add_right_comm]; exact IsWord.E i n ih
  | F i n _ ih => rw [mul_assoc, add_right_comm]; exact IsWord.F i n ih

lemma isWord_ePow (w : List (I × ℕ)) : IsWord R (ePow R w) (wtW R w) := by
  induction w with
  | nil => exact IsWord.one
  | cons p w ih => rw [ePow_cons, wtW_cons, add_comm]; exact IsWord.E p.1 p.2 ih

lemma isWord_fPow (w : List (I × ℕ)) : IsWord R (fPow R w) (-wtW R w) := by
  induction w with
  | nil => simpa using IsWord.one
  | cons p w ih =>
    rw [fPow_cons, wtW_cons, neg_add, ← smul_neg, add_comm]; exact IsWord.F p.1 p.2 ih

lemma elt_mem_aFormFE_of_mem_latFE {L l : Y →+ ℤ} {s : QuantumGroup R 𝕧}
    (hs : s ∈ latFE R (L - l)) : elt L l s (latFE_le _ hs) ∈ aFormFE R := by
  induction hs using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨c, w, w', hc, hw, rfl⟩ := hx
    obtain ⟨a, rfl⟩ := hc
    rw [elt_smul _ _ _ (hw ▸ fPow_mul_ePow_mem w w'), ← laurent_smul]
    exact Submodule.smul_mem _ _ (elt_fPow_ePow_mem _)
  | zero => rw [elt_zero']; exact zero_mem _
  | add x y hx hy ihx ihy =>
    rw [elt_add _ _ (latFE_le _ hx) (latFE_le _ hy)]; exact add_mem ihx ihy
  | neg x hx ih =>
    have e : elt L l (-x) (latFE_le _ (neg_mem hx)) = -elt L l x (latFE_le _ hx) := by
      rw [eq_neg_iff_add_eq_zero, ← elt_add, elt_congr (neg_add_cancel x) _ (zero_mem _),
        elt_zero']
    rw [e]; exact neg_mem ih

/-- Every product of divided powers `Eᵢ^{(n)}`, `Fᵢ^{(n)}` times `1_λ` lies in the `𝒜`-span of the
`F_w E_{w'} 1_λ` (from [Lus] 23.1.3). -/
theorem IsWord.elt_mem_aFormFE {u : QuantumGroup R 𝕧} {L l : Y →+ ℤ} (hu : IsWord R u (L - l)) :
    elt L l u hu.mem ∈ aFormFE R := by
  obtain ⟨s, hs, h⟩ := hu.good l
  rw [elt_eq_of_sub_mem_rightRel ratFunc_X_not_root hu.mem (latFE_le _ hs) h]
  exact elt_mem_aFormFE_of_mem_latFE hs

lemma eq_zero_of_mem_adWeightSpace {χ χ' : Y →+ ℤ} (h : χ ≠ χ') {u : QuantumGroup R 𝕧}
    (hu : u ∈ adWeightSpace R 𝕧 χ) (hu' : u ∈ adWeightSpace R 𝕧 χ') : u = 0 :=
  Submodule.disjoint_def.1 ((iSupIndep_adWeightSpace ratFunc_X_not_root).pairwiseDisjoint h) u
    hu hu'

/-- `IsWord.elt_mem_aFormFE` for an arbitrary weight index. -/
theorem IsWord.elt_mem_aFormFE' {u : QuantumGroup R 𝕧} {χ L l : Y →+ ℤ} (hu : IsWord R u χ)
    (h : u ∈ adWeightSpace R 𝕧 (L - l)) : elt L l u h ∈ aFormFE R := by
  by_cases hχ : χ = L - l
  · subst hχ; exact hu.elt_mem_aFormFE
  · rw [elt_congr (eq_zero_of_mem_adWeightSpace hχ hu.mem h) h (zero_mem _), elt_zero']
    exact zero_mem _

lemma mul_mem_aFormFE {x y : Modified R 𝕧} (hx : x ∈ aFormFE R) (hy : y ∈ aFormFE R) :
    x * y ∈ aFormFE R := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
    induction hy using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨w, w', L, l, h, rfl⟩ := hx
      obtain ⟨u, u', L', l', h', rfl⟩ := hy
      by_cases hl : l = L'
      · subst hl
        rw [elt_mul_elt]
        exact (((isWord_fPow w).mul (isWord_ePow w')).mul
          ((isWord_fPow u).mul (isWord_ePow u'))).elt_mem_aFormFE' _
      · rw [elt_mul_elt_of_ne hl]; exact zero_mem _
    | zero => rw [mul_zero]; exact zero_mem _
    | add y z _ _ hy hz => rw [mul_add]; exact add_mem hy hz
    | smul a y _ hy => rw [mul_smul_comm]; exact Submodule.smul_mem _ _ hy
  | zero => rw [zero_mul]; exact zero_mem _
  | add x z _ _ hx hz => rw [add_mul]; exact add_mem hx hz
  | smul a x _ hx => rw [smul_mul_assoc]; exact Submodule.smul_mem _ _ hx

/-- **[Lus] 23.2.2 (a), (c)**, first half: `𝒜U̇` (the `𝒜`-subalgebra generated by the `1_λ`,
`Eᵢ^{(n)} 1_λ`, `Fᵢ^{(n)} 1_λ`) is the `𝒜`-span of the `F_w E_{w'} 1_λ`. -/
theorem aForm_eq_aFormFE : (aForm R).toSubmodule = aFormFE R := by
  refine le_antisymm (fun x hx ↦ ?_) (Submodule.span_le.2 ?_)
  · induction hx using NonUnitalAlgebra.adjoin_induction with
    | mem x hx =>
      rcases hx with ⟨l, rfl⟩ | ⟨i, n, l, rfl | rfl⟩
      · exact IsWord.one.elt_mem_aFormFE' _
      · have hw : IsWord R (qDivPow (𝕧 ^ D.d i) n (E R 𝕧 i)) (n • R.root i) := by
          simpa using IsWord.E i n (IsWord.one (R := R))
        exact hw.elt_mem_aFormFE' _
      · have hw : IsWord R (qDivPow (𝕧 ^ D.d i) n (F R 𝕧 i)) (n • -R.root i) := by
          simpa using IsWord.F i n (IsWord.one (R := R))
        exact hw.elt_mem_aFormFE' _
    | add x y _ _ hx hy => exact add_mem hx hy
    | zero => exact zero_mem _
    | mul x y _ _ hx hy => exact mul_mem_aFormFE hx hy
    | smul a x _ hx => exact Submodule.smul_mem _ a hx
  · rintro _ ⟨w, w', L, l, h, rfl⟩
    have hg := (isGen_fPow (R := R) w).mul (isGen_ePow w')
    by_cases hχ : L - l = -wtW R w + wtW R w'
    · exact hg.elt_mem hχ h
    · rw [elt_congr (eq_zero_of_mem_adWeightSpace (Ne.symm hχ) hg.1 h) h (zero_mem _), elt_zero']
      exact zero_mem _

/-! ### The Chevalley involution on `U̇` -/

variable (R) in
/-- The Chevalley involution `ω` (`Eᵢ ↔ Fᵢ`, `K_μ ↦ K_{-μ}`) as an element of `torusAut`. -/
def omegaAut : torusAut R 𝕧 :=
  ⟨(chevalleyEquiv R 𝕧, LinearEquiv.neg ℤ), fun μ ↦ chevalley_K R 𝕧 μ⟩

lemma wt_omegaAut (l : Y →+ ℤ) : wt (omegaAut R) l = -l := by
  ext μ
  have h : (omegaAut R).1.2⁻¹ μ = -μ := by
    have := autY_apply_inv (omegaAut R).1.2 μ
    change -((omegaAut R).1.2⁻¹ μ) = μ at this
    exact neg_eq_iff_eq_neg.mp this
  rw [wt_apply, h, map_neg, AddMonoidHom.neg_apply]

lemma map_omega_elt {L l : Y →+ ℤ} {u : QuantumGroup R 𝕧} (hu : u ∈ adWeightSpace R 𝕧 (L - l))
    (hu' : chevalley R 𝕧 u ∈ adWeightSpace R 𝕧 (-L - -l)) :
    map (omegaAut R) (elt L l u hu) = elt (-L) (-l) (chevalley R 𝕧 u) hu' := by
  rw [map_elt]
  exact elt_index (wt_omegaAut L) (wt_omegaAut l) rfl _ _

lemma chevalley_ePow (w : List (I × ℕ)) : chevalley R 𝕧 (ePow R w) = fPow R w := by
  induction w with
  | nil => simp
  | cons p w ih => rw [ePow_cons, fPow_cons, _root_.map_mul, map_qDivPow', chevalley_E, ih]

lemma chevalley_fPow (w : List (I × ℕ)) : chevalley R 𝕧 (fPow R w) = ePow R w := by
  induction w with
  | nil => simp
  | cons p w ih => rw [ePow_cons, fPow_cons, _root_.map_mul, map_qDivPow', chevalley_F, ih]

lemma map_omega_smul (a : 𝒜) (x : Modified R 𝕧) :
    map (omegaAut R) (a • x) = a • map (omegaAut R) x := by
  rw [laurent_smul, map_smul, ← laurent_smul]

lemma map_omega_mem_aForm {x : Modified R 𝕧} (hx : x ∈ aForm R) :
    map (omegaAut R) x ∈ aForm R := by
  induction hx using NonUnitalAlgebra.adjoin_induction with
  | mem x hx =>
    rcases hx with ⟨l, rfl⟩ | ⟨i, n, l, rfl | rfl⟩
    · rw [one, map_omega_elt _ (by rw [_root_.map_one, sub_self]; exact one_mem_adWeightSpace)]
      exact (isGen_one.of_eq (_root_.map_one _)).elt_mem (sub_self _) _
    · rw [divE, map_omega_elt _ (by
        rw [map_qDivPow', chevalley_E]
        convert qDivPow_F_mem (R := R) _ i n using 2
        rw [smul_neg]; abel)]
      exact (isGen_F i n).of_eq (by rw [map_qDivPow', chevalley_E]) |>.elt_mem
        (by rw [smul_neg]; abel) _
    · rw [divF, map_omega_elt _ (by
        rw [map_qDivPow', chevalley_F]
        convert qDivPow_E_mem (R := R) _ i n using 2
        rw [smul_neg]; abel)]
      exact (isGen_E i n).of_eq (by rw [map_qDivPow', chevalley_F]) |>.elt_mem
        (by rw [smul_neg]; abel) _
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | zero => rw [map_zero]; exact zero_mem _
  | mul x y _ _ hx hy => rw [map_mul]; exact mul_mem hx hy
  | smul a x _ hx => rw [map_omega_smul]; exact SMulMemClass.smul_mem a hx

lemma map_omega_mem_aFormEF {x : Modified R 𝕧} (hx : x ∈ aFormFE R) :
    map (omegaAut R) x ∈ aFormEF R := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨w, w', L, l, h, rfl⟩ := hx
    have h' : ePow R w * fPow R w' ∈ adWeightSpace R 𝕧 (-L - -l) := by
      have := map_mem_adWeightSpace_sub (omegaAut R) h
      rw [wt_omegaAut, wt_omegaAut] at this
      convert this using 1
      change _ = chevalley R 𝕧 _
      rw [_root_.map_mul, chevalley_fPow, chevalley_ePow]
    rw [map_omega_elt h (by rwa [_root_.map_mul, chevalley_fPow, chevalley_ePow])]
    rw [elt_congr (by rw [_root_.map_mul, chevalley_fPow, chevalley_ePow]) _ h']
    exact elt_ePow_fPow_mem h'
  | zero => rw [map_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | smul a x _ hx => rw [map_omega_smul]; exact Submodule.smul_mem _ a hx

lemma map_omega_mem_aFormFE {x : Modified R 𝕧} (hx : x ∈ aFormEF R) :
    map (omegaAut R) x ∈ aFormFE R := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨w, w', L, l, h, rfl⟩ := hx
    have h' : fPow R w * ePow R w' ∈ adWeightSpace R 𝕧 (-L - -l) := by
      have := map_mem_adWeightSpace_sub (omegaAut R) h
      rw [wt_omegaAut, wt_omegaAut] at this
      convert this using 1
      change _ = chevalley R 𝕧 _
      rw [_root_.map_mul, chevalley_fPow, chevalley_ePow]
    rw [map_omega_elt h (by rwa [_root_.map_mul, chevalley_fPow, chevalley_ePow])]
    rw [elt_congr (by rw [_root_.map_mul, chevalley_fPow, chevalley_ePow]) _ h']
    exact elt_fPow_ePow_mem h'
  | zero => rw [map_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | smul a x _ hx => rw [map_omega_smul]; exact Submodule.smul_mem _ a hx

lemma map_omega_map_omega (x : Modified R 𝕧) : map (omegaAut R) (map (omegaAut R) x) = x := by
  rw [map_map]
  have h : omegaAut R * omegaAut R = 1 := torusAut_ext ratFunc_X_not_root (by
    ext u
    exact DFunLike.congr_fun (chevalley_comp_chevalley R 𝕧) u)
  rw [h, map_one]

/-- **[Lus] 23.2.2 (a), (c)**, second half: `𝒜U̇` is the `𝒜`-span of the `E_w F_{w'} 1_λ`. -/
theorem aForm_eq_aFormEF : (aForm R).toSubmodule = aFormEF R := by
  refine le_antisymm (fun x hx ↦ ?_) (fun x hx ↦ ?_)
  · have h1 : map (omegaAut R) x ∈ aFormFE R := by
      rw [← aForm_eq_aFormFE]; exact map_omega_mem_aForm hx
    simpa [map_omega_map_omega] using map_omega_mem_aFormEF h1
  · have h1 : map (omegaAut R) x ∈ (aForm R).toSubmodule := by
      rw [aForm_eq_aFormFE]; exact map_omega_mem_aFormFE hx
    simpa [map_omega_map_omega] using map_omega_mem_aForm h1

/-- **[Lus] 23.2.2 (a)**: the `𝒜`-spans of the `F_w E_{w'} 1_λ` and of the `E_w F_{w'} 1_λ`
coincide. -/
theorem aFormFE_eq_aFormEF : aFormFE R = aFormEF R := by
  rw [← aForm_eq_aFormFE, aForm_eq_aFormEF]

end Modified

end LieLean.QuantumGroup
