/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.PBW.Monomials
import LieLean.Algebra.QuantumGroup.PBW.RootVectorsQuantum
import LieLean.Algebra.QuantumGroup.TriangularDecomposition
import Mathlib.Algebra.Polynomial.Coeff

/-!
# Linear independence of the PBW monomials along a reduced word

Let `v ≠ 0` not be a root of unity, `Tᵢ = braidEquivOfNotRoot` Lusztig's automorphisms of
`U = U_v(𝔤)`, and `ω = i₁ ⋯ iₙ` a reduced word of a Coxeter group `W` with the Coxeter matrix of
the Cartan datum. We prove ([Jan] Lemma 8.21 b), [Lus] 40.2.1) that the ordered monomials

`E_{β₁}^{c₁} ⋯ E_{βₙ}^{cₙ}`, `E_{β_m} = T_{i₁} ⋯ T_{i_{m-1}}(E_{i_m})`,

are linearly independent (`QuantumGroup.linearIndependent_pbwMonomial_of_isReduced`), under the
hypotheses guaranteeing that the root vectors along reduced words lie in `U⁺`
(`BraidOuterCondition` and `aᵢⱼ aⱼᵢ ≤ 3`; both hold in finite type,
`QuantumGroup.linearIndependent_pbwMonomial_of_isFiniteCartan`). [Jan] states this in finite type
and for the opposite order of the factors.

The proof is the induction of [Jan] 8.21 b) (`CoxeterSystem.linearIndependent_pbwMonomial`): a
monomial along `i ω` is `Eᵢᵃ Tᵢ(M)` with `M` a monomial along `ω`, and

`∑ₐ Eᵢᵃ Tᵢ(uₐ) = 0` with `uₐ ∈ U⁺` implies `uₐ = 0` for all `a`
(`QuantumGroup.eq_zero_of_sum_E_pow_mul_map`).

Indeed `Eᵢ = Tᵢ(-K̃ᵢ⁻¹ Fᵢ)`, so applying `Tᵢ⁻¹` gives `∑ₐ cₐ Fᵢᵃ K̃ᵢ⁻ᵃ uₐ = 0` with nonzero scalars
`cₐ`, and the triangular decomposition `U ≅ U⁻ ⊗ U⁰ ⊗ U⁺` (`triangularEquiv`) separates the
summands: the powers `θᵢᵃ` are linearly independent modulo the Serre ideal of `'f`, because the
algebra map `'f → k[X]`, `θᵢ ↦ X`, `θⱼ ↦ 0` (`j ≠ i`), kills the Serre elements
(`LusztigF.nodeEval`).

## Main results

* `QuantumGroup.eq_zero_of_sum_E_pow_mul_map`: the sum `∑ₐ Eᵢᵃ Tᵢ(U⁺)` is direct.
* `QuantumGroup.linearIndependent_pbwMonomial_of_isReduced`,
  `QuantumGroup.linearIndependent_pbwMonomial_of_isFiniteCartan`: independence of the ordered
  monomials in the root vectors along a reduced word.

Proofs adapted from the ungated `m15-pbw` branch (3473bfd); the arguments are
reconstructed.

## References

* [Jan] J. C. Jantzen, *Lectures on quantum groups*, GSM 6, 8.21–8.24.
* [Lus] G. Lusztig, *Introduction to quantum groups*, 40.2.1.
-/

noncomputable section

open Polynomial TensorProduct

/-! ### Powers of a generator modulo the Serre ideal -/

namespace QuantumGroup

variable {k B : Type*} [Field k] [Ring B] [Algebra k B] {q : k}

lemma qSerreDiv_zero_left {m : ℕ} (hm : m ≠ 0) (b : B) : qSerreDiv q m 0 b = 0 := by
  refine Finset.sum_eq_zero fun r _ ↦ ?_
  rcases Nat.eq_zero_or_pos r with rfl | hr
  · simp [qDivPow, zero_pow hm]
  · simp [qDivPow, zero_pow hr.ne']

end QuantumGroup


namespace LusztigF

open QuantumGroup

variable {k I : Type*} [Field k] [DecidableEq I]

variable (k) in
/-- The algebra map `'f → k[X]` with `θᵢ ↦ X` and `θⱼ ↦ 0` for `j ≠ i`. -/
def nodeEval (i : I) : LusztigF k I →ₐ[k] k[X] :=
  FreeAlgebra.lift k fun j ↦ if j = i then X else 0

@[simp] lemma nodeEval_θ_self (i : I) : nodeEval k i (θ k i) = X := by simp [nodeEval]

lemma nodeEval_θ_of_ne {i j : I} (h : j ≠ i) : nodeEval k i (θ k j) = 0 := by
  simp [nodeEval, h]

/-- `θᵢ ↦ X`, `θⱼ ↦ 0` kills the Serre ideal: every Serre element involves two distinct
generators. -/
theorem nodeEval_eq_zero_of_mem_serreIdeal {D : LusztigCartanDatum I} {v : k} (i : I)
    {x : LusztigF k I} (hx : x ∈ serreIdeal D v) : nodeEval k i x = 0 := by
  induction hx using TwoSidedIdeal.span_induction with
  | mem x hx =>
    obtain ⟨a, b, hab, rfl⟩ := hx
    rw [serreElement, map_qSerreDiv]
    by_cases hb : b = i
    · subst hb
      rw [nodeEval_θ_of_ne hab, qSerreDiv_zero_left]
      have := D.isGeneralizedCartan_cartanMatrix.offDiag_nonpos a b hab
      omega
    · rw [nodeEval_θ_of_ne hb, qSerreDiv_zero_right]
  | zero => simp
  | add x y _ _ hx hy => rw [map_add, hx, hy, add_zero]
  | neg x _ hx => rw [map_neg, hx, neg_zero]
  | left_absorb a x _ hx => rw [map_mul, hx, mul_zero]
  | right_absorb b x _ hx => rw [map_mul, hx, zero_mul]

end LusztigF

namespace QuantumGroup

open LusztigF CoxeterSystem

variable {k : Type*} [Field k] {I Y : Type*} [AddCommGroup Y] [DecidableEq I]
  {D : LusztigCartanDatum I} {R : D.RootDatum Y} {v : k}

variable (R v) in
/-- `U` is a nontrivial ring: the counit `U → k` is a ring homomorphism. -/
instance instNontrivial : Nontrivial (QuantumGroup R v) :=
  (counit R v).toRingHom.domain_nontrivial

variable (R v) in
/-- `U⁺`, the image of `x ↦ x⁺`, is the subalgebra generated by the `Eᵢ`. -/
theorem range_plusHom : (plusHom R v).range = Algebra.adjoin k (Set.range (E R v)) := by
  rw [← Algebra.map_top, ← FreeAlgebra.adjoin_range_ι, AlgHom.map_adjoin, ← Set.range_comp]
  congr 2
  funext i
  simp [plusHom]

variable [NeZero v]

/-- `(-K̃ᵢ⁻¹ Fᵢ)ᵃ` is a nonzero multiple of `Fᵢᵃ K̃ᵢ⁻ᵃ`. -/
lemma exists_neg_K_mul_F_pow (i : I) (a : ℕ) :
    ∃ c : k, c ≠ 0 ∧ (-(K R v (-ktilde R i) * F R v i)) ^ a =
      c • (F R v i ^ a * K R v (-(a • ktilde R i))) := by
  induction a with
  | zero => exact ⟨1, one_ne_zero, by simp⟩
  | succ a ih =>
    obtain ⟨c, hc, h⟩ := ih
    refine ⟨-(c * v ^ (-R.root i (-((a + 1) • ktilde R i)))),
      neg_ne_zero.2 (mul_ne_zero hc (zpow_ne_zero _ (NeZero.ne v))), ?_⟩
    have hK : K R v (-(a • ktilde R i)) * K R v (-ktilde R i) =
        K R v (-((a + 1) • ktilde R i)) := by
      rw [K_add, succ_nsmul, neg_add]
    rw [pow_succ, h, mul_neg, smul_mul_assoc, mul_assoc, ← mul_assoc (K R v _), hK, K_mul_F,
      mul_smul_comm, ← mul_assoc, ← pow_succ, smul_smul, neg_smul]

/-- **The sum `∑ₐ Eᵢᵃ Tᵢ(U⁺)` is direct** ([Jan] Lemma 8.21 a)): if `T` is an injective algebra
endomorphism of `U` with Lusztig's formulas for `Tᵢ` on the generators, and `uₐ ∈ U⁺` satisfy
`∑ₐ Eᵢᵃ T(uₐ) = 0`, then all `uₐ` vanish. Requires `v` not a root of unity (triangular
decomposition). -/
theorem eq_zero_of_sum_E_pow_mul_map (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) {i : I}
    {T : QuantumGroup R v →ₐ[k] QuantumGroup R v} (hT : Function.Injective T)
    (HT : HasBraidGeneratorImages i T) (f : ℕ →₀ QuantumGroup R v)
    (hf : ∀ a, f a ∈ (plusHom R v).range) (h : (f.sum fun a x ↦ E R v i ^ a * T x) = 0) :
    f = 0 := by
  set G : QuantumGroup R v := -(K R v (-ktilde R i) * F R v i) with hG_def
  have hG : T G = E R v i := by
    rw [hG_def, map_neg, map_mul, HT.map_K, HT.map_F, ite_eq_left rfl, reflY_neg_ktilde, mul_neg,
      neg_neg, ← mul_assoc, Kt_mul_K_neg, one_mul]
  have h1 : (f.sum fun a x ↦ G ^ a * x) = 0 := by
    apply hT
    rw [map_zero, ← h, Finsupp.sum, Finsupp.sum, map_sum]
    refine Finset.sum_congr rfl fun a _ ↦ ?_
    rw [map_mul, map_pow, hG]
  choose X hX using hf
  change ∀ a, (plusHom R v) (X a) = f a at hX
  choose c hc hGc using fun a ↦ exists_neg_K_mul_F_pow (R := R) (v := v) i a
  set z : TriSpace k I Y := ∑ a ∈ f.support,
    (c a • θ k i ^ a) ⊗ₜ[k] ((AddMonoidAlgebra.single (-(a • ktilde R i)) (1 : k)) ⊗ₜ[k] X a)
    with hz_def
  have hz : triMap (R := R) (v := v) z = 0 := by
    rw [← h1, hz_def, map_sum, Finsupp.sum]
    refine Finset.sum_congr rfl fun a _ ↦ ?_
    rw [triMap_tmul, map_smul, map_pow, minusHom_θ, zeroHom_single, hX, hG_def, hGc]
    simp only [smul_mul_assoc, mul_assoc]
  have hzW := mem_serreTriSubmodule_of_triMap_eq_zero R v hv' hz
  ext b
  rw [Finsupp.zero_apply]
  by_cases hb : b ∈ f.support
  swap
  · exact Finsupp.notMem_support_iff.1 hb
  let ℓ : LusztigF k I →ₗ[k] k := (Polynomial.lcoeff k b) ∘ₗ (nodeEval k i).toLinearMap
  let π : TriSpace k I Y →ₗ[k] LusztigF k I ⧸ serreSubmodule D v :=
    (TensorProduct.lid k _).toLinearMap ∘ₗ TensorProduct.map ℓ
      ((TensorProduct.lid k _).toLinearMap ∘ₗ
        TensorProduct.map (augmentation Y).toLinearMap (serreSubmodule D v).mkQ)
  have hπ : ∀ y g x', π (y ⊗ₜ (g ⊗ₜ x')) =
      ℓ y • augmentation Y g • Submodule.Quotient.mk (p := serreSubmodule D v) x' :=
    fun _ _ _ ↦ rfl
  have hℓ : ∀ a, ℓ (c a • θ k i ^ a) = if a = b then c a else 0 := by
    intro a
    simp only [ℓ, LinearMap.comp_apply, AlgHom.toLinearMap_apply, map_smul, map_pow,
      nodeEval_θ_self, Polynomial.lcoeff_apply, Polynomial.coeff_X_pow,
      smul_eq_mul]
    split_ifs with h1 h2 h2
    · rw [mul_one]
    · exact absurd h1.symm h2
    · exact absurd h2.symm h1
    · rw [mul_zero]
  have hW : serreTriSubmodule Y D v ≤ LinearMap.ker π := by
    rw [serreTriSubmodule, Submodule.span_le]
    rintro _ ⟨y, g, x', rfl, h | h⟩
    · have : ℓ y = 0 := by
        simp [ℓ, nodeEval_eq_zero_of_mem_serreIdeal i h]
      simp [hπ, this]
    · have : Submodule.Quotient.mk (p := serreSubmodule D v) x' = 0 :=
        (Submodule.Quotient.mk_eq_zero _).2 (mem_serreSubmodule.2 h)
      simp [hπ, this]
  have hzπ := hW hzW
  rw [LinearMap.mem_ker, hz_def, map_sum, Finset.sum_eq_single_of_mem b hb, hπ, hℓ, ite_eq_left rfl,
    augmentation_single, one_smul, smul_eq_zero, or_iff_right (hc b),
    Submodule.Quotient.mk_eq_zero] at hzπ
  · rw [← hX b]
    exact (TwoSidedIdeal.mem_ker _).1
      (serreIdeal_le_ker_plusHom (R := R) (NeZero.ne v) hv' (mem_serreSubmodule.1 hzπ))
  · intro a _ hab
    rw [hπ, hℓ, ite_eq_right hab, zero_smul]

variable (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1)

/-- `braidEquivOfNotRoot` has Lusztig's generator formulas. -/
lemma braidEquivOfNotRoot_images (l : I) :
    HasBraidGeneratorImages l (braidEquivOfNotRoot R hv' l).toAlgHom :=
  braidEquivOfGeneric_images (fun i ↦ (shortNode_braidGeneric_of_not_root hv' i).sub_ne)
    (braidSerreGeneric_of_not_root hv') l

section Reduced

variable (hD : D.BraidOuterCondition)
  (hfin : ∀ i j, i ≠ j → D.cartanMatrix i j * D.cartanMatrix j i ≤ 3)
  {W : Type*} [Group W] {cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W}

include hD hfin in
/-- The ordered monomials in the root vectors along a reduced word lie in `U⁺`. -/
theorem pbwMonomial_mem_adjoin_of_isReduced {ω : List I} (hω : cs.IsReduced ω)
    (c : Fin ω.length → ℕ) :
    pbwMonomial (braidEquivOfNotRoot R hv') (E R v) ω c ∈
      Algebra.adjoin k (Set.range (E R v)) :=
  pbwMonomial_mem _ _ (fun n hn ↦ rootVector_mem_adjoin_of_not_root hD hfin hv' hω n hn) c

include hD hfin in
/-- **Linear independence of the PBW monomials** ([Jan] Lemma 8.21 b), opposite order,
[Lus] 40.2.1): for `v ≠ 0` not a root of unity and a reduced word `ω = i₁ ⋯ iₙ` of a Coxeter group
with the Coxeter matrix of the Cartan datum, the ordered monomials `E_{β₁}^{c₁} ⋯ E_{βₙ}^{cₙ}` in
the root vectors `E_{β_m} = T_{i₁} ⋯ T_{i_{m-1}}(E_{i_m})` are linearly independent. The hypotheses
on the Cartan datum (`BraidOuterCondition` and `aᵢⱼ aⱼᵢ ≤ 3`) are those under which the root vectors
along reduced words are known to lie in `U⁺`; they hold in finite type. -/
theorem linearIndependent_pbwMonomial_of_isReduced {ω : List I} (hω : cs.IsReduced ω) :
    LinearIndependent k (pbwMonomial (braidEquivOfNotRoot R hv') (E R v) ω) := by
  refine linearIndependent_pbwMonomial
    (S := Subalgebra.toSubmodule (Algebra.adjoin k (Set.range (E R v)))) ?_ ω ?_
  · intro i f hf h
    refine eq_zero_of_sum_E_pow_mul_map hv' (T := (braidEquivOfNotRoot R hv' i).toAlgHom)
      (braidEquivOfNotRoot R hv' i).injective (braidEquivOfNotRoot_images hv' i) f
      (fun a ↦ ?_) h
    rw [range_plusHom]
    exact hf a
  · intro n c
    exact pbwMonomial_mem_adjoin_of_isReduced hv' hD hfin (hω.drop n) c

end Reduced

/-- **Linear independence of the PBW monomials in finite type** ([Jan] Lemma 8.21 b), opposite
order, [Lus] 40.2.1): for a Cartan datum of finite type, `v ≠ 0` not a root of unity and a reduced
word `ω` of a Coxeter group with the Coxeter matrix of the datum (e.g. the Weyl group of a
realization), the ordered monomials in the root vectors along `ω` are linearly independent. -/
theorem linearIndependent_pbwMonomial_of_isFiniteCartan [Fintype I]
    (hA : D.cartanMatrix.IsFiniteCartan) {W : Type*} [Group W]
    {cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W} {ω : List I} (hω : cs.IsReduced ω) :
    LinearIndependent k (pbwMonomial (braidEquivOfNotRoot R hv') (E R v) ω) :=
  linearIndependent_pbwMonomial_of_isReduced hv'
    (LusztigCartanDatum.braidOuterCondition_of_isFiniteCartan hA)
    (fun _ _ hij ↦ hA.mul_le_three hij) hω

end QuantumGroup
