/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.PBW.IntegralA2
import LieLean.Algebra.QuantumGroup.PBW.RankTwoB2

/-!
# Integral straightening in type `B₂`

Let `e, f` satisfy the quantum Serre relations of type `B₂`, `e` short with parameter `q` and `f`
long with parameter `p = q²`, and let `y = ef - p⁻¹fe`, `x = ey - ye`, `X = [2]⁻¹ x` (for `e = Eᵢ`,
`f = Eⱼ` these are the root vectors `TᵢTⱼ(Eᵢ)` and `Tᵢ(Eⱼ)`). Write `e^{(a)}, y^{(c)}` for the divided
powers at `q` and `X^{(b)}, f^{(d)}` for those at `p`. We prove

* `f^{(s)} e^{(r)} = Σ_n (-1)ⁿ q^{(r-n)(2s-n)} e^{(r-n)} W_{n,s}` with
  `W_{n,s} = Σ_m q^{2(n-m)(s-m)+2m} X^{(n-m)} y^{(2m-n)} f^{(s-m)}`
  (`B2Integral.qDivPow_f_mul_qDivPow_e`), and
* `f^{(s)} X^{(r)} = Σ_n (-1)ⁿ p^{-n(r-n)} ν_n X^{(r-n)} y^{(2n)} f^{(s-n)}` with explicit Laurent
  coefficients `ν_n` (`B2Integral.qDivPow_f_mul_qDivPow_X`).

Both are instances of one two-term straightening identity (`B2Integral.straighten`). Consequently
the `Λ`-combinations of the ordered monomials `e^{(a)} X^{(b)} y^{(c)} f^{(d)}` (`Λ` a subring
containing `q^{±1}`) are stable under left multiplication by all `e^{(n)}` and `f^{(n)}`
(`B2Integral.qDivPow_f_mul_mem`), and every `X^{(n)}`, `y^{(n)}` lies in the subring generated by
`Λ` and the `e^{(a)}`, `f^{(d)}` (`B2Integral.qDivPow_X_mem`, `B2Integral.qDivPow_y_mem`).

These are the rank-two commutation formulas behind [Lus] 41.1.4 in type `B₂`; Lusztig obtains them
in *Quantum groups at roots of 1*. The derivation here is our own.

## References

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993.
* G. Lusztig, *Quantum groups at roots of 1*, Geom. Dedicata 35 (1990).
-/

open Finset

noncomputable section

namespace LieLean.QuantumGroup

namespace B2Integral

variable {k B : Type*} [Field k] [Ring B] [Algebra k B]

/-! ### A two-term straightening identity -/

section Straighten

variable {t : k}

/-- `t^{-b}[a] + t^a[b] = [a+b]`. -/
lemma qInt_add (a b : ℕ) : t⁻¹ ^ b * qInt t a + t ^ a * qInt t b = qInt t (a + b) := by
  induction b with
  | zero => simp [qInt]
  | succ b ih =>
    rw [← add_assoc, qInt_succ, qInt_succ, ← ih]
    ring

variable (t) in
/-- The coefficient `(-1)ⁿ t^{(r-n)N - n(r-n)}` of the straightening identity. -/
def sCoef (N r n : ℕ) : k := (-1) ^ n * t ^ ((r - n) * N) * t⁻¹ ^ (n * (r - n))

/-- **Two-term straightening.** If `Wₙ a = t^{N-2n} a Wₙ - [n+1] W_{n+1}` for all `n`, then
`W₀ a^{(r)} = Σ_{n ≤ r} (-1)ⁿ t^{(r-n)(N-n)} a^{(r-n)} Wₙ`. -/
theorem straighten (ht0 : t ≠ 0) (hti : ∀ n : ℕ, 0 < n → qInt t n ≠ 0) (N : ℕ) {a : B}
    {W : ℕ → B}
    (hW : ∀ n, W n * a = (t ^ N * t⁻¹ ^ (2 * n)) • (a * W n) - qInt t (n + 1) • W (n + 1))
    (r : ℕ) :
    W 0 * qDivPow t r a =
      ∑ n ∈ range (r + 1), sCoef t N r n • (qDivPow t (r - n) a * W n) := by
  induction r with
  | zero => simp [sCoef, qDivPow_zero']
  | succ r ih =>
    have hc := hti (r + 1) (Nat.succ_pos r)
    refine smul_right_injective B hc ?_
    simp only
    have hL : qInt t (r + 1) • (W 0 * qDivPow t (r + 1) a) = W 0 * qDivPow t r a * a := by
      rw [mul_assoc, A2Integral.qDivPow_mul_self a r hc, mul_smul_comm]
    have hT : ∀ n ∈ range (r + 1), sCoef t N r n • (qDivPow t (r - n) a * W n) * a =
        (sCoef t N r n * (t ^ N * t⁻¹ ^ (2 * n)) * qInt t (r - n + 1)) •
            (qDivPow t (r + 1 - n) a * W n) -
          (sCoef t N r n * qInt t (n + 1)) • (qDivPow t (r - n) a * W (n + 1)) := by
      intro n hn
      have hnr : n ≤ r := Nat.lt_succ_iff.1 (mem_range.1 hn)
      rw [smul_mul_assoc, mul_assoc, hW, mul_sub, mul_smul_comm, mul_smul_comm, ← mul_assoc,
        A2Integral.qDivPow_mul_self a _ (hti _ (Nat.succ_pos _)),
        show r - n + 1 = r + 1 - n by omega, smul_mul_assoc, smul_sub, smul_smul, smul_smul,
        smul_smul, mul_assoc (sCoef t N r n)]
    rw [hL, ih, sum_mul, sum_congr rfl hT, sum_sub_distrib, smul_sum,
      sum_range_succ (fun n ↦ (sCoef t N r n * qInt t (n + 1)) •
        (qDivPow t (r - n) a * W (n + 1))) r,
      sum_range_succ' (fun n ↦ (sCoef t N r n * (t ^ N * t⁻¹ ^ (2 * n)) * qInt t (r - n + 1)) •
        (qDivPow t (r + 1 - n) a * W n)) r,
      sum_range_succ' _ (r + 1), sum_range_succ _ r]
    have hmid : ∀ n ∈ range r,
        qInt t (r + 1) • (sCoef t N (r + 1) (n + 1) •
            (qDivPow t (r + 1 - (n + 1)) a * W (n + 1))) =
          (sCoef t N r (n + 1) * (t ^ N * t⁻¹ ^ (2 * (n + 1))) * qInt t (r - (n + 1) + 1)) •
              (qDivPow t (r + 1 - (n + 1)) a * W (n + 1)) -
            (sCoef t N r n * qInt t (n + 1)) • (qDivPow t (r - n) a * W (n + 1)) := by
      intro n hn
      have hnr : n < r := mem_range.1 hn
      obtain ⟨c, rfl⟩ : ∃ c, r = n + 1 + c := ⟨r - (n + 1), by omega⟩
      rw [show n + 1 + c + 1 - (n + 1) = c + 1 by omega, show n + 1 + c - n = c + 1 by omega,
        show n + 1 + c - (n + 1) + 1 = c + 1 by omega, smul_smul, ← sub_smul]
      congr 1
      have key := qInt_add (t := t) (c + 1) (n + 1)
      have hinv : t⁻¹ ^ (c + 1) * t ^ (c + 1) = 1 := by
        rw [← mul_pow, inv_mul_cancel₀ ht0, one_pow]
      simp only [sCoef, show n + 1 + c + 1 - (n + 1) = c + 1 by omega,
        show n + 1 + c - (n + 1) = c by omega, show n + 1 + c - n = c + 1 by omega]
      rw [show n + 1 + c + 1 = c + 1 + (n + 1) by omega, ← key]
      linear_combination (norm := ring_nf) (-((-1) ^ n * t ^ ((c + 1) * N) * t⁻¹ ^ (n * (c + 1)) *
        qInt t (n + 1))) * hinv
    rw [sum_congr rfl hmid, sum_sub_distrib]
    have h0 : qInt t (r + 1) • (sCoef t N (r + 1) 0 • (qDivPow t (r + 1 - 0) a * W 0)) =
        (sCoef t N r 0 * (t ^ N * t⁻¹ ^ (2 * 0)) * qInt t (r - 0 + 1)) •
          (qDivPow t (r + 1 - 0) a * W 0) := by
      rw [smul_smul]
      congr 1
      simp only [sCoef, pow_zero, Nat.sub_zero, one_mul, zero_mul, mul_one, add_mul, pow_add]
      ring
    have hlast : qInt t (r + 1) • (sCoef t N (r + 1) (r + 1) •
        (qDivPow t (r + 1 - (r + 1)) a * W (r + 1))) =
        -((sCoef t N r r * qInt t (r + 1)) • (qDivPow t (r - r) a * W (r + 1))) := by
      rw [smul_smul, Nat.sub_self, Nat.sub_self, ← neg_smul]
      congr 1
      simp only [sCoef, Nat.sub_self, zero_mul, mul_zero, pow_zero, mul_one, pow_succ]
      ring
    rw [h0, hlast]
    abel

end Straighten

/-! ### Type `B₂`: elementary relations -/

section Relations

variable {q : k} (hq0 : q ≠ 0) (hqi : ∀ n : ℕ, 0 < n → qInt q n ≠ 0)
  (hpi : ∀ n : ℕ, 0 < n → qInt (q ^ 2) n ≠ 0) {e X y f : B}
  (H : B2PBW.Rel (q ^ 2) e (qInt q 2 • X) y f)

include H in
lemma fe : f * e = q ^ 2 • (e * f) - q ^ 2 • y := H.fe

include H in
lemma ye : y * e = e * y - qInt q 2 • X := H.ye

include hqi H in
lemma Xe : X * e = (q ^ 2)⁻¹ • (e * X) := by
  have h := H.xe
  rw [smul_mul_assoc, mul_smul_comm, smul_smul, mul_comm, ← smul_smul] at h
  exact smul_right_injective B (hqi 2 (by norm_num)) h

include H in
lemma fy : f * y = (q ^ 2)⁻¹ • (y * f) := H.fy

include hq0 hqi H in
lemma yX : y * X = (q ^ 2)⁻¹ • (X * y) := by
  have h := H.yx (pow_ne_zero 2 hq0)
  rw [mul_smul_comm, smul_mul_assoc, smul_comm] at h
  exact smul_right_injective B (hqi 2 (by norm_num)) h

include hq0 hqi H in
/-- `f X = X f - (q² - 1) y^{(2)}`. -/
lemma fX : f * X = X * f - (q ^ 2 - 1) • qDivPow q 2 y := by
  have h := H.fx (pow_ne_zero 2 hq0)
  have hy : y * y = qInt q 2 • qDivPow q 2 y := by
    rw [← A2Integral.qDivPow_mul_self y 1 (hqi 2 (by norm_num)), A2Integral.qDivPow_one']
  rw [mul_smul_comm, smul_mul_assoc, hy, smul_comm (q ^ 2 - 1), ← smul_sub] at h
  exact smul_right_injective B (hqi 2 (by norm_num)) h

end Relations

/-! ### q-integer identities -/

section QInt

variable {q : k}

/-- `[2]_q [b]_{q²} = [2b]_q`. -/
lemma qInt_two_mul (b : ℕ) : qInt q 2 * qInt (q ^ 2) b = qInt q (2 * b) := by
  have h2 : qInt q 2 = q + q⁻¹ := by simp [qInt, sum_range_succ]
  induction b with
  | zero => simp [qInt]
  | succ b ih =>
    rw [show 2 * (b + 1) = 2 * b + 1 + 1 by ring, qInt_succ (v := q) (2 * b + 1),
      qInt_succ (v := q) (2 * b), ← ih, qInt_succ (v := q ^ 2) b, h2]
    ring

/-- `[2b+2; 2b]_q = [b+1]_{q²} [2b+1]_q`. -/
lemma qBinomial_two_add (h2 : qInt q 2 ≠ 0) (hF : ∀ n, qFactorial q n ≠ 0) (b : ℕ) :
    qBinomial q (2 * b + 2) (2 * b) = qInt (q ^ 2) (b + 1) * qInt q (2 * b + 1) := by
  have e := qBinomial_mul_qFactorial_mul_qFactorial (v := q)
    (show 2 * b ≤ 2 * b + 2 by omega)
  have h2' : qFactorial q 2 = qInt q 2 := by simp [qFactorial, qInt]
  have hF2 : qFactorial q (2 * b + 2) =
      qInt q (2 * b + 1 + 1) * (qInt q (2 * b + 1) * qFactorial q (2 * b)) := by
    rw [qFactorial_succ, qFactorial_succ]
  rw [show 2 * b + 2 - 2 * b = 2 by omega, h2', hF2] at e
  have hm := qInt_two_mul (q := q) (b + 1)
  rw [show 2 * (b + 1) = 2 * b + 1 + 1 by ring] at hm
  apply mul_right_cancel₀ (mul_ne_zero h2 (hF (2 * b)))
  linear_combination e - qInt q (2 * b + 1) * qFactorial q (2 * b) * hm

end QInt

/-! ### Type `B₂`: divided powers -/

section Divided

/-- Commuting divided powers. -/
lemma qDivPow_mul_qDivPow_comm {u u' c : k} {w a : B} (h : w * a = c • (a * w)) (m n : ℕ) :
    qDivPow u m w * qDivPow u' n a = c ^ (m * n) • (qDivPow u' n a * qDivPow u m w) := by
  simp only [qDivPow, smul_mul_smul_comm, pow_mul_pow_of_mul_eq_smul h m n, smul_smul, mul_comm]

variable {q : k} (hq0 : q ≠ 0) (hqi : ∀ n : ℕ, 0 < n → qInt q n ≠ 0)
  (hpi : ∀ n : ℕ, 0 < n → qInt (q ^ 2) n ≠ 0) {e X y f : B}
  (H : B2PBW.Rel (q ^ 2) e (qInt q 2 • X) y f)

include hqi H in
lemma Xd_e (b : ℕ) :
    qDivPow (q ^ 2) b X * e = (q ^ 2)⁻¹ ^ b • (e * qDivPow (q ^ 2) b X) := by
  simpa [A2Integral.qDivPow_one'] using
    qDivPow_mul_qDivPow_comm (u := q ^ 2) (u' := q) (Xe hqi H) b 1

include hq0 hqi H in
lemma yd_Xd (c b : ℕ) :
    qDivPow q c y * qDivPow (q ^ 2) b X =
      (q ^ 2)⁻¹ ^ (c * b) • (qDivPow (q ^ 2) b X * qDivPow q c y) :=
  qDivPow_mul_qDivPow_comm (yX hq0 hqi H) c b

include H in
lemma fd_yd (d c : ℕ) :
    qDivPow (q ^ 2) d f * qDivPow q c y =
      (q ^ 2)⁻¹ ^ (d * c) • (qDivPow q c y * qDivPow (q ^ 2) d f) :=
  qDivPow_mul_qDivPow_comm (fy H) d c

include hq0 hqi H in
/-- `y^{(c+1)} e = e y^{(c+1)} - q^{-c}[2] X y^{(c)}`. -/
lemma yd_e (c : ℕ) :
    qDivPow q (c + 1) y * e =
      e * qDivPow q (c + 1) y - (q⁻¹ ^ c * qInt q 2) • (X * qDivPow q c y) := by
  induction c with
  | zero => simp [A2Integral.qDivPow_one', qDivPow_zero', ye H]
  | succ c ih =>
    have hc : qInt q (c + 1 + 1) ≠ 0 := hqi _ (by omega)
    have hc' : qInt q (c + 1) ≠ 0 := hqi _ (by omega)
    refine smul_right_injective B hc ?_
    simp only
    have h1 : qInt q (c + 1 + 1) • (qDivPow q (c + 1 + 1) y * e) =
        y * (qDivPow q (c + 1) y * e) := by
      rw [← smul_mul_assoc, ← mul_qDivPow q y (c + 1) hc, mul_assoc]
    rw [h1, ih, mul_sub, ← mul_assoc, ye H, mul_smul_comm, ← mul_assoc y X, yX hq0 hqi H]
    simp only [sub_mul, smul_mul_assoc, mul_assoc, mul_qDivPow q y (c + 1) hc,
      mul_qDivPow q y c hc', mul_smul_comm, smul_sub, smul_smul]
    rw [qInt_succ (v := q) (c + 1)]
    match_scalars
    all_goals (try simp only [inv_pow])
    all_goals (try field_simp)
    all_goals (try ring)

include hq0 hpi H in
/-- `f^{(D+1)} e = p^{D+1} e f^{(D+1)} - p y f^{(D)}`. -/
lemma fd_e (D : ℕ) :
    qDivPow (q ^ 2) (D + 1) f * e =
      (q ^ 2) ^ (D + 1) • (e * qDivPow (q ^ 2) (D + 1) f) - q ^ 2 • (y * qDivPow (q ^ 2) D f) := by
  induction D with
  | zero => simp [A2Integral.qDivPow_one', qDivPow_zero', fe H]
  | succ D ih =>
    have hc : qInt (q ^ 2) (D + 1 + 1) ≠ 0 := hpi _ (by omega)
    have hc' : qInt (q ^ 2) (D + 1) ≠ 0 := hpi _ (by omega)
    refine smul_right_injective B hc ?_
    simp only
    rw [← smul_mul_assoc, ← mul_qDivPow (q ^ 2) f (D + 1) hc, mul_assoc, ih, mul_sub,
      mul_smul_comm, mul_smul_comm, ← mul_assoc f e, fe H, ← mul_assoc f y, fy H]
    simp only [sub_mul, smul_mul_assoc, mul_assoc, mul_qDivPow (q ^ 2) f (D + 1) hc,
      mul_qDivPow (q ^ 2) f D hc', mul_smul_comm, smul_sub, smul_smul]
    rw [qInt_succ (v := q ^ 2) (D + 1)]
    match_scalars
    all_goals (try field_simp)
    all_goals (try ring)

include hq0 hqi hpi H in
/-- `f^{(D+1)} X = X f^{(D+1)} - (p - 1) p^{-D} y^{(2)} f^{(D)}`. -/
lemma fd_X (D : ℕ) :
    qDivPow (q ^ 2) (D + 1) f * X = X * qDivPow (q ^ 2) (D + 1) f -
      ((q ^ 2 - 1) * (q ^ 2)⁻¹ ^ D) • (qDivPow q 2 y * qDivPow (q ^ 2) D f) := by
  induction D with
  | zero => simp [A2Integral.qDivPow_one', qDivPow_zero', fX hq0 hqi H]
  | succ D ih =>
    have hc : qInt (q ^ 2) (D + 1 + 1) ≠ 0 := hpi _ (by omega)
    have hc' : qInt (q ^ 2) (D + 1) ≠ 0 := hpi _ (by omega)
    have hfy2 : f * qDivPow q 2 y = (q ^ 2)⁻¹ ^ 2 • (qDivPow q 2 y * f) := by
      simpa [A2Integral.qDivPow_one'] using fd_yd (q := q) H 1 2
    refine smul_right_injective B hc ?_
    simp only
    rw [← smul_mul_assoc, ← mul_qDivPow (q ^ 2) f (D + 1) hc, mul_assoc, ih, mul_sub,
      mul_smul_comm, ← mul_assoc f X, fX hq0 hqi H, ← mul_assoc f, hfy2]
    simp only [sub_mul, smul_mul_assoc, mul_assoc, mul_qDivPow (q ^ 2) f (D + 1) hc,
      mul_qDivPow (q ^ 2) f D hc', mul_smul_comm, smul_sub, smul_smul]
    rw [qInt_succ (v := q ^ 2) (D + 1)]
    match_scalars
    all_goals (try simp only [inv_pow])
    all_goals (try field_simp)
    all_goals (try ring)

end Divided

/-! ### The family `W_{n,s}` and `f^{(s)} e^{(r)}` -/

section FE

variable {q : k}

variable (q) in
/-- The ordered monomial `X^{(b)} y^{(c)} f^{(d)}`. -/
def M3 (X y f : B) (b c d : ℕ) : B :=
  qDivPow (q ^ 2) b X * qDivPow q c y * qDivPow (q ^ 2) d f

lemma M3_congr {q : k} {X y f : B} {b c d b' c' d' : ℕ} (hb : b = b') (hc : c = c')
    (hd : d = d') : M3 q X y f b c d = M3 q X y f b' c' d' := by
  subst hb hc hd; rfl

variable (q) in
/-- A summand of `W_{n,s}`. -/
def Wt (X y f : B) (n s m : ℕ) : B :=
  if n ≤ 2 * m ∧ m ≤ n ∧ m ≤ s then
    q ^ (2 * ((n - m) * (s - m)) + 2 * m) • M3 q X y f (n - m) (2 * m - n) (s - m)
  else 0

variable (q) in
/-- `W_{n,s} = Σ_m q^{2(n-m)(s-m)+2m} X^{(n-m)} y^{(2m-n)} f^{(s-m)}`. -/
def W (X y f : B) (n s : ℕ) : B := ∑ m ∈ range (s + 1), Wt q X y f n s m

variable (hq0 : q ≠ 0) (hqi : ∀ n : ℕ, 0 < n → qInt q n ≠ 0)
  (hpi : ∀ n : ℕ, 0 < n → qInt (q ^ 2) n ≠ 0) {e X y f : B}
  (H : B2PBW.Rel (q ^ 2) e (qInt q 2 • X) y f)

include hq0 hqi hpi H

/-- Right multiplication of `X^{(b)} y^{(c)} f^{(d)}` by `e`. -/
lemma M3_e (b c d : ℕ) :
    M3 q X y f b c d * e = ((q ^ 2) ^ d * (q ^ 2)⁻¹ ^ b) • (e * M3 q X y f b c d) -
      (if c = 0 then 0 else ((q ^ 2) ^ d * q⁻¹ ^ (c - 1) * qInt q 2 * qInt (q ^ 2) (b + 1)) •
        M3 q X y f (b + 1) (c - 1) d) -
      (if d = 0 then 0 else (q ^ 2 * qInt q (c + 1)) • M3 q X y f b (c + 1) (d - 1)) := by
  have hXX : qDivPow (q ^ 2) b X * X = qInt (q ^ 2) (b + 1) • qDivPow (q ^ 2) (b + 1) X :=
    A2Integral.qDivPow_mul_self X b (hpi _ (by omega))
  have hyy : qDivPow q c y * y = qInt q (c + 1) • qDivPow q (c + 1) y :=
    A2Integral.qDivPow_mul_self y c (hqi _ (by omega))
  have hYe : qDivPow q c y * e = e * qDivPow q c y -
      (if c = 0 then 0 else (q⁻¹ ^ (c - 1) * qInt q 2) • (X * qDivPow q (c - 1) y)) := by
    rcases c with _ | c
    · simp [qDivPow_zero']
    · simp only [Nat.add_one_ne_zero, ite_false, Nat.add_sub_cancel]
      exact yd_e hq0 hqi H c
  have hFe : qDivPow (q ^ 2) d f * e = (q ^ 2) ^ d • (e * qDivPow (q ^ 2) d f) -
      (if d = 0 then 0 else q ^ 2 • (y * qDivPow (q ^ 2) (d - 1) f)) := by
    rcases d with _ | d
    · simp [qDivPow_zero']
    · simp only [Nat.add_one_ne_zero, ite_false, Nat.add_sub_cancel]
      exact fd_e hq0 hpi H d
  have hXe := Xd_e hqi H b
  simp only [M3]
  set P := qDivPow (q ^ 2) b X
  set Q := qDivPow q c y
  set F := qDivPow (q ^ 2) d f
  have h1 : P * Q * F * e = (q ^ 2) ^ d • (P * (Q * e) * F) - P * Q *
      (if d = 0 then 0 else q ^ 2 • (y * qDivPow (q ^ 2) (d - 1) f)) := by
    rw [mul_assoc (P * Q) F e, hFe, mul_sub, mul_smul_comm, ← mul_assoc (P * Q) e F,
      mul_assoc P Q e]
  have h2 : P * (Q * e) * F = (q ^ 2)⁻¹ ^ b • (e * (P * Q * F)) - P *
      (if c = 0 then 0 else (q⁻¹ ^ (c - 1) * qInt q 2) • (X * qDivPow q (c - 1) y)) * F := by
    rw [hYe, mul_sub, sub_mul, ← mul_assoc P e Q, hXe, smul_mul_assoc, smul_mul_assoc]
    simp only [mul_assoc]
  have h3 : P * (if c = 0 then 0 else (q⁻¹ ^ (c - 1) * qInt q 2) • (X * qDivPow q (c - 1) y)) *
      F = if c = 0 then 0 else (q⁻¹ ^ (c - 1) * qInt q 2 * qInt (q ^ 2) (b + 1)) •
        (qDivPow (q ^ 2) (b + 1) X * qDivPow q (c - 1) y * F) := by
    split_ifs
    · simp
    · rw [mul_smul_comm, smul_mul_assoc, ← mul_assoc P X, hXX, smul_mul_assoc, smul_mul_assoc,
        smul_smul]
  have h4 : P * Q * (if d = 0 then 0 else q ^ 2 • (y * qDivPow (q ^ 2) (d - 1) f)) =
      if d = 0 then 0 else (q ^ 2 * qInt q (c + 1)) • (P * qDivPow q (c + 1) y *
        qDivPow (q ^ 2) (d - 1) f) := by
    split_ifs
    · simp
    · rw [mul_smul_comm, ← mul_assoc, mul_assoc P Q y, hyy, mul_smul_comm, smul_mul_assoc,
        smul_smul]
  rw [h1, h2, h3, h4]
  split_ifs <;> module

variable (q) in
/-- An auxiliary summand: the first correction term of `W_{n,s} e`. -/
def At (X y f : B) (n s m : ℕ) : B :=
  if n ≤ 2 * m ∧ m ≤ n ∧ m ≤ s ∧ n < 2 * m then
    (q ^ (2 * ((n - m) * (s - m)) + 2 * m) * ((q ^ 2) ^ (s - m) * q⁻¹ ^ (2 * m - n - 1) *
      qInt q 2 * qInt (q ^ 2) (n - m + 1))) • M3 q X y f (n - m + 1) (2 * m - n - 1) (s - m)
  else 0

variable (q) in
/-- An auxiliary summand: the second correction term of `W_{n,s} e`. -/
def Bt (X y f : B) (n s m : ℕ) : B :=
  if n ≤ 2 * m ∧ m ≤ n ∧ m < s then
    (q ^ (2 * ((n - m) * (s - m)) + 2 * m) * (q ^ 2 * qInt q (2 * m - n + 1))) •
      M3 q X y f (n - m) (2 * m - n + 1) (s - m - 1)
  else 0

lemma Wt_e (n s m : ℕ) :
    Wt q X y f n s m * e = (q ^ (2 * s) * q⁻¹ ^ (2 * n)) • (e * Wt q X y f n s m) -
      At q X y f n s m - Bt q X y f n s m := by
  simp only [Wt, At, Bt]
  by_cases hv : n ≤ 2 * m ∧ m ≤ n ∧ m ≤ s
  · rw [ite_eq_left hv, smul_mul_assoc, M3_e hq0 hqi hpi H, mul_smul_comm]
    have hlam : (q ^ 2) ^ (s - m) * (q ^ 2)⁻¹ ^ (n - m) = q ^ (2 * s) * q⁻¹ ^ (2 * n) := by
      obtain ⟨s', rfl⟩ : ∃ s', s = m + s' := ⟨s - m, by omega⟩
      obtain ⟨n', rfl⟩ : ∃ n', n = m + n' := ⟨n - m, by omega⟩
      rw [Nat.add_sub_cancel_left, Nat.add_sub_cancel_left]
      have h1 : q ^ (2 * m) * q⁻¹ ^ (2 * m) = 1 := by
        rw [← mul_pow, mul_inv_cancel₀ hq0, one_pow]
      linear_combination (-(q ^ (2 * s') * q⁻¹ ^ (2 * n'))) * h1
    rw [hlam]
    split_ifs <;> first
      | (exfalso; omega)
      | (simp only [smul_sub, sub_zero, smul_smul]; module)
  · rw [ite_eq_right hv, ite_eq_right (show ¬ (n ≤ 2 * m ∧ m ≤ n ∧ m ≤ s ∧ n < 2 * m) by omega),
      ite_eq_right (show ¬ (n ≤ 2 * m ∧ m ≤ n ∧ m < s) by omega)]
    simp

omit hq0 hqi hpi H in
/-- The coefficient identity behind `W_e`. -/
lemma At_add_Bt (n s m : ℕ) (hm : m < s) :
    At q X y f n s (m + 1) + Bt q X y f n s m = qInt q (n + 1) • Wt q X y f (n + 1) s (m + 1) := by
  simp only [At, Bt, Wt]
  by_cases hA : n ≤ 2 * (m + 1) ∧ m + 1 ≤ n ∧ m + 1 ≤ s ∧ n < 2 * (m + 1)
  · rw [ite_eq_left hA, ite_eq_left (show n + 1 ≤ 2 * (m + 1) ∧ m + 1 ≤ n + 1 ∧ m + 1 ≤ s by omega),
      M3_congr (b := n - (m + 1) + 1) (c := 2 * (m + 1) - n - 1) (d := s - (m + 1))
        (b' := n + 1 - (m + 1)) (c' := 2 * (m + 1) - (n + 1)) (d' := s - (m + 1))
        (by omega) (by omega) rfl]
    by_cases hB : n ≤ 2 * m ∧ m ≤ n ∧ m < s
    · rw [ite_eq_left hB, M3_congr (b := n - m) (c := 2 * m - n + 1) (d := s - m - 1)
        (b' := n + 1 - (m + 1)) (c' := 2 * (m + 1) - (n + 1)) (d' := s - (m + 1))
        (by omega) (by omega) (by omega), ← add_smul, smul_smul]
      congr 1
      obtain ⟨β, γ, D, hn, hm', hs⟩ : ∃ β γ D, n = 2 * β + γ + 2 ∧ m = β + γ + 1 ∧
          s = D + β + γ + 2 := ⟨n - m - 1, 2 * m - n, s - m - 1, by omega, by omega, by omega⟩
      rw [show n - (m + 1) = β by omega, show s - (m + 1) = D by omega,
        show 2 * (m + 1) - n - 1 = γ + 1 by omega, show n - m = β + 1 by omega,
        show s - m = D + 1 by omega, show 2 * m - n + 1 = γ + 1 by omega,
        show n + 1 - (m + 1) = β + 1 by omega, hm', hn,
        show 2 * β + γ + 2 + 1 = 2 * β + 2 + (γ + 1) by ring]
      have key1 := qInt_add (t := q) (2 * β + 2) (γ + 1)
      have key2 := qInt_two_mul (q := q) (β + 1)
      rw [show 2 * (β + 1) = 2 * β + 2 by ring] at key2
      linear_combination (q ^ (2 * (β * D) + 2 * (β + γ + 1 + 1)) * (q ^ 2) ^ D * q⁻¹ ^ (γ + 1)) *
        key2 + q ^ (2 * ((β + 1) * D) + 2 * (β + γ + 1 + 1)) * key1
    · rw [ite_eq_right hB, add_zero, smul_smul]
      congr 1
      obtain ⟨D, hn, hs⟩ : ∃ D, n = 2 * m + 1 ∧ s = D + m + 1 := ⟨s - m - 1, by omega, by omega⟩
      rw [show n - (m + 1) = m by omega, show s - (m + 1) = D by omega,
        show 2 * (m + 1) - n - 1 = 0 by omega, show n + 1 - (m + 1) = m + 1 by omega, hn,
        show 2 * m + 1 + 1 = 2 * (m + 1) by ring, ← qInt_two_mul (q := q) (m + 1)]
      ring
  · by_cases hB : n ≤ 2 * m ∧ m ≤ n ∧ m < s
    · rw [ite_eq_right hA, ite_eq_left hB, ite_eq_left (show n + 1 ≤ 2 * (m + 1) ∧ m + 1 ≤ n + 1 ∧ m + 1 ≤ s by
        omega), zero_add, M3_congr (b := n - m) (c := 2 * m - n + 1) (d := s - m - 1)
        (b' := n + 1 - (m + 1)) (c' := 2 * (m + 1) - (n + 1)) (d' := s - (m + 1))
        (by omega) (by omega) (by omega), smul_smul]
      congr 1
      obtain ⟨D, hn, hs⟩ : ∃ D, n = m ∧ s = D + m + 1 := ⟨s - m - 1, by omega, by omega⟩
      rw [show n - m = 0 by omega, show 2 * m - n + 1 = m + 1 by omega,
        show n + 1 - (m + 1) = 0 by omega, hn]
      ring
    · rw [ite_eq_right hA, ite_eq_right hB,
        ite_eq_right (show ¬ (n + 1 ≤ 2 * (m + 1) ∧ m + 1 ≤ n + 1 ∧ m + 1 ≤ s) by omega)]
      simp

/-- `W_{n,s} e = q^{2s-2n} e W_{n,s} - [n+1] W_{n+1,s}`. -/
lemma W_e (n s : ℕ) :
    W q X y f n s * e = (q ^ (2 * s) * q⁻¹ ^ (2 * n)) • (e * W q X y f n s) -
      qInt q (n + 1) • W q X y f (n + 1) s := by
  have hsum : ∑ m ∈ range (s + 1), (At q X y f n s m + Bt q X y f n s m) =
      qInt q (n + 1) • W q X y f (n + 1) s := by
    have hA0 : At q X y f n s 0 = 0 := by simp [At]
    have hBs : Bt q X y f n s s = 0 := by simp [Bt]
    have hW0 : Wt q X y f (n + 1) s 0 = 0 := by simp [Wt]
    rw [sum_add_distrib, W, smul_sum, sum_range_succ' (At q X y f n s), sum_range_succ (Bt q X y f n s),
      sum_range_succ' (fun m ↦ qInt q (n + 1) • Wt q X y f (n + 1) s m), hA0, hBs, hW0, smul_zero,
      add_zero, add_zero, add_zero, ← sum_add_distrib]
    exact sum_congr rfl fun m hm ↦ At_add_Bt n s m (mem_range.1 hm)
  rw [W, sum_mul, sum_congr rfl fun m _ ↦ Wt_e hq0 hqi hpi H n s m, sum_sub_distrib,
    sum_sub_distrib, ← smul_sum, ← mul_sum, sub_sub, ← sum_add_distrib, hsum]

omit hq0 hqi hpi H in
lemma W_zero (s : ℕ) : W q X y f 0 s = qDivPow (q ^ 2) s f := by
  rw [W, sum_range_succ', sum_eq_zero fun m _ ↦ by simp [Wt]]
  simp [Wt, M3, qDivPow_zero']

/-- **Integral `B₂` straightening, first form.**
`f^{(s)} e^{(r)} = Σ_n (-1)ⁿ q^{(r-n)(2s-n)} e^{(r-n)} W_{n,s}`. -/
theorem qDivPow_f_mul_qDivPow_e (s r : ℕ) :
    qDivPow (q ^ 2) s f * qDivPow q r e =
      ∑ n ∈ range (r + 1), sCoef q (2 * s) r n • (qDivPow q (r - n) e * W q X y f n s) := by
  rw [← W_zero (q := q) (X := X) (y := y) s]
  exact straighten hq0 hqi (2 * s) (W := fun n ↦ W q X y f n s)
    (fun n ↦ W_e hq0 hqi hpi H n s) r

end FE

/-! ### `f^{(s)} X^{(r)}` -/

section FX

variable {q : k}

variable (q) in
/-- The Laurent coefficients `ν_n = Π_{j<n} (q² - 1) q^{-2(s-1-j)} [2j+1]`. -/
def nu (s n : ℕ) : k :=
  ∏ j ∈ range n, ((q ^ 2 - 1) * (q ^ 2)⁻¹ ^ (s - 1 - j) * qInt q (2 * j + 1))

variable (q) in
/-- `V_{s,n} = ν_n y^{(2n)} f^{(s-n)}` (zero for `n > s`). -/
def V (y f : B) (s n : ℕ) : B :=
  if n ≤ s then nu q s n • (qDivPow q (2 * n) y * qDivPow (q ^ 2) (s - n) f) else 0

variable (hq0 : q ≠ 0) (hqi : ∀ n : ℕ, 0 < n → qInt q n ≠ 0)
  (hpi : ∀ n : ℕ, 0 < n → qInt (q ^ 2) n ≠ 0) {e X y f : B}
  (H : B2PBW.Rel (q ^ 2) e (qInt q 2 • X) y f)

include hq0 hqi hpi H

lemma V_X (s n : ℕ) :
    V q y f s n * X = ((q ^ 2) ^ 0 * (q ^ 2)⁻¹ ^ (2 * n)) • (X * V q y f s n) -
      qInt (q ^ 2) (n + 1) • V q y f s (n + 1) := by
  have hyX (c : ℕ) : qDivPow q c y * X = (q ^ 2)⁻¹ ^ c • (X * qDivPow q c y) := by
    simpa [A2Integral.qDivPow_one'] using yd_Xd hq0 hqi H c 1
  have hF := A2Integral.qFactorial_ne_zero_of_qInt hqi
  rcases lt_trichotomy n s with h | rfl | h
  · obtain ⟨D, hD⟩ : ∃ D, s - n = D + 1 := ⟨s - n - 1, by omega⟩
    simp only [V, ite_eq_left h.le, ite_eq_left (show n + 1 ≤ s by omega), hD,
      show s - (n + 1) = D by omega]
    rw [smul_mul_assoc, mul_assoc, fd_X hq0 hqi hpi H D, mul_sub, ← mul_assoc, hyX,
      mul_smul_comm, ← mul_assoc (qDivPow q (2 * n) y), A2Integral.qDivPow_mul_qDivPow y _ _
        (hF _), qBinomial_two_add (hqi 2 (by norm_num)) hF,
      show 2 * (n + 1) = 2 * n + 2 by ring]
    simp only [nu, prod_range_succ, show s - 1 - n = D by omega, smul_mul_assoc, mul_smul_comm,
      mul_assoc]
    module
  · simp only [V, le_refl, ite_true, Nat.sub_self, qDivPow_zero', mul_one,
      show ¬ n + 1 ≤ n by omega, ite_false, smul_zero, sub_zero, pow_zero, one_mul]
    rw [smul_mul_assoc, hyX, mul_smul_comm, smul_smul, smul_smul, mul_comm]
  · simp [V, show ¬ n ≤ s by omega, show ¬ n + 1 ≤ s by omega]

omit hq0 hqi hpi H in
lemma V_zero (s : ℕ) : V q y f s 0 = qDivPow (q ^ 2) s f := by
  simp [V, nu, qDivPow_zero']

/-- **Integral `B₂` straightening, second form.**
`f^{(s)} X^{(r)} = Σ_n (-1)ⁿ p^{-n(r-n)} ν_n X^{(r-n)} y^{(2n)} f^{(s-n)}`. -/
theorem qDivPow_f_mul_qDivPow_X (s r : ℕ) :
    qDivPow (q ^ 2) s f * qDivPow (q ^ 2) r X =
      ∑ n ∈ range (r + 1), sCoef (q ^ 2) 0 r n • (qDivPow (q ^ 2) (r - n) X * V q y f s n) := by
  rw [← V_zero (q := q) (y := y) s]
  exact straighten (pow_ne_zero 2 hq0) hpi 0 (W := fun n ↦ V q y f s n)
    (fun n ↦ V_X hq0 hqi hpi H s n) r

end FX

/-! ### The ordered `Λ`-span -/

section Span

variable {q : k}

variable (q) in
/-- The ordered monomial `e^{(a)} X^{(b)} y^{(c)} f^{(d)}`. -/
def M4 (e X y f : B) (a b c d : ℕ) : B := qDivPow q a e * M3 q X y f b c d

variable (q) in
/-- The `Λ`-combinations of the ordered monomials `e^{(a)} X^{(b)} y^{(c)} f^{(d)}`. -/
def orderedSpan (Λ : Subring k) (e X y f : B) : AddSubgroup B :=
  AddSubgroup.closure {w | ∃ c ∈ Λ, ∃ a b c' d : ℕ, w = c • M4 q e X y f a b c' d}

variable {Λ : Subring k} {e X y f : B}

lemma smul_mem_orderedSpan {c : k} (hc : c ∈ Λ) {x : B} (hx : x ∈ orderedSpan q Λ e X y f) :
    c • x ∈ orderedSpan q Λ e X y f := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨c', hc', a, b, c'', d, rfl⟩ := hx
    exact AddSubgroup.subset_closure ⟨c * c', mul_mem hc hc', a, b, c'', d, by rw [smul_smul]⟩
  | zero => rw [smul_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [smul_add]; exact add_mem hx hy
  | neg x _ hx => rw [smul_neg]; exact neg_mem hx

lemma M4_mem_orderedSpan (a b c d : ℕ) : M4 q e X y f a b c d ∈ orderedSpan q Λ e X y f :=
  AddSubgroup.subset_closure ⟨1, one_mem _, a, b, c, d, by rw [one_smul]⟩

lemma one_mem_orderedSpan : (1 : B) ∈ orderedSpan q Λ e X y f := by
  simpa [M4, M3, qDivPow_zero'] using M4_mem_orderedSpan (q := q) (Λ := Λ) (e := e) (X := X)
    (y := y) (f := f) 0 0 0 0

lemma mul_mem_orderedSpan_of_gen {z : B}
    (hz : ∀ a b c d, z * M4 q e X y f a b c d ∈ orderedSpan q Λ e X y f) {x : B}
    (hx : x ∈ orderedSpan q Λ e X y f) : z * x ∈ orderedSpan q Λ e X y f := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨c, hc, a, b, c', d, rfl⟩ := hx
    rw [mul_smul_comm]; exact smul_mem_orderedSpan hc (hz a b c' d)
  | zero => rw [mul_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [mul_add]; exact add_mem hx hy
  | neg x _ hx => rw [mul_neg]; exact neg_mem hx

lemma qInt_mem {t : k} (ht : t ∈ Λ) (ht' : t⁻¹ ∈ Λ) (n : ℕ) : qInt t n ∈ Λ :=
  sum_mem fun _ _ ↦ mul_mem (pow_mem ht _) (pow_mem ht' _)

lemma sCoef_mem {t : k} (ht : t ∈ Λ) (ht' : t⁻¹ ∈ Λ) (N r n : ℕ) : sCoef t N r n ∈ Λ :=
  mul_mem (mul_mem (pow_mem (neg_mem (one_mem _)) _) (pow_mem ht _)) (pow_mem ht' _)

lemma nu_mem (hqΛ : q ∈ Λ) (hqΛ' : q⁻¹ ∈ Λ) (s n : ℕ) : nu q s n ∈ Λ := by
  have hp : q ^ 2 ∈ Λ := pow_mem hqΛ 2
  have hp' : (q ^ 2)⁻¹ ∈ Λ := by rw [← inv_pow]; exact pow_mem hqΛ' 2
  exact prod_mem fun j _ ↦ mul_mem (mul_mem (sub_mem hp (one_mem _)) (pow_mem hp' _))
    (qInt_mem hqΛ hqΛ' _)

variable (hq0 : q ≠ 0) (hqi : ∀ n : ℕ, 0 < n → qInt q n ≠ 0)
  (hpi : ∀ n : ℕ, 0 < n → qInt (q ^ 2) n ≠ 0)
  (H : B2PBW.Rel (q ^ 2) e (qInt q 2 • X) y f) (hqΛ : q ∈ Λ) (hqΛ' : q⁻¹ ∈ Λ)

include hqi hqΛ hqΛ' in
/-- The ordered span is stable under left multiplication by `e^{(n)}`. -/
theorem qDivPow_e_mul_mem (n : ℕ) {x : B} (hx : x ∈ orderedSpan q Λ e X y f) :
    qDivPow q n e * x ∈ orderedSpan q Λ e X y f := by
  refine mul_mem_orderedSpan_of_gen (fun a b c d ↦ ?_) hx
  rw [M4, ← mul_assoc, A2Integral.qDivPow_mul_qDivPow e n a
    (A2Integral.qFactorial_ne_zero_of_qInt hqi _), smul_mul_assoc]
  exact smul_mem_orderedSpan (A2Integral.qBinomial_mem hqΛ hqΛ' _ _) (M4_mem_orderedSpan _ _ _ _)

include hq0 hqi hpi H hqΛ hqΛ' in
/-- A product `e^{(a)} X^{(b')} y^{(c')} f^{(d')} · X^{(b)} y^{(c)} f^{(d)}` lies in the ordered
span. -/
lemma M4_mul_M3_mem (a b' c' d' b c d : ℕ) :
    M4 q e X y f a b' c' d' * M3 q X y f b c d ∈ orderedSpan q Λ e X y f := by
  have hp : q ^ 2 ∈ Λ := pow_mem hqΛ 2
  have hp' : (q ^ 2)⁻¹ ∈ Λ := by rw [← inv_pow]; exact pow_mem hqΛ' 2
  have hFq := A2Integral.qFactorial_ne_zero_of_qInt hqi
  have hFp := A2Integral.qFactorial_ne_zero_of_qInt hpi
  have e1 : M4 q e X y f a b' c' d' * M3 q X y f b c d =
      qDivPow q a e * (qDivPow (q ^ 2) b' X * (qDivPow q c' y *
        ((qDivPow (q ^ 2) d' f * qDivPow (q ^ 2) b X) * (qDivPow q c y *
          qDivPow (q ^ 2) d f)))) := by
    simp only [M4, M3, mul_assoc]
  rw [e1, qDivPow_f_mul_qDivPow_X hq0 hqi hpi H, sum_mul, mul_sum, mul_sum, mul_sum]
  refine AddSubgroup.sum_mem _ fun n _ ↦ ?_
  simp only [V]
  split_ifs with hn
  · have hYX : ∀ z, qDivPow q c' y * (qDivPow (q ^ 2) (b - n) X * z) =
        (q ^ 2)⁻¹ ^ (c' * (b - n)) • (qDivPow (q ^ 2) (b - n) X * (qDivPow q c' y * z)) := by
      intro z; rw [← mul_assoc, yd_Xd hq0 hqi H, smul_mul_assoc, mul_assoc]
    have hFY : qDivPow (q ^ 2) (d' - n) f * (qDivPow q c y * qDivPow (q ^ 2) d f) =
        (q ^ 2)⁻¹ ^ ((d' - n) * c) • (qDivPow q c y * (qDivPow (q ^ 2) (d' - n) f *
          qDivPow (q ^ 2) d f)) := by
      rw [← mul_assoc, fd_yd H, smul_mul_assoc, mul_assoc]
    have hXX : ∀ z, qDivPow (q ^ 2) b' X * (qDivPow (q ^ 2) (b - n) X * z) =
        qBinomial (q ^ 2) (b' + (b - n)) b' • (qDivPow (q ^ 2) (b' + (b - n)) X * z) := by
      intro z; rw [← mul_assoc, A2Integral.qDivPow_mul_qDivPow X _ _ (hFp _), smul_mul_assoc]
    have hYY : ∀ z, qDivPow q c' y * (qDivPow q (2 * n) y * (qDivPow q c y * z)) =
        (qBinomial q (c' + 2 * n) c' * qBinomial q (c' + 2 * n + c) (c' + 2 * n)) •
          (qDivPow q (c' + 2 * n + c) y * z) := by
      intro z
      rw [← mul_assoc, A2Integral.qDivPow_mul_qDivPow y _ _ (hFq _), smul_mul_assoc,
        ← mul_assoc, A2Integral.qDivPow_mul_qDivPow y _ _ (hFq _), smul_mul_assoc, smul_smul]
    have hFF : qDivPow (q ^ 2) (d' - n) f * qDivPow (q ^ 2) d f =
        qBinomial (q ^ 2) (d' - n + d) (d' - n) • qDivPow (q ^ 2) (d' - n + d) f :=
      A2Integral.qDivPow_mul_qDivPow f _ _ (hFp _)
    simp only [smul_mul_assoc, mul_smul_comm, mul_assoc]
    rw [hYX, hFY]
    simp only [mul_smul_comm]
    rw [hXX, hYY, hFF]
    simp only [mul_smul_comm, smul_smul]
    refine smul_mem_orderedSpan ?_ ?_
    · repeat' (first
        | exact sCoef_mem hp hp' _ _ _
        | exact nu_mem hqΛ hqΛ' _ _
        | exact A2Integral.qBinomial_mem hqΛ hqΛ' _ _
        | exact A2Integral.qBinomial_mem hp hp' _ _
        | exact pow_mem hp' _
        | apply mul_mem)
    · simpa only [M4, M3, mul_assoc] using M4_mem_orderedSpan (q := q) (Λ := Λ) (e := e) (X := X)
        (y := y) (f := f) a (b' + (b - n)) (c' + 2 * n + c) (d' - n + d)
  · simp only [smul_zero, mul_zero, zero_mul]
    exact zero_mem _

include hq0 hqi hpi H hqΛ hqΛ' in
/-- **Stability under `f^{(s)}`.** The ordered span is stable under left multiplication by the
divided powers of `f`. -/
theorem qDivPow_f_mul_mem (s : ℕ) {x : B} (hx : x ∈ orderedSpan q Λ e X y f) :
    qDivPow (q ^ 2) s f * x ∈ orderedSpan q Λ e X y f := by
  refine mul_mem_orderedSpan_of_gen (fun a b c d ↦ ?_) hx
  rw [M4, ← mul_assoc, qDivPow_f_mul_qDivPow_e hq0 hqi hpi H, sum_mul]
  refine AddSubgroup.sum_mem _ fun n _ ↦ ?_
  rw [W, mul_sum, smul_sum, sum_mul]
  refine AddSubgroup.sum_mem _ fun m _ ↦ ?_
  simp only [Wt]
  split_ifs
  · rw [mul_smul_comm, smul_smul, smul_mul_assoc]
    refine smul_mem_orderedSpan (mul_mem (sCoef_mem hqΛ hqΛ' _ _ _) (pow_mem hqΛ _)) ?_
    exact M4_mul_M3_mem hq0 hqi hpi H hqΛ hqΛ' _ _ _ _ _ _ _
  · simp only [mul_zero, smul_zero, zero_mul]
    exact zero_mem _

end Span

/-! ### The root vectors lie in the integral subring -/

section Generate

variable {q : k} {Λ : Subring k} {e X y f : B}
  (hq0 : q ≠ 0) (hqi : ∀ n : ℕ, 0 < n → qInt q n ≠ 0)
  (hpi : ∀ n : ℕ, 0 < n → qInt (q ^ 2) n ≠ 0)
  (H : B2PBW.Rel (q ^ 2) e (qInt q 2 • X) y f) (hqΛ : q ∈ Λ) (hqΛ' : q⁻¹ ∈ Λ)
  {T : Subring B} (hΛT : ∀ c ∈ Λ, algebraMap k B c ∈ T) (heT : ∀ a, qDivPow q a e ∈ T)
  (hfT : ∀ d, qDivPow (q ^ 2) d f ∈ T)

include hΛT in
lemma smul_mem_T {c : k} (hc : c ∈ Λ) {x : B} (hx : x ∈ T) : c • x ∈ T := by
  rw [Algebra.smul_def]; exact mul_mem (hΛT c hc) hx

include hqΛ hqΛ' hΛT heT hfT in
/-- Every summand of `f^{(s)} e^{(r)}` other than a prescribed one lies in `T`, provided the
divided powers of `X` and `y` occurring in it do. -/
lemma summand_mem {r s n m : ℕ}
    (hX : n ≤ 2 * m ∧ m ≤ n ∧ m ≤ s → qDivPow (q ^ 2) (n - m) X ∈ T)
    (hY : n ≤ 2 * m ∧ m ≤ n ∧ m ≤ s → qDivPow q (2 * m - n) y ∈ T) :
    sCoef q (2 * s) r n • (qDivPow q (r - n) e * Wt q X y f n s m) ∈ T := by
  refine smul_mem_T hΛT (sCoef_mem hqΛ hqΛ' _ _ _) ?_
  simp only [Wt]
  split_ifs with hv
  · rw [mul_smul_comm]
    refine smul_mem_T hΛT (pow_mem hqΛ _) (mul_mem (heT _) ?_)
    exact mul_mem (mul_mem (hX hv) (hY hv)) (hfT _)
  · rw [mul_zero]; exact zero_mem _

include hq0 hqi hpi H hqΛ hqΛ' hΛT heT hfT in
/-- **Integrality of the root vectors.** All divided powers `X^{(n)}`, `y^{(n)}` lie in any
subring containing `Λ`, the `e^{(a)}` and the `f^{(d)}`. -/
theorem qDivPow_X_mem_and_qDivPow_y_mem (N : ℕ) :
    ∀ b ≤ N, qDivPow (q ^ 2) b X ∈ T ∧ qDivPow q b y ∈ T := by
  induction N with
  | zero =>
    intro b hb
    obtain rfl : b = 0 := by omega
    simp only [qDivPow_zero']
    exact ⟨one_mem _, one_mem _⟩
  | succ N ih =>
    -- `y^{(N+1)}`, from `f^{(N+1)} e^{(N+1)}`
    have hy : qDivPow q (N + 1) y ∈ T := by
      have hFE := mul_mem (hfT (N + 1)) (heT (N + 1))
      rw [qDivPow_f_mul_qDivPow_e hq0 hqi hpi H, sum_range_succ, W, mul_sum, smul_sum,
        sum_range_succ (fun m ↦ sCoef q (2 * (N + 1)) (N + 1) (N + 1) •
          (qDivPow q (N + 1 - (N + 1)) e * Wt q X y f (N + 1) (N + 1) m)) (N + 1)] at hFE
      have hrest : ∑ n ∈ range (N + 1), sCoef q (2 * (N + 1)) (N + 1) n •
            (qDivPow q (N + 1 - n) e * W q X y f n (N + 1)) +
          ∑ m ∈ range (N + 1), sCoef q (2 * (N + 1)) (N + 1) (N + 1) •
            (qDivPow q (N + 1 - (N + 1)) e * Wt q X y f (N + 1) (N + 1) m) ∈ T := by
        refine add_mem (sum_mem fun n hn ↦ ?_) (sum_mem fun m hm ↦ ?_)
        · have hn := mem_range.1 hn
          rw [W, mul_sum, smul_sum]
          refine sum_mem fun m _ ↦ summand_mem hqΛ hqΛ' hΛT heT hfT ?_ ?_
          · intro hv; exact (ih _ (by omega)).1
          · intro hv; exact (ih _ (by omega)).2
        · have hm := mem_range.1 hm
          refine summand_mem hqΛ hqΛ' hΛT heT hfT ?_ ?_
          · intro hv; exact (ih _ (by omega)).1
          · intro hv; exact (ih _ (by omega)).2
      have hlast : sCoef q (2 * (N + 1)) (N + 1) (N + 1) • (qDivPow q (N + 1 - (N + 1)) e *
          Wt q X y f (N + 1) (N + 1) (N + 1)) =
          ((-1) ^ (N + 1) * q ^ (2 * (N + 1))) • qDivPow q (N + 1) y := by
        simp [sCoef, Wt, M3, qDivPow_zero', smul_smul, show 2 * (N + 1) - (N + 1) = N + 1 by omega]
      rw [← add_assoc, hlast] at hFE
      have h2 := sub_mem hFE hrest
      rw [add_sub_cancel_left] at h2
      have hu : ((-1) ^ (N + 1) * q ^ (2 * (N + 1)))⁻¹ ∈ Λ := by
        rw [mul_inv, ← inv_pow, ← inv_pow]
        exact mul_mem (pow_mem (by simp) _) (pow_mem hqΛ' _)
      have := smul_mem_T hΛT hu h2
      rwa [smul_smul, inv_mul_cancel₀ (mul_ne_zero (pow_ne_zero _ (by norm_num))
        (pow_ne_zero _ hq0)), one_smul] at this
    -- `X^{(N+1)}`, from `f^{(N+1)} e^{(2N+2)}`
    have hX : qDivPow (q ^ 2) (N + 1) X ∈ T := by
      have hFE := mul_mem (hfT (N + 1)) (heT (2 * N + 2))
      rw [qDivPow_f_mul_qDivPow_e hq0 hqi hpi H, sum_range_succ, W, mul_sum, smul_sum,
        sum_range_succ (fun m ↦ sCoef q (2 * (N + 1)) (2 * N + 2) (2 * N + 2) •
          (qDivPow q (2 * N + 2 - (2 * N + 2)) e * Wt q X y f (2 * N + 2) (N + 1) m)) (N + 1)] at hFE
      have hrest : ∑ n ∈ range (2 * N + 2), sCoef q (2 * (N + 1)) (2 * N + 2) n •
            (qDivPow q (2 * N + 2 - n) e * W q X y f n (N + 1)) +
          ∑ m ∈ range (N + 1), sCoef q (2 * (N + 1)) (2 * N + 2) (2 * N + 2) •
            (qDivPow q (2 * N + 2 - (2 * N + 2)) e * Wt q X y f (2 * N + 2) (N + 1) m) ∈ T := by
        refine add_mem (sum_mem fun n hn ↦ ?_) (sum_mem fun m hm ↦ ?_)
        · have hn := mem_range.1 hn
          rw [W, mul_sum, smul_sum]
          refine sum_mem fun m _ ↦ summand_mem hqΛ hqΛ' hΛT heT hfT ?_ ?_
          · intro hv; exact (ih _ (by omega)).1
          · intro hv
            rcases Nat.lt_or_ge (2 * m - n) (N + 1) with h | h
            · exact (ih _ (by omega)).2
            · rw [show 2 * m - n = N + 1 by omega]; exact hy
        · have hm := mem_range.1 hm
          refine summand_mem hqΛ hqΛ' hΛT heT hfT ?_ ?_
          · intro hv; exact (ih _ (by omega)).1
          · intro hv; exact (ih _ (by omega)).2
      have hlast : sCoef q (2 * (N + 1)) (2 * N + 2) (2 * N + 2) •
          (qDivPow q (2 * N + 2 - (2 * N + 2)) e * Wt q X y f (2 * N + 2) (N + 1) (N + 1)) =
          q ^ (2 * (N + 1)) • qDivPow (q ^ 2) (N + 1) X := by
        have h1 : 2 * N + 2 - (N + 1) = N + 1 := by omega
        have h2 : 2 * (N + 1) - (2 * N + 2) = 0 := by omega
        have hm1 : (-1 : k) ^ (2 * N + 2) = 1 := by
          rw [show 2 * N + 2 = 2 * (N + 1) by ring, pow_mul]; simp
        simp [sCoef, Wt, M3, qDivPow_zero', h1, h2, hm1, show 2 * N + 2 ≤ 2 * (N + 1) by omega]
        intro h; omega
      rw [← add_assoc, hlast] at hFE
      have h2 := sub_mem hFE hrest
      rw [add_sub_cancel_left] at h2
      have := smul_mem_T hΛT (pow_mem hqΛ' (2 * (N + 1))) h2
      rwa [smul_smul, ← mul_pow, inv_mul_cancel₀ hq0, one_pow, one_smul] at this
    intro b hb
    rcases Nat.lt_or_ge b (N + 1) with h | h
    · exact ih b (by omega)
    · obtain rfl : b = N + 1 := by omega
      exact ⟨hX, hy⟩

end Generate



end B2Integral

end LieLean.QuantumGroup
