/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.PBW.IntegralG2CommutingAB

/-!
# G₂ commutation certificate for BC

The adjacent normalized root vectors q-commute. The three internal pairs are proved by
polynomial identities in the two-sided ideal generated by the quantum Serre relations.
The scalar nonvanishing assumptions used to cancel these identities hold at every parameter
which is not a root of unity; their necessity at special parameters is not asserted.
-/

open Finset

noncomputable section

namespace LieLean.QuantumGroup.G2Integral

variable {k B : Type*} [Field k] [Ring B] [Algebra k B]
  {q : k} {e f : B}

set_option maxHeartbeats 4000000 in
-- Normalizing the expanded two-sided Serre certificate requires this larger budget.
lemma z_mul_x2_raw (hq : q ≠ 0)
    (h6 : (1 + (q ^ 4) + (-1 * (q ^ 2))) ≠ 0)
    (h4 : (1 + (q ^ 4)) ≠ 0)
    (hS4 : qSerre q 4 e f = 0) (hS2 : qSerre (q ^ 3) 2 f e = 0) :
    G2PBW.z q e f * G2PBW.x2 q e f =
      (q ^ 3)⁻¹ • (G2PBW.x2 q e f * G2PBW.z q e f) := by
  have hd : ((q ^ 11) * (1 + (q ^ 4)) * (1 + (q ^ 4) + (-1 * (q ^ 2)))) ≠ 0 := by
    aesop
  have key : ((q ^ 11) * (1 + (q ^ 4)) * (1 + (q ^ 4) + (-1 * (q ^ 2)))) •
      (G2PBW.z q e f * G2PBW.x2 q e f - (q ^ 3)⁻¹ • (G2PBW.x2 q e f * G2PBW.z q e f)) =
      (((-1 * q) + (-1 * (q ^ 9)) + (-2 * (q ^ 5)))) • ((f * e) * ((qSerre (q ^ 3) 2 f e) * (e * e
        * e))) +
      ((q + (q ^ 5) + (q ^ 9))) • ((f * e * f) * (qSerre q 4 e f)) +
      ((q ^ 5)) • ((f) * ((qSerre (q ^ 3) 2 f e) * (e * e * e * e))) +
      ((-1 * (q ^ 5))) • ((f * f) * ((qSerre q 4 e f) * (e))) +
      (((-1 * (q ^ 4)) + (-1 * (q ^ 6)))) • ((f * f * e) * (qSerre q 4 e f)) +
      (((-1 * (q ^ 3)) + (-1 * (q ^ 7)))) • ((qSerre (q ^ 3) 2 f e) * (e * f * e * e * e)) +
      ((1 + (q ^ 2) + (q ^ 8) + (q ^ 10) + (2 * (q ^ 4)) + (2 * (q ^ 6)))) • ((qSerre (q ^ 3) 2 f
        e) * (e * e * f * e * e)) +
      ((q + (q ^ 11) + (-1 * (q ^ 3)) + (2 * (q ^ 5)))) • ((f) * ((qSerre q 4 e f) * (f * e))) +
      (((q ^ 6) + (-1 * (q ^ 4)) + (-1 * (q ^ 8)))) • ((f) * ((qSerre q 4 e f) * (e * f))) +
      (((-1 * (q ^ 3)) + (-1 * (q ^ 9)) + (-1 * (q ^ 11)) + (-3 * (q ^ 5)) + (-2 * q) + (-2 * (q ^
        7)))) • ((qSerre (q ^ 3) 2 f e) * (e * e * e * f * e)) +
      (((q ^ 9) + (q ^ 13) + (-1 * (q ^ 11)))) • ((f * e) * ((qSerre q 4 e f) * (f))) +
      ((q + (q ^ 9) + (2 * (q ^ 5)))) • ((f * e * e) * ((qSerre (q ^ 3) 2 f e) * (e * e))) +
      (((q ^ 8) + (2 * (q ^ 4)))) • ((qSerre (q ^ 3) 2 f e) * (e * e * e * e * f)) +
      (((q ^ 9) + (q ^ 13))) • ((f * e * e * e) * ((qSerre (q ^ 3) 2 f e) * (e))) +
      (((-1 * (q ^ 7)) + (-1 * (q ^ 11)) + (-1 * (q ^ 13)))) • ((qSerre q 4 e f) * (f * f * e)) +
      (((q ^ 6) + (q ^ 16) + (-1 * (q ^ 8)) + (2 * (q ^ 10)))) • ((qSerre q 4 e f) * (f * e * f))
        +
      (((q ^ 11) + (-1 * (q ^ 9)) + (-1 * (q ^ 13)))) • ((qSerre q 4 e f) * (e * f * f)) +
      (((q ^ 7) + (q ^ 11))) • ((e) * ((qSerre (q ^ 3) 2 f e) * (f * e * e * e))) +
      (((-1 * (q ^ 2)) + (-1 * (q ^ 4)) + (-1 * (q ^ 12)) + (-1 * (q ^ 14)) + (-2 * (q ^ 6)) + (-2
        * (q ^ 8)) + (-2 * (q ^ 10)))) • ((e) * ((qSerre (q ^ 3) 2 f e) * (e * f * e * e))) +
      ((q + (q ^ 3) + (q ^ 13) + (q ^ 15) + (2 * (q ^ 7)) + (2 * (q ^ 11)) + (3 * (q ^ 5)) + (3 *
        (q ^ 9)))) • ((e) * ((qSerre (q ^ 3) 2 f e) * (e * e * f * e))) +
      (((q ^ 14) + (-1 * (q ^ 6)) + (-1 * (q ^ 16)) + (-2 * (q ^ 12)))) • ((e * f) * ((qSerre q 4
        e f) * (f))) +
      (((q ^ 4) + (q ^ 8) + (-1 * (q ^ 6)) + (-1 * (q ^ 10)))) • ((e * f) * ((qSerre (q ^ 3) 2 f
        e) * (e * e * e))) +
      (((q ^ 6) + (q ^ 10) + (-1 * (q ^ 4)) + (-1 * (q ^ 8)))) • ((e * f * f) * (qSerre q 4 e f))
        +
      (((q ^ 6) + (q ^ 14) + (2 * (q ^ 10)))) • ((e * f * e) * ((qSerre (q ^ 3) 2 f e) * (e * e)))
        +
      (((-1 * (q ^ 4)) + (-1 * (q ^ 8)))) • ((e) * ((qSerre (q ^ 3) 2 f e) * (e * e * e * f))) +
      (((-1 * (q ^ 2)) + (-1 * (q ^ 4)) + (-1 * (q ^ 14)) + (-1 * (q ^ 16)) + (-3 * (q ^ 8)) + (-3
        * (q ^ 12)) + (-2 * (q ^ 6)) + (-2 * (q ^ 10)))) • ((e * f * e * e) * ((qSerre (q ^ 3) 2 f
        e) * (e))) +
      (((-1 * (q ^ 10)) + (-1 * (q ^ 14)))) • ((e * f * e * e * e) * (qSerre (q ^ 3) 2 f e)) +
      ((q ^ 12)) • ((e) * ((qSerre q 4 e f) * (f * f))) +
      (((-1 * (q ^ 7)) + (-1 * (q ^ 11)))) • ((e * e * f) * ((qSerre (q ^ 3) 2 f e) * (e * e))) +
      (((q ^ 6) + (q ^ 10))) • ((e * e) * ((qSerre (q ^ 3) 2 f e) * (f * e * e))) +
      (((-1 * (q ^ 3)) + (-1 * (q ^ 11)) + (-2 * (q ^ 7)))) • ((e * e) * ((qSerre (q ^ 3) 2 f e) *
        (e * f * e))) +
      (((-1 * (q ^ 8)) + (-1 * (q ^ 16)) + (-2 * (q ^ 12)))) • ((e * e) * ((qSerre (q ^ 3) 2 f e)
        * (e * e * f))) +
      (((q ^ 3) + (q ^ 5) + (q ^ 13) + (q ^ 15) + (2 * (q ^ 7)) + (2 * (q ^ 9)) + (2 * (q ^ 11))))
        • ((e * e * f * e) * ((qSerre (q ^ 3) 2 f e) * (e))) +
      (((q ^ 5) + (q ^ 11) + (q ^ 15) + (q ^ 17) + (3 * (q ^ 9)) + (3 * (q ^ 13)))) • ((e * e * f
        * e * e) * (qSerre (q ^ 3) 2 f e)) +
      (((-1 * (q ^ 6)) + (-1 * (q ^ 10)))) • ((e * e * e * f) * ((qSerre (q ^ 3) 2 f e) * (e))) +
      (((q ^ 7) + (q ^ 11) + (-1 * (q ^ 9)) + (-1 * (q ^ 13)))) • ((e * e * e) * ((qSerre (q ^ 3)
        2 f e) * (f * e))) +
      (((q ^ 8) + (q ^ 16) + (2 * (q ^ 12)))) • ((e * e * e) * ((qSerre (q ^ 3) 2 f e) * (e * f)))
        +
      (((-1 * (q ^ 6)) + (-1 * (q ^ 8)) + (-1 * (q ^ 14)) + (-3 * (q ^ 12)) + (-2 * (q ^ 10)) +
        (-2 * (q ^ 16)))) • ((e * e * e * f * e) * (qSerre (q ^ 3) 2 f e)) +
      (((q ^ 9) + (2 * (q ^ 13)))) • ((e * e * e * e * f) * (qSerre (q ^ 3) 2 f e)) +
      ((-1 * (q ^ 12))) • ((e * e * e * e) * ((qSerre (q ^ 3) 2 f e) * (f))) := by
    simp only [G2PBW.x1, G2PBW.x2, G2PBW.z, qSerre,
      Finset.sum_range_succ, Finset.sum_range_zero, qBinomial]
    simp only [pow_succ, pow_zero, one_mul, mul_one, mul_add, add_mul, mul_sub, sub_mul,
      smul_sub, smul_add, mul_smul_comm, smul_mul_assoc, smul_smul, mul_assoc, zero_add,
      Nat.sub_zero, Nat.sub_self, Nat.add_one_sub_one]
    match_scalars <;> (field_simp; try ring)
  rw [hS4, hS2] at key
  simp only [zero_mul, mul_zero, smul_zero, add_zero] at key
  exact sub_eq_zero.mp ((smul_eq_zero.mp key).resolve_left hd)

end LieLean.QuantumGroup.G2Integral
