/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.PBW.IntegralG2CommutingCD

/-!
# Adjacent G₂ commutation relations

The adjacent normalized root vectors q-commute. The three internal pairs are proved by
polynomial identities in the two-sided ideal generated by the quantum Serre relations.
The scalar nonvanishing assumptions used to cancel these identities hold at every parameter
which is not a root of unity; their necessity at special parameters is not asserted.
-/

open Finset

noncomputable section

namespace LieLean.QuantumGroup.G2Integral

variable {k B : Type*} [Field k] [Ring B] [Algebra k B]
  {q : k} {e f : B}

variable (hq : q ≠ 0) (h2 : qInt q 2 ≠ 0) (h3 : qInt q 3 ≠ 0)
  (h4 : q ^ 4 + 1 ≠ 0) (h6 : q ^ 4 - q ^ 2 + 1 ≠ 0)
  (hS4 : qSerre q 4 e f = 0) (hS2 : qSerre (q ^ 3) 2 f e = 0)

include hq h4 hS4 hS2 in
lemma X2_mul_X3 : X2 q e f * X3 q e f = (q ^ 3)⁻¹ • (X3 q e f * X2 q e f) := by
  have h := x2_mul_x3_raw hq (by simpa only [add_comm] using h4) hS4 hS2
  simp only [X2, X3, mul_smul_comm, smul_mul_assoc, h, smul_smul]
  module

include hq h4 h6 hS4 hS2 in
lemma Z_mul_X2 : Z q e f * X2 q e f = (q ^ 3)⁻¹ • (X2 q e f * Z q e f) := by
  have h6' : 1 + q ^ 4 + -1 * q ^ 2 ≠ 0 := by convert h6 using 1; ring
  have h := z_mul_x2_raw hq h6' (by simpa only [add_comm] using h4) hS4 hS2
  simp only [Z, X2, mul_smul_comm, smul_mul_assoc, h, smul_smul]
  module

include hq h2 h6 hS4 hS2 in
lemma x1_mul_Z : G2PBW.x1 q e f * Z q e f = (q ^ 3)⁻¹ • (Z q e f * G2PBW.x1 q e f) := by
  have h6' : 1 + q ^ 4 + -1 * q ^ 2 ≠ 0 := by convert h6 using 1; ring
  have h2' : 1 + q ^ 2 ≠ 0 := by
    simpa only [add_comm] using square_add_one_ne_zero hq h2
  have h := x1_mul_z_raw hq h2' h6' hS4 hS2
  simp only [Z, mul_smul_comm, smul_mul_assoc, h, smul_smul]
  module

include h2 h3 in
lemma Z_def : qInt q 3 • Z q e f = X2 q e f * G2PBW.x1 q e f -
    q • (G2PBW.x1 q e f * X2 q e f) := by
  simp only [Z, X2, G2PBW.z, smul_sub, smul_mul_assoc, mul_smul_comm, smul_smul,
    qFactorial_three]
  match_scalars <;> (field_simp; try ring)

include hq h2 h3 h4 hS4 hS2 in
lemma Z_mul_X3 : Z q e f * X3 q e f = (q ^ 3)⁻¹ • (X3 q e f * Z q e f) -
    ((q ^ 2 - 1) ^ 2 / (q ^ 2 * qInt q 3)) • (X2 q e f ^ 3) := by
  have hA := X2_mul_X3 hq h4 hS4 hS2
  have hD := x1_mul_X3 hq h2 h3 hS4 hS2
  apply smul_right_injective B h3
  simp only [smul_sub, smul_smul]
  rw [← smul_mul_assoc, Z_def h2 h3, mul_comm (qInt q 3) ((q ^ 3)⁻¹), ← smul_smul,
    ← mul_smul_comm (qInt q 3) (X3 q e f) (Z q e f), Z_def h2 h3]
  linear_combination (norm := skip) X2 q e f * hD + hA * G2PBW.x1 q e f -
    q • (G2PBW.x1 q e f * hA) - q⁻¹ ^ 2 • (hD * X2 q e f)
  simp only [mul_sub, sub_mul, smul_sub, smul_mul_assoc,
    mul_smul_comm, smul_smul, pow_succ, pow_zero, one_mul, mul_assoc]
  match_scalars <;> (field_simp; try ring)

end LieLean.QuantumGroup.G2Integral
