/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.PBW.IntegralG2Basic

/-!
# G₂ commutation certificate for AB

The adjacent normalized root vectors q-commute. The three internal pairs are proved by
polynomial identities in the two-sided ideal generated by the quantum Serre relations.
The scalar nonvanishing assumptions used to cancel these identities hold at every parameter
which is not a root of unity; their necessity at special parameters is not asserted.
-/

open Finset

noncomputable section

namespace LieLean.QuantumGroup.G2Integral

variable {k B : Type*} [Field k] [Ring B] [Algebra k B]
  {q : k} {e f : B}

set_option maxHeartbeats 4000000 in
-- Normalizing the expanded two-sided Serre certificate requires this larger budget.
lemma x2_mul_x3_raw (hq : q ≠ 0)
    (h4 : (1 + (q ^ 4)) ≠ 0)
    (hS4 : qSerre q 4 e f = 0) (hS2 : qSerre (q ^ 3) 2 f e = 0) :
    G2PBW.x2 q e f * G2PBW.x3 q e f =
      (q ^ 3)⁻¹ • (G2PBW.x3 q e f * G2PBW.x2 q e f) := by
  have hd : ((q ^ 7) * (1 + (q ^ 4))) ≠ 0 := by
    aesop
  have key : ((q ^ 7) * (1 + (q ^ 4))) •
      (G2PBW.x2 q e f * G2PBW.x3 q e f - (q ^ 3)⁻¹ • (G2PBW.x3 q e f * G2PBW.x2 q e f)) =
      ((-1 * (q ^ 2))) • ((qSerre (q ^ 3) 2 f e) * (e * e * e * e)) +
      ((q ^ 2)) • ((f) * ((qSerre q 4 e f) * (e))) +
      ((q + (q ^ 3))) • ((f * e) * (qSerre q 4 e f)) +
      (((-1 * (q ^ 2)) + (-1 * (q ^ 4)) + (-1 * (q ^ 8)))) • ((qSerre q 4 e f) * (f * e)) +
      (((q ^ 5) + (q ^ 7))) • ((qSerre q 4 e f) * (e * f)) +
      ((-1 + (-1 * (q ^ 4)) + (-1 * (q ^ 6)))) • ((e * f) * (qSerre q 4 e f)) +
      ((1 + (q ^ 2) + (q ^ 4) + (q ^ 6))) • ((e) * ((qSerre (q ^ 3) 2 f e) * (e * e * e))) +
      ((q ^ 6)) • ((e) * ((qSerre q 4 e f) * (f))) +
      ((-1 + (-1 * (q ^ 2)) + (-1 * (q ^ 6)) + (-1 * (q ^ 8)) + (-2 * (q ^ 4)))) • ((e * e) *
        ((qSerre (q ^ 3) 2 f e) * (e * e))) +
      (((q ^ 2) + (q ^ 4) + (q ^ 6) + (q ^ 8))) • ((e * e * e) * ((qSerre (q ^ 3) 2 f e) * (e))) +
      ((-1 * (q ^ 6))) • ((e * e * e * e) * (qSerre (q ^ 3) 2 f e)) := by
    simp only [G2PBW.x1, G2PBW.x2, G2PBW.x3, qSerre,
      Finset.sum_range_succ, Finset.sum_range_zero, qBinomial]
    simp only [pow_succ, pow_zero, one_mul, mul_one, mul_add, add_mul, mul_sub, sub_mul,
      smul_sub, smul_add, mul_smul_comm, smul_mul_assoc, smul_smul, mul_assoc, zero_add,
      Nat.sub_zero, Nat.sub_self, Nat.add_one_sub_one]
    match_scalars <;> (field_simp; try ring)
  rw [hS4, hS2] at key
  simp only [zero_mul, mul_zero, smul_zero, add_zero] at key
  exact sub_eq_zero.mp ((smul_eq_zero.mp key).resolve_left hd)

end LieLean.QuantumGroup.G2Integral
