/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.PBW.GenericBasis
import LieLean.Algebra.QuantumGroup.BraidAction.CoupledSerreNegative

/-!
# Negative quantum PBW bases in the Chevalley-conjugated convention

## Main definitions and results

* `chevalleyPlusEquivMinus`: the actual coefficient-linear algebra isomorphism `U⁺ ≃ U⁻`.
* `negativeBraidEquiv`: the conjugated operators `C Tᵢ C⁻¹`, where `C` is Chevalley.
* `chevalley_pbwMonomial`: positive monomials map to ordered `F`-root monomials for these
  conjugated operators, in the same word order and without reversing multiplication.
* `finiteTypeNegativePBWBasis`: a genuine basis of the subalgebra generated by the `Fᵢ`.
* `finiteTypeNegativePBWBasis_sum_repr`: reconstruction in the actual ambient quantum group.

Chevalley fixes coefficients and sends `Eᵢ ↔ Fᵢ`, `K_μ ↦ K_{-μ}`. The conjugated operators
are not asserted to be the original braid operators on `F`: scalar discrepancies already
appear at a simple edge. Independence only needs a nonzero non-root-of-unity parameter.
Spanning and the basis additionally retain characteristic zero and transcendence over `ℚ`
from the positive basis. This is not yet a full negative/toral/positive multiplication basis.

## References

Reconstructed by restricting the presentation-defined Chevalley involution and transporting
`PBW.GenericBasis`; no additional printed theorem number or broader parameter theorem is claimed.
-/

noncomputable section
open Module Matrix.Realization.KacMoodyAlgebra
namespace QuantumGroup

variable {I Y k : Type*} [DecidableEq I] [AddCommGroup Y]
  {D : LusztigCartanDatum I} (R : D.RootDatum Y) [Field k] (v : k)

/-- Chevalley maps the actual positive subalgebra onto the actual negative subalgebra. -/
theorem chevalley_map_adjoin_E :
    (Algebra.adjoin k (Set.range (E R v))).map (chevalleyEquiv R v).toAlgHom =
      Algebra.adjoin k (Set.range (F R v)) := by
  rw [AlgHom.map_adjoin, ← Set.range_comp]
  congr 1
  apply congrArg Set.range
  funext i
  exact chevalley_E R v i

/-- The coefficient-linear Chevalley involution restricted to the generated subalgebras.
This construction has no nonzero, non-root-of-unity, or characteristic hypothesis. -/
def chevalleyPlusEquivMinus :
    Algebra.adjoin k (Set.range (E R v)) ≃ₐ[k] Algebra.adjoin k (Set.range (F R v)) :=
  ((chevalleyEquiv R v).subalgebraMap _).trans
    (Subalgebra.equivOfEq _ _ (chevalley_map_adjoin_E R v))

@[simp] theorem chevalleyPlusEquivMinus_apply
    (x : Algebra.adjoin k (Set.range (E R v))) :
    (chevalleyPlusEquivMinus R v x : QuantumGroup R v) = chevalley R v x := rfl

variable {v} [NeZero v] (hv : ∀ n : ℕ, 0 < n → v ^ n ≠ 1)

/-- The negative convention is explicitly Chevalley-conjugated: `C ∘ Tᵢ ∘ C⁻¹`.
It is not identified with the original `Tᵢ` acting on the negative generators. -/
def negativeBraidEquiv (i : I) : QuantumGroup R v ≃ₐ[k] QuantumGroup R v :=
  (chevalleyEquiv R v).symm.trans
    ((braidEquivOfNotRoot R hv i).trans (chevalleyEquiv R v))

/-- The conjugated operator intertwines the original one with Chevalley. -/
theorem negativeBraidEquiv_chevalley (i : I) (x : QuantumGroup R v) :
    negativeBraidEquiv R hv i (chevalley R v x) =
      chevalley R v (braidEquivOfNotRoot R hv i x) := by
  change (chevalleyEquiv R v)
    (braidEquivOfNotRoot R hv i ((chevalleyEquiv R v).symm (chevalleyEquiv R v x))) = _
  rw [AlgEquiv.symm_apply_apply]
  rfl

/-- Actual root vectors are exchanged by Chevalley using the conjugated braid convention. -/
theorem chevalley_rootVector (ω : List I) (n : ℕ) (hn : n < ω.length) :
    chevalley R v (CoxeterSystem.rootVector (braidEquivOfNotRoot R hv) (E R v) ω n hn) =
      CoxeterSystem.rootVector (negativeBraidEquiv R hv) (F R v) ω n hn := by
  induction ω generalizing n with
  | nil => simp at hn
  | cons i ω ih =>
    cases n with
    | zero => simp [CoxeterSystem.rootVector_cons_zero]
    | succ n =>
      rw [CoxeterSystem.rootVector_cons_succ, CoxeterSystem.rootVector_cons_succ,
        ← negativeBraidEquiv_chevalley, ih]

/-- Ordered positive monomials become ordered negative monomials without order reversal. -/
theorem chevalley_pbwMonomial (ω : List I) (c : Fin ω.length → ℕ) :
    chevalley R v (CoxeterSystem.pbwMonomial (braidEquivOfNotRoot R hv) (E R v) ω c) =
      CoxeterSystem.pbwMonomial (negativeBraidEquiv R hv) (F R v) ω c := by
  induction ω with
  | nil => simp
  | cons i ω ih =>
    rw [CoxeterSystem.pbwMonomial_cons, CoxeterSystem.pbwMonomial_cons,
      map_mul, map_pow, chevalley_E, ← negativeBraidEquiv_chevalley, ih]

variable [Fintype I] {K H : Type*} [Field K] [CharZero K]
  [AddCommGroup H] [Module K H]
  (P : Matrix.Realization D.cartanMatrix K H) (hD : D.cartanMatrix.IsFiniteCartan)

/-- Negative ordered monomials are independent at any nonzero non-root-of-unity parameter.
No characteristic-zero or transcendence hypothesis on the coefficient field `k` is needed. -/
theorem linearIndependent_negativePBWMonomial_of_isFiniteCartan
    {ω : List I} (hω : (P.coxeterSystem hD.isGeneralizedCartan).IsReduced ω) :
    LinearIndependent k
      (CoxeterSystem.pbwMonomial (negativeBraidEquiv R hv) (F R v) ω) := by
  have h := (linearIndependent_pbwMonomial_of_isFiniteCartan (R := R) hv hD hω).map'
    (chevalleyEquiv R v).toLinearMap (chevalleyEquiv R v).toLinearEquiv.ker
  change LinearIndependent k (fun c ↦ chevalley R v
    (CoxeterSystem.pbwMonomial (braidEquivOfNotRoot R hv) (E R v) ω c)) at h
  simpa only [chevalley_pbwMonomial] using h

/-- The genuine longest-word negative PBW basis, at a transcendental parameter in
characteristic zero, obtained by the actual Chevalley subalgebra equivalence. -/
def finiteTypeNegativePBWBasis [CharZero k] (htrans : Transcendental ℚ v)
    {ω : List I} (hω : (P.coxeterSystem hD.isGeneralizedCartan).IsReduced ω)
    (hw : (P.coxeterSystem hD.isGeneralizedCartan).wordProd ω = finiteTypeLongest P hD) :
    Basis (Fin ω.length → ℕ) k (Algebra.adjoin k (Set.range (F R v))) :=
  (finiteTypePBWBasis R P hD hv htrans hω hw).map
    (chevalleyPlusEquivMinus R v).toLinearEquiv

/-- The negative basis vectors are exactly the actual ordered conjugated-braid `F` monomials. -/
theorem finiteTypeNegativePBWBasis_apply [CharZero k] (htrans : Transcendental ℚ v)
    {ω : List I} (hω : (P.coxeterSystem hD.isGeneralizedCartan).IsReduced ω)
    (hw : (P.coxeterSystem hD.isGeneralizedCartan).wordProd ω = finiteTypeLongest P hD)
    (c : Fin ω.length → ℕ) :
    (finiteTypeNegativePBWBasis R hv P hD htrans hω hw c : QuantumGroup R v) =
      CoxeterSystem.pbwMonomial (negativeBraidEquiv R hv) (F R v) ω c := by
  change chevalley R v (finiteTypePBWBasis R P hD hv htrans hω hw c) = _
  rw [finiteTypePBWBasis_apply, chevalley_pbwMonomial]

/-- Basis coordinates reconstruct every element of the actual negative subalgebra as a
finite sum of ordered conjugated-braid `F` monomials in the ambient quantum group. -/
theorem finiteTypeNegativePBWBasis_sum_repr [CharZero k] (htrans : Transcendental ℚ v)
    {ω : List I} (hω : (P.coxeterSystem hD.isGeneralizedCartan).IsReduced ω)
    (hw : (P.coxeterSystem hD.isGeneralizedCartan).wordProd ω = finiteTypeLongest P hD)
    (x : Algebra.adjoin k (Set.range (F R v))) :
    ((finiteTypeNegativePBWBasis R hv P hD htrans hω hw).repr x).sum
      (fun c a ↦ a • CoxeterSystem.pbwMonomial
        (negativeBraidEquiv R hv) (F R v) ω c) = (x : QuantumGroup R v) := by
  have h := congrArg (Algebra.adjoin k (Set.range (F R v))).val
    ((finiteTypeNegativePBWBasis R hv P hD htrans hω hw).linearCombination_repr x)
  simpa only [Finsupp.linearCombination_apply, Finsupp.sum, map_sum, map_smul,
    Subalgebra.val_apply,
    finiteTypeNegativePBWBasis_apply] using h

/-- The basis uses precisely the Chevalley images of the established positive vectors,
with coefficient field, exponent indexing, and word order unchanged. -/
theorem finiteTypeNegativePBWBasis_apply_chevalley [CharZero k]
    (htrans : Transcendental ℚ v)
    {ω : List I} (hω : (P.coxeterSystem hD.isGeneralizedCartan).IsReduced ω)
    (hw : (P.coxeterSystem hD.isGeneralizedCartan).wordProd ω = finiteTypeLongest P hD)
    (c : Fin ω.length → ℕ) :
    (finiteTypeNegativePBWBasis R hv P hD htrans hω hw c : QuantumGroup R v) =
      chevalley R v
        (CoxeterSystem.pbwMonomial (braidEquivOfNotRoot R hv) (E R v) ω c) := by
  rw [finiteTypeNegativePBWBasis_apply, chevalley_pbwMonomial]

/-- A longest reduced word and its actual negative basis exist without a supplied basis,
equivalence, or root enumeration. Transcendence is retained from the positive spanning proof. -/
theorem exists_finiteTypeNegativePBWBasis [CharZero k] (htrans : Transcendental ℚ v) :
    ∃ ω : List I, (P.coxeterSystem hD.isGeneralizedCartan).IsReduced ω ∧
      (P.coxeterSystem hD.isGeneralizedCartan).wordProd ω = finiteTypeLongest P hD ∧
      ∃ b : Basis (Fin ω.length → ℕ) k (Algebra.adjoin k (Set.range (F R v))),
      ∀ c, (b c : QuantumGroup R v) =
        CoxeterSystem.pbwMonomial (negativeBraidEquiv R hv) (F R v) ω c := by
  obtain ⟨ω, hω, hw⟩ :=
    (P.coxeterSystem hD.isGeneralizedCartan).exists_isReduced (finiteTypeLongest P hD)
  exact ⟨ω, hω, hw.symm, finiteTypeNegativePBWBasis R hv P hD htrans hω hw.symm,
    finiteTypeNegativePBWBasis_apply R hv P hD htrans hω hw.symm⟩

end QuantumGroup
