/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import Mathlib.Data.DFinsupp.WellFounded
import Mathlib.RingTheory.Adjoin.Basic

/-!
# Ordered spanning from Levendorskii–Soibelman type commutation relations

Let `x₀, …, x_{n-1}` be elements of a `k`-algebra `B`. Suppose that for all `a < b`
there is a scalar `c` with
`x_b x_a - c x_a x_b ∈ span {x_{m₁} ⋯ x_{m_r} | a < m₁ ≤ ⋯ ≤ m_r < b}`
(`OrderedSpan.IsLS`: commutation relations of Levendorskii–Soibelman type, with the correction
term spanned by ordered monomials in the letters strictly between `a` and `b`). Then the ordered
monomials `x₀^{c₀} ⋯ x_{n-1}^{c_{n-1}}` span the subalgebra generated by the `xₘ`
(`OrderedSpan.span_mono_eq_adjoin`).

The proof straightens an arbitrary word: an adjacent descent `x_b x_a` (`a < b`) is replaced by
`c x_a x_b` (fewer inversions, same letter counts) plus words whose letter-count vector is
smaller in the lexicographic order of `ℕⁿ` (one letter `a` is lost and only letters `> a` are
added). Lexicographic order on `ℕⁿ` is well founded.

We also record how the hypothesis behaves under prepending a letter through an algebra
endomorphism (`OrderedSpan.isLS_cons`) and under restriction to an initial segment
(`OrderedSpan.IsLS.castSucc`); these are the two operations that build the root vectors along an
alternating word.

## Main results

* `OrderedSpan.span_mono_eq_adjoin`
* `OrderedSpan.isLS_cons`, `OrderedSpan.IsLS.castSucc`, `OrderedSpan.BaseRel.castSucc`

## References

Our own reconstruction of the standard straightening argument (cf. Levendorskii–Soibelman,
De Concini–Kac).
-/

noncomputable section

namespace QuantumGroup

namespace OrderedSpan

variable {k B : Type*} [Field k] [Ring B] [Algebra k B] {n : ℕ} (x : Fin n → B)

/-- The product `x_{w₁} ⋯ x_{w_r}` of a word. -/
def wordProd (w : List (Fin n)) : B := (w.map x).prod

/-- The ordered monomial `x₀^{c₀} ⋯ x_{n-1}^{c_{n-1}}`. -/
def mono (c : Fin n → ℕ) : B := (List.ofFn fun i ↦ x i ^ c i).prod

variable (k) in
/-- The span of the products of the nondecreasing words. -/
def sortedSpan : Submodule k B :=
  Submodule.span k {y | ∃ w : List (Fin n), w.Pairwise (· ≤ ·) ∧ wordProd x w = y}

variable (k) in
/-- The span of the products of the nondecreasing words in the letters strictly between `a`
and `b`. -/
def innerSpan (a b : Fin n) : Submodule k B :=
  Submodule.span k {y | ∃ w : List (Fin n), w.Pairwise (· ≤ ·) ∧
    (∀ m ∈ w, a < m ∧ m < b) ∧ wordProd x w = y}

variable (k) in
/-- Commutation relations of Levendorskii–Soibelman type. -/
def IsLS : Prop :=
  ∀ a b : Fin n, a < b → ∃ c : k, x b * x a - c • (x a * x b) ∈ innerSpan k x a b

variable {x}

@[simp] lemma wordProd_nil : wordProd x [] = 1 := rfl

@[simp] lemma wordProd_cons (a : Fin n) (w : List (Fin n)) :
    wordProd x (a :: w) = x a * wordProd x w := by
  simp [wordProd]

lemma wordProd_append (u w : List (Fin n)) :
    wordProd x (u ++ w) = wordProd x u * wordProd x w := by
  simp [wordProd]

/-! ### Measures -/

/-- The number of inversions of a word. -/
def inv : List (Fin n) → ℕ
  | [] => 0
  | a :: w => w.countP (fun b ↦ decide (b < a)) + inv w

lemma inv_swap {a b : Fin n} (hab : a < b) (p s : List (Fin n)) :
    inv (p ++ a :: b :: s) < inv (p ++ b :: a :: s) := by
  induction p with
  | nil =>
    simp [inv, hab, not_lt.mpr hab.le]
    omega
  | cons c p ih =>
    simp only [List.cons_append, inv]
    rw [((List.Perm.swap b a s).append_left p).countP_eq]
    omega

/-- The letter-count vector of a word. -/
def cnt (w : List (Fin n)) : Fin n → ℕ := fun i ↦ w.count i

lemma cnt_swap (a b : Fin n) (p s : List (Fin n)) :
    cnt (p ++ a :: b :: s) = cnt (p ++ b :: a :: s) := by
  funext i
  exact ((List.Perm.swap b a s).append_left p).count_eq i

lemma cnt_lt {a b : Fin n} (hab : a < b) (p s u : List (Fin n)) (hu : ∀ m ∈ u, a < m) :
    toLex (cnt (p ++ u ++ s)) < toLex (cnt (p ++ b :: a :: s)) := by
  have hu0 : ∀ j, j ≤ a → u.count j = 0 := fun j hj ↦
    List.count_eq_zero.mpr fun hm ↦ absurd (hu j hm) (not_lt.mpr hj)
  refine ⟨a, fun j hj ↦ ?_, ?_⟩
  · have hj' : j < a := hj
    simp [cnt, hu0 j hj'.le, (hj'.trans hab).ne', hj'.ne']
  · simp [cnt, hu0 a le_rfl, hab.ne']

lemma exists_descent : ∀ w : List (Fin n), ¬ w.Pairwise (· ≤ ·) →
    ∃ p a b s, a < b ∧ w = p ++ b :: a :: s
  | [], h => absurd List.Pairwise.nil h
  | c :: w, h => by
    by_cases hw : w.Pairwise (· ≤ ·)
    · obtain ⟨d, hd, hcd⟩ : ∃ d ∈ w, ¬ c ≤ d := by
        by_contra hh
        exact h (List.pairwise_cons.mpr ⟨fun d hd ↦ by
          by_contra h'
          exact hh ⟨d, hd, h'⟩, hw⟩)
      replace hcd := not_le.mp hcd
      obtain ⟨d₀, w', rfl⟩ := List.exists_cons_of_ne_nil (List.ne_nil_of_mem hd)
      have h₀ : d₀ ≤ d := by
        rcases List.mem_cons.mp hd with rfl | hd'
        · exact le_rfl
        · exact (List.pairwise_cons.mp hw).1 d hd'
      exact ⟨[], d₀, c, w', lt_of_le_of_lt h₀ hcd, rfl⟩
    · obtain ⟨p, a, b, s, hab, rfl⟩ := exists_descent w hw
      exact ⟨c :: p, a, b, s, hab, rfl⟩

/-! ### Straightening -/

variable (x) in
/-- **Straightening.** Under the commutation relations `IsLS`, the product of every word lies
in the span of the products of the nondecreasing words. -/
theorem wordProd_mem_sortedSpan (h : IsLS k x) (w : List (Fin n)) :
    wordProd x w ∈ sortedSpan k x := by
  suffices H : ∀ N : Lex (Fin n → ℕ), ∀ m : ℕ, ∀ w : List (Fin n),
      toLex (cnt w) = N → inv w = m → wordProd x w ∈ sortedSpan k x from H _ _ w rfl rfl
  intro N
  induction N using WellFoundedLT.induction with
  | _ N ihN =>
  intro m
  induction m using Nat.strong_induction_on with
  | _ m ihm =>
  intro w hN hm
  by_cases hs : w.Pairwise (· ≤ ·)
  · exact Submodule.subset_span ⟨w, hs, rfl⟩
  obtain ⟨p, a, b, s, hab, rfl⟩ := exists_descent w hs
  obtain ⟨c, hc⟩ := h a b hab
  have e : wordProd x (p ++ b :: a :: s) = c • wordProd x (p ++ a :: b :: s) +
      wordProd x p * (x b * x a - c • (x a * x b)) * wordProd x s := by
    simp only [wordProd_append, wordProd_cons, mul_sub, sub_mul, mul_smul_comm, smul_mul_assoc,
      mul_assoc]
    abel
  rw [e]
  refine add_mem (Submodule.smul_mem _ _ (ihm _ (hm ▸ inv_swap hab p s) _
    (by rw [cnt_swap]; exact hN) rfl)) ?_
  have key : ∀ y ∈ innerSpan k x a b, wordProd x p * y * wordProd x s ∈ sortedSpan k x := by
    intro y hy
    induction hy using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨u, -, hu, rfl⟩ := hy
      rw [← wordProd_append, ← wordProd_append]
      exact ihN _ (hN ▸ cnt_lt hab p s u fun m hm ↦ (hu m hm).1) _ _ rfl rfl
    | zero => simp
    | add y z _ _ hy hz =>
      simpa only [mul_add, add_mul] using add_mem hy hz
    | smul r y _ hy =>
      simpa only [mul_smul_comm, smul_mul_assoc] using Submodule.smul_mem _ r hy
  exact key _ hc

/-! ### Ordered monomials -/

omit [Field k] [Algebra k B] in
lemma mono_insert : ∀ {n : ℕ} (x : Fin n → B) (c : Fin n → ℕ) (a : Fin n),
    (∀ i < a, c i = 0) → x a * mono x c = mono x (Function.update c a (c a + 1))
  | 0, _, _, a, _ => a.elim0
  | n + 1, x, c, a, hc => by
    have hsplit (d : Fin (n + 1) → ℕ) :
        mono x d = x 0 ^ d 0 * mono (fun i ↦ x i.succ) (fun i ↦ d i.succ) := by
      simp [mono, List.ofFn_succ]
    rw [hsplit, hsplit]
    cases a using Fin.cases with
    | zero =>
      simp only [Function.update_self]
      have hu : (fun i : Fin n ↦ Function.update c 0 (c 0 + 1) i.succ) = fun i ↦ c i.succ := by
        funext i
        rw [Function.update_of_ne (Fin.succ_ne_zero i)]
      rw [hu, pow_succ', mul_assoc]
    | succ a =>
      have h0 : c 0 = 0 := hc 0 (Fin.succ_pos a)
      rw [Function.update_of_ne (Fin.succ_ne_zero a).symm, h0]
      simp only [pow_zero, one_mul]
      have hu : (fun i : Fin n ↦ Function.update c a.succ (c a.succ + 1) i.succ) =
          Function.update (fun i ↦ c i.succ) a (c a.succ + 1) := by
        funext i
        by_cases hi : i = a
        · subst hi; simp
        · rw [Function.update_of_ne (fun h ↦ hi (Fin.succ_injective _ h)),
            Function.update_of_ne hi]
      rw [hu]
      exact mono_insert (fun i ↦ x i.succ) (fun i ↦ c i.succ) a
        fun i hi ↦ hc i.succ (Fin.succ_lt_succ_iff.mpr hi)

omit [Field k] [Algebra k B] in
lemma wordProd_eq_mono_of_pairwise : ∀ w : List (Fin n), w.Pairwise (· ≤ ·) →
    wordProd x w = mono x (cnt w)
  | [], _ => by
    simp [mono, cnt]
  | a :: w, hw => by
    obtain ⟨ha, hw⟩ := List.pairwise_cons.mp hw
    rw [wordProd_cons, wordProd_eq_mono_of_pairwise w hw, mono_insert]
    · congr 1
      funext i
      by_cases hi : i = a
      · subst hi; simp [cnt]
      · rw [Function.update_of_ne hi]
        simp [cnt, Ne.symm hi]
    · intro i hi
      exact List.count_eq_zero.mpr fun hm ↦ absurd (ha i hm) (not_le.mpr hi)

variable (x) in
/-- **Ordered spanning.** Under commutation relations of Levendorskii–Soibelman type, the
ordered monomials span the subalgebra generated by the `xₘ`. -/
theorem span_mono_eq_adjoin (h : IsLS k x) :
    Submodule.span k (Set.range (mono x)) = (Algebra.adjoin k (Set.range x)).toSubmodule := by
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨c, rfl⟩
    change mono x c ∈ Algebra.adjoin k (Set.range x)
    exact list_prod_mem fun y hy ↦ by
      obtain ⟨i, rfl⟩ := List.mem_ofFn.mp hy
      exact pow_mem (Algebra.subset_adjoin (Set.mem_range_self i)) _
  · have hS : sortedSpan k x ≤ Submodule.span k (Set.range (mono x)) := by
      rw [sortedSpan, Submodule.span_le]
      rintro _ ⟨w, hw, rfl⟩
      rw [wordProd_eq_mono_of_pairwise w hw]
      exact Submodule.subset_span ⟨_, rfl⟩
    refine le_trans ?_ hS
    have h1 : (1 : B) ∈ sortedSpan k x := Submodule.subset_span ⟨[], List.Pairwise.nil, rfl⟩
    have hmul : ∀ j, ∀ y ∈ sortedSpan k x, x j * y ∈ sortedSpan k x := by
      intro j y hy
      induction hy using Submodule.span_induction with
      | mem y hy =>
        obtain ⟨w, -, rfl⟩ := hy
        rw [← wordProd_cons]
        exact wordProd_mem_sortedSpan x h _
      | zero => simp
      | add y z _ _ hy hz => simpa only [mul_add] using add_mem hy hz
      | smul r y _ hy => simpa only [mul_smul_comm] using Submodule.smul_mem _ r hy
    intro z hz
    have hz' : ∀ y ∈ sortedSpan k x, z * y ∈ sortedSpan k x := by
      induction hz using Algebra.adjoin_induction with
      | mem z hz =>
        obtain ⟨j, rfl⟩ := hz
        exact hmul j
      | algebraMap r =>
        intro y hy
        simpa only [Algebra.smul_def] using Submodule.smul_mem _ r hy
      | add z w _ _ hz hw =>
        intro y hy
        simpa only [add_mul] using add_mem (hz y hy) (hw y hy)
      | mul z w _ _ hz hw =>
        intro y hy
        simpa only [mul_assoc] using hz (w * y) (hw y hy)
    simpa only [mul_one] using hz' 1 h1

/-! ### Building the relations along a word -/

variable (k) in
/-- The relations between the first letter and every later letter. -/
def BaseRel (y : Fin (n + 1) → B) : Prop :=
  ∀ l : Fin n, ∃ c : k, y l.succ * y 0 - c • (y 0 * y l.succ) ∈ innerSpan k y 0 l.succ

lemma map_innerSpan {e : B} {x' : Fin n → B} (φ : B →ₐ[k] B) {a b : Fin n} {z : B}
    (hz : z ∈ innerSpan k x' a b) :
    φ z ∈ innerSpan k (Fin.cons e (fun i ↦ φ (x' i)) : Fin (n + 1) → B) a.succ b.succ := by
  induction hz using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨u, hu, hab, rfl⟩ := hz
    refine Submodule.subset_span ⟨u.map Fin.succ, ?_, ?_, ?_⟩
    · exact List.pairwise_map.mpr (hu.imp fun h ↦ Fin.succ_le_succ_iff.mpr h)
    · intro m hm
      obtain ⟨m', hm', rfl⟩ := List.mem_map.mp hm
      exact ⟨Fin.succ_lt_succ_iff.mpr (hab m' hm').1, Fin.succ_lt_succ_iff.mpr (hab m' hm').2⟩
    · simp [wordProd, List.map_map, map_list_prod, Function.comp_def]
  | zero => simp
  | add y z _ _ hy hz => simpa only [map_add] using add_mem hy hz
  | smul r y _ hy => simpa only [map_smul] using Submodule.smul_mem _ r hy

/-- Prepending a letter: if `x'` satisfies the commutation relations, so does
`(e, φ x'₀, φ x'₁, …)` for an algebra endomorphism `φ`, as soon as the relations between `e`
and the later letters hold. -/
theorem isLS_cons {e : B} {x' : Fin n → B} (φ : B →ₐ[k] B) (h : IsLS k x')
    (hb : BaseRel k (Fin.cons e (fun i ↦ φ (x' i)) : Fin (n + 1) → B)) :
    IsLS k (Fin.cons e (fun i ↦ φ (x' i)) : Fin (n + 1) → B) := by
  intro a b hab
  cases a using Fin.cases with
  | zero =>
    cases b using Fin.cases with
    | zero => exact absurd hab (lt_irrefl _)
    | succ b => exact hb b
  | succ a =>
    cases b using Fin.cases with
    | zero => exact absurd hab (not_lt.mpr (Fin.zero_le _))
    | succ b =>
      obtain ⟨c, hc⟩ := h a b (Fin.succ_lt_succ_iff.mp hab)
      refine ⟨c, ?_⟩
      have := map_innerSpan (e := e) φ hc
      simpa only [map_sub, map_mul, map_smul, Fin.cons_succ] using this

lemma innerSpan_castSucc_le (y : Fin (n + 1) → B) (a b : Fin n) :
    innerSpan k y a.castSucc b.castSucc ≤ innerSpan k (fun i ↦ y i.castSucc) a b := by
  rw [innerSpan, Submodule.span_le]
  rintro _ ⟨u, hu, hab, rfl⟩
  have hlift : ∀ u : List (Fin (n + 1)), (∀ m ∈ u, m < b.castSucc) →
      ∃ u' : List (Fin n), u = u'.map Fin.castSucc := by
    intro u
    induction u with
    | nil => exact fun _ ↦ ⟨[], rfl⟩
    | cons m u ih =>
      intro hm
      obtain ⟨u', rfl⟩ := ih fun m' h' ↦ hm m' (List.mem_cons_of_mem _ h')
      have hm' : (m : ℕ) < n :=
        lt_trans (Fin.lt_def.mp (hm m List.mem_cons_self)) b.isLt
      exact ⟨Fin.castLT m hm' :: u', by simp⟩
  obtain ⟨u', rfl⟩ := hlift u fun m hm ↦ (hab m hm).2
  refine Submodule.subset_span ⟨u', ?_, ?_, ?_⟩
  · exact (List.pairwise_map.mp hu).imp fun h ↦ Fin.castSucc_le_castSucc_iff.mp h
  · intro m hm
    have := hab _ (List.mem_map_of_mem hm)
    exact ⟨Fin.castSucc_lt_castSucc_iff.mp this.1, Fin.castSucc_lt_castSucc_iff.mp this.2⟩
  · simp [wordProd, List.map_map, Function.comp_def]

/-- Restriction to an initial segment preserves the commutation relations. -/
theorem IsLS.castSucc {y : Fin (n + 1) → B} (h : IsLS k y) :
    IsLS k fun i : Fin n ↦ y i.castSucc := by
  intro a b hab
  obtain ⟨c, hc⟩ := h a.castSucc b.castSucc (Fin.castSucc_lt_castSucc_iff.mpr hab)
  exact ⟨c, innerSpan_castSucc_le y a b hc⟩

/-- Restriction to an initial segment preserves the relations with the first letter. -/
theorem BaseRel.castSucc {y : Fin (n + 2) → B} (h : BaseRel k y) :
    BaseRel k fun i : Fin (n + 1) ↦ y i.castSucc := by
  intro l
  obtain ⟨c, hc⟩ := h l.castSucc
  exact ⟨c, innerSpan_castSucc_le y 0 l.succ hc⟩

end OrderedSpan

end QuantumGroup
