/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.BraidAction.NeighborSerreShort
import LieLean.Algebra.QuantumGroup.BraidAction.OrthogonalGeneral
import Mathlib.GroupTheory.Coxeter.Basic

/-!
# Braid group operators on rank-two subalgebras of infinite type

Let `i ≠ j` with `a = -aᵢⱼ`, `a' = -aⱼᵢ` and `a a' ≥ 4`, so that `sᵢ sⱼ` has infinite order
(`h(i,j) = ∞` in [Lus] 2.1.1). We prove the case `h = ∞` of [Lus] Lemma 40.1.1 for Lusztig's
automorphisms `Tᵢ = T''_{i,1}` (any algebra automorphisms with the generator formulas
`HasBraidGeneratorImages`): for every `p ≥ 0`, `⋯ Tᵢ Tⱼ Tᵢ (Eⱼ)` and `⋯ Tⱼ Tᵢ Tⱼ (Eᵢ)` (`p` factors)
lie in the subalgebra generated by `Eᵢ, Eⱼ`
(`QuantumGroup.alternatingWord_prod_E_mem_adjoin_of_four_le`).

The proof follows Lusztig's. We work with the twisted commutators
`Xp i j n = X n` (`q = vᵢ`, `Q = q^a`; `X 0 = Eⱼ`, `X (n+1) = Eᵢ X n - q^{2n} Q⁻¹ X n Eᵢ`) and
`Xm i j n`, the same with `q⁻¹, Q⁻¹`; these play the role of Lusztig's elements
`x'_{i,j;1,n;-1}` and `x_{i,j;1,n;-1}` of [Lus] 37.2.1. The input is the lowering identity
`Tᵢ(Xm i j m) ∈ k · Xp i j (a - m)` for `m ≤ a` (`QuantumGroup.exists_map_rankTwoXm`; cf. [Lus]
37.2.5 (b) with `e = -1`), obtained from `BraidDiagonal.Hyp.stepE`, together with
`Xp i j 1 ∈ k · Xm j i 1`. Then:

* if `a, a' ≥ 2`, the subalgebras `Zᵢ = ⟨Xp i j a, Xp i j (a-1)⟩` and
  `Zⱼ = ⟨Xp j i a', Xp j i (a'-1)⟩` satisfy `Tⱼ Zᵢ ⊆ Zⱼ`, `Tᵢ Zⱼ ⊆ Zᵢ`, `Tᵢ(Eⱼ) ∈ Zᵢ`,
  `Tⱼ(Eᵢ) ∈ Zⱼ` ([Lus] 40.1.1 (a)–(c));
* if `a ≥ 4`, `a' = 1`, the same holds for `Zᵢ = ⟨Xp i j a, Xp i j (a-1), Xp i j (a-2)⟩` and
  `Zⱼ = ⟨Xm i j 1, Xm i j 2⟩` ([Lus] 40.1.1 (d)–(f));

and the alternating words are handled by `QuantumGroup.alternatingWord_prod_apply_mem`.

## References

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, 37.2.1, 37.2.5, Lemma 40.1.1.
-/

open LieLean

noncomputable section

namespace LieLean.QuantumGroup

/-! ### Alternating words acting on two subalgebras -/

section Alternating

variable {B : Type*} {k A : Type*} [CommSemiring k] [Semiring A] [Algebra k A]
  {T : B → A ≃ₐ[k] A} {E : B → A} {i j : B} {Zi Zj : Subalgebra k A}

/-- If `Tᵢ` maps `Zⱼ` into `Zᵢ`, `Tⱼ` maps `Zᵢ` into `Zⱼ` and `Tⱼ(Eᵢ) ∈ Zⱼ`, then the
alternating products `⋯ Tᵢ Tⱼ (Eᵢ)` of length `n + 1` lie in `Zⱼ` (`n` even) or `Zᵢ` (`n` odd). -/
theorem alternatingWord_prod_apply_mem_aux (hj : T j (E i) ∈ Zj)
    (hij : ∀ x ∈ Zj, T i x ∈ Zi) (hji : ∀ x ∈ Zi, T j x ∈ Zj) (n : ℕ) :
    ((CoxeterSystem.alternatingWord i j (n + 1)).map T).prod (E i) ∈
      (if Even n then Zj else Zi) := by
  induction n with
  | zero => simpa [CoxeterSystem.alternatingWord] using hj
  | succ n ih =>
    rw [CoxeterSystem.alternatingWord_succ' i j (n + 1), List.map_cons, List.prod_cons,
      AlgEquiv.mul_apply]
    by_cases hn : Even n
    · have h1 : ¬Even (n + 1) := Nat.not_even_iff_odd.mpr hn.add_one
      simp only [hn, h1, ↓reduceIte] at ih ⊢
      exact hij _ ih
    · have h1 : Even (n + 1) := (Nat.not_even_iff_odd.mp hn).add_one
      simp only [hn, h1, ↓reduceIte] at ih ⊢
      exact hji _ ih

/-- The alternating products `⋯ Tᵢ Tⱼ (Eᵢ)` lie in any subalgebra `P ∋ Eᵢ` containing `Zᵢ, Zⱼ`
as in `alternatingWord_prod_apply_mem_aux`. -/
theorem alternatingWord_prod_apply_mem {P : Subalgebra k A} (hj : T j (E i) ∈ Zj)
    (hij : ∀ x ∈ Zj, T i x ∈ Zi) (hji : ∀ x ∈ Zi, T j x ∈ Zj) (hZi : Zi ≤ P) (hZj : Zj ≤ P)
    (hE : E i ∈ P) (n : ℕ) :
    ((CoxeterSystem.alternatingWord i j n).map T).prod (E i) ∈ P := by
  cases n with
  | zero => simpa [CoxeterSystem.alternatingWord] using hE
  | succ n =>
    have h := alternatingWord_prod_apply_mem_aux hj hij hji n
    split_ifs at h
    exacts [hZj h, hZi h]

end Alternating

/-! ### The twisted commutators -/

open BraidDiagonal

variable {k : Type*} [Field k] {I Y : Type*} [AddCommGroup Y] [DecidableEq I]
  {D : LusztigCartanDatum I} {R : D.RootDatum Y} {v : k}

variable (R v) in
/-- `Xp i j n = X n` with `q = vᵢ`, `Q = q^{-aᵢⱼ}`: `Xp i j 0 = Eⱼ`,
`Xp i j (n+1) = Eᵢ Xp i j n - q^{2n} Q⁻¹ Xp i j n Eᵢ` (cf. [Lus] 37.2.1, `x'_{i,j;1,n;-1}`). -/
def rankTwoXp (i j : I) (n : ℕ) : QuantumGroup R v :=
  X (v ^ D.d i) ((v ^ D.d i) ^ negA D i j) (E R v i) (E R v j) n

variable (R v) in
/-- `Xm i j n = X n` with `q = vᵢ⁻¹`, `Q = q^{-aᵢⱼ}` (cf. [Lus] 37.2.1, `x_{i,j;1,n;-1}`). -/
def rankTwoXm (i j : I) (n : ℕ) : QuantumGroup R v :=
  X (v ^ D.d i)⁻¹ ((v ^ D.d i)⁻¹ ^ negA D i j) (E R v i) (E R v j) n

lemma rankTwoXp_zero (i j : I) : rankTwoXp R v i j 0 = E R v j := rfl

lemma rankTwoXm_zero (i j : I) : rankTwoXm R v i j 0 = E R v j := rfl

lemma rankTwoXp_succ (i j : I) (n : ℕ) :
    rankTwoXp R v i j (n + 1) = E R v i * rankTwoXp R v i j n -
      shift (v ^ D.d i) ((v ^ D.d i) ^ negA D i j) n • (rankTwoXp R v i j n * E R v i) := rfl

lemma rankTwoXm_succ (i j : I) (n : ℕ) :
    rankTwoXm R v i j (n + 1) = E R v i * rankTwoXm R v i j n -
      shift (v ^ D.d i)⁻¹ ((v ^ D.d i)⁻¹ ^ negA D i j) n • (rankTwoXm R v i j n * E R v i) := rfl

section Membership

variable {P : Subalgebra k (QuantumGroup R v)} {i j : I}

lemma rankTwoXp_mem (hi : E R v i ∈ P) (hj : E R v j ∈ P) (n : ℕ) : rankTwoXp R v i j n ∈ P := by
  induction n with
  | zero => exact hj
  | succ n ih =>
    rw [rankTwoXp_succ]
    exact sub_mem (mul_mem hi ih) (Subalgebra.smul_mem _ (mul_mem ih hi) _)

lemma rankTwoXm_mem (hi : E R v i ∈ P) (hj : E R v j ∈ P) (n : ℕ) : rankTwoXm R v i j n ∈ P := by
  induction n with
  | zero => exact hj
  | succ n ih =>
    rw [rankTwoXm_succ]
    exact sub_mem (mul_mem hi ih) (Subalgebra.smul_mem _ (mul_mem ih hi) _)

/-- If `T(Eᵢ) ∈ P` and `T(Xp i j m) ∈ P`, then `T(Xp i j (m + n)) ∈ P` for all `n`. -/
lemma map_rankTwoXp_add_mem {T : QuantumGroup R v →ₐ[k] QuantumGroup R v} {m : ℕ}
    (hE : T (E R v i) ∈ P) (hm : T (rankTwoXp R v i j m) ∈ P) (n : ℕ) :
    T (rankTwoXp R v i j (m + n)) ∈ P := by
  induction n with
  | zero => exact hm
  | succ n ih =>
    rw [← add_assoc, rankTwoXp_succ, map_sub, map_mul, map_smul, map_mul]
    exact sub_mem (mul_mem hE ih) (Subalgebra.smul_mem _ (mul_mem ih hE) _)

lemma map_adjoin_mem {T : QuantumGroup R v →ₐ[k] QuantumGroup R v}
    {s : Set (QuantumGroup R v)} (h : ∀ x ∈ s, T x ∈ P) :
    ∀ x ∈ Algebra.adjoin k s, T x ∈ P := fun _ hx ↦
  (Algebra.adjoin_le (S := P.comap T) fun y hy ↦ (Subalgebra.mem_comap _ _ _).2 (h y hy)) hx

end Membership

/-! ### Images under `Tᵢ` -/

section Images

variable [NeZero v] {i j : I} {S : QuantumGroup R v →ₐ[k] QuantumGroup R v}

/-- `Xp i j 1 = -(vᵢ^{-aᵢⱼ})⁻¹ Xm j i 1`, using `vᵢ^{-aᵢⱼ} = vⱼ^{-aⱼᵢ}`. -/
lemma rankTwoXp_one (hij : i ≠ j) :
    rankTwoXp R v i j 1 = (-((v ^ D.d i) ^ negA D i j)⁻¹) • rankTwoXm R v j i 1 := by
  have hp := twoNode_param_pow (D := D) (v := v) hij
  have h0 : (v ^ D.d i) ^ negA D i j ≠ 0 := pow_ne_zero _ (pow_ne_zero _ (NeZero.ne v))
  rw [rankTwoXp_succ, rankTwoXm_succ, rankTwoXp_zero, rankTwoXm_zero, inv_pow, hp]
  simp only [shift, pow_zero, mul_zero, one_mul, inv_inv, smul_sub, smul_smul]
  rw [neg_mul, inv_mul_cancel₀ h0]
  module

lemma rankTwoXp_one' (hij : i ≠ j) :
    ∃ c : k, rankTwoXp R v i j 1 = c • rankTwoXm R v j i 1 := ⟨_, rankTwoXp_one hij⟩

variable (HS : HasBraidGeneratorImages i S)
include HS

omit [NeZero v] in
lemma map_E_self : S (E R v i) = braidEi R i := by
  simp [HS.map_E]

/-- `Tᵢ(Eⱼ) = [a]ᵢ!⁻¹ Xp i j a` for `j ≠ i`, `a = -aᵢⱼ`. -/
lemma map_E_eq_rankTwoXp (hij : i ≠ j) :
    S (E R v j) = (qFactorial (v ^ D.d i) (negA D i j))⁻¹ • rankTwoXp R v i j (negA D i j) := by
  have hq0 : v ^ D.d i ≠ 0 := pow_ne_zero _ (NeZero.ne v)
  have hc : (v ^ D.d i) ^ negA D i j * (v ^ D.d i * (v ^ D.d i) ^ negA D i j)⁻¹ =
      (v ^ D.d i)⁻¹ := by
    field_simp
  rw [HS.map_E, ite_eq_right hij.symm, rankTwoXp, X_eq_serreAux hq0 (pow_ne_zero _ hq0), hc]
  rfl

/-- **The lowering identity** (cf. [Lus] 37.2.5 (b), `e = -1`): for `m ≤ -aᵢⱼ`,
`Tᵢ(Xm i j m)` is a scalar multiple of `Xp i j (-aᵢⱼ - m)`. -/
lemma exists_map_rankTwoXm (hij : i ≠ j) (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) :
    ∀ m ≤ negA D i j, ∃ c : k,
      S (rankTwoXm R v i j m) = c • rankTwoXp R v i j (negA D i j - m) := by
  intro m
  induction m with
  | zero =>
    intro _
    exact ⟨_, by rw [rankTwoXm_zero, map_E_eq_rankTwoXp HS hij, Nat.sub_zero]⟩
  | succ m ih =>
    intro hm
    obtain ⟨c, hc⟩ := ih (by omega)
    obtain ⟨n, hn⟩ : ∃ n, negA D i j - m = n + 1 := ⟨negA D i j - m - 1, by omega⟩
    have hn' : negA D i j - (m + 1) = n := by omega
    have H := braidDiagonal_hyp R v (NeZero.ne v) hij hq
    have hq0 : v ^ D.d i ≠ 0 := pow_ne_zero _ (NeZero.ne v)
    have hs : shift (v ^ D.d i)⁻¹ ((v ^ D.d i)⁻¹ ^ negA D i j) m =
        shift (v ^ D.d i) ((v ^ D.d i) ^ negA D i j) (n + 1) := by
      have ha : negA D i j = n + 1 + m := by omega
      simp only [shift, inv_pow, inv_inv]
      rw [ha]
      generalize v ^ D.d i = q at hq0 ⊢
      field_simp
      ring
    have hstep : braidEi R i * rankTwoXp R v i j (n + 1) -
        shift (v ^ D.d i) ((v ^ D.d i) ^ negA D i j) (n + 1) •
          (rankTwoXp R v i j (n + 1) * braidEi R i) =
        (-(shift (v ^ D.d i) ((v ^ D.d i) ^ negA D i j) (n + 1) *
          cc (v ^ D.d i) ((v ^ D.d i) ^ negA D i j) (n + 1))) • rankTwoXp R v i j n :=
      H.stepE (K_neg_mul_Kt i) n
    refine ⟨c * -(shift (v ^ D.d i) ((v ^ D.d i) ^ negA D i j) (n + 1) *
      cc (v ^ D.d i) ((v ^ D.d i) ^ negA D i j) (n + 1)), ?_⟩
    rw [hn', rankTwoXm_succ, map_sub, map_mul, map_smul, map_mul, hc, map_E_self HS, hn, hs,
      mul_smul_comm, smul_mul_assoc, smul_comm _ c, ← smul_sub, hstep, smul_smul]

end Images

/-! ### The two cases of infinite type -/

section Infinite

variable [NeZero v] {i j : I} {S T : QuantumGroup R v →ₐ[k] QuantumGroup R v}

local notation "P" => Algebra.adjoin k ({E R v i, E R v j} : Set (QuantumGroup R v))

omit [NeZero v] in
lemma E_mem_pair_left' : E R v i ∈ P := Algebra.subset_adjoin (by simp)

omit [NeZero v] in
lemma E_mem_pair_right' : E R v j ∈ P := Algebra.subset_adjoin (by simp)

variable (R v) in
/-- `⟨Xp i j a, Xp i j (a - 1)⟩`, `a = -aᵢⱼ`. -/
def rankTwoZ (i j : I) : Subalgebra k (QuantumGroup R v) :=
  Algebra.adjoin k {rankTwoXp R v i j (negA D i j), rankTwoXp R v i j (negA D i j - 1)}

omit [NeZero v] in
lemma rankTwoZ_le_pair : rankTwoZ R v i j ≤ P := by
  refine Algebra.adjoin_le ?_
  rintro x (rfl | rfl) <;>
    exact rankTwoXp_mem (R := R) (v := v) (i := i) (j := j) E_mem_pair_left' E_mem_pair_right' _

omit [NeZero v] in
lemma rankTwoZ_le_pair' : rankTwoZ R v j i ≤ P := by
  rw [Set.pair_comm]
  exact rankTwoZ_le_pair (i := j) (j := i)

/-- `Tⱼ(Eᵢ) ∈ ⟨Xp j i a', Xp j i (a'-1)⟩`. -/
lemma map_E_mem_rankTwoZ (HT : HasBraidGeneratorImages j T) (hij : i ≠ j) :
    T (E R v i) ∈ rankTwoZ R v j i := by
  rw [map_E_eq_rankTwoXp HT hij.symm]
  exact Subalgebra.smul_mem _ (Algebra.subset_adjoin (by simp)) _

/-- [Lus] 40.1.1 (a), for `T''`: if `a' ≥ 1`, then `Tⱼ(Xp i j (m+1)) ∈ ⟨Xp j i a', Xp j i (a'-1)⟩`
for all `m`. -/
lemma map_rankTwoXp_succ_mem_rankTwoZ (HT : HasBraidGeneratorImages j T) (hij : i ≠ j)
    (hqj : v ^ D.d j - (v ^ D.d j)⁻¹ ≠ 0) (ha' : 1 ≤ negA D j i) (m : ℕ) :
    T (rankTwoXp R v i j (m + 1)) ∈ rankTwoZ R v j i := by
  rw [add_comm]
  refine map_rankTwoXp_add_mem (map_E_mem_rankTwoZ HT hij) ?_ m
  obtain ⟨c, hc⟩ := exists_map_rankTwoXm HT hij.symm hqj 1 ha'
  rw [rankTwoXp_one hij, map_smul, hc, smul_smul]
  exact Subalgebra.smul_mem _ (Algebra.subset_adjoin (by simp)) _

/-- [Lus] 40.1.1 (b), for `T''`: if `a ≥ 2` and `a' ≥ 1`, `Tⱼ` maps `Zᵢ` into `Zⱼ`. -/
lemma map_rankTwoZ_le (HT : HasBraidGeneratorImages j T) (hij : i ≠ j)
    (hqj : v ^ D.d j - (v ^ D.d j)⁻¹ ≠ 0) (ha : 2 ≤ negA D i j) (ha' : 1 ≤ negA D j i) :
    ∀ x ∈ rankTwoZ R v i j, T x ∈ rankTwoZ R v j i := by
  refine map_adjoin_mem ?_
  rintro x (rfl | rfl)
  · have e : negA D i j = negA D i j - 1 + 1 := by omega
    rw [e]
    exact map_rankTwoXp_succ_mem_rankTwoZ HT hij hqj ha' _
  · have e : negA D i j - 1 = negA D i j - 2 + 1 := by omega
    rw [e]
    exact map_rankTwoXp_succ_mem_rankTwoZ HT hij hqj ha' _

variable (R v) in
/-- `⟨Xp i j a, Xp i j (a - 1), Xp i j (a - 2)⟩`. -/
def rankTwoZ₃ (i j : I) : Subalgebra k (QuantumGroup R v) :=
  Algebra.adjoin k {rankTwoXp R v i j (negA D i j), rankTwoXp R v i j (negA D i j - 1),
    rankTwoXp R v i j (negA D i j - 2)}

variable (R v) in
/-- `⟨Xm i j 1, Xm i j 2⟩`. -/
def rankTwoZm (i j : I) : Subalgebra k (QuantumGroup R v) :=
  Algebra.adjoin k {rankTwoXm R v i j 1, rankTwoXm R v i j 2}

/-- At `a' = 1`: `Tⱼ(Eᵢ) ∈ k · Xm i j 1`. -/
lemma map_E_mem_rankTwoZm (HT : HasBraidGeneratorImages j T) (hij : i ≠ j)
    (ha' : negA D j i = 1) : T (E R v i) ∈ rankTwoZm R v i j := by
  rw [map_E_eq_rankTwoXp HT hij.symm, ha', rankTwoXp_one hij.symm, smul_smul]
  exact Subalgebra.smul_mem _ (Algebra.subset_adjoin (by simp)) _

/-- [Lus] 40.1.1 (e), for `T''`: if `a' = 1`, then `Tⱼ(Xp i j (m+2)) ∈ ⟨Xm i j 1, Xm i j 2⟩`. -/
lemma map_rankTwoXp_add_two_mem (HT : HasBraidGeneratorImages j T) (hij : i ≠ j)
    (hqj : v ^ D.d j - (v ^ D.d j)⁻¹ ≠ 0) (ha' : negA D j i = 1) (m : ℕ) :
    T (rankTwoXp R v i j (m + 2)) ∈ rankTwoZm R v i j := by
  rw [add_comm]
  refine map_rankTwoXp_add_mem (map_E_mem_rankTwoZm HT hij ha') ?_ m
  have hq0 : v ^ D.d i ≠ 0 := pow_ne_zero _ (NeZero.ne v)
  obtain ⟨c, hc⟩ := exists_map_rankTwoXm HT hij.symm hqj 1 ha'.ge
  have h1 : T (rankTwoXp R v i j 1) = ((-((v ^ D.d i) ^ negA D i j)⁻¹) * c) • E R v i := by
    rw [rankTwoXp_one hij, map_smul, hc, ha', Nat.sub_self, rankTwoXp_zero, smul_smul]
  have hE : T (E R v i) = ((qFactorial (v ^ D.d j) 1)⁻¹ * -((v ^ D.d j) ^ negA D j i)⁻¹) •
      rankTwoXm R v i j 1 := by
    rw [map_E_eq_rankTwoXp HT hij.symm, ha', rankTwoXp_one hij.symm, smul_smul, ha']
  have hs : shift (v ^ D.d i) ((v ^ D.d i) ^ negA D i j) 1 *
      shift (v ^ D.d i)⁻¹ ((v ^ D.d i)⁻¹ ^ negA D i j) 1 = 1 := by
    simp only [shift, inv_pow, inv_inv]
    generalize v ^ D.d i = q at hq0 ⊢
    field_simp
  set α := (qFactorial (v ^ D.d j) 1)⁻¹ * -((v ^ D.d j) ^ negA D j i)⁻¹
  set β := -((v ^ D.d i) ^ negA D i j)⁻¹ * c
  set s := shift (v ^ D.d i) ((v ^ D.d i) ^ negA D i j) 1
  set s' := shift (v ^ D.d i)⁻¹ ((v ^ D.d i)⁻¹ ^ negA D i j) 1
  have key : α • rankTwoXm R v i j 1 * β • E R v i - s • (β • E R v i * α • rankTwoXm R v i j 1) =
      (α * β * -s) • rankTwoXm R v i j 2 := by
    have hs' : s * s' = 1 := hs
    have e : α * β * -s * s' = -(α * β) := by linear_combination (-(α * β)) * hs'
    rw [rankTwoXm_succ i j 1, smul_sub, smul_smul, e]
    simp only [smul_mul_assoc, mul_smul_comm, smul_smul]
    module
  rw [rankTwoXp_succ, map_sub, map_mul, map_smul, map_mul, h1, hE, key]
  exact Subalgebra.smul_mem _ (Algebra.subset_adjoin (by simp)) _

omit [NeZero v] in
lemma rankTwoZ₃_le_pair : rankTwoZ₃ R v i j ≤ P := by
  refine Algebra.adjoin_le ?_
  rintro x (rfl | rfl | rfl) <;>
    exact rankTwoXp_mem (R := R) (v := v) (i := i) (j := j) E_mem_pair_left' E_mem_pair_right' _

omit [NeZero v] in
lemma rankTwoZm_le_pair : rankTwoZm R v i j ≤ P := by
  refine Algebra.adjoin_le ?_
  rintro x (rfl | rfl) <;>
    exact rankTwoXm_mem (R := R) (v := v) (i := i) (j := j) E_mem_pair_left' E_mem_pair_right' _

/-- `Tᵢ(Eⱼ) ∈ ⟨Xp i j a, Xp i j (a-1), Xp i j (a-2)⟩`. -/
lemma map_E_mem_rankTwoZ₃ (HS : HasBraidGeneratorImages i S) (hij : i ≠ j) :
    S (E R v j) ∈ rankTwoZ₃ R v i j := by
  rw [map_E_eq_rankTwoXp HS hij]
  exact Subalgebra.smul_mem _ (Algebra.subset_adjoin (by simp)) _

/-- [Lus] 40.1.1 (d), for `T''`: `Tᵢ` maps `⟨Xm i j 1, Xm i j 2⟩` into
`⟨Xp i j a, Xp i j (a-1), Xp i j (a-2)⟩` if `a ≥ 2`. -/
lemma map_rankTwoZm_le (HS : HasBraidGeneratorImages i S) (hij : i ≠ j)
    (hqi : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) (ha : 2 ≤ negA D i j) :
    ∀ x ∈ rankTwoZm R v i j, S x ∈ rankTwoZ₃ R v i j := by
  refine map_adjoin_mem ?_
  rintro x (rfl | rfl)
  · obtain ⟨c, hc⟩ := exists_map_rankTwoXm HS hij hqi 1 (by omega)
    rw [hc]
    exact Subalgebra.smul_mem _ (Algebra.subset_adjoin (by simp)) _
  · obtain ⟨c, hc⟩ := exists_map_rankTwoXm HS hij hqi 2 ha
    rw [hc]
    exact Subalgebra.smul_mem _ (Algebra.subset_adjoin (by simp)) _

/-- [Lus] 40.1.1 (e), for `T''`: if `a ≥ 4` and `a' = 1`, `Tⱼ` maps
`⟨Xp i j a, Xp i j (a-1), Xp i j (a-2)⟩` into `⟨Xm i j 1, Xm i j 2⟩`. -/
lemma map_rankTwoZ₃_le (HT : HasBraidGeneratorImages j T) (hij : i ≠ j)
    (hqj : v ^ D.d j - (v ^ D.d j)⁻¹ ≠ 0) (ha : 4 ≤ negA D i j) (ha' : negA D j i = 1) :
    ∀ x ∈ rankTwoZ₃ R v i j, T x ∈ rankTwoZm R v i j := by
  refine map_adjoin_mem ?_
  rintro x (rfl | rfl | rfl)
  · rw [show negA D i j = negA D i j - 2 + 2 by omega]
    exact map_rankTwoXp_add_two_mem HT hij hqj ha' _
  · rw [show negA D i j - 1 = negA D i j - 3 + 2 by omega]
    exact map_rankTwoXp_add_two_mem HT hij hqj ha' _
  · rw [show negA D i j - 2 = negA D i j - 4 + 2 by omega]
    exact map_rankTwoXp_add_two_mem HT hij hqj ha' _

/-! ### Alternating words -/

variable {Tf : I → QuantumGroup R v ≃ₐ[k] QuantumGroup R v}

/-- **[Lus] Lemma 40.1.1 for `h(i,j) = ∞`** (for `T''_{i,1}`): if `aᵢⱼ aⱼᵢ ≥ 4`, then for every
`n` the element `⋯ Tᵢ Tⱼ (Eᵢ)` (alternating word of length `n`, ending with `Tⱼ`) lies in the
subalgebra generated by `Eᵢ, Eⱼ`. Here `Tₗ` is any family of algebra automorphisms with Lusztig's
generator formulas; `v ≠ 0`, `vₗ - vₗ⁻¹ ≠ 0` are the only conditions on the parameter. -/
theorem alternatingWord_prod_E_mem_adjoin_of_four_le
    (HT : ∀ l, HasBraidGeneratorImages l (Tf l).toAlgHom)
    (hq : ∀ l, v ^ D.d l - (v ^ D.d l)⁻¹ ≠ 0) (hij : i ≠ j)
    (h4 : ¬D.cartanMatrix i j * D.cartanMatrix j i ≤ 3) (n : ℕ) :
    ((CoxeterSystem.alternatingWord i j n).map Tf).prod (E R v i) ∈ P := by
  rw [cartanMatrix_eq_neg_negA hij, cartanMatrix_eq_neg_negA hij.symm, neg_mul_neg] at h4
  have h4' : 4 ≤ negA D i j * negA D j i := by
    have : (4 : ℤ) ≤ (negA D i j : ℤ) * negA D j i := by omega
    exact_mod_cast this
  have ha0 : negA D i j ≠ 0 := by rintro h; simp [h] at h4'
  have ha0' : negA D j i ≠ 0 := by rintro h; simp [h] at h4'
  obtain ⟨Zi, Zj, hj, hZij, hZji, hZi, hZj⟩ : ∃ Zi Zj : Subalgebra k (QuantumGroup R v),
      Tf j (E R v i) ∈ Zj ∧ (∀ x ∈ Zj, Tf i x ∈ Zi) ∧ (∀ x ∈ Zi, Tf j x ∈ Zj) ∧
        Zi ≤ P ∧ Zj ≤ P := by
    by_cases h1 : negA D i j = 1
    · rw [h1, one_mul] at h4'
      exact ⟨rankTwoZm R v j i, rankTwoZ₃ R v j i, map_E_mem_rankTwoZ₃ (HT j) hij.symm,
        map_rankTwoZ₃_le (HT i) hij.symm (hq i) h4' h1,
        map_rankTwoZm_le (HT j) hij.symm (hq j) (by omega),
        by rw [Set.pair_comm]; exact rankTwoZm_le_pair,
        by rw [Set.pair_comm]; exact rankTwoZ₃_le_pair⟩
    by_cases h1' : negA D j i = 1
    · rw [h1', mul_one] at h4'
      exact ⟨rankTwoZ₃ R v i j, rankTwoZm R v i j, map_E_mem_rankTwoZm (HT j) hij h1',
        map_rankTwoZm_le (HT i) hij (hq i) (by omega),
        map_rankTwoZ₃_le (HT j) hij (hq j) h4' h1', rankTwoZ₃_le_pair, rankTwoZm_le_pair⟩
    · exact ⟨rankTwoZ R v i j, rankTwoZ R v j i, map_E_mem_rankTwoZ (HT j) hij,
        map_rankTwoZ_le (HT i) hij.symm (hq i) (by omega) (by omega),
        map_rankTwoZ_le (HT j) hij (hq j) (by omega) (by omega),
        rankTwoZ_le_pair, rankTwoZ_le_pair'⟩
  exact alternatingWord_prod_apply_mem hj hZij hZji hZi hZj E_mem_pair_left' n

end Infinite

end LieLean.QuantumGroup
