/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.PBW.RankTwoB2LocalSpan
import LieLean.Algebra.QuantumGroup.PBW.RankTwoA2ContextSpan
import LieLean.Algebra.QuantumGroup.PBW.Independence
import Mathlib.Algebra.Algebra.Subalgebra.MulOpposite

/-!
# Ordered spans of the actual four-letter B₂ PBW words

Let `i, j` be nodes of an arbitrary Cartan datum with `aᵢⱼ = -2`, `aⱼᵢ = -1` (`i` short),
`q = vᵢ` and `p = q² = vⱼ`. The two reduced words of the longest element of the rank-two
parabolic subgroup are `i j i j` and `j i j i`.

* Along `i j i j` the root vectors are `Eᵢ, Tᵢ(Eⱼ), TᵢTⱼ(Eᵢ), Eⱼ`, and their ordered monomials
  are the monomials `b2PBWMono` (`QuantumGroup.pbwMonomial_b2_eq`).
* Along `j i j i` the root vectors are `Eⱼ`, `Tⱼ(Eᵢ) = y'`, `TⱼTᵢ(Eⱼ) = [2]ᵢ!⁻¹ x'` and
  `TⱼTᵢTⱼ(Eᵢ) = Eᵢ`, where `y' = EⱼEᵢ - p⁻¹EᵢEⱼ` and `x' = y'Eᵢ - Eᵢy'`
  (`QuantumGroup.pbwMonomial_b2_rev_eq`).

The elements `Eᵢ, x', y', Eⱼ` satisfy the B₂ straightening relations `B2PBW.Rel` in the
*opposite* algebra (`B2PBW.rel_op`): the relations are the reversals of the ones used for
`i j i j`, and the two quantum Serre relations are palindromic. Hence the local ordered spanning
theorem `B2PBW.span_mono_eq_adjoin` applies to the reversed monomials as well
(`B2PBW.span_revMono_eq_adjoin`).

## Main results

* `QuantumGroup.span_pbwMonomial_b2`, `QuantumGroup.span_pbwMonomial_b2_rev`: both actual
  four-letter words span the two-generator subalgebra, in arbitrary ambient Cartan data.
* `QuantumGroup.span_pbwMonomial_b2_braid`: the two words have equal ordered spans.
* `QuantumGroup.span_pbwMonomial_b2_context`,
  `QuantumGroup.span_pbwMonomial_b2_context_of_not_root`: the equality persists in arbitrary
  prefix/suffix word context, given the full four-term braid relation (supplied by the
  constructed braid automorphisms at a non-root-of-unity parameter under `BraidOuterCondition`).

The local results assume a nonzero parameter, `vᵢ - vᵢ⁻¹ ≠ 0` and `[2]ᵢ! ≠ 0`.

## References

Reconstructed from the repository's B₂ straightening relations and root-vector computations;
the passage to the reversed word through the opposite algebra is our own device.
-/

noncomputable section

open LusztigF

namespace QuantumGroup

namespace B2PBW

variable {k B : Type*} [Field k] [Ring B] [Algebra k B]

/-- The cubic quantum Serre element in terms of the reversed commutators
`y' = f e - q⁻² e f` and `x' = y' e - e y'`: `S₃(e, f) = q² e x' - x' e`. -/
lemma qSerre_three_eq_rev {q : k} (hq : q ≠ 0) (e f : B) :
    qSerre q 3 e f =
      q ^ 2 • (e * (A2PBW.qComm (q ^ 2) f e * e - e * A2PBW.qComm (q ^ 2) f e)) -
        (A2PBW.qComm (q ^ 2) f e * e - e * A2PBW.qComm (q ^ 2) f e) * e := by
  simp only [qSerre, Finset.sum_range_succ, Finset.sum_range_zero, qBinomial, A2PBW.qComm]
  simp only [pow_succ, pow_zero, one_mul, mul_one, mul_sub, sub_mul, smul_sub, mul_smul_comm,
    smul_mul_assoc, smul_smul, mul_assoc, zero_add, Nat.sub_zero, Nat.sub_self,
    Nat.add_one_sub_one]
  match_scalars <;> (field_simp; try ring)

open MulOpposite in
/-- The reversed root vectors `e < x' < y' < f` satisfy the B₂ straightening relations in the
opposite algebra, by the two quantum Serre relations. -/
theorem rel_op {q : k} (hq : q ≠ 0) {e f : B} (hS3 : qSerre q 3 e f = 0)
    (hS2 : qSerre (q ^ 2) 2 f e = 0) :
    Rel (q ^ 2) (op e) (op (A2PBW.qComm (q ^ 2) f e * e - e * A2PBW.qComm (q ^ 2) f e))
      (op (A2PBW.qComm (q ^ 2) f e)) (op f) where
  fe := by
    apply unop_injective
    simp only [unop_mul, unop_sub, unop_smul, unop_op]
    exact A2PBW.mul_eq_qComm (pow_ne_zero 2 hq) f e
  ye := by
    apply unop_injective
    simp only [unop_mul, unop_sub, unop_op]
    abel
  xe := by
    apply unop_injective
    simp only [unop_mul, unop_smul, unop_op]
    rw [qSerre_three_eq_rev hq, sub_eq_zero] at hS3
    rw [← hS3, smul_smul, inv_mul_cancel₀ (pow_ne_zero 2 hq), one_smul]
  fy := by
    apply unop_injective
    simp only [unop_mul, unop_smul, unop_op]
    exact A2PBW.qComm_mul_left_of_qSerre (pow_ne_zero 2 hq) hS2

open MulOpposite in
/-- **Reversed local B₂ spanning.** The reversed ordered monomials `f^a y'^b x'^c e^d` span the
subalgebra generated by `e` and `f`, in any algebra where the two quantum Serre relations hold.
Obtained from `span_mono_eq_adjoin` in the opposite algebra. -/
theorem span_revMono_eq_adjoin {q : k} (hq : q ≠ 0) (h1 : q ^ 2 - 1 ≠ 0)
    (h2 : (q ^ 2) ^ 2 - 1 ≠ 0) {e f : B} (hS3 : qSerre q 3 e f = 0)
    (hS2 : qSerre (q ^ 2) 2 f e = 0) :
    Submodule.span k (Set.range fun m : ℕ × ℕ × ℕ × ℕ ↦
      f ^ m.1 * (A2PBW.qComm (q ^ 2) f e ^ m.2.1 *
        ((A2PBW.qComm (q ^ 2) f e * e - e * A2PBW.qComm (q ^ 2) f e) ^ m.2.2.1 *
          e ^ m.2.2.2))) =
      (Algebra.adjoin k {e, f}).toSubmodule := by
  set y := A2PBW.qComm (q ^ 2) f e
  set x := y * e - e * y
  set g : ℕ × ℕ × ℕ × ℕ → B := fun m ↦ f ^ m.1 * (y ^ m.2.1 * (x ^ m.2.2.1 * e ^ m.2.2.2))
  have H := span_mono_eq_adjoin (rel_op hq hS3 hS2) (pow_ne_zero 2 hq) h1 h2
  have hr : Set.range (mono (op e) (op x) (op y) (op f)) =
      (opLinearEquiv k : B ≃ₗ[k] Bᵐᵒᵖ).toLinearMap '' Set.range g := by
    ext z
    constructor
    · rintro ⟨⟨a, b, c, d⟩, rfl⟩
      refine ⟨g (d, c, b, a), ⟨_, rfl⟩, ?_⟩
      change op (f ^ d * (y ^ c * (x ^ b * e ^ a))) = _
      simp only [mono, op_mul, op_pow, mul_assoc]
    · rintro ⟨_, ⟨⟨a, b, c, d⟩, rfl⟩, rfl⟩
      refine ⟨(d, c, b, a), ?_⟩
      change _ = op (f ^ a * (y ^ b * (x ^ c * e ^ d)))
      simp only [mono, op_mul, op_pow, mul_assoc]
  have hA : Algebra.adjoin k {op e, op f} = (Algebra.adjoin k ({e, f} : Set B)).op := by
    rw [Subalgebra.op_adjoin]
    congr 1
    ext z
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff, Set.mem_preimage]
    constructor
    · rintro (rfl | rfl) <;> simp
    · rintro (h | h)
      · exact Or.inl (by rw [← h, op_unop])
      · exact Or.inr (by rw [← h, op_unop])
  rw [hr, Submodule.span_image, hA] at H
  ext z
  constructor
  · intro hz
    have h' : op z ∈ (Submodule.span k (Set.range g)).map
        (opLinearEquiv k : B ≃ₗ[k] Bᵐᵒᵖ).toLinearMap := ⟨z, hz, rfl⟩
    rw [H] at h'
    exact Subalgebra.mem_op.mp h'
  · intro hz
    have h' : op z ∈ Subalgebra.toSubmodule (Algebra.adjoin k ({e, f} : Set B)).op :=
      Subalgebra.mem_op.mpr hz
    rw [← H] at h'
    obtain ⟨y, hy, hyz⟩ := h'
    rwa [show y = z from op_injective hyz] at hy

end B2PBW

variable {k I Y : Type*} [Field k] [AddCommGroup Y] [DecidableEq I]
  {D : LusztigCartanDatum I} (R : D.RootDatum Y) (v : k)

/-- `y' = EⱼEᵢ - vᵢ⁻²EᵢEⱼ`; in type `B₂` this is the root vector `Tⱼ(Eᵢ)`. -/
def b2RevRootY (i j : I) : QuantumGroup R v :=
  A2PBW.qComm ((v ^ D.d i) ^ 2) (E R v j) (E R v i)

/-- `x' = y'Eᵢ - Eᵢy'`; in type `B₂`, `TⱼTᵢ(Eⱼ) = [2]ᵢ!⁻¹ x'`. -/
def b2RevRootX (i j : I) : QuantumGroup R v :=
  b2RevRootY R v i j * E R v i - E R v i * b2RevRootY R v i j

variable [NeZero v] {i j : I} (hij : i ≠ j) (h : D.cartanMatrix i j = -2)
  (h' : D.cartanMatrix j i = -1)
  (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) (h2 : qFactorial (v ^ D.d i) 2 ≠ 0)

include hij h h' hq h2

/-- The reversed raw B₂ monomials `Eⱼ^a y'^b x'^c Eᵢ^d` span the actual two-generator
subalgebra, in arbitrary ambient Cartan data. -/
theorem span_b2RevMono_pair :
    Submodule.span k (Set.range fun m : ℕ × ℕ × ℕ × ℕ ↦
      E R v j ^ m.1 * (b2RevRootY R v i j ^ m.2.1 *
        (b2RevRootX R v i j ^ m.2.2.1 * E R v i ^ m.2.2.2))) =
      (Algebra.adjoin k {E R v i, E R v j}).toSubmodule := by
  have hq0 : v ^ D.d i ≠ 0 := pow_ne_zero _ (NeZero.ne v)
  obtain ⟨_, h1, hp2⟩ := B2PBW.param_ne hq0 hq h2
  have hS3 := serre_E R v hij
  rw [B2PBW.toNat_one_sub_eq_three h] at hS3
  have hS2 := serre_E R v hij.symm
  rw [A2PBW.toNat_one_sub_eq_two h', parameter_eq_square_of_double_edge h h'] at hS2
  exact B2PBW.span_revMono_eq_adjoin hq0 h1 hp2 hS3 hS2

/-- The reversed B₂ monomials with the normalized third root vector `[2]ᵢ!⁻¹ x'` span the
actual two-generator subalgebra. -/
theorem span_b2RevPBWMono_pair :
    Submodule.span k (Set.range fun m : ℕ × ℕ × ℕ × ℕ ↦
      E R v j ^ m.1 * (b2RevRootY R v i j ^ m.2.1 *
        (((qFactorial (v ^ D.d i) 2)⁻¹ • b2RevRootX R v i j) ^ m.2.2.1 * E R v i ^ m.2.2.2))) =
      (Algebra.adjoin k {E R v i, E R v j}).toSubmodule := by
  rw [← span_b2RevMono_pair R v hij h h' hq h2]
  have hc : (qFactorial (v ^ D.d i) 2)⁻¹ ≠ 0 := inv_ne_zero h2
  have e (m : ℕ × ℕ × ℕ × ℕ) :
      E R v j ^ m.1 * (b2RevRootY R v i j ^ m.2.1 *
        (((qFactorial (v ^ D.d i) 2)⁻¹ • b2RevRootX R v i j) ^ m.2.2.1 * E R v i ^ m.2.2.2)) =
      ((qFactorial (v ^ D.d i) 2)⁻¹ ^ m.2.2.1) • (E R v j ^ m.1 * (b2RevRootY R v i j ^ m.2.1 *
        (b2RevRootX R v i j ^ m.2.2.1 * E R v i ^ m.2.2.2))) := by
    rw [smul_pow]
    simp only [smul_mul_assoc, mul_smul_comm]
  apply le_antisymm <;> rw [Submodule.span_le] <;> rintro _ ⟨m, rfl⟩
  · dsimp only
    rw [e]
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨m, rfl⟩)
  · dsimp only
    have hm := (inv_smul_eq_iff₀ (pow_ne_zero m.2.2.1 hc)).mpr (e m)
    rw [SetLike.mem_coe, ← hm]
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨m, rfl⟩)

omit [NeZero v] hij h h' hq h2 in
lemma b2RootY_eq_X :
    b2RootY R v i j = BraidDiagonal.X (v ^ D.d i) ((v ^ D.d i) ^ 2) (E R v i) (E R v j) 1 := by
  rw [BraidDiagonal.X_succ (n := 0), b2_shift_zero]
  rfl

variable (T : I → QuantumGroup R v ≃ₐ[k] QuantumGroup R v)
  (Hi : HasBraidGeneratorImages i (T i).toAlgHom)
  (Hj : HasBraidGeneratorImages j (T j).toAlgHom)

include Hi Hj

/-- The actual recursive PBW monomial of the word `i j i j` is the B₂ monomial `b2PBWMono`. -/
theorem pbwMonomial_b2_eq (c : Fin [i, j, i, j].length → ℕ) :
    CoxeterSystem.pbwMonomial T (E R v) [i, j, i, j] c =
      b2PBWMono R v i j (c 0, c 1, c 2, c 3) := by
  rw [b2PBWMono_eq_rootVectors Hi Hj hij h h' hq h2]
  simp only [CoxeterSystem.pbwMonomial, map_mul, map_pow, map_one, mul_one]
  rfl

/-- The actual recursive PBW monomial of the word `j i j i` is the reversed B₂ monomial
`Eⱼ^a y'^b ([2]ᵢ!⁻¹ x')^c Eᵢ^d`. -/
theorem pbwMonomial_b2_rev_eq (c : Fin [j, i, j, i].length → ℕ) :
    CoxeterSystem.pbwMonomial T (E R v) [j, i, j, i] c =
      E R v j ^ c 0 * (b2RevRootY R v i j ^ c 1 *
        (((qFactorial (v ^ D.d i) 2)⁻¹ • b2RevRootX R v i j) ^ c 2 * E R v i ^ c 3)) := by
  have hq0 : v ^ D.d i ≠ 0 := pow_ne_zero _ (NeZero.ne v)
  have hY' : (T j) (E R v i) = b2RevRootY R v i j := by
    have e := a2_rootVector_two hij.symm Hj
    change (T j) (E R v i) = _ at e
    rw [e, braidEj_eq_of_cartanMatrix_eq_neg_one h', parameter_eq_square_of_double_edge h h']
    rfl
  have hY : (T j) (b2RootY R v i j) = E R v i := by
    rw [b2RootY_eq_X R v (j := j)]
    exact b2_T_X_one Hj hij h h' hq h2
  have hX : (T j) ((T i) (E R v j)) = (qFactorial (v ^ D.d i) 2)⁻¹ • b2RevRootX R v i j := by
    have e := a2_rootVector_two hij Hi
    change (T i) (E R v j) = _ at e
    rw [e, b2_braidEj_eq h, map_smul, b2RootX, map_sub, map_mul, map_mul, hY, hY']
    rfl
  have hE : (T j) ((T i) ((T j) (E R v i))) = E R v i := by
    have e := b2_rootVector_three Hi Hj hij h h' hq
    change (T i) ((T j) (E R v i)) = _ at e
    rw [e, b2_cc_two hq0 hq, ← b2_qFactorial_two hq0, inv_mul_cancel₀ h2, one_smul,
      ← b2RootY_eq_X, hY]
  simp only [CoxeterSystem.pbwMonomial, map_mul, map_pow, map_one, mul_one]
  change E R v j ^ c 0 * ((T j) (E R v i) ^ c 1 * ((T j) ((T i) (E R v j)) ^ c 2 *
    (T j) ((T i) ((T j) (E R v i))) ^ c 3)) = _
  rw [hE, hX, hY']

/-- The actual PBW word `i j i j` spans the two-generator subalgebra. -/
theorem span_pbwMonomial_b2 :
    Submodule.span k (Set.range (CoxeterSystem.pbwMonomial T (E R v) [i, j, i, j])) =
      (Algebra.adjoin k {E R v i, E R v j}).toSubmodule := by
  have hr : Set.range (CoxeterSystem.pbwMonomial T (E R v) [i, j, i, j]) =
      Set.range (b2PBWMono R v i j) := by
    ext x
    constructor
    · rintro ⟨c, rfl⟩
      exact ⟨_, (pbwMonomial_b2_eq R v hij h h' hq h2 T Hi Hj c).symm⟩
    · rintro ⟨⟨a, b, c, d⟩, rfl⟩
      exact ⟨![a, b, c, d], pbwMonomial_b2_eq R v hij h h' hq h2 T Hi Hj _⟩
  rw [hr]
  exact span_b2PBWMono_pair R v hij h h' hq h2

/-- The actual PBW word `j i j i` spans the two-generator subalgebra. -/
theorem span_pbwMonomial_b2_rev :
    Submodule.span k (Set.range (CoxeterSystem.pbwMonomial T (E R v) [j, i, j, i])) =
      (Algebra.adjoin k {E R v i, E R v j}).toSubmodule := by
  rw [← span_b2RevPBWMono_pair R v hij h h' hq h2]
  congr 1
  ext x
  constructor
  · rintro ⟨c, rfl⟩
    exact ⟨(c 0, c 1, c 2, c 3), (pbwMonomial_b2_rev_eq R v hij h h' hq h2 T Hi Hj c).symm⟩
  · rintro ⟨⟨a, b, c, d⟩, rfl⟩
    exact ⟨![a, b, c, d], pbwMonomial_b2_rev_eq R v hij h h' hq h2 T Hi Hj _⟩

/-- The two actual four-letter B₂ words have equal ordered PBW spans. -/
theorem span_pbwMonomial_b2_braid :
    Submodule.span k (Set.range (CoxeterSystem.pbwMonomial T (E R v) [i, j, i, j])) =
      Submodule.span k (Set.range (CoxeterSystem.pbwMonomial T (E R v) [j, i, j, i])) := by
  rw [span_pbwMonomial_b2 R v hij h h' hq h2 T Hi Hj,
    span_pbwMonomial_b2_rev R v hij h h' hq h2 T Hi Hj]

/-- **B₂ span invariance in context.** An actual B₂ braid move preserves the ordered PBW span
in arbitrary prefix/suffix context, given the full four-term braid relation. No reducedness of
the context is needed. -/
theorem span_pbwMonomial_b2_context
    (hT : T i * T j * T i * T j = T j * T i * T j * T i) (p s : List I) :
    Submodule.span k (Set.range (CoxeterSystem.pbwMonomial T (E R v)
      (p ++ [i, j, i, j] ++ s))) =
    Submodule.span k (Set.range (CoxeterSystem.pbwMonomial T (E R v)
      (p ++ [j, i, j, i] ++ s))) := by
  apply CoxeterSystem.span_pbwMonomial_context
    T (E R v) (span_pbwMonomial_b2_braid R v hij h h' hq h2 T Hi Hj)
  simpa only [List.map_cons, List.map_nil, List.prod_cons, List.prod_nil,
    mul_one, ← mul_assoc] using hT

omit hq h2 Hi Hj in
/-- At a non-root-of-unity parameter, the constructed braid automorphisms satisfy the full B₂
braid relation (under `BraidOuterCondition`), so B₂ braid moves preserve ordered PBW spans in
arbitrary word context. -/
theorem span_pbwMonomial_b2_context_of_not_root
    (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) (hD : D.BraidOuterCondition) (p s : List I) :
    Submodule.span k (Set.range (CoxeterSystem.pbwMonomial
      (braidEquivOfNotRoot R hv') (E R v) (p ++ [i, j, i, j] ++ s))) =
    Submodule.span k (Set.range (CoxeterSystem.pbwMonomial
      (braidEquivOfNotRoot R hv') (E R v) (p ++ [j, i, j, i] ++ s))) := by
  apply span_pbwMonomial_b2_context R v hij h h' (shortNode_braidGeneric_of_not_root hv' i).sub_ne
    (qFactorial_ne_zero_of_not_root (NeZero.ne v) hv' i 2) (braidEquivOfNotRoot R hv')
    (braidEquivOfNotRoot_images hv' i) (braidEquivOfNotRoot_images hv' j)
  have hLift : D.cartanMatrix.coxeterMatrix.IsBraidLiftable (braidEquivOfNotRoot R hv') :=
    isBraidLiftable_braidEquivOfGeneric
      (fun l ↦ (shortNode_braidGeneric_of_not_root hv' l).sub_ne)
      (braidSerreGeneric_of_not_root hv')
      (fun l ↦ LusztigF.qFactorial_ne_zero_of_not_root (NeZero.ne v) hv' l 3) hD
  have hm : D.cartanMatrix.coxeterMatrix i j = 4 := by
    rw [Matrix.coxeterMatrix_apply_of_ne _ hij, h, h']
    rfl
  have hm' : D.cartanMatrix.coxeterMatrix j i = 4 := by
    rw [Matrix.coxeterMatrix_apply_of_ne _ hij.symm, h, h']
    rfl
  have e := hLift i j hij (by omega)
  simpa [CoxeterSystem.braidWord, hm, hm', CoxeterSystem.alternatingWord,
    ← mul_assoc] using e

end QuantumGroup
