/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.PBW.RankTwoA2

/-!
# Local A₂ ordered spanning in arbitrary ambient quantum groups

## Main results

* `A2PBW.span_mono_qComm_eq_adjoin`: quadratic Serre relations give ordered spanning
  of the two-generator subalgebra of any ambient algebra.
* `span_a2PBWMono_pair`: actual A₂ monomials span the subalgebra generated by a simple
  edge, without restricting the ambient Cartan datum to two nodes.
* `span_a2PBWMono_pair_reverse`: either orientation gives the same local span.

Only a nonzero parameter is required for the quantum-group results. There is no
characteristic-zero, transcendence, non-root-of-unity, or finite-type hypothesis.
This local straightening result does not assert general longest-word ordered spanning.

## References

Reconstructed from the quadratic quantum Serre relations using the established
`A2PBW` monomial operators. The two-letter free-algebra argument does not require a
representation satisfying relations involving other ambient nodes.
-/

noncomputable section
namespace QuantumGroup
namespace A2PBW
open LusztigF
variable {k B : Type*} [Field k] [Ring B] [Algebra k B]
  {q : k} {e f X : B}

private theorem monoMap_pair_rep
    (hfe : f * e = q • (e * f) - q • X)
    (hXe : X * e = q⁻¹ • (e * X)) (hfX : f * X = q⁻¹ • (X * f))
    (x : FreeAlgebra k Bool) (s : Space k) :
    monoMap k e X f (rep q false x s) =
      FreeAlgebra.lift k (fun b : Bool ↦ if b then f else e) x * monoMap k e X f s := by
  induction x using FreeAlgebra.induction generalizing s with
  | grade0 a =>
    rw [AlgHom.commutes, AlgHom.commutes, Module.algebraMap_end_apply, map_smul,
      Algebra.smul_def]
  | grade1 b =>
    cases b with
    | false =>
      change monoMap k e X f (rep q false (θ k false) s) = _
      rw [rep_θ_left, FreeAlgebra.lift_ι_apply, monoMap_opE]
      rfl
    | true =>
      change monoMap k e X f (rep q false (θ k true) s) = _
      rw [rep_θ_right (by decide : false ≠ true), FreeAlgebra.lift_ι_apply,
        monoMap_opF hfe hXe hfX]
      rfl
  | mul a b ha hb =>
    rw [map_mul, Module.End.mul_apply, ha, hb, map_mul, mul_assoc]
  | add a b ha hb =>
    rw [map_add, LinearMap.add_apply, map_add, ha, hb, map_add, add_mul]

/-- Quadratic Serre relations give ordered spanning of the two-generator subalgebra,
inside any ambient algebra, without an assumption that these are all its generators. -/
theorem span_mono_qComm_eq_adjoin (hq : q ≠ 0)
    (hS : qSerre q 2 e f = 0) (hS' : qSerre q 2 f e = 0) :
    Submodule.span k (Set.range (mono e (qComm q e f) f)) =
      (Algebra.adjoin k {e, f}).toSubmodule := by
  have hpair : Set.range (fun b : Bool ↦ if b then f else e) = {e, f} := by
    ext x
    simp only [Set.mem_range, Set.mem_insert_iff, Set.mem_singleton_iff]
    constructor
    · rintro ⟨b, rfl⟩
      cases b <;> simp
    · rintro (rfl | rfl)
      · exact ⟨false, rfl⟩
      · exact ⟨true, rfl⟩
  refine le_antisymm (Submodule.span_le.mpr ?_) ?_
  · rintro _ ⟨p, rfl⟩
    change mono e (qComm q e f) f p ∈ Algebra.adjoin k {e, f}
    have he : e ∈ Algebra.adjoin k {e, f} := Algebra.subset_adjoin (by simp)
    have hf : f ∈ Algebra.adjoin k {e, f} := Algebra.subset_adjoin (by simp)
    have hX : qComm q e f ∈ Algebra.adjoin k {e, f} :=
      sub_mem (mul_mem he hf) (Subalgebra.smul_mem _ (mul_mem hf he) _)
    exact mul_mem (mul_mem (pow_mem he _) (pow_mem hX _)) (pow_mem hf _)
  · rw [← hpair, Algebra.adjoin_range_eq_range_freeAlgebra_lift]
    rintro _ ⟨x, rfl⟩
    change FreeAlgebra.lift k (fun b : Bool ↦ if b then f else e) x ∈ _
    have hx := monoMap_pair_rep (mul_eq_qComm hq e f)
      (qComm_mul_left_of_qSerre hq hS) (mul_qComm_right_of_qSerre hq hS')
      x (Finsupp.single (0, 0, 0) 1)
    rw [monoMap_single_zero, mul_one] at hx
    rw [← hx, monoMap, ← Finsupp.range_linearCombination]
    exact LinearMap.mem_range_self _ _
end A2PBW

variable {k I Y : Type*} [Field k] [AddCommGroup Y] [DecidableEq I]
  {D : LusztigCartanDatum I} (R : D.RootDatum Y) (v : k) [NeZero v]
  {i j : I} (hij : i ≠ j) (h : D.cartanMatrix i j = -1)
  (h' : D.cartanMatrix j i = -1)

include hij h h'

/-- Local A₂ ordered spanning in an arbitrary ambient Cartan datum. Only the two
Cartan entries and a nonzero parameter are required; other nodes are unrestricted. -/
theorem span_a2PBWMono_pair :
    Submodule.span k (Set.range (a2PBWMono R v i j)) =
      (Algebra.adjoin k {E R v i, E R v j}).toSubmodule := by
  have hS := serre_E R v hij
  have hS' := serre_E R v hij.symm
  rw [A2PBW.toNat_one_sub_eq_two h] at hS
  rw [A2PBW.toNat_one_sub_eq_two h', ← D.d_eq_of_simply_laced_edge h h'] at hS'
  change Submodule.span k
    (Set.range (A2PBW.mono (E R v i) (braidEj R v i j) (E R v j))) = _
  rw [a2_braidEj_eq_qComm h]
  exact A2PBW.span_mono_qComm_eq_adjoin (pow_ne_zero _ (NeZero.ne v)) hS hS'

/-- Reversing the simple-edge orientation preserves the local ordered-monomial span. -/
theorem span_a2PBWMono_pair_reverse :
    Submodule.span k (Set.range (a2PBWMono R v i j)) =
      Submodule.span k (Set.range (a2PBWMono R v j i)) := by
  rw [span_a2PBWMono_pair R v hij h h', span_a2PBWMono_pair R v hij.symm h' h,
    Set.pair_comm]
end QuantumGroup
