/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.GroupTheory.Coxeter.RankTwoParabolic
import Mathlib.RingTheory.Adjoin.Basic

/-!
# Braid group operators map simple root vectors into `U⁺`: the reduction to rank two

Let `(W, S)` be a Coxeter system with Coxeter matrix `M`, and let `Tᵢ` (`i ∈ B`) be algebra
automorphisms of an algebra `A` satisfying the braid relations of `M`, so that
`T_w = T_{i₁} ⋯ T_{iₖ}` is well defined for any reduced expression `w = s_{i₁} ⋯ s_{iₖ}`
(Matsumoto's theorem, `CoxeterSystem.braidLift`). Let `Eᵢ ∈ A`. We show
(`CoxeterSystem.braidLift_apply_mem_adjoin`): if the rank-two statement holds, then for every
`w ∈ W` and `i` with `ℓ(w sᵢ) > ℓ(w)`,

* `T_w(Eᵢ)` lies in the subalgebra generated by the `Eⱼ`, and
* `T_w(Eᵢ) = Eⱼ` whenever `w sᵢ w⁻¹ = sⱼ` (i.e. `w αᵢ = αⱼ` for the corresponding roots).

The rank-two statement (`CoxeterMatrix.RankTwoRootProperty`) asks, for `i ≠ k` and the alternating
products `u = ⋯ sᵢ sₖ` of length `n < mᵢₖ`, that `T_u(Eᵢ)` lie in the subalgebra generated by `Eᵢ`
and `Eₖ`, and that `T_u(Eᵢ) = Eₗ` for `n = mᵢₖ - 1`, where `sₗ` is the simple reflection not at the
start of `u`. For Lusztig's braid group operators on `U_v(𝔤)` this is verified in
`LieLean/Algebra/QuantumGroup/PBW/RootVectorsQuantum.lean`.

The proof is the standard induction on `ℓ(w)` ([Jan] 8.20, [Lus] 40.1.2): choose
a right descent `k` of `w`, write `w = w' u` with `w'` minimal in `w W_{i,k}` and `u ∈ W_{i,k}`,
so that `T_w = T_{w'} T_u`, apply the rank-two statement to `u` and the induction hypothesis to
`w'`; for the second assertion, `w' (u sᵢ u⁻¹) w'⁻¹ = sⱼ` and length additivity force
`u sᵢ u⁻¹` to be a simple reflection. The argument is our own; it uses
only Coxeter combinatorics, no root system.

## Main definitions / results

* `CoxeterMatrix.RankTwoRootProperty`: the rank-two hypothesis.
* `CoxeterSystem.braidLift_apply_mem_adjoin`: the general statement.
* `CoxeterSystem.rootVector`, `CoxeterSystem.rootVector_mem_adjoin`: the root vectors
  `E_{βₙ} = T_{i₁} ⋯ T_{i_{n-1}}(E_{iₙ})` along a reduced word lie in the subalgebra generated by
  the `Eⱼ` (for a reduced word of the longest element in finite type these are the root vectors of
  [Jan] 8.21, [Lus] 40.1).

## References

* [Jan] J. C. Jantzen, *Lectures on quantum groups*, GSM 6, Prop. 8.20.
* [Lus] G. Lusztig, *Introduction to quantum groups*, Lemma 40.1.2, Prop. 40.1.3.
-/

namespace CoxeterMatrix

open CoxeterSystem

variable {B : Type*} (M : CoxeterMatrix B) {k A : Type*} [CommSemiring k] [Semiring A]
  [Algebra k A]

/-- **The rank-two root vector property** of algebra automorphisms `Tᵢ` and elements `Eᵢ`: for
`i ≠ k` and the alternating word `u = ⋯ i k` of length `n < mᵢₖ`, `T_u(Eᵢ)` lies in the
subalgebra generated by `Eᵢ, Eₖ`, and for `n = mᵢₖ - 1` it equals `Eₗ`, where `l` is the letter
not at the start of the word. -/
structure RankTwoRootProperty (T : B → A ≃ₐ[k] A) (E : B → A) : Prop where
  mem : ∀ i j, i ≠ j → ∀ n, (M i j = 0 ∨ n < M i j) →
    ((alternatingWord i j n).map T).prod (E i) ∈ Algebra.adjoin k {E i, E j}
  eq : ∀ i j, i ≠ j → ∀ n, n + 1 = M i j →
    ((alternatingWord i j n).map T).prod (E i) = E (if Even n then j else i)

end CoxeterMatrix

namespace CoxeterSystem

open List

variable {B W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)
  {k A : Type*} [CommSemiring k] [Semiring A] [Algebra k A]

local prefix:100 "s " => cs.simple
local prefix:100 "π " => cs.wordProd
local prefix:100 "ℓ " => cs.length

variable {cs} {T : B → A ≃ₐ[k] A} {E : B → A}

/-- The induction behind `braidLift_apply_mem_adjoin`, by length. -/
private theorem braidLift_apply_mem_adjoin_aux (hT : M.IsBraidLiftable T)
    (hR : M.RankTwoRootProperty T E) (n : ℕ) :
    ∀ w, ℓ w = n → ∀ i, ¬cs.IsRightDescent w i →
      cs.braidLift T w (E i) ∈ Algebra.adjoin k (Set.range E) ∧
        ∀ j, w * s i = s j * w → cs.braidLift T w (E i) = E j := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
  intro w hw i hwi
  by_cases h1 : w = 1
  · subst h1
    refine ⟨?_, fun j hj ↦ ?_⟩
    · rw [braidLift_one, AlgEquiv.one_apply]
      exact Algebra.subset_adjoin ⟨i, rfl⟩
    · rw [one_mul, mul_one] at hj
      rw [braidLift_one, AlgEquiv.one_apply, cs.simple_injective hj]
  obtain ⟨k₀, hk⟩ := cs.exists_rightDescent_of_ne_one h1
  have hki : i ≠ k₀ := by rintro rfl; exact hwi hk
  set J : Set B := {i, k₀} with hJ
  obtain ⟨w', hw', u, hu, rfl⟩ := cs.exists_mem_minCosetReps_mul_eq J w
  have hlen := length_mul_of_mem_minCosetReps hw' hu
  have hu1 : u ≠ 1 := by
    rintro rfl
    rw [mul_one] at hk
    exact hw' k₀ (by simp [hJ]) hk
  have hlu : 0 < ℓ u := Nat.pos_of_ne_zero fun h ↦ hu1 (cs.length_eq_zero_iff.mp h)
  have hlt : ℓ w' < n := by omega
  have hw'i : ¬cs.IsRightDescent w' i := hw' i (by simp [hJ])
  have hw'k : ¬cs.IsRightDescent w' k₀ := hw' k₀ (by simp [hJ])
  -- `u` has no right descent `i`
  have hui : ¬cs.IsRightDescent u i := by
    have h2 := length_mul_of_mem_minCosetReps hw'
      (Subgroup.mul_mem _ hu (simple_mem_parabolicSubgroup (show i ∈ J by simp [hJ])))
    rw [cs.not_isRightDescent_iff, mul_assoc, h2, hlen] at hwi
    rw [cs.not_isRightDescent_iff]
    omega
  have hsplit : cs.braidLift T (w' * u) = cs.braidLift T w' * cs.braidLift T u :=
    braidLift_mul hT hlen
  obtain ⟨m, hm, rfl⟩ := exists_eq_wordProd_alternatingWord hki hu hui
  have hred := cs.isReduced_alternatingWord i k₀ (k := m) (by omega)
  have hTu : cs.braidLift T (π (alternatingWord i k₀ m)) =
      ((alternatingWord i k₀ m).map T).prod := braidLift_wordProd hT hred
  have ihi := ih _ hlt w' rfl i hw'i
  have ihk := ih _ hlt w' rfl k₀ hw'k
  refine ⟨?_, fun j hj ↦ ?_⟩
  · -- membership
    rw [hsplit, AlgEquiv.mul_apply, hTu]
    have hle : Algebra.adjoin k {E i, E k₀} ≤
        (Algebra.adjoin k (Set.range E)).comap (cs.braidLift T w').toAlgHom := by
      rw [Algebra.adjoin_le_iff, Set.insert_subset_iff, Set.singleton_subset_iff]
      exact ⟨ihi.1, ihk.1⟩
    exact hle (hR.mem i k₀ hki m hm)
  · -- the simple case: `u sᵢ u⁻¹` is a simple reflection
    set u := π (alternatingWord i k₀ m) with hu_def
    set t := u * s i * u⁻¹ with ht_def
    have ht : t ∈ cs.parabolicSubgroup J :=
      Subgroup.mul_mem _ (Subgroup.mul_mem _ hu (simple_mem_parabolicSubgroup (by simp [hJ])))
        (Subgroup.inv_mem _ hu)
    have hwt : w' * t = s j * w' := by
      calc w' * t = w' * u * s i * u⁻¹ := by rw [ht_def]; group
        _ = s j * w' := by rw [hj]; group
    have hlt' := length_mul_of_mem_minCosetReps hw' ht
    have ht1 : t ≠ 1 := by
      intro h
      rw [ht_def, mul_inv_eq_one, mul_eq_left] at h
      have := cs.length_simple i
      rw [h, length_one] at this
      exact absurd this (by norm_num)
    have hlt1 : ℓ t = 1 := by
      have := cs.length_simple_mul w' j
      have h0 : 0 < ℓ t := Nat.pos_of_ne_zero fun h ↦ ht1 (cs.length_eq_zero_iff.mp h)
      rw [← hwt, hlt'] at this
      omega
    obtain ⟨ω, hωred, hωJ, hωe⟩ := exists_isReduced_of_mem_parabolicSubgroup ht
    have hωlen : ω.length = 1 := by rw [← hωred.eq, hωe, hlt1]
    obtain ⟨l, rfl⟩ := List.length_eq_one_iff.mp hωlen
    rw [wordProd_singleton] at hωe
    have hlJ : l ∈ J := hωJ l (by simp)
    have hul : u * s i = s l * u := by
      rw [hωe, ht_def, inv_mul_cancel_right]
    rcases eq_of_alternatingWord_mul_simple_eq hki hm hul with ⟨rfl, -⟩ | ⟨hm1, hl⟩
    · exact absurd rfl hu1
    rw [hsplit, AlgEquiv.mul_apply, hTu, hR.eq i k₀ hki m hm1, ← hl]
    have hw'l : ¬cs.IsRightDescent w' l := hw' l hlJ
    refine (ih _ hlt w' rfl l hw'l).2 j ?_
    rw [hωe]; exact hwt

/-- **Braid group operators map simple root vectors into the subalgebra generated by the `Eⱼ`**
([Jan] Prop. 8.20, [Lus] 40.1.2): if the `Tᵢ` satisfy the braid relations and the
rank-two root vector property, then for `w ∈ W` and `i` with `ℓ(w sᵢ) > ℓ(w)`, `T_w(Eᵢ)` lies in
the subalgebra generated by the `Eⱼ`, and `T_w(Eᵢ) = Eⱼ` if `w sᵢ = sⱼ w`. -/
theorem braidLift_apply_mem_adjoin (hT : M.IsBraidLiftable T) (hR : M.RankTwoRootProperty T E)
    {w : W} {i : B} (hwi : ¬cs.IsRightDescent w i) :
    cs.braidLift T w (E i) ∈ Algebra.adjoin k (Set.range E) :=
  (braidLift_apply_mem_adjoin_aux hT hR _ w rfl i hwi).1

/-- **Simple roots are sent to simple root vectors** ([Jan] Prop. 8.20, cf. [Lus] 39.2
in rank two): if `ℓ(w sᵢ) > ℓ(w)` and `w sᵢ w⁻¹ = sⱼ` (i.e. `w αᵢ = αⱼ`), then `T_w(Eᵢ) = Eⱼ`. -/
theorem braidLift_apply_eq_of_mul_simple_eq (hT : M.IsBraidLiftable T)
    (hR : M.RankTwoRootProperty T E) {w : W} {i j : B} (hwi : ¬cs.IsRightDescent w i)
    (h : w * s i = s j * w) : cs.braidLift T w (E i) = E j :=
  (braidLift_apply_mem_adjoin_aux hT hR _ w rfl i hwi).2 j h

variable (T E) in
/-- The `n`-th root vector `E_{β_{n+1}} = T_{i₁} ⋯ T_{iₙ}(E_{i_{n+1}})` along a word
`ω = i₁ i₂ ⋯` ([Jan] 8.21, [Lus] 40.1.3). For a reduced word of the longest element
of a finite Weyl group these are the root vectors of the PBW basis. -/
def rootVector (ω : List B) (n : ℕ) (hn : n < ω.length) : A :=
  ((ω.take n).map T).prod (E ω[n])

/-- The root vectors along a reduced word lie in the subalgebra generated by the `Eⱼ`. -/
theorem rootVector_mem_adjoin (hT : M.IsBraidLiftable T) (hR : M.RankTwoRootProperty T E)
    {ω : List B} (hω : cs.IsReduced ω) (n : ℕ) (hn : n < ω.length) :
    rootVector T E ω n hn ∈ Algebra.adjoin k (Set.range E) := by
  have hred : cs.IsReduced (ω.take n) := hω.take n
  have hred' : cs.IsReduced (ω.take (n + 1)) := hω.take (n + 1)
  have hsplit : ω.take (n + 1) = ω.take n ++ [ω[n]] := by
    rw [List.take_add_one, List.getElem?_eq_getElem hn]
    rfl
  have hwi : ¬cs.IsRightDescent (π (ω.take n)) ω[n] := by
    rw [cs.not_isRightDescent_iff, ← wordProd_singleton, ← wordProd_append, ← hsplit, hred'.eq,
      hred.eq]
    simp [List.length_take]
    omega
  have := braidLift_apply_mem_adjoin hT hR hwi
  rwa [braidLift_wordProd hT hred] at this

end CoxeterSystem
