/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.BraidAction.FiniteCartanArtin
import LieLean.Algebra.QuantumGroup.BraidAction.GeneralArtin
import LieLean.Algebra.QuantumGroup.PBW.RankTwoInfinite
import LieLean.Algebra.QuantumGroup.PBW.RankTwoRootVectors
import LieLean.Algebra.QuantumGroup.PBW.RootVectors
import LieLean.GroupTheory.Coxeter.Longest
import LieLean.LinearAlgebra.Matrix.Cartan.FiniteRankTwo

/-!
# Lusztig's braid group operators map simple root vectors into `U⁺`

Let `D` be a Cartan datum, `W` a Coxeter group with the Coxeter matrix of `D` (e.g. the Weyl group
of a realization), and `T_w = T_{i₁} ⋯ T_{iₖ}` (reduced expression, Matsumoto's theorem) the
products of Lusztig's automorphisms `Tᵢ = braidEquivOfGeneric` of `U = U_v(𝔤)`. We prove
([Jan] Prop. 8.20 in finite type, [Lus] Lemma 40.1.2, Prop. 40.1.3): if `ℓ(w sᵢ) > ℓ(w)`,
i.e. `w αᵢ > 0`, then

* `T_w(Eᵢ)` lies in `U⁺`, the subalgebra generated by the `Eⱼ`
  (`QuantumGroup.braidLift_E_mem_adjoin`);
* `T_w(Eᵢ) = Eⱼ` whenever `w sᵢ w⁻¹ = sⱼ`, i.e. `w αᵢ = αⱼ` (`QuantumGroup.braidLift_E_eq`);
* consequently the root vectors `E_{βₙ} = T_{i₁} ⋯ T_{iₙ₋₁}(E_{iₙ})` along any reduced word lie
  in `U⁺` (`QuantumGroup.rootVector_mem_adjoin_of_isReduced`); for a reduced word of the longest
  element of a finite Weyl group these are the root vectors of the PBW basis ([Jan] 8.21,
  [Lus] 40.1.3, 40.2.2).

The hypotheses are those of the Artin group action `braidArtinHom` (`v ≠ 0`, `vᵢ - vᵢ⁻¹ ≠ 0`,
`BraidSerreGeneric`, `[3]ᵢ! ≠ 0`, `BraidOuterCondition`); there is no condition on the rank-two
subdiagrams. The general induction is `CoxeterSystem.braidLift_apply_mem_adjoin`
(`PBW/RootVectors.lean`); here we verify its rank-two hypothesis
(`QuantumGroup.rankTwoRootProperty_braidEquivOfGeneric`) from the rank-two computations of
`PBW/RankTwoRootVectors.lean` and `BraidAction/TripleEdgeRelation.lean` (`aᵢₖ aₖᵢ ≤ 3`) and of
`PBW/RankTwoInfinite.lean` (`aᵢₖ aₖᵢ ≥ 4`, [Lus] Lemma 40.1.1 for `h = ∞`): for each pair `i ≠ k`
the elements `⋯ Tᵢ Tₖ (Eᵢ)` along the alternating words of length `< mᵢₖ` lie in the subalgebra
generated by `Eᵢ, Eₖ`, and the one of length `mᵢₖ - 1` is a simple root vector.

## Main results

* `QuantumGroup.rankTwoRootProperty_braidEquivOfGeneric`: the rank-two hypothesis.
* `QuantumGroup.braidLift_E_mem_adjoin`, `QuantumGroup.braidLift_E_eq`,
  `QuantumGroup.rootVector_mem_adjoin_of_isReduced`: the statements above.
* `QuantumGroup.exists_longestElement_rootVectors_mem_adjoin_of_isFiniteCartan` (and
  `_of_not_root`): the root vectors along a reduced word of `w₀` in finite type; here
  `BraidOuterCondition` is derived from `Matrix.IsFiniteCartan`.
* `_of_not_root` versions for `Tᵢ = braidEquivOfNotRoot` (`v` not a root of unity); those of
  `braidLift_E_mem_adjoin`, `braidLift_E_eq`, `rootVector_mem_adjoin_of_isReduced` are in
  `PBW/RootVectorsNotRoot.lean`, without `BraidOuterCondition`.

## References

* [Jan] J. C. Jantzen, *Lectures on quantum groups*, GSM 6, Prop. 8.20, §8.21.
* [Lus] G. Lusztig, *Introduction to quantum groups*, Lemma 40.1.2, Prop. 40.1.3.

The rank-two computations are our own reconstruction from the lowering identities of the
repository.
-/

open LieLean

noncomputable section

namespace LieLean.QuantumGroup

open BraidDiagonal CoxeterSystem

variable {k : Type*} [Field k] {I Y : Type*} [AddCommGroup Y] [DecidableEq I]
  {D : LusztigCartanDatum I} {R : D.RootDatum Y} {v : k}

/-! ### Membership in a subalgebra containing two generators -/

section Membership

variable {P : Subalgebra k (QuantumGroup R v)}

lemma serreAux_mem {q c : k} {m : ℕ} {a b : QuantumGroup R v} (ha : a ∈ P) (hb : b ∈ P) :
    serreAux q c m a b ∈ P :=
  Subalgebra.sum_mem _ fun _ _ ↦
    Subalgebra.smul_mem _ (mul_mem (mul_mem (pow_mem ha _) hb) (pow_mem ha _)) _

lemma braidEj_mem {a b : I} (ha : E R v a ∈ P) (hb : E R v b ∈ P) : braidEj R v a b ∈ P :=
  Subalgebra.smul_mem _ (serreAux_mem ha hb) _

lemma X_mem {q Q : k} {a b : QuantumGroup R v} (ha : a ∈ P) (hb : b ∈ P) (n : ℕ) :
    X q Q a b n ∈ P := by
  induction n with
  | zero => exact hb
  | succ n ih =>
    rw [X_succ]
    exact sub_mem (mul_mem ha ih) (Subalgebra.smul_mem _ (mul_mem ih ha) _)

/-- If `T(a)` and `T(X 1)` lie in `P`, so do all `T(X (n+1))`. -/
lemma map_X_mem {T : QuantumGroup R v →ₐ[k] QuantumGroup R v} {q Q : k}
    {a b : QuantumGroup R v} (ha : T a ∈ P) (h1 : T (X q Q a b 1) ∈ P) (n : ℕ) :
    T (X q Q a b (n + 1)) ∈ P := by
  induction n with
  | zero => exact h1
  | succ n ih =>
    rw [X_succ, map_sub, map_mul, map_smul, map_mul]
    exact sub_mem (mul_mem ha ih) (Subalgebra.smul_mem _ (mul_mem ih ha) _)

end Membership

/-! ### The rank-two computations

`S`, `T` are algebra endomorphisms with Lusztig's generator formulas at `i`, `j`, and `P` is the
subalgebra generated by `Eᵢ, Eⱼ`. -/

section RankTwo

variable {i j : I} {S T : QuantumGroup R v →ₐ[k] QuantumGroup R v}

local notation "P" => Algebra.adjoin k ({E R v i, E R v j} : Set (QuantumGroup R v))

lemma E_mem_pair_left : E R v i ∈ P := Algebra.subset_adjoin (by simp)

lemma E_mem_pair_right : E R v j ∈ P := Algebra.subset_adjoin (by simp)

lemma map_E_mem_pair (HT : HasBraidGeneratorImages j T) (hij : i ≠ j) : T (E R v i) ∈ P := by
  rw [HT.map_E, ite_eq_right hij]
  exact braidEj_mem E_mem_pair_right E_mem_pair_left

/-- Type `A₂`: `Tⱼ(Eᵢ) ∈ ⟨Eᵢ, Eⱼ⟩` and `TᵢTⱼ(Eᵢ) = Eⱼ`. -/
lemma a2_words [NeZero v] (HS : HasBraidGeneratorImages i S) (HT : HasBraidGeneratorImages j T)
    (hij : i ≠ j) (h : D.cartanMatrix i j = -1) (h' : D.cartanMatrix j i = -1)
    (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) :
    T (E R v i) ∈ P ∧ S (T (E R v i)) = E R v j :=
  ⟨map_E_mem_pair HT hij, a2_rootVector_three HS HT hij h h' hq⟩

section B2

variable [NeZero v] (HS : HasBraidGeneratorImages i S) (HT : HasBraidGeneratorImages j T)
  (hij : i ≠ j) (h : D.cartanMatrix i j = -2) (h' : D.cartanMatrix j i = -1)
  (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) (h2 : qFactorial (v ^ D.d i) 2 ≠ 0)

include HS HT hij h h' hq h2 in
/-- Type `B₂`, words starting at the short node `i`:
`Tⱼ(Eᵢ), TᵢTⱼ(Eᵢ) ∈ ⟨Eᵢ, Eⱼ⟩` and `TⱼTᵢTⱼ(Eᵢ) = Eᵢ`. -/
lemma b2_words_short :
    T (E R v i) ∈ P ∧ S (T (E R v i)) ∈ P ∧ T (S (T (E R v i))) = E R v i := by
  have hq0 : v ^ D.d i ≠ 0 := pow_ne_zero _ (NeZero.ne v)
  refine ⟨map_E_mem_pair HT hij, ?_, ?_⟩
  · rw [b2_rootVector_three HS HT hij h h' hq]
    exact Subalgebra.smul_mem _ (X_mem E_mem_pair_left E_mem_pair_right 1) _
  · rw [b2_rootVector_three HS HT hij h h' hq, map_smul, b2_T_X_one HT hij h h' hq h2,
      b2_cc_two hq0 hq]
    rw [b2_qFactorial_two hq0] at h2 ⊢
    rw [inv_mul_cancel₀ h2, one_smul]

include HS HT hij h h' hq h2 in
/-- Type `B₂`, words starting at the long node `j`:
`Tᵢ(Eⱼ), TⱼTᵢ(Eⱼ) ∈ ⟨Eᵢ, Eⱼ⟩` and `TᵢTⱼTᵢ(Eⱼ) = Eⱼ`. -/
lemma b2_words_long :
    S (E R v j) ∈ P ∧ T (S (E R v j)) ∈ P ∧ S (T (S (E R v j))) = E R v j := by
  refine ⟨?_, ?_, b2_rootVector_four HS HT hij h h' hq h2⟩
  · rw [b2_rootVector_two HS hij h]
    exact Subalgebra.smul_mem _ (X_mem E_mem_pair_left E_mem_pair_right 2) _
  · rw [b2_rootVector_two HS hij h, map_smul]
    refine Subalgebra.smul_mem _ (map_X_mem (map_E_mem_pair HT hij) ?_ 1) _
    rw [b2_T_X_one HT hij h h' hq h2]
    exact E_mem_pair_left

end B2

section G2

variable [NeZero v] (HS : HasBraidGeneratorImages i S) (HT : HasBraidGeneratorImages j T)
  (hij : i ≠ j) (h : D.cartanMatrix i j = -3) (h' : D.cartanMatrix j i = -1)
  (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) (h3 : qFactorial (v ^ D.d i) 3 ≠ 0)

include HT hij h h' hq h3 in
lemma g2_map_X_mem (n : ℕ) :
    T (X (v ^ D.d i) ((v ^ D.d i) ^ 3) (E R v i) (E R v j) (n + 1)) ∈ P := by
  refine map_X_mem (map_E_mem_pair HT hij) ?_ n
  rw [tripleSix_T_X_one HT hij h h' hq h3]
  exact E_mem_pair_left

include HS HT hij h h' hq h3 in
/-- Type `G₂`, words starting at the short node `i`: the first four elements
`Tⱼ(Eᵢ), …, TᵢTⱼTᵢTⱼ(Eᵢ)` lie in `⟨Eᵢ, Eⱼ⟩` and `TⱼTᵢTⱼTᵢTⱼ(Eᵢ) = Eᵢ`. -/
lemma g2_words_short :
    T (E R v i) ∈ P ∧ S (T (E R v i)) ∈ P ∧ T (S (T (E R v i))) ∈ P ∧
      S (T (S (T (E R v i)))) ∈ P ∧ T (S (T (S (T (E R v i))))) = E R v i := by
  refine ⟨map_E_mem_pair HT hij, ?_, ?_, ?_, tripleSix_Ei HS HT hij h h' hq h3⟩
  · rw [tripleSix_T_Ei HT hij, tripleSix_S_Yv HS hij h h' hq]
    exact Subalgebra.smul_mem _ (X_mem E_mem_pair_left E_mem_pair_right 2) _
  · rw [tripleSix_T_Ei HT hij, tripleSix_S_Yv HS hij h h' hq, map_smul]
    exact Subalgebra.smul_mem _ (g2_map_X_mem HT hij h h' hq h3 1) _
  · rw [tripleSix_T_Ei HT hij, tripleSix_S_Yv HS hij h h' hq, map_smul, map_smul,
      tripleSix_S_TX2 HS HT hij h h' hq h3]
    exact Subalgebra.smul_mem _ (Subalgebra.smul_mem _
      (X_mem E_mem_pair_left E_mem_pair_right 1) _) _

include HS HT hij h h' hq h3 in
/-- Type `G₂`, words starting at the long node `j`: the first four elements
`Tᵢ(Eⱼ), …, TⱼTᵢTⱼTᵢ(Eⱼ)` lie in `⟨Eᵢ, Eⱼ⟩` and `TᵢTⱼTᵢTⱼTᵢ(Eⱼ) = Eⱼ`. -/
lemma g2_words_long :
    S (E R v j) ∈ P ∧ T (S (E R v j)) ∈ P ∧ S (T (S (E R v j))) ∈ P ∧
      T (S (T (S (E R v j)))) ∈ P ∧ S (T (S (T (S (E R v j))))) = E R v j := by
  refine ⟨?_, ?_, ?_, ?_, tripleSix_Ej HS HT hij h h' hq h3⟩
  · rw [tripleSix_S_Ej HS hij h]
    exact Subalgebra.smul_mem _ (X_mem E_mem_pair_left E_mem_pair_right 3) _
  · rw [tripleSix_S_Ej HS hij h, map_smul]
    exact Subalgebra.smul_mem _ (g2_map_X_mem HT hij h h' hq h3 2) _
  · rw [tripleSix_S_Ej HS hij h, map_smul, map_smul, tripleSix_T_X_succ HT hij 2, map_sub,
      map_mul, map_smul, map_mul, tripleSix_S_Yv HS hij h h' hq,
      tripleSix_S_TX2 HS HT hij h h' hq h3]
    refine Subalgebra.smul_mem _ (sub_mem (mul_mem ?_ ?_) (Subalgebra.smul_mem _
      (mul_mem ?_ ?_) _)) _ <;>
      exact Subalgebra.smul_mem _ (X_mem E_mem_pair_left E_mem_pair_right _) _
  · simp only [tripleSix_S_Ej HS hij h, map_smul, tripleSix_T_X_succ HT hij 2, map_sub,
      map_mul, tripleSix_S_Yv HS hij h h' hq, tripleSix_S_TX2 HS HT hij h h' hq h3]
    repeat' first | apply Subalgebra.smul_mem | apply sub_mem | apply mul_mem
    · exact g2_map_X_mem HT hij h h' hq h3 1
    · exact g2_map_X_mem HT hij h h' hq h3 0
    · exact g2_map_X_mem HT hij h h' hq h3 0
    · exact g2_map_X_mem HT hij h h' hq h3 1

end G2

end RankTwo

/-! ### The rank-two property and the general theorem -/

variable [NeZero v] (hq : ∀ i, v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0)
  (hS : ∀ i, BraidSerreGeneric D v i) (h3 : ∀ i, qFactorial (v ^ D.d i) 3 ≠ 0)
  (hD : D.BraidOuterCondition)

omit [DecidableEq I] [NeZero v] in
/-- The possible pairs of off-diagonal entries `(aᵢⱼ, aⱼᵢ)` with `aᵢⱼ aⱼᵢ ≤ 3`. -/
lemma cartan_pair_cases {i j : I} (hij : i ≠ j)
    (hfin : D.cartanMatrix i j * D.cartanMatrix j i ≤ 3) :
    (D.cartanMatrix i j = 0 ∧ D.cartanMatrix j i = 0) ∨
    (D.cartanMatrix i j = -1 ∧ D.cartanMatrix j i = -1) ∨
    (D.cartanMatrix i j = -2 ∧ D.cartanMatrix j i = -1) ∨
    (D.cartanMatrix i j = -1 ∧ D.cartanMatrix j i = -2) ∨
    (D.cartanMatrix i j = -3 ∧ D.cartanMatrix j i = -1) ∨
    (D.cartanMatrix i j = -1 ∧ D.cartanMatrix j i = -3) := by
  have hA := D.isGeneralizedCartan_cartanMatrix
  have hx := hA.offDiag_nonpos i j hij
  have hy := hA.offDiag_nonpos j i hij.symm
  by_cases h0 : D.cartanMatrix i j = 0
  · exact Or.inl ⟨h0, (hA.zero_comm i j).1 h0⟩
  have h0' : D.cartanMatrix j i ≠ 0 := fun h ↦ h0 ((hA.zero_comm i j).2 h)
  have e1 : -3 ≤ D.cartanMatrix i j := by
    nlinarith [mul_nonneg_of_nonpos_of_nonpos hx (show D.cartanMatrix j i + 1 ≤ 0 by omega)]
  have e2 : -3 ≤ D.cartanMatrix j i := by
    nlinarith [mul_nonneg_of_nonpos_of_nonpos hy (show D.cartanMatrix i j + 1 ≤ 0 by omega)]
  right
  interval_cases hi : D.cartanMatrix i j <;> interval_cases hj : D.cartanMatrix j i <;> simp_all

include hq hS in
/-- The general `Tₗ` have Lusztig's generator formulas. -/
lemma braidEquivOfGeneric_images (l : I) :
    HasBraidGeneratorImages l (braidEquivOfGeneric (R := R) (hq l) (hS l)).toAlgHom :=
  braidHom_hasBraidGeneratorImages (braidGeneric_of_braidSerreGeneric (hq l) (hS l))
    (transformedSerre_of_braidSerreGeneric (hq l) (hS l))

omit [DecidableEq I] [NeZero v] in
include hq hS in
lemma qFactorial_negA_ne {i j : I} (hij : j ≠ i) :
    qFactorial (v ^ D.d i) (negA D i j) ≠ 0 :=
  (braidGeneric_of_braidSerreGeneric (hq i) (hS i)).qFactorial_ne j hij

/-- **The rank-two root vector property** of Lusztig's `Tᵢ` (`braidEquivOfGeneric`) and the
`Eᵢ`, for the Coxeter matrix of any Cartan datum ([Jan] Lemma 8.19, [Lus] Lemma 40.1.1, rank
two): along the alternating words `⋯ Tᵢ Tₗ` of length `n < mᵢₗ`, the elements `⋯ Tᵢ Tₗ (Eᵢ)` lie
in the subalgebra generated by `Eᵢ, Eₗ`, and for `n = mᵢₗ - 1` they are simple root vectors. -/
theorem rankTwoRootProperty_braidEquivOfGeneric :
    D.cartanMatrix.coxeterMatrix.RankTwoRootProperty
      (fun i ↦ braidEquivOfGeneric (R := R) (hq i) (hS i)) (E R v) := by
  have HT := braidEquivOfGeneric_images (R := R) hq hS
  have h2 : ∀ {i l : I}, l ≠ i → D.cartanMatrix i l = -2 → qFactorial (v ^ D.d i) 2 ≠ 0 :=
    fun hli h ↦ by simpa [b2_negA h] using qFactorial_negA_ne hq hS hli
  have h3' : ∀ {i l : I}, l ≠ i → D.cartanMatrix i l = -3 → qFactorial (v ^ D.d i) 3 ≠ 0 :=
    fun hli h ↦ by simpa [tripleSix_negA h] using qFactorial_negA_ne hq hS hli
  constructor
  · intro i l hil n hn
    by_cases hfin : D.cartanMatrix i l * D.cartanMatrix l i ≤ 3
    swap
    · exact alternatingWord_prod_E_mem_adjoin_of_four_le HT hq hil hfin n
    rw [Matrix.coxeterMatrix_apply_of_ne _ hil] at hn
    have hl := E_mem_pair_left (k := k) (R := R) (v := v) (i := i) (j := l)
    have hr := E_mem_pair_right (k := k) (R := R) (v := v) (i := i) (j := l)
    rcases cartan_pair_cases hil hfin with ⟨h1, h1'⟩ | ⟨h1, h1'⟩ | ⟨h1, h1'⟩ |
      ⟨h1, h1'⟩ | ⟨h1, h1'⟩ | ⟨h1, h1'⟩ <;>
      simp only [h1, h1'] at hn <;> norm_num [Matrix.coxeterEntry] at hn <;>
      interval_cases n <;>
      simp only [alternatingWord, List.concat_eq_append, List.nil_append, List.cons_append,
        List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one,
        AlgEquiv.mul_apply, AlgEquiv.one_apply]
    all_goals first
      | exact hl
      | skip
    -- `A₁ × A₁`
    · rw [show (braidEquivOfGeneric (R := R) (hq l) (hS l)) (E R v i) = E R v i from
        a1a1_rootVector_two hil.symm h1' (HT l)]
      exact hl
    -- `A₂`
    · exact (a2_words (HT i) (HT l) hil h1 h1' (hq i)).1
    · rw [show (braidEquivOfGeneric (R := R) (hq i) (hS i))
          ((braidEquivOfGeneric (R := R) (hq l) (hS l)) (E R v i)) = E R v l from
        (a2_words (HT i) (HT l) hil h1 h1' (hq i)).2]
      exact hr
    -- `B₂`, `i` short
    · exact (b2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h2 hil.symm h1)).1
    · exact (b2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h2 hil.symm h1)).2.1
    · convert hl using 1
      exact (b2_words_short (HT i) (HT l) hil h1 h1' (hq i)
        (h2 hil.symm h1)).2.2
    -- `B₂`, `i` long
    · rw [Set.pair_comm]
      exact (b2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h2 hil h1')).1
    · rw [Set.pair_comm]
      exact (b2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h2 hil h1')).2.1
    · convert hl using 1
      exact (b2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l)
        (h2 hil h1')).2.2
    -- `G₂`, `i` short
    · exact (g2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h3' hil.symm h1)).1
    · exact (g2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h3' hil.symm h1)).2.1
    · exact (g2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h3' hil.symm h1)).2.2.1
    · exact (g2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h3' hil.symm h1)).2.2.2.1
    · convert hl using 1
      exact (g2_words_short (HT i) (HT l) hil h1 h1' (hq i)
        (h3' hil.symm h1)).2.2.2.2
    -- `G₂`, `i` long
    · rw [Set.pair_comm]
      exact (g2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h3' hil h1')).1
    · rw [Set.pair_comm]
      exact (g2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h3' hil h1')).2.1
    · rw [Set.pair_comm]
      exact (g2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h3' hil h1')).2.2.1
    · rw [Set.pair_comm]
      exact (g2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h3' hil h1')).2.2.2.1
    · convert hl using 1
      exact (g2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l)
        (h3' hil h1')).2.2.2.2
  · intro i l hil n hn
    rw [Matrix.coxeterMatrix_apply_of_ne _ hil] at hn
    by_cases hfin : D.cartanMatrix i l * D.cartanMatrix l i ≤ 3
    swap
    · rw [Matrix.coxeterEntry_of_four_le (by omega)] at hn
      omega
    rcases cartan_pair_cases hil hfin with ⟨h1, h1'⟩ | ⟨h1, h1'⟩ | ⟨h1, h1'⟩ |
      ⟨h1, h1'⟩ | ⟨h1, h1'⟩ | ⟨h1, h1'⟩ <;>
      simp only [h1, h1'] at hn <;> norm_num [Matrix.coxeterEntry] at hn <;>
      subst hn <;>
      simp only [alternatingWord, List.concat_eq_append, List.nil_append, List.cons_append,
        List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one,
        AlgEquiv.mul_apply] <;>
      norm_num
    · exact a1a1_rootVector_two hil.symm h1' (HT l)
    · exact (a2_words (HT i) (HT l) hil h1 h1' (hq i)).2
    · exact (b2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h2 hil.symm h1)).2.2
    · exact (b2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h2 hil h1')).2.2
    · exact (g2_words_short (HT i) (HT l) hil h1 h1' (hq i) (h3' hil.symm h1)).2.2.2.2
    · exact (g2_words_long (HT l) (HT i) hil.symm h1' h1 (hq l) (h3' hil h1')).2.2.2.2

/-! ### Main results -/

section Main

variable {W : Type*} [Group W] {cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W}

include h3 hD in
/-- **Braid group operators map simple root vectors into `U⁺`** ([Jan] Prop. 8.20,
[Lus] Lemma 40.1.2): if `ℓ(w sᵢ) > ℓ(w)` (i.e. `w αᵢ > 0`), then `T_w(Eᵢ) ∈ U⁺ = ⟨Eⱼ⟩`, where
`T_w = T_{i₁} ⋯ T_{iₖ}` for a reduced expression of `w` and `Tᵢ = braidEquivOfGeneric`. Here `W` is
any Coxeter group with the Coxeter matrix of `D`, e.g. the Weyl group of a realization; the
hypotheses are those of `braidArtinHom`. -/
theorem braidLift_E_mem_adjoin {w : W} {i : I} (hwi : ¬cs.IsRightDescent w i) :
    cs.braidLift (fun i ↦ braidEquivOfGeneric (R := R) (hq i) (hS i)) w (E R v i) ∈
      Algebra.adjoin k (Set.range (E R v)) :=
  braidLift_apply_mem_adjoin (isBraidLiftable_braidEquivOfGeneric hq hS h3 hD)
    (rankTwoRootProperty_braidEquivOfGeneric hq hS) hwi

include h3 hD in
/-- **Simple roots go to simple root vectors** ([Jan] Prop. 8.20, cf. [Lus] 39.2 in rank two): if
`ℓ(w sᵢ) > ℓ(w)` and `w sᵢ = sⱼ w` (i.e. `w αᵢ = αⱼ`), then `T_w(Eᵢ) = Eⱼ`. -/
theorem braidLift_E_eq {w : W} {i j : I} (hwi : ¬cs.IsRightDescent w i)
    (h : w * cs.simple i = cs.simple j * w) :
    cs.braidLift (fun i ↦ braidEquivOfGeneric (R := R) (hq i) (hS i)) w (E R v i) = E R v j :=
  braidLift_apply_eq_of_mul_simple_eq (isBraidLiftable_braidEquivOfGeneric hq hS h3 hD)
    (rankTwoRootProperty_braidEquivOfGeneric hq hS) hwi h

include h3 hD in
/-- **Root vectors lie in `U⁺`** ([Jan] 8.21, [Lus] Prop. 40.1.3): along a reduced
word `ω = i₁ i₂ ⋯` of the Coxeter group, the root vectors
`E_{βₙ₊₁} = T_{i₁} ⋯ T_{iₙ}(E_{iₙ₊₁})` lie in `U⁺`. For a reduced word of the longest element of a
finite Weyl group (`CoxeterSystem.longestElement`) these are the root vectors of the PBW basis. -/
theorem rootVector_mem_adjoin_of_isReduced {ω : List I} (hω : cs.IsReduced ω) (n : ℕ)
    (hn : n < ω.length) :
    CoxeterSystem.rootVector (fun i ↦ braidEquivOfGeneric (R := R) (hq i) (hS i)) (E R v) ω n hn ∈
      Algebra.adjoin k (Set.range (E R v)) :=
  CoxeterSystem.rootVector_mem_adjoin (isBraidLiftable_braidEquivOfGeneric hq hS h3 hD)
    (rankTwoRootProperty_braidEquivOfGeneric hq hS) hω n hn

include h3 hD in
/-- **The root vectors along a reduced word of `w₀`** ([Jan] 8.21, [Lus] 40.1.3):
for a finite Coxeter group with the Coxeter matrix of `D`, there is a reduced word of
the longest element `w₀` (of length `ℓ(w₀)`, the number of positive roots), and all root vectors
along any such word lie in `U⁺`. -/
theorem exists_longestElement_rootVectors_mem_adjoin [Finite W] :
    ∃ ω : List I, cs.IsReduced ω ∧ cs.wordProd ω = cs.longestElement ∧
      ∀ n (hn : n < ω.length),
        CoxeterSystem.rootVector (fun i ↦ braidEquivOfGeneric (R := R) (hq i) (hS i)) (E R v)
          ω n hn ∈ Algebra.adjoin k (Set.range (E R v)) := by
  obtain ⟨ω, hω, he⟩ := cs.exists_isReduced cs.longestElement
  exact ⟨ω, hω, he.symm, rootVector_mem_adjoin_of_isReduced hq hS h3 hD hω⟩

section FiniteType

variable [Fintype I]

include h3 in
/-- `braidLift_E_mem_adjoin` for a Cartan matrix of finite type (`Matrix.IsFiniteCartan`), which
implies `BraidOuterCondition`. -/
theorem braidLift_E_mem_adjoin_of_isFiniteCartan (hA : D.cartanMatrix.IsFiniteCartan) {w : W}
    {i : I} (hwi : ¬cs.IsRightDescent w i) :
    cs.braidLift (fun i ↦ braidEquivOfGeneric (R := R) (hq i) (hS i)) w (E R v i) ∈
      Algebra.adjoin k (Set.range (E R v)) :=
  braidLift_E_mem_adjoin hq hS h3 (LusztigCartanDatum.braidOuterCondition_of_isFiniteCartan hA)
    hwi

include h3 in
/-- **Finite type**: for a Cartan matrix of finite type and a finite Coxeter group `W` with its
Coxeter matrix (e.g. the Weyl group of a realization), the root vectors along a reduced word of
the longest element lie in `U⁺` ([Jan] 8.21, [Lus] 40.1.3). -/
theorem exists_longestElement_rootVectors_mem_adjoin_of_isFiniteCartan [Finite W]
    (hA : D.cartanMatrix.IsFiniteCartan) :
    ∃ ω : List I, cs.IsReduced ω ∧ cs.wordProd ω = cs.longestElement ∧
      ∀ n (hn : n < ω.length),
        CoxeterSystem.rootVector (fun i ↦ braidEquivOfGeneric (R := R) (hq i) (hS i)) (E R v)
          ω n hn ∈ Algebra.adjoin k (Set.range (E R v)) :=
  exists_longestElement_rootVectors_mem_adjoin hq hS h3
    (LusztigCartanDatum.braidOuterCondition_of_isFiniteCartan hA)

end FiniteType

end Main

section NotRoot

variable {W : Type*} [Group W] {cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W}
  (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1)

omit hq hS h3

/-- **Finite type, generic parameter**: for a Cartan matrix of finite type, `v` not a root of
unity and a finite Coxeter group `W` with its Coxeter matrix, the root vectors along a reduced
word of the longest element lie in `U⁺`; no hypothesis on the diagram is needed. -/
theorem exists_longestElement_rootVectors_mem_adjoin_of_isFiniteCartan_of_not_root [Fintype I]
    [Finite W] (hA : D.cartanMatrix.IsFiniteCartan) :
    ∃ ω : List I, cs.IsReduced ω ∧ cs.wordProd ω = cs.longestElement ∧
      ∀ n (hn : n < ω.length),
        CoxeterSystem.rootVector (braidEquivOfNotRoot R hv') (E R v) ω n hn ∈
          Algebra.adjoin k (Set.range (E R v)) :=
  exists_longestElement_rootVectors_mem_adjoin_of_isFiniteCartan
    (fun i ↦ (shortNode_braidGeneric_of_not_root hv' i).sub_ne)
    (braidSerreGeneric_of_not_root hv')
    (fun i ↦ LusztigF.qFactorial_ne_zero_of_not_root (NeZero.ne v) hv' i 3) hA

end NotRoot

end LieLean.QuantumGroup
