/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.PBW.SimplyLacedLongestSpan
import LieLean.Algebra.QuantumGroup.PBW.NegativeBasis

/-!
# Simply-laced quantum PBW bases at non-root-of-unity parameters

## Main results

* `simplyLacedPBWBasis`: the actual positive PBW basis for a longest reduced word.
* `simplyLacedPBWBasis_apply`, `simplyLacedPBWBasis_sum_repr`: exact ambient vectors and
  finite coordinate reconstruction in the algebra generated by the `Eᵢ`.
* `simplyLacedNegativePBWBasis`: the actual negative basis transported by Chevalley,
  with exact ambient vectors and reconstruction in the algebra generated by the `Fᵢ`.
* `exists_simplyLacedPBWBases`: a longest reduced word and both bases, without a supplied
  word, spanning assertion, root enumeration, or basis.

The quantum coefficient field is arbitrary. Only nonzero and non-root-of-unity hypotheses
on its parameter are used; neither characteristic zero nor transcendence is assumed.
Finite Cartan type, simple lacing, and a finite Coxeter system are retained. Negative
monomials use precisely `negativeBraidEquiv`, the conjugates `C Tᵢ C⁻¹`, with unchanged word
and multiplication order. They are not asserted to use the original negative operators.
No non-simply-laced spanning or full negative–toral–positive basis is proved here.

## References

Reconstructed by combining the actual spanning equality in `PBW.SimplyLacedLongestSpan`
with the existing finite-Cartan independence theorem in `PBW.Independence`, then transporting
through `chevalleyPlusEquivMinus` from `PBW.NegativeBasis`. Its older transcendental basis
constructions are not used.
-/

noncomputable section
open Module
namespace QuantumGroup

variable {k I Y : Type*} [Field k] [AddCommGroup Y] [DecidableEq I] [Fintype I]
  {D : LusztigCartanDatum I} (R : D.RootDatum Y) {v : k} [NeZero v]
  (hv : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) (hSL : D.cartanMatrix.IsSimplyLaced)
  {W : Type*} [Group W] [Finite W]
  (cs : CoxeterSystem D.cartanMatrix.coxeterMatrix W)
  (hD : D.cartanMatrix.IsFiniteCartan)
  {w : List I} (hw : cs.IsReduced w) (hw₀ : cs.wordProd w = cs.longestElement)

/-- The actual ordered monomials form a basis of the positive algebra, over any quantum
coefficient field at a nonzero non-root-of-unity parameter in finite simply-laced type. -/
def simplyLacedPBWBasis :
    Basis (Fin w.length → ℕ) k (Algebra.adjoin k (Set.range (E R v))) :=
  (Basis.span (linearIndependent_pbwMonomial_of_isFiniteCartan (R := R) hv hD hw)).map
    (LinearEquiv.ofEq _ _
      (span_pbwMonomial_longest_of_isFiniteCartan_of_simplyLaced R v hv hSL cs hw hw₀ hD))

/-- The positive basis vectors are exactly the existing ordered braid-root monomials. -/
theorem simplyLacedPBWBasis_apply (c : Fin w.length → ℕ) :
    (simplyLacedPBWBasis R hv hSL cs hD hw hw₀ c : QuantumGroup R v) =
      CoxeterSystem.pbwMonomial (braidEquivOfNotRoot R hv) (E R v) w c := by
  simp only [simplyLacedPBWBasis, Basis.map_apply, Basis.span_apply]
  rfl

/-- The positive basis coordinates give a finite sum equal to the actual ambient element. -/
theorem simplyLacedPBWBasis_sum_repr (x : Algebra.adjoin k (Set.range (E R v))) :
    ((simplyLacedPBWBasis R hv hSL cs hD hw hw₀).repr x).sum
      (fun c a ↦ a • CoxeterSystem.pbwMonomial
        (braidEquivOfNotRoot R hv) (E R v) w c) = (x : QuantumGroup R v) := by
  have h := congrArg (Algebra.adjoin k (Set.range (E R v))).val
    ((simplyLacedPBWBasis R hv hSL cs hD hw hw₀).linearCombination_repr x)
  simpa only [Finsupp.linearCombination_apply, Finsupp.sum, map_sum, map_smul,
    Subalgebra.val_apply, simplyLacedPBWBasis_apply] using h

/-- The actual negative basis, using the coefficient-linear Chevalley equivalence. -/
def simplyLacedNegativePBWBasis :
    Basis (Fin w.length → ℕ) k (Algebra.adjoin k (Set.range (F R v))) :=
  (simplyLacedPBWBasis R hv hSL cs hD hw hw₀).map
    (chevalleyPlusEquivMinus R v).toLinearEquiv

/-- The negative vectors use the explicit conjugated operators `C Tᵢ C⁻¹`, without
reversing the word or multiplication order. -/
theorem simplyLacedNegativePBWBasis_apply (c : Fin w.length → ℕ) :
    (simplyLacedNegativePBWBasis R hv hSL cs hD hw hw₀ c : QuantumGroup R v) =
      CoxeterSystem.pbwMonomial (negativeBraidEquiv R hv) (F R v) w c := by
  change chevalley R v (simplyLacedPBWBasis R hv hSL cs hD hw hw₀ c) = _
  rw [simplyLacedPBWBasis_apply, chevalley_pbwMonomial]

/-- Finite coordinate reconstruction in the actual negative subalgebra, viewed in `U`. -/
theorem simplyLacedNegativePBWBasis_sum_repr (x : Algebra.adjoin k (Set.range (F R v))) :
    ((simplyLacedNegativePBWBasis R hv hSL cs hD hw hw₀).repr x).sum
      (fun c a ↦ a • CoxeterSystem.pbwMonomial
        (negativeBraidEquiv R hv) (F R v) w c) = (x : QuantumGroup R v) := by
  have h := congrArg (Algebra.adjoin k (Set.range (F R v))).val
    ((simplyLacedNegativePBWBasis R hv hSL cs hD hw hw₀).linearCombination_repr x)
  simpa only [Finsupp.linearCombination_apply, Finsupp.sum, map_sum, map_smul,
    Subalgebra.val_apply, simplyLacedNegativePBWBasis_apply] using h

include hSL hD in
/-- A longest reduced word and both actual PBW bases exist without any supplied basis
or spanning premise. Both bases use the same exponent tuples and word order. -/
theorem exists_simplyLacedPBWBases :
    ∃ w : List I, cs.IsReduced w ∧ cs.wordProd w = cs.longestElement ∧
      ∃ (bp : Basis (Fin w.length → ℕ) k (Algebra.adjoin k (Set.range (E R v))))
        (bn : Basis (Fin w.length → ℕ) k (Algebra.adjoin k (Set.range (F R v)))),
        (∀ c, (bp c : QuantumGroup R v) =
          CoxeterSystem.pbwMonomial (braidEquivOfNotRoot R hv) (E R v) w c) ∧
        (∀ c, (bn c : QuantumGroup R v) =
          CoxeterSystem.pbwMonomial (negativeBraidEquiv R hv) (F R v) w c) := by
  obtain ⟨w, hw, he⟩ := cs.exists_isReduced cs.longestElement
  exact ⟨w, hw, he.symm, simplyLacedPBWBasis R hv hSL cs hD hw he.symm,
    simplyLacedNegativePBWBasis R hv hSL cs hD hw he.symm,
    simplyLacedPBWBasis_apply R hv hSL cs hD hw he.symm,
    simplyLacedNegativePBWBasis_apply R hv hSL cs hD hw he.symm⟩

end QuantumGroup
