/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.BraidAction.Mixed

/-!
# The diagonal braid relation `[Tᵢ(Eⱼ), Tᵢ(Fⱼ)]` in every degree

For `j ≠ i`, `r = -aᵢⱼ` and `q = vᵢ`, we prove, for Lusztig's candidate images
`Tᵢ(Eⱼ) = braidEj`, `Tᵢ(Fⱼ) = braidFj` of `QuantumGroup/BraidAction/Mixed.lean`,
`Tᵢ(Eⱼ) Tᵢ(Fⱼ) - Tᵢ(Fⱼ) Tᵢ(Eⱼ) = (K_{sᵢ j̃} - K_{-sᵢ j̃}) / (vⱼ - vⱼ⁻¹)`,
the image under `Tᵢ` of the defining relation `Eⱼ Fⱼ - Fⱼ Eⱼ = (K̃ⱼ - K̃ⱼ⁻¹)/(vⱼ - vⱼ⁻¹)`.
This holds for every value of the Cartan entry `aᵢⱼ`; the degree-one and degree-two cases
proved in `Coupled.lean` and `DegreeTwo.lean` by explicit normal ordering are special cases.

## Method

Write `X n = E X (n-1) - q^{2(n-1)} Q⁻¹ X (n-1) E` with `X 0 = Eⱼ` (so `X n = (ad Eᵢ)ⁿ Eⱼ`),
and `Y m` likewise from `Fⱼ` and `Fᵢ`; then `Tᵢ(Eⱼ) = [r]!⁻¹ X r` and
`Tᵢ(Fⱼ) = (-1)^r q^r [r]!⁻¹ Y r` for `Q = q^r`. We have `Fᵢ X (n+1) = X (n+1) Fᵢ + c X n K̃ᵢ⁻¹`
with an explicit scalar `c` (`BraidDiagonal.F_mul_X`), and dually for `Eᵢ Y (m+1)`. The
commutators `C n m = [X n, Y m]` then satisfy a two-term recursion in `n`
(`BraidDiagonal.comm_succ_succ`), and by induction every `C n m` with `n ≤ m` is a single
monomial in `Fᵢ`, `K̃ᵢ^{±1}`, `K̃ⱼ^{±1}` (`BraidDiagonal.Hyp.shape`):
`C n m ∝ Fᵢ^{m-n} K̃ᵢ^{-n} K̃ⱼ⁻¹` for `n < m`, and `C n n ∝ K̃ᵢⁿ K̃ⱼ - K̃ᵢ^{-n} K̃ⱼ⁻¹`. The
consistency of the recursion reduces to two scalar identities between `q`-integers
(`BraidDiagonal.coefA_mul_alpha`, `BraidDiagonal.coefA_diag`), and at `n = m = r` the
coefficient is `(-1)^r q^{-r} ([r]!)² / (vⱼ - vⱼ⁻¹)` (`BraidDiagonal.coefB_pow`).
No quantum Serre relation is used: the computation takes place in the algebra generated by
`Eᵢ, Fᵢ, K̃ᵢ^{±1}, K̃ⱼ^{±1}` once `Eⱼ, Fⱼ` have been commuted past each other.

The abstract computation is stated for elements of any `k`-algebra satisfying the relevant
relations (`BraidDiagonal.Hyp`); `QuantumGroup.braidDiagonal_hyp` checks them in `U`.

## Main results

* `QuantumGroup.braidEj_mul_braidFj_sub`: the diagonal relation, in arbitrary ambient rank,
  for every Cartan entry, assuming `v ≠ 0`, `vᵢ - vᵢ⁻¹ ≠ 0` and `[r]ᵢ! ≠ 0`.
* `QuantumGroup.BraidDiagonal.Hyp.comm_self`: its abstract form
  `[X r, Y r] = (-1)^r q^{-r} ([r]!)² c (K^r L - K'^r L')`.
* `QuantumGroup.braidEj_commute_braidFj`: `[Tᵢ(Eⱼ), Tᵢ(Fₗ)] = 0` for distinct `j, l ≠ i`, for
  arbitrary Cartan entries, assuming only `v ≠ 0` (`BraidDiagonal.X_comm_X_of_commute`).
* `QuantumGroup.reflY_ktilde_of_ne`: `sᵢ(j̃) = j̃ + r ĩ` for every Cartan entry.

## References

This is our own computation. The relation is part of the statement that `Tᵢ` is an algebra
automorphism ([Lus] §37.1, [Jan] Ch. 8), whose published proofs proceed differently.

* [Lus] G. Lusztig, *Introduction to quantum groups*, Birkhäuser 1993, §37.1.
* [Jan] J. C. Jantzen, *Lectures on quantum groups*, GSM 6, Ch. 8.
-/

open LieLean

noncomputable section

open Finset

namespace LieLean.QuantumGroup

namespace BraidDiagonal

variable {k : Type*} [Field k]

/-! ### Scalars -/

section Scalars

variable (q Q : k)

/-- `α d = (q - q⁻¹)⁻¹ Σ_{t<d} q^{-2t}`, the coefficient of `K` in `E F^d - F^d E`. -/
def alpha : ℕ → k
  | 0 => 0
  | d + 1 => alpha d + (q - q⁻¹)⁻¹ * q⁻¹ ^ (2 * d)

/-- `β d = (q - q⁻¹)⁻¹ Σ_{t<d} q^{2t}`, the coefficient of `K⁻¹` in `E F^d - F^d E`. -/
def beta : ℕ → k
  | 0 => 0
  | d + 1 => beta d + (q - q⁻¹)⁻¹ * q ^ (2 * d)

/-- The twist `s n = q^{2n} Q⁻¹` in the recursion `X (n+1) = E X n - s n X n E`. -/
def shift (n : ℕ) : k := q ^ (2 * n) * Q⁻¹

/-- `cc m = (q - q⁻¹)⁻¹ Σ_{t<m} (q^{-2t} Q - q^{2t} Q⁻¹)`; for `Q = q^r` this is `[m][r-m+1]`. -/
def cc : ℕ → k
  | 0 => 0
  | n + 1 => cc n + (q - q⁻¹)⁻¹ * ((shift q Q n)⁻¹ - shift q Q n)

variable {q Q}

lemma shift_succ (n : ℕ) : shift q Q (n + 1) = q ^ 2 * shift q Q n := by
  simp only [shift]; ring

lemma cc_eq (m : ℕ) : cc q Q m = Q * alpha q m - Q⁻¹ * beta q m := by
  induction m with
  | zero => simp [cc, alpha, beta]
  | succ m ih =>
    rw [cc, ih, alpha, beta, shift, mul_inv, inv_inv, inv_pow]
    ring

lemma sq_sub_one_ne (hq : q ≠ 0) (hd : q - q⁻¹ ≠ 0) : q ^ 2 - 1 ≠ 0 := by
  intro h
  apply hd
  have e : q - q⁻¹ = q⁻¹ * (q ^ 2 - 1) := by field_simp
  rw [e, h, mul_zero]

lemma alpha_mul (hq : q ≠ 0) (hd : q - q⁻¹ ≠ 0) (d : ℕ) :
    (q - q⁻¹) * alpha q (d + 1) = q⁻¹ ^ d * qInt q (d + 1) := by
  induction d with
  | zero => simp [alpha, qInt, hd]
  | succ d ih =>
    have h1 : qInt q 1 = 1 := by simp [qInt]
    rw [alpha, mul_add, ih, show d + 1 + 1 = 1 + (d + 1) by ring, qInt_add 1 (d + 1), h1]
    simp only [inv_pow]
    field_simp [sq_sub_one_ne hq hd]
    ring

lemma beta_mul (hq : q ≠ 0) (hd : q - q⁻¹ ≠ 0) (d : ℕ) :
    (q - q⁻¹) * beta q (d + 1) = q ^ d * qInt q (d + 1) := by
  induction d with
  | zero => simp [beta, qInt, hd]
  | succ d ih =>
    rw [beta, mul_add, ih, qInt_succ (d + 1)]
    field_simp [sq_sub_one_ne hq hd]
    ring

lemma beta_succ (hq : q ≠ 0) (hd : q - q⁻¹ ≠ 0) (d : ℕ) :
    beta q (d + 1) = q ^ (2 * d) * alpha q (d + 1) := by
  apply mul_left_cancel₀ hd
  rw [beta_mul hq hd, mul_left_comm, alpha_mul hq hd, inv_pow]
  field_simp
  ring

/-- `β (d+1) α d = q² β d α (d+1)`. -/
lemma beta_succ_mul_alpha (hq : q ≠ 0) (hd : q - q⁻¹ ≠ 0) (d : ℕ) :
    beta q (d + 1) * alpha q d = q ^ 2 * beta q d * alpha q (d + 1) := by
  cases d with
  | zero => simp [alpha, beta]
  | succ d =>
    rw [beta_succ hq hd (d + 1), beta_succ hq hd d,
      show 2 * (d + 1) = 2 * d + 2 by ring, pow_add]
    ring

/-- The base case of the off-diagonal recursion. -/
lemma one_sub_mul_alpha (hq : q ≠ 0) (hQ : Q ≠ 0) (hd : q - q⁻¹ ≠ 0) (m : ℕ) :
    (1 - q ^ (2 * m) * Q⁻¹ * Q⁻¹) * alpha q (m + 1) = Q⁻¹ * cc q Q (m + 1) := by
  rw [cc_eq, beta_succ hq hd]
  field_simp

/-- `(q - q⁻¹) cc (m+1) = [m+1] (Q q^{-m} - Q⁻¹ q^m)`. -/
lemma cc_mul (hq : q ≠ 0) (hd : q - q⁻¹ ≠ 0) (m : ℕ) :
    (q - q⁻¹) * cc q Q (m + 1) = qInt q (m + 1) * (Q * q⁻¹ ^ m - Q⁻¹ * q ^ m) := by
  rw [cc_eq, mul_sub, mul_left_comm, alpha_mul hq hd, mul_left_comm (q - q⁻¹) Q⁻¹,
    beta_mul hq hd]
  ring

variable (q Q) in
/-- Coefficients of the off-diagonal commutators `[X n, Y m] = A n m • F^{m-n} K'^n L'`. -/
def coefA (c : k) : ℕ → ℕ → k
  | 0, 0 => -c
  | 0, m + 1 => coefA c 0 m * (1 - q ^ (2 * m) * Q⁻¹ * Q⁻¹)
  | n + 1, m => -beta q (m - n) * coefA c n m

variable (q Q) in
/-- Coefficients of the diagonal commutators `[X n, Y n] = B n • (K^n L - K'^n L')`. -/
def coefB (c : k) : ℕ → k
  | 0 => c
  | n + 1 => -(shift q Q n * cc q Q (n + 1)) * coefB c n

/-- The consistency condition that kills the `K K'^n` term off the diagonal. -/
lemma coefA_mul_alpha (hq : q ≠ 0) (hQ : Q ≠ 0) (hd : q - q⁻¹ ≠ 0) (c : k) :
    ∀ n m, n < m → coefA q Q c n (m + 1) * alpha q (m + 1 - n) =
      shift q Q n * cc q Q (m + 1) * coefA q Q c n m := by
  intro n
  induction n with
  | zero =>
    intro m _
    have h := one_sub_mul_alpha (Q := Q) hq hQ hd m
    simp only [coefA, shift, Nat.sub_zero, mul_zero, pow_zero, one_mul]
    linear_combination coefA q Q c 0 m * h
  | succ n ih =>
    intro m hm
    have h1 := ih m (by omega)
    have h2 := beta_succ_mul_alpha hq hd (m - n)
    rw [show m + 1 - n = m - n + 1 by omega] at h1
    simp only [coefA, show m + 1 - (n + 1) = m - n by omega,
      show m + 1 - n = m - n + 1 by omega]
    rw [shift_succ]
    linear_combination (-coefA q Q c n (m + 1)) * h2 + (-(q ^ 2) * beta q (m - n)) * h1

/-- The consistency condition on the diagonal. -/
lemma coefA_diag (hq : q ≠ 0) (hQ : Q ≠ 0) (hd : q - q⁻¹ ≠ 0) (c : k) (n : ℕ) :
    (q - q⁻¹)⁻¹ * coefA q Q c n (n + 1) = -(shift q Q n * cc q Q (n + 1)) * coefB q Q c n := by
  induction n with
  | zero =>
    simp only [coefA, coefB, cc, shift, mul_zero, pow_zero, one_mul, zero_add]
    field_simp
  | succ n ih =>
    have h1 := coefA_mul_alpha hq hQ hd c n (n + 1) (by omega)
    have h2 := beta_succ (q := q) hq hd 1
    simp only [show n + 1 + 1 - n = 2 by omega] at h1
    simp only [coefA, coefB, show n + 1 + 1 - n = 2 by omega]
    rw [shift_succ, ← ih]
    simp only [mul_one] at h2
    rw [h2]
    linear_combination (-(q - q⁻¹)⁻¹ * q ^ 2) * h1

lemma coefB_eq_prod (c : k) (n : ℕ) :
    coefB q Q c n = (∏ t ∈ range n, -(shift q Q t * cc q Q (t + 1))) * c := by
  induction n with
  | zero => simp [coefB]
  | succ n ih => rw [coefB, ih, prod_range_succ]; ring

lemma qFactorial_eq_prod (n : ℕ) : qFactorial q n = ∏ t ∈ range n, qInt q (t + 1) := by
  induction n with
  | zero => simp [qFactorial]
  | succ n ih => rw [qFactorial_succ, ih, prod_range_succ, mul_comm]

/-- For `Q = q^r` and `t < r`, `cc (t+1) = [t+1][r-t]`. -/
lemma cc_pow (hq : q ≠ 0) (hd : q - q⁻¹ ≠ 0) {r t : ℕ} (ht : t < r) :
    cc q (q ^ r) (t + 1) = qInt q (t + 1) * qInt q (r - t) := by
  apply mul_left_cancel₀ hd
  rw [cc_mul hq hd, mul_left_comm, qInt_mul_sub]
  obtain ⟨u, rfl⟩ : ∃ u, r = t + u := ⟨r - t, by omega⟩
  rw [show t + u - t = u by omega, pow_add]
  simp only [inv_pow]
  field_simp

/-- For `Q = q^r`, `B r = (-1)^r q^{-r} ([r]!)² c`. -/
lemma coefB_pow (hq : q ≠ 0) (hd : q - q⁻¹ ≠ 0) (c : k) (r : ℕ) :
    coefB q (q ^ r) c r = ((-1) ^ r * q⁻¹ ^ r * qFactorial q r ^ 2) * c := by
  rw [coefB_eq_prod]
  congr 1
  rw [prod_congr rfl fun t ht ↦ by rw [cc_pow hq hd (mem_range.1 ht)]]
  have e1 : ∏ t ∈ range r, -(shift q (q ^ r) t * (qInt q (t + 1) * qInt q (r - t))) =
      (∏ t ∈ range r, (-1 : k)) * (∏ t ∈ range r, q ^ (2 * t)) *
        (∏ t ∈ range r, (q ^ r)⁻¹) * (∏ t ∈ range r, qInt q (t + 1)) *
          ∏ t ∈ range r, qInt q (r - t) := by
    simp only [← prod_mul_distrib, shift]
    refine prod_congr rfl fun t _ ↦ ?_
    ring
  have e2 : ∏ t ∈ range r, qInt q (r - t) = ∏ t ∈ range r, qInt q (t + 1) := by
    rw [← prod_range_reflect]
    refine prod_congr rfl fun t ht ↦ ?_
    rw [show r - (r - 1 - t) = t + 1 by have := mem_range.1 ht; omega]
  have e3 : (∏ t ∈ range r, q ^ (2 * t)) * (∏ t ∈ range r, (q ^ r)⁻¹) = q⁻¹ ^ r := by
    rw [prod_pow_eq_pow_sum, prod_const, card_range, ← mul_sum, mul_comm 2,
      sum_range_id_mul_two, inv_pow, inv_pow, ← pow_mul]
    field_simp
    rw [← pow_add]
    congr 1
    cases r with
    | zero => rfl
    | succ r => simp only [Nat.add_sub_cancel]; ring
  rw [e1, e2, ← qFactorial_eq_prod, prod_const, card_range]
  linear_combination (-1 : k) ^ r * qFactorial q r ^ 2 * e3

end Scalars

/-! ### Twisted commutators -/

section Ring

variable {B : Type*} [Ring B] [Algebra k B] {q Q : k}

variable (q Q) in
/-- `X 0 = x`, `X (n+1) = E X n - s n X n E`, where `s n = q^{2n} Q⁻¹`. For `x = Eⱼ` and
`Q = q^r` this is `(ad Eᵢ)^n Eⱼ` (for the adjoint action of the Hopf algebra). -/
def X (E x : B) : ℕ → B
  | 0 => x
  | n + 1 => E * X E x n - shift q Q n • (X E x n * E)

lemma X_succ (E x : B) (n : ℕ) :
    X q Q E x (n + 1) = E * X q Q E x n - shift q Q n • (X q Q E x n * E) := rfl

/-- Eigenvectors: if `w E = t E w` and `w x = μ x w` then `w X n = μ tⁿ X n w`. -/
lemma mul_X {E x w : B} {t μ : k} (hwE : w * E = t • (E * w)) (hwx : w * x = μ • (x * w))
    (n : ℕ) : w * X q Q E x n = (μ * t ^ n) • (X q Q E x n * w) := by
  induction n with
  | zero => simpa [X] using hwx
  | succ n ih =>
    have hwE' (z : B) : w * (E * z) = t • (E * (w * z)) := by
      rw [← mul_assoc, hwE, smul_mul_assoc, mul_assoc]
    have ih' (z : B) : w * (X q Q E x n * z) = (μ * t ^ n) • (X q Q E x n * (w * z)) := by
      rw [← mul_assoc, ih, smul_mul_assoc, mul_assoc]
    rw [X_succ, mul_sub, mul_smul_comm, hwE', ih', ih, hwE]
    simp only [mul_smul_comm, smul_mul_assoc, sub_mul, smul_sub, smul_smul, mul_assoc, pow_succ]
    congr 1 <;> congr 1 <;> ring

/-- One step of the `F`-commutation of the twisted commutators. -/
lemma F_mul_step {E F K K' Y Z : B} {γ s : k}
    (hEF : E * F - F * E = (q - q⁻¹)⁻¹ • (K - K'))
    (hK'E : K' * E = q⁻¹ ^ 2 • (E * K'))
    (hKY : K * Y = s • (Y * K)) (hK'Y : K' * Y = s⁻¹ • (Y * K'))
    (hFY : F * Y = Y * F + γ • (Z * K'))
    (hZ : γ • (E * Z - (q⁻¹ ^ 2 * s) • (Z * E)) = γ • Y) :
    F * (E * Y - s • (Y * E)) =
      (E * Y - s • (Y * E)) * F + (γ + (q - q⁻¹)⁻¹ * (s⁻¹ - s)) • (Y * K') := by
  have hFE : F * E = E * F - (q - q⁻¹)⁻¹ • (K - K') := by rw [← hEF]; abel
  have hZ' : γ • (E * Z * K') - (γ * (q⁻¹ ^ 2 * s)) • (Z * E * K') = γ • (Y * K') := by
    have := congrArg (· * K') hZ
    simpa only [smul_mul_assoc, sub_mul, smul_sub, smul_smul] using this
  calc F * (E * Y - s • (Y * E))
      = (F * E) * Y - s • ((F * Y) * E) := by
        rw [mul_sub, mul_smul_comm, mul_assoc, mul_assoc]
    _ = (E * F - (q - q⁻¹)⁻¹ • (K - K')) * Y - s • ((Y * F + γ • (Z * K')) * E) := by
        rw [hFE, hFY]
    _ = E * (F * Y) - (q - q⁻¹)⁻¹ • (K * Y) + (q - q⁻¹)⁻¹ • (K' * Y)
          - s • (Y * (F * E)) - (s * γ) • (Z * (K' * E)) := by
        simp only [sub_mul, add_mul, smul_mul_assoc, mul_assoc, smul_sub, smul_add, smul_smul]
        abel
    _ = E * (Y * F + γ • (Z * K')) - (q - q⁻¹)⁻¹ • (s • (Y * K))
          + (q - q⁻¹)⁻¹ • (s⁻¹ • (Y * K'))
          - s • (Y * (E * F - (q - q⁻¹)⁻¹ • (K - K')))
          - (s * γ) • (Z * (q⁻¹ ^ 2 • (E * K'))) := by
        rw [hFY, hKY, hK'Y, hFE, hK'E]
    _ = (E * Y - s • (Y * E)) * F + (γ + (q - q⁻¹)⁻¹ * (s⁻¹ - s)) • (Y * K') +
          ((γ • (E * Z * K') - (γ * (q⁻¹ ^ 2 * s)) • (Z * E * K')) - γ • (Y * K')) := by
        simp only [mul_add, mul_sub, sub_mul, mul_smul_comm, smul_mul_assoc, mul_assoc,
          smul_sub, smul_smul, add_smul, sub_smul]
        module
    _ = (E * Y - s • (Y * E)) * F + (γ + (q - q⁻¹)⁻¹ * (s⁻¹ - s)) • (Y * K') := by
        rw [hZ', sub_self, add_zero]

lemma inv_sq_mul_shift_succ (hq : q ≠ 0) (n : ℕ) :
    q⁻¹ ^ 2 * shift q Q (n + 1) = shift q Q n := by
  rw [shift_succ, ← mul_assoc, ← mul_pow, inv_mul_cancel₀ hq, one_pow, one_mul]

lemma K_mul_X {E x K : B} (hKE : K * E = q ^ 2 • (E * K)) (hKx : K * x = Q⁻¹ • (x * K))
    (n : ℕ) : K * X q Q E x n = shift q Q n • (X q Q E x n * K) := by
  rw [mul_X hKE hKx, shift, ← pow_mul, mul_comm]

lemma K'_mul_X {E x K' : B} (hK'E : K' * E = q⁻¹ ^ 2 • (E * K')) (hK'x : K' * x = Q • (x * K'))
    (n : ℕ) : K' * X q Q E x n = (shift q Q n)⁻¹ • (X q Q E x n * K') := by
  rw [mul_X hK'E hK'x, shift, ← pow_mul, mul_inv, inv_inv, inv_pow, mul_comm]

/-- `F X (n+1) = X (n+1) F + cc (n+1) X n K'`: the lowering operator `ad F` on `(ad E)^n x`. -/
lemma F_mul_X (hq : q ≠ 0) {E F K K' x : B}
    (hEF : E * F - F * E = (q - q⁻¹)⁻¹ • (K - K'))
    (hKE : K * E = q ^ 2 • (E * K)) (hK'E : K' * E = q⁻¹ ^ 2 • (E * K'))
    (hxF : x * F = F * x) (hKx : K * x = Q⁻¹ • (x * K)) (hK'x : K' * x = Q • (x * K'))
    (n : ℕ) :
    F * X q Q E x (n + 1) = X q Q E x (n + 1) * F + cc q Q (n + 1) • (X q Q E x n * K') := by
  induction n with
  | zero =>
    have h := F_mul_step (Z := 0) (γ := 0) (s := shift q Q 0) hEF hK'E
      (K_mul_X hKE hKx 0) (K'_mul_X hK'E hK'x 0) (by simp [X, hxF]) (by simp)
    simpa [cc, X_succ] using h
  | succ n ih =>
    have h := F_mul_step (Y := X q Q E x (n + 1)) (Z := X q Q E x n) (γ := cc q Q (n + 1))
      (s := shift q Q (n + 1)) hEF hK'E (K_mul_X hKE hKx _) (K'_mul_X hK'E hK'x _) ih
      (by rw [inv_sq_mul_shift_succ hq, X_succ])
    rw [X_succ E x (n + 1), h]; rfl

variable (q Q) in
/-- The commutators `[X n, Y m]` of the twisted commutators of `x` (under `E`) and `y`
(under `F`). -/
def comm (E F x y : B) (n m : ℕ) : B :=
  X q Q E x n * X q Q F y m - X q Q F y m * X q Q E x n

/-- The recursion in the first index, for twisted commutators of `x` and `y` with independent
parameters `Q`, `Q'`. -/
lemma bracket_succ_succ {E F K x y : B} {Q' γ : k} {n m : ℕ}
    (hEY : E * X q Q' F y (m + 1) = X q Q' F y (m + 1) * E + γ • (X q Q' F y m * K))
    (hKX : K * X q Q E x n = shift q Q n • (X q Q E x n * K)) :
    X q Q E x (n + 1) * X q Q' F y (m + 1) - X q Q' F y (m + 1) * X q Q E x (n + 1) =
      E * (X q Q E x n * X q Q' F y (m + 1) - X q Q' F y (m + 1) * X q Q E x n) -
        shift q Q n • ((X q Q E x n * X q Q' F y (m + 1) - X q Q' F y (m + 1) * X q Q E x n) * E) -
          (shift q Q n * γ) • ((X q Q E x n * X q Q' F y m - X q Q' F y m * X q Q E x n) * K) := by
  have hYE (z : B) : X q Q' F y (m + 1) * (E * z) =
      E * (X q Q' F y (m + 1) * z) - γ • (X q Q' F y m * (K * z)) := by
    rw [← mul_assoc, ← mul_assoc, ← mul_assoc, hEY]
    simp only [add_mul, smul_mul_assoc, mul_assoc]
    abel
  rw [X_succ E x n]
  simp only [sub_mul, mul_sub, smul_mul_assoc, mul_smul_comm, mul_assoc]
  rw [hEY, hYE, hKX]
  simp only [mul_add, mul_smul_comm, smul_sub, smul_add, smul_smul]
  module

/-- The recursion in the first index. -/
lemma comm_succ_succ {E F K x y : B} {γ : k} {n m : ℕ}
    (hEY : E * X q Q F y (m + 1) = X q Q F y (m + 1) * E + γ • (X q Q F y m * K))
    (hKX : K * X q Q E x n = shift q Q n • (X q Q E x n * K)) :
    comm q Q E F x y (n + 1) (m + 1) = E * comm q Q E F x y n (m + 1) -
      shift q Q n • (comm q Q E F x y n (m + 1) * E) -
        (shift q Q n * γ) • (comm q Q E F x y n m * K) :=
  bracket_succ_succ hEY hKX

/-- The recursion in the second index for `n = 0`. -/
lemma comm_zero_succ {E F x y : B} (hxF : x * F = F * x) (m : ℕ) :
    comm q Q E F x y 0 (m + 1) =
      F * comm q Q E F x y 0 m - shift q Q m • (comm q Q E F x y 0 m * F) := by
  simp only [comm, X, sub_mul, mul_sub, smul_mul_assoc, mul_smul_comm, mul_assoc, smul_sub]
  rw [← mul_assoc x F, hxF, mul_assoc]
  module

/-- `E F^{d+1} = F^{d+1} E + F^d (α (d+1) K - β (d+1) K')`. -/
lemma E_mul_F_pow {E F K K' : B} (hEF : E * F - F * E = (q - q⁻¹)⁻¹ • (K - K'))
    (hKF : K * F = q⁻¹ ^ 2 • (F * K)) (hK'F : K' * F = q ^ 2 • (F * K')) (d : ℕ) :
    E * F ^ (d + 1) = F ^ (d + 1) * E + F ^ d * (alpha q (d + 1) • K - beta q (d + 1) • K') := by
  have hEF' : E * F = F * E + (q - q⁻¹)⁻¹ • (K - K') := by rw [← hEF]; abel
  induction d with
  | zero => simp [alpha, beta, hEF', smul_sub]
  | succ d ih =>
    have h1 := mul_pow_of_mul_eq_smul hKF (d + 1)
    have h2 := mul_pow_of_mul_eq_smul hK'F (d + 1)
    have ha : alpha q (d + 1 + 1) = alpha q (d + 1) + (q - q⁻¹)⁻¹ * q⁻¹ ^ (2 * (d + 1)) := rfl
    have hb : beta q (d + 1 + 1) = beta q (d + 1) + (q - q⁻¹)⁻¹ * q ^ (2 * (d + 1)) := rfl
    rw [ha, hb, pow_mul, pow_mul]
    rw [pow_succ' F (d + 1), ← mul_assoc, hEF', add_mul, mul_assoc, ih]
    simp only [mul_add, mul_sub, sub_mul, smul_mul_assoc, mul_smul_comm, smul_sub,
      h1, h2, add_smul, ← mul_assoc, ← pow_succ']
    module

/-- The basic step behind the shapes: `ad`-type commutator of `E` with `F^{d+1} T`. -/
lemma E_comm_F_pow_mul {E F K K' T : B} {s ρ : k}
    (hEF : E * F - F * E = (q - q⁻¹)⁻¹ • (K - K'))
    (hKF : K * F = q⁻¹ ^ 2 • (F * K)) (hK'F : K' * F = q ^ 2 • (F * K'))
    (hTE : T * E = ρ • (E * T)) (hsρ : s * ρ = 1) (d : ℕ) :
    E * (F ^ (d + 1) * T) - s • (F ^ (d + 1) * T * E) =
      F ^ d * (alpha q (d + 1) • (K * T) - beta q (d + 1) • (K' * T)) := by
  rw [← mul_assoc, E_mul_F_pow hEF hKF hK'F, mul_assoc (F ^ (d + 1)) T E, hTE]
  simp only [add_mul, sub_mul, smul_mul_assoc, mul_smul_comm, smul_smul, mul_assoc, hsρ,
    one_smul, mul_sub]
  abel

/-- The hypotheses of the diagonal computation: `E, F, K, K'` generate a copy of the
relations of `U_q(sl₂)` (without `K K' = 1`, which is not needed), `L, L'` are toral elements
`q`-commuting with `E, F` with the scalar `Q`, and `x, y` play the roles of `Eⱼ, Fⱼ`. -/
structure Hyp (q Q c : k) (E F K K' L L' x y : B) : Prop where
  q_ne : q ≠ 0
  Q_ne : Q ≠ 0
  sub_ne : q - q⁻¹ ≠ 0
  EF : E * F - F * E = (q - q⁻¹)⁻¹ • (K - K')
  KE : K * E = q ^ 2 • (E * K)
  K'E : K' * E = q⁻¹ ^ 2 • (E * K')
  KF : K * F = q⁻¹ ^ 2 • (F * K)
  K'F : K' * F = q ^ 2 • (F * K')
  LF : L * F = Q • (F * L)
  L'E : L' * E = Q • (E * L')
  L'F : L' * F = Q⁻¹ • (F * L')
  LK : L * K = K * L
  L'K : L' * K = K * L'
  K'K : K' * K = K * K'
  xF : x * F = F * x
  Ey : E * y = y * E
  Kx : K * x = Q⁻¹ • (x * K)
  K'x : K' * x = Q • (x * K')
  Ky : K * y = Q • (y * K)
  K'y : K' * y = Q⁻¹ • (y * K')
  xy : x * y - y * x = c • (L - L')

namespace Hyp

variable {c : k} {E F K K' L L' x y : B} (h : Hyp q Q c E F K K' L L' x y)
include h

lemma E_mul_Y (m : ℕ) :
    E * X q Q F y (m + 1) = X q Q F y (m + 1) * E + cc q Q (m + 1) • (X q Q F y m * K) := by
  have hFE : F * E - E * F = (q - q⁻¹)⁻¹ • (K' - K) := by
    rw [← neg_sub, h.EF, ← smul_neg, neg_sub]
  exact F_mul_X h.q_ne hFE h.K'F h.KF h.Ey.symm h.K'y h.Ky m

lemma comm_zero_zero : comm q Q E F x y 0 0 = c • (L - L') := by
  simpa [comm, X] using h.xy

lemma comm_zero_succ' (m : ℕ) :
    comm q Q E F x y 0 (m + 1) = coefA q Q c 0 (m + 1) • (F ^ (m + 1) * L') := by
  induction m with
  | zero =>
    rw [comm_zero_succ h.xF, h.comm_zero_zero]
    simp only [coefA, shift, mul_zero, pow_zero, one_mul, zero_add, pow_one, smul_sub,
      mul_sub, sub_mul, smul_mul_assoc, mul_smul_comm, h.LF, h.L'F, smul_smul]
    have hQ := h.Q_ne
    match_scalars <;> field_simp
    ring
  | succ m ih =>
    rw [comm_zero_succ h.xF, ih,
      show coefA q Q c 0 (m + 1 + 1) = coefA q Q c 0 (m + 1) *
        (1 - q ^ (2 * (m + 1)) * Q⁻¹ * Q⁻¹) by rw [coefA.eq_2]]
    simp only [mul_smul_comm, smul_mul_assoc, mul_assoc, h.L'F, smul_smul]
    simp only [← mul_assoc, ← pow_succ', ← pow_succ, shift]
    module

lemma T_mul_E (n : ℕ) :
    K' ^ n * L' * E = (Q * (q⁻¹ ^ 2) ^ n) • (E * (K' ^ n * L')) := by
  have h1 := pow_mul_pow_of_mul_eq_smul h.K'E n 1
  simp only [pow_one, mul_one] at h1
  rw [mul_assoc, h.L'E, mul_smul_comm, ← mul_assoc, h1, smul_mul_assoc, smul_smul, mul_assoc,
    mul_comm Q]

lemma shift_mul_T (n : ℕ) : shift q Q n * (Q * (q⁻¹ ^ 2) ^ n) = 1 := by
  have := h.q_ne
  have := h.Q_ne
  simp only [shift, ← pow_mul, inv_pow]
  field_simp

lemma T_mul_K (n : ℕ) : K' ^ n * L' * K = K * (K' ^ n * L') := by
  have hc : Commute K' K := h.K'K
  rw [mul_assoc, h.L'K, ← mul_assoc, (hc.pow_left n).eq, mul_assoc]

/-- The shapes of the commutators `[X n, Y m]` for `n ≤ m`. -/
theorem shape (n : ℕ) :
    (∀ m, n < m → comm q Q E F x y n m = coefA q Q c n m • (F ^ (m - n) * (K' ^ n * L'))) ∧
      comm q Q E F x y n n = coefB q Q c n • (K ^ n * L - K' ^ n * L') := by
  induction n with
  | zero =>
    refine ⟨fun m hm ↦ ?_, ?_⟩
    · obtain ⟨m, rfl⟩ : ∃ m', m = m' + 1 := ⟨m - 1, by omega⟩
      simpa using h.comm_zero_succ' m
    · simpa [coefB] using h.comm_zero_zero
  | succ n ih =>
    have hKX := K_mul_X (q := q) (Q := Q) h.KE h.Kx n
    have hstep := E_comm_F_pow_mul (T := K' ^ n * L') h.EF h.KF h.K'F (h.T_mul_E n)
      (h.shift_mul_T n)
    have hT : K' ^ (n + 1) * L' = K' * (K' ^ n * L') := by rw [pow_succ', mul_assoc]
    have hE (A : k) (d : ℕ) :
        E * (A • (F ^ (d + 1) * (K' ^ n * L'))) -
            shift q Q n • (A • (F ^ (d + 1) * (K' ^ n * L')) * E) =
          A • (F ^ d * (alpha q (d + 1) • (K * (K' ^ n * L')) -
            beta q (d + 1) • (K' * (K' ^ n * L')))) := by
      rw [mul_smul_comm, smul_mul_assoc, smul_comm (shift q Q n) A, ← smul_sub, hstep]
    have hK (A : k) (d : ℕ) : A • (F ^ d * (K' ^ n * L')) * K =
        A • (F ^ d * (K * (K' ^ n * L'))) := by
      rw [smul_mul_assoc, mul_assoc, h.T_mul_K]
    refine ⟨fun m hm ↦ ?_, ?_⟩
    · obtain ⟨m, rfl⟩ : ∃ m', m = m' + 1 := ⟨m - 1, by omega⟩
      obtain ⟨d, hd⟩ : ∃ d, m = n + 1 + d := ⟨m - (n + 1), by omega⟩
      have hA := coefA_mul_alpha h.q_ne h.Q_ne h.sub_ne c n m (by omega)
      rw [show m + 1 - n = d + 1 + 1 by omega] at hA
      rw [comm_succ_succ (h.E_mul_Y m) hKX, ih.1 (m + 1) (by omega), ih.1 m (by omega),
        show m + 1 - n = d + 1 + 1 by omega, show m - n = d + 1 by omega,
        show m + 1 - (n + 1) = d + 1 by omega, hE, hK, hT, coefA.eq_3,
        show m + 1 - n = d + 1 + 1 by omega]
      simp only [mul_sub, mul_smul_comm, smul_sub, smul_smul]
      match_scalars
      · linear_combination hA
      · ring
    · have hA := coefA_diag h.q_ne h.Q_ne h.sub_ne c n
      have hL : (K ^ n * L) * K = K ^ (n + 1) * L := by
        rw [mul_assoc, h.LK, ← mul_assoc, ← pow_succ]
      rw [comm_succ_succ (h.E_mul_Y n) hKX, ih.1 (n + 1) (by omega), ih.2,
        show n + 1 - n = 0 + 1 by omega, hE, smul_mul_assoc, sub_mul, hL, h.T_mul_K, hT]
      simp only [coefB, alpha, beta, pow_zero, one_mul, zero_add, mul_sub, smul_sub,
        smul_smul, mul_smul_comm]
      set A := coefA q Q c n (n + 1)
      set γ := cc q Q (n + 1)
      match_scalars <;> first | ring1 | linear_combination hA | linear_combination -hA

end Hyp

/-- **The diagonal commutator** for `Q = q^r`:
`[X r, Y r] = (-1)^r q^{-r} ([r]!)² c (K^r L - K'^r L')`. -/
theorem Hyp.comm_self {c : k} {E F K K' L L' x y : B} {r : ℕ}
    (h : Hyp q (q ^ r) c E F K K' L L' x y) :
    comm q (q ^ r) E F x y r r =
      ((-1) ^ r * q⁻¹ ^ r * qFactorial q r ^ 2 * c) • (K ^ r * L - K' ^ r * L') := by
  rw [(h.shape r).2, coefB_pow h.q_ne h.sub_ne]

/-- The recursion in the first index for `m = 0`. -/
lemma comm_succ_zero {E F x y : B} {Q' : k} (hEy : E * y = y * E) (n : ℕ) :
    X q Q E x (n + 1) * X q Q' F y 0 - X q Q' F y 0 * X q Q E x (n + 1) =
      E * (X q Q E x n * X q Q' F y 0 - X q Q' F y 0 * X q Q E x n) -
        shift q Q n • ((X q Q E x n * X q Q' F y 0 - X q Q' F y 0 * X q Q E x n) * E) := by
  simp only [X, sub_mul, mul_sub, smul_mul_assoc, mul_smul_comm, mul_assoc, smul_sub]
  rw [← mul_assoc y E, ← hEy, mul_assoc]
  module

/-- **Coupled off-diagonal commutators vanish in every degree**: if `x` and `y` commute, then
so do all the twisted commutators `X n` of `x` (under `E`, with parameter `Q`) and `Y m` of `y`
(under `F`, with an independent parameter `Q'`). -/
theorem X_comm_X_of_commute (hq : q ≠ 0) {E F K K' x y : B} {Q' : k}
    (hEF : E * F - F * E = (q - q⁻¹)⁻¹ • (K - K'))
    (hK'F : K' * F = q ^ 2 • (F * K')) (hKF : K * F = q⁻¹ ^ 2 • (F * K))
    (hKE : K * E = q ^ 2 • (E * K)) (hKx : K * x = Q⁻¹ • (x * K))
    (hxF : x * F = F * x) (hEy : E * y = y * E)
    (hK'y : K' * y = Q'⁻¹ • (y * K')) (hKy : K * y = Q' • (y * K)) (hxy : x * y = y * x)
    (n m : ℕ) : X q Q E x n * X q Q' F y m = X q Q' F y m * X q Q E x n := by
  rw [← sub_eq_zero]
  have hFE : F * E - E * F = (q - q⁻¹)⁻¹ • (K' - K) := by
    rw [← neg_sub, hEF, ← smul_neg, neg_sub]
  have hEY (m : ℕ) := F_mul_X (Q := Q') hq hFE hK'F hKF hEy.symm hK'y hKy m
  have h0 : ∀ m, X q Q E x 0 * X q Q' F y m - X q Q' F y m * X q Q E x 0 = 0 := by
    intro m
    induction m with
    | zero => simpa [X, sub_eq_zero] using hxy
    | succ m ih =>
      have := comm_zero_succ (q := q) (Q := Q') (E := E) (F := F) (x := x) (y := y) hxF m
      simp only [comm] at this
      rw [show X q Q E x 0 = X q Q' E x 0 from rfl, this,
        ← show X q Q E x 0 = X q Q' E x 0 from rfl, ih]
      simp
  induction n generalizing m with
  | zero => exact h0 m
  | succ n ih =>
    cases m with
    | zero => rw [comm_succ_zero hEy, ih 0]; simp
    | succ m =>
      rw [bracket_succ_succ (hEY m) (K_mul_X hKE hKx n), ih (m + 1), ih m]
      simp

/-- `X n` is the rescaled Serre element `serreAux q (q^n (q Q)⁻¹) n E x`. -/
lemma X_eq_serreAux (hq : q ≠ 0) (hQ : Q ≠ 0) (E x : B) (n : ℕ) :
    X q Q E x n = serreAux q (q ^ n * (q * Q)⁻¹) n E x := by
  induction n with
  | zero => simp [X, serreAux]
  | succ n ih =>
    have e1 : q ^ (n + 1) * (q * Q)⁻¹ * q⁻¹ = q ^ n * (q * Q)⁻¹ := by field_simp; ring
    have e2 : q ^ (n + 1) * (q * Q)⁻¹ * q ^ n = shift q Q n := by
      simp only [shift]; field_simp; ring
    rw [X_succ, ih, serreAux_succ' hq, e1, e2]

end Ring

end BraidDiagonal

/-! ### The diagonal relation in the quantum group -/

variable {k : Type*} [Field k] {I Y : Type*} [AddCommGroup Y] [DecidableEq I]
  {D : LusztigCartanDatum I} {R : D.RootDatum Y} {v : k}

/-- `K_μⁿ = K_{n μ}`. -/
lemma K_pow (μ : Y) (n : ℕ) : K R v μ ^ n = K R v (n • μ) := by
  induction n with
  | zero => simp
  | succ n ih => rw [pow_succ, ih, K_add, succ_nsmul]

omit [DecidableEq I] in
/-- `sᵢ(j̃) = j̃ + r ĩ` for `r = -aᵢⱼ`, in every degree. -/
lemma reflY_ktilde_of_ne {i j : I} (hij : i ≠ j) :
    reflY R i (ktilde R j) = ktilde R j + negA D i j • ktilde R i := by
  have hr : R.root i (ktilde R j) = -((D.d i : ℤ) * negA D i j) := by
    rw [root_ktilde_comm, root_ktilde, cartanMatrix_eq_neg_negA hij]
    ring
  rw [reflY_apply, hr, neg_smul, sub_neg_eq_add, mul_smul]
  simp only [ktilde, natCast_zsmul]
  rw [smul_comm (D.d i) (negA D i j)]

omit [DecidableEq I] in
/-- `v^{⟨ĩ, j⟩} = vᵢ^{-r}` for `j ≠ i`, `r = -aᵢⱼ`. -/
lemma zpow_root_ktilde_of_ne {i j : I} (hij : i ≠ j) :
    v ^ R.root j (ktilde R i) = ((v ^ D.d i) ^ negA D i j)⁻¹ := by
  rw [root_ktilde, cartanMatrix_eq_neg_negA hij, mul_neg, zpow_neg, zpow_mul, zpow_natCast,
    zpow_natCast]

variable (R v) in
/-- The relations used by the abstract diagonal computation hold in `U`. -/
lemma braidDiagonal_hyp (hv : v ≠ 0) {i j : I} (hij : i ≠ j)
    (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) :
    BraidDiagonal.Hyp (v ^ D.d i) ((v ^ D.d i) ^ negA D i j) (v ^ D.d j - (v ^ D.d j)⁻¹)⁻¹
      (E R v i) (F R v i) (Kt R v i) (K R v (-ktilde R i)) (Kt R v j) (K R v (-ktilde R j))
      (E R v j) (F R v j) := by
  have h1 := zpow_root_ktilde_of_ne (R := R) (v := v) hij
  have h2 : v ^ R.root i (ktilde R j) = ((v ^ D.d i) ^ negA D i j)⁻¹ := by
    rw [root_ktilde_comm, h1]
  exact
    { q_ne := pow_ne_zero _ hv
      Q_ne := pow_ne_zero _ (pow_ne_zero _ hv)
      sub_ne := hq
      EF := by simpa using E_mul_F_sub R v i i
      KE := Kt_mul_E i
      K'E := by rw [K_neg_ktilde_mul_E, inv_pow]
      KF := Kt_mul_F i
      K'F := K_neg_ktilde_mul_F i
      LF := by rw [Kt, K_mul_F, zpow_neg, h2, inv_inv]
      L'E := by rw [K_mul_E, map_neg, zpow_neg, h2, inv_inv]
      L'F := by rw [K_mul_F, map_neg, neg_neg, h2]
      LK := K_comm R v _ _
      L'K := K_comm R v _ _
      K'K := K_comm R v _ _
      xF := E_mul_F_of_ne hij.symm
      Ey := E_mul_F_of_ne hij
      Kx := by rw [Kt, K_mul_E, h1]
      K'x := by rw [K_mul_E, map_neg, zpow_neg, h1, inv_inv]
      Ky := by rw [Kt, K_mul_F, zpow_neg, h1, inv_inv]
      K'y := by rw [K_mul_F, map_neg, neg_neg, h1]
      xy := by simpa using E_mul_F_sub R v j j }

/-- **The diagonal braid relation in every degree**: for `j ≠ i`,
`[Tᵢ(Eⱼ), Tᵢ(Fⱼ)] = (K_{sᵢ j̃} - K_{-sᵢ j̃}) / (vⱼ - vⱼ⁻¹)`. -/
theorem braidEj_mul_braidFj_sub (hv : v ≠ 0) {i j : I} (hij : i ≠ j)
    (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) (hr : qFactorial (v ^ D.d i) (negA D i j) ≠ 0) :
    braidEj R v i j * braidFj R v i j - braidFj R v i j * braidEj R v i j =
      (v ^ D.d j - (v ^ D.d j)⁻¹)⁻¹ •
        (braidK R v i (.ofAdd (ktilde R j)) - braidK R v i (.ofAdd (-ktilde R j))) := by
  set q := v ^ D.d i with hqdef
  set r := negA D i j with hrdef
  have hq0 : q ≠ 0 := pow_ne_zero _ hv
  have hQ : q ^ r ≠ 0 := pow_ne_zero _ hq0
  have hc : q ^ r * (q * q ^ r)⁻¹ = q⁻¹ := by field_simp
  have hC := (braidDiagonal_hyp R v hv hij hq).comm_self
  rw [← hqdef, ← hrdef] at hC
  have hX : braidEj R v i j =
      (qFactorial q r)⁻¹ • BraidDiagonal.X q (q ^ r) (E R v i) (E R v j) r := by
    rw [BraidDiagonal.X_eq_serreAux hq0 hQ, hc]; rfl
  have hY : braidFj R v i j = ((qFactorial q r)⁻¹ * (-1) ^ r * q ^ r) •
      BraidDiagonal.X q (q ^ r) (F R v i) (F R v j) r := by
    rw [BraidDiagonal.X_eq_serreAux hq0 hQ, hc]; rfl
  have hK1 : Kt R v i ^ r * Kt R v j = braidK R v i (.ofAdd (ktilde R j)) := by
    rw [braidK_apply, reflY_ktilde_of_ne hij, Kt, K_pow, Kt, K_add, add_comm]
  have hK2 : K R v (-ktilde R i) ^ r * K R v (-ktilde R j) =
      braidK R v i (.ofAdd (-ktilde R j)) := by
    rw [braidK_apply, map_neg, reflY_ktilde_of_ne hij, K_pow, K_add, neg_add, smul_neg,
      add_comm]
  rw [hX, hY, smul_mul_smul_comm, smul_mul_smul_comm,
    mul_comm ((qFactorial q r)⁻¹ * (-1) ^ r * q ^ r) (qFactorial q r)⁻¹, ← smul_sub]
  change _ • BraidDiagonal.comm q (q ^ r) _ _ _ _ r r = _
  rw [hC, hK1, hK2, smul_smul]
  congr 1
  have hs : ((-1 : k) ^ r) ^ 2 = 1 := by rw [← pow_mul, mul_comm, pow_mul]; simp
  have hqq : q ^ r * q⁻¹ ^ r = 1 := by rw [← mul_pow, mul_inv_cancel₀ hq0, one_pow]
  have hf : (qFactorial q r)⁻¹ * qFactorial q r = 1 := inv_mul_cancel₀ hr
  set c := (v ^ D.d j - (v ^ D.d j)⁻¹)⁻¹
  linear_combination
    (((qFactorial q r)⁻¹ * qFactorial q r + 1) * ((-1) ^ r) ^ 2 * (q ^ r * q⁻¹ ^ r) * c) * hf +
      ((q ^ r * q⁻¹ ^ r) * c) * hs + c * hqq


/-- **Coupled off-diagonal commutators vanish in every degree**: for distinct `j, l ≠ i`,
`Tᵢ(Eⱼ) Tᵢ(Fₗ) = Tᵢ(Fₗ) Tᵢ(Eⱼ)`, for arbitrary Cartan entries `aᵢⱼ`, `aᵢₗ`. Only `v ≠ 0` is
assumed (at singular quantum factorials this is an identity for the totalized candidates). -/
theorem braidEj_commute_braidFj (hv : v ≠ 0) {i j l : I} (hij : i ≠ j) (hil : i ≠ l)
    (hjl : j ≠ l) : braidEj R v i j * braidFj R v i l = braidFj R v i l * braidEj R v i j := by
  have hq0 : v ^ D.d i ≠ 0 := pow_ne_zero _ hv
  have hc (r : ℕ) : (v ^ D.d i) ^ r * (v ^ D.d i * (v ^ D.d i) ^ r)⁻¹ = (v ^ D.d i)⁻¹ := by
    field_simp
  have h1 := zpow_root_ktilde_of_ne (R := R) (v := v) hij
  have h2 := zpow_root_ktilde_of_ne (R := R) (v := v) hil
  have H := BraidDiagonal.X_comm_X_of_commute (q := v ^ D.d i) (Q := (v ^ D.d i) ^ negA D i j)
    (Q' := (v ^ D.d i) ^ negA D i l) hq0 (E := E R v i) (F := F R v i) (K := Kt R v i)
    (K' := K R v (-ktilde R i)) (x := E R v j) (y := F R v l)
    (by simpa using E_mul_F_sub R v i i) (K_neg_ktilde_mul_F i) (Kt_mul_F i) (Kt_mul_E i)
    (by rw [Kt, K_mul_E, h1]) (E_mul_F_of_ne hij.symm) (E_mul_F_of_ne hil)
    (by rw [K_mul_F, map_neg, neg_neg, h2]) (by rw [Kt, K_mul_F, zpow_neg, h2, inv_inv])
    (E_mul_F_of_ne hjl) (negA D i j) (negA D i l)
  rw [BraidDiagonal.X_eq_serreAux hq0 (pow_ne_zero _ hq0), hc,
    BraidDiagonal.X_eq_serreAux hq0 (pow_ne_zero _ hq0), hc] at H
  simp only [braidEj, braidFj, smul_mul_smul_comm, H, mul_comm]

end LieLean.QuantumGroup
