/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.BraidAction.Recovery
import LieLean.Algebra.QuantumGroup.BraidAction.CoupledSerreNegative

/-!
# Neighbor-first transformed Serre relations at a short node

Let `j ≠ i`, `q = vᵢ`, `r = -aᵢⱼ ≥ 1`, `s = -aⱼᵢ`, `p = vⱼ` (so `p^s = q^r` by the
symmetrizer), `Q = q^r`, and let `X n = (ad Eᵢ)ⁿ Eⱼ` be the twisted commutators of
`BraidAction/Diagonal.lean`, so that `Tᵢ(Eⱼ) = [r]!⁻¹ X r`. We prove the neighbor-first
transformed Serre relation `S_{1-aⱼᵢ}(Tᵢ Eⱼ, Tᵢ Eᵢ) = 0` for the family `aⱼᵢ = -1` (the node `i`
is short), for every `aᵢⱼ`, in arbitrary ambient rank.

## Main results

* `QuantumGroup.ShortNode.qSerre_X_eq`, `QuantumGroup.twoNode_qSerre_braidEj_braidEi_eq`: the
  **reduction**, for arbitrary Cartan entries `r ≥ 1`, `s`:
  `S_{s+1}(Tᵢ Eⱼ, Tᵢ Eᵢ) = [r]!^{-(s+1)} cc r • serreAux p p s (X r) (X (r-1))` (`cc r = [r]`),
  a purely positive-part element. It comes from peeling one twisted commutator off the Serre
  element (`ShortNode.qSerre_succ_eq`, using `qBinomial_inv`) and the lowering identity
  `X r Tᵢ(Eᵢ) - q⁻ʳ Tᵢ(Eᵢ) X r = cc r X (r-1)` of `BraidDiagonal.Hyp.stepE`.
* `QuantumGroup.ShortNode.X_succ_mul_X` (abstract), `QuantumGroup.shortNode_X_succ_mul_X`
  (in `U`): the positive-part **q-commutation** `X r X (r-1) = q^r X (r-1) X r`, from
  `X (r+1) = 0` and `X 1 X 0 = q^r X 0 X 1` (the Serre relations `S_{r+1}(Eᵢ, Eⱼ) = 0` and
  `S₂(Eⱼ, Eᵢ) = 0`, `ShortNode.X_one_mul_sub`), assuming `α ≠ 0` for the explicit scalar
  `α = q^{r-1} [2r-2, r-1] - q^r [2r-2, r]` (`ShortNode.coeff`). It satisfies
  `α [r] = [2r-2, r-1]` (`ShortNode.coeff_mul_qInt`) and `α = 1` for `r ≤ 2`.
* `QuantumGroup.shortNode_qSerre_braidEj_braidEi`,
  `QuantumGroup.shortNode_qSerre_braidFj_braidFi`: `S₂(Tᵢ Eⱼ, Tᵢ Eᵢ) = 0` and
  `S₂(Tᵢ Fⱼ, Tᵢ Fᵢ) = 0` when `aⱼᵢ = -1`, for every `aᵢⱼ`, in arbitrary ambient rank, assuming
  `v ≠ 0`, `vᵢ - vᵢ⁻¹ ≠ 0` and `[2r-2, r-1]ᵢ ≠ 0`. The `F`-version is transported by the
  Chevalley involution (`twoNode_chevalley_braidEj`).

## Method

The twisted derivation `d z = Eᵢ z - q^{⟨αᵢ, wt z⟩} z Eᵢ` sends `X n` to `X (n+1)`, and on
products `d (X a X b) = X (a+1) X b + q^{2a-r} X a X (b+1)` (`ShortNode.leibniz`). Starting
from `Φ = X 1 X 0 - q^r X 0 X 1 = S₂(Eⱼ, Eᵢ) = 0` and applying `d` exactly `2r-2` times
(`ShortNode.dIter`), the coefficients of the products `X a X b` (`a + b = 2r - 1`) are Gaussian
binomial coefficients in `q²` (`ShortNode.coef_delta`); since `X n = 0` for `n > r`, only
`X r X (r-1)` and `X (r-1) X r` survive, with coefficients `α` and `-q^r α`
(`ShortNode.coef_top`, `ShortNode.coef_next`). For `r = 3` (type `G₂`), `α = q² + q⁻²`: this
is the factor `qᵢ⁴ + 1` of `BraidAction/TripleEdge.lean`.

## Boundary

The hypothesis `[2r-2, r-1]ᵢ ≠ 0` holds at every parameter that is not a root of unity, and
for `r ≤ 2` it follows from `[r]ᵢ! ≠ 0`. It cannot be removed from the positive-part identity:
an exact linear-algebra computation over `ℚ(ζ₈)` (outside this library) shows that for
`r = 3`, `qᵢ⁴ = -1`, the element `X 3 X 2 - q³ X 2 X 3` of the free algebra on `Eᵢ, Eⱼ` is not
in the two-sided ideal generated by the two Serre relations. For `r ≤ 5`, computations over
finite fields indicate that, when `[r]ᵢ! ≠ 0`, the identity fails exactly when
`[2r-2, r-1]ᵢ = 0`.

## References

Reconstructed from the quotient presentation; this computation was not taken from a source
(the statement that `Tᵢ` is an automorphism is [Lus] Thm. 37.1.2 (check), [Jan] Thm. 8.16
(check), proved there differently).
-/

noncomputable section

open Finset

namespace QuantumGroup

namespace ShortNode

open BraidDiagonal

variable {k : Type*} [Field k]

/-! ### Scalars -/

section Scalars

variable (q Q : k)

/-- The Gaussian binomial coefficient in `q²`, written `q^{j(m-j)} [m j]_q`. -/
def gauss (m j : ℕ) : k := q ^ (j * (m - j)) * qBinomial q m j

/-- One application of the twisted derivation to the coefficients `c a` of `X a X (N - a)`. -/
def step (c : ℕ → k) : ℕ → k
  | 0 => shift q Q 0 * c 0
  | a + 1 => c a + shift q Q (a + 1) * c (a + 1)

/-- Iterates of `step`. -/
def coef (c : ℕ → k) : ℕ → ℕ → k
  | 0 => c
  | m + 1 => step q Q (coef c m)

/-- The indicator function of `a₀`. -/
def delta (a₀ : ℕ) : ℕ → k := fun a ↦ if a = a₀ then 1 else 0

/-- The scalar `α = q^n [2n, n] - q^{n+1} [2n, n+1]` (for `r = n + 1`). -/
def coeff (n : ℕ) : k := q ^ n * qBinomial q (2 * n) n - q ^ (n + 1) * qBinomial q (2 * n) (n + 1)

variable {q Q}

@[simp] lemma gauss_zero_right (m : ℕ) : gauss q m 0 = 1 := by simp [gauss]

lemma gauss_eq_zero_of_lt {m j : ℕ} (h : m < j) : gauss q m j = 0 := by
  simp [gauss, qBinomial_eq_zero_of_lt q h]

lemma gauss_succ_succ (hq : q ≠ 0) (m j : ℕ) :
    gauss q (m + 1) (j + 1) = gauss q m j + q ^ (2 * (j + 1)) * gauss q m (j + 1) := by
  have hP := qBinomial_succ_succ q⁻¹ m j
  rw [qBinomial_inv, qBinomial_inv, qBinomial_inv, inv_inv] at hP
  rcases lt_trichotomy j m with h | rfl | h
  · obtain ⟨t, rfl⟩ : ∃ t, m = j + 1 + t := ⟨m - (j + 1), by omega⟩
    rw [show j + 1 + t - j = t + 1 by omega] at hP
    have e : q ^ (t + 1) * q⁻¹ ^ (t + 1) = 1 := by rw [← mul_pow, mul_inv_cancel₀ hq, one_pow]
    simp only [gauss, hP, show j + 1 + t + 1 - (j + 1) = t + 1 by omega,
      show j + 1 + t - j = t + 1 by omega, show j + 1 + t - (j + 1) = t by omega]
    linear_combination q ^ (j * (t + 1)) * qBinomial q (j + 1 + t) j * e
  · simp [gauss]
  · rw [gauss_eq_zero_of_lt (by omega), gauss_eq_zero_of_lt h, gauss_eq_zero_of_lt (by omega)]
    ring

lemma shift_add (a j : ℕ) : shift q Q (a + j) = q ^ (2 * j) * shift q Q a := by
  simp only [shift]; ring

lemma shift_mul_shift (a b : ℕ) :
    shift q Q a * shift q Q b = shift q Q 0 * shift q Q (a + b) := by
  simp only [shift]; ring

/-- The iterates of `step` on an indicator function are Gaussian binomial coefficients. -/
lemma coef_delta (hq : q ≠ 0) (a₀ m : ℕ) :
    (∀ a < a₀, coef q Q (delta a₀) m a = 0) ∧
      ∀ j, coef q Q (delta a₀) m (a₀ + j) = gauss q m j * shift q Q a₀ ^ (m - j) := by
  induction m with
  | zero =>
    refine ⟨fun a ha ↦ by simp [coef, delta, ha.ne], fun j ↦ ?_⟩
    cases j with
    | zero => simp [coef, delta]
    | succ j => simp [coef, delta, gauss_eq_zero_of_lt (Nat.succ_pos j)]
  | succ m ih =>
    obtain ⟨h0, h1⟩ := ih
    refine ⟨fun a ha ↦ ?_, fun j ↦ ?_⟩
    · cases a with
      | zero => simp [coef, step, h0 0 ha]
      | succ a => simp [coef, step, h0 a (by omega), h0 (a + 1) ha]
    · cases j with
      | zero =>
        cases a₀ with
        | zero =>
          have := h1 0
          simp only [add_zero] at this
          simp only [coef, step, this, gauss_zero_right, Nat.sub_zero, pow_succ]
          ring
        | succ a₀ =>
          have := h1 0
          simp only [add_zero] at this
          simp only [coef, step, this, h0 a₀ (Nat.lt_succ_self a₀), gauss_zero_right,
            Nat.sub_zero, pow_succ]
          ring
      | succ j =>
        have e1 := h1 j
        have e2 := h1 (j + 1)
        change step q Q (coef q Q (delta a₀) m) (a₀ + j + 1) = _
        simp only [step]
        rw [e1, show a₀ + j + 1 = a₀ + (j + 1) by ring, e2, gauss_succ_succ hq, shift_add,
          show m + 1 - (j + 1) = m - j by omega]
        rcases lt_or_ge j m with hj | hj
        · rw [show m - j = m - (j + 1) + 1 by omega]
          ring
        · rw [gauss_eq_zero_of_lt (by omega : m < j + 1)]
          ring

/-- `α [n+1] = [2n, n]`. -/
lemma coeff_mul_qInt (hq : q ≠ 0) (hd : q - q⁻¹ ≠ 0) (n : ℕ) :
    coeff q n * qInt q (n + 1) = qBinomial q (2 * n) n := by
  apply mul_left_cancel₀ hd
  have h1 := qBinomial_mul_sub q (2 * n) n
  have h2 := qInt_mul_sub (v := q) (n + 1)
  rw [show 2 * n - n = n by omega] at h1
  have e : q ^ n * q⁻¹ ^ n = 1 := by rw [← mul_pow, mul_inv_cancel₀ hq, one_pow]
  unfold coeff
  linear_combination (q ^ n * qBinomial q (2 * n) n - q ^ (n + 1) * qBinomial q (2 * n) (n + 1)) *
    h2 + q ^ (n + 1) * h1 + (q - q⁻¹) * qBinomial q (2 * n) n * e

/-- `α ≠ 0` as soon as `[2n, n] ≠ 0`. -/
lemma coeff_ne_zero (hq : q ≠ 0) (hd : q - q⁻¹ ≠ 0) {n : ℕ} (hb : qBinomial q (2 * n) n ≠ 0) :
    coeff q n ≠ 0 := fun h ↦ hb (by rw [← coeff_mul_qInt hq hd, h, zero_mul])

lemma coeff_zero : coeff q 0 = 1 := by simp [coeff]

lemma coeff_one (hq : q ≠ 0) : coeff q 1 = 1 := by
  simp only [coeff, mul_one, qBinomial_one_right, qBinomial_self, pow_one]
  simp only [qInt, sum_range_succ, sum_range_zero]
  field_simp
  ring

lemma shift_eq_zpow (hq : q ≠ 0) (r a : ℕ) :
    shift q (q ^ r) a = q ^ (((2 * a : ℕ) : ℤ) - r) := by
  rw [shift, zpow_sub₀ hq, zpow_natCast, zpow_natCast, div_eq_mul_inv]

lemma pow_mul_zpow_pow (hq : q ≠ 0) (a : ℕ) (b : ℤ) (c : ℕ) :
    q ^ a * (q ^ b) ^ c = q ^ ((a : ℤ) + b * c) := by
  rw [← zpow_natCast q a, ← zpow_natCast (q ^ b) c, ← zpow_mul, ← zpow_add₀ hq]

/-- The coefficient of `X (n+1) X n` after `2n` derivations, for `n = m + 1`. -/
lemma coef_top (hq : q ≠ 0) (m : ℕ) :
    gauss q (2 * (m + 1)) (m + 1) * shift q (q ^ (m + 2)) 1 ^ (2 * (m + 1) - (m + 1)) -
        q ^ (m + 2) * (gauss q (2 * (m + 1)) (m + 2) *
          shift q (q ^ (m + 2)) 0 ^ (2 * (m + 1) - (m + 2))) =
      coeff q (m + 1) := by
  have m3 : q ^ ((m + 1) * (m + 1)) * shift q (q ^ (m + 2)) 1 ^ (m + 1) = q ^ (m + 1) := by
    rw [shift_eq_zpow hq, pow_mul_zpow_pow hq, ← zpow_natCast]
    congr 1
    push_cast
    ring
  have m4 : q ^ ((m + 2) * m) * shift q (q ^ (m + 2)) 0 ^ m = 1 := by
    rw [shift_eq_zpow hq, pow_mul_zpow_pow hq, ← zpow_zero q]
    congr 1
    push_cast
    ring
  simp only [gauss, coeff]
  rw [show 2 * (m + 1) - (m + 1) = m + 1 by omega, show 2 * (m + 1) - (m + 2) = m by omega,
    show m + 1 + 1 = m + 2 from rfl]
  linear_combination qBinomial q (2 * (m + 1)) (m + 1) * m3 -
    q ^ (m + 2) * qBinomial q (2 * (m + 1)) (m + 2) * m4

/-- The coefficient of `X n X (n+1)` after `2n` derivations, for `n = m + 1`: `-q^{n+1} α`. -/
lemma coef_next (hq : q ≠ 0) (m : ℕ) :
    gauss q (2 * (m + 1)) m * shift q (q ^ (m + 2)) 1 ^ (2 * (m + 1) - m) -
        q ^ (m + 2) * (gauss q (2 * (m + 1)) (m + 1) *
          shift q (q ^ (m + 2)) 0 ^ (2 * (m + 1) - (m + 1))) =
      -q ^ (m + 2) * coeff q (m + 1) := by
  have m1 : q ^ (m * (m + 2)) * shift q (q ^ (m + 2)) 1 ^ (m + 2) = 1 := by
    rw [shift_eq_zpow hq, pow_mul_zpow_pow hq, ← zpow_zero q]
    congr 1
    push_cast
    ring
  have m2 : q ^ (m + 2) * (q ^ ((m + 1) * (m + 1)) * shift q (q ^ (m + 2)) 0 ^ (m + 1)) = q := by
    rw [shift_eq_zpow hq, pow_mul_zpow_pow hq, ← zpow_natCast q (m + 2), ← zpow_add₀ hq]
    convert zpow_one q using 2
    push_cast
    ring
  have hs : qBinomial q (2 * (m + 1)) m = qBinomial q (2 * (m + 1)) (m + 2) := by
    have := qBinomial_symm q (show m + 2 ≤ 2 * (m + 1) by omega)
    rwa [show 2 * (m + 1) - (m + 2) = m by omega] at this
  have h1 := qBinomial_mul_sub q (2 * (m + 1)) (m + 1)
  rw [show 2 * (m + 1) - (m + 1) = m + 1 by omega, show m + 1 + 1 = m + 2 from rfl] at h1
  have e0 : q ^ (m + 1) * q⁻¹ ^ (m + 1) = 1 := by
    rw [← mul_pow, mul_inv_cancel₀ hq, one_pow]
  have e0' : q ^ (m + 2) * q⁻¹ ^ (m + 2) = 1 := by
    rw [← mul_pow, mul_inv_cancel₀ hq, one_pow]
  set b0 := qBinomial q (2 * (m + 1)) (m + 1)
  set b1 := qBinomial q (2 * (m + 1)) (m + 2)
  have h1' : (q ^ (2 * m + 3) - q) * b0 = (q ^ (2 * m + 4) - 1) * b1 := by
    linear_combination q ^ (m + 2) * h1 + q * b0 * e0 - b1 * e0'
  simp only [gauss, coeff]
  rw [show 2 * (m + 1) - m = m + 2 by omega, show 2 * (m + 1) - (m + 1) = m + 1 by omega,
    show m + 1 + 1 = m + 2 from rfl, hs]
  linear_combination b1 * m1 - b0 * m2 + h1'

end Scalars

/-! ### The twisted derivation on products of twisted commutators -/

section Ring

variable {B : Type*} [Ring B] [Algebra k B] {q Q : k}

/-- The twisted Leibniz rule: `d (X a X b) = X (a+1) X b + q^{2a} Q⁻¹ X a X (b+1)` for
`d z = e z - q^{2(a+b)} Q⁻² z e`. -/
lemma leibniz (e x : B) (a b : ℕ) :
    e * (X q Q e x a * X q Q e x b) -
        (shift q Q 0 * shift q Q (a + b)) • (X q Q e x a * X q Q e x b * e) =
      X q Q e x (a + 1) * X q Q e x b + shift q Q a • (X q Q e x a * X q Q e x (b + 1)) := by
  rw [X_succ, X_succ, ← shift_mul_shift]
  simp only [sub_mul, mul_sub, smul_mul_assoc, mul_smul_comm, mul_assoc, smul_sub, smul_smul]
  module

variable (q Q) in
/-- A level-`N` combination `Σ_{a ≤ N} c a • X a X (N - a)`. -/
def lvl (e x : B) (N : ℕ) (c : ℕ → k) : B :=
  ∑ a ∈ range (N + 1), c a • (X q Q e x a * X q Q e x (N - a))

/-- One application of the twisted derivation at level `N`. -/
lemma e_mul_lvl (e x : B) (N : ℕ) (c : ℕ → k) (hc : c (N + 1) = 0) :
    e * lvl q Q e x N c - (shift q Q 0 * shift q Q N) • (lvl q Q e x N c * e) =
      lvl q Q e x (N + 1) (step q Q c) := by
  set g : ℕ → B := fun a ↦ (shift q Q a * c a) • (X q Q e x a * X q Q e x (N + 1 - a)) with hg
  have hL : e * lvl q Q e x N c - (shift q Q 0 * shift q Q N) • (lvl q Q e x N c * e) =
      ∑ a ∈ range (N + 1), c a • (X q Q e x (a + 1) * X q Q e x (N - a)) +
        ∑ a ∈ range (N + 1), g a := by
    rw [lvl, mul_sum, sum_mul, smul_sum, ← sum_sub_distrib, ← sum_add_distrib]
    refine sum_congr rfl fun a ha ↦ ?_
    have ha := Nat.lt_succ_iff.1 (mem_range.1 ha)
    have hl := leibniz (q := q) (Q := Q) e x a (N - a)
    rw [show a + (N - a) = N by omega, show N - a + 1 = N + 1 - a by omega] at hl
    rw [mul_smul_comm, smul_mul_assoc, smul_comm (shift q Q 0 * shift q Q N), ← smul_sub, hl, hg]
    simp only [smul_add, smul_smul]
    rw [mul_comm (c a)]
  have hR : lvl q Q e x (N + 1) (step q Q c) =
      ∑ a ∈ range (N + 1), c a • (X q Q e x (a + 1) * X q Q e x (N - a)) +
        ∑ a ∈ range (N + 1 + 1), g a := by
    rw [lvl, sum_range_succ', sum_range_succ' g, ← add_assoc, ← sum_add_distrib]
    congr 1
    · refine sum_congr rfl fun a _ ↦ ?_
      simp only [step, hg, add_smul, Nat.add_sub_add_right]
  rw [hL, hR, sum_range_succ g (N + 1)]
  simp [hg, hc]

variable (q Q) in
/-- Iterates of the twisted derivation `z ↦ e z - q^{2L} Q⁻² z e`, starting at level `N`. -/
def dIter (e : B) (N : ℕ) : ℕ → B → B
  | 0, z => z
  | m + 1, z => e * dIter e N m z - (shift q Q 0 * shift q Q (N + m)) • (dIter e N m z * e)

lemma dIter_sub_smul (e : B) (N m : ℕ) (z w : B) (t : k) :
    dIter q Q e N m (z - t • w) = dIter q Q e N m z - t • dIter q Q e N m w := by
  induction m with
  | zero => rfl
  | succ m ih =>
    simp only [dIter, ih, mul_sub, sub_mul, mul_smul_comm, smul_mul_assoc, smul_sub]
    module

lemma dIter_zero_right (e : B) (N m : ℕ) : dIter q Q e N m 0 = 0 := by
  induction m with
  | zero => rfl
  | succ m ih => simp [dIter, ih]

/-- Iterating the twisted derivation on a level-one combination. -/
lemma dIter_lvl (e x : B) (c : ℕ → k) (hc : ∀ m, coef q Q c m (m + 2) = 0) (m : ℕ) :
    dIter q Q e 1 m (lvl q Q e x 1 c) = lvl q Q e x (m + 1) (coef q Q c m) := by
  induction m with
  | zero => rfl
  | succ m ih =>
    rw [dIter, ih, Nat.add_comm 1 m, e_mul_lvl e x (m + 1) _ (hc m)]
    rfl

lemma lvl_one_delta_one (e x : B) : lvl q Q e x 1 (delta 1) = X q Q e x 1 * x := by
  simp [lvl, delta, X]

lemma lvl_one_delta_zero (e x : B) : lvl q Q e x 1 (delta 0) = x * X q Q e x 1 := by
  simp [lvl, delta, X]

lemma coef_delta_support (hq : q ≠ 0) {a₀ : ℕ} (h : a₀ ≤ 1) (m : ℕ) :
    coef q Q (delta a₀) m (m + 2) = 0 := by
  obtain ⟨-, h1⟩ := coef_delta (Q := Q) hq a₀ m
  rw [show m + 2 = a₀ + (m + 2 - a₀) by omega, h1, gauss_eq_zero_of_lt (by omega), zero_mul]

lemma X_add_eq_zero (e x : B) {n : ℕ} (h : X q Q e x n = 0) (t : ℕ) : X q Q e x (n + t) = 0 := by
  induction t with
  | zero => exact h
  | succ t ih => rw [← add_assoc, X_succ, ih]; simp

/-- At level `2n + 1`, only `X n X (n+1)` and `X (n+1) X n` survive when `X (n+2) = 0`. -/
lemma lvl_eq_of_vanish (e x : B) (n : ℕ) (hX : ∀ t, X q Q e x (n + 2 + t) = 0) (c : ℕ → k) :
    lvl q Q e x (2 * n + 1) c = c n • (X q Q e x n * X q Q e x (n + 1)) +
      c (n + 1) • (X q Q e x (n + 1) * X q Q e x n) := by
  rw [lvl, sum_eq_add_of_mem n (n + 1) (by simp; omega) (by simp; omega) (by omega)]
  · rw [show 2 * n + 1 - n = n + 1 by omega, show 2 * n + 1 - (n + 1) = n by omega]
  · intro a ha hne
    have ha := Nat.lt_succ_iff.1 (mem_range.1 ha)
    rcases lt_or_gt_of_ne hne.1 with h | h
    · rw [show 2 * n + 1 - a = n + 2 + (n - 1 - a) by omega, hX, mul_zero, smul_zero]
    · obtain ⟨t, rfl⟩ : ∃ t, a = n + 2 + t := ⟨a - (n + 2), by omega⟩
      rw [hX, zero_mul, smul_zero]

/-- **The q-commutation of the two top twisted commutators.** If `X (n+2) = 0` and
`X 1 x = q^{n+1} x X 1` (with `Q = q^{n+1}`), and `α = coeff q n ≠ 0`, then
`X (n+1) X n = q^{n+1} X n X (n+1)`. -/
theorem X_succ_mul_X {e x : B} (hq : q ≠ 0) {n : ℕ}
    (hS : X q (q ^ (n + 1)) e x (n + 2) = 0)
    (hT : X q (q ^ (n + 1)) e x 1 * x = q ^ (n + 1) • (x * X q (q ^ (n + 1)) e x 1))
    (hα : coeff q n ≠ 0) :
    X q (q ^ (n + 1)) e x (n + 1) * X q (q ^ (n + 1)) e x n =
      q ^ (n + 1) • (X q (q ^ (n + 1)) e x n * X q (q ^ (n + 1)) e x (n + 1)) := by
  cases n with
  | zero => simpa [X] using hT
  | succ m =>
    set Q := q ^ (m + 1 + 1) with hQ
    have hX := X_add_eq_zero e x hS
    have hΦ : X q Q e x 1 * x - Q • (x * X q Q e x 1) = 0 := sub_eq_zero.2 hT
    have hD := congrArg (dIter q Q e 1 (2 * (m + 1))) hΦ
    rw [dIter_sub_smul, dIter_zero_right, ← lvl_one_delta_one, ← lvl_one_delta_zero,
      dIter_lvl e x _ (coef_delta_support hq le_rfl), dIter_lvl e x _ (coef_delta_support hq
        zero_le_one), lvl_eq_of_vanish e x _ hX, lvl_eq_of_vanish e x _ hX] at hD
    obtain ⟨-, c1⟩ := coef_delta (Q := Q) hq 1 (2 * (m + 1))
    obtain ⟨-, c0⟩ := coef_delta (Q := Q) hq 0 (2 * (m + 1))
    have e1 := c1 (m + 1)
    have e2 := c1 m
    have e3 := c0 (m + 2)
    have e4 := c0 (m + 1)
    rw [show 1 + (m + 1) = m + 1 + 1 by ring] at e1
    rw [show 1 + m = m + 1 by ring] at e2
    rw [zero_add] at e3 e4
    rw [e1, e2, e3, e4] at hD
    have hA := coef_top hq m
    have hB := coef_next hq m
    rw [show q ^ (m + 2) = Q from rfl] at hA hB
    set A := coeff q (m + 1)
    have key : A • (X q Q e x (m + 1 + 1) * X q Q e x (m + 1) -
        Q • (X q Q e x (m + 1) * X q Q e x (m + 1 + 1))) = 0 := by
      rw [← hD]
      linear_combination (norm := module)
        -hA • (X q Q e x (m + 1 + 1) * X q Q e x (m + 1)) -
          hB • (X q Q e x (m + 1) * X q Q e x (m + 1 + 1))
    exact sub_eq_zero.1 ((smul_eq_zero.1 key).resolve_left hα)

/-- The degree-one twisted commutator against `x`: `X 1 x - Q x X 1 = S₂(x, e)`. -/
lemma X_one_mul_sub (hQ : Q ≠ 0) (e x : B) :
    X q Q e x 1 * x - Q • (x * X q Q e x 1) = qSerre Q 2 x e := by
  simp only [qSerre, sum_range_succ, sum_range_zero, X, shift, qBinomial_one_right,
    qBinomial_self, qBinomial_zero_right, qInt]
  simp only [sub_mul, mul_sub, smul_mul_assoc, mul_smul_comm, mul_assoc, smul_sub, smul_smul,
    pow_zero, pow_one, pow_two, one_mul, mul_one, zero_add, Nat.reduceSub, Nat.sub_self]
  match_scalars <;> field_simp <;> ring

/-! ### Peeling a twisted commutator off a Serre element -/

/-- `serreAux` depends on `v` only through the quantum binomials, which are invariant under
`v ↦ v⁻¹`. -/
lemma serreAux_inv (v c : k) (m : ℕ) (a b : B) :
    serreAux v⁻¹ c m a b = serreAux v c m a b := by
  simp only [serreAux, qBinomial_inv]

/-- A rescaled Serre element of degree one: `serreAux v c 1 a b = a b - c b a`. -/
lemma serreAux_deg_one (v c : k) (a b : B) : serreAux v c 1 a b = a * b - c • (b * a) := by
  simp [serreAux, sum_range_succ, sub_eq_add_neg]

/-- Peeling off one twisted commutator: `S_{s+1}(a, b) = serreAux p p s a (a b - p⁻ˢ b a)`. -/
lemma qSerre_succ_eq {p : k} (hp : p ≠ 0) (s : ℕ) (a b : B) :
    qSerre p (s + 1) a b = serreAux p p s a (a * b - p⁻¹ ^ s • (b * a)) := by
  rw [← serreAux_one, ← serreAux_inv p, serreAux_succ (inv_ne_zero hp), serreAux_inv]
  simp only [one_mul, inv_inv]

/-- **The reduction** of the neighbor-first Serre element: with `A = -F K` (the image of the
centre generator) and `p^s = Q = q^{n+1}`,
`S_{s+1}(X (n+1), A) = cc (n+1) • serreAux p p s (X (n+1)) (X n)`. -/
theorem qSerre_X_eq {c : k} {E F K K' L L' x y : B} {n : ℕ}
    (h : Hyp q (q ^ (n + 1)) c E F K K' L L' x y) (hK'K : K' * K = 1)
    {p : k} (hp : p ≠ 0) {s : ℕ} (hps : p ^ s = q ^ (n + 1)) :
    qSerre p (s + 1) (X q (q ^ (n + 1)) E x (n + 1)) (-(F * K)) =
      cc q (q ^ (n + 1)) (n + 1) •
        serreAux p p s (X q (q ^ (n + 1)) E x (n + 1)) (X q (q ^ (n + 1)) E x n) := by
  rw [qSerre_succ_eq hp, ← serreAux_smul_right]
  congr 1
  have hQ : q ^ (n + 1) ≠ 0 := pow_ne_zero _ h.q_ne
  have hst := h.stepE hK'K n
  have hsh : shift q (q ^ (n + 1)) (n + 1) = q ^ (n + 1) := by
    simp only [shift]
    field_simp
    ring
  rw [hsh] at hst
  rw [inv_pow, hps]
  set Z := X q (q ^ (n + 1)) E x (n + 1)
  have e : Z * -(F * K) - (q ^ (n + 1))⁻¹ • (-(F * K) * Z) =
      (-(q ^ (n + 1))⁻¹) • (-(F * K) * Z - q ^ (n + 1) • (Z * -(F * K))) := by
    rw [smul_sub, smul_smul, neg_mul (q ^ (n + 1))⁻¹, inv_mul_cancel₀ hQ]
    module
  rw [e, hst, smul_smul]
  congr 1
  field_simp

end Ring

end ShortNode

/-! ### The quantum group -/

variable {k : Type*} [Field k] {I Y : Type*} [AddCommGroup Y] [DecidableEq I]
  {D : LusztigCartanDatum I} {R : D.RootDatum Y} {v : k}

omit [DecidableEq I] in
/-- The symmetrizer: `vⱼ^{-aⱼᵢ} = vᵢ^{-aᵢⱼ}`. -/
lemma twoNode_param_pow {i j : I} (hij : i ≠ j) :
    (v ^ D.d j) ^ negA D j i = (v ^ D.d i) ^ negA D i j := by
  have hs := D.d_mul_cartanMatrix_comm i j
  rw [cartanMatrix_eq_neg_negA hij, cartanMatrix_eq_neg_negA hij.symm] at hs
  have h : D.d j * negA D j i = D.d i * negA D i j := by
    have h' : ((D.d j * negA D j i : ℕ) : ℤ) = ((D.d i * negA D i j : ℕ) : ℤ) := by
      push_cast
      linarith
    exact_mod_cast h'
  rw [← pow_mul, ← pow_mul, h]

variable (R v) in
/-- `Tᵢ(Eⱼ) = [r]ᵢ!⁻¹ X r` for `r = -aᵢⱼ = n + 1`. -/
lemma twoNode_braidEj_eq_X (hv : v ≠ 0) {i j : I} {n : ℕ} (hn : negA D i j = n + 1) :
    braidEj R v i j = (qFactorial (v ^ D.d i) (n + 1))⁻¹ •
      BraidDiagonal.X (v ^ D.d i) ((v ^ D.d i) ^ (n + 1)) (E R v i) (E R v j) (n + 1) := by
  have hq0 : v ^ D.d i ≠ 0 := pow_ne_zero _ hv
  have hc : (v ^ D.d i) ^ (n + 1) * (v ^ D.d i * (v ^ D.d i) ^ (n + 1))⁻¹ = (v ^ D.d i)⁻¹ := by
    field_simp
  rw [BraidDiagonal.X_eq_serreAux hq0 (pow_ne_zero _ hq0), hc, braidEj, hn]

/-- **Reduction of the neighbor-first transformed Serre relation** to the positive part, for
arbitrary Cartan entries `r = -aᵢⱼ = n + 1 ≥ 1`, `s = -aⱼᵢ`, in arbitrary ambient rank:
`S_{s+1}(Tᵢ Eⱼ, Tᵢ Eᵢ) = [r]ᵢ!^{-(s+1)} cc r • serreAux vⱼ vⱼ s (X r) (X (r-1))`, where
`cc r = [r]ᵢ` (`BraidDiagonal.cc_pow`). Only `v ≠ 0` and `vᵢ - vᵢ⁻¹ ≠ 0` are assumed; no Serre
relation is used. -/
theorem twoNode_qSerre_braidEj_braidEi_eq [NeZero v] {i j : I} (hij : i ≠ j)
    (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) {n : ℕ} (hn : negA D i j = n + 1) :
    qSerre (v ^ D.d j) (1 - D.cartanMatrix j i).toNat (braidEj R v i j) (braidEi R i) =
      ((qFactorial (v ^ D.d i) (n + 1))⁻¹ ^ (negA D j i + 1) *
          BraidDiagonal.cc (v ^ D.d i) ((v ^ D.d i) ^ (n + 1)) (n + 1)) •
        serreAux (v ^ D.d j) (v ^ D.d j) (negA D j i)
          (BraidDiagonal.X (v ^ D.d i) ((v ^ D.d i) ^ (n + 1)) (E R v i) (E R v j) (n + 1))
          (BraidDiagonal.X (v ^ D.d i) ((v ^ D.d i) ^ (n + 1)) (E R v i) (E R v j) n) := by
  have hv := NeZero.ne v
  have hH := braidDiagonal_hyp R v hv hij hq
  rw [hn] at hH
  have hps : (v ^ D.d j) ^ negA D j i = (v ^ D.d i) ^ (n + 1) := by
    rw [twoNode_param_pow hij, hn]
  have h1 := qSerre_smul_smul (v := v ^ D.d j) (negA D j i + 1)
    (BraidDiagonal.X (v ^ D.d i) ((v ^ D.d i) ^ (n + 1)) (E R v i) (E R v j) (n + 1))
    (braidEi R i) (qFactorial (v ^ D.d i) (n + 1))⁻¹ 1
  rw [one_smul, mul_one] at h1
  rw [one_sub_cartanMatrix_toNat hij.symm, twoNode_braidEj_eq_X R v hv hn, h1,
    ShortNode.qSerre_X_eq hH (K_neg_mul_Kt i) (pow_ne_zero _ hv) hps, smul_smul]

omit [DecidableEq I] in
/-- If `aⱼᵢ = -1` then `-aᵢⱼ ≥ 1`. -/
lemma twoNode_exists_negA_eq_succ {i j : I} (hij : i ≠ j)
    (h' : D.cartanMatrix j i = -1) : ∃ n, negA D i j = n + 1 := by
  have hs := D.d_mul_cartanMatrix_comm i j
  rw [h', cartanMatrix_eq_neg_negA hij] at hs
  have := D.d_pos j
  refine ⟨negA D i j - 1, ?_⟩
  rcases Nat.eq_zero_or_pos (negA D i j) with h0 | h0
  · rw [h0] at hs
    simp at hs
    omega
  · omega

/-- The positive-part q-commutation `X r X (r-1) = vᵢ^r X (r-1) X r` in `U` when `aⱼᵢ = -1`,
`r = -aᵢⱼ = n + 1`, from the Serre relations of `U`, assuming `α_r ≠ 0`. -/
theorem shortNode_X_succ_mul_X [NeZero v] {i j : I} (hij : i ≠ j)
    (h' : D.cartanMatrix j i = -1) {n : ℕ} (hn : negA D i j = n + 1)
    (hα : ShortNode.coeff (v ^ D.d i) n ≠ 0) :
    BraidDiagonal.X (v ^ D.d i) ((v ^ D.d i) ^ (n + 1)) (E R v i) (E R v j) (n + 1) *
        BraidDiagonal.X (v ^ D.d i) ((v ^ D.d i) ^ (n + 1)) (E R v i) (E R v j) n =
      (v ^ D.d i) ^ (n + 1) •
        (BraidDiagonal.X (v ^ D.d i) ((v ^ D.d i) ^ (n + 1)) (E R v i) (E R v j) n *
          BraidDiagonal.X (v ^ D.d i) ((v ^ D.d i) ^ (n + 1)) (E R v i) (E R v j) (n + 1)) := by
  have hv := NeZero.ne v
  have hq0 : v ^ D.d i ≠ 0 := pow_ne_zero _ hv
  have hQ : (v ^ D.d i) ^ (n + 1) ≠ 0 := pow_ne_zero _ hq0
  refine ShortNode.X_succ_mul_X hq0 ?_ ?_ hα
  · have hc : (v ^ D.d i) ^ (n + 2) * (v ^ D.d i * (v ^ D.d i) ^ (n + 1))⁻¹ = 1 := by
      field_simp
      ring
    rw [BraidDiagonal.X_eq_serreAux hq0 hQ, hc, serreAux_one]
    have hs := serre_E R v hij
    rwa [one_sub_cartanMatrix_toNat hij, hn] at hs
  · have hs := serre_E R v hij.symm
    have hji : negA D j i = 1 := by simp [negA, h']
    have hp := twoNode_param_pow (D := D) (v := v) hij
    rw [hji, pow_one, hn] at hp
    rw [h', hp, show (1 - (-1 : ℤ)).toNat = 2 by norm_num] at hs
    rw [← sub_eq_zero, ShortNode.X_one_mul_sub hQ, hs]

/-- **The neighbor-first transformed Serre relation at a short node**: if `aⱼᵢ = -1` then
`S₂(Tᵢ Eⱼ, Tᵢ Eᵢ) = 0`, for every `aᵢⱼ`, in arbitrary ambient rank, assuming `v ≠ 0`,
`vᵢ - vᵢ⁻¹ ≠ 0` and `[2r-2, r-1]ᵢ ≠ 0` (`r = -aᵢⱼ`). The last hypothesis is automatic for
`r ≤ 2` given `[r]ᵢ! ≠ 0`; for `r = 3` (type `G₂`) it amounts to `vᵢ⁴ + 1 ≠ 0` given `[3]ᵢ ≠ 0`.
Reconstructed; see the module docstring. -/
theorem shortNode_qSerre_braidEj_braidEi [NeZero v] {i j : I} (h' : D.cartanMatrix j i = -1)
    (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0)
    (hb : qBinomial (v ^ D.d i) (2 * negA D i j - 2) (negA D i j - 1) ≠ 0) :
    qSerre (v ^ D.d j) (1 - D.cartanMatrix j i).toNat (braidEj R v i j) (braidEi R i) = 0 := by
  have hij : i ≠ j := by
    rintro rfl
    rw [D.cartanMatrix_self] at h'
    norm_num at h'
  have hv := NeZero.ne v
  obtain ⟨n, hn⟩ := twoNode_exists_negA_eq_succ hij h'
  rw [hn, show 2 * (n + 1) - 2 = 2 * n by omega, Nat.add_sub_cancel] at hb
  have hji : negA D j i = 1 := by simp [negA, h']
  have hp := twoNode_param_pow (D := D) (v := v) hij
  rw [hji, pow_one, hn] at hp
  have hX := shortNode_X_succ_mul_X (R := R) hij h' hn
    (ShortNode.coeff_ne_zero (pow_ne_zero _ hv) hq hb)
  rw [twoNode_qSerre_braidEj_braidEi_eq hij hq hn, hji, ShortNode.serreAux_deg_one, hp, hX,
    sub_self, smul_zero]

/-- The Chevalley factor of `Tᵢ(Eⱼ)` in every degree: `ω(Tᵢ Eⱼ) = (-1)^r vᵢ^{-r} Tᵢ(Fⱼ)`. -/
theorem twoNode_chevalley_braidEj (hv : v ≠ 0) (i j : I) :
    chevalley R v (braidEj R v i j) =
      ((-1) ^ negA D i j * (v ^ D.d i)⁻¹ ^ negA D i j) • braidFj R v i j := by
  simp only [braidEj, braidFj, map_smul, map_serreAux, chevalley_E, smul_smul]
  congr 1
  have e1 : ((-1 : k) ^ negA D i j) ^ 2 = 1 := by
    rw [← pow_mul, mul_comm, pow_mul, neg_one_sq, one_pow]
  have e2 : (v ^ D.d i)⁻¹ ^ negA D i j * (v ^ D.d i) ^ negA D i j = 1 := by
    rw [← mul_pow, inv_mul_cancel₀ (pow_ne_zero _ hv), one_pow]
  set f := (qFactorial (v ^ D.d i) (negA D i j))⁻¹
  linear_combination (-f * ((v ^ D.d i)⁻¹ ^ negA D i j * (v ^ D.d i) ^ negA D i j)) * e1 - f * e2

/-- The neighbor-first transformed Serre relation for the `F`-images at a short node
(`aⱼᵢ = -1`), transported from the `E`-version by the Chevalley involution. -/
theorem shortNode_qSerre_braidFj_braidFi [NeZero v] {i j : I} (h' : D.cartanMatrix j i = -1)
    (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0)
    (hb : qBinomial (v ^ D.d i) (2 * negA D i j - 2) (negA D i j - 1) ≠ 0) :
    qSerre (v ^ D.d j) (1 - D.cartanMatrix j i).toNat (braidFj R v i j) (braidFi R i) = 0 := by
  have hv := NeZero.ne v
  have hs := congrArg (chevalley R v) (shortNode_qSerre_braidEj_braidEi (R := R) h' hq hb)
  rw [map_qSerre, map_zero, chevalley_braidEi hv, twoNode_chevalley_braidEj hv,
    qSerre_smul_smul] at hs
  refine (smul_eq_zero.mp hs).resolve_left (mul_ne_zero (pow_ne_zero _ (mul_ne_zero
    (pow_ne_zero _ (neg_ne_zero.mpr one_ne_zero)) (pow_ne_zero _ (inv_ne_zero
      (pow_ne_zero _ hv))))) (pow_ne_zero _ (pow_ne_zero _ hv)))

end QuantumGroup
