/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.BraidAction.HigherSerre

/-!
# Degree-three triple-edge braid prerequisites

## Main results
Explicit degree-three candidates and centre-first quartic Serre identities.
The ambient rank and compatible toral lattice are unrestricted.

## References
Reconstructed from the repository quantum quotient presentation and its `T''` convention.
No external primary source consulted. These are necessary identities, not a G₂ automorphism
or a length-six action.
-/

noncomputable section
namespace QuantumGroup
variable {k : Type*} [Field k]
section Ring
variable {B : Type*} [Ring B] [Algebra k B]

set_option maxHeartbeats 4000000 in
-- Normal ordering the quartic identity produces many scalar coefficients.
private lemma centre_three (a b c u u' : B) (q t : k) (hq : q ≠ 0)
    (hca : c * a = a * c - t • (u - u'))
    (hcb : c * b = b * c)
    (hua : u * a = q ^ 2 • (a * u))
    (hub : u * b = q⁻¹ ^ 3 • (b * u))
    (huc : u * c = q⁻¹ ^ 2 • (c * u))
    (hu'a : u' * a = q⁻¹ ^ 2 • (a * u'))
    (hu'b : u' * b = q ^ 3 • (b * u'))
    (hu'c : u' * c = q ^ 2 • (c * u'))
    (hu'u : u' * u = 1) (huu' : u * u' = 1) :
    qSerre q 4 (-(c * u))
      (a ^ 3 * b - ((q ^ 2 + 1 + q⁻¹ ^ 2) * q⁻¹) • (a ^ 2 * b * a) +
        ((q ^ 2 + 1 + q⁻¹ ^ 2) * q⁻¹ ^ 2) • (a * b * a ^ 2) -
        q⁻¹ ^ 3 • (b * a ^ 3)) = 0 := by
  have hca_assoc (z : B) := congrArg (fun x : B ↦ x * z) hca
  have hcb_assoc (z : B) := congrArg (fun x : B ↦ x * z) hcb
  have hua_assoc (z : B) := congrArg (fun x : B ↦ x * z) hua
  have hub_assoc (z : B) := congrArg (fun x : B ↦ x * z) hub
  have huc_assoc (z : B) := congrArg (fun x : B ↦ x * z) huc
  have hu'a_assoc (z : B) := congrArg (fun x : B ↦ x * z) hu'a
  have hu'b_assoc (z : B) := congrArg (fun x : B ↦ x * z) hu'b
  have hu'c_assoc (z : B) := congrArg (fun x : B ↦ x * z) hu'c
  have hu'u_assoc (z : B) := congrArg (fun x : B ↦ x * z) hu'u
  have huu'_assoc (z : B) := congrArg (fun x : B ↦ x * z) huu'
  simp only [mul_assoc, sub_mul, smul_mul_assoc, one_mul] at *
  simp (config := { maxSteps := 1000000 }) only [qSerre, Finset.sum_range_succ,
    Finset.sum_range_zero, qBinomial,
    Nat.reduceSub, pow_succ, pow_zero,
    mul_one, one_mul, mul_zero, add_zero, zero_add, one_smul,
    mul_neg, neg_mul, neg_neg, mul_sub, sub_mul, mul_add, add_mul,
    mul_smul_comm, smul_mul_assoc, smul_add, smul_sub, smul_neg, mul_assoc,
    hua, hub, hca_assoc, hcb_assoc, hua_assoc, hub_assoc, huc_assoc, hu'a_assoc,
    hu'b_assoc, hu'c_assoc, hu'u_assoc]
  match_scalars <;> field_simp [hq] <;> ring

set_option maxHeartbeats 4000000 in
-- Normal ordering uses the totalized commutator coefficient without cancellation.
private lemma triple_lowering (a b c u u' : B) (q t : k) (hq : q ≠ 0)
    (hca : c * a = a * c - t • (u - u')) (hcb : c * b = b * c)
    (hua : u * a = q ^ 2 • (a * u))
    (hub : u * b = q⁻¹ ^ 3 • (b * u))
    (hu'a : u' * a = q⁻¹ ^ 2 • (a * u'))
    (hu'b : u' * b = q ^ 3 • (b * u')) (hu'u : u' * u = 1) :
    let X := a ^ 3 * b - ((q ^ 2 + 1 + q⁻¹ ^ 2) * q⁻¹) • (a ^ 2 * b * a) +
      ((q ^ 2 + 1 + q⁻¹ ^ 2) * q⁻¹ ^ 2) • (a * b * a ^ 2) -
      q⁻¹ ^ 3 • (b * a ^ 3);
    -(c * u) * X - q ^ 3 • (X * -(c * u)) =
      (t * (1 - q ^ 6)) • (a ^ 2 * b - ((q + q⁻¹) * q⁻¹ ^ 2) • (a * b * a) +
        q⁻¹ ^ 4 • (b * a ^ 2)) := by
  have hca_assoc (z : B) := congrArg (fun x : B ↦ x * z) hca
  have hcb_assoc (z : B) := congrArg (fun x : B ↦ x * z) hcb
  have hua_assoc (z : B) := congrArg (fun x : B ↦ x * z) hua
  have hub_assoc (z : B) := congrArg (fun x : B ↦ x * z) hub
  have hu'a_assoc (z : B) := congrArg (fun x : B ↦ x * z) hu'a
  have hu'b_assoc (z : B) := congrArg (fun x : B ↦ x * z) hu'b
  simp only [mul_assoc, sub_mul, smul_mul_assoc] at *
  simp only [pow_succ, pow_zero, one_mul, mul_sub, sub_mul, mul_add, add_mul, mul_neg, neg_mul,
    mul_smul_comm, smul_mul_assoc, smul_add, smul_sub, smul_neg, mul_assoc,
    hua, hub, hca_assoc, hcb_assoc, hua_assoc, hub_assoc, hu'a_assoc, hu'b_assoc,
    hu'u, mul_one]
  match_scalars <;> field_simp [hq] <;> ring

set_option maxHeartbeats 4000000 in
-- A certificate in the ideal generated by the two ORIGINAL Serre relations.
/-- Original-relation certificate for the G₂ neighbor-first relation.
Reconstructed by exact Laurent coefficient elimination. No transformed relation is assumed;
the prefactor is retained, so no nonvanishing of `q⁴ + 1` is required here. -/
theorem tripleEdge_originalSerre_certificate (a b : B) (q : k) (hq : q ≠ 0)
    (hs : qSerre q 4 a b = 0) (ht : qSerre (q ^ 3) 2 b a = 0) :
    let X := (a ^ 3 * b - ((q ^ 2 + 1 + q⁻¹ ^ 2) * q⁻¹) • (a ^ 2 * b * a) +
      ((q ^ 2 + 1 + q⁻¹ ^ 2) * q⁻¹ ^ 2) • (a * b * a ^ 2) -
      q⁻¹ ^ 3 • (b * a ^ 3))
    let Y := (a ^ 2 * b - ((q + q⁻¹) * q⁻¹ ^ 2) • (a * b * a) +
      q⁻¹ ^ 4 • (b * a ^ 2))
    (q ^ 7 * (q ^ 4 + 1)) • (Y * X - q⁻¹ ^ 3 • (X * Y)) = 0 := by
  dsimp only
  have he : (q ^ 7 * (q ^ 4 + 1)) • ((a ^ 2 * b - ((q + q⁻¹) * q⁻¹ ^ 2) • (a * b * a) +
      q⁻¹ ^ 4 • (b * a ^ 2)) * (a ^ 3 * b - ((q ^ 2 + 1 + q⁻¹ ^ 2) * q⁻¹) • (a ^ 2 * b * a) +
      ((q ^ 2 + 1 + q⁻¹ ^ 2) * q⁻¹ ^ 2) • (a * b * a ^ 2) -
      q⁻¹ ^ 3 • (b * a ^ 3)) -
      q⁻¹ ^ 3 • ((a ^ 3 * b - ((q ^ 2 + 1 + q⁻¹ ^ 2) * q⁻¹) • (a ^ 2 * b * a) +
      ((q ^ 2 + 1 + q⁻¹ ^ 2) * q⁻¹ ^ 2) • (a * b * a ^ 2) -
      q⁻¹ ^ 3 • (b * a ^ 3)) * (a ^ 2 * b - ((q + q⁻¹) * q⁻¹ ^ 2) • (a * b * a) +
      q⁻¹ ^ 4 • (b * a ^ 2)))) =
      (q ^ 5 * (1 + q ^ 2)) • (qSerre q 4 a b * a * b) -
      (q ^ 2 * (1 + q ^ 2 + q ^ 6)) • (qSerre q 4 a b * b * a) +
      q ^ 6 • (a * qSerre q 4 a b * b) +
      q ^ 2 • (b * qSerre q 4 a b * a) -
      (1 + q ^ 4 + q ^ 6) • (a * b * qSerre q 4 a b) +
      (q * (1 + q ^ 2)) • (b * a * qSerre q 4 a b) -
      q ^ 2 • (qSerre (q ^ 3) 2 b a * a ^ 4) +
      ((q ^ 4 + 1) * (1 + q ^ 2)) • (a * qSerre (q ^ 3) 2 b a * a ^ 3) -
      ((q ^ 4 + 1) * (1 + q ^ 2 + q ^ 4)) • (a ^ 2 * qSerre (q ^ 3) 2 b a * a ^ 2) +
      (q ^ 2 * (q ^ 4 + 1) * (1 + q ^ 2)) • (a ^ 3 * qSerre (q ^ 3) 2 b a * a) -
      q ^ 6 • (a ^ 4 * qSerre (q ^ 3) 2 b a) := by
    simp only [qSerre, Finset.sum_range_succ, Finset.sum_range_zero, qBinomial,
      Nat.reduceSub, pow_succ, pow_zero, mul_one, one_mul, mul_zero, add_zero,
      zero_add, one_smul, mul_neg, neg_mul, neg_neg, mul_sub, sub_mul, mul_add,
      add_mul, mul_smul_comm, smul_mul_assoc, smul_add, smul_sub, mul_assoc]
    match_scalars <;> field_simp [hq] <;> ring
  rw [he, hs, ht]
  simp

private lemma triple_reverse_serre (X A Y : B) (q t : k) (hq : q ≠ 0)
    (hAX : A * X - q ^ 3 • (X * A) = t • Y)
    (hYX : Y * X - q⁻¹ ^ 3 • (X * Y) = 0) :
    qSerre (q ^ 3) 2 X A = 0 := by
  have he : qSerre (q ^ 3) 2 X A =
      (A * X - q ^ 3 • (X * A)) * X -
        q⁻¹ ^ 3 • (X * (A * X - q ^ 3 • (X * A))) := by
    simp [qSerre, Finset.sum_range_succ, qBinomial, pow_two, mul_assoc,
      mul_sub, sub_mul, smul_sub, smul_smul, hq, add_smul]
    module
  rw [he, hAX]
  rw [smul_mul_assoc, mul_smul_comm, smul_comm, ← smul_sub, hYX, smul_zero]

end Ring

variable {I Y : Type*} [AddCommGroup Y] [DecidableEq I]
  {D : LusztigCartanDatum I} {R : D.RootDatum Y} {v : k} {i j : I}

/-- Degree-three positive candidate, reconstructed from the defining sum.
The inverse factorial is totalized; it is not cancelled. -/
theorem braidEj_eq_of_cartanMatrix_eq_neg_three (hv : v ≠ 0)
    (h : D.cartanMatrix i j = -3) :
    braidEj R v i j = (qFactorial (v ^ D.d i) 3)⁻¹ •
      (E R v i ^ 3 * E R v j -
        (((v ^ D.d i) ^ 2 + 1 + (v ^ D.d i)⁻¹ ^ 2) * (v ^ D.d i)⁻¹) •
          (E R v i ^ 2 * E R v j * E R v i) +
        (((v ^ D.d i) ^ 2 + 1 + (v ^ D.d i)⁻¹ ^ 2) * (v ^ D.d i)⁻¹ ^ 2) •
          (E R v i * E R v j * E R v i ^ 2) -
        (v ^ D.d i)⁻¹ ^ 3 • (E R v j * E R v i ^ 3)) := by
  simp only [braidEj, negA, h, Int.reduceNeg, neg_neg, Int.reduceToNat]
  congr 1
  simp only [serreAux, Finset.sum_range_succ, Finset.sum_range_zero, qBinomial,
    Nat.reduceSub, pow_succ, pow_zero, mul_one, one_mul, mul_zero, add_zero,
    zero_add, one_smul, mul_neg, neg_mul, neg_neg, mul_add, add_mul, mul_assoc]
  match_scalars <;> field_simp [pow_ne_zero (D.d i) hv] <;> ring

/-- The Chevalley factor for the actual degree-three candidate is `-qᵢ⁻³`.
Reconstructed directly from the definitions, without cancelling a factorial. -/
theorem chevalley_braidEj_of_cartanMatrix_eq_neg_three (hv : v ≠ 0)
    (h : D.cartanMatrix i j = -3) :
    chevalley R v (braidEj R v i j) = -(v ^ D.d i)⁻¹ ^ 3 • braidFj R v i j := by
  simp only [braidEj, braidFj, negA, h, Int.reduceNeg, neg_neg, Int.reduceToNat,
    map_smul, serreAux, map_sum, map_mul, map_pow, chevalley_E, smul_smul]
  congr 1
  field_simp [pow_ne_zero (D.d i) hv]

omit [DecidableEq I] in
/-- Symmetrizer compatibility forces `q_j = q_i³` at entries `(-3,-1)`.
Reconstructed from the Cartan datum, with no equality-of-parameters assumption. -/
theorem parameter_eq_cube_of_triple_edge
    (h : D.cartanMatrix i j = -3) (h' : D.cartanMatrix j i = -1) :
    v ^ D.d j = (v ^ D.d i) ^ 3 := by
  have hd : D.d j = D.d i * 3 := by
    have hs := D.d_mul_cartanMatrix_comm i j
    rw [h, h'] at hs
    omega
  rw [hd, pow_mul]

omit [DecidableEq I] in
/-- Symmetrizer-correct reflection of the neighboring toral exponent at a triple edge.
Reconstructed from the root datum; the reverse entry is unrestricted. -/
lemma reflY_ktilde_of_cartanMatrix_eq_neg_three (h : D.cartanMatrix i j = -3) :
    reflY R i (ktilde R j) = ktilde R j + 3 • ktilde R i := by
  have hr : R.root i (ktilde R j) = -((D.d i : ℤ) * 3) := by
    rw [root_ktilde, ← D.d_mul_cartanMatrix_comm i j, h]
    ring
  rw [reflY_apply, hr, neg_smul, sub_neg_eq_add, mul_smul, natCast_zsmul]
  simp only [ktilde, ← natCast_zsmul, smul_smul, Nat.cast_ofNat]
  rw [mul_comm]

set_option maxHeartbeats 1000000 in
-- Elaborating the normal-ordering lemma in the quotient needs a larger budget.
/-- The centre-first positive quartic Serre relation for the actual degree-three candidate.
Reconstructed from the quotient relations. Only `v ≠ 0` is needed: no nonvanishing
quantum sum, difference or factorial is assumed. The reverse entry is unrestricted. -/
theorem qSerre_braidEi_braidEj_of_cartanMatrix_eq_neg_three (hv : v ≠ 0)
    (h : D.cartanMatrix i j = -3) :
    qSerre (v ^ D.d i) (1 - D.cartanMatrix i j).toNat
      (braidEi R i) (braidEj R v i j) = 0 := by
  have hij : i ≠ j := by
    rintro rfl
    rw [D.cartanMatrix_self] at h
    norm_num at h
  have hca : F R v i * E R v i = E R v i * F R v i -
      (v ^ D.d i - (v ^ D.d i)⁻¹)⁻¹ • (Kt R v i - K R v (-ktilde R i)) := by
    have hc := E_mul_F_sub R v i i
    simp only [ite_true] at hc
    linear_combination (norm := module) -hc
  have hub : Kt R v i * E R v j =
      (v ^ D.d i)⁻¹ ^ 3 • (E R v j * Kt R v i) := by
    rw [Kt, K_mul_E, root_ktilde, h, mul_neg, zpow_neg, zpow_mul,
      zpow_natCast, zpow_ofNat, inv_pow]
  have hu'b : K R v (-ktilde R i) * E R v j =
      (v ^ D.d i) ^ 3 • (E R v j * K R v (-ktilde R i)) := by
    rw [K_mul_E, map_neg, root_ktilde, h, mul_neg, neg_neg, zpow_mul,
      zpow_natCast, zpow_ofNat]
  have hs := centre_three (E R v i) (E R v j) (F R v i)
    (Kt R v i) (K R v (-ktilde R i)) (v ^ D.d i)
    (v ^ D.d i - (v ^ D.d i)⁻¹)⁻¹ (pow_ne_zero _ hv) hca
    (E_mul_F_of_ne hij.symm).symm (Kt_mul_E i) hub (Kt_mul_F i)
    (by simpa only [inv_pow] using K_neg_ktilde_mul_E (R := R) (v := v) i)
    hu'b (K_neg_ktilde_mul_F i) (K_neg_mul_Kt i) (Kt_mul_K_neg i)
  rw [h, braidEj_eq_of_cartanMatrix_eq_neg_three hv h]
  change qSerre (v ^ D.d i) 4 (braidEi R i) (_ • _) = 0
  have he := qSerre_smul_smul (v := v ^ D.d i) 4
    (braidEi (v := v) R i)
    (E R v i ^ 3 * E R v j -
      (((v ^ D.d i) ^ 2 + 1 + (v ^ D.d i)⁻¹ ^ 2) * (v ^ D.d i)⁻¹) •
        (E R v i ^ 2 * E R v j * E R v i) +
      (((v ^ D.d i) ^ 2 + 1 + (v ^ D.d i)⁻¹ ^ 2) * (v ^ D.d i)⁻¹ ^ 2) •
        (E R v i * E R v j * E R v i ^ 2) -
      (v ^ D.d i)⁻¹ ^ 3 • (E R v j * E R v i ^ 3))
    1 (qFactorial (v ^ D.d i) 3)⁻¹
  rw [one_smul, one_pow, one_mul, hs, smul_zero] at he
  exact he

/-- The centre-first negative quartic Serre relation for the actual degree-three candidate.
Reconstructed via the proved quotient Chevalley map. No relation package or braid
automorphism is assumed; ambient rank, toral lattice and reverse entry are unrestricted. -/
theorem qSerre_braidFi_braidFj_of_cartanMatrix_eq_neg_three (hv : v ≠ 0)
    (h : D.cartanMatrix i j = -3) :
    qSerre (v ^ D.d i) (1 - D.cartanMatrix i j).toNat
      (braidFi R i) (braidFj R v i j) = 0 := by
  have hs := congrArg (chevalley R v)
    (qSerre_braidEi_braidEj_of_cartanMatrix_eq_neg_three (R := R) hv h)
  rw [map_qSerre, map_zero, chevalley_braidEi hv,
    chevalley_braidEj_of_cartanMatrix_eq_neg_three hv h, qSerre_smul_smul] at hs
  exact (smul_eq_zero.mp hs).resolve_left
    (mul_ne_zero (pow_ne_zero _ (pow_ne_zero _ (pow_ne_zero _ hv)))
      (neg_ne_zero.mpr (pow_ne_zero _ (inv_ne_zero (pow_ne_zero _ hv)))))

set_option maxHeartbeats 1000000 in
-- Instantiation of the original commutator and toral normal-ordering certificate.
/-- The degree-three candidate's lowering q-commutator in the actual quotient.
Reconstructed from original mixed and toral relations; no transformed relation assumed.
The reverse Cartan entry and ambient rank are unrestricted, and no denominator is cancelled. -/
theorem tripleEdge_braidEi_braidEj_qcomm (hv : v ≠ 0)
    (h : D.cartanMatrix i j = -3) :
    braidEi R i * braidEj R v i j -
        (v ^ D.d i) ^ 3 • (braidEj R v i j * braidEi R i) =
      ((qFactorial (v ^ D.d i) 3)⁻¹ *
        ((v ^ D.d i - (v ^ D.d i)⁻¹)⁻¹ * (1 - (v ^ D.d i) ^ 6))) •
      (E R v i ^ 2 * E R v j -
        ((v ^ D.d i + (v ^ D.d i)⁻¹) * (v ^ D.d i)⁻¹ ^ 2) •
          (E R v i * E R v j * E R v i) +
        (v ^ D.d i)⁻¹ ^ 4 • (E R v j * E R v i ^ 2)) := by
  have hij : i ≠ j := by
    rintro rfl
    rw [D.cartanMatrix_self] at h
    norm_num at h
  have hca : F R v i * E R v i = E R v i * F R v i -
      (v ^ D.d i - (v ^ D.d i)⁻¹)⁻¹ • (Kt R v i - K R v (-ktilde R i)) := by
    have hc := E_mul_F_sub R v i i
    simp only [ite_true] at hc
    linear_combination (norm := module) -hc
  have hub : Kt R v i * E R v j =
      (v ^ D.d i)⁻¹ ^ 3 • (E R v j * Kt R v i) := by
    rw [Kt, K_mul_E, root_ktilde, h, mul_neg, zpow_neg, zpow_mul,
      zpow_natCast, zpow_ofNat, inv_pow]
  have hu'b : K R v (-ktilde R i) * E R v j =
      (v ^ D.d i) ^ 3 • (E R v j * K R v (-ktilde R i)) := by
    rw [K_mul_E, map_neg, root_ktilde, h, mul_neg, neg_neg, zpow_mul,
      zpow_natCast, zpow_ofNat]
  have hAX := triple_lowering (E R v i) (E R v j) (F R v i)
    (Kt R v i) (K R v (-ktilde R i)) (v ^ D.d i)
    (v ^ D.d i - (v ^ D.d i)⁻¹)⁻¹ (pow_ne_zero _ hv) hca
    (E_mul_F_of_ne hij.symm).symm (Kt_mul_E i) hub
    (by simpa only [inv_pow] using K_neg_ktilde_mul_E (R := R) (v := v) i)
    hu'b (K_neg_mul_Kt i)
  rw [braidEj_eq_of_cartanMatrix_eq_neg_three hv h]
  simpa only [braidEi, mul_smul_comm, smul_mul_assoc, smul_sub, smul_smul,
    smul_add, mul_sub, sub_mul, mul_add, add_mul, mul_comm, mul_left_comm, mul_assoc] using
    congrArg (fun z : QuantumGroup R v ↦ (qFactorial (v ^ D.d i) 3)⁻¹ • z) hAX

set_option maxHeartbeats 1000000 in
-- Applying the normal-ordering certificate in the quotient needs a larger budget.
/-- Neighbor-first positive Serre relation for the actual degree-three braid candidate.
Reconstructed from the quotient presentation at mutual entries `(-3,-1)`.
Rank, characteristic and toral lattice are unrestricted. The inverse factorial and
quantum difference remain totalized. This proof cancels the explicit factor `qᵢ⁴ + 1`;
necessity of that extra assumption is not asserted. -/
theorem qSerre_braidEj_braidEi_of_triple_edge (hv : v ≠ 0)
    (h : D.cartanMatrix i j = -3) (h' : D.cartanMatrix j i = -1)
    (h4 : (v ^ D.d i) ^ 4 + 1 ≠ 0) :
    qSerre (v ^ D.d j) (1 - D.cartanMatrix j i).toNat
      (braidEj R v i j) (braidEi R i) = 0 := by
  have hij : i ≠ j := by
    rintro rfl
    rw [D.cartanMatrix_self] at h
    norm_num at h
  have hp := parameter_eq_cube_of_triple_edge (v := v) h h'
  have hca : F R v i * E R v i = E R v i * F R v i -
      (v ^ D.d i - (v ^ D.d i)⁻¹)⁻¹ • (Kt R v i - K R v (-ktilde R i)) := by
    have hc := E_mul_F_sub R v i i
    simp only [ite_true] at hc
    linear_combination (norm := module) -hc
  have hub : Kt R v i * E R v j =
      (v ^ D.d i)⁻¹ ^ 3 • (E R v j * Kt R v i) := by
    rw [Kt, K_mul_E, root_ktilde, h, mul_neg, zpow_neg, zpow_mul,
      zpow_natCast, zpow_ofNat, inv_pow]
  have hu'b : K R v (-ktilde R i) * E R v j =
      (v ^ D.d i) ^ 3 • (E R v j * K R v (-ktilde R i)) := by
    rw [K_mul_E, map_neg, root_ktilde, h, mul_neg, neg_neg, zpow_mul,
      zpow_natCast, zpow_ofNat]
  have hAX := triple_lowering (E R v i) (E R v j) (F R v i)
    (Kt R v i) (K R v (-ktilde R i)) (v ^ D.d i)
    (v ^ D.d i - (v ^ D.d i)⁻¹)⁻¹ (pow_ne_zero _ hv) hca
    (E_mul_F_of_ne hij.symm).symm (Kt_mul_E i) hub
    (by simpa only [inv_pow] using K_neg_ktilde_mul_E (R := R) (v := v) i)
    hu'b (K_neg_mul_Kt i)
  have hs : qSerre (v ^ D.d i) 4 (E R v i) (E R v j) = 0 := by
    simpa only [h, Int.reduceSub, Int.reduceToNat] using serre_E R v hij
  have ht : qSerre ((v ^ D.d i) ^ 3) 2 (E R v j) (E R v i) = 0 := by
    simpa only [h', hp, Int.reduceSub, Int.reduceToNat] using serre_E R v hij.symm
  have hYX := tripleEdge_originalSerre_certificate (E R v i) (E R v j) (v ^ D.d i)
    (pow_ne_zero _ hv) hs ht
  have hYX0 := (smul_eq_zero.mp hYX).resolve_left
    (mul_ne_zero (pow_ne_zero _ (pow_ne_zero _ hv)) h4)
  have H := triple_reverse_serre _ _ _ (v ^ D.d i) _ (pow_ne_zero _ hv) hAX hYX0
  rw [h', hp, braidEj_eq_of_cartanMatrix_eq_neg_three hv h]
  change qSerre ((v ^ D.d i) ^ 3) 2 (_ • _) (braidEi R i) = 0
  rw [← one_smul k (braidEi (v := v) R i), qSerre_smul_smul]
  exact (smul_eq_zero.mpr (Or.inr H))

/-- Neighbor-first negative Serre relation at mutual entries `(-3,-1)`.
Reconstructed via the proved quotient Chevalley map and its actual scalar factors;
no automorphism or transformed-relation hypothesis is assumed. -/
theorem qSerre_braidFj_braidFi_of_triple_edge (hv : v ≠ 0)
    (h : D.cartanMatrix i j = -3) (h' : D.cartanMatrix j i = -1)
    (h4 : (v ^ D.d i) ^ 4 + 1 ≠ 0) :
    qSerre (v ^ D.d j) (1 - D.cartanMatrix j i).toNat
      (braidFj R v i j) (braidFi R i) = 0 := by
  have hs := congrArg (chevalley R v)
    (qSerre_braidEj_braidEi_of_triple_edge (R := R) hv h h' h4)
  rw [map_qSerre, map_zero, chevalley_braidEi hv,
    chevalley_braidEj_of_cartanMatrix_eq_neg_three hv h, qSerre_smul_smul] at hs
  exact (smul_eq_zero.mp hs).resolve_left
    (mul_ne_zero (pow_ne_zero _ (neg_ne_zero.mpr (pow_ne_zero _ (inv_ne_zero (pow_ne_zero _ hv)))))
      (pow_ne_zero _ (pow_ne_zero _ hv)))

end QuantumGroup
