/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.BraidAction.NeighborSerreDegreeOne
import LieLean.Algebra.QuantumGroup.BraidAction.TripleEdge

/-!
# The braid automorphism at the long node of `G₂`

For an exact two-node Cartan datum with entries `aᵢⱼ = -1`, `aⱼᵢ = -3` (type `G₂`, with `i` the
long simple root), Lusztig's `Tᵢ` is an algebra automorphism of `U`. The image
`X = Tᵢ(Eⱼ) = EᵢEⱼ - vᵢ⁻¹EⱼEᵢ` has degree one, and by `NeighborSerreDegreeOne.lean` the only
input needed is the positive identity `serreAux p p 3 X Eⱼ = 0` (`p = vⱼ`, `vᵢ = p³`), i.e.

  `X³Eⱼ - [3]_p p X²EⱼX + [3]_p p² XEⱼX² - p³ EⱼX³ = 0`.

We prove it by an explicit certificate: `p⁷(p⁶ + 1)` times the left side is a combination, with
coefficients in `ℤ[p]`, of two-sided multiples of the two original Serre relations
`S₂(Eᵢ, Eⱼ) = 0` (parameter `p³`) and `S₄(Eⱼ, Eᵢ) = 0` (parameter `p`).

## Main results

* `QuantumGroup.tripleEdgeOther_originalSerre_certificate`: the certificate, in any algebra.
* `QuantumGroup.tripleEdgeOther_serreAux_braidEj`: the positive identity in `U`.
* `QuantumGroup.qSerre_braidEj_braidEi_of_triple_edge_other`,
  `QuantumGroup.qSerre_braidFj_braidFi_of_triple_edge_other`: the neighbor-first quartic Serre
  relations `S₄(Tᵢ Eⱼ, Tᵢ Eᵢ) = 0`, `S₄(Tᵢ Fⱼ, Tᵢ Fᵢ) = 0` (ambient rank unrestricted).
* `QuantumGroup.tripleEdgeOther_transformedSerre`, `QuantumGroup.tripleEdgeOtherBraidEquiv`:
  `Tᵢ` as an algebra equivalence, with inverse the reversal conjugate of `Tᵢ`.

Assumptions: exactly two distinct nodes, entries `(-1, -3)`, arbitrary field and root-datum
lattice, `v ≠ 0`, `vᵢ - vᵢ⁻¹ ≠ 0` and `vᵢ² + 1 ≠ 0` (equivalently `p⁶ + 1 ≠ 0`). The last one
is cancelled from the certificate; its necessity is not claimed. (In the relevant weight space
the certificate is unique over `ℚ(p)` and has the denominator `p⁶ + 1`.) The automorphism at
the other node is `tripleEdgeBraidEquiv` (`TripleEdgeBraid.lean`); the length-six braid relation
is not treated here.

## References

Reconstructed from the quotient presentation; the certificate was found by exact linear algebra
over `ℚ(p)`. No primary source was consulted.
-/

noncomputable section

namespace QuantumGroup

section Ring

variable {k : Type*} [Field k] {B : Type*} [Ring B] [Algebra k B]

set_option maxHeartbeats 4000000 in
-- Expanding the 23-term certificate into words of length seven and comparing coefficients.
/-- Original-relation certificate for the neighbor-first relation at the long node of `G₂`:
with `X = ab - p⁻³ba`, `p⁷(p⁶ + 1) serreAux p p 3 X b` lies in the two-sided ideal generated by
`S₂(a, b)` (parameter `p³`) and `S₄(b, a)` (parameter `p`). Reconstructed by exact coefficient
elimination; the prefactor is retained, so no nonvanishing of `p⁶ + 1` is required here. -/
theorem tripleEdgeOther_originalSerre_certificate (a b : B) (p : k) (hp : p ≠ 0)
    (hs : qSerre (p ^ 3) 2 a b = 0) (ht : qSerre p 4 b a = 0) :
    (p ^ 7 * (p ^ 6 + 1)) • serreAux p p 3 (a * b - p⁻¹ ^ 3 • (b * a)) b = 0 := by
  set S1 := qSerre (p ^ 3) 2 a b with hS1
  set S2 := qSerre p 4 b a with hS2
  have he : (p ^ 7 * (p ^ 6 + 1)) • serreAux p p 3 (a * b - p⁻¹ ^ 3 • (b * a)) b =
      (p ^ 11 + p ^ 9) • (S1 * a * b ^ 3)
      - p ^ 10 • (a * S1 * b ^ 3)
      + (p ^ 14 + p ^ 12 + p ^ 10 + p ^ 8 + p ^ 6) • (a * b * S1 * b ^ 2)
      - (p ^ 14 + p ^ 12 + 2 * p ^ 10 + p ^ 8 + p ^ 6 + p ^ 4) • (a * b ^ 2 * S1 * b)
      + p ^ 10 • (a * b ^ 3 * S1)
      - (p ^ 14 + p ^ 12 + 2 * p ^ 10 + p ^ 8 + p ^ 6) • (S1 * b * a * b ^ 2)
      + (p ^ 10 - p ^ 4) • (b * S1 * a * b ^ 2)
      - (p ^ 11 + p ^ 9) • (b * a * S1 * b ^ 2)
      + (p ^ 13 + p ^ 11 + p ^ 9 + p ^ 7) • (b * a * b * S1 * b)
      + (p ^ 7 + p ^ 5 + p ^ 3 + p) • (b * a * b ^ 2 * S1)
      + (p ^ 13 + p ^ 11 + p ^ 9 + p ^ 7) • (S1 * b ^ 2 * a * b)
      + (p ^ 7 + p ^ 5 + p ^ 3 + p) • (b * S1 * b * a * b)
      - (p ^ 5 + p ^ 3) • (b ^ 2 * S1 * a * b)
      - (p ^ 10 - p ^ 4) • (b ^ 2 * a * S1 * b)
      - (p ^ 8 + p ^ 6 + 2 * p ^ 4 + p ^ 2 + 1) • (b ^ 2 * a * b * S1)
      + p ^ 4 • (S1 * b ^ 3 * a)
      - (p ^ 10 + p ^ 8 + p ^ 6 + 2 * p ^ 4 + p ^ 2 + 1) • (b * S1 * b ^ 2 * a)
      + (p ^ 8 + p ^ 6 + p ^ 4 + p ^ 2 + 1) • (b ^ 2 * S1 * b * a)
      - p ^ 4 • (b ^ 3 * S1 * a)
      + (p ^ 5 + p ^ 3) • (b ^ 3 * a * S1)
      + p ^ 4 • (S2 * a ^ 2)
      - (p ^ 10 + p ^ 4) • (a * S2 * a)
      + p ^ 10 • (a ^ 2 * S2) := by
    rw [hS1, hS2]
    simp only [qSerre, serreAux, Finset.sum_range_succ, Finset.sum_range_zero, qBinomial,
      Nat.reduceSub, pow_succ, pow_zero, mul_one, one_mul, mul_zero, add_zero,
      zero_add, one_smul, mul_neg, neg_mul, neg_neg, mul_sub, sub_mul, mul_add,
      add_mul, mul_smul_comm, smul_mul_assoc, smul_add, smul_sub, mul_assoc]
    match_scalars <;> field_simp [hp] <;> ring
  rw [he, hs, ht]
  simp

end Ring

variable {k : Type*} [Field k] {I Y : Type*} [AddCommGroup Y] [DecidableEq I]
  {D : LusztigCartanDatum I} {R : D.RootDatum Y} {v : k} {i j : I}

/-- The positive identity `serreAux p p 3 (Tᵢ Eⱼ) Eⱼ = 0`, `p = vⱼ`, at mutual entries
`(-1, -3)`, from the original Serre relations. The ambient rank is unrestricted; the proof
cancels `vᵢ² + 1`, whose necessity is not claimed. Reconstructed. -/
theorem tripleEdgeOther_serreAux_braidEj (hv : v ≠ 0)
    (h : D.cartanMatrix i j = -1) (h' : D.cartanMatrix j i = -3)
    (h2 : (v ^ D.d i) ^ 2 + 1 ≠ 0) :
    serreAux (v ^ D.d j) (v ^ D.d j) (negA D j i) (braidEj R v i j) (E R v j) = 0 := by
  have hij : i ≠ j := by
    rintro rfl
    rw [D.cartanMatrix_self] at h
    norm_num at h
  have hp := parameter_eq_cube_of_triple_edge (v := v) h' h
  have hs : qSerre ((v ^ D.d j) ^ 3) 2 (E R v i) (E R v j) = 0 := by
    simpa only [h, hp, Int.reduceSub, Int.reduceToNat] using serre_E R v hij
  have ht : qSerre (v ^ D.d j) 4 (E R v j) (E R v i) = 0 := by
    simpa only [h', Int.reduceSub, Int.reduceToNat] using serre_E R v hij.symm
  have hc := tripleEdgeOther_originalSerre_certificate (E R v i) (E R v j) (v ^ D.d j)
    (pow_ne_zero _ hv) hs ht
  have hn : negA D j i = 3 := by simp [negA, h']
  rw [hn, braidEj_eq_of_cartanMatrix_eq_neg_one h, hp, ← inv_pow]
  refine (smul_eq_zero.mp hc).resolve_left (mul_ne_zero (pow_ne_zero _ (pow_ne_zero _ hv)) ?_)
  have h6 : (v ^ D.d j) ^ 6 = ((v ^ D.d j) ^ 3) ^ 2 := by ring
  rwa [h6, ← hp]

/-- **Neighbor-first quartic Serre relation at the long node of `G₂`**:
`S₄(Tᵢ Eⱼ, Tᵢ Eᵢ) = 0` at mutual entries `(-1, -3)`. The ambient rank and toral lattice are
unrestricted. The proof cancels `vᵢ² + 1`; its necessity is not claimed. Reconstructed. -/
theorem qSerre_braidEj_braidEi_of_triple_edge_other [NeZero v]
    (h : D.cartanMatrix i j = -1) (h' : D.cartanMatrix j i = -3)
    (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) (h2 : (v ^ D.d i) ^ 2 + 1 ≠ 0) :
    qSerre (v ^ D.d j) (1 - D.cartanMatrix j i).toNat
      (braidEj R v i j) (braidEi R i) = 0 := by
  rw [degreeOne_qSerre_braidEj_braidEi_eq_serreAux h hq]
  exact tripleEdgeOther_serreAux_braidEj (NeZero.ne v) h h' h2

/-- The negative neighbor-first quartic Serre relation at mutual entries `(-1, -3)`, via the
Chevalley involution. -/
theorem qSerre_braidFj_braidFi_of_triple_edge_other [NeZero v]
    (h : D.cartanMatrix i j = -1) (h' : D.cartanMatrix j i = -3)
    (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) (h2 : (v ^ D.d i) ^ 2 + 1 ≠ 0) :
    qSerre (v ^ D.d j) (1 - D.cartanMatrix j i).toNat
      (braidFj R v i j) (braidFi R i) = 0 :=
  degreeOne_qSerre_braidFj_braidFi h (qSerre_braidEj_braidEi_of_triple_edge_other h h' hq h2)

variable [NeZero v] (hij : i ≠ j) (hall : ∀ l, l = i ∨ l = j)
  (h : D.cartanMatrix i j = -1) (h' : D.cartanMatrix j i = -3)

include hij hall h h' in
/-- The transformed quantum Serre relations at the long node of an exact `G₂` datum. -/
theorem tripleEdgeOther_transformedSerre (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0)
    (h2 : (v ^ D.d i) ^ 2 + 1 ≠ 0) : TransformedSerre R v i :=
  degreeOne_transformedSerre hij hall h hq (tripleEdgeOther_serreAux_braidEj (NeZero.ne v) h h' h2)

/-- **Lusztig's braid automorphism at the long node of `G₂`**, with explicit inverse.
Assumptions: exactly two distinct nodes, entries `aᵢⱼ = -1`, `aⱼᵢ = -3`, arbitrary field and
root-datum lattice, `v ≠ 0`, `vᵢ - vᵢ⁻¹ ≠ 0` and `vᵢ² + 1 ≠ 0`. -/
def tripleEdgeOtherBraidEquiv (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0)
    (h2 : (v ^ D.d i) ^ 2 + 1 ≠ 0) : QuantumGroup R v ≃ₐ[k] QuantumGroup R v :=
  braidEquiv (degreeOne_braidGeneric hall h hq)
    (tripleEdgeOther_transformedSerre hij hall h h' hq h2)

end QuantumGroup
