/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.QuantumGroup.BraidAction.NeighborSerreShort
import LieLean.Algebra.QuantumGroup.BraidAction.TripleEdgeBraid

/-!
# The braid automorphism at the short node of a two-node datum

For an exact two-node Cartan datum `{i, j}` with `aⱼᵢ = -1` and arbitrary `aᵢⱼ = -r` (so `i` is
the short node: types `A₂`, `B₂`, `G₂` for `r = 1, 2, 3`, and the rank-two Kac–Moody data
`(-r, -1)` for `r ≥ 4`), Lusztig's `Tᵢ` is an algebra automorphism of `U`, uniformly in `r`.

## Main results

* `QuantumGroup.shortNode_transformedSerre`: the transformed Serre relations at `i`, from
  `BraidAction/NeighborSerreShort.lean`.
* `QuantumGroup.shortNodeBraidEquiv`: `Tᵢ` as an algebra equivalence (`braidEquiv`), assuming
  `BraidGeneric D v i` and `[2r-2, r-1]ᵢ ≠ 0`.
* `QuantumGroup.shortNode_qBinomial_ne_zero_of_negA_le_two`,
  `QuantumGroup.shortNodeBraidEquiv_of_negA_le_two`: for `r ≤ 2` (types `A₂`, `B₂`) the extra
  hypothesis follows from `BraidGeneric`.
* `QuantumGroup.shortNodeBraidEquiv_of_not_root`: if `v` is not a root of unity, no further
  hypothesis is needed.
* `QuantumGroup.shortNode_qBinomial_ne_zero_of_triple_edge`,
  `QuantumGroup.shortNodeBraidEquiv_eq_tripleEdgeBraidEquiv`: for `G₂` the extra hypothesis
  follows from `[3]ᵢ! ≠ 0` and `vᵢ⁴ + 1 ≠ 0`, and the automorphism is `tripleEdgeBraidEquiv`.

For `G₂` the hypothesis `vᵢ⁴ + 1 ≠ 0` is therefore not removed. It is equivalent to
`[4, 2]ᵢ ≠ 0` given `[3]ᵢ! ≠ 0`, and it cannot be dropped from the positive-part identity used
here: at `vᵢ⁴ = -1` the element `X 3 X 2 - vᵢ³ X 2 X 3` is not in the ideal generated by the
two Serre relations (see `BraidAction/NeighborSerreShort.lean`).

## References

Reconstructed from the quotient presentation.
-/

open LieLean

noncomputable section

namespace LieLean.QuantumGroup

variable {k : Type*} [Field k] {I Y : Type*} [AddCommGroup Y] [DecidableEq I]
  {D : LusztigCartanDatum I} {R : D.RootDatum Y} {v : k} [NeZero v]
  {i j : I} (hij : i ≠ j) (hall : ∀ l, l = i ∨ l = j) (h' : D.cartanMatrix j i = -1)

include hij hall h' in
/-- The transformed quantum Serre relations at the short node of an exact two-node datum. -/
theorem shortNode_transformedSerre (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0)
    (hb : qBinomial (v ^ D.d i) (2 * negA D i j - 2) (negA D i j - 1) ≠ 0) :
    TransformedSerre R v i where
  serre_E l m hlm hl := by
    rcases hall l with rfl | rfl <;> rcases hall m with rfl | rfl
    · exact (hlm rfl).elim
    · exact (hl rfl).elim
    · simpa [braidImageE, hij.symm] using shortNode_qSerre_braidEj_braidEi (R := R) h' hq hb
    · exact (hlm rfl).elim
  serre_F l m hlm hl := by
    rcases hall l with rfl | rfl <;> rcases hall m with rfl | rfl
    · exact (hlm rfl).elim
    · exact (hl rfl).elim
    · simpa [braidImageF, hij.symm] using shortNode_qSerre_braidFj_braidFi (R := R) h' hq hb
    · exact (hlm rfl).elim

/-- **Lusztig's braid automorphism at the short node** of an exact two-node datum with
`aⱼᵢ = -1`, for every `aᵢⱼ = -r`, with explicit reversal-conjugate inverse. -/
def shortNodeBraidEquiv (hg : BraidGeneric D v i)
    (hb : qBinomial (v ^ D.d i) (2 * negA D i j - 2) (negA D i j - 1) ≠ 0) :
    QuantumGroup R v ≃ₐ[k] QuantumGroup R v :=
  braidEquiv hg (shortNode_transformedSerre hij hall h' hg.sub_ne hb)

omit [DecidableEq I] [NeZero v] in
include hij in
/-- For `r ≤ 2` the extra hypothesis follows from `[r]ᵢ! ≠ 0`. -/
theorem shortNode_qBinomial_ne_zero_of_negA_le_two (hg : BraidGeneric D v i)
    (h : negA D i j ≤ 2) :
    qBinomial (v ^ D.d i) (2 * negA D i j - 2) (negA D i j - 1) ≠ 0 := by
  obtain h0 | h0 | h0 : negA D i j = 0 ∨ negA D i j = 1 ∨ negA D i j = 2 := by omega
  · simp [h0]
  · simp [h0]
  · have hf := hg.qFactorial_ne j (Ne.symm hij)
    rw [h0] at hf ⊢
    simp only [qFactorial_succ, qFactorial_zero, mul_one] at hf
    simpa [qBinomial_one_right] using left_ne_zero_of_mul hf

/-- The automorphism at the short node for `r = -aᵢⱼ ≤ 2` (types `A₂`, `B₂`), with no
hypothesis beyond `BraidGeneric`. -/
def shortNodeBraidEquiv_of_negA_le_two (hg : BraidGeneric D v i) (h : negA D i j ≤ 2) :
    QuantumGroup R v ≃ₐ[k] QuantumGroup R v :=
  shortNodeBraidEquiv hij hall h' hg (shortNode_qBinomial_ne_zero_of_negA_le_two hij hg h)

omit [DecidableEq I] in
/-- At a parameter that is not a root of unity, the extra hypothesis holds. -/
theorem shortNode_qBinomial_ne_zero_of_not_root (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) :
    qBinomial (v ^ D.d i) (2 * negA D i j - 2) (negA D i j - 1) ≠ 0 := by
  classical
  intro h0
  have h := qBinomial_mul_qFactorial_mul_qFactorial (v := v ^ D.d i)
    (show negA D i j - 1 ≤ 2 * negA D i j - 2 by omega)
  rw [h0, zero_mul, zero_mul] at h
  exact LusztigF.qFactorial_ne_zero_of_not_root (NeZero.ne v) hv' i _ h.symm

omit [DecidableEq I] in
/-- At a parameter that is not a root of unity, the generic hypotheses of `braidEquiv` hold
at every node. -/
theorem shortNode_braidGeneric_of_not_root (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) (i : I) :
    BraidGeneric D v i where
  sub_ne h0 := by
    have hq : v ^ D.d i ≠ 0 := pow_ne_zero _ (NeZero.ne v)
    apply hv' (D.d i * 2) (Nat.mul_pos (D.d_pos i) two_pos)
    rw [sub_eq_zero] at h0
    calc v ^ (D.d i * 2) = v ^ D.d i * v ^ D.d i := by rw [pow_mul, sq]
      _ = v ^ D.d i * (v ^ D.d i)⁻¹ := by nth_rewrite 2 [h0]; rfl
      _ = 1 := mul_inv_cancel₀ hq
  qFactorial_ne _ _ := by
    classical
    exact LusztigF.qFactorial_ne_zero_of_not_root (NeZero.ne v) hv' i _

/-- **The short-node automorphism at a generic parameter**: for an exact two-node datum with
`aⱼᵢ = -1` and any `aᵢⱼ`, if `v` is not a root of unity then `Tᵢ` is an automorphism. -/
def shortNodeBraidEquiv_of_not_root (hv' : ∀ n : ℕ, 0 < n → v ^ n ≠ 1) :
    QuantumGroup R v ≃ₐ[k] QuantumGroup R v :=
  shortNodeBraidEquiv hij hall h' (shortNode_braidGeneric_of_not_root hv' i)
    (shortNode_qBinomial_ne_zero_of_not_root hv')

omit [DecidableEq I] [NeZero v] in
/-- For `G₂` (`r = 3`) the extra hypothesis follows from `[3]ᵢ! ≠ 0` and `vᵢ⁴ + 1 ≠ 0`. -/
theorem shortNode_qBinomial_ne_zero_of_triple_edge (hv : v ≠ 0) (h : D.cartanMatrix i j = -3)
    (h3 : qFactorial (v ^ D.d i) 3 ≠ 0) (h4 : (v ^ D.d i) ^ 4 + 1 ≠ 0) :
    qBinomial (v ^ D.d i) (2 * negA D i j - 2) (negA D i j - 1) ≠ 0 := by
  have hr : negA D i j = 3 := by simp [negA, h]
  rw [hr]
  set q := v ^ D.d i
  have hq : q ≠ 0 := pow_ne_zero _ hv
  have h2 : qInt q 2 ≠ 0 := by
    intro h0
    apply h3
    simp [qFactorial_succ, h0]
  have h4' : qInt q 4 = qInt q 2 * (q⁻¹ ^ 2 * (q ^ 4 + 1)) := by
    simp only [qInt, Finset.sum_range_succ, Finset.sum_range_zero]
    field_simp
    ring
  have hf4 : qFactorial q 4 ≠ 0 := by
    rw [qFactorial_succ, h4']
    exact mul_ne_zero (mul_ne_zero h2 (mul_ne_zero (pow_ne_zero _ (inv_ne_zero hq)) h4)) h3
  have hb := qBinomial_mul_qFactorial_mul_qFactorial (v := q) (show 2 ≤ 4 by norm_num)
  rw [show 2 * 3 - 2 = 4 by norm_num, show 3 - 1 = 2 by norm_num]
  intro h0
  apply hf4
  rw [← hb, h0, zero_mul, zero_mul]

include hij hall h' in
/-- At the triple node of `G₂`, the short-node automorphism is `tripleEdgeBraidEquiv`. -/
theorem shortNodeBraidEquiv_eq_tripleEdgeBraidEquiv (h : D.cartanMatrix i j = -3)
    (hq : v ^ D.d i - (v ^ D.d i)⁻¹ ≠ 0) (h3 : qFactorial (v ^ D.d i) 3 ≠ 0)
    (h4 : (v ^ D.d i) ^ 4 + 1 ≠ 0) :
    shortNodeBraidEquiv (R := R) hij hall h' (tripleEdge_braidGeneric hij hall h hq h3)
        (shortNode_qBinomial_ne_zero_of_triple_edge (NeZero.ne v) h h3 h4) =
      tripleEdgeBraidEquiv hij hall h h' hq h3 h4 :=
  rfl

end LieLean.QuantumGroup
