/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.GroupTheory.Coxeter.Exchange
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.LinearAlgebra.Finsupp.VectorSpace
import Mathlib.LinearAlgebra.Finsupp.LinearCombination
import Mathlib.Tactic.Module

/-!
# The Iwahori–Hecke algebra of a Coxeter system

Let `(W, S)` be a Coxeter system (`cs : CoxeterSystem M W`), `R` a commutative ring and `q ∈ R`.
The (generic) Iwahori–Hecke algebra `𝓗 = 𝓗_q(W)` is the `R`-algebra with an `R`-basis
`(T_w)_{w ∈ W}` in which, for `s ∈ S` and `w ∈ W`,
```
T_s T_w = T_{sw}                        if ℓ(sw) > ℓ(w),
T_s T_w = (q - 1) T_w + q T_{sw}        if ℓ(sw) < ℓ(w).
```

**Convention.** We use the normalization of [HumC] Ch. 7 and of [KL]: the quadratic relation is
`(T_s - q)(T_s + 1) = 0`, i.e. `T_s² = (q - 1) T_s + q` (`T_simple_mul_self`,
`T_simple_sub_mul_T_simple_add`). For Kazhdan–Lusztig theory one takes `R = ℤ[v, v⁻¹]` and
`q = v²`; Soergel's normalization `H_s = v⁻¹ T_s` is not used here.

## Construction

We follow [HumC] §7.1–7.3 (the argument does not use Matsumoto's theorem). On the free module
`E = W →₀ R` with basis `(e_w)` we define operators `λ_s` ("left multiplication by `T_s`") and
`ρ_s` ("right multiplication by `T_s`") by the formulas above (`leftOp`, `rightOp`). The
exchange condition (through `CoxeterSystem.simple_mul_eq_mul_simple`) shows that every `λ_s`
commutes with every `ρ_t` (`leftOp_mul_rightOp`). Let `𝓛 ⊆ End_R(E)` be the commutant of the
`ρ_t` (`heckeOps`; Humphreys uses instead the subalgebra generated by the `λ_s`, which turns out
to be the same). The map `𝓛 → E`, `f ↦ f(e_1)`, is bijective: it is injective because
`e_w = ρ_{s_k} ⋯ ρ_{s_1} e_1` for a reduced word `w = s_1 ⋯ s_k`, and surjective because
`λ_{s_1} ⋯ λ_{s_k} e_1 = e_w`. Its inverse `lmul : E → 𝓛` transports the composition of `𝓛` to a
multiplication on `E` with unit `e_1`, and `𝓗` is `E` with this multiplication; `T_w = e_w`.

## Main definitions

* `IwahoriHeckeAlgebra cs q`: the Iwahori–Hecke algebra, an `R`-algebra.
* `IwahoriHeckeAlgebra.basis cs q : Basis W R (IwahoriHeckeAlgebra cs q)`, with
  `IwahoriHeckeAlgebra.T cs q w = basis cs q w`.

## Main results

* `IwahoriHeckeAlgebra.T_one`, `T_simple_mul_T`, `T_mul_T_simple`: the defining formulas
  ([GP] Lemma 4.4.3).
* `IwahoriHeckeAlgebra.T_mul_T`: `T_x T_y = T_{xy}` if `ℓ(xy) = ℓ(x) + ℓ(y)`.
* `IwahoriHeckeAlgebra.T_simple_mul_self`: the quadratic relation.
* `IwahoriHeckeAlgebra.isUnit_T`: if `q` is a unit, every `T_w` is invertible
  ([GP] Remark 4.4.4(b)).
* `IwahoriHeckeAlgebra.adjoin_T_simple`, `algHom_ext`: `𝓗` is generated by the `T_s`.
* `IwahoriHeckeAlgebra.map_mul_of_map_mul_T_simple`: a criterion for a semilinear map out of `𝓗`
  to be multiplicative (used for the bar involution and for specializations).

## References

* [HumC] J. E. Humphreys, *Reflection groups and Coxeter groups*, CUP 1990, §7.1–7.3.
* [KL] D. Kazhdan, G. Lusztig, *Representations of Coxeter groups and Hecke algebras*,
  Invent. Math. **53** (1979), 165–184.
* [GP] M. Geck, G. Pfeiffer, *Characters of finite Coxeter groups and Iwahori–Hecke algebras*,
  LMS Monographs 21, OUP 2000, §4.4.
-/

open Finsupp Module

namespace IwahoriHeckeAlgebra

variable {B W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)
variable {R : Type*} [CommRing R] (q : R)

local prefix:100 "s " => cs.simple
local prefix:100 "ℓ " => cs.length

/-- The operator `λ_s` on `W →₀ R` of left multiplication by `T_s`:
`e_w ↦ e_{sw}` if `ℓ(sw) > ℓ(w)`, `e_w ↦ (q - 1) e_w + q e_{sw}` otherwise ([HumC] §7.2). -/
noncomputable def leftOp (i : B) : Module.End R (W →₀ R) :=
  linearCombination R fun w ↦ if ℓ w < ℓ (s i * w) then single (s i * w) 1
    else (q - 1) • single w 1 + q • single (s i * w) 1

/-- The operator `ρ_s` on `W →₀ R` of right multiplication by `T_s`:
`e_w ↦ e_{ws}` if `ℓ(ws) > ℓ(w)`, `e_w ↦ (q - 1) e_w + q e_{ws}` otherwise ([HumC] §7.2). -/
noncomputable def rightOp (i : B) : Module.End R (W →₀ R) :=
  linearCombination R fun w ↦ if ℓ w < ℓ (w * s i) then single (w * s i) 1
    else (q - 1) • single w 1 + q • single (w * s i) 1

theorem leftOp_single (i : B) (w : W) : leftOp cs q i (single w 1) =
    if ℓ w < ℓ (s i * w) then single (s i * w) 1
    else (q - 1) • single w 1 + q • single (s i * w) 1 := by
  simp [leftOp]

theorem rightOp_single (i : B) (w : W) : rightOp cs q i (single w 1) =
    if ℓ w < ℓ (w * s i) then single (w * s i) 1
    else (q - 1) • single w 1 + q • single (w * s i) 1 := by
  simp [rightOp]

theorem leftOp_single_one (i : B) : leftOp cs q i (single 1 1) = single (s i) 1 := by
  simp [leftOp_single]

theorem rightOp_single_one (i : B) : rightOp cs q i (single 1 1) = single (s i) 1 := by
  simp [rightOp_single]

/-- The left operators `λ_s` commute with the right operators `ρ_t` (proof of [GP] Thm. 4.4.6). -/
theorem leftOp_mul_rightOp (i j : B) :
    leftOp cs q i * rightOp cs q j = rightOp cs q j * leftOp cs q i := by
  refine Finsupp.lhom_ext' fun w ↦ LinearMap.ext_ring ?_
  simp only [LinearMap.coe_comp, Function.comp_apply, lsingle_apply, Module.End.mul_apply]
  have hL := cs.length_simple_mul w i
  have hR := cs.length_mul_simple w j
  have hLR := cs.length_mul_simple (s i * w) j
  have hRL := cs.length_simple_mul (w * s j) i
  rw [← mul_assoc] at hRL
  by_cases c1 : ℓ w < ℓ (w * s j) <;> by_cases c2 : ℓ (w * s j) < ℓ (s i * w * s j) <;>
  by_cases c3 : ℓ w < ℓ (s i * w) <;> by_cases c4 : ℓ (s i * w) < ℓ (s i * w * s j) <;>
  simp only [leftOp_single, rightOp_single, map_add, map_smul, ← mul_assoc, c1, c2, c3, c4,
    ite_true, ite_false] <;>
  first
  | omega
  | module
  | rw [cs.simple_mul_eq_mul_simple (i := i) (j := j) (w := w) (by omega) (by omega)]

/-- The submodule of `End_R(W →₀ R)` of operators commuting with all the right operators `ρ_s`.
The Iwahori–Hecke algebra is identified with it through `lmul`. -/
def heckeOps : Submodule R (Module.End R (W →₀ R)) where
  carrier := {f | ∀ i, f * rightOp cs q i = rightOp cs q i * f}
  add_mem' {f g} hf hg i := by rw [add_mul, mul_add, hf i, hg i]
  zero_mem' i := by simp
  smul_mem' c f hf i := by rw [smul_mul_assoc, mul_smul_comm, hf i]

variable {cs q} in
theorem heckeOps_apply_rightOp {f : Module.End R (W →₀ R)} (hf : f ∈ heckeOps cs q) (i : B)
    (x : W →₀ R) : f (rightOp cs q i x) = rightOp cs q i (f x) :=
  LinearMap.congr_fun (hf i) x

theorem leftOp_mem_heckeOps (i : B) : leftOp cs q i ∈ heckeOps cs q :=
  fun j ↦ leftOp_mul_rightOp cs q i j

theorem one_mem_heckeOps : (1 : Module.End R (W →₀ R)) ∈ heckeOps cs q := fun i ↦ by simp

variable {cs q} in
theorem mul_mem_heckeOps {f g : Module.End R (W →₀ R)} (hf : f ∈ heckeOps cs q)
    (hg : g ∈ heckeOps cs q) : f * g ∈ heckeOps cs q := fun i ↦ by
  rw [mul_assoc, hg i, ← mul_assoc, hf i, mul_assoc]

variable {cs q} in
/-- An operator commuting with the `ρ_s` is determined by its value at `e_1`. -/
theorem eq_of_mem_heckeOps {f g : Module.End R (W →₀ R)} (hf : f ∈ heckeOps cs q)
    (hg : g ∈ heckeOps cs q) (h : f (single 1 1) = g (single 1 1)) : f = g := by
  have key : ∀ w : W, f (single w 1) = g (single w 1) := by
    intro w
    induction w using cs.induction_mul_simple with
    | one => exact h
    | mul_simple w i hlt ih =>
      have : single (w * s i) (1 : R) = rightOp cs q i (single w 1) := by
        rw [rightOp_single, ite_eq_left hlt]
      rw [this, heckeOps_apply_rightOp hf, heckeOps_apply_rightOp hg, ih]
  refine Finsupp.lhom_ext fun w c ↦ ?_
  rw [← smul_single_one, map_smul, map_smul, key]

/-- Evaluation at `e_1` on `heckeOps`. -/
noncomputable def evalOne : heckeOps cs q →ₗ[R] (W →₀ R) where
  toFun f := f.1 (single 1 1)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

theorem evalOne_bijective : Function.Bijective (evalOne cs q) := by
  refine ⟨fun f g h ↦ Subtype.ext (eq_of_mem_heckeOps f.2 g.2 h), ?_⟩
  have key : ∀ w : W, single w (1 : R) ∈ LinearMap.range (evalOne cs q) := by
    intro w
    induction w using cs.induction_simple_mul with
    | one => exact ⟨⟨1, one_mem_heckeOps cs q⟩, rfl⟩
    | simple_mul w i hlt ih =>
      obtain ⟨f, hf⟩ := ih
      refine ⟨⟨leftOp cs q i * f.1, mul_mem_heckeOps (leftOp_mem_heckeOps cs q i) f.2⟩, ?_⟩
      change leftOp cs q i (evalOne cs q f) = _
      rw [hf, leftOp_single, ite_eq_left hlt]
  rw [← LinearMap.range_eq_top, eq_top_iff]
  rintro x -
  induction x using Finsupp.induction_linear with
  | zero => exact zero_mem _
  | add x y hx hy => exact add_mem hx hy
  | single w c =>
    rw [← smul_single_one]
    exact Submodule.smul_mem _ _ (key w)

/-- The left regular representation `x ↦ (y ↦ x y)` of the Iwahori–Hecke algebra on its
underlying module `W →₀ R`: `lmul x` is the unique operator commuting with the `ρ_s` that maps
`e_1` to `x`. -/
noncomputable def lmul : (W →₀ R) →ₗ[R] Module.End R (W →₀ R) :=
  (heckeOps cs q).subtype ∘ₗ
    (LinearEquiv.ofBijective (evalOne cs q) (evalOne_bijective cs q)).symm.toLinearMap

theorem lmul_mem (x : W →₀ R) : lmul cs q x ∈ heckeOps cs q :=
  ((LinearEquiv.ofBijective (evalOne cs q) (evalOne_bijective cs q)).symm x).2

theorem lmul_apply_single_one (x : W →₀ R) : lmul cs q x (single 1 1) = x :=
  (LinearEquiv.ofBijective (evalOne cs q) (evalOne_bijective cs q)).apply_symm_apply x

theorem lmul_apply_rightOp (x : W →₀ R) (i : B) (y : W →₀ R) :
    lmul cs q x (rightOp cs q i y) = rightOp cs q i (lmul cs q x y) :=
  heckeOps_apply_rightOp (lmul_mem cs q x) i y

variable {cs q} in
theorem lmul_eq {f : Module.End R (W →₀ R)} (hf : f ∈ heckeOps cs q) :
    lmul cs q (f (single 1 1)) = f :=
  eq_of_mem_heckeOps (lmul_mem cs q _) hf (lmul_apply_single_one cs q _)

theorem lmul_single_one : lmul cs q (single 1 1) = 1 := lmul_eq (one_mem_heckeOps cs q)

theorem lmul_single_simple (i : B) : lmul cs q (single (s i) 1) = leftOp cs q i := by
  rw [← lmul_eq (leftOp_mem_heckeOps cs q i), leftOp_single_one]

theorem lmul_lmul (x y : W →₀ R) : lmul cs q (lmul cs q x y) = lmul cs q x * lmul cs q y := by
  conv_lhs => rw [← lmul_apply_single_one cs q y]
  exact lmul_eq (mul_mem_heckeOps (lmul_mem cs q x) (lmul_mem cs q y))

end IwahoriHeckeAlgebra

variable {B W : Type*} [Group W] {M : CoxeterMatrix B}
variable {R : Type*} [CommRing R]

/-- The Iwahori–Hecke algebra `𝓗_q(W)` of the Coxeter system `cs` over `R` with parameter `q`
([HumC] §7.1–7.3). As an `R`-module it is `W →₀ R`, with standard basis
`IwahoriHeckeAlgebra.T cs q w`; the product `x y` is `λ_x(y)` where `λ_x` is the unique operator
on `W →₀ R` commuting with the right operators `ρ_s` and mapping `e_1` to `x`. -/
def IwahoriHeckeAlgebra (_cs : CoxeterSystem M W) (_q : R) : Type _ := W →₀ R

namespace IwahoriHeckeAlgebra

variable (cs : CoxeterSystem M W) (q : R)

local prefix:100 "s " => cs.simple
local prefix:100 "ℓ " => cs.length

noncomputable instance : AddCommGroup (IwahoriHeckeAlgebra cs q) :=
  inferInstanceAs (AddCommGroup (W →₀ R))

noncomputable instance : Module R (IwahoriHeckeAlgebra cs q) :=
  inferInstanceAs (Module R (W →₀ R))

/-- The identification of `𝓗` with `W →₀ R` as `R`-modules. -/
noncomputable def toFinsupp : IwahoriHeckeAlgebra cs q ≃ₗ[R] (W →₀ R) := LinearEquiv.refl R _

noncomputable instance : Ring (IwahoriHeckeAlgebra cs q) :=
  { (inferInstance : AddCommGroup (IwahoriHeckeAlgebra cs q)) with
    mul x y := (toFinsupp cs q).symm (lmul cs q (toFinsupp cs q x) (toFinsupp cs q y))
    one := (toFinsupp cs q).symm (single 1 1)
    mul_assoc x y z := by
      change lmul cs q (lmul cs q (toFinsupp cs q x) (toFinsupp cs q y)) (toFinsupp cs q z) =
        lmul cs q (toFinsupp cs q x) (lmul cs q (toFinsupp cs q y) (toFinsupp cs q z))
      rw [lmul_lmul]
      rfl
    one_mul x := by
      change lmul cs q (single 1 1) (toFinsupp cs q x) = x
      rw [lmul_single_one]
      rfl
    mul_one x := lmul_apply_single_one cs q x
    left_distrib x y z := map_add (lmul cs q x) y z
    right_distrib x y z := by
      change lmul cs q (toFinsupp cs q (x + y)) (toFinsupp cs q z) =
        lmul cs q (toFinsupp cs q x) (toFinsupp cs q z) +
          lmul cs q (toFinsupp cs q y) (toFinsupp cs q z)
      rw [map_add, map_add]
      rfl
    zero_mul x := by
      change lmul cs q (toFinsupp cs q 0) (toFinsupp cs q x) = 0
      rw [map_zero, map_zero, LinearMap.zero_apply]
    mul_zero x := map_zero (lmul cs q x) }

theorem mul_def (x y : IwahoriHeckeAlgebra cs q) :
    x * y = (toFinsupp cs q).symm (lmul cs q (toFinsupp cs q x) (toFinsupp cs q y)) := rfl

theorem toFinsupp_mul (x y : IwahoriHeckeAlgebra cs q) :
    toFinsupp cs q (x * y) = lmul cs q (toFinsupp cs q x) (toFinsupp cs q y) := rfl

theorem toFinsupp_one : toFinsupp cs q 1 = single 1 1 := rfl

noncomputable instance : Algebra R (IwahoriHeckeAlgebra cs q) :=
  Algebra.ofModule
    (fun r x y ↦ by
      apply (toFinsupp cs q).injective
      rw [map_smul, toFinsupp_mul, toFinsupp_mul, map_smul, map_smul, LinearMap.smul_apply])
    (fun r x y ↦ by
      apply (toFinsupp cs q).injective
      rw [map_smul, toFinsupp_mul, toFinsupp_mul, map_smul, map_smul])

/-- The standard basis `(T_w)_{w ∈ W}` of the Iwahori–Hecke algebra. -/
noncomputable def basis : Basis W R (IwahoriHeckeAlgebra cs q) :=
  Finsupp.basisSingleOne.map (toFinsupp cs q).symm

/-- The standard basis element `T_w` of the Iwahori–Hecke algebra. -/
noncomputable def T (w : W) : IwahoriHeckeAlgebra cs q := (toFinsupp cs q).symm (single w 1)

theorem basis_apply (w : W) : basis cs q w = T cs q w := by simp [basis, T]

theorem toFinsupp_T (w : W) : toFinsupp cs q (T cs q w) = single w 1 := rfl

theorem basis_repr_apply (h : IwahoriHeckeAlgebra cs q) :
    (basis cs q).repr h = toFinsupp cs q h := by
  simp [basis]

@[simp]
theorem T_one : T cs q 1 = 1 := rfl

theorem toFinsupp_T_mul (w : W) (x : IwahoriHeckeAlgebra cs q) :
    toFinsupp cs q (T cs q w * x) = lmul cs q (single w 1) (toFinsupp cs q x) := rfl

theorem toFinsupp_mul_T (x : IwahoriHeckeAlgebra cs q) (w : W) :
    toFinsupp cs q (x * T cs q w) = lmul cs q (toFinsupp cs q x) (single w 1) := rfl

/-- `T_s T_w = T_{sw}` if `ℓ(sw) > ℓ(w)`, and `T_s T_w = (q - 1) T_w + q T_{sw}` otherwise
([GP] Lemma 4.4.3(b)). -/
theorem T_simple_mul_T (i : B) (w : W) : T cs q (s i) * T cs q w =
    if ℓ w < ℓ (s i * w) then T cs q (s i * w)
    else (q - 1) • T cs q w + q • T cs q (s i * w) := by
  apply (toFinsupp cs q).injective
  rw [toFinsupp_T_mul, lmul_single_simple, toFinsupp_T, leftOp_single]
  split_ifs <;> simp [toFinsupp_T]

/-- `T_w T_s = T_{ws}` if `ℓ(ws) > ℓ(w)`, and `T_w T_s = (q - 1) T_w + q T_{ws}` otherwise
([GP] Lemma 4.4.3(b)). -/
theorem T_mul_T_simple (w : W) (i : B) : T cs q w * T cs q (s i) =
    if ℓ w < ℓ (w * s i) then T cs q (w * s i)
    else (q - 1) • T cs q w + q • T cs q (w * s i) := by
  apply (toFinsupp cs q).injective
  rw [toFinsupp_mul_T, toFinsupp_T, ← rightOp_single_one cs q, lmul_apply_rightOp,
    lmul_apply_single_one, rightOp_single]
  split_ifs <;> simp [toFinsupp_T]

theorem T_simple_mul_T_of_lt {i : B} {w : W} (h : ℓ w < ℓ (s i * w)) :
    T cs q (s i) * T cs q w = T cs q (s i * w) := by
  rw [T_simple_mul_T, ite_eq_left h]

theorem T_mul_T_simple_of_lt {w : W} {i : B} (h : ℓ w < ℓ (w * s i)) :
    T cs q w * T cs q (s i) = T cs q (w * s i) := by
  rw [T_mul_T_simple, ite_eq_left h]

theorem T_simple_mul_T_of_lt' {i : B} {w : W} (h : ℓ (s i * w) < ℓ w) :
    T cs q (s i) * T cs q w = (q - 1) • T cs q w + q • T cs q (s i * w) := by
  rw [T_simple_mul_T, ite_eq_right (by omega)]

theorem T_mul_T_simple_of_lt' {w : W} {i : B} (h : ℓ (w * s i) < ℓ w) :
    T cs q w * T cs q (s i) = (q - 1) • T cs q w + q • T cs q (w * s i) := by
  rw [T_mul_T_simple, ite_eq_right (by omega)]

/-- `T_x T_y = T_{xy}` whenever `ℓ(xy) = ℓ(x) + ℓ(y)` ([KL] §1). -/
theorem T_mul_T {x y : W} (h : ℓ (x * y) = ℓ x + ℓ y) : T cs q x * T cs q y = T cs q (x * y) := by
  induction y using cs.induction_mul_simple generalizing x with
  | one => simp
  | mul_simple y i hlt ih =>
    have h1 := cs.length_mul_le (x * y) (s i)
    have h2 := cs.length_mul_le x y
    have h3 := cs.length_mul_simple y i
    rw [cs.length_simple, ← mul_assoc] at *
    have hxy : ℓ (x * y) = ℓ x + ℓ y := by omega
    rw [← T_mul_T_simple_of_lt cs q hlt, ← mul_assoc, ih hxy, T_mul_T_simple_of_lt cs q (by omega)]

/-- The quadratic relation `T_s² = (q - 1) T_s + q` ([KL] §1). -/
theorem T_simple_mul_self (i : B) :
    T cs q (s i) * T cs q (s i) = (q - 1) • T cs q (s i) + algebraMap R _ q := by
  rw [T_simple_mul_T_of_lt' cs q (by simp), CoxeterSystem.simple_mul_simple_self, T_one,
    Algebra.algebraMap_eq_smul_one]

/-- The quadratic relation in factored form: `(T_s - q)(T_s + 1) = 0`. -/
theorem T_simple_sub_mul_T_simple_add (i : B) :
    (T cs q (s i) - algebraMap R _ q) * (T cs q (s i) + 1) = 0 := by
  rw [sub_mul, mul_add, mul_add, T_simple_mul_self, mul_one, mul_one, ← Algebra.smul_def,
    sub_smul, one_smul]
  abel

/-- If `q` is a unit, `T_s` is a unit, with inverse `q⁻¹ T_s - (1 - q⁻¹)` ([HumC] §7.1). -/
theorem T_simple_mul_inv (hq : IsUnit q) (i : B) :
    T cs q (s i) * (hq.unit⁻¹.1 • T cs q (s i) - (1 - hq.unit⁻¹.1) • 1) = 1 := by
  have e : hq.unit⁻¹.1 * q = 1 := hq.val_inv_mul
  have e' : hq.unit⁻¹.1 * (q - 1) = 1 - hq.unit⁻¹.1 := by rw [mul_sub, e, mul_one]
  rw [mul_sub, mul_smul_comm, T_simple_mul_self, mul_smul_comm, mul_one,
    Algebra.algebraMap_eq_smul_one, smul_add, smul_smul, smul_smul, e, e', one_smul]
  abel

theorem inv_mul_T_simple (hq : IsUnit q) (i : B) :
    (hq.unit⁻¹.1 • T cs q (s i) - (1 - hq.unit⁻¹.1) • 1) * T cs q (s i) = 1 := by
  rw [sub_mul, smul_mul_assoc, smul_mul_assoc, one_mul]
  rw [← T_simple_mul_inv cs q hq i, mul_sub, mul_smul_comm, mul_smul_comm, mul_one]

theorem isUnit_T_simple (hq : IsUnit q) (i : B) : IsUnit (T cs q (s i)) :=
  ⟨⟨_, _, T_simple_mul_inv cs q hq i, inv_mul_T_simple cs q hq i⟩, rfl⟩

/-- If `q` is a unit, every `T_w` is a unit ([GP] Remark 4.4.4(b)). -/
theorem isUnit_T (hq : IsUnit q) (w : W) : IsUnit (T cs q w) := by
  induction w using cs.induction_simple_mul with
  | one => simp
  | simple_mul w i hlt ih =>
    rw [← T_simple_mul_T_of_lt cs q hlt]
    exact (isUnit_T_simple cs q hq i).mul ih

/-- For a reduced word `ω`, `T_{π ω}` is the product of the `T_s` over the letters of `ω`. -/
theorem T_wordProd {ω : List B} (hω : cs.IsReduced ω) :
    T cs q (cs.wordProd ω) = (ω.map fun i ↦ T cs q (s i)).prod := by
  induction ω with
  | nil => simp
  | cons i ω ih =>
    have hω' : cs.IsReduced ω := by simpa using hω.drop 1
    rw [List.map_cons, List.prod_cons, ← ih hω', cs.wordProd_cons, T_mul_T]
    have := hω.eq
    rw [cs.wordProd_cons] at this
    rw [this, hω'.eq, cs.length_simple, List.length_cons]
    ring

/-- Induction principle on `𝓗` along the standard basis. -/
theorem induction_on {p : IwahoriHeckeAlgebra cs q → Prop} (h : IwahoriHeckeAlgebra cs q)
    (T : ∀ w, p (T cs q w)) (add : ∀ x y, p x → p y → p (x + y))
    (smul : ∀ (a : R) x, p x → p (a • x)) : p h := by
  have hh : h ∈ Submodule.span R (Set.range (basis cs q)) := by
    rw [Basis.span_eq]; trivial
  induction hh using Submodule.span_induction with
  | mem x hx => obtain ⟨w, rfl⟩ := hx; exact T w
  | zero => simpa using smul 0 (IwahoriHeckeAlgebra.T cs q 1) (T 1)
  | add x y _ _ hx hy => exact add x y hx hy
  | smul a x _ hx => exact smul a x hx

/-- The Iwahori–Hecke algebra is generated by the `T_s`. -/
theorem adjoin_T_simple :
    Algebra.adjoin R (Set.range fun i ↦ T cs q (s i)) = ⊤ := by
  rw [eq_top_iff]
  rintro h -
  induction h using induction_on cs q with
  | T w =>
    induction w using cs.induction_simple_mul with
    | one => rw [T_one]; exact Subalgebra.one_mem _
    | simple_mul w i hlt ih =>
      rw [← T_simple_mul_T_of_lt cs q hlt]
      exact Subalgebra.mul_mem _ (Algebra.subset_adjoin ⟨i, rfl⟩) ih
  | add x y hx hy => exact Subalgebra.add_mem _ hx hy
  | smul a x hx => exact Subalgebra.smul_mem _ hx a

/-- An algebra homomorphism out of `𝓗` is determined by the images of the `T_s`. -/
@[ext]
theorem algHom_ext {A : Type*} [Semiring A] [Algebra R A]
    {f g : IwahoriHeckeAlgebra cs q →ₐ[R] A} (h : ∀ i, f (T cs q (s i)) = g (T cs q (s i))) :
    f = g :=
  AlgHom.ext_of_adjoin_eq_top (adjoin_T_simple cs q) <| by
    rintro _ ⟨i, rfl⟩
    exact h i

/-- A criterion for multiplicativity: an additive map `φ : 𝓗 → A`, semilinear with respect to a
ring homomorphism `σ : R → S` (`A` an `S`-algebra), with `φ 1 = 1` and
`φ (h T_s) = φ h φ(T_s)` for all `h` and `s`, is multiplicative. -/
theorem map_mul_of_map_mul_T_simple {S A : Type*} [CommRing S] [Ring A] [Algebra S A]
    (σ : R →+* S) (φ : IwahoriHeckeAlgebra cs q →+ A)
    (hsmul : ∀ (a : R) h, φ (a • h) = σ a • φ h) (hone : φ 1 = 1)
    (hT : ∀ h i, φ (h * T cs q (s i)) = φ h * φ (T cs q (s i)))
    (x y : IwahoriHeckeAlgebra cs q) : φ (x * y) = φ x * φ y := by
  induction y using induction_on cs q generalizing x with
  | T w =>
    induction w using cs.induction_mul_simple generalizing x with
    | one => simp [hone]
    | mul_simple w i hlt ih =>
      rw [← T_mul_T_simple_of_lt cs q hlt, ← mul_assoc, hT, ih, hT, mul_assoc]
  | add y z hy hz => rw [mul_add, map_add, hy, hz, map_add, mul_add]
  | smul a y hy => rw [mul_smul_comm, hsmul, hy, hsmul, mul_smul_comm]

end IwahoriHeckeAlgebra
