/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.GroupTheory.Coxeter.Hecke.Involutions
import LieLean.GroupTheory.Coxeter.Parabolic.CoxeterSystem

/-!
# Parabolic subalgebras of Iwahori–Hecke algebras and induced modules

Let `cs : CoxeterSystem M W`, `J ⊆ B`, `W_J` the standard parabolic subgroup (a Coxeter group with
Coxeter matrix `M|_J`, `CoxeterSystem.parabolicCoxeterSystem`) and `W^J` the set of minimal
left coset representatives (`CoxeterSystem.minCosetReps`, elements without right descents in
`J`). Let `𝓗 = 𝓗_q(W)` and `𝓗_J = 𝓗_q(W_J)`.

* The generators `T_s`, `s ∈ J`, of `𝓗` satisfy the Hecke relations of `M|_J`, which gives an
  algebra homomorphism `𝓗_J → 𝓗`, `T_w ↦ T_w` (`parabolicHom`, `parabolicHom_T`); it is
  injective, with image the span of the `T_w`, `w ∈ W_J`.
* Since every `w ∈ W` is uniquely `w = d v` with `d ∈ W^J`, `v ∈ W_J` and `ℓ(w) = ℓ(d) + ℓ(v)`,
  hence `T_w = T_d T_v`, `𝓗` is a free right `𝓗_J`-module with basis `(T_d)_{d ∈ W^J}`
  (`rightBasis`) and a free left `𝓗_J`-module with basis `(T_{d⁻¹})_{d ∈ W^J}` (`leftBasis`)
  ([GP] Prop. 2.1.1, Rem. 2.1.6, 4.4.7(b); [GP] states the left-module case).
* For a one-dimensional representation `χ : 𝓗_J → R`, the induced module
  `𝓗 ⊗_{𝓗_J} R_χ`, realized as the quotient of `𝓗` by the left ideal generated by the elements
  `h - χ(h)`, `h ∈ 𝓗_J` (`InducedModule χ`), is a free `R`-module with basis the images of the
  `T_d`, `d ∈ W^J` (`inducedBasis`). For `χ = ind` (`T_s ↦ q`) this is Deodhar's parabolic
  module `M^J` (`ParabolicModule`), whose Kazhdan–Lusztig basis defines the parabolic
  Kazhdan–Lusztig polynomials (V. Deodhar, *On some geometric aspects of Bruhat orderings II*,
  J. Algebra **111** (1987)); for `χ = sgn` one gets Deodhar's other parabolic module.

The right module structure is expressed as a module over the opposite algebra `𝓗_Jᵐᵒᵖ`.

## Main definitions

* `IwahoriHeckeAlgebra.parabolicHom J : 𝓗_J →ₐ[R] 𝓗`.
* Instances `Module 𝓗_J 𝓗` (`h • x = h x`) and `Module 𝓗_Jᵐᵒᵖ 𝓗` (`op h • x = x h`).
* `IwahoriHeckeAlgebra.rightBasis J : Basis W^J 𝓗_Jᵐᵒᵖ 𝓗`,
  `IwahoriHeckeAlgebra.leftBasis J : Basis W^J 𝓗_J 𝓗`.
* `IwahoriHeckeAlgebra.InducedModule χ`, `IwahoriHeckeAlgebra.inducedBasis χ`,
  `IwahoriHeckeAlgebra.ParabolicModule`.

## Main results

* `IwahoriHeckeAlgebra.parabolicHom_T`, `parabolicHom_injective`, `range_parabolicHom`.
* `IwahoriHeckeAlgebra.rightBasis_apply`, `leftBasis_apply`: the bases are `T_d`, `T_{d⁻¹}`.
* `IwahoriHeckeAlgebra.inducedBasis_apply`: the basis of `InducedModule χ` is `T_d ⊗ 1`.

## References

* [GP] M. Geck, G. Pfeiffer, *Characters of finite Coxeter groups and Iwahori–Hecke algebras*,
  LMS Monographs 21, OUP 2000, §2.1, §4.4.
* V. Deodhar, *On some geometric aspects of Bruhat orderings II. The parabolic analogue of
  Kazhdan–Lusztig polynomials*, J. Algebra **111** (1987), 483–506.
-/

open MulOpposite Module

namespace IwahoriHeckeAlgebra

open CoxeterSystem

variable {B W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)
variable {R : Type*} [CommRing R] (q : R) (J : Set B)

local prefix:100 "s " => cs.simple
local prefix:100 "π " => cs.wordProd
local prefix:100 "ℓ " => cs.length

/-! ### The parabolic subalgebra -/

/-- The `T_s`, `s ∈ J`, satisfy the Hecke relations of the restricted Coxeter matrix `M|_J`. -/
theorem isHeckeFamily_T_restrict :
    (M.restrict J).IsHeckeFamily q (fun j : J ↦ T cs q (s j)) where
  quadratic j := T_simple_sub_mul_T_simple_add cs q j
  braid i j hij hm := by
    have e : ∀ a b : J, ((braidWord (M.restrict J) a b).map fun k : J ↦ T cs q (s k)) =
        (braidWord M a b).map fun k ↦ T cs q (s k) := fun a b ↦ by
      rw [braidWord, braidWord, ← map_alternatingWord Subtype.val, List.map_map]
      rfl
    rw [e, e]
    exact (isHeckeFamily_T cs q).braid i j (fun h ↦ hij (Subtype.ext h)) hm

/-- The algebra homomorphism `𝓗_q(W_J) → 𝓗_q(W)`, `T_w ↦ T_w` (`parabolicHom_T`), from the
Iwahori–Hecke algebra of the standard parabolic subgroup `W_J`. It is injective
(`parabolicHom_injective`). -/
noncomputable def parabolicHom :
    IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q →ₐ[R] IwahoriHeckeAlgebra cs q :=
  lift _ q _ ⟨_, isHeckeFamily_T_restrict cs q J⟩

@[simp]
theorem parabolicHom_T (w : cs.parabolicSubgroup J) :
    parabolicHom cs q J (T _ q w) = T cs q (w : W) := by
  obtain ⟨η, hη, rfl⟩ := (cs.parabolicCoxeterSystem J).exists_isReduced w
  have hred : cs.IsReduced (η.map Subtype.val) := by
    unfold CoxeterSystem.IsReduced
    rw [← coe_parabolicCoxeterSystem_wordProd, ← length_parabolicCoxeterSystem, hη.eq,
      List.length_map]
  rw [parabolicHom, lift_apply_T _ hη, coe_parabolicCoxeterSystem_wordProd, T_wordProd cs q hred,
    List.map_map]
  rfl

theorem toFinsupp_parabolicHom (x : IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q) :
    toFinsupp cs q (parabolicHom cs q J x) = Finsupp.mapDomain Subtype.val (toFinsupp _ q x) := by
  induction x using induction_on _ q with
  | T w => rw [parabolicHom_T, toFinsupp_T, toFinsupp_T, Finsupp.mapDomain_single]
  | add x y hx hy => rw [map_add, map_add, hx, hy, map_add, Finsupp.mapDomain_add]
  | smul a x hx => rw [map_smul, map_smul, hx, map_smul, Finsupp.mapDomain_smul]

/-- `𝓗_q(W_J) → 𝓗_q(W)` is injective. -/
theorem parabolicHom_injective : Function.Injective (parabolicHom cs q J) := by
  intro x y h
  have := congrArg (toFinsupp cs q) h
  rw [toFinsupp_parabolicHom, toFinsupp_parabolicHom] at this
  exact (toFinsupp _ q).injective (Finsupp.mapDomain_injective Subtype.val_injective this)

/-- The image of `𝓗_q(W_J) → 𝓗_q(W)` is the span of the `T_w`, `w ∈ W_J`. -/
theorem range_parabolicHom :
    LinearMap.range (parabolicHom cs q J).toLinearMap =
      Submodule.span R (Set.range fun w : cs.parabolicSubgroup J ↦ T cs q (w : W)) := by
  rw [LinearMap.range_eq_map, ← (basis _ q).span_eq, Submodule.map_span, ← Set.range_comp]
  congr 2
  funext w
  simp [basis_apply]

/-! ### `𝓗` as a free `𝓗_J`-module -/

/-- `𝓗_q(W)` as a left module over `𝓗_q(W_J)`: `h • x = h x`. -/
noncomputable instance : Module (IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q)
    (IwahoriHeckeAlgebra cs q) :=
  Module.compHom _ (parabolicHom cs q J).toRingHom

/-- `𝓗_q(W)` as a right module over `𝓗_q(W_J)`: `op h • x = x h`. -/
noncomputable instance : Module (IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q)ᵐᵒᵖ
    (IwahoriHeckeAlgebra cs q) :=
  Module.compHom _ (RingHom.op (parabolicHom cs q J).toRingHom)

theorem parabolic_smul_def (h : IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q)
    (x : IwahoriHeckeAlgebra cs q) : h • x = parabolicHom cs q J h * x := rfl

theorem parabolic_op_smul_def (h : IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q)
    (x : IwahoriHeckeAlgebra cs q) : op h • x = x * parabolicHom cs q J h := rfl

variable {J} in
/-- `T_d T_v = T_{dv}` for `d ∈ W^J`, `v ∈ W_J`. -/
theorem T_mul_T_of_mem_minCosetReps {d v : W} (hd : d ∈ cs.minCosetReps J)
    (hv : v ∈ cs.parabolicSubgroup J) : T cs q d * T cs q v = T cs q (d * v) :=
  T_mul_T cs q (length_mul_of_mem_minCosetReps hd hv)

variable {J} in
/-- `T_v T_{d⁻¹} = T_{v d⁻¹}` for `d ∈ W^J`, `v ∈ W_J`. -/
theorem T_mul_T_inv_of_mem_minCosetReps {d v : W} (hd : d ∈ cs.minCosetReps J)
    (hv : v ∈ cs.parabolicSubgroup J) : T cs q v * T cs q d⁻¹ = T cs q (v * d⁻¹) := by
  refine T_mul_T cs q ?_
  have h := length_mul_of_mem_minCosetReps hd (Subgroup.inv_mem _ hv)
  rw [← length_inv, mul_inv_rev, inv_inv, h, length_inv, length_inv, add_comm]

/-- The `R`-linear isomorphism `(W^J →₀ 𝓗_Jᵐᵒᵖ) ≃ 𝓗`, `(h_d)_d ↦ Σ_d T_d h_d`, coming from the
decomposition `W ≃ W^J × W_J`. -/
noncomputable def rightDecomposition :
    (cs.minCosetReps J →₀ (IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q)ᵐᵒᵖ) ≃ₗ[R]
      IwahoriHeckeAlgebra cs q :=
  Finsupp.mapRange.linearEquiv ((MulOpposite.opLinearEquiv R).symm ≪≫ₗ toFinsupp _ q) ≪≫ₗ
    (Finsupp.curryLinearEquiv R).symm ≪≫ₗ Finsupp.domLCongr (cs.minCosetRepsProdEquiv J) ≪≫ₗ
      (toFinsupp cs q).symm

theorem rightDecomposition_single (d : cs.minCosetReps J)
    (x : IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q) :
    rightDecomposition cs q J (Finsupp.single d (op x)) = T cs q d * parabolicHom cs q J x := by
  induction x using induction_on _ q with
  | T v =>
    have h1 : (Finsupp.curryLinearEquiv R).symm (Finsupp.single d (Finsupp.single v (1 : R))) =
        Finsupp.single (d, v) 1 := by
      rw [LinearEquiv.symm_apply_eq]
      exact (Finsupp.curry_single (d, v) 1).symm
    rw [parabolicHom_T, T_mul_T_of_mem_minCosetReps cs q d.2 v.2, rightDecomposition]
    simp only [LinearEquiv.trans_apply, Finsupp.mapRange.linearEquiv_apply,
      Finsupp.mapRange_single, LinearEquiv.trans_apply, coe_opLinearEquiv_symm, unop_op,
      toFinsupp_T, h1, Finsupp.domLCongr_single, minCosetRepsProdEquiv_apply]
    rfl
  | add x y hx hy => rw [op_add, Finsupp.single_add, map_add, hx, hy, map_add, mul_add]
  | smul a x hx => rw [op_smul, ← Finsupp.smul_single, map_smul, hx, map_smul, mul_smul_comm]

theorem rightDecomposition_eq_linearCombination
    (f : cs.minCosetReps J →₀ (IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q)ᵐᵒᵖ) :
    rightDecomposition cs q J f =
      Finsupp.linearCombination _ (fun d : cs.minCosetReps J ↦ T cs q d) f := by
  induction f using Finsupp.induction_linear with
  | zero => simp
  | add f g hf hg => rw [map_add, map_add, hf, hg]
  | single d x =>
    rw [Finsupp.linearCombination_single, ← op_unop x, rightDecomposition_single]
    rfl

/-- `𝓗_q(W)` is a free right `𝓗_q(W_J)`-module with basis `(T_d)_{d ∈ W^J}` (the mirror
image of [GP] 4.4.7(b) under `w ↦ w⁻¹`, cf. [GP] Prop. 2.1.1, Rem. 2.1.6). -/
noncomputable def rightBasis :
    Basis (cs.minCosetReps J) (IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q)ᵐᵒᵖ
      (IwahoriHeckeAlgebra cs q) :=
  Basis.ofRepr (LinearEquiv.ofBijective
    (Finsupp.linearCombination _ fun d : cs.minCosetReps J ↦ T cs q d) (by
      have : ⇑(Finsupp.linearCombination
          (IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q)ᵐᵒᵖ
          fun d : cs.minCosetReps J ↦ T cs q d) = rightDecomposition cs q J :=
        funext fun f ↦ (rightDecomposition_eq_linearCombination cs q J f).symm
      rw [this]
      exact (rightDecomposition cs q J).bijective)).symm

@[simp]
theorem rightBasis_apply (d : cs.minCosetReps J) : rightBasis cs q J d = T cs q d := by
  simp [rightBasis, Basis.coe_ofRepr]

theorem rightBasis_repr (x : IwahoriHeckeAlgebra cs q) :
    (rightBasis cs q J).repr x = (rightDecomposition cs q J).symm x := by
  apply (rightDecomposition cs q J).injective
  rw [LinearEquiv.apply_symm_apply, rightDecomposition_eq_linearCombination]
  have e : (fun d : cs.minCosetReps J ↦ T cs q d) = ⇑(rightBasis cs q J) :=
    funext fun d ↦ (rightBasis_apply cs q J d).symm
  rw [e]
  exact (rightBasis cs q J).linearCombination_repr x

instance : Module.Free (IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q)ᵐᵒᵖ
    (IwahoriHeckeAlgebra cs q) :=
  Module.Free.of_basis (rightBasis cs q J)

theorem rightDecomposition_symm_mul (x : IwahoriHeckeAlgebra cs q)
    (h : IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q) :
    (rightDecomposition cs q J).symm (x * parabolicHom cs q J h) =
      op h • (rightDecomposition cs q J).symm x := by
  rw [← rightBasis_repr, ← rightBasis_repr, ← parabolic_op_smul_def, map_smul]

/-- The bijection `W^J × W_J ≃ W`, `(d, v) ↦ v d⁻¹`. -/
noncomputable def minCosetRepsProdEquiv' : cs.minCosetReps J × cs.parabolicSubgroup J ≃ W :=
  ((Equiv.refl _).prodCongr (Equiv.inv _)).trans
    ((cs.minCosetRepsProdEquiv J).trans (Equiv.inv W))

theorem minCosetRepsProdEquiv'_apply (p : cs.minCosetReps J × cs.parabolicSubgroup J) :
    minCosetRepsProdEquiv' cs J p = (p.2 : W) * (p.1 : W)⁻¹ := by
  simp [minCosetRepsProdEquiv', mul_inv_rev]

/-- The `R`-linear isomorphism `(W^J →₀ 𝓗_J) ≃ 𝓗`, `(h_d)_d ↦ Σ_d h_d T_{d⁻¹}`. -/
noncomputable def leftDecomposition :
    (cs.minCosetReps J →₀ IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q) ≃ₗ[R]
      IwahoriHeckeAlgebra cs q :=
  Finsupp.mapRange.linearEquiv (toFinsupp _ q) ≪≫ₗ (Finsupp.curryLinearEquiv R).symm ≪≫ₗ
    Finsupp.domLCongr (minCosetRepsProdEquiv' cs J) ≪≫ₗ (toFinsupp cs q).symm

theorem leftDecomposition_single (d : cs.minCosetReps J)
    (x : IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q) :
    leftDecomposition cs q J (Finsupp.single d x) = parabolicHom cs q J x * T cs q (d : W)⁻¹ := by
  induction x using induction_on _ q with
  | T v =>
    have h1 : (Finsupp.curryLinearEquiv R).symm (Finsupp.single d (Finsupp.single v (1 : R))) =
        Finsupp.single (d, v) 1 := by
      rw [LinearEquiv.symm_apply_eq]
      exact (Finsupp.curry_single (d, v) 1).symm
    rw [parabolicHom_T, T_mul_T_inv_of_mem_minCosetReps cs q d.2 v.2, leftDecomposition]
    simp only [LinearEquiv.trans_apply, Finsupp.mapRange.linearEquiv_apply,
      Finsupp.mapRange_single, toFinsupp_T, h1, Finsupp.domLCongr_single,
      minCosetRepsProdEquiv'_apply]
    rfl
  | add x y hx hy => rw [Finsupp.single_add, map_add, hx, hy, map_add, add_mul]
  | smul a x hx => rw [← Finsupp.smul_single, map_smul, hx, map_smul, smul_mul_assoc]

theorem leftDecomposition_eq_linearCombination
    (f : cs.minCosetReps J →₀ IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q) :
    leftDecomposition cs q J f =
      Finsupp.linearCombination _ (fun d : cs.minCosetReps J ↦ T cs q (d : W)⁻¹) f := by
  induction f using Finsupp.induction_linear with
  | zero => simp
  | add f g hf hg => rw [map_add, map_add, hf, hg]
  | single d x =>
    rw [Finsupp.linearCombination_single, leftDecomposition_single]
    rfl

/-- `𝓗_q(W)` is a free left `𝓗_q(W_J)`-module with basis `(T_{d⁻¹})_{d ∈ W^J}` (the `d⁻¹`,
`d ∈ W^J`, are the minimal right coset representatives) ([GP] 4.4.7(b), Prop. 2.1.1). -/
noncomputable def leftBasis :
    Basis (cs.minCosetReps J) (IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q)
      (IwahoriHeckeAlgebra cs q) :=
  Basis.ofRepr (LinearEquiv.ofBijective
    (Finsupp.linearCombination _ fun d : cs.minCosetReps J ↦ T cs q (d : W)⁻¹) (by
      have : ⇑(Finsupp.linearCombination (IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q)
          fun d : cs.minCosetReps J ↦ T cs q (d : W)⁻¹) = leftDecomposition cs q J :=
        funext fun f ↦ (leftDecomposition_eq_linearCombination cs q J f).symm
      rw [this]
      exact (leftDecomposition cs q J).bijective)).symm

@[simp]
theorem leftBasis_apply (d : cs.minCosetReps J) : leftBasis cs q J d = T cs q (d : W)⁻¹ := by
  simp [leftBasis, Basis.coe_ofRepr]

instance : Module.Free (IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q)
    (IwahoriHeckeAlgebra cs q) :=
  Module.Free.of_basis (leftBasis cs q J)

/-! ### Induced modules -/

section Induced

variable {cs q J} (χ : IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q →ₐ[R] R)

/-- The left ideal of `𝓗_q(W)` generated by the elements `h - χ(h)`, `h ∈ 𝓗_q(W_J)`, for a
one-dimensional representation `χ` of `𝓗_q(W_J)`. -/
noncomputable def inducedIdeal : Submodule (IwahoriHeckeAlgebra cs q) (IwahoriHeckeAlgebra cs q) :=
  Submodule.span _ (Set.range fun h ↦ parabolicHom cs q J h - algebraMap R _ (χ h))

/-- The module `𝓗_q(W) ⊗_{𝓗_q(W_J)} R_χ` induced from a one-dimensional representation `χ` of
the parabolic subalgebra, realized as the quotient of `𝓗_q(W)` by the left ideal generated by
the `h - χ(h)`, `h ∈ 𝓗_q(W_J)`. It is a left `𝓗_q(W)`-module, free over `R` with basis the
images of the `T_d`, `d ∈ W^J` (`inducedBasis`). -/
abbrev InducedModule : Type _ := IwahoriHeckeAlgebra cs q ⧸ inducedIdeal χ

/-- The `R`-linear map `𝓗 → (W^J →₀ R)`, `Σ_d T_d h_d ↦ (χ(h_d))_d`; its kernel is the left
ideal `inducedIdeal χ`. -/
noncomputable def inducedCoeff : IwahoriHeckeAlgebra cs q →ₗ[R] (cs.minCosetReps J →₀ R) :=
  Finsupp.mapRange.linearMap (χ.toLinearMap ∘ₗ (MulOpposite.opLinearEquiv R).symm.toLinearMap) ∘ₗ
    (rightDecomposition cs q J).symm.toLinearMap

theorem inducedCoeff_apply (x : IwahoriHeckeAlgebra cs q) (d : cs.minCosetReps J) :
    inducedCoeff χ x d = χ (unop ((rightDecomposition cs q J).symm x d)) := by
  simp [inducedCoeff]

theorem inducedCoeff_mul_parabolicHom (x : IwahoriHeckeAlgebra cs q)
    (h : IwahoriHeckeAlgebra (cs.parabolicCoxeterSystem J) q) :
    inducedCoeff χ (x * parabolicHom cs q J h) = χ h • inducedCoeff χ x := by
  ext d
  rw [inducedCoeff_apply, rightDecomposition_symm_mul, Finsupp.smul_apply, Finsupp.smul_apply,
    smul_eq_mul, unop_mul, unop_op, map_mul, inducedCoeff_apply, smul_eq_mul, mul_comm]

theorem inducedCoeff_T (d : cs.minCosetReps J) :
    inducedCoeff χ (T cs q d) = Finsupp.single d 1 := by
  have h : (rightDecomposition cs q J).symm (T cs q d) = Finsupp.single d (op 1) := by
    rw [LinearEquiv.symm_apply_eq, rightDecomposition_single, map_one, mul_one]
  simp [inducedCoeff, h]

theorem inducedCoeff_surjective : Function.Surjective (inducedCoeff χ) := by
  intro f
  induction f using Finsupp.induction_linear with
  | zero => exact ⟨0, map_zero _⟩
  | add f g hf hg =>
    obtain ⟨x, rfl⟩ := hf
    obtain ⟨y, rfl⟩ := hg
    exact ⟨x + y, map_add _ x y⟩
  | single d a =>
    exact ⟨a • T cs q d, by rw [map_smul, inducedCoeff_T, Finsupp.smul_single, smul_eq_mul,
      mul_one]⟩

theorem restrictScalars_inducedIdeal :
    (inducedIdeal χ).restrictScalars R = LinearMap.ker (inducedCoeff χ) := by
  ext x
  rw [Submodule.restrictScalars_mem, LinearMap.mem_ker]
  constructor
  · intro hx
    obtain ⟨c, rfl⟩ := Finsupp.mem_span_range_iff_exists_finsupp.mp hx
    rw [Finsupp.sum, map_sum]
    refine Finset.sum_eq_zero fun h _ ↦ ?_
    rw [smul_eq_mul, mul_sub, map_sub, inducedCoeff_mul_parabolicHom, ← Algebra.commutes,
      ← Algebra.smul_def, map_smul, sub_self]
  · intro hx
    rw [← (rightDecomposition cs q J).apply_symm_apply x, rightDecomposition_eq_linearCombination,
      Finsupp.linearCombination_apply, Finsupp.sum]
    refine Submodule.sum_mem _ fun d _ ↦ ?_
    set a := (rightDecomposition cs q J).symm x d
    have h0 : χ (unop a) = 0 := by
      rw [← inducedCoeff_apply, hx, Finsupp.zero_apply]
    have e : a • T cs q d = T cs q d * (parabolicHom cs q J (unop a) - algebraMap R _ (χ (unop a)))
      := by
      rw [h0, map_zero, sub_zero, ← parabolic_op_smul_def, op_unop]
    rw [e]
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨unop a, rfl⟩)

/-- The `R`-linear isomorphism `𝓗 ⊗_{𝓗_J} R_χ ≃ (W^J →₀ R)`. -/
noncomputable def inducedModuleEquiv : InducedModule χ ≃ₗ[R] (cs.minCosetReps J →₀ R) :=
  (Submodule.Quotient.restrictScalarsEquiv R (inducedIdeal χ)).symm ≪≫ₗ
    Submodule.quotEquivOfEq _ _ (restrictScalars_inducedIdeal χ) ≪≫ₗ
      (inducedCoeff χ).quotKerEquivOfSurjective (inducedCoeff_surjective χ)

theorem inducedModuleEquiv_mk (x : IwahoriHeckeAlgebra cs q) :
    inducedModuleEquiv χ (Submodule.Quotient.mk x) = inducedCoeff χ x := by
  simp [inducedModuleEquiv, Submodule.Quotient.restrictScalarsEquiv_symm_mk,
    LinearMap.quotKerEquivOfSurjective_apply_mk]

/-- The induced module `𝓗_q(W) ⊗_{𝓗_q(W_J)} R_χ` is a free `R`-module with basis the images
`T_d ⊗ 1` of the `T_d`, `d ∈ W^J` (`inducedBasis_apply`) (Deodhar 1987,
§2). -/
noncomputable def inducedBasis : Basis (cs.minCosetReps J) R (InducedModule χ) :=
  Basis.ofRepr (inducedModuleEquiv χ)

@[simp]
theorem inducedBasis_apply (d : cs.minCosetReps J) :
    inducedBasis χ d = Submodule.Quotient.mk (T cs q d) := by
  rw [inducedBasis, Basis.coe_ofRepr, LinearEquiv.symm_apply_eq, inducedModuleEquiv_mk,
    inducedCoeff_T]

instance : Module.Free R (InducedModule χ) := Module.Free.of_basis (inducedBasis χ)

end Induced

/-- Deodhar's parabolic module `M^J = 𝓗_q(W) ⊗_{𝓗_q(W_J)} ind`, induced from the index
representation `T_s ↦ q` of `𝓗_q(W_J)`; it is free over `R` with basis `(T_d ⊗ 1)_{d ∈ W^J}`
(`inducedBasis`). -/
noncomputable abbrev ParabolicModule : Type _ := InducedModule (ind (cs.parabolicCoxeterSystem J) q)

end IwahoriHeckeAlgebra
