/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.GroupTheory.Coxeter.Hecke.Basic
import LieLean.GroupTheory.Coxeter.Matsumoto
import Mathlib.Algebra.FreeAlgebra
import Mathlib.Algebra.RingQuot

/-!
# The presentation of the Iwahori–Hecke algebra

Let `(W, S)` be a Coxeter system with Coxeter matrix `M`, `R` a commutative ring and `q ∈ R`.
The Iwahori–Hecke algebra `𝓗 = 𝓗_q(W)` (`IwahoriHeckeAlgebra cs q`, normalization
`(T_s - q)(T_s + 1) = 0`) is generated by the `T_s`, subject to the quadratic relations and the
braid relations `T_s T_t T_s ⋯ = T_t T_s T_t ⋯` (`m_{st}` factors on both sides, `m_{st} < ∞`),
and these are defining relations ([GP] Def. 4.4.1; [GP] Def. 4.4.1, Thm. 4.4.6).

We prove this in the form of a universal property (`IwahoriHeckeAlgebra.lift`): for any
`R`-algebra `A` and elements `tᵢ ∈ A` (`i ∈ B`) satisfying these relations
(`CoxeterMatrix.IsHeckeFamily`) there is a unique `R`-algebra homomorphism `𝓗 → A` with
`T_{sᵢ} ↦ tᵢ`. It sends `T_w` to `t_{i₁} ⋯ t_{iₖ}` for any reduced word `w = s_{i₁} ⋯ s_{iₖ}`,
which is well defined by Matsumoto's theorem (`CoxeterSystem.braidLift`); multiplicativity
follows from `IwahoriHeckeAlgebra.map_mul_of_map_mul_T_simple`. We then identify `𝓗` with the
algebra `CoxeterMatrix.HeckeAlgebra M q` presented by generators and relations (a quotient of
the free algebra `FreeAlgebra R B`), which only depends on `M` and `q`.

## Main definitions

* `CoxeterMatrix.IsHeckeFamily M q t`: the elements `t i` of an `R`-algebra satisfy the
  quadratic relations `(tᵢ - q)(tᵢ + 1) = 0` and the braid relations of `M`.
* `IwahoriHeckeAlgebra.lift`: the universal property
  `{t // M.IsHeckeFamily q t} ≃ (𝓗 →ₐ[R] A)`.
* `CoxeterMatrix.HeckeAlgebra M q`: the algebra presented by generators `Tᵢ` and the Hecke
  relations, with generators `HeckeAlgebra.gen` and universal property `HeckeAlgebra.lift`.
* `IwahoriHeckeAlgebra.equivHeckeAlgebra : 𝓗_q(W) ≃ₐ[R] M.HeckeAlgebra q`.

## Main results

* `IwahoriHeckeAlgebra.isHeckeFamily_T`: the `T_s` satisfy the Hecke relations.
* `IwahoriHeckeAlgebra.lift_apply_T`: `lift t (T_w) = t_{i₁} ⋯ t_{iₖ}` for reduced words.
* `IwahoriHeckeAlgebra.equivHeckeAlgebra_T_simple`: the presentation `𝓗_q(W) ≅ M.HeckeAlgebra q`.

## References

* [HumC] J. E. Humphreys, *Reflection groups and Coxeter groups*, CUP 1990, §7.1–7.3.
* [GP] M. Geck, G. Pfeiffer, *Characters of finite Coxeter groups and Iwahori–Hecke algebras*,
  LMS Monographs 21, OUP 2000, §4.4.
-/

namespace CoxeterMatrix

variable {B : Type*} (M : CoxeterMatrix B) {R : Type*} [CommRing R] (q : R)
variable {A : Type*} [Ring A] [Algebra R A]

/-- Elements `t i` (`i ∈ B`) of an `R`-algebra satisfy the *Hecke relations* of the Coxeter
matrix `M` with parameter `q`: the quadratic relations `(tᵢ - q)(tᵢ + 1) = 0` and the braid
relations `tᵢ tⱼ tᵢ ⋯ = tⱼ tᵢ tⱼ ⋯` (`mᵢⱼ` factors on each side) for `i ≠ j`, `mᵢⱼ < ∞`. -/
structure IsHeckeFamily (t : B → A) : Prop where
  quadratic : ∀ i, (t i - algebraMap R A q) * (t i + 1) = 0
  braid : M.IsBraidLiftable t

variable {M q}

/-- The quadratic relation in the form `tᵢ² = (q - 1) tᵢ + q`. -/
theorem IsHeckeFamily.mul_self {t : B → A} (ht : M.IsHeckeFamily q t) (i : B) :
    t i * t i = (q - 1) • t i + algebraMap R A q := by
  have h := ht.quadratic i
  rw [sub_mul, mul_add, mul_add, mul_one, mul_one, ← Algebra.smul_def] at h
  rw [← sub_eq_zero, ← h, sub_smul, one_smul]
  abel

/-- The image of a Hecke family under an algebra homomorphism is a Hecke family. -/
theorem IsHeckeFamily.map {A' : Type*} [Ring A'] [Algebra R A'] {t : B → A}
    (ht : M.IsHeckeFamily q t) (f : A →ₐ[R] A') : M.IsHeckeFamily q (f ∘ t) where
  quadratic i := by simpa using congrArg f (ht.quadratic i)
  braid i j hij hm := by
    have := congrArg f (ht.braid i j hij hm)
    rwa [map_list_prod, map_list_prod, List.map_map, List.map_map] at this

end CoxeterMatrix

namespace IwahoriHeckeAlgebra

open CoxeterSystem

variable {B W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)
variable {R : Type*} [CommRing R] (q : R)
variable {A : Type*} [Ring A] [Algebra R A]

local prefix:100 "s " => cs.simple
local prefix:100 "π " => cs.wordProd
local prefix:100 "ℓ " => cs.length

/-- The standard generators `T_s` of `𝓗` satisfy the Hecke relations
([GP] Def. 4.4.1, Thm. 4.4.6). -/
theorem isHeckeFamily_T : M.IsHeckeFamily q (fun i ↦ T cs q (s i)) where
  quadratic := T_simple_sub_mul_T_simple_add cs q
  braid i j _ _ := by
    rw [← T_wordProd cs q (cs.isReduced_alternatingWord i j (Or.inr le_rfl)),
      ← T_wordProd cs q (cs.isReduced_alternatingWord j i (Or.inr le_rfl))]
    exact congrArg (T cs q) (cs.wordProd_braidWord_eq i j)

/-- The `R`-linear map `𝓗 → A`, `T_w ↦ t_{i₁} ⋯ t_{iₖ}` (for a chosen reduced word of `w`).
It is an algebra homomorphism if the `t i` satisfy the Hecke relations (`liftAlgHom`). -/
noncomputable def liftLinear (t : B → A) : IwahoriHeckeAlgebra cs q →ₗ[R] A :=
  Finsupp.linearCombination R (cs.braidLift t) ∘ₗ (toFinsupp cs q).toLinearMap

theorem liftLinear_T (t : B → A) (w : W) : liftLinear cs q t (T cs q w) = cs.braidLift t w := by
  simp [liftLinear, toFinsupp_T]

variable {cs q}

theorem liftLinear_mul_T_simple {t : B → A} (ht : M.IsHeckeFamily q t)
    (h : IwahoriHeckeAlgebra cs q) (i : B) :
    liftLinear cs q t (h * T cs q (s i)) = liftLinear cs q t h * t i := by
  induction h using induction_on cs q with
  | T w =>
    rcases cs.length_mul_simple w i with hlt | hlt
    · rw [T_mul_T_simple_of_lt cs q (by omega), liftLinear_T, liftLinear_T,
        braidLift_mul_simple ht.braid (cs.not_isRightDescent_iff.mpr hlt)]
    · have hw : cs.braidLift t w = cs.braidLift t (w * s i) * t i := by
        conv_lhs => rw [← cs.simple_mul_simple_cancel_right (w := w) i]
        refine braidLift_mul_simple ht.braid (cs.not_isRightDescent_iff.mpr ?_)
        rw [cs.simple_mul_simple_cancel_right]
        omega
      rw [T_mul_T_simple_of_lt' cs q (by omega), map_add, map_smul, map_smul, liftLinear_T,
        liftLinear_T, hw, mul_assoc, ht.mul_self, mul_add, mul_smul_comm,
        Algebra.algebraMap_eq_smul_one, mul_smul_comm, mul_one]
  | add x y hx hy => rw [add_mul, map_add, map_add, hx, hy, add_mul]
  | smul a x hx => rw [smul_mul_assoc, map_smul, hx, map_smul, smul_mul_assoc]

variable (cs q) in
/-- The algebra homomorphism `𝓗 → A` with `T_{sᵢ} ↦ tᵢ` defined by a Hecke family `t`. -/
noncomputable def liftAlgHom (t : B → A) (ht : M.IsHeckeFamily q t) :
    IwahoriHeckeAlgebra cs q →ₐ[R] A :=
  AlgHom.ofLinearMap (liftLinear cs q t)
    (by rw [← T_one, liftLinear_T, braidLift_one])
    (map_mul_of_map_mul_T_simple cs q (RingHom.id R) (liftLinear cs q t).toAddMonoidHom
      (fun a h ↦ map_smul (liftLinear cs q t) a h)
      (by change liftLinear cs q t (T cs q 1) = 1; rw [liftLinear_T, braidLift_one])
      (fun h i ↦ by
        change liftLinear cs q t (h * T cs q (s i)) =
          liftLinear cs q t h * liftLinear cs q t (T cs q (s i))
        rw [liftLinear_mul_T_simple ht, liftLinear_T, braidLift_simple]))

theorem liftAlgHom_apply (t : B → A) (ht : M.IsHeckeFamily q t) (x : IwahoriHeckeAlgebra cs q) :
    liftAlgHom cs q t ht x = liftLinear cs q t x := rfl

variable (cs q A) in
/-- **The universal property of the Iwahori–Hecke algebra** ([GP] Def. 4.4.1 and
[GP] Def. 4.4.1, Thm. 4.4.6): `R`-algebra homomorphisms `𝓗_q(W) → A` correspond to families
`(tᵢ)_{i ∈ B}` in `A` satisfying the quadratic relations `(tᵢ - q)(tᵢ + 1) = 0` and the braid
relations of the Coxeter matrix, via `f ↦ (f(T_{sᵢ}))ᵢ`. The proof uses Matsumoto's theorem
(through `CoxeterSystem.braidLift`). -/
noncomputable def lift :
    {t : B → A // M.IsHeckeFamily q t} ≃ (IwahoriHeckeAlgebra cs q →ₐ[R] A) where
  toFun t := liftAlgHom cs q t.1 t.2
  invFun f := ⟨fun i ↦ f (T cs q (s i)), (isHeckeFamily_T cs q).map f⟩
  left_inv t := Subtype.ext <| funext fun i ↦ by
    change liftAlgHom cs q t.1 t.2 (T cs q (s i)) = t.1 i
    rw [liftAlgHom_apply, liftLinear_T, braidLift_simple]
  right_inv f := algHom_ext cs q fun i ↦ by
    change liftAlgHom cs q _ _ (T cs q (s i)) = _
    rw [liftAlgHom_apply, liftLinear_T, braidLift_simple]

/-- `lift t` maps `T_w` to `t_{i₁} ⋯ t_{iₖ}` for any reduced word `i₁ ⋯ iₖ` of `w`. -/
theorem lift_apply_T (t : {t : B → A // M.IsHeckeFamily q t}) {ω : List B}
    (hω : cs.IsReduced ω) : lift cs q A t (T cs q (π ω)) = (ω.map t.1).prod := by
  change liftAlgHom cs q t.1 t.2 _ = _
  rw [liftAlgHom_apply, liftLinear_T, braidLift_wordProd t.2.braid hω]

/-- `lift t` maps `T_{sᵢ}` to `tᵢ`. -/
@[simp]
theorem lift_apply_T_simple (t : {t : B → A // M.IsHeckeFamily q t}) (i : B) :
    lift cs q A t (T cs q (s i)) = t.1 i :=
  congrFun (congrArg Subtype.val ((lift cs q A).left_inv t)) i

/-- The Hecke family corresponding to an algebra homomorphism `f` is `(f(T_{sᵢ}))ᵢ`. -/
theorem lift_symm_apply (f : IwahoriHeckeAlgebra cs q →ₐ[R] A) (i : B) :
    ((lift cs q A).symm f).1 i = f (T cs q (s i)) := rfl

end IwahoriHeckeAlgebra

/-! ### The Hecke algebra given by generators and relations -/

namespace CoxeterMatrix

open FreeAlgebra

variable {B : Type*} (M : CoxeterMatrix B) {R : Type*} [CommRing R] (q : R)
variable {A : Type*} [Ring A] [Algebra R A]

/-- The defining relations of the Hecke algebra on the free algebra `R⟨Tᵢ : i ∈ B⟩`:
`(Tᵢ - q)(Tᵢ + 1) = 0` and the braid relations `Tᵢ Tⱼ Tᵢ ⋯ = Tⱼ Tᵢ Tⱼ ⋯` (`mᵢⱼ` factors) for
`i ≠ j` with `mᵢⱼ ≠ 0`. -/
inductive HeckeRel : FreeAlgebra R B → FreeAlgebra R B → Prop
  | quadratic (i : B) : HeckeRel ((ι R i - algebraMap R _ q) * (ι R i + 1)) 0
  | braid (i j : B) (hij : i ≠ j) (hm : M i j ≠ 0) :
      HeckeRel ((CoxeterSystem.braidWord M i j).map (ι R)).prod
        ((CoxeterSystem.braidWord M j i).map (ι R)).prod

/-- The Hecke algebra of the Coxeter matrix `M` with parameter `q`, given by generators `Tᵢ`
(`i ∈ B`) and the relations `CoxeterMatrix.HeckeRel`. By
`IwahoriHeckeAlgebra.equivHeckeAlgebra` it is isomorphic to the Iwahori–Hecke algebra of any
Coxeter system with Coxeter matrix `M`. -/
abbrev HeckeAlgebra : Type _ := RingQuot (M.HeckeRel q)

namespace HeckeAlgebra

/-- The generator `Tᵢ` of `M.HeckeAlgebra q`. -/
noncomputable def gen (i : B) : M.HeckeAlgebra q := RingQuot.mkAlgHom R _ (ι R i)

/-- The generators of `M.HeckeAlgebra q` satisfy the Hecke relations. -/
theorem isHeckeFamily_gen : M.IsHeckeFamily q (gen M q) where
  quadratic i := by
    have := RingQuot.mkAlgHom_rel R (HeckeRel.quadratic (M := M) (q := q) i)
    simpa [gen] using this
  braid i j hij hm := by
    have := RingQuot.mkAlgHom_rel R (HeckeRel.braid (q := q) i j hij hm)
    rwa [map_list_prod, map_list_prod, List.map_map, List.map_map] at this

variable {M q}

/-- Algebra homomorphisms out of `M.HeckeAlgebra q` agree if they agree on the generators. -/
@[ext]
theorem hom_ext {f g : M.HeckeAlgebra q →ₐ[R] A} (h : ∀ i, f (gen M q i) = g (gen M q i)) :
    f = g :=
  RingQuot.ringQuot_ext' R f g (FreeAlgebra.hom_ext (funext h))

theorem freeAlgebraLift_heckeRel {t : B → A} (ht : M.IsHeckeFamily q t) ⦃x y : FreeAlgebra R B⦄
    (h : M.HeckeRel q x y) : FreeAlgebra.lift R t x = FreeAlgebra.lift R t y := by
  cases h with
  | quadratic i => simpa using ht.quadratic i
  | braid i j hij hm =>
    rw [map_list_prod, map_list_prod, List.map_map, List.map_map]
    simpa using ht.braid i j hij hm

variable (M q A) in
/-- The universal property of `M.HeckeAlgebra q`: algebra homomorphisms out of it correspond to
Hecke families. -/
noncomputable def lift :
    {t : B → A // M.IsHeckeFamily q t} ≃ (M.HeckeAlgebra q →ₐ[R] A) where
  toFun t := RingQuot.liftAlgHom R ⟨FreeAlgebra.lift R t.1, freeAlgebraLift_heckeRel t.2⟩
  invFun f := ⟨fun i ↦ f (gen M q i), (isHeckeFamily_gen M q).map f⟩
  left_inv t := Subtype.ext <| funext fun i ↦ by
    simp [gen, RingQuot.liftAlgHom_mkAlgHom_apply]
  right_inv f := hom_ext fun i ↦ by
    simp [gen, RingQuot.liftAlgHom_mkAlgHom_apply]

@[simp]
theorem lift_apply_gen (t : {t : B → A // M.IsHeckeFamily q t}) (i : B) :
    lift M q A t (gen M q i) = t.1 i := by
  simp [lift, gen, RingQuot.liftAlgHom_mkAlgHom_apply]

end HeckeAlgebra

end CoxeterMatrix

namespace IwahoriHeckeAlgebra

variable {B W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)
variable {R : Type*} [CommRing R] (q : R)

local prefix:100 "s " => cs.simple

/-- **Presentation of the Iwahori–Hecke algebra** ([GP] Def. 4.4.1; [GP] Def. 4.4.1,
Thm. 4.4.6): `𝓗_q(W)` is isomorphic to the algebra generated by `Tᵢ` (`i ∈ B`) subject to the
quadratic relations `(Tᵢ - q)(Tᵢ + 1) = 0` and the braid relations, via `T_{sᵢ} ↦ Tᵢ`. -/
noncomputable def equivHeckeAlgebra : IwahoriHeckeAlgebra cs q ≃ₐ[R] M.HeckeAlgebra q :=
  AlgEquiv.ofAlgHom (lift cs q _ ⟨_, CoxeterMatrix.HeckeAlgebra.isHeckeFamily_gen M q⟩)
    (CoxeterMatrix.HeckeAlgebra.lift M q _ ⟨_, isHeckeFamily_T cs q⟩)
    (CoxeterMatrix.HeckeAlgebra.hom_ext fun i ↦ by simp)
    (algHom_ext cs q fun i ↦ by simp)

@[simp]
theorem equivHeckeAlgebra_T_simple (i : B) :
    equivHeckeAlgebra cs q (T cs q (s i)) = CoxeterMatrix.HeckeAlgebra.gen M q i := by
  simp [equivHeckeAlgebra]

@[simp]
theorem equivHeckeAlgebra_symm_gen (i : B) :
    (equivHeckeAlgebra cs q).symm (CoxeterMatrix.HeckeAlgebra.gen M q i) = T cs q (s i) := by
  simp [equivHeckeAlgebra]

end IwahoriHeckeAlgebra
