/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Ellis
-/
import LieLean.Algebra.Lie.UniversalEnveloping.TensorDecomposition
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# The kernel of `U(L) → U(L')` for a surjective morphism of Lie algebras

Let `f : L → L'` be a surjective morphism of Lie algebras over a commutative ring `R`. The kernel
of the induced algebra morphism `U(f) : U(L) → U(L')` is the two-sided ideal generated by
`ι(ker f)`.

## Main definitions

* `LieHom.descend`: a morphism of Lie algebras `g : L → L''` vanishing on `ker f` descends along
  the surjection `f` to a morphism `L' → L''`.

## Main results

* `UniversalEnvelopingAlgebra.ker_map_eq_span`: `ker U(f) = ⟨ι(ker f)⟩` for surjective `f`.
* `UniversalEnvelopingAlgebra.mem_span_of_map_eq_zero`: the useful inclusion `⊆`.

## Proof

The inclusion `⊇` is clear. Conversely, let `J = ⟨ι(ker f)⟩`. The composite
`L → U(L) → U(L)/J` is a morphism of Lie algebras vanishing on `ker f`, so it factors through a
morphism `L' → U(L)/J`, which extends to an algebra morphism `ψ : U(L') → U(L)/J`. Then
`ψ ∘ U(f)` is the quotient map (both agree on `ι(L)`), so `ker U(f) ⊆ J`. This is the standard
argument (see e.g. Bourbaki, *Lie groups and Lie algebras*, Ch. I, §2.3 (check)); it is written
out here in full.
-/

open Function

noncomputable section

namespace LieHom

variable {R L L' L'' : Type*} [CommRing R] [LieRing L] [LieAlgebra R L] [LieRing L']
  [LieAlgebra R L'] [LieRing L''] [LieAlgebra R L''] {f : L →ₗ⁅R⁆ L'} (hf : Surjective f)
  (g : L →ₗ⁅R⁆ L'') (hg : ∀ x, f x = 0 → g x = 0)

include hg in
lemma eq_of_map_eq {x y : L} (hxy : f x = f y) : g x = g y := by
  rw [← sub_eq_zero, ← map_sub]
  exact hg _ (by rw [map_sub, hxy, sub_self])

/-- A morphism of Lie algebras `g : L → L''` vanishing on the kernel of a surjective morphism
`f : L → L'` descends to a morphism `L' → L''`. -/
def descend : L' →ₗ⁅R⁆ L'' where
  toFun y := g (surjInv hf y)
  map_add' y z := by
    rw [← map_add]
    exact eq_of_map_eq g hg (by simp [surjInv_eq hf])
  map_smul' c y := by
    rw [RingHom.id_apply, ← map_smul]
    exact eq_of_map_eq g hg (by simp [surjInv_eq hf])
  map_lie' {y z} := by
    rw [← LieHom.map_lie]
    exact eq_of_map_eq g hg (by simp [surjInv_eq hf])

@[simp] lemma descend_apply (x : L) : descend hf g hg (f x) = g x :=
  eq_of_map_eq g hg (surjInv_eq hf (f x))

end LieHom

namespace UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

variable {R L L' : Type*} [CommRing R] [LieRing L] [LieAlgebra R L] [LieRing L']
  [LieAlgebra R L'] {f : L →ₗ⁅R⁆ L'}

/-- If `f : L → L'` is a surjective morphism of Lie algebras, then an element of `U(L)` in the
kernel of `U(f)` lies in the two-sided ideal generated by `ι(ker f)`. -/
theorem mem_span_of_map_eq_zero (hf : Surjective f) {u : UniversalEnvelopingAlgebra R L}
    (hu : map f u = 0) : u ∈ TwoSidedIdeal.span (ι R '' {x | f x = 0}) := by
  set J := TwoSidedIdeal.span (ι R '' {x | f x = 0})
  let q := RingCon.mkₐ R J.ringCon
  have hq : ∀ v, q v = 0 ↔ v ∈ J := fun v ↦ by
    rw [TwoSidedIdeal.mem_iff, ← RingCon.eq]
    rfl
  let g : L →ₗ⁅R⁆ J.ringCon.Quotient := (q : _ →ₗ⁅R⁆ _).comp (ι R)
  have hg : ∀ x, f x = 0 → g x = 0 := fun x hx ↦
    (hq _).mpr (TwoSidedIdeal.subset_span ⟨x, hx, rfl⟩)
  let ψ := lift R (LieHom.descend hf g hg)
  have : ψ.comp (map f) = q := hom_ext R (LieHom.ext fun x ↦ by
    change ψ (map f (ι R x)) = q (ι R x)
    rw [map_ι, lift_ι_apply, LieHom.descend_apply]
    rfl)
  rw [← hq, ← this, AlgHom.comp_apply, hu, map_zero]

/-- The kernel of `U(f) : U(L) → U(L')` for a surjective morphism of Lie algebras `f : L → L'` is
the two-sided ideal generated by `ι(ker f)`. -/
theorem ker_map_eq_span (hf : Surjective f) :
    TwoSidedIdeal.ker (map f) = TwoSidedIdeal.span (ι R '' {x | f x = 0}) := by
  refine le_antisymm (fun u hu ↦ mem_span_of_map_eq_zero hf ((TwoSidedIdeal.mem_ker _).mp hu)) ?_
  rw [TwoSidedIdeal.span_le]
  rintro _ ⟨x, hx, rfl⟩
  rw [SetLike.mem_coe, TwoSidedIdeal.mem_ker, map_ι, hx, map_zero]

end UniversalEnvelopingAlgebra
